### ISSUE TITLE
Filters in dashboard not update chars when $pollingInterval is null

### ISSUE THREAD

**Issue by danielreales7** [laravel-filament/filament#10026]
### Package

filament/filament

### Package Version

v3.1.8

### Laravel Version

v10.34.2

### PHP Version

8.1

### Problem description

If I use `protected static ?string $pollingInterval = 'keep-alive';` It is always sending requests to the server, which is wrong.
Widgets should update based on filters.

If I set `$pollingInterval = null` not update chars.

### Expected behavior

When the user filters is when the chars should be updated, not every X seconds.

### Steps to reproduce

composer install
php artisan migrate
php artisan db:seed

There is only one product in the Seeder, if you update the date to the current one when you run the seeder, a product should appear, if you select a different range it will not.

But you will see that it does not update because it is null.

### Reproduction repository

https://github.com/danielreales7/test-filament-currency

**Comment by danharrin** [comment]
Fixed by #10041.
