### ISSUE TITLE
 Target class [Filament\Http\Middleware\EncryptCookies] does not exist. 

### ISSUE THREAD

**Issue by Dontorpedo** [laravel-filament/filament#1005]
### Package

filament/filament

### Package Version

v2.7

### Laravel Version

v8.77.1

### PHP Version

php 8.1

### Bug description

After installation this error appears:

 Target class [Filament\Http\Middleware\EncryptCookies] does not exist.

**Comment by danharrin** [comment]
Hey, I can't reproduce this. Can you make sure that `config/filament.php` doesn't exist from a previous version please :)
