### ISSUE TITLE
Filament\Forms\Components\Select::isOptionDisabled(): Argument #2 ($label) must be of type string, null given, called in C:\htdocs\idara.23.11\vendor\filament\forms\src\Components\Select.php on line 184

### ISSUE THREAD

**Issue by AHMED-J-ALSAREM** [laravel-filament/filament#10086]
### Package

filament/filament

### Package Version

v3.0.0

### Laravel Version

v10

### Livewire Version

v3.0.0

### PHP Version

php.8.1

### Problem description

  SelectFilter::make('Domain')
                    ->relationship('tenant', 'domain')
                    ->searchable()
                    ->preload(),

Filament\Forms\Components\Select::isOptionDisabled(): Argument #2 ($label) must be of type string, null given, called in C:\htdocs\idara.23.11\vendor\filament\forms\src\Components\Select.php on line 184

### Expected behavior

  SelectFilter::make('Domain')
                    ->relationship('tenant', 'domain')
                    ->searchable()
                    ->preload(),

Filament\Forms\Components\Select::isOptionDisabled(): Argument #2 ($label) must be of type string, null given, called in C:\htdocs\idara.23.11\vendor\filament\forms\src\Components\Select.php on line 184

### Steps to reproduce

  SelectFilter::make('Domain')
                    ->relationship('tenant', 'domain')
                    ->searchable()
                    ->preload(),

Filament\Forms\Components\Select::isOptionDisabled(): Argument #2 ($label) must be of type string, null given, called in C:\htdocs\idara.23.11\vendor\filament\forms\src\Components\Select.php on line 184

### Reproduction repository

  SelectFilter::make('Domain')                     ->relationship('tenant', 'domain')                     ->searchable()                     ->preload(),

### Relevant log output

```shell
SelectFilter::make('Domain')
                    ->relationship('tenant', 'domain')
                    ->searchable()
                    ->preload(),

Filament\Forms\Components\Select::isOptionDisabled(): Argument #2 ($label) must be of type string, null given, called in C:\htdocs\idara.23.11\vendor\filament\forms\src\Components\Select.php on line 184
```

**Comment by danharrin** [comment]
No reproduction repository, it needs to be a GitHub repository containing an app.

**Comment by danharrin** [comment]
Check all other issues for reproduction repository examples

**Comment by AHMED-J-ALSAREM** [comment]
This is the solution to the problem 

 SelectFilter::make('tenant_id')
                ->label('Domain')
                ->options(Tenant::whereNotNull('domain')->pluck('domain', 'id'))
                ->searchable()
                ->preload(),

**Comment by CatShredengera** [comment]
> This is the solution to the problem
> 
> SelectFilter::make('tenant_id') ->label('Domain') ->options(Tenant::whereNotNull('domain')->pluck('domain', 'id')) ->searchable() ->preload(),

What if I use relationships? This option doesn't solve my problem

**Comment by PrasadChinwal** [comment]
Try using `->getOptionLabelFromRecordUsing()` method
```php
Forms\Components\Select::make('person_id')
                ->relationship(
                    'student',
                    modifyQueryUsing: fn (Builder $query) => $query->where('is_student', true)
                )
                ->getOptionLabelFromRecordUsing(fn (Model $record) => "{$record->full_name}")
                ->preload()
                ->searchable()
                ->live()
                ->required(),
```

**Comment by lukasinko** [comment]
I've hit the same issue. The solution from @PrasadChinwal works for me, but it looks to me more like workaround. I could imagine the option label is fetched from the edited $record automatically.

**Comment by PrasadChinwal** [comment]
@lukasinko Actually this is well documented. [https://filamentphp.com/docs/3.x/forms/fields/select#customizing-the-relationship-option-labels](https://filamentphp.com/docs/3.x/forms/fields/select#customizing-the-relationship-option-labels)

I believe under the hood the model gets hydrated hence you have access to the attribute. (Not sure though just my understanding)

**Comment by muhsinazmal9** [comment]
> ### Package
> filament/filament
> 
> ### Package Version
> v3.0.0
> 
> ### Laravel Version
> v10
> 
> ### Livewire Version
> v3.0.0
> 
> ### PHP Version
> php.8.1
> 
> ### Problem description
> SelectFilter::make('Domain') ->relationship('tenant', 'domain') ->searchable() ->preload(),
> 
> Filament\Forms\Components\Select::isOptionDisabled(): Argument #2 ($label) must be of type string, null given, called in C:\htdocs\idara.23.11\vendor\filament\forms\src\Components\Select.php on line 184
> 
> ### Expected behavior
> SelectFilter::make('Domain') ->relationship('tenant', 'domain') ->searchable() ->preload(),
> 
> Filament\Forms\Components\Select::isOptionDisabled(): Argument #2 ($label) must be of type string, null given, called in C:\htdocs\idara.23.11\vendor\filament\forms\src\Components\Select.php on line 184
> 
> ### Steps to reproduce
> SelectFilter::make('Domain') ->relationship('tenant', 'domain') ->searchable() ->preload(),
> 
> Filament\Forms\Components\Select::isOptionDisabled(): Argument #2 ($label) must be of type string, null given, called in C:\htdocs\idara.23.11\vendor\filament\forms\src\Components\Select.php on line 184
> 
> ### Reproduction repository
> SelectFilter::make('Domain') ->relationship('tenant', 'domain') ->searchable() ->preload(),
> 
> ### Relevant log output
> ```shell
> SelectFilter::make('Domain')
>                     ->relationship('tenant', 'domain')
>                     ->searchable()
>                     ->preload(),
> 
> Filament\Forms\Components\Select::isOptionDisabled(): Argument #2 ($label) must be of type string, null given, called in C:\htdocs\idara.23.11\vendor\filament\forms\src\Components\Select.php on line 184
> ```

Your Solution:
```shell
SelectFilter::make('Domain')
    ->relationship('tenant', 'domain')
    ->getOptionLabelFromRecordUsing(fn (Tenant $record) => "{$record->domain}")
    ->searchable()
    ->preload(),
```

EnjoY!

**Comment by DarkcoderSe** [comment]
> This is the solution to the problem
> 
> SelectFilter::make('tenant_id') ->label('Domain') ->options(Tenant::whereNotNull('domain')->pluck('domain', 'id')) ->searchable() ->preload(),

Instead of doing this. Use relationship(). This error generally occurs when your relationship returns null instead of the selected field in a string. so using `modifyQueryUsing: fn (Builder $query) => $query->where('is_student', true)` is suitable option here.
