### ISSUE TITLE
Filament\Forms\Components\Select::isOptionDisabled(): Argument #2 ($label) must be of type string, null given, called in C:\htdocs\idara.23.11\vendor\filament\forms\src\Components\Select.php on line 184

### ISSUE THREAD

**Issue by AHMED-J-ALSAREM** [laravel-filament/filament#10085]
### Package

filament/filament

### Package Version

v3.0.0

### Laravel Version

v10

### Livewire Version

v3.0.0

### PHP Version

php.8.1

### Problem description

  SelectFilter::make('Domain')
                    ->relationship('tenant', 'domain')
                    ->searchable()
                    ->preload(),

### Expected behavior

  SelectFilter::make('Domain')
                    ->relationship('tenant', 'domain')
                    ->searchable()
                    ->preload(),

### Steps to reproduce

  SelectFilter::make('Domain')
                    ->relationship('tenant', 'domain')
                    ->searchable()
                    ->preload(),

### Reproduction repository

  SelectFilter::make('Domain')                     ->relationship('tenant', 'domain')                     ->searchable()                     ->preload(),

### Relevant log output

```shell
SelectFilter::make('Domain')
                    ->relationship('tenant', 'domain')
                    ->searchable()
                    ->preload(),
```

**Comment by damms005** [comment]
If you landed here and wished this issue were not closed, and your `Select` component is displaying options from a related model, then ensure no option has a `null` label. The `titleAttribute` attribute hates it, as shown below:

```php
    Select::make('author_id')
        ->relationship(name: 'author', titleAttribute: 'full_name')
```

In the above, if there is an `author` without `full_name` value (i.e. `null`), you may get wacked by the OP's error.

**Comment by obeidareda37** [comment]
How to deal with potentially nullable columns in the above case?
@damms005 
@danharrin

**Comment by damms005** [comment]
@obeidareda37 honestly I think the best thing to do in this case is to ensure to use an attribute that is not nullable.

**Comment by momostafa** [comment]
> How to deal with potentially nullable columns in the above case? @damms005 @danharrin

Use query builder or DB::raw the key is Using "whereNotNull" 
example
```php
                        Forms\Components\Select::make('contact_id')
                        ->label('Single Contacts')
                        ->multiple()
                        ->visible(fn (Get $get) => $get('sending_mode') === 'single')
                        ->required(fn (Get $get) => $get('sending_mode') === 'single')
                        ->getSearchResultsUsing( fn (string $search): array => Contacts::query()
                            ->select([
                          DB::raw("CONCAT(contact_fname, ' ', contact_lname, ' - ', full_number) as fullname"),
                          'id',
                        ])->where('user_id', Auth::user()->id)
                        ->where('contact_fname', 'like', "%{$search}%")
                        ->orWhere('contact_lname', 'like', "%{$search}%")
                        ->orWhere('full_number', 'like', "%{$search}%")
                        ->limit(20)->pluck('fullname', 'id')
                        ->whereNotNull()
                        ->toArray())
                        ->getOptionLabelsUsing(fn (array $values): array => Contacts::whereIn('id', $values)->pluck('full_number', 'id')->toArray())
                        ->searchable(['contact_fname', 'contact_lname','full_number'])
                        ->searchPrompt('Search by name or Mobile Number'),
```

**Comment by maukoese** [comment]
> How to deal with potentially nullable columns in the above case? @damms005 @danharrin

Thank you so much. I'd have wasted hours if I hadn't seen your comment

**Comment by damms005** [comment]
Glad you found that helpful, @maukoese 

By the way, I checked your GitHub profile and noticed you work with a number of databases that are supported by [DevDb](https://marketplace.visualstudio.com/items?itemName=damms005.devdb).

I'll appreciate it if you can checkout DevDb and give me your honest opinion! You can hmu on [X](https://x.com/_damms005).

**Comment by nextcorpltd** [comment]
Utilize whereNotNull() nos selects
