### ISSUE TITLE
The "--pm" option does not exist.

### ISSUE THREAD

**Issue by senter-logistics** [laravel-filament/filament#10097]
### Package

filament/filament

### Package Version

v3.0-stable

### Laravel Version

v10.0

### PHP Version

PHP 8.3.0

### Problem description

I'm using "filament/filament": "3.0-stable", but when i use the option --pm 
`php artisan make:filament-theme --pm=yarn`
the output is  The "--pm" option does not exist. 

### Expected behavior

--pm option to work.

### Steps to reproduce

On a new project run 
php artisan make:filament-theme --pm=yarn

### Reproduction repository

https://github.com/senter-logistics/senter-website.git

**Comment by danharrin** [comment]
No reproduction repo
