### ISSUE TITLE
Create another action stopped working since v3.0.102

### ISSUE THREAD

**Issue by lamberttraccard** [laravel-filament/filament#10094]
### Package

filament/filament

### Package Version

v3.0.102

### Laravel Version

v10.34.2

### Livewire Version

v3.0.8

### PHP Version

PHP 8.2.0

### Problem description

The "create another" action is no longer working. The modal closes as if you had clicked on the create button. The $arguments in the action closure are always empty.

### Expected behavior

Clicking on the "Create Another" button should not close the modal.

### Steps to reproduce

<img width="1466" alt="image" src="https://github.com/filamentphp/filament/assets/4272598/da87362c-c751-429c-a87f-32dc9e6f6e83">

<img width="1170" alt="image" src="https://github.com/filamentphp/filament/assets/4272598/10828ef5-1d56-47c2-ac2e-777b3a01c1da">

### Reproduction repository

https://github.com/lamberttraccard/filament-issue

**Comment by lamberttraccard** [comment]
It also impacts all actions that use $arguments. See https://filamentphp.com/docs/3.x/actions/modals#adding-an-extra-modal-action-button-to-the-footer.

**Comment by tonypartridge** [comment]
V3.0.102 causes this. Debugging which PR causes it.

**Comment by danharrin** [comment]
should be fixed

**Comment by noel-lang** [comment]
I also came across this and after the latest update, it's working again. Thanks to everyone involved for such a quick fix! Much appreciated. ❤️

**Comment by christmex** [comment]
hi sorry, so how can i  "Reset the form and don't close the modal" inside the

```php
if ($arguments['another'] ?? false) {
}
```
kinda confuse thx
