### ISSUE TITLE
Custom table indicator

### ISSUE THREAD

**Issue by JoashVisione** [laravel-filament/filament#10104]
### Package

filament/filament

### Package Version

v3.0.0

### Laravel Version

v10.0.0

### Livewire Version

v3.0.0

### PHP Version

PHP 8.2.0

### Problem description

Using the Indicator as described in the document is not working. There is actually no class named Indicator

### Expected behavior

To expected to show two custom indicators

### Steps to reproduce

Create a customer filter inside the table filters and paste in the code below:

use Filament\Forms\Components\DatePicker;
use Filament\Tables\Filters\Filter;
use Filament\Tables\Filters\Indicator;
 
Filter::make('created_at')
    ->form([
        DatePicker::make('from'),
        DatePicker::make('until'),
    ])
    // ...
    ->indicateUsing(function (array $data): array {
        $indicators = [];
 
        if ($data['from'] ?? null) {
            $indicators[] = Indicator::make('Created from ' . Carbon::parse($data['from'])->toFormattedDateString())
                ->removeField('from');
        }
 
        if ($data['until'] ?? null) {
            $indicators[] = Indicator::make('Created until ' . Carbon::parse($data['until'])->toFormattedDateString())
                ->removeField('until');
        }
 
        return $indicators;
    })

Even the editor shows a compiler error

### Reproduction repository

https://github.com/JoashVisione/filament-customer-indicators

**Comment by zepfietje** [comment]
Make sure to update Filament and create a real reproduction repository please.

**Comment by JoashVisione** [comment]
Thank you for reaching out.

How do I update filament and check the current version? I am still a
novice.
