### ISSUE TITLE
hiddenOn field breaks modal in which the field is hidden

### ISSUE THREAD

**Issue by mokhosh** [laravel-filament/filament#10114]
### Package

filament/filament

### Package Version

v3.1.12

### Laravel Version

v10.35.0

### Livewire Version

v3.2.6

### PHP Version

8.2.13

### Problem description

If you add `hiddenOn` on a tabs field inside a form that is inside a modal, after opening the modal inside which the tabs field is visible, the other modal inside which the tabs field is hidden breaks and you can only see the transparent backdrop.

### Expected behavior

Both modals should load just fine.

### Steps to reproduce

- add a tabs field with one tab and one field inside it to a resource form
- add `hiddenOn('edit')` to tabs
- remove `create` and `edit` pages so they open in modals
- click on create new model
- close the modal
- click on edit model to see the modal break

### Reproduction repository

https://github.com/mokhosh/filament-v3-bug-reproduction

**Comment by danharrin** [comment]
Fixed
