### ISSUE TITLE
Allow repeater afterStateHydrated $state to allow null values

### ISSUE THREAD

**Issue by kenjilabs** [laravel-filament/filament#1012]
### Package

filament/forms

### Package Version

v2.7.1

### Laravel Version

v8.77.1

### Livewire Version

v2.8.2

### PHP Version

PHP 8.1

### Bug description

When form values are saved to the database and later If I add a new repeater field to it. it's giving an error message 

![image](https://user-images.githubusercontent.com/2118549/147452034-2bc3a57f-5a2d-4da2-9953-f9f359238f0d.png)

![image](https://user-images.githubusercontent.com/2118549/147452048-399102f2-2e40-4c13-ab2a-acdef427bc3d.png)

if i go to vendor\filament\forms\src\Components\Repeater.php file and edit 

![image](https://user-images.githubusercontent.com/2118549/147451822-d8943db9-1af0-4115-b2c5-94b9f07364a9.png)

and add replace `array $state` to `null | array $state` the error is gone

**Comment by danharrin** [comment]
Fixed by #1015 :)
