### ISSUE TITLE
`->expandableLimitedList()` seems not working as expected for InfoList

### ISSUE THREAD

**Issue by itskawsar** [laravel-filament/filament#10147]
### Package

filament/filament

### Package Version

^3.0-stable

### Laravel Version

^10.10

### Livewire Version

v3.2.6

### PHP Version

8.2.8

### Problem description

I have 9 items in my list, I wanted to show only 3 and hide 6 items. But it shows 4 instead of 3 and hides 5 items instead of 6. Also, the text is showing Show 6 more or Show 6 less (which is correct).

Here is my code:

```php
TextEntry::make('assets.asset_name')
        ->listWithLineBreaks()
        ->limitList(3)
        ->expandableLimitedList(),
```

![image](https://github.com/filamentphp/filament/assets/1224493/3ab32d0e-a972-4a03-9e15-a2e0134c8474)
_When expected items are hidden_

![image](https://github.com/filamentphp/filament/assets/1224493/8162cadc-27bb-49de-adc7-1a2af1049f5e)
_When expected items are shown_

### Expected behavior

Should show 3 items out of 9 and hide 6 items.

### Steps to reproduce

1. run `php artisan migrate:fresh --seed`
2. Login to admin
3. go to **Users** from sidebar navigation
4. click on a single user to see the view
5. you will see a text-entry called **Assets**

### Reproduction repository

https://github.com/itskawsar/f3-reproduction

**Comment by danharrin** [comment]
Should be fixed by #10155.
