### ISSUE TITLE
Active filters indicator not showing when using QueryBuilder

### ISSUE THREAD

**Issue by michele-grifa** [laravel-filament/filament#10157]
### Package

filament/filament

### Package Version

v3.1.14

### Laravel Version

v10.35.0

### PHP Version

8.1.0

### Problem description

If I use a QueryBuilder on a table, the active filters indicators are not showed.

### Expected behavior

Using the QueryBuilder show the active filters indicator

### Steps to reproduce

- Create a Table
- Use the QueryBuilder instead of a Filter
- Add a rule

### Reproduction repository

https://github.com/michele-grifa/demo-constraint-bug

**Comment by danharrin** [comment]
I've decided against using active indicators, because its essentially just duplicating the information that is already in the header of each repeater item, and also because we wouldnt be able to easily support OR groups

**Comment by danharrin** [comment]
That being said, you can implement your own `indicateUsing()` on the filter if you really want to

**Comment by cawecoy** [comment]
Hi @danharrin

I use filters in Modal, so active filters indicators above the table are not duplicating any information in my case. I need them and would appreciate if they are shown automatically by deafult and I don't have to create `indicateUsing()` for every table I have. 

Can't we have a global configuration to show filters indicator by default in `AppServiceProvider` `boot()` method?

**Comment by ZacharyDuBois** [comment]
@danharrin Not that this is very elegant, but for a flat query (no or statements), you could itemize the indicator (like how filters work). When an 'OR' is present, you could just state something like "Advanced query".

The functionality right now can get confusing if using the `QueryBuilder` with other normal filters. The normal filters will show in the active bar but not the advanced query.

An even easier way to do this would be just always display "Advanced query" when the QueryBuilder is in use.
