### ISSUE TITLE
Test helpers sensitive to Builder json order

### ISSUE THREAD

**Issue by fritz-c** [laravel-filament/filament#10165]
### Package

filament/filament

### Package Version

v3.1.15

### Laravel Version

v10.35.0

### Livewire Version

v3.2.6

### PHP Version

8.2.13

### Problem description

When testing resources that use the Builder component, the `fillForm` method can throw an exception (`Undefined array key "type"`) if the `data` comes before the `type` key in the json array.

### Expected behavior

`fillForm` should work regardless of the order of the keys in the builder items.

### Steps to reproduce

The steps are in the reproduction repository readme along with the setup instructions.

### Reproduction repository

https://github.com/fritz-c/filament-builder-test-bug

**Comment by danharrin** [comment]
Should be fixed in the next release
