### ISSUE TITLE
`afterStateUpdated` unable to use $set to update DateTimePicker field, DateTimePicker is set to `null`

### ISSUE THREAD

**Issue by cao-minh-duc** [laravel-filament/filament#10171]
### Package

filament/filament

### Package Version

v3.0.0

### Laravel Version

v10.0.0

### Livewire Version

v3.0.0

### PHP Version

PHP 8.3.0

### Problem description

`afterStateUpdated` unable to use $set to update DateTimePicker field, DateTimePicker is set to `null`

### Expected behavior

Able to use $set to update DateTimePicker field

### Steps to reproduce

SpatieMediaLibraryFileUpload::make('photos')
                    ->image()
                    ->multiple()
                    ->reorderable()
                    ->reactive()
                    ->afterStateUpdated(function (Set $set, $state) {
                       $set('paid_at', now()->addDay())
                    }),
                Forms\Components\DateTimePicker::make('paid_at')
                    ->default(now())
                    ->required(),

### Reproduction repository

https://github.com/cao-minh-duc/expense-tracker

**Comment by danharrin** [comment]
Try `now()->addDay()->toDateTimeString()`
