### ISSUE TITLE
I have 3 problem when i upgrade 

### ISSUE THREAD

**Issue by febelery** [laravel-filament/filament#1019]
### Package

filament/forms

### Package Version

v2.7.1

### Laravel Version

v8.77

### PHP Version

PHP 8.1

### Bug description

1. `public static function form(Form $form): Form`
```php
Forms\Components\HasManyRepeater::make('categories')
                    ->schema([
                            Forms\Components\TextInput::make('title')
                    ]),
```
or 
```php
Forms\Components\Repeater::make('categories')
                    ->schema([
                            Forms\Components\TextInput::make('title')
                    ]),

```
Default render one, but shouldn't none of them be rendered by default? One should be added only by clicking the Add button.

2. `FileUpload` upload image work fine, sometimes the image is not displayed but can be submitted normally
3. `App\Forms\Components\SomeForm` has a `fileupload` filed, but upload field is `array`, I have to expand the array manually , It was normal before
```php
Forms\Components\FileUpload::make('image')->image()

/////////////////

    public function saveRelationships(): void
    {
        $state = $this->getState();
        $model = $this->getModel();
        $relationship = $model->{$this->getRelationship()}();
        $state['image'] = is_array($state['image']) ? Arr::first($state['image']) : $state['image']; // there

        if ($setting = $relationship->first()) {
            $setting->update($state);
        } else {
            $relationship->updateOrCreate($state);
        }

        $model->touch();
    }
```
submit like this
```php
['image' => ['uuid-uuid-uuid-uuid' => 'xxxxxxxx.png']]
```
but i need 
```php
['image' =>  'xxxxxxxx.png']
```

**Comment by danharrin** [comment]
Hey, can you make sure that your assets are also on the latest version (run Laravel Mix to compile them & `php artisan view:clear`)?

**Comment by febelery** [comment]
I deleted the project and re-downloaded it from git and it still does it

**Comment by danharrin** [comment]
Addressing your other points:

We've made it default behaviour to have 1 item filled by default on the repeater. It's not great UX to have to click a button to add one manually each time. To disable this, you can pass `defaultItems(0)` to the repeater. Obviously, the default item is not created when you have existing data, only when you `$form->fill()`.

With regards to the file upload change - we recently added better support for multi-uploads, and this was one of the changes we made to ensure that the code was clean. Instead of having to check if the upload is multiple every time & changing the state from array to string, we always have the state as an array and then dehydrate it as a string if there is only 1 file uploaded. We don't guarantee that there won't be breaking changes when you override parts of our internal form components, so just be careful in the future to check the changelog of the project before upgrading to make sure you're not overriding anything important.

**Comment by febelery** [comment]
@danharrin but set `defaultItems(0)` have two items?

**Comment by danharrin** [comment]
> @danharrin but set `defaultItems(0)` have two items?

Oh haha, I didn't know that was a bug. I fixed it in #1025.

**Comment by febelery** [comment]
![2021122183644](https://user-images.githubusercontent.com/52574911/147463589-c278a8f7-791c-4fb6-afa4-58e1834266ba.png)

**Comment by danharrin** [comment]
Should be working now on the latest release?

**Comment by febelery** [comment]
> Should be working now on the latest release?

It's working

**Comment by febelery** [comment]
@danharrin 

With regard to file upload, when the title field is not empty, the picture will not be displayed. When the title field is empty, the picture will be displayed normally


https://user-images.githubusercontent.com/52574911/147521856-17d6510c-3b36-4c6c-a336-bf6c5d282779.mp4

**Comment by danharrin** [comment]
Can I have some code to replicate that problem please?

**Comment by febelery** [comment]
```php

Forms\Components\Group::make()->schema([
                Forms\Components\Card::make()->schema([
                    Forms\Components\TextInput::make('title')
                        ->required()
                    Forms\Components\DateTimePicker::make('start_at')
                        ->displayFormat('Y-m-d H:i:s')
                        ->default(now())
                        ->required(),
                    Forms\Components\DateTimePicker::make('end_at')
                        ->displayFormat('Y-m-d H:i:s')
                        ->default(now()->addDays(2))
                        ->required(),
                    Forms\Components\FileUpload::make('cover')
                        ->required()
                        ->image(),
```

**Comment by danharrin** [comment]
This should be fixed in the latest version - let me know if not.

**Comment by febelery** [comment]
> This should be fixed in the latest version - let me know if not.

it's working
