### ISSUE TITLE
Unable to change $state using `->beforeStateUpdated()` for `Filament\Tables\Columns\ToggleColumn`

### ISSUE THREAD

**Issue by itskawsar** [laravel-filament/filament#10194]
### Package

filament/filament

### Package Version

^3.0-stable

### Laravel Version

^10.10

### Livewire Version

v3.2.6

### PHP Version

8.2.8

### Problem description

I'm trying to set a different value to the $state other than `true`/`false` or `0`/`1` when toggle trying to save. I followed the documentation and find out the toggle is changing the $state but still storing `true`/`false` or `0`/`1` to the database.

I tried the following code:

```php
Tables\Columns\ToggleColumn::make('email_verified_at')
        ->beforeStateUpdated(function ($record, $state) {
                // Runs before the state is saved to the database.
                // return $state?date('Y-m-d H:i:s'):'0000-00-00 00:00:00';
                return $state?date('Y-m-d H:i:s'):null;
        })
        ->label('Verified'),

// testing... you can ignore this part
Tables\Columns\ToggleColumn::make('is_admin')
        ->label('Admin')
        ->beforeStateUpdated(function ($record, $state) {
                return $state?5:6;
        }),
```

![image](https://github.com/filamentphp/filament/assets/1224493/3e1f9b83-1f7f-4947-98d2-71049bd7e8e5)
I got the following error.

### Expected behavior

I like to change the $state to **current date** if the toggle is `true`, and set the $state to **NULL** when the toggle is `false`. 

### Steps to reproduce

1. run `php artisan migrate:fresh --seed`
2. Login to admin
3. go to Users from sidebar navigation
5. you will see toggle columns for **Verified** and **Admin**

### Reproduction repository

https://github.com/itskawsar/f3-reproduction

**Comment by danharrin** [comment]
`beforeStateUpdated()` cannot modify the state. You want `updateStateUsing()`

```
->updateStateUsing(function ($record, $state) {
                return $record->update(['email_verified_at' => $state?date('Y-m-d H:i:s'):null]);
        })
```

**Comment by Yscream** [comment]
hi! what's solution for filament 2.x version?
