### ISSUE TITLE
$translatableContentDriver: Call to a member function updateRecord() on null

### ISSUE THREAD

**Issue by aeq-dev** [laravel-filament/filament#10200]
### Package

filament/tables

### Package Version

3

### Laravel Version

10

### Livewire Version

3.1

### PHP Version

8.2

### Problem description

Getting this error : 
`Call to a member function updateRecord() on null`
when updating to the last version
https://github.com/filamentphp/filament/commit/1911534319148f4f78f444785c5482217a79da16
### Expected behavior

Save RealtionManager having translation trait

### Steps to reproduce

1. Setup RealtionManager with translation trait
2. Save a record
3. Get error

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by danharrin** [comment]
Fixed in next version
