### ISSUE TITLE
(SPA) Navigating outside filament panel page and then get back to panel using back button will break the page.

### ISSUE THREAD

**Issue by rahmanramsi** [laravel-filament/filament#10205]
### Package

filament/filament

### Package Version

v3.1.17

### Laravel Version

v10.35.0

### Livewire Version

v3.2.3

### PHP Version

PHP 8.1.24

### Problem description

When SPA mode active.

While navigating to page that is not in filament panel page context, and then get back to filament panel, the page will break, as you can see in the gif below.

![CleanShot 2023-12-09 at 15 38 36](https://github.com/filamentphp/filament/assets/48276043/4e11818d-27c1-4d43-ad51-ff9182bb069b)

This behavior only happen when navigating in the same domain, but outside of filament panel page

### Expected behavior

Page work normally

### Steps to reproduce

- Open panel page
- Navigate to page that is outside of panel page (in this context is laravel homepage)
- then navigate back using back button
- filament panel page will break

### Reproduction repository

https://github.com/rahmanramsi/filament-backnavigatebug

**Comment by danharrin** [comment]
This seems to be a Livewire bug in wire:navigate. I do not have time to submit a failing test PR to Livewire to narrow this down, but I encourage you to. As such, I do not think it's worth having an issue open on this repository, when there's not any code changes we can make to Filament.
