### ISSUE TITLE
TextInput with numeric modifier doesn't set minValue and maxValue attributes on Wizard Steps

### ISSUE THREAD

**Issue by lartisan** [laravel-filament/filament#10230]
### Package

filament/filament

### Package Version

v3.1.18

### Laravel Version

v10.35

### PHP Version

PHP 8.2.13

### Problem description

I have defined a `TextInput` on a wizard step. I have set the `numeric` field modifier and also added `minValue(1)` and `maxValue(2)`. I could modify the value under the min one and also above the max one.

### Expected behavior

TextInput with numeric modifier should set minValue and maxValue attributes on Wizard Steps

### Steps to reproduce

- Open adminpanel page
- Navigate to the Users resource
- Press Create to create a new User
- Increase or decrease the value for age

### Reproduction repository

https://github.com/lartisan/numeric-min-max-values

**Comment by danharrin** [comment]
Yes this is currently deliberate. If we do not remove this frontend validation, there are console errors as the browser cannot validate hidden fields (in this case from other wizard hidden steps). Same for collapsible sections and tabs

**Comment by lartisan** [comment]
Ok, thanks for getting back .. so I guess validation is my only choise :)

**Comment by markosole** [comment]
Exact same problem here and with same versions. Was trying to figure out why, I've noticed some other things but will note them down and report in new issue report.

**Comment by danharrin** [comment]
@markosole please dont open a new issue, please read my response above

**Comment by markosole** [comment]
Thank you @danharrin , small workarounds here and there. One of the things I would like to mention is `->autocapitalize('words')`  feature which does not work, does not matter if form is in Wizard or not. 
The way how  managed it is by using tailwind css class `capitalize`  on TextInput field.

```php
  ->extraInputAttributes(['class' => 'capitalize'])
```

**Comment by danharrin** [comment]
The autocapitalise feature applies to mobile devices with touch keyboards, I think? Verify your browser behaviour here - https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize#result
