### ISSUE TITLE
File Upload Bug When Display And View Page

### ISSUE THREAD

**Issue by DeviJv** [laravel-filament/filament#10252]
### Package

filament/tables

### Package Version

v3

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

8.2

### Problem description

<img width="953" alt="image" src="https://github.com/filamentphp/filament/assets/26791396/9ab709fa-c20a-4c47-9f94-574809718122">
after uploading then error 
but image success uploaded to dir

### Expected behavior

no

### Steps to reproduce

not displayed on list and edit page

### Reproduction repository

https://github.com/DeviJv/error-select-form-loop-json-array-filament

**Comment by danharrin** [comment]
Not a good enough reproduction. It is not minimal. We do not even have all the files required to run it. Please open a discussion instead, it's probably not a bug.
