### ISSUE TITLE
Styling for suffix and affix actions

### ISSUE THREAD

**Issue by titantwentyone** [laravel-filament/filament#10394]
### Package

filament/filament

### Package Version

3.1.21

### Laravel Version

10.10

### Livewire Version

3.3

### PHP Version

8.2

### Problem description

When displaying affix or suffix actions for a field, the stye for the button is just rendered as a button.

### Expected behavior

This isn't a bug per se - more of a request for styling - but it would be nice if these were flush with the field and rounded off at the appropriate sides

### Steps to reproduce

The following code:

```
TextInput::make('quantity')
    ->hiddenLabel()
    ->numeric()
    ->required()
    ->minValue(1)
    ->step(1)
    ->default(1)
    ->suffixAction(
        Action::make('AddToCart')
            ->icon('heroicon-m-pencil-square')
            ->button()
            ->size(ActionSize::Large)
            ->action(function() {
                $this->addToCart();
            })
    ),
```
Renders the following:

![image](https://github.com/filamentphp/filament/assets/1583366/e1ab45bf-d786-4410-805c-bdbe9a68be13)

Ideally this would render as:

![image](https://github.com/filamentphp/filament/assets/1583366/b2e6daef-83fa-4e90-a44c-834ed2b7a918)

Just head to site homepage in repo - Panels not needed.

### Reproduction repository

https://github.com/titantwentyone/suffix-affix-actions

**Comment by danharrin** [comment]
I don't know how well this would fit in our design system, potentially you could use `link()` instead of `button()`?

**Comment by zepfietje** [comment]
I agree with @danharrin's comment, and was about to suggest using `link()` as well.

**Comment by zepfietje** [comment]
I'm going to close this issue, but feel free to attempt a pull request that takes into account all edge cases. 🙂
