### ISSUE TITLE
Fialment validation does not work

### ISSUE THREAD

**Issue by Chrynn** [laravel-filament/filament#10411]
### Package

filament/filament

### Package Version

v3.0

### Laravel Version

v10.10

### Livewire Version

v3.3

### PHP Version

v8.1

### Problem description

Filament validation does not work even with installed livewire.

### Expected behavior

Filament should validate form by selected rules on input (required on select and alpha on input) and show errors under the inputs on frontend.

### Steps to reproduce

- fork project, checkout branch
- start project by README.md
- login to the app with credentials in `2023_11_27_121317_default_user.php`
- fill form on page 'Test' and check the output values (it should not show them with incorrect data on input)

### Reproduction repository

https://github.com/Chrynn/test-project/pull/4

### Others

Im I missing something or its bug? Please help with right validation setup.

**Comment by danharrin** [comment]
The docs say `$this->form->getState()` should be used to validate and return form data. https://filamentphp.com/docs/3.x/forms/adding-a-form-to-a-livewire-component
