### ISSUE TITLE
Call to a member function associate() on null

### ISSUE THREAD

**Issue by DeviJv** [laravel-filament/filament#10424]
### Package

filament/filament

### Package Version

3

### Laravel Version

10

### Livewire Version

3

### PHP Version

8.2

### Problem description

hallo 

i have multiple repeater form in wizard then got this error

<img width="896" alt="image" src="https://github.com/filamentphp/filament/assets/26791396/86aca068-f4c1-4cd1-839c-29641c0bb8b6">

here my relation

on Penjualan model 
<img width="296" alt="image" src="https://github.com/filamentphp/filament/assets/26791396/c0e16bf5-2e11-464d-bfd7-bd7cdb8a4dda">

repeater items() -> no error and problem here
<img width="362" alt="image" src="https://github.com/filamentphp/filament/assets/26791396/eb35b6dc-eb25-4441-9d20-23803c48d4e7">

repeater payments()

<img width="630" alt="image" src="https://github.com/filamentphp/filament/assets/26791396/a00e1d78-7fc1-45e7-a7a7-e48029c7ff39">

### Expected behavior

the items repeater on the second step  and payment on latest step (wizard)

help to fix this dev 

thx u

### Steps to reproduce

step 1 and 2 it totally fine until i added payment repeater on step tree 

### Reproduction repository

https://github.com/DeviJv/error-multi-repeater-form-filament

**Comment by danharrin** [comment]
Please read the instructions on how to create a reproduction repository.

**Comment by Wan237** [comment]
Have you solved this?
