### ISSUE TITLE
Previous step in the Wizard is empty

### ISSUE THREAD

**Issue by KiaBoluki** [laravel-filament/filament#10429]
### Package

filament/filament

### Package Version

v3.1.26

### Laravel Version

v10.10

### Livewire Version

v3.3

### PHP Version

PHP v8.1

### Problem description

When I click on the `Back` button in the `Wizard` it shows an empty `Step` 
I have tested it in `Chrome` , `Edge` , `FireFox`
I have cleaned browser cache. 
run `php artisan optimize:clean`
run `composer clear-cache`
run `composer dump-autoload` 

the issue persists. 

https://github.com/filamentphp/filament/assets/11926947/6fc57090-7555-429a-8027-286b82d86e9b

 

### Expected behavior

I expect to see the previous step form

### Steps to reproduce

1. install new laravel
2. install livewire 3 
3. install filament 3 panel
4. create filament resource 
5. create wizard in resource 
6. create steps 
7. add some inputs in the steps
8. try to use Back and Next buttons

### Reproduction repository

https://github.com/KiaBoluki/filament-wizard-bug

**Comment by conveydk** [comment]
I can confirm this on 3.1.25.

**Comment by miguilimzero** [comment]
I can also confirm on 3.1.27.

**Comment by miguilimzero** [comment]
Maybe related to https://github.com/filamentphp/filament/pull/10261?

**Comment by sh4msi** [comment]
I am also involved with this issue in version 3.1.27.

**Comment by danharrin** [comment]
Should be fixed by #10474.

**Comment by JPdesconectado** [comment]
I'm still facing this issue in production. I'm on v3.1.35.

**Comment by michabbb** [comment]
can someone confirm if this is fixed now ?

**Comment by sh4msi** [comment]
> can someone confirm if this is fixed now ?

It has been fixed
