### ISSUE TITLE
Custom Billing Provider: Route not found error.

### ISSUE THREAD

**Issue by TheFrankman** [laravel-filament/filament#10438]
### Package

filament/filament

### Package Version

v3.0

### Laravel Version

v10.10

### Livewire Version

v3

### PHP Version

8.3

### Problem description

When defining a custom billing provider, i get the error `Route [the.route.name] not defined.` Despite the route being available when running `php artisan route:list`

The route name is provided via the `getRouteAction()` method on the billing provider.

### Expected behavior

Should load the view.

## Setup

- Start with a blank filament php project.
- Add multi-tenancy
- Install filament spark (otherwise you can't implement `Filament\Billing\Providers\Contracts\Provider`)
- Create a middleware `php artisan make:middleware RedirectIfOrganisationNotSubscribed`
- Create a custom billing provider by adding the below code to app/Providers/CustomBillingProvider.php

```
<?php

namespace App\Providers;

use App\Http\Middleware\RedirectIfOrganisationNotSubscribed;
use Filament\Billing\Providers\Contracts\Provider;

class CustomBillingProvider implements Provider
{
    public function getRouteAction(): string
    {
        return route('filament.admin.pages.subscription-management');
    }

    public function getSubscribedMiddleware(): string
    {
        return RedirectIfOrganisationNotSubscribed::class;
    }
}
```

- Create a new filament page : `php artisan make:filament-page` don't select a resource. Call it SubscriptionManagement. You should now have a page that looks like this :

```
<?php

namespace App\Filament\Pages;

use Filament\Pages\Page;

class SubscriptionManagement extends Page
{
    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.pages.subscription-management';
}
```

- If you at this stage do a `php artisan:route-list | grep "subscription-management"` you will see your route

## Recreate the error
In your panel provider add the following : 

```
use App\Providers\CustomBillingProvider;

->requiresTenantSubscription()
->tenantBillingProvider(new CustomBillingProvider());
```
run `php artisan route:list` you will get the error : ` Route [filament.admin.pages.subscription-management] not defined.`

If you comment those two out and run `route:list` again, you will see the route there !

### Reproduction repository

https://github.com/TheFrankman/custom-billing-provider-issue

**Comment by danharrin** [comment]
1) You should not need to install Filament Spark, that interface is part of filament/filament
2) This is a `route action`. Imagine putting this into a `Route::get()`. `Route::get('/billing', route('filament.admin.pages.subscription-management'))` wouldnt work as it is run while routes are being registered.
3) Our docs have a good example: https://filamentphp.com/docs/3.x/panels/tenancy#writing-a-custom-billing-integration

```php
public function getRouteAction(): string
{
    return function (): RedirectResponse {
        return redirect()->route('filament.admin.pages.subscription-management');
    };
}
```
