### ISSUE TITLE
custom filter not work when qurey callback function first params not use specific key name

### ISSUE THREAD

**Issue by popdaul** [laravel-filament/filament#10454]
### Package

filament/filament

### Package Version

v3.1.27

### Laravel Version

v10.38.2

### Livewire Version

v3.0.0

### PHP Version

PHP 8.3.0

### Problem description

when I use `Filament\Tables\Filters\Filter::query()` function then set the callback function first param name is not `$query`, the query will not work 

### Expected behavior

expect the parameters can set with any name and query can work

### Steps to reproduce

1. use a table custom filter
2. the filter use query function
3. set first callback parameter name is not `$query`
4. reproduce~

### Reproduction repository

https://github.com/popdaul/filament-issue

**Comment by popdaul** [comment]
This is not a necessary issue. But the document doesn't say it's necessary to set `$query` parameter name.

Conside add `Note` or `Tips` to document, or compatible with any key name about callback parameter.

I have tried resolv this issue.

`src/Concerns/EvaluatesClosures.php`
```
    protected function resolveClosureDependencyForEvaluation(ReflectionParameter $parameter, array $namedInjections, array $typedInjections): mixed
    {
        $parameterName = $parameter->getName();

        if (array_key_exists($parameterName, $namedInjections)) {
            return value($namedInjections[$parameterName]);
        }
        ## is here
        if (isset($namedInjections['query'])
            && $parameter->getType()->getName() === \Illuminate\Database\Eloquent\Builder::class) {
            return value($namedInjections['query']);
        }
``` 

But it may have too much impact.

**Comment by danharrin** [comment]
This is the same for every parameter in Filament, they all have a strict naming convention. If you want to add a new feature (resolution based on Builder type), we'd love to see a PR, thanks!
