### ISSUE TITLE
Global Settings in Middelware not working correctly

### ISSUE THREAD

**Issue by sitenzo** [laravel-filament/filament#10459]
### Package

filament/filament

### Package Version

3.1.27

### Laravel Version

10.38.2

### PHP Version

8.1.6

### Problem description

In my project i use different locales, there are some static values in Filament that i want to set depending on the locale.
When i add them in *AppServiceProvider* all config work but not the static ones based on locale (users local is set in middleware).

When i only add the static values in a *Middleware* and no config in *AppServiceProvider* it works.
When i add other config for table in *AppServiceProvider* locale not working
When i add all config for table in *Middleware* locale not working and some other table settings not working like `->striped()` but the `->paginationPageOptions([25,50,100])` is working.

### Expected behavior

Setting Global settings in Middleware so it wil always loads the global settings.

### Steps to reproduce

Clone repo.

1) See `XFilamentPanelOptions` Middleware 
2) Serve the application 
3) checkout table (dates / striped)

### Reproduction repository

https://github.com/sitenzo/FilamentGlobalSettings

**Comment by danharrin** [comment]
The middleware needs to be persistent - https://livewire.laravel.com/docs/security#configuring-persistent-middleware

Will add to the docs

**Comment by danharrin** [comment]
You can add `isPersistent: true` to `middleware()` in the panel provider btw
