### ISSUE TITLE
Multi-tenancy breaks advanced custom navigation items

### ISSUE THREAD

**Issue by pixelastronauts** [laravel-filament/filament#10457]
### Package

filament/filament

### Package Version

v3.1.27

### Laravel Version

v10.38.2

### Livewire Version

v3.3.3

### PHP Version

PHP 8.3.0

### Problem description

When adding multi-tenancy to a new panel and then customizing the navigation through the ```->navigation``` function it breaks the multi-tenancy functionality.

You can't switch between teams & visiting the '/admin' route is giving a error:

```Missing required parameter for [Route: filament.admin.pages.dashboard] [URI: admin/team/{tenant}] [Missing parameter: tenant].```

It looks like it has something to do with the ```:href="filament()->getUrl($tenant)"``` inside the tenant-menu.blade.php file.

### Expected behavior

To have the navigation changed and the switching between tenants work.

### Steps to reproduce

Install new panel, add multi-tenancy and add some custom navigation through the ```->navigation``` function in the ```AdminPanelProvider.php```

### Reproduction repository

https://github.com/pixelastronauts/filament-tenancy-navigation-bug

**Comment by pixelastronauts** [comment]
Found the problem. It's not having the right 'Dashboard' route defined inside the navigation. 

Changing ```->url(fn (): string => Dashboard::getUrl())``` to ```->url(route('filament.admin.pages.dashboard', ['tenant' => Filament::getTenant()]))``` is fixing the problem. Despite that both return the same url.

Maybe it's a good idea to have something about this mentioned in the docs?

**Comment by danharrin** [comment]
`->url(Dashboard::getUrl())` also works

**Comment by danharrin** [comment]
Should have fixed the underlying issue

**Comment by pacoproc** [comment]
I am having a similar issue. I replaced the line :href="filament()->getUrl($tenant)"  for   :href="url(filament()->getPanel()->getPath() . '/team/' . $tenant->team_slug)"   on the tenant-menu.blade.php and it fixed my issue. Tenants are clickable again.
