### ISSUE TITLE
Error : Filament not Installed. When creating filament-user, even filament panels already installed

### ISSUE THREAD

**Issue by arsadii** [laravel-filament/filament#10487]
### Package

filament/filament

### Package Version

v3.1.28

### Laravel Version

v10.38.2

### Livewire Version

v3.3.3

### PHP Version

PHP 8.1.26

### Problem description

When I run `php artisan make:filament-user`, error **Filament not installed** : 
![image](https://github.com/filamentphp/filament/assets/67938386/03ded0cc-664b-4804-b870-0f3bba0d2dd4)

I've try to install the filament panels by running `php artisan filament:install --panels`
And It's successfully installed. I can go to my login page.

I also have clear config cache by running `php artisan config:clear` but still get the same error.

### Expected behavior

I can create filament user successfully

### Steps to reproduce

I don't really know why exactly this happen. I just get the error after fresh my DB, and when trying to create filament-user, and this error show up.
1. Clone this repo
2. Run `php artisan filament:install --panels` and use `dashboard` as a panel ID.

### Reproduction repository

https://github.com/arsadii/repro-perkara

**Comment by danharrin** [comment]
no `default()` panel, that is created when you install

**Comment by arsadii** [comment]
> no `default()` panel, that is created when you install

I'm sorry, my bad

**Comment by EntroSolutions** [comment]
I have the same problem after fresh installation @danharrin what exactly you mean with this short answer: no ->default() ?

**Comment by SlimDeluxe** [comment]
~@EntroSolutions it appears you have to add `->default()` in the generated service provider file. I suppose it should be set by default but it isn't. It should at least be documented.~
Edit: sorry, not true

**Comment by danharrin** [comment]
`filament:install --panels` generates a service provider containing the `default()` call

**Comment by SlimDeluxe** [comment]
@danharrin I've tested it again with a clean laravel project and it's true. I apologize 🫣

**Comment by NAPSTERSIHOTANG** [comment]
where should i put default() call

**Comment by ariiprs** [comment]
after run command "php artisan filament:install --panels" and show question "Whats the admin id?"
i type "admin"
and then check on bootstrap\providers.php, is the file Filament\AdminPanelProvider.php is registered or not. and also make sure when answer the question of "Whats the admin id?" just answer with string, not number. cause it will created as the first word of the file

**Comment by ubiratan-neto** [comment]
Instalei o filament: composer require filament/filament
Criei o Painel: php artisan filament:install --panels
Quando vou criar o usuário utilizando o comando: php artisan make:filament-user
Ele dava o erro: Filament has not been installed yet: php artisan filament:install --panels
Fui no app>Providers>Filament>AdminPanelProvider.php e utilizei o que vi aqui nas respostas default()
Agora quando vou cirar o usuário, consigo colocar o nome, o email, mas não aparece a questão da senha e dá o seguinte erro: 

 Illuminate\Database\QueryException 

  SQLSTATE[HY000] [2002] php_network_getaddresses: getaddrinfo for drivetel_mysql failed: Este anfitrio no  conhecido.  (Connection: mysql, SQL: select exists(select * from `users` where `email` = admin@drivetel.pt) as `exists`)

  at vendor\laravel\framework\src\Illuminate\Database\Connection.php:829
    825▕                     $this->getName(), $query, $this->prepareBindings($bindings), $e
    826▕                 );
    827▕             }
    828▕
  ➜ 829▕             throw new QueryException(
    830▕                 $this->getName(), $query, $this->prepareBindings($bindings), $e
    831▕             );
    832▕         }
    833▕     }

  1   vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:65
      PDOException::("PDO::__construct(): php_network_getaddresses: getaddrinfo for drivetel_mysql failed: Este anfitrio no  conhecido. ")

  2   vendor\laravel\framework\src\Illuminate\Database\Connectors\Connector.php:65
      PDO::__construct()

**Comment by monospacedigital** [comment]
Guys, i think the issue is you can't reuse a pre-existing username. So for example, if i have already have a username _admin_, and i try to create a username with admin, then it gets an error because that user already exists. It's probably trying to create a user with the name you specified. You should already be authenticated. Just try logging in with the admin email and password and you should already be able to log in.

**Comment by monospacedigital** [comment]
Maybe occurs because you already have the user set up. Try logging in with your user with the "admin" authentication.
