### ISSUE TITLE
after v3.1.23 Table content is overflowing

### ISSUE THREAD

**Issue by danieladarve** [laravel-filament/filament#10517]
### Package

filament/filament

### Package Version

v3.1.29

### Laravel Version

v10.38.1

### PHP Version

PHP 8.2.12

### Problem description

Tables overflow in screen
![Screenshot 2023-12-27 at 11 21 59 am](https://github.com/filamentphp/filament/assets/22025439/6b2b1b96-06de-4494-b397-ae5f91c2fd4e)

Due to this PR on v3.1.23 [https://github.com/filamentphp/filament/pull/10290](https://github.com/filamentphp/filament/pull/10290)

### Expected behavior

table should not overflow
![Screenshot 2023-12-27 at 1 00 04 pm](![Screenshot 2023-12-27 at 1 11 53 pm](https://github.com/filamentphp/filament/assets/22025439/aca3b4d8-f760-4165-b825-ce1023bae5a8))

### Steps to reproduce

upgrade any version above v3.1.23

### Reproduction repository

https://github.com/danieladarve/filament

**Comment by danharrin** [comment]
Closing this as the reproduction repository does not follow instructions

**Comment by danharrin** [comment]
Fixed by #10636.
