### ISSUE TITLE
Select allowhtml()

### ISSUE THREAD

**Issue by sitenzo** [laravel-filament/filament#10513]
### Package

filament/filament

### Package Version

3.1.28

### Laravel Version

10.38.2

### PHP Version

8.1.6

### Problem description

The allowHtml on a select is not working anymore, it always escapes the label now

```php
Select::make('technology')
    ->options([
        'tailwind' => '<span class="text-blue-500">Tailwind</span>',
        'alpine' => '<span class="text-green-500">Alpine</span>',
        'laravel' => '<span class="text-red-500">Laravel</span>',
        'livewire' => '<span class="text-pink-500">Livewire</span>',
    ])
    ->searchable()
    ->allowHtml()
```

[Allowing html in the option labels](https://filamentphp.com/docs/3.x/forms/fields/select#allowing-html-in-the-option-labels)

### Expected behavior

That the HTML label wil be rendered as HTML.

### Steps to reproduce

Add below code to a form.

```php
Select::make('technology')
    ->options([
        'tailwind' => '<span class="text-blue-500">Tailwind</span>',
        'alpine' => '<span class="text-green-500">Alpine</span>',
        'laravel' => '<span class="text-red-500">Laravel</span>',
        'livewire' => '<span class="text-pink-500">Livewire</span>',
    ])
    ->searchable()
    ->allowHtml()
```

run `npm run build`

Checkout the options from select.

### Reproduction repository

https://github.com/sitenzo/FilamentGlobalSettings/tree/testing-allowhtml-select

**Comment by danharrin** [comment]
Did this break in a particular version?

**Comment by sitenzo** [comment]
@danharrin you can close this for now.

If i delete the public/css & public/js before composer update and than run NPM run build it works for de example in the docs.
Still have 2 that dont work, but think that is a code issue insted of a Filament issue.
