### ISSUE TITLE
Unable to install 2.0

### ISSUE THREAD

**Issue by malpaso** [laravel-filament/filament#1051]
### Package

filament/filament

### Package Version

v2.0

### Laravel Version

v8.6.10

### Livewire Version

v2.8

### PHP Version

PHP 8.1.1

### Bug description

Unable to install Filament, receive the message below
`composer require filament/filament:^2.0

  [InvalidArgumentException]
  Could not find package filament/filament in a version matching "2.0" and a stability matching "dev".

require [--dev] [--dry-run] [--prefer-source] [--prefer-dist] [--prefer-install PREFER-INSTALL] [--fixed] [--no-suggest] [--no-progress] [--no-update] [--no-install] [--no-scripts] [--update-no-dev] [-w|--update-with-dependencies] [-W|--update-with-all-dependencies] [--with-dependencies] [--with-all-dependencies] [--ignore-platform-req IGNORE-PLATFORM-REQ] [--ignore-platform-reqs] [--prefer-stable] [--prefer-lowest] [--sort-packages] [-o|--optimize-autoloader] [-a|--classmap-authoritative] [--apcu-autoloader] [--apcu-autoloader-prefix APCU-AUTOLOADER-PREFIX] [--] [<packages>]...`

### Steps to reproduce

composer require filament/filament:^2.0

Taken from [Filament Installation](https://filamentadmin.com/docs/2.x/admin/installation#installation)

**Comment by danharrin** [comment]
As mentioned on Discord, you don't have PHP 8 installed.

**Comment by yiiprogrammer** [comment]
I'm receiving this error too: " Could not find package filament/filament in a version matching"
I do have PHP 8.1.2

![image](https://user-images.githubusercontent.com/4888901/150766379-48b7f458-11ae-4cea-b5d6-cf7eede8869f.png)

**Comment by danharrin** [comment]
Try just `composer require filament/filament`

**Comment by yiiprogrammer** [comment]
Yes, that worked perfectly: composer require filament/filament

I wonder why it didn't work with this: composer require filament/filament:^2.0
from here: https://filamentadmin.com/docs/2.x/admin/installation

![image](https://user-images.githubusercontent.com/4888901/150770345-e278a6df-55c1-4d6e-9a36-02741e5b47f0.png)

**Comment by danharrin** [comment]
We were getting lots of questions asking why v1 was installing when they hadn't followed the v2 system requirements properly 😂 `:^2.0` works well for most people I think, not sure why its different for some people. Maybe it's Windows?
