### ISSUE TITLE
Required Translatable Fields

### ISSUE THREAD

**Issue by Skullbock** [laravel-filament/filament#10527]
### Package

filament/spatie-laravel-translatable-plugin

### Package Version

3.1.29

### Laravel Version

10.39

### Livewire Version

3.3.3

### PHP Version

8.2

### Problem description

When creating a resource with a translatable field that is requires, currently filament drops any validation error that's not related to the selected locale.

This may lead to weird errors since if that field is required, it's probably required in all the languages, not only the active one.
This may lead to errors hardly understandable by the end user, especially if the required field is used in routing (ie: the slug) which breaks the form completedly.

Can we deal with this in a more configurable option maybe? I'm happy to PR the change if you provide a preferred way of dealing with this!

see  https://github.com/filamentphp/spatie-laravel-translatable-plugin/blob/3.x/src/Resources/Pages/CreateRecord/Concerns/Translatable.php#L44-L61

### Expected behavior

A validation error should be triggered, or the validation should be triggered based on a specific configuration option in the resource

### Steps to reproduce

Use the translatable plugin with 2 languages or more, and set a field required, then create a resource.

### Reproduction repository

https://github.com/filamentphp/spatie-laravel-translatable-plugin/

**Comment by tsalim13** [comment]
Any solution please ?

**Comment by automat64** [comment]
Any workaround for this?
