### ISSUE TITLE
TextInput incompatible with imaskjs "overwrite" and "padFractionalZeros" property combination

### ISSUE THREAD

**Issue by basepack** [laravel-filament/filament#1053]
### Package

filament/forms

### Package Version

v2.7.4

### Laravel Version

latest v8

### Livewire Version

latest v2

### PHP Version

PHP 8.1

### Bug description

Currently Filement Forms does not have the "overwrite" property of imaskjs, so I implemented it myself like this:

```php
TextInput::make('price')->label('Prijs (in euro)')
                    ->numeric()
                    ->mask(fn(TextInput\Mask $mask) => $mask->jsonOptions(<<<imaskoptions
                    {
                        scale: 2,
                        padFractionalZeros: true,
                        overwrite: true
                    }
                    imaskoptions))
```

Using the same parameters as with the imaskjs Numbers demo here: https://imask.js.org/guide.html#masked-number does work. For some reason when I type: "11", the input will be automatically become "1100,00" instead of "11,00".

![Screen Recording 2021-12-29 at 14 44 57](https://user-images.githubusercontent.com/939500/147668780-8cfb083a-d2d8-4acb-a0d3-bf58afd736ba.gif)

You are seeing console logs going, thats the result of chaning the Alpine TextInput Component to:
```js
var text_input_default = (Alpine) => {
  Alpine.data("textInputFormComponent", ({
    getMaskOptionsUsing,
    state: state2
  }) => {
    return {
      mask: null,
      state: state2,
      init: function() {
        if (!getMaskOptionsUsing) {
          return;
        }
        if (this.state) {
          this.$el.value = this.state?.valueOf();
        }
        this.mask = IMask(this.$el, getMaskOptionsUsing(IMask)).on("accept", () => {
            console.log('on accept' + this.mask.unmaskedValue)
            this.state = this.mask.unmaskedValue;
        });
        this.$watch("state", () => {
            console.log('watch state'+ this.mask.unmaskedValue)
          this.mask.unmaskedValue = this.state?.valueOf();
        });
      }
    };
  });
};
```

**Comment by danharrin** [comment]
In the latest version, this works for me:

```php
TextInput::make('price')
    ->label('Prijs (in euro)')
    ->mask(fn (TextInput\Mask $mask) => $mask->numeric()->decimalPlaces(2)->padFractionalZeros()->overwrite())
```

The mask needs to be numeric.

**Comment by basepack** [comment]
Hi @danharrin, thanks for the update, that was fast! However it does not activate the imaksjs 'overwrite' mode at the moment, see this gif for an idea what the current status is:
(using your exact code)

Normally in overwrite mode one could just type: "11.22" at once and be ready.

![Screen Recording 2021-12-30 at 07 58 57](https://user-images.githubusercontent.com/939500/147729169-662e3ce8-a3ec-4688-bfa3-5bc3f6d3f1b5.gif)

Steps taken:
1. type '11'
2. type '.' and ',' nothing happens (in overwrite mode the cursor should jump after the dot by now)
3. Place cursor at end position and remove zero's
4. try to type "22", but after the first "2" it append a "0" which I also cannot overwrite
5. remove the last "0" and type my last "2"

Am I missing some obvious setting here?

**Comment by danharrin** [comment]
@basepack can you give me the exact raw HTML that works as intended for you - don't use Filament at all. Because overwrite mode is not enabled for the example you linked to from the iMask docs.

**Comment by basepack** [comment]
@danharrin, great now we are into something. It is actually not the `overwrite` mode that is causing this strange behavior but `->padFractionalZeros()` method is not working as intended, see a working jsfiddle here: https://jsfiddle.net/96uy8pcz/ 

The idea is, that the ",00" part gets appended to the input value as soon as you tab out and the input looses focus.

**Comment by danharrin** [comment]
Hmm, well if you can get it to work with iMask normally then it should be pretty easy to make it work with Filament :)

**Comment by basepack** [comment]
I suspect it is Alpinejs clashing somewhere with imaskjs as you could see in my first post, because every input change event gets through twice.

Before I opened this ticket I have thoroughly debugged imaskjs and the Alpine `textInputFormComponent` component, but could not get it solved after hours of debugging. So that's where I am at currently :)

Just forget the `overwrite` part of this issue, and keep the `padFractionalZeros` part which does not work in the current version of Filament/Forms

**Comment by danharrin** [comment]
I've tried debugging this for a while, not getting anywhere. I think it's just a quirk with Alpine and iMask unfortunately 😬 But if you find a fix and submit a PR, I will happily review and merge it. Or, if you find anything more about why this issue happens, I can try and work on a fix for you.
