### ISSUE TITLE
Attempt to read property "budget" on null on form submit.

### ISSUE THREAD

**Issue by SupernovaIndustries** [laravel-filament/filament#10541]
i'm having this error ' _**Attempt to read property "budget" on null**_ ' when trying to submit this form.

The form shows correctly the numbers and also min and max, but wen i try to submit it throws the error.

```
            TextInput::make('quote')
                ->required()
                ->numeric()
                ->maxValue((int)$project->budget)
                ->minValue((int)$project->budget*0.4)
                ->prefixIcon('heroicon-s-currency-euro')
                ->prefix('Min. '.Number::currency($project->budget*0.4, 'EUR', 'fr'))
                ->suffix('Max. '.Number::currency($project->budget, 'EUR', 'fr'))
                ->label('Budget'),
            Select::make('project_id')
            ->required()
            ->relationship(
                name: 'project',
                titleAttribute: 'slug',
                modifyQueryUsing: fn (Builder $query) =>
                    $query->where('id', request()->route()->parameter('project'))
                )
                ->preload()
                ->label('Progetto'),
```

For example in this case min is 10000 and max is 25000 but when i submit it throws the error

Min works
![image](https://github.com/filamentphp/filament/assets/44363714/fe2c234a-b111-4079-ab98-90b3658d5814)

Max works
![image](https://github.com/filamentphp/filament/assets/44363714/bbf7af3d-f865-47a5-bd09-8b30ea744303)

Any clue?

_Originally posted by @MechanicalEclipse in https://github.com/filamentphp/filament/discussions/10416_

**Comment by zepfietje** [comment]
Please create an issue using the bug report template, and provide a reproduction repository.
