### ISSUE TITLE
SelectFilter throw the error: Undefined array key "value"

### ISSUE THREAD

**Issue by ismaail** [laravel-filament/filament#10543]
### Package

filament/filament

### Package Version

v3.1.30

### Laravel Version

v10.39.0

### PHP Version

PHP 8.2.13

### Problem description

using **SelectFilter** with **form** throw  this error `Undefined array key "value"`

the error is from the method `getActiveCount`  in `tables/src/Filters/SelectFilter.php`  

### Expected behavior

show select filter

### Steps to reproduce

create Table SelectFilter whith form

```php
public static function table(Table $table): Table
{
    return $table
        //... 
        ->filters([
            Tables\Filters\SelectFilter::make('Location')
                ->form([
                    // Region
                    Select::make('region')
                        ->options(Region::whereHas('properties')->pluck('name', 'id')->toArray()),
                    ])
        ])
}
```

### Reproduction repository

https://github.com/nextmediageneration/immobilier_storage_app

**Comment by danharrin** [comment]
Technically, the SelectFilter has, and always has, relied on `value` or `values` as the name of the field. There is no need to override the entire `form()` like this:

```php
Tables\Filters\SelectFilter::make('Location')
     ->options(Region::whereHas('properties')->pluck('name', 'id')->toArray())
```

Anyway, I've just added some checks to prevent the error. They will be in the next release b60269e4beaa90e77a4494a5719fe614e0e978b3. But as I said, the error shouldnt happen in the first place if you use the correct field name.

**Comment by ismaail** [comment]
b60269e fixes the issue, thanks.
