### ISSUE TITLE
Select searchable confused with HTML content

### ISSUE THREAD

**Issue by jonaaix** [laravel-filament/filament#10550]
### Package

filament/forms

### Package Version

3.1.29

### Laravel Version

10.10

### PHP Version

8.2

### Problem description

When I create a relation form select, that is searchable and uses custom HTML labels, the search results are always empty.

```php
// Works not
Forms\Components\Select::make('category_id')
    ->relationship(name: 'category')
    ->getOptionLabelFromRecordUsing(function (Model $record) {
        return "<span class='text-primary-600 dark:text-primary-400'>[{$record->id}]</span> {$record->name}";
    })
    ->native(false)
    ->preload()
    ->searchable(true)
    ->allowHtml(true);

// Works
Forms\Components\Select::make('category_id')
    ->relationship(name: 'category')
    ->getOptionLabelFromRecordUsing(function (Model $record) {
        return "[{$record->id}] {$record->name}";
    })
    ->native(false)
    ->preload()
    ->searchable(true)
    ->allowHtml(true);
```

So I would guess the HTML code does not get removed while the search is running

### Expected behavior

The search results should be the same, no matter using HTML or not.

P.S. It would be a great feature in general to have the builtin ability to show the option Id using something like `->showOptionId()`. 

### Steps to reproduce

Clone demo repository. 
`npm ci && composer install`
Start `npm run dev` and `php artisan serve`. 
Check Form in `ProductResource.php`

### Reproduction repository

https://github.com/btxtiger/filament-select-bug-10550

**Comment by danharrin** [comment]
I just downloaded the repository and did not change anything

<img width="1512" alt="Screenshot 2023-12-28 at 21 47 20" src="https://github.com/filamentphp/filament/assets/41773797/b1801a9d-f143-4c69-af40-16c1b4f4c74f">

**Comment by jonaaix** [comment]
@danharrin Did you type something into the searchbox ?

**Comment by danharrin** [comment]
Please send me a screen recording, I'm having trouble understanding what you think is wrong

**Comment by jonaaix** [comment]
[screencast-localhost_8000-2023.12.28-23_36_03.webm](https://github.com/filamentphp/filament/assets/15804690/507ac1cf-d491-4f24-bd42-0b8185f12105)

**Comment by danharrin** [comment]
Issue with Choices.js - https://codepen.io/danharrin/pen/JjzdvNK

Not something we can fix in Filament.
