### ISSUE TITLE
while logging in on the live server and returning to the login page

### ISSUE THREAD

**Issue by MasterAdmin2** [laravel-filament/filament#10560]
### Package

filament/filament

### Package Version

"filament/filament": "^3.1",

### Laravel Version

"laravel/framework": "^10.10",

### Livewire Version

3.0

### PHP Version

8.2

### Problem description

while logging in on the live server and returning to the login page

### Expected behavior

```php
array:4 [
  "data" => array:15 [
    "data" => array:3 [
      "email" => null
      "password" => null
      "remember" => false
    ]
    "mountedActions" => []
    "mountedActionsArguments" => []
    "mountedActionsData" => []
    "defaultAction" => null
    "defaultActionArguments" => null
    "componentFileAttachments" => []
    "mountedFormComponentActions" => []
    "mountedFormComponentActionsArguments" => []
    "mountedFormComponentActionsData" => []
    "mountedFormComponentActionsComponents" => []
    "mountedInfolistActions" => []
    "mountedInfolistActionsData" => []
    "mountedInfolistActionsComponent" => null
    "mountedInfolistActionsInfolist" => null
  ]
  "name" => "filament.pages.auth.login"
  "component" => "Filament\Pages\Auth\Login"
  "id" => "CtkK9rZGi7fnfpYsveGS"
]
``` 

### Steps to reproduce

while logging in on the live server and returning to the login page

### Reproduction repository

https://github.com/MasterAdmin2/filament

### Relevant log output

```shell
while logging in on the live server and returning to the login page
```

I installed Breeze, and tried to log in, and tried to access the filament dashboard it is returning me a blank black screen.
and added debugbar, it is fetching data, but only not showing it on the browser.

**Comment by danharrin** [comment]
Any browser console errors?

**Comment by MasterAdmin2** [comment]
> Any browser console errors?

Yes mate, livewire.js not found but I had successfully done all the uploads. If u want I can share you the hosting account with the domain itself.

**Comment by danharrin** [comment]
This is not a bug in Filament, please seek help in the Livewire Discord or GitHub Discussions for how to configure Livewire in production
