### ISSUE TITLE
The event 'TenantSet' is called multiple times when setting the tenant in the panel (more than 50 times)

### ISSUE THREAD

**Issue by wq9578** [laravel-filament/filament#10601]
### Package

filament/filament

### Package Version

v3.1.32

### Laravel Version

v10.10

### Livewire Version

v3.3.3

### PHP Version

PHP 8.2.5

### Problem description

The event 'TenantSet' is called multiple times when setting the tenant in the panel (in my case more than 50 times!).
This slows down the application, in particular if the current tenant is stored in the database.

### Expected behavior

The event 'TenantSet' should be called only once.

### Steps to reproduce

Source available here: https://github.com/filamentphp/filament/discussions/10589#discussioncomment-7989573

### Reproduction repository

https://github.com/filamentphp/filament/discussions/10589#discussioncomment-7989573

**Comment by wq9578** [comment]
Laravel version is actually 10.39.0

**Comment by danharrin** [comment]
Fixed by #10604.
