### ISSUE TITLE
Panel access not respected in tessts

### ISSUE THREAD

**Issue by MrKoopie** [laravel-filament/filament#10605]
### Package

filament/filament

### Package Version

v3.1.32

### Laravel Version

v10.39

### Livewire Version

v3.3.4

### PHP Version

PHP 8.3.0

### Problem description

When a user is denied access in User::canAccessPanel(): false, it should not be able to access anything in the panel.

In tests, however, User::canAccessPanel() is ignored, making tests work differently from how the system works in production.

### Expected behavior

When a user is not allowed to access a panel, it should not be able to see anything from that specific panel. While permissions help (and are implemented), this can cause confusion for the developer since the test environment handles panel permissions differently than accessing the same panel in production using a browser.

Note: I am aware that you can use permissions to resolve this, however, the test environment works different compared to a normal production environment access using the browser. This makes testing for 

### Steps to reproduce

1. Clone https://github.com/MrKoopie/filamentphp-unexpected-panel-access-in-test
2. In User::canAccessPanel() false is returned, denying access in the browser.
3. Test using `vendor/bin/pest`. The tests succeed, despite the fact that an user should not be able to access a panel.

### Reproduction repository

https://github.com/MrKoopie/filamentphp-unexpected-panel-access-in-test

**Comment by danharrin** [comment]
Testing a Livewire component does not run middleware. Access is checked in middleware. Make an additional HTTP `get()` test to test access.

**Comment by danharrin** [comment]
In fact, this first example does this just fine - https://filamentphp.com/docs/3.x/panels/testing#routing--render
