### ISSUE TITLE
Edit page - delete button error #5240

### ISSUE THREAD

**Issue by hamzadevtech1** [laravel-filament/filament#10608]
### Package

filament/filament

### Package Version

3

### Laravel Version

10

### Livewire Version

3

### PHP Version

8.2

### Problem description

I understand that this issue is related to livewire 3 but is there a solution for it in filament 3 ? instead of using halt method ? I am raising this issue for filament 3, for filament 2 this resolution works

https://github.com/filamentphp/filament/pull/5738/commits/90c57adb12f2540862b4550c52534fe8eda1624c

### Expected behavior

on delete the filament should redirect to home page

### Steps to reproduce

click on delete button on edit page and it throws error. Trying to get getKey() on null.

which makes sense because the record is deleted

### Reproduction repository

https://github.com/filamentphp/filament/pull/5738/commits/90c57adb12f2540862b4550c52534fe8eda1624c

**Comment by justrau** [comment]
This error happens when `render_on_redirect => true` in livewire.php config.
