### ISSUE TITLE
Badge count not limited to current tenant in multi-tenancy mode

### ISSUE THREAD

**Issue by wq9578** [laravel-filament/filament#10620]
### Package

filament/filament

### Package Version

v3.1.32

### Laravel Version

v10.39.0

### Livewire Version

v3.3.5

### PHP Version

PHP 8.2.5

### Problem description

The badge count is not limited to items belonging to the current tenant in multi-tenancy mode.
Instead, the number of all matching items is shown (including those belonging to other tenants as well).
Hence, the wrong number is shown, and foreign data is revealed.

### Expected behavior

Only the number of matching items **of the current tenant** should be shown.

### Steps to reproduce

Attach a badge with
`->badge(Customer::query()->where('active', true)->count())`
as described at https://filamentphp.com/docs/3.x/panels/resources/listing-records#adding-badges-to-filter-tabs

Correct number (implemented manually here):
`->badge(Customer::query()->where('team_id', Filament::getTenant()->id)->where('active', true)->count())`

### Reproduction repository

https://filamentphp.com/docs/3.x/panels/resources/listing-records#adding-badges-to-filter-tabs

**Comment by danharrin** [comment]
Please read the tenancy documentation. There are very few places where we scope queries. The rest should be scoped yourself. There is no global scope system. You have written this query within your own codebase, so you must scope it yourself according to the current tenant.

**Comment by zepfietje** [comment]
That's not a bug, since you're explicitly defining the query (which is not scoped by tenant).

**Comment by kombiahrk** [comment]
you can do this by adding a globalScopes for model using middleware

**Comment by wq9578** [comment]
Thank you very much to both of you. Filament is really a fantastic project.

I had already implemented the solution proposed here: https://filamentphp.com/docs/3.x/panels/tenancy#using-tenant-aware-middleware-to-apply-global-scopes

In order to avoid a trap it might be helpful to add a remark after the paragraph [Adding badges to filter tabs](https://filamentphp.com/docs/3.x/panels/resources/listing-records#adding-badges-to-filter-tabs) (below the image), such as:

> When implementing multi-tenancy, scoping must be applied, for example by using [tenant-aware middleware](https://filamentphp.com/docs/3.x/panels/tenancy#using-tenant-aware-middleware-to-apply-global-scopes).

**Comment by danharrin** [comment]
I would prefer not to add it to the docs there. There are probably hundreds of places where you can write a query in Filament, and it would be impossible to add it consistently to each one. Hence why this section exists, that I hope everyone reads if they use tenancy - https://filamentphp.com/docs/3.x/panels/tenancy#tenancy-security
