### ISSUE TITLE
Overflow issue with long table data

### ISSUE THREAD

**Issue by aldesrahim** [laravel-filament/filament#10633]
### Package

filament/filament

### Package Version

v3.1.33

### Laravel Version

v10.39.0

### Livewire Version

v3.3.5

### PHP Version

PHP 8.2.14

### Problem description

Hi everyone, i've a problem with vertical scrollbar (overflow-x) in page that interacts with table, so basically the scrollbar is very long and after some test, i've found that this was caused because my table has long data (vertically) and each columns has `sortable` applied. this issue affect UI on mobile and i'm not come up with any solutions at the moment.

additional information:
- this happens in google chrome browser
- it works fine in firefox
- i'm running Pop!_OS 22.04 LTS
- Chrome: Version 120.0.6099.129 (Official Build) (64-bit)
- Firefox: 120.0.1 (64-bit)

Screenshot (google chrome):
![image](https://github.com/filamentphp/filament/assets/37100012/39b005b3-315f-4a41-bea7-37ec8cd58bb6)

Screenshot (firefox | expected behavior):
![image](https://github.com/filamentphp/filament/assets/37100012/36590fd2-e2f5-42c9-ae57-ffbba51ec619)

### Expected behavior

1. Hide the unnecessary vertical scroll bar at the bottom

### Steps to reproduce

1. Create a new page or resource with a table with long columns or many columns
2. Add `sortable` on each column that hidden (let say you have 23 columns, table only display 11 columns, then add `sortable` to 12th until 23th columns)
3. See unnecessary vertical scroll bar at the bottom

### Reproduction repository

https://github.com/aldesrahim/filament-table-issue-overflow-x-sortable

**Comment by danharrin** [comment]
Fixed by #10636.
