### ISSUE TITLE
Create another button on createOptionForm not working

### ISSUE THREAD

**Issue by abduselam1** [laravel-filament/filament#10657]
### Package

filament/filament

### Package Version

v3.1.33

### Laravel Version

v10.39.0

### Livewire Version

v3.3.5

### PHP Version

8.1.6

### Problem description

After creating a record using "Create and create another" button on createOptionForm closed instead of reloading the form 
![image](https://github.com/filamentphp/filament/assets/57281126/ad59ebff-ac02-4f45-ae73-97f5a4495dbd)
![image](https://github.com/filamentphp/filament/assets/57281126/52a95b8d-5e03-4cb6-911b-0c70318853e5)
![image](https://github.com/filamentphp/filament/assets/57281126/35148e5d-d7a9-4e3c-ad8c-7455947cd41b)

### Expected behavior

The form should reload to add another record

### Steps to reproduce

When clicking on Create and create another button it should reload the form
OR Remove the button for createOptionForm.

### Reproduction repository

https://github.com/filamentphp/filament

**Comment by nttu94507** [comment]
try add `protected static bool $canCreateAnother = false ` in your resource
