### ISSUE TITLE
Lazy loaded widgets are not using the `$view` property when widget discovery is disabled

### ISSUE THREAD

**Issue by emmadesilva** [laravel-filament/filament#10663]
### Package

filament/filament

### Package Version

v3.1.0

### Laravel Version

v10.39.0

### Livewire Version

v3.3.5

### PHP Version

PHP 8.1.10

### Problem description

When widget discovery is disabled and a widget component is lazy loaded Livewire is unable to find the Blade view, and ignores the $view property, instead trying to parse it from the class name, causing an exception in case the view is differently named. When disabling lazy loading, the $view is used.

Possibly related to https://github.com/filamentphp/filament/issues/7892 and https://github.com/filamentphp/filament/issues/9066

### Expected behavior

The $view parameter should always be used.

### Steps to reproduce

1. Scaffold a widget, and rename the view file and $view property to match
2. Disable widget autodiscovery for the panel
3. Register the widget in a page header widgets
4. Visit the page, it will crash

// Throws Livewire\Exceptions\ComponentNotFoundException
// Unable to find component: [app.filament.widgets.git-hub-account-widget]

### Reproduction repository

https://github.com/caendesilva/filament-bug-repro/tree/lazy-loading-bug

**Comment by emmadesilva** [comment]
Should note that the reason I want to disable autodiscovery is because I don't want all widgets on the main dashboard. Using a different namespace (as in https://www.answeroverflow.com/m/1146705590769430558) seems hacky, and I don't think I should need to create a custom dashboard class.

**Comment by danharrin** [comment]
Autodiscovery registers every appropriate class as a Livewire component. When you disable that, the Livewire components are not registered anymore. You can register them without registering widgets using `discoverLivewireComponents()` or passing an array to `livewireComponents()`.
