### ISSUE TITLE
Resource title has translation of previous locale when switching locales

### ISSUE THREAD

**Issue by laurensdelombaert** [laravel-filament/filament#1067]
### Package

Other

### Package Version

v2.7.5

### Laravel Version

v8.77.1

### Livewire Version

v2.0.0

### PHP Version

PHP 8.0

### Bug description

When translating the name of a resource through the spatie-laravel-translatable plugin the title will only update after switching the locale a second time.

This will lag the title one locale behind with the previous locale if the name field was translated.

### Steps to reproduce

[Video](https://user-images.githubusercontent.com/32126029/147708372-ca9c0b72-2950-4136-b0a0-818904a207d4.mp4)

The above video was recorded through a flesh clone of the demo app with:

- Type 'json' on the name column for the brands table instead of 'text'.
- 'Spatie\Translatable\HasTranslations' in the Brand model.
- 'Filament\Resources\Concerns\Translatable' in the Brand resource.
- 'EditRecord\Concerns\Translatable' in the Edit brand resource.
- ['en', 'nl'] as languages in the config file.

**Comment by danharrin** [comment]
Fixed by #1068.
