### ISSUE TITLE
$data in handleRecordUpdate doesnt include fields with a relationship

### ISSUE THREAD

**Issue by danieladarve** [laravel-filament/filament#10670]
### Package

filament/filament

### Package Version

v3.1.35

### Laravel Version

v10.38.1

### PHP Version

PHP 8.2.12

### Problem description

When attempting to customize the saving process as suggested in the [documentation](https://filamentphp.com/docs/3.x/panels/resources/editing-records#customizing-the-saving-process) if the form contains either a Section or a Fieldset with a relationship enabled. The form state wont include the fields.

```
public static function form(Form $form): Form
{
    return $form
        ->schema([
            Section::make('Details')
                ->schema([
                    TextInput::make('name')
                        ->required(),
                ])
                ->columnSpan(1),
            Section::make('Address')
                ->relationship('address')
                ->schema([
                    TextInput::make('line_1')
                        ->required(),
                    TextInput::make('line_2'),
                    TextInput::make('line_3'),
                    TextInput::make('locality'),
                    TextInput::make('postcode')
                        ->required(),
                    Select::make('region')
                        ->options([
                            'ACT' => 'Australian Capital Territory',
                            'NSW' => 'New South Wales',
                            'NT' => 'Northern Territory',
                            'QLD' => 'Queensland',
                            'SA' => 'South Australia',
                            'TAS' => 'Tasmania',
                            'VIC' => 'Victoria',
                            'WA' => 'Western Australia',
                        ]),
                    Hidden::make('country')
                        ->required(),
                ])
        ]);
}
```

```
protected function handleRecordUpdate(Model $record, array $data): Model
    {
        dd($data);
    }
```

User Model
```
class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
        'password' => 'hashed',
    ];

    public function address(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Address::class);
    }
}
```

Addressable Model
```
class Addressable extends Model
{
    use HasFactory;

    protected $table = 'addressables';

    protected $fillable = [
        'address_id',
        'addressable_id',
        'addressable_type',
    ];

    public function address(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo(Address::class);
    }
}
```

Address Model
```
class Address extends Model
{
    use HasFactory;

    protected $fillable = [
        'name',
    ];
}
```

```
array:16 [▼ // app/Filament/Resources/StoreResource/Pages/EditStore.php:24
  "name" => "Test Name"
]
```

### Expected behavior

the full form state should be returned

### Steps to reproduce

In the reproduction repository

1. Go to the user resource
2. Edit the user
3. Click save

### Reproduction repository

https://github.com/danieladarve/filament-form-state-issue/tree/main/database

**Comment by Crazyde** [comment]
Hi! I have the same issue. Have you got a fix?

**Comment by Sjoerd24** [comment]
I noticed the same behaviour. How is the update to related records made in these cases?

**Comment by danieladarve** [comment]
The update and updating the relationship works however it is the full form state is not returned.
Another thing i noticed is even if you opt to change the handling of the record update the record will be updated regardless:

```
protected function handleRecordUpdate(Model $record, array $data): Model
{
    return $record;
}
```
Halting the saving process also has no effect:
```
protected function beforeSave(): void
{
    $this->halt();
}
```

**Comment by danharrin** [comment]
This is deliberate. The saving process happens inside Filament. The data that is returned excludes relationships, so that you can pass the data array to `create()` or `update()` without filtering out relationships.

If you want to alter how a relationship is saved, you can usually use `saveRelationshipsUsing()` or `saveRelationshipsBeforeChildrenUsing()`. To find the default implementation, you can click on the `relationship()` method in your IDE and check it out.

The relationship saving process is very complex, so it's best that it is hidden away like this and only overridden when the user needs to do so, on a component-by-component basis.

I do think this is pretty well documented when dealing with field relationships. You can also pass `dehydrated()` after `relationship()`, which adds the relationship data into the final form data array. But be aware that Filament will still save relationships, unless you pass `null` to `saveRelationshipsUsing()` or `saveRelationshipsBeforeChildrenUsing()`.

**Comment by danieladarve** [comment]
Thank you, this is def not documented in the docs

**Comment by Sjoerd24** [comment]
Thanks for the info Dan! Very useful information for my situation. :)
