### ISSUE TITLE
Input mask and validation

### ISSUE THREAD

**Issue by clinvest** [laravel-filament/filament#10694]
### Package

filament/filament

### Package Version

v3.1.35

### Laravel Version

v10.0.0

### Livewire Version

v3.0.0

### PHP Version

PHP 8.2.0

### Problem description

I have a field with a mask. The mask work correctly, I cannot type letters. But when I type letter, mask seems working, but letter are effectively "typed" (even if hidden) and we cannot validate the field.

```
TextInput::make('amount')
  ->mask(RawJs::make('$money($input)'))
  ->stripCharacters(',')
  ->numeric()
```

<img width="630" alt="Capture d’écran 2024-01-08 à 09 18 17" src="https://github.com/filamentphp/filament/assets/144620798/5c45bc9b-452d-4cec-8192-169d6332c58f">

### Expected behavior

If I enter "100aaa" in the field I expect the field to be valid as aaa shouldn't be in the input value.

### Steps to reproduce

1 - Go to http://127.0.0.1:8000/admin/users/create
2 - Type "100aaa" (even if you don't see the letters)
3 - Submit the form

You should get a "The amount field must be a number." error

### Reproduction repository

https://github.com/clinvest/filament-issue

**Comment by danharrin** [comment]
This is an Alpine/Livewire bug. Here is proof - https://wirebox.app/b/yrde7. You can open a failing test PR on the Livewire repository to initiate a fix.
