### ISSUE TITLE
Uncaught Snapshot missing on Livewire component with id

### ISSUE THREAD

**Issue by Lars-icepay** [laravel-filament/filament#10715]
### Package

filament/filament

### Package Version

v3.1.18

### Laravel Version

v10.35.0

### Livewire Version

v3.3.0

### PHP Version

php:8.2-fpm

### Problem description

When multiple (1+) Livewire components are on a page, clicking a header action will remove all but one livewire components. The  error "Uncaught Snapshot missing on Livewire component with id" is thrown when this occurs. In the recording below I put 3 test livewire component. Using different components will give the same result. 

https://github.com/filamentphp/filament/assets/106535819/ba354f8e-b9ee-42df-85fb-d93f13ea6931

### Expected behavior

I expect that that the, in this case, action form modal is opened and that the livewire components stay on the page.

### Steps to reproduce

The simplest way to reproduce the error is to add two or more Livewire components to a page. Add a header section and 

```php
    public static function infolist(Infolist $infolist): Infolist
    {
        return $infolist
            ->schema([
                Livewire::make(Interference::class),
                Livewire::make(Interference::class),
                Livewire::make(Interference::class),
                Section::make('break')
                    ->headerActions([
                        Action::make('throw error')
                            ->form([
                                TextInput::make('TestInput')
                            ])
                    ])
            ]);
    }
```

I added an reproduction repository with a full project with a livewire component

### Reproduction repository

https://github.com/Lars-icepay/filament-bug-test

### Relevant log output

```shell
Uncaught Snapshot missing on Livewire component with id: C2gixlm2VfB448Pfvq0f
```

**Comment by danharrin** [comment]
Fixed by #10946. You will need to give each component a unique `key()`, so we can pass it to Livewire for tracking.
