### ISSUE TITLE
The query builder filter Stuck the whole page with an error

### ISSUE THREAD

**Issue by sbc640964** [laravel-filament/filament#10725]
### Package

filament/filament

### Package Version

v3.1.42

### Laravel Version

v10.40.0

### PHP Version

8.1.2

### Problem description

The query builder filter Stuck the whole page with an error

![image](https://github.com/filamentphp/filament/assets/46646044/14ea3068-bf22-4a81-87de-1bea2f6e27f8)

Note: the attached repository is a branch of another repository

### Expected behavior

that there be no errors

### Steps to reproduce

Add a query builder with filters
Add a filter in the builder for text (for example)
Open the filters panel and add a filter
Select another value in the operator field
That's it, you'll see the error right away

### Reproduction repository

https://github.com/sbc640964/filament-tags-error/tree/query-builder-error

### Relevant log output

```shell
Uncaught TypeError: Cannot read properties of undefined (reading 'getElementsByClassName')
    at Proxy.getRecordsOnPage (http://10.0.0.2:8001/js/filament/tables/components/table.js?v=3.1.42.0:1:1206)
    at eval (eval at safeAsyncFunction (http://10.0.0.2:8001/livewire/livewire.js?id=e2b302e9:1249:21), <anonymous>:3:66)
    at [Alpine] const recordsOnPage = getRecordsOnPage()
```

**Comment by austincarpenter** [comment]
Also experiencing this with v3.0-3.2, when generally interacting with filters.

`this.$root` is undefined in `filament/tables/components/table.js`. Triggered by `resources/views/index.blade.php` by Alpine when binding the selection checkbox's checked state.

**Comment by austincarpenter** [comment]
Applying `->deselectAllRecordsWhenFiltered(false)` to the table prevents this error as a temporary workaround, although records will of course not be deselected.
