### ISSUE TITLE
Filamentphp ImportAction - Unable to import .csv file - File of invalid type - Firefox Browser

### ISSUE THREAD

**Issue by ARRW-Core** [laravel-filament/filament#10732]
### Package

filament/filament

### Package Version

v3.1.36

### Laravel Version

v10.40.0

### Livewire Version

^3.3

### PHP Version

PHP 8.2.13

### Problem description

![Screenshot_2](https://github.com/filamentphp/filament/assets/68743127/a95a1f9e-ae28-471d-8882-1f51029c7282)

Cannot upload .csv file that is downloaded with download example csv file

### Expected behavior

![Screenshot_3](https://github.com/filamentphp/filament/assets/68743127/6f3d5d97-62de-426d-8ab7-5e2fcfde1c87)

By directly changing the .csv to .txt, it is possible to upload the file. 

### Steps to reproduce

- Git pull the repository
- set up .env
- php artisan migrate --seed
- php artisan key:generate
- Open Firefox (there is no issue with chrome)
- Login with test@mail.com -> password 
- Users resource -> Import users
- Download example csv
- Upload the downloaded csv

### Reproduction repository

https://github.com/ARRW-Core/filament_csv_import_issue.git

**Comment by petrisorcraciun** [comment]
mime types for csv: 
'text/csv', 'application/csv', 'text/x-comma-separated-values', 'text/x-csv'

**Comment by danharrin** [comment]
Thanks @petrisorcraciun, #10762

**Comment by uqjohart** [comment]
Updated to the latest version, it now thorws this error when trying to upload the example csv (See attached)
<img width="366" alt="2024-01-15 08_42_09-Staff - SDP — Mozilla Firefox" src="https://github.com/filamentphp/filament/assets/85085437/f50a1523-4d28-48ef-82df-d8756eefbc98">

**Comment by danharrin** [comment]
Please tell me the mime type of your file

**Comment by uqjohart** [comment]
> Please tell me the mime type of your file

Just the plain old csv you get when you click on the 'Download an example csv' link provided by filament. 
(Filament v3.1.47)

Edit: attached
[staff-importer-example.csv](https://github.com/filamentphp/filament/files/13933347/staff-importer-example.csv)

**Comment by danharrin** [comment]
I downloaded your file, uploaded it in my own project, and it worked fine. I'm gonna need more info.

**Comment by uqjohart** [comment]
Looks like it is only a problem on Firefox. Works on chrome and edge. Firefox must be doing something silly.

Regards,

Joshua Hartmann
Senior Web Application Developer

E ***@***.***
________________________________

**Comment by danharrin** [comment]
Just tried in Firefox and it seems fine for me

**Comment by notscottsmith** [comment]
This is occurring with my instance of Filament - using the csv provided by the importer itself.

![image](https://github.com/filamentphp/filament/assets/51853082/b0154284-7027-4a07-9172-8de7984a3cab)

I'm using Firefox, Laravel v11, and v3.2.52 of Filament. If I rename the file to .txt it works fine. If I use Edge/Chrome, it works fine.

Firefox looks to be detecting the CSV files as "application/vnd.ms-excel" and not text/csv, et al.

https://codepen.io/GrizzlyStu/pen/YzjZjez - This allows you to interrogate the mime-type that your browser interprets it as.

![image](https://github.com/filamentphp/filament/assets/51853082/e55efce0-b15d-454b-8c6a-3a6db5bd78e8)

Adding "application/vnd.ms-excel" to CanImportRecords.php solves this issue for Firefox users.

![image](https://github.com/filamentphp/filament/assets/51853082/d0873b8a-5943-4a03-b33a-6fd368aa4ca5)

I created a [PR](https://github.com/filamentphp/filament/pull/12038) for this, just in case.
