### ISSUE TITLE
Alpine Expression Error: undefined for form within livewire component

### ISSUE THREAD

**Issue by sasaorasanin** [laravel-filament/filament#10757]
### Package

filament/filament

### Package Version

v3.1.42

### Laravel Version

10.40.0

### Livewire Version

v3.3.5

### PHP Version

8.2.12

### Problem description

Alpine Expression Error: undefined for form within livewire component.
I get error on the picture, bcs of the error the form doesnt work and submiting refreshes the page. (I am calling this component inside modal)
![image](https://github.com/filamentphp/filament/assets/100382372/424a4680-59e1-47fd-9516-70ff271765ee)

```php
<?php

namespace App\Livewire;

use Filament\Forms\Contracts\HasForms;
use Livewire\Component;
use Filament\Forms\Components\RichEditor;
use Filament\Forms\Form;
use Filament\Forms\Concerns\InteractsWithForms;

class Chat extends Component implements HasForms
{
    use InteractsWithForms;

    public ?array $data = [];
    
    public function mount(): void
    {
        $this->form->fill();
    }

    public function render()
    {
        return view('livewire.chat');
    }
    
    public function form(Form $form): Form
    {
        return $form
            ->schema([
                RichEditor::make('body')
            ])
            ->statePath('data');
    }
    public function send (): void
    {
        dd($this->form->getState());
    }
}
```

### Expected behavior

Bind form field to $data array.

### Steps to reproduce

https://filamentphp.com/docs/3.x/forms/adding-a-form-to-a-livewire-component

### Reproduction repository

https://github.com/soixt/demo-for-testing

### Relevant log output

```shell
Alpine Expression Error: undefined

Expression: "richEditorFormComponent({
                            state: $wire.$entangle('data.body', false),
                        })"
```

**Comment by leoblanski** [comment]
I guess I have a similar problem... Basically, what I'm doing is creating a new RichEditor component within a form. It works perfectly when I'm using complete resources (with CRUD pages). However, for some reason – I don't know if it's a bug or if I'm doing something wrong – when using it in a simple resource generated with php artisan filament:resource TestResource --simple,' it doesn't work…

```
public static function form(Form $form): Form
    {
        return $form
            ->schema([
                RichEditor::make('body')
                    ->label('Description')
                    ->required(),
            ]);
    }
```

Returns: Uncaught Could not find Livewire component in DOM tree on console

![test](https://github.com/filamentphp/filament/assets/34586977/c10bb468-b850-4de0-86aa-352350a7abaf)

**Comment by sasaorasanin** [comment]
F*ck, I figure it out.... Such a dumb error message for what was causing it... I had two elements in my livewire component on root level.
