### ISSUE TITLE
Action tooltips re-appear after modal is closed

### ISSUE THREAD

**Issue by binaryfire** [laravel-filament/filament#10772]
### Package

filament/filament

### Package Version

3.1.43

### Laravel Version

10.3.2

### Livewire Version

3.3.5

### PHP Version

8.3

### Problem description

Action tooltips reappear after the action modal is closed. See:

<img width="1011" alt="image" src="https://github.com/filamentphp/filament/assets/5361908/9181d8ef-d57f-4996-82f1-7727ddb0bee0">

### Expected behavior

Action tooltips should not reappear after the trigger button has been clicked.

### Steps to reproduce

Launch the reproduction repo, click the icon button in the dashboard widget, then click "Confirm" to close the modal. The tooltip will re-appear.

### Reproduction repository

https://github.com/binaryfire/filament-action-bugs

**Comment by danharrin** [comment]
The action is focused, what is the reason they should not appear when the button is focused? This is an accessibility feature of Tippy.js, as far as I know.

**Comment by binaryfire** [comment]
Hmm ok. Feels strange to me - see this vid: https://www.youtube.com/watch?v=N_Z2MmbE6rc. I can't recall seeing this behaviour in any other platforms.

It's worse in other places. This is what happens with an icon button next to the user menu:

<img width="430" alt="image" src="https://github.com/filamentphp/filament/assets/5361908/6273e873-5f9c-44bb-9b15-9e5999fa80ad">

**Comment by danharrin** [comment]
I think this is to do with focus trapping. When the modal is opened, focus is shifted into the modal, and Alpine remembers the previously focused element. When the modal is closed, Alpine refocuses the element that was previously focused. Then, Tippy receives this focus event and opens the tooltip again.

**Comment by binaryfire** [comment]
Any suggestions on how to stop it from happening? It looks pretty broken in my UI.

PS. Tippy was abandoned 2 years ago: https://github.com/atomiks/tippyjs. You probably want to migrate to Floating UI for tooltips at some point

**Comment by danharrin** [comment]
I can't think of anything to stop it, and I do think that it is a good default behaviour, regardless of whether or not it works in your case
