### ISSUE TITLE
Actions in sidebar open modals inside of sidebar instead of center of screen

### ISSUE THREAD

**Issue by binaryfire** [laravel-filament/filament#10771]
### Package

filament/filament

### Package Version

3.1.43

### Laravel Version

10.3.2

### Livewire Version

3.3.5

### PHP Version

8.3

### Problem description

Some apps have actions at the top and/or bottom of the sidebar. For example a single full-width button at the top or 
"Get help" and "Send feedback" icon buttons at the bottom.

However actions added to the Filament sidebar open their modals inside of sidebar instead of in the center of the screen:

<img width="1572" alt="image" src="https://github.com/filamentphp/filament/assets/5361908/5e6664f4-6eaa-4e98-82a7-71b6b8e8fd62">

### Expected behavior

Action triggers in the sidebar should open modals in the center of the screen.

### Steps to reproduce

Launch the reproduction repository, then click the button at the top of the sidebar or the icon button at the bottom of the sidebar.

### Reproduction repository

https://github.com/binaryfire/filament-action-bugs

**Comment by danharrin** [comment]
This wasn't really the intention of the component, so can you please debug this and work out what's happening? Maybe the modal component needs to live in the main page content, and you just emit an event to open it from the sidebar?

**Comment by binaryfire** [comment]
Dispatching an event from the sidebar buttons to open a modal in the main page works. Thanks.

**Comment by mwaqasiu** [comment]
@binaryfire 

Hey, I have the same use case. Can you please tell me how you fix it?

**Comment by binaryfire** [comment]
Hi @mwaqasiu. Check out the code in the reproductin repo. I updated it with a working example.
