### ISSUE TITLE
Plugin assets can't be registered conditionally for packages

### ISSUE THREAD

**Issue by PhiloNL** [laravel-filament/filament#10786]
### Package

filament/filament

### Package Version

v3.1.47

### Laravel Version

v10.40.0

### Livewire Version

v3.3.5

### PHP Version

8.2.14

### Problem description

I have a Filament plugin that registers an asset. This asset is attempted to be loaded when accessing the panel that includes the plugin. So far so good. When accessing the panel the asset is not found however because the asset is not published. This happens when the asset is registered inside the plugin:

```php
class FilamentPlugin  implements \Filament\Contracts\Plugin
{
    public function getId(): string
    {
        return 'example';
    }

    public function boot(Panel $panel): void
    {
        FilamentAsset::register(
            assets: [
                Js::make('example-asset', __DIR__.'/../resources/js/example.js'),
            ],
            package: 'example/package'
        );
    }

    public function register(Panel $panel): void
    {

    }
}
```

The `php artisan filament:assets` command does not pick up these assets. The alternative is to register the asset inside the service provider but this will include the asset in every panel, even if the panel does not use the given plugin.

### Expected behavior

`php artisan filament:assets` initializes panels to ensure plugins are initialized and assets are registered to be published or maybe a different API for packages to register assets.

### Steps to reproduce

Run `php artisan filament:assets` and see that `example.js` is never published.

### Reproduction repository

https://github.com/PhiloNL/filament-asset-bug

### Relevant log output

A workaround is to change the registration method into a static method and also call it from the package service provider when running a CLI command:

```php
class MyPackageServiceProvider extends ServiceProvider
{
    public function boot(): void
    {
        if(app()->runningInConsole()) {
            MyFilamentPlugin::registerPackageScripts();
        }
    }
}
```

This will ensure the asset is published but not included within panels that don't use the plugin.

**Comment by saade** [comment]
Hi @PhiloNL, since we use async alpine to load scripts and styles, they only get requested when your plugin is rendered in the current view. If your panel does not use the plugin, it should not be requested, can you confirm this behavior?

**Comment by PhiloNL** [comment]
Hi @saade,

If I add this to my package AppServiceProvider:

```php
        FilamentAsset::register(
            assets: [
                Js::make('my-script', __DIR__.'/../../resources/js/script.js'),
            ],
            package: 'vendor/package'
        );
```

And add `alert('hello');` to this script, it will fire an alert on every panel.
If I register the asset inside the plugin, the script will only fire on the panel that uses the plugin. So this works as mentioned earlier. The problem now is that `php artisan filament:assets` doesn't know about these assets so they never get published.

**Comment by danharrin** [comment]
You can now use `$panel->assets()` in `register()` for this. 

Doing so in `boot()` will only register them in middleware when the panel is actually getting run. I've added a new method so that the assets will always be registered in the console, but only actually require them in the panel they were registered to.

**Comment by PhiloNL** [comment]
Thanks Dan! 😄
