### ISSUE TITLE
Action button icon does not apply specified `color()` when `outlined()` method is used.

### ISSUE THREAD

**Issue by kidereo** [laravel-filament/filament#10813]
### Package

filament/filament

### Package Version

v3.2.1

### Laravel Version

v10.40.0

### Livewire Version

v3.3.5

### PHP Version

PHP v8.3.0

### Problem description

Action button icon no longer applies specified `color()` when `outlined()` method is used. Only the label is the right colour. Was working fine before. Thanks!

### Expected behavior

Outlined button is expected to show both label and icon in the colour specified.

### Steps to reproduce

Clone reproduction repository.
Run migrations with seeder.
Navigate to Books resource.
Observe filled buttons with white text and icon color on primary background.
In the `ListBooks.php`, uncomment `outlined()`.
Observe the Import from CSV button becoming outlined with border and font colour as specified but icon remaining in white.

### Reproduction repository

https://github.com/kidereo/filamentphp-issues

**Comment by Jam0r85** [comment]
I also have this issue

**Comment by zepfietje** [comment]
Fixed by https://github.com/filamentphp/filament/pull/10858.
