### ISSUE TITLE
Could not find Livewire component in DOM tree (RichEditor ONLY Simple Resource - Modal)

### ISSUE THREAD

**Issue by leoblanski** [laravel-filament/filament#10810]
### Package

filament/filament

### Package Version

v3.1.0 / v3.1.47

### Laravel Version

v10.39.0 / v10.40.0 

### PHP Version

8.2

### Problem description

I'm creating a new RichEditor component into form, it works perfectly when I'm using complete resources (With CRUD pages), but for some reason, when using a simple resource, generated simply with `php artisan filament:resource TestResource --simple` it doesn't work...

Same code in each resource:

```
public static function form(Form $form): Form
    {
        return $form
            ->schema([
                RichEditor::make('body')
                    ->label('Description')
                    ->required(),
            ]);
    }
```

Returns: Uncaught Could not find Livewire component in DOM tree on console 

![test](https://github.com/filamentphp/filament/assets/34586977/91ff2c02-f1f2-48de-9b0b-5f01c182237e)

### Expected behavior

I expected a preview image as it works on the complete Resource.

### Steps to reproduce

- run `php artisan make:filament-resource --simple` with any resource name;
- Open resource and replace the form code:
```
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                RichEditor::make('name')                   
            ]);
    }
```
- Open the resource and try to attach an image
- Open the console and take a look on the error.

If you do the same thing, but using `php artisan filament:resource TestResource --generate` it works.

### Reproduction repository

https://github.com/leoblanski/filament-upload-image-bug

**Comment by danharrin** [comment]
Tried Chrome, Firefox and Safari, and I am unable to reproduce the issue. So I am going to need a better reproduction repository to be able to fix this.

https://github.com/filamentphp/filament/assets/41773797/b47afa88-9cef-438a-b67e-5caf8f66b755

**Comment by rappasoft** [comment]
I can reproduce this issue on 3.2.10.

I can also confirm it is only on simple resources.

**Comment by danharrin** [comment]
#11004
