### ISSUE TITLE
When there is a SQL error in the importer, it causes multiple retries.

### ISSUE THREAD

**Issue by bzy107** [laravel-filament/filament#10816]
### Package

filament/filament

### Package Version

v3.1.47

### Laravel Version

v10.40.0

### Livewire Version

v3.3.5

### PHP Version

8.2.11

### Problem description

This issue is related to #10814 and occurred when using PostgreSQL. Additionally, the queue is running in the database.

```
QUEUE_CONNECTION=database
```

When a job fails due to a SQL error during CSV import, the `getJobRetryUntil()` function retries the job for the specified time. However, it currently also retries the error for the specified number of times. Therefore, I want to modify it to only retry once, but currently, it is only possible to specify a time.

As a solution, I would like to make `getJobRetryUntil()` nullable so that the job is only executed once.

This image is from a case where getJobRetryUntil was set to 3 seconds.
```php
    public function getJobRetryUntil(): CarbonInterface
    {
        return now()->addSeconds(3);
    }
```
![スクリーンショット 2024-01-16 2 19 41](https://github.com/filamentphp/filament/assets/28666304/bddf3a37-ee46-4284-a9fc-1d3f4b3ef8d3)

**I will create a pull request for this issue later.**

### Expected behavior

If getJobRetryUntil() is set to null, it will be executed only once.
```php
    public function getJobRetryUntil(): ?CarbonInterface
    {
        return null;
    }
```
![スクリーンショット 2024-01-16 2 25 27](https://github.com/filamentphp/filament/assets/28666304/f11acf4d-39ac-4a6d-8426-25ddf17b3491)

### Steps to reproduce

Please refer to #10814 for more information.

### Reproduction repository

https://github.com/bzy107/filament-select-bug

**Comment by danharrin** [comment]
It appears that this is a feature request rather than a bug report, so closing
