### ISSUE TITLE
There are cases where a SQL error occurs before validation in the importer.

### ISSUE THREAD

**Issue by bzy107** [laravel-filament/filament#10814]
### Package

filament/filament

### Package Version

v3.1.47

### Laravel Version

v10.40.0

### Livewire Version

v3.3.5

### PHP Version

8.2.11

### Problem description

When importing with CSV and passing a string to the 'id' field, I expected it to result in a validation error. 

```php
    public static function getColumns(): array
    {
        return [
            ImportColumn::make('id')
                ->rules(
                    [
                        'nullable',
                        'integer',
                        'exists:App\Models\Patient',
                    ]
                ),
                ...
        ];
    }
```

However, the job fails before reaching the validation error. In the `failed_jobs.exception` there is a message like the following (excerpt):
```
PDOException: SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type bigint: "a"
```

I am using PostgreSQL in the database (version 14), and the importer is executed in the background with `QUEUE_CONNECTION=database`

This issue does not occur with MySQL, only with PostgreSQL.

image:
![スクリーンショット 2024-01-16 1 26 56](https://github.com/filamentphp/filament/assets/28666304/e185ce51-da1c-43e4-8d3c-d48b927c4983)
![スクリーンショット 2024-01-16 1 27 43](https://github.com/filamentphp/filament/assets/28666304/2be53fa5-3593-4e33-95d1-a04ea8d19a40)
![スクリーンショット 2024-01-16 1 28 41](https://github.com/filamentphp/filament/assets/28666304/ffd28c5c-dec1-4224-9edd-dac200937e64)
![スクリーンショット 2024-01-16 1 36 52](https://github.com/filamentphp/filament/assets/28666304/bc27a951-c757-4aae-bab4-4dfcd07c4275)
failed_jobs table
![スクリーンショット 2024-01-16 1 35 01](https://github.com/filamentphp/filament/assets/28666304/1096b701-c31e-40ed-963d-5a363692ec26)

**I will create a pull request for this issue later.**

### Expected behavior

The contents of the validation errors should be displayed in the downloaded error file.
`The id field must be an integer.`

### Steps to reproduce

Please update the .env file to reflect the PostgreSQL configuration:
```
DB_CONNECTION=pgsql
DB_PORT=5432
```
Also, change the queue connection in the .env file:
```
QUEUE_CONNECTION=database
```

Running the Seeder
```bash
php artisan migrate:fresh --seed
```

Access `/admin/patients` to display the import modal.
Upload a CSV file with the id specified as a string, as shown below:
```csv
id,date_of_birth,name,type
a,2024-01-01,Clare,cat
```

Execute the worker before running the import (otherwise, it might fail for other reasons):
```bash
php artisan queue:work
```

Execute the import in the modal. This should reproduce the issue.

### Reproduction repository

https://github.com/bzy107/filament-select-bug

**Comment by danharrin** [comment]
It's the `resolveRecord()`, it runs before validation, since the record needs to be available for certain validation rules, like `unique`. So you should check there before resolving. The SQL error is coming from your own query.

**Comment by bzy107** [comment]
@danharrin 
I understand. Checking for unique constraints is indeed necessary. However, it's important to consider cases where errors might occur during ID-based searches, as seen in the case of Postgres. 
This assumes scenarios where the user mistakenly passes a string instead of the correct ID.
Are there alternative approaches to handle this?

Additionally, if there's an ID field in the CSV, ignoring the unique constraint on the self-ID could lead to import failures. It would be beneficial to add a feature addressing this issue promptly (#10756).

**Comment by danharrin** [comment]
Alternative approach is to check the UUID validity before passing it to your query. Maybe with `Str::uuid()`.
