### ISSUE TITLE
Filament Table Actions (Edit, Delete) not working on Livewire component

### ISSUE THREAD

**Issue by PrasadChinwal** [laravel-filament/filament#10854]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

v10.0

### Livewire Version

v3.0

### PHP Version

^8.2

### Problem description

I am trying to use Filament tables outside panels i.e. in a livewire component. I followed the docs and I can see the table in the browser. The create action works perfectly as expected but sometimes need double clicking.
Problem:
- Edit action never opens a modal or a slideover
- Delete action doesn't work too.
- When you search or sort you get a javascript/alpine error that `Alpine Expression Error: Cannot read properties of undefined (reading 'getElementsByClassName')`

### Expected behavior

- When you click on edit button it opens either a modal or slideover.
- When you click on delete it triggers the delete action or requests confirmation.
- The search/sort works as expected.

### Steps to reproduce

1. Clone the reproduction repository
2. Create .env
3. Run migrations
4. Install composer and npm dependencies
5. Visit application home route.
6. Create a user 
7. Test edit/delete/sort/search functionalities

### Reproduction repository

https://github.com/PrasadChinwal/filament-tables

### Relevant log output

```shell
Uncaught TypeError: Cannot read properties of undefined (reading 'getElementsByClassName')
    at Proxy.getRecordsOnPage (http://semesterplanner.test/js/filament/tables/components/table.js?v=3.2.2.0:1:1206)
    at eval (eval at safeAsyncFunction (http://semesterplanner.test/livewire/livewire.js?id=e2b302e9:1249:21), <anonymous>:3:66)
    at [Alpine] const recordsOnPage = getRecordsOnPage()

                                            if (recordsOnPage.length && areRecordsSelected(recordsOnPage)) {
                                                $el.checked = true

                                                return 'checked'
                                            }

                                            $el.checked = false

                                            return null (eval at safeAsyncFunction (http://semesterplanner.test/livewire/livewire.js?id=e2b302e9:1249:21), <anonymous>:13:59)
    at http://semesterplanner.test/livewire/livewire.js?id=e2b302e9:1271:23
    at tryCatch (http://semesterplanner.test/livewire/livewire.js?id=e2b302e9:1191:14)
    at http://semesterplanner.test/livewire/livewire.js?id=e2b302e9:3445:19
    at Array.reactiveEffect (http://semesterplanner.test/livewire/livewire.js?id=e2b302e9:2365:18)
    at flushJobs (http://semesterplanner.test/livewire/livewire.js?id=e2b302e9:714:15)
```

**Comment by danharrin** [comment]
Please simplify your reproduction repository. Start from a fresh Laravel app and just add the minimal amount of code possible to reproduce the issue. Please do not include files that are not relevant to me being able to see the problem.

**Comment by zepfietje** [comment]
Closing this as no additional info or minimal reproduction repository has been provided.
