### ISSUE TITLE
Add Support for Searching in Encrypted Columns

### ISSUE THREAD

**Issue by batuhanhazarguler** [laravel-filament/filament#10863]
### Package

filament/filament

### Package Version

v3

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

PHP 8.3

### Problem description

There is currently no built-in support or documented method in Filament for searching in encrypted columns. When attempting to add a Closure function to the searchable function, I am unable to achieve the desired result.

### Expected behavior

I request the addition of a feature or a documented method in Filament to search in encrypted columns. This should include an improvement that allows defining custom search queries in encrypted columns, for example by adding a Closure function to the searchable function.

### Steps to reproduce

Make a field encrypted in the model and then attempt to search for that field in the table.

### Reproduction repository

https://github.com/batuhanhazarguler/filamentphp-encrypted

**Comment by danharrin** [comment]
This is not a bug. Please do not open issues for feature requests.

Please investigate ways to search encrypted data outside of Filament, the same techniques in Eloquent apply. However, I do not think it's something that is easily possible.

**Comment by batuhanhazarguler** [comment]
Thanks very much for your answer. Please excuse me if I'm wrong..
