### ISSUE TITLE
Add Support for Searching in Encrypted Columns

### ISSUE THREAD

**Issue by batuhanhazarguler** [laravel-filament/filament#10861]
### Package

filament/filament

### Package Version

v3

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

PHP 8.3

### Problem description

There is currently no built-in support or documented method in Filament for searching in encrypted columns. When attempting to add a Closure function to the searchable function, I am unable to achieve the desired result.

### Expected behavior

I request the addition of a feature or a documented method in Filament to search in encrypted columns. This should include an improvement that allows defining custom search queries in encrypted columns, for example by adding a Closure function to the searchable function.

### Steps to reproduce

Make a field encrypted in the model and then attempt to search for that field in the table.

### Reproduction repository

https://github

**Comment by edrisaturay** [comment]
To solve this.. I use Laravel Scout and the Filament Laravel Scout Plugin https://filamentphp.com/plugins/kainiklas-laravel-scout

Following the Laravel Scout documentation, I configured Laravel Scout to use the Collection Driver because I had a relatively small DB
and it's working perfectly.
