### ISSUE TITLE
Money mask with comma as decial separator does not work properly

### ISSUE THREAD

**Issue by pelmered** [laravel-filament/filament#10867]
### Package

filament/filament

### Package Version

v3.2.2

### Laravel Version

v10.41.0

### Livewire Version

v3.3.5

### PHP Version

8.2.14

### Problem description

When you use a mask on TextInput like this `->mask(RawJs::make('$money($input, \',\', \' \')'))` with comma as decimal separator, it does not work properly. 

Related Alpine documentation: https://alpinejs.dev/plugins/mask#money-inputs

It looks like it is working like it should in vanilla Alpline.js as well: https://codesandbox.io/p/sandbox/alpine-js-forked-g2dg8t?file=%2Findex.html

### Expected behavior

Se "Steps to reproduce"

### Steps to reproduce

Compare the following two fields in a form:

```
            // This gives "1 234 567" - wrong
            // This should give "12 345,67"
            TextInput::make('any_column')
                     ->mask(RawJs::make('$money($input, \',\', \' \')'))
                     ->formatStateUsing(fn (string $state): string => 12345.67)
                     ->stripCharacters([',','.',' ',])->numeric(),

            // This gives "12,345.67" - correct
            TextInput::make('any_other_column')
                     ->mask(RawJs::make('$money($input, \'.\')'))
                     ->formatStateUsing(fn (string $state): string => 12345.67)
                     ->stripCharacters([',','.',' ',])->numeric(),
```

Or check http://127.0.0.1:8000/admin/users/1/edit in the reproduction repository.

### Reproduction repository

https://github.com/pelmered/filament-moeny-issue

**Comment by danharrin** [comment]
What browser are you using?

**Comment by danharrin** [comment]
I can reproduce the results with both Livewire wire:model binding and Alpine x-model binding, here: https://wirebox.app/b/47r9n

![Image](https://github.com/filamentphp/filament/assets/41773797/6568e567-4bc6-40e7-ac37-d4de6731bd2b)

Please open a failing test PR on the Livewire/Alpine repositories to request a fix.

**Comment by webthiagosilva** [comment]
I have the same problem, when I try to invert the tabs the mask doesn't work

**Comment by danharrin** [comment]
It's still a problem, but needs to be fixed in Alpine/Livewire and not Filament.

**Comment by luiseduardobraschi** [comment]
Hey, @danharrin 

Hasn't it been solved here?

https://github.com/alpinejs/alpine/commit/85cf3097f8642634c83d150cc8249ac173977f30

**Comment by danharrin** [comment]
That test doesnt cover the money mask, or decimal separators. The entire mask feature isnt broken, it's just that decimal issue.

**Comment by pelmered** [comment]
I created and issue here: https://github.com/alpinejs/alpine/discussions/4222

I also found this old issue that might be the same problem: https://github.com/alpinejs/alpine/discussions/3009

**Comment by pelmered** [comment]
I got a response there. The value should be sent in as a string, and not a decimal. Then it works as expected. 

So the code from above should be:

```
            TextInput::make('any_column')
                     ->mask(RawJs::make('$money($input, \',\', \' \')'))
                     ->formatStateUsing(fn (string $state): string => '12345.67') // <- '12345.67' as a string
                     ->stripCharacters([',','.',' ',])->numeric(),
```

**Comment by webthiagosilva** [comment]
> Recebi uma resposta lá. O valor deve ser enviado como uma string e não como um decimal. Então funciona conforme o esperado.
> 
> Portanto o código acima deveria ser:
> 
> ```
>             TextInput::make('any_column')
>                      ->mask(RawJs::make('$money($input, \',\', \' \')'))
>                      ->formatStateUsing(fn (string $state): string => '12345.67') // <- '12345.67' as a string
>                      ->stripCharacters([',','.',' ',])->numeric(),
> ```

It's good news, I'll test it and come back to let you know if everything went well!

**Comment by luiseduardobraschi** [comment]
I wanted it to work like [this](http://igorescobar.github.io/jQuery-Mask-Plugin/#money).

I ended up using `formatStateUsing`  and `afterStateUpdated`  with this helper function:

```PHP
function format_price_input($value)
{
    $value = preg_replace('/[^\d]/', '', $value);

    if(empty($value)){
        return '';
    }

    $currency = config('locale.currency', 'en');

    $money = Money::$currency(ltrim($value, '0'));
    $currencies = new ISOCurrencies;

    $formatter = get_number_formatter();

    $moneyFormatter = new IntlMoneyFormatter($formatter, $currencies);

    return $moneyFormatter->format($money);
}
```
and [moneyphp/Money](/moneyphp/Money).

**Comment by luiseduardobraschi** [comment]
I wanted it to work like [this](http://igorescobar.github.io/jQuery-Mask-Plugin/#money).

I ended up using `formatStateUsing`  and `afterStateUpdated`  with this helper function:

```PHP
function format_price_input($value)
{
    $value = preg_replace('/[^\d]/', '', $value);

    if(empty($value)){
        return '';
    }

    $currency = config('locale.currency', 'USD');

    $money = Money::$currency(ltrim($value, '0'));
    $currencies = new ISOCurrencies;

    $formatter = get_number_formatter();

    $moneyFormatter = new IntlMoneyFormatter($formatter, $currencies);

    return $moneyFormatter->format($money);
}
```
and [moneyphp/Money](/moneyphp/Money).

**Comment by pelmered** [comment]
> I wanted it to work like [this](http://igorescobar.github.io/jQuery-Mask-Plugin/#money).
> 
> I ended up using `formatStateUsing` and `afterStateUpdated` with this helper function:
> 
> ```
> function format_price_input($value)
> {
>     $value = preg_replace('/[^\d]/', '', $value);
> 
>     if(empty($value)){
>         return '';
>     }
> 
>     $currency = config('locale.currency', 'USD');
> 
>     $money = Money::$currency(ltrim($value, '0'));
>     $currencies = new ISOCurrencies;
> 
>     $formatter = get_number_formatter();
> 
>     $moneyFormatter = new IntlMoneyFormatter($formatter, $currencies);
> 
>     return $moneyFormatter->format($money);
> }
> ```
> 
> and [moneyphp/Money](/moneyphp/Money).

I actually have made a package for Money fields using MoneyPHP for filament. It was during the development of that I stumbled across this problem. 
Check it out here: https://github.com/pelmered/filament-money-field

`MoneyFormatter::format()` does pretty much the same thing as your helper there. See here: https://github.com/pelmered/filament-money-field/blob/main/src/MoneyFormatter.php#L15
I don't have that `preg_replace`, but maybe I should add that?

**Comment by luiseduardobraschi** [comment]
@pelmered Looks neat. I installed but I don't have much time to test.
Anyway, I think you would like to see this package by @leandrocfe:

[leandrocfe/filament-ptbr-form-fields](/leandrocfe/filament-ptbr-form-fields)

It looks like the money mask is a bit buggy, but they are working on it. I'm using one of the issues' "hacks" and it works exactly like my jQuery mask example above.

**Comment by luiseduardobraschi** [comment]
The exact snippet I'm using is this:

https://github.com/leandrocfe/filament-ptbr-form-fields/issues/15#issuecomment-1771939838

BTW, a native money input would be nice. And I think this is becoming much more of a thread for the "discussions" area than "issues."

**Comment by pelmered** [comment]
> The exact snippet I'm using is this:
> 
> https://github.com/leandrocfe/filament-ptbr-form-fields/issues/15#issuecomment-1771939838
> 
> BTW, a native money input would be nice. And I think this is becoming much more of a thread for the "discussions" area than "issues."

Thank you! That is an interesting solution. I will try something like that.
