### ISSUE TITLE
The table columns are not scrollable when there are a lot of columns to show/hide.

### ISSUE THREAD

**Issue by iyashpal** [laravel-filament/filament#10888]
### Package

filament/filament

### Package Version

v3.2.2

### Laravel Version

v10.41

### Livewire Version

v3.3.5

### PHP Version

PHP 8.2

### Problem description

1. I am working on a project and there is a resource that has a lot of table columns, and all are not required to be visible every time. So, I made some columns hidden but when I click on columns button the popup box goes out of the viewport and I am unable to scroll the hidden columns. This is happening in Resource Relation Manager table view.
 
<img width="563" alt="Screenshot 2024-01-18 at 8 34 48 AM" src="https://github.com/filamentphp/filament/assets/19922707/7cfff585-6aeb-4414-9565-43b0257d89f7">

2. Second is it will be great if the columns popup/popover has a fixed height and can be scrollable all the time. The reason is when there are a lot of columns it creates the whole page scrollable with empty space below the table records.
<img width="1512" alt="Screenshot 2024-01-18 at 8 51 53 AM" src="https://github.com/filamentphp/filament/assets/19922707/3cdd2ec9-dd5a-4885-a8db-1a7ab710b520">

![image](https://github.com/filamentphp/filament/assets/19922707/06a1f2b3-21f2-49d4-8e02-1f72f483542e)

3. When the dev tool is opened in Resource List View and the page scroll top is 0, the columns popup float placement goes to top and I am unable to scroll the columns, but when I scroll down popup float placement goes to bottom and I am able to see all the columns with the page scroll.
<img width="1512" alt="Screenshot 2024-01-18 at 9 04 17 AM" src="https://github.com/filamentphp/filament/assets/19922707/cb905a5b-6ac8-4388-b0c7-39df8165c03e">

### Expected behavior

The table columns popup/popover should be scrollable every where.

### Steps to reproduce

1. Setup a table fields having 30+ columns.
2. Setup the table fields in relation manager as well.
3. Click on columns icon to check/uncheck the columns.

### Reproduction repository

https://github.com/iyashpal/filamentphp-bug-reporting

**Comment by danharrin** [comment]
Please make a PR that adds a max height to the dropdown, and adds `overflow-y-auto`

**Comment by danharrin** [comment]
https://github.com/filamentphp/filament/pull/10902#issuecomment-1898709489
