### ISSUE TITLE
Method Filament\Forms\Components\Select::disablePlaceholderSelection does not exist

### ISSUE THREAD

**Issue by coinrese** [laravel-filament/filament#1089]
### Package

filament/forms

### Package Version

v2.7.3

### Laravel Version

v8.77.1

### Livewire Version

v2.8.2

### PHP Version

PHP 8.0.11

### Bug description

Defined a select field using the disablePlaceholderSelection() method but it returns a BadMethodCallException

### Steps to reproduce

Define a select as per the example in the docs

```
Select::make('status')
    ->options([
        'draft' => 'Draft',
        'review' => 'In review',
        'published' => 'Published',
    ])
    ->default('draft')
    ->disablePlaceholderSelection()
```

**Comment by danharrin** [comment]
Hey, make sure you're on the latest version. This method was added very recently.

**Comment by coinrese** [comment]
Thanks, the method works after updating to the latest version but it makes for an unusual behaviour.

Once the placeholder is removed from the list the first option is selected but it wont be submitted when saving the form. In order to select/submit the first option you must open the dropdown select an alternative option and then go back and select the first option. 

I've tried setting the first option as a default but it didn't fix the issue.

**Comment by danharrin** [comment]
What did you try with `default()`?
