### ISSUE TITLE
Design of form wizard with many steps

### ISSUE THREAD

**Issue by AhmadFida2** [laravel-filament/filament#10903]
### Package

filament/filament

### Package Version

v3.2.3

### Laravel Version

v10.41.0

### Livewire Version

v3.3.5

### PHP Version

PHP 8.3.2

### Problem description

Form Wizard Steps header UI overflows and becomes hidden if it has many steps. This confuses the end user as steps keep appearing on clicking Next button but no steps showing on Steps Header.

### Expected behavior

The header should move to second row and remain within container of the wizard. 

### Steps to reproduce

Just runt the given repo app. Goto Test resource and try to add a new resource. It will show wizards steps header broken.

### Reproduction repository

https://github.com/AhmadFida2/filament-wizard-issue

**Comment by AhmadFida2** [comment]
I have added a resource with Form having 12 Steps and nothing else. You can have a look at UI.

**Comment by AhmadFida2** [comment]
Even if you make column span Full, the steps still overflow out of bounds of desktop.

**Comment by AhmadFida2** [comment]
![image](https://github.com/filamentphp/filament/assets/154905529/be7f474a-8acf-4eb4-a88a-65954683a5e0)

**Comment by zepfietje** [comment]
The solution here is probably to use the mobile design at a certain container size (CSS container queries). It's hard to get that right for every case though, as using a large number of steps will result in a bad design while it would work just fine with 3 steps for example. Thoughts, @AhmadFida2 @danharrin?

**Comment by danharrin** [comment]
Container queries, combined with making the steps container horizontally scrollable when it overflows

**Comment by AhmadFida2** [comment]
Horizontal Scrolling should be there as it is in Tabs.

**Comment by lukas-frey** [comment]
Also, could the text be left-aligned instead of center (at least on desktop)? If you also enter a `description` for each step and it gets split among multiple lines (as also seen in the example), it doesn't look good.

**Comment by zepfietje** [comment]
Feel free to create a pull request fixing that, @lukas-frey.
