### ISSUE TITLE
initially hidden Repeater field error

### ISSUE THREAD

**Issue by AmirJavaidSwe** [laravel-filament/filament#1091]
### Package

filament/filament

### Package Version

v2.7.3

### Laravel Version

v8.77.1

### Livewire Version

v2.8.2

### PHP Version

PHP 8.0.9

### Bug description

```
Forms\Components\Radio::make('has_skills')
->label('Do you have any skills')
->required()
->reactive()
->boolean(),


Forms\Components\Repeater::make('skills')->schema([
    Forms\Components\TextInput::make('skill_name')
    ->label("Skill"),
])
->hidden(fn (Closure $get) => (int) $get('has_skills') !== 1)
->defaultItems(1)
```

this is my code for making a repeater field, but initially hidden, but I am getting this error when  I am trying to use the above code

![image](https://user-images.githubusercontent.com/41790096/147848032-dbc3efa6-8e0c-4ddc-966c-0f39f89adcaa.png)

**Comment by danharrin** [comment]
Fixed by #1094.
