### ISSUE TITLE
Filament Export Action Queue Issue

### ISSUE THREAD

**Issue by Umar-Farooq-Shafi** [laravel-filament/filament#10939]
### Package

filament/filament

### Package Version

v3.2.6

### Laravel Version

v10.41.0

### Livewire Version

v3.3.5

### PHP Version

8.2

### Problem description

When Export the file the ` Illuminate\Bus\ChainedBatch` keep running

`Illuminate\Bus\ChainedBatch.................................................... RUNNING`

### Expected behavior

Export the file successfully

### Steps to reproduce

```
ExportBulkAction::make()
                    ->label('Export')
                    ->icon('heroicon-o-arrow-down-tray')
                    ->color('primary')
                    ->modalHidden(true)
                    ->exporter(UserExporter::class),
```

UserExporter
```
<?php

namespace App\Filament\Exports;

use App\Models\User\User;
use Filament\Actions\Exports\ExportColumn;
use Filament\Actions\Exports\Exporter;
use Filament\Actions\Exports\Models\Export;

class UserExporter extends Exporter
{
    protected static ?string $model = User::class;

    public static function getColumns(): array
    {
        return [
            ExportColumn::make('name'),
        ];
    }

    public static function getCompletedNotificationBody(Export $export): string
    {
        $body = 'Your user export has completed and '.number_format($export->successful_rows).' '.str('row')->plural($export->successful_rows).' exported.';

        if ($failedRowsCount = $export->getFailedRowsCount()) {
            $body .= ' '.number_format($failedRowsCount).' '.str('row')->plural($failedRowsCount).' failed to export.';
        }

        return $body;
    }
}
```

### Reproduction repository

https://github.com/Umar-Farooq-Shafi/filament-export-action

**Comment by danharrin** [comment]
What is Laravel v10.41.0? The latest is v10.3.2. You need to be on the latest version to use the exports feature, as chained batches are a relatively new feature.

**Comment by rthomas023** [comment]
Hi,

I'm not sure if this is related or not, but I have what might be a similar issue.

I am running Filament v3.2.6 and I have defined an export action for a resource and the job is sent to the queue just fine. I can see the jobs in Horizon, but I get the following error:

Illuminate\Database\Eloquent\ModelNotFoundException: No query results for model [Filament\Actions\Exports\Models\Export]

This used to work, up until a few days ago when I was running a version slightly older than v3.2.6. I believe I was running 3.2.2 or 3.2.4 - as I tend to update quite a bit as I am still in development.

I see the record in the exports table just fine, but the export file is never created and then of course, there is not a corresponding record in the notifications table.

If there is anything else I can provide, please let me know!

Thank you!

Rick

**Comment by danharrin** [comment]
It probably is going to be a separate problem, so setting up a new issue and a reproduction repository will help me fix it in the least time

**Comment by danharrin** [comment]
I need more info to be able to fix the issue. I downloaded your repository, and tested it with both sync & Redis connections. It worked both times:

https://github.com/filamentphp/filament/assets/41773797/3f266a99-dd37-4092-bb9d-5e8f048beb5b

**Comment by Umar-Farooq-Shafi** [comment]
`$this->app->bind(Authenticatable::class, User::class)`
that was the issue. thanks @danharrin

**Comment by Umar-Farooq-Shafi** [comment]
@danharrin Is there a way to add the same functionality 

https://filamentphp.com/plugins/pxlrbt-excel

The issue is it's too slow and does not use of batch jobs and `Laravel-Excel` is slow

**Comment by danharrin** [comment]
Filament's ExportAction does heavily use batched jobs, and what functionality are you looking for?

**Comment by danharrin** [comment]
pxlrbt-excel uses Laravel Excel

**Comment by Umar-Farooq-Shafi** [comment]
@danharrin like Custom Query, do not export the column that are headen.
Instead of using exporter class
Only export the data that are in the current table as I'm using single model on different places.

**Comment by danharrin** [comment]
You can have multiple exporters, one for each table if you want. We have chosen this structure as there is less "magic" involved, and it can be completely decoupled from the table definition. If we used the table definition within the export jobs, then the export process would be slower, since we'd have to instantiate a Livewire component in the queue and extract the data from it.

I'd accept a PR that allowed you to pass a custom `->query()` into the ExportAction.

**Comment by Umar-Farooq-Shafi** [comment]
How I can manage the columns that are hidden and Table Filters?

**Comment by danharrin** [comment]
Table filters are applied to the query automatically. Columns can be hidden by conditionally returning them from `getColumns()` based on `auth()->user()`.

**Comment by Umar-Farooq-Shafi** [comment]
getting error while downloading the file.

<img width="1440" alt="Screen Shot 2024-01-20 at 10 48 15 PM" src="https://github.com/filamentphp/filament/assets/62417503/cf628f1d-d529-442c-aa34-5b2c9f9a5bc5">

**Comment by Umar-Farooq-Shafi** [comment]
Is there a way to download just CSV file only?

<img width="430" alt="Screen Shot 2024-01-20 at 10 51 23 PM" src="https://github.com/filamentphp/filament/assets/62417503/23fb9273-e0ac-4356-9478-c4d1b49787f4">

**Comment by danharrin** [comment]
You can PR an option to remove XLSX if you want it

For the Not Found, make sure your APP_URL is correct.

**Comment by Umar-Farooq-Shafi** [comment]
thanks @danharrin

**Comment by mohammadapr** [comment]
Filamat version 3.2. The Excel output I receive has its permission set to root, preventing users from downloading it. We haven't found a solution yet. I've tried commands like chmod 777 and chown www-data, but they didn't work. Do you have any solutions?

**Comment by danharrin** [comment]
A proper disk like S3 should solve file perms issues?

**Comment by joao-antonio-gomes** [comment]
I'm trying to chain a job who will send the report to user email, and then another job who will delete the sended report from storage

PrepareExportJob -> SendReportJob -> DeleteFileJob

However, when SendReportJob is loading file from storage throw an error because cant find the xlsx report, this happens because the xlsx takes more time to write on the storage than SendReportJob takes to run
How can I achieve to wait for xlsx be writed on local before send mail?

**Comment by Umar-Farooq-Shafi** [comment]
@joao-antonio-gomes maybe add some delay to `SendReportJob`?

**Comment by mohammadapr** [comment]
> A proper disk like S3 should solve file perms issues?

thank you, this solution worked but i want store in storage folder

**Comment by byiringirofabrice** [comment]
![Screenshot 2024-08-27 000221](https://github.com/user-attachments/assets/7b2afd66-b9ad-41fb-9c79-ca8fbe4012e0)
![Screenshot 2024-08-27 000340](https://github.com/user-attachments/assets/8315f3a9-aeb7-46e7-9a08-7be6679a6b02)
I have make  export but nothing shows to notification

**Comment by fachryansyah** [comment]
I got same error, filament always create with root permission, prevent user to download it.
<img width="791" alt="Screenshot 2024-11-16 at 01 18 01" src="https://github.com/user-attachments/assets/3a15882e-2d4c-4cda-acf4-3aabb5e0d6e0">

I'm already modify the filesystem.php like this
```php
'export' => [ // Custom disk for exports
            'driver' => 'local',
            'root' => storage_path('app/public/exports'),
            'url' => env('APP_URL') . '/exports',
            'visibility' => 'public',
            'permissions' => [
                'file' => [
                    'public' => 0644,
                    'private' => 0600,
                ],
                'dir' => [
                    'public' => 0755,
                    'private' => 0700,
                ],
            ],
            'throw' => false,
        ],
```
But the filament still uses root in file permissions.

**Comment by fachryansyah** [comment]
I found away to solve "filament always create with root permission" @mohammadapr @danharrin (but unsafe). Just modify this file inside vendor filament folder
<img width="645" alt="Screenshot 2024-11-16 at 01 28 51" src="https://github.com/user-attachments/assets/d78ec7d5-7786-468c-9417-23abd55ad9c7">
you can change the visibility to public. 

Can I patch this code to add some flexibility so developers can adjust the permissions?

**Comment by danharrin** [comment]
Export files do not need to be directly accessible as far as I know, we stream the downloads from the filesystem. If they do not stream, open that as an issue with a reproduction repository and we will look into it. I am not open to a PR making these files get stored publicly.

**Comment by fachryansyah** [comment]
> Export files do not need to be directly accessible as far as I know, we stream the downloads from the filesystem. If they do not stream, open that as an issue with a reproduction repository and we will look into it. I am not open to a PR making these files get stored publicly.

Thats true, the downloader files will stream from the filesystem, no matter the permission is root / not.
Idk why, when I download the exported file got this error
```
[2024-11-15 17:58:25] production.ERROR: fpassthru(): Argument #1 ($stream) must be of type resource, null given {"userId":1,"exception":"[object] (TypeError(code: 0): fpassthru(): Argument #1 ($stream) must be of type resource, null given at /vendor/laravel/framework/src/Illuminate/Filesystem/FilesystemAdapter.php:309
```
And I tried changing the permission from 600 to 644. It works perfectly.

Edit:
Changing the file permissions from 600 to 644 will solve the issue, but when you export again, it will revert to 600.

**Comment by fachryansyah** [comment]
So this is my temporary solution without modify the vendor files, add new disks with private permission from 600 to 644
```php
'export' => [ // Custom disk for exports
            'driver' => 'local',
            'root' => storage_path('app/public/exports'),
            'url' => env('APP_URL') . '/exports',
            'visibility' => 'public',
            'permissions' => [
                'file' => [
                    'public' => 0644,
                    'private' => 0644, // from my pervious config 600 change to 644
                ],
                'dir' => [
                    'public' => 0755,
                    'private' => 0700,
                ],
            ],
            'throw' => false,
        ],
```

**Comment by danharrin** [comment]
I think this is a server issue on your end and not to do with the code in Filament, we just use Laravel's filesystem helpers.

**Comment by hagiik** [comment]
> I need more info to be able to fix the issue. I downloaded your repository, and tested it with both sync & Redis connections. It worked both times:
> 
>  Screen.Recording.2024-01-20.at.16.10.23.mp4

why does it take so long to get the download file, even when on hosting I have to run queue:work to see the process. how to run behind the server without having to do that?

**Comment by hagiik** [comment]
> I need more info to be able to fix the issue. I downloaded your repository, and tested it with both sync & Redis connections. It worked both times:
> 
>  Screen.Recording.2024-01-20.at.16.10.23.mp4

why does it take so long to get the download file, even when on hosting I have to run queue:work to see the process. how to run behind the server without having to do that?

**Comment by Heyosseus** [comment]
> ![Screenshot 2024-08-27 000221](https://private-user-images.githubusercontent.com/128990682/361589194-7b2afd66-b9ad-41fb-9c79-ca8fbe4012e0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0NDM1MjcsIm5iZiI6MTczNjQ0MzIyNywicGF0aCI6Ii8xMjg5OTA2ODIvMzYxNTg5MTk0LTdiMmFmZDY2LWI5YWQtNDFmYi05Yzc5LWNhOGZiZTQwMTJlMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOVQxNzIwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kMjVmN2ExOWViOTNkMjQyZmM1OTM2YjBkZTYzOGFhMjAzOTE2YzAyYTBkOTBlODZkODQ5ZDFjOTBhZTRhNjQyJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nF-3a_R1kL1wf0ig0sT3H6nH9aAO6iDFSopVDXVsUoc) ![Screenshot 2024-08-27 000340](https://private-user-images.githubusercontent.com/128990682/361589678-8315f3a9-aeb7-46e7-9a08-7be6679a6b02.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzY0NDM1MjcsIm5iZiI6MTczNjQ0MzIyNywicGF0aCI6Ii8xMjg5OTA2ODIvMzYxNTg5Njc4LTgzMTVmM2E5LWFlYjctNDZlNy05YTA4LTdiZTY2NzlhNmIwMi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjUwMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI1MDEwOVQxNzIwMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNzMyM2JmMjQyM2I5N2Y1YWIzNTYyZGJlNzAxZGIyOTdjYmNlZjY5NzQyMTBlYzkyN2QyYTk5NTg2OWFhMzFhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.SFr_hGB0Ma1m-XJO87tzwVQUK_0JkFqTXNLU9Ay3Sgs) I have make export but nothing shows to notification

You should add ->databaseNotifications() in the AdminPanelProvider.  Also make sure to run php artisan queue:work if you have QUEUE_CONNECTION=database in the .env and then it will normally display in the notifications.

**Comment by makuguren** [comment]
> ![Screenshot 2024-08-27 000221](https://github.com/user-attachments/assets/7b2afd66-b9ad-41fb-9c79-ca8fbe4012e0) ![Screenshot 2024-08-27 000340](https://github.com/user-attachments/assets/8315f3a9-aeb7-46e7-9a08-7be6679a6b02) I have make export but nothing shows to notification

I have also the same error

**Comment by danharrin** [comment]
Make sure your queue is running.

**Comment by MaapTom** [comment]
> Make sure your queue is running.

Why doesn't it work when I simply run _php artisan serve_? Is there a way for laravel to still be running the queue without setting this command individually?

**Comment by danharrin** [comment]
Set the queue driver to be `sync`. At that point it is no longer a queue. The whole point of the queue is to run the process in the background.

**Comment by MaapTom** [comment]
> Set the queue driver to be `sync`. At that point it is no longer a queue. The whole point of the queue is to run the process in the background.

Cool, it work. Really thanks!

**Comment by kofiarkoh** [comment]
@danharrin ,

setting to queue driver to `sync` works for me but setting it to `database` fails even when the queue is started. do you know possible cause?
