### ISSUE TITLE
Import / Export actions break if User model has a binary column

### ISSUE THREAD

**Issue by binaryfire** [laravel-filament/filament#10953]
### Package

filament/filament

### Package Version

3.2.5

### Laravel Version

10.41.0

### Livewire Version

3.3.5

### PHP Version

8.3

### Problem description

Import / Export actions break when the User model has a binary column (eg. like the one added by [michaeldyrynda/laravel-efficient-uuid](https://github.com/michaeldyrynda/laravel-efficient-uuid). It causes the following exception:
<img width="820" alt="image" src="https://github.com/filamentphp/filament/assets/5361908/4900d198-2463-4cc8-a1bf-6a0ca17a4612">

I'm guessing this is because the User model is being serialized before casts are applied? In which case the value of binary columns would be a bunch of garbage characters. The `exports` and `imports` tables only store the user_id so perhaps you could just pass in the id rather than serializing the whole model?

### Expected behavior

Import and export actions should work regardless of the types of columns present.

### Steps to reproduce

Install reproduction repository, go to the Product resource, create a couple of products, then try exporting. The repo uses `michaeldyrynda/laravel-efficient-uuid` to demonstrate the issue but it happens with any binary columns.

### Reproduction repository

https://github.com/binaryfire/filament-import-export-bug

**Comment by danharrin** [comment]
Overriding `jsonSerialize()` on the model to remove the binary column should be a universal solution to this problem

**Comment by binaryfire** [comment]
Doesn't help unfortunately. I'm still getting an exception even when the binary column isn't included:

    public function jsonSerialize(): mixed
    {
        return [
            'id' => $this->id,
            'full_name' => $this->full_name,
            'email' => $this->email,
            'email_verified_at' => $this->email_verified_at,
            'created_at' => $this->created_at,
            'updated_at' => $this->updated_at,
        ];
    }
    
If it was an issue at this point in the stack I'd be getting a `JsonEncodingException` ([see this](https://github.com/illuminate/database/blob/6c33ca6a6f9b7bcc7c66f0fb9f671c35c7105d7b/Eloquent/Model.php#L1657))

But I'm getting an `InvalidPayloadException` so it's happening somewhere else.

**Comment by danharrin** [comment]
Can you also override `toArray()` please?

**Comment by danharrin** [comment]
It's not possible to simply JSON encode an object, so Laravel must be converting it into an array at some point first, which is where we need to catch it

**Comment by binaryfire** [comment]
No luck with that either.

If I `dd($user)` in `CanExportRecords` I get this:
<img width="334" alt="image" src="https://github.com/filamentphp/filament/assets/5361908/32a63b63-ccb4-4f17-9a3f-a474aa8faee6">

And if I `dd($export)`:
<img width="446" alt="image" src="https://github.com/filamentphp/filament/assets/5361908/4b253964-8ff2-42ff-aa62-0bcb6ed4eced">

So it's definitely the authenticated user that's causing the issue. 

The above dumps are with both `jsonSerialize()` and `toArray()` overridden on the `User` model to exclude `uuid`. But I don't think `auth()->user()` involves either of those methods? It just returns the unmodified model instance right?

**Comment by danharrin** [comment]
Dumping out a model does not serialise it into JSON or an array, so that is expected

**Comment by binaryfire** [comment]
[This](https://github.com/laravel/framework/blob/fb9d508f62690dbbfc44150dd2831c4bc1412f83/src/Illuminate/Queue/Queue.php#L107) is where it falls over.

If I `dd($this->createPayloadArray($job, $queue, $data))` I see this in the result:
`attributes";a:9:{s:2:"id";i:1;s:4:"uuid";s:16:"qpÞ¸ø#F§½éUšÎ(Ø` (the characters from the uncast binary column).

`createPayloadArray()` calls [`createObjectPayload()`](https://github.com/laravel/framework/blob/fb9d508f62690dbbfc44150dd2831c4bc1412f83/src/Illuminate/Queue/Queue.php#L140) which just includes the unmodified `$job` in `data`.

Would it be easier to just pass the user's primary key and model class name to the job rather than the model / relation? That would also avoid having to pass around sensitive data like `remember_token` and any other sensitive attributes that have been added to the model, which is better for security.

**Comment by danharrin** [comment]
We don't pass the user to the job, its only there as its set as a relationship. We just need to unset that relationship before passing it to the job

**Comment by danharrin** [comment]
4cd2b114e40559eab6816466945e4c1edb338703

**Comment by binaryfire** [comment]
@danharrin Thanks, really appreciate the fix. Works perfectly now!
