### ISSUE TITLE
ImportColumn is always required in the 3.2.7

### ISSUE THREAD

**Issue by sandersjj** [laravel-filament/filament#10960]
### Package

filament/filament

### Package Version

v3.2.7

### Laravel Version

v10.41.0

### PHP Version

PHP 8.2.15

### Problem description

Since v3.2.7 all `ImportColumn` are required. This broke in V3.2.7 since in v3.2.6 it still works. 

```php
            ImportColumn::make('item_code')
                ->requiredMapping()
                ->label('Artikelcode')
                ->example('ABC123')
                ->rules(['required', 'string', 'max:255']),
            ImportColumn::make('supplier_code')
                ->label('Leveranciercode')
                ->example('ABC123'),
```

In this example the first column should be required which it is but the second shouldn't. However the UI marks it as required:

![Screenshot 2024-01-21 at 10 46 42](https://github.com/filamentphp/filament/assets/176772/dba2c064-6695-4537-b7a5-f31beae56625)

### Expected behavior

The first column should be required and the second one shouldn't be. 

### Steps to reproduce

1. See reproduction repo
2. Go to `/admin/products`
3. Click `importeer producten`
4. Try any csv
5. You will see both fields are required. 

### Reproduction repository

https://github.com/sandersjj/import-issue

**Comment by danharrin** [comment]
Fixed by #10957
