### ISSUE TITLE
in component SpatieMediaLibraryFileUpload methods disk and directory not work

### ISSUE THREAD

**Issue by farhad321** [laravel-filament/filament#1098]
### Package

filament/spatie-laravel-media-library-plugin

### Package Version

v2.6.5

### Laravel Version

8.77.1

### Livewire Version

 v2.8.2

### PHP Version

8.0.3

### Bug description

hello 
thank you for this package

in component SpatieMediaLibraryFileUpload
methods disk and directory not work and 
file store only in storage/app/public 

I want to folder to a specific path
![Untitled22222222222](https://user-images.githubusercontent.com/9474884/147859081-742fac5a-7519-4220-9110-c83bf406c756.png)

**Comment by danharrin** [comment]
Hi, as far as I know the original media library package does not support custom disks and directories in the same way as normal uploads. I think the media disk can be configured through Spatie's config file.

**Comment by robertorinaldi-dev** [comment]
Actually it seems possible to set disk together with collection https://spatie.be/docs/laravel-medialibrary/v9/advanced-usage/working-with-multiple-filesystems

**Comment by danharrin** [comment]
> Actually it seems possible to set disk together with collection https://spatie.be/docs/laravel-medialibrary/v9/advanced-usage/working-with-multiple-filesystems

Cool, I've fixed the disk thing in the next release. However, that doesn't cover `directory()`.

**Comment by VladimirVM** [comment]
Directory can changed in file config/media-library.php
Set custom "path_generator"
`'path_generator' => PathGenerator\MyPathGenerator::class,`
