### ISSUE TITLE
Problem with multi select when using keyboard

### ISSUE THREAD

**Issue by lolen** [laravel-filament/filament#1099]
### Package

filament/forms

### Package Version

v2.7.15

### Laravel Version

v8.77.1

### Livewire Version

v2.8.2

### PHP Version

PHP 8.0.13

### Bug description

Problems arise when we want to use the multiselect field only with the keyboard. We approve the first result with enter, but the next result is not shown in the list. If we click outside the element and back into the field, everything will be back to normal.
![chrome-capture](https://user-images.githubusercontent.com/3825268/147861628-c44b7227-f0c2-426d-b33a-1f2bde24a35c.gif)
 

### Steps to reproduce

```
Forms\Components\MultiSelect::make('technologies')
->options([
    'tailwind' => 'TailwindCSS',
    'alpine' => 'Alpine.js',
    'laravel' => 'Laravel',
    'livewire' => 'Laravel Livewire',
]),
```

**Comment by danharrin** [comment]
Should be fixed by #1101 - let me know. Make sure to clear your view cache.
