### ISSUE TITLE
Syntax error or access violation

### ISSUE THREAD

**Issue by Diddyy** [laravel-filament/filament#11]
Hey! 

Awesome package!
Although out of the box navigating to the 'permissions' tab (/filament/permissions) I'm presented with this error

```SQLSTATE[42000]: Syntax error or access violation: 1055 'mcpro.permissions.name' isn't in GROUP BY (SQL: select count(*) as aggregate from (select `permissions`.* from `permissions` group by `permissions`.`id`) as `permissions`) (View: /Users/josh/code/mcpro/vendor/livewire/livewire/src/Macros/livewire-view.blade.php)```

Not looked into it yet, if I grab a chance I'll see if I can chuck together a PR to fix this!

**Comment by Diddyy** [comment]
It seems to get round this you have to update `mysql` in config/database.php from
`'strict' => true,` to `'strict' => false,`

**Comment by ryanscherler** [comment]
Hi @Diddyy - glad to hear you like the package!

I would definitely appreciate the PR on this. 

** I also likely need to re-write the [file-upload field package](https://github.com/laravel-filament/field-file) - If youre up for it would you wanna take a crack at that too?

Thanks and talk soon,

**Comment by ryanscherler** [comment]
Closing this issue and moving this repository to a **read-only** state in favor of using [Laravel Jetstream](https://jetstream.laravel.com) for bootstrapping new applications.
