### ISSUE TITLE
Export sort by column other ID causes an incorrect amount of rows exported

### ISSUE THREAD

**Issue by WayneHarris** [laravel-filament/filament#11006]
### Package

filament/filament

### Package Version

v3.2.10

### Laravel Version

v.10.40

### Livewire Version

v.3.3.0

### PHP Version

PHP 8.3

### Problem description

If a ```defaultSort``` is set on a resource table using a column other than ID, large data exports will miss rows in the export due to the chunks returned from ```orderedChunkById```

This seems it may make sense, as  ```orderedChunkById```is either ordered by ID ascending or descending and assumes that if you add an order by "created", the query does not work. 

If confirmed, a possible resolution would be to switch methods between ```orderedChunkById``` and  ```chunk``` if a sort other than ID is in the query. Although this comes with some concerns, as noted https://laravel.com/docs/10.x/queries#chunking-results

"If you are updating database records while chunking results, your chunk results could change in unexpected ways. If you plan to update the retrieved records while chunking, it is always best to use the chunkById method instead. This method will automatically paginate the results based on the record's primary key."

I've added an updated branch of the filament demo, which updates the seeder to include only one user and a more significant number of brands and updated the brand resource default sort to ```created_at```. Due to the export volume, you will likely need to update the queue settings from sync to a driver to run Horizon.

https://github.com/WayneHarris/filamentdemo/pull/1

### Expected behavior

Exports should include the same amount of rows and export total rows

### Steps to reproduce

On a larger data set, into 10s of thousands, create a resource table with a default sort of "created_at" "desc".

### Reproduction repository

https://github.com/WayneHarris/filamentdemo/tree/issue/export-with-other-column-sort

**Comment by WayneHarris** [comment]
Hey, @danharrin I think there is still some issue with the ```order by``` on large exports, as noted on the issue. I will look into this further to see what could be done to resolve it, but if you are able to confirm the issue in case I am missing something obvious.

**Comment by danharrin** [comment]
Switched to `chunk()` in non-ID cases in #11108
