### ISSUE TITLE
The input for selecting the chart filter is truncated

### ISSUE THREAD

**Issue by lamberttraccard** [laravel-filament/filament#11015]
### Package

filament/filament

### Package Version

v3.2.11

### Laravel Version

v10.42.0

### Livewire Version

v3.3.3

### PHP Version

PHP 8.2

### Problem description

The input for selecting the chart filter is truncated. Issue introduced in https://github.com/filamentphp/filament/commit/36a1aa72abe7878293ad4dece334b4b79dab9f37

![CleanShot 2024-01-23 at 21 34 27@2x](https://github.com/filamentphp/filament/assets/4272598/39dd5faa-cd5a-4074-805b-ac42e9e52236)

### Expected behavior

The input should render properly and not be truncated.

### Steps to reproduce

Go to the dashboard page.

### Reproduction repository

https://github.com/lamberttraccard/filament-issue/tree/fix-chart-filter

**Comment by zepfietje** [comment]
Thanks for reporting!

Fixed by https://github.com/filamentphp/filament/commit/86f5196982775fd258257aa12921512c2ee5074c.
