### ISSUE TITLE
Dynamic TextInput don't fill

### ISSUE THREAD

**Issue by OlyaK95** [laravel-filament/filament#11029]
### Package

filament/filament

### Package Version

3.2.11

### Laravel Version

10.42.0

### PHP Version

8.2.8

### Problem description

I have a custom page with dynamic form. When I click on select, I want to choose some `ModuleType` and view `Elements` of this `ModuleType`.
But TextInput's fills only when I have default state on Select.

```
Select::make("id")
    ->label("Module Type")
    ->required()
    ->options(function () {
        return ModuleType::all()->pluck("full_name", "id");
    })
    ->default(1)
    ->live()
    ->searchable()
    ->preload(),
```
With default state:
![image](https://github.com/filamentphp/filament/assets/129214474/ebd1a8b1-5767-4603-83ab-695d672559b1)

Without default state:
![image](https://github.com/filamentphp/filament/assets/129214474/fa0c5276-01d7-4dfe-ba85-177ff5c0a04d)

### Expected behavior

TextInput's must fills with data.

### Steps to reproduce

- git clone https://github.com/OlyaK95/livewire-check-elements.git
- cd livewire-check-elements
- composer install
- npm install
- cp .env.example .env
- php artisan key:generate
- set database at .env file
- php artisan migrate
- npm run build
- open local server
- login with username `admin@filament.test` and password `qwerty`
- go to CheckElements page

### Reproduction repository

https://github.com/OlyaK95/livewire-check-elements.git

**Comment by zepfietje** [comment]
[`$set()`](https://filamentphp.com/docs/3.x/forms/advanced#injecting-a-function-to-set-the-state-of-another-field) in `afterStateUpdated()` is probably what you're looking for.

**Comment by OlyaK95** [comment]
@zepfietje Can you tell me where I need to use `$set()` in `afterStateUpdated()`? I replaced all `default()` with `$set()` but nothing changes.

**Comment by OlyaK95** [comment]
@danharrin Hi! I know that you can answer on any question because you are genius) Can you spend ten minutes on my question?
