### ISSUE TITLE
/livewire/livewire.js  net::ERR_ABORTED 404 (Not Found)

### ISSUE THREAD

**Issue by Pok09** [laravel-filament/filament#11058]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

10.10

### PHP Version

PHP 8.3.0

### Problem description

When I put the project on a live server I get this error and authentication does not work

`https://.../livewire/livewire.js?id=5eee0fac net::ERR_ABORTED 404 (Not Found)`

I even tried with a fresh install of Laravel and Filament php, without anything else, (

the problem remains the same

### Expected behavior

Authentication work

### Steps to reproduce

Install Laravel
Install Filament
run

on live server

### Reproduction repository

RAS

**Comment by Cleverscript** [comment]
configure your host in NGINX

[livewire.js and app.js 404](https://laracasts.com/discuss/channels/vite/problem-with-site-in-proudcction-livewirejs-and-appjs-404)

`location ~* \.(jpg|jpeg|gif|png|webp|svg|woff|woff2|ttf|css|js|ico|xml)$ {
       try_files $uri /index.php?$query_string;
       access_log off;
       log_not_found off;
       expires 14d;
}`

**Comment by babacarcissedia** [comment]
Made my day today. I was missing the `try_files` block
