### ISSUE TITLE
Issue with checkbox list and multiselect dropdown reactive

### ISSUE THREAD

**Issue by AmirJavaidSwe** [laravel-filament/filament#1106]
### Package

filament/filament

### Package Version

v2.7.17

### Laravel Version

v8.77.1

### Livewire Version

v2.8.2

### PHP Version

PHP 8.0,.9

### Bug description

So, I found one more issue with the checkbox list and multi-select
in the checkbox list even if I click any of the checkboxes it has been making checked all of them
and on clicking again one it is unchecking them all

and in multi-select
when I don't use reactive property/method with it, then it is working fine but when I use reactive it is throwing some error
I am attaching the video please go through

https://user-images.githubusercontent.com/41790096/147877647-8501f696-0880-46e2-b155-ec7517177345.mp4

**Comment by danharrin** [comment]
I'm guessing this is fixed in #1112, but your video is broken so I can't really check.
