### ISSUE TITLE
KeyValue form component erase values when entering new matching key

### ISSUE THREAD

**Issue by telkins** [laravel-filament/filament#1107]
### Package

filament/filament

### Package Version

v2.7.14

### Laravel Version

v8.77.1

### Livewire Version

v2.8.2

### PHP Version

8.1.0

### Bug description

The KeyValue form component seems to erase values when entering a new key if it matches a pre-existing key...even if you're not yet done typing.

### Steps to reproduce

Let's say I have an array that already has `'key' => 'value'` and I add a new row to add another set: `'key_code' => 'abc123'`.

Once I start to type the new key in, as soon as it matches the existing key, it clears the existing value and clears out the new row.

**Comment by danharrin** [comment]
Fixed by #1113.
