### ISSUE TITLE
Excessive queries with import / export jobs

### ISSUE THREAD

**Issue by binaryfire** [laravel-filament/filament#11077]
### Package

filament/filament

### Package Version

v3.2.14

### Laravel Version

v10.42.0

### Livewire Version

v3.4.1

### PHP Version

8.3

### Problem description

While investigating https://github.com/filamentphp/filament/issues/10953 I discovered Filament's Import and Export jobs have the "n+1-esque" problem that is described here:

https://www.youtube.com/watch?v=SDHNacIrqhI

https://subscribe.mateusguimaraes.com/posts/scaling-laravel-to-30-000-requests-sec-and-over-100m-jobs

From the Mateus's article:
> Regarding Laravel Horizon, one important thing: the jobs needed to be dumb. Real dumb.
> I'm used to passing models as arguments to jobs — Laravel handles that extraordinarily by deserializing the model, passing it to the job and then serializing it on the queue worker. When that happens, the record is fetched from the database: a query is executed. Now imagine doing one query to fetch each outgoing message.
> 
> This is definitely something I did not want, so the jobs had to be as dumb as possible in what relates to the database — all the necessary arguments were passed directly from the account handler job, so by the time it was executed it already knew all it had to.
> No need to pass a List instance to a job if all it needs is the list_id — just pass "int $listId" instead.

Here's what's happening in Filament when I export multiple products in the reproduction repo:

<img width="917" alt="image" src="https://github.com/filamentphp/filament/assets/5361908/1837b49f-573a-44bb-a75b-a74c9a3ad94c">

The same 2 models (`User` and `Export`) are being repeatedly retrieved from the db. This is probably fine for single-tenant applications but it will cause major issues in multi-tenant apps. Imagine a multi-tenant with 4 queue workers where 30 tenants each exported 10k+ records simultaneously. The db load would already be pretty significant, but retrieving the `Import` / `Export` and `User` model each time will 3x that load.

What about just passing in the user's id, and an array of the data necessary for the import / export to run? Could also base64 encode that data, although that increases the size by about 33%.

As a side effect, solving this will also solve https://github.com/filamentphp/filament/issues/10953

### Expected behavior

Any data that is the same for each job should only be retrieved once from the database.

### Steps to reproduce

1. Install the reproduction repo. Be sure the use the `.env.example` file (or `QUEUE_CONNECTION=database`).
2. Start a queue worker
3. Navigate to the Products resource and create a few products
4. Run the Export action
5. Visit `localhost:8000/telescope` to view the queries

### Reproduction repository

https://github.com/binaryfire/filament-job-queries

**Comment by binaryfire** [comment]
Happy to work on a PR, just want to agree on an approach first.

**Comment by binaryfire** [comment]
Oops. After digging into the code I realised the Import / Export models keep track of the current number of `processed_rows`. So of course they need to be queried for each batch. So I guess there's not much more than can be optimized here?

**Comment by danharrin** [comment]
Yeah, not much that can be optimised. But increasing the chunk size (cautiously) will allow you to reduce the number of jobs that get dispatched & the number of queries run

**Comment by juliancc** [comment]
I'm running on an issue of a job with over 7k rows. I'm on laravel vapor and my db is hitting max connections. I'm chunking to 50 rows so it's creating over 140 jobs. Anyone know why is maxing out connections? shouldn't the jobs utilize same connection? the server is pretty much getting ddosed.
