### ISSUE TITLE
Import BelongsToMany relationships

### ISSUE THREAD

**Issue by danharrin** [laravel-filament/filament#11087]

**Comment by iddir94** [comment]
I endorse this

**Comment by urufudev** [comment]
It would be great if this could be done.

**Comment by danharrin** [comment]
How about submitting a PR?

**Comment by pschilly** [comment]
Is this to make it so that you can add an "Import Action" to a relationship manager?

**Comment by danharrin** [comment]
No, I believe you can do that, and we even document it
