### ISSUE TITLE
searchable() - dropdown lagging, refeshing the page there is lag and within sec it correct itself

### ISSUE THREAD

**Issue by Suraj127-git** [laravel-filament/filament#11081]
### Package

filament/filament

### Package Version

3.2

### Laravel Version

10.10

### Livewire Version

3.4

### PHP Version

8.1

### Problem description

I have images that it takes 5 sec to get it correct dropdown and I tried many cache command

https://github.com/filamentphp/filament/assets/52707003/c4f85be4-ca4a-48cc-8c39-aa83b0c2bb17

php artisan view: cache php artisan route: cache php artisan config: cache php artisan icons: cache

This is the code

Forms\Components\Section::make('Address Details') ->schema([ Forms\Components\Select::make('country_id') ->relationship(name: 'country', titleAttribute: 'name') ->searchable() ->preload() ->multiple() ->required(), Forms\Components\Select::make('state_id') ->relationship(name: 'state', titleAttribute: 'name') ->searchable() ->preload() ->multiple() ->required(), Forms\Components\Select::make('city_id') ->relationship(name: 'city', titleAttribute: 'name') ->searchable() ->preload() ->multiple() ->required(), Forms\Components\Select::make('department_id') ->relationship(name: 'department', titleAttribute: 'name') ->searchable() ->preload() ->multiple() ->required(), ])->columns(3),
![filament-error](https://github.com/filamentphp/filament/assets/52707003/8bd90ed4-cb15-4866-b129-537d3a4c47c1)
![filament-succes](https://github.com/filamentphp/filament/assets/52707003/0893d218-5a83-48f5-b54b-c9bb0860872e)

There are 2 images attached their image where it take time to load or lag and in 5 seconds then it corrected itself

### Expected behavior

Not lagging

### Steps to reproduce

by commenting the 

->searchable()

### Reproduction repository

https://github.com/Suraj127-git/laravel-filament-panel

**Comment by Suraj127-git** [comment]
Using filament as an admin panel in the SAAS application in (EmployeeResource.php) in the form section in the country input field this issue is occurring Need help in this matter

**Comment by danharrin** [comment]
Please do not open a bug report for this, it's not really a bug, just a result of the slowness of the app. The Select components look like that while your network is still loading the select.js component. For advice, please use Discord or the GitHub Discussions area.
