### ISSUE TITLE
Wrong alignment of inline label for text input

### ISSUE THREAD

**Issue by dissto** [laravel-filament/filament#11098]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

v10.00

### Livewire Version

v3

### PHP Version

PHP 8.3.0

### Problem description

There is an aligment mismatch between then labels of a `TextInput` and a `Placeholder` when both have `->inlineLabel()` applied to them.

![Screenshot 2024-01-26 220722](https://github.com/filamentphp/filament/assets/11778632/fb460c7c-f926-4b7e-8a6d-7999b6ee3aca)

I have wrapped it into a section to emphasize it even more:

![Screenshot 2024-01-26 220749](https://github.com/filamentphp/filament/assets/11778632/23910749-6fb6-4c3e-a80b-bb98a71d9cb4)

![Screenshot 2024-01-26 221359](https://github.com/filamentphp/filament/assets/11778632/be17c099-637a-4fd1-bc56-3c989f28e5ac)

Relevant code:
```php    

public static function form(Form $form): Form
    {
        return $form
            ->schema([

                TextInput::make('email')
                    ->label('Input Label')
                    ->inlineLabel()
                    ->helperText('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec hendrerit magna. Sed nec ex eget augue aliquet aliquam.'),

                Placeholder::make('ph_email')
                    ->label('Placeholder Label')
                    ->inlineLabel()
                    ->content(function (Model $record) {
                        return $record->email;
                    })
                    ->helperText('Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec hendrerit magna. Sed nec ex eget augue aliquet aliquam.'),
            ])->columns(1);
    }
```

### Expected behavior

Both to be either aligned start or center, but not one or the other.

### Steps to reproduce

Just use the UserResource as example. This repo is ready to run `migrate:fresh --seed` which seeds the user `test@example.com` with the default password.

### Reproduction repository

https://github.com/dissto/filament-label-alignment

**Comment by danharrin** [comment]
@zepfietje this is to do with the vertical alignment you introduced on the field wrapper, it doesn't take the helper text into account

**Comment by zepfietje** [comment]
I ran into this myself recently as well. Easy fix: use padding instead of centering it vertically (like we do for textarea). Will fix it soon.
