### ISSUE TITLE
Fresh install bug

### ISSUE THREAD

**Issue by Cegem-360** [laravel-filament/filament#11093]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

v10.10

### PHP Version

PHP 8.2

### Problem description

After new laravel installatinon, after 
"composer require filament/filament:"^3.2" -W 
php artisan filament:install --panels"
 commands (offical Installation instruction) all generated file maked like this "App\Providers\Filament\1PanelProvider::class,", also in class at App\Providers\Filament\1PanelProvider.php, and inside the file also get this.

### Expected behavior

As usual Installation is succesc full and not get any error in first 1 minute.

### Steps to reproduce

Laravel install with composer create-project laravel/laravel XYZ, after run this
composer require filament/filament:"^3.2" -W 
php artisan filament:install --panels

### Reproduction repository

https://github.com/DCrepper/kertfilament

**Comment by jhuta** [comment]
The problem still occurs with the "php artisan filament:install --panels" command if it asks...
 What is the ID? [admin]
and he will be answered: 1
Creates a file starting with a number.
If you specify "admin", it's ok.
