### ISSUE TITLE
SPA and unsavedChangesAlerts 

### ISSUE THREAD

**Issue by Cegem-360** [laravel-filament/filament#11095]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

v10.10

### Livewire Version

v3.4

### PHP Version

PHP 8.2

### Problem description

If i enable SPA mode in configuration at adminPanelProvider all time i get "Unsaved changes alerts are not supported in SPA mode.". But even if i dont use and disable it still remain this error.

### Expected behavior

nothing be show as error

### Steps to reproduce

enabe in fresh install filament, then SPA function call and disable ->unsavedChangesAlerts(condition: false)

### Reproduction repository

https://github.com/DCrepper/kertfilament

**Comment by Cegem-360** [comment]
Side note if i delete everything from 'vendor\filament\filament\resources\views\components\unsaved-action-changes-alert.blade.php', is working everything fine

**Comment by danharrin** [comment]
Please use `^3.2` as the version as per the docs, not `3.2`. 3.2 is 3.2.0 which had this issue, `^3.2` is the latest 3.2 version.

**Comment by Cegem-360** [comment]
Thx, it worked.

**Comment by Vineeshe** [comment]
> Side note if i delete everything from 'vendor\filament\filament\resources\views\components\unsaved-action-changes-alert.blade.php', is working everything fine



> Side note if i delete everything from 'vendor\filament\filament\resources\views\components\unsaved-action-changes-alert.blade.php', is working everything fine

thank bro i also have same  issue , instead delete, i just coment out that php file, now working fine.
