### ISSUE TITLE
login page not working

### ISSUE THREAD

**Issue by tauseedzaman** [laravel-filament/filament#11105]
### Package

filament/filament

### Package Version

V3.2

### Laravel Version

V10.8

### Livewire Version

V3.1

### PHP Version

V8.2.12

### Problem description

after a fresh install i visited `/admin/login` and see this loading bar on the button automatically apperis..

![image](https://github.com/filamentphp/filament/assets/64689921/6c4d220a-bb25-4b54-a759-cc52d4d9fea6)

i tried to login with correct credentials... it didn't work then i tried with wrong credentials it didn't worked again but didn't showed any error also...

plz advise

### Expected behavior

i have used filament before many times.. but haven't seen this behavior now is it a bug in this version or i am doing something wrong...?

### Steps to reproduce

just installed filament in my project... no customization are made.

### Reproduction repository

https://github.com/tauseedzaman/inventory-management-system

### Relevant log output

```shell
no info available in logs.. logs are clear.. no error, no warnings...
```

**Comment by danharrin** [comment]
Please start from a fresh Laravel project, currently I cannot install your repository due to unrelated NPM issues.

And I do not think this is a problem with Filament, so I'm going to convert this to a discussion. You might get faster help on Discord for diagnosis.
