### ISSUE TITLE
UI Broken when CheckboxList/Select(with `->multiple()`) create on the fly

### ISSUE THREAD

**Issue by samlm0** [laravel-filament/filament#11123]
### Package

filament/forms

### Package Version

v3.2.16

### Laravel Version

v10.42.0

### Livewire Version

v3.4.2

### PHP Version

8.3.2

### Problem description

I think it's the user interface bug.

CheckboxList always return boolean to backend data
Select (with `->multiple()`) show is required, but option has been selected 

### Expected behavior

I would expect the the component can work like normal

### Steps to reproduce

![CleanShot 2024-01-28 at 23 21 12](https://github.com/filamentphp/filament/assets/9084029/ca5e68fc-7d6f-4221-b089-24cb53f30a12)

### Reproduction repository

https://github.com/samlm0/filament/tree/bug_select_multiple

**Comment by danharrin** [comment]
Please check this - https://filamentphp.com/docs/3.x/forms/advanced#dynamic-fields-based-on-a-select-option

You need to `->fill()` the container otherwise the data is not structured correctly.
