### ISSUE TITLE
SPA and user menu items

### ISSUE THREAD

**Issue by joowdx** [laravel-filament/filament#11131]
### Package

filament/filament

### Package Version

v3.2.12

### Laravel Version

v10.42.0

### Livewire Version

v3.4.1

### PHP Version

v8.2.12

### Problem description

User menu items does not get updated when switching panels in with **SPA** mode.

### Expected behavior

- Current panel user menu items should be reflected when switching back and forth with **SPA** mode enabled. 
- Having **SPA** mode disabled doesn't have this issue.

### Steps to reproduce

Add different user menu items in different panels.

### Admin Panel
```
$panel
  ->spa()
  ->userMenuItems([
      MenuItem::make()
          ->label(fn () => 'Go to app')
          ->icon('heroicon-o-user-group')
          ->url(fn () => url('/'))
  ])
```

### App Panel
```
$panel
  ->spa()
  ->userMenuItems([
      MenuItem::make()
          ->label(fn () => 'Admin')
          ->icon('heroicon-o-user-group')
          ->url(fn () => url('/admin'))
  ])
```

### Reproduction repository

https://github.com/joowdx/filament-spa

**Comment by danharrin** [comment]
#11720, you can add an exception for the URLs that switch between panels to force a hard refresh.
