### ISSUE TITLE
Searchable Select crashes on arrow down when focused through tab key

### ISSUE THREAD

**Issue by fabio-ivona** [laravel-filament/filament#11144]
### Package

filament/forms

### Package Version

v3.2.16

### Laravel Version

v10.42.0

### Livewire Version

v3.4.4

### PHP Version

PHP8.x

### Problem description

when a searchable select input field is focused using Tab key and the Arrow Down key is pressed, the dropdown opens up showing "arrowdown" in the search field and the search input is locked: it is impossible to use the search field anymore, clicking on it lead to close the dropdown:

![image](https://github.com/filamentphp/filament/assets/8792274/d0765eea-c24f-4f39-a6e1-103cd9fcdb9e)

[Screencast from 2024-01-29 18-03-39.webm](https://github.com/filamentphp/filament/assets/8792274/c92a16de-68b9-42dd-bcab-926357de2ce3)

### Expected behavior

Pressing the down arrow should allow to move selection between the dropdown elements without impacting on the search field

### Steps to reproduce

- clone the sample repository
- `composer install`
- `php artisan serve`
- log in with default credentials
- navigate in Users and Edit `Test User`
- focus the "Name field"
- press TAB arrow key to focus the Foo select field
- press Arrow Down

the dropdown will open like this:

![image](https://github.com/filamentphp/filament/assets/8792274/b197b133-3d74-451c-9c18-63cd3d87cb0d)

### Reproduction repository

https://github.com/fabio-ivona/filament-searchable-select-issue

### Relevant log output

```shell
no output in browser console
```

**Comment by zepfietje** [comment]
https://github.com/filamentphp/filament/issues/10811#issuecomment-1892724312
