### ISSUE TITLE
Table overflow

### ISSUE THREAD

**Issue by magarciasantos** [laravel-filament/filament#11146]
### Package

filament/filament

### Package Version

v3.2.16

### Laravel Version

10.42.0

### Livewire Version

v3.4.4

### PHP Version

8.2.11

### Problem description

I was adding several columns to a table and enabling the individual search for them all. Both a table scroll bar and the body/bottom scroll bar appear
<img width="1676" alt="Screenshot_2024-01-29_at_14 00 04" src="https://github.com/filamentphp/filament/assets/70562227/d62972d3-029f-445c-b432-76fbbbabc7b1">

### Expected behavior

Only the table's horizontal scrollbar should appear
<img width="1613" alt="Screenshot_2024-01-29_at_14 13 19" src="https://github.com/filamentphp/filament/assets/70562227/f266462c-374e-476a-a06c-bec5e70cef3d">

### Steps to reproduce

Add a column that can't be shown on screen and enable its individual search

### Reproduction repository

https://github.com/magarciasantos/filament-table-overflow-bug.git

**Comment by magarciasantos** [comment]
The side panel seems to be broken also

**Comment by wannesmatthys** [comment]
This seems to happen for me aswell when I have an error page (403 forbidden for example), and I use the back button of my browser. (on chrome)
