### ISSUE TITLE
FileUpload component does not show correct file name on edit forms when using storeFileNamesIn

### ISSUE THREAD

**Issue by correiarmjoao** [laravel-filament/filament#11160]
### Package

filament/filament

### Package Version

v3.2.19

### Laravel Version

v10.42.0

### Livewire Version

v3.4.4

### PHP Version

PHP 8.3.1

### Problem description

When using the option storeFileNamesIn on the FileUpload component the file name shown on the edit form is not correct.
The component shows the id created on upload as the file name instead of the file name saved in the database column.

### Expected behavior

The component should show the file name saved on the database column.

### Steps to reproduce

1. Link storage `php artisan storage:link`
2. Create a post with an image attachment
3. See the created post

NOTE: Use http://localhost:8000 in the urls to match the .env APP_URL

### Reproduction repository

https://github.com/correiarmjoao/filament-issue-fileupload

**Comment by correiarmjoao** [comment]
From what I checked this method is returning the correct data.
https://github.com/filamentphp/filament/blob/203d9d61236471670bc3df32e2b9f5e6748ae956/packages/forms/src/Components/BaseFileUpload.php#L139-L176

But its being ignored on the javascript side by the regex check.
https://github.com/filamentphp/filament/blob/203d9d61236471670bc3df32e2b9f5e6748ae956/packages/forms/resources/js/components/file-upload.js#L338-L367

I'm not sure but I believe this is because of image previews, it saw it mentioned here https://github.com/filamentphp/filament/issues/4088#issuecomment-1304505001 but couldn't this also check the flag isPreviewable or am I missing something?

**Comment by danharrin** [comment]
Good point about checking isPreviewable, I've added that into #11132
