### ISSUE TITLE
darkModeBrandLogo doesn't work

### ISSUE THREAD

**Issue by matijarezek** [laravel-filament/filament#11167]
### Package

filament/filament

### Package Version

v3.2.19

### Laravel Version

v10.42.0

### PHP Version

PHP  8.3.2

### Problem description

In the new 3.2.19 update, the darkModeBrandLogo doesn't show up. 
The normal logo works as intended.

Tried on a new installation and it is the same.

### Expected behavior

That the logo for the dark mode shows.

### Steps to reproduce

Update to the 3.2.19 and put an asset to darkModeBrandLogo() in any panel.

### Reproduction repository

https://github.com/matijarezek/filament-issue-darkModeBrandLogo-bug

**Comment by zepfietje** [comment]
Fixed in the next release. The workflow that builds assets seems to have failed.
