### ISSUE TITLE
Image cannot be displayed in the admin panel 

### ISSUE THREAD

**Issue by rosolovsky** [laravel-filament/filament#1118]
### Package

filament/spatie-laravel-media-library-plugin

### Package Version

2.8.0

### Laravel Version

8.77.1

### Livewire Version

2.8.2

### PHP Version

8.0.14

### Bug description

Image cannot be displayed in the admin panel.
I see it endlessly. 
![medialibrary](https://user-images.githubusercontent.com/5950382/147962450-9205519a-5117-4ca8-8965-3ba5d49ad666.png)

**Comment by danharrin** [comment]
Make sure that your public directory is linked: `php artisan storage:link`.

If that doesn't work, please check for console errors.

**Comment by rosolovsky** [comment]
I am developing locally and it probably has to do with "Referrer Policy: strict-origin-when-cross-origin"
![medialibrary-1](https://user-images.githubusercontent.com/5950382/147965587-42c96938-86aa-40f4-95fa-73e208ab762b.png)

**Comment by danharrin** [comment]
I don't think this is a Filament issue, make sure your `APP_URL` is correct.

**Comment by SebastiaanKloos** [comment]
> I don't think this is a Filament issue, make sure your `APP_URL` is correct.

I've experienced this same issue and was the APP_URL setting indeed

**Comment by rosolovsky** [comment]
> I don't think this is a Filament issue, make sure your `APP_URL` is correct.

Yes you are right. The problem was with the wrong APP_URL setting.
Thanks!!!
