### ISSUE TITLE
Duplicate query

### ISSUE THREAD

**Issue by Mambi** [laravel-filament/filament#11201]
### Package

filament/filament

### Package Version

v3.2.15

### Laravel Version

v10.10

### Livewire Version

v3.4.2

### PHP Version

PHP 8.3

### Problem description

i have added a relation manager to the Pharmacie ressource and when editing a record i noticed that there's a duplicate query 
![Capture_decran_2024-01-27_a_8 15 17_AM](https://github.com/filamentphp/filament/assets/6738211/fdddb77a-dcf3-47e4-811e-7cb11a4cd381)

### Expected behavior

only one query should be used 

### Steps to reproduce

1. clone the repo
2. Seed the database
3. try to add a new relation to the Pharmacie ressource
4. have a look on the debug bar

### Reproduction repository

https://github.com/Mambi/filament3.git

**Comment by danharrin** [comment]
Have a look at the stack trace, those queries originate from Livewire. I don't think there's anything we can do on our end to solve, but please let me know if there is and I will reopen.

**Comment by hammad-somnowell** [comment]
Facing same issue
