### ISSUE TITLE
MorphMany RelationManager can only associate one item

### ISSUE THREAD

**Issue by DevRaeph** [laravel-filament/filament#11205]
### Package

filament/filament

### Package Version

v3.2.22

### Laravel Version

v10.43.0

### PHP Version

8.3

### Problem description

I've tried to create a MorphTo Model called Vehicle with the morph attribute named owner.
Then I have to MorphMany models called Customer and Carrier. Both should be able to have multiple vehicle.
I've tried to implement the relation manager on the Customer resource to associate the vehicles.
After the first association I can't associate another one. 
The Select field stays empty.

### Expected behavior

I expected that i can associate more models one after another. 

### Steps to reproduce

Pull repo, then create a user and log in.
Create 2 vehicles and one customer. Edit the customer and try to associate a vehicle, after that try to associate anoter one.

### Reproduction repository

https://github.com/DevRaeph/filament-morph-many-relation

**Comment by marcosmarcolin** [comment]
Hi @DevRaeph,

I haven't been able to simulate your project locally yet, but have you tried allowing duplicates?https://filamentphp.com/docs/3.x/panels/resources/relation-managers#handling-duplicates

Maybe that could be it.

**Comment by DevRaeph** [comment]
Yes i tried allowing duplicates, that also changed nothing.


Marcos Marcolin ***@***.***> schrieb am Do. 1. Feb. 2024 um
12:45:

**Comment by marcosmarcolin** [comment]
Correct @DevRaeph,

I ended up deleting the answer because I realized I was wrong, it refers to the table, not the form.
