### ISSUE TITLE
Unpin fixed league/csv version

### ISSUE THREAD

**Issue by alepieser** [laravel-filament/filament#11213]
### Package

filament/actions

### Package Version

v3.2.23

### Laravel Version

v10.0.0

### PHP Version

PHP 8.2.0

### Problem description

Hello,

There was a fix on filament/filament to unpin fixed league/csv version but the package filament/action has still the version pinned to 9.11.0.

Thanks

### Expected behavior

To be able to upgrade league/csv to 9.14

### Steps to reproduce

Check composer file

{
    "name": "filament/actions",
    "description": "Easily add beautiful action modals to any Livewire component.",
    "license": "MIT",
    "homepage": "https://github.com/filamentphp/filament",
    "support": {
        "issues": "https://github.com/filamentphp/filament/issues",
        "source": "https://github.com/filamentphp/filament"
    },
    "require": {
        "php": "^8.1",
        "anourvalar/eloquent-serialize": "^1.2",
        "filament/forms": "self.version",
        "filament/infolists": "self.version",
        "filament/notifications": "self.version",
        "filament/support": "self.version",
        "illuminate/contracts": "^10.0",
        "illuminate/database": "^10.0",
        "illuminate/support": "^10.0",
        "league/csv": "9.11.0",
        "openspout/openspout": "^4.23",
        "spatie/laravel-package-tools": "^1.9"

### Reproduction repository

https://github.com/alepieser/filament_bug

**Comment by danharrin** [comment]
done

**Comment by danharrin** [comment]
Gonna need to revert, its causing imports not to run
