### ISSUE TITLE
Cannot be installed with Laravel 11 (release date Feb 6)

### ISSUE THREAD

**Issue by blocher** [laravel-filament/filament#11239]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

v11.0

### Livewire Version

v.3.4.4

### PHP Version

PHP 8.3.1

### Problem description

Filament cannot be installed with Laravel 11.

`composer require filament/filament:"^3.2" -W`
./composer.json has been updated
Running composer update filament/filament --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - filament/filament[v3.2.0, ..., 3.x-dev] require illuminate/console ^10.0 -> found illuminate/console[v10.0.0, ..., 10.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires filament/filament ^3.2 -> satisfiable by filament/filament[v3.2.0, ..., 3.x-dev].

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

### Expected behavior

Filament installs when running `composer require filament/filament:"^3.2" -W`

### Steps to reproduce

run `composer require filament/filament:"^3.2" -W` when Laravel 11 is installed 

### Reproduction repository

https://github.com/blocher/therapy

### Relevant log output

```shell
./composer.json has been updated
Running composer update filament/filament --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - filament/filament[v3.2.0, ..., 3.x-dev] require illuminate/console ^10.0 -> found illuminate/console[v10.0.0, ..., 10.x-dev] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires filament/filament ^3.2 -> satisfiable by filament/filament[v3.2.0, ..., 3.x-dev].


Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by zepfietje** [comment]
https://github.com/filamentphp/filament/pull/10972

**Comment by fershopls** [comment]
Hello, sorry to bother, but I can't install fillament on a fresh Laravel 11 project.

```$ composer require filament/filament:"^3.2" -W```

```
The "3.2" constraint for "filament/filament" appears too strict and will likely not match what you want. See https://getcomposer.org/constraints
./composer.json has been updated
Running composer update filament/filament --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1                                                                                                                                                                                          
    - illuminate/console[v10.0.0, ..., v10.48.4] require nunomaduro/termwind ^1.13 -> found nunomaduro/termwind[v1.13.0, ..., v1.15.1] but these were not loaded, likely because it conflicts with another require.                                                                                                                                                                                       
    - filament/filament v3.2.0 requires illuminate/console ^10.0 -> satisfiable by illuminate/console[v10.0.0, ..., v10.48.4].                                                                       
    - Root composer.json requires filament/filament 3.2 -> satisfiable by filament/filament[v3.2.0].                                                                                                 
                                                                                                                                                                                                     

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

I saw on #10972 [mokhosh](https://github.com/mokhosh) said it was working at Laravel 11 and saw the PR correctly merged.

I don't know if I am missing something.

Thank you so much for your valuable time.

**Comment by fershopls** [comment]
In case anyone is having the same issue. I just needed to target the right release version:

$ ```composer require filament/filament="3.2.57" -W```

This works for me.

**Comment by Kwenziwa** [comment]
This works for me i was able to install it. @fershopls Thank you so much.
> composer require filament/filament="3.2.57" -W

**Comment by carlospinhod** [comment]
> In case anyone is having the same issue. I just needed to target the right release version:
> 
> $ `composer require filament/filament="3.2.57" -W`
> 
> This works for me.

This solved my problem aswell ty!

**Comment by LukaszJaro** [comment]
This is what finally did it for me: 

`composer require filament/actions:"3.2.71" -W`

Thanks @fershopls ! This should be pinned since it's not possible to follow the filament installation documentation currently.

 Problem 1
    - illuminate/console[v10.0.0, ..., v10.48.9] require nunomaduro/termwind ^1.13 -> found nunomaduro/termwind[v1.13.0, ..., v1.15.1] but these were not loaded, likely because it conflicts with another require.
    - filament/actions v3.2.0 requires filament/infolists v3.2.0 -> satisfiable by filament/infolists[v3.2.0].
    - filament/infolists v3.2.0 requires illuminate/console ^10.0 -> satisfiable by illuminate/console[v10.0.0, ..., v10.48.9].
    - Root composer.json requires filament/actions 3.2 -> satisfiable by filament/actions[v3.2.0].

**Comment by davidbadelllab** [comment]
> En caso de que alguien tenga el mismo problema. Solo necesitaba apuntar a la versión de lanzamiento correcta:
> 
> $ `composer require filament/filament="3.2.57" -W`
> 
> Esto funciona para mí.

---->>>>Genial me funciona perfecta gracia por el aporte<<<<<---
