### ISSUE TITLE
BelongsToManyMultiSelect default not selected, results in double selection if select again

### ISSUE THREAD

**Issue by tangjh** [laravel-filament/filament#1126]
### Package

filament/forms

### Package Version

v2.8.0

### Laravel Version

latest

### Livewire Version

latest

### PHP Version

PHP 8.0.0

### Bug description

Same issue as:
https://github.com/laravel-filament/filament/pull/1114/commits/ffb87a609a72f471884dc49fcd26de9cf2247931

Tested the above changes and it fixes the issue.

**Comment by danharrin** [comment]
Fixed by #1128.
