### ISSUE TITLE
Table record actions hiddenLabel only works if set as button

### ISSUE THREAD

**Issue by noquierouser** [laravel-filament/filament#11270]
### Package

filament/filament

### Package Version

v3.2.2

### Laravel Version

v10.41.0

### Livewire Version

v3.3.5

### PHP Version

PHP 8.3.2

### Problem description

Table record actions still shows label when `hiddenLabel()` is set, yet when the action is set as a `button()`, the setting works properly.

### Expected behavior

Action label to be hidden, regardless of `button()` setting.

### Steps to reproduce

As is in [TestRecordResource.php](https://github.com/noquierouser/table-action-label/blob/main/app/Filament/Resources/TestRecordResource.php).

```php
$table
  // …
  ->actions([
      /* Label still showing */
      Tables\Actions\EditAction::make()
          ->hiddenLabel(),
  
      /* Label is properly hidden */
      Tables\Actions\DeleteAction::make()
          ->hiddenLabel()
          ->button(),
  ])
  // …
```

### Reproduction repository

https://github.com/noquierouser/table-action-label

**Comment by danharrin** [comment]
Fixed in #11283. But in this case, you should probably use `iconButton()` instead.
