### ISSUE TITLE
Form Repeater component causing BadMethodCallException: HasOne::associate()

### ISSUE THREAD

**Issue by nettsite** [laravel-filament/filament#11282]
### Package

filament/forms

### Package Version

3.1.33

### Laravel Version

10.39.0

### Livewire Version

3.3.5

### PHP Version

8.3.2-1+ubuntu22.04.1+deb.sury.org+1

### Problem description

When creating or saving a model from a resource which contains a Repeater field linked to a relationship, an exception is thrown:
```
Call to undefined method Illuminate\Database\Eloquent\Relations\HasOne::associate()
```

### Expected behavior

Related records should be created or updated in the database.

### Steps to reproduce

The offending field:
```
Repeater::make('specimens')
                    ->columnSpanFull()
                    ->relationship('specimens')
                    ->schema([
                        Select::make('specimen_container_id')
                            ->relationship('specimen_container', 'description')
                            ->searchable(['description', 'colour', 'type'])
                            // ->hiddenLabel()
                            ->required()
                            ->columnSpan(8),
                        TextInput::make('number_of_containers')
                            ->numeric()
                            // ->hiddenLabel()
                            ->required()
                            ->columnStart(6)
                            ->columnSpan(1),
                    ]),
```
Commenting that out in the Resource eliminates the error.

The relationship in the model:
```
public function specimens(): HasMany
    {
        return $this->hasMany(Specimen::class);
    }
```

The same happens using the Awcodes\TableRepeater\Components\TableRepeater component.

### Reproduction repository

https://github.com/nettsite/repeater-issue

### Relevant log output

```shell
https://flareapp.io/share/x5MZGwXm
```

**Comment by danharrin** [comment]
Please publicise the reproduction repository otherwise we will need to close

**Comment by nettsite** [comment]
Sorry, that was dumb. It is now public.

**Comment by danharrin** [comment]
Try `->saveRelationshipsUsing(null)` on the Select

**Comment by nettsite** [comment]
Pure genius. I suspected it had something to do with the Select.

Thank you very much.

**Comment by danharrin** [comment]
I think it's because the Select doesnt have full support for HasOne

**Comment by nettsite** [comment]
It works seamlessly with ```->saveRelationshipsUsing(null)```.

I shall try and do a pull and add that to the docs, shall I?
