### ISSUE TITLE
searchable() conflict with disable() on Select component

### ISSUE THREAD

**Issue by massimomarazzi** [laravel-filament/filament#11289]
### Package

filament/forms

### Package Version

v3.2.25

### Laravel Version

v10.43

### Livewire Version

v3.4.4

### PHP Version

PHP 8.1

### Problem description

`->seachable() `  function cause the issue.
I need to enable/disable select component with Toggle component (but also with checkbox is same), so i make i simple callback
like this on disable() `->disabled(fn(Get $get): bool => $get('toggle_value'))`
but don't work anymore. 
Select with default state disabled remain disabled and if is enabled by default remain enabled, indipendendly from toggle value.
This issue is caused by `->seachable() ` function, if you comment this function all work as expected. 
See code below or repo

### Expected behavior

When change toggle value, the component, in this case Select,  add/remove disable attribute.

### Steps to reproduce

```

Toggle::make('enable_company_id')
                    ->label('Enable/Disable Company select')
                    ->dehydrated(false)
                    ->live(),
                Select::make('company_id')
                    ->label(__('Company'))
                    ->options([
                        '0' => '--',
                        '1' => 'Company 1',
                        '2' => 'Company 2',
                        '3' => 'Company 3',
                        '4' => 'Company 4',
                        '5' => 'Company 5',
                        '6' => 'Company 6',
                    ])
                    ->searchable() /*<<< Comment this and all works*/
                    ->preload()
                    ->nullable()
                    ->disabled(fn(Get $get): bool => $get('enable_company_id'))
```

### Reproduction repository

https://github.com/massimomarazzi/filament-select-disabled

**Comment by danharrin** [comment]
#10263, #8951, #8935, #8097, #3068
