### ISSUE TITLE
CreateAction::make()->label(null) does not localize and instead always outputs "Create"

### ISSUE THREAD

**Issue by RalphMRivera** [laravel-filament/filament#11302]
### Package

filament/actions

### Package Version

v3.2.27

### Laravel Version

10.43.0

### Livewire Version

v3.4.4

### PHP Version

PHP 8.2.15

### Problem description

The code `CreateAction::make()->label(null)` always outputs the word "Create" regardless of the locale. The output should be the action name with localization.

### Expected behavior

In Spanish ("es"), for example, the output should be "Crear."

Further explanation...

Assuming this code with a resource named "book".

```php
protected function getHeaderActions(): array
{
    return [
        CreateAction::make(), // example 1
        CreateAction::make()->label(null), // example 2
        CreateAction::make()->modelLabel(null), // example 3
    ];
}
```

When local set to "en"

- English, example 1 = **New book**
- English, example 2 = **Create**
- English, example 3 = **New book**

When local set to "es"

- Spanish, example 1 = **Crear book**
- Spanish, example 2 = **Create** _<----- This should be **Crear**_
- Spanish, example 3 = **Crear book**

### Steps to reproduce

Go to the list page of the book resource:

https://github.com/RalphMRivera/filament-issue/blob/main/app/Filament/Resources/BookResource/Pages/ListBooks.php

### Reproduction repository

https://github.com/RalphMRivera/filament-issue

**Comment by danharrin** [comment]
Actions generate their labels from the name of the action. For actions like CreateAction, we define a label in `setUp()` that is localised for convenience. By setting that to null, you are removing it.

Changing it would be a breaking change for people who want to remove the localised label. And also, in my opinion the current behaviour is expected and I would not change it even in a major version.

**Comment by RalphMRivera** [comment]
@danharrin - Understood. Thank you for the explanation. That was helpful and clarified things for me. Is there a way to localize an action button without a model label so that instead of "Create book" (English) or "Crear book" (Spanish), I get "Create" and "Crear" without having to use a custom `label()` and lean on the existing Filament language files?

**Comment by danharrin** [comment]
Have a look at the existing translation string we use, and pass an empty string as the model label?

**Comment by RalphMRivera** [comment]
@danharrin - This is the solution that I have  used:   

```php
CreateAction::make()
->label(fn (): string => __('filament-actions::create.single.label', ['label' => null]));
```

This results in "New" in English and "Crear" in Spanish.

I yanked that from [here](https://github.com/filamentphp/filament/blob/f26e35ee750c461f26f898bd97b75bf0e3b448ac/packages/tables/src/Actions/CreateAction.php#L30). I was worried that was a bad practice which is why I was looking for an alternative.

Thank you again for all your hard work. You've made my team's job easier.

**Comment by danharrin** [comment]
Yeah that looks good to me
