### ISSUE TITLE
Custom page navigation menu item acts weird with multi-tenancy , it changes the tenant it doesn't show the active tenant url  it shows other tenant url

### ISSUE THREAD

**Issue by amoktar** [laravel-filament/filament#11306]
### Package

filament/filament

### Package Version

v3.2.27

### Laravel Version

v10.43

### PHP Version

8.1

### Problem description

Custom page navigation menu item acts weird with multi-tenancy , it changes the tenant it doesn't show the active tenant url 
it shows other tenant url

### Expected behavior

Navigation menu item shouldn't change the current tenant 

### Steps to reproduce

1.  create more than one tenant 
2. register navigationGroups in the panel provider 
```php
 ->navigationGroups([
                NavigationGroup::make()
                    ->label(fn (): string => __('text.settings'))
                    ->icon('heroicon-o-cog-6-tooth')
                    ->collapsed(),
            ])
```
3. `make:filament-page TestPage --type=custom` no resource
4. override the method getNavigationGroup and return __('txt') or trans('txt')
```php
     public static function getNavigationGroup(): ?string
    {
        return __('text.settings');
    }
```

this commit has the bug reproduction
https://github.com/AMoktar/filamentphp-v3-tutorial-tony/commit/a23d53cd9c7eb6172b5c43ee884aac964b51c93f

that's it 
The navigation item of the TestPage has a route for any tenant other than the active one 

### Reproduction repository

https://github.com/AMoktar/filamentphp-v3-tutorial-tony/commit/a23d53cd9c7eb6172b5c43ee884aac964b51c93f

**Comment by danharrin** [comment]
Should be fixed in #11309
