### ISSUE TITLE
Saving / Creating a form from the header actions does not work

### ISSUE THREAD

**Issue by anselmpaul** [laravel-filament/filament#11338]
### Package

filament/filament

### Package Version

v3.2.28

### Laravel Version

v10.43.0

### PHP Version

PHP 8.1

### Problem description

When using the `parent::getCreateFormAction()`or `parent::getSaveFormAction()` in the header functions of a Create or Edit page, they do not work. On click nothing happens.

### Expected behavior

The actions should run, creating or saving the record.

### Steps to reproduce

1. Clone the provided repo.
2. Run the migrations `php artisan migrate`
3. Add a user `php artisan make:filament-user`
4. Run the application `php artisan serve`
5. Create a "test". Try to use the header create Action, or Create with the normal action and then try to edit this record and save with the header action
6. Observe that it's not working.

### Reproduction repository

https://github.com/anselmpaul/filament-create-save-bug/tree/main/app/Filament/Resources/TestResource/Pages

**Comment by danharrin** [comment]
`->submit(null)->action('create')` / `->submit(null)->action('save')`
