### ISSUE TITLE
FileUpload field not clearing state

### ISSUE THREAD

**Issue by pxlrbt** [laravel-filament/filament#1133]
### Package

filament/forms

### Package Version

2.8

### Laravel Version

8.78.0

### Livewire Version

2.8.2

### PHP Version

8.1.0

### Bug description

The FileUpload field is not clearing Filepond's state after saving. 

### Steps to reproduce

- Register a simple FileUpload field in Filament admin: `Forms\Components\FileUpload::make('test')`
- Click "Create & add another"
- Filepond state is not cleared and still showing the selected files

This check is causing the issue:
https://github.com/laravel-filament/filament/blob/2.x/packages/forms/resources/js/components/file-upload.js#L129-L131

**Comment by danharrin** [comment]
Yeah, I know about this issue, but I've got no idea how to fix it unfortunately.

The reason that check exists is because of a Livewire bug that I can't track down, and without it the input will sometimes clear randomly :(
