### ISSUE TITLE
Laravel Echo cannot be found

### ISSUE THREAD

**Issue by raonikhil** [laravel-filament/filament#11332]
### Package

filament/filament

### Package Version

v3.2.28

### Laravel Version

v10.43.0

### Livewire Version

v3.4.4

### PHP Version

v8.2.15

### Problem description

Laravel echo not found error is shown when trying to listen to an event in filament custom page. 

### Expected behavior

Laravel echo should be accessible in the Filament Panel.

### Steps to reproduce

1. clone the repo `git clone git@github.com:raonikhil/echo2.git` & `cd ./echo`
2. copy the contents of .env.example to .env
3. `php artisan migrate`
4. `npm run dev`
5. `php artisan serve`
6. Login 
7. go to: http://localhost/chat and check the chrome console, there is no "laravel echo not found" error as echo is also used on this page
8. Now go to: http://localhost/admin/customers/1/chat which is inside filament 
9. Open Chrome console error to see: `Laravel Echo cannot be found`

### Reproduction repository

https://github.com/raonikhil/echo2.git

**Comment by sbc640964** [comment]
I have this problem too.
Is there anything I can do?

**Comment by raonikhil** [comment]
Waiting for @zepfietje @danharrin to do their magic and fix this!
I am waiting on go live after this fix 👍🏼

**Comment by danharrin** [comment]
How about trying to fix submit a PR yourself? This issue is not being prioritised at the moment

**Comment by sbc640964** [comment]
@raonikhil this not a bug.
you need publish configuration [Read here](https://filamentphp.com/docs/3.x/panels/installation#publishing-configuration)
there is a config the  echo there

**Comment by StaffCollab** [comment]
It is not the config that causes the problem! it just seems like it only works on the db notifications but not outside it.

**Comment by danharrin** [comment]
That sounds impossible to be honest

**Comment by raonikhil** [comment]
@StaffCollab was correct, if you publish the config, you can enable echo and it works like a charm

**Comment by raonikhil** [comment]
@StaffCollab - @sbc640964 was correct, if you publish the config, you can enable echo and it works like a charm

**Comment by hyphen81** [comment]
I'm having this issue too. I have the config published, and broadcast notifications are working within Filament. However, I need to handle events using Laravel Echo in javascript for a specific use case in a livewire component, and I get Echo not found. I tried adding the bootstrap.js file with the imports per the Laravel Echo documentation and still nothing. Has anyone gotten echo working in a livewire component? Can you share what you did to get it to work?

**Comment by emjay64** [comment]
Same issue here, if anyone has figured this out please share.

**Comment by vamsijanaki** [comment]
Any update on this, Same issue i cant wise Echo in frontend js ?

**Comment by lordjack** [comment]
Hello guys, I was able to solve this error following this tutorial, I hope it helps you too. @raonikhil 

https://laraveldaily.com/post/configure-laravel-reverb-filament-broadcasting

**Comment by geosem42** [comment]
> @raonikhil this not a bug. you need publish configuration [Read here](https://filamentphp.com/docs/3.x/panels/installation#publishing-configuration) there is a config the echo there

Thank you, this worked for me!
