### ISSUE TITLE
Badge component attributes only work partially in pre- and suffix actions inside tables

### ISSUE THREAD

**Issue by dissto** [laravel-filament/filament#11341]
### Package

filament/filament

### Package Version

v3.2.28

### Laravel Version

10.43.0

### Livewire Version

v3.4.4

### PHP Version

8.3.1

### Problem description

Adding a Badge component inside a `->prefix()` or `->suffix()` (via view or Blade::render) only accepts attributes partially. For example it accepts `color`, `size` and `class` whereas `icon` or `tooltip` will be ignored. No errors thrown either. If you were to add a heroicon that does not exist, it will throw and error, so it recognizes those attributes.

![Screenshot 2024-02-09 192453](https://github.com/filamentphp/filament/assets/11778632/e3024423-e0a0-4dc5-8600-be25536f341e)

![Screenshot 2024-02-09 192651](https://github.com/filamentphp/filament/assets/11778632/edc6a318-d8b5-45fe-ae7e-422713e51c11)

### Expected behavior

To work the same as it does in `->description` (and generally anywhere else)

### Steps to reproduce

Return a view with a badge component inside to either the prefix or suffix of `TableColumn::`

### Reproduction repository

https://github.com/dissto/filament-badge-issue

**Comment by danharrin** [comment]
The reproduction repository does not appear to reproduce the problem. Please point me to the place in the repository where it does, or add it, or we will need to close this

**Comment by dissto** [comment]
Apologies i have linked the wrong repo:

https://github.com/dissto/filament-badge-issue

**Comment by zepfietje** [comment]
@dissto, could you check if this is still an issue on the 3.x branch?
Might have been related to https://github.com/filamentphp/filament/pull/11346.

**Comment by dissto** [comment]
@zepfietje im kinda at a loss on how to get the latest change without it being tagged a new release. Composer update gets me v3.2.29 and if i use 3.x-dev I dont see the changed file though. 
Since there is only one line changed I manually changed it in the test project, which did not resolve the issue.

**Comment by dissto** [comment]
Just letting you know v3.2.30 did **not** resolve this issue.
