### ISSUE TITLE
JavaScript errors when both SPA and table defer loading are enabled

### ISSUE THREAD

**Issue by jalilfahimi** [laravel-filament/filament#11371]
### Package

filament/filament

### Package Version

v3.2.31

### Laravel Version

v10.43.0

### Livewire Version

v3.4.4

### PHP Version

PHP 8.3

### Problem description

I am recieving js errors in console when both spa and table defer loading are enabled.
I have noticed that these errors are triggered only once after a hard reload has happened.
For second time visiting the same table, errors are gone.

[errors.log](https://github.com/filamentphp/filament/files/14239189/errors.log)

### Expected behavior

--

### Steps to reproduce

First, you need to enable spa in your panel `panel()` with calling `->spa()`.
Then, in a resource, call `->deferLoading()` in the `form()` function.
Finally, reload the list page of that resource.

### Reproduction repository
https://github.com/jalilfahimi/filamentphp
-

**Comment by danharrin** [comment]
No reproduction repo

**Comment by jalilfahimi** [comment]
@danharrin Hey Dan, sorry for the wrong repo.
reproduction repo is now edited.

**Comment by danharrin** [comment]
I am unable to reproduce the issue with the latest Livewire version


https://github.com/filamentphp/filament/assets/41773797/12158cff-c222-437e-83c8-f31da7543ad9
