### ISSUE TITLE
Table ->groupsOnly() Heading UI Issue

### ISSUE THREAD

**Issue by davidwhicker** [laravel-filament/filament#11373]
### Package

filament/filament

### Package Version

Latest

### Laravel Version

Latest

### Livewire Version

Latest

### PHP Version

8.3

### Problem description

When using ->groupsOnly() on a table to show summaries the first column ( group identifier ) is not adding a header to the table and so everything shunts to the left and out of alignment with columns. 

`return $table
            ->query(Invoice::query()
                ->when(
                    Invoice::has('client'),
                    function ($query) {
                        $query->whereHas('client', function ($query) {
                            $query->where('origin', 'internet');
                        });
                    }
                )
                ->where('date', '>=', Carbon::now()->subYear()->format('Y-m-d'))
            )
            ->defaultGroup('client.company_name')
            ->groupsOnly()
            ->columns([
                Tables\Columns\TextColumn::make('sub_total')->summarize(Sum::make()->label('Sub Total')),
                Tables\Columns\TextColumn::make('budgetProfit')->summarize(Sum::make()->label('Budget Profit')),
                Tables\Columns\TextColumn::make('profit')->summarize(Sum::make()->label('Profit')),
            ]);`

<img width="1164" alt="Screenshot 2024-02-12 at 14 10 25" src="https://github.com/filamentphp/filament/assets/51021366/d343ec66-60fa-46bc-aead-86b762303eb1">

### Expected behavior

Labels should say in columns

### Steps to reproduce

Table in livewire component ( outside of panels ). Code above.

### Reproduction repository

[https://github.com/FortuneV13/filamentphp](url)

Discord Help Topic: https://discord.com/channels/883083792112300104/1206603170566905876

**Comment by danharrin** [comment]
No reproduction repo

**Comment by davidwhicker** [comment]
> No reproduction repo

wasnt sure how to do this as my data is all confidential ( work ). There is nothing fancy going on beyond the code snippet provided above.

**Comment by danharrin** [comment]
<img width="932" alt="Screenshot 2024-02-12 at 17 45 58" src="https://github.com/filamentphp/filament/assets/41773797/2ba16d8e-0b91-4f74-9b72-a186aabcb937">

Simplify the code, upload to a new repo with a seeder and everything

**Comment by maytham553-elite** [comment]
same issue

**Comment by maytham553** [comment]
**Fix: Add missing `TextColumn` for group key to resolve UI alignment issue**
### Summary:
To fix the UI misalignment issue when using `groupsOnly()`, add a `TextColumn::make('name_of_your_group')` for the group key.
### Example Fix:
```php
return $table
    ->query(
        Invoice::query()
            ->when(Invoice::has('client'), function ($query) {
                $query->whereHas('client', function ($query) {
                    $query->where('origin', 'internet');
                });
            })
            ->where('date', '>=', Carbon::now()->subYear()->format('Y-m-d'))
    )
    ->defaultGroup('client.company_name')   // Group by client company name
    ->groupsOnly()
    ->columns([
        Tables\Columns\TextColumn::make('client.company_name'),  // Add group key column to fix alignment
        Tables\Columns\TextColumn::make('sub_total')
            ->summarize(Sum::make()->label('Sub Total')),
        Tables\Columns\TextColumn::make('budgetProfit')
            ->summarize(Sum::make()->label('Budget Profit')),
        Tables\Columns\TextColumn::make('profit')
            ->summarize(Sum::make()->label('Profit')),
    ]);
```
### Explanation:
This adds the missing `TextColumn::make('client.company_name')` to ensure proper alignment of the group header with the other columns.
