### ISSUE TITLE
Database notification for export action does not work with alternative User class

### ISSUE THREAD

**Issue by CamilleScholtz** [laravel-filament/filament#11394]
### Package

filament/actions

### Package Version

v3.2.33

### Laravel Version

v10.43.0

### Livewire Version

v3.4.4

### PHP Version

v8.3.0

### Problem description

Instead of `User` we use `DashboardUser` as our authenticatable user class. So far I have not run into any problems except for the database notification that gets send upon a successful export action. The problem is that the `notifications` table it sets the `notifiable_type` to `App\Models\User` instead of the expected `App\Models\DashboardUser`.

The problem seems to arise from the following line: https://github.com/filamentphp/filament/blob/3.x/packages/actions/src/Concerns/CanExportRecords.php#L181

It unsets the user relation (which did point to a correct `DashboardUser`). Then in the `ExportCompletion` class it fetches the user again from the export action. From what I see this is not a polymorphic column but always points to `Users`: https://github.com/filamentphp/filament/blob/3.x/packages/actions/src/Exports/Jobs/ExportCompletion.php#L77

### Expected behavior

 `notifiable_type` in the `notifications` table should be set to the actual used User class, such as `App\Models\DashboardUser`

### Steps to reproduce

Use a User class other than `User` and try to make a table export.

**Comment by chrishentges** [comment]
@CamilleScholtz I had a similar issue but resolved it by adding the following to my AppServiceProvider register method

`$this->app->bind(\Illuminate\Contracts\Auth\Authenticatable::class, \App\Models\Admin::class);`
