### ISSUE TITLE
Scout Table search do not work applySearchToTableQuery is not defined

### ISSUE THREAD

**Issue by omar-bfe** [laravel-filament/filament#11392]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

v10

### PHP Version

PHP 8.3

### Problem description

the proble here is that the table dose not implement `applySearchToTableQuery` in the `canSearchRecords` Concerns and i find there is 2 concerns with the same name but different namespace one implements `applySearchToTableQuery` and the other not on inside Tables/Concerns and the Other is inside Tables/Table/Concerns and of course we are not able to modify the search query on a table. 

### Expected behavior

We can ovveride the Table search Query 

### Steps to reproduce

just clone the repo 

`Sail up `
`sail composer install `
`sail artisan horizon`
`sail artisan migrate --seed`
`sail artisan scout:import "App\Models\Synthetiser"`
go to http://localhost:7700 to see meilisearch dashboard with the index 
go to http://localhost/admin and login with admin@example.com and password: password

### Reproduction repository

https://github.com/omar-karray/filament-scout-issue

**Comment by danharrin** [comment]
`applySearchToTableQuery()` needs to be on the List page, not the resource file
