### ISSUE TITLE
404 in slugable records

### ISSUE THREAD

**Issue by isaeken** [laravel-filament/filament#114]
a basic solution
`static::getModel()::where(self::getRouteKeyName(), $record)->firstOrFail();`

https://github.com/laravel-filament/filament/blob/9414a1aa80ae20b07e29707916c9d408efbe50e9/src/Resources/Pages/EditRecord.php#L58

**Comment by danharrin** [comment]
Sorry, what's the issue you're facing?

**Comment by isaeken** [comment]
i changed model route key name using getRouteKeyName (https://laravel.com/docs/8.x/routing#customizing-the-default-key-name)

the model urls is generating correctly but edit page returns 404. I'am fixed this in local using code in my first comment.

**Comment by danharrin** [comment]
Thanks! Will get a fix pushed out.

**Comment by danharrin** [comment]
Fixed by #167.
