### ISSUE TITLE
Unsaved alert when using FileUpload with S3

### ISSUE THREAD

**Issue by ArtDepartmentMJ** [laravel-filament/filament#11405]
### Package

filament/filament

### Package Version

v3.2.33

### Laravel Version

v10.43.0

### PHP Version

PHP 8.3.0

### Problem description

When using the FileUpload component with anAWS S3 image and there is an image popuated in a resource form and unsavedChangesAlerts are enabled in the panel it will always prompt you for unsaved changes even if none have been made.

It does not do this if using a local disk e.g. public

### Expected behavior

If no changes have been made it should not prompt for unsaved changes

### Steps to reproduce

1. Add an image FileUpload using an S3 disk to the resource
2. Upload an image
3. Save
4. Leaving the page will still prompt for unsaved chages

```
        return $form
            ->schema([
                FileUpload::make('image')
                    ->image()
                    ->disk('s3')
                    ->preserveFilenames()
            ]);
```

### Reproduction repository

https://github.com/ArtDepartmentMJ/filamnet_unsaved_changes_issue

**Comment by danharrin** [comment]
The reproduction repo is working with my own S3 bucket, so I am unsure how I can proceed with fixing this issue. But I would welcome any further investigation or information, and if anyone else has this issue too please get in touch.
