### ISSUE TITLE
Make custom component directories consistent

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#11413]
Potentially move custom form fields and table columns into `Filament/` in the app instead of top-level `Forms/` and `Tables/` directories.

**Comment by zepfietje** [comment]
@danharrin could you reference the commit that solves this issue? 🙂

**Comment by danharrin** [comment]
No sorry, it was done very early in v4 development and I don't really want to go back through the history, you can check the blame if you want

**Comment by zepfietje** [comment]
Aight, found it: https://github.com/filamentphp/filament/commit/19c142c232824a96442bf6c842cd8a7323ebb696.
Thanks!
