### ISSUE TITLE
SelectFilter ->relationship not returning results

### ISSUE THREAD

**Issue by emjay64** [laravel-filament/filament#11425]
### Package

filament/filament

### Package Version

v3.2.34

### Laravel Version

v10.44.0

### Livewire Version

v3.4.4

### PHP Version

8.2.15

### Problem description

With the change in https://github.com/filamentphp/filament/pull/11164 - 
The SelectFilter returns 0 results.

### Expected behavior

The SelectFilter should return the records belonging to the filtered parent_id.

### Steps to reproduce

Navigate to Listings Resource
From the filters select a ParentSku

### Reproduction repository

https://github.com/EmJay646/filament-select-filter

**Comment by blalmal10a** [comment]
I have the same/similar problem, select doesnt work with ->multiple() method chained to it, they are in a many to many relation. Can anyone provide temporary solution?

**Comment by LikeLown** [comment]
I'm not sure if it's the same issue, but for me, updating to the latest version through composer.json with "^3.2" instead of "3.2" resolved the problem, as it applied the fix from 20 days ago.

**Comment by danharrin** [comment]
Only an issue for recursive relationships
