### ISSUE TITLE
KeyValue doesn't seem to allow one to delete a row

### ISSUE THREAD

**Issue by telkins** [laravel-filament/filament#1142]
### Package

filament/filament

### Package Version

v2.8.1

### Laravel Version

v8.78.0

### Livewire Version

v2.8.2

### PHP Version

PHP 8.1.0

### Bug description

I have a KeyValue component for my form on a `HasManyRelationManager` class.

The attribute is `text` in the database and is cast to `'array'` in the model.

I have the following rule applied: `array:keyValue1,keyValue2`.

I can add rows and save the updated model without issue.  However, when I try to delete a row and save, it appears to save without issue, but the deleted row is still present.  That is, it doesn't actually delete the row...or persist it.

### Steps to reproduce

Please see Bug Description.

### Relevant log output

```shell
n/a
```

**Comment by danharrin** [comment]
As discussed on Discord, this is to do with the translatable package and not the field.
