### ISSUE TITLE
Failure to download information about the failed row when resolveRecord() returns null

### ISSUE THREAD

**Issue by jlsodai** [laravel-filament/filament#11456]
### Package

filament/filament

### Package Version

3.1

### Laravel Version

10.40.0

### PHP Version

PHP 8.1.27

### Problem description

Based on the code below, and as indicated in the [documentation](https://filamentphp.com/docs/3.x/actions/prebuilt-actions/import#updating-existing-records-when-importing-only), import will be skipped when no resolveRecord() returns null. This works well.

`
public function resolveRecord(): ?Product
{
    return Product::query()
        ->where('sku', $this->data['sku'])
        ->first();
}
`

However, a click to **download information about the failed row** results in an error.

<img width="1420" alt="image" src="https://github.com/filamentphp/filament/assets/10335555/2d5e2a40-000e-4742-9e86-a4feab79697e">

### Expected behavior

I expect to download a csv indicating rows which failed to import.

### Steps to reproduce

`public function resolveRecord(): ?Product
{
    return null;
}`

### Reproduction repository

https://github.com/jlsodai/issues/blob/main/resolveRecord.php

**Comment by zepfietje** [comment]
Please provide a reproduction repository with a fully working Laravel/Filament app.
