### ISSUE TITLE
BelongsToManyRelationManager throws an error when model policy viewAny is false

### ISSUE THREAD

**Issue by 4H1R** [laravel-filament/filament#1146]
### Package

filament/filament

### Package Version

v2.8.0

### Laravel Version

v8.77.1

### Livewire Version

v2.8.2

### PHP Version

PHP 8.1

### Bug description

When we have two resources and we allow user to access one of them from model policy and we don't allow the other one
when we want to edit the resource that we have access to it throws this error
ErrorException
Undefined array key 1 (View: /var/www/html/vendor/filament/filament/resources/views/components/resources/relation-managers/index.blade.php) 

but when we allow user to access both resources it works i think maybe the code doesn't check if **viewAny** is true or false before rendering the relationship table

### Steps to reproduce

1. Make two resources with model policies
2. allow all of the access to one resource and deny another resource
3. make belongs to many relationship between them
4. try to edit the resource that you have access to

**Comment by danharrin** [comment]
Fixed by #1189.
