### ISSUE TITLE
Create & Edit page cancel button navigation loop

### ISSUE THREAD

**Issue by Ticlext-Altihaf** [laravel-filament/filament#11460]
### Package

filament/filament

### Package Version

v3.2.34

### Laravel Version

v10.10

### PHP Version

8.3.3

### Problem description

After creating record, user redirected to `edit` page, if user click `Cancel` button on `edit` page, it will redirect to `create` page, and if user click `Cancel` button again, it will go back to `edit` page and so on.

It seems to be caused by #4430, the current behavior is nice as it allows you to go back to custom page, but this seem doesn't work on this scenario. I think using JavaScript `window.history.go(-1)` would allow current behavior while fixing this bug, but I'm not quite sure.

### Expected behavior

Current: Edit page -> Create page -> .... -> Edit page -> Create page 

Expected: Edit page -> Create page -> List page

### Steps to reproduce

```bash
wget https://filament-issue.unitedbycode.com/storage/filament-issue.zip
unzip filament-issue.zip
php artisan make:filament-resource -G User
php artisan serve
```

1. Open Dashboard
2. Go to "Users"
3. Click "New user" button
4. Fill out the form & create
5. Now it should be on Edit page, click "Cancel" button
6. Now on Create page, click "Cancel" button once more
7. We back on Edit page

https://github.com/filamentphp/filament/assets/77704356/580c88d0-1d09-46eb-8454-cafaaa05990e

### Reproduction repository

https://github.com/Ticlext-Altihaf/filament-issues-previous-url-loop

**Comment by danharrin** [comment]
Fixed by #11773.

**Comment by lotarbo** [comment]
@danharrin Hi. I have same problem. The Cancel button only scrolls to the top and changes the url. And only after a few clicks it returns to the list page
I use Tabs with persistTabInQueryString()

I think the first time you enter an entity - cancel should return back to the list.
And if we go through tabs - either return to the list or switch tabs in reverse order. Although it seems logical to return to the list at once, it's not a back button as it seems to me.

Filament v3.2.112

https://github.com/user-attachments/assets/f4f31989-e3b9-45a8-9d37-8b60d0fb3d08

**Comment by avinmaster** [comment]
Still. When you try to go to the previous page with browser navigation, it will remove query and then JS of tabs will add it again, so you can't return.
