### ISSUE TITLE
Not Obvious Where To Set Up Relationships Between Models

### ISSUE THREAD

**Issue by gurbaxani** [laravel-filament/filament#11475]
Hello! Please mention **which file to edit** while implementing this code. As a beginner, it's not obvious. Please update your docs to reflect this.

![image](https://github.com/filamentphp/filamentphp.com/assets/98401812/61716e82-b656-4be8-a63e-c815baf42233)

Thanks :)

**Comment by CodeWithDennis** [comment]
Why does Filament need to put this in their docs? If you want to know about it, just learn how Laravel models and relationships work.

https://laravel.com/docs/10.x/eloquent-relationships#main-content

**Comment by PetarKresimirCulina** [comment]
I agree, this isn't related to Filament, it is expected that you know the basic concepts of Laravel to begin with.
