### ISSUE TITLE
`Action::make()`throws "Typed property Filament\Tables\Actions\Action::$view must not be accessed before initialization" error

### ISSUE THREAD

**Issue by ralphjsmit** [laravel-filament/filament#1147]
### Package

filament/tables

### Package Version

v2.8.3

### Laravel Version

v8.78.0

### Livewire Version

v2.8.2

### PHP Version

PHP 8.1.1

### Bug description

I tried adding a "Print" action to my tables component. This threw the following error:

```
Typed property Filament\Tables\Actions\Action::$view must not be accessed before initialization (View: /...../vendor.nosync/filament/tables/resources/views/components/actions-cell.blade.php)
```

<img width="1180" alt="Schermafbeelding 2022-01-05 om 13 38 02" src="https://user-images.githubusercontent.com/59207045/148218826-d3f02b73-54bd-45df-9876-707723dd3a65.png">

### Steps to reproduce

Add the following function to your Livewire component:

```php
use Filament\Tables\Actions\Action;

protected function getTableActions(): array
{
    return [
        Action::make('Print')->action(fn ($record) => dump($record)),
    ];
}
```

### Relevant log output

```shell
See above for error output. Let me know if you need more of the stacktrace.
```

**Comment by danharrin** [comment]
Hey, you need to use an action that is documented - like `LinkAction` or `IconButtonAction`.

**Comment by ralphjsmit** [comment]
Hey Dan, ah I see! Sorry, I was slightly confused by that part in the docs. I read it more like 'a LinkAction is a special kind of action'.. :) Thanks!
