### ISSUE TITLE
Accessor applies twice to TextInput field on Form

### ISSUE THREAD

**Issue by Xodus-CO** [laravel-filament/filament#115]
**Describe the bug**
Table with products list, one column is Text for price and it is displayed correctly with the accessor applied.  The price field in the db is in pennies, so the accessor performs `return round($value /100, 2);`.

Click on product to edit screen which has a fieldset with price TextInput, it initially shows as fully pennies value (987), then flashes to .987, then displays .1 as the final value.    If I disable the accessor or set it to multiply by 10, the correct 'price' is displayed on the edit form, but obviously not the list table.

**Expected behavior**
I expected the accessor to be applied once to the TextInput field and the correctly formatted price to be displayed.

**Screenshots**

**Context**
- Browser: Firefox
- Server OS: Windows 10
- PHP version: 7.4.10
- Database: MariaDB 10.4.14

![filament_bug_list](https://user-images.githubusercontent.com/7006390/110250330-fda04500-7f37-11eb-8950-7373e5dfb4eb.PNG)
![filament_bug_form](https://user-images.githubusercontent.com/7006390/110250331-fe38db80-7f37-11eb-9721-d825dc8d3c5c.PNG)

**Comment by Xodus-CO** [comment]
I've just got the accessor on the model only.

`
    public function getPriceAttribute($value)
    {
        return round($value / 100,2);
    }`

  ```
public static function form(Form $form)
    {
        return $form
            ->schema([
                        Components\Grid::make([
                            Components\TextInput::make('name')->autofocus()->required(),
                            Components\BelongsToSelect::make('menu_category_id')
                                ->label('Category')
                                ->relationship('menu_category', 'name'),
                            ])
                            ->columns(2),
                        Components\Fieldset::make(
                            'Pricing',
                            [
                                Components\TextInput::make('price')->required(),
                                Components\Checkbox::make('special')->label('Special?'),
                                Components\Checkbox::make('limited')->label('Limited?'),
                                Components\Checkbox::make('active')->label('Active?'),

                            ]
                        )
```


```

public static function table(Table $table)
    {
        return $table
            ->columns([
                Columns\Text::make('vendor.name')
                    ->searchable()
                    ->sortable(),

                Columns\Image::make('image')
                    ->disk('local') // Set a custom disk that images should be read from.
                    ->height($height = 40), // Set the height of the image in pixels.

                Columns\Text::make('price')->currency($symbol = '$'),

            ])
```

**Comment by jamessessford** [comment]
Cheers @Xodus-CO, I'll try to look a bit further into this tonight

**Comment by jamessessford** [comment]
@Xodus-CO are you on the latest version of the package? I've just tried the same logic as you have provided above and didn't have any problems with how the price displayed.

The only extra thing I had to add was a mutator to set the value back to pennies before inserting in the database

**Comment by ryangjchandler** [comment]
@jamessessford Thanks for trying. I've marked this as cannot reproduce for the time being.

**Comment by Xodus-CO** [comment]
I was on 1.44, updated to 1.46, same issue.  Added mutator on product model and it now displays fine in both places.

So being an Input in the form vs a 'display' on the table definitely makes it think it changed.

Thanks and sorry for the false alarm.
