### ISSUE TITLE
Exporter does not export related columns

### ISSUE THREAD

**Issue by darkraul79** [laravel-filament/filament#11500]
Are this Closed????

I still have the same issue on v3.2.0

![Captura de pantalla 2024-02-20 124902](https://github.com/filamentphp/filament/assets/9088326/f98ff7d9-98c4-4bd9-90cf-a6c87321b0a9)

When I do the export, it only exports the columns that are not related.

![Captura de pantalla 2024-02-20 125450](https://github.com/filamentphp/filament/assets/9088326/6e96c224-fb62-4b4b-b165-04fd6ad27840)

![Captura de pantalla 2024-02-20 123658](https://github.com/filamentphp/filament/assets/9088326/58dd0da5-fcb8-4e69-b38c-aeccad9eefbd)

Of course, the models are well related, since they appear correctly in the list of records.

![Captura de pantalla 2024-02-20 125538](https://github.com/filamentphp/filament/assets/9088326/73e53e82-2da9-4539-bd46-1a241e4036fa)

_Originally posted by @darkraul79 in https://github.com/filamentphp/filament/issues/10835#issuecomment-1954060741_

**Comment by danharrin** [comment]
It was released in [v3.2.4](https://github.com/filamentphp/filament/releases/tag/v3.2.4).
