### ISSUE TITLE
CheckboxList not working when using statePath

### ISSUE THREAD

**Issue by ernoferrari** [laravel-filament/filament#11507]
### Package

filament/filament

### Package Version

v3.2.35

### Laravel Version

v10.45.0

### Livewire Version

v3.4.6

### PHP Version

8.2.1

### Problem description

I have a custom page with form and I have set a statePath. ChecboxList works like a single checkbox field. But if I remove the statePath call, then it works right.

### Expected behavior

CheckboxList should set state as array with selected options but now it just set the value to true.

### Steps to reproduce

Add statePath to your form and add CheckboxList component, like here: https://github.com/ernoferrari/filament-checkboxlist-issue/blob/main/app/Filament/Pages/IssuePage.php

### Reproduction repository

https://github.com/ernoferrari/filament-checkboxlist-issue

**Comment by zepfietje** [comment]
Make sure to fill the form as per the docs: https://filamentphp.com/docs/3.x/forms/adding-a-form-to-a-livewire-component#adding-the-form.

**Comment by MoShirv** [comment]
I have the same problem .

**Comment by ernoferrari** [comment]
@MShJSTM Just add this code to the page and it should work:

`public function mount(): void
    {
        $this->form->fill();
    }
`
