### ISSUE TITLE
Internal data leaking to the client browser using the Edit form

### ISSUE THREAD

**Issue by wq9578** [laravel-filament/filament#11562]
### Package

filament/filament

### Package Version

v3.2.34

### Laravel Version

v10.44.0

### Livewire Version

v3.4.4

### PHP Version

PHP 8.3.1

### Problem description

Internal data leaking to the client browser using the Edit form, for example JSON like the following:
```
record:Array[2]
    0:null
    1:Object
	class:"App\Models\Flight"
	key:25
	s:"mdl"
```

Biggest problem:
1. Exposing the auto-incremented ID is what should not happen.
The `int` primary key (in this example 25) should not be used, but instead the `uuid` field used for the routes also:
```
    public function getRouteKeyName(): string
    {
        return 'uuid';
    }
```
Internally the incrementing primary key remains, but externally only the UUID should be used, as, for example, discussed in "[Utilizing UUID as a Secondary Key in Laravel](https://medium.com/@laravelprotips/uuid-in-laravel-a-simple-guide-55cdc4642d43#5539)".
Example route (with multi-tenancy): `http://127.0.0.1:8000/testpanel/123456789/flights/06f11502-5c99-43ef-9332-4943d380507c/edit`

Smaller issue:
2. The class "App\Models\Flight" is exposed.

### Expected behavior

1. Only the UUID (the field specified in `getRouteKeyName()`) should be transmitted to the browser, not the primary key.
2. Some obfuscation should be used instead of the class name, for example its SHA-256 hash.

### Steps to reproduce

1. Run in terminal: `git clone https://github.com/wq9578/filament-issue-data-leakage.git`
2. Run in terminal: `cd filament-issue-data-leakage/filament-issue/ && composer install && php artisan serve`
3. Open website at http://127.0.0.1:8000 and click: Sign In > Flights > Edit [single row]
4. View page source and search for: Models\

Current URL maintains privacy by exposing the UUID only (e.g., http://127.0.0.1:8000/admin/flights/e7b25d4e-def8-4c1d-a5dc-71773ae6face/edit), but within the JSON data the model class (`App\Models\Flight`) and internal primary key (`1`) are transmitted.

Pretty JSON:
```
record:Array[2]
    0:null
    1:Object
	class:"App\Models\Flight"
	key:1
	s:"mdl"
```

Raw HTML: `{&quot;class&quot;:&quot;App\\Models\\Flight&quot;,&quot;key&quot;:1,&quot;s&quot;:&quot;mdl&quot;}`

### Reproduction repository

https://github.com/wq9578/filament-issue-data-leakage

**Comment by danharrin** [comment]
Filament uses Livewire to persist the model. This is Livewire behaviour.

I don't know about the key obfuscation, you should probably report it to Livewire if you expect different behaviour. For the class name, I think you can hide it if you define a morph map entry for that model?

**Comment by wq9578** [comment]
Thanks a lot!

> Filament uses Livewire to persist the model. This is Livewire behaviour.
> 
> I don't know about the key obfuscation, you should probably report it to Livewire if you expect different behaviour.

Reported to Livewire here: https://github.com/livewire/livewire/discussions/8141


> For the class name, I think you can hide it if you define a morph map entry for that model?

It worked following the instructions at https://laravel.com/docs/11.x/eloquent-relationships#custom-polymorphic-types:

> You may call the enforceMorphMap method in the boot method of your App\Providers\AppServiceProvider class or create a separate service provider if you wish.
