### ISSUE TITLE
Custom Infolist Repeatable Entry form field is getting hidden

### ISSUE THREAD

**Issue by AravindRam-Ranium** [laravel-filament/filament#11590]
### Package

filament/filament

### Package Version

3.2

### Laravel Version

10.10

### Livewire Version

3.0

### PHP Version

8.1

### Problem description

On a custom `Infolist` page, I have tried to generate dynamic form fields with [Core concept](https://filamentphp.com/docs/3.x/support/overview)  inside the custom `ViewEntry`. If i submit an Infolist submit action button the form fields become invisible. 

### Expected behavior

When I click the action button from Infolist, I have to validate all dynamic form fields and show the validation messages under the respective form fields. 

### Steps to setup & replicate issue

1. Clone and install composer
2. Please use .env.example for environment values
3. Create a database with the name "repeatable_entry_issue" 
4. Migrate and seed (php artisan migrate:fresh --seed)
5. Use any user from the table to login as admin and use the "password" word as a password
6. After the login, you will be redirected to the "consent-option-request" page
7. If you click the "Save consent" button you get an alert notification. the form fields will get wiped out.

We have to show the validation messages on every form field after the [validation](https://github.com/akshaybokaderanium/filament-repeatable-entry-issue-repro/blob/724d99e0af726cf7880f4047ea3d841dfc1c7d98/app/Livewire/ConsentRequest.php#L142).

Livewire Component class : https://github.com/akshaybokaderanium/filament-repeatable-entry-issue-repro/blob/724d99e0af726cf7880f4047ea3d841dfc1c7d98/app/Livewire/ConsentRequest.php#L95

Blade file : https://github.com/akshaybokaderanium/filament-repeatable-entry-issue-repro/blob/724d99e0af726cf7880f4047ea3d841dfc1c7d98/resources/views/infolist/consent-option-checkbox.blade.php

### Reproduction repository

https://github.com/akshaybokaderanium/filament-repeatable-entry-issue-repro

**Comment by zepfietje** [comment]
Looks like you're meaning to use form repeater instead of an infolist?
https://filamentphp.com/docs/3.x/forms/fields/repeater

**Comment by danharrin** [comment]
Livewire is not able to persist an Eloquent collection (`$this->collections`) between requests.

As such, you should define a getter method that can be used to retrieve the collections:

```php
RepeatableEntry::make('collections')
    ->label('')
    ->state($this->getCollections())
```

```php
public function mount(): void
{
    $this->user = auth()->user();

    if (!$this->user) {
        abort(403, 'Forbidden User');
    }

    if ($this->getCollections()->count() < 1) {
        abort(403, 'No required consent');
    }
}

protected function getCollections()
{
    return $this->user->outstandingConsents();
}
```

```php
->collapsed(function (ConsentOption $record) {
    $first = $this->getCollections()->first();
    return  !($first->id === $record->id);
})
```
