### ISSUE TITLE
`make:filament-resource` fails when using the `--generate` option

### ISSUE THREAD

**Issue by RalphMRivera** [laravel-filament/filament#11606]
### Package

filament/filament

### Package Version

v3.2.39

### Laravel Version

10.46.0

### Livewire Version

v3.4.6

### PHP Version

8.2.15

### Problem description

The `make:filament-resource` command fails when using the `--generate` option.

### Expected behavior

A resource should be generated with a table and form pre-populated as per [Automatically generating forms and tables](https://filamentphp.com/docs/3.x/panels/resources/getting-started#automatically-generating-forms-and-tables).

### Steps to reproduce

- Install filament
- Use `php artisan make:model Flight --migration` to create a model and migration.
- Add a few columns to the Flight migration.
- Migrating the database or not does not affect this bug. I tried both ways.
- Run `php artisan make:filament-resource Flight --generate`

### Reproduction repository

https://github.com/RalphMRivera/filament-issue

### Relevant log output

```shell
~/Projects/filament-issue [main] php artisan make:filament-resource Flight --generate

   TypeError

  Filament\Commands\MakeResourceCommand::getModelSchema(): Return value must be of type Illuminate\Support\Facades\Schema, Illuminate\Database\Schema\SQLiteBuilder returned

  at vendor/filament/support/src/Commands/Concerns/CanReadModelSchemas.php:27
     23▕     protected function getModelSchema(string $model): Schema
     24▕     {
     25▕         return app($model)
     26▕             ->getConnection()
  ➜  27▕             ->getSchemaBuilder();
     28▕     }
     29▕
     30▕     protected function getModelTable(string $model): string
     31▕     {

      +14 vendor frames

  15  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
```

**Comment by dreftas** [comment]
Same issue for me.

**Comment by petrisorcraciun** [comment]
https://github.com/filamentphp/filament/pull/11604
