### ISSUE TITLE
Got Call to a member function auth() on null error on filament testing

### ISSUE THREAD

**Issue by amirrezashahidi83** [laravel-filament/filament#11645]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

v10.10

### Livewire Version

v3.3

### PHP Version

php 8.1

### Problem description

Hi. I'm writing some tests to check if creating admin process is right. But I got this error:
Call to a member function auth() on null (View: C:\Users\AmirReza\Desktop\Projects\risman-admin\storage\framework\views\a168b0ebcff266df6b662fc4b6d06e88.blade.php)

```
<?php
namespace Tests\Feature;

use function Pest\Livewire\livewire;
it('creates admin',function () {
        livewire(\App\Filament\Resources\AdminResource\Pages\CreateAdmin::class)
        ->fillForm([

        ])
        ->call('create')
        ->assertHasNoFormErrors();
    }
);
```

### Expected behavior

pass my test

### Steps to reproduce
just install packages using composer install and run tests using pest and you will see the error
### Reproduction repository

https://github.com/amirrezashahidi83/risman-admin

**Comment by chengkangzai** [comment]
aren't this expected behaviour? 
i think you should create a user and login with that user 

```php
it('creates admin',function () {

    $user = User::factory()->create();
    actingAs($user);

        livewire(\App\Filament\Resources\AdminResource\Pages\CreateAdmin::class)
        ->fillForm([

        ])
        ->call('create')
        ->assertHasNoFormErrors();
    }
);
```

**Comment by amirrezashahidi83** [comment]
Thanks for your replay But it didn't worked.
I used `dd(auth()->user()); `to check my user data and  it was ok,I can test target page successfuly
`    $response = $this->get('/admins/create');
    $response->assertStatus(200);
`

**Comment by chengkangzai** [comment]
hmm does it mean that `auth()->user()` return an null?

**Comment by amirrezashahidi83** [comment]
No I mean I can see user data without any problem. Here is output of dd():
`App\Models\Admin {#3090
  #connection: "mysql"
  #table: "admins"
  #primaryKey: "id"
  #keyType: "int"
  +incrementing: true
  #with: []
  #withCount: []
  +preventsLazyLoading: false
  #perPage: 15
  +exists: true
  +wasRecentlyCreated: false
  #escapeWhenCastingToString: false
  #attributes: array:12 [
    "id" => 1
    "name" => "admin"
    "username" => "admin"
    "password" => "$2y$10$q1a0QkbWo0uCKxZKo6IFaODkx/KNO0ndJj8JiwzDlcrL4ZOufc9ma"
    "merchant_id" => "80b03beb-5c77-4b95-9c08-891a5fbeab30"
    "email" => ""
    "remember_token" => "DwQA11AyzRquqRzhTEGmNrjsSNyjS47fEjeZ6E8DMae2Of0XMxfMcXubMwsi"
    "created_at" => "2022-12-19 14:44:08"
    "updated_at" => "0000-00-00 00:00:00"
    "role" => "super"
    "school_id" => null
    "mobile_token" => ""
  ]
  #original: array:12 [
    "id" => 1
    "name" => "admin"
    "username" => "admin"
    "password" => "$2y$10$q1a0QkbWo0uCKxZKo6IFaODkx/KNO0ndJj8JiwzDlcrL4ZOufc9ma"
    "merchant_id" => "80b03beb-5c77-4b95-9c08-891a5fbeab30"
    "email" => ""
    "remember_token" => "DwQA11AyzRquqRzhTEGmNrjsSNyjS47fEjeZ6E8DMae2Of0XMxfMcXubMwsi"
    "created_at" => "2022-12-19 14:44:08"
    "updated_at" => "0000-00-00 00:00:00"
    "role" => "super"
    "school_id" => null
    "mobile_token" => ""
  ]
  #changes: []
  #casts: []
  #classCastCache: []
  #attributeCastCache: []
  #dateFormat: null
  #appends: []
  #dispatchesEvents: []
  #observables: []
  #relations: []
  #touches: []
  +timestamps: true
  +usesUniqueIds: false
  #hidden: []
  #visible: []
  #guarded: []
  #rememberTokenName: "remember_token"
  -roleClass: null
  -permissionClass: null
  -wildcardClass: null
  -wildcardPermissionsIndex: ? array
} // tests\Feature\CreateResourcesTest.php:11`

**Comment by chengkangzai** [comment]
I notice few problem after cloning your repo

1. Your livewire keep giving 419 Problem, which solve by adding it to VerifyCSRFToken Middleware. [Ref](https://stackoverflow.com/questions/67782936/laravel-livewire-element-after-leave-a-text-field-gives-error-419)
2. You did not install livewire pest plugin  https://pestphp.com/docs/plugins#content-livewire
3. Your Migration File is wrong, maybe you created your database schema manually without using laravel migration system ( there is no migration script for creating a admin table)
4. You should use `RefreshDatabase` trait to get phpunit to automatically refresh your database while you test.

I suggest you to take a deeper dive on study in laravel <3 

Cheers!

**Comment by amirrezashahidi83** [comment]
It solved. I had to inject AdminPanelProvider in my tests
