### ISSUE TITLE
SpatieMediaLibraryFileUpload refetches images whenever Select field is changed

### ISSUE THREAD

**Issue by zzkevinlim** [laravel-filament/filament#1165]
### Package

filament/filament

### Package Version

v2.8.3

### Laravel Version

v8.78.1

### Livewire Version

v2.8.2

### PHP Version

PHP 8.0.13

### Bug description

When editing an existing entry, SpatieMediaLibraryFileUpload field re-fetches all of its images every time user interacts with any Select fields (with relationship attached) on the form.

EDIT: This bug also interrupts SpatieMediaLibraryFileUpload from finishing its media upload process if user interacts with any Select field (with relationship attached) in the mean time.

### Steps to reproduce

1. Create a resource, its form must contain at least one SpatieMediaLibraryFileUpload field and one Select field.
2. Create a new entry, upload a few images to SpatieMediaLibraryFileUpload field, select any options on the Select field.
3. Spatie Media must be using S3, file visibility is private for all files uploaded.
4. Edit the same entry, now try selecting another option on that Select field, you will notice SpatieMediaLibraryFileUpload will refetch all  its images submitted on step 2.

**Comment by danharrin** [comment]
Hi, I can't replicate this. Is it still an issue?

**Comment by zzkevinlim** [comment]
@danharrin Unfortunately, it still is.

**Comment by zzkevinlim** [comment]
![image](https://user-images.githubusercontent.com/12163198/148894766-a41f4b9b-a445-489d-8af3-a2925b77183f.png)

**Comment by danharrin** [comment]
Should be fixed by #1201.
