### ISSUE TITLE
The Password and password confirmation must match.

### ISSUE THREAD

**Issue by chrisAlkemy** [laravel-filament/filament#1167]
### Package

filament/filament

### Package Version

1.13.4

### Laravel Version

8.78.1

### Livewire Version

2.8.2

### PHP Version

7.4.27

### Bug description

On the create user page, the password field and confirm password are the same but an error message is generated saying: The Password and password confirmation must match.

### Steps to reproduce

1. go to "Manage Users"
2. Click on "Create"
3. Fill de fields
4. Click on "Create" or "Create & Create another"

**Comment by danharrin** [comment]
Hi, we've dropped bug fix support for v1. However, if you create a PR then I will merge it and tag a new release. Please upgrade to v2 :)
