### ISSUE TITLE
ERROR in an optional parameter of a route when update Filament from 3.0.92 to 3.2.4

### ISSUE THREAD

**Issue by jals-es** [laravel-filament/filament#11671]
### Package

filament/filament

### Package Version

v3.2.4

### Laravel Version

v10.46.0

### Livewire Version

v3.4.6

### PHP Version

8.2.15

### Problem description

**When update filament from 3.0.92 to 3.2.4, it trows this error:**

`Cannot use positional argument after named argument during unpacking`

`vendor/livewire/livewire/src/Features/SupportLifecycleHooks/SupportLifecycleHooks.php(21)`

I debug and i can see that it have an array with:
```
$params = [
      'project' => 'test',
      'build' => 1003394,
      0 => null
]
```

I think this is because I have an optional param in the url.

`Pages\ViewBuildVisualTests::route('/{project: name}/builds/{build: name}/{selectedScreenshot?}')`

### Expected behavior

That it did not give an error when loading the page.

### Steps to reproduce

1. Mount the project and the database runing migrations. 
2. Run db:seed.
3. Login into filament panel.
4. Go to TestResource and create one.
5. Click to view the record and **it trows the error**. `URL EXAMPLE: http://localhost/admin/tests/1`
6. Add some extra parameter in the url to fill the optional parameter and it works. `URL EXAMPLE: http://localhost/admin/tests/1/randomstring`

So as you can see the optional parameter are not working.

### Reproduction repository

https://github.com/jals-es/filament-issue

**Comment by danharrin** [comment]
Bug in dependency: https://github.com/livewire/livewire/discussions/7914
