### ISSUE TITLE
Action Modal Would not open 

### ISSUE THREAD

**Issue by chengkangzai** [laravel-filament/filament#11678]
### Package

filament/filament

### Package Version

v3.2.43

### Laravel Version

v10.46.0

### Livewire Version

v3.4.6

### PHP Version

PHP 8.3.3

### Problem description

Action that suppose to show a modal for user to fill up form doesn't appear.
Video as attached

https://github.com/filamentphp/filament/assets/43839286/cf1a2e99-a2d1-4ad7-8db5-f04467185e38

### Expected behavior

Show up a modal that show the form for user 

### Steps to reproduce

1. Create a new laravel project
2. Require Livewire , Filament 
3. Create a new page without resource
4. Implement that class with `HasTable`
5. use `HasWizard` and `InteractsWithTable` trait.
6. proceed to create table and wizard
7. Add A Action that have `->steps()` method to header action
8. Click The header action, it doesnt show up the pop up

### Reproduction repository

https://github.com/chengkangzai/filament-page-table-conlict-reproduce-repo

**Comment by ghostzero** [comment]
I can reproduce this bug using `filament/filament: v3.2.34`:

1. Create a `Action` in `getHeaderActions`:

```php
Actions\Action::make('cancel') // the cancel word takes a key part here (i guess)
    ->action(fn (VendorOrder $record) => $record->cancel())
    ->requiresConfirmation(),
```

2. Reload site & click button

3. Wait for `update` request to finish. It triggers `close-modal`, but expected is `open-modal`.

```
{
    "components": [
        {
            "snapshot": "....",
            "effects": {
                "returns": [
                    null
                ],
                "html": "...",
                "dispatches": [
                    {
                        "name": "close-modal",
                        "params": {
                            "id": "9GlBRvIXyn8EBAYwiVJn-action"
                        }
                    }
                ]
            }
        }
    ],
    "assets": []
}
```

The thing i saw is that if i rename the action to `confirm_cancel`, it will return `open-modal`. So i guess it has something to do with the action name. e.g:

```php
Actions\Action::make('confirm_cancel') // works as expected
    ->action(fn (VendorOrder $record) => $record->cancel())
    ->requiresConfirmation(),
```

**Comment by chengkangzai** [comment]
I dont think this is the problem that causes this problem. 
As you can see in the reproduction repository, the name doesnt include cancel in the `make` method.

**Comment by sylfel** [comment]
Hi

I had nearly same problem, without table.
This is my example code : 

```php
    public function addToCategoryAction(): Action
    {
        return Action::make('addToCategory')
            ->form([
                TextInput::make('title')
                    ->required()
                    ->maxLength(255),
            ])
            ->action(function (array $data): void {
                dd($data);
            });
    }
```

If a change `addToCategory` in ` return Action::make('addToCategory')` to anything else, form doesn't appear !

**Comment by danharrin** [comment]
If you use `InteractsWithTables`, Filament assumes you are rendering the table.

Table actions and header actions use the same modal HTML.

Since the table renders its own modal HTML, we omit Filament's modal HTML to avoid it getting rendered twice.

When not rendering a table but using `InteractsWithTables`, add `<x-filament-actions::modals />`.

**Comment by chengkangzai** [comment]
Thanks @danharrin for the enlightenment.
i realised i didnt setup the table properly because i only implements`HasTables` without implements `HasForms` ( and `InteractsWithFroms`)

it works after i implement and use it following the guide [here](https://filamentphp.com/docs/3.x/tables/adding-a-table-to-a-livewire-component#adding-the-table)
