### ISSUE TITLE
how to disabled next tabs in each tab | filament

### ISSUE THREAD

**Issue by matinrajabi** [laravel-filament/filament#11689]
### Package

filament/forms

### Package Version

v3

### Laravel Version

v10.10

### PHP Version

8.1

### Problem description

hello guys i want to create tab for my form but i want to disable the others tab until this tab fields complete.

i can't use wizard because in tab 1 i want to use wizard for one of my field which is something like this : (category > subcat1 > subcat2 > ... > subcat(n) ), So i can't use wizard into wizard and i must use tab.

thanks for your help :)

### Expected behavior

now i use tab and all tabs are available but the rest of form is dependent to user selection in category field 

### Steps to reproduce

if anybody can help to fix this problem OR can suggest me another way to have a nested selection for categories with different children which rest of the fields are depend on the selected category, i will appreciate a lot 

(i don't want to talk this much but there are endless questions here =_=)

### Reproduction repository

https://github.com/matinrajabi/digi_v3

**Comment by zepfietje** [comment]
Reproduction repository is not available.
Also this sounds like more of a support request than an actual issue, so please create a help thread on our Discord server, or start a discussion here on GitHub.
Thanks! 🙂
