### ISSUE TITLE
repeater form sort icon in rtl direction Is on the right

### ISSUE THREAD

**Issue by mohammad2306** [laravel-filament/filament#1168]
### Package

filament/filament

### Package Version

2.8.3

### Laravel Version

8.78

### Livewire Version

2

### PHP Version

8

### Bug description

![image](https://user-images.githubusercontent.com/61474718/148599063-271f7342-8fdc-4c2a-a034-63028fa3b7e5.png)

**Comment by danharrin** [comment]
Hey, I'm not an expert in RTL design, so while this project supports RTL layouts, I am not actively working on them. If you'd like to see this fix, please submit a PR or wait for someone who knows what they're doing to.

**Comment by babakfp** [comment]
Why did you close the issue?🤦‍♂️😂. So you don't know how to fix this issue, at least don't close it so other people can see it and maybe they decide to fix it.
@danharrin
