### ISSUE TITLE
Using closure on Table column action does not work

### ISSUE THREAD

**Issue by tiagof** [laravel-filament/filament#11696]
### Package

filament/filament

### Package Version

v3.2.43

### Laravel Version

v10.46

### Livewire Version

v3

### PHP Version

PHP 8.2

### Problem description

This works (shows confirmation):
````
Tables\Columns\TextColumn::make('name')
    ->action(Tables\Actions\Action::make('test')->requiresConfirmation()),
`````
This does not:
````
Tables\Columns\TextColumn::make('name')
    ->action(fn () => Tables\Actions\Action::make('test')->requiresConfirmation()),
````

### Expected behavior

Using a closure to, for example, decide the action to trigger, should work.

### Steps to reproduce

See problem description.
Add a column with a closure as the ->action() parameter:
````
Tables\Columns\TextColumn::make('name')
    ->action(fn () => Tables\Actions\Action::make('test')->requiresConfirmation()),
````

### Reproduction repository

https://github.com/tiagof/filament-bugs-report/tree/table-column-action-bug

**Comment by danharrin** [comment]
Closures in this case are run when the cell is clicked, and are not used to register actions. We cannot use the syntax to do both

**Comment by tiagof** [comment]
Ok...but it seems a bit inconsistent with all the other methods that receive Closures.

Any suggestion on how to have 2+ actions on a table column and decide which one to trigger based on some record property?

Thanks!

**Comment by danharrin** [comment]
What is different about the actions?

**Comment by tiagof** [comment]
Several things. The actual code I'd like to write:

```
->action(fn (ActionRequest $record) => match ($record->actionType) {
    ActionType::MAIL => EditDestination::makeTableAction(),
    ActionType::DOC => EditTasks::makeTableAction(),
    default => null,
})
```

**Comment by danharrin** [comment]
There isn't going to be an easy way to do that at the moment

**Comment by danharrin** [comment]
You can access `$record` in the functions of the action objects themselves so you can attempt to customise the modal content based on that etc

**Comment by danharrin** [comment]
And of course, you can add as many normal actions to each row as you want instead of using a column

**Comment by tiagof** [comment]
> And of course, you can add as many normal actions to each row as you want instead of using a column

Yeah...I'll probably revert to that!

Thanks!!
