### ISSUE TITLE
Select field with Multi-Tenancy does not work correctly

### ISSUE THREAD

**Issue by mi-lopez** [laravel-filament/filament#11709]
### Package

filament/forms

### Package Version

v3.2.44

### Laravel Version

v10.47.0

### Livewire Version

v3.4.7

### PHP Version

PHP 8.2.15

### Problem description

Following the Multi-Tenancy guide everything seems to work correctly https://filamentphp.com/docs/3.x/panels/tenancy. Except when using the creation of a relationship through a modal https://filamentphp.com/docs/3.x/forms/fields/select#creating-a-new-option-in-a-modal

When trying to save a value inside the modal, it does not automatically add the value of the Model defined as Tenancy (Company) for example, a postgreSQL error appears saying that `Not null violation: 7 ERROR: null value in column "company_id" of relation "owners" violates not-null constraint`

### Expected behavior

The value for `company_id` should be detected automatically, in the same way that a form outside the scope of a modal window does.

### Steps to reproduce

1. Start proyect and go to http://localhost:8000/app/
2. Create an account on http://localhost:8000/app/register
3. Create a new Company with any name
4. Navigate to http://localhost:8000/app/1/patients
5. Create new Patient
6. Click on the + Owner Select to create a New Owner
7. Fill the form and Create a new Owner
8. See the error `SQLSTATE[23502]: Not null violation: 7 ERROR: null value in column "company_id" of relation "owners" violates not-null constraint DETAIL: `

### Reproduction repository

https://github.com/mi-lopez/filament-multi-tenancy-select-form

**Comment by danharrin** [comment]
<img width="830" alt="Screenshot 2024-03-06 at 12 02 16" src="https://github.com/filamentphp/filament/assets/41773797/3d2b6012-80b7-4d6d-b2d3-bd51c71a2575">

`->createOptionUsing(fn ($data) => Filament::getTenant()->owners()->create($data))`
