### ISSUE TITLE
Performance issues with predefined options in Forms\Components\Select

### ISSUE THREAD

**Issue by DistantOrbit** [laravel-filament/filament#1170]
### Package

filament/filament

### Package Version

filament/filament v2.7.0

### Laravel Version

laravel/framework v8.77.1

### Livewire Version

livewire/livewire v2.8.2

### PHP Version

PHP 8.1.1

### Bug description

Noticable delay between select element's options are loaded and the previously set value is populated. 

### Steps to reproduce

With a new filament project set up: 

* Create a resource
* Add a select field to the resource's form, for example:

```
Forms\Components\Select::make('language_id')
                    ->label('Language')
                    ->required()
                    ->options(Language::all()->pluck('name', 'id'))
                    ->searchable(),
```

* In filament admin, create an new instance of the resource, assign a value to the select and save it
* Go to the newly created instance's edit page and watch as the select renders, it will go from empty with loader/spinner to "Select an option" (loader disappears) and then finally to display the previously assigned value, but with a noticable delay for this last step.

**Comment by danharrin** [comment]
Fixed by #1202! Will be much better in the next release.
