### ISSUE TITLE
Customer's section on the demo is not working

### ISSUE THREAD

**Issue by elfeffe** [laravel-filament/filament#1171]
### Package

filament/filament

### Package Version

2

### Laravel Version

i

### Livewire Version

2

### PHP Version

8

### Bug description

https://demo.filamentadmin.com/shop/customers

### Steps to reproduce

visit https://demo.filamentadmin.com/shop/customers

### Relevant log output

```shell
none
```

**Comment by danharrin** [comment]
Thanks, this is being fixed.
