### ISSUE TITLE
Can't resolve info list entry in closures

### ISSUE THREAD

**Issue by mokhosh** [laravel-filament/filament#11723]
### Package

filament/filament

### Package Version

v3.2.44

### Laravel Version

v11.0-dev

### Livewire Version

v3.4.7

### PHP Version

8.3.3

### Problem description

We can resolve table columns by passing them to closures like this:

```php
use Filament\Tables\Columns\Column;

$this->formatStateUsing(function (Column $column, $state): ?string {
    return $columns->something();
});
```

And you would think we can do the same with infolist entries, but we can't:

```php
use Filament\Infolists\Components\Entry;

$this->formatStateUsing(function (Entry $entry, $state): ?string {
    return $entry->something();
});
```

Results in:

```
Unresolvable dependency resolving [Parameter #0 [ <required> string $name ]] in class Filament\Infolists\Components\Entry
```

### Expected behavior

This should be able to resolve the entry on which `formatStateUsing` is being called on.

### Steps to reproduce

Steps are in the Read Me https://github.com/mokhosh/filament-bug-reproduction/blob/main/README.md

### Reproduction repository

https://github.com/mokhosh/filament-bug-reproduction

**Comment by danharrin** [comment]
It's `$component`, not `$entry`, same as forms.

**Comment by mokhosh** [comment]
thanks. is this then a documentation issue? or is it there, and it's an attention disorder on my part?
