### ISSUE TITLE
Pagination buttons and table filter datepicker popover are competing on the z-index with the selected page popping through

### ISSUE THREAD

**Issue by Cigoler** [laravel-filament/filament#1172]
### Package

filament/tables

### Package Version

v2.8.3

### Laravel Version

v8.78.1

### Livewire Version

v2.5

### PHP Version

PHP 8

### Bug description

![image](https://user-images.githubusercontent.com/2905728/148654612-a01f60d7-e124-4a6a-9636-69316816250a.png)

Just a little thing. The selected pagination page button is showing up through popovers on the filter popup.

For some reason it has z-10 class applied. Not sure if that is intentional or not, but without it works fine.

![image](https://user-images.githubusercontent.com/2905728/148654799-9e77c463-bea3-4b11-afbc-a7c3c1285763.png)

**Comment by danharrin** [comment]
Closed by #1186.
