### ISSUE TITLE
Filament\FilamentManager::getUserName(): Return value must be of type string, null returned 

### ISSUE THREAD

**Issue by lilouch** [laravel-filament/filament#1173]
### Package

filament/filament

### Package Version

V2.0

### Laravel Version

V.8

### PHP Version

8.0

### Bug description

I have changed the user table on my db to able to have : firstname, lastname and username.
However, Filament Admin use 'name". So, I have encountered this error when I connect to my filament admin portal

`Filament\FilamentManager::getUserName(): Return value must be of type string, null returned 
`
```
    public function getUserName(Model $user): string

    {

        if ($user instanceof HasName) {

            return $user->getFilamentName();

        }
        return $user->getAttributeValue('name');
    }
```

I have modified the file but I cannot rely on it.

Is there a way to handle that ? For example include `'$firstname' . '$lastname'`  ?

thank you in advance

**Comment by bezhanSalleh** [comment]
@lilouch yes there is. all you have to do is implement the `HasName` interface the comes with filament.
in your `User` mode:
```php
class User extends Authenticatable implements HasName
{
    public function getFilamentName(): string
    {
        return $this->fullName;
    }

    /**
   * Get the user's full name.
   *
   * @return string
   */ 
    public function getFullNameAttribute()
    {
        return "{$this->first_name} {$this->last_name}";
    }
    ...
}
```
or you can just return your `username` instead, whatever works best for ya.

**Comment by danharrin** [comment]
Thanks @bezhanSalleh!

**Comment by gldtn** [comment]
Hey @danharrin 

Hope you're doing well! Maybe this might make the Filament docs even more user-friendly. Currently, the documentation suggests adding the following to the User model:
 
 ```php
 class User extends Authenticatable implements FilamentUser, HasName
{
    // ...
 
    public function getFilamentName(): string
    {
        return "{$this->first_name} {$this->last_name}";
    }
}
```
I initially had a bit of trouble with this, but then I stumbled upon this issue.

I was thinking, perhaps including this example in the documentation might help clarify things, especially for those who are relatively new to this, like myself.

I believe this little addition could make a significant difference. Thanks a bunch for considering this suggestion, and for all the fantastic work on Filament!

Now I can use something like `TextColumn::make('fullName')`! 😀 

Thanks @bezhanSalleh for providing this.
