### ISSUE TITLE
Infolist form component

### ISSUE THREAD

**Issue by danharrin** [laravel-filament/filament#11753]

**Comment by hussain4real** [comment]
This will solve some hacks in my code base

**Comment by saade** [comment]
would be cool to use infolists components on forms too 😅

**Comment by zepfietje** [comment]
> would be cool to use infolists components on forms too 😅

That's exactly what this issue is about :)

**Comment by saade** [comment]
> > would be cool to use infolists components on forms too 😅
> 
> That's exactly what this issue is about :)

@zepfietje Oh, i thought it was the opposite. Then it would be cool to use Forms components on Infolists 😅, for quick editing like a title or smth. I'm currently using a `Infolists\Components\Livewire::make(MyCustomForm::class)`

**Comment by zepfietje** [comment]
That would really still be a number of infolist entries in a form with a single field then, right?

**Comment by saade** [comment]
> That would really still be a number of infolist entries in a form with a single field then, right?

yes if you're not using an infolist on the view page, only a disabled form.

if you wish to use both, a form for creation/editing process and a infolist to display data while allowing some field to be quickly edited on the view page, we need to support form components inside infolists.

**Comment by MACscr** [comment]
> > That would really still be a number of infolist entries in a form with a single field then, right?
> 
> yes if you're not using an infolist on the view page, only a disabled form.
> 
> if you wish to use both, a form for creation/editing process and a infolist to display data while allowing some field to be quickly edited on the view page, we need to support form components inside infolists.

Actually a cool way to do that would be simply have a infolist view option for a every form field. This way you could display a form in a read only mode that would simply look like an infolist. No need to manage two versions of it.

**Comment by saade** [comment]
> Actually a cool way to do that would be simply have a infolist view option for a every form field. This way you could display a form in a read only mode that would simply look like an infolist. No need to manage two versions of it.

That way we can't have separated layouts for the form/ infolist. Take a blog post for example, the form layout for creating a blog post is very different than the infolist for viewing a post.

**Comment by dangnhdev** [comment]
Hello I'm searching for this. Does this got committed somewhere or just closed as not planned? 😅

**Comment by danharrin** [comment]
Closed as completed in v4

**Comment by danharrin** [comment]
still possible if you use a nested LW component in v3

**Comment by abhisha10** [comment]
How can i use form inside of infolist tab using nessted LW component in v3

**Comment by saade** [comment]
> How can i use form inside of infolist tab using nessted LW component in v3

```php
Infolists\Components\Tabs::make()
  ->schema([
      Infolists\Components\Livewire::make(YourLivewireComponent::class)
  ])
```
