### ISSUE TITLE
Misalignment in bullet point text wrapping

### ISSUE THREAD

**Issue by sergioraldana** [laravel-filament/filament#11780]
### Package

filament/filament

### Package Version

v3.2.37

### Laravel Version

v10.45.1

### PHP Version

PHP 8.1

### Problem description

When a Text Column has bulleted() + wrap(), the bullet points does not align properly with the text in the celd. The first line of text has the bullet point  align correctly, but subsequent lines does not maintain this alignment, causing an inconsistent indentation pattern. This issue impact the visual presentation and readability of the row.

<img width="966" alt="Captura de pantalla 2024-03-09 a la(s) 10 12 18" src="https://github.com/filamentphp/filament/assets/60765721/2ddab77b-285f-4b87-a549-18035c336c5e">

### Expected behavior

I expected all lines of text within the bulleted list to maintain consistent alignment with the bullet point, regardless of the length of the text. This means that each line should start at the same horizontal position relative to the bullet point, ensuring a neat and organized appearance throughout the list.

### Steps to reproduce

Create a TextColum with bulleted and wrap:

`Tables\Columns\TextColumn::make('comportamientos')
                    ->listWithLineBreaks()
                    ->bulleted()
                    ->wrap()
                    ->label('Comportamientos'),`

### Reproduction repository

https://github.com/sergioraldana/SGTH

**Comment by zepfietje** [comment]
I've looked into this issue, but it seems like only dirty hacks are available (like [creating fake bullets](https://stackoverflow.com/questions/63062154/prevent-long-list-item-from-moving-below-bullet)).

Unfortunately it's not something I'm comfortable with, and it would be a breaking change.
Let us know if you do think you've found a potential solution though.

**Comment by howdu** [comment]
@zepfietje please checkout my simple fix moving the nowrap css class.
https://github.com/filamentphp/filament/pull/13041
