### ISSUE TITLE
Changes to Select field values not visible without page reload when using native(false)

### ISSUE THREAD

**Issue by pingumen96** [laravel-filament/filament#11806]
### Package

filament/forms

### Package Version

^3.2

### Laravel Version

^10.10

### PHP Version

PHP 8.3

### Problem description

When using ->native(false) with a Select field, the updates made to the selected value are not immediately visible. A page reload is required to see the changes.

**Example of Field Declaration:**
```
Select::make('category_id')
    ->label('Category')
    ->options(Category::all()->pluck('name', 'id'))
    ->relationship('category', 'name')
    ->editOptionForm([
        TextInput::make('name')
            ->label('Name')
            ->required(),
    ])
    ->createOptionForm([
        TextInput::make('name')
            ->label('Name')
            ->required(),
    ])->native(false)
```

### Expected behavior

The value should update and be visible immediately after modification.

### Steps to reproduce

1. Navigate to the customer creation page.
2. Create a category.
3. Select a category and attempt to edit it. After closing the modal, the category value does not appear updated.

### Reproduction repository

https://github.com/pingumen96/filament_tests

**Comment by zepfietje** [comment]
Might this be related to that Choices.js bug, @danharrin?

**Comment by pingumen96** [comment]
Thank you very much for your work!
