### ISSUE TITLE
If RichEditor not empty I cannot delete block with it.

### ISSUE THREAD

**Issue by webspilka** [laravel-filament/filament#11819]
### Package

filament/filament

### Package Version

v3.2.44

### Laravel Version

v10.47.0

### Livewire Version

v3.4.7

### PHP Version

PHP 8.3.3-1

### Problem description

I cannot delete block with `RichEditor` if it has content. If I clear content than delete all works well
I use https://github.com/Z3d0X/filament-fabricator that use Forms\Components\Repeater.

https://github.com/filamentphp/filament/assets/1138069/af57e8ac-af7a-460f-8de3-43d349e866ee

### Expected behavior

just delete block

### Steps to reproduce

look at video
simple block for Filament\Fabricator
```php
namespace App\Filament\Fabricator\PageBlocks;

use Filament\Forms\Components\TextInput;
use Filament\Forms\Components\RichEditor;
use Filament\Forms\Components\Builder\Block;
use Z3d0X\FilamentFabricator\PageBlocks\PageBlock;

class MyBlock extends PageBlock
{
    public static function getBlockSchema(): Block
    {
        return Block::make('my')
            ->schema([
                TextInput::make('name'),
                RichEditor::make('content')
            ]);
    }

    public static function mutateData(array $data): array
    {
        return $data;
    }
}
```

### Reproduction repository

https://github.com/Z3d0X/filament-fabricator

### Relevant log output

```shell
https://flareapp.io/share/V7jkDoL5
```

**Comment by zepfietje** [comment]
Please keep the issue on the Fabricator repo (https://github.com/Z3d0X/filament-fabricator/issues/144).

**Comment by coleshirley** [comment]
I can confirm this issue happens without the fabricator project installed. The `richEditorFormComponent` seems to still be entangled with the livewire component state after it is removed from the page inside of a block builder block. Looking into solutions

**Comment by zepfietje** [comment]
Thanks, @coleshirley!
