### ISSUE TITLE
afterStateUpdated does not work on FileUpload

### ISSUE THREAD

**Issue by Robinvm** [laravel-filament/filament#1183]
### Package

filament/forms

### Package Version

v2.8.3

### Laravel Version

v8.78.1

### Livewire Version

v2.8.2

### PHP Version

8.0

### Bug description

When you call afterStateUpdated in a FileUpload field, it does not get called

### Steps to reproduce

Just create the field and call afterStateUpdated

**Comment by danharrin** [comment]
As discussed on Discord, this is a bug but the solution would break other components. So this is a known limitation with FileUpload components for now.
