### ISSUE TITLE
`extraModalFooterActions` not working properly inside anonymous actions

### ISSUE THREAD

**Issue by binaryfire** [laravel-filament/filament#11841]
### Package

filament/filament

### Package Version

3.2.47

### Laravel Version

10.3.3

### Livewire Version

3.4.8

### PHP Version

8.3

### Problem description

Actions inside the `->extraModalFooterActions()` method of anonymous form actions are not working properly. The button shows but the modal doesn't open and the code in `->action()` doesn't fire.

### Expected behavior

They should work normally

### Steps to reproduce

1. Download the reproduction repo
2. Navigate to Products, then click "New Product"
3. Click the "Extra modal footer actions test" button in the form
4. Click the "Extra action" button in the footer. You'll see that no modal opens and the code inside `->action()` doesn't fire.

### Reproduction repository

https://github.com/binaryfire/filament-reproduction-repo

**Comment by danharrin** [comment]
Due to the way actions can be nested, there are only certain combinations that work:

- Page actions can be nested in the footer of other page actions
- Table actions can be nested in the footer of other table actions
- Form component actions can be nested in the FORM of ANY action, including form component actions, but they cannot be nested inside the footer of form component actions right now

This is the closest you will get, otherwise you will need to move the nested action into the form schema of the first: https://filamentphp.com/docs/3.x/actions/modals#adding-an-extra-modal-action-button-to-the-footer

**Comment by binaryfire** [comment]
@danharrin Thanks for clarifying. 

Nesting form component actions in the footer of other form component actions is what I originally tried to do, but I hit a `Filament\Forms\Components\Actions\Action::$component must not be accessed before initialization` exception.

You said it can't be done "right now" so I'm hoping that means it'll get added at some point😁 Would be very useful.

**Comment by e-m-s-y** [comment]
"but they cannot be nested inside the footer of form component actions right now", is this still true today with v4? I stumbled upon this issue myself. When I paste the code in getHeaderActions() on a Page it works whilst adding it to hintActions does not. The button labelled 'first' does open show / open the second.

Edit:
```
RepeatableEntry::make('comments')
->hintActions([
    Action::make('first')
        ->requiresConfirmation()
        ->action(function () {
            // ...
        })
        ->extraModalFooterActions([
            Action::make('second')
                ->requiresConfirmation()
                ->action(function () {
                    // ...
                })
                ->extraModalFooterActions([
                    Action::make('third')
                        ->requiresConfirmation()
                        ->action(function () {
                            // ...
                        })
                        ->extraModalFooterActions([
                            Action::make('fourth')
                                ->requiresConfirmation()
                                ->action(function () {
                                    // ...
                                })
                                ->cancelParentActions('second'),
                        ]),
                ]),
        ])
]),
```
