### ISSUE TITLE
Selected option from relation doesn't get passed to action callback in custom modal

### ISSUE THREAD

**Issue by webmasterlv** [laravel-filament/filament#11870]
### Package

filament/filament

### Package Version

v3.2.50

### Laravel Version

v10.48.3

### Livewire Version

v3.4.9.

### PHP Version

8.2

### Problem description

I want to create button in the top header of the Resource. I added new action in getHeaderActions() of the ListRecords class. There is a textarea and a dropdown. The dropdown is of `Forms\Components\Select` and configured to use relationship:

```php
Action::make('AddRelation')
    ->form([
        Forms\Components\Textarea::make('text')
            ->required(),

        Forms\Components\Select::make('relation_id')
            ->relationship('relationship', 'name')
            ->preload()
            ->multiple()
            ->maxItems(1)
    ])
    ->action(function (array $data): void {
        //`text` is here, but `relation_id` is not.
        dd($data);
})
```

### Expected behavior

`action()` should receive all user entered form data regardless of the input type.

### Steps to reproduce

- Setup environmet
- `composer install`
- `php artisan migrate`
- `php artisan db:seed`
- `php artisan make:filament-user` - create user as requested
- Log into panel, navigate to "Relations"
- Click on "Add test"
- Fill the form and submit. You can see that there only will be data from textarea.

### Reproduction repository

https://github.com/webmasterlv/filament-test.git

**Comment by danharrin** [comment]
Form components using `relationship()` are designed not to dehydrate into `$data` so that you can save that data to the main model out of the box. When calling `->saveRelationships()` or when your action is associated with a record, it will save the data for you.

If you add `->dehydrated()` onto that Select after `->relationship()`, it should work.
