### ISSUE TITLE
getOptionLabelUsing not work

### ISSUE THREAD

**Issue by IgorDePaula** [laravel-filament/filament#11872]
### Package

filament/filament

### Package Version

3.2

### Laravel Version

10.10

### PHP Version

php 8.1

### Problem description

I tried different formats but appears that this method is invisible

```php
  Forms\Components\Select::make('curse_id')
                    ->label('Curso')
                    ->required()
                    ->searchable()
                    ->getSearchResultsUsing(fn (string $search): array => Curse::where('name', 'like', "%{$search}%")->limit(50)->pluck('name', 'id')->toArray())
                    ->getOptionLabelUsing(fn(Model $record) => "adasd {$record->ambit->name} - {$record->name}")
```

```php
  Forms\Components\Select::make('curse_id')
                    ->label('Curso')
                    ->required()
                    ->searchable()
                    ->relationship(
                        name: 'curse',
                        titleAttribute: 'name',
                    )
                    ->getOptionLabelUsing(fn(Model $record) => "adasd {$record->ambit->name} - {$record->name}")
```

using ```getOptionLabelUsing``` or ```getOptionLabelsUsing``` I have the same result: only the name model registry is returned. Attention that I put an ```adasd``` and this text is not returned.

### Expected behavior

I expect that I search for a course, the filament returns together the ambit name.

### Steps to reproduce

Need docker and make

1- Up the project with ```make docker-up```
2- ```make docker-bash``` and ```php artisan migrate```
3- Create a Filament User (now, I havent ACL or Roles)
4- Create an Ambit, Course and then discipline.
5- You will see that course not have an ambit name, only course name

### Reproduction repository

https://github.com/VirtuaSec/virtuasec4/blob/main/app/Filament/Resources/DisciplineResource.php

### Relevant log output

```shell
From network tab

{
	"components": [
		{
			"calls": [
				{
					"method": "getFormSelectSearchResults",
					"params": [
						"data.curse_id",
						"Primeiro ano"
					],
					"path": ""
				}
			],
			"snapshot": "{\"data\":{\"record\":null,\"data\":[{\"name\":null,\"curse_id\":null},{\"s\":\"arr\"}],\"previousUrl\":\"http:\\/\\/localhost:8000\\/admin\\/disciplines\",\"mountedActions\":[[],{\"s\":\"arr\"}],\"mountedActionsArguments\":[[],{\"s\":\"arr\"}],\"mountedActionsData\":[[],{\"s\":\"arr\"}],\"defaultAction\":null,\"defaultActionArguments\":null,\"componentFileAttachments\":[[],{\"s\":\"arr\"}],\"mountedFormComponentActions\":[[],{\"s\":\"arr\"}],\"mountedFormComponentActionsArguments\":[[],{\"s\":\"arr\"}],\"mountedFormComponentActionsData\":[[],{\"s\":\"arr\"}],\"mountedFormComponentActionsComponents\":[[],{\"s\":\"arr\"}],\"mountedInfolistActions\":[[],{\"s\":\"arr\"}],\"mountedInfolistActionsData\":[[],{\"s\":\"arr\"}],\"mountedInfolistActionsComponent\":null,\"mountedInfolistActionsInfolist\":null,\"savedDataHash\":null},\"memo\":{\"id\":\"82MawsvmxxOt55VR6W4Y\",\"name\":\"app.filament.resources.discipline-resource.pages.create-discipline\",\"path\":\"admin\\/disciplines\\/create\",\"method\":\"GET\",\"children\":[],\"scripts\":[],\"assets\":[],\"errors\":[],\"locale\":\"pt_BR\"},\"checksum\":\"2de86504566b72d0b46be2c71a7b2de31ca138410a4530077052f6c689c8d8dc\"}",
			"updates": {}
		}
	]
}
```

**Comment by danharrin** [comment]
`getOptionLabelUsing()` is not used when `getSearchResultsUsing()` is called. `getSearchResultsUsing()` only returns an array of IDs and labels. `getOptionLabelUsing()` is used when a search has not been made yet and we need to render the current label of the select from the ID.

In your second example, replace `getOptionLabelUsing()` with `getOptionLabelFromRecordUsing()`, which is a method only used by `relationship()`.

The docs do talk about these methods. If you see room for improvement, submit a PR.

**Comment by IgorDePaula** [comment]
@danharrin works greate. Thank you very much.

**Comment by bilogic** [comment]
> `getOptionLabelUsing()` is not used when `getSearchResultsUsing()` is called.

@danharrin 

the documentation is wrong since v3 https://filamentphp.com/docs/5.x/forms/select#returning-custom-search-results

**Comment by danharrin** [comment]
What specifically is wrong? I think it's quite clear what the distinction is, and it aligns with my comment above

**Comment by bilogic** [comment]
@danharrin 

```php
use Filament\Forms\Components\Select;

Select::make('author_id')
    ->searchable()
    ->getSearchResultsUsing(fn (string $search): array => User::query()
        ->where('name', 'like', "%{$search}%")
        ->limit(50)
        ->pluck('name', 'id')
        ->all())
    ->getOptionLabelUsing(fn ($value): ?string => "not happening"), // this line has no effect
```

**Comment by danharrin** [comment]
It does, read the documentation

**Comment by bilogic** [comment]
I'm on Filament 4 and using `Select` in a modal, the docs for 4 is exactly the same, and that line has no effect, both the `->pluck()` and `getOptionLabelUsing`  return `->name`, so it is important to change it to `"not happening"` to see the problem.

**Comment by danharrin** [comment]
> This is used when the form is first loaded when the user has not made a search yet.

**Comment by bilogic** [comment]
Ok thanks, I get it now after re-reading several times. I think it's clearer to comment the code a bit, will file a PR if I think of something good.
