### ISSUE TITLE
Changing FileUpload field state() does not refresh the field/FilePond on front-end

### ISSUE THREAD

**Issue by mansoorkhan96** [laravel-filament/filament#11888]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

v10.0

### Livewire Version

v3.x

### PHP Version

PHP8.2

### Problem description

I am trying to Upload a file from a URL using a Form Action. I download the file and save it to `livewire-tmp` directory and then update the FileUpload component state but it does not refresh the field state, hence there is no preview of the image.

However, the downloaded file is uploaded successfully and saved on form submission.

### Expected behavior

Once the FileUpload field state is updated it should refresh the state on front-end ie. FilePond and show the preview of image as normal.

### Steps to reproduce

1) Add this action to your FileUpload field
```php
use App\Services\UrlUploadedFile

Forms\Components\FileUpload::make('avatar')
  ->image()
  ->hintAction(
      \Filament\Forms\Components\Actions\Action::make('upload_from_url')
          ->action(function (FileUpload $component) {
              $url = 'https://via.placeholder.com/150x150';

              $filePath = UrlUploadedFile::createFromUrl($url)
                  ->store('livewire-tmp', ['disk' => 'local']);

              $filePath = explode('/', $filePath)[1];

              $file = TemporaryUploadedFile::createFromLivewire($filePath);

              $component->state([$file]);
              // also tried
              // $component->state($file);
          })),
```

2) Open Admin panel and click on the upload_from_url action, It would not preview the image. However the field should refresh and show preview.

3) Now Save the form and it should show the preview.

### Reproduction repository

https://github.com/mansoorkhan96/filament-playground

**Comment by mansoorkhan96** [comment]
Maybe there should be a way to pass an absolute path to a method which programatically uploads the file?

**Comment by mansoorkhan96** [comment]
Or maybe its not possible?

When the file is uploaded from browser, FilePond shows the preview from browser by adding it to its canvas. But when the file is uploaded from backend, filepond cannot show the preview unless its a public file or unless it gets temporary url for the private file (if the temp url support for local disk is added on user land)

**Comment by danharrin** [comment]
Filepond needs a path to the permanent storage. TemporaryUploadeFile objects are only supported when Filepond initiates that upload process originally. I would store it permanently if I were you, and introduce a cleanup process for unused files.

**Comment by mansoorkhan96** [comment]
> Filepond needs a path to the permanent storage. TemporaryUploadeFile objects are only supported when Filepond initiates that upload process originally. I would store it permanently if I were you, and introduce a cleanup process for unused files.

Thanks for the response. Actually I am building this for plugin idea, So i am trying to keep less code on user land. 

If thats the way to do it: Suppose, if the file was stored to `posts/featured_img/` and if the form was never submitted, How would it know if there are files that need to be cleaned up.

**Comment by danharrin** [comment]
You would not have any records in the database that reference the file

**Comment by JohnRoux** [comment]
I'm trying to do this exact thing, but when I change the state path for the fileUpload, the preview stops previewing the old image and also doesn't preview the new image, even though it is a permanently stored image on the correct disk.

Using $set() to change the state doesn't refresh the component:

Eg:
```
$set('image_default', [Str::uuid()->toString() =>"01JP2M9ET2B47C6J5273E0QWVG.png"])
```

**Comment by JohnRoux** [comment]
I've got a Create Page wizard with a couple steps.

Step 1 has the user pick a theme to start from
After validation of Step 1, I default a bunch of things based on that theme.
(Brand name, theme colours, various text and a couple of logos)


Step 3 shows the full theme options where the user can customize those theme/brand settings.


I was origionally also thinking of trying to use the TemporaryUploadedFile. But no luck (which makes sense since it's filepond itiiating it)

But filepond works well with existing state, so I thought I'd be able to do a copy of the logos in that Step1AfterValidation
But the preview (and also the file storage) simply isn't working.

The file path itself isn't being saved. (nor is the preview working)

**Comment by mansoorkhan96** [comment]
Incase its helpful for you, I was able to solve this using a different approach. 

https://github.com/mansoorkhan96/filament-unsplash-picker
