### ISSUE TITLE
Infolist Actions Inside Tab

### ISSUE THREAD

**Issue by vanrezky** [laravel-filament/filament#11895]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

v10.10

### PHP Version

8.2

### Problem description

Hallo.. im here to report some bug inside my code. im using infolist to show customer data.
inside infolist, im using tabs and textentry.. tabs -> tabs/tab -> Textentry and add action suffix. it show nothing bugs.. but when i click the button, its show nothing.

![image](https://github.com/filamentphp/filament/assets/57346827/8562e443-b33f-4a7b-92a7-d72cc853d55d)

![image](https://github.com/filamentphp/filament/assets/57346827/5e12b549-6dda-42ba-a083-2c1120eabc06)

### Expected behavior

-

### Steps to reproduce

-

### Reproduction repository
https://github.com/vanrezky/toko-online-filament3.git

**Comment by vanrezky** [comment]
test

**Comment by danharrin** [comment]
Your infolist entry names are not unique. You have two `balance` entries. They should be unique, or you can give them a unique `->key()` instead like `->key('balanceWithAction')`

**Comment by vanrezky** [comment]
thanks. that works @danharrin
