### ISSUE TITLE
Problem in installing filament 3.2 for laravel 11

### ISSUE THREAD

**Issue by darshan45672** [laravel-filament/filament#11903]
### Package

filament/filament

### Package Version

v3.2.0

### Laravel Version

v11.0.7

### Livewire Version

v3.4.9

### PHP Version

PHP 8.2.12

### Problem description

I tired to install filament for my laravel 11 project but current version of filament (3.2.0) is not supported by laravel 11.

firstly i executed ``` composer require filament/filament:"^3.2" -W ``` but i got a error shown in the below image.
![error when using filament/filament:"^3.2 ](https://github.com/filamentphp/filament/assets/109609462/c2563479-760e-4a7b-bb31-e21b40dcca4b)

next seeing the error i executed ``` composer require filament/filament:"^3.2.0" -W ``` manually but still i got error as shown in the below image.
![error when using filament/filament:"^3.2.0 ](https://github.com/filamentphp/filament/assets/109609462/e7305e95-103f-4e86-b9eb-2c15d87d4401)

i searched solution for this issue but they asked to use ``` composer require filament/filament:"^3.2.0" -W ```, but still its not working.
![solution suggested](https://github.com/filamentphp/filament/assets/109609462/bfc1f10c-6650-46b3-9824-6498776f5825)

### Expected behavior

filament installed sucessfully without any flaws.

### Steps to reproduce

- first install laravel 11 ```composer create-project laravel/laravel:^11.0 example-app```
- cd example-app
- install livewire ```composer require livewire/livewire```
- install filament  ```composer require filament/filament:"^3.2" -W``` or ```  composer require filament/filament:"^3.2.0" -W ```

### Reproduction repository

https://github.com/darshan45672/Blog/tree/dev

**Comment by danharrin** [comment]
`3.2.0` doesn't support Laravel 11. Your machine should be installing the latest 3.2 with `^3.2`, but it looks like something is wrong on your end.

Try installing `3.2.52`, and then after it is installed swap `3.2.52` for `^3.2` in your `composer.json` file and update again

**Comment by danharrin** [comment]
Or just try `composer require filament/filament` without a version

**Comment by darshan45672** [comment]
ok Thank you it works !!
![output](https://github.com/filamentphp/filament/assets/109609462/8d437c94-af9d-460f-ae22-0557119e0ffd)

Thank You @danharrin  for resolving my issue.
Thank you soo much for your assist.

**Comment by RonBPalmer** [comment]
I had this same error and resolved it with the solution provided: composer require filament/filament:"^3.2.52" -W

**Comment by ikhsan990** [comment]
try run

composer require filament/filament:"^3.2.66" -W --ignore-platform-req=ext-intl
