### ISSUE TITLE
Widgets in Cluster have to much spacing when long list of cluster submenu's  

### ISSUE THREAD

**Issue by eelco2k** [laravel-filament/filament#11909]
### Package

filament/filament

### Package Version

v3.2.50

### Laravel Version

v10

### PHP Version

8.3

### Problem description

When i have a cluster with a lot of submenu's a Resource List Page with Widgets give me a lot of space between the Widgets and the Table. See image below.

![Scherm­afbeelding 2024-03-18 om 11 57 32](https://github.com/filamentphp/filament/assets/878103/b7d4c117-b756-4ddc-8b77-6746de47e213)

it looks like it goes wrong in the styling in filament/filament/resources/views/components/page/index.blade.php:86

```php
<div
                @class([
                    'grid flex-1 auto-cols-fr gap-y-8',
                    'h-full' => $fullHeight,
                ])
            >
```
when I temporary add 'h-72' after 'flex' the issue is fixed.

like so:

```php
<div
                @class([
                    'grid h-72 flex-1 auto-cols-fr gap-y-8',
                    'h-full' => $fullHeight,
                ])
            >
```

### Expected behavior

no spacing between Widgets and Table in Cluster with a lot of submenu items

### Steps to reproduce

create a cluster. create a lot of menu items and a lot of submenu items. Create one resource with widgets and a tableview.

### Reproduction repository

[https://github.com/eelco2k/filamentphp-issue-cluster](https://github.com/eelco2k/filamentphp-issue-cluster)

**Comment by eelco2k** [comment]
see issue https://github.com/filamentphp/filament/issues/13037 which is more relevant only the screenshot in this issue gives a clue.

**Comment by zepfietje** [comment]
Could you create a pull request with the fix you described in linked issue, @eelco2k? 🙂

**Comment by eelco2k** [comment]
created the pull request https://github.com/filamentphp/filament/pull/13052

**Comment by zepfietje** [comment]
Thanks!
