### ISSUE TITLE
Typed property Filament\Actions\MountableAction::$livewire must not be accessed before initializatio

### ISSUE THREAD

**Issue by andresilvagomez** [laravel-filament/filament#11926]
### Package

filament/actions

### Package Version

v3.2.53

### Laravel Version

v10.48.3

### Livewire Version

v3.4.9

### PHP Version

8.3.4

### Problem description

When I'm trying to invoke an action, I got `Typed property Filament\Actions\MountableAction::$livewire must not be accessed before initializatio`

here is the error

https://flareapp.io/share/67OWWEv7

### Expected behavior

Dont get the error

### Steps to reproduce

Call some action

### Reproduction repository

https://flareapp.io/share/67OWWEv7

**Comment by danharrin** [comment]
Update Filament
