### ISSUE TITLE
modifyQueryUsing in default table query gives incorrect record in table Action

### ISSUE THREAD

**Issue by yashdesai87** [laravel-filament/filament#11944]
### Package

filament/filament

### Package Version

3.2.55

### Laravel Version

10

### PHP Version

8.3.0

### Problem description

In the filament resource, when the original table query is modified by using `modifyQueryUsing` and multiple `whereIn()` and `OrWhereIn()` conditions, the actions per row uses the **same record** instead of referring to unique records.

```
public static function table(Table $table): Table
{
    return $table
          ->modifyQueryUsing(function (Builder $query) {
              $query
                  ->whereIn('id',[1,2,3,4,5])
                  ->OrWhereIn('id',[1,2,3,4,5]);
          })
          ->columns([
              TextColumn::make('id'),
              TextColumn::make('name'),
          ])
          ->actions([
              Action::make('action')
              ->label('Take Action')
              ->modalHeading(function(User $user){
                  return 'Taking Action on user '.$user->id.' ('.$user->name.')';
                  })
                  ->button()
    ]);
}
```

### Expected behavior

Clicking on the "Take Action" button should have given the heading specific to the row selected as

- Taking Action on user 1 (Test User)
- Taking Action on user 2 (Dr. Jaiden Satterfield)
- Taking Action on user 3 (Dr. Lia Gaylord)
- Taking Action on user 4 (Murray Flatley)
- Taking Action on user 5 (Lavada Grady)

However, it is showing

- Taking Action on user 1 (Test User)
- Taking Action on user 1 (Test User)
- Taking Action on user 1 (Test User)
- Taking Action on user 1 (Test User)
- Taking Action on user 1 (Test User)

regardless of whichever "Take Action" button is clicked.

### Steps to reproduce

The simplest code fragment below is enough to replicate the issue. I have modified the original table query to only show rows which have the id as 1,2,3,4,5. The problem occurs when multiple `OrWhereIn` conditions are used. 

  ```
return $table
    ->modifyQueryUsing(function (Builder $query) {
        $query
            ->whereIn('id',[1,2,3,4,5])
            ->OrWhereIn('id',[1,2,3,4,5]);
    })
```

Because of the above, clicking on any "Take Action" button gives the same output

![image](https://github.com/filamentphp/filament/assets/2519350/4e9f2f2e-2830-442e-b092-50a448eb3aaf)

### Reproduction repository

https://github.com/yashdesai87/filament-modifyqueryusing-issue

**Comment by danharrin** [comment]
Wrap the clauses in a single `->where()` group https://laravel.com/docs/11.x/queries#logical-grouping

**Comment by raonikhil** [comment]
Thank you. This worked.

**Comment by yashdesai87** [comment]
Thank you. This worked.

**Comment by franckdarren** [comment]
Merci. Cela a fonctionné.
