### ISSUE TITLE
I have some error with link cdns

### ISSUE THREAD

**Issue by mrmyintmyat** [laravel-filament/filament#11953]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

v10.10

### PHP Version

8.1+

### Problem description

ui/ux design problem. In console it is showing

async-alpine.js?v=3.2.56.0:1 Mixed Content: The page at 'https://domain.com/admin' was loaded over HTTPS, but requested an insecure script 'http://domain.com/js/filament/widgets/components/chart.js?v=3.2.56.0'. This request has been blocked; the content must be served over HTTPS.
async-alpine.js?v=3.2.56.0:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://domain.com/js/filament/widgets/components/chart.js?v=3.2.56.0
async-alpine.js?v=3.2.56.0:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://domain.com/js/filament/widgets/components/chart.js?v=3.2.56.0
async-alpine.js?v=3.2.56.0:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://domain.com/js/filament/widgets/components/chart.js?v=3.2.56.0
async-alpine.js?v=3.2.56.0:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http:/domain.com/js/filament/widgets/components/chart.js?v=3.2.56.0

### Expected behavior

but if I used http domain, it worked. like http://domain.com

when I used https://domain.com,it doesn't wok.It is showing error

### Steps to reproduce

but if I used http domain, it worked. like http://domain.com

when I used https://domain.com,it doesn't wok.It is showing error

In console it is showing

async-alpine.js?v=3.2.56.0:1 Mixed Content: The page at 'https://domain.com/admin' was loaded over HTTPS, but requested an insecure script 'http://domain.com/js/filament/widgets/components/chart.js?v=3.2.56.0'. This request has been blocked; the content must be served over HTTPS.
async-alpine.js?v=3.2.56.0:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://domain.com/js/filament/widgets/components/chart.js?v=3.2.56.0
async-alpine.js?v=3.2.56.0:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://domain.com/js/filament/widgets/components/chart.js?v=3.2.56.0
async-alpine.js?v=3.2.56.0:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http://domain.com/js/filament/widgets/components/chart.js?v=3.2.56.0
async-alpine.js?v=3.2.56.0:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: http:/domain.com/js/filament/widgets/components/chart.js?v=3.2.56.0

### Reproduction repository

https://myintmyat.dev/admin

**Comment by putrafajarh** [comment]
I had same problem too, using Cloudflare Flexible SSL (my nginx serve HTTP).
already set the APP_URL to https, try clear filament cache, config, nothing help..

**Comment by leandrocfe** [comment]
> I had same problem too, using Cloudflare Flexible SSL (my nginx serve HTTP).
> already set the APP_URL to https, try clear filament cache, config, nothing help..

Try to add in .env `ASSET_URL=https://yourdomain.com`

**Comment by mrmyintmyat** [comment]
> > I had same problem too, using Cloudflare Flexible SSL (my nginx serve HTTP).
> > already set the APP_URL to https, try clear filament cache, config, nothing help..
> 
> Try to add in .env `ASSET_URL=https://yourdomain.com`

Finally 🥳 
Thank you.
