### ISSUE TITLE
Select does not load default value in Edit Action with relationship

### ISSUE THREAD

**Issue by joaonivaldo** [laravel-filament/filament#11964]
### Package

filament/forms

### Package Version

v3.2.57

### Laravel Version

v10.48.3

### Livewire Version

v3.4.9

### PHP Version

php 8.3

### Problem description

I have a Select that when I enter the Edit Action it is not marking the default value that comes from the relationship. The relationship is being loaded normally and showing the value in the Select Label. I've already tried select with relationship and options and nothing. 
![image](https://github.com/filamentphp/filament/assets/4040086/c6712b29-460c-48c0-a07f-25cfd3a51664)

### Expected behavior

Once loaded, the form should select the FOLDER 4 item

### Steps to reproduce

Clone the repository,
run php artisan:migrate --seed
Join Dashborard
Choose Subfolders from the Menu
Click Edit in the ID folder line 5
Ready

### Reproduction repository

https://github.com/joaonivaldo/filament_erro_select

### Relevant log output

```shell
$sub1->subpasta->parent
= App\Models\Categoria {#7159
    id: 5,
    uuid: "0a3beef6-2d1c-46e0-af7e-915435c9fbec",
    parent_id: null,
    slug: "pasta-4",
    label: "Pasta 4",
```

**Comment by danharrin** [comment]
```php
Forms\Components\Group::make([
    Select::make('parent_id')
        ->required()
        ->label(fn(Model $record): string => 'Pasta Principal: ' . $record->parent->label)
        ->relationship(
            'parent',
            'label',
            modifyQueryUsing: fn(Builder $query) => $query->whereNull('parent_id')
        )
        //->options(Categoria::query()->whereNull('parent_id')->pluck('label', 'id'))
        ->searchable()
        ->placeholder('Selecione uma pasta.')
        ->loadingMessage('Carregando. Aguarde...')
        ->noSearchResultsMessage('Sem registros...')
        ->searchPrompt('Selecione uma pasta.')
        ->searchingMessage('Procurando...')
        ->preload()
        ->live()
        ->columnSpanFull(),
])->relationship('subpasta'),
```

https://filamentphp.com/docs/3.x/forms/advanced#saving-data-to-relationships

**Comment by joaonivaldo** [comment]
It worked this way, but it created another problem. The second Select is not loading the values or setting the default value. It depends on the first select. Once you loaded the first one, you have to load the second one, they are nested. Can you see why or do I have to open another ticket? Thank you very much.

![image](https://github.com/filamentphp/filament/assets/4040086/684ecf66-348e-499f-aa39-9ce5eef116e5)

**Comment by danharrin** [comment]
Use `$get('subpasta.parent_id')`

**Comment by joaonivaldo** [comment]
I added it as you mentioned, but it seems to me that the second select is not being populated. When I click on it, the value appears in the list. Do I have to add anything else besides live() in the first component for it to load the second at startup?

![image](https://github.com/filamentphp/filament/assets/4040086/81455273-b560-48d2-8c93-f02a9cd2c6de)

**Comment by joaonivaldo** [comment]
It worked. I restarted the artisan server and it worked. Mysteries. Thank you very much for your help.
