### ISSUE TITLE
TrashedFilter only works when i refresh the page

### ISSUE THREAD

**Issue by AHMED-GAMAL-AG** [laravel-filament/filament#11975]
### Package

filament/filament

### Package Version

3.2

### Laravel Version

10.10

### Livewire Version

10.0

### PHP Version

8.2.1

### Problem description

The TrashedFilter when chained with ->native(false) doesn't apply until i refresh the page 

https://github.com/filamentphp/filament/assets/76778937/0650ac6a-2f77-4bfc-81db-66f684831e0d

when removing the ->native(false) chain it doesn't work until i click anywhere on the screen

https://github.com/filamentphp/filament/assets/76778937/5f926d5f-6c2b-4aea-947b-6bb9ba6d6cf8

### Expected behavior

the TrashedFilter should work without refreshing the screen 

### Steps to reproduce

1) the filter should work correctly without need to refresh the page when
chained with ->native(false) 

2) the filter should work correctly when chained with ->native(true) without need to anywhere on the screen

### Reproduction repository

https://github.com/AHMED-GAMAL-AG/Filament-TrashedFilter-Bug

**Comment by danharrin** [comment]
Works fine for me 

https://github.com/filamentphp/filament/assets/41773797/a121328b-defc-47b6-8d5b-1a6e62abe40d
