### ISSUE TITLE
Route [login] not defined. after User information change

### ISSUE THREAD

**Issue by IranMine123** [laravel-filament/filament#11988]
### Package

filament/filament

### Package Version

v3.2.58

### Laravel Version

v10.48.4

### Livewire Version

v3.4.9

### PHP Version

PHP 8.2.12

### Problem description

Hello when user change itself's information like password and etc in form, something like Authentication Exception happen. then _Filament redirects user to login route._ this requires a route have name of "login". well i don't want that. i mean i really dont want to define a route with 'login' name. tried to change the redirect url on Authentication Middleware by creating a custom one and put it in ->authMiddleware() but didn't work.

### Expected behavior

redirect user to defined custom url, or make user stay on panel, or the panel's login page, after user changes itself information on panel with forms

### Steps to reproduce

- Login to panel
- Change the user's info with forms (no matters what, password, username, role and etc)
- after save, going back to dashboard or resource table (users table) <------- problem occurs

### Reproduction repository

https://github.com/IranMine123/filament-login-bug

### Relevant log output

```shell
https://flareapp.io/share/LPdKe2Ym
here is the exception error
```

**Comment by danharrin** [comment]
#9075, #7725, #7223, #11629, #5226, please look for duplicate issues before posting

This is a Laravel issue with the fact they are hardcoding this route name in the framework. We do not believe there is a solution on the Filament side. You just need to define a redirect route with that name

**Comment by dpenacton** [comment]
🛠 **Trouble with Export/Import Functionality in Laravel Filament Admin Panel: 'Login Route Not Found' Error**

I've been tackling the export/import feature, aiming for smooth functionality. However, upon attempting to export or import a CSV, it seems to generate within the notifications. Yet, when I endeavor to download the file, a persistent 'login route not found' error arises.

![Screenshot](https://img.enacton.com/ShareX/2024/04/w4FMvKPUQJ.png)

I've configured separate guards for authentication, catering to both admin and user panels. Additionally, I've ensured that the export/import policy is correctly set to return true within the view function.

Furthermore, I've diligently included `Export::polymorphicUserRelationship();` in the app service provider and executed all requisite database changes.

Despite these efforts, I find myself still grappling with the 'login route not found' issue when attempting to access export/import. Any suggestions on resolving this within the Laravel Filament admin panel?

**Comment by Osub** [comment]
https://flareapp.io/share/RmrBDglm

**Comment by antal-levente** [comment]
@DishantPal the issue probably appears because the auth guard is different on the export route then the one you are using for your Filament panel.

In my case it was because i used a different auth guard and even though it was correctly configured according to the documentation. Filament ignored the different user provider on the route and still went with the default one. Basically the solution is to change the auth guard on the export route, however those are hardcoded in the Filament files. Which seems to me to be a bug.

A simple workaround could be if you simply overwrite the route in your route file:
```php
use Filament\Actions\Exports\Http\Controllers\DownloadExport;

Route::get('/filament/exports/{export}/download', DownloadExport::class)
    ->name('filament.exports.download')
    ->middleware(['web', 'auth:admin']);
```

**Comment by ohchiko** [comment]
I was having the same issue while using a simple resource of User (editing done in a modal form), and I have multiple panels. The solution I came up with was to modify the `App\Providers\AppServiceProvider`'s `boot` method as mentioned in https://github.com/filamentphp/filament/discussions/5226#discussioncomment-10473083.

```php
use Filament\Facades\Filament;
use Filament\Http\Middleware\Authenticate;
use Illuminate\Auth\AuthenticationException;
use Illuminate\Session\Middleware\AuthenticateSession;

    // ...

    public function boot(): void
    {
        Authenticate::redirectUsing(fn(): string => Filament::getLoginUrl());
        AuthenticateSession::redirectUsing(
            fn(): string => Filament::getLoginUrl()
        );
        AuthenticationException::redirectUsing(
            fn(): string => Filament::getLoginUrl()
        );

        // ...
    }

    // ...
```

And to automatically redirect the user to the login page after successfuly editing (the modal does not automatically redirect to login page, it just delete the auth session), use `successRedirectUrl` method on the `EditAction`.

```php
Tables\Actions\EditAction::make()->successRedirectUrl(
    fn(): string => Filament::getLoginUrl()
),
```

The `getLoginUrl` can determine the current panel. But, if you're unsure, you can use `Filament::getCurrentPanel()->getLoginUrl()` instead.

Hope it helps.

**Comment by galliroberto** [comment]
> @DishantPal the issue probably appears because the auth guard is different on the export route then the one you are using for your Filament panel.
> 
> In my case it was because i used a different auth guard and even though it was correctly configured according to the documentation. Filament ignored the different user provider on the route and still went with the default one. Basically the solution is to change the auth guard on the export route, however those are hardcoded in the Filament files. Which seems to me to be a bug.
> 
> A simple workaround could be if you simply overwrite the route in your route file:
> 
> ```
> use Filament\Actions\Exports\Http\Controllers\DownloadExport;
> 
> Route::get('/filament/exports/{export}/download', DownloadExport::class)
>     ->name('filament.exports.download')
>     ->middleware(['web', 'auth:admin']);
> ```

I added it, now I have 404.
Without redirect to login, but I don't understand the reason

**Comment by MladenJanjetovic** [comment]
I am noticing a lot of issues with Filament if you are using other admin guard than User model related. And that is a very common case. So it's strange that all these issues are closed and marked as not planned usually.
