### ISSUE TITLE
Incorrect links to resources when using ->tenantDomain() on a panel

### ISSUE THREAD

**Issue by andy3471** [laravel-filament/filament#11983]
### Package

filament/filament

### Package Version

v3.2.58

### Laravel Version

v11.0

### PHP Version

8.3.0

### Problem description

This is a folllow on from this issue: https://github.com/filamentphp/filament/issues/11896

Since the issue was resolved, I've noticed that links under any panel that has the ->tenantDomain set will have the links all generate incorrectly. It seems to be using the ID of the tenant as the base URL:

![image](https://github.com/filamentphp/filament/assets/7016492/9553c279-eb27-4687-8501-ae433c25fdbe)

It looks like this issue is on the base resource class:
```php
    public static function getUrl(string $name = 'index', array $parameters = [], bool $isAbsolute = true, ?string $panel = null, ?Model $tenant = null): string
    {
        if (blank($panel) || Filament::getPanel($panel)->hasTenancy()) {
            $parameters['tenant'] ??= ($tenant ?? Filament::getTenant());
        }

        $routeBaseName = static::getRouteBaseName(panel: $panel);

        return route("{$routeBaseName}.{$name}", $parameters, $isAbsolute);
    }
```

### Expected behavior

Links to generate with the base URL of the panel you are currently on

### Steps to reproduce

Pull the example repository
Copy the .env.example to .env
Run the database migrations + seed

Add the following you your hosts file for testing:

127.0.0.1 site-1.inform-ehr.local
127.0.0.1 site-2.inform-ehr.local
127.0.0.1 site-3.inform-ehr.local

Go to site-1.inform-ehr.local and try to login with [test@example.com](mailto:test@example.com) / password

Click the link to the Users resource, your browser will go to http://1/users

### Reproduction repository

https://github.com/andy3471/filament-tenant-domain

**Comment by danharrin** [comment]
Does it work with `{tenant:domain}` instead of `{tenant}`?

**Comment by andy3471** [comment]
@danharrin  If I set it to tenant:domain, I get the original issue (#11896) again.

**Comment by danharrin** [comment]
#12008 should fix that, if you use the `:domain` too

**Comment by pschilly** [comment]
I am getting this same exact problem in v4 - where if I set the tenantDomain() with either a full domain or a subdomain, all of the redirects goto: `{tenant-slug}.domain.test/{tenant-slug}`
