### ISSUE TITLE
RelationshipJoiner with json field

### ISSUE THREAD

**Issue by robert-abram** [laravel-filament/filament#11992]
### Package

filament/filament

### Package Version

v3.0.0

### Laravel Version

v10.0.0

### Livewire Version

v3.1

### PHP Version

PHP 8.3

### Problem description

When filmant use RelatipnshipJoiner (prepareQueryForNoConstraints function) and relationship is with json field then line trigger exception, because distinct cannot be made on json fields

```
$relationshipQuery->distinct()->select($relationshipQuery->getModel()->getTable() . '.*');
```

### Expected behavior

```
$relationshipQuery->select($relationshipQuery->getModel()->getTable() . '.*');
```

### Steps to reproduce

Attach action to relationship with json field

### Reproduction repository

https://github.com/filamentphp/filament

### Relevant log output

```shell
SQLSTATE[42883]: Undefined function
```

**Comment by dangnhdev** [comment]
Solution in https://github.com/filamentphp/filament/issues/8698
