### ISSUE TITLE
[Missing parameter: tenant] `->profile(isSimple: false)`

### ISSUE THREAD

**Issue by devhoussam1998** [laravel-filament/filament#11998]
### Package

filament/filament

### Package Version

^3.2

### Laravel Version

^11.0

### Livewire Version

^3.4

### PHP Version

^8.2

### Problem description

<img width="1794" alt="Screenshot 2024-03-23 at 01 20 55" src="https://github.com/filamentphp/filament/assets/121255432/61b057db-075a-42d8-abe7-812d0abfab61">

### Expected behavior

`->profile(isSimple: false)` does not work with Multi-tenancy

### Steps to reproduce

Install Laravel 11
Install Filament 3
Follow Filament v3 Multi-tenancy Docs
Add `->profile(isSimple: false)` to `$panel` config.

### Reproduction repository

https://github.com/devhoussam1998/test-app

**Comment by danharrin** [comment]
<img width="882" alt="Screenshot 2024-03-23 at 19 22 49" src="https://github.com/filamentphp/filament/assets/41773797/0c526ef7-d8b6-4d68-afd4-44ee55597337">
