### ISSUE TITLE
Laravel 11 with Filament 3 do not send forgot password email

### ISSUE THREAD

**Issue by mberneis** [laravel-filament/filament#11995]
### Package

filament/filament

### Package Version

v3.2.58

### Laravel Version

11.0.8

### Livewire Version

v3

### PHP Version

8.2

### Problem description

A brand new project created with Laravel and filament 3.0 does not send forgot password emails.
No changes were made besides creating a new Laravel project without starter kit and installing filament panel.
One filament user (mberneis@gmail.com) was created.
This ability works fine on my Laravel 10/filament3 projects.

### Expected behavior

Password Email will be send out. - Mail is correctly configured as I tested in tinker console with
`Mail::raw('Hello World',function($msg) {$msg->to('filament@example.com')->subject('test mail from tinker');});`

### Steps to reproduce

Install Laravel 11
Install Filament 3
create one filament user
goto login panel
click forgot password
enter email from filament user
App Shows Notification but no email is send

### Reproduction repository

https://github.com/mberneis/filament_bug_proof

**Comment by zepfietje** [comment]
Are you sure you've started the queue worker?

**Comment by mberneis** [comment]
Yes, that was it! - Laravel 11 set the default queue to database instead of sync as Laravel 10.
Changed the configuration and all looks great!

**Comment by abunda77** [comment]
change to sync "QUEUE_CONNECTION=sync"
