### ISSUE TITLE
Laravel 8 Support

### ISSUE THREAD

**Issue by shirazsoft** [laravel-filament/filament#12]
Hi
Please add laravel 8 support.

**Comment by ryanscherler** [comment]
Hi @shirazsoft - at the moment we aren't able to put much time into Filament, but are happy to accept PR's for upgrading to Laravel 8 if you're up for it!

**Comment by ryanscherler** [comment]
Closing this issue and moving this repository to a **read-only** state in favor of using [Laravel Jetstream](https://jetstream.laravel.com) for bootstrapping new applications.
