### ISSUE TITLE
getUploadedFileUsing is not working.

### ISSUE THREAD

**Issue by salihanmridha** [laravel-filament/filament#12012]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

v10.10

### PHP Version

PHP 8.1

### Problem description

On Filament V2 I could use getUploadedFileUrlUsing and it was working without only preview the file properly. 

Forms\Components\FileUpload::make('audio_file')->label("Audio File")
                                           ->disk('google')
                                           ->directory('quiz')
                                           ->visibility('public')
                                           ->preserveFilenames()
                                           ->enableOpen()
                                           ->enableDownload()
                                            ->getUploadedFileNameForStorageUsing(
                                                fn (TemporaryUploadedFile $file): string => (string) str($file->getClientOriginalName())
                                                    ->prepend('-' . Carbon::now()->valueOf()),
                                            )
                                           ->getUploadedFileUrlUsing(function (string $file){
                                               return 'https://mydomain.com/file.jpg';
                                           }),
                                           
 But in V3 this getUploadedFileUrlUsing is now not worked. I think the method is now renamed to getUploadedFileUsing
 
 but it is not working after upload the file and if I get it from url.
 
 here is my code below
 
 Forms\Components\FileUpload::make('quiz_audio')->label("Quiz Audio")
                                               ->disk('google')
                                               ->directory('quiz-audio')
                                               ->visibility('public')
                                               ->preserveFilenames()
                                               ->openable()
                                               ->downloadable()
                                               ->getUploadedFileNameForStorageUsing(
                                                   fn (TemporaryUploadedFile $file): string => (string) str($file->getClientOriginalName())
                                                       ->prepend('-'.\Carbon\Carbon::now()->valueOf()),
                                               )
                                               ->getUploadedFileUsing(function (string $file){
                                                   return 'https://mydomain.com/file.jpg';
                                               }),

### Expected behavior

if it return url it should display it from the url.

### Steps to reproduce

In your resource just add FileUpload Component and try to use getUploadedFileUsing method like this:

Forms\Components\FileUpload::make('quiz_audio')->label("Quiz Audio")
                                               ->disk('google')
                                               ->directory('quiz-audio')
                                               ->visibility('public')
                                               ->preserveFilenames()
                                               ->openable()
                                               ->downloadable()
                                               ->getUploadedFileNameForStorageUsing(
                                                   fn (TemporaryUploadedFile $file): string => (string) str($file->getClientOriginalName())
                                                       ->prepend('-'.\Carbon\Carbon::now()->valueOf()),
                                               )
                                               ->getUploadedFileUsing(function (){
                                                   return 'https://mydomain.com/file.jpg';
                                               }),

### Reproduction repository

https://github.com/salihanmridha/lmp

**Comment by danharrin** [comment]
No reproduction repository. Also using an undocumented internal feature, which has changed in v3. You need to return an array from this method now, please inspect the source code.

**Comment by freshleafmedia** [comment]
@danharrin how can developers tell which methods are internal?

I would expect that if the method is `public` (and doesn't have an `@internal` docblock) it can safely be called, is this not true with Filament?

**Comment by danharrin** [comment]
It's not a documented method. It can be safely called, but it could change between major versions without us documenting it in the upgrade guide. We try to avoid breaking changes to public methods in minor versions.
