### ISSUE TITLE
Performance issue when using multiple domains

### ISSUE THREAD

**Issue by Liosfr** [laravel-filament/filament#12053]
### Package

filament/filament

### Package Version

v4.48.2

### Laravel Version

v10.48.2

### PHP Version

8.3

### Problem description

Hello ! 

First of all, thank you for your work.

My laravel application is a pure api that handles a certain level of loads. For reasons of cost and ease of use, we decided to install filament on it, but on another domain. For the moment, the filament panel is empty; not even a resource has been created.

So I have my API domain: api.x.com/api/v1
My filament domain: filament.x.com/

When I went into production, I noticed a 250% increase in memory usage on overall traffic. With telescope on local, we can just see a boost on memory, but no request nor queries related to filament.
![image](https://github.com/filamentphp/filament/assets/25798370/426ca043-0ab5-4dd9-b43f-ccc6af0bec64)

On local env with just an health endpoint :  
**With Filament**
Memory usage	48.5 MB
**Without Filament**
Memory usage	44 MB

This with 5k req/s is not 

I recognise that this may be my uncommon usage, but i guess I'm not the only one who wants to install filament in addition to an existing application. 

I suspect the service provider, but I don't know enough about how filament works to say what should be done. Should filament boot itself if its path/domain doesn't concern it?

### Expected behavior

That filament only boots when it is in a context that affects it

### Steps to reproduce

- Setup an example API
- Add filament on it, with an custom domain
- All traffic take much more memory

### Reproduction repository

https://github.com/Liosfr/filament-perf

**Comment by danharrin** [comment]
Unfortunately not, the Filament service providers need to run in requests it is not being used by. This is because of the routes that get registered. Laravel's route caching needs to know what routes have been registered. Also, if you try and use the `route()` helper or `::getUrl()` to generate URLs to Filament, they will fail if Filament did not register the routes in the first place.
