### ISSUE TITLE
Relation Managers Error when editing a record

### ISSUE THREAD

**Issue by sawirricardo** [laravel-filament/filament#1208]
### Package

filament/filament

### Package Version

v2.7

### Laravel Version

v8.77

### Livewire Version

v2.8

### PHP Version

PHP 8.1.1

### Bug description

Tried to edit a relation record, should show modal, but showing error instead.

### Steps to reproduce

1. Create a relation manager
2. Refresh the page. Go somewhere else.
2. Try to access the resource again to edit a relation record

### Relevant log output

```shell
TypeError
Filament\Resources\RelationManagers\HasManyRelationManager::canEdit(): Argument #1 ($record) must be of type Illuminate\Database\Eloquent\Model, null given, called in /vendor/filament/filament/src/Resources/RelationManagers/Concerns/CanEditRecords.php on line 74
```

**Comment by danharrin** [comment]
Thanks. It's fixed in the latest version.
