### ISSUE TITLE
Filament\Tables\Table::getInverseRelationshipFor(): Argument #1 ($record) must be of type Illuminate\Database\Eloquent\Model

### ISSUE THREAD

**Issue by classicalguss** [laravel-filament/filament#12115]
### Package

filament/filament

### Package Version

v3.2.0

### Laravel Version

v10.0.0

### PHP Version

PHP 8.2.17

### Problem description

I am trying to use Associate::make()->multiple on a HasMany - BelongsTo relation. 

Searching and picking works fine, but as soon as I hit save I get the error. If I removed multiple() it will work fine.

Please keep in mind that I had to put 

### Expected behavior

Expected to save correctly.

### Steps to reproduce

My models are as follows

```
class Company extends Model
{
    use HasFactory;

     public function users(): HasMany
     {
	return $this->hasMany(User::class);
     }

}
```

And in User Model

```
public function company(): BelongsTo
{
	return $this->belongsTo(Company::class);
}
```

I ran this to produce the relation manager
`php artisan make:filament-relation-manager CompanyResource users name --associate
` 
And my code in the relation manager table() function is as follows

```
            ->headerActions([
                Tables\Actions\AssociateAction::make()->multiple()
            ])
```

### Reproduction repository

https://github.com/classicalguss/curly-disco

**Comment by saade** [comment]
I think the problem here its that when using `multiple()` `$data['recordId']` will be an array, then the `if` will not run since `$record` will be a `Collection`.

https://github.com/filamentphp/filament/blob/98c4703ad45227e19aa596cc8df060515a7feddd/packages/tables/src/Actions/AssociateAction.php#L77
