### ISSUE TITLE
FileImage cannot be enabled conditionally

### ISSUE THREAD

**Issue by miagg** [laravel-filament/filament#12121]
### Package

filament/filament

### Package Version

v3.2.61

### Laravel Version

v11.1.1

### Livewire Version

v3.4.9

### PHP Version

PHP 8.3.3

### Problem description

FileImage field cannot be conditionally enabled based on another field. 

```php
return $form
  ->schema([
      Checkbox::make('has_image')
          ->live(),
      FileUpload::make('image')
          ->disabled(fn (Get $get) => !$get('has_image')),
  ]);
```

https://github.com/filamentphp/filament/assets/6439071/2f6040ce-c19d-4c45-8c95-c30c12b4c560

Is there a way to disable the component dynamically? My need is to keep the component disabled with the image preview visible but no action buttons or drag-and-drop and only enable editing based on another field's value.

The `disabled` callback on image field is called every time the checkbox is clicked but it does not honor the disabled state.

### Expected behavior

The `FileImage` field should get refreshed and disabled based on the `disabled` callback.

### Steps to reproduce

1. Clone reproduction repository and head to `/admin/users/create`

Alternatively add the above code on any resource form.

### Reproduction repository

https://github.com/miagg/fileimage-disabled-reactivity

**Comment by danharrin** [comment]
This is a known behaviour that we do not have a way to fix. It is the same issue as https://github.com/filamentphp/filament/issues/10263, https://github.com/filamentphp/filament/issues/8951, https://github.com/filamentphp/filament/issues/8935, https://github.com/filamentphp/filament/issues/8097, https://github.com/filamentphp/filament/issues/3068

Maybe in a future major version we will be able to solve this, but currently we do not have a solution.
