### ISSUE TITLE
is someone active i have the same problem like him

### ISSUE THREAD

**Issue by Zakaria010701** [laravel-filament/filament#12184]
is someone active i have the same problem like him

_Originally posted by @Zakaria010701 in https://github.com/filamentphp/filament/issues/9063#issuecomment-2036833705_
            public function form(Form $form): Form
{
    return $form->schema([
        CheckboxList::make('branch')
            ->label('Filialen')
            ->options([
                'Frankfurt' => 'Frankfurt',
                'Wiesbaden' => 'Wiesbaden',
                'Viderma'   => 'Viderma',
            ])
            ->required(),

        CheckboxList::make('category_id')
            ->label('Kategorien')
            ->options(function () use ($form) {
                return Category::pluck('name', 'id');
            })
            ->afterStateUpdated(function ($set, $state) use ($form) {
                $selectedCategoryId = $state['values']['category_id'] ?? null;
                if ($selectedCategoryId) {
                    $selectedServices = Service::where('category_id', $selectedCategoryId)->pluck('id')->toArray();
                    
                    $set('services', $selectedServices);
                } else {
                    // Wenn keine Kategorie ausgewählt ist, leere die ausgewählten Services
                    $set('services', []);
                }
            })
            ->live(),

        CheckboxList::make('consultation_category_id')
            ->label('Beratungskategorie')
            ->options(function () use ($form) {
                return Category::pluck('name', 'id');
            })
            ->required(),

        CheckboxList::make('services')
            ->label('Services')
            ->options([])
            ->required(),
    ])->columns(4)->statePath('data');
}

}

**Comment by danharrin** [comment]
Please open a bug report following our template
