### ISSUE TITLE
laravel filament checkbox didnt work

### ISSUE THREAD

**Issue by Zakaria010701** [laravel-filament/filament#12183]
### Package

filament/filament

### Package Version

v.3.0.0

### Laravel Version

v.10,0.0

### PHP Version

PHP 8.3.0

### Problem description

Select category does not automatically select the content in the service

### Expected behavior

i want that if i choose something in category then i want that automatically will chose the services from the category   sorry for my english 

### Steps to reproduce

CheckboxList::make('category_id')
                ->label('Kategorien')
                ->options(function () {
                    return Category::pluck('name', 'id');
                })
                ->live()
                ->afterStateUpdated(function ($set, $state) {
                    $selectedCategoryId = $state['values']['category_id'] ?? null; 
                    $selectedServices = $selectedCategoryId ? Service::where('category_id', $selectedCategoryId)->pluck('id')->toArray() : [];
                    $set('servicesOptions', $selectedServices);
                })
                ->required(),
    
            CheckboxList::make('consultation_category_id')
                ->label('Beratungskategorie')
                ->options(function () {
                    return Category::pluck('name', 'id');
                })
                ->required(),
    
                CheckboxList::make('services')
                ->label('Services')
                ->options(Service::pluck('name', 'id'))
                ->disabled(fn(Get $get) =>!filled($get(path :'category_id')))
                ->required(),

### Reproduction repository

https://github.com/ALTrees/ladexiv

**Comment by Zakaria010701** [comment]
can someone please help me i am new

**Comment by danharrin** [comment]
No public reproduction repository

Questions can be asked in the discussion section or Discord
