### ISSUE TITLE
FileUpload Preview problem inside repeater

### ISSUE THREAD

**Issue by phpust** [laravel-filament/filament#12189]
### Package

filament/forms

### Package Version

^3.2

### Laravel Version

v10.10

### PHP Version

PHP 8.1

### Problem description

when i use FileUpload inside a form its fine and shows preview , even if is refresh the page.
but when i use FileUpload inside a repeater it shows preview until i refresh the page. then i got this:

![Screenshot 2024-04-04 at 16-56-12 Edit Test ](https://github.com/filamentphp/filament/assets/9350475/62f148f5-b60f-4ba9-9638-d5337a92bffa)

### Expected behavior

what should i do to fix this?

### Steps to reproduce

this is my code
```php[
            Forms\Components\Textarea::make($pre_unique_key.'_question')
                ->label("Question")
                ->columnSpan('full')
                ->autosize()
                ->hidden(fn(\Filament\Forms\Get $get):bool => $get('type')!=$key)
                ->visible(fn(\Filament\Forms\Get $get):bool => $get('type')==$key),
            Forms\Components\Repeater::make($pre_unique_key.'options')
                ->label("Options")
                ->collapsible()
                ->collapsed()
                ->itemLabel("dfgdgf")
                ->schema([
                    Forms\Components\FileUpload::make('option')
                        ->label("Option")
                        ->disk('public')
                        ->fetchFileInformation(false)
                        ->acceptedFileTypes(['image/jpeg','image/jpg','image/png','audio/mpeg','video/mp4','video/ogg','video/webm'])
                        ->maxSize(200000)
                        ->visibility('public')
                        ->columnSpan(3),
                    Forms\Components\Toggle::make("is_true")
                        ->columnSpan(1)
                        ->onColor('success')
                        ->offColor('danger')
                        ->inline(false),
                ])
                ->columns('4')
                ->columnSpan('2')
                ->hidden(fn(\Filament\Forms\Get $get):bool => $get('type')!=$key)
                ->visible(fn(\Filament\Forms\Get $get):bool => $get('type')==$key),
            ]
```

### Reproduction repository

https://github.com/phpust/filament-fileupload

**Comment by zepfietje** [comment]
Actual reproduction repository is required.

**Comment by phpust** [comment]
[zepfietje](https://github.com/zepfietje) this is the repository
https://github.com/phpust/filament-fileupload

i have another question too. is there any way to  set selected list for some of ToggleButtons options.
something like this
```
Forms\Components\ToggleButtons::make('words.list')
    ->options([
        'draft' => 'Draft',
        'scheduled' => 'Scheduled',
        'published' => 'Published'
    ])
    ->selected(['draft','published'])
    ->inline(),

**Comment by egproo** [comment]
@zepfietje also repeater inside repeater on edit (exstra empty fields being displayed)

**Comment by valpuia604** [comment]
@phpust I used your repo and everything is working fine. My guess for your own error is that you provide incorrect `APP_URL`

EDITED: Yes I am correct, because in your `.env.example` you put `APP_URL=http://127.0.0.1:8000/` but if you remove the last `/` from app_url (in .env) then it's working

![Screenshot from 2024-04-11 15-39-19](https://github.com/filamentphp/filament/assets/141896542/0e697025-8914-40af-9da3-6856bd9ca10e)

**Comment by danharrin** [comment]
Thanks @valpuia604
