### ISSUE TITLE
Select/Checkbox List with relationship should require the titleAttribute

### ISSUE THREAD

**Issue by bohdan-shulha** [laravel-filament/filament#12217]
### Package

filament/forms

### Package Version

v3

### Laravel Version

v11

### Livewire Version

v3

### PHP Version

PHP 8.3

### Problem description

It is not possible to use relationship() without specifying the `titleAttribute` anyway.

This will result in invalid SQL being formed:

```sql
SELECT
  DISTINCT "categories".*
FROM
  "categories"
  LEFT JOIN "category_post" ON "categories"."id" = "category_post"."category_id"
ORDER BY
  "categories"."" ASC -- note the order column name
```

The code that breaks (probably, can break at other call sites as well):

https://github.com/filamentphp/filament/blob/v3.2.63/packages/forms/src/Components/Select.php#L736

I'd be happy to submit a PR with the changes with direct instructions on how the behavior should be adjusted.

### Expected behavior

The `titleAttribute` should be required and:
1) To prevent backward compatibility - throw an exception;
2) Make it required in the relationship() method signature (v4?);

### Steps to reproduce

Create a new form with this field, don't forget to `preload()`:

```php
Select::make('categories')->relationship()->preload()->multiple();
```

### Reproduction repository

https://github.com/bohdan-shulha/filament-issues

**Comment by danharrin** [comment]
The param is not required if you use `getOptionLabelFromRecordUsing()`

**Comment by bohdan-shulha** [comment]
Oh, right. But can we have some kind of error/warning instead? It took a while to understand what's wrong.:(
