### ISSUE TITLE
Bug in query builder on polymorphic relation

### ISSUE THREAD

**Issue by daar** [laravel-filament/filament#12319]
### Package

filament/filament

### Package Version

v3.2.64

### Laravel Version

v10.48.7

### Livewire Version

v3.4.10

### PHP Version

PHP v8.3.4

### Problem description

When adding a column to a polymorphic relationship and sorting the column, the SQL query is not correct.

```PHP
                Tables\Columns\TextColumn::make('consultable.consultable_type')
                    ->sortable()
                    ->searchable(),
```

The resulting query is:

```SQL
SELECT
    *
FROM
    `laboratory_requests`
WHERE
    EXISTS(
    SELECT
        *
    FROM
        `payments`
    WHERE
        `laboratory_requests`.`id` = `payments`.`payable_id` AND `payments`.`payable_type` = 'App\Models\LaboratoryRequest' AND `status` = 0
) AND(DATE(`updated_at`) <= 2024 -04 -13)
ORDER BY
    `status` ASC,
    (
    SELECT
        `consultable_type`
    FROM
        `laboratory_requests` AS `laravel_reserved_0`
    WHERE
        `laravel_reserved_0`.`` = `laboratory_requests`.`consultable_id`
)
DESC
LIMIT 10 OFFSET 0
```

Which gives the error: **SQLSTATE[42S22]: Column not found: 1054 Unknown column 'laravel_reserved_0.' in 'where clause'**

### Expected behavior

To get it to work the following line:

```
  `laravel_reserved_0`.``
```

should instead be:

```SQL
  `laravel_reserved_0`.`id`
```

### Steps to reproduce

-

### Reproduction repository

-

**Comment by phato777** [comment]
I am also experiencing this same exact issue. I see it was closed because requirements for posting and reproducing weren't met, but just wanted y'all to know the OP isn't the only one with this issue. Just make a polymorphic one to one, add it to a table as a column with sortable and try to sort it, you'll see the issue.

**Comment by JairZijp** [comment]
Yep, I'm also having this issue
