### ISSUE TITLE
TextArea component filename

### ISSUE THREAD

**Issue by iancallahan** [laravel-filament/filament#1231]
### Package

filament/forms

### Package Version

v2.0

### Laravel Version

v8.17

### PHP Version

PHP 8.1

### Bug description

Everything was running locally but I ran into an error on a staging server - Class "Filament\Forms\Components\TextArea" not found.

It turns out this is due to the file for the TextArea component does not have a PascalCase filename. It is Textarea.php, and this can cause issues across servers with different capitalization configuration. 

I'm happy to do a pull request for this but for something so trivial I'm not sure if that's just more work on the maintainer's end. 

Thanks!

**Comment by danharrin** [comment]
Thank you, this will be fixed in the next version.

**Comment by danharrin** [comment]
As on the Mozilla website - Textarea is all 1 word - https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea

**Comment by iancallahan** [comment]
My bad, the fact that it worked locally on MacOS alongside the other pascal case component names threw me off. You're right. Thanks.

**Comment by ap1969** [comment]
@iancallahan I just had the same issue. TextArea works OK locally on Win 10, fails on deployment via ubuntu docker image. Luckily your post here helped me out. Thanks.

**Comment by ryangjchandler** [comment]
Class names, function names etc are historically case-**insensitive** in PHP, although this could differ from environment to environment. Best to use PHPStan or Psalm to do these sort of checks for you.
