### ISSUE TITLE
Import not Mapping the  result

### ISSUE THREAD

**Issue by codeies** [laravel-filament/filament#12320]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

10.10

### PHP Version

8.0

### Problem description

I am trying to map the csv fields during import but it dosent work ! Its always saying the field "x" is Required . Though its fine if we have exact same csv header as in DB
![Screenshot 2024-04-13 022726](https://github.com/filamentphp/filament/assets/69535487/aa33f444-b9db-4d23-80f6-cda40cda6672)
![columnmapping](https://github.com/filamentphp/filament/assets/69535487/fbf83c70-3410-4ce3-8d04-1831b3f1dfb5)

### Expected behavior

After selecting field from dropdown it should be mapped instead of require ! 
```
Console error
Uncaught TypeError: Cannot read properties of null (reading 'name')
    at livewire.js?id=239a5c52:351:19
    at Array.reduce (<anonymous>)
    at dataGet (livewire.js?id=239a5c52:348:27)
    at Object.get (livewire.js?id=239a5c52:9595:20)
    at getValue (livewire.js?id=239a5c52:3281:46)
    at livewire.js?id=239a5c52:3337:19
    at reactiveEffect (livewire.js?id=239a5c52:2369:18)
    at Object.effect2 [as effect] (livewire.js?id=239a5c52:2344:7)
    at effect (livewire.js?id=239a5c52:737:35)
    at wrappedEffect (livewire.js?id=239a5c52:753:29)
```

### Steps to reproduce

Try clicking Import . Select any of the field with ->requireMapping() , 

### Reproduction repository

https://github.com/codeies/reproduction-filament

**Comment by dmitry-udod** [comment]
@codeies Hi! Could you provide the full reproduction repository and the uploading file (products.csv)? Currently, I only see a part of the repository and can't reproduce the bug.

**Comment by danharrin** [comment]
Let us know when you've fixed the reproduction repo and we'll reopen this

**Comment by codeies** [comment]
I found the issue @danharrin , It was causing by the package joshembling/image-optimizer ! 
Leaving this comment will help anyone who is facing similar issue !

**Comment by malzariey** [comment]
> I found the issue @danharrin , It was causing by the package joshembling/image-optimizer ! Leaving this comment will help anyone who is facing similar issue !

Thanks @codeies ,

**Comment by lirimahmeti** [comment]
> I found the issue @danharrin , It was causing by the package joshembling/image-optimizer ! Leaving this comment will help anyone who is facing similar issue !

Did you find a fix or did you just remove that package?

**Comment by akn999** [comment]
@codeies Thank you
