### ISSUE TITLE
formatStateUsing doesn't work

### ISSUE THREAD

**Issue by Mahmoudreda66** [laravel-filament/filament#12324]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

v10.10

### PHP Version

v8.1

### Problem description

i use formatStateUsing method in some of my tables, it works for some columns and don't invoke in others like:

it works and invokes here:
`Tables\Columns\TextColumn::make('status')
        ->formatStateUsing(fn (Order $order) => $order->deadline ?? 'Not Exists')
        ->label('الحالة')
        ->searchable()`
        
and it doesn't work here:

`Tables\Columns\TextColumn::make('deadline')
        ->label('وقت الانتهاء')
        ->formatStateUsing(fn (Order $order) => $order->deadline ?? 'Not Exists')
        ->dateTime()
        ->sortable()`
        
`Tables\Columns\TextColumn::make('branch.name')
          ->formatStateUsing(fn (Order $order) => $order->deadline ?? 'Not Exists')
          ->numeric()
          ->sortable()`
          
          why?

### Expected behavior

to work nicely to invoke the method for all columns!

### Steps to reproduce

1- make resource
2- make column like relation column
3- use formatStateUsing

### Reproduction repository

https://github.com/Mahmoudreda66/customer-support

**Comment by malzariey** [comment]
I think its an expected behavior, as in the two columns 

```php
Tables\Columns\TextColumn::make('deadline') ->label('وقت الانتهاء') ->formatStateUsing(fn (Order $order) => $order->deadline ?? 'Not Exists') ->dateTime() ->sortable()

Tables\Columns\TextColumn::make('branch.name') ->formatStateUsing(fn (Order $order) => $order->deadline ?? 'Not Exists') ->numeric() ->sortable()
```

You are specifying the type of the column, either `numeric()` or `dateTime()`. 

Just use the first column 
```php
Tables\Columns\TextColumn::make('status') ->formatStateUsing(fn (Order $order) => $order->deadline ?? 'Not Exists') ->label('الحالة') ->searchable()
```
And format the dateTime in the `formatStateUsing`

**Comment by Mahmoudreda66** [comment]
@malzariey no i duplicated it for example only.

method doesn't work with any text column that gets its data from relationship

**Comment by malzariey** [comment]
I believe you would want to say that formatStateUsing is not working with null values. right?

**Comment by malzariey** [comment]
I believe what you are looking for is `placeholder()'

If the column value is null, `placeholder` is used instead of `formatState`

You have another option of using `getStateUsing` to customize the column value.

**Comment by danharrin** [comment]
`getStateUsing()` is used to define the content of the column. `formatStateUsing()` should only be used to FORMAT state that already exists. In this case, since there is no state, there is nothing to format.
