### ISSUE TITLE
Using the builder and removing a block in code does not remove the content from the Record on subsequent save.

### ISSUE THREAD

**Issue by RobertsG** [laravel-filament/filament#12338]
### Package

filament/filament

### Package Version

v3.2.47

### Laravel Version

v10.48.2

### PHP Version

PHP 8.3.0

### Problem description

The Builder block functionality has an issue when saving a record after having removed a Building blocks code from a Resource. The blocks json remains on the record.
This causes issues when using the records content in the future as it's not even possible to delete the leftover structure without re-enabling the Builder block that was used to create the Block entry for the record.

### Expected behavior

If a block is removed from a Builder and the Record is saved again, it should be removed from the document structure.

### Steps to reproduce

1. Create code in a resource with a Builder with a single Block or two, doesn't really matter.
2. Create a record with block.
3. Remove the used Builder block (not the builder it self) from the Resource code.
4. Open the record to first of all see that the block is not visible in the builder, even though the record contains the code for it (this of course is because the builder doesn't have instructions on how to display this block, so we're not focusing on this issue now).
5. Add new blocks or just save the Record.
6. Check out the document structure to see that it still contains the Deleted blocks code.

### Reproduction repository

https://github.com/RobertsG/filament-builder-block

**Comment by dmitry-udod** [comment]
@RobertsG  Hi! I cannot reproduce the bug. Could you clarify the reproduction steps or attach a video of the problem?"


https://github.com/filamentphp/filament/assets/4639175/dbfae4ab-1492-4c6f-8f2a-dd579778992d

**Comment by RobertsG** [comment]
You forgot to remove the Code block from the Resource code.
Here's a video recording: [https://photos.app.goo.gl/DVriQiTmY7gKUy3w9](https://photos.app.goo.gl/DVriQiTmY7gKUy3w9) (for some reason upload is not working)
The issue is that if a certain block is removed from the Builder at some point in the future, the existing data will persist forever, even if editing the record without the builder step.

**Comment by danharrin** [comment]
I disagree that should be the behaviour. It could result in unintentional data loss, which Filament will not use as a default behaviour.

If you remove code, you should create a migration to loop through all the builder JSON and remove the blocks.

**Comment by RobertsG** [comment]
What would you recommend I do in case the builder is made dynamically from a different resource?

**Comment by danharrin** [comment]
Use an observer on that resource to dispatch a job and make the data changes?
