### ISSUE TITLE
Database Notifications is not displayed correctly due to the ListPage parameter page=2 when the `$isPaginated` option is active

### ISSUE THREAD

**Issue by wallacemaxters** [laravel-filament/filament#12342]
### Package

filament/filament

### Package Version

v3.2.65

### Laravel Version

10.48.7

### Livewire Version

3.4.10

### PHP Version

8.2

### Problem description

Database notifications do not appear when we have a page=2 parameter in the url on the ListRecord page. From what I understand, the Filament\Notifications\Livewire::getNotifications() method returns paginated results and the url parameter affects notifications, when it should only affect ListRecord results.

### Expected behavior

 View notifications regardless of the parameter provided in the ListPage

### Steps to reproduce

1) Run the command php artisan migrate:fresh --seed
2) Login with e-mail `filament@test.com` and password `123456`
3) Go to "Users" page
4) Click in "2" pagination
5) Refresh page
6) Open the notifications

### Reproduction repository

https://github.com/wallacemaxters/filament-bug-report

**Comment by danharrin** [comment]
No reproduction repository

**Comment by wallacemaxters** [comment]
Please, reopen the issue. I updated the step to reproduction link

**Comment by dmitry-udod** [comment]
Hi all! It seems the bug exists; here is a confirmation:

https://github.com/filamentphp/filament/assets/4639175/f328f9d7-a7d6-4d5c-907d-5378c6c6d478

As a proposal to fix the bug, we could choose a different name for the GET parameter used for database notifications (I'm not sure about the param name)

```php 

return $this->getNotificationsQuery()->simplePaginate(50, pageName: 'notifications-page');

```
