### ISSUE TITLE
More ways to upload files

### ISSUE THREAD

**Issue by febelery** [laravel-filament/filament#1234]
### Package

filament/forms

### Package Version

v2.0.0

### Laravel Version

v8.77

### Livewire Version

v2.0

### PHP Version

PHP 8.1

### Bug description

Extended file upload is too painful, currently there are two ways S3 and local, I want to use other cloud providers, can only upload to the local server, and then upload on the local server, too slow

**Comment by danharrin** [comment]
This is not a bug, don't abuse issues like this. File upload providers that work with Laravel and Livewire work with Filament.
