### ISSUE TITLE
hiddenOn() and disabledOn() not working

### ISSUE THREAD

**Issue by NgYueHong** [laravel-filament/filament#12350]
### Package

filament/filament

### Package Version

3.2

### Laravel Version

11

### PHP Version

8.3

### Problem description

The form input does not hide or disabled on edit.

The hide and disabled function does work when click on the edit button on the table.
![image](https://github.com/filamentphp/filament/assets/6602432/b6bd60d6-d815-4723-90b6-f08a8448d1cd)

However, it does not work when click on the "edit" button from the modal.
![image](https://github.com/filamentphp/filament/assets/6602432/6604f912-a3eb-4e16-81fe-8b3c6f3c4adb)

```
public static function form(Form $form): Form
    {
        return $form
            ->schema([
                TextInput::make('name')->required(),
                TextInput::make('email')->email()->required()->disabledOn('edit'),
                TextInput::make('password')->password()->required()->hiddenOn('edit'),
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('id'),
                TextColumn::make('name'),
                TextColumn::make('email'),
            ])
            ->filters([
                //
            ])
            ->actions([
                Tables\Actions\ViewAction::make()
                    ->extraModalFooterActions([
                        Tables\Actions\EditAction::make()
                    ]),
                Tables\Actions\EditAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\BulkActionGroup::make([
                    Tables\Actions\DeleteBulkAction::make(),
                ]),
            ]);
    }

```

### Expected behavior

The form should hide and disabled as well even if click from the modal button.

### Steps to reproduce

Try to access the edit page from modal and you will see the `disabledOn()` and `hiddenOn()` not working.

### Reproduction repository

https://github.com/NgYueHong/FilamentBug

**Comment by dmitry-udod** [comment]
@NgYueHong @zepfietje Hi all! It's not a bug.

There are two different operations **edit** (when you click on Edit from the list) and **view.edit** (when you click on Edit button from View page).

So you need to change your code from:

```php

 TextInput::make('email')->email()->required()->disabledOn('edit'),
 TextInput::make('password')->password()->required()->hiddenOn('edit'),
```

To 

```php 
 TextInput::make('email')->email()->required()->disabledOn(['edit', 'view.edit']),
 TextInput::make('password')->password()->required()->hiddenOn(['edit', 'view.edit']),
```

Here is a quick demo


https://github.com/filamentphp/filament/assets/4639175/b54e20e5-8e80-460f-9964-0b4d9934d663
