### ISSUE TITLE
Error when calling preserveFilenames function in Class Forms\Components\FileUpload

### ISSUE THREAD

**Issue by Shieldforce** [laravel-filament/filament#12368]
### Package

filament/filament

### Package Version

3.1.31

### Laravel Version

10.48.8

### PHP Version

8.1

### Problem description

Error when calling preserveFilenames function in Class
Forms\Components\FileUpload

It doesn't generate any error but the file name is not kept!

### Expected behavior

so that the file persists with the same name

### Steps to reproduce

create a component form

Forms\Components\FileUpload::make('file')
                                     ->preserveFilenames()
                                     ->label('File Label'),

### Reproduction repository

https://github.com/Shieldforce/api-transactions

**Comment by dmitry-udod** [comment]
@Shieldforce Hi! There is no filament package in your reproduction repository :(

![image](https://github.com/filamentphp/filament/assets/4639175/63a360ac-5bb7-4787-b658-8c7205dab599)
