### ISSUE TITLE
Modal Cancel Action Triggering on modal open not when it closes

### ISSUE THREAD

**Issue by thesubhendu** [laravel-filament/filament#12380]
### Package

filament/filament

### Package Version

v3.2.25

### Laravel Version

10.15

### PHP Version

8.2

### Problem description

I want some code to execute when modal closes but code executed when modal opens

### Expected behavior

Code should be executed when modal closes not when opened

## This do not trigger any action when modal closed

```
 $table->actions([
                Action::make('help')
                    ->modalContent(view('actions.help'))
                    ->modalCancelAction(function (StaticAction $action) {
                         $action->label('Close');
                         return $action->action(function() {
                             info('Some laravel log');
                         });
                    }),
])

## This executed code but when modal opens not when it close.
```
## Also Tried
```
 $table->actions([
                Action::make('help')
                    ->modalContent(view('actions.help'))
                    ->modalCancelAction(function() {
                             info('some laravel log');
                         }),
])
```

**Comment by danharrin** [comment]
The cancel action is a *static* action, so it cannot run a callback function like that. It can only run a Livewire method like that. The callback is running to try and resolve the name of the Livewire method so it can be rendered to wire:click.

**Comment by CamKemBell** [comment]
I ran into a similar problem building a workflow on how to handle closing multiple modals, the easier way to handle it was to listen for the event on the page, then clear the properties that hold the actions which were going to be remounted. It's a bit hacky, but works supprisingly well.

@danharrin => It would be awesome to have a feature that we could use for more advanced Filament applications that have multiple modal workflows to be able to clear/shut all open modals.

```php
trait HandlesModalCloseActions
{
    #[On('close-modal')]
    public function closeActions(?string $id = null): void
    {
        if ($id !== null && Str::doesntContain($id, $this->getId())) {
            return;
        }

        $this->clearMountedActions();
        $this->dispatchLightboxCloseEvent($id);
    }
    
    protected function clearMountedActions(): void
    {
        $propertiesToClear = [
            // Table actions
            'mountedTableActions' => [],
            'mountedTableActionsData' => [],
            'mountedTableActionsArguments' => [],
            'mountedTableActionRecord' => null,

            // Form actions
            'mountedFormActions' => [],
            'mountedFormActionsData' => [],
            'mountedFormActionsArguments' => [],
            'mountedFormActionRecord' => null,

            // Standard actions
            'mountedActions' => [],
            'mountedActionsData' => [],
            'mountedActionsArguments' => [],
            'mountedActionRecord' => null,

            // Infolist actions
            'mountedInfolistActions' => [],
            'mountedInfolistActionsData' => [],
            'mountedInfolistActionsArguments' => [],
            'mountedInfolistActionRecord' => null,
            'mountedInfolistActionsComponent' => null,
        ];

        foreach ($propertiesToClear as $property => $defaultValue) {
            if (property_exists($this, $property)) {
                $this->$property = $defaultValue;
            }
        }
    }

    protected function dispatchLightboxCloseEvent(?string $id): void
    {
        if ($id === null) {
            return;
        }

        $this->dispatch('opened-form-component-action-modal', id: $id);
    }
}
```

**Comment by danharrin** [comment]
In v4 all action modals are unified and share a `mountedActions` prop together, so calling `cancelParentActions()` etc applies to all different types of modal.

**Comment by CamKemBell** [comment]
> In v4 all action modals are unified and share a `mountedActions` prop together, so calling `cancelParentActions()` etc applies to all different types of modal.

Will that close all open `X` modal close buttons? I would assume if it did, you would want it configurable?
That's what I was achieving with this above, hooking into the modal close button action, so we can clear the property that stores the modals when the `X` button is clicked, otherwise the user has to click the close button 1 at a time if we want to use the built-in close buttons.

Either way, looking forward to consolidating the actions when we upgrade, just waiting on some plugins that are lagging!
