### ISSUE TITLE
Disabling 'attachFiles' does not prevent files from being attached (MarkdownEditor/RichEditor)

### ISSUE THREAD

**Issue by ZacharyDuBois** [laravel-filament/filament#12392]
### Package

filament/filament

### Package Version

v3.2.70

### Laravel Version

v11.4.0

### Livewire Version

v3.4.10

### PHP Version

8.3

### Problem description

When adding `'attachFiles'` to the `disableToolbarButtons([...])`, file upload functionality is still present allowing a user to still upload a file (via drag/drop, copy/paste, etc).

(Side note, you need to update your issue template repo as it contains duplicate tables, references to Sanctum which isn't installed, etc).

### Expected behavior

Disabling `'attachFiles'` should inhibit a file upload from occurring. Could result in some newer developers making mistakes when implementing as it's not documented that disabling the item in the tool bar does not inhibit the action (I understand the method call specifically mentions toolbar buttons).

### Steps to reproduce

Create a new form with the following field:

```php
Forms\Components\MarkdownEditor::make('text')
    ->disableToolbarButtons(['attachFiles']),
Forms\Components\RichEditor::make('text')
    ->disableToolbarButtons(['attachFiles']),
```

You can still drag and drop a file and it will successfully upload.

### Reproduction repository

https://github.com/ZacharyDuBois/filament-file-upload-issue

**Comment by dmitry-udod** [comment]
@ZacharyDuBois Hi! Yes, there is a problem with the markdown editor, but I cannot reproduce the bug with the rich text editor. Please see the video below.


https://github.com/filamentphp/filament/assets/4639175/f4244e64-8574-41fe-be93-80305d5807df

**Comment by ignacio-dev** [comment]
This also happens with other things like blockquotes, headings, etc...

**Comment by ignacio-dev** [comment]
Any updates on this? As seen in @dmitry-udod’s video, the issue doesn’t happen with drag-and-drop, but copy-pasting allows adding disabled elements, and even unsupported ones (like `<h1>`?!)

**Comment by danharrin** [comment]
I don't think we can prevent copy-pasting unsupported elements in Trix, you should use an HTML sanitizer before outputting to ensure these don't end up on your site.

I think v4's move to TipTap could address this.
