### ISSUE TITLE
Tables\Columns\TextColumn Wrap() ins't work

### ISSUE THREAD

**Issue by felipe-balloni** [laravel-filament/filament#1244]
### Package

filament/filament

### Package Version

v2.8.11

### Laravel Version

v8.79.0

### PHP Version

php 8.0.14

### Bug description

I think it wrap()  of component Tables\Columns\TextColumn isn't working.

### Steps to reproduce

create a column into a table resource:

Tables\Columns\TextColumn::make('client.name')
                    ->label('Cliente')
                    ->wrap()
                    ->sortable()
                    ->searchable()
                    ->extraAttributes(['class' => 'max-w-60']),

**Comment by danharrin** [comment]
Just checked and it definitely works, but you need enough content within the column for it to take effect. This is something CSS controls, not Filament. If you inspect your column cells, they should contain the `whitespace-normal` class, indicating they can wrap.

**Comment by felipe-balloni** [comment]
Hi, @danharrin, sorry to insist on this...

It's my code:

```
public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('id')
                    ->label('#')
                    ->sortable(),
                Tables\Columns\TextColumn::make('client.name')
                    ->label('Cliente')
                    ->wrap()
                    ->sortable()
                    ->searchable()
                    ->extraAttributes(['class' => 'max-w-60']),
                Tables\Columns\BadgeColumn::make('type.name')
                    ->label('Tipo receita')
                    ->searchable()
                    ->colors(['success']),
                Tables\Columns\TextColumn::make('ophthalmologist')
                    ->label('Oftalmologista')
                    ->wrap()
                    ->sortable()
                    ->searchable(),
                Tables\Columns\TextColumn::make('comments')
                    ->label('Observações')
                    ->wrap()
                    ->sortable()
                    ->searchable()
                    ->extraAttributes(['class' => 'max-w-36']),
            ])
```

![Captura de Tela 2022-01-16 às 12 47 27](https://user-images.githubusercontent.com/19998735/149667294-c4d249c2-001c-4ad6-af12-c810e7be2aae.png)


Cells contain the _whitespace-normal_ class, however _tbody_ is set _whitespace-nowrap_ and I realize that removing this body class works...

Or I`m doing wrong? I'll be grateful if you show me what I did wrong.

**Comment by a-smily** [comment]
That has helped me :)

A ->description() with long text also had no wraps, it only worked after inserting this CSS class.

`->extraAttributes(['class' => 'whitespace-normal'])`

However, I had to search for a long time until I found this help..
