### ISSUE TITLE
Failed install

### ISSUE THREAD

**Issue by Hassanbhb** [laravel-filament/filament#12441]
### Package

filament/filament

### Package Version

v3.0.0

### Laravel Version

v11.4.0

### PHP Version

PHP 8.2.12

### Problem description

I get this error when I execute this command: `composer require filament/filament:"^3.2" -W`

```
./composer.json has been updated
Running composer update filament/filament --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - filament/filament v3.2.39 requires filament/support v3.2.39 -> satisfiable by filament/support[v3.2.39].
    - filament/filament v3.2.40 requires filament/support v3.2.40 -> satisfiable by filament/support[v3.2.40].
    - filament/filament v3.2.41 requires filament/support v3.2.41 -> satisfiable by filament/support[v3.2.41].
    - filament/filament v3.2.42 requires filament/support v3.2.42 -> satisfiable by filament/support[v3.2.42].
    - filament/filament v3.2.43 requires filament/support v3.2.43 -> satisfiable by filament/support[v3.2.43].
    - filament/filament v3.2.44 requires filament/support v3.2.44 -> satisfiable by filament/support[v3.2.44].
    - filament/filament v3.2.45 requires filament/support v3.2.45 -> satisfiable by filament/support[v3.2.45].
    - filament/filament v3.2.46 requires filament/support v3.2.46 -> satisfiable by filament/support[v3.2.46].
    - filament/filament v3.2.47 requires filament/support v3.2.47 -> satisfiable by filament/support[v3.2.47].
    - filament/filament v3.2.48 requires filament/support v3.2.48 -> satisfiable by filament/support[v3.2.48].
    - filament/filament v3.2.49 requires filament/support v3.2.49 -> satisfiable by filament/support[v3.2.49].
    - filament/filament v3.2.50 requires filament/support v3.2.50 -> satisfiable by filament/support[v3.2.50].
    - filament/filament v3.2.51 requires filament/support v3.2.51 -> satisfiable by filament/support[v3.2.51].
    - filament/filament v3.2.52 requires filament/support v3.2.52 -> satisfiable by filament/support[v3.2.52].
    - filament/filament v3.2.53 requires filament/support v3.2.53 -> satisfiable by filament/support[v3.2.53].
    - filament/filament v3.2.54 requires filament/support v3.2.54 -> satisfiable by filament/support[v3.2.54].
    - filament/filament v3.2.55 requires filament/support v3.2.55 -> satisfiable by filament/support[v3.2.55].
    - filament/filament v3.2.56 requires filament/support v3.2.56 -> satisfiable by filament/support[v3.2.56].
    - filament/filament v3.2.57 requires filament/support v3.2.57 -> satisfiable by filament/support[v3.2.57].
    - filament/filament v3.2.58 requires filament/support v3.2.58 -> satisfiable by filament/support[v3.2.58].
    - filament/filament v3.2.59 requires filament/support v3.2.59 -> satisfiable by filament/support[v3.2.59].
    - filament/filament v3.2.60 requires filament/support v3.2.60 -> satisfiable by filament/support[v3.2.60].
    - filament/filament v3.2.61 requires filament/support v3.2.61 -> satisfiable by filament/support[v3.2.61].
    - filament/filament v3.2.62 requires filament/support v3.2.62 -> satisfiable by filament/support[v3.2.62].
    - filament/filament v3.2.63 requires filament/support v3.2.63 -> satisfiable by filament/support[v3.2.63].
    - filament/filament v3.2.64 requires filament/support v3.2.64 -> satisfiable by filament/support[v3.2.64].
    - filament/filament v3.2.65 requires filament/support v3.2.65 -> satisfiable by filament/support[v3.2.65].
    - filament/filament v3.2.66 requires filament/support v3.2.66 -> satisfiable by filament/support[v3.2.66].
    - filament/filament v3.2.67 requires filament/support v3.2.67 -> satisfiable by filament/support[v3.2.67].
    - filament/filament v3.2.68 requires filament/support v3.2.68 -> satisfiable by filament/support[v3.2.68].
    - filament/filament v3.2.69 requires filament/support v3.2.69 -> satisfiable by filament/support[v3.2.69].
    - filament/filament v3.2.70 requires filament/support v3.2.70 -> satisfiable by filament/support[v3.2.70].
    - filament/filament[v3.2.36, ..., v3.2.38] require illuminate/console ^10.45 -> satisfiable by illuminate/console[v10.45.0, ..., v10.48.8].
    - filament/filament[v3.2.0, ..., v3.2.35] require illuminate/console ^10.0 -> satisfiable by illuminate/console[v10.0.0, ..., v10.48.8].
    - filament/filament v3.2.71 requires filament/support v3.2.71 -> satisfiable by filament/support[v3.2.71].
    - filament/support[v3.2.39, ..., v3.2.71] require ext-intl * -> it is missing from your system. Install or enable PHP's intl extension.
    - illuminate/console[v10.0.0, ..., v10.48.8] require nunomaduro/termwind ^1.13 -> found nunomaduro/termwind[v1.13.0, ..., v1.15.1] but these were not loaded, likely because it conflicts with another require.
    - Root composer.json requires filament/filament ^3.2 -> satisfiable by filament/filament[v3.2.0, ..., v3.2.71].

To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-intl` to temporarily ignore these required extensions.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.`
```

### Expected behavior

There shouldn't be an error.

### Steps to reproduce

Install Laravel with Laravel installer.
run this command:  `composer require filament/filament:"^3.2" -W`

### Reproduction repository

no need

**Comment by NasFahmi** [comment]
i have same problem, and i already turn on extension intl in php.ini, but still get the same error required ext-intl, have a solution yet?

**Comment by NasFahmi** [comment]
I found a way to install filament without the "required ext-intl error", maybe this is tricky, all these problems are due to xampp not being able to load the intl extension correctly,
1. uncomment intl extension in php.ini,
2. check whether intl has been loaded using php -m, on my computer, when I check using git bash/powershell intl is not loaded, but when using xampp shell intl is loaded correctly,

when i check intl extension in powershell
![image](https://github.com/filamentphp/filament/assets/103549350/805e5c99-ba47-459a-a731-c516f23ce44b)
by using xampp shell you can find intl extenstion is loaded correctly
![image](https://github.com/filamentphp/filament/assets/103549350/3f92bcac-5181-4dd2-867f-68f5231a759e)
>>
![image](https://github.com/filamentphp/filament/assets/103549350/ea30a289-bbf9-42d6-9851-dd54ec97f9dc)
3. When in xampp shell check again whether intl has been loaded using php -m,
4. If the intl extension has loaded correctly, create a laravel 11 + filament project using xampp shell
5. and thats it, now you can install filament with xampp shell
![image](https://github.com/filamentphp/filament/assets/103549350/bab65037-77a1-4839-b7bb-3dbe7e8f4f28)

update:
after doing this method, intl extension loaded correcly when using powershell/git bash terminal

**Comment by Hassanbhb** [comment]
Sorry for the late reply, I kind of moved on after being stuck as I was new to Laravel.
Your solution is great, I had to uncomment intl & zip extentions in the php.ini file.

**Comment by irfanahmadhidayat** [comment]
> I found a way to install filament without the "required ext-intl error", maybe this is tricky, all these problems are due to xampp not being able to load the intl extension correctly,
> 
> 1. uncomment intl extension in php.ini,
> 2. check whether intl has been loaded using php -m, on my computer, when I check using git bash/powershell intl is not loaded, but when using xampp shell intl is loaded correctly,
> 
> when i check intl extension in powershell ![image](https://private-user-images.githubusercontent.com/103549350/327948830-805e5c99-ba47-459a-a731-c516f23ce44b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzU2MzksIm5iZiI6MTcyMzUzNTMzOSwicGF0aCI6Ii8xMDM1NDkzNTAvMzI3OTQ4ODMwLTgwNWU1Yzk5LWJhNDctNDU5YS1hNzMxLWM1MTZmMjNjZTQ0Yi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QwNzQ4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT05OWRlNzI1ZGRmNDM3YmQ3N2FmNDI4NzZlM2JhMTg2ZDU0ZTc2MTMxMzk4NDM1ODcxYjJjZGZjYTA1ZDNmMThlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.iJJXPGHxYlKP3Sqto_98eMrEIHM4bqigPOMcTjaquxA) by using xampp shell you can find intl extenstion is loaded correctly ![image](https://private-user-images.githubusercontent.com/103549350/327948901-3f92bcac-5181-4dd2-867f-68f5231a759e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzU2MzksIm5iZiI6MTcyMzUzNTMzOSwicGF0aCI6Ii8xMDM1NDkzNTAvMzI3OTQ4OTAxLTNmOTJiY2FjLTUxODEtNGRkMi04NjdmLTY4ZjUyMzFhNzU5ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QwNzQ4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04M2JjNDJkNjEwNTM4MGIzNGJmNTgyNTk5ZmNmMTQ1YTBjNjhkMGMzNzkxYWRhMjYzMjA0N2IwMDVjMDhkOTBlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.nSdTiSKVNk0RHNF-wlpgi76DxSxogrLy4OxVNgfOJQ8)
> 
> > >
> 
> ![image](https://private-user-images.githubusercontent.com/103549350/327948943-ea30a289-bbf9-42d6-9851-dd54ec97f9dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzU2MzksIm5iZiI6MTcyMzUzNTMzOSwicGF0aCI6Ii8xMDM1NDkzNTAvMzI3OTQ4OTQzLWVhMzBhMjg5LWJiZjktNDJkNi05ODUxLWRkNTRlYzk3ZjlkYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QwNzQ4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNWQ2MjU1MmZkMTVmNDI2YzRmYzE0NWE0ODZmNDU4MDliY2VmOGU4ZDc2N2EyNjM0Y2U5ZTY5MmRmZTRkNDljJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kkS6ipylYNxcMjP-PNZTn83z7MICHGJEMEVLosGDBzY) 3. When in xampp shell check again whether intl has been loaded using php -m, 4. If the intl extension has loaded correctly, create a laravel 11 + filament project using xampp shell 5. and thats it, now you can install filament with xampp shell ![image](https://private-user-images.githubusercontent.com/103549350/327948983-bab65037-77a1-4839-b7bb-3dbe7e8f4f28.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM1MzU2MzksIm5iZiI6MTcyMzUzNTMzOSwicGF0aCI6Ii8xMDM1NDkzNTAvMzI3OTQ4OTgzLWJhYjY1MDM3LTc3YTEtNDgzOS1iN2JiLTNkYmU3ZThmNGYyOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxM1QwNzQ4NTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZjliZTY4NzVlNjdlM2YyMDZlYTEwMWQ3NDBhYWIxYzZiOTQxYmMyNmNmNDdmYTVjM2I0NzNjMWIwMTgwMjM1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.kIc90IhSDBVzrFRtO9OfkkpoMVnSEXdX-Pn14nl10sE)
> 
> update: after doing this method, intl extension loaded correcly when using powershell/git bash terminal

it's work for me, thanks for the solustions
