### ISSUE TITLE
phpstan error on filament macro

### ISSUE THREAD

**Issue by ariaieboy** [laravel-filament/filament#12464]
### Package

filament/filament

### Package Version

v3

### Laravel Version

v11

### Livewire Version

v3

### PHP Version

8.3

### Problem description

Since filamentphp uses a custom macroable trait phpstan, larastan does not recognize the custom macros we add to the components.

### Expected behavior

According to this issue https://github.com/larastan/larastan/issues/1935 we need a phpstan extension that adds the filament macroable to it.

### Steps to reproduce

1. add a custom macro to your service provider 
2. use your macro in the code base
3. analyze the code using phpstan

### Reproduction repository

https://github.com/ariaieboy/filament-phpstan-issue

**Comment by danharrin** [comment]
This is a feature request really, so going to close. Feel free to release an extension as a package that people can pull in

**Comment by deonoize** [comment]
Use https://github.com/ImSuperlative/larastan-filament-macro
