### ISSUE TITLE
ToggleButtons multiple not working on edit-page

### ISSUE THREAD

**Issue by eae-omeyer** [laravel-filament/filament#12474]
### Package

filament/filament

### Package Version

v3.2.71

### Laravel Version

v11.5.0

### Livewire Version

v3.4.10

### PHP Version

PHP 8.3.6

### Problem description

After adding a ToggleButton component with multiple enabled to a resource form, it works as expected on the create-page, but not on the edit-page. On the edit-page, clicking on any unselected option will select all options and clicking on any selected option will unselect all options. Practically all or nothing.

### Expected behavior

The ToggleButton component with multiple enabled should also work as expected on the edit-page.

### Steps to reproduce

Add a ToggleButton component with multiple enabled to any resource form and try to use it on the edit-page.

### Reproduction repository

https://github.com/eae-omeyer/issue-filament-togglebuttons-multiple

**Comment by dmitry-udod** [comment]
@eae-omeyer Hi! There's a problem with the 'options' parameter in your database for the test user. You cast 'options' to an array, but in the database, you have a null value. Please check the video below.


https://github.com/filamentphp/filament/assets/4639175/aba039b3-37c5-491b-bafc-837c8213ce9a

**Comment by eae-omeyer** [comment]
Thank you very much for your commitment. Setting an empty array as the default value solves the problem. I wrongly assumed that the component can handle 'null'.
