### ISSUE TITLE
filament forms repeater afterStateUpdated is not called problem

### ISSUE THREAD

**Issue by XarchencoMO** [laravel-filament/filament#12505]
### Package

filament/forms

### Package Version

v2.17.53

### Laravel Version

v9|v10

### Livewire Version

v2.12.6

### PHP Version

8.2

### Problem description

When i calling afterStateUpdated on RepeaterFiled in filament/forms, nothing happens (i used xdebug to keep track of what was happening, but nothing was happening)

### Expected behavior

In my opinion, after adding/deleting/moving an object inside the repeater, this method should have been called, perhaps when changing one of the fields inside the form specified in the repeater, it should be called, but here I'm not 100% sure

### Steps to reproduce

if you are using docker, you can start my docker compose contrainers 
`docker  compose up -d --build`
then you can go inside the "app" container: 
'docker compose exec -ti app /bin/sh'
then inside the "app" container: 
- `composer i `
- 'cp .env.example .env'
- 'php artisan key:generate'
- `php artisan migrate`

### Reproduction repository

https://github.com/XarchencoMO/filament-forms-repeater-problem

**Comment by elasti-co** [comment]
When I try to place in Repeater with relationship() option any field with array casting using dot notation it fails to bind model.

```
Repeater::make('tasks')
    ->relationship()
    ->schema([
        TextInput::make('content.text')
    ]);
```

Maybe it is somehow connected with this issue.
Don't know how to solve the problem.
Now upgrading from v2 where it worked fine.

**Comment by danharrin** [comment]
Yeah this has been fixed in v3 now, if we did it in v2 it would be a breaking change :)

```php
Repeater::make('tasks')
    ->relationship()
    ->schema([
        Group::make([
            TextInput::make('text'),
        ])->relationship('content'),
    ]);
```
