### ISSUE TITLE
Exception Route [login] not defined. when navigating to second panel.

### ISSUE THREAD

**Issue by nettsite** [laravel-filament/filament#12529]
### Package

filament/filament

### Package Version

3.2

### Laravel Version

11.5

### PHP Version

PHP Version 8.3.6

### Problem description

Exception Route [login] not defined. when navigating to second panel.

### Expected behavior

Filament login page

### Steps to reproduce

Installed a new Laravel app.
Installed Filament: ```composer require filament/filament:"^3.2" -W```
Ran install: ```php artisan filament:install --panels``` - named the first panel "tenant", changed path to ''
Created second panel: php artisan make:filament-panel landlord

Navigating to the "tenant" panel, http://merlin, I am redirected to http://merlin/login as expected, and see the login page.
Navigating to the second panel, http://merlin/landlord, I get the exception.

```
:~/Projects/merlin$ composer update
Loading composer repositories with package information
Updating dependencies
Nothing to modify in lock file
Installing dependencies from lock file (including require-dev)
Nothing to install, update or remove
```
```
@php artisan filament:upgrade
  ⇂ public/js/filament/forms/components/color-picker.js  
  ⇂ public/js/filament/forms/components/date-time-picker.js  
  ⇂ public/js/filament/forms/components/file-upload.js  
  ⇂ public/js/filament/forms/components/key-value.js  
  ⇂ public/js/filament/forms/components/markdown-editor.js  
  ⇂ public/js/filament/forms/components/rich-editor.js  
  ⇂ public/js/filament/forms/components/select.js  
  ⇂ public/js/filament/forms/components/tags-input.js  
  ⇂ public/js/filament/forms/components/textarea.js  
  ⇂ public/js/filament/tables/components/table.js  
  ⇂ public/js/filament/widgets/components/chart.js  
  ⇂ public/js/filament/widgets/components/stats-overview/stat/chart.js  
  ⇂ public/js/filament/filament/app.js  
  ⇂ public/js/filament/filament/echo.js  
  ⇂ public/js/filament/notifications/notifications.js  
  ⇂ public/js/filament/support/async-alpine.js  
  ⇂ public/js/filament/support/support.js  
  ⇂ public/css/filament/forms/forms.css  
  ⇂ public/css/filament/support/support.css  
  ⇂ public/css/filament/filament/app.css  

   INFO  Successfully published assets!  

   INFO  Configuration cache cleared successfully.  

   INFO  Route cache cleared successfully.  

   INFO  Compiled views cleared successfully.  

   INFO  Successfully upgraded!  
```

### Reproduction repository

https://github.com/nettsite/merlin.git

**Comment by nettsite** [comment]
I forgot to mention I added spatie/laravel-multitenancy, but it isn't implemented.

**Comment by declum** [comment]
Tenant has `->login()`, but Landloard panel doesnt have. After adding `->login()` to your sample repo, login page is presented.

**Comment by nettsite** [comment]
Thank you, that works. 

Should the ```php artisan make:filament-panel landlord``` not add the login() function, in the same way that 
```php artisan filament:install --panels``` does?

**Comment by declum** [comment]
I think default panel stub has login.

https://github.com/filamentphp/filament/blob/5bb040c5f819a80340e2180942c88f353567a96e/packages/support/stubs/DefaultPanelProvider.stub
https://github.com/filamentphp/filament/blob/5bb040c5f819a80340e2180942c88f353567a96e/packages/support/stubs/PanelProvider.stub

**Comment by danharrin** [comment]
Thanks @declum
