### ISSUE TITLE
LARAVEL 11 - WARN  We've attempted to register the AdminPanelProvider in your [bootstrap/providers.php] file. If you get an error while trying to access your panel then this process has probably failed. You can manually register the service provider by adding it to the array.

### ISSUE THREAD

**Issue by BaltasarOrtiz** [laravel-filament/filament#12535]
### Package

filament/filament

### Package Version

v3.2.57

### Laravel Version

v11.0

### Livewire Version

v3.0.0

### PHP Version

PHP 8.2.12

### Problem description

php artisan filament:install --panels

  What is the ID? [admin]
❯ admin

  AdminPanelProvider.php already exists, do you want to overwrite it? (yes/no) [yes]
❯ yes

   INFO  Filament panel [C:\laragon\www\Proyectos\courses_fillament\app\Providers/Filament/AdminPanelProvider.php] created successfully.  

   WARN  We've attempted to register the AdminPanelProvider in your [bootstrap/providers.php] file. If you get an error while trying to access your panel then this process has probably failed. You can manually register the service provider by adding it to the array.

  ⇂ C:\laragon\www\Proyectos\courses_fillament\public\js\filament\forms\components\color-picker.js  
  ⇂ C:\laragon\www\Proyectos\courses_fillament\public\js\filament\forms\components\date-time-picker.js
  ⇂ C:\laragon\www\Proyectos\courses_fillament\public\js\filament\forms\components\file-upload.js
  ⇂ C:\laragon\www\Proyectos\courses_fillament\public\js\filament\forms\components\key-value.js
  ⇂ C:\laragon\www\Proyectos\courses_fillament\public\js\filament\forms\components\markdown-editor.js
  ⇂ C:\laragon\www\Proyectos\courses_fillament\public\js\filament\forms\components\rich-editor.js
  ⇂ C:\laragon\www\Proyectos\courses_fillament\public\js\filament\forms\components\select.js
  ⇂ C:\laragon\www\Proyectos\courses_fillament\public\js\filament\forms\components\tags-input.js
  ⇂ C:\laragon\www\Proyectos\courses_fillament\public\js\filament\forms\components\textarea.js
  ⇂ C:\laragon\www\Proyectos\courses_fillament\public\js\filament\tables\components\table.js
  ⇂ C:\laragon\www\Proyectos\courses_fillament\public\js\filament\widgets\components\chart.js
  ⇂ C:\laragon\www\Proyectos\courses_fillament\public\js\filament\widgets\components\stats-overview\stat\chart.js
  ⇂ C:\laragon\www\Proyectos\courses_fillament\public\js\filament\filament\app.js
  ⇂ C:\laragon\www\Proyectos\courses_fillament\public\js\filament\filament\echo.js
  ⇂ C:\laragon\www\Proyectos\courses_fillament\public\js\filament\notifications\notifications.js
  ⇂ C:\laragon\www\Proyectos\courses_fillament\public\js\filament\support\async-alpine.js
  ⇂ C:\laragon\www\Proyectos\courses_fillament\public\js\filament\support\support.js
  ⇂ C:\laragon\www\Proyectos\courses_fillament\public\css\filament\forms\forms.css
  ⇂ C:\laragon\www\Proyectos\courses_fillament\public\css\filament\support\support.css
  ⇂ C:\laragon\www\Proyectos\courses_fillament\public\css\filament\filament\app.css

   INFO  Successfully published assets!

   INFO  Configuration cache cleared successfully.

   INFO  Route cache cleared successfully.  

   INFO  Compiled views cleared successfully.

   INFO  Successfully upgraded!  

  All done! Would you like to show some love by starring the Filament repo on GitHub? (yes/no) [yes]
❯ no.

### Expected behavior

I should be able to run the following command `php artisan filament:install --panels` correctly and then this one `php artisan make:filament-user`, but I can't because the panels are not installed correctly.

### Steps to reproduce

First install filament:
`composer require filament/filament:"^3.2.57" -W`
After that this one:
`php artisan filament:install --panels`

### Reproduction repository

https://github.com/BaltasarOrtiz/courses_filament

### Relevant log output

```shell
WARN  We've attempted to register the AdminPanelProvider in your [bootstrap/providers.php] file. If you get an error while trying to access your panel then this process has probably failed. You can manually register the service provider by adding it to the array.
```

**Comment by APM-Thomas-Hempel** [comment]
I have the same issue. When you run the panel installation again it throws an error, that the AdminPanelProvider already exists. But it actually doesn't

```
➜  git:(main) ✗ php artisan filament:install --panels    

[...shortend...]

   ERROR  app/Providers/Filament/AdminPanelProvider.php already exists, aborting.  

Failed to run artisan filament:install --panels: exit status 1

➜ git:(main) ✗ ls -l app/Providers/                       
-rw-r--r--  1 thomas  staff  361 Apr  9 16:13 AppServiceProvider.php
```

**Comment by dmitry-udod** [comment]
As for me it's not an issue Filament just warn you that it has modified your code...

**Comment by danharrin** [comment]
I don't see anything wrong here, do you think the issue can be closed @dmitry-udod ?

**Comment by danharrin** [comment]
The WARNING is a WARNING and not an error, it tells you how to troubleshoot if the installation command doesn't exist? It doesn't mean that the installation failed?

**Comment by dmitry-udod** [comment]
@danharrin  In my opinion, it's common behavior and not an issue. Can be closed.

**Comment by danharrin** [comment]
I think theres quite a high chance I might be misunderstanding why this issue was opened. If I am misunderstanding, please @ me and explain further what the problem is, I will reopen.

**Comment by BaltasarOrtiz** [comment]
@danharrin 

The problem occurs when I want to install the panels as mentioned above. It does register in `[bootstrap/providers.php]`, but when I try the following command `php artisan make:filament-user ` I get the following error: COMMAND -> `PS C:\xampp\htdocs\courses_filament> php artisan make:filament-user`  ERROR ->
`Filament has not been installed yet: php artisan filament:install --panels`. 

_So, even if I run the command to install the panels it doesn't seem to work properly because it doesn't allow me to run the other filament commands._

The providers file: [bootstrap/providers.php]
```
return [
    App\Providers\AppServiceProvider::class,
    App\Providers\Filament\AdminPanelProvider::class,
    App\Providers\FortifyServiceProvider::class,
    App\Providers\JetstreamServiceProvider::class,
];
```

**Comment by ismoil-nosr** [comment]
> @danharrin
> 
> The problem occurs when I want to install the panels as mentioned above. It does register in `[bootstrap/providers.php]`, but when I try the following command `php artisan make:filament-user ` I get the following error: COMMAND -> `PS C:\xampp\htdocs\courses_filament> php artisan make:filament-user` ERROR -> `Filament has not been installed yet: php artisan filament:install --panels`.
> 
> _So, even if I run the command to install the panels it doesn't seem to work properly because it doesn't allow me to run the other filament commands._
> 
> The providers file: [bootstrap/providers.php]
> 
> ```
> return [
>     App\Providers\AppServiceProvider::class,
>     App\Providers\Filament\AdminPanelProvider::class,
>     App\Providers\FortifyServiceProvider::class,
>     App\Providers\JetstreamServiceProvider::class,
> ];
> ```

Hi, I ran into this problem today. After a while I found out that you have to add `->default()` into your `AdminPanelProvider`.
[Link to the similar issue](https://github.com/filamentphp/filament/discussions/10369)

**Comment by BaltasarOrtiz** [comment]
The `->default()` is already in `AdminPanelProvider`, I reinstalled everything again to verify what you mentioned and even though that option is already there I still get the same error.

```class AdminPanelProvider extends PanelProvider
{
    public function panel(Panel $panel): Panel
    {
        return $panel
            ->default()
            ->id('admin')
            ->path('admin')
            ->login()
            ->colors([
                'primary' => Color::Amber,
            ])........................................
            
```

**Comment by danharrin** [comment]
Please publish the new reproduction repository
