### ISSUE TITLE
JS Select form field in a Wizard with a dynamic schema triggers a JS error `Livewire Entangle Error: Livewire property cannot be found on component`

### ISSUE THREAD

**Issue by matthewnessworthy** [laravel-filament/filament#12561]
### Package

filament/forms

### Package Version

v3.2.72

### Laravel Version

v11.6.0

### Livewire Version

v3.4.11

### PHP Version

PHP 8.2.18

### Problem description

When including a JS powered Select form field  in a Wizard step, where the step can dynamically contain a schema without a Select (or an empty schema), the JS powered Select throws an error.
Additionally, the Select field then does not save its contents to the state.
This is specific to adding a Wizard, existing Wizards work as expected.

### Expected behavior

The JS Select component should not cause a JS error and should correctly update the state with its contents

### Steps to reproduce

Setup the project
```
composer install
npm install
npm run build
```

Start the webserver
```
php artisan serve
```

Go to the Page resource page http://127.0.0.1:8000/admin/pages/create

Click `Add to content blocks`

Select the radio button `Widget 1`
Check the browser console, you will see an error similar to the following:
```
Livewire Entangle Error: Livewire property ['data.content_blocks.96526d4c-b088-471c-b16f-c598838b2294.data.broken_js_select_box'] cannot be found on component: ['app.filament.resources.page-resource.pages.create-page']
```

In the `Reproduction repository` below i have linked to the commit that specifically contains the form in question.

### Reproduction repository

Repo: https://github.com/matthewnessworthy/filamentphp-wizard-bug
Commit: https://github.com/matthewnessworthy/filamentphp-wizard-bug/commit/7916e0dc8d23e4cd14d30378902c6829f334c054

**Comment by matthewnessworthy** [comment]
Additionally, I've added  a commit https://github.com/matthewnessworthy/filamentphp-wizard-bug/commit/bd96ed550c951d3dc8951ba99058b16aea57e50e where it shows the data is not being saved from the JS Select box, example output in from the `mutateFormDataBeforeCreate` method. Note that the select box input `broken-js-select-box` is empty 

```
array:1 [▼ // app/Filament/Resources/PageResource/Pages/CreatePage.php:14
  "content_blocks" => array:1 [▼
    0 => array:2 [▼
      "type" => "widget"
      "data" => array:4 [▼
        "widget-2-text" => null
        "widget" => "widget-1"
        "widget-1-text" => "test"
        "broken-js-select-box" => null
      ]
    ]
  ]
]
``` 

<img width="537" alt="Screenshot 2024-05-02 at 10 25 25" src="https://github.com/filamentphp/filament/assets/5653887/265ee8e6-8825-4789-9418-d546e9d19609">

**Comment by matthewnessworthy** [comment]
Further, the `CheckboxList` also does not work correctly, selecting 1 selects all, unselecting 1 unselects all, and the result is not available as an array/json in `mutateFormDataBeforeCreate `
```
array:1 [▼ // app/Filament/Resources/PageResource/Pages/CreatePage.php:14
  "content_blocks" => array:1 [▼
    0 => array:2 [▼
      "type" => "widget"
      "data" => array:4 [▼
        "widget" => "widget-2"
        "widget-2-checkbox" => true
        "widget-2-text" => "test"
        "broken-js-select-box" => null
      ]
    ]
  ]
]
```
<img width="738" alt="Screenshot 2024-05-02 at 13 41 33" src="https://github.com/filamentphp/filament/assets/5653887/79f02ac7-2a4b-40a9-b98e-c72bafd04ffa">

**Comment by matthewnessworthy** [comment]
@danharrin would you mind taking a peek at this bug when you have a moment?

**Comment by dmitry-udod** [comment]
@matthewnessworthy Hi! The bug occurs because Livewire is trying to access a non-existing property in the Wizard data. As a temporary solution you can try setting a default value for your widget component. I know this isn't a perfect solution, but it works :) Check the video below please.

https://github.com/filamentphp/filament/assets/4639175/7879a4e7-56df-45ad-9dcf-d6a8e777b05b

**Comment by matthewnessworthy** [comment]
@dmitry-udod Thanks for taking the time to have a look and suggest a temporary fix. 
It only appears to work because the select box is named the same in each of the conditions in the 2nd step, and if i were to use 3 steps or more it would also not be viable.
I've pushed a commit naming the select box differently each time that indicates what I am talking about.

**Comment by matthewnessworthy** [comment]
I've moved the checkbox issue to its own issue https://github.com/filamentphp/filament/issues/12602

**Comment by danharrin** [comment]
#12600
