### ISSUE TITLE
ActionGroup::configureUsing not working properly

### ISSUE THREAD

**Issue by sitenzo** [laravel-filament/filament#12569]
### Package

filament/filament

### Package Version

v3.2.72

### Laravel Version

v11.6.0

### Livewire Version

v3.4.11

### PHP Version

PHP 8.2.11

### Problem description

`ActionGroup::configureUsing` not working properly.
Only the ->icon() is being applied.

### Expected behavior

Properties set on `ActionGroup::configureUsing` will be applied.

### Steps to reproduce

Add a ActionGroup to Headeractions or TableActions

Add following code to AppServiceProvider.php

```php
        Tables\Actions\ActionGroup::configureUsing(function (Tables\Actions\ActionGroup $ActionGroup): void {
            $ActionGroup
                ->icon('heroicon-o-face-smile')
                ->label('Actions')
                ->button()
                ->extraAttributes([
                    'class' => 'opacity-70',
                ]);
        });

        \Filament\Actions\ActionGroup::configureUsing(function (\Filament\Actions\ActionGroup $ActionGroup): void {
            $ActionGroup
                ->label('Actions')
                ->icon('heroicon-o-face-smile')
                ->button()
                ->extraAttributes([
                    'class' => 'opacity-70',
                ]);
        });
```

Example on how it must look

![image](https://github.com/filamentphp/filament/assets/52133032/f03602bb-5422-4902-8cf5-17311c56bc97)

how it looks

![image](https://github.com/filamentphp/filament/assets/52133032/bf45b5b3-08c4-41ec-9d9c-92bbb8486c38)

As you see only the icon will be applied.

### Reproduction repository

https://github.com/sitenzo/FilamentPhpTest

**Comment by dmitry-udod** [comment]
@sitenzo Hi! It seems we have some config overriding here. However, if you set the `isImportant: true` parameter (undocumented), everything works as expected. Please check the video below.


https://github.com/filamentphp/filament/assets/4639175/0e154aad-66f2-41d9-bce3-be9507b02c5f

**Comment by sitenzo** [comment]
@dmitry-udod Thanks for this solution, it indeed works as expected.
