### ISSUE TITLE
User cannot verify email when canAccessPanel() checks for hasVerifiedEmail()

### ISSUE THREAD

**Issue by Tklaversma** [laravel-filament/filament#12577]
### Package

filament/filament

### Package Version

v3

### Laravel Version

v11.5

### Livewire Version

v3

### PHP Version

PHP 8.2

### Problem description

In the `AdminPanelProvider` I have:
```php
public function panel(Panel $panel): Panel
{
    return $panel
        // ...
        ->login()
        ->emailVerification()
        // ...
}
```
which enables the feature that users must first verify their email address, before they can login.

So:
1. user registers
2. user receives email with link to verify his email address
3. clicks on the link and is shown the login page (Filament now has the signature available in the backed to compare)
4. user fills in credentials and clicks on login

At this moment the user's email address is verified and the user is logged in.

**Problem:**
I have this in my User model:
```php
public function canAccessPanel(Panel $panel): bool
{
    return $this->hasVerifiedEmail();
}
```
which makes sure that only users with a verified email address can login, which is a nice feature to have.

BUT, I cannot verify my email address now, since I need to have a verified email 😕 .

How should I be able to make use of this `canAccessPanel()` where I only allow users with a verified email address, but still allow users to verify their email address (clicking the signed URL in the email they receive to verify their email address)?

Help?

**Comment by renatofrota** [comment]
Add emailVerification() method to the $panel chain on [Admin]PanelProvider.php. Remove the check for hasVerifiedEmail() on canAccessPanel().
