### ISSUE TITLE
sidebar not show correctly in spa mode

### ISSUE THREAD

**Issue by Arsham-rmz** [laravel-filament/filament#12592]
### Package

filament/filament

### Package Version

v3.2.72

### Laravel Version

v10.48.10

### Livewire Version

v3.4.12

### PHP Version

PHP 8.1.12

### Problem description

![داشبورد - sms-center - Google Chrome 2024-05-02 23-07-23](https://github.com/filamentphp/filament/assets/19541275/6127b256-50f6-481c-9b80-3c23a1983ed8)

### Expected behavior

it should work correctly 

### Steps to reproduce

in spa mode when click on a link , the sidebar will change position based on spa top load bar
it's happen when i update filament to last version
i don't know what was previous version

### Reproduction repository

https://github.com/filamentphp/filament

**Comment by navidsafavi** [comment]
Hey, I have same problem. In RTL mode with spa() config you can see this issue, actually is for progress-bar loading style.
issue is there, any new update?

**Comment by navidsafavi** [comment]
problem in nprogress plugin
use this, can solve temporary your problem
@Arsham-rmz 

`
        FilamentView::registerRenderHook(
            PanelsRenderHook::STYLES_AFTER,
            fn (): string => '<style>
           .nprogress-custom-parent #nprogress .spinner, .nprogress-custom-parent #nprogress .bar {position: fixed!important}
            </style>',
        );
`
