### ISSUE TITLE
Checkboxes in a CheckboxList, when included in a Wizard step, toggles all checkboxes in the group regardless of the one toggled

### ISSUE THREAD

**Issue by matthewnessworthy** [laravel-filament/filament#12602]
### Package

filament/forms

### Package Version

v3.2.72

### Laravel Version

v3.2.72

### Livewire Version

v3.4.11

### PHP Version

PHP 8.2.18

### Problem description

When including a JS powered CheckboxList form field in a Wizard step, where the step can dynamically contain a schema, the CheckboxList toggles all on every checkbox click.

### Expected behavior

When toggling a checkbox in a CheckboxList only that checkbox should be toggled

### Steps to reproduce

Setup the project
```
composer install
npm install
npm run build
```

Start the webserver
```
php artisan serve
```

Go to the Page resource page http://127.0.0.1:8000/admin/pages/create

Click Add to content blocks

Select the radio button `Select + Checkboxes + Text` and click `Next`
Toggle any of the checkboxes and you will see all the checkboxes toggle

![Mov to](https://github.com/filamentphp/filament/assets/5653887/36ffd899-494b-4716-9429-3e884fd93fa2)

### Reproduction repository

https://github.com/matthewnessworthy/filamentphp-wizard-bug

**Comment by dmitry-udod** [comment]
@matthewnessworthy Hi! Thanks for test environment :) I have submitted a  PR to solve this bug  check #12605, please

**Comment by danharrin** [comment]
Please follow this guide, specifically the `afterStateUpdated()` part: https://filamentphp.com/docs/3.x/forms/advanced#dynamic-fields-based-on-a-select-option
