### ISSUE TITLE
`->keyBindings(['mod+enter'])` only works once

### ISSUE THREAD

**Issue by bilogic** [laravel-filament/filament#12619]
### Package

filament/filament

### Package Version

v3.2.73

### Laravel Version

v11.6.0

### Livewire Version

v3.4.12

### PHP Version

8.2.18

### Problem description

There are 2 problems here, 1 might be a clue to the other

1. `ctrl` + `enter` works the first time, form is submitted, subsequent attempts have no effect, form not submitted
2. If mouse click on `Comment`, the textbox will become empty, for `ctrl` + `enter` however, the textbox does not become empty... this is weird and also a bug

### Expected behavior

1. `ctrl` + `enter` should work repeatedly
2. `ctrl` + `enter` should also empty the textbox just like clicking on `Comment`

### Steps to reproduce

As explained in problem description

### Reproduction repository

https://github.com/bilogic/filament-issue/tree/ctrl-enter-only-once

**Comment by dmitry-udod** [comment]
Hi! Duplicate of #8870

**Comment by bilogic** [comment]
cool thanks!
