### ISSUE TITLE
Disable is not working for file upload / spatie media after mount

### ISSUE THREAD

**Issue by philippbuerger** [laravel-filament/filament#1263]
### Package

filament/forms

### Package Version

v2.9.1

### Laravel Version

v8.79.0

### Livewire Version

v2.9.0

### PHP Version

PHP 8.0

### Bug description

The `disabled()` method is not working for the file upload / spatie media file upload after the component is mounted. If the condition is true while mounting the component, the field is correctly disabled, but if the condition gets true while "runtime" the field gets not disabled.

**Comment by danharrin** [comment]
Hey, this is a bug with FilePond, which does not allow the field to be disabled (with the `disabled` HTML attribute) after it has been initialised. Sorry about that.

**Comment by robertorinaldi-dev** [comment]
There is a disabled property in filepond, can't we use that? https://pqina.nl/filepond/docs/api/instance/properties/#core-properties

**Comment by robertorinaldi-dev** [comment]
Has it the same issue like the disabled attribute?

**Comment by danharrin** [comment]
Yeah, how do we set this dynamically from Blade?

**Comment by robertorinaldi-dev** [comment]
Mmm couldn't we watch a `disabled` parameter as we do with `state`?
When I have a little more time maybe I'll take a look at it and see if I can make a PR

**Comment by robertorinaldi-dev** [comment]
Haven't tried, but I was thinking that `multiple` might have the same problem too, right?

**Comment by danharrin** [comment]
Yeah, multiple would as well. Can't imagine how we would watch `disabled` as a parameter, `state` works because its a public property on the LW component.
