### ISSUE TITLE
The POST method is not supported for route admin/login

### ISSUE THREAD

**Issue by Osub** [laravel-filament/filament#12643]
### Package

filament/filament

### Package Version

v3

### Laravel Version

v11

### Livewire Version

v3

### PHP Version

php8.2

### Problem description

The POST method is not supported for route admin/login. Supported methods: GET, HEAD.

https://flareapp.io/share/KPgMLkq5

### Expected behavior

https://flareapp.io/share/KPgMLkq5

### Steps to reproduce

https://flareapp.io/share/KPgMLkq5

### Reproduction repository

https://github.com/filamentphp/filament/

### Relevant log output

```shell
https://flareapp.io/share/KPgMLkq5
```

**Comment by sunnybherwani** [comment]
I'm also encountered with this issue.
Do you guys got any solution for this?
