### ISSUE TITLE
Repeater won't send values to database when 2 or more fields are inside the repeater.(i've to use same name as the input's name but how can i name them when 2 or more fields are there?)

### ISSUE THREAD

**Issue by isubarnaL** [laravel-filament/filament#12640]
### Package

filament/forms

### Package Version

v3.2

### Laravel Version

v11

### PHP Version

PHP 8.2.12

### Problem description

this is my resource code 
```

                Repeater::make('tripplans')
                ->schema([
                    TextInput::make('triptitle')
                    ->required(),
                    TextInput::make('tripdesc')
                    ->required(),
                ])
                ->addActionLabel('Add Another Day')
                ->columns(2)
                ->columnSpan(2),
               

```
if i just make the name of repeater triptitle/tripdesc it will send the data of that named field and won't send input data of other field
### Expected behavior

i wanted it to just work normally and the values to be stored as json in db.

### Steps to reproduce

using repeater multiple times is not working.

### Reproduction repository

https://github.com/isubarnaL/travel

**Comment by isubarnaL** [comment]
I've found that when i change the name of the repeater to triptitle, it sends the value of triptitle input as intended but its still not sending the value of tripdesc. how can i write the name of the repeater so as to send the value of all input fields?

**Comment by efremov-ie** [comment]
@isubarnaL It should work

```
Repeater::make('tripplans')
    ->schema([
        TextInput::make('tripplans.triptitle')
        ->required(),
        TextInput::make('tripplans.tripdesc')
        ->required(),
    ])
    ->addActionLabel('Add Another Day')
    ->columns(2)
    ->columnSpan(2),
```

**Comment by isubarnaL** [comment]
@efremov-ie Its not working.The same error.
```
1364 Field 'triptitle' doesn't have a default value
```

**Comment by danharrin** [comment]
No public reproduction repo.

`tripplans` needs to be a JSON column in your database. `triptitle` and `tripdesc` should not exist. All data will be stored in one column. If you need alt behaviour, you need to modify the form data before save and fill to extract the values into the separate columns.
