### ISSUE TITLE
Move to Alpine.js Sort plugin

### ISSUE THREAD

**Issue by danharrin** [laravel-filament/filament#12666]

**Comment by CharrafiMed** [comment]
I noticed this issue is currently unassigned, and I would like to help with it. Can I take on this task?
If there are any specific guidelines or requirements I should follow, please let me know.
Thank you!

**Comment by danharrin** [comment]
Hi, @awcodes are you interested in someone else helping out here? If yes, maybe pass on any info @CharrafiMed might need? Or maybe you don't have any information for them and they can go ahead and start working on the ticket? Thanks

**Comment by awcodes** [comment]
@CharrafiMed feel free to take a crack at it. I started it but, didn't get very far. Let me know if you have any questions.

**Comment by CharrafiMed** [comment]
@awcodes oki thanks, I will start working on it soon.

**Comment by danharrin** [comment]
I think this was attempted quite a bit and we weren't able to get it working with all the same features we had before
