### ISSUE TITLE
UI - Switch/Toggle button whitespace clickable

### ISSUE THREAD

**Issue by babakfp** [laravel-filament/filament#1269]
### Package

filament/filament

### Package Version

The one that is used in the demo

### Laravel Version

_

### PHP Version

_

### Bug description

![Screenshot 2022-01-17 031928](https://user-images.githubusercontent.com/44144724/149760777-dbe40dc3-d0b5-4bd6-80b7-81049253e6d2.png)
The red area is clickable because of the `flex` class, use `inline-flex` instead.

**Comment by ryangjchandler** [comment]
@babakfp Please feel free to open a PR with this change, we'd really appreciate it! :)

**Comment by danharrin** [comment]
Changing that class would break hints AFAIK

**Comment by babakfp** [comment]
> Changing that class would break hints AFAIK

What is that?

**Comment by danharrin** [comment]
Theres hint text that can be added to any form component using `hint('text here')`

Removing the full width flex would probably break the `justify-between`, right?

**Comment by babakfp** [comment]
> Removing the full width flex would probably break the justify-between, right?

Nop

**Comment by babakfp** [comment]
If the parent has `justify-between`, it will still be full-width, but if it doesn't have it, it will be inline.

**Comment by danharrin** [comment]
Just checked, changing it to `inline-flex` does break hints.

<img width="622" alt="Screenshot 2022-01-18 at 08 47 05" src="https://user-images.githubusercontent.com/41773797/149902239-a907da44-7f26-43c3-999a-b1c7af99a9f4.png">

This should be aligned to the right, as we're using `justify-between`.

**Comment by danharrin** [comment]
Instead, we should remove the `flex-1` from the label element. I've just done this, and it'll be available in the next release.

**Comment by danharrin** [comment]
It's been released
