### ISSUE TITLE
Cannot log in to panel if User model id type is string (UUID)

### ISSUE THREAD

**Issue by barkoczi** [laravel-filament/filament#12701]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

v11

### Livewire Version

v3.4.12

### PHP Version

PHP 8.3

### Problem description

After a fresh install, I modified the App/Model/User.php to have primary key string (in order to store unique id):
`class User extends Authenticatable
{
    use HasFactory, Notifiable;
    public $keyType = 'string';
    public $incrementing = false;
...
 public static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            $model->id = (string) uniqid("usr_");
        });
    }
`

Also modified the 0001_01_01_000000_create_users_table.php migrate file:
`....
 Schema::create('users', function (Blueprint $table) {
            $table->uuid('id')->primary();
....`

After these modification I re-migrated the database, created a new user, but I am not able to log in to the panel anymore: it just redirect to the login screen. 

I debugged the app a little bit, the user record queried correctly at login, but in the vendor/filament/filament/src/Http/Middleware/Authenticate.php L22
`if (!$guard->check()) {
            $this->unauthenticated($request, $guards);
            return;
  }`

the $guard->check() remain null and unauthenticate the user. 

Could you give me some clue why it is not working with PK type string and why it is working PK type int?

### Expected behavior

User can log in even the User model PK is string.

### Steps to reproduce

`$ laravel new
 $ composer require filament/filament:"^3.2" -W
 $ php artisan filament:install --panels
 $ php artisan migrat`

Change App/Model/User.php

`class User extends Authenticatable
{
    use HasFactory, Notifiable;
    public $keyType = 'string';
    public $incrementing = false;
...
 public static function boot()
    {
        parent::boot();

        static::creating(function ($model) {
            $model->id = (string) uniqid("usr_");
        });
    }`

Modify the 0001_01_01_000000_create_users_table.php migrate file:
`
....
 Schema::create('users', function (Blueprint $table) {
            $table->uuid('id')->primary();
....
`

Refresh database and create new user:
`$ php artisan migrate:fresh
 $ php artisan make:filament-user`

The User record will be created correctly, but can't log in anymore, even the credentials are correct, it will be redirected to the login screen. 

### Reproduction repository

https://github.com/barkoczi/fl2

**Comment by barkoczi** [comment]
Got an answer on Discord: the generated id is not a valid UUID that's why it is deleted.

**Comment by ghost** [comment]
in case anyone from google runs into this, I had the same problem

if you change your `users` table primary key from an `id` to a `uuid`, you need to also make a change to the `sessions` table migration.

change this:

```php
$table->foreignId('user_id')->nullable()->index();
``` 

to this:

```php
$table->foreignUuid('user_id')->nullable()->index();
```

**Comment by campaigncenter** [comment]
> in case anyone from google runs into this, I had the same problem
> 
> if you change your `users` table primary key from an `id` to a `uuid`, you need to also make a change to the `sessions` table migration.
> 
> change this:
> 
> ```
> $table->foreignId('user_id')->nullable()->index();
> ```
> 
> to this:
> 
> ```
> $table->foreignUuid('user_id')->nullable()->index();
> ```

In case anyone else is searching for Sessions migration, check 0001_01_01_000000_create_users_table.php which has multiple tables including Sessions.
