### ISSUE TITLE
php artisan make:fileament-resource generate wrong code if a column is an enum

### ISSUE THREAD

**Issue by rabol** [laravel-filament/filament#12717]
### Package

filament/filament

### Package Version

v3.2.76

### Laravel Version

v11.7.0

### PHP Version

v8.3.6

### Problem description

If you have a  column on your model that is of type enum then the generated code by ```php artisan make:filament-resource UserResource -G``` is not correct.

this is generated
```
Tables\Columns\TextColumn::make('user_level')
                    ->numeric()
                    ->sortable(),
```

### Expected behavior

That the code generated is valid and working.

### Steps to reproduce

Use the repo, login select the users

### Reproduction repository

https://github.com/rabol/filament-bug

**Comment by giacomomasseron** [comment]
I cloned your repo but this is the migration:

    $table->integer('user_level')->default(0);

it's not an enum

**Comment by rabol** [comment]
On the model it’s casted to a enum, how would you otherwise do it?

it works in all other parts of the app

**Comment by giacomomasseron** [comment]
You could use the `enum` function of a migration.

IMHO seems more an enhancement, instead of a bug.

Filament gets database schema to create the list and the form. It does not check the laravel casts.

**Comment by rabol** [comment]
a boolean work even if it stored in the db as an int

**Comment by zepfietje** [comment]
This isn't a bug if the column is an integer in the database indeed.
