### ISSUE TITLE
Copyable() is not working on a TextColumn in a table

### ISSUE THREAD

**Issue by JobiJoba** [laravel-filament/filament#12740]
### Package

filament/filament

### Package Version

v3.2.76

### Laravel Version

v11.7.0

### Livewire Version

v3.0

### PHP Version

PHP 8.3.0

### Problem description

I'm using the copyable() attribute on a TextColumn but unfortunately, it doesn't execute correctly. 

I've an error in the console log. 

I thought it was due to the fact that I've Thai Text in that field but I tried with multiple fields and it does the same thing. I also tried on another resource. I've reproduce the error in a different repo and the same issue arise.
![image](https://github.com/filamentphp/filament/assets/6494791/dbc1a79a-e82d-4656-a465-28504b9c2d73)

### Expected behavior

The text is the clipboard

### Steps to reproduce

Go on the page User in the example repo and click on the name of your user, it does not display a message and show an error message in the console.

### Reproduction repository

https://github.com/JobiJoba/filament-issue-textcolumn-copyable

### Relevant log output

```shell
(I've put a screenshot in the Problem description)
```

**Comment by zepfietje** [comment]
Are you accessing the site over HTTPS? That's required for the clipboard API to work.

**Comment by JobiJoba** [comment]
Argh, of course not :)
Is it possible to put the "SSL" in red in the doc ? or maybe also a better error message / warning ?

**Comment by zepfietje** [comment]
The error isn't a Filament error, so nothing to do there.
We don't mark words in red elsewhere in the docs, so I guess it's just a matter of actually reading what's there. 😆
