### ISSUE TITLE
Use many time same extend custom field on page and display problem

### ISSUE THREAD

**Issue by jechazelle** [laravel-filament/filament#12758]
### Package

filament/filament

### Package Version

v3.2.76

### Laravel Version

v11.7

### Livewire Version

v3.4.12

### PHP Version

8.2

### Problem description

hi,
I tried to use many time the same custom field extend from RichEditor (class MentionsRichEditor extends RichEditor) and I have a problem with the display.

I tried with different state :

**basic display:**
```
MentionsRichEditor::make('content')
    ->mentionsItems(),

MentionsRichEditor::make('content2')
    ->mentionsItems(),

MentionsRichEditor::make('content3')
    ->mentionsItems(),
```

I see this:
<img width="635" alt="Capture d’écran 2024-05-13 à 11 59 08" src="https://github.com/filamentphp/filament/assets/6713790/30098a17-9bd8-4bdc-bb8f-be7ed0ea0dce">

**tab display:**
```
Tabs::make('Tabs')
  ->tabs([
      Tabs\Tab::make('Tab 1')
          ->schema([
              MentionsRichEditor::make('content')
                  ->mentionsItems(),
          ]),
      Tabs\Tab::make('Tab 2')
          ->schema([
              MentionsRichEditor::make('content2')
                  ->mentionsItems(),
          ]),
      Tabs\Tab::make('Tab 3')
          ->schema([
              MentionsRichEditor::make('content3')
                  ->mentionsItems(),
          ]),
  ])->activeTab(2)
```

Tab1:
<img width="636" alt="Capture d’écran 2024-05-13 à 12 00 44" src="https://github.com/filamentphp/filament/assets/6713790/e6f05cc5-6179-47ed-96a5-fbd7339d2b2b">

Tab2:
<img width="630" alt="Capture d’écran 2024-05-13 à 12 01 04" src="https://github.com/filamentphp/filament/assets/6713790/011a2652-8681-4fc2-8f78-5a265c2ed48a">

Tab3:
<img width="637" alt="Capture d’écran 2024-05-13 à 12 01 16" src="https://github.com/filamentphp/filament/assets/6713790/60069147-64b8-4b23-9156-ff227473c53f">

### Expected behavior

Nice display.

### Steps to reproduce

1. Create a custom field 
```
php artisan make:form-field MentionsRichEditor
```

2. Extend the custom field 
```
<?php

namespace App\Forms\Components;

use Filament\Forms\Components\RichEditor;

class MentionsRichEditor extends RichEditor
{
    protected string $view = 'forms.components.mentions-rich-editor';

    protected array $mentionsItems = [];

    public function mentionsItems(): static
    {
        $this->mentionsItems = [
            [
                'key' => 'test',
                'link' => 'profil'
            ],
            [
                'key' => 'test2',
                'link' => 'profil2'
            ]
        ];

        return $this;
    }

    public function getMentionsItems(): array
    {
        return $this->mentionsItems;
    }
}
``` 

3. In the view, use rich editor
```
<div>
    @include('filament-forms::components.rich-editor')
</div>

@assets
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tributejs/3.3.2/tribute.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tributejs/3.3.2/tribute.min.css" />
@endassets

<script>
    // Wait for the page to load before executing our code
    window.addEventListener('load', () => {
        // Get the component id, using the $getId() function of our RichEditor
        const id = '{{ $getId() }}';
console.log(id);
        // Create the Tribute instance
        const tribute = new Tribute({
            // The values are the users that can be mentioned, so we will get this list from the mentionsItems variable that we created before in our custom component
            values: @json($getMentionsItems(), JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),

            // Here we will customize the way that the mention must be shown, so when the user will mention another a link will be injected into the RichEditor with a link to the mentioned user's profile
            selectTemplate: function(item) {
                if (typeof item === "undefined") return null;
                if (this.range.isContentEditable(this.current.element)) {
                    return '<a href="' + item.original.link + '">@' + item.original.key + '</a>';
                }
                return "@" + item.original.key;
            },
        });

        // Attach the tribute instance to the RichEditor using the id retrieved above
        tribute.attach(document.getElementById(id));

        // Get the editor instance to override "keypress" and "keydown" events by an empty function
        const editor = document.getElementById(id).editor;
        if (editor != null) {
            editor.composition.delegate.inputController.events.keypress = function() {};
            editor.composition.delegate.inputController.events.keydown = function() {};
        }
    });
</script>
```

4. use the custom field on resource, in tab many time:
```
Tabs::make('Tabs')
->tabs([
    Tabs\Tab::make('Tab 1')
        ->schema([
            MentionsRichEditor::make('content')
                ->mentionsItems(),
        ]),
    Tabs\Tab::make('Tab 2')
        ->schema([
            MentionsRichEditor::make('content2')
                ->mentionsItems(),
        ]),
    Tabs\Tab::make('Tab 3')
        ->schema([
            MentionsRichEditor::make('content3')
                ->mentionsItems(),
        ]),
])->activeTab(2)
```

### Reproduction repository

https://github.com/jechazelle/filament-custom-field

**Comment by danharrin** [comment]
And this doesn't happen when you replace the custom rich editor with the standard rich editor?

**Comment by jechazelle** [comment]
Thx @danharrin for your answer!

With "normal" field, it's ok:
```

Tabs::make('Tabs')
  ->tabs([
      Tabs\Tab::make('Tab 1')
          ->schema([
              RichEditor::make('content'),
          ]),
      Tabs\Tab::make('Tab 2')
          ->schema([
              RichEditor::make('content2'),
          ]),
      Tabs\Tab::make('Tab 3')
          ->schema([
              RichEditor::make('content3'),
          ]),
  ])->activeTab(2)
```


It's when I extend the view:
```
@include('filament-forms::components.rich-editor')
```

**Comment by danharrin** [comment]
The `@include` needs to be at the first level of the component, it cannot be wrapped in a div as it will interfere with the field wrapper.

**Comment by jechazelle** [comment]
I had tried without the div and I had the same problem (https://github.com/jechazelle/filament-custom-field/blob/main/resources/views/forms/components/mentions-rich-editor.blade.php):

```
@include('filament-forms::components.rich-editor')
```

**Comment by aotearoait** [comment]
I have experienced the same issue with a custom tab. The livewire error is `Uncaught Snapshot missing on Livewire component with id:` this occurs when you have tabs with more than 3 tabs and with custom tabs.
What is more unusual, if you have multiple tabs with custom livewire views, it only does this with the first one.
After Save
![image](https://github.com/filamentphp/filament/assets/33107115/bd4fcf6c-e99a-43c1-8d50-91cecedd258e)
Before Save
![image](https://github.com/filamentphp/filament/assets/33107115/aa348774-c732-4f6c-ba3f-118d47ad670f)

**Comment by danharrin** [comment]
Make sure the nested Livewire components have unique `key`s

**Comment by aotearoait** [comment]
> Make sure the nested Livewire components have unique `key`s

Yeah both have unique keys but still an issue, did you resolve your issue?

**Comment by aotearoait** [comment]
I think this is still an active issue.
I have 2 tabs with custom components eg `Livewire::make(Boundary::class)`
I have tested keeping both custom components empty apart from the wrapper with a key on each and it still throws a JS error `livewire.js?id=770f7738:4599 Uncaught Component not found: UC8OPitFqAqnvvOBynlv`
So these are empty components and still throws this error. It then causes the save button and other actions to no longer work.

**Comment by danharrin** [comment]
I think its a completely unrelated issue that you should open separately with a separate reproduction repository
