### ISSUE TITLE
Slow Initial Page Load Time Despite Cache Clearing and Setting in Filament Demo

### ISSUE THREAD

**Issue by dpenacton** [laravel-filament/filament#12751]
### Package

filament/filament

### Package Version

3.0.0

### Laravel Version

v11.0

### Livewire Version

3.0.0

### PHP Version

8.3.0

### Problem description

When attempting to clear and set the cache for the Filament demo on GitHub, there persists a significant delay in loading the initial page, taking over 40 seconds. Despite cache clearing and reconfiguration, the issue persists, impacting the user experience.

Despite the cache clearing and reconfiguration process, the initial page load time remains slow, taking over 40 seconds. Subsequent page loads show improved performance, indicating a potential caching issue during the initial load.

### Expected behavior

It should load faster once all the caches are set

### Steps to reproduce

Steps to Reproduce:
1. Clone the Filament demo repository: `git clone https://github.com/laravel-filament/demo.git filament-demo && cd filament-demo`
2. Install dependencies: `composer install --ignore-platform-req=ext-pcntl --ignore-platform-req=ext-posix`
3. Copy the environment file: `cp .env.example .env`
4. Generate a Laravel application key: `php artisan key:generate`
5. Migrate the database: `php artisan migrate`
6. Seed the database: `php artisan db:seed`
7. Create a symbolic link to storage: `php artisan storage:link`
8. Clear and set the cache:
   ```
   php artisan o:c
   php artisan view:cache
   php artisan route:cache
   php artisan icons:cache
   php artisan filament:cache-components
   php artisan event:cache
   php artisan config:cache
   php artisan optimize
   ```

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by danharrin** [comment]
Converting this to a discussion, as I use this repo every day and if I could reproduce the issue then I would have noticed it by now
