### ISSUE TITLE
Bug: Fileupload Component With Accepted Types As 'text/csv' Will Not Let Me Upload A CSV file On Public Disk

### ISSUE THREAD

**Issue by rlockett1121** [laravel-filament/filament#12760]
### Package

filament/filament

### Package Version

3.2.73

### Laravel Version

v10.48.10

### PHP Version

8.3.6

### Problem description

As a part of our project I am trying to upload a CSV file as an optional part of a wizard when updating a record. If I am using the S3 disk this works fine, but if I use the public disk I get the error "The [FIELDNAME] field must be a file of type: text/csv." when I then try and save my record.

### Expected behavior

My CSV file should be saved regardless what disk we are using

### Steps to reproduce

1. Make a record that uses a wizard as a part of it's create/edit form.

2. Put in a component for a file upload as a part of the wizard, using the public disk, with the following code: 
`FileUpload::make('your_field')->downloadable()->acceptedFileTypes(['text/csv'])`

3. Then take a CSV file, upload it into the field and save. It should upload initially, but then refuse to save the record

### Reproduction repository

https://github.com/rlockett1121/filament-csv-bug-project

**Comment by danharrin** [comment]
That file type only applies to some CSV files. Try this:

```
['text/csv', 'text/x-csv', 'application/csv', 'application/x-csv', 'text/comma-separated-values', 'text/x-comma-separated-values', 'text/plain', 'application/vnd.ms-excel']
```

**Comment by rlockett1121** [comment]
Thanks, that looked like it worked
