### ISSUE TITLE
Impossible to load JS attach on custom field on modal (relation manager) but work on resource page

### ISSUE THREAD

**Issue by jechazelle** [laravel-filament/filament#12769]
### Package

filament/filament

### Package Version

v3.2.72

### Laravel Version

v10.48.10

### Livewire Version

v3.4.12

### PHP Version

PHP 8.2

### Problem description

Currently I have a custom field, extend rich editor to add a mention system:

```
<?php

namespace App\Forms\Components;

use Filament\Forms\Components\RichEditor;

class MentionsRichEditor extends RichEditor
{
    protected string $view = 'forms.components.mentions-rich-editor';

    protected array $mentionsItems = [];

    public function mentionsItems(): static
    {
        $this->mentionsItems = [
            [
                'key' => 'test',
                'link' => 'profil'
            ],
            [
                'key' => 'test2',
                'link' => 'profil2'
            ]
        ];

        return $this;
    }

    public function getMentionsItems(): array
    {
        return $this->mentionsItems;
    }
}
```

and the view:

```
@include('filament-forms::components.rich-editor')

@assets
    <script src="https://cdnjs.cloudflare.com/ajax/libs/tributejs/3.3.2/tribute.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/tributejs/3.3.2/tribute.min.css" />
@endassets

<script>
    // Wait for the page to load before executing our code
    window.addEventListener('load', () => {
        // Get the component id, using the $getId() function of our RichEditor
        const id = '{{ $getId() }}';
        console.log(id);
        // Create the Tribute instance
        const tribute = new Tribute({
            // The values are the users that can be mentioned, so we will get this list from the mentionsItems variable that we created before in our custom component
            values: @json($getMentionsItems(), JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES),

            // Here we will customize the way that the mention must be shown, so when the user will mention another a link will be injected into the RichEditor with a link to the mentioned user's profile
            selectTemplate: function(item) {
                if (typeof item === "undefined") return null;
                if (this.range.isContentEditable(this.current.element)) {
                    return '<a href="' + item.original.link + '">@' + item.original.key + '</a>';
                }
                return "@" + item.original.key;
            },
        });

        // Attach the tribute instance to the RichEditor using the id retrieved above
        tribute.attach(document.getElementById(id));

        // Get the editor instance to override "keypress" and "keydown" events by an empty function
        const editor = document.getElementById(id).editor;
        if (editor != null) {
            editor.composition.delegate.inputController.events.keypress = function() {};
            editor.composition.delegate.inputController.events.keydown = function() {};
        }
    });
</script>
```

On the page (edit post) the custom field works, I see the different ID and I can use the mention:
<img width="1414" alt="Capture d’écran 2024-05-13 à 16 10 46" src="https://github.com/filamentphp/filament/assets/6713790/d3d779e3-953c-4623-93c3-7e8625d5f971">

But when I use the custom field on the modal (from relation manager, posts attach on a user), the custom field isn't loaded:
<img width="1416" alt="Capture d’écran 2024-05-13 à 16 12 17" src="https://github.com/filamentphp/filament/assets/6713790/560c0820-725d-4055-b0e8-d526346c9937">

<img width="1419" alt="Capture d’écran 2024-05-13 à 16 12 34" src="https://github.com/filamentphp/filament/assets/6713790/aa81f479-e4ec-4cf9-998d-3eacd4b8fe64">

Impossible to load the JS and.. execute the mention.

### Expected behavior

Use custom field on page and modal with same behavior

### Steps to reproduce

1. Create a custom field with JS
2. Use the custom field on edit page (on resource) => ok
3. Use the custom field on modal (relation maanger) => nok

### Reproduction repository

https://github.com/jechazelle/filament-custom-field

**Comment by jechazelle** [comment]
Someone here seems to have this problem too https://laracasts.com/discuss/channels/filament/filament-custom-rich-editor-javascript-not-loading-in-modal-relation-manager?page=1&replyId=935999

I found the problem again, but not a solution.

a little help would be appreciated 🙂

**Comment by BatthewZ** [comment]
Would it help to use AlpineJS for initialisation? I had some load issues,possibly due to server-side rendering with JS in a livewire component/blade template.  I ended up fixing it with something like:

```
<div x-data="my_component">
  <!-- All of your component stuff in here -->
</div>

@script 
Alpine.data("my_component", () => {
    return {
    
        init() {
          //  All of your logic in here, sans the window.addEventListener wrapper
        }
    }
}
@endscript 
```

My understanding is that Alpine.js calls the 'init()' function after the related div with the x-data is rendered on the browser, so I *think* it might make everything happen in the right order.  Please let me know if I'm wrong...

**Comment by danharrin** [comment]
I don't think `@assets` is a thing that we have added support for? Have you tried the Livewire `@script` directive as above?

Also, I would really appreciate it if you did not open more issues for questions about building custom fields, these aren't Filament bugs and belong in Discussions or Discord. If you do find a Filament bug then of course an issue is fine

**Comment by jechazelle** [comment]
@BatthewZ thx for this way, the JS is execute but I have always the same problem : I get only one ID on two fields from modal. I would like to execute the JS on each custom field. But in my console.log, I have only the same last ID...

@danharrin I understand, I thought it was a bug because on a resource it's perfect, on modal I can get ID on each custom field. I tried `@assets` because I search a way to execute the JS on each field from modal... :-)

Modal:
```
MentionsRichEditor::make('one_sentence')
    ->id('one_sentence')
    ->mentionsItems($form)
    ->fileAttachmentsDisk('media')
    ->label('One sentence'),

MentionsRichEditor::make('description')
    ->id('description')
    ->mentionsItems($form)
    ->fileAttachmentsDisk('media')
    ->label('Description'),
```

View:
```

<div x-data="my_component">
    @include('filament-forms::components.rich-editor')
</div>
    
@assets
<script src="{{ url('js/libs/Tribute/Tribute.min.js') }}"></script>

<link href="{{ url('css/libs/Tribute/Tribute.min.css') }}" rel="stylesheet">
@endassets

@script
<script>
    Alpine.data("my_component", () => {
        return {

            init() {
                //  All of your logic in here, sans the window.addEventListener wrapper
                const id = '{{ $getId() }}';

                console.log(id);
            }
        }
    });
</script>
@endscript
```

Console.log:
<img width="1022" alt="Capture d’écran 2024-05-14 à 15 08 20" src="https://github.com/filamentphp/filament/assets/6713790/a3ac7452-a6e5-477a-aff9-2a85b2a80075">

**Comment by ahmed-fawzy99** [comment]
I have this problem, too, with [Mux Uplader](https://www.mux.com/docs/guides/mux-uploader). It's unfortunate that there seems to be no solution for this.

**Comment by AbuKhalil95** [comment]
The issue I believe is related to how relation manager invokes js to load on click, so that no js is loaded before thus you miss the window event 'load' or in my case I was waiting for DOMContentLoaded, as a workaround I invoked a custom event once the js script is loaded instead, or in your case you could go without the event listener and just check for existing dom Id's you are looking for.

I missed this when reading about relation managers https://filamentphp.com/docs/3.x/panels/resources/relation-managers#disabling-lazy-loading, where you could even disable the lazy loading but I had not tested the option as the component is heavy enough for me to keep the lazy loading.
