### ISSUE TITLE
RichEditor content no longer displayed when relationship manager modal window reopen

### ISSUE THREAD

**Issue by jechazelle** [laravel-filament/filament#12779]
### Package

filament/filament

### Package Version

v3.2.77

### Laravel Version

v11.7.0

### Livewire Version

v3.4.12

### PHP Version

PHP 8.2

### Problem description

Hi,

This problem isn't here on the v3.2.76.

When I open a modal from relation manager, close the modal and open again, the content is missing:

Click on "Edit":
<img width="1026" alt="Capture d’écran 2024-05-14 à 13 59 05" src="https://github.com/filamentphp/filament/assets/6713790/7751b8c1-9d70-4985-9fc4-49f9b5c174bd">

First open, content is here:
<img width="1039" alt="Capture d’écran 2024-05-14 à 14 06 05" src="https://github.com/filamentphp/filament/assets/6713790/79116b0b-9ade-479c-bc30-827080a81a0c">

Close modal and open again, the content isn't here:
<img width="1041" alt="Capture d’écran 2024-05-14 à 14 05 26" src="https://github.com/filamentphp/filament/assets/6713790/f78acca8-2991-4724-bea0-57be63357dde">

### Expected behavior

Content always present on close and reopen modal on relation manager.

### Steps to reproduce

1. Open modal on relation manager
2. Close the modal
3. Reopen the modal

### Reproduction repository

https://github.com/jechazelle/filament-custom-field

**Comment by danharrin** [comment]
Pushed b108e14b4b512ec0bede124bb22a75a3c14907ca for the next release
