### ISSUE TITLE
close-modal event fires multiple times

### ISSUE THREAD

**Issue by OlyaK95** [laravel-filament/filament#12791]
### Package

filament/filament

### Package Version

3.2.78

### Laravel Version

10.48.10

### Livewire Version

3.4.12

### PHP Version

8.3.6

### Problem description

On the edit page of resource with relation manager when I click on edit button of some relation record opens modal window.  When I close this modal I have three requests.
![2024-05-15_01-07-32](https://github.com/filamentphp/filament/assets/129214474/85a0e4f3-8dab-465b-bbbe-75b7f71f6f8a)
![2024-05-15_01-07-51](https://github.com/filamentphp/filament/assets/129214474/a30ee0b7-9a90-4754-a438-508d503272d3)
![2024-05-15_01-08-04](https://github.com/filamentphp/filament/assets/129214474/96c2e934-80ef-4688-be3f-d201ded2874a)
![2024-05-15_01-08-16](https://github.com/filamentphp/filament/assets/129214474/e6bb32c8-0c44-42a9-aefe-3e0f770d3d39)

Similar questions [here](https://github.com/filamentphp/filament/discussions/12231) and [here](https://discord.com/channels/883083792112300104/1159725038367412294/1159725038367412294)

### Expected behavior

When I close modal I need only one request.

### Steps to reproduce

1. Edit any resource with relation manager
2. Click Edit on any relation record to open modal window
3. Close modal window
I can't reproduce this on fresh project like my github example below, because close-modal event don't fire no one time...

### Reproduction repository

https://github.com/OlyaK95/close-modal-issue

**Comment by danharrin** [comment]
Duplicate #10581
