### ISSUE TITLE
Tab with 2 or more custom components thows livewire error on click of actions

### ISSUE THREAD

**Issue by aotearoait** [laravel-filament/filament#12816]
### Package

filament/filament

### Package Version

3.2.72

### Laravel Version

11.6.0

### Livewire Version

3.4.12

### PHP Version

8.3.6

### Problem description

When creating multiple tabs on a form and adding more than 1 custom component tab ( eg a custom tab that shows a table ),
if you save form or perform any action that requires re-rendering, the tab content is now gone and livewire throws an error `Uncaught Snapshot missing on Livewire component with id: 6TUO5eLzk5BAWJjoChfx` or  `Uncaught Component not found: 6TUO5eLzk5BAWJjoChfx`
Have tried with adding keys to the custom component but still does not rectify the issue, the ids it is not finding seem to be in a parent div.

![image](https://github.com/filamentphp/filament/assets/33107115/38fd9938-689f-4083-81be-7679ceb22487)

### Expected behavior

System to work with save buttons and all components remaining rendered

### Steps to reproduce

Create a form with tabs, use multiple custom components 
(I use 3 normal form tabs and 2 custom component tabs)
Save the form or perform an action that requires re-rendering.

### Reproduction repository

https://github.com/d3vnz/filament-issue

**Comment by danharrin** [comment]
Please give each component a key like

```php
Tab::make('Tab3')
    ->schema([

       Livewire::make(CustomTabComponent1::class)->key('custom-one')
    ]),
Tab::make('Tab4')
    ->schema([

        Livewire::make(CustomTabComponent2::class)->key('custom-two')
    ]),
Tab::make('Tab5')
    ->schema([

        Livewire::make(CustomTabComponent3::class)->key('custom-three')
    ]),
```

Which is the equivalent of doing `@livewire(CustomTabComponent3::class, [], key('custom-three'))` etc

**Comment by aotearoait** [comment]
Have added the keys and still have same issue. Replicated on the repository attached to this issue as well.

**Comment by aotearoait** [comment]
So it shows the correct key but after rerender or save button, the entire component is empty
![image](https://github.com/filamentphp/filament/assets/33107115/4bcb250b-6747-4964-bba1-4489288fefcc)
Then
![image](https://github.com/filamentphp/filament/assets/33107115/1bd8ed7c-f8db-4694-8e3c-f19cfe114e08)

**Comment by danharrin** [comment]
I don't think you need the wire:key attributes within the view

**Comment by aotearoait** [comment]
Great that has fixed a big part of it.  Not sure if I should open up another bug for this one but if you look at repository now, notice I added a table to one of the custom components. This stops the save button on main form component from working. (Thought it was related issue to the key but maybe not)

**Comment by danharrin** [comment]
Unfortunately we don't fully support tables embedded within forms at this time. There is a workaround though - use the `->lazy()` method on the Livewire component with the table

```
Livewire::make(CustomTabComponent2::class)->key('custom-2')->lazy(),
```

**Comment by madsem** [comment]
I have the same issue, after adding `->key()` the error disappeared, but when adding more than 5 livewire components into my InfoList, the page loads and is blank:

```php
<?php

namespace App\Http\Livewire\Dashboards;

use App\Enums\PermissionsEnum;
use App\Http\Livewire\Dashboards\Company\ByDayDashboard;
use App\Http\Livewire\Dashboards\Company\ByOfferDashboard;
use App\Http\Livewire\Dashboards\Company\ByTrafficSourcesDashboard;
use App\Http\Livewire\Dashboards\Company\ByVerticalDashboard;
use App\Http\Livewire\Dashboards\Company\ByPartnerDashboard;
use App\Http\Livewire\ListComponent;
use Filament\Infolists\Components\Livewire;
use Filament\Infolists\Components\Tabs;
use Filament\Infolists\Infolist;
use Filament\Support\Enums\IconPosition;
use Illuminate\Contracts\View\View;
use Illuminate\Support\Facades\Auth;

class CompanyDashboard extends ListComponent
{
    public function mount()
    {
        Auth::user()->can(PermissionsEnum::SeeCompanyDashboard->value);
    }

    public function render(): View
    {
        return view('livewire.dashboards.company.company-dashboard');
    }

    public function infolist(Infolist $infolist): Infolist
    {
        return $infolist
            ->schema([
                Tabs::make('Tabs')
                    ->persistTab()
                    ->persistTabInQueryString()
                    ->id('company-dashboard')
                    ->tabs([
                        Tabs\Tab::make('By Day Dashboard')
                            ->icon('heroicon-m-calendar-days')
                            ->iconPosition(IconPosition::After)
                            ->schema([
                                Livewire::make(ByDayDashboard::class)
                                    ->key('leif-days'),
                            ]),
                        Tabs\Tab::make('By Traffic Source Dashboard')
                            ->icon('heroicon-m-circle-stack')
                            ->iconPosition(IconPosition::After)
                            ->schema([
                                Livewire::make(ByTrafficSourcesDashboard::class)
                                    ->key('leif-sources')
                                    ->lazy(),
                            ]),
                        Tabs\Tab::make('By Partner Dashboard')
                            ->icon('heroicon-m-user-group')
                            ->iconPosition(IconPosition::After)
                            ->schema([
                                Livewire::make(ByPartnerDashboard::class)
                                    ->key('leif-partners')
                                    ->lazy(),
                            ]),
                        Tabs\Tab::make('By Vertical Dashboard')
                            ->icon('heroicon-m-tag')
                            ->iconPosition(IconPosition::After)
                            ->schema([
                                Livewire::make(ByVerticalDashboard::class)
                                    ->key('leif-verticals')
                                    ->lazy(),
                            ]),
                        Tabs\Tab::make('By Offer Dashboard')
                            ->icon('heroicon-m-banknotes')
                            ->iconPosition(IconPosition::After)
                            ->schema([
                                Livewire::make(ByOfferDashboard::class)
                                    ->key('leif-offers')
                                    ->lazy(),
                            ]),
                    ]),
            ]);
    }

}
```
<img width="1702" alt="Screenshot 2024-06-10 at 14 03 47" src="https://github.com/filamentphp/filament/assets/3166991/082c53f7-6c8c-4038-af7b-3036f7006049">


If I remove one of the Tabs with a component inside, or comment out the component inside the tab, everything shows as expected.

**Comment by madsem** [comment]
Ok, this seems to be Safari related:
`SecurityError: Attempt to use history.replaceState() more than 100 times per 10 seconds`

seems to prevent promises from being resolved, when I use Chrome I can see all my dashboard components.

https://github.com/livewire/livewire/discussions/5923

Confirmed this, I've applied the hotfix mentioned in the above issue, and Safari works again:
```js
const original = window.history.replaceState;
let timer = Date.now();

let timeout = null;
let lastArgs = null;

window.history.replaceState = function (...args) {
	const time = Date.now();

	if (time - timer < 300) {
		lastArgs = args;
		
		if (timeout) {
			clearTimeout(timeout);
		}
		
		timeout = setTimeout(() => {
			original.apply(this, lastArgs);
			
			timeout = null;
			lastArgs = null;
		}, 100);
		
		return;
	}

	timer = time;

	original.apply(this, args);
};
```
