### ISSUE TITLE
Template Filament project doesn't work

### ISSUE THREAD

**Issue by wq9578** [laravel-filament/filament#12855]
### Package

filament/filament

### Package Version

v3.2.80

### Laravel Version

v11.7.0

### Livewire Version

v3.4.12

### PHP Version

8.2.11

### Problem description

The template Filament project available at `https://filament-issue.unitedbycode.com` doesn't work.

The command `php artisan serve` fails.
Also trying `composer dump-autoload` fails with the same error message.

(Originally, I wanted to create a reproduction repository since I faced bug https://github.com/filamentphp/filament/issues/6576 (method afterStateUpdated() called twice) with the current version of Filament.)

### Expected behavior

A working template Filament project.

### Steps to reproduce

Download from `https://filament-issue.unitedbycode.com` and unpack.
Change into project directory and run `php artisan serve`.

If you clone the reproduction repository, run `composer install` before running `php artisan serve `.

### Reproduction repository

https://github.com/wq9578/template-filament-project

### Relevant log output

```shell
% php artisan serve     

In sanctum.php line 21:
                                             
  Class "Laravel\Sanctum\Sanctum" not found  
                                             

% composer dump-autoload
Generating optimized autoload files
Warning: Ambiguous class resolution, "Filament\Support\Commands\Aliases\MakeIssueCommand" was found in both "/Users/githubuser/Downloads/filament-issue/vendor/filament/support/src/Commands/Aliases/MakeIssueCommand.php" and "/Users/githubuser/Downloads/filament-issue/vendor/filament/filament/src/Support/Commands/Aliases/MakeIssueCommand.php", the first will be used.
> Illuminate\Foundation\ComposerScripts::postAutoloadDump
> @php artisan package:discover --ansi

In sanctum.php line 21:
                                             
  Class "Laravel\Sanctum\Sanctum" not found  
                                             

Script @php artisan package:discover --ansi handling the post-autoload-dump event returned with error code 1
```

**Comment by dev-idkwhoami** [comment]
Your issue does not lie with filament.

Whoever made that zip file and included the vendor directory, somehow managed to remove the laravel/sanctum dependency from the composer.json.

To fix your issue in the root directory run
```shell
composer require laravel/sanctum
```

Then `php artisan serve` will function as expected.

**Comment by wq9578** [comment]
Thanks!
Running `composer require laravel/sanctum` solves the issue.
(There still appears the warning "Ambiguous class resolution" mentioned above.)

However, since the link to `https://filament-issue.unitedbycode.com` is announced here when opening an issue, I would consider the ZIP file somehow part of the Filament project.
So the ZIP file still should be fixed (by removing both the issue and the warning).
@ijpatricio seems to be the person in charge (hosting the website).

**Comment by danharrin** [comment]
I've notified Patricio myself so closing this issue
