### ISSUE TITLE
ImageEntry not show stacked images

### ISSUE THREAD

**Issue by IgorDePaula** [laravel-filament/filament#12885]
### Package

filament/filament

### Package Version

3

### Laravel Version

11

### Livewire Version

3

### PHP Version

8.3

### Problem description

I wrotten a code for show a relationship of record with images, but dont show images, For any reason, the img tag dont render the src attribute.

![image](https://github.com/filamentphp/filament/assets/2833993/1c8db4e7-3920-4b31-ad58-f639a46d3d0f)
with relation but no propety/path
![image](https://github.com/filamentphp/filament/assets/2833993/ff02c301-9a20-4369-a985-0b23b77e8965)
============================
![image](https://github.com/filamentphp/filament/assets/2833993/5f4a1b40-e20f-49f1-a589-2b633a821ce9)
with property/path
![image](https://github.com/filamentphp/filament/assets/2833993/fb90f117-1bf8-4032-86c9-8b7374121565)

### Expected behavior

![image](https://github.com/filamentphp/filament/assets/2833993/f0cd6e78-8fff-446a-8555-b0779637a100)

### Steps to reproduce

![image](https://github.com/filamentphp/filament/assets/2833993/814665fa-4f6b-468f-a49f-d0afc80381c4)

### Reproduction repository

https://github.com/HTechBrasil/primatool-backend

**Comment by Denysetya1** [comment]
I had the same problem

**Comment by danharrin** [comment]
No public reproduction repo

**Comment by kateengland-moore** [comment]
@danharrin does this mean that you won't be fixing this issue? It says closed as not planned, but then the bot has moved to Done on the Roadmap.

**Comment by danharrin** [comment]
A requirement for us to investigate issues is a reproduction repository. The user posted one that is not public, so we are not investigating.

If you create a public repository reproducing the issue in a minimal way, we will investigate.

**Comment by kateengland-moore** [comment]
@danharrin I'll try to put something together and paste the link here
