### ISSUE TITLE
SpatieMediaLibraryImageEntry infolist not displaying non-image media uploads

### ISSUE THREAD

**Issue by nea** [laravel-filament/filament#12951]
### Package

filament/spatie-laravel-media-library-plugin

### Package Version

v3.2.50

### Laravel Version

v11.0.6

### PHP Version

PHP 8.3

### Problem description

Hi there

I am using Spatie Media Library for file uploads of different kinds, images as well as e.g. PDFs.
Uploading both types and displaying on an edit view works fine, can be downloaded and opened.

For a view I created an Infolist with `SpatieMediaLibraryImageEntry` of the attachments. The image is shown correctly, the PDF just has a "broken" symbol as it is included as `<img...` tag, which it is not obviously. The url itself is correct behind that.
![image](https://github.com/filamentphp/filament/assets/392035/d29b024b-fdf0-4f5a-8fb1-35e17ec5fd7a)

Is there a way to also display other than image attachments?
I looked for options on the Entry, but didn't find an obvious one.

Thanks in advance

### Expected behavior

All media is shown or linked correctly

### Steps to reproduce

* Create a resource with media
* Upload an image and a PDF file
* Create a view with an infolist of these attachments

### Reproduction repository

Only private

**Comment by mokhosh** [comment]
@danharrin Can we please reopen this? As this is not something you really need special conditions to reproduce. You just have to upload a PDF file in normal conditions.

I wanted to create a new issue with two questions:
1. How to customise the thumbnail for PDF files.
2. How to make them downloadable.
But I thought maybe it's better to use this issue.

Also, if these are not currently possible, I would be willing to make a PR if you give me a general direction where to start.
Thanks.

**Comment by danharrin** [comment]
PDFs are not images so I would not expect this to work. If you have a background process generating thumbnails, you can use an image entry to display them on behalf of the PDF file. Thumbnail generation is not really a concern of Filament IMO.

You can use an action in your infolist to provide a download button, right?

**Comment by mokhosh** [comment]
@danharrin You're right thumbnail generation is done easily through Spatie medialibrary package itself. I was more thinking like being able to give them default fallback image, or being able to decide based on each item.

In the same way for download, we can use an action to download all files, but there is no way to make each item clickable and downloadable, right?

**Comment by danharrin** [comment]
Have you tried giving the entry a `->url()`? That would not be for individual images though

**Comment by mokhosh** [comment]
Yeah that would have a similar functionality to an action on the entry.

**Comment by danharrin** [comment]
I think I would accept a PR for `downloadable()` on the image entry
