### ISSUE TITLE
On a HasMany relationship manager, when using a function to filter a list of options on a relationship list, when using "Create and Create Another", the second create overrides the Pivot Relation

### ISSUE THREAD

**Issue by AlexJames-Dev** [laravel-filament/filament#1295]
### Package

filament/filament

### Package Version

2.9.7

### Laravel Version

8.75

### Livewire Version

2.9

### PHP Version

8.1

### Bug description

On a HasMany relationship manager, when using a function to filter a list of options on a relationship list, when using "Create and Create Another", the second create overrides the first Pivot Relation

https://user-images.githubusercontent.com/43570309/150422376-502f0c56-1690-4a02-9c58-6774aedfc2e5.mov

![unknown](https://user-images.githubusercontent.com/43570309/150422379-1014a715-1946-4251-a160-02f3a2236178.png)

**Comment by danharrin** [comment]
Fixed by #1320.
