### ISSUE TITLE
DatePicker Alpine error when using getFormStatePath

### ISSUE THREAD

**Issue by AlexJames-Dev** [laravel-filament/filament#1296]
### Package

filament/forms

### Package Version

2.9.7

### Laravel Version

8.75

### Livewire Version

2.9

### PHP Version

8.1

### Bug description

DatePicker Alpine error when using getFormStatePath to store all form data in one variable as per documentation.

https://user-images.githubusercontent.com/43570309/150423056-4d7bf47a-4e01-435e-81a9-c8b8ba4fe3f6.mp4

**Comment by danharrin** [comment]
You need to call `$this->form->fill()` or `$this->form->fill([your data])` in every single form, usually from the `mount()` method. It's in the Getting Started docs of the table builder.
