### ISSUE TITLE
Problem with multiple() in ToggleButtons

### ISSUE THREAD

**Issue by schmeits** [laravel-filament/filament#12962]
### Package

filament/filament

### Package Version

v3.2.83

### Laravel Version

11.8.0

### PHP Version

PHP 8.3.3

### Problem description

If I'm using the example from the docs

```PHP
Forms\Components\ToggleButtons::make('this_field_does_not_exist')
    ->multiple()
    ->options([
        'tailwind' => 'Tailwind CSS',
        'alpine' => 'Alpine.js',
        'laravel' => 'Laravel',
        'livewire' => 'Laravel Livewire',
    ])
```
On the edit page of the resource when I want to select one option... all the options are selected.

### Expected behavior

I expected only the clicked option would be selected, but they are all selected even if the field is not in the database

### Steps to reproduce

1. create a record in the database using Filament... everything is working
2. edit the resource 
3. try to select one of the options, you will notice that all the options are selected

### Reproduction repository

https://github.com/schmeits/multiple-bug

### Relevant log output

```shell
I already created a fix... in the setUp function in the ToggleButtons field you could add a check in the afterStateHydrated to check if the value is null, but it should be [] in case of a isMultiple field:

protected function setUp(): void
    {
        parent::setUp();

        $this->afterStateHydrated(static function (ToggleButtons $component, $state): void {
            if ($component->isMultiple && is_null($state))
            {
                $component->state([]);
            }
        });

        $this->default(function (ToggleButtons $component): mixed {
            return $component->isMultiple() ? [] : null;
        });
    }
```

**Comment by danharrin** [comment]
Can you make the PR please?

**Comment by schmeits** [comment]
Will do in the morning :)
