### ISSUE TITLE
FileUpload acceptedFileTypes audio check only mp3

### ISSUE THREAD

**Issue by POMXARK** [laravel-filament/filament#12961]
### Package

filament/forms

### Package Version

v3.2

### Laravel Version

v11.0.9

### Livewire Version

v3.5.0

### PHP Version

PHP 8.2

### Problem description

data types are not validated

### Expected behavior

was waiting for the file to upload

### Steps to reproduce

```php
use GuzzleHttp\Psr7\MimeType;

 public static function form(Form $form): Form
    {
        $types = app(MimeType::class);

        $acceptedAudioTypes = [
            $types->fromExtension('mp3'),
            $types->fromExtension('wav'),
            $types->fromExtension('flac'),
        ];

        return $form
            ->schema([
                Forms\Components\FileUpload::make('audio')
                    ->acceptedFileTypes($acceptedAudioTypes)
                    ->helperText(new HtmlString('MP3, WAV, FLAC'))
            ]);
    }
    
    ```

### Reproduction repository

https://github.com/POMXARK/filament_3_FileUpload_acceptedFileTypes

**Comment by POMXARK** [comment]
![2024-05-30_19-54](https://github.com/filamentphp/filament/assets/18720947/667dea4e-98c2-4331-b37f-5a389762edcc)
![2024-05-30_19-55](https://github.com/filamentphp/filament/assets/18720947/70673c3a-8492-4a65-8ba2-8298353f5281)

**Comment by zepfietje** [comment]
Have you tried passing the types as an array of strings?

**Comment by POMXARK** [comment]
> Have you tried passing the types as an array of strings?

yes

**Comment by zepfietje** [comment]
Okay we need more info on what’s happening and what you’re expecting to happen. Please also check the actual mime of the file using the CLI.

**Comment by zepfietje** [comment]
I'm going to close this issue since we haven't heard back from the author.
