### ISSUE TITLE
Custom page not showing in cluster navigation

### ISSUE THREAD

**Issue by mattyforth** [laravel-filament/filament#12976]
### Package

filament/filament

### Package Version

v3.2.63

### Laravel Version

v11.2.0

### Livewire Version

v3.4.10

### PHP Version

8.3.0

### Problem description

Hello!

I have a custom cluster called `LegalCase`, and within that cluster I have a `CaseResource` with the regular pages, list, view etc.

My `LegalCase` model has a status and can be pending, and I have created a custom page to just show the pending cases by modifying the query. 

```
<?php

namespace App\Filament\Clusters\LegalCase\Resources\CaseResource\Pages;

use App\Filament\Clusters\LegalCase;
use App\Filament\Clusters\LegalCase\Resources\CaseResource;
use Filament\Resources\Pages\ListRecords;
use Filament\Tables\Table;

class ListPendingCases extends ListRecords
{
    protected static string $resource = CaseResource::class;

    protected static ?string $cluster = LegalCase::class;

    protected static ?string $navigationLabel = 'Pending cases';

    public function table(Table $table): Table
    {
        return CaseResource::table($table)->description('Hello');
    }
}
```

```
    // CaseResource.php
    public static function getPages(): array
    {
        return [
            //...
            'pending' => ListPendingCases::route('/pending'),
        ];
    }
```

The page itself works fine when I navigate manually to the route I've defined, however it won't show up in the LegalCase cluster navigation, which according to the docs, I'm certain it should?

### Expected behavior

The page should be visible in the clusters sub navigation menu.

### Steps to reproduce

1. Pull repo
2. `php artisan serve`
4. Migrate & seed
5. Navigation to /admin and login
6. Click "Legal case" navigation menu item
7. See that there is no option for "pending cases" under the "your cases" item.
8. Navigation to the `/admin/legal-case/cases/pending` page manually and see that the page is working (you should see a "pending" description on the table)
9. View the code inside `app/Filament/Clusters/LegalCase/Resources/CaseResource/Pages/ListPendingCases.php` to verify that `$cluster` is set to `LegalCase::class`

### Reproduction repository

https://github.com/mattyforth/filament-cluster-navigation-issue

**Comment by alexmanase** [comment]
Your class `ListPendingCases` should extend `Resource`, not `ListRecords`.

**Comment by alexmanase** [comment]
Here is the fix: https://github.com/mattyforth/filament-cluster-navigation-issue/pull/1/files

**Comment by danharrin** [comment]
It should actually extend Page, this isn't a resource @alexmanase 

Make a page with `make:filament-page` and then add a table using https://filamentphp.com/docs/3.x/tables/adding-a-table-to-a-livewire-component
