### ISSUE TITLE
Action lifecycle hooks form data

### ISSUE THREAD

**Issue by tareq-alqadi** [laravel-filament/filament#12973]
### Package

filament/filament

### Package Version

v3.2.83

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

PHP 8.2

### Problem description

When using the table create or edit action, I can't access the current modal form data; it gives me an empty array.
The problem occurs after [commit](https://github.com/filamentphp/filament/commit/b367120eef552a452a57febf330229111ec0e2b1)

### Expected behavior

Access current modal form data

### Steps to reproduce

Using before hook in table create or edit actions.

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by saschagysel** [comment]
I can confirm this and would like to nominate this as a high priority bug as its breaking all data handling with the ->before() hook which is for sure used by many.

**Comment by gehrisandro** [comment]
Here is a regression test for the broken behaviour: https://github.com/filamentphp/filament/pull/12987
