### ISSUE TITLE
No Interaction of dependent select field after being re-enabled

### ISSUE THREAD

**Issue by dev-idkwhoami** [laravel-filament/filament#12988]
### Package

filament/filament

### Package Version

3.2.83

### Laravel Version

11.9.1

### Livewire Version

3.5.0

### PHP Version

8.3.2

### Problem description

When trying to disable a field based on a condition, like whether a previous field is filled or not the disabled select field is not interactable after the element itself was "enabled". 

I also tried using the `->native(false)` option but in both cases the same issue occurs.

![brave_f65EIJBWvV](https://github.com/filamentphp/filament/assets/26493113/37426969-36c9-49ec-beac-1af860b8e71f)

### Expected behavior

The select field should be interactable and behave as like it would when it wasn't disabled.

Here an example of how it should work by providing a default state for the continent field:

![brave_zaFp4GU8cm](https://github.com/filamentphp/filament/assets/26493113/6a364a07-30d6-4442-8cd3-615aebc5f066)

### Steps to reproduce

1. Navigate to Customers
2. "Edit" any record from the table
3. Click the "New Address" button
4. Select any Continent
5. Issue occurred

### Reproduction repository

https://github.com/dev-idkwhoami/filament-demo/tree/bug/dependent-disabled-select-fields

**Comment by danharrin** [comment]
https://github.com/filamentphp/filament/issues/11289, https://github.com/filamentphp/filament/issues/10263, https://github.com/filamentphp/filament/issues/8951, https://github.com/filamentphp/filament/issues/8935, https://github.com/filamentphp/filament/issues/8097, https://github.com/filamentphp/filament/issues/3068
