### ISSUE TITLE
Weird scrolling behavior when Laravel Debugbar is expanded

### ISSUE THREAD

**Issue by josepdecid** [laravel-filament/filament#12983]
### Package

filament/filament

### Package Version

v3.2.83

### Laravel Version

v11.8.0

### Livewire Version

v3.5.0

### PHP Version

PHP 8.3.7

### Problem description

When expanding the [Laravel debugbar](https://github.com/barryvdh/laravel-debugbar) the scrolling does not behave as expected. The whole site should scroll together but instead, the navbar on top of the main content remains fixed (as expected) but the part on top of the sidebar scrolls up.

I've tried it with Chrome, Firefox, and Safari (also using incognito to disable all the extensions) and it happens the same with all of them. 

I've only found this problem using the debug bar for now, but this may happen with other out-of-filament elements. It does not occur when the screen is just smaller than the content

https://github.com/filamentphp/filament/assets/11754473/92dca9eb-fb64-4ded-960f-765da1363af9

![Smaller screen](https://github.com/filamentphp/filament/assets/11754473/875cd8fa-f76d-4f8f-9e5f-2d35bc5b648a)

### Expected behavior

Scrolling the page should leave the whole navigation bar fixed on top.

### Steps to reproduce

Navigate to any resource, expand the Laravel Debugbar and scroll down.

### Reproduction repository

https://github.com/josepdecid/events-manager-laravel

**Comment by danharrin** [comment]
Ref: https://github.com/filamentphp/filament/pull/12984#issuecomment-2138754648

I think I agree with this comment and should see if someone can get a fix within Debugbar.
