### ISSUE TITLE
Select: array_diff(): Argument #2 must be of type array, string given

### ISSUE THREAD

**Issue by stvnthomas** [laravel-filament/filament#13001]
### Package

filament/filament

### Package Version

v3.2.83

### Laravel Version

v11.9.1

### Livewire Version

v3.5.0

### PHP Version

8.3.7

### Problem description

I have a select field with relationship-sourced options.

```
Forms\Components\Select::make('roles')
    ->label('Role')
    ->preload()
    ->relationship(titleAttribute: 'name')
    ->required()
    ->searchable(),
```

Saving the field results in the following error:

```
array_diff(): Argument #2 must be of type array, string given
```

The user data is saved (created, updated) but the role relationship isn't. The error originates on [Select.php#L994-L1000](https://github.com/filamentphp/filament/blob/0699ac595508a94cf62fd12ece1279d67f463151/packages/forms/src/Components/Select.php#L994-L1000).

Downgrading to 3.2.78 fixes the issue. The issue isn't present on selects using `options()`.

### Expected behavior

The relationship to save without an error.

### Steps to reproduce

1. Clone the repo
2. Repo readme has steps to run and reproduce the issue

### Reproduction repository

https://github.com/stvnthomas/filament-select-relationship-issue

**Comment by danharrin** [comment]
Fixed by #13010
