### ISSUE TITLE
Form split sections do not grow as expected

### ISSUE THREAD

**Issue by atmediauk** [laravel-filament/filament#13047]
### Package

filament/forms

### Package Version

3.2

### Laravel Version

11.9

### PHP Version

8.3.6

### Problem description

The columns are incorrectly sized at larger breakpoints. Specifically once the width of the page exceeds 1024px both columns shrink. Please see screen recording - https://jumpshare.com/v/mvrJTiKCPuITzXH3GmLC

### Expected behavior

I expected the left hand section to continue growing as the width of the page increased. 

### Steps to reproduce

Followed documentation example here - https://filamentphp.com/docs/3.x/forms/layout/split#overview

### Reproduction repository

https://github.com/atmediauk/filament-split

**Comment by zepfietje** [comment]
Please provide more details on what you're expecting and what's happening instead. Without screenshots, we can't really help you with visual issues. 🙂

**Comment by danharrin** [comment]
Also, if you have any experience with Tailwind it would be helpful if you told us what class is wrong/missing, or even create a PR to add it in the right place

**Comment by atmediauk** [comment]
@zepfietje Apologies, I've added a screen recording outlining the issue.

@danharrin Sorry this is my first time quickly playing with Filament (and so far it rocks). But I am still getting to grips with it all yet.

**Comment by zepfietje** [comment]
Thanks for adding the screen recording, @atmediauk!

I'm 99.9% sure the issue in this case is the default number of columns on the form.
From a certain breakpoint, the form has 2 columns, which causes the "split" element to only span half of the available columns.

Adding `->columnSpan('full')` to your `Split` component should fix this for you.
Just let me know if you think I'm wrong, and I'll reopen this issue. 😊

**Comment by atmediauk** [comment]
@zepfietje You are absolutely right, using ``` ->columnSpan('full') ``` worked great. Thank you :)

**Comment by blackforestcode** [comment]
> @zepfietje You are absolutely right, using `->columnSpan('full')` worked great. Thank you :)

You should add this to the documentation.

**Comment by zepfietje** [comment]
> You should add this to the documentation.

Feel free to create a PR for that, @blackforestcode.
Then we'll have a look and merge it :)
