### ISSUE TITLE
Duplicate query execution in Widgets

### ISSUE THREAD

**Issue by ManojKiranAppathurai** [laravel-filament/filament#1306]
### Package

filament/filament

### Package Version

2.9.8

### Laravel Version

8.80.0

### Livewire Version

2.10.0

### PHP Version

8.1.1

### Bug description

When I try to show the count of user in dashboard. Its executing the same query 3 times.

### Steps to reproduce

After the fresh installation make a widget by running the below command.

`php artisan make:filament-widget DashboardStatsOverview`

and paste the following code.

```
<?php

namespace App\Filament\Widgets;

use App\Models\User;
use Filament\Widgets\StatsOverviewWidget as BaseWidget;
use Filament\Widgets\StatsOverviewWidget\Card;

class DashboardStatsOverview extends BaseWidget
{
    protected function getCards(): array
    {
        User::query()->count();

        return [
            Card::make('Unique views', '192.1k'),
            Card::make('Bounce rate', '21%'),
            Card::make('Average time on page', '3:12'),

            Card::make('Unique views', '192.1k'),
            Card::make('Bounce rate', '21%'),
            Card::make('Average time on page', '3:12'),
        ];
    }
}

```

Install the [barryvdh/laravel-debugbar](https://github.com/barryvdh/laravel-debugbar)

and you will see the 

![image](https://user-images.githubusercontent.com/30294553/150567975-cc28e990-9f7c-42f7-b610-faeed6f5a2e2.png)

I have also Created a Demo repo for this issue.

https://github.com/ManojKiranAppathurai/filamentwidgettest

**Comment by ryangjchandler** [comment]
@ManojKiranAppathurai I would recommend doing this query somewhere else, like `mount()` or `hydrate()` since `getCards()` is clearly called multiple times.

**Comment by danharrin** [comment]
I also suggest using Ryan's method.

**Comment by ManojKiranAppathurai** [comment]
@ryangjchandler I have tried `mount` and `hydrate` method for stats card. Its working fine but for the Chart widgets with `pollingInterval` is causing the error. 

When i use `hydrate` method to set the props on initial load its not settting the value. But after the first polling request is sent the charts is updated and there is no issues.


When i use `mount` method to set the props on initial load the values for chart is loaded. But on the polling requests I am getting

`Typed property Filament\Widgets\ChartWidget::$dataChecksum must not be accessed before initialization`

![image](https://user-images.githubusercontent.com/30294553/150625554-343fe130-920f-4c1f-a291-acd9cbdb3713.png)

**Comment by ManojKiranAppathurai** [comment]
I have updated the repo.

**Comment by danharrin** [comment]
If you're overriding methods from the base class, make sure to call the `parent::` version first.
