### ISSUE TITLE
### Package

### ISSUE THREAD

**Issue by myregistration** [laravel-filament/filament#13097]
### Package

Actions

### Package Version

v3

### How can we help you?

I've tried using mutateFormDataBeforeFill, beforeFill, afterFill in the relative `CreateRecord` and I've also tried `before`, `beforeFormFilled`, `afterFormFilled` in table's `CreateAction`.  I even tried hard-coding the `$data` array value for the select menu and created a test select menu, but nothing is working.  Are we supposed to set the `->default()` value in the select menu?  I would think mutating the `$data` array would set the initial select menu option.  If I `dd($data)` in the `beforeFormFilled` or `afterFormFilled` methods I can see the value is being set.  Thanks

Here's a test select menu I created in a `Filament Resource` class to test the relative lifecycle methods:

```
public static function form(Form $form): Form
{
	return $form
            ->schema([

                Select::make('category')
                    ->options([
                        'option1' => 'Option 1',
                        'option2' => 'Option 2',
                        'option3' => 'Option 3',
                    ])->default('option1')
                    ->required(),
```

```
public static function table(Table $table): Table
{
	return $table
	    ->headerActions([
		    Tables\Actions\CreateAction::make()
    		    ->beforeFormFilled(function (array $data, Component $livewire): array {

        		    $data['category'] = 'option2';

        		    return $data;
   		     }),
```

_Originally posted by @myregistration in https://github.com/filamentphp/filament/discussions/13092_

**Comment by danharrin** [comment]
Issues are for bug reports, please do not use "convert to issue" for this as it belongs in a discussion
