### ISSUE TITLE
Extra semicolons being produced in Column/Image image style attribute

### ISSUE THREAD

**Issue by jellycow** [laravel-filament/filament#131]
**Describe the bug**
When using the new Column\Image there are extra semicolons being produced in the style attribute of the images

**To reproduce**
Steps to reproduce the behaviour:
1. Add an Image column to a table
2. Open browser inspector 
3. Find image tag

**Expected behaviour**
No extraneous markup should be present in the style attribute

**Screenshots**
![Src Issue](https://user-images.githubusercontent.com/209072/110398365-a69b8c80-806b-11eb-8561-dfb0a478411e.jpg)

**Context**
- Package version: [1.4.5]
- Livewire version: [e.g. 2.0.0]
- Laravel version: [8.30]
- Browser: [Chrome v 88.0.4324.19]
- Server OS: [OSX 10.11.6]
- PHP version: [7.4]
- Database: [MySQL 8.0]

**Additional details**
The issue is caused by extra semicolons in the Column\Image view file

![Extra Semi Colons](https://user-images.githubusercontent.com/209072/110398431-c9c63c00-806b-11eb-82a8-01074a71a185.jpg)

**Comment by danharrin** [comment]
Fixed by #134.
