### ISSUE TITLE
Form Builder - Checkbox List Weird Behavior When Have Trailing Space on The Name

### ISSUE THREAD

**Issue by Ticlext-Altihaf** [laravel-filament/filament#13116]
### Package

filament/forms

### Package Version

v3.2.86

### Laravel Version

v11.10.0

### Livewire Version

v3.5.0

### PHP Version

PHP 8.3.7

### Problem description

When `CheckboxList` name have trailing space, the checks can't be toggled individually, current workaround is to **remove any trailing space** in the name

https://github.com/filamentphp/filament/assets/77704356/3fce0316-e09d-40c2-bd67-13e9eb7a42ff

Note: skip to 0:29 for the problem

### Expected behavior

Just like any normal `CheckboxList` 

### Steps to reproduce

-  This is OK
```php
CheckboxList::make('test')
```

- This is OK
```php
CheckboxList::make(' test')
```

- This will cause weird behavior
```php
CheckboxList::make('test ')
```

- Step in the video
```
git clone https://github.com/Ticlext-Altihaf/fillament-issue-checkbox-list
php artisan migrate
php artisan serve
```

### Reproduction repository

https://github.com/Ticlext-Altihaf/fillament-issue-checkbox-list

**Comment by danharrin** [comment]
We don't support names with trailing spaces, names should be usable within array keys and PHP properties etc and can not contain spaces.
