### ISSUE TITLE
DateTimePicker option '->seconds(false)' stops working in form after '->minDate(now())' is added

### ISSUE THREAD

**Issue by tjallo** [laravel-filament/filament#13123]
### Package

filament/filament

### Package Version

v3.2.86

### Laravel Version

v11.10.0

### Livewire Version

v3.5.0

### PHP Version

PHP 8.3.7

### Problem description

When adding the `->minDate(now())` option to a DateTimePicker component in your form, the `->seconds(false)` option is ignored, and you are able to select seconds again.

### Expected behavior

Seconds should dissapear when ->seconds(false) is set for the DateTimePicker Component, like this: 
![image](https://github.com/filamentphp/filament/assets/31376864/10a61f2c-b6a7-41f5-a8c0-301623432508)

### Steps to reproduce

Create a form for your Resource, I have done this like this:

```
 public static function form(Form $form): Form
    {
        return $form
            ->schema([
                TextInput::make('event_name')->required(),
                Select::make('car_class_id')->relationship('carClass', 'class_name'),
                Select::make('event_location_id')->relationship('eventLocation', 'name'),
                DateTimePicker::make('event_start_time')->prefix('Starts')->seconds(false)->timezone('Europe/Amsterdam'),
                DateTimePicker::make('event_end_time')->prefix('Ends')->seconds(false)->timezone('Europe/Amsterdam')
            ]);
    }
```

Now you can't set seconds in your form, this is expected behaviour.

Now add `->minDate` verifiers as follows:

   ```
 public static function form(Form $form): Form
    {
        return $form
            ->schema([
                TextInput::make('event_name')->required(),
                Select::make('car_class_id')->relationship('carClass', 'class_name'),
                Select::make('event_location_id')->relationship('eventLocation', 'name'),
                DateTimePicker::make('event_start_time')->prefix('Starts')->seconds(false)->timezone('Europe/Amsterdam')->minDate(now()),
                DateTimePicker::make('event_end_time')->prefix('Ends')->seconds(false)->timezone('Europe/Amsterdam')->minDate(now()->addDay())
            ]);
    }
```

Now seconds appear again, which isn't expected behaviour, the minDate behaviour is however working as expected:
![image](https://github.com/filamentphp/filament/assets/31376864/65263eb6-706d-460c-b59f-702c2b72e81b)

### Reproduction repository

https://github.com/tjallo/filament-issue

**Comment by zepfietje** [comment]
Please add an actual reproduction repository next time, @tjallo.

This issue is caused by the `minDate` value you're passing.
Since `now()` contains seconds, the `min` attribute on the input contains a value with seconds. This causes Chrome to show the seconds placeholder even though the step is configured to be minutes. Passing `now()->seconds(0)` as `minDate` gives your desired result.

I'm not sure if this is really a Filament issue.
What do you think, @danharrin?
