### ISSUE TITLE
cant scroll while reorder

### ISSUE THREAD

**Issue by arsaey** [laravel-filament/filament#13120]
### Package

filament/filament

### Package Version

v3

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

8.1

### Problem description

there is no way to scroll items when drag them. in large list when drag also required scroll

### Expected behavior

dragged items come with scroll

### Steps to reproduce

create a large list which need scroll and make items reorderable

### Reproduction repository

https://github.com/filamentphp/filament/

**Comment by s-arbabi** [comment]
cant reproduce
