### ISSUE TITLE
Uncontained section

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#13147]

**Comment by andrewdwallo** [comment]
Is this still planned for v3 or only v4? Very much needing this!

**Comment by zepfietje** [comment]
Plan to work on this for v4 (hence the milestone).

**Comment by andrewdwallo** [comment]
Oh okay thought it had both v3 and v4 milestone tags when I asked. Sounds good!

**Comment by danharrin** [comment]
I have implemented this in #14968 as I needed it when refactoring a component for v4, but open to changes before v4 release
