### ISSUE TITLE
Filament 3.2 installation returns error Class Redis not found when  .env configured as CACHE_STORE=redis

### ISSUE THREAD

**Issue by abetterlogic** [laravel-filament/filament#13160]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

11.10

### PHP Version

PHP 8.2

### Problem description

Filament installation gives error while installing and setting .env  CACHE_STORE=redis

<img width="1112" alt="Screenshot 2024-06-09 at 11 43 51 AM" src="https://github.com/filamentphp/filament/assets/95415398/95a2d826-16bf-4675-a843-9e080600b69f">

### Expected behavior

Installation process should be seamless.

### Steps to reproduce

keep .env  CACHE_STORE=redis
and try installing through command 
composer require filament/filament:"^3.2" -W

### Reproduction repository

https://github.com/abetterlogic/abl-plm-sbm-slsabl

**Comment by danharrin** [comment]
This is not a Filament issue, this is an issue running commands while your app is not configured correctly, you can see in the stack trace that its coming from the TelescopeServiceProvider. You need to set up Redis properly before you can use Redis.
