### ISSUE TITLE
Filament breaks in SPA mode on page change in latest version

### ISSUE THREAD

**Issue by robinheidrich** [laravel-filament/filament#13183]
### Package

filament/filament

### Package Version

v3.2.87

### Laravel Version

v11.10.0

### Livewire Version

v3.5.0

### PHP Version

v8.3.4

### Problem description

In the latest version of Filament, SPA mode no longer works properly. When you change the page, everything disappears and the following error appears in the console:

![image](https://github.com/filamentphp/filament/assets/23118399/bdf7f36b-7094-4393-bb77-abcc34bb6e6e)

### Expected behavior

No errors when changing pages.

### Steps to reproduce

1. activate SPA mode
2. change the page
3. everything disappears and the error is displayed in the console.

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by daom89** [comment]
Yes i confirm in 3.2.87 version spa mode broken the app

![image](https://github.com/filamentphp/filament/assets/1903642/dc952cb6-6843-4530-a6d7-cb1e51b77581)

![image](https://github.com/filamentphp/filament/assets/1903642/8424b82e-ba3e-4a8b-bad5-026a8f32bd63)

Desactive spa() mode works

**Comment by jeffegiovani** [comment]
Exactly the same problem here, after running "composer update", my stack info:

**Package**
filament/filament

**Package Version**
v3.2.87 (upgraded from v3.2.86)

**Laravel Version**
v10.48.12

**Livewire Version**
v3.5.0

**PHP Version**
v8.2.3

**Comment by bzy107** [comment]
https://github.com/filamentphp/filament/pull/13074#issuecomment-2158844614

**Comment by danharrin** [comment]
Should be fixed in the latest release

**Comment by AFSDARIF** [comment]
SPA still doesn't work in production

**Comment by danharrin** [comment]
With the same error? Probably a cache issue or your published assets are not up to date
