### ISSUE TITLE
Filament does not encode square brackets in the URL by default

### ISSUE THREAD

**Issue by Tklaversma** [laravel-filament/filament#13188]
### Package

filament/filament

### Package Version

v3.2.68

### Laravel Version

v11.10

### Livewire Version

v3.5.0

### PHP Version

PHP 8.2

### Problem description

Filament does not encode square brackets `[ ]` in the URL by default.

### Expected behavior

Square brackets should be encoded according to [RFC 3986](https://www.ietf.org/rfc/rfc3986.txt).

### Steps to reproduce

I encountered this problem when I was redirecting a user from a certain action to another resource with a filter applied, like so:
```php
return $table
    ->...
    ->actions([
        ActionGroup::make([
            Action::make('...')
                  ->...
                  ->action(
                      fn($record) => redirect()->to(
                          ListOtherResourceFilament::getUrl([
                              'tableFilters' => [
                                  'unit' => [
                                      'reservable' => [
                                          'code' => $record->id
                                      ],
                                  ],
                              ],
                          ])
                      )
                  )
            ,
        ]),
    ]);
```
As you can see here, I add a filter (query string) to the URL the user is redirecting to. Since `redirect()->to()` is a Laravel function, it encodes the full URL, as it should!, and I end up on:
```
https://example.local/....?tableFilters%5Bunit%5D%5Breservable%5D%5Bcode%5D=UN100000
```
This works. Filament does understand the filter and applies it on load. But whenever I change the current filter to another value on that page, Filament **ADDS** the whole filter again, this time unencoded. So I end up with the URL that has the filter twice.
```
https://example.local/....?tableFilters%5Bunit%5D%5Breservable%5D%5Bcode%5D=UN100000&tableFilters[unit][reservable][code]=UN100001
```
And it even gets worse when I apply another filter.

In my opinion there are 2 solutions. 
1. Filament should encode square brackets globally. Impact might be big...
2. Filament keeps using square brackets unencoded (which is easier to read, but against RFC), and tries to fix applying filters to URL's that have those square brackets encoded.

---

If you want to make this working, as a workaround you can do the following (special thanks to @dissto):
```php
return $table
    ->...
    ->actions([
        ActionGroup::make([
            Action::make('...')
                  ->...
                  ->url(function ($record) {
                      $query = http_build_query([
                          'tableFilters' => [
                              'unit' => [
                                  'reservable' => [
                                      'code' => $record->code,
                                  ],
                              ],
                          ],
                      ]);

                      return ListOtherResourceFilament::getUrl() . '?' . urldecode($query);
                  })
            ,
        ]),
    ]);
```

### Reproduction repository

https://github.com/Tklaversma/filament

**Comment by danharrin** [comment]
Filament uses the `route()` helper to generate URLs, so what can we do here? Is this not an issue in Laravel?

**Comment by Tklaversma** [comment]
@danharrin the filters itself are handled by Filament and they don't get encoded. That's the issue. 

If I encode it myself in Laravel, I get the square brackets encoded. In Filament they always shown unencoded in the url.

**Comment by danharrin** [comment]
Where do we handle constructing the URL then? I don't recall writing anything like that. The `getUrl()` method just wraps the `route()` helper

**Comment by Tklaversma** [comment]
@danharrin I can dig in if you want. Up till now I just confirmed it's happening in Filament and not in Laravel.

**Comment by danharrin** [comment]
Yes please

**Comment by Tklaversma** [comment]
@danharrin after some digging, Laravel is applying RFC3986 correctly. Under the hood `\Illuminate\Support\Arr::query()` is called, which builds the query string like so:
```php
    /**
     * Convert the array into a query string.
     *
     * @param  array  $array
     * @return string
     */
    public static function query($array)
    {
        return http_build_query($array, '', '&', PHP_QUERY_RFC3986);
    }
```
Hence the `PHP_QUERY_RFC3986`. This will make sure that the query string is encoded accordingly. And the RFC3986 rules state that square brackets may only be used in the host part of the URL.

So, coming back to my original post, Filament is **NOT** using Laravel to apply filters, since square brackets are visible in the URL whenever any filter is applied by the user clicking it. But whenever we route to a resource page with given filters applied accordingly (encoded square brackets), Filament does apply the filter, but after that breaks, whenever it tries to apply any other filters.

So, as mentioned earlier, in my opinion there are 2 solutions.
1. Filament should encode square brackets globally.
2. Or Filament keeps using square brackets unencoded (which is easier to read, but against RFC), and tries to fix applying filters to URL's that have those square brackets encoded.

@danharrin I think we should dive into that. I mean using unencoded square brackets in the url is nice, readable and works, but it's incorrect and Laravel is correctly encoding them. Are we breaking from Laravel ways or are we fixing Filament?

**Comment by danharrin** [comment]
Laravel is responsible for generating URLs, Livewire is responsible for updating the URL when filters are used (through JavaScript), Filament handles neither of those things

**Comment by Tklaversma** [comment]
@danharrin Guess this is a Livewire thing then. Then I'll make an issue there.

**Comment by danharrin** [comment]
Should be relatively easy to reproduce, add an array property with the `Url` attribute on it. Gonna close this but if there is anything we can do to fix this in Filament let me know

**Comment by Tklaversma** [comment]
See https://github.com/livewire/livewire/discussions/8553

**Comment by danharrin** [comment]
I don't think you're going to get a response if you have just linked a Filament installation, its worth creating a separate description explaining how the URLs differ when generated by Laravel or Livewire and having a Wirebox with plain Livewire code.
