### ISSUE TITLE
Navigation order does not respect the `$navigationSort` parameter when used with `$navigationGroup`

### ISSUE THREAD

**Issue by peter-mw** [laravel-filament/filament#13189]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

v11

### Livewire Version

v3

### PHP Version

PHP 8.2

### Problem description

Navigation does not respect the `$navigationSort` parameter when used with `$navigationGroup` 

### Expected behavior

![image](https://github.com/filamentphp/filament/assets/5698247/8bb10309-e489-475b-a243-ac46f21bc145)

Expected to page named `Two` to be between `One` and `Three`

### Steps to reproduce

Open the file [app/Filament/Pages/Two.php](https://github.com/peter-mw/filament-nav-order-bug/blob/main/app/Filament/Pages/Two.php#L15)

Remove line `protected static ?string $navigationGroup = 'Two';` and order is  corect, but with this line the page `Two` does after `Three` 

### Reproduction repository

https://github.com/peter-mw/filament-nav-order-bug

### Relevant log output

```shell
No log
```

**Comment by danharrin** [comment]
All groups go after ungrouped items, we do not break up the ungrouped items with groups as it could result in weird behaviour where you expect part of the group to be in one place and another part to be in another

**Comment by peter-mw** [comment]
Is there some way to archive this effect, or this this can be made behind a flag ?  

Will you accept PR for something like this?

![image](https://github.com/filamentphp/filament/assets/5698247/84c3694b-ba1d-4a01-920f-9b644c00d6ec)

**Comment by danharrin** [comment]
No sorry, it would introduce too much complexity into the navigation logic.

**Comment by danharrin** [comment]
You can use navigation groups with blank labels to achieve a similar affect if you define the `navigation()` function yourself

**Comment by peter-mw** [comment]
Will try, thanks for the suggestions

**Comment by peter-mw** [comment]
hi @danharrin 

Can we have something like  `protected static ?array $acceptNavigationGroups = ['Two']`

Parameter in the main menu `acceptNavigationGroups` ? 

It will look like this

```
class One extends Page
{
    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.pages.one';

    protected static ?int $navigationSort = 1;

    protected static ?array $acceptNavigationGroups = ['Two'];

}


class Two extends Page
{
    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.pages.two';

    protected static ?int $navigationSort = 2;

    protected static ?string $navigationGroup = 'Two';

}

```

 
What do you think ?

**Comment by peter-mw** [comment]
Or even better, an option is to research recursive menus with the KNP Menu builder, https://github.com/KnpLabs/KnpMenu

It allows unlimited nested menus.

**Comment by danharrin** [comment]
There is no technical reasons in PHP to not support nested menus. It's all frontend design work that is nearly impossible to balance and account for all combinations

**Comment by peter-mw** [comment]
@danharrin 

How to have a menu item appear inside another menu?

To make menu Two appear inside menu One, is not possbible at the moment 

We can have new `navigationParent` parameter to solve this issue.  


For example:

```php
protected static ?string $navigationParent = 'One';
```

The class would look like this:

```php
class TwoOne extends Page
{
    protected static ?int $navigationSort = 2;
    protected static ?string $navigationParent = 'One';
}
class ThreeOne extends Page
{
    protected static ?int $navigationSort = 3;
    protected static ?string $navigationParent = 'One';
}
```

The problem is how to have a single menu item, then a dynamic menu **inside the single menu**, and then another single menu item.


Can you suggest solution ?

**Comment by danharrin** [comment]
I dont understand what that would do, sorry

**Comment by peter-mw** [comment]
Hi, here is a picture of what im trying to make 

![image](https://github.com/filamentphp/filament/assets/5698247/999ac70c-b41f-4fd0-b7d9-c00c7c8b0c86)


Is this possible ?

**Comment by danharrin** [comment]
I suggest using clusters instead

**Comment by danharrin** [comment]
`navigationParentItem` already exists btw https://filamentphp.com/docs/3.x/panels/navigation#grouping-navigation-items-under-other-items
