### ISSUE TITLE
Revealable password button does not fill expected area

### ISSUE THREAD

**Issue by johnbacon** [laravel-filament/filament#13197]
### Package

filament/forms

### Package Version

Latest

### Laravel Version

v10.x

### Livewire Version

Latest

### PHP Version

PHP 8.1.x

### Problem description

![image](https://github.com/filamentphp/filament/assets/308588/85c5ed00-d467-4831-bf51-d69bc73a90a1)

The revealable password button's click target is smaller than the expected area (the "suffix" section).

### Expected behavior

I would expect to be able to click all the way to the suffix container's borders.

### Steps to reproduce

1. Go to demo.filamentphp.com
2. Review the revealable button's bounds (`fi-ac-icon-btn-action`)

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by zepfietje** [comment]
Thanks for opening this issue, @johnbacon!

While I do understand some may expect the entire box to be clickable, the current behavior is by design. The suffix action is just an icon button, so that icon button determines its size. Spanning the full container would be very tricky, since devs may add additional actions, an icon or label there too.

**Comment by johnbacon** [comment]
@zepfietje I hear you on that!

I know that you're limited somewhat, but I feel there must be a way. I'm not at a machine right now to examine the markup, but if the concern is for multiple actions, could that be handled instead with a sibling selector or grid spacing for only those cases where there _are_ multiple elements?

**Comment by zepfietje** [comment]
Honestly I don't think it's worth the complexity.

Potentially we could introduce another action type (just like button, link, icon button, badge, dropdown item) to be used inside input affixes. It'd need to support all inputs and combinations of suffixes and actions though.

Feel free to have a look and create a pull request if you think you've found a solid solution that takes into account all variables and edge cases here. 🙂
