### ISSUE TITLE
Layout issue with multiple resource relationships

### ISSUE THREAD

**Issue by jellycow** [laravel-filament/filament#132]
**Describe the bug**
When adding 2 or more relationships to a resource the layout is not as expected with one section per relationship. Instead an empty section is created and associated relationship table is displayed inside the previous relationship section.

**To reproduce**
Steps to reproduce the behaviour:
1. Add 2 or more relationships to a resource
2. Create a record
3. Edit the record
4. You will see 2 relationships within the one section and a blank section below it

**Expected behaviour**
Each relationship component would be inside its own section

**Screenshots**

How the edit page looks
![Incorrect layout out of multiple relationships](https://user-images.githubusercontent.com/209072/110402223-f0d43c00-8072-11eb-9213-21298458cfe0.png)

Page source for this layout 
![Src of layout issue](https://user-images.githubusercontent.com/209072/110402240-f893e080-8072-11eb-9374-6a996554a2cf.png)

Looking at the page src it looks like the 2nd relationship component is being added into the first's section and a new section is also created with a blank div with the 2nd relationship's component's live wire id as well.

Expected layout
![Expected layout of multiple relationships](https://user-images.githubusercontent.com/209072/110402336-24af6180-8073-11eb-88cb-39a89761b8de.png)

Expected page source
![Src of expected layout](https://user-images.githubusercontent.com/209072/110402367-33961400-8073-11eb-872c-eba7b89a9709.png)

**Context**
- Package version: [1.4.5]
- Livewire version: [2.3.0]
- Laravel version: [8.30]
- Browser: [Chrome]
- Server OS: [OSX 10.11.6]
- PHP version: [7.4]
- Database: [MySQL 8.0]

**Additional details**
 Original order of the relationships is as below

![Relationship order](https://user-images.githubusercontent.com/209072/110402192-e023c600-8072-11eb-9ad7-72efbe1fa107.png)

** Update **
If more than 2 relationships are added, the subsequent sections appear to be correct but the initial 2 are as described

![4 relationships](https://user-images.githubusercontent.com/209072/110403077-6391e700-8074-11eb-8f9a-af13aafa4114.png)

**Comment by danilopolani** [comment]
That's weird, I have no problems:

![image](https://user-images.githubusercontent.com/6277291/110499696-c7f68a00-80f8-11eb-9a1a-bfd244ba7575.png)

The source looks fine too:

![image](https://user-images.githubusercontent.com/6277291/110499789-df357780-80f8-11eb-89a8-6ef209bfa563.png)

**Comment by jellycow** [comment]
Odd indeed! I’ll rebuild everything and try another example to see if it persists.

**Comment by ryangjchandler** [comment]
@jellycow Try upgrading to the latest version of Livewire, your original issue says you're on 2.0.0 which is quite out of date now.

**Comment by jellycow** [comment]
Sorry, that should have been livewire version 2.3.0. Just checked your PR and I can confirm the change has fixed the issue for me. Thanks a lot.

**Comment by ryangjchandler** [comment]
Ah, a key does make sense. Rookie error - I'll approve the PR but will wait for @danharrin to look too.

**Comment by danharrin** [comment]
Hey! This has been merged and released.

**Comment by jellycow** [comment]
Excellent work!
