### ISSUE TITLE
Are `primary`, `info`, `danger`, `warning` or `success` colors?

### ISSUE THREAD

**Issue by bilogic** [laravel-filament/filament#13202]
### Package

filament/filament

### Package Version

3.2.88

### Laravel Version

10.48.12

### Livewire Version

3.5.0   

### PHP Version

8.2.18

### Problem description

https://filamentphp.com/docs/3.x/support/blade-components/button#changing-the-color-of-a-button

`primary`, `info`, `danger`, `warning` and `success` are technically not colors. Only `gray` is a color.

### Expected behavior

Instead of `->color(...)`, it would be more appropriate to call it `->tone()`, `->theme()` or something else

### Steps to reproduce

N/A

### Reproduction repository

https://github.com/bilogic/filament-issue

**Comment by bilogic** [comment]
At this rate of closure, it's impossible to give good feedback.

**Comment by danharrin** [comment]
You submitted a bug report for what is basically a feature request or suggestion, which we ask for in Discussions
