### ISSUE TITLE
Method Filament\Actions\ActionGroup::getName does not exist.

### ISSUE THREAD

**Issue by kl4ver** [laravel-filament/filament#13230]
### Package

filament/filament

### Package Version

v3.2.83

### Laravel Version

v10.48.12

### Livewire Version

v3.5.0

### PHP Version

PHP 8.1

### Problem description

In the `getHeaderActions` of a `HasForms` component in the `forms` method, I try to add an `ActionGroup`, but then I get the error `Method Filament\Actions\ActionGroup::getName does not exist.`

```
public function getHeaderActions(): array
	{
		return [
			ActionGroup::make([
				FormAction::make('AAA'),
				FormAction::make('BBB'),
				FormAction::make('CCC'),

			])->label('test'),
		];
	}

```

How to fix this? In the tables it's working perfect.

### Expected behavior

There shouldn't be any error, you should also can use this function in forms

### Steps to reproduce

Add the code above to a form

### Reproduction repository

https://github.com/ask

**Comment by danharrin** [comment]
No reproduction repository

**Comment by kl4ver** [comment]
> No reproduction repository

I know, but I have a sample code provided, isn't this enough?

**Comment by danharrin** [comment]
Please read the issue template
