### ISSUE TITLE
[Bug] Tests will fail if you change the default admin panel

### ISSUE THREAD

**Issue by mokhosh** [laravel-filament/filament#13280]
### Package

filament/filament

### Package Version

v3.2.40

### Laravel Version

v11.10.0

### Livewire Version

v3.5.0

### PHP Version

v8.3.8

### Problem description

When you change the default panel a lot of tests fail, even though the actual panel and resources work fine.
The error is:
```
Illuminate\View\ViewException: Route [filament.user.resources.users.edit] not defined.
```
which is because it's trying to create a url for the resource but it can't decide correctly which panel it is located in.

### Expected behavior

Tests should work if the actual panel is working.

### Steps to reproduce

Clone the reproduction repo, run pest, and check out the actual pages in the browser.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/mokhosh/filament-multipanel-test-bug

**Comment by danharrin** [comment]
You need to call `Filament::setCurrentPanel(Filament::getPanel('id'))` before tests in a different panel.

**Comment by mokhosh** [comment]
Thanks dan. Is this in the docs?

**Comment by mokhosh** [comment]
Also, I was a bit worried about fixing this manually, since I thought I might be creating an unrealistic situation in the tests that will always pass even if the code fails in the real world.

So that's not the case?

**Comment by danharrin** [comment]
That code is called in middleware when accessing the panel, if you dont make a request in the test then the code doesnt run which causes the problem. I would welcome an addition to the panel testing docs

**Comment by mokhosh** [comment]
Here Dan. Thank you. https://github.com/filamentphp/filament/pull/13291
