### ISSUE TITLE
n+1 query in TagsColumn

### ISSUE THREAD

**Issue by mohammad2306** [laravel-filament/filament#1330]
### Package

filament/filament

### Package Version

2.9.8

### Laravel Version

8.80

### Livewire Version

2

### PHP Version

8

### Bug description

hi, i use TagsColumn::make('roles.name') for show user roles
in queries i have n+1 problem

**Comment by drhoussem** [comment]
@danharrin I was about to submit an issue then I found that @mohammad2306 had the same bug

**Comment by pathros** [comment]
Is it the same or similar to the one I reported on the [discord channel](https://discord.com/channels/883083792112300104/883085267383226478/1080545473611448420) ?
