### ISSUE TITLE
MarkdownEditor and RichEditor returns an Entangle error when a JSON value is empty

### ISSUE THREAD

**Issue by gavinhewitt** [laravel-filament/filament#1333]
### Package

filament/filament

### Package Version

latest

### Laravel Version

latest

### Livewire Version

latest

### PHP Version

8.1

### Bug description

I have a 'meta' json field that's correctly cast as array and if I try to edit that in an Textarea or TextInput it works as expected. If I change the input to RichEditor or MarkdownEditor the field is not loaded and there's an error in the console. As a workaround you can set a value in `mutateFormDataBeforeFill(array $data)`, but that can't be the way this should work ;-)

![image](https://user-images.githubusercontent.com/1969103/150803003-e57e4dba-8d97-4d6b-a4f9-144c9af50f5a.png)

**Comment by danharrin** [comment]
Very much an edge case ahha, never heard of anyone wanting to edit JSON with a rich text editor 😂 But I suppose we should cast it to a string anyway.

I will look into this when I refactor the casting system for components, which is on my todo list.

**Comment by gavinhewitt** [comment]
> Very much an edge case ahha, never heard of anyone wanting to edit JSON with a rich text editor 😂 But I suppose we should cast it to a string anyway.
> 
> I will look into this when I refactor the casting system for components, which is on my todo list.

Hm, I think I have described it poorly, leaving room for misinterpretation. What I meant with json field is that there's a 'meta' JSON field, that holds a 'description' entry (referenced as $record->meta['description']). When I use this field in Filament (meta.description) you get this error, if $record->meta['description'] does not exist yet.

Not sure if that is what you gathered from my original description, but hope to clear it a bit more. 

![image](https://user-images.githubusercontent.com/1969103/151701989-4cc2d197-1d3f-4e61-ac93-161c8a59d791.png)

**Comment by danharrin** [comment]
Ahah that makes much more sense. Indeed, we should make it work if the JSON key doesn't exist in the database.

**Comment by danharrin** [comment]
Fixed in the next version :)
