### ISSUE TITLE
Move to Alpine.js Anchor plugin

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#13333]
Replaces the following direct dependencies: `tippy.js`, `alpine-floating-ui`, and `alpine-tooltip`.

Replaces https://github.com/filamentphp/filament/issues/8701.

**Comment by zepfietje** [comment]
@awcodes are there any differences between your plugin and [the Alpine.js one](https://alpinejs.dev/plugins/anchor)?

Asking since Livewire ships with the Alpine.js plugin and we're also going to move to the [Alpine.js Sort plugin](https://github.com/filamentphp/filament/issues/12666).

**Comment by awcodes** [comment]
Anchor is a lot less flexible. It only offers placement and offset settings and it requires more manual set up. Also, to my knowledge it isn't a11y compatible out of the box.

**Comment by zepfietje** [comment]
Alright, thanks for clarifying, @awcodes!

**Comment by awcodes** [comment]
Something else to keep in mind with this is that anchor fundamentally operates in a different way than we are using the floating ui plugin. Anchor just says attach this element to this other element vs this element has a drop down component. If that makes sense. So, switching to anchor will lose the context and ability to use the open/close/toggle methods which are embedded with the floating ui alpine plugin. More importantly the biggest issue i see is that anchor doesn't support teleport which it looks like every instance of the floating ui implementation is using by default so we could run into a lot of z index issues.

**Comment by zepfietje** [comment]
Thanks for the clear summary, @awcodes!

I agree the missing teleport feature is a deal-breaker.
However, maybe we could use [HTML's `popover` API](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover)?

**Comment by binaryfire** [comment]
> Thanks for the clear summary, @awcodes!
> 
> I agree the missing teleport feature is a deal-breaker. However, maybe we could use [HTML's `popover` API](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/popover)?

Hey @zepfietje. A bit off topic, but I just stumbled across this and thought I'd mention that browser support for the popover API isn't great. They used it for Flux UI's dropdowns and they're completely broken on my iPhone X. It's definitely worth checking _Can I Use_ before implementing any new APIs. Anything above ~94% is ok. Anything less and there will usually be problems on 
 still fairly modern (eg. 2 year old) browsers.

This page also shows it only has partial support: https://developer.mozilla.org/en-US/docs/Web/API/Popover_API

And there are ongoing iOS issues: https://bugs.webkit.org/show_bug.cgi?id=267688
