### ISSUE TITLE
Custom user menu item not being translated

### ISSUE THREAD

**Issue by cawecoy** [laravel-filament/filament#13342]
### Package

filament/filament

### Package Version

3.2.91

### Laravel Version

10.48.12

### PHP Version

8.2.18

### Problem description

[Custom user menu item](https://filamentphp.com/docs/3.x/panels/navigation#customizing-the-user-menu) is not being translated, it is always shown in the app's main language, no matter the user switches to another language.

### Expected behavior

Custom user menu item to be translatable.

### Steps to reproduce

I am using  [filament/spatie-laravel-translatable-plugin](https://filamentphp.com/plugins/filament-spatie-translatable).

Provider:

```php
use App\Filament\Pages\Settings;
use Filament\Navigation\MenuItem;
use Filament\Panel;
use Filament\SpatieLaravelTranslatablePlugin;

public function panel(Panel $panel): Panel
{
    return $panel
        // ...
        ->userMenuItems([
            MenuItem::make()
                ->label(__('admin.settings'))
                ->url('#')
                ->icon('heroicon-o-cog-6-tooth'),
            // ...
        ])
        ->plugins([
                SpatieLaravelTranslatablePlugin::make()
                    ->defaultLocales(['en', 'es']),
        ]);
}
```

lang/en/admin.php:

```php
return ['settings' => 'Settings'];
```

lang/es/admin.php:

```php
return ['settings' => 'Ajustes'];
```

Note that the [offical doc](https://filamentphp.com/docs/3.x/panels/navigation#customizing-the-user-menu) shows something like `->label('Settings')` but I am doing `->label(__('admin.settings'))` because my app's user menu should be translatable.

But when the user switches the language to Spanish, it still shows "Settings" (custom user menu items are the only things in my application that are not translated to Spanish, it is still in English language). The Filament native built-in "Logout" user menu item is translated correctly, it's only my CUSTOM menu items that are not being translated at all.

Additional information: I've found a workaround to make it work using closure.

```php
->label(fn (): string => __('admin.settings'))
```

But I expect it to work using just `->label(__('admin.settings'))`  without the workaround.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com

**Comment by zepfietje** [comment]
Please provide a reproduction repository.

**Comment by SerjoA** [comment]
the only way you can translate this is via closure, like this:

```
MenuItem::make()
               ->label(fn() => __('Profile'))
               ->icon('heroicon-o-user-circle')
               ->url(static fn() => url(Profile::getUrl())),
```

@cawecoy

**Comment by cawecoy** [comment]
It works when adding the array key `'settings' => MenuItem::make()`:

```
use App\Filament\Pages\Settings;
use Filament\Navigation\MenuItem;
use Filament\Panel;
use Filament\SpatieLaravelTranslatablePlugin;

public function panel(Panel $panel): Panel
{
    return $panel
        // ...
        ->userMenuItems([
            'settings' => MenuItem::make()
                ->label(__('admin.settings'))
                ->url('#')
                ->icon('heroicon-o-cog-6-tooth'),
            // ...
        ])
        ->plugins([
                SpatieLaravelTranslatablePlugin::make()
                    ->defaultLocales(['en', 'es']),
        ]);
}
```
