### ISSUE TITLE
Number::useLocale not working

### ISSUE THREAD

**Issue by Zacktamondo** [laravel-filament/filament#13340]
### Package

filament/filament

### Package Version

v3.2.92

### Laravel Version

v11.11.1

### Livewire Version

v3.5.1

### PHP Version

PHP 8.3.8

### Problem description

When adding the number helper function it doesn't work as expected.
I used ar locale because it changes the numbers completely.

### Expected behavior

To change the Locale according to the provided locale in the AppServiceProvider

### Steps to reproduce

1. Make a filament project
2. Make a test resource
3. Add Number::useLocale('ar'); to AppServiceProvider boot() function
4. check

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/Zacktamondo/FilamentNum

**Comment by Zacktamondo** [comment]
Hello @danharrin and @dmason30  
Thank you for your hard work, but I tested it with the repo after updating to the latest and the issue still persist.
Is there anything I need to do after applying the Number::useLocale to make it take effect that I am not aware of?
Thanks a lot again for your work

**Comment by dmason30** [comment]
> Hello @danharrin and @dmason30 Thank you for your hard work, but I tested it with the repo after updating to the latest and the issue still persist. Is there anything I need to do after applying the Number::useLocale to make it take effect that I am not aware of? Thanks a lot again for your work

As the PR description states to now override the Filament default you have to set `Table::$defaultNumberLocale` and `Infolist::$defaultNumberLocale` rather than relying on `Number::useLocale(..)` the filament docs will be updated soon to have these as the recommended ways to override the default number locale.

You will need to wait for Filament to have released this change.

**Comment by Zacktamondo** [comment]
I didn't spot that my bad.
Thanks for the info and the fix.

**Comment by Zacktamondo** [comment]
Hello @danharrin,
For some reason, the latest version didn't include the changes made by @dmason30 to fix the issue.
I checked the release zip too, it's not included.

**Comment by danharrin** [comment]
Yes it was merged after the release, its not in the changelog.
