### ISSUE TITLE
ToolTip "bubble" does not conform to its contents

### ISSUE THREAD

**Issue by notAreYouScared** [laravel-filament/filament#13350]
### Package

filament/filament

### Package Version

v3.2.86

### Laravel Version

v11.10.0

### Livewire Version

v3.5.0

### PHP Version

PHP 8.2.20

### Problem description

When a tooltip is larger than 51 characters it will spill the contents outside of the tooltip window
`required|string|max:60|in:20,testing,the,max,size,of,the,fancy,tool,tip,and,showing,that,it,does,not,wrap`

![image](https://github.com/filamentphp/filament/assets/1757840/4d9926b9-0d9b-4ff0-bae5-cf8704b3fbfe)

Smaller ToolTips are not affected by this. Less than 51 characters. 
`required|string|max:60|in:20,testing,the,max,size,o`
![image](https://github.com/filamentphp/filament/assets/1757840/07aaacdf-2cc5-406b-b508-9f5899429730)
![image](https://github.com/filamentphp/filament/assets/1757840/cba77ffa-c442-4e9b-aebf-464aeabafd40)
![image](https://github.com/filamentphp/filament/assets/1757840/88f0f47d-9f09-49c8-9645-fac539c49cf8)

### Expected behavior

The tooltip conforms to the "bubble" & wraps to ~50 characters per line.

### Steps to reproduce

Create a tooltip with a long value >50.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/NoThanks. < The "template" you guys offer does not even have Filament installed... It's more work than what it's worth. If you find that you need to close this issue due to this not existing, that's unfortunate.

**Comment by danharrin** [comment]
> The "template" you guys offer does not even have Filament installed

You just have to require the package you're using. Not everyone is using the panel builder, so why do we need to assume what you need?

Additionally, even if this is a problem it is probably in https://github.com/ryangjchandler/alpine-tooltip or Tippy.js itself.
