### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by Shaz3e** [laravel-filament/filament#13360]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

v11.9

### Livewire Version

v3.0.0

### PHP Version

PHP 8.2.13

### Problem description

When I run the following command
```
composer require filament/filament:"^3.2" -W
```

I showed the following logs
```
The "3.2" constraint for "filament/filament" appears too strict and will likely not match what you want. See https://getcomposer.org/constraints
./composer.json has been updated
Running composer update filament/filament --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - illuminate/console[v10.0.0, ..., v10.48.14] require nunomaduro/termwind ^1.13 -> found nunomaduro/termwind[v1.13.0, ..., v1.15.1] but these were not loaded, likely because it conflicts with another require.                                                                    
    - filament/filament v3.2.0 requires illuminate/console ^10.0 -> satisfiable by illuminate/console[v10.0.0, ..., v10.48.14].             
    - Root composer.json requires filament/filament 3.2 -> satisfiable by filament/filament[v3.2.0].                                        
                                                                                                                                            

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

### Expected behavior

Expected behavior was to install the filament but installation stopped due to log mentioned log

### Steps to reproduce

Install fresh laravel 
```
laravel new "yourproject"
```

without breeze
and mysql

### Reproduction repository (issue will be closed if this is not valid)

[repo](https://github.com/Shaz3e/laravel-filamentphp)

### Relevant log output

```shell
The "3.2" constraint for "filament/filament" appears too strict and will likely not match what you want. See https://getcomposer.org/constraints
./composer.json has been updated
Running composer update filament/filament --with-all-dependencies
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - illuminate/console[v10.0.0, ..., v10.48.14] require nunomaduro/termwind ^1.13 -> found nunomaduro/termwind[v1.13.0, ..., v1.15.1] but these were not loaded, likely because it conflicts with another require.                                                                    
    - filament/filament v3.2.0 requires illuminate/console ^10.0 -> satisfiable by illuminate/console[v10.0.0, ..., v10.48.14].             
    - Root composer.json requires filament/filament 3.2 -> satisfiable by filament/filament[v3.2.0].                                        
                                                                                                                                            

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

**Comment by pau1phi11ips** [comment]
@Shaz3e I just used `composer require filament/filament -W` and it installed OK. I had the same error with the 3.2 constraint.

**Comment by Jubeki** [comment]
Do you maybe use Windows? The `^` is an escape character in the Windows terminal and is therefor removed before executing composer. You could try it with `filament/filament:^^3.2` or `filament/filament:^^^^3.2`. This should not be filament specific, and should happen with any composer package which defined a constraint.

**Comment by Shaz3e** [comment]
Yes when I install without any extra flag it works and following is working fine
```
composer require filament/filament
```

**Comment by albertdimasa** [comment]
I have same error too and i use command like this. Maybe because i use laragon 

`composer require filament/filament --ignore-platform-req=ext-zip`

**Comment by heartbreakproductions** [comment]
I am getting the same problem i cant install filament. 
when i use 
> composer require filament/filament

> Your requirements could not be resolved to an installable set of 
packages.

  Problem 1
    - filament/filament v3.2.39 requires filament/support v3.2.39 -> satisfiable by filament/support[v3.2.39].
    - filament/filament v3.2.40 requires filament/support v3.2.40 -> satisfiable by filament/support[v3.2.40].
    - filament/filament v3.2.41 requires filament/support v3.2.41 -> satisfiable by filament/support[v3.2.41].
    - filament/filament v3.2.42 requires filament/support v3.2.42 -> satisfiable by filament/support[v3.2.42].
    - filament/filament v3.2.43 requires filament/support v3.2.43 -> satisfiable by filament/support[v3.2.43].
    - filament/filament v3.2.44 requires filament/support v3.2.44 -> satisfiable by filament/support[v3.2.44].
    - filament/filament v3.2.45 requires filament/support v3.2.45 -> satisfiable by filament/support[v3.2.45].
    - filament/filament v3.2.46 requires filament/support v3.2.46 -> satisfiable by filament/support[v3.2.46].
    - filament/filament v3.2.47 requires filament/support v3.2.47 -> satisfiable by filament/support[v3.2.47].
    - filament/filament v3.2.48 requires filament/support v3.2.48 -> satisfiable by filament/support[v3.2.48].
    - filament/filament v3.2.49 requires filament/support v3.2.49 -> satisfiable by filament/support[v3.2.49].
    - filament/filament v3.2.50 requires filament/support v3.2.50 -> satisfiable by filament/support[v3.2.50].
    - filament/filament v3.2.51 requires filament/support v3.2.51 -> satisfiable by filament/support[v3.2.51].
    - filament/filament v3.2.52 requires filament/support v3.2.52 -> satisfiable by filament/support[v3.2.52].
    - filament/filament v3.2.53 requires filament/support v3.2.53 -> satisfiable by filament/support[v3.2.53].
    - filament/filament v3.2.54 requires filament/support v3.2.54 -> satisfiable by filament/support[v3.2.54].
    - filament/filament v3.2.55 requires filament/support v3.2.55 -> satisfiable by filament/support[v3.2.55].
    - filament/filament v3.2.56 requires filament/support v3.2.56 -> satisfiable by filament/support[v3.2.56].
    - filament/filament v3.2.57 requires filament/support v3.2.57 -> satisfiable by filament/support[v3.2.57].
    - filament/filament v3.2.58 requires filament/support v3.2.58 -> satisfiable by filament/support[v3.2.58].
    - filament/filament v3.2.59 requires filament/support v3.2.59 -> satisfiable by filament/support[v3.2.59].
    - filament/filament v3.2.60 requires filament/support v3.2.60 -> satisfiable by filament/support[v3.2.60].
    - filament/filament v3.2.61 requires filament/support v3.2.61 -> satisfiable by filament/support[v3.2.61].
    - filament/filament v3.2.62 requires filament/support v3.2.62 -> satisfiable by filament/support[v3.2.62].
    - filament/filament v3.2.63 requires filament/support v3.2.63 -> satisfiable by filament/support[v3.2.63].
    - filament/filament v3.2.64 requires filament/support v3.2.64 -> satisfiable by filament/support[v3.2.64].
    - filament/filament v3.2.65 requires filament/support v3.2.65 -> satisfiable by filament/support[v3.2.65].
    - filament/filament v3.2.66 requires filament/support v3.2.66 -> satisfiable by filament/support[v3.2.66].
    - filament/filament v3.2.67 requires filament/support v3.2.67 -> satisfiable by filament/support[v3.2.67].
    - filament/filament v3.2.68 requires filament/support v3.2.68 -> satisfiable by filament/support[v3.2.68].
    - filament/filament v3.2.69 requires filament/support v3.2.69 -> satisfiable by filament/support[v3.2.69].
    - filament/filament v3.2.70 requires filament/support v3.2.70 -> satisfiable by filament/support[v3.2.70].
    - filament/filament v3.2.71 requires filament/support v3.2.71 -> satisfiable by filament/support[v3.2.71].
    - filament/filament v3.2.72 requires filament/support v3.2.72 -> satisfiable by filament/support[v3.2.72].
    - filament/filament v3.2.73 requires filament/support v3.2.73 -> satisfiable by filament/support[v3.2.73].
    - filament/filament v3.2.74 requires filament/support v3.2.74 -> satisfiable by filament/support[v3.2.74].
    - filament/filament v3.2.75 requires filament/support v3.2.75 -> satisfiable by filament/support[v3.2.75].
    - filament/filament v3.2.76 requires filament/support v3.2.76 -> satisfiable by filament/support[v3.2.76].
    - filament/filament v3.2.77 requires filament/support v3.2.77 -> satisfiable by filament/support[v3.2.77].
    - filament/filament v3.2.78 requires filament/support v3.2.78 -> satisfiable by filament/support[v3.2.78].
    - filament/filament v3.2.79 requires filament/support v3.2.79 -> satisfiable by filament/support[v3.2.79].
    - filament/filament v3.2.80 requires filament/support v3.2.80 -> satisfiable by filament/support[v3.2.80].
    - filament/filament v3.2.81 requires filament/support v3.2.81 -> satisfiable by filament/support[v3.2.81].
    - filament/filament v3.2.82 requires filament/support v3.2.82 -> satisfiable by filament/support[v3.2.82].
    - filament/filament v3.2.83 requires filament/support v3.2.83 -> satisfiable by filament/support[v3.2.83].
    - filament/filament v3.2.84 requires filament/support v3.2.84 -> satisfiable by filament/support[v3.2.84].
    - filament/filament v3.2.85 requires filament/support v3.2.85 -> satisfiable by filament/support[v3.2.85].
    - filament/filament v3.2.86 requires filament/support v3.2.86 -> satisfiable by filament/support[v3.2.86].
    - filament/filament v3.2.87 requires filament/support v3.2.87 -> satisfiable by filament/support[v3.2.87].
    - filament/filament v3.2.88 requires filament/support v3.2.88 -> satisfiable by filament/support[v3.2.88].
    - filament/filament v3.2.89 requires filament/support v3.2.89 -> satisfiable by filament/support[v3.2.89].
    - filament/filament v3.2.90 requires filament/support v3.2.90 -> satisfiable by filament/support[v3.2.90].
    - filament/filament v3.2.91 requires filament/support v3.2.91 -> satisfiable by filament/support[v3.2.91].
    - filament/filament v3.2.92 requires filament/support v3.2.92 -> satisfiable by filament/support[v3.2.92].
    - filament/filament v3.2.93 requires filament/support v3.2.93 -> satisfiable by filament/support[v3.2.93].
    - filament/filament v3.2.94 requires filament/support v3.2.94 -> satisfiable by filament/support[v3.2.94].
    - filament/filament v3.2.95 requires filament/support v3.2.95 -> satisfiable by filament/support[v3.2.95].
    - filament/filament v3.2.96 requires filament/support v3.2.96 -> satisfiable by filament/support[v3.2.96].
    - filament/filament v3.2.97 requires filament/support v3.2.97 -> satisfiable by filament/support[v3.2.97].
    - filament/filament v3.2.98 requires filament/support v3.2.98 -> satisfiable by filament/support[v3.2.98].
    - filament/filament v0.1.0 requires php ^7.4 -> your php version (8.2.12) does not satisfy that requirement.
    - filament/filament[v1.0.0, ..., v1.13.4] require illuminate/auth ^8.0 -> found illuminate/auth[v8.0.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - filament/filament[v2.5.3, ..., v2.9.6] require illuminate/auth ^8.6 -> found illuminate/auth[v8.6.0, ..., v8.83.27] but these were not loaded, likely because it conflicts with another require.
    - filament/filament[v2.9.7, ..., v2.16.65] require illuminate/auth ^8.6|^9.0 -> found illuminate/auth[v8.6.0, ..., v8.83.27, v9.0.0, ..., v9.52.16] but these were not loaded, likely because it conflicts with another require.
    - filament/filament v2.15.0 requires filament/notifications v2.15.0 -> found filament/notifications[dev-3.x-alpha, v2.15.1, ..., 2.x-dev, v3.0.0-alpha1, ..., 3.x-dev] but it does not match the constraint.
    - filament/filament[v2.16.66, ..., v2.17.56] require illuminate/auth ^8.6|^9.0|^10.0 -> found illuminate/auth[v8.6.0, ..., v8.83.27, v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.20] but these 
were not loaded, likely because it conflicts with another require.
    - filament/filament v2.17.23 requires filament/tables v2.17.23 -> found filament/tables[dev-3.x-alpha, v1.0.0, ..., v1.10.12, 
v2.3.6, ..., 2.x-dev, v3.0.0-alpha1, ..., 3.x-dev] but it does not match the constraint.
    - filament/filament[v3.0.0, ..., v3.0.8] require illuminate/auth ^9.0|^10.0 -> found illuminate/auth[v9.0.0, ..., v9.52.16, v10.0.0, ..., v10.48.20] but these were not loaded, likely because 
it conflicts with another require.
    - filament/filament[v3.0.9, ..., v3.2.35] require illuminate/auth ^10.0 -> found illuminate/auth[v10.0.0, ..., v10.48.20] but 
these were not loaded, likely because it conflicts with another require.
    - filament/filament v3.1.38 requires filament/infolists v3.1.38 -> found filament/infolists[dev-3.x-alpha, v3.0.0-alpha1, ..., 3.x-dev] but it does not match the constraint.
    - filament/filament[v3.2.36, ..., v3.2.38] require illuminate/auth ^10.45 -> found illuminate/auth[v10.45.0, ..., v10.48.20] but these were not loaded, likely because it conflicts with another require.
    - filament/support[v3.2.39, ..., v3.2.98] require ext-intl * 
-> it is missing from your system. Install or enable PHP's intl extension.
    - Root composer.json requires filament/filament * -> satisfiable by filament/filament[v0.1.0, v1.0.0, ..., v1.13.4, v2.5.3, ..., v2.17.56, v3.0.0, ..., v3.2.98].

To enable extensions, verify that they are enabled in your .ini files:
    - C:\xampp\php\php.ini
You can also run `php --ini` in a terminal to see which files are used by PHP in CLI mode.
Alternatively, you can run Composer with `--ignore-platform-req=ext-intl` to temporarily ignore these required extensions.        
You can also try re-running composer require with an explicit version constraint, e.g. "composer require filament/filament:*" to figure out if any version is installable, or "composer require filament/filament:^2.1" if you know which you need.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.

help :(

**Comment by Misbahur** [comment]
> I have same error too and i use command like this. Maybe because i use laragon
> 
> `composer require filament/filament --ignore-platform-req=ext-zip`

thanks it's work

**Comment by kidereo** [comment]
I too had these errors installing Filament on Windows 10 using Herd. 
Running `composer require filament/filament --ignore-platform-req=ext-zip` as recommended above solved the issue.

**Comment by Asadktk** [comment]
i have same error when i install without version like that
composer require filament/filament
 the error was resolve

**Comment by ammarfillet** [comment]
> @Shaz3e I just used `composer require filament/filament -W` and it installed OK. I had the same error with the 3.2 constraint.

YO THANKYOU SO MUCH

**Comment by Ahmad-Fathy** [comment]
just enable zip extension in php.ini

**Comment by dmshved** [comment]
> @Shaz3e I just used `composer require filament/filament -W` and it installed OK. I had the same error with the 3.2 constraint.

Thanks! This command helped me

**Comment by VictorQuicano** [comment]
In some cases it's necessary `extension=intl`, delete ';'
