### ISSUE TITLE
Infinite redirect loop

### ISSUE THREAD

**Issue by plakhin** [laravel-filament/filament#13379]
### Package

filament/filament

### Package Version

v3.2.92

### Laravel Version

v11.11.1

### Livewire Version

v3.5.1

### PHP Version

PHP 8.3.8

### Problem description

I'm building a panel without login and without default Dashboard page.
I've removed `->login()` from `AdminPanelProvider` and now once I remove `->pages([Pages\Dashboard::class])` from `AdminPanelProvider` I'm getting infinite redirect loop when trying to access the panel root url, however if I try to access any resource, e.g. `/users` I can access it without any issues, the issue happens only with the root `/` url. 

In case Login is needed (`->login()` call exists in `AdminPanelProvider`), everything works fine — after successful login I'm being redirected to the first navigation menu item page even if I have Dashboard removed from `AdminPanelProvider`.

### Expected behavior

I've expected root `/` url would redirect to the first navigation item page in case there's no Dashboard, same as if login is needed to access the panel.

### Steps to reproduce

Install fresh Filament Panel Builder, create any Resource, remove `->login()` call from `AdminPanelProvider`, remove `->pages([Pages\Dashboard::class])` from `AdminPanelProvider`. Try to open admin panel by root url, e.g. `http://filament.test/`.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/plakhin/filament-issue

**Comment by danharrin** [comment]
No public reproduction

**Comment by plakhin** [comment]
> No public reproduction

sorry, forgot to change repo visibility, give me few seconds please

**Comment by plakhin** [comment]
@danharrin, thanks for reopening!

**Comment by danharrin** [comment]
In the next release please verify that #13588 fixes the problem

**Comment by plakhin** [comment]
Yep, looking forward to try it ASAP :) Thanks!

**Comment by danharrin** [comment]
You can patch it in your /vendor if you want to check before

**Comment by plakhin** [comment]
I've already tried and it solves the issue. ~I'm just not sure this is the best way.~

UPD: Sorry, no issues with #13588, all good there.
