### ISSUE TITLE
Missing action.php translations

### ISSUE THREAD

**Issue by luilliarcec** [laravel-filament/filament#1338]
### Package

filament/filament

### Package Version

v2.9.9

### Laravel Version

v8.80.0

### Livewire Version

v2.10.1

### PHP Version

PHP 8.1

### Bug description

I am testing the package, and I see that when I delete a resource, a modal appears, but the cancel button does not show the "Cancel" message, but a translation path, this happens when my application uses the "es" language. I was seeing that in the ["feature: Page action modals"](https://github.com/laravel-filament/filament/commit/99a0e362d8d9ffc245fbc272dcd0134a73a73119) commit, it introduces a new file "lang/en/pages/actions.php" however that file is not found in the other translations. I would be happy to make a pull request with the Spanish translation, but unfortunately I could not do it for the other languages.

**Comment by danharrin** [comment]
Hey, I don't regard missing translations as a "bug" really - they're all community-contributed and Filament is not responsible for keeping them up to date - that would be a huge task and we do not have the resources to fix every string for every language.

Please submit a PR if you find something missing in your language :) That would be much appreciated.
