### ISSUE TITLE
DateTimePicker errors when data has value not matching minutes step

### ISSUE THREAD

**Issue by RicLeP** [laravel-filament/filament#13402]
### Package

filament/filament

### Package Version

v3.2.92

### Laravel Version

v10.48.14

### PHP Version

PHP 8.2.20

### Problem description

I have a form containing a `DateTimePicker` input with a `->minutesStep(5)`.

This field can be left blank and when the form is saved the current time will be used, however this then breaks the form when editing the resource if the saved minutes are not a multiple of the `->minutesStep(5)` value (I think this is the issues from my testing).

If my field data when loading the form is: `2024-06-26 08:35:00` the save works.
If my field data when loading the form is: `2024-06-26 08:34:00` the save does not work.

This can be an issue when leaving the field blank allows timestamps to be saved as `now()`, or when using imported data that may not have times matching the step.

This is the error from Chrome

> An invalid form control with name='' is not focusable.
> 
> <input max=​"59" min=​"0" step=​"5" type=​"number" inputmode=​"numeric" x-model.debounce=​"minute" class=​"me-1 w-10 border-none bg-transparent p-0 text-center text-sm text-gray-950 focus:​ring-0 dark:​text-white">​

And Firefox

> An invalid form control is not focusable.

Tested in Chrome Canary and Firefox nightly

### Expected behavior

The form should correctly save (or show a validation error). Or saved data should adhere to `minutesStep()`

### Steps to reproduce

Edit:

Install repository

`php artisan migrate`

`php artisan db:seed`

This will create two records in the `Test` `Model`

![image](https://github.com/filamentphp/filament/assets/19726976/ab54d3aa-bce4-4567-9a48-27422922d7bb)

Open browser console.

Edit ‘On 5 minute interval’ and hit save without making any changes - saving it successful.

Edit ‘Not on 5 minute interval’ and hit save without making any changes - saving will fail.

--

Create a form with a `DateTimePicker` and a set the `minutesStep()`. Load a resource with a value not matching the `minutesStep()`. Attempt to save.

```
Forms\Components\DateTimePicker::make('published_at')
    ->seconds(false)
    ->minutesStep(5)
    ->native(false),
```

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/RicLeP/filament-datetime-bug

**Comment by RicLeP** [comment]
Repository added: https://github.com/RicLeP/filament-datetime-bug

**Comment by zepfietje** [comment]
I'm not sure if this should be treated as a Filament bug, or you should [manually format the state](https://filamentphp.com/docs/3.x/forms/advanced#field-hydration) to conform to the configured step after hydrating the field.

**Comment by RicLeP** [comment]
I wasn't sure either. The error messages the browser gives are very confusing for anyone wanting to debug it, they've nothing to do with the data having the wrong values to work.

For me I see the issue being when external data has been imported, you don't know if it's in the right format. Or saving now() if left empty. 

I agree that it can be resolved when hydrating but with combination of different data sources and the misleading errors (due to browsers more than Filament I think) I can see people being caught out.

Should inputs with minitrStep set hydrate correctly by default?

**Comment by zepfietje** [comment]
Hmm, formatting on Filament's side may confuse devs if they don't expect their stored data to be formatted after hydration.

The native browser input would probably give an unexpected result too (like https://github.com/filamentphp/filament/issues/13123#issuecomment-2155979990).
I'm going to close this issue for now, but tagging @danharrin to see if he thinks we should reopen and implement a "fix" in Filament.

**Comment by RicLeP** [comment]
Related issue - Textarea with numeric() set in a wizard. The user can enter commas, but if the field is on a prior wizard step when saving is throws a _An invalid form control is not focusable._ error in the browser. This stops the data being saved but shows no error or feedback to the user, just a cryptic message in the console.
