### ISSUE TITLE
Source Code duplicates color in style attribute

### ISSUE THREAD

**Issue by rafalateneo** [laravel-filament/filament#13413]
### Package

filament/filament

### Package Version

v3.2.86

### Laravel Version

v10.48.12

### Livewire Version

v3.5.0

### PHP Version

8.2.11

### Problem description

Source Code duplicates all color values in style attribute after edit.
![Zrzut ekranu 2024-06-27 o 11 38 51](https://github.com/filamentphp/filament/assets/174005973/8ccbd9c3-fa32-49c9-8645-d48fb8940885)

### Expected behavior

No duplicates of color attribute.

### Steps to reproduce

1. select some text in TipTap editor
2. change text color using Color toolbar button
3. click Source Code toolbar button
4. click Confirm button
5. click Source Code again to see duplicate of color attribute

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/awcodes/filament-tiptap-editor

**Comment by zepfietje** [comment]
Please open an issue on the [repository of the TipTap Editor plugin](https://github.com/awcodes/filament-tiptap-editor).
