### ISSUE TITLE
Authorization preventing a custom action from working.

### ISSUE THREAD

**Issue by Jeordy** [laravel-filament/filament#13417]
### Package

filament/tables

### Package Version

v3.2.92

### Laravel Version

v11.12.0

### Livewire Version

v3.5.1

### PHP Version

PHP 8.3.8

### Problem description

I've created the following filament table with a deleteAction and a Policy check on the user to have the ability to remove a permission. I'm using Spatie Permission to handle the permissions, but do so in a Policy.

```
public function table(Table $table): Table
    {
        dump(auth()->user()->roles);
        dump(auth()->user()->can('update', Permission::class));

        return $table
            ->query(Permission::query())
            ->columns([
                TextColumn::make('name')
                    ->searchable()
                    ->sortable(),
                TextColumn::make('description')
                    ->searchable()
                    ->sortable(),

            ])
            ->filters([
                // ...
            ])
            ->actions([
                Action::make('deleteAction')
                    ->disabled(!auth()->user()->can('delete', Permission::class)),
            ])
            ->bulkActions([
                // ...
            ]);
    }
```

The Policy looks like this:

```
public function delete(User $user): bool
    {
        return $user->hasPermissionTo('permissions.delete', 'web');
    }
```

Whenever I click on the Delete button, the button disappears and the action is not executed! So I added the next two lines in the table() function:

+ dump(auth()->user()->roles);
+ dump(auth()->user()->can('delete', Permission::class));

On table load I get the roles model with roles and a true on the policy check. But!! After clicking the Delete button, the the result is an empty roles model and a false on the permission check.

It looks like the User object is present, but the roles relation is not initialized.

### Expected behavior

Execute the deleteAction.

### Steps to reproduce

Create a custom action with a button that is only visible when a policy meets the permission.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/not-a-github-repository

**Comment by zepfietje** [comment]
You may want to try wrapping the condition in a callback.
Not a valid reproduction repository.
