### ISSUE TITLE
Add panel option to customize auth routes

### ISSUE THREAD

**Issue by juliangums** [laravel-filament/filament#13454]
### Package

filament/filament

### Package Version

latest

### Laravel Version

latest

### Livewire Version

latest

### PHP Version

latest

### Problem description

The issue is outlined in these two discussions:
https://github.com/filamentphp/filament/discussions/11705
https://github.com/filamentphp/filament/discussions/13431

If I have multiple panels sharing the same login, I need to be able to set a login redirect URL on the panels that don't have their own login.

### Expected behavior

We need to have an option to specify the login redirect route of another panel.

### Steps to reproduce

1. Clone the repos
2. Migrate and seed the database
3. Open the app and log in with `admin@admin.com` and `admin`.
4. You are in the `noteam` panel. Logging out from here will work. But if you navigate to the `team` panel by replacing `noteam` with `team` in the URL, and you try to log out, you will be redirected to the generic login route which does not exist.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/juliangums/filament-multi-panel-auth-test

**Comment by danharrin** [comment]
Can you please reproduce the redirect issue and write a few steps as to how to get there

**Comment by juliangums** [comment]
@danharrin updated this with a repo and instructions.

**Comment by juliangums** [comment]
Basically if I extend the `Panel` and override this method from `HasAuth`
```php
    public function getLoginUrl(array $parameters = []): ?string
    {
        if (! $this->hasLogin()) {
            return null;
        }

        return $this->route('auth.login', $parameters);
    }
```
I can get the desired outcome. I will do that for now, but it might be an option to create a setter, so people can override it without extending `Panel`.

**Comment by danharrin** [comment]
You may do this in v3 onwards

```
->login(fn () => redirect('url here'))
```

**Comment by danharrin** [comment]
This applies to all auth routes, where you can pass in a "route action"
