### ISSUE TITLE
Ability for Form Placeholder to poll

### ISSUE THREAD

**Issue by danharrin** [laravel-filament/filament#13479]
### Discussed in https://github.com/filamentphp/filament/discussions/13459

<div type='discussions-op-text'>

<sup>Originally posted by **SimonMacIntyre** July  3, 2024</sup>
We make use of Placeholder in forms, to show data related to the entity. For example let's say we have an EditUser page and form. 

We are using Placeholder as an example while viewing this page, to show some interesting live updating status about some thing based on this user. (Note: This is not suitable to be in a table/relation manager, we make heavy use of that too, but this specifically is a component we want to show right up in the form in a read-only fashion, but have it live-update).

Any chance of this being a feature we can add some day? Ideally it would be as simple as... 
```php
Placeholder::make('status')->poll(5)->...
```
</div>

**Comment by danharrin** [comment]
cc @SimonMacIntyre

**Comment by alvleont** [comment]
I can make it work just by adding to the TextEntry the following trait:
```php
use CanPollRecords;
```
And the corresponding polling validator in the blade view:
```
@if ($pollingInterval = $getPollingInterval()) wire:poll.{{ $pollingInterval }} @endif
```

https://github.com/user-attachments/assets/7e6d18ad-f3ac-4237-93b0-9355c5d2813e

However, it seems that Placeholder will be deprecated. Am I right?


![Image](https://github.com/user-attachments/assets/2b8c0f52-a64f-4f36-9bc0-110bb1be2e96)

**Comment by SimonMacIntyre** [comment]
Interesting, I'll give that a try, and also take a look at the TextEntry and if that is also pollable or not, thanks for the comment!

**Comment by alvleont** [comment]
It isn't. I mean, this is a code proposal for V4, but I guess I need some guidance before making a PR.

**Comment by danharrin** [comment]
This has been implemented as #14964 in v4

**Comment by indigoram89** [comment]
@danharrin  Hi! One more thing about polling is we need to have ability to poll a ViewPage including RelationManagers. For example I have getSubheading() on my ViewPage and I need to poll this subheading because it has important information.

But for now we do not have ability to poll Infolist or RelationManager page including subheading of this page.

**Comment by indigoram89** [comment]
@danharrin  Hello, do we have any solutions to poll View or RelationManger page entirely from the box? Or poll Infolist like Table. I record a video course for my subscribers and we need to have this feature to demonstrate a correct example.
