### ISSUE TITLE
Alpine trap is deprecated

### ISSUE THREAD

**Issue by lolen** [laravel-filament/filament#1347]
### Package

filament/filament

### Package Version

v2.9.9

### Laravel Version

v8.80.0

### Livewire Version

v2.10.1

### PHP Version

PHP 8.0.14

### Bug description

The "@alpinejs/trap" library is deprecated. Developers recommend to use the "@alpinejs/focus". And they say:

> You can swap this package for that package with zero breaking changes.

Some information[here](https://www.npmjs.com/package/@alpinejs/trap)

**Comment by danharrin** [comment]
Was literally about to push a PR for this, but it completely broke all JS on my local environment. Looking to see whats up now.

**Comment by robertorinaldi-dev** [comment]
Dan Harrin on discord: Alpine.js has sunsetted @alpinejs/trap. If you're using the standalone table builder, make sure to replace it with @alpinejs/focus. You also need to update the plugin in app.js. No further changes are required.

**Comment by danharrin** [comment]
Fixed in the latest version 👍
