### ISSUE TITLE
Tables don't show data

### ISSUE THREAD

**Issue by Wulfheart** [laravel-filament/filament#1348]
### Package

filament/filament

### Package Version

v2.9.10

### Laravel Version

v8.81.0

### PHP Version

PHP 8.1.2

### Bug description

When applying a name to a table column the output is not shown in the table itself.

```php
public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('surname')->name('Nachname')->sortable(),
                Tables\Columns\TextColumn::make('forename')->sortable(),
            ])
            ->filters([
                //
            ])
            ->defaultSort('surname');
    }
```

This results in the following output:
![image](https://user-images.githubusercontent.com/25671390/151049630-28a86ac3-a342-4dde-8204-a65bcea2afb3.png)

If the `name` method is removed the data is shown in the table:
![image](https://user-images.githubusercontent.com/25671390/151049718-ea5d2bf5-d4b1-45a4-a06e-36663ab4cafc.png)

Thank you in advance!

**Comment by danharrin** [comment]
Hey! Looks like you're looking for the `->label()` method. Where is `->name()` used in the docs? It's probably a mistake our end.

**Comment by Wulfheart** [comment]
Ah thanks!
But it worked for the form schema:
```php
public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Card::make([
                    Forms\Components\TextInput::make('forename')->label('Vorname')->required(),
                    Forms\Components\TextInput::make('surname')->name('Nachname')->required(),
                    Forms\Components\TextInput::make('email')->name('Email')->email()->required(),
                    Forms\Components\DatePicker::make('birthday')->name('Geburtstag'),
                    Forms\Components\TextInput::make('mobile_number')->name('Handynummer')->tel(),
                    Forms\Components\TextInput::make('phone_number')->name('Festnetznummer')->tel(),
                    Forms\Components\RichEditor::make('note')->name('Notizen')->columnSpan(2),
                ])->columns(2)

            ]);
    }
```

But I am going to change it. What exactly is the difference between name and label?

**Comment by danharrin** [comment]
`->name()` is just an internal method for setting the field name to use from the database. It's used within the `make()` method and nowhere else - did you just see it hinted by your IDE or something? Maybe we should mark it as `@internal` with a docblock if that is the case.

**Comment by Wulfheart** [comment]
Yes. It was typehinted.
