### ISSUE TITLE
Autocapitalizing text Not working

### ISSUE THREAD

**Issue by kahfieidn** [laravel-filament/filament#13500]
### Package

filament/forms

### Package Version

v3.0

### Laravel Version

v10.0

### Livewire Version

v3.0

### PHP Version

PHP 8.2

### Problem description

ive been read docs https://filamentphp.com/docs/3.x/forms/fields/text-input#setting-the-html-input-type

when i try, text not auto capitalize, help to solve this

### Expected behavior

I want to make mask input text with auto capitalize text

### Steps to reproduce

```
use Filament\Forms\Components\TextInput;
 
TextInput::make('name')
    ->autocapitalize('words')
```

Text at name not showing auto capital

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/kahfieidn/sijarimu-filament

**Comment by zepfietje** [comment]
Please read more about when the HTML autocapitalize feature works and what it does exactly: https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/autocapitalize.
