### ISSUE TITLE
Stats overview widget charts randomly change color when resizing browser

### ISSUE THREAD

**Issue by ryanmortier** [laravel-filament/filament#13518]
### Package

filament/filament

### Package Version

v3.2.92

### Laravel Version

v11.14.0

### Livewire Version

v3.5.2

### PHP Version

PHP 8.2.21

### Problem description

When using stat widgets, the chart color will load fine on a hard reload but when you resize the browser window, will randomly flip between colors.

![WqE9mpX](https://github.com/filamentphp/filament/assets/2053960/8c62af63-420f-4bec-9e0c-429470bce3c8)

![f1IyqJJ](https://github.com/filamentphp/filament/assets/2053960/e392555b-43ea-453a-bdf9-6b0983a4bdc5)

I tested in both Chrome and Safari so I don't think it's a browser issue.

More discussion here: https://github.com/filamentphp/filament/discussions/10637

**Edit:** They also appear to change color with sidebar collapse and also polling updates.

### Expected behavior

Stay the original color.

### Steps to reproduce

Open demo app dashboard and resize browser. Observe stat widget chart colors change.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/filamentphp/demo

**Comment by zepfietje** [comment]
I've been able to reproduce this issue on Safari now.
If you have any idea about the cause of the bug, please let us know or attempt a pull request to fix the issue. 🙂
