### ISSUE TITLE
Hungarian translation attribute typo - Filament Panels

### ISSUE THREAD

**Issue by Szabocsongi576** [laravel-filament/filament#13524]
### Package

Other

### Package Version

v3.2.0

### Laravel Version

v10.48.12

### Livewire Version

v3.5.0

### PHP Version

PHP 8.1.27

### Problem description

The attached picture describes the 5 cases where the attribute name in the throttled.body string is not correct.

![image](https://github.com/filamentphp/filament/assets/47359412/19d66588-ee5f-4859-8d0e-51d61ed65ae7)

### Expected behavior

The proper name is ":seconds", as in the other language files.

![image](https://github.com/filamentphp/filament/assets/47359412/d77d5ff6-240c-492d-97ab-08c65fc99a81)

### Steps to reproduce

Open the files.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/filamentphp/panels/tree/3.x/resources/lang/hu

**Comment by VasasA** [comment]
@Szabocsongi576 Thank You! Köszönjük! This issue is fixed by this [PR.](https://github.com/filamentphp/filament/pull/15074/files)
