### ISSUE TITLE
Filters Removal causes "type" error

### ISSUE THREAD

**Issue by ahsandevtech2** [laravel-filament/filament#13525]
### Package

filament/tables

### Package Version

v3.2.92

### Laravel Version

v10.48.13

### Livewire Version

v3.5.1

### PHP Version

PHP 8.0.2

### Problem description

So I am using only filament's table builder in my project and I am using both queryBuilder and simple Filter in one of my tables. The scenerio I have in my table is that I want to preselect some filters when the table loads like that:
              
              ->filters([
                Filter::make('status')
                    ->form([
                        TextInput::make('status_name')->debounce(500)->default('active'),
                    ])->query(function (Builder $query, array $data) {
                        return $query->whereHas('status_type', function ($query) use ($data) {
                            $query->where('name', 'like', '%' . $data['status_name'] . '%');
                        });
                    })->indicateUsing(function (array $data): array {
                        $indicators = [];
                        $name = $data['status_name'] ?? '';

                        if (!empty($name)) {
                            $indicators[] = Tables\Filters\Indicator::make($name)->removeField('status_name');
                        }

                        return $indicators;
                    }),
                Filter::make('assignee')
                    ->form([
                        TextInput::make('assignee_name')->debounce(500)->default(Auth::user()->full_name),
                    ])->query(function (Builder $query, array $data) {
                        return $query->whereHas('administrative_officer', function ($query) use ($data) {
                            $query->orWhere('name', 'like', '%' . $data['assignee_name'] . '%');
                            $query->orWhere('surname', 'like', '%' . $data['assignee_name'] . '%');
                        });
                    })->indicateUsing(function (array $data): array {
                        $indicators = [];
                        $assignee = $data['assignee_name'] ?? '';

                        if (!empty($assignee)) {
                            $indicators[] = Tables\Filters\Indicator::make($assignee)->removeField('assignee_name');
                        }

                        return $indicators;
                    }),
                Filter::make('admin')
                    ->form([
                        TextInput::make('admin_name')->debounce(500)->default(Auth::user()->full_name),
                    ])->query(function (Builder $query, array $data) {
                        return $query->whereHas('authorized_officer', function ($query) use ($data) {
                            $query->orWhere('name', 'like', '%' . $data['admin_name'] . '%');
                            $query->orWhere('surname', 'like', '%' . $data['admin_name'] . '%');
                        });
                    })->indicateUsing(function (array $data): array {
                        $indicators = [];
                        $assignee = $data['admin_name'] ?? '';

                        if (!empty($assignee)) {
                            $indicators[] = Tables\Filters\Indicator::make($assignee)->removeField('admin_name');
                        }

                        return $indicators;
                    }),
                QueryBuilder::make()
                    ->constraints([
                        QueryBuilder\Constraints\TextConstraint::make('case_number'),
                        QueryBuilder\Constraints\TextConstraint::make('case_date'),
                        QueryBuilder\Constraints\TextConstraint::make('case_cause.name'),
                        QueryBuilder\Constraints\TextConstraint::make('case_forum.name'),
                        QueryBuilder\Constraints\TextConstraint::make('case_reference_number'),
                        QueryBuilder\Constraints\TextConstraint::make('department.name'),
                        QueryBuilder\Constraints\TextConstraint::make('district.name'),
                        QueryBuilder\Constraints\TextConstraint::make('member_category.name'),
                        QueryBuilder\Constraints\TextConstraint::make('relates_to.case_number'),
                        QueryBuilder\Constraints\TextConstraint::make('award'),
                    ])->columnSpanFull(),
            ], Tables\Enums\FiltersLayout::AboveContentCollapsible)
            
But the problem is when I add a rule from query builder like that:
  
<img width="1190" alt="Screenshot 2024-07-10 at 1 35 34 PM" src="https://github.com/filamentphp/filament/assets/124149818/714674c7-0b7e-480f-bb6f-610a64edf25d">

And when I remove all the filters by clicking the remove all button on the bottom right I get this error: "Undefined array key "type" which is happening only if I use both the filters (simple filter and queryBuilder)
      

### Expected behavior

Expected behavior would be not getting any error if I clear all the filters.

### Steps to reproduce

<img width="1188" alt="image" src="https://github.com/filamentphp/filament/assets/124149818/03037dc6-e50f-40c5-b845-bd76f2f55083">

Use both filters and click the clear all button in bottom right

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/PropaySystems/solidarity

**Comment by ahsandevtech2** [comment]
I solved this issue for now by overriding the "removeTableFilters" method in my Livewire component and unsetting queryBuilder from the filters like that:
        
        $filters = $this->getTable()->getFilters();
        
        if(isset($filters['queryBuilder'])) {
            unset($filters['queryBuilder']);
        }

**Comment by zepfietje** [comment]
Invalid reproduction repository.
