### ISSUE TITLE
FileUpload doesn't  upload in production

### ISSUE THREAD

**Issue by uniquedigitals** [laravel-filament/filament#13582]
### Package

filament/filament

### Package Version

3.2

### Laravel Version

11

### Livewire Version

3.5

### PHP Version

8.3.0

### Problem description

 I'm using Laravel with Filament
admin, I could upload images offline in local server but once i'm in production, It doesn't upload. The FileUpload component doesn't work. Do you know what I can do?

### Expected behavior

![b80a0fc4-d41f-4406-9fd9-f856e585c5ff](https://github.com/user-attachments/assets/25def40f-76e4-4c29-91b4-48aa5c00bed9)
i expected to see the image uploaded and render in views

### Steps to reproduce

i checked console and saw 404
![Capture](https://github.com/user-attachments/assets/bc747e8d-0060-41fe-b8a0-7ad6b146170b)

### Reproduction repository (issue will be closed if this is not valid)

b

### Relevant log output

```shell
404 .... file not found
```

**Comment by fatihtkale** [comment]
Did you fix his by any chance?
