### ISSUE TITLE
Make Stat a ViewComponent

### ISSUE THREAD

**Issue by danharrin** [laravel-filament/filament#13580]

**Comment by zepfietje** [comment]
What about deprecating the stat overview widget and just making stat a widget?
I've heard people find it confusing that the stat overview widget is its own grid inside the widgets grid. Also, I don't think there's a clear reason for having the overview class, is there, @danharrin?

**Comment by danharrin** [comment]
I want to keep the overview class since you can then share the same data between cards instead of having to potentially make the same queries in multiple
