### ISSUE TITLE
`mutateRecordDataUsing` not mutating data when used with `ReplicateAction`

### ISSUE THREAD

**Issue by Boefjim** [laravel-filament/filament#13604]
### Package

filament/filament

### Package Version

v3.2.40

### Laravel Version

v11.16.0

### Livewire Version

v3.5.4

### PHP Version

PHP 8.2

### Problem description

When using the `mutateRecordDataUsing` method with the `ReplicateAction` it does not seem to mutate any of the data as specified in the callback function.

### Expected behavior

The `mutateRecordDataUsing` method with the `ReplicateAction` should mutate the data according to the specified callback function.

### Steps to reproduce

1. Clone reproduction repository
2. Run `php artisan key:generate`
3. Run `php artisan serve`
4. Go to localhost:8000/admin
5. Login with pre-filled credentials
6. Go to User resource
7. Press the replicate button
8. Notice you get an unique error because the email was not mutated
9. Notice how in line 43 of `UserResource.php` this email should be mutated
10. Notice how this implementation is exactly as specified in the documentation at https://filamentphp.com/docs/3.x/actions/prebuilt-actions/replicate#customizing-data-before-filling-the-form

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/Boefjim/FilamentMutateRecordDataUsingBug

**Comment by Boefjim** [comment]
I would like to add that for now there is a workaround by using `beforeReplicaSaved`, so I would not say this is an urgent issue, but still one that should be addressed since it is definitely irregular behaviour.
Here is a link to the discussion that made me file this issue: https://github.com/filamentphp/filament/discussions/12617

**Comment by wychoong** [comment]
is this fixed with #13668 ?

**Comment by intrepidws** [comment]
Now that I'm looking at this with fresh eyes - it seems perhaps this issue (and the discussion that preceded it) is actually just a misunderstanding of how `mutateRecordDataUsing()` is supposed to work.

In [the documentation for this method](https://filamentphp.com/docs/3.x/actions/prebuilt-actions/replicate#customizing-data-before-filling-the-form) it specifically says that it is meant to be used to:

> modify the data from a record before it is filled into the form

I totally missed this myself, and was trying to use it incorrectly. In my usage, the usage in the original discussion #12617 as well as the usage in the sample repo from this issue, the code isn't actually using a `form()` method at all. So there is no form data for `mutateRecordDataUsing()` to modify.

It seems like `beforeReplicaSaved()` method is actually what _should_ be used to modify record data when a form field isn't involved.

**Comment by Boefjim** [comment]
Ah, that does indeed make sense, thanks for the clarification!
