### ISSUE TITLE
Modal does not allow altering if relationship

### ISSUE THREAD

**Issue by verbeeksteven** [laravel-filament/filament#1361]
### Package

filament/filament

### Package Version

v2.9.13

### Laravel Version

v8.81

### Livewire Version

v2.10.1

### PHP Version

v8.1

### Bug description

Attempting to edit the resources/vendor/filament/components/modal/index.blade.php does nothing for a relationship modal since it uses the modal as part of the table package `tables::components.modal.index`, rather then filament admin package and you cannot publish the table views.

### Steps to reproduce

Publish the views, edit `modal/index.blade.php` and attempt to edit or create a new relationship. You'll not see the edits reflected. You would have to edit `vendor/filament/tables/resources/components/modal/index.blade.php` or copy that folder to `resources/vendor/tables`

Not sure how best to fix this, if table is not used outside of filament admin you could probably remove the table version since it's the same. If they are used separately, maybe we just need to be able to publish the table views via the publish command?

**Comment by danharrin** [comment]
Hey, this is deliberate. All table modals in the admin panel use the the table modal view. You can publish the tables views using `vendor:publish --tag="tables-views"`. Make sure to delete any views that you don't edit, I don't recommend publishing views unless its absolutely necessary,
