### ISSUE TITLE
FileUpload overlapping other elements

### ISSUE THREAD

**Issue by bbredewold** [laravel-filament/filament#13639]
### Package

filament/filament

### Package Version

v3.2.39

### Laravel Version

v9

### Livewire Version

v3

### PHP Version

8.2

### Problem description

The FileUpload form field, is overlapping the field that is directly underneath it, which causes problems with clicking the next element. As you can see in the screenshot, it looks like the `.filepond--list-scroller` element seems to be overlapping quite a bit...

![BRB2024-07-19 at 09 00 09](https://github.com/user-attachments/assets/3b7e54dc-77df-4f1f-9e8d-0b41e9573daa)

In the original FilePond widget, the `.filepond--list-scroller` element seems be stay more in bounds:

![BRB2024-07-19 at 09 05 15](https://github.com/user-attachments/assets/1fd233d7-e9d6-4b8d-84bc-365d58a1f90b)

### Expected behavior

I think it should not overlap other fields.

### Steps to reproduce

Make a form with a field right under e FileUpload field.

### Reproduction repository (issue will be closed if this is not valid)

https://demo.filamentphp.com/shop/products/products/create

**Comment by bbredewold** [comment]
Pretty valid to me: https://demo.filamentphp.com/shop/products/products/create

**Comment by Gi0vanniM** [comment]
Also still having this issue.
Got a workaround by setting z-index on FileUpload and the input field below it.
```php
FileUpload::make('attachments')
->extraAttributes([
    'style' => 'z-index: 5;',
]),

Select::make('select_input')
->extraAttributes([
    'style' => 'z-index: 10;',
]),
```
