### ISSUE TITLE
Performance issue with table

### ISSUE THREAD

**Issue by Tryfciu** [laravel-filament/filament#13631]
### Package

filament/filament

### Package Version

v3.2.94

### Laravel Version

v10.48.16

### Livewire Version

v3.5.4

### PHP Version

PHP 8.2

### Problem description

Hey! Yesterday we managed to bump versions in our application (v3.2.73 -> v.3.2.94) and we encountered strange performance drop with table component.  After version bump in some cases our table load time jumped from couple of seconds to 20-30 seconds. To be fair, our table is huge (100 records, 12 columns, 20+ filters), and it already had some issues with performance but we solved some of them and were happy. I run some performance tests to find out what is going on and this is the result.

Before version bump

![image](https://github.com/user-attachments/assets/2e5a08f1-e456-458d-a6f0-489391b89c16)

After version bump

![image](https://github.com/user-attachments/assets/b70c078f-7fae-4774-8894-097d9257d3f7)

It looks like watchForCheckboxClicks method takes enormous amount of time to do the work. There was a [discussion](https://github.com/filamentphp/filament/pull/13074#issuecomment-2149482294) about possible performance but as far as I understand there were no changes made.

LINKED PR https://github.com/filamentphp/filament/pull/13074

### Expected behavior

We would like the table to load in the same amount of time it did before or at least in bearable time. In the linked PR there was an idea to let user manage this feature on/off and it would be superb for us.

### Steps to reproduce

In provided repository:
- run seeder (2000 users)
- go to http://127.0.0.1:8000/examples/list
- apply email filter with any value
- disable filter by pressing X in active filters section (yellow box)
![image](https://github.com/user-attachments/assets/9de17b5d-dc09-4115-9b35-96cda1d5a1e6)
- application lags for a while (if you downgrade version under 3.2.87 - version with `watchForCheckboxClicks` then application run smoothly)
- performance check for provided example 
![image](https://github.com/user-attachments/assets/c5ef62db-b87a-46f7-938b-924bc8247aeb)

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/Tryfciu/filament-issue

**Comment by den1n** [comment]
I have the same problem with Filament v3.2.95.

The table freezes every time:

- when any of the filters are applied or removed
- when the user presses the back/forward button in the browser.

![image](https://github.com/user-attachments/assets/9f2ad07e-cdca-4309-9051-5deacf80f4ae)

My table contains 1800 records, paginated by 100 records.

**Comment by Montaserz** [comment]
We are facing the same issue with watchForCheckboxClicks. Tried downgrading to 3.2.92 and still facing the same issue. 50 records only.
![Screenshot](https://github.com/user-attachments/assets/77dcbeab-3bad-47c3-9d12-349c9ea09c4a)
