### ISSUE TITLE
FileUpload uncontrollably modifying the file path

### ISSUE THREAD

**Issue by davmarek** [laravel-filament/filament#13632]
### Package

filament/forms

### Package Version

3.2.90

### Laravel Version

11.10.0

### Livewire Version

3.5.0

### PHP Version

8.2.20

### Problem description

The FileUpload component is prefixing the stored file path with `storage/` prefix when displaying the file (image) preview. This approach is correct for displaying an image.

When Laravel Accessor is created on the attribute with file path to add the `storage/` prefix when using the file path attribute elsewhere on the website. Then, Filament forcefully adds the `storage/` prefix anyway, thus not finding the file (image).

That behaviour than makes Filament think, that no file is there -> no file is displayed -> when the model is saved, the value is set to null.

### Expected behavior

The FileUpload component should have an option to disable the automatic prefixing to enable the developer to add it themselves globally.

### Steps to reproduce

1. Add an Accessor to add the `storage/` prefix to the attribute that stores the file path (example value: `img/event/something.jpg`)

> Note: In this example, a default image path is being set if the attribute is null. This is not exactly necessary to reproduce the issue, but serves as an example of practical use.

```php
protected function image(): Attribute
{
    return Attribute::make(
        get: fn (?string $value) => Storage::url($value ?? self::DEFAULT_IMAGE),
    );
}
```

2. Use the FileUpload component
```php
Forms\Components\FileUpload::make('image')
          ->visibility('public')
          ->directory('img/event')
          ->image()
          ->downloadable()
          ->openable(),
```

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/davmarek/filament-issue-fileupload

**Comment by danharrin** [comment]
I don't think this is really an issue with Filament, it expects that whatever string is saved is the same string that then gets returned back to the form from the model.

Filament does not know the difference between you doing this and a file that might be in a /storage directory **within** the filesystem.

Please rename the attribute getter to avoid the issue.
