### ISSUE TITLE
Bug with repeater state when using model eager loading by default

### ISSUE THREAD

**Issue by yuters** [laravel-filament/filament#13633]
### Package

filament/forms

### Package Version

v3.2.95

### Laravel Version

v11.1.4

### PHP Version

PHP 8.3.0

### Problem description

There's a strange issue with repeaters after saving a form when the model relationship for the repeater is [eager loaded by default](https://laravel.com/docs/11.x/eloquent-relationships#eager-loading-by-default).

When saving a new item on the repeater, it disappears from the front-end. When deleting a repeater item, it reappears after save. The underlying save/delete on the table is working as expected, this seems to be only an issue on the front-end.

Save multiple times without changing anything, and you can see it toggling back to its previous state.

### Expected behavior

The repeater item that was added or deleted should remain that way on the front-end after save.

### Steps to reproduce

1. Add the `protected $with` property with an eager loaded relationship to the parent model.
2. Create a repeater for the relationship using the `->relationship()` method
3. Add items on the repeater and save. (At this point, everything works fine)
4. Then add other items to the repeater and save again, they are then added to the database, but they disappear from the front-end
5. Save changes again, they reappear on the front-end, but gets deleted in the database.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/yuters/filament-repeater-bug

**Comment by fedenuche** [comment]
Hi guys, I think I have the same issue or something pretty similar. In my case when adding more than one item in the repeater,  only one is shown after saving. But the correct items aren't shown after deleting one and saving, I have to refresh the page to show all the items.

## Package Version

v3.2.140

## Laravel Version

v11.42.1

One detail I noticed is that when I save and only one item is showing if I inspect the source code, looks like it lost the record ID.

### Example withour ID:
![Image](https://github.com/user-attachments/assets/12b9abdd-a481-4537-8ee0-40199fcdf24c)

### Example with ID:
This is how it looks when I refresh the page and all the items are shown.
![Image](https://github.com/user-attachments/assets/cafa50d9-aa1a-4483-8699-d14c62d07fb1)

**Comment by yuters** [comment]
If you make a new issue with a reproducible repo, I'd be glad to take a look!

**Comment by fedenuche** [comment]
> If you make a new issue with a reproducible repo, I'd be glad to take a look!

Thanks @yuters I created this issue https://github.com/filamentphp/filament/issues/15766

Just let me know if I can help with anything else!
