### ISSUE TITLE
Simple Repeater with FileUpload

### ISSUE THREAD

**Issue by sglkc** [laravel-filament/filament#13636]
### Package

filament/filament

### Package Version

v3.2.95

### Laravel Version

v11.16.0

### Livewire Version

v3.5.4

### PHP Version

8.3.9

### Problem description

I wanted to make a multiple image upload, but `multiple()` alone consumes too much vertical space. So I tried to use a simple Repeater instead, since it returns an array of filenames.

Uploading works, but it's currently impossible (?) to view uploaded files in a Repeater using `simple()` in edit/view form. Tried to map the array before filling, error is the same as #12076 

### Expected behavior

Replacing `simple` with `schema` works as expected. 

![image](https://github.com/user-attachments/assets/8877076c-fcec-410f-ad27-d64cd85fed83)

### Steps to reproduce

1. Make a `Repeater->simple(FileUpload)`
2. Upload something
![image](https://github.com/user-attachments/assets/59d7711c-6fa5-42c7-ab7f-d5ce36c77b66)

3. Edit page opened and throws error
![image](https://github.com/user-attachments/assets/fc5642d9-a29c-4741-803c-13652dae1637)

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/sglkc/filament-issues/tree/fileupload-repeater

**Comment by petrisorcraciun** [comment]
[maybe it's helpful](https://filamentphp.com/docs/3.x/forms/fields/file-upload#displaying-files-in-a-grid ); use multiple and panelLayout

**Comment by danharrin** [comment]
Unfortunately, this component is not officially supported with the simple repeater due to its data storage mechanism. I suggest using the file upload with `multiple()` and (as above) a panel layout or grid or custom CSS.
