### ISSUE TITLE
Checkbox state sharing issue in dynamically generated CheckboxList

### ISSUE THREAD

**Issue by GregoireGaonach** [laravel-filament/filament#13669]
### Package

filament/filament

### Package Version

v3.2.95

### Laravel Version

v11.16.0

### Livewire Version

v3.5.4

### PHP Version

8.3.9

### Problem description

When a `CheckboxList' is automatically generated in a reactive way using a `$get()` parameter, all checkbox states are shared, i.e. when you click on one select item, all of them are selected. You can see the problem in action in the video below.

https://github.com/user-attachments/assets/e8c68ab2-c2e0-49a3-a03f-11d5b119112d

### Expected behavior

`CheckbloxList` checkboxes should be independent of each other.

### Steps to reproduce

Here is the minimum code to reproduce the unexpected behavior:

```php
Wizard::make([
    Wizard\Step::make("Step 1")
        ->schema([
            Select::make('user_id')
                ->options(
                    User::pluck('name', 'id')
                        ->toArray()
                )
                ->required()
                ->live(),
        ]),
    Wizard\Step::make("Step 2")
        ->schema(function (Get $get) {
            return Comment::query()
                ->where('user_id', $get('user_id'))
                ->get()
                ->groupBy('category')
                ->map(function ($comments, $category) {
                    return CheckboxList::make('comments-' . $category)
                        ->options($comments->pluck('content', 'id')->toArray());
                })->toArray();
        }),
]),
```

If the `CheckboxList` is not dynamically generated, then the `CheckboxList` will work as expected:

```php
Wizard\Step::make("Step 2")
    ->schema(Comment::query()
        ->where('user_id', auth()->id())
        ->get()
        ->groupBy('category')
        ->map(function ($comments, $category) {
            return CheckboxList::make('comments-' . $category)
                ->options($comments->pluck('content', 'id')->toArray());
        })->toArray()),
```

Looking at the HTML code, each checkbox appears to be independent, each `wire:key` is unique:
```php
wire:key="KjveNOLET1qV8SNhxs6z.data.comments-category-1.Filament\Forms\Components\CheckboxList.options.4"
```

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/CeriseGoutPelican/filament-issue

**Comment by ferremek** [comment]
I have the same issue, even when I use the sample code:
```
CheckboxList::make('technologies')
    ->options([
        'tailwind' => 'Tailwind CSS',
        'alpine' => 'Alpine.js',
        'laravel' => 'Laravel',
        'livewire' => 'Laravel Livewire',
    ])
```

There seems to be an issue when using this CheckboxList in a Livewire component. Because when I add this in a Resource then it works as expected.

**Comment by GregoireGaonach** [comment]
So we discussed the issue with toeknee on Discord, and it is likely not a bug, but probably related to the fact that all form elements need to be loaded on mount before being updated.

So a workaround would be to:
1. loop through all possible categories
2. create an empty and hidden checkbox list for each one
3. update and display the checkbox lists depending on the `getter`.

This should work well, unless the number of categories is important which is not ideal.

@ferremek : If you're using a checkbox list directly in Livewire, don't forget to add `$this->form->fill();` on mount and add the `public?array $data` as [described in the documentation](https://filamentphp.com/docs/3.x/forms/adding-a-form-to-a-livewire-component). This should fix it.

**Comment by ferremek** [comment]
@CeriseGoutPelican Wow, you're sharp! That fixed it for me!
