### ISSUE TITLE
Group Only Table results in table querying all records

### ISSUE THREAD

**Issue by sawirricardo** [laravel-filament/filament#13699]
### Package

filament/filament

### Package Version

v3.2.40

### Laravel Version

v11.17.0

### Livewire Version

v3.5.4

### PHP Version

PHP 8.3.9

### Problem description

The app timeout when accessing Orders menu

### Expected behavior

It should not query all records, at least not without limit

### Steps to reproduce

```
git clone https://github.com/sawirricardo/filafun
cd filafun
composer install
cp .env.example .env
php artisan migrate:fresh --seed
php artisan serve
```

- Go to https://127.0.0.1:8000/admin
- login as test@example.com password
- access menu orders

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/sawirricardo/filafun

**Comment by danharrin** [comment]
This is required to calculate summaries across records, we need to know what groups are available. The reason there is no limit is because it's impossible to get reliable numbers of groups when paginating, as some pages may only return 1 group.
