### ISSUE TITLE
Please Help me out with this last question, I want to display my table record based on a condition, apart of using filter, i can't find it in the documentation. For example, i want to display employee records where status = 1, i don't want to use filter, and tab to do that, how can i achieved it?

### ISSUE THREAD

**Issue by aldids01** [laravel-filament/filament#13710]
Please Help me out with this I want to display my table record based on a condition, apart of using filter, i can't find it in the documentation. For example, i want to display employee records where status = 1, i don't want to use filter, and tab to do that, how can i achieved it?

_Originally posted by @aldids01 in https://github.com/filamentphp/filament/discussions/13673#discussioncomment-10147663_

**Comment by Jonas-johansen** [comment]
You could modifiy the table base query.
```php
    public static function table(Table $table): Table
    {
        return $table
            ->modifyQueryUsing(fn ($query) => $query->where('status', 1))
```

**Comment by danharrin** [comment]
Please do not open bug reports for questions that already exist in Discussions. Again and we will block you from posting on the repo.

**Comment by aldids01** [comment]
> Please do not open bug reports for questions that already exist in Discussions. Again and we will block you from posting on the repo.

Okay Sir
