### ISSUE TITLE
Attach file button adds image url markdown instead of opening upload file dialogue

### ISSUE THREAD

**Issue by mokhosh** [laravel-filament/filament#1372]
### Package

filament/forms

### Package Version

v2.9.14

### Laravel Version

v8.81.0

### Livewire Version

v2.10.1

### PHP Version

php 8.1

### Bug description

I installed filament forms solely to use the image upload feature with the markdown editor without having to go through creating my own component. But the markdown field doesn't seem to support file upload. It just adds `![](url)` when you try to upload a file.

**Comment by danharrin** [comment]
Hey, this isn't actually a "bug" as it was the intended behaviour when we created the component. You should be able to drag and drop images onto the textarea to upload them though, right?

That being said, I would accept a PR that opens an upload dialog when you click the button :)

**Comment by mokhosh** [comment]
@danharrin ok then not a bug, just inconsistent with the trix component and tat bit confusing at first.

**Comment by danharrin** [comment]
Yeah I totally understand. It makes sense to open a dialog when that button is clicked.
