### ISSUE TITLE
only sidebar is showing

### ISSUE THREAD

**Issue by maverik23** [laravel-filament/filament#13746]
### Package

filament/filament

### Package Version

3.2

### Laravel Version

11

### Livewire Version

3

### PHP Version

8.2.3

### Problem description

When a panel is created, it does not show the navbar or the dashboard, it seems to be defined as opacity-0

<img width="1699" alt="Captura de pantalla 2024-07-30 a la(s) 9 38 11" src="https://github.com/user-attachments/assets/b103dfa4-64d1-4ca3-836a-1a55ec579b29">

### Expected behavior

be able to visualize and interact with the elements correctly

### Steps to reproduce

```
composer require filament/filament 
artisan filament:install --panels
```

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/filamentphp/filament

**Comment by swen4** [comment]
@maverik23 
Just found a possible cause for this, since I had the same issue:

In `config/livewire.php` make sure `inject_assets` is set to true.

**Comment by maverik23** [comment]
> @maverik23 Just found a possible cause for this, since I had the same issue:
> 
> In `config/livewire.php` make sure `inject_assets` is set to true.

!yup problem solved

Thank you
