### ISSUE TITLE
DatePicker with Min and Max focus Chosen/Current month

### ISSUE THREAD

**Issue by dharen008** [laravel-filament/filament#13750]
### Package

filament/filament

### Package Version

3.1

### Laravel Version

11

### Livewire Version

3

### PHP Version

8.2

### Problem description

if the DatePicker is like this

now() = March

DatePicker::make( 'date' )
->minDate( April )
->maxDate( December )

If you click on the date field, the focus month will be minDate, not the current month.

### Expected behavior

If possible, we should have an option to choose which month to focus on when clicking the date field or any function that will not force the user to focus on the minDate.

### Steps to reproduce

have additional feature to set the focus date when click

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/dharen008/Vendors.git

**Comment by zepfietje** [comment]
Invalid reproduction repository.

**Comment by dharen008** [comment]
Hi @zepfietje,

I've provided the info above

"if the DatePicker is like this

now() = March

DatePicker::make( 'date' )
->minDate( April )
->maxDate( December )

If you click on the date field, the focus month will be minDate, not the current month."
