### ISSUE TITLE
unsavedChangesAlerts() do not include the view/infolist

### ISSUE THREAD

**Issue by dharen008** [laravel-filament/filament#13766]
### Package

filament/filament

### Package Version

3.1

### Laravel Version

11

### Livewire Version

3

### PHP Version

8.2

### Problem description

Even though nothing is being updated, this still occurs: [https://app.screencast.com/06hEAEkreBfhN](url)

After clicking the view button, do not close the modal and then refresh it. The unsavedChangesAlerts() function also affects the view/infolist.

### Expected behavior

According to the documentation, only the create and edit actions should use this function. and it should not affect the view/infolist

### Steps to reproduce

remove the unsavedChangesAlerts() function on view/infolist

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/dharen008/Vendors.git

**Comment by zepfietje** [comment]
Invalid reproduction repository.
