### ISSUE TITLE
problem in Accessing the Main Form elements from the createOptionForm

### ISSUE THREAD

**Issue by KareemHussen** [laravel-filament/filament#13787]
### Package

filament/filament

### Package Version

v3.0

### Laravel Version

v11.0

### Livewire Version

v3

### PHP Version

PHP v8.2

### Problem description

Can't access the main form elements while im inside the options of the select inside the createOptionForm

### Expected behavior

expected that the user_id will be a valid number

### Steps to reproduce

            Forms\Components\Select::make('user_id')
            ->label('Client')
            ->options(function (callable $get) {
                $users = User::role('Client')->get()->pluck('name', 'id');
                return $users ?? [] ;
            })
            ->required(),

           
            Forms\Components\Card::make("Destination Information")
                ->schema([
                    
                    Forms\Components\Grid::make(2)
                        ->schema([
                            Forms\Components\Select::make('from_area')
                                ->label('From Area')
                                ->reactive()
                                ->live()
                                ->options(function (Get $get , callable $set) {
                                    Log::info("area ".$get('user_id'));
                                    $cityId = $get('from_city');
                                    $user_id = $get('user_id');
                                    if ($cityId && $user_id) {
                                        return Destination::where('user_id', $user_id)
                                            ->when($get('to_area'), fn($q) => $q->where('to_area', $get('to_area')))
                                            ->whereNotNull('price')
                                            ->whereHas('fromArea', function($q) use ($cityId) {
                                                $q->where('city_id', $cityId);
                                            })
                                            ->with('fromArea')
                                            ->get()
                                            ->pluck('fromArea.name', 'fromArea.id')
                                            ->toArray();
                                    }
                                    return [];
                                })
                                ->searchable()
                                ->createOptionForm([
                                    Forms\Components\Select::make('city_id')
                                        ->label('City')
                                        ->reactive()
                                        ->live()
                                        ->options(function (Get $get) {
                                            dd($get('user_id'));
                                            $get('user_id') ? $cites = City::where('user_id', $get('user_id'))->pluck('name', 'id') : $cites = [];
                                            return $cites ?? [] ;
                                        })
                                        ->required(),
                                    Forms\Components\TextInput::make('name')
                                        ->label('Area Name')
                                        ->required(),
                                ])
                                ->createOptionUsing(function ($data , Get $get) {
                                    return Area::create($data)->id;
                                })
                                ->required(),

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/aliteleb/filament-select-issue.git

**Comment by rvzug** [comment]
I've seen similar recently, fixed it by using ```->createOptionForm``` not with an array, but with a closure and passing the $get of the parent to that create-form:

```php
// ... FormField with name id here ...
 ->createOptionForm(
      function(Get $get) {
          $company_id = $get('id');  // state of parent item is now available as $company_id in the following array

              return [
                  Hidden::make('company_id')
                      ->label('Company')
                      ->required()
                      ->live()
                      ->default(function use ($company_id) { return $company_id; }),
                  Forms\Components\TextInput::make('street_line_1')
                      ->label('Straatnaam')
                      ->required()
                      ->maxLength(255),
// ...
```

I also thought and tried the ```$get('../../company_id')```, but that does not work (and is not intended to work that way)

**Comment by zepfietje** [comment]
You should indeed pass a closure in this case, using `Get $get` from the create option form since that's a separate action with its own form.
