### ISSUE TITLE
Upgrade Choices.js to v11

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#13829]
Seems like Choices.js is no longer dead! 🥳
https://github.com/Choices-js/Choices/pull/1166

**Comment by zepfietje** [comment]
@danharrin @awcodes @pxlrbt @ryangjchandler, in case any of you were working on a custom select component; seems like Choices.js will be properly maintained again! 🙌

**Comment by zepfietje** [comment]
Choices.js v11 has just been released! Are we able to upgrade to that version in v3, or would that be a breaking change, @danharrin? Might fix a lot of the issues we have with that library.

**Comment by danharrin** [comment]
Let's do it in v4 only just in case

**Comment by zepfietje** [comment]
Sure.

**Comment by zepfietje** [comment]
Just had a call with @caturria.
The Choices.js select field is very inaccessible to people using screen readers.
Basically every time you'd interact with the field via keyboard users would expect to open the select results by pressing the arrow down key. As a result of a Choices.js bug, "arrow down" is entered into the select search input.

We should reconsider upgrading to the latest major version of Choices.js if possible without breaking changes.

**Comment by danharrin** [comment]
#15178
