### ISSUE TITLE
File Upload Error for Files Larger Than 2MB

### ISSUE THREAD

**Issue by SKSritharan** [laravel-filament/filament#13858]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

v11.9

### Livewire Version

v3.0

### PHP Version

PHP 8.3

### Problem description

When attempting to upload a file larger than 2MB using the file upload feature in Filament PHP, an error is encountered. This issue has been observed both in personal implementations and on the Filament demo site, specifically in the product create form.

### Expected behavior

Files larger than 2MB should upload successfully without any errors.

![image](https://github.com/user-attachments/assets/16fa5ac0-6c44-44b1-91da-5e7dad087f5e)

### Steps to reproduce

1. Go to the product create form on the Filament demo site or a similar form in a personal Filament implementation.
2. Attempt to upload a file larger than 2MB using the file upload feature.
3. Observe the error message or failed upload process.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/filamentphp/demo

**Comment by xtreme2020** [comment]
Did you check your php.ini configuration?
Look for 
-- Maximum allowed size for uploaded files.
upload_max_filesize = 60M 

--Must be greater than or equal to upload_max_filesize
post_max_size = 60M

Here a tutorial on how to locate your current php ini file
[https://codewithsusan.com/notes/php-configs-with-php-ini](https://codewithsusan.com/notes/php-configs-with-php-ini)
After update those values remember restart NGINX or Apache services.
