### ISSUE TITLE
HTML Descriptions are incorrectly converted to entities when using a CheckboxList with Enums

### ISSUE THREAD

**Issue by atmediauk** [laravel-filament/filament#13860]
### Package

filament/forms

### Package Version

v3.2.97

### Laravel Version

v11.20.0

### PHP Version

PHP 8.3.9

### Problem description

When adding a CheckboxList with an Enum class, specifically with HTML descriptions, the descriptions are incorrectly converted to html entities despite using ```HtmlString()```

- Example screenshot: https://jmp.sh/4kAh6or4 
- Related Docs: https://filamentphp.com/docs/3.x/support/enums#using-the-enum-description-with-form-field-descriptions

### Expected behavior

I expected the HTML strings to be rendered as functioning markup.

### Steps to reproduce

To reproduce simply add a Checkboxlist with enum descriptions that contain html. See reproduction repo for example.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/atmediauk/filament-checkboxlist

**Comment by danharrin** [comment]
`public function getDescription(): ?string` has a return type of `string` which will cast the `HtmlString` into a `string` which causes the HTML not to render.

The solution here is for us to add `Htmlable` to the interface, but investigation needs to be made to assess if this is a breaking change or not.

**Comment by danharrin** [comment]
Done in v4 in #15120
