### ISSUE TITLE
A UI bug in Wizard forms, when the number of tabs is many in mobile mode

### ISSUE THREAD

**Issue by hamidroohani** [laravel-filament/filament#13870]
### Package

filament/filament

### Package Version

V3.2

### Laravel Version

V11.0.0

### Livewire Version

V3.0

### PHP Version

PHP 8.3

### Problem description

there is a UI bug in Wizard forms, when the number of tabs is many. and user must scroll a lot to see the form

![Screenshot 2024-08-08 at 10 25 16](https://github.com/user-attachments/assets/3ba59296-187f-40b2-a09c-6c896f8662cf)

### Expected behavior

It would be better if it had a `max-width` and `scroll`

### Steps to reproduce

Just create a Wizard form and put lots of steps in the wizard and change the screen to the `responsive-mode`

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/hamidroohani/filament-issue.git

**Comment by zepfietje** [comment]
This isn't a bug as it's designed to work this way.
It's basically impossible for us to account for all uses of the wizard as some people prefer scrolling while others don't.
Feel free to make adjustments for your own project using CSS.
