### ISSUE TITLE
Broken sticky topbar in `v4.x`

### ISSUE THREAD

**Issue by MartijnCuppens** [laravel-filament/filament#13881]
### Package

filament/filament

### Package Version

v4.x

### Laravel Version

v11.20.0

### PHP Version

PHP 8.3.0

### Problem description

This only occurs in `v4`. The livewire component `packages/panels/resources/views/livewire/topbar.blade.php` wraps a `<div>` around the topbar. This breaks the sticky behaviour.

### Expected behavior

Topbar should sticky to the top.

### Steps to reproduce

You'll see it when your page is long enough and you scroll:

https://github.com/user-attachments/assets/308703b4-41ec-4fa5-87fa-2b21f299792a

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/MartijnCuppens/filament

**Comment by danharrin** [comment]
ac9c31039b1fe7a03cc4091c5cea154ea46de709
