### ISSUE TITLE
DeleteAction within ActionGroup resulting in fatal error in unit test

### ISSUE THREAD

**Issue by BradnDodd** [laravel-filament/filament#13899]
### Package

filament/filament

### Package Version

3.2.40

### Laravel Version

11.20.0

### Livewire Version

3.5.4

### PHP Version

8.3

### Problem description

When testing a DeleteAction within an ActionGroup it produces the following errors; 

```
Failed asserting that a table action with name [delete] exists on the [App\Livewire\ListPosts] component.
Failed asserting that null is an instance of class Filament\Tables\Actions\Action.
```

When debugging through it appears that the `flatActions` variable against the Action group stores some of the actions with a capitalised name but when testing its searching for an entirely lowercase name thus producing the above errors  

### Expected behavior

A successful result on a unit test for a delete action

### Steps to reproduce

Checkout this reproduction repo , composer install then run php artisan test. There is a single unit test there that should reproduce the bug 

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/BradnDodd/filament-bug/

### Relevant log output

```shell
Failed asserting that a table action with name [delete] exists on the [App\Livewire\ListPosts] component.
Failed asserting that null is an instance of class Filament\Tables\Actions\Action.
```

**Comment by BradnDodd** [comment]
https://github.com/filamentphp/filament/pull/13900 Fix for this bug here. From clicking around the UI this seems to still work on the interface and also fixes my unit test issue.

**Comment by danharrin** [comment]
https://github.com/filamentphp/filament/pull/13900#issuecomment-2283800832
