### ISSUE TITLE
Tenancy does not work when Guest access is set in Filament

### ISSUE THREAD

**Issue by akshit-arora** [laravel-filament/filament#13907]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

11.20.0

### Livewire Version

v3.5

### PHP Version

PHP 8.2

### Problem description

If the filament has been set to access without user authentication, i.e. the guest access, enabling the tenancy gives an error.

```
Filament\FilamentManager::getUserDefaultTenant(): Argument #1 ($user) must be of type Filament\Models\Contracts\HasTenants|Illuminate\Database\Eloquent\Model|Illuminate\Contracts\Auth\Authenticatable, null given, called in D:\laravel\filament-guest-tenant-issue\vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php on line 357
```

Tenancy is expecting a logged in user.

### Expected behavior

The tenancy should not be dependent on the user authentication. User authentication can be disabled and guest access can be set from the AdminPanelProvider. The tenancy should work in both the cases.

### Steps to reproduce

Set up the guest access in Filament as described in the docs [here](https://filamentphp.com/docs/3.x/panels/users#setting-up-guest-access-to-a-panel)

Apply tenancy in the Panel configuration

```
use App\Models\Team;
use Filament\Panel;
 
public function panel(Panel $panel): Panel
{
    return $panel
        // ...
        ->tenant(Team::class);
}
```

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/akshit-arora/filament-guest-tenancy-issue

**Comment by danharrin** [comment]
Closing as not supported as per https://github.com/filamentphp/filament/pull/13908#issuecomment-2284467526
