### ISSUE TITLE
Upgrade filament v2 to v3 didnt work

### ISSUE THREAD

**Issue by PauloFelipeM** [laravel-filament/filament#13931]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

PHP 8.2

### Problem description

Hello all, I'm trying to upgrade my filament version to 3 but it didnt work, I tried the automatically upgrade, it changed a lot of stuff in my code, but at the composer update process I got this:

  Access level to Filament\Forms\Concerns\InteractsWithForms::getFormStatePath() must be public (as in class Filament\Resources\Pages\ViewRecord)

I fixed other errors like that, but, this error is happening inside the filament package, I not sure how to fixed it

![image](https://github.com/user-attachments/assets/4185a6a2-f3b3-4834-a9ef-3bb705f39729)

my composer.json:

{
    "name": "laravel/laravel",
    "type": "project",
    "description": "The Laravel Framework.",
    "keywords": ["framework", "laravel"],
    "license": "MIT",
    "require": {
        "php": "^8.2",
        "ext-iconv": "*",
        "devaslanphp/filament-avatar": "@stable",
        "doctrine/dbal": "^3.5",
        "dutchcodingcompany/filament-socialite": "@stable",
        "filament/filament": "^3.2",
        "filament/spatie-laravel-media-library-plugin": "^3.2",
        "filament/spatie-laravel-settings-plugin": "^3.2",
        "guava/filament-icon-picker": "@stable",
        "guzzlehttp/guzzle": "^7.2",
        "jeffgreco13/filament-breezy": "@stable",
        "laravel/framework": "^10.10",
        "laravel/sanctum": "^3.3",
        "laravel/tinker": "^2.8",
        "league/flysystem-aws-s3-v3": "~3.12",
        "league/oauth2-client": "^2.6",
        "maatwebsite/excel": "^3.1",
        "owenvoke/blade-fontawesome": "^2.1",
        "protonemedia/laravel-verify-new-email": "^1.6",
        "psr/simple-cache": "^1.0",
        "pusher/pusher-php-server": "^7.2",
        "spatie/laravel-permission": "^5.5",
        "stichoza/google-translate-php": "^4.1"
    },
    "require-dev": {
        "fakerphp/faker": "^1.9.1",
        "kkomelin/laravel-translatable-string-exporter": "^1.17",
        "laravel/pint": "^1.0",
        "laravel/sail": "^1.18",
        "mockery/mockery": "^1.4.4",
        "nunomaduro/collision": "^7.0",
        "phpunit/phpunit": "^10.1",
        "spatie/laravel-ignition": "^2.0"
    },
    "autoload": {
        "psr-4": {
            "App\\": "app/",
            "Database\\Factories\\": "database/factories/",
            "Database\\Seeders\\": "database/seeders/"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "Tests\\": "tests/"
        }
    },
    "scripts": {
        "install-project-win": [
            "npm install",
            "composer install",
            "npm run build",
            "composer dump-autoload",
            "copy .env.example .env",
            "@php artisan key:generate",
            "@php artisan migrate",
            "@php artisan db:seed"
        ],
        "install-project": [
            "npm install",
            "composer install",
            "npm run build",
            "composer dump-autoload",
            "cp .env.example .env",
            "@php artisan key:generate",
            "@php artisan migrate",
            "@php artisan db:seed"
        ],
        "post-autoload-dump": [
            "Illuminate\\Foundation\\ComposerScripts::postAutoloadDump",
            "@php artisan package:discover --ansi"
        ],
        "post-update-cmd": [
            "@php artisan vendor:publish --tag=laravel-assets --ansi --force",
            "@php artisan filament:upgrade"
        ],
        "post-root-package-install": [
            "@php -r \"file_exists('.env') || copy('.env.example', '.env');\""
        ],
        "post-create-project-cmd": [
            "@php artisan key:generate --ansi"
        ]
    },
    "extra": {
        "laravel": {
            "dont-discover": []
        }
    },
    "config": {
        "optimize-autoloader": true,
        "preferred-install": "dist",
        "sort-packages": true,
        "allow-plugins": {
            "pestphp/pest-plugin": true
        }
    },
    "minimum-stability": "stable",
    "prefer-stable": true
}

### Expected behavior

to upgrade the version

### Steps to reproduce

Tried to upgrade the filament version 2 to 3

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/devaslanphp/project-management

**Comment by malzariey** [comment]
I belive that you overridden the default ```getFormStatePath()``` in on of your ListPages.

You just need to match the function signiture.
