### ISSUE TITLE
Searchable select gets 'meta' as search input when you unfocus the page

### ISSUE THREAD

**Issue by Danoctum** [laravel-filament/filament#13966]
### Package

filament/filament

### Package Version

v3.2.92

### Laravel Version

v10.48.15

### Livewire Version

v3.5.2

### PHP Version

PHP 8.2.19

### Problem description

When I make a component like this:
`
                                    Forms\Components\Select::make('test')
                                        ->searchable()
                                        ->options(['test' => 'test'])`

And when I open the dropdown, type nothing, and go to another application (using alt + tab or cmd + tab for example) the search fields gets 'meta' as an input.

### Expected behavior

I'd expect the searchfield to stay empty.

### Steps to reproduce

- Create a form with the select component that is searchable in a modem. (it's important that it's the first focused item you get when you hit tab)
- Hit tab + command
- See that the dropdown opens and the search field has 'meta' in it.
- Doing it again and again will keep appending 'meta'
<img width="421" alt="image" src="https://github.com/user-attachments/assets/9b94bf3e-23fa-4545-b891-98ca7d667f01">

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/filamentphp/demo

**Comment by danharrin** [comment]
I think #13829 would fix this
