### ISSUE TITLE
Docs improvement: collapsible method needs parameter in form section

### ISSUE THREAD

**Issue by bhupindersingh007** [laravel-filament/filament#1397]
### Package

filament/filament

### Package Version

v1.9

### Laravel Version

v8.40

### PHP Version

PHP 7.4

### Bug description

Error occured, if no parameter is supplied to collapsible() method in form section ( specified in log output )

Docs : https://filamentadmin.com/docs/1.x/admin/forms#section ( parameter is no given in docs)

But, collapsible method works when have parameter like true.

### Steps to reproduce
use collapsible method without any parameter

_No response_

### Relevant log output

```shell
ArgumentCountError
Too few arguments to function Filament\Forms\Components\Section::collapsible(), 0 passed in F:\playground\projects\laravel-filament\app\Filament\Resources\CustomerResource.php on line 39 and exactly 1 expected

public function collapsible($collapsible)

    {

        $this->configure(function () use ($collapsible) {

            $this->collapsible = $collapsible;

        });

        return $this;

    }


```

**Comment by danharrin** [comment]
Hey, I am not actively working on v1 anymore, but would welcome any PRs to solve issues you are having.
