### ISSUE TITLE
unsavedChangesAlerts() on Simple (modal) resources

### ISSUE THREAD

**Issue by dharen008** [laravel-filament/filament#13990]
### Package

filament/filament

### Package Version

3.1

### Laravel Version

11

### Livewire Version

3

### PHP Version

8.2

### Problem description

This issue occurs only with Simple (modal) resources.

1. The unsavedChangesAlerts() should only appear if new data has been entered. Currently, it shows even when no new data is added.
2. On the View/infolist page, unsavedChangesAlerts() still appears if you reload or refresh the page.

### Expected behavior

Expected Behavior for Simple (Modal) Resources

1. Triggering unsavedChangesAlerts():
- The unsavedChangesAlerts() function should only be triggered when there is a new or unsaved change in the data.
- If no data has been added, modified, or removed, the alert should not appear.

2. Behavior After Clicking the Button Without Closing the Modal:
- If a user clicks the button but does not close the modal and then refreshes the page, the unsavedChangesAlerts() should not activate unless there are actual unsaved changes.

2. Behavior on View/Infolist Pages:
- When viewing or refreshing the View/infolist pages, unsavedChangesAlerts() should not be displayed, as these actions should not imply any unsaved changes.

This behavior ensures that users are only alerted when there is a legitimate risk of losing unsaved data, avoiding unnecessary warnings.

### Steps to reproduce

Try it on my holiday Simple (modal) resources.

The problem happens after clicking the button, but not closing the modal. If you then refresh the page, the unsavedChangesAlerts() function triggers, even though no changes have been made. This can be seen here: [https://app.screencast.com/06hEAEkreBfhN](https://github.com/filamentphp/filament/issues/url).

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/dharen008/demo

**Comment by danharrin** [comment]
Hi, we chose the behaviour of always showing the alert if a modal is open to simplify the implementation, and also remind the user that they were part way through an operation while leaving. I don't have any plans to change this implementation at the moment due to the complexity involved otherwise, but let me know if you have any ideas about how to solve simply in a PR.

**Comment by dharen008** [comment]
@danharrin how about on Problem 2?

https://app.screencast.com/06hEAEkreBfhN?conversation=qccfLJFXI8fHiyjPaNgdBy

Problem Description:
On the View/infolist page, unsavedChangesAlerts() still appears if you reload or refresh the page.

Behavior:
Behavior on View/Infolist Pages:
When viewing or refreshing the View/infolist pages, unsavedChangesAlerts() should not be displayed, as these actions should not imply any unsaved changes.
