### ISSUE TITLE
Prebuilt Actions - Global Settings is not working

### ISSUE THREAD

**Issue by dharen008** [laravel-filament/filament#14003]
### Package

filament/filament

### Package Version

3.1

### Laravel Version

11

### Livewire Version

3

### PHP Version

8.2

### Problem description

There are a few functions that are not working in the global settings within the AppServiceProvider boot method.

We tested it on the following actions: DeleteAction, RestoreAction, ForceDeleteAction, AttachAction, DetachAction, DeleteBulkAction, RestoreBulkAction, and ForceDeleteBulkAction. None of these actions are functioning as expected, and there may be other functions that are also not working.

This is just one example. For more examples of other Prebuilt Actions, you can check my demo repository.

DeleteAction::configureUsing( function ( DeleteAction $deleteAction ): void {
            $deleteAction
                ->successNotificationTitle( 'Custom Title' )
                ->successNotification( fn () => dump( 'Custom Notification' ) )
                ->modalHeading( 'Custom heading' )
                ->modalDescription( 'Custom description' );
        } );

### Expected behavior

Global settings for Prebuilt Actions should be working as expected. Please check other functions as well, beyond those I've provided in my demo repository.

### Steps to reproduce

Check my demo repository in AppServiceProvider and try the Prebuilt Actions on the Country resource. They will not work as expected.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/dharen008/demo

**Comment by danharrin** [comment]
try `isImportant: true` on the `configureUsing()` to override what happens in the `setUp()` method

**Comment by dharen008** [comment]
Thanks @danharrin! This works! Hopefully, there will be documentation about this in the panel builder in the future.

I'm curious about the $during function. Would it be possible to provide an example of how to use it?

```
Actions\DetachAction::configureUsing( function ( DetachAction $detachAction ): void {
	$detachAction
		->modalHeading( 'Custom heading' )
		->modalDescription( 'Custom description' );
}, null, true );
```

**Comment by danharrin** [comment]
it applies the configurations only for the duration of the function, and then reverts them

**Comment by dharen008** [comment]
Noted, ill just try to figure it out how it works, anyway many thanks for the help! good job on filament by the way!
