### ISSUE TITLE
After updating to v3.2.107 issue

### ISSUE THREAD

**Issue by dharen008** [laravel-filament/filament#14029]
### Package

filament/filament

### Package Version

3.1

### Laravel Version

11

### Livewire Version

3

### PHP Version

8.2

### Problem description

1. After updating to v3.2.107, the ->bulkActions() overwrite for the belongsToMany pivot table has an error.

![image](https://github.com/user-attachments/assets/4f0e5e11-1f89-4281-ab87-fbbb2eaa0482)

2. We also noticed in the new version that when pressing the attach button, the select dropdown automatically focuses and displays the options.

### Expected behavior

it should overwrite the parent bulkAction arrays

### Steps to reproduce

1. Go to my demo repository view two files UserResource.php and ManagesRelationManager.php

ManagesRelationManager.php bulkActions should overwrite UserResource.php bulkActions

2. Pressing the attach button, the select dropdown automatically focuses and displays the options.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/dharen008/demo

**Comment by hsul4n** [comment]
Same issue

**Comment by danharrin** [comment]
Fixed by #14049 in the next release

**Comment by dharen008** [comment]
I confirm that issue #1 is fixed in #14049,

but is issue #2 still not fixed, or is it supposed to be like that now?

Thank you @danharrin for fixing it!

#2 issue reported above
"We also noticed in the new version that when pressing the attach button, the select dropdown automatically focuses and displays the options."

**Comment by danharrin** [comment]
I don't see anything that could cause that, but also I don't think it's the end of the world. It could be focus trapping. What was the previous version you upgraded from? Could you investigate which PR caused it?

**Comment by dharen008** [comment]
Yes your correct, We can ignore it for now, but it would be nice to fix it if your team have time after taking care of the more important tasks. Thanks again for quickly resolving the issue.
