### ISSUE TITLE
Select options not clickable when options array goes from empty to populated

### ISSUE THREAD

**Issue by AlexJames-Dev** [laravel-filament/filament#1416]
### Package

filament/filament

### Package Version

v2.9.16

### Laravel Version

v8.81.0

### Livewire Version

v2.10.1

### PHP Version

8.1.1

### Bug description

When populating a selection options list by using a callable $get from a dependant select, if the select array begins out as an empty array, once the dependant select is chosen, the options cannot be clicked on from the dropdown.

https://user-images.githubusercontent.com/43570309/151969289-bcef9c8e-782f-4116-afef-ad2ca58f18f4.mov

```php
Select::make('college_id')
            ->label('College')
            ->searchable()
            ->options(College::all()->pluck('name', 'id')->toArray())
            ->reactive()
            ->afterStateUpdated(fn (callable $set) => $set('course_id', null))
            ->required(),

Select::make('course_id')
          ->label('Course')
          ->searchable()
          ->options(function (callable $get){
              $college = College::find($get('college_id'));

              if (! $college)
              {
                  return [];
              }

              return $college->courses->pluck('name', 'id')->toArray();
          })
          ->helperText("Select a College first")
          ->required(),

```

**Comment by ManojKiranAppathurai** [comment]
Related to #1182

**Comment by danharrin** [comment]
https://github.com/laravel-filament/filament/issues/1182#issuecomment-1019463355

**Comment by danharrin** [comment]
As per #1951, I've found a solution. You may now have dynamic, dependant `options()`, with full search support :)
