### ISSUE TITLE
Dashboard Retains Filters Even After Refresh or URL Reset

### ISSUE THREAD

**Issue by naowas** [laravel-filament/filament#14180]
### Package

filament/filament

### Package Version

v3.0

### Laravel Version

v10.0.0

### Livewire Version

v3

### PHP Version

8.2

### Problem description

I added some filters to my Dashboard, but when I reload the page, the data remains filtered. Even after I clear the query parameters from the URL and revisit the dashboard, the filtered data is still displayed. 

This issue is also present in the filament demo.

### Expected behavior

After refreshing the page or removing the query parameters from the URL, the dashboard should display unfiltered data, reverting to its default state.

### Steps to reproduce

Visit [Filament PHP Demo](https://demo.filamentphp.com/).

Apply a filter to the data in the dashboard.
Then, either:
Revisit the dashboard by clicking on it from the sidebar, or
Remove all query parameters from the URL and press Enter.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/filamentphp/demo

**Comment by danielh-official** [comment]
I do know that there is a [persist filters in session functionality](https://filamentphp.com/docs/3.x/tables/filters/getting-started#persist-filters-in-session) for tables. My first thought for this would be that this functionality was applied to Dashboard Filters by default without the ability to turn it off.

A fix, that's consistent with table design, would be to disable it by default and then add a `persistFiltersInSession` method to the `filtersForm` method (see: https://filamentphp.com/docs/3.x/panels/dashboard#filtering-widget-data).

**Comment by naowas** [comment]
> I do know that there is a [persist filters in session functionality](https://filamentphp.com/docs/3.x/tables/filters/getting-started#persist-filters-in-session) for tables. My first thought for this would be that this functionality was applied to Dashboard Filters by default without the ability to turn it off.
> 
> A fix, that's consistent with table design, would be to disable it by default and then add a `persistFiltersInSession` method to the `filtersForm` method (see: https://filamentphp.com/docs/3.x/panels/dashboard#filtering-widget-data).

It worked. Thanks

**Comment by colincameron** [comment]
@danielh-official can you clarify your fix? I have the same issue, but there is no `persistFiltersInSession` method when defining a form in the `filtersForm` method.

There also doesn't appear to be a way to disable filter persistence by default like you suggest.

**EDIT:** never mind, I realised I needed to override the function persistsFiltersInSession() on my dashboard class, as defined in the HasFilters trait. My searching had only shown up the identically-named function on the Table class.

**Comment by Pawel-IT** [comment]
Same issue here a clarification and a note in the docs would be nice.

**Comment by Pawel-IT** [comment]
Would it make sense to reopen this issue? I see that it was added to the roadmap as a bug but I no longer see it on the roadmap. Am I just not seeing it?

**Comment by Pawel-IT** [comment]
I did figure it out, but would be nice if you could chain this like you can with table filters:

Add this to your dashboard page:

```    
public function persistsFiltersInSession(): bool
    {
        return false;
    }
```

Also, if you want to add a reset action to your dashboard page:

```
   protected function getHeaderActions(): array
    {
        return [
            Action::make('clearAllFilters')
                ->label('Clear All Filters')
                ->action(function () {
                    $this->reset();
                }),
        ];
}
```

That seems to have fixed it for me.

**Comment by joshembling** [comment]
As above, if you are using this in a ViewPage e.g. an Infolist, you must use 

```php
public function persistsFiltersInSession(): bool
    {
        return false;
    }
```
