### ISSUE TITLE
While adding single Card to StatsOverviewWidget card is displayed to full page size

### ISSUE THREAD

**Issue by ManojKiranAppathurai** [laravel-filament/filament#1421]
### Package

filament/filament

### Package Version

v2.9.8

### Laravel Version

v8.80.0

### PHP Version

8.1.1

### Bug description

While adding a single Card on `Filament\Widgets\StatsOverviewWidget` it displays the card for entire page length in PC

![image](https://user-images.githubusercontent.com/30294553/152106541-02ef11e7-f49b-4295-ab6c-7bb581759f89.png)

### Steps to reproduce

Add the widgets class
```
<?php

namespace App\Filament\Widgets;

use Filament\Widgets\StatsOverviewWidget as BaseWidget;
use Filament\Widgets\StatsOverviewWidget\Card;

class UserCountWidget extends BaseWidget
{
    public static function canView(): bool
    {
        return true;
    }

    protected function getCards(): array
    {

        return [
            Card::make('Unique views', '10'),
        ];
    }
}

```

**Comment by danharrin** [comment]
Yeah, this is deliberate. The cards adapt to fill the space they are given. Stats overview widgets span the full width by default, you can change this to only 1 column maybe.

**Comment by ChrisHardie** [comment]
For what it's worth, I tried setting `$columnSpan = 1` on a Stats overview widget and it indeed narrows the width of all the cards to one column, but then they don't wrap/float into a grid as one might expect, so you end up scrolling through them. The demo implies that there's a way to have cards take up a smaller width and wrap around each other automatically, but it's not clear how to do that from the docs.

**Comment by danharrin** [comment]
I'd need a screenshot to be able to see what's happening and what you want to achieve instead

**Comment by ChrisHardie** [comment]
@danharrin here are a few showing the desktop view and a smaller responsive view. This is with `$columnSpan = 1`. In both cases, the hope would be to have the width of the stat card be wide enough to hold the content at its current size but narrow enough to allow for multiple cards per row.

<img width="1439" alt="Screen Shot 2022-03-22 at 10 43 42" src="https://user-images.githubusercontent.com/311772/159508987-0b41072a-5281-4332-ae16-3233049ee9d2.png">
<img width="571" alt="Screen Shot 2022-03-22 at 10 44 20" src="https://user-images.githubusercontent.com/311772/159508997-52bc920f-f96d-43eb-ba5a-0ea72a0071ca.png">

It seems likely I'm just not finding the right syntax. Thanks for any guidance you can offer.

**Comment by danharrin** [comment]
How about overriding `getColumns()` to return 4.
