### ISSUE TITLE
modifyQueryUsing() causes query issue in FilamentPHP Select component and fails to select the correct element when editing records

### ISSUE THREAD

**Issue by orodrigue12** [laravel-filament/filament#14289]
### Package

filament/filament

### Package Version

3.2

### Laravel Version

11.9

### Livewire Version

3.4

### PHP Version

8.2

### Problem description

I am experiencing an issue with the modifyQueryUsing() method in the FilamentPHP Select component. The problem occurs when editing a record — the query does not select the correct element that should be pre-selected in the dropdown for editing.

The issue occurs when I try to load the form for editing an existing record. The Select component either fails to load the correct options or doesn't select the right element as it should during record editing.

The issue arose because the query didn't handle selecting the correct element for editing when $state was provided. Here's the code I had to do to get it fixed, which I hope is a good option:

![Capture d’écran du 2024-09-18 20-14-16](https://github.com/user-attachments/assets/566c42de-3e2b-429b-9822-17e7fb36b731)

### Expected behavior

The correct element should be pre-selected in the Select dropdown when editing a record, based on the current value.

### Steps to reproduce

Implement a Select field in a FilamentPHP form and use modifyQueryUsing() to modify the query dynamically.

Edit an existing record with a pre-selected value for the Select field.

The dropdown does not show the correct pre-selected option, or the form fails to load properly.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/filamentphp/demo

**Comment by danharrin** [comment]
I do not believe the code is present in the demo repository, please do not cut corners if you would like us to review the bug report ourselves.
