### ISSUE TITLE
Plugin + cache crashes the website

### ISSUE THREAD

**Issue by mark-sdb** [laravel-filament/filament#14297]
### Package

filament/filament

### Package Version

v3.2.113

### Laravel Version

v11.23.5

### Livewire Version

v3.5.6

### PHP Version

8.3.9

### Problem description

When running `php artisan filament:optimize` my website cannot load, the admin panel cached file contains a __set_state that doesnt exist.

I think it may be related to a plugin:

Excerpt from /bootstrap/cache/filamen/panels/admin.php
```php
...
  array (
    0 => 
    \Filament\Widgets\WidgetConfiguration::__set_state(array(
       'widget' => 'Nicepants\\FilamentReleaseNotes\\Widgets\\ReleaseNotesWidget',
       'properties' => 
      array (
      ),
    )),
    1 => 'Filament\\Widgets\\AccountWidget',
  ),
...
```

If i change this to:

```php
...
  array (
    0 => 'Nicepants\\FilamentReleaseNotes\\Widgets\\ReleaseNotesWidget',
    1 => 'Filament\\Widgets\\AccountWidget',
  ),
...
```

The site works with cache enabled.

This is the location where the plugin defines the offending widget:

https://github.com/mark-nicepants/filament-release-notes/blob/2bff8ef79e21389fd40e9e9decf63be4823e238d/src/FilamentReleaseNotesPlugin.php#L71

(Im also the package creator so if I need to change the package, please let me know)

### Expected behavior

No crash op app open :-)

### Steps to reproduce

- Clone the repo
- Run `php artisan filament:optimize`
- See cache admin panel php file line 60 for offending __set_state

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/mark-nicepants/filament-cache-issue

**Comment by danharrin** [comment]
You cannot register widgets with `make()` in the panel/plugin, only on pages and in resources. Replacing the `::make()` with `::class` should resolve, but let me know if not.

**Comment by mark-sdb** [comment]
Thanks, this was the problem :-)
