### ISSUE TITLE
Admin panel issue on production

### ISSUE THREAD

**Issue by abhijeetpandeyOO7** [laravel-filament/filament#14313]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

v11.9

### PHP Version

8.3

### Problem description

not able to step up production-ready site , admin is not working

### Expected behavior

after login 403, and once the user model is updated still issue persist with 500 error

### Steps to reproduce

fresh setup laravel and filament , create user and try login

### Reproduction repository (issue will be closed if this is not valid)

na

**Comment by parmonov98** [comment]
https://task.devdata.uz/admin

admin@domain.uz  :  12345678
