### ISSUE TITLE
Upgrade CodeMirror to v6

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#14356]

**Comment by thethunderturner** [comment]
I would like to give this a try.. however for the Markdown component which uses [EasyMDE](https://github.com/Ionaru/easy-markdown-editor/blob/master/package.json), it only supports codemirror v5.

How do you suggest we move forward from this? @danharrin @zepfietje

**Comment by danharrin** [comment]
Thanks, unsure what this ticket is asking then.
