### ISSUE TITLE
Upgrade Chart.js to v4

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#14354]

**Comment by zepfietje** [comment]
Reopening this issue since #14979 does not properly upgrade Chart.js.
There are breaking changes documented in the [migration gruide](https://www.chartjs.org/docs/latest/migration/v4-migration.html) that apply to the use of Chart.js in Filament.

**Comment by thethunderturner** [comment]
> Reopening this issue since #14979 does not properly upgrade Chart.js. There are breaking changes documented in the [migration gruide](https://www.chartjs.org/docs/latest/migration/v4-migration.html) that apply to the use of Chart.js in Filament.

Do you know what breaks exactly? Then I can push a fix for it

**Comment by danharrin** [comment]
Look like very minimal changes f2db998e1879e80553c74b3b56e6ec43d275c8eb
