### ISSUE TITLE
Import action does not work

### ISSUE THREAD

**Issue by koti42** [laravel-filament/filament#14364]
### Package

filament/filament

### Package Version

v3.2.114

### Laravel Version

V10.10

### PHP Version

PHP 8.1

### Problem description

When I try to use the import function, I get an error that there is no such function.

https://github.com/user-attachments/assets/90c8cf11-2a4d-4eba-92a2-b68b0f95c3e4

### Expected behavior

It has to work without error.

### Steps to reproduce

It has to work without error.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/koti42/e-ticaret

**Comment by danharrin** [comment]
You are using the wrong `ImportAction` namespace, it needs to be from `Filament\Tables\Actions`

**Comment by koti42** [comment]
oh thank you. Can I use this in headerAction?

**Comment by danharrin** [comment]
Yes
