### ISSUE TITLE
Multi Guard

### ISSUE THREAD

**Issue by DanielCodeWeb** [laravel-filament/filament#14389]
### Package

filament/filament

### Package Version

3.2

### Laravel Version

11

### Livewire Version

3.5

### PHP Version

8.3.0

### Problem description

Hello,

I am encountering an issue in my Laravel project where I have two separate authentication systems — one for regular users and one for administrators via the Filament admin panel. Both use the same database, and it seems that the sessions are overlapping.

Problem description:

### Expected behavior

Example 1: When the administrator logs out of the admin panel, the current user session on the main site is also terminated.

The administrator is authenticated via the admin guard, and the user is authenticated via the web guard.
After the admin logs out, the regular user is also logged out from their session on the main site.
Example 2: When the user logs out from the main site, the administrator is also logged out of the admin panel.

### Steps to reproduce

The user logs in through the web guard, and the admin logs in through the admin guard.
When the user logs out, the admin session is also terminated, although they should function independently.
Suspected cause: It seems that both systems are sharing the same session or cookie, causing a conflict. I have attempted to configure separate guards for users and admins, but the sessions still overlap.

I would appreciate assistance in properly configuring the system so that logging out from one session (admin or user) does not affect the other.

Thank you in advance for your help!

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/DanielCodeWeb/FOTPROGLARAVEL3

**Comment by danharrin** [comment]
I think this is the default Laravel behaviour when invalidating the session and I am not aware of any fixes, sorry.

**Comment by channor** [comment]
I encountered the same issue while trying to separate user sessions between different panels in my Filament app.

What worked for me was using separate subdomains for each guard. For example:

* `admin.filament.local` for the `admin` guard
* `filament.local` for the `users` guard

This ensures each guard uses a different session domain, which prevents session overlap between guards.

In `config/app.php`:

```php
return [
    'domain' => env('APP_DOMAIN', 'filament.local'),
];
```

In `CompanyPanelProvider`:

```php
$panel->domain(config('app.domain'));
```

In `AdminPanelProvider`:

```php
$panel->domain('admin.' . config('app.domain'));
```

Setting the domain on Laravel routes follows the same principle: it ensures each guard operates on a separate session domain, avoiding conflicts.
