### ISSUE TITLE
Richeditor Does not work in SliderOver and Markdown Does not work in Modals

### ISSUE THREAD

**Issue by sohailahmad07** [laravel-filament/filament#14394]
### Package

filament/filament

### Package Version

3.2.115

### Laravel Version

11.25.0

### Livewire Version

3.5.6

### PHP Version

8.3

### Problem description

Hi 

when you open a rich editor in a slide-over you can not add an image. it will show the image for a second but then it will disappear how every it works fine in a modal and it own page

Similarly, the markdown editor does not show in a modal but works correctly in Slideover and it own page  

here a video (Rich editor in slideover)
[Screencast from 2024-09-30 15-11-30.webm](https://github.com/user-attachments/assets/271431ea-f9eb-4e7b-99bf-86f2b17b5971)

Here image of Markdown in modal
![Screenshot 2024-09-30 at 15-21-33 Users - Laravel](https://github.com/user-attachments/assets/c2dcabfe-b6f7-4579-b0b2-7e0b03b05ed3)

### Expected behavior

It should show the image and it should not disappear and in the case of markdown is should sho the markdown

## Step To Reproduces
- Install a New Laravel Project 
- Install Filament Panels
- Create a filament Resource
- Remove the Create Page and Edit page so it opens in a modal & slide over respectively 
- Add RichEditor & Markdown to a Form 
- Add A `->sliderOver()` to create form
- you will see the image can not be uploaded to a rich editor in Create Slideover
- and the Markdown editor will not be accessible in the edit Modal

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/sohailahmad07/filament-editors-bug

**Comment by sohailahmad07** [comment]
An update on the issue 

**Rich Editor**

The rich editor image upload does not work because of the Grammarly extension but if you add these attributes to Trix editor tag

data-gramm="false"
data-gramm_editor="false"
data-enable-grammarly="false"

it should disable Grammarly

the I tried using `extra attribute` to add these but It does not work if i add the manually but publish view that i work but i don't think that is recommended

**Comment by zepfietje** [comment]
Fixed by https://github.com/filamentphp/filament/pull/14416.
