### ISSUE TITLE
Issue with login while I am using laravel-mongo for using mongodb as my database

### ISSUE THREAD

**Issue by gannusravan** [laravel-filament/filament#14398]
### Package

filament/filament

### Package Version

V3

### Laravel Version

11

### PHP Version

8.2

### Problem description

I am facing issue with filament and mongodb I am using laravel-mongodb for using mongodb as my database I have successfully runned my migrations and created filament user also but I am facing problem which login to the panel here is a screenshot of my issue and I tried alot to get the solution but I have not found any answer for this issue.
![17277087278566988607312664715063](https://github.com/user-attachments/assets/bad9d1f8-89d3-4bd2-ac38-b681b309824d)

if anyone solved this problem please guide me to resolve this issue thanks in advance

### Expected behavior

Expected to login to the filament dashboard or return login credentials not found errors 

### Steps to reproduce

I think we need to upgrade the filament user authentication code to address this issue. Still I am working on the issue and trying to contribute to the filament if I found any thing I will update.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/gannusravan/crm.wisecredence.com.git

**Comment by danharrin** [comment]
Hi, apologies but we do not support non-standard database drivers in Filament. These are MySQL, Postgres, SQLite and MSSQL.

**Comment by gannusravan** [comment]
Ok thanks

**Comment by sneakylenny** [comment]
To be able to use Mongo, you should change the cache driver to something other than database. This is a Laravel issue, not a Filament issue.

Source:
https://github.com/filamentphp/filament/discussions/13692#discussioncomment-10797589

Extra, don't forget to extend Mongo's model:
https://github.com/mongodb/laravel-mongodb/issues/1706
