### ISSUE TITLE
Select value does not update

### ISSUE THREAD

**Issue by danharrin** [laravel-filament/filament#14420]
Open modal with searchable select, then switch record, value does not change

**Comment by yogesh16** [comment]
@danharrin I can make PR on this.
Can you please provide me more information?

**Comment by danielgnh** [comment]
@danharrin 
> Open modal with searchable select, then switch record, value does not change

`Select, DateTimePicker, DatePicker, TimePicker` fields 
with `->native(false), ->searchable()` parameters **can't be filled** with data passed into the `$this->form->fill()`
