### ISSUE TITLE
Bug-report project does not run out-of-the-box

### ISSUE THREAD

**Issue by MarkKremer** [laravel-filament/filament#14505]
### Package

Other

### Package Version

newest

### Laravel Version

^11.9

### PHP Version

^8.2

### Problem description

When creating a bug report on Github (https://github.com/filamentphp/filament/issues/new), I'm given the following example project to base my reproduction on: https://filament-issue.unitedbycode.com/
This project does not work out-of-the-box even though the page states that it does and it could also be more user-friendly.

### Expected behavior

A list of things I ran into while setting-up the project:
1. The page states that the only requirement is to run `php artisan serve`. That is not the case. I also had to run:
    - `php artisan key:generate`
    - `composer install`?
    - `php artisan migrate`
    - `php artisan db:seed` or something else to create a user.
2. The `composer.json` doesn't contain filament as a dependency, even though it's present in the `vendor` directory.
3. The user that is pre-filled in the login form (`App\Filament\Pages\Auth`) does not match the seeded user.
4. `App\Providers\Filament\AdminPanelProvider` isn't registered.
5. http://127.0.0.1:8000/ shows the default Laravel app. This could redirect to the login form so I don't have to search for routes (which I couldn't find using `php artisan route:list` because they weren't registered).
6. The README.md is the default Laravel README so it didn't help me with any of the above.

### Steps to reproduce

1. Create a bug report on https://github.com/filamentphp/filament/issues/new/choose.
2. Click the link under "Reproduction repository" (https://filament-issue.unitedbycode.com/).
3. Download and unzip the project.
4. Run the project using `php artisan serve`.
5. Go to http://127.0.0.1:8000/
6. See that it doesn't work out-of-the-box.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/MarkKremer/filament-pr-2

**Comment by danharrin** [comment]
cc @ijpatricio

**Comment by ijpatricio** [comment]
Thanks for the heads up, I'll fix it and report back here.

**Comment by ijpatricio** [comment]
@danharrin All is done, including proper instructions, and readiness for 4.x

https://unitedbycode.com/filament-issue

Old link https://filament-issue.unitedbycode.com/ still works (on the same project), but the redirect removes the path (Astro)
I'll see if I can fix.
I'm prioritizing E2E tests on the produced ZIP. (unzip, serve, be able to go into the dashboard)
And then screenshots on 4.x.
