### ISSUE TITLE
FileUpload flashes without css then displays fully

### ISSUE THREAD

**Issue by VuongPham2001** [laravel-filament/filament#14522]
### Package

filament/filament

### Package Version

v3.2.100

### Laravel Version

v10.48.20

### PHP Version

PHP 8.1

### Problem description

When I click on CreateAction to open FileUpload, it flashes for about 1 second without css and then it displays with css.
![image](https://github.com/user-attachments/assets/d6b6d25f-a1b5-4871-907e-0e92df36f3dd)
![image](https://github.com/user-attachments/assets/44426539-6dba-40fb-83c8-2a2d8d59a4d0)

### Expected behavior

when I click on CreateAction to open FileUpload it has to open the full Upload form and no blinking is allowed
![image](https://github.com/user-attachments/assets/0ddac77d-0fcc-4590-ae2f-1ceddc0bdb98)

### Steps to reproduce

 /**
     * @param Form $form
     * @return Form
     */
    public function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\FileUpload::make('attachment')
                    ->required()
                    ->preserveFilenames()
                    ->disk('s3')
                    ->directory($this->getStorageDirectory())
                    ->visibility('public')
                    ->maxSize(51200)
                    ->live(onBlur: true)
                    ->afterStateUpdated(function ($state, callable $set) {
                        if ($state) {
                            $fileName = pathinfo($state->getClientOriginalName(), PATHINFO_FILENAME);
                            $set('name', $fileName);
                            $set('file_type', $state->getMimeType());
                            $set('file_path', $this->getStorageDirectory() . '/' . $state->getClientOriginalName());
                        }
                    }),
                Forms\Components\Hidden::make('name'),
                Forms\Components\Hidden::make('file_type'),
                Forms\Components\Hidden::make('file_path'),
            ])->columns(1);
    }

    /**
     * @param Table $table
     * @return Table
     */
    public function table(Table $table): Table
    {
        return $table
            ->recordTitleAttribute('name')
            ->paginated(false)
            ->recordAction(null)
            ->columns([
                Tables\Columns\TextColumn::make('name'),
                Tables\Columns\TextColumn::make('file_type'),
            ])
            ->filters([
                //
            ])
            ->headerActions([
                Tables\Actions\CreateAction::make()
                    ->label('Upload files')
                    ->icon('heroicon-m-arrow-up-tray')
                    ->createAnother(false)
                    ->modalWidth(MaxWidth::TwoExtraLarge)
                    ->modalHeading('Upload files')
                    ->modalSubmitActionLabel('Upload')
                    ->mutateFormDataUsing(function (array $data): array {
                        $data['candidate_id'] = $this->ownerRecord->id;
                        return $data;
                    })
                    ->action(function ($data) {
                        $this->ownerRecord->files()->create($data);

                        Notification::make()
                            ->title('File uploaded successfully')
                            ->success()
                            ->send();
                    }),
            ])

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/filamentphp/filament

**Comment by juanalvarezPro** [comment]
@VuongPham2001 Hello, how were you able to resolve the bug?
