### ISSUE TITLE
Laravel 11.28.0 breaks multi-select searchable dropdowns

### ISSUE THREAD

**Issue by GabrielSieben** [laravel-filament/filament#14528]
### Package

filament/filament

### Package Version

v3.2.117

### Laravel Version

v11.28.0

### Livewire Version

v3.5.4

### PHP Version

PHP 8.3.12

### Problem description

Hello,

Laravel 11.28.0 causes searchable, multiple-select dropdowns to never return any results.

<img width="296" alt="image" src="https://github.com/user-attachments/assets/35d7ffa4-55af-4d31-a0c3-c3045cd7fafe">

There is an error in the browser console as well. In my testing, this error also occurs on Filament v3.2.100 and v3.2.96 if paired with Laravel v11.28.0.

<img width="602" alt="image" src="https://github.com/user-attachments/assets/5fbf10fc-5cea-4c6d-aad6-a62b23034941">

Merely downgrading Laravel to v11.27.2 in Composer fixes this issue. An example:

```
Select::make('groups')
    ->multiple()
    ->hintIcon('heroicon-o-rectangle-group')
    ->relationship('groups', 'name', function (Builder $query) {
        return $query->whereHas('course', function ($query): void {
            $query->where('courses.id', $this->section->course_id);
        });
    })
    ->searchable(),
```

### Expected behavior

Search results appear.

### Steps to reproduce

Upgrade a project to Laravel v11.28.0; use a multiple-select dropdown.

### Reproduction repository (issue will be closed if this is not valid)

I'm not taking another several hours of my day to build an easily demonstrable issue like this; if it was more complex, then yes.

### Relevant log output

Uncaught (in promise) TypeError: Cannot read properties of null (reading 'concat')
    at Proxy.getChoices (select.js?v=3.2.117.0:1:95896)
    at async Proxy.refreshChoices (select.js?v=3.2.117.0:1:95538)
    at async Proxy.init (select.js?v=3.2.117.0:1:94100)

**Comment by GabrielSieben** [comment]
I'm perfectly content with leaving this here; it will affect other people, it will get found, and the requirement to clone and build a repo for obvious stuff like this, is not reasonable, especially when the provided demo project doesn't even work.

**Comment by matthewmnewman** [comment]
You're right, and this issue doesn't only affect the multi-select box but also impacts the navigation and various components that use .map and .includes. Even a fresh Laravel installation with a basic Filament panel shows the same problem. I’ve locked deployments for several applications to Laravel version 11.27.2 until this is fixed.

**Comment by pertsenga** [comment]
I just encountered the exact issue. Searchable select filters are suddenly not working because of the same error. Any fix?
![Screenshot 2024-10-16 at 6 20 39 PM](https://github.com/user-attachments/assets/99372a83-ad74-437b-971c-536ff2b4c9c5)

Edit: I just downgraded Laravel to v11.27.2 and it worked

**Comment by saulens22** [comment]
Here's reproduction with Filament Demo repository: https://github.com/saulens22/filament-demo/tree/laravel-11.28-bug 

Every `Select` that is `searchable()` or `multiple()` breaks with Laravel 11.28

**Comment by zenepay** [comment]
I got this issues when using select in Repeater
