### ISSUE TITLE
Brand Logo instructions are not updated in docs

### ISSUE THREAD

**Issue by elnva** [laravel-filament/filament#14546]
### Package

filament/filament

### Package Version

v3.0.0

### Laravel Version

11

### PHP Version

8.2.0

### Problem description

In this link https://filamentphp.com/docs/2.x/admin/appearance#changing-the-brand-logo is suggested, in order to change brand logo, one should create resources/views/vendor/filament/components/brand.blade.php file. However in docs/15-upgrade-guide.md in Logo Customization section it is stated that:

    In v2, you can customize the logo of the admin panel using a `/resources/views/vendor/filament/components/brand.blade.php` file. In v3, this has been moved to the new `brandLogo()` API. You can now [set the brand logo](themes#adding-a-logo) by adding it to your panel configuration.

### Expected behavior

Correct documentation to change the logo. 

### Steps to reproduce

Create  resources/views/vendor/filament/components/brand.blade.php file and it has no effect on logo. Probably one should call brandLogo method on panel as suggested by migration docs/

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/elnva/filament-issue

**Comment by hizmarck** [comment]
I think that 's the v2 of filamentphp, but there's a new doc for the v3

https://filamentphp.com/docs/3.x/panels/themes#adding-a-logo
