### ISSUE TITLE
Form Tab layout with columns options should not render section component on full span

### ISSUE THREAD

**Issue by theanadimukt** [laravel-filament/filament#14557]
### Package

filament/forms

### Package Version

V3.0.0

### Laravel Version

v11.27.2

### Livewire Version

v3.0.0

### PHP Version

PHP 8.2.0

### Problem description

As per stated on Filament documentation [Form - Tabs layout - Using Grid Columns Within A Tab](https://filamentphp.com/docs/3.x/forms/layout/tabs#using-grid-columns-within-a-tab), component inside tabs should display in numbers of given columns .

However when put Section component inside tab with 3 columns option, it doesn't work as expected, instead it renders section in full span. There should have three columns of three section, but it's rendering three rows.

```
Tabs::make('Tabs')
    ->tabs([
        Tabs\Tab::make('Tab 1')
            ->schema([
                Section::make('Sunday')
                ->schema([
                    //
                ]),
            Section::make('Monday')
                ->schema([
                    //
                ]),
            Section::make('Tuesday')
                ->schema([
                    //
                ]),
            ])
            ->columns(3),
        // ...
    ])
```

Please check below screenshot 

<img width="1161" alt="Screenshot 2024-10-16 at 23 12 56" src="https://github.com/user-attachments/assets/62662634-65a2-4aab-ab49-27dc34ec984f">

### Expected behavior

Expected rendering should be something like below

<img width="1161" alt="Screenshot 2024-10-16 at 23 21 32" src="https://github.com/user-attachments/assets/5345fc50-2b07-4aed-bdfb-733d14dcdd73">

### Steps to reproduce

1. Create resource
2. Add below scripts to your form method

```
Tabs::make('Tabs')
    ->tabs([
        Tabs\Tab::make('Tab 1')
            ->schema([
                Section::make('Sunday')
                ->schema([
                    //
                ]),
            Section::make('Monday')
                ->schema([
                    //
                ]),
            Section::make('Tuesday')
                ->schema([
                    //
                ]),
            ])
            ->columns(3),
        // ...
    ])
```

3. go to panel UI
4. Click on resource menu
5. Click on New and check tab 

Alternatively, 
1. checkout reproduction repository
2. login to admin panel
3. go to Business resource menu
4. click on new
5. There you will see tab with section rows

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/theanadimukt/filament-tab-issue

**Comment by gheorghelupu17** [comment]
Hi @theanadimukt  in the set up of section component you have $this->columnSpan('full'); This is the reason
<img width="423" alt="Screenshot 2024-10-18 at 01 19 00" src="https://github.com/user-attachments/assets/c3b4f8b4-bd77-489f-af8f-0a836b66dcf5">
It's easier to set the columnSpan to 1
```
Tabs::make('Tabs')`
    ->tabs([
        Tabs\Tab::make('Tab 1')
            ->schema([
                Section::make('Sunday')
                 ->columnSpan(1)
                ->schema([
                    //
                ]),
            Section::make('Monday')
                 ->columnSpan(1)
                ->schema([
                    //
                ]),
            Section::make('Tuesday')
               ->columnSpan(1)
                ->schema([
                    //
                ]),
            ])
            ->columns(3),
        // ...
    ])
```

**Comment by danharrin** [comment]
Yeah, just an API stylistic choice that usually you want Sections to be full width so that is the default

**Comment by theanadimukt** [comment]
Thanks for quick response @gheorghelupu17 
@danharrin and @team Thank you for creating such an awesome package ❤️
