### ISSUE TITLE
Fileupload issue with @filamentScripts

### ISSUE THREAD

**Issue by mokhosh** [laravel-filament/filament#14563]
### Package

filament/filament

### Package Version

v3.2.119

### Laravel Version

v11.28.1

### PHP Version

8.3.12

### Problem description

If you have `FileUpload` in a form on a Livewire component, and you add `@filamentScripts` you will get this JS error:

```
TypeError: Cannot read properties of null (reading 'insertBefore')
```

If you remove `@filamentScripts` everything works perfectly.

### Expected behavior

I assumed it would be the other way around. Meaning things should not work without `@filamentScripts` and should work perfectly with it.

### Steps to reproduce

1. Add a form to a Livewire component
2. Add a FileUpload to your form
3. Add `@filamentScripts` to the view

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/mokhosh/filament-upload-bug

### Relevant log output

```shell
file-upload.js?v=3.2.119.0:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertBefore')
    at Ca (file-upload.js?v=3.2.119.0:1:9468)
    at Object.replaceElement (file-upload.js?v=3.2.119.0:2:73201)
    at Wd (file-upload.js?v=3.2.119.0:2:74830)
    at Hd (file-upload.js?v=3.2.119.0:2:74871)
    at ut (file-upload.js?v=3.2.119.0:2:77076)
    at Proxy.init (file-upload.js?v=3.2.119.0:40:95660)
```

**Comment by nathanjansen** [comment]
I experienced the same problem. Removing @filamentScripts from the view fixes it for me, it is already in the layout.

**Comment by zepfietje** [comment]
As @nathanjansen said above, the scripts are already loaded in the layout.
