### ISSUE TITLE
Fix Dropdown Width in Table When 'ActionGroup' Actions Are Buttons

### ISSUE THREAD

**Issue by A909M** [laravel-filament/filament#14625]
### Package

filament/filament

### Package Version

v3.2.120

### Laravel Version

11.29.0

### Livewire Version

v3.5.12

### PHP Version

8.3.12

### Problem description

![width dorp down ActionGroup when actions is Button](https://github.com/user-attachments/assets/c07e2ab7-fed6-40de-99bb-9dbfb496dd1a)

I encountered a layout issue in the Filament Tables component when using `ActionGroup `with button-style actions. The dropdown width does not adjust correctly, leading to display problems. The solution could be to implement a conditional check to dynamically set the dropdown width.

-  If the `ActionGroup `uses button-style actions, the `w-auto` class should be applied to adjust the width automatically.
- If buttons are not used, the default` w-screen` class should remain, ensuring the dropdown stretches across the screen.

Here’s an example of how I’m defining the **`ActionGroup`**:
```
ActionGroup::make([
    Tables\Actions\EditAction::make()->button(),
    Tables\Actions\ViewAction::make()->button(),
])
```

### Expected behavior

- When using button-style actions, the dropdown width should be adjusted using the w-auto class to ensure it adapts to the content size.
- When not using buttons, the default behavior (w-screen) should be applied, allowing the dropdown to stretch across the screen.

Possible Fix: In the `filament\support\resources\views\components\dropdown\index.blade.php` file, apply a conditional check:

If the `ActionGroup` contains button-style actions, apply [w-auto](url).
If not, apply `w-screen` by default.

### Steps to reproduce

1. Define an `ActionGroup `with button-style actions in a Filament table.
2. Load the table and open the dropdown.
3. Notice that the dropdown width is not optimal when button actions are used.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/A909M/filament-dropdown-issue

**Comment by danharrin** [comment]
Groups are essentially dropdowns, so they need to use the dropdown item view. There isn't currently a way to make them buttons and aligned horizontally, and I'm not interested in doing this right now. Thanks for reporting though.
