### ISSUE TITLE
Instructions to compile extra Tailwind classes

### ISSUE THREAD

**Issue by patrick-leb** [laravel-filament/filament#14632]
The only bit of info i could find was here:
https://filamentphp.com/docs/3.x/tables/advanced#custom-row-classes

however, this was not enough in my case. I had add this to my AppServiceProvider as well:

```php
    public function boot(): void
    {
        FilamentAsset::register([
            Css::make('app-css',Vite::asset('resources/css/app.css')),
            Js::make('app-js',Vite::asset('resources/css/app.js')),
        ]);
    }
```

I think its probably worth its own section too :) 

EDIT:
I just realized that this bricks artisan commands if you don't run `npm run build` first to have the manifest.json generated. This is probably not the best option.

**Comment by zepfietje** [comment]
Please check the following docs: https://filamentphp.com/docs/3.x/panels/themes#creating-a-custom-theme.

**Comment by patrick-leb** [comment]
Respectfully, I'm not looking at creating a new theme, I simply need a way to add a couple of tailwind classes here and there.

**Comment by zepfietje** [comment]
"Theme" might sound like a lot more, but essentially it's a compiled stylesheet.
A theme is in fact what you should use to achieve your goal.

**Comment by maltebaer** [comment]
hey @patrick-leb to fix your issue, simply wrap the asset register in a check for the existence of the build manifest. like so

```php
public function boot(): void
{
    if (file_exists(public_path('build/manifest.json'))) {
        FilamentAsset::register([
            Css::make('app-css', Vite::asset('resources/css/app.css')),
        ]);
    }
}
```

however, i guess it's better to use @zepfietje approach by creating a custom theme, in order to avoid loading unnecessary and potentially conflicting styles into the panel.
