### ISSUE TITLE
Modal JS conflict in RelationManagers

### ISSUE THREAD

**Issue by gregoryloichot** [laravel-filament/filament#14700]
### Package

filament/tables

### Package Version

v3.2.122

### Laravel Version

v11.30

### PHP Version

PHP 8.2

### Problem description

Let's say we have a relation manager with a custom column. In this column, we want to add a button that opens a modal window.
This works when there are no actions in the relation manager (it is possible to open the modal window). If there are actions present (in Edit mode, for example) in the relation manager, then the modal window contained in the custom column no longer works.

If this Title Custom column is added in a table (not a relation manager), it works as expected (even in Edit mode).

### Expected behavior

The modal window should open under all circumstances.

### Steps to reproduce

1. Clone the project.
2. Go to `/admin/articles/1` (View Mode) -> Click on buttons "Comment 1" and "Comment 2" : a modal is opened.
3. Go to `/admin/articles/1/edit` (View Mode) -> Click on buttons "Comment 1" and "Comment 2" : nothing happens.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/gregoryloichot/filament-modal-issue

### Relevant log output

```shell
In edit mode, JS errors in the browser:

Alpine Expression Error: isOpen is not defined
Expression: "isOpen"
<div x-cloak="" x-show="isOpen">

Alpine Expression Error: isOpen is not defined
Expression: "isOpen"
<div class="fi-modal-close-overlay f…/50 dark:bg-gray-950/75" aria-hidden="true" x-show="isOpen" x-transition.duration.300ms.opacity="">

Uncaught ReferenceError: isOpen is not defined
```

**Comment by wpalani** [comment]
I'm facing a similar issue, have you found a solution to yours?

**Comment by gregoryloichot** [comment]
> I'm facing a similar issue, have you found a solution to yours?

Hi,

I don't… I've reorganized my UI to avoid this situation, but I hope a solution to be found; this is only a workaround for me.

**Comment by sunnymarco** [comment]
Darn, i ran into the same thing just now using a custom column. In my app, my custom column exists in both the Resource List view and in a Relational Manager of that resource. When using my custom column alongside other actions, specifically the Edit action, my custom column breaks :[ (only in the Relational Manager context). My work around will be to create a new Action that has all the same content that the Edit action has and not use the out-of-the-box Edit action for now.

**Comment by danharrin** [comment]
Since Filament does not support nesting modals here, I would suggest using column action modals - https://filamentphp.com/docs/3.x/tables/columns/getting-started#action-modals
