### ISSUE TITLE
Correcting Kurdish language locale code

### ISSUE THREAD

**Issue by swara-mohammed** [laravel-filament/filament#1477]
### Package

filament/filament

### Package Version

v2.0.0

### Laravel Version

v8.0

### PHP Version

php 8.0

### Bug description

Please change the Kurdish language (Sorani) that added with short code (ku) to this project with (ckb) because this is a correct locale code.

**Comment by danharrin** [comment]
Sorry, not sure what you mean. What exactly should I rename and what should it be?

**Comment by swara-mohammed** [comment]
One of the languages of translation is Kurdish (sorani). The language code is (ku) but the correct is (ckb).

![Bildschirmfoto 2022-02-06 um 22 42 53](https://user-images.githubusercontent.com/9349190/152702803-7e3cdf29-9783-4d65-9d29-beb3af788a09.png)

from wikipedia:
![Bildschirmfoto 2022-02-06 um 22 51 11](https://user-images.githubusercontent.com/9349190/152702843-3b46620e-aba5-4afb-8a54-94593a250203.png)

**Comment by danharrin** [comment]
As far as I know, Laravel uses ISO 639-1 codes and not ISO 639-3.

You can see the differences here - https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
