### ISSUE TITLE
Viewing FileUpload get CORS at Google Chrome

### ISSUE THREAD

**Issue by jeegaje** [laravel-filament/filament#14793]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

PHP 8.2

### Problem description

I try to edit The file I have uploaded using  FileUpload. At local it works fine but in production i got CORS only at Google Chrome, I try at Mozilla it works fine
![image](https://github.com/user-attachments/assets/45dfd60b-9ff7-448c-974e-b9b1c768105a)

### Expected behavior

at Mozilla it works fine
![Screenshot 2024-11-14 122742](https://github.com/user-attachments/assets/3516977b-b6d5-4fb1-b9cc-6bdde06bc3e6)

### Steps to reproduce

`Group::make()
    ->relationship('maintenancePumpData')
    ->schema([
        Forms\Components\TextInput::make('number_of_inspection')
            ->label('Pemeriksaan')
            ->readOnly()
            ->disabled(function (Model $record) {
                return $record->status == 'approved';
            }),
        Forms\Components\TextInput::make('running_hours_total')
            ->label('Running Hours Total')
            ->disabled(function (Model $record) {
                return $record->status == 'approved';
            }),
        Forms\Components\FileUpload::make('running_hours_total_image')
            ->label('Running Hours Total Documentation')
            ->directory('maintenance/data-pump')
            ->image()
            ->openable()
            ->downloadable()
            ->disabled(function (Model $record) {
                return $record->status == 'approved';
            }),
        Forms\Components\TextInput::make('running_hours_monthly')
            ->label('Running Hours Bulanan')
            ->disabled(function (Model $record) {
                return $record->status == 'approved';
            }),
        Forms\Components\FileUpload::make('running_hours_monthly_image')
            ->label('Running Hours Bulanan Documentation')
            ->directory('maintenance/data-pump')
            ->image()
            ->openable()
            ->downloadable()
            ->disabled(function (Model $record) {
                return $record->status == 'approved';
            }),
    ])`
    
 This is the code that i use

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/jeegaje/dex

**Comment by danharrin** [comment]
No reproduction, and this is very environment specific so that bit is important
