### ISSUE TITLE
Custom ViewField with livewire component with table prevents form from saving

### ISSUE THREAD

**Issue by MarcelWeidum** [laravel-filament/filament#14806]
### Package

filament/filament

### Package Version

v3.2.124

### Laravel Version

v11.31.0

### Livewire Version

v3.5.12

### PHP Version

PHP 8.3.13

### Problem description

When a form has a `ViewField` with a view that renders a livewire component which `HasTable` the form can't be saved.

https://github.com/user-attachments/assets/45adaec4-9372-4636-8048-12e27fe1ae64

### Expected behavior

The form should be saved

### Steps to reproduce

1. Make resource
2. Make livewire component with table
3. Load the livewire component in resource `ViewField`
4. Form doesn't save

Reproduction repository:
https://github.com/MarcelWeidum/fila-custom-table-in-form

On the reproduction repository create a post, on edit it loads the table in the second tab

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/MarcelWeidum/fila-custom-table-in-form

**Comment by danharrin** [comment]
It is not possible to embed tables in forms, since the table includes a modal form, and HTML does not allow `<form>` elements to be nested within each other.
