### ISSUE TITLE
`filament()->getCurrentPanel()` always returns a panel, even outside Filament

### ISSUE THREAD

**Issue by austincarpenter** [laravel-filament/filament#14840]
### Package

filament/filament

### Package Version

v3

### Laravel Version

v11

### Livewire Version

v3

### PHP Version

PHP 8.3

### Problem description

When serving a response outside of Filament, `filament()->getCurrentPanel()` returns the default panel.

I reuse form schemas between Filament routes and public routes and would like to add conditional code to tweak various parameters.

I'd question whether these lines are needed in `PanelRegistry`:
https://github.com/filamentphp/filament/blob/085ba5449421a6cba81deee7bf52c626785cad59/packages/panels/src/PanelRegistry.php#L21-L32

To me the default panel is not necessarily the current panel.

Happy to provide a PR if needed.

### Expected behavior

I would expect this return `null` when not in a Filament context, especially considering the return type of the method is `?Panel`.

### Steps to reproduce

Execute 

```php
filament()->getCurrentPanel()
```

when not in a request served by Filament.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/filamentphp/demo

**Comment by zepfietje** [comment]
I agree this is confusing and I would personally expect the same behavior as you described, @austincarpenter.

This is related to what we discussed the other day, @danharrin.

**Comment by danharrin** [comment]
Breaking so implemented in v4 #15137
