### ISSUE TITLE
Livewire encountered corrupt data when trying to hydrate the [app.filament.resources.ad.ad-resource.pages.edit-ad] component

### ISSUE THREAD

**Issue by farhad321** [laravel-filament/filament#1485]
### Package

filament/filament

### Package Version

 v2.7.15

### Laravel Version

v8.77.1

### Livewire Version

v2.8.2

### PHP Version

8.0.3

### Bug description

https://flareapp.io/share/VmeXyjy5

when adding a new ad to the site make this problem.

but ads that seed from the database before do not have this problem.

This only happens for newly created cases
For cases that do not already have a problem and I can easily switch between tabs

### Steps to reproduce

new ad
click relation tab
show error

![1](https://user-images.githubusercontent.com/9474884/152841880-025cff7c-46ee-487d-bea9-81da3e14bd14.jpg)

new ad

![image](https://user-images.githubusercontent.com/9474884/152842153-7e0021ff-87e6-486f-bd2f-d69801a1fccf.png)

the old ad  that creates with seed from WordPress work very good

![image](https://user-images.githubusercontent.com/9474884/152842426-765e1d4f-036f-49ab-9e8a-ad98c5bf9713.png)

**Comment by NeroAzure** [comment]
I had a similar problem, when calling the edit view of a record I got this error. I managed to track it down to my custom casts,  when removing those, the error went away. It seems that casts (or even attribute accessors) do trigger this issue, as they change the value of the records attribute. In my case I was casting a string to an instance of a custom enum implementation.

**Comment by danharrin** [comment]
Yeah, these issues are almost always in userland instead of Filament unfortunately. Check out this page - https://laravel-livewire.com/docs/2.x/troubleshooting#checksum-issues - and make sure your alpha-numeric keys in your data aren't being mutated.

But if there is a genuine Filament issue involving this error, please let me know.

**Comment by farhad321** [comment]
really I don't know what I do.

**Comment by farhad321** [comment]
I have a else problam that stirng show [object Object] in  input
![image](https://user-images.githubusercontent.com/9474884/153555762-ac1cb6ea-1fdc-4b0a-9814-b4388a7aaf62.png)

**Comment by farhad321** [comment]
I use "php artisan optimize"
solve for now

**Comment by farhad321** [comment]
This problem is coming back and has become a problem

**Comment by danharrin** [comment]
Please post a link to the Flare exception (click Share when it next happens). I want to inspect the Livewire tab to see if that tells us whats up.

**Comment by farhad321** [comment]
hello
flare not work good
 create url with ngrok
https://a027-87-98-181-95.ngrok.io/admin/ads/30/edit?activeRelationManager=App%5CFilament%5CResources%5CAd%5CAdResource%5CRelationManagers%5CCategoriesRelationManager

after edit ad show error

I'm online 
thank you

**Comment by danharrin** [comment]
I cannot sign in. Why is Flare not working?

**Comment by danharrin** [comment]
Gonna leave these screenshots here for reference

<img width="1440" alt="Screenshot 2022-02-16 at 09 53 19" src="https://user-images.githubusercontent.com/41773797/154239644-fd513ee0-dad4-4986-97f3-d750e708bc74.png">

<img width="1440" alt="Screenshot 2022-02-16 at 09 53 49" src="https://user-images.githubusercontent.com/41773797/154239745-93f5b8dc-4039-4ca4-976e-8dbefa7314f1.png">

**Comment by danharrin** [comment]
From first glance, I can't see any bad array keys that could be triggering this payload exception. What do you think, @ryangjchandler?

**Comment by farhad321** [comment]
![image](https://user-images.githubusercontent.com/9474884/154241527-6d3c21c9-e2e5-4746-8b02-1a532d10cf7e.png)
 
image  model Ad

**Comment by farhad321** [comment]
gitlab
https://gitlab.com/dev2.ca/kiusk/

**Comment by farhad321** [comment]
Check all the properties and let you know

**Comment by farhad321** [comment]
1)comment all form input resource exist problem.
2)comment all relation resource remove the problem.
3)uncomment one by one relation resource does not exist problem.
4)uncomment one by one all form input resource does not exist problem.
5)now does not exist problem all is thing is good.
but what to don't repeat this problem?

**Comment by ryangjchandler** [comment]
> From first glance, I can't see any bad array keys that could be triggering this payload exception. What do you think, @ryangjchandler?

Nothing stands out at a quick glance.

**Comment by farhad321** [comment]
![5](https://user-images.githubusercontent.com/9474884/154265418-ed2e7fee-477d-47fd-90b5-b9454abad845.png)


[important-notes](https://laravel-livewire.com/docs/2.x/properties#important-notes)
Here are three ESSENTIAL things to note about public properties before embarking on your Livewire journey:

Property names can't conflict with property names reserved for Livewire (e.g. rules or messages)
Data stored in public properties is made visible to the front-end JavaScript. Therefore, you SHOULD NOT store sensitive data in them.
Properties can ONLY be either JavaScript-friendly data types (string, int, array, boolean), OR one of the following PHP types: Stringable, Collection, DateTime, Model, EloquentCollection.

Thank you very much @danharrin
The problem was solved with your help
