### ISSUE TITLE
Content in a modal's first field is highlighted when modals open

### ISSUE THREAD

**Issue by binaryfire** [laravel-filament/filament#14913]
### Package

filament/filament

### Package Version

3.2.125

### Laravel Version

11.34.2

### Livewire Version

3.5.12

### PHP Version

8.3

### Problem description

When a modal is opened, the first field's  contents are highighted/selected (as if the user has clicked into the field and and pressed Ctrl + A to select all).

Also, the first field is autofocused by default (even if `->autofocus()` isn't used).

![image](https://github.com/user-attachments/assets/af076cf0-4e71-485c-bacc-a0a2430da53d)

### Expected behavior

- Field contents shouldn't be highlighted. Otherwise as soon as a user types something the field's contents are overwritten, which is a major UX issue.

- Autofocusing shouldn't happen by default. It makes it more likely a user will unintentionally change the value of a field with an accidental keystroke. It should only happen if `->autofocus()` is used. 

### Steps to reproduce

1. Head to https://demo.filamentphp.com/shop/orders/1
2. Scroll down to the first Payment and click the "Edit" table action
3. The Reference field will be autofocused and its contents will be highlighted

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/filamentphp/demo

**Comment by danharrin** [comment]
This is Alpine.js `x-trap` behaviour for accessibility: https://alpinejs.dev/plugins/focus#x-trap

**Comment by binaryfire** [comment]
I checked out a few articles and ok re: autofocus, but are you sure auto-selecting everything is correct for accessibility? I didn't see that behaviour in modal examples on any of the accessibility sites.

Check out the example here: https://www.w3.org/WAI/ARIA/apg/patterns/dialog-modal/examples/dialog/

If you fill out some fields and tab through them, only the focus changes. The field contents aren't ever selected. The only place I've seen "select-all-on-tab" is the Alpine link you shared and it seems a lot less accessible - users have to press an arrow key to deselect the content if they want to edit it. Otherwise the field is cleared.

**Comment by danharrin** [comment]
I agree that it isn't convenient for users that don't require the feature, but again the select-all thing is also Alpine and not Filament

https://github.com/user-attachments/assets/1569f1bb-ba4d-4e04-884f-7cee075974c7

So please raise the issue over there and see the reasoning

**Comment by binaryfire** [comment]
Ok will do. But IMHO it'd be better to not use `x-trap` until it's fixed because I think it's breaking accessibility much more than it's helping it.

**Comment by danharrin** [comment]
Unfortunately I disagree, focus trapping is very important to ensure modals are accessible in the first place
