### ISSUE TITLE
column actions don't currently have loading states

### ISSUE THREAD

**Issue by BrendanTWhite** [laravel-filament/filament#1499]
### Package

filament/tables

### Package Version

v2.9.15

### Laravel Version

v8.81.0

### Livewire Version

v2.10.1

### PHP Version

8.1.0

### Bug description

loading states were recently added to most elements, but are not yet on column actions. Would it be possible to add them to column actions?

See [this discord thread[(https://discord.com/channels/883083792112300104/883085278993068082/940557772251078658) for details.

### Steps to reproduce

n/a

### Relevant log output

```shell
n/a
```

**Comment by BrendanTWhite** [comment]
We could reduce the opacity of the elements, possibly also reduce the colour saturation. Just a suggestion. :-)

**Comment by danharrin** [comment]
Implemented in #1639 - simple opacity and cursor change.
