### ISSUE TITLE
Tenant selector routes are set to navigationItem url

### ISSUE THREAD

**Issue by Sirpattalot** [laravel-filament/filament#15069]
### Package

filament/filament

### Package Version

3.2

### Laravel Version

11.9

### Livewire Version

3

### PHP Version

8.2

### Problem description

Multi-tenant panel works perfectly, until adding a custom navigation link. Once the link is added via navigationItems(), all tenants in the tenant selector navigate to the url defined by the navigation item (/home) instead of /test/{tenant_id}

It doesn't matter if I use a hardcoded url like /home or a route('name') the behaviour is the same.

### Expected behavior

Navigation Items should be independent of the tenant selector. The tenant selector should navigate to other tenants, NOT to the url defined by the navigation item.

### Steps to reproduce

Create a multi-tenant panel, and a custom navigation item. Note that the tenant options will navigate to the url defined by the navigation item

`class TestPanelProvider extends PanelProvider
{
    public function panel(Panel $panel): Panel
    {

        return $panel
            ->id('test')
            ->path('test')
            ->colors([
                'primary' => Color::hex('#16A7DE')
            ])
            ->tenant(Test::class)
            ->discoverResources(in: app_path('Filament/Test/Resources'), for: 'App\\Filament\\Test\\Resources')
            ->discoverPages(in: app_path('Filament/Test/Pages'), for: 'App\\Filament\\Test\\Pages')
            ->pages([
                Dashboard::class,
            ])
            ->navigationItems([
                NavigationItem::make('Back to Home')
                    ->url('/home')
                    ->icon('heroicon-o-arrow-left')
                    ->sort(-10)
            ])
    }
}`

I haven't included a repo because the issue is simple enough, and has been previously report. Create multi-tenant panel, add a custom navigation item. Try to navigate via the tenant switcher.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/Sirpattalot/not-necessary

**Comment by danharrin** [comment]
Even if we redirected to `/test/{tenant_id}`, we still need to know where to redirect that user to after that. Which page? At the moment, we use the first navigation item in the sidebar as that is where most people expect to land.

Instead of inserting a navigation item, maybe use a render hook to add your new link above the sidebar content?
