### ISSUE TITLE
MODAL BLANK WHEN CLICK ADD IN RELATION MANAGER POLYMORPH

### ISSUE THREAD

**Issue by BOFOII** [laravel-filament/filament#15079]
### Package

filament/filament

### Package Version

v3.0.0

### Laravel Version

v10.0.0

### Livewire Version

v3.0.0

### PHP Version

8.1

### Problem description

is there something wrong with my code?, it shows the relation, but can't create it, no modal appears, just black

![Screenshot (1047)](https://github.com/user-attachments/assets/ba40ca59-10c1-44da-932b-c19ac1393966)

![Screenshot (1048)](https://github.com/user-attachments/assets/c7ce60d8-c84e-4f45-a474-72e93a4ef18c)

![Screenshot (1050)](https://github.com/user-attachments/assets/61856355-4f75-4bb1-b427-e7a4c812ed24)

when i click new license

![Screenshot (1045)](https://github.com/user-attachments/assets/1b178c24-010a-4303-a3a9-cd0d8bc5475a)

### Expected behavior

Show add modal and not blank

### Steps to reproduce

Creating relation mnager with polymorp relation

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/bofoiii

**Comment by BOFOII** [comment]
all action in table return blank page

**Comment by danharrin** [comment]
No reproduction, and please update Filament

**Comment by BOFOII** [comment]
i tired to 
composer update

php artisan filament:upgrade

still same

**Comment by DimasDwi25** [comment]
have you found a solution to this problem?

**Comment by BOFOII** [comment]
> have you found a solution to this problem?

kaga mas v:, pusing juga saya

**Comment by danharrin** [comment]
If someone creates a reproduction repository I will reopen it. But it sounds like the issue with Livewire that we fixed in the most recent release of Filament.

**Comment by danharrin** [comment]
Double check your actual Filament version in `php artisan about`

**Comment by BOFOII** [comment]
![Cuplikan layar 2024-12-14 152214](https://github.com/user-attachments/assets/62a21efa-caa9-40cf-857c-79f4d15f7e56)

**Comment by BOFOII** [comment]
> have you found a solution to this problem?

I think this person has the same problem

**Comment by danharrin** [comment]
Those are "Themes" versions, not "Filament. Find the "Filament" section

**Comment by danharrin** [comment]
Actually I see it. You are on v3.2.0. Not `v3.2.130`

Make sure Filament it set to `^3.2` in your composer.json and not `3.2` or `3.2.0`

**Comment by BOFOII** [comment]
ahh, it works fine, thank you very much for helping with this issue, glad to learn how to use this library

> Actually I see it. You are on v3.2.0. Not `v3.2.130`
> 
> Make sure Filament it set to `^3.2` in your composer.json and not `3.2` or `3.2.0`

**Comment by BOFOII** [comment]
i got a new problem 405 Method Not Allowed, <html>
<head><title>405 Method Not Allowed</title></head>
<body>
<center><h1>405 Method Not Allowed</h1></center>
<hr><center>hws</center>
</body>
</html>

**Comment by BOFOII** [comment]
![Screenshot (1078)](https://github.com/user-attachments/assets/393c0de8-560e-4d1c-ba04-1c042aaa4840)

**Comment by BOFOII** [comment]
when i put , the page displat403 <i class="mdi mdi-file-question" style="min-width: 1.5rem; font-size: 20px"></i>
