### ISSUE TITLE
When selecting year first in datepicker, it breaks

### ISSUE THREAD

**Issue by Robinvm** [laravel-filament/filament#1507]
### Package

filament/forms

### Package Version

v2.10.3

### Laravel Version

v8.82.0

### Livewire Version

v2.10.1

### PHP Version

8.0

### Bug description

When you have a datepicker and you click the year first on mobile. it breaks

**Comment by saade** [comment]
This happen's when i'm not able do input a valid date within the debounce time.


https://user-images.githubusercontent.com/14329460/153031351-1d89a100-fd0a-4e87-a146-6985b490ade9.MOV

**Comment by danharrin** [comment]
yes please @saade, you'll probably be able to take a look before I will

**Comment by saade** [comment]
Will hook into this tonight! Sorry for the delay

**Comment by danharrin** [comment]
Please be patient. In most open source projects this would probably not be fixed for weeks.

**Comment by Robinvm** [comment]
This still does not work

https://user-images.githubusercontent.com/22294849/154634289-925ee4da-7f56-49c7-9fd7-97d9ea9d511e.MOV

**Comment by saade** [comment]
@danharrin i'm on the latest version `2.10.11`, but looking at the vendor folder, my changes are not there, can you have a look at this?

<img width="495" alt="image" src="https://user-images.githubusercontent.com/14329460/154767955-16a32ee2-8d8f-4ad1-b286-8e23eb907796.png">

**Comment by saade** [comment]
@Robinvm can't reproduce that on the latest version. Make sure you're on the latest too

https://user-images.githubusercontent.com/14329460/154875558-9a67b31b-a8fa-4bb6-959f-251f508af043.MOV

**Comment by Robinvm** [comment]
I am on the latest. Just checked again and ran composer update, bug still apears.

**Comment by danharrin** [comment]
I think the assets just needed recompiling, I've just done that.

**Comment by Robinvm** [comment]
Now it works!!! Thankyou both!
