### ISSUE TITLE
Update v3.2.129 breaks live TagsInput

### ISSUE THREAD

**Issue by Jacobtims** [laravel-filament/filament#15076]
### Package

filament/filament

### Package Version

v3.2.130

### Laravel Version

11.35.0

### Livewire Version

3.5.12

### PHP Version

8.2.26

### Problem description

Pull request #15046 breaks the `TagsInput` field when I use another live (`->live()`) field in my form.
When I interact with the live field and then select a tag in the TagsInput field it doesn't show the selected tags.

Selected tags should appear here:
![image](https://github.com/user-attachments/assets/7efa9810-cb31-4c7b-937d-b9ffb138f16d)

### Expected behavior

The selected tags should appear here:
![image](https://github.com/user-attachments/assets/98a9f34d-854c-4039-a7c5-1bfcbe81d352)

### Steps to reproduce

1. Create a form
2. Add a field with `->live()`
3. Add a `TagsInput` field
4. Interact with the live field
5. Try to select a tag

Check the `UserResource` in the reproduction repository for an example.

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/Jacobtims/filament-issue-live-tagsinput

**Comment by kay0ramon** [comment]
I'm having the same problem.

**Comment by danharrin** [comment]
I can't imagine how `.stop` would cause that, have you tried removing that bit in `/vendor`? Does that really fix the problem?

**Comment by Jacobtims** [comment]
> I can't imagine how `.stop` would cause that, have you tried removing that bit in `/vendor`? Does that really fix the problem?

Just tested it and it has indeed nothing to do with the `.stop`.

When I lock Livewire to version "3.5.12" everything works fine with Filament "v3.2.130" version. So, there is still an issue with the latest Livewire version.

**Comment by danharrin** [comment]
I am reverting #15062. Livewire will stay locked until a solution is found. I do not have any more time to dedicate to this. Sorry.
