### ISSUE TITLE
NavigationGroup Icon not showing when using translated label in Arabic (RTL)

### ISSUE THREAD

**Issue by shaheenfawzy** [laravel-filament/filament#15090]
### Package

filament/filament

### Package Version

v3.2

### Laravel Version

v11.34.2

### Livewire Version

v3.x

### PHP Version

8.3.11

### Problem description

When using ->navigationGroups() method on panel with trarnslated label the icon disappears when the app locale is set to ar which a rtl language 
```php
$panel->navigationGroup([
    NavigationGroup::make()
        ->icon('heroicon-o-calculator')
        ->label(__('Accounting')),
])
```

here when app()->setLocale('ar') the calculator icon isn't showing
![image](https://github.com/user-attachments/assets/0d127218-859d-48f4-8679-e00320e47492)

when using app()->setLocal('en') or any ltr language the icon is showing correctly
![image](https://github.com/user-attachments/assets/a8fe592b-6c6f-4534-a4fa-ca7e8a56aff3)

### Expected behavior

The calculator Icon for the Accounting Navigation Group should show in the case of the use of a rtl language

### Steps to reproduce

```php
$panel->navigationGroup([
    NavigationGroup::make()
        ->icon('heroicon-o-calculator')
        ->label(__('Accounting')),
])
```

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/shaheenfawzy/filament-navigation-group-icon

**Comment by shaheenfawzy** [comment]
I still don't know how to solve the issue or why it happens, but if anyone encountered the same issue I found a solution that works, using the ->navigation() method on the panel and registering the navigation groups and navigation items manually here how to do it from the docs: https://filamentphp.com/docs/3.x/panels/navigation#registering-custom-navigation-groups

**Comment by danharrin** [comment]
Try this

```
$panel->navigationGroups([
    __('Accounting') => NavigationGroup::make()
        ->icon('heroicon-o-calculator'),
])
```

**Comment by huge10** [comment]
> Try this
> 
> ```
> $panel->navigationGroups([
>     __('Accounting') => NavigationGroup::make()
>         ->icon('heroicon-o-calculator'),
> ])
> ```

This unfortunately doesn't seem to work. Did it work for you, @shaheenfawzy? Kinda surprised not more people are experiencing this issue. For me icons are showing for the default language of the app, but not any translations. The group work, the labels are translated, the icons just get lost for any translation except the default.

**Comment by huge10** [comment]
Okay, the following worked for me:

```php
$panel->navigationGroup([
    NavigationGroup::make()
        ->icon('heroicon-o-calculator')
        ->label(fn (): string => __('Accounting')),
])
```
