### ISSUE TITLE
hasOne relations don't work when building a table

### ISSUE THREAD

**Issue by zltn** [laravel-filament/filament#151]
**Describe the bug**

**To reproduce**
1. Create a model that has a hasOne relationship
2. Create a table for that model
3. Print the relation with `Columns\Text::make('myHasOneRelation')`
4. You see nothing
5. Change the relationship on the model to a hasMany and you'll see the array printed with one object

**Expected behavior**
Receive the hasOne object so I could print it with `formatUsing()`

**Context**
- Package version: 1.4.7
- Livewire version: 2.3
- Laravel version: 8.32.1
- Browser: Chrome & Safari
- Server OS: local macOS
- PHP version: 7.4.4
- Database: MySQL 8.0.19

**Comment by danharrin** [comment]
Hey! Are you using the dot syntax to retrieve the column from the related table?

e.g. `Columns\Text::make('myHasOneRelation.name')`

**Comment by jamessessford** [comment]
I had a look to see if I could reproduce this and it seems to be the behaviour you would expect if you weren't trying to retreive a field, but the whole relationship.

`Columns\Text::make('myHasOneRelation')` doesn't return anything, presumably as it's returning a model which can't be converted wheras `Columns\Text::make('myHasManyRelation')` is returning a collection which will be converted to a JSON string

**Comment by ryangjchandler** [comment]
@jamessessford Yeah, I can't see any reason why someone would need to retrieve the whole relationship, so I wouldn't say this is a bug more of an unexpected scenario.

@zltn If you want to show some information about the relation, you should use the dot-notation syntax as mentioned by @danharrin or you could also use an accessor on the model itself.

**Comment by jamessessford** [comment]
@ryangjchandler definitely

**Comment by zltn** [comment]
The dot syntax works and I can do a workaround for this model. My original approach was to pass on the entire object and use the `formatUsing()` method on the entire object. @ryangjchandler this would be the big use case for which you'd want the entire object. Same for passing on the object to a custom view with `view()` which I'm planning for another model.

**Comment by zltn** [comment]
@ryangjchandler yeah that's what I used for this simple use case and it makes sense as I can reuse this accessor. My other case was to build a popover for cell that shows a full user object on hover but I can most likely just do another query from the custom view with the user id there.

**Comment by ryangjchandler** [comment]
> @ryangjchandler yeah that's what I used for this simple use case and it makes sense as I can reuse this accessor. My other case was to build a popover for cell that shows a full user object on hover but I can most likely just do another query from the custom view with the user id there.

Hm, I'll take a look at this later on if I get a chance - see if there's any sensible way for us to do this.

**Comment by ryangjchandler** [comment]
@zltn Here's what you want to do:

```php
Text::make('myHasOneRelation')
    ->getValueUsing(function ($record) {
        return $record->myHasOneRelation;
    })
    ->formatUsing(function ($myHasOneRelation) {
        return $myHasOneRelation->name;
    })
```

If you have any questions, please feel free to re-open this issue and we can look at ways of improving the developer experience.

**Comment by pathros** [comment]
Regarding the HasOne error:

Could you please explain with more detail? I mean, in which file or namespace in Filament Admin should I try?

In my case, in a ModelResource file, inside the 

```
public static function form(Form $form): Form
    {
        return $form
            ->schema([
                 //a hasOne relationship defined in my model
                 Forms\Components\BelongsToSelect::make('myHasOneRelation')->relationship('myHasOneRelation','myHasOneRelation.id')->required()->helperText('ID '),//hasOne relationship
            ])
    }
```

method, how do I implement a "hasOne" relationship in a create / edit form? Because I get the following error:


> TypeError
> Filament\Forms\Components\BelongsToSelect::getRelationship(): Return value must be of type ?Illuminate\Database\Eloquent\Relations\BelongsTo, Illuminate\Database\Eloquent\Relations\HasOne returned

**Comment by pathros** [comment]
Moreover, I have a ["BelongsToThrough"](https://github.com/staudenmeir/belongs-to-through) relationship, defined in my model like so:

```
 public function myrelationship2(){
        return $this->belongsToThrough(User::class,Event::class,'id','',[Event::class=>'event_id',User::class=>'responsable_id']);
    }
```

How would I implement it inside my ModelResources "$form->schema()" and "$table->columns()"?
