### ISSUE TITLE
/livewire/update 405 when save some html tag

### ISSUE THREAD

**Issue by BOFOII** [laravel-filament/filament#15149]
### Package

filament/filament

### Package Version

v3.2.0

### Laravel Version

v10.0.0

### Livewire Version

v3.0.0

### PHP Version

8.1

### Problem description

route /livewire/update 405 when save some html tag, in production mode, how can i fix this

### Expected behavior

/livewire/update return 200

### Steps to reproduce

fill input with some html code like <meta>

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/bofoiii

**Comment by BOFOII** [comment]
```
<html>
<head><title>405 Method Not Allowed</title></head>
<body>
<center><h1>405 Method Not Allowed</h1></center>
<hr><center>hws</center>
</body>
</html>
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
<!-- a padding to disable MSIE and Chrome friendly error page -->
```

**Comment by danharrin** [comment]
No details, no reproduction

**Comment by BOFOII** [comment]
how to fix that ?
