### ISSUE TITLE
[2.x] Dark Mode issues

### ISSUE THREAD

**Issue by ManojKiranAppathurai** [laravel-filament/filament#1515]
### Package

filament/filament

### Package Version

2.10.4

### Laravel Version

8.83.0

### Livewire Version

2.10.1

### PHP Version

8.1.1

## If anyone facing the issues Kindly let me know in the comments and I will add to the List.  So that it can be tracked and Fixed in upcoming version

Here I am pointing out the List of UI issues caused by Dark Mode. 

* [ ]  Toggle Field Icon is displayed with white background.
* [ ]  Relation Managers tab heading is blurred and while hovering the text turns into black or gray .

<details>
  <summary>Toggle Field Icon is displayed with white background</summary>
  
  ## Screenshot
![image](https://user-images.githubusercontent.com/30294553/153174477-f73237f3-d3c7-4f36-96ae-9d710342c552.png)
  ## Reproducible Code
```
    Toggle::make('is_active')
        ->label('Is Active ?')
        ->inline(false)
        ->onIcon('heroicon-o-check')
        ->offIcon('heroicon-o-x'),
```
</details>

<details>
  <summary>Relation Managers tab heading is blurred and while hovering the text turns into black or gray </summary>
  
  ## Screenshot
![image](https://user-images.githubusercontent.com/30294553/153243363-fb8abd7b-2263-4b44-8f31-14f95ffa3991.png)
  ## Reproducible Code
```
    Add more than one relation managers to page and you can see the difference
```
</details>

cc @danharrin  @ryangjchandler @ryanscherler

**Comment by ManojKiranAppathurai** [comment]
@danharrin  please pin the issues so that users don't duplicate it.

**Comment by danharrin** [comment]
Fixed by #1595 and #1597.

**Comment by ManojKiranAppathurai** [comment]
using toggle in Table Filter still causes the issue. In form it looks fine with border but in filter it doesn't have any borders around it

![image](https://user-images.githubusercontent.com/30294553/153813687-bce9867e-e0c7-4fb6-8c1d-45924fbd9e67.png)

**Comment by danharrin** [comment]
Fixed in the next release

**Comment by alvarezrrj** [comment]
Select displays with light background when `searchable()` is used

**Comment by zepfietje** [comment]
Could you open a new bug report, @alvarezrrj?
