### ISSUE TITLE
Datetime picker with reactive property run into an infinite loop when update by another input

### ISSUE THREAD

**Issue by sohailahmad07** [laravel-filament/filament#15173]
### Package

filament/forms

### Package Version

3.2.131

### Laravel Version

11.36.1

### Livewire Version

3.5.12

### PHP Version

8.3

### Problem description

Hi i have a reactive DateTime input but it when i try to update the input time from another input then it goes into an infinite loop as you can see in the video 

[Screencast from 2024-12-24 20-57-51.webm](https://github.com/user-attachments/assets/b8452a41-aa98-434b-a8fe-5f38dc607c60)

### Expected behavior

it should only update the date and time input once and should not be a infinite loop

### Steps to reproduce

1. Install and fresh laravel project with filament form
2. generate a livewire filament form `php artisan make:livewire-form Products/CreateProduct --generate`
3. Add 2 inputs , Textinput and DateTimeinput **Both need to be reactive**
4. Set the time when the Textinput is update i will go into an infinite loop

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/sohailahmad07/filament-DateTime-infinit-loop

**Comment by edmer664** [comment]
@sohailahmad07 This resolves the infinite loop by returning a formatted string instead of a date object:

```php


// ...existing code...
Forms\Components\TextInput::make('period_of_time')
    ->debounce()
    ->prefixIcon('heroicon-o-clock')
    ->suffix('Hrs')
    ->afterStateUpdated(function (string $state, Forms\Set $set) {
        $newDate = now()->addHours((int)$state);
        $set('date',$newDate->format('Y-m-d H:i:s'));
    })
    ->required(),
// ...existing code...
Forms\Components\DateTimePicker::make('date')
    ->lazy()
    ->native(false),
```


https://github.com/user-attachments/assets/625f2c3d-28f7-4dd1-ad48-6dd8368fd9e6

**Comment by sohailahmad07** [comment]
@edmer664 thnx that solved it
