### ISSUE TITLE
Bug with images used spatie-laravel-translatable-plugin

### ISSUE THREAD

**Issue by dmitryvasilevskiy** [laravel-filament/filament#15211]
### Package

filament/filament

### Package Version

v3.2.131

### Laravel Version

v11.36.1

### Livewire Version

v3.14.8

### PHP Version

PHP 8.3.10

### Problem description

Install https://github.com/filamentphp/spatie-laravel-translatable-plugin and change local with Images show error 

`vendor\filament\forms\src\Components\BaseFileUpload.php :712`
`foreach() argument must be of type array|object, string given`

When I want update image

`Filament\Forms\Components\BaseFileUpload::Filament\Forms\Components\{closure}(): Argument #2 ($value) must be of type array, string given`
`vendor\filament\forms\src\Components\BaseFileUpload.php :595`

### Expected behavior

Expect change local without errors and update image wtihout errors. I 

### Steps to reproduce

1) install https://github.com/filamentphp/spatie-laravel-translatable-plugin
2) set in model public $translatable = ['image']; 
3) set in resource Forms\Components\FileUpload::make('image')->columnSpanFull()

Help please change 4 line in BaseFileUpload (I cant do PR in this repository). 
example file with [work file](https://github.com/dmitryvasilevskiy/bug-with-images-used-spatie-laravel-translatable-plugin/blob/main/BaseFileUpload.php)

### Reproduction repository (issue will be closed if this is not valid)

https://github.com/dmitryvasilevskiy/bug-with-images-used-spatie-laravel-translatable-plugin

**Comment by danharrin** [comment]
Hello, we have handed over maintenance of this plugin to trusted developers, here: https://github.com/lara-zeus/translatable. You should open a new issue there for a resolution. It may already be fixed if you use their fork also.

The current plan is to officially deprecate the plugin and suggest the new plugin when v4 is released.

Many thanks

**Comment by dmitryvasilevskiy** [comment]
thanks
