### ISSUE TITLE
numeric TextInput with minValue(0) is unaffected

### ISSUE THREAD

**Issue by imaddev** [laravel-filament/filament#1530]
### Package

filament/forms

### Package Version

v2.10.5

### Laravel Version

v8.83

### Livewire Version

v2.10.1

### PHP Version

PHP 8.1.2

### Bug description

the numeric **TextInput** with **minValue(0)** is unaffected so we may get negative values which we don't want, when I inspect the html code I see that the **min** attribute does not exist on the input!

**Comment by ryangjchandler** [comment]
@imaddev The problem here is that `{!! ($value = $getMinValue()) ? "min=\"{$value}\"" : null !!}` will fail if the value is `0`. We should probably do a `!== null` check instead.

**Comment by adrianlzx1996** [comment]
This is still happening

**Package**
filament/forms

**Package Version**
v2.15.44

**Laravel Version**
v9.19

**Livewire Version**
v2.10.7

**PHP Version**
PHP 8.0.23
