### ISSUE TITLE
Can classes be added rows at a table?

### ISSUE THREAD

**Issue by swara-mohammed** [laravel-filament/filament#1592]
Can classes be added rows at a table?

This example is manually inserted through the browser:
![Bildschirmfoto 2022-02-07 um 11 31 44](https://user-images.githubusercontent.com/9349190/152771267-4fb4e144-b782-496a-8585-2d1503ebb2ab.png)

_Originally posted by @swara-mohammed in https://github.com/laravel-filament/filament/discussions/1481_

**Comment by danharrin** [comment]
Not yet, please don't use Issues for questions / feature requests
