### ISSUE TITLE
Upload dialogue pops up multiple times if you have wire:key on parent element

### ISSUE THREAD

**Issue by mokhosh** [laravel-filament/filament#1593]
### Package

filament/forms

### Package Version

v2.9.14

### Laravel Version

v8.81.0

### Livewire Version

v2.10.1

### PHP Version

php 8.1

### Bug description

I have this in my component:
```blade
<div wire:key="{{ $model->id }}">
    {{ $this->form }}
</div>
```
Now when I try to edit different models and press the attachment button, the upload dialogue pops of to the number of models I've tried to edit previously.
If I remove the `wire:key` the problem goes away, which seems counter intuitive.

**Comment by mokhosh** [comment]
This is the form schema btw:
```php
protected function getFormSchema(): array
{
    return [
        RichEditor::make('model.story')
            ->label('Story')
            ->disableAllToolbarButtons()
            ->enableToolbarButtons($this->defaultToolbarWithAttachments)
            ->fileAttachmentsDirectory('attachments')
    ];
}
```

**Comment by danharrin** [comment]
I cannot replicate this with your instructions unfortunately, but even if this is accurate, it would be a Trix / Livewire issue rather than anything to do with Filament.
