### ISSUE TITLE
BadMethodCallException: Method Illuminate\Support\Stringable::markdown does not exist.

### ISSUE THREAD

**Issue by leo-unglaub** [laravel-filament/filament#162]
Hey,
i am trying your software on a fresh laravel installation (latest release) and i get the following error message when i try to open the login page. 

```
BadMethodCallException
Method Illuminate\Support\Stringable::markdown does not exist. (View: vendor\filament\filament\packages\forms\resources\views\components\field-group.blade.php) 
```

There is nothing else installed in this testing installation. The only package installed is yours. I already did the database migration and created a new admin user.

Greetings
Leo

**Comment by ryangjchandler** [comment]
@leo-unglaub Which version of Laravel are you on?

**Comment by leo-unglaub** [comment]
I am on the latest release (v8.32.1).

**Comment by leo-unglaub** [comment]
If i remember correctly the markdown method got added in v8.26.0 or so. So that should be available in my v8.32.1 installation.

**Comment by danharrin** [comment]
@leo-unglaub yeah exactly, this is very odd...

**Comment by danharrin** [comment]
Can you use Tinker to see if you can use the Stringable markdown example in the docs?

**Comment by leo-unglaub** [comment]
Hmm, if its just on my installation please dont waste any time on this issue. I am working around it locally and then it will be fine! Thanks to both of you!

**Comment by rionjau** [comment]
Hi @leo-unglaub, I am developing locally as well and facing similar issue. How did you resolve it?

**Comment by ryangjchandler** [comment]
@rionjau Which version of Laravel are you using?

**Comment by rionjau** [comment]
8.23.1

**Comment by danharrin** [comment]
Can you upgrade to the latest Laravel version please?

**Comment by rionjau** [comment]
I have and still not working. 
I have 8.51.0 now

**Comment by rionjau** [comment]
Line 50 in vendor\filament\filament\packages\forms\resources\views\components\field-group.blade.php it the one causing the error.

**Comment by danharrin** [comment]
The method exists? 🤷‍♂️ https://laravel.com/docs/8.x/helpers#method-fluent-str-markdown

**Comment by danharrin** [comment]
<img width="1030" alt="Screenshot 2021-09-07 at 11 24 17" src="https://user-images.githubusercontent.com/41773797/132329332-4658a943-af78-4428-ad0c-af8415069eed.png">
