### ISSUE TITLE
Unable to delete item in repeater if Mask is used for TextInput

### ISSUE THREAD

**Issue by tangjh** [laravel-filament/filament#1624]
### Package

filament/filament

### Package Version

v2.10.9

### Laravel Version

v8.77.1

### Livewire Version

v2.0.2

### PHP Version

PHP 8.0

### Bug description

Adding a mask to a TextInput in a repeater resulting item unable to be deleted.  When click delete, the item is removed and then it reappears as an empty item.

If remove the mask, the item is deleted correctly.

                             Forms\Components\HasManyRepeater::make('my_rep')
                                    ->relationship('my_rel')
                                    ->schema([
                                        Forms\Components\TextInput::make('duration')
                                            ->label(__('DUR'))
                                            ->mask(
                                                fn (Forms\Components\TextInput\Mask $mask) => $mask
                                                    ->numeric()
                                                    ->integer()
                                            )

...

**Comment by danharrin** [comment]
Hey, I'm not going to be able to fix this. It's an incompatibility issue with Livewire/Alpine & iMask.js, but I am not skilled enough in the internals of that library to work out what's up. Alpine will soon be releasing its own masking plugin, so we'll move to using that as soon as it's released.

**Comment by simonbuehler** [comment]
oh, https://alpinejs.dev/plugins/mask does exist!

**Comment by Nicolai6120** [comment]
This bug is actual in `v2.16.52`
