### ISSUE TITLE
bug in upload files

### ISSUE THREAD

**Issue by sbc640964** [laravel-filament/filament#1645]
### Package

filament/filament

### Package Version

2.10

### Laravel Version

9.1.0

### PHP Version

8.1.0

### Bug description

I get an error when submitting a form with an attachment:

>League\Flysystem\Filesystem::write(): Argument #2 ($contents) must be of type string, null given, called in >C:\Users\....\my_app\vendor\laravel\framework\src\Illuminate\Filesystem\FilesystemAdapter.php on line 331

### Steps to reproduce

field:

```
Forms\Components\FileUpload::make('file'),
```

**Comment by danharrin** [comment]
Hi, this is not a Filament issue. I think it's most likely to be to do with your environment, but if not it'll be related to Livewire or Flysystem itself. We don't control the file upload logic, Livewire does, which uses Flysystem under the hood.

**Comment by sbc640964** [comment]
@danharrin 
I wonder who it is related to ...

The "yes" insult is performed
The file is in its place in the storge / public folder
It probably gets stuck in the file view after uploading

**Comment by drhootch** [comment]
@sbc640964 did you find a solution to this ? i face the same issue

**Comment by RealMrHex** [comment]
@sbc640964 same issue, any solution?

**Comment by rickgrotavi** [comment]
I got the same issue. It turned out that the user was uploading a file with a very long name. If you rename the file, everything works fine.
