### ISSUE TITLE
Unexpected behavior when overwriting edit action

### ISSUE THREAD

**Issue by zltn** [laravel-filament/filament#166]
**Describe the bug**
When you overwrite the openEdit() method on a relations manager table to redirect and navigate back the edit button doesn't work until je refresh the page. 

Context, would like to edit a resource that is attached on it's own edit page vs the relations popup because the resource itself has a second layer deep relation which is not shown.

**To reproduce**
1. Create a relationsManager for an object that has their own relationship
2. Overwrite the openEdit method likte this:
```php 
    public function openEdit($record)
    {
        $this->redirect(UserResource::generateUrl('edit',[$record]));
    }
```
3. Edit the record and press the back button in Chrome/Safari
4. The edit button doesn't redirect anymore and you need to refresh the page

**Context**

- Package version: Latest Dev
- Livewire version: 2.3
- Laravel version: 8.32.1
- Browser: Chrome & Safari
- Server OS: local macOS
- PHP version: 7.4.4
- Database: MySQL 8.0.19

**Comment by zltn** [comment]
did some more digging but couldn't figure out what was happening, looked like something was disabling the table onclick, but couldn't figure out where it was coming from.

Found another approach that does work but I had to overwrite the entire table method to set the `url` vs setting an `action` which was the default for relations

```php
    public function getTable()
    {
        return static::table(Table::make())
            ->filterable($this->filterable)
            ->pagination(false)
            ->recordActions([
                RecordActions\Link::make('edit')
                    ->label(static::$editRecordActionLabel)
                    ->url(fn ($record) => UserResource::generateUrl('edit', ['record' => $record]))
                    ->when(fn ($record) => Filament::can('update', $record)),
            ])
            ->searchable($this->searchable)
            ->sortable($this->sortable);
    }
```

**Comment by danharrin** [comment]
@zltn that is actually a better approach, does it work with the back button now?

**Comment by zltn** [comment]
Yeah, this works. I'm just trying to avoid overwriting too many methods while the package is still under active development. That's why I tried `openEdit()` first but didn't realize it was specific to actions not urls until I saw `getTable()`

**Comment by ryangjchandler** [comment]
> Yeah, this works. I'm just trying to avoid overwriting too many methods while the package is still under active development. That's why I tried `openEdit()` first but didn't realize it was specific to actions not urls until I saw `getTable()`

There shouldn't be any breaking changes so overriding methods is relatively safe.

**Comment by ryangjchandler** [comment]
@zltn From what I can tell, @danharrin is right, this is something on the Livewire side of things. Livewire has some `pushState` related stuff, so I'm guessing it's not restoring it correctly and `@entangle` is breaking too (using a `Tags` input breaks on navigation back).

**Comment by ryangjchandler** [comment]
@zltn I've opened a PR (#181) that would make your workaround a little easier.
