### ISSUE TITLE
Unable to deselect a value on a searchable select field

### ISSUE THREAD

**Issue by mxm1070** [laravel-filament/filament#1660]
### Package

filament/forms

### Package Version

v2.10.11

### Laravel Version

v9.1.0

### Livewire Version

v2.10.3

### PHP Version

PHP 8.1.2

### Bug description

I'm playing around with the Select field and I've noticed if you make it searchable there seems to be no way to deselect a value. You can't select the placeholder, type in the placeholder, clear the value, etc. If it's non searchable it's fine. I've tried nullable() and disablePlaceholderSelection(false) and neither of these help.

### Steps to reproduce

```php
Select::make('customer_id')
    ->label('Customer')
    ->placeholder('-')
    ->options(Customer::all()->pluck('name', 'id'))
    ->searchable()
```

**Comment by coffeeyoghurt** [comment]
`backspace` is working though see https://github.com/laravel-filament/filament/blob/2.x/packages/forms/resources/views/components/select.blade.php#L65 

But an actual `X` in the right corner would be helpful indeed.

**Comment by danharrin** [comment]
Hey, as @coffeeyoghurt, backspace and delete keys may be used to remove the value. If you want, add a cross button and PR it, that would be a good addition :)
