### ISSUE TITLE
Form - Custom state binding not working with numeric inputs

### ISSUE THREAD

**Issue by coffeeyoghurt** [laravel-filament/filament#1680]
### Package

filament/forms

### Package Version

v2.10.11

### Laravel Version

v.9

### Livewire Version

v2.10.4

### PHP Version

PHP 8.1

### Bug description

The `->lazy()` or `->stateBindingModifiers(['lazy.debounce.500ms'])` are not working for numeric input fields. It looks like the livewire `@entangle()` only accepts `.defer`. 

### Steps to reproduce

```php
// works:
TextInput::make('input_a')->lazy();
TextInput::make('input_b')->stateBindingModifiers(['lazy.debounce.500ms']);

// does not work / throws JS error (Uncaught SyntaxError: Invalid or unexpected token)
TextInput::make('number_a')->numeric()->lazy();
TextInput::make('number_b')->numeric()->stateBindingModifiers(['lazy.debounce.500ms']);
```

The problem seems to be the javascript Mask. I don't know what the best approach is to resolve this. Adding a debounce is really useful when doing a calculation in the backend for example. Currently it does not have a debounce and the result is a buggy feeling when entering a numeric value as the livewire response keeps overwriting the currently typed text. 

### Relevant log output

The DOM of an input field with custom debounce looks like this: 

```
<input wire:model.lazy.debounce.500ms="form.input_b" type="text" id="form.input_b" min="0">
```

The DOM of a numeric field with debounce looks like this, note the `entangle()` 
```
<input x-data="textInputFormComponent({
                        getMaskOptionsUsing: (IMask) => (/** options **/),
                        state: $wire.entangle('form.number_b').lazy.debounce.500ms,
                    })" type="text" wire:ignore="" id="form.number_b" inputmode="decimal" min="0" step="any">
```

**Comment by ryangjchandler** [comment]
@coffeeyoghurt Entangle only supports `.defer`, that's correct. Supporting `lazy` with entangle in theory is quite difficult since it's essentially the same as having no `.lazy` at all.

If you add `->reactive()` to your field, the debounce should still work though.

**Comment by coffeeyoghurt** [comment]
@ryangjchandler thank you for your reply. How would you set a debounce? 

`->reactive()` is also working for the numeric field, but when I set a debounce on it is not working as it creates something like this: `$wire.entangle('form.number_b').debounce.500ms` which does not seem to work with `entangle()`

**Comment by ryangjchandler** [comment]
@danharrin Do we already have support for this?

If not, we'll need to support `$getStateBindingModifiers` for entangled components somehow. Or we introduce dedicated `->debounce(int|float $duration)` methods.

**Comment by danharrin** [comment]
This is just a limitation with the current version of Livewire unfortunately, as you have both pointed out. I'd love to support debounce / lazy inputs for `@entangle`-based components, but since it's not a "bug" with Filament I'm going to close the issue. If someone wants to look into adding debounce functionality to certain components in Alpine. they're more than welcome and it would be greatly appreciated.

**Comment by coffeeyoghurt** [comment]
@danharrin, I have tried a few things and maybe benefitting from the alpine.js input events and debounce could be an option: 

Hacking this line into the text-input.blade.php does have the expected behavior, after 1 second the value is updated in livewire. 
![image](https://user-images.githubusercontent.com/77242852/155219828-67b61e77-0dc3-4e6a-935f-d51d0f7b212c.png)

Would this something that could work for filament? I will try to make a PR for this later on.

**Comment by ryangjchandler** [comment]
We should make the debounce configurable - definitely worth a PR though. 

Probably worth making a `CanBeDebounced` trait too so other fields can easily take advantage of this.

**Comment by skeemer** [comment]
I think this issue needs reopened. Regardless of the limitations of Livewire, code that is completely correct results in hours of time wasted trying to figure out why it doesn't work. I ran into this problem with the ColorPicker since it also uses `entangle`. This will be the case for any of the field components that use Alpine/entangle. This should be addressed somehow.

**Comment by danharrin** [comment]
We use issues to track what we need to work on. In this case, as soon as Livewire adds a debounce feature to their framework, Filament will work immediately in the way you expect. For that reason, I don't see why this issue should be open.

If you wish, contribute a new documentation page with "Troubleshooting"
