### ISSUE TITLE
MultiSelect options cannot be dynamic or they break

### ISSUE THREAD

**Issue by ralphjsmit** [laravel-filament/filament#1697]
### Package

filament/filament

### Package Version

2.10.12

### Laravel Version

8.83.2

### Livewire Version

2.10.4

### PHP Version

8.1.2

### Bug description

I use a closure to dynamically determine the options that should be visible in the MultiSelect field component.

Here is a simple reproduction component, which initially has two options. After changing it, it should have three options:

```php
MultiSelect::make('persons')
    ->options(
        function (callable $get, $state) {
            $a = [
                0 => 'A',
                1 => 'B',
            ];

            if ( $state !== [] ) {
                $a[2] = 'C';
            }

            return $a;
        }
    )
    ->reactive()
    ->required()
```

**What I expect:** The dropdown should offer three options instead of two.
**What I see:** The dropdown offers two options and the third option is empty / has no label..?

Here's a [video](https://stream.new/v/JcOUIwvP3aH02GB6zf6TtaU62lVFBR7UDPxRd01f9zp2Y).

The console gives the following errors:

<img width="1340" alt="Schermafbeelding 2022-02-23 om 17 25 48" src="https://user-images.githubusercontent.com/59207045/155362229-91b4d8f4-267e-47ad-9bf2-3dab765c2fa1.png">

**Comment by danharrin** [comment]
As per #1951, I've found a solution. You may now have dynamic, dependant `options()`, with full search support :)

**Comment by ralphjsmit** [comment]
💪 Thanks!
