### ISSUE TITLE
forms translations are copied to the old laravel ( < 9) lang directory 

### ISSUE THREAD

**Issue by petermaas** [laravel-filament/filament#1700]
### Package

filament/forms

### Package Version

v2.10.12

### Laravel Version

v9.0.0

### Livewire Version

v2.10.1

### PHP Version

PHP 8.1.2

### Bug description

**Issue**
php artisan vendor:publish --tag=forms-translations
Copied Directory [/vendor/filament/forms/resources/lang] To [/resources/lang/vendor/forms]

**Solution**
Should copy to [/lang/vendor/forms]

**Comment by ryangjchandler** [comment]
@petermaas This is related to the `PackageServiceProvider` that we use provided by https://github.com/spatie/laravel-package-tools.
