### ISSUE TITLE
Widgets Chart disaprears on browser tab change!

### ISSUE THREAD

**Issue by bezhanSalleh** [laravel-filament/filament#1719]
### Package

filament/filament

### Package Version

v2.10.8 & v2.10.14

### Laravel Version

v9.2.0

### Livewire Version

v2.10.4

### PHP Version

PHP 8.0.2

### Bug description

https://discord.com/channels/883083792112300104/883085267383226478/946885928935358628

https://user-images.githubusercontent.com/10007504/155814834-f7d36ec9-be87-43e8-be34-b67261e6dc80.mov

### Steps to reproduce

- Create a new filamentphp project
- add a stats overview widget or chart-widget
- change the tab and come back

**Comment by ryangjchandler** [comment]
Have spent some time researching this and came across a few issues reporting the same thing elsewhere:
* https://github.com/chartjs/Chart.js/issues/961
* https://github.com/chartjs/Chart.js/issues/2141
* https://forum.ionicframework.com/t/chartjs-disappear-when-changing-tabs/16715

It's no immediately clear what the correct fix is for this but it looks like it's a Chart.js problem.

**Comment by bezhanSalleh** [comment]
I did came across those as well and then went and tested it on Safari, Edge, Firfox and Chrome.
this only happens with Chrome, works perfect on others

https://user-images.githubusercontent.com/10007504/156244578-f14da508-f74a-4042-91fe-483b510978bd.mov

.
