### ISSUE TITLE
make:filament-resource command failure

### ISSUE THREAD

**Issue by DanielRTRD** [laravel-filament/filament#1726]
### Package

filament/filament

### Package Version

v2.10.14

### Laravel Version

v8.83.1

### PHP Version

8.0.12

### Bug description

I have a model called "Resource" and a model called "ResourceUpdate".

Trying to generate a filament resource running `php artisan make:filament-resource Resource --generate` for "Resource"/"ResourceUpdate" will generate a "empty" filament resource. So it seems like if you have any combination with "Resource" does not work.

Workaround:
1. Rename model file and name of class to "R"/"RU"
2. Run `php artisan make:filament-resource R --generate` / `php artisan make:filament-resource RU --generate`
3. Rename model files and name of class back to original
4. Update `$model` variable in generated `RResource.php`/`RUResource.php` with correct model class. For example:
```php
use App\Models\Resource as ModelsResource;
...

class RResource extends Resource
{
    protected static ?string $model = ModelsResource::class;
...
```

### Steps to reproduce

1. `php artisan make:filament-resource Resource --generate`

**Comment by danharrin** [comment]
Couple of questions, you have dbal installed, right?

Also, on your renamed model, is the table name correct? I.e, if you dont have an `rs` table, do you have a custom `$table` set on your model?

**Comment by DanielRTRD** [comment]
1. Yes.
2. No, I have not set a custom table name. [Link to model](https://github.com/P3D-Legacy/pokemon3d.net/blob/filament/app/Models/ResourceUpdate.php).

**Comment by danharrin** [comment]
What is your table called? And what command are you using to generate fields for this model?

**Comment by DanielRTRD** [comment]
> What is your table called? And what command are you using to generate fields for this model?
`resources` and ´resource_updates´ :)

**Comment by danharrin** [comment]
It's because your model has "Resource" in the name, which Filament tries to strip away to find the correct model name. And when you rename your Model to get around this, the table names are then mismatched to the model names, so you need to specify a custom `$table` property on the models for Filament to retrieve the columns from your database.
