### ISSUE TITLE
Select field size doesn't adjust to the specified in the colspan

### ISSUE THREAD

**Issue by romaldyminaya** [laravel-filament/filament#1734]
### Package

filament/filament

### Package Version

v2.10.14

### Laravel Version

^8.75

### PHP Version

PHP 8.1.2

### Bug description

When using the select field with various columsn ,when the content of the select field surprasses the colSpan size, it doesn't truncate as it did before. See image below:

![image](https://user-images.githubusercontent.com/2809147/156006030-beddcd3a-1a7c-448b-98c0-8ed90b0cb745.png)

### Steps to reproduce

Example code:

                HasManyRepeater::make('items')
                    ->label('')
                    ->relationship('items')
                    ->schema([
                        Select::make('vehicle_type')
                            ->label(__('labels.vehicle_type'))
                            ->searchable()
                            ->options(VehicleType::toArray())->required(),
                        TextInput::make('quantity')
                            ->label(__('labels.quantity'))
                            ->numeric()
                            ->default(1)
                            ->required(),
                        Toggle::make('is_helpersrequired')
                            ->label(__('labels.is_helpersrequired'))
                            ->inline(false),
                        TextInput::make('pallets')
                            ->label(__('labels.pallets'))
                            ->numeric()
                            ->default(0),
                    ])->columns(4),

> As you can see, it has 4 colums and it should fix perfectly.

**Comment by danharrin** [comment]
This was introduced by #1611, any clue how to fix it @jacksleight? I can definitely replicate it but I'm having trouble finding a fix.

The issue is that the new outer flex container for the select is allowing its children to exceed the width of it.

**Comment by jacksleight** [comment]
Hmmmm... I'll take a look!

**Comment by danharrin** [comment]
Thank you mate

**Comment by romaldyminaya** [comment]
Thank you homie 💪🏼
