### ISSUE TITLE
Select throws JS error when Options are not casted to String and you use searchable()

### ISSUE THREAD

**Issue by joshbenham** [laravel-filament/filament#1739]
### Package

filament/forms

### Package Version

v2.10.11

### Laravel Version

v9.1.0

### Livewire Version

v2.10.4

### PHP Version

PHP 8.1.2

### Bug description

I created a Year dropdown with the Select field which used ->searchable().

As I just used range() I did not cast the values to a string

Then trying to Search for a given Year a JS error gets thrown

```
Uncaught (in promise) TypeError: options2[key].trim is not a function
```

The error is found in selectFormComponent 

```js
if (options2[key].trim().toLowerCase().includes(search)) {
```

### Steps to reproduce

Create a Field 

```php
Select::make('value')
    ->searchable()
    ->options(array_combine(range(date('Y') + 2, 1969), range(date('Y') + 2, 1969))),
```

Then try and search the values and look at the JS Console.

```php
Select::make('value')
    ->searchable()
    ->options(array_combine(range(date('Y') + 2, 1969), array_map('strval', range(date('Y') + 2, 1969)))),
```

To fix it I had to cast the values to string.

**Comment by danharrin** [comment]
Fixed by #1765.
