### ISSUE TITLE
Call to undefined method Filament\Resources\Tables\Columns\View::url()

### ISSUE THREAD

**Issue by raphael-evolutap** [laravel-filament/filament#174]
This problem occurs when using **Columns\View**.

Two working solutions that i've tried:

**1 - Verify if url() method exists in column** 
Path: filament\filament\packages\tables\src\Table.php
`method_exists($column, 'url') ? $column->url($url) : $column;`

**2 - Put Concerns\CanOpenUrl trait inside View column**
Path: filament\filament\packages\tables\src\Columns\View.php

**Comment by ryangjchandler** [comment]
@raphael-evolutap I can't see why you'd want to use the `url()` method, you have full control over the view and just output a URL there. What is it you're trying to do exactly?

**Comment by raphael-evolutap** [comment]
Maybe i'm using it wrong, but i make a view to display a status.
It was working before 1.5

This is how i'm declaring it, i'm not using url inside view
`Columns\View::make('status')->view('components.status')`

**Comment by ryangjchandler** [comment]
@raphael-evolutap Ah, sorry I got a bit confused. I thought you were trying to call `View::make('status')->url()` - I think this is a bug then, I'll need to reproduce in an hour or so.

**Comment by raphael-evolutap** [comment]
@ryangjchandler ok, no problem. Thanks

**Comment by ryangjchandler** [comment]
@raphael-evolutap I've opened up a PR (#177) with a fix for this issue.
