### ISSUE TITLE
Version v2.10.15 missing semicolon in CanCreateRecords

### ISSUE THREAD

**Issue by mallardduck** [laravel-filament/filament#1740]
### Package

filament/filament

### Package Version

v2.10.15

### Laravel Version

v9

### PHP Version

PHP 8.1.3

### Bug description

When setting up Filament I found that the current latest release is flawed and has a broken line.

### Steps to reproduce

Install the affected version and load a page that uses this trait.

### Relevant log output

```shell
> During class fetch: Uncaught ParseError: syntax error, unexpected token "}", expecting ";" in vendor/filament/filament/src/Resources/Pages/ListRecords/Concerns/CanCreateRecords.php:100
```

https://github.com/laravel-filament/filament/blob/819d69e0371c8b886c710601673572059753bad0/packages/admin/src/Resources/Pages/ListRecords/Concerns/CanCreateRecords.php#L99

**Comment by ManojKiranAppathurai** [comment]
@danharrin I think I have missed the semicolon. And CI failed to catch the bug. We need to start adding more tests

**Comment by mallardduck** [comment]
Could be good to re-enable the phpstan workflows.
Seems they are manually disabled currently.

**Comment by danharrin** [comment]
They've been disabled since the L9 upgrade, because I haven't had time to fix them yet (even though the code works fine). Otherwise yeah, PHPstan will have caught this.

I'll start manually running PHPstan before every release, until we have the workflow working again.

**Comment by ryangjchandler** [comment]
@danharrin Since I fixed up the PHPStan stuff, the workflow should mostly run fine I think.

**Comment by mallardduck** [comment]
I have a PR to fix the handful of issues PHPStan is alerting on locally. Want me to send that up?
