### ISSUE TITLE
Update localization strings to use short keys

### ISSUE THREAD

**Issue by danharrin** [laravel-filament/filament#18]
Migration to using [short translation keys](https://laravel.com/docs/master/localization#using-short-keys) instead of the default translation would be a good idea. They allows us to serve more contextual translations, and keep them separate from app translations.

For example, the login button's current translation:
```php
__('Login')
```
could be appropriately moved to:
```php
__('filament::auth.login.buttons.submit')
```

**Comment by ryanscherler** [comment]
Ah yes! Good catch – I've always wondered what the right approach is related to translation strings. I'll definitely convert them!
