### ISSUE TITLE
`HasManyRepeater` does not respect custom relationship sort order

### ISSUE THREAD

**Issue by jacksleight** [laravel-filament/filament#1816]
### Package

filament/forms

### Package Version

2.10.23

### Laravel Version

9.3.1

### Livewire Version

2.10.4

### PHP Version

8.0.15

### Bug description

If you define a relationship with a custom sort order and use that in a `HasManyRepeater` the order of the records rendered in the repeater is not correct.

For example I have this relationship where all comments should appear in reverse order, latest at the top:

```php
    public function comments()
    {
        return $this->hasMany(Comment::class)->orderBy('created_at', 'desc');
    }
```

```php
    HasManyRepeater::make('comments')
        ->schema([
            // ...
        ])
        ->relationship('comments'),
```

But when the `HasManyRepeater` renders the records always appear in ascending ID order, not descending date order.

If I inspect the queries being run the query is correct and is returning the rows in the right order. The records are keyed by the row ID, and by the looks of it the collection is being re-sorted by key somewhere between the query and the when it's rendered.

I'd attempt a fix myself but I cant figure out where it's happening.

### Steps to reproduce

Create a `HasManyRepeater` using a relationship that sets a custom sort order, not ascending ID.

**Comment by danharrin** [comment]
Same issue as https://github.com/laravel-filament/filament/issues/1601#issuecomment-1057862428 I think, I'm not sure how to fix it either.

**Comment by jacksleight** [comment]
That one seems to be concerning filtering not sorting, but perhaps that's not relevent.

If it is the same issue unfortunately the same fix isn't possible, as `RelationshipRepeater::relationship()` doesn't accept a second argument.

Filament is definitely receiving the correct data in the correct order from the relationship, if I dump it in `fillFromRelationship()` its in the right order. It's just getting re-sorted somewhere before it gets to the Blade view.

**Comment by jacksleight** [comment]
I found the cause of the problem:

https://github.com/livewire/livewire/blob/0d8e44fb558a3f77835f0a8eefdaa98d766bc372/src/HydrationMiddleware/NormalizeDataForJavaScript.php#L31

If Filament stored the `HasManyRepeater` state as an associative array rather than a numerically indexed array this wouldn't apply and the items would remain in the correct order. I've submitted a potential fix.
