### ISSUE TITLE
Prefixed TextInput->url() fails validation

### ISSUE THREAD

**Issue by pixelpeter** [laravel-filament/filament#1818]
### Package

filament/filament

### Package Version

v2.10.23

### Laravel Version

v9.3.1

### Livewire Version

v2.10.4

### PHP Version

8.1.2

### Bug description

Adding a `prefix()` to a `TextInput` with type `url()` will fail validation
<img width="797" alt="grafik" src="https://user-images.githubusercontent.com/6502630/157097031-88ac2c3b-847a-4f3d-b930-a42020da1d25.png">

### Steps to reproduce

Issue is based on this code
```php
Forms\Components\TextInput::make('website')
    ->required()
    ->prefix('https://')
    ->url(),
```

### Relevant log output

```shell
none
```

**Comment by danharrin** [comment]
This is because the prefix is not part of the input value, it's just text. Maybe you instead want a `default('https://')`, or a custom rule that does not validate the URL protocol (https://) part of the string.
