### ISSUE TITLE
Input\Text::mask does not save the model with the masked input value 

### ISSUE THREAD

**Issue by pironti** [laravel-filament/filament#1833]
### Package

filament/forms

### Package Version

v2.0.0

### Laravel Version

v8.54

### Livewire Version

v2.7

### PHP Version

PHP 8.1.2

### Bug description

When I added a mask to the InputText field, the mask works fine in the frontend but when I try to save the record the mask is not present in the state. And the record is saved without the mask (only values);

As shown below, here is my code snnipet:

![image](https://user-images.githubusercontent.com/57006721/157319940-e120b0ad-6ac2-4269-8aab-155e6a4bbcfc.png)

### Steps to reproduce

 - Add mask to the TextInput
 - Create a mask pattern (00.000.000/0000-00)
 - Save the record

**Comment by ryangjchandler** [comment]
@pironti This is the expected behaviour - the mask is for the front-end and not the server-side.

**Comment by danharrin** [comment]
See Ryan's comment 👍
