### ISSUE TITLE
BelongsToManyMultiSelect doing infinite search

### ISSUE THREAD

**Issue by rahmanramsi** [laravel-filament/filament#1872]
### Package

filament/forms

### Package Version

2.10.24

### Laravel Version

v9.4.1

### Livewire Version

v2.10.4

### PHP Version

PHP 8.0.15

### Bug description

When doing search on  BelongsToManyMultiSelect, it will infinitely request to server
![Peek 2021-03-09 11-22](https://user-images.githubusercontent.com/48276043/157834823-f2ed8644-4cd4-490e-ba82-55f605f83b6a.gif)

### Steps to reproduce

Create filament form using `BelongsToManyMultiSelect` components

**Comment by ryangjchandler** [comment]
@rahmanramsi Are you able to provide the code for your `BelongsToManyMultiSelect` please. I'm unable to reproduce this on the latest release.

**Comment by rahmanramsi** [comment]
@ryangjchandler u can test this repo https://github.com/rahmanramsi/filament-example-bug 

also i found another bug. When using `SpatieMediaLibraryFileUpload::make('avatar')` , after submit it will also do infinite request.

**Comment by danharrin** [comment]
Cannot replicate this either, using your repo.

https://user-images.githubusercontent.com/41773797/158340816-4a2c50b0-692e-4038-96d7-75e57a04532b.mov

Also make sure that you have a Livewire property defined for each of your form fields. I don't think that is the cause of your issue though.

**Comment by rahmanramsi** [comment]
I dont know why its happening only on me
https://user-images.githubusercontent.com/48276043/158360440-b2dedc38-a614-4865-907a-454bd33d4ff4.mp4

**Comment by dsturm** [comment]
Hej @rahmanramsi,

I was currently facing a similar issue, where an changing a reactive field results in an infinite request loop. I need to break it down further and try to answer here to this.

**Comment by basepack** [comment]
This looks like the same issue as in #1915. And there is also a very clean example branche as I am not using any third party software. 

A form like below is enough to trigger this error:
<img width="794" alt="image" src="https://user-images.githubusercontent.com/939500/158561023-f91dcb62-b945-4024-9892-8ac0ea2ddfba.png">

**Comment by danharrin** [comment]
Please downgrade to Alpine v2.9.0, and report back if this fixes it. I think https://github.com/alpinejs/alpine/commit/260679bec16f44c891b2c2082d020b53cc834eee is causing this issue.

I've just released a new admin panel version that locks Alpine to this version, and it works.

I will get in contact with the Alpine team.

**Comment by danharrin** [comment]
alpinejs/alpine#2729
