### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of null

### ISSUE THREAD

**Issue by eislambey** [laravel-filament/filament#188]
**Describe the bug**
Im getting `Uncaught TypeError` error on the JavaScript console while swtiching filter.

**To reproduce**
1. Create a resource for example UserResource
2. Add a filter that matches with some records. for example `Admins`
3. Add another filter that does not matches with any record. for example `Members`
2. Go to resource page.
3. Click `Filter` and select `Members` filter.
4. Then select `Admins` filter.
4. See the error on JavaScript console.

**Expected behavior**
Should not be any error there.

**Statck Trace**
```
LoadingStates.js:192 Uncaught TypeError: Cannot read property 'split' of null
    at LoadingStates.js:192
    at Array.forEach (<anonymous>)
    at startLoading (LoadingStates.js:190)
    at setLoading (LoadingStates.js:161)
    at LoadingStates.js:50
    at MessageBus.js:17
    at Array.forEach (<anonymous>)
    at MessageBus.value (MessageBus.js:16)
    at Object.call (HookManager.js:38)
    at Object.callHook (Store.js:120)
(anonymous) @ LoadingStates.js:192
startLoading @ LoadingStates.js:190
setLoading @ LoadingStates.js:161
(anonymous) @ LoadingStates.js:50
(anonymous) @ MessageBus.js:17
value @ MessageBus.js:16
call @ HookManager.js:38
callHook @ Store.js:120
sendMessage @ index.js:223
value @ index.js:231
later @ debounce.js:8
setTimeout (async)
(anonymous) @ debounce.js:12
value @ index.js:204
callback @ node_initializer.js:87
```

**My Code**
```php
public static function table(Table $table): Table
{
    return $table
        ->columns([
            Text::make("id"),
            Text::make("name"),
            Text::make("email"),
            Text::make("role"),
        ])
        ->filters([
            Filter::make("admins", fn($query) => $query->where("role", "admin")),
            Filter::make("members", fn($query) => $query->where("role", "member")),
        ]);
}
```

**Screenshots**
Initial
![image](https://user-images.githubusercontent.com/10918436/110933437-d386c280-833d-11eb-90d6-6e5b78c135c1.png)

`Members` filter selected.
![image](https://user-images.githubusercontent.com/10918436/110933468-de415780-833d-11eb-8aa2-c2c1af0c0fc8.png)

Then `Admins` filter selected.
![image](https://user-images.githubusercontent.com/10918436/110933394-c36ee300-833d-11eb-8783-7e9c03f8929e.png)

**Context**
- Package version: 1.5.4
- Livewire version: 2.4.0
- Laravel version: 8.32.1
- PHP version: 8.0.1
- Browser: Chromium
- Server OS: Arch Linux

**Comment by ryangjchandler** [comment]
@eislambey The error is actually coming from Livewire's JavaScript - I'll have to try and reproduce the problem first to figure out if it's something our side or Livewire's.

**Comment by shuvroroy** [comment]
@ryangjchandler Please check these PR.

https://github.com/laravel-filament/filament/pull/212

**Comment by eislambey** [comment]
I can confirm #212 solves the issue. Thanks @shuvroroy !

**Comment by danharrin** [comment]
Merged into `develop`, please give the branch a thorough test!
