### ISSUE TITLE
Newly created resource Page fails to load with "InvalidArgumentException View [{{ view }}] not found."

### ISSUE THREAD

**Issue by JonathanH-UK** [laravel-filament/filament#189]
I've spoken briefly to ryangjchandler about this in the Discord channel.
It looks like when the resource scaffold gets built, that it's including an invalid definition of $view in the page template.

Steps to reproduce:
1) 'artisan make:filament-resource <name>'
2) Define a basic Form and Table schema in the main Resource php 
3) Try to load the menu item from the Filament Dashboard
4) Error as per issue subject.

Workaround:
Either comment out the $view in the Pages/List<name>.php file or (presumably) give it a valid custom view to use.

**Comment by danharrin** [comment]
Fixed in v1.5.5.
