### ISSUE TITLE
Simple patination arrows in RTL should be swapped

### ISSUE THREAD

**Issue by asefsoft** [laravel-filament/filament#1899]
### Package

filament/tables

### Package Version

2.10.27

### Laravel Version

8

### PHP Version

8

### Bug description

Hello
In RTL environment this arrows of simple pagination must be swapped with each other.

current status in RTL:
![image](https://user-images.githubusercontent.com/46367425/158148850-b39cc619-c32e-4dad-879a-a12e07d5b7dd.png)

it shoud be like this:
![image](https://user-images.githubusercontent.com/46367425/158149928-0fa205ec-f7fc-4e93-9bf1-0c078030baf8.png)

Thanks

### Steps to reproduce

Set locale of your laravel app to a RTL language in config.php file
`    'locale' => 'fa',`

then create a filement table with simple pationation to see problem

**Comment by danharrin** [comment]
Hey, while this project has an RTL mode, this completely depends on community support. None of the maintainers have experience designing RTL interfaces. However, we'll never reject PRs from anyone looking to improve the RTL experience themselves. If you'd like to see this fixed, please submit a PR.
