### ISSUE TITLE
RelationManager not found by Livewire

### ISSUE THREAD

**Issue by iantasker** [laravel-filament/filament#190]
**Describe the bug**
If you are registering a resource in a package using `Filament\PluginServiceProvider` you get the following error when your resource includes a RelationManager. 

![image](https://user-images.githubusercontent.com/17986190/110943426-18592c00-8333-11eb-8622-c9b41100d23b.png)

**To reproduce**
1. Extend `Filament\PluginServiceProvider` in your package
2. Create a resource with a RelationManager
3. View the resource 

**Expected behavior**
The relation manager should load correctly. 

![image](https://user-images.githubusercontent.com/17986190/110943543-3c1c7200-8333-11eb-92dc-e1a39326da61.png)

**Screenshots**

**Context**
- Package version: [e.g. 0.1.0] 1.5.5
- Livewire version: [e.g. 2.0.0] 2.3.5
- Laravel version: [e.g. 8.0.0] 8.32
- Browser: [e.g. Chrome, Safari] Chrome
- Server OS: [e.g. Ubuntu 18.04.4] Ubuntu 18.04.4
- PHP version: [e.g. 7.4] 7.4
- Database: [e.g. MySQL 8.0] N/A

**Additional details**
None

**Comment by danharrin** [comment]
Closed by #191.
