### ISSUE TITLE
store gif with fileupload

### ISSUE THREAD

**Issue by mohammad2306** [laravel-filament/filament#1905]
### Package

filament/filament

### Package Version

2.10.20

### Laravel Version

8.83.2

### PHP Version

8.0.10

### Bug description

I want to store a gif, but png is saved

### Steps to reproduce

Forms\Components\FileUpload::make('gif')
->disk('uploads')
->directory('gifs')

**Comment by mohammad2306** [comment]
The problem is when I upload a gif and save that converted to png
![image](https://user-images.githubusercontent.com/61474718/158212322-f036600f-fd9c-4b6a-9950-7b3c3d0a6279.png)
![image](https://user-images.githubusercontent.com/61474718/158212626-14c29be4-4247-4a68-bfbf-1911bd75102e.png)

**Comment by titantwentyone** [comment]
Having a read up and believe that FilePond will preserve PNGs and JPEGs but convert GIFs to PNGs. I found [https://stackoverflow.com/questions/58874156/make-filepond-image-transform-plugin-ignore-animated-gifs](this) which provides a solution for preserving animated GIFs so presumably there is a way also for regular gifs.  We'd need a PR to amend the setup of FilePond.

**Comment by danharrin** [comment]
Thanks for the extra info @titantwentyone, but that solution looks complex and I'm not sure if I want to include that code within the core when I'm not really sure how any of it works.

For now, I'm going to accept this as a "known issue" that we won't fix. GIFs are not properly supported in FilePond, so you'll need to make a custom file upload component with a library that does support that format.
