### ISSUE TITLE
Table Sorting Doesn't Work by Has One Of Many Relationship Field

### ISSUE THREAD

**Issue by intrepidws** [laravel-filament/filament#1912]
### Package

filament/filament

### Package Version

v2.10.27

### Laravel Version

v9.4.1

### Livewire Version

v2.10.4

### PHP Version

PHP 8.1.0

### Bug description

I have a Customer model and a Visit model that are connected by a hasMany relationship. To get the latest visit, I have a [Has One of Many relationship](https://laravel.com/docs/9.x/eloquent-relationships#has-one-of-many) setup on my Customer model like this:

```php
public function latestVisit()
{
    return $this->hasOne(\App\Models\Visit::class)
        ->latestOfMany('visited_at');
}
```

I have this field showing on the table of my CustomerResource like this:

```php
Tables\Columns\TextColumn::make('latestVisit.visited_at')
    ->label('Latest Visit')
    ->date('m/d/y')
    ->sortable(),
```

However, when I attempt to actually sort the table by this column, it does not work. Instead it seems to just order the table by the customer ID.

**Comment by Wulfheart** [comment]
Second that. (See #1942)

**Comment by danharrin** [comment]
Question is - is this Filament's responsibility to implement custom SQL, or should Laravel provide a solution

**Comment by danharrin** [comment]
Whilst I think this is possible with custom SQL, I think that it's Laravel's responsibility to include this as a core feature of the framework. If anyone notices a PR for this feature, let me know and I'll make sure it works with Filament :)

**Comment by shanerbaner82** [comment]
@intrepidws and @danharrin it looks like we were able to do the following to suit our needs:
```PHP
Table::make()
    ->columns([
        TextColumn::make('latestPost.title')
            ->label('Latest Post')
            ->sortable(query: function (Builder $query, string $direction) {
                $query
                    ->leftJoin('posts as latest_posts', function ($join) {
                        $join->on('users.id', '=', 'latest_posts.user_id')
                             ->whereRaw('latest_posts.created_at = (SELECT MAX(created_at) FROM posts WHERE posts.user_id = users.id)');
                    })
                    ->orderBy('latest_posts.title', $direction);
            }),
    ]);
```

I think the interesting part here is to use a `leftJoin()` vs a `with()`, this will allow us to modify the parent query which gives us the ability to filter, sort etc more natively (SQL), whereas `with()` seems to be doing the filtering, sorting after the query returns data.

**Comment by intrepidws** [comment]
@shanerbaner82 You are a gentleman and a scholar - this worked perfectly.
