### ISSUE TITLE
Form state is lost if returning from an Error Modal (e.g. SQL Error)

### ISSUE THREAD

**Issue by JonathanH-UK** [laravel-filament/filament#192]
**Describe the bug**
If an SQL error occurs when submitting a Filament Resource Create form, then this gets displayed as a modal dialog, which you can click away from to get back to the form, which looks like it is still filled in. However when you try to resubmit it, it fails validation claiming that the required fields are missing.

**To reproduce**

Causing an SQL error... There's plenty of ways to achieve the same
1. Set up a simple table and make sure that one column is not Nullable and has no default value - e.g.:
  $table->string('required_text');
  $table->string('blah');
2. Create a Filament form schema for 'required_text' but not for 'blah

Reproducing 
1. Fill in your required field(s) and click 'Create'
2. Creation fails with an SQL error (e.g. 'column [blah] has no default value')
3. Click outside of the model error dialog
4. Note that your required fields look as if they are complete
5. Fix the SQL in the background (e.g. modfiy column 'blah' to be nullable or to have a valid default)
6. Click 'Create' again
7. You'll get a validation error claiming that the Required fields must be completed.

**Expected behavior**
I'd expect the form to still contian its values but for them to be accepted when re-trying the 'create'

**Screenshots**
Probably unnecessary. Can provide on request.

**Context**
- Package version: 1.5.5
- Livewire version: 2.4.0
- Laravel version: 8.31.1
- Browser: Firefox Developer Edition
- Server OS: Homestead (Ubuntu)
- PHP version: 7.4
- Database: MariaDB 

**Additional details**
Add any other details about the problem here.

**Comment by danharrin** [comment]
Hey @JonathanH-UK! This is an issue with Livewire, and not Filament. In reality, it's not really a problem as users of your app should not be hitting SQL issues anyway.

**Comment by ryangjchandler** [comment]
@JonathanH-UK There's no really anyway of making this more graceful in Filament, without completely ditching Livewire. When Livewire encounters a problem, the entire request/response lifecycle doesn't finish because of the exception being thrown.
