### ISSUE TITLE
duplicate scripts or styles

### ISSUE THREAD

**Issue by tmtung144** [laravel-filament/filament#1937]
### Package

filament/filament

### Package Version

v2

### Laravel Version

v9

### Livewire Version

v2

### PHP Version

8.1

### Bug description

Repeat identical paths when registering styles or scripts

### Steps to reproduce

When I register custom Fields I need to embed some css or js files

![image](https://user-images.githubusercontent.com/19670776/159048642-b2006d91-5e9c-4abc-aa3b-19683f9f1ace.png)
It will suffer from repeating the same path over and over again

![image](https://user-images.githubusercontent.com/19670776/159048555-fd67172a-cc47-4df4-ae95-43a7fb763f8e.png)

This probably won't affect page load speed (with modern browsers) but it makes the code look ugly and redundant.

I hope you can add filters for this feature. Thank you!

**Comment by danharrin** [comment]
Give the scripts and styles array string keys and this shouldn't happen.

`['custom-field-css' => 'url']`

**Comment by tmtung144** [comment]
OK :D
