### ISSUE TITLE
Flysystem 3: private files never get a temporary URL

### ISSUE THREAD

**Issue by zenati** [laravel-filament/filament#1939]
### Package

filament/filament

### Package Version

v2.10.29

### Laravel Version

v9

### PHP Version

8.1

### Bug description

With FlySystem 3 (with AWS S3 bucket), the  `supportsTemporaryUrls` will be always false.
So when saving a private file, it works, but in the edit page, Filepond is unable to get file size, as he thinks the file is public.

In fact, the S3 adapter has neither "temporaryUrl" nor "getTemporaryUrl" methods.

```
            $storageAdapter = method_exists($storage, 'getAdapter') ? $storage->getAdapter() : (method_exists($storageDriver = $storage->getDriver(), 'getAdapter') ? $storageDriver->getAdapter() : null);
            $supportsTemporaryUrls = method_exists($storageAdapter, 'temporaryUrl') || method_exists($storageAdapter, 'getTemporaryUrl');

            if ($storage->getVisibility($file) === 'private' && $supportsTemporaryUrls) {
                return $storage->temporaryUrl(
                    $file,
                    now()->addMinutes(5),
                );
            }
```

### Steps to reproduce

```
                FileUpload::make('attachments')
                    ->disk('s3')
                    ->multiple()
                    ->minFiles(1)
                    ->maxFiles(5)
                    ->acceptedFileTypes(['text/csv'])
                    ->preserveFilenames()
                    ->directory(now()->format('Y/m/d/H/i/s/v'))
                    ->visibility('private')
```

**Comment by danharrin** [comment]
So what is the method to get temporary URLs for private files in v3?

**Comment by zenati** [comment]
`$supportsTemporaryUrls` should be

`method_exists($storage, 'temporaryUrl') || method_exists($storage, 'getTemporaryUrl');`

and not

`method_exists($storageAdapter, 'temporaryUrl') || method_exists($storageAdapter, 'getTemporaryUrl');`

**Comment by danharrin** [comment]
Hey, I opened #2157 to fix this issue. My solution is a little bit different to yours.

Could you please double check if it fixes things for you? :) Then I can merge it.
