### ISSUE TITLE
Desktop Collapsible Sidebar UI 

### ISSUE THREAD

**Issue by ZedoXmv** [laravel-filament/filament#1955]
### Package

filament/filament

### Package Version

v2.10.32

### Laravel Version

v9.5.1

### Livewire Version

v2.10.4

### PHP Version

8.1.2

### Bug description

1. Desktop Collapsible Sidebar does not account for the scrollbar (therefore icons are very small w/ scrollbar)
2. Desktop Collapsible Sidebar does not have any padding for the page

![image](https://user-images.githubusercontent.com/75579178/159234454-1b2310f4-1be2-4370-bd4d-423d582ada8d.png)

### Steps to reproduce

- add several navigation items

**Comment by ryangjchandler** [comment]
@ZedoXmv Are you using a custom theme?

**Comment by ManojKiranAppathurai** [comment]
I can reproduce this. I haven't done any changes in filament related files except brand logo and all the published assests are up to date and I can confirm this

![image](https://user-images.githubusercontent.com/30294553/159244772-2f036faa-c58b-4d71-8030-7bf36beb5dc7.png)

By reducing the browser zoom to **90%** fixes the issue.

![image](https://user-images.githubusercontent.com/30294553/159244911-2bb3f47d-e48b-4370-8163-839ee7bf94d9.png)

**Comment by danharrin** [comment]
It's just a Windows issue, the icons need `shrink-0`

**Comment by ZedoXmv** [comment]
> It's just a Windows issue, the icons need `shrink-0`

My screenshot in https://github.com/laravel-filament/filament/issues/1955#issue-1175113227 is Mac OS chrome

**Comment by pxlrbt** [comment]
@danharrin Not sure what's the best way to solve this. shrink-0 would solve the issue for icons, but the padding on the right side would be missing and therefore the hover/active state would look weird.

I tried to simulate this with padding-right: 20px on the sidebar.

<img width="80" alt="Bildschirmfoto 2022-03-21 um 14 10 31" src="https://user-images.githubusercontent.com/22632550/159267675-a66fc530-8e7e-4ba1-82b0-0c6c27a54ea0.png">

**Comment by danharrin** [comment]
Maybe @jacksleight has some insights on this? He's a Tailwind whizz :D

**Comment by pxlrbt** [comment]
We could increase the collapsed sidebar width to `5.4rem` and `justify-center` the icons.

https://user-images.githubusercontent.com/22632550/159278931-30dae86f-77af-448b-b3fa-220a1b1b59ef.mov

I'll open a PR.

**Comment by ManojKiranAppathurai** [comment]
Will do and let you know

**Comment by jacksleight** [comment]
In my experience scrollbars are a nightmare to predict and account for. I dont think there are any perfect solutions.

It is possible to calculate the scrollbar width in JS and then set that as a CSS custom property so it can be added to the `width` value you set, but that's a bit of a pain.

If you don't care about the scrollbars (even on systems where they'd normally appear) I have this utility that I reach for occasionally:

```css
@layer utilities {
    .hide-scrollbar {
        -ms-overflow-style: none; /* for Internet Explorer, Edge */
        scrollbar-width: none; /* for Firefox */
        overflow-y: scroll;
    }
    .hide-scrollbar::-webkit-scrollbar {
        display: none; /* for Chrome, Safari, and Opera */
    }
}
```

```blade
<nav class="hide-scrollbar flex-1 overflow-y-auto py-6 filament-sidebar-nav">
```

It will hide the scrollbar but keep the element scrollable. See: https://blog.hubspot.com/website/hide-scrollbar-css for more info.

FYI you can create the same issue on macOS by making scrollbars always appear in Preferences > General:

![Screenshot 2022-03-21 at 16 14 23](https://user-images.githubusercontent.com/126740/159306154-857e69df-b430-49bd-be3d-e67006c85465.png)

**Comment by ManojKiranAppathurai** [comment]
@pxlrbt now getting different behaviour

![image](https://user-images.githubusercontent.com/30294553/159420540-ccff9fb9-c401-4ed7-915c-cc07cc9b3c71.png)

**Comment by pxlrbt** [comment]
@ManojKiranAppathurai Did you recompile the assets? Looks like that's missing. It's merged anyway so just upgrade to the latest version.

**Comment by ManojKiranAppathurai** [comment]
![image](https://user-images.githubusercontent.com/30294553/159766160-00b367db-753c-4bbb-81c3-7cadff4abf03.png)

Looks fine except on Grouped navigation items

**Comment by pxlrbt** [comment]
@ManojKiranAppathurai Are they collapsed? Not sure what would be the best way to show them in the sidebar.

**Comment by ManojKiranAppathurai** [comment]
I Think adding icon to menu group will fix the issue.

**Comment by pxlrbt** [comment]
@ManojKiranAppathurai What do you mean by "Adding icon to menu group"? What should happen when clicking the icon? I think the only solution would be to uncollapse the group when collapsing the sidebar.
