### ISSUE TITLE
 FileUpload Field beside Select or RichEditor was broken

### ISSUE THREAD

**Issue by themahdavi** [laravel-filament/filament#1962]
### Package

filament/forms

### Package Version

2.10.0

### Laravel Version

9.2.0

### Livewire Version

2.10.0

### PHP Version

8.0.3

### Bug description

I've use FileUpload Field beside Select and RichEditor for save post field in DB. when Uploading post thumbnail before other fields fill no problem and everything work currectly but if i select option from Select Field or fill RichEditor with images and other stuff (just javascripty thing) FileUpload Field Broken and not work currectly but not show any error in console.

### Steps to reproduce

When fill FileUpload after fill Select, RichEditor or any javascripty thing FileUpload completely broken !

**Comment by danharrin** [comment]
This could be related a bug we experienced in Alpine.js, please make sure you're on Alpine v3.9.2.
