### ISSUE TITLE
Default options are not selected in MultiSelect dropdown

### ISSUE THREAD

**Issue by henninghorn** [laravel-filament/filament#1966]
### Package

filament/filament

### Package Version

v2.10.33

### Laravel Version

v9.5.1

### Livewire Version

v2.10.4

### PHP Version

PHP 8.1.2

### Bug description

Default options in a MultiSelect field are not selected in the dropdown.

### Steps to reproduce

The field:
```php
MultiSelect::make('testing')
    ->default([2])
    ->options([
        1 => 'Option 1',
        2 => 'Option 2',
        3 => 'Option 3',
    ]),
```

Before clicking dropdown (looks fine):
<img width="876" alt="billede" src="https://user-images.githubusercontent.com/742607/159485208-7470f760-7968-4a97-837d-8bdf0ee22042.png">

When clicking dropdown (Bug: Option 2 is not checked):
<img width="867" alt="billede" src="https://user-images.githubusercontent.com/742607/159485332-c36f5f71-32fb-4df6-b395-4e46843a3e71.png">

I would expect the dropdown to look like this (Expected: Option 2 to be checked):
<img width="867" alt="billede" src="https://user-images.githubusercontent.com/742607/159485535-528ec714-55ba-4b6e-82e2-3bf339062107.png">

Instead you're now able to double select the same option:
<img width="869" alt="billede" src="https://user-images.githubusercontent.com/742607/159485755-a892d713-fc99-4a02-90d5-4cbff9593018.png">

**Comment by ryangjchandler** [comment]
@henninghorn Are you using the admin package or the forms package on its own?

**Comment by themahdavi** [comment]
the default value is shown in input box but not checked in list of options.
two way :
1- when cleanup default value from input box and check from list have not any problem but default value not usable.
2- when don't cleanup default value from input and select again from list shown double of them and try to delete on of theme shown error : **Uncaught TypeError: t is undefined**
