### ISSUE TITLE
FileUpload - Delete file button not working

### ISSUE THREAD

**Issue by martinmildner** [laravel-filament/filament#1967]
### Package

filament/forms

### Package Version

v2.10.33

### Laravel Version

v8.x

### Livewire Version

v2.10.4

### PHP Version

PHP 8.1

### Bug description

Currently, uploaded files/images can no longer be deleted when using **FileUpload::make()**. FilePond's Delete button is not clickable anymore. Using **->removeUploadedFileButtonPosition('bottom')** works fine, if the field is high enough (e.g. with an image). **->panelLayout(null)** also seems to fix the problem (thanks for the hint to **saade**).

### Steps to reproduce

Create a FileUpload field:

`FileUpload::make('image')
->disk('public')
->directory('xxx/images')
->image() 
`

Upload an image. Save. Try to delete the file.
The problem was confirmed by another user on Discord.

**Comment by martinmildner** [comment]
@jacksleight yes, correct - it's on a secondary tab. Working correctly on the first tab.

**Comment by jacksleight** [comment]
FYI: https://github.com/pqina/filepond/issues/819
