### ISSUE TITLE
TimePicker component not working on 2.10.32+

### ISSUE THREAD

**Issue by ralphjsmit** [laravel-filament/filament#1968]
### Package

filament/forms

### Package Version

2.10.32+

### Laravel Version

8.83.5

### Livewire Version

v2.10.4

### PHP Version

8.1.x

### Bug description

Starting from version 2.10.32 the TimePicker component doesn't work anymore. Changing the value in the little dropdown doesn't display the value in the white input element anymore. That stays just empty. There are no errors in the console.

This works on version 2.10.31 and lower.

### Steps to reproduce

A reproduction could be as simple as this:

```php
TimePicker::make('start_time'),
```

**Comment by ryangjchandler** [comment]
Maybe related to https://github.com/laravel-filament/filament/pull/1930?

**Comment by ralphjsmit** [comment]
> Maybe related to #1930?

Could be, initially the value is `null` of course.. 🧐

**Comment by ryangjchandler** [comment]
Let me see what's going on!

**Comment by danharrin** [comment]
Reverted that PR. This issue is worse.
