### ISSUE TITLE
FileUpload Locale it does not work correctly

### ISSUE THREAD

**Issue by themahdavi** [laravel-filament/filament#1985]
### Package

filament/forms

### Package Version

2.10

### Laravel Version

9.2

### Livewire Version

2.6

### PHP Version

8.0.3

### Bug description

When change Laravel locale the Filament all packages set to new locale, design and more thing change dynamically.
but in FileUpload form component when change the locale of Laravel project this component try to set correct locale of Filepond package and search **[https://cdn.skypack.dev/filepond/locale/](https://cdn.skypack.dev/filepond/locale/)** CDN to get locale translation and not find some languages because locale filename of all locale not same as (en-en) 

from this page [https://github.com/pqina/filepond/tree/master/locale](https://github.com/pqina/filepond/tree/master/locale)
for example : da-dk.js , fa_ir.js, no-nb.js

and shown error in console get request for locale js file not respond!

for solution : define option to FileUpload component can handle filename of locale of Filepond package 🤙 
anyone have best solution ?

**Comment by themahdavi** [comment]
in FileUpload form component Link for handle locale : 
[https://github.com/laravel-filament/filament/blob/7865a0f2d97c645e99497de94fc110ee83735d36/packages/forms/resources/views/components/file-upload.blade.php#L14](https://github.com/laravel-filament/filament/blob/7865a0f2d97c645e99497de94fc110ee83735d36/packages/forms/resources/views/components/file-upload.blade.php#L14)

**Comment by Zagna** [comment]
Skypack seems to only have Filepond, no locales. Switch to https://cdn.jsdelivr.net/npm/filepond@4/locale/?

**Comment by themahdavi** [comment]
CDN link not problem

filename cause problem

[in this ](https://github.com/laravel-filament/filament/blob/7865a0f2d97c645e99497de94fc110ee83735d36/packages/forms/resources/views/components/file-upload.blade.php#L14) link logic of send filename to CDN not completely load every links


because for example code generate fa-fa.js but in filepond fa_ir.js is correct

**Comment by Zagna** [comment]
Simple switch which checks for both 'fa' and 'fa-ir' and sets $locale to 'fa_ir'?
Same for norwegian and swedish.

**Comment by themahdavi** [comment]
yes switch need fix for support all locale
