### ISSUE TITLE
Resource Table and Form with enum columns are not generated automatically with --generate flag

### ISSUE THREAD

**Issue by iotronlab** [laravel-filament/filament#1988]
### Package

filament/filament

### Package Version

v2.10

### Laravel Version

v9.5.1

### Livewire Version

v2.0

### PHP Version

PHP 8.0.12

### Bug description

a table with a enum column like below is not being generated automatically in forms and tables
```
 $table->enum('gender', ['M', 'F', 'Private'])->default('Private');
```
```
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                //
            ]);
    }
```
command:
```
php artisan make:filament-resource Customer/Customer --generate 
```

**Comment by bezhanSalleh** [comment]
doctrine doesn't seem to have support for this atm.

**Comment by wychoong** [comment]
> Expected/known: ENUMs cannot be reverse-engineered into a Type, since each is different from all others. 

https://github.com/doctrine/dbal/issues/3819#issuecomment-573419808

**Comment by ManuDoni** [comment]
I confirm this bug with Filament 2.15.17
When I run the make command with the option `--generate`, the `table` and `form` methods are empty if you have at least one enum column.
I think this should be in the documentation, or maybe we can read enums as strings while generating.

**Comment by wychoong** [comment]
#3476

**Comment by cawecoy** [comment]
This problem is still happening on the version 3.1.

Can't Filmanent just ignore the `enum` column and generate the `table` and `form` for the other columns?! Or do something like @ManuDoni said (to read `enums` as `strings`)?
