### ISSUE TITLE
Composer issue

### ISSUE THREAD

**Issue by manishlok** [laravel-filament/filament#2]
Since filament package require php 7.2 as  minimum requirement version of php but I got error.

driesvints/blade-icons 2.2.0 requires php ^7.4 -> your PHP version (7.2.*) does not satisfy that requirement.

**Comment by manishlok** [comment]
Quick fix is by passing --ignore-platform-reqs

composer require filament/filament dev-master --ignore-platform-reqs

Now, package is installed.

**Comment by ryanscherler** [comment]
I’m thinking maybe to jump bump the min php version of the package to 7.4 rather than ignore platform requirements.

**Comment by ryanscherler** [comment]
PHP 7.4 now required as core for this package. (https://github.com/laravel-filament/filament/commit/0ca17f0e49d3e02b8e28f03a7e5b44c2a22e75b4)
