### ISSUE TITLE
Laravel Octane Dependency Injection issue with Admin Panel Navigation

### ISSUE THREAD

**Issue by coleshirley** [laravel-filament/filament#2010]
### Package

filament/filament

### Package Version

2.10.36

### Laravel Version

9.5.1

### Livewire Version

2.10.4

### PHP Version

8.1.3

### Bug description

When using laravel octane to serve an application the navigation items get cached by the octane server and get rendered when they are not supposed to. This is because determining whether or not an item should be rendered on the navigation is done when the item is added to the navigation cache instead of when rendering the blade view.

### Steps to reproduce

See my demo repository readme for an explanation, video demo, and possible solutions

https://github.com/coleshirley/filament-octane-dependency-injection

**Comment by danharrin** [comment]
Fixed in #2055.
