### ISSUE TITLE
Limitation: generate option in MakeResourceCommand only works on models in default App\Models directory

### ISSUE THREAD

**Issue by arnonm** [laravel-filament/filament#2028]
### Package

filament/filament

### Package Version

v2.0.0

### Laravel Version

v9.2

### Livewire Version

v2.10.4

### PHP Version

PHP 8.1.3

### Bug description

running php artisan make:filament-resource User --generate works only if User is in app\Model\User
Currently it generates an empty table and form

### Steps to reproduce

running php artisan make:filament-resource User --generate works only if User is in app\Model\User
Currently it generates an empty table and form

**Comment by danharrin** [comment]
Yeah, otherwise how would we find the path to the model to retrieve the table name? We follow Laravel conventions, if you're not using those then you're on your own and will have to do more work like altering generated files yourself. Sorry about that.

**Comment by danharrin** [comment]
Ignore previous message, I just saw the PR. I will check it out, if the solution you propose does not introduce much extra complexity to the codebase then I'll consider merging. Thank you.
