### ISSUE TITLE
have_inline_labels config not working with ManageRecords

### ISSUE THREAD

**Issue by ttungbmt** [laravel-filament/filament#2039]
### Package

filament/filament

### Package Version

v2.0.0

### Laravel Version

v9.1.2

### Livewire Version

v2.0.0

### PHP Version

8.0.0

### Bug description

`have_inline_labels` not working with ManageRecords (Form Modal)

![image](https://user-images.githubusercontent.com/12232155/160561743-381d4dfc-c043-4b4f-88cf-e90be952aabf.png)

**Comment by danharrin** [comment]
Yeah this is deliberate. We've found that inline labels don't look very good in modals because of the reduced space, so that setting only applies to main resource forms.
