### ISSUE TITLE
Readonly / Disabled should prevent saving changed data

### ISSUE THREAD

**Issue by bernhardh** [laravel-filament/filament#2049]
### Package

filament/forms

### Package Version

v2.10.40

### Laravel Version

v8.83.6

### Livewire Version

v2.10.4

### PHP Version

8

### Bug description

As discussed in discord (see https://discordapp.com/channels/883083792112300104/883085278993068082/958647490050150400): If you set a field to disabled, it still returns/updates the value. 

For example, let's say I have a field name and only specific users should be allowed to modify it. My first guess was:

```php
Forms\Components\TextInput::make("name")
    ->disabled(fn() => !auth()->user()->isOwner())
```

This works as expected. But thats not secure. I just opened the browser dev-tools (F12) removed the "disabled" attribute from the form, modified the value and could saved my changed value. As a workaround I am using at the moment:

```php
Forms\Components\TextInput::make("name")
    ->visible(fn() => auth()->user()->isOwner()),
Forms\Components\Placeholder::make("name")
    ->visible(fn() => !auth()->user()->isOwner())
```

@danharrin said on discord:

> technically disabled() only controls frontend, you'd need dehydrated(false) to control saving
we can set dehydrated(false) when disabled() is called though, as a fix

**Comment by danharrin** [comment]
Hm, so I reverted #2100 because it's a breaking change for some people. I've added notes to the docs to instruct users to use `dehydrated(false)` if they don't want a field to be saved.

https://filamentphp.com/docs/2.x/forms/fields#disabling
