### ISSUE TITLE
Mismatch between documented behavior and actual behavior of disabled() on form field

### ISSUE THREAD

**Issue by edgrosvenor** [laravel-filament/filament#205]
**Describe the bug**
The documentation makes it look like you can pass a boolean to the disabled method on a form component, but the method doesn't actually accept a parameter. This means it's not possible to conditionally disable a field. The reason this is a bug rather than a feature request is simply that it doesn't behave the way the documentation looks like it should.

**To reproduce**

Attempt to use the disabled method as described in the documentation: 

`->disabled($disabled = false) // Make the field read-only.`

**Expected behavior**

**Screenshots**

**Context**
- Package version: 1.5.5
- Livewire version: 2.4.0
- Laravel version: 8.32.1
- Browser: N/A
- Server OS: Mac
- PHP version: 8.0
- Database: [e.g. MySQL 8.0]

**Additional details**
Add any other details about the problem here.

**Comment by ryangjchandler** [comment]
@danharrin One to sort out in develop I think with the refactoring.

**Comment by edgrosvenor** [comment]
@ryangjchandler I sent up a PR. Not sure if it's the approach you'd want to take, but it does bring the behavior of the method in line with the documentation.

**Comment by danharrin** [comment]
Hey! Admittedly, this is a mistake I made in the documentation. I expected it to be understood as "fields are enabled by default" but this was a confusing way to convey that.

This has been fixed as part of the large forms refactor, I encourage you to check out the `dev-develop` version of the package in Composer which will contain the fix until we iron out the refactor enough for merging.

Thanks!
