### ISSUE TITLE
Dependant Multiselect - duplicate options and not reactive

### ISSUE THREAD

**Issue by danharrin** [laravel-filament/filament#2065]
### Discussed in https://github.com/laravel-filament/filament/discussions/2035

<div type='discussions-op-text'>

<sup>Originally posted by **johncarter-** March 28, 2022</sup>
I'm trying to dynamically load a different set of options on a `Multiselect` based on the choice from a `Select`.

Two problems I'm facing:

1. I'm getting duplicate options in the `Multiselect` options
2. The `Multiselect` doesn't refresh on change of the select

See short video: https://vimeo.com/693103553/5985b15db3

Here's my code:

```php
Repeater::make('products_from')
    ->columns(2)
    ->schema([
        Select::make('product_attribute')
            ->reactive()
            ->options([
                'brand' => 'Brand',
                'type' => 'Type'
            ]),
        MultiSelect::make('selected_attributes')
            //->getSearchResultsUsing(fn (Closure $get, string $query) => Technology::where('name', 'like', "%{$query}%")->limit(50)->pluck('name', 'id'))
            ->options(function (Closure $get) {
                ray($get('product_attribute'));

                if (!$get('product_attribute')) {
                    return [];
                }

                $attributeModel = match ($get('product_attribute')) {
                    'brand' => ProductBrand::class,
                    'type' => ProductType::class
                };

                return $attributeModel::all()->pluck('name', 'id')->toArray();
            }),
    ])
```

Anyone know what I'm doing wrong?</div>

**Comment by danharrin** [comment]
@johncarter - I've replaced our current Select component with tom-select in #2077, if you can, test it out. I still need to style the new component but it should be fully-functional.

**Comment by johncarter-** [comment]
@danharrin I'm trying to test this out. I thought I could use a composer patch, but that fails. 🤷‍♂️

![image](https://user-images.githubusercontent.com/3776888/161963768-cd6d1877-e4a2-40d5-8b53-25f9a5019235.png)

**Comment by jojostx** [comment]
I'm facing this same issue, is there any update on it? @johncarter-

**Comment by johncarter-** [comment]
Hey mate, yeah you can check the status of the PR #2057.

I think its pretty much ready to go, but I haven't had a chance to check it yet.
