### ISSUE TITLE
Setup PHP-CS-Fixer GitHub Action

### ISSUE THREAD

**Issue by ryangjchandler** [laravel-filament/filament#207]
It would be great to get some code formatting setup for the PHP files. There's 2 approaches we could take here:

1. Automatically run the formatting action when somebody pushes to a PR (annoying because you would have to pull down between each push if changes have been committed back).
2. Automatically run the formatting action when a PR is merged into `develop` (can cause merge conflicts if develop's formatting is newer than the branches).
3. Manually trigger the action using a comment on the PR, such as `/format-php` (good because we can still run on an individual branch just before merging in).

Would be interested in your thoughts @danharrin and @ryanscherler.

**Comment by edgrosvenor** [comment]
Add it to the composer test script and strongly encourage everyone who submits a PR to run that to make sure they didn't break anything.

I always stick it in the composer after update script as well so that any time I update my dependencies my ugly code gets cleaned up. But that doesn't help on user-submitted PRs.

**Comment by ryangjchandler** [comment]
> Add it to the composer test script and strongly encourage everyone who submits a PR to run that to make sure they didn't break anything.
> 
> I always stick it in the composer after update script as well so that any time I update my dependencies my ugly code gets cleaned up. But that doesn't help on user-submitted PRs.

Yeah, that could work. I like the idea of running it manually too, the most annoying thing is when I have to re-pull my code before pushing to a PR / branch. 

Another alternative would be using Git hooks, so it runs before the code is even pushed but that's another piece of setup for the contributor.
