### ISSUE TITLE
Builder does not seem to function correctly when used for pivot field in edit form for BelongsToManyRelationManager

### ISSUE THREAD

**Issue by NeroAzure** [laravel-filament/filament#2079]
### Package

filament/filament

### Package Version

v2.10.41

### Laravel Version

v9.6.0

### Livewire Version

v2.10.4

### PHP Version

8.1.2

### Bug description

When trying to edit a previously attached BelongsToMany-relation, an error is thrown, which states `Cannot access offset of type string on string` in line 248 of the Builder `return $this->getBlock($itemData['type'])`. After some research I think I found the culprit for this, see, I defined a pivot-model for the pivot data with the according casts, but this model is not involved when the Builder is fed with data/when retrieving the records for the table, which results in the Builder receiving just a string instead of the expected array.

A quick, albeit not so neat workaround is to manually re-add the cast by overriding the `getTableQuery`-method on the RelationManager and call `withCasts` in there.

Example:
```php
public function getTableQuery(): Builder
{
    return parent::getTableQuery()
        ->withCasts(['your_builder_column' => 'json']);
}
```

Maybe you have a better idea to solve this, maybe this is so niche that it does not need to be fixed.
In the later case, just close this issue, at least this issue is here to lead others with the same problem to a solution. 😄

**Comment by danharrin** [comment]
Hey, is this fixed by #2309?
