### ISSUE TITLE
HasManyRepeater does not pass current object to schema

### ISSUE THREAD

**Issue by Katalam** [laravel-filament/filament#2102]
### Package

filament/forms

### Package Version

v2.10.29

### Laravel Version

v8.83.1

### Livewire Version

v2.10.3

### PHP Version

PHP 8.1

### Bug description

The current object in a HasManyRepeater Component is not given to closure in a placeholder content method inside the schema of the HasManyRepeater Component.

### Steps to reproduce

Add a form to a component with the model having a HasMany Relationship and add following field
```
return [
    HasManyRepeater::make('file_involveds')
    ->schema([
        Placeholder::make('role')
    ])
    ->relationship('involveds')
]
```
Now add content of the placeholder with a closure based on the current index of the HasManyRepeater
```
return [
    HasManyRepeater::make('file_involveds')
    ->schema([
        Placeholder::make('role')
        ->content(fn ($record) => dd($record))
    ])
    ->relationship('involveds')
]
```
or
```
return [
    HasManyRepeater::make('file_involveds')
    ->schema([
        Placeholder::make('role')
        ->content(function ($record) {
            dd($record);
        })
    ])
    ->relationship('involveds')
]
```
So shorthand doesn't make a difference. In both cases, the die and dump outputs a null value.
Expected is the current object of the HasManyRepeater Iteration.

The fill method as follows:

```
public function mount(File $file)
{
    $this->form->fill([
        'file_involveds' => $this->file->involveds->toArray(),
    ]);
}
```

**Comment by danharrin** [comment]
Hey, you need to do this instead:

```php
public File $file;

public function mount()
{
    $this->form->fill([]);
}

public function getFormModel(): Model
{
    return $this->file;
}
```

Filament handles loading + saving the relationship for you :)
