### ISSUE TITLE
Repeater add new items when nested repeater items got sorted!

### ISSUE THREAD

**Issue by mohamedmoussasoli** [laravel-filament/filament#2105]
### Package

filament/filament

### Package Version

v2.10.41

### Laravel Version

v9.6.0

### PHP Version

v8.1

### Bug description

I have a repeater which have nested repeater, when i sort the nested repeater items a new items are added above the main repeater and the number of new items in the main repeater is based on the number of items in the nested repearer.
<img width="1279" alt="Screenshot 2022-04-07 at 10 15 41 PM" src="https://user-images.githubusercontent.com/9276573/162288589-0ab00413-0ec2-428a-932c-15badf655b87.png">

### Steps to reproduce

Here is a repeater field with nested repeater

Repeater::make('options')
    ->schema([

        Grid::make(2)
            ->schema([

                TextInput::make('name'),

                Repeater::make('values')
                    ->schema([

                        TextInput::make('value'),

                    ])

            ])

    ]),

when adding more values and trying to sort the values repeater new items will be added above the options repeater.

**Comment by danharrin** [comment]
Introduced by #2017, fixed by #2156.

**Comment by danharrin** [comment]
Fixed by #2164.
