### ISSUE TITLE
Sidebard collapse behaviour

### ISSUE THREAD

**Issue by invaders-xx** [laravel-filament/filament#2112]
### Package

filament/filament

### Package Version

v2.10.44

### Laravel Version

v8.83.7

### Livewire Version

v2.10.4

### PHP Version

PHP 8

### Bug description

https://discord.com/channels/883083792112300104/883085267383226478/960448193370402816
There is a video there explaining the issue

**Comment by danharrin** [comment]
Fixed by #2214
