### ISSUE TITLE
Avoid the creation of a resource called "Resource"

### ISSUE THREAD

**Issue by sjardim** [laravel-filament/filament#2123]
### Package

filament/filament

### Package Version

v2.10.43

### Laravel Version

v9.2

### Livewire Version

v2.10.5

### PHP Version

PHP 8.0.14

### Bug description

Filament's  `MakeResourceCommand` doesn't show an error if we try creating a resource called "Resource". 

Yeah, I know it sounds dumb, but I had a project where the model had to be named 'Resource'. :)

### Steps to reproduce

1 - Create a model called "Resource" with migration;
4 - Create a Filament resource called "Resource";

5 - Open `Filament/Resources/Resource.php` file and see that on line 7, the model is missing:

`use App\Models\;`

And a parse error will appear on the browser:
`syntax error, unexpected token ";", expecting "{"`

6 - Adding the "Resource" to line 7 will give another error as it will conflict with Filament's resource:

`syntax error, unexpected token "::"`
On line 16: `protected static ?string $model = ::class;`

Suggested fix: Add a simple check on the **MakeResourceCommand** class to warn the user and skip the resource creation

```
 $model = (string) Str::of($this->argument('name') ?? $this->askRequired('Model (e.g. `BlogPost`)', 'name'))
            ->studly()
            ->beforeLast('Resource')
            ->trim('/')
            ->trim('\\')
            ->trim(' ')
            ->studly()
            ->replace('/', '\\');
        
  if($model === '') { //Because beforeLast() returns empty string
      $this->error('A Filament Resource cannot be called "Resource"! Please choose another name.');
      return false;
  }
```

**Comment by danharrin** [comment]
Fixed by #2310, you can create a ResourceResource but it requires you to alias the model class on the import :)
