### ISSUE TITLE
MultiSelect getOptions(): Return value must be of type array, null returned

### ISSUE THREAD

**Issue by borgianvme** [laravel-filament/filament#2173]
### Package

filament/forms

### Package Version

v2.10.45

### Laravel Version

8.83.8

### Livewire Version

v2.10.5

### PHP Version

PHP 8.0

### Bug description

Dependant MultiSelect throwing **getOptions(): Return value must be of type array, null returned** when the input that the Multi-select is dependant on has no value yet.

### Steps to reproduce

1. Dependant MultiSelect based on another Select.
2. Select has no default value selected
3. As soon as the page is refreshed the error should be thrown.

### Relevant log output

```shell
Filament\Forms\Components\MultiSelect::getOptions(): Return value must be of type array, null returned (View: /var/www/html/vendor/filament/forms/resources/views/components/multi-select.blade.php)
```

**Comment by ryangjchandler** [comment]
@borgianvme Can you provide some more code please. Specifically the `->options()` method on the Multiselect field.

**Comment by borgianvme** [comment]
@ryangjchandler  After seeing your comment, I realised that it was actually the code in `->options()` that was causing the issue. After moving a few things around the issue isn't there anymore. Thank you, really helpful.
