### ISSUE TITLE
SpatieMediaLibraryImageColumn returns invalid url

### ISSUE THREAD

**Issue by sten** [laravel-filament/filament#2182]
### Package

filament/spatie-laravel-media-library-plugin

### Package Version

v2.10.46

### Laravel Version

v9.7.0

### Livewire Version

v2.10.5

### PHP Version

8.0.17

### Bug description

The SpatieMediaLibraryImageColumn returns only the filename and not the url with the full path with the subdirectory of the ID. E.g.:  
`<img src="UDnEjV8095Pr5NfR9vaLYr8I6pEDOQ-metaay11LWxldXZlbi1sb2dvLWJsYWNrLWFuZC13aGl0ZS5wbmc=--thumbnail.jpg">` instead of
`<img src="http://.../storage/2/conversions/UDnEjV8095Pr5NfR9vaLYr8I6pEDOQ-metaay11LWxldXZlbi1sb2dvLWJsYWNrLWFuZC13aGl0ZS5wbmc=--thumbnail.jpg">`

It does not take the conversion into account.

### Steps to reproduce

This is the code I am using:

`Tables\Columns\SpatieMediaLibraryImageColumn::make('logo')->conversion('thumbnail'),`

The bug is in the SpatieMediaLibraryImageColumn class on line 41:

```
public function getImagePath(): ?string
    {
        $state = $this->getState();

        if ($state) {
            return $state;
        }

        $record = $this->getRecord();

        if (! method_exists($record, 'getFirstMediaUrl')) {
            return $state;
        }

        return $record->getFirstMediaUrl($this->getCollection(), $this->getConversion());
    }
```

The `getState()` function only returns the file name and does not take return a url nor does it take the conversion and collection settings into account. If you remove these lines everything works:

```
//remove this:
if ($state) {
     return $state;
}
```

**Comment by danharrin** [comment]
With the media library though, the file name isn't stored in the column, why's that happening in your case? Do you have a `logo` column?

**Comment by sten** [comment]
@danharrin You were right! I did still have a column `logo`. I am trying out Filament and it was a left over from a test before I tried out the filament media library plugin.

Thanks for the swift reply and the great software!

**Comment by danharrin** [comment]
No worries!
