### ISSUE TITLE
Table selectable columns

### ISSUE THREAD

**Issue by invaders-xx** [laravel-filament/filament#2186]
### Package

filament/filament

### Package Version

v2.11

### Laravel Version

v8.83.7

### Livewire Version

v2.10.4

### PHP Version

PHP 8

### Bug description

the selectable column feature seems not to be working on relations:

Tables\Columns\TextColumn::make('type.name')
                    ->label(__('Type'))
                    ->sortable()
                    ->toggleable(true, true)
                    ->searchable(),
Others works fine but not this one:

Please see the video : 

https://user-images.githubusercontent.com/604907/164388469-b86676dc-1ba1-4884-8ca7-554a8339abf5.mp4

**Comment by reinier-dubbelglas** [comment]
I experience the same issue on Laravel v9.9.0 / LiveWire v2.10.5
