### ISSUE TITLE
not work feature #1693 on relation columns

### ISSUE THREAD

**Issue by themahdavi** [laravel-filament/filament#2192]
### Package

filament/tables

### Package Version

2.11.0

### Laravel Version

9.9.0

### Livewire Version

2.6

### PHP Version

8.1.2

### Bug description

when using relational columns selectable not work corrcetly

for example i have products table with user.name column
`Tables\Columns\TextColumn::make('user.name')->searchable()->sortable()->toggleable(),`

when add toggable() on this column not work toggling

**and one small improve to RTL version add one css class to dropdown : `rtl:pl-0`**

**Comment by ryangjchandler** [comment]
This has been fixed by #2187 and will be in the next release.
