### ISSUE TITLE
When saving a hasManyRepeater which has translatable fields, it changes input to [object Object]

### ISSUE THREAD

**Issue by Robinvm** [laravel-filament/filament#2204]
### Package

filament/forms

### Package Version

2.11.0

### Laravel Version

9.9

### Livewire Version

2.10

### PHP Version

8.1

### Bug description

When saving a hasManyRepeater which has translatable fields, it changes input to [object Object]

**Comment by danharrin** [comment]
Repeaters aren't translatable ATM
