### ISSUE TITLE
Problem with create new resources

### ISSUE THREAD

**Issue by OrlovPetr** [laravel-filament/filament#2205]
### Package

filament/filament

### Package Version

v.2.11.2

### Laravel Version

v9.2

### PHP Version

PHP 8.1

### Bug description

Work with filament first time and get the problem.
When create new resource by `php artisan make:filament-resource Resource` command and then set up it (just fields and table columns), don't see it in admin panel.
Thought problem is in empty DB table, but after filling it with fake data problem didn't go away.
It's very strange because with User resource all was ok.
Link 2 screenshots with admin panel example and PHP Storm window with opened resource file example
<img width="1440" alt="Снимок экрана 2022-04-23 в 15 45 34" src="https://user-images.githubusercontent.com/43413878/164895170-4dce2ae7-d501-47ea-a336-54f7a03eb025.png">
<img width="1440" alt="Снимок экрана 2022-04-23 в 15 45 11" src="https://user-images.githubusercontent.com/43413878/164895164-cd661030-2c6e-4a41-ade1-d9f19a4bcc00.png">

### Steps to reproduce

- create new resource by `php artisan make:filament-resource Resource`;
- set up it in forms and table functions;
- look it in admin panel

**Comment by ryangjchandler** [comment]
@OrlovPetr Do you have a policy for that model?

**Comment by OrlovPetr** [comment]
> @OrlovPetr Do you have a policy for that model?
Yes, model created with policy, request and other resources

**Comment by OrlovPetr** [comment]
Problem was in policy, thanks!
