### ISSUE TITLE
Datepicker doesn't clear on first backspace

### ISSUE THREAD

**Issue by Cannonb4ll** [laravel-filament/filament#2232]
### Package

filament/forms

### Package Version

v2.0.0

### Laravel Version

v9.0.0

### PHP Version

PHP 8.1

### Bug description

It seems that when you try to clear a datetimepicker input with backspace (after focussing) it doesn't clear the date right away, but rather defaults to today. I'm working with Chrome version 100.

I am not sure if this is a W3C standard, but the video should illustrate enough.

https://user-images.githubusercontent.com/3110750/165464311-4bc0ebfd-0fe5-457f-b08e-78b175b865b6.mp4

### Steps to reproduce

1. Create a form with datetimepicker
2. Make it filled with a date in the future
3. Focus the field and clear it, it will default to today's date.

**Comment by danharrin** [comment]
Cannot reproduce this, sorry.

```php
DateTimePicker::make('date')
```

https://user-images.githubusercontent.com/41773797/167310831-ec534e63-a935-4325-8d15-128948b37a76.mov

**Comment by Cannonb4ll** [comment]
@danharrin That's because you've forgot step 2:

**Make it filled with a date in the future**

This simulates when having a model, use this:

```php
Forms\Components\DateTimePicker::make('created_at')->default(now())
```

**Comment by danharrin** [comment]
Oh I thought you meant "select a date in the future", not have that as default

**Comment by StephanMeijer** [comment]
Wished for behaviour: 
![wished for behaviour](https://user-images.githubusercontent.com/3169264/167620980-68dbadea-b938-4ead-8ccc-fcb6a3857489.gif)

Actual behaviour:
![actual behaviour](https://user-images.githubusercontent.com/3169264/167621004-b9edd3c3-8817-4d49-a30d-673ece0acc8f.gif)
