### ISSUE TITLE
Select placeholder text doesn't follow colours of other Input placeholders

### ISSUE THREAD

**Issue by MechJosh0** [laravel-filament/filament#2240]
### Package

filament/forms

### Package Version

v2.0

### Laravel Version

v8.75

### Livewire Version

v2.9

### PHP Version

PHP 8.0.18

### Bug description

The placeholder text for `Select` isn't using any colour and defaults to black. This looks strange when comparing it to other default values which are light grey.

<img width="730" alt="image" src="https://user-images.githubusercontent.com/11144798/165569031-60c39728-9a87-42c2-8e51-dfdc71ee821c.png">

### Steps to reproduce

```php
Select::make('authorId')
    ->label('Author')
    ->options(User::all()->pluck('name', 'id'))
    ->searchable()
```

**Comment by ryangjchandler** [comment]
@MechJosh0 Select fields don't actually have placeholders, they just have a disabled option field that acts as a default empty value. Because of this, it's hard to style them the same way as placeholders without using JavaScript to bind the classes based on the chosen option.

**Comment by MechJosh0** [comment]
I would have thought as you create the disabled value, you know it's the "placeholder" option and can style is accordingly can you not? If you're using livewire this sounds possible.

**Comment by saade** [comment]
With only css is not possible, The only hack we can do is something like this:
https://jsfiddle.net/p63eg7d8/

But will only work on required selects :/

**Comment by danharrin** [comment]
Yeah, this is not possible unfortunately, I have tried many times. I wish `<select>` had native support for empty values & placeholders.
