### ISSUE TITLE
Navigation sidebar tooltip issue with labels containing single quote

### ISSUE THREAD

**Issue by invaders-xx** [laravel-filament/filament#2245]
### Package

filament/filament

### Package Version

v2.11.6

### Laravel Version

v8.83.10

### Livewire Version

v2.10.5

### PHP Version

PHP 8

### Bug description

In ressource, overriding getNavigationLabel function which returns a string containing a single quote like : Types d'entreprises, generate a console error for tooltip label:
```
Alpine Expression Error: Unexpected identifier

Expression: "
                Alpine.effect(() => {
                    if (Alpine.store('sidebar').isOpen) {
                        tooltip = false
                    } else {
                        tooltip = {
                            content: 'Types d'entreprises',
                            theme: Alpine.store('theme') === 'light' ? 'dark' : 'light',
                            placement: document.dir === 'rtl' ? 'left' : 'right',
                        }
                    }
                })
            "
```

**Comment by ryangjchandler** [comment]
I would have expected the `@js` directive to correctly encode this..

**Comment by danharrin** [comment]
> I would have expected the `@js` directive to correctly encode this..

Think we need to PR the fix to Laravel then

**Comment by ryangjchandler** [comment]
It encodes the apostrophe in Unicode, but I guess JS isn't a fan of that.
