### ISSUE TITLE
Breaking change in Table Actions?

### ISSUE THREAD

**Issue by MACscr** [laravel-filament/filament#2256]
### Package

filament/filament

### Package Version

v2.11.8

### Laravel Version

v9.10.1

### Livewire Version

v2.10.5

### PHP Version

8.0.18

### Bug description

When adding the impersonate plugin (https://github.com/stechstudio/filament-impersonate) Action button to the Users table like so:

```php
            ->prependActions([
                Impersonate::make('impersonate'),
            ]);
```

I get the following error: `Typed property Filament\Tables\Actions\Action::$view must not be accessed before initialization`

I was told that https://github.com/laravel-filament/filament/pull/2246 should fix it, but I am fully updated and it doesn't appear to have solved it. Dan asked me to open an issue as it appears to be more a Filament Admin issue/change than the plugin itself.

### Steps to reproduce

See bug description

### Relevant log output

```shell
Filament\Tables\Actions\Action::getView
vendor/filament/tables/src/Actions/Concerns/HasView.php
:39
```

**Comment by ryangjchandler** [comment]
Pretty sure this is fixed in latest release.

**Comment by MACscr** [comment]
> Pretty sure this is fixed in latest release.

I submitted this after the latest release that has the PR mentioned in this issue that supposedly solves it. You can see my my versioning that I should already have it.

**Comment by danharrin** [comment]
stechstudio/filament-impersonate#12
