### ISSUE TITLE
Class "Str" not found

### ISSUE THREAD

**Issue by eminos** [laravel-filament/filament#226]
**Describe the bug**

Class "Str" not found (View: /app/vendor/filament/filament/packages/forms/resources/views/components/field-group.blade.php)

A new Filament installation on an old/upgraded Laravel app.
It's Laravel 8.0 but it has been upgraded for a few years, and I'm suspecting I've missed some Laravel upgrade steps regarding the String helpers.

Anyway, it might be something you might want to fix.

**Comment by eminos** [comment]
Adding `'Str' => Illuminate\Support\Str::class,` to `config/app.php` aliases array, solved this.

**Comment by danharrin** [comment]
Hey, can you ease ensure that the alias is registered in your config like this?

https://stackoverflow.com/a/59503877

**Comment by ryangjchandler** [comment]
@danharrin Think it's safe to close this, user error.

**Comment by danharrin** [comment]
Sure, I'll move it to a discussion.
