### ISSUE TITLE
Bug: Filament\Widgets\StatsOverviewWidget\Card does not render $color

### ISSUE THREAD

**Issue by lhilton** [laravel-filament/filament#2270]
### Package

filament/filament

### Package Version

v2.11.9

### Laravel Version

v9.10.1

### Livewire Version

v2.10.5

### PHP Version

8.0.4

### Bug description

Using the `Card::color()` function is not providing the appropriate color update to the text of the StatsOverviewWidget Card.

### Steps to reproduce

Start from the creation of [stats overview widgets](https://filamentphp.com/docs/2.x/admin/dashboard#stats-overview-widgets), create a class as follows:

```php
<?php

namespace App\Filament\Widgets;

use Filament\Widgets\StatsOverviewWidget as BaseWidget;
use Filament\Widgets\StatsOverviewWidget\Card;

class ColorTestWidget extends BaseWidget
{
    protected function getCards(): array
    {
        return [
            Card::make('Color Test', 'This copy should be red')
                ->color('danger')
        ];
    }
}

```

Register this widget. You will see that the text in the Color Test widget is still default instead of danger (red).

**Comment by lhilton** [comment]
I have submitted PR #2271 that can resolve this issue.

**Comment by danharrin** [comment]
The color is actually on the `->description()` and not the actual number by design:

<img width="1097" alt="Screenshot 2022-05-01 at 15 57 53" src="https://user-images.githubusercontent.com/41773797/166151594-e52c44d0-9b07-47bd-8b86-60281135c444.png">

Apologies for this not being clearer!
