### ISSUE TITLE
Unique fields are counting itself as duplicate when editing

### ISSUE THREAD

**Issue by Xoshbin** [laravel-filament/filament#2279]
### Package

filament/filament

### Package Version

v2.10.44

### Laravel Version

v8.0

### PHP Version

PHP 8.0

### Bug description

I have a form with a "slug" field that should be "unique()", but the issue is I have to change that field with increase or decrease at least a character to be able to save the form because it's counting the field as duplicate, I have to do my changes in the form then edit the unique field to be able to save it, then I have to come back to the form to change the slug back to it's original and save it again.

**Comment by Xoshbin** [comment]
No I'm not using that

**Comment by ryangjchandler** [comment]
@Xoshbin Add that to the field and it should work.
