### ISSUE TITLE
RichEditor does not render in dependable group

### ISSUE THREAD

**Issue by jyrkidn** [laravel-filament/filament#229]
**Describe the bug**
If you add the RichEditor field in a dependable group, you get this once you select the value to show the group.

At the same time the console also throws this error:

```
Uncaught TypeError: cyclic object value
    supportEntangle SupportAlpine.js:88
    value alpine.js:1545
    value alpine.js:1545
    valueMutated alpine.js:1425
    value alpine.js:1113
    value alpine.js:1793
    value alpine.js:1792
    value alpine.js:1787
    value alpine.js:1781
    e alpine.js:1520
    value alpine.js:1614
    value alpine.js:1596
    v alpine.js:90
    v alpine.js:94
    v alpine.js:94
    v alpine.js:94
    v alpine.js:94
    v alpine.js:94
    v alpine.js:94
    v alpine.js:94
    v alpine.js:94
    v alpine.js:94
    v alpine.js:94
    v alpine.js:94
    value alpine.js:1590
    value alpine.js:1607
    e alpine.js:1517
    initializeComponent alpine.js:1911
    e alpine.js:1856
    discoverComponents alpine.js:1870
    discoverComponents alpine.js:1869
    e alpine.js:1855
    l runtime.js:63
    _invoke runtime.js:293
    E runtime.js:118
    f filament.js:1
    a filament.js:1
    promise callback*f filament.js:1
    a filament.js:1
    d filament.js:1
    d filament.js:1
    start alpine.js:1850
    i alpine.js:1940
    deferLoadingAlpine create:716
    dispatch dispatch.js:6
    value index.js:87
    <anonymous> create:721
    EventListener.handleEvent* create:720
SupportAlpine.js:88:37
```

**To reproduce**
1. Make a new resource
2. Add this in the form method
```php
Select::make('type')
    ->placeholder('Select a type')
    ->options([
        'redirect' => 'Redirect',
        'article' => 'Article',
    ])
    ->dependable()
    ->required(),

Group::make([
    TextInput::make('redirect_url')
        ->required(),
])->when(fn ($record) => $record->type === 'redirect'),

Group::make([
    RichEditor::make('content')
        ->required(),
])->when(fn ($record) => $record->type === 'article')
```
3. Create a new item for this resource in your browser 
4. Choose the article type

**Expected behavior**
The RichEditor that renders properly

**Screenshots**
![image](https://user-images.githubusercontent.com/2447042/111373086-c8b09280-869b-11eb-86f3-f893fe0fb1c4.png) 

**Context**
- Package version: 1.6.4
- Livewire version: 2.4.0
- Laravel version: 8.33.0
- Browser: Firefox
- Server OS: PopOS 20.10
- PHP version: 8.0.3
- Database: MySQL 8.0.23

**Comment by jyrkidn** [comment]
After some debugging, I found out that the 'filament-styles:rich-editor-component' and 'filament-scripts:rich-editor-component' contents are not loaded, because on page load the field is not loaded. If I add the contents of both to `resources/views/components/layouts/base.blade.php` it does work.

**Comment by danharrin** [comment]
Can you recache your views and recheck please?

```bash
php artisan view:cache
```

**Comment by jyrkidn** [comment]
@danharrin thanks, recaching the views worked.
