### ISSUE TITLE
Order Not Delete Item Of hasMany

### ISSUE THREAD

**Issue by LuanddFireGroup** [laravel-filament/filament#2291]
### Package

filament/filament

### Package Version

v2.x

### Laravel Version

^9.2

### Livewire Version

v2

### PHP Version

^8.0.2

### Bug description

I build a similar Filament Demo, when I delete a item product in order and save but not working and Form required input after save
![Screen Shot 2022-05-05 at 10 31 52](https://user-images.githubusercontent.com/99637434/166860108-878555ae-ee7c-4342-bae2-59ba0a88e36d.png)
e

**Comment by LuanddFireGroup** [comment]
> 
Hi kamilst96,

In your order have 3 product item , i delete last item by trash icon and click save. But it validate required input. U can test follow me.

**Comment by kamilst96** [comment]
I created repeater the way I was supposed to and it appears to we working nicely. Please provide the steps and code needed to reproduce the problem, as you skipped the **Steps to reproduce** section of the report.

GitHub allows speeding up videos if it's too slow for you, by the way.

https://user-images.githubusercontent.com/37311362/167162693-ee4b362c-5ac1-4cef-a995-2eac2fff0073.mp4

**Comment by danharrin** [comment]
I cannot reproduce this either, clicking the delete button on the repeater item deletes it and means it wont be validated.

**Comment by danharrin** [comment]
If this is an actual issue, please specify specific replication code in a repository.

**Comment by qalainau** [comment]
Hi! The same problem occurs in your demo.
![2022-05-09_12-11-05](https://user-images.githubusercontent.com/238779/167334490-ba9329b3-3545-4e95-a2c6-7687952a0a15.gif)

**Comment by LuanddFireGroup** [comment]
> @danharrin The issue exists in demo and is tied to `mask()` method on **qty** input in **OrderResource**, line 88.

Hi Kamilst96

Can U resolve ? Because just Mask  format input and i need format input.
Tks U so much

**Comment by danharrin** [comment]
Hmm right, this is a masking issue. We actually have many other issues with our masking library and we're replacing it in v3. I don't think it's fixable, iMask.js just doesn't seem to play well with Livewire.

If anyone has time and would like to fix the issue, that would be great. But I do not have enough time to work on it - there are other issues & features that really need my time. Sorry about that.
