### ISSUE TITLE
Run filament:upgrade command causes an error

### ISSUE THREAD

**Issue by themahdavi** [laravel-filament/filament#2292]
### Package

filament/filament

### Package Version

2.11.9

### Laravel Version

9.10.1

### Livewire Version

2.10

### PHP Version

8.1.5

### Bug description

When Run `php artisan filament:upgrade` if haven't `app\Http\Livewire` directory causes an error 
![image](https://user-images.githubusercontent.com/31320104/166860848-23980ba6-7b3b-43b8-8478-e7c309b1282b.png)

I think in file [UpgradeCommand.php](https://github.com/laravel-filament/filament/blob/97f3352597795d108e7c2b94ede68665114fb043/packages/admin/src/Commands/UpgradeCommand.php#L19) command `livewire:discover` looking for Livewire folder in Http.

**Comment by danharrin** [comment]
Fixed by livewire/livewire#4923
