### ISSUE TITLE
Notifications are not showing after v2.10.45

### ISSUE THREAD

**Issue by mxm1070** [laravel-filament/filament#2306]
### Package

filament/filament

### Package Version

v2.11.10

### Laravel Version

v9.11

### Livewire Version

v2.10.5

### PHP Version

8.1.5

### Bug description

I have a multitenant application that I've configured as outlined in my discussion post here #1407. Today I noticed the saved and other notifications not displaying. As far as I can track in the application the notification is still triggering normally it's just not displaying visually. I tracked it back through the versions to see when it first started and the first problem was from v2.10.26 to v2.10.27:

In v2.10.26 everything is fine: 
<img width="1792" alt="Screen Shot 2022-05-06 at 7 38 05 PM" src="https://user-images.githubusercontent.com/11588575/167228986-221d9090-d3a7-4179-9139-a04ccf8ab6e7.png">

In v2.10.27 things start to get a little weird:
<img width="1792" alt="Screen Shot 2022-05-06 at 7 39 03 PM" src="https://user-images.githubusercontent.com/11588575/167229007-47662f99-0f7f-46cb-89df-d20cd0b11904.png">

This persists up to v2.10.42 where I can't load the application anymore because of a weird error:

Method Illuminate\Support\Collection::isActive does not exist.

I don't know why this happens, but I can't load the application on any version after this unless I start a new project. After I start a new project at v2.10.42 everything works fine until v2.10.46 where the notifications stop showing. So it would appear something changed between v2.10.45 and v.2.10.46 that broke this for me. This persists for all future versions. 

The problem is I can't really remove my changes because I have found no other way to support multitenancy. I hope there's a manual configuration change I can make to support this. Any help would be greatly appreciated.

Edit:

I've dug into this further and I can trace the events as far as NotificationManager::handleLivewireResponses() is correct and does dispatch the notification to the $component->dispatchBrowserEvent(); After this I don't know what happens to it. But I do know that inside the notification-manager.blade.php:
```
x-data="{
        notifications: {{ \Illuminate\Support\Js::from(session()->pull('notifications', [])) }},
        add (event) {
            console.log(event.detail);
            this.notifications = this.notifications.concat(event.detail)
            console.log(this.notifications);
        },
        remove: function (notification) {
            this.notifications = this.notifications.filter(i => i.id !== notification.id)
        },
    }"
```
The x-data never gets updated because the session()->pull() is always empty for whatever reason.

### Steps to reproduce

Install filament v2.10.45.
Create a user and user resource with a text input to change the user's name.
Save the form.
This should work fine. 
Modify composer.json. to not autoload filament:
```
"extra": {
        "laravel": {
            "dont-discover": [
                "filament/filament"
            ]
        }
    }
```
Add \Filament\FilamentServiceProvider::class at the end of the providers list in config/app.php.
Update the name again and it should work.
Update filament to v2.10.46.
Try again and it won't work.
Return the app to the original configuration and it should work again.
So clearly something is conflicting between my configuration for multitenancy and the changes in v2.10.46.

**Comment by danharrin** [comment]
1) Make sure your view cache is clear (`php artisan view:clear`)
2) Have you got any overridden views in `resources/views/vendor`

**Comment by mxm1070** [comment]
@danharrin I've tried clearing and that hasn't helped, and I don't have any overridden views.

If you want me to be more clear:

1. laravel new filament
2. cd filament
3. composer require filament/filament:"2.10.45"
4. php artisan migrate
5. php artisan make:filament-user
6. php artisan make:filament-resource User
7. Add TextInput::make('name') to your user resource form
8. Visit /admin, sign in, edit the name of the first user and verify you see the saved notification.
9. In your composer.json: extra.laravel.dont-discover add "filament/filament" to the array.
10. composer update
11. Add \Filament\FilamentServiceProvider::class to the end of your providers array in the config/app.php
12. php artisan view:clear
13. Reload the page and edit the name and save again, you should still see the saved notification.
14. In the composer.json update Filament to use v2.10.46 or later.
15. composer update
16. php artisan view:clear
17. Reload the page and edit the name and save again, you should not see the notification.

If you undo these 2 steps:
1. In your composer.json: extra.laravel.dont-discover remove "filament/filament" from the array.
2. Remove \Filament\FilamentServiceProvider::class from the end of your providers array in the config/app.php
3. composer update
4. php artisan view:clear

It should start working again. If this process didn't produce results for you I can record an exact example or I can provide a bare repo for testing. But these 2 changes are core required changes for my application to work in a multitenant environment. It seems to me like maybe I'm missing a step in setting up Livewire that would normally happen first if I let the service provider auto discover. I just find it really strange that I can trace the correct functionality to the dispatching of the Livewire event, but it does not show up in the x-data of the Livewire component. As far as I can tell v2.10.46 introduced the NotificationManager and the isAfterRedirect detection and these changes seem to be related.

As to why I turned off the auto discovery (more info here #1407), I cannot determine who the current tenant is until the boot phase of my service provider so I cannot use the normal Filament resource discovery because it happens in the register phase and I cannot control what resources are loaded at this point. I fear that this configuration is the cause of the problem, but I also don't see a way around it.

**Comment by danharrin** [comment]
This is a very complex issue very specific replication instructions & a small audience affected, so I am marking this issue as Low Priority.

**Comment by danharrin** [comment]
#1868 was implemented in v2.10.46, so maybe take a look there and work out which part is to blame

**Comment by danharrin** [comment]
Please check if #2341 fixes this, in the new release.

**Comment by mxm1070** [comment]
Thanks for the suggestions and updates! Unfortunately #2341 doesn't seem to fix it. I've gone through #1868 as much as I can and nothing seems wrong besides it just doesn't work for me. Everything up through:
```php
$component->dispatchBrowserEvent('notify', $notifications);
```
seems fine. If I change the line in notification-manager.blade.php from a pull to get:
```php
\Illuminate\Support\Js::from(session()->get('notifications', []))
```
and reload I do see the notification so it seems to me like it's a disconnect with Livewire refreshing and I don't have a ton of experience with it to know what's going on.

**Comment by marcusmyers** [comment]
@mxm1070 Can you tell in your dev tools console tab and see if your `/filament/app.js` file 404's when trying to load it? I think this might be part of your issue as I'm having the same issues as you are having.

**Comment by mxm1070** [comment]
@marcusmyers No I'm not getting any 404's or console errors, and when I compare the working Livewire request to the non working one it looks the same.

**Comment by farhad321** [comment]
I have this problem .but when use swoole( cache php in memory)

**Comment by danharrin** [comment]
Thanks for those details, glad you got it working in the end 👍
