### ISSUE TITLE
Can't install and login: CSRF issue? Might be my config but I'm lost.

### ISSUE THREAD

**Issue by PovilasKorop** [laravel-filament/filament#2328]
### Package

filament/filament

### Package Version

v2

### Laravel Version

v9

### Livewire Version

v2

### PHP Version

8.0

### Bug description

For testing and for publishing some content on Filament, I've installed a totally fresh Laravel project, and totally fresh Filament Admin on top. Created a filament user, but login form gives me 419 error, seems to be related to CSRF.

And it seems to point at Livewire. Is there something else that needed to be configured so Livewire would work?

I've re-read the installation instruction, checked the domains in `.env`, added my domain to the config of Filament (just in case), looked at other issues here on Github, haven't found anything.

<img width="1088" alt="Screenshot 2022-05-09 at 12 21 36" src="https://user-images.githubusercontent.com/1510147/167381508-13ddeac9-a8fe-4471-960b-e605393004bb.png">
<img width="1615" alt="Screenshot 2022-05-09 at 12 22 46" src="https://user-images.githubusercontent.com/1510147/167381524-06103bf9-fdcb-4fe6-a0cf-5178b1b3e227.png">
<img width="1658" alt="Screenshot 2022-05-09 at 12 22 52" src="https://user-images.githubusercontent.com/1510147/167381529-aeb55c2e-1bce-4dad-81f3-b886eab6b56d.png">

I'm using Laravel valet.
Might be some stupid misconfiguration on my part, but currently, I'm lost, any help appreciated.

### Steps to reproduce

Just install a fresh Laravel 9 project and Filament 2 on top.

**Comment by danharrin** [comment]
This is definitely related to Livewire, you can test this out by creating a Livewire component within the project and verifying that the issue also occurs when AJAX requests are sent.

There's some comments here -
https://github.com/livewire/livewire/issues/831#issuecomment-833450176

Make sure `SESSION_DRIVER` is NOT set to array but at least file or redis?

**Comment by danharrin** [comment]
I've just changed the `SESSION_DRIVER` to `array` and I can replicate your issue, so I assume it's that.

**Comment by PovilasKorop** [comment]
@danharrin thanks for the ideas for debugging, I just came back to open laptop after a few hours and... it just works.

I've checked that `SESSION_DRIVER` is `file`, as it was default `.env` from Laravel installation.

So no idea what went wrong. But it works now.
Shrug. Computers need afternoon nap, too, I guess :)

Thanks again for your time.

**Comment by abanghendri** [comment]
Hi Sir, my issue is quite simillar, it already day 4th and I cannot figure out why
so I try to use sanctum for API gateway, sanctum need cookie on session_driver, but when I change session_driver from file to cookie, I cannot login to filament dashboard, it says 419 page expired, and my quasar app doesn't set X-XSRF-TOKEN on the header, so it return 419 also

please help
