### ISSUE TITLE
Textarea::rows method throwing error

### ISSUE THREAD

**Issue by bernhardh** [laravel-filament/filament#2330]
### Package

filament/forms

### Package Version

v2.11.12

### Laravel Version

v9.11.0

### Livewire Version

v2.10.5

### PHP Version

8.0.18

### Bug description

Just added a TextArea and calling the `rows` method:

```php
Forms\Components\Textarea::make('storage_instructions')->rows(2)
```

Getting the error "Undefined variable $concealingComponent". The same without `rows(2)` just works fine.

It has samething to do with the view `vendor / filament / forms / resources / views / components / textarea.blade.php`: https://github.com/laravel-filament/filament/blob/971e3d64194ca408680b8280faf9f9779ebdf152/packages/forms/resources/views/components/textarea.blade.php#L44

**Comment by ryangjchandler** [comment]
@bernhardh Have you recently upgraded?

**Comment by bernhardh** [comment]
I upgraded 1 hour ago or so:

![image](https://user-images.githubusercontent.com/642292/167411604-d814431f-4434-442f-82a3-6ced5d4ff324.png)

**Comment by ryangjchandler** [comment]
Have you cleared your views?

**Comment by bernhardh** [comment]
Issue is fixed with latest release. Thanks!
