### ISSUE TITLE
RelationManager Edit behaviour (Save and Notifications)

### ISSUE THREAD

**Issue by invaders-xx** [laravel-filament/filament#2337]
### Package

filament/filament

### Package Version

v2.12.1

### Laravel Version

v9.11.0

### Livewire Version

v2.10.5

### PHP Version

PHP 8

### Bug description

If you look at the video, you will see the behaviour of the modal and also the notifications at the end when refreshing page.
The behaviour of the "save" button loading state also appears while uploading images.

https://user-images.githubusercontent.com/604907/167545227-fc6492ac-f28c-4426-80f3-fc22794a8765.mp4

https://user-images.githubusercontent.com/604907/167545798-4d190f3f-8935-46f1-8890-b98cf9caadd3.mp4

Console ouput:
<img width="627" alt="image" src="https://user-images.githubusercontent.com/604907/167545426-5b887c1e-ba1a-4cd7-a2f2-46b499e20744.png">

**Comment by themahdavi** [comment]
Yes this problem It happens.
change state of save button to "updating file ..." may take a second after  #2334
but before this pull from @danharrin on Edit not working

**Comment by danharrin** [comment]
Notifications should be fixed by #2341.
