### ISSUE TITLE
RelationManager: use pivot's primaryKey if available

### ISSUE THREAD

**Issue by kamilst96** [laravel-filament/filament#2356]
### Package

filament/filament

### Package Version

v2.12.1

### Laravel Version

v9.11.0

### Livewire Version

v2.3

### PHP Version

PHP 8.1.5

### Bug description

If I create LocationUser with two same location_id and user_id:
| pivot_id | location_id | user_id |
|---|---|---|
| 11 | 2 | 7 |
| 12 | 2 | 7 |

Filament will fail to distinguish between them, assign them user_id for x-model, so they both will be selected for bulk operations. Would it be possible to configure the column used by tables to distinguish records?

My best guess would be to check whether getKey() on pivot returns null, which would be usual for pivot table, and then apply the current logic. If it returns something, use it as key.

Table config as below. All tables have models.

```
User:
- id

Location:
- id
- date_from
- date_to
- is_active

LocationUser:
- pivot_id, PK
- location_id
- user_id
- pivot_date_from
- pivot_date_to
- pivot_is_active
```

### Steps to reproduce

- Create tables as in description
- Treat pivot_id as PK for LocationUser
- Avoid inbuilt `attach() / detach()` methods
- Create two records, bridging the same records

**Comment by danharrin** [comment]
Related to #1804

**Comment by danharrin** [comment]
Please test #2377, the docs for this feature are in the PR.

The primary key on the pivot table needs to be `id`, unless you specify a custom key name on a custom pivot model. Also ensure that `id` (or your pivot key name) is listed in the `withPivot()` array of the relationship AND its inverse relationship.

**Comment by kamilst96** [comment]
It appears to be working, though I failed to use my custom PK, so I removed prefixes from intermediate table. They won't be needed directly anyway if this pulls off, but I'll keep trying.

**Working:**
- Attaching / detaching / editing records.
- Table selector and actions correctly use PK
- Saving pivot data through $record->pivot directly in custom actions

**Issues:**
- For all of this to work, I have to use `Model`, not `Pivot`. Maybe it's just my messed config.
- Pivot's own `id` key masks record's `id`, so creating url links for them is impossible. `Collection::pluck()` is a little confused because of masked `id` allowing duplicates
- There is a pivot available on `$record` now, but I can't access it in columns and inputs, using dot notation,
though it works in custom actions, when injecting the collection.
- You are also using `pivot_` prefixed properties, and removing them before passing record to user. My `pivot_is_active` became `pivot_pivot_is_active`, and still qualified for purging from record, so I was a little confused when I didn't see my keys.

Would it be possible to ditch merging resource with relation and make pivot available with dot notation?
Alternatively, we could have `pivot_` prefixed attributes, and smash then into their relation when saving.

**Comment by francoism90** [comment]
@danharrin I'm confused about this PR:

```php
class Posts extends Model
{
    public function users(): MorphToMany
    {
        return $this->morphToMany(User::class, 'userable')
            ->using(Userable::class)
            ->withPivot(['user_id', 'options'])
            ->withTimestamps();
    }
}

class Userable extends MorphPivot
{
    /**
     * @var string
     */
    protected $primaryKey = 'user_id';

    protected $casts = [
        'options' => AsArrayObject::class,
    ];
}
```
What I'm I missing here?

Thanks!

Edit: to answer my own question; you can define an inverse relationship using: `inverseRelationshipName`. :)
