### ISSUE TITLE
#Migrating to a simple resource error The "--type" option does not exist on make:filament-page command.

### ISSUE THREAD

**Issue by sayasuhendra** [laravel-filament/filament#2379]
### Package

filament/filament

### Package Version

v2.0

### Laravel Version

9.2

### Livewire Version

v2.6

### PHP Version

PHP 8.0.17

### Bug description

php artisan make:filament-page RoomType --resource=RoomTypeResource --type=ManageRecords

![image](https://user-images.githubusercontent.com/4870292/167920839-8f306f90-694a-49d1-ab3a-0b005ec6fe32.png)
![image](https://user-images.githubusercontent.com/4870292/167920939-89835473-7c01-4b8d-ae6f-30441835edef.png)

### Steps to reproduce

[#](https://filamentphp.com/docs/2.x/admin/resources#migrating-to-a-simple-resource)Migrating to a simple resource

php artisan make:filament-page ManageCustomers --resource=CustomerResource --type=ManageRecords

### Relevant log output

```shell
The "--type" option does not exist. 
```
```

**Comment by danharrin** [comment]
Make sure you're on the latest version - `composer update`. This is a new feature.
