### ISSUE TITLE
Able to create related (belongsto) record when In view page

### ISSUE THREAD

**Issue by DanielvdSpoel** [laravel-filament/filament#2381]
### Package

filament/forms

### Package Version

2.12.3

### Laravel Version

9.12.2

### Livewire Version

2.10.5

### PHP Version

8.1.3

### Bug description

Pretty simple, you are able to open the create belongsto record when viewing (not editing) a record

### Steps to reproduce

1) Create a resource with a view and edit page
2) Use the following field:
`                  BelongsToSelect::make('brand_id')
                                    ->relationship('brand', 'name')
                                    ->createOptionForm([
                                        Forms\Components\TextInput::make('name')
                                            ->label(__('forms.labels.name'))
                                            ->required()
                                    ]),`
3) Open record
4) You are able to open the model on the view page

**Comment by StephanMeijer** [comment]
Nor sure if I understand correctly? but do you mean like this? https://twitter.com/danjharrin/status/1524052133057908737
