### ISSUE TITLE
Table view showing raw array for many to many relationships

### ISSUE THREAD

**Issue by JonathanH-UK** [laravel-filament/filament#239]
**Describe the bug**
I've got a many-to-many relationship via a pivot table which I can successfully manage using a Relationship Manager to Add/Attach related objects. 
However when viewing my Resource's table, if I try to display the related object(s), I get a raw array instead.

**To reproduce**
1. Create two models linked with a belongsToMany() relationship via a pivot table (e.g. Products and Orders)
2. Build a filament resource for the Orders model.
3. Either set up a relation manager and link some Products to Orders or seed a couple into the database
4. Back in the Resource, define a table column of `Columns\Text::make('products.title')`

**Expected behavior**
A list of linked object titles (either delimited, or as a bullet list)

**Screenshots**
![image](https://user-images.githubusercontent.com/15343370/111608294-f4816480-87d0-11eb-93b2-691234076eed.png)

**Context**
- Package version: 1.6.4

**Additional details**
Example resourse based on ZoomPolls model with a modules() definition defining the pivot relationship to Modules model:

```
class ZoomPollResource extends Resource
{
    public static $icon = 'heroicon-o-collection';

    public static function form(Form $form)
    {
        return $form
            ->schema([
                Components\TextInput::make('title'),
            ]);
    }

    public static function table(Table $table)
    {
        return $table
            ->columns([
                Columns\Text::make('title'),
                Columns\Text::make('modules.title') // THIS Results in a raw array of the whole object(s) in the table
            ])
            ->filters([
                //
            ]);
    }

```

**Comment by danharrin** [comment]
Ah I actually misunderstood you when you asked this in Discord originally. This isn't a bug really, its a feature that we don't yet have. You can achieve the same using a `products` column and then using `formatUsing()` to `pluck()` the titles from the collection and `implode()` them with a `separator`.

**Comment by johanpaolorodriguez** [comment]
> 
> 
> Has this feature been resolved yet?
