### ISSUE TITLE
Uploading images/files should show loading indicator in "add and save" btn

### ISSUE THREAD

**Issue by Saifallak** [laravel-filament/filament#2390]
### Package

filament/spatie-laravel-media-library-plugin

### Package Version

^2.12.4

### Laravel Version

^9.12.2

### Livewire Version

^2.10.5

### PHP Version

8.0.0

### Bug description

in recent filament updates, you (filament) introduced loading indicator to prevent saving while upload images/files
but it's not applied to "save and add another" btn.

<img src="https://media.discordapp.net/attachments/883085278993068082/974070463896637510/unknown.png">

### Steps to reproduce

just upload any file ( personally using spatie media plugin )

**Comment by danharrin** [comment]
Yeah this is deliberate, displaying "Uploading file" twice in the UI looks ugly. However, the button is still disabled.

**Comment by Saifallak** [comment]
> Yeah this is deliberate, displaying "Uploading file" twice in the UI looks ugly. However, the button is still disabled.

Okay if its intended behavior. I though its a bug 🐛
