### ISSUE TITLE
Filament modals are ignoring configured alignment

### ISSUE THREAD

**Issue by bernhardh** [laravel-filament/filament#2413]
### Package

filament/filament

### Package Version

v2.12.7

### Laravel Version

v9.12.2

### Livewire Version

v2.1.05

### PHP Version

PHP 8

### Bug description

Filament admin is ignoring or not using at all the `filament.layout.forms.actions.alignment` config setting on modals. 

### Steps to reproduce

Set in your filament config the `alignment` to `center`

```php
   'layout' => [
        'forms' => [
            'actions' => [
                'alignment' => 'center',
            ],
        ],
    ],
```

And then open any modal which has a form inside.

#### Expected result: 
The buttons should be centered exactly like the are on regular forms. So  more or less like this:

![image](https://user-images.githubusercontent.com/642292/168134505-a1be2aa1-c22c-413d-957e-48243acf7102.png)

#### Actual result

The buttons are on the left side:

![image](https://user-images.githubusercontent.com/642292/168134431-6d8281bf-13c6-4f72-bec8-5a820666b45c.png)

**Comment by danharrin** [comment]
Fixed by #2415, please confirm

**Comment by bernhardh** [comment]
Now the button alignment is correct. Thanks! 

The only issue now: Why has the button this weird border around it? Looks like it has a focus or something. Or is this a bug from my side?

https://user-images.githubusercontent.com/642292/168250096-a167c339-8be3-4bee-acdc-40a12bf2e443.mp4

**Comment by danharrin** [comment]
I don't believe it's a bug, I think it's default behaviour of x-trap to focus the first button?

**Comment by bernhardh** [comment]
Ok, it looks odd to me. But if its not a bug, but a feature, then I am ok with this :D. Thanks!
