### ISSUE TITLE
Select Fields aren't set to the default value

### ISSUE THREAD

**Issue by ralphjsmit** [laravel-filament/filament#2416]
### Package

filament/forms

### Package Version

2.12.7

### Laravel Version

9.10.x

### Livewire Version

v2.10.5

### PHP Version

8.1.x

### Bug description

I just noticed that it looks like `Select` field don't get set to their default value. 

For example, the below field doesn't get set to the default value for me:

```php
Select::make('test')
    ->options([
        1 => 'One',
        2 => 'Two',
    ])
    ->default(2),
```

Is this a bug or am I missing something?

**Comment by danharrin** [comment]
Hmm, can you try `->default('2')`

**Comment by danharrin** [comment]
Also, just copied your code into my own form and it worked first try

**Comment by ralphjsmit** [comment]
Hm, just copied the code again in the project after booting my Mac and it worked instantly 🫠 Didn't do anything with composer or npm. Testing this was the last thing I did yesterday evening and the first thing I did today. Perhaps a temporary glitch.

**Comment by danharrin** [comment]
Maybe you used `form->fill([])` instead of `form->fill()`?

**Comment by ralphjsmit** [comment]
> Maybe you used `form->fill([])` instead of `form->fill()`?

No, it was in the admin panel, so I'm not manually filling it. Though I think that I know now why this happened. 

It probably failed on the Edit page of a model. This model had `null` as a value for the Select property. I expected the `->default()` to be applied (since no option was yet chosen), but it probably wasn't because the value _is already_ `null`. So probably more a glitch in my mind than a glitch in Filament 🥹
