### ISSUE TITLE
Using multiple Placeholder on one form with the same name leads to error

### ISSUE THREAD

**Issue by riskmate-ac** [laravel-filament/filament#2418]
### Package

filament/forms

### Package Version

v2.12.7

### Laravel Version

v9.12.2

### Livewire Version

v2.10.5

### PHP Version

PHP 8.1.4

### Bug description

When the Placeholder element is used several times in the same form it is not possible to not assign it a name, therefore leaving it with Placeholder::make('').

Doing this throws an error:
```
SQLSTATE[HY000]: General error: 1364 Field 'title' doesn't have a default value 
```

As Placeholders are listed under "Layout" it would be good to have the option simply not naming them but including a content to be displayed. By that you have a lot more possibilities to add specific content that helps to explain forms.

### Steps to reproduce

- Create a form
- Place mutliple Placeholder::make('') in it
- Submit form

Example for an unnamed Placeholder:
```
Placeholder::make('')
                    ->content(new HTMLString('<p class="text-lg font-semibold">General Data</p><p>Blablablabla<span>Blablabla</span></p>')),
```

### Relevant log output

```shell
SQLSTATE[HY000]: General error: 1364 Field 'title' doesn't have a default value
```

**Comment by danharrin** [comment]
Yeah this is deliberate, fields must have a unique name. If you'd like to disable the label, use `->disableLabel()`

**Comment by riskmate-ac** [comment]
Thank you, I did not know about this option - now, it'S one of my favourites!
