### ISSUE TITLE
Uploading a File using FileUpload does not save to the database, if there is a invalid path in the database

### ISSUE THREAD

**Issue by Quadrubo** [laravel-filament/filament#2419]
### Package

filament/forms

### Package Version

v2.12

### Laravel Version

v9.11

### PHP Version

PHP 8.1.2

### Bug description

Uploading a File doesn't save the path to the database, if there is already a path to file that doesn't exist in the database.

- Uploading a File when the column in the Database contains `NULL` is working. 
- Uploading a File when the column in the Database contains a valid path to a File is working.
- Uploading a File when the column in the Database contains an invalid path to a File (File was manually deleted, etc.) is NOT working.

### Steps to reproduce

1) Take any resource with a FileUpload.
2) Manually delete the File from the Server / change the Field in the Database to an invalid filename. 
3) Test if uploading a new File is working...

**Comment by danharrin** [comment]
Fixed by #2487.
