### ISSUE TITLE
TimePicker not working

### ISSUE THREAD

**Issue by joaquin3684** [laravel-filament/filament#2421]
### Package

filament/forms

### Package Version

2.12.7

### Laravel Version

9.12.2

### Livewire Version

2.10.5

### PHP Version

8.1

### Bug description

The time picker is not working.

<img width="1058" alt="image" src="https://user-images.githubusercontent.com/12788242/168314432-0b39107d-f091-4555-8986-855a9d93d3c2.png">

It shows the input to select the time but when i close it. it doesn't update the input with the selected value

**Comment by danharrin** [comment]
Fixed in the upcoming version
