### ISSUE TITLE
DatePicker window should jump to first available date when using minDate()

### ISSUE THREAD

**Issue by AlexJames-Dev** [laravel-filament/filament#2424]
### Package

filament/forms

### Package Version

v2.12.8 

### Laravel Version

v9.12.2

### Livewire Version

v2.10.5

### PHP Version

8.1.5

### Bug description

DatePicker window does not jump to first available date when using the minDate() function

### Steps to reproduce

Create two DatePicker fields, set the first reactive and the second to minDate(fn(callable $get) => $get('first_date')). Assign a date a few months in the future in the first field, then open the second field. The dates will be greyed out, but the will still remain on the current month, rather than jumping to the month with the first available selectable date.

**Comment by danharrin** [comment]
Fixed by #2489
