### ISSUE TITLE
Display the filters above the table

### ISSUE THREAD

**Issue by ishaarany** [laravel-filament/filament#2425]
### Package

filament/tables

### Package Version

v2..0.0

### Laravel Version

v9.2

### Livewire Version

v2..0.0

### PHP Version

PHP 8.0.2

### Bug description

I follow the docs to display the filters above the table as described here  [https://filamentphp.com/docs/2.x/tables/filters#displaying-filters-above-the-table-content](displaying-filters-above-the-table-content]), but Phpstorm shows a message of undefined class "Filament\Tables\Filters\Layout". I try to find this class on vendor package's folder but nothing found.

### Steps to reproduce

* create a resource
* Add filters to table
* add the getTableFiltersLayout() method as mentioned in docs in resource file.

**Comment by danharrin** [comment]
Run `composer update && php artisan filament:upgrade`

**Comment by ishaarany** [comment]
wow It works,
Thank you.
