### ISSUE TITLE
Custom Date Filters not getting reset

### ISSUE THREAD

**Issue by mokhosh** [laravel-filament/filament#2427]
### Package

filament/filament

### Package Version

v2.12.7

### Laravel Version

v9.2

### Livewire Version

v2.6

### PHP Version

php 8.1

### Bug description

i used the example here to create date filters
https://filamentphp.com/docs/2.x/tables/filters#custom-filter-forms
everything works but when i click "reset filters" dates are not reset 

i checked filament admin panel demo and you have a date filter in "orders" page.
https://demo.filamentphp.com/shop/orders
there the reset button works, and dates have a muted default value which prompted me to check what happens if i add a default, and it worked. the only problem is i don't want them to have defaults.

so i added `->default(null)` and now they reset, but this feels like a dirty fix.

also why do the default date on "orders" page have a muted color? are they normal defaults?

### Steps to reproduce

1. create custom date filters for a table just copy pasting the docs example
2. try to reset dates after setting them

**Comment by danharrin** [comment]
Please upgrade to v2.12.9

**Comment by mokhosh** [comment]
worked thanks
