### ISSUE TITLE
Didn't scroll up to field with validation error when press submit button.

### ISSUE THREAD

**Issue by ziming** [laravel-filament/filament#2437]
### Package

filament/forms

### Package Version

2.12.10

### Laravel Version

9.12.2

### Livewire Version

2.10.5

### PHP Version

8.1.5

### Bug description

Thanks for fixing the issue where the collapsed section didn't expand when there is validation error when press submit

https://github.com/laravel-filament/filament/issues/2231

Now the collapsed section did expand upon validation error, however it didn't scroll up to the 1st place/field with the error, leading to users confused as they press the submit button at the bottom of the form but nothing happen. Some of them are tech savvy enough to realise and scroll all the way up, but some also don't and end up close the browser tab in our internal usability testing.

If this can be fixed, it will be great!

**Comment by danharrin** [comment]
Fixed by #2508.
