### ISSUE TITLE
Bug: Date picker doesn't render year and month correctly when autofocus() is set

### ISSUE THREAD

**Issue by Michael-HEIW** [laravel-filament/filament#2446]
### Package

filament/forms

### Package Version

v2.12.2

### Laravel Version

v9.12.1

### Livewire Version

v2.10.5

### PHP Version

PHP 8.0.16 

### Bug description

The year and month does not render correctly when the date picker field is set to `autofocus()` and the field has a default date. The date picker displays in an expanded state, with the correct date but incorrect month and no year.

![image](https://user-images.githubusercontent.com/71503011/168799864-c8cceaf5-255e-4e53-89aa-fdd8c24299ed.png)

As soon as I mouse over the picker the month and year renders correctly. Confirmed with Firefox and Chrome

When I comment out the `autofocus()` the date picker doesn't start expanded, on clicking the date field it does render correctly.

### Steps to reproduce

```php
class Create extends Component implements Forms\Contracts\HasForms
{
    use Forms\Concerns\InteractsWithForms;
    /**
     * @var ?string
     */
    public $start_date;

    /**
     * @var ?string
     */
    public $end_date;

    public function mount(): void
    {

        $this->form->fill([
            'start_date'        => now()->startOfDay(),
            'end_date'          => now()->endOfDay(),
        ]);
    }

    protected function getFormSchema(): array
    {
        return [
            DateTimePicker::make('start_date')
                ->label(__('Start date'))
                ->autofocus()
                ->required(),

            DateTimePicker::make('end_date')
                ->label(__('End date'))
                ->after('start_date')
                ->required(),
];
}
}
```

**Comment by danharrin** [comment]
Fixed by #2504.
