### ISSUE TITLE
BelongsToSelect nullable

### ISSUE THREAD

**Issue by guilebc** [laravel-filament/filament#2458]
### Package

filament/forms

### Package Version

v2.0.0

### Laravel Version

v9.12.2

### Livewire Version

v2.10.5

### PHP Version

PHP 8.1.5

### Bug description

I want to remove the selected category and its value to be "null" in the database.
I don't know if this behavior is normal when I click on the cross that allows you to remove what is selected.
I made a video of the problem to make it easier to understand.

https://www.youtube.com/watch?v=lA3J84asq5M

Just this code
`Forms\Components\BelongsToSelect::make('category_id')->relationship('category', 'name')->searchable()->nullable()`

**Comment by danharrin** [comment]
Fixed by #2488
