### ISSUE TITLE
DatePicker minDate doesn't work when new format date is provided

### ISSUE THREAD

**Issue by lucamago** [laravel-filament/filament#2464]
### Package

filament/filament

### Package Version

 v2.12.10

### Laravel Version

v9.13.0

### Livewire Version

v2.10.5

### PHP Version

PHP 8.1.6

### Bug description

Setting minDate on a DatePicker for example:

`->minDate(now()->subDays(7))`
 
works as expected:

![image](https://user-images.githubusercontent.com/3899577/169151555-8100790c-c2a2-4466-a09b-45a899ebe07d.png)

 but if you also set a new date format for example:

`->minDate(now()->subDays(7))
->format('d/m/Y')`

the date picker not maintain the minDate you passed as value.

![image](https://user-images.githubusercontent.com/3899577/169151602-2cf28369-cbf7-4bbc-9d08-984053e15c34.png)

### Steps to reproduce

- Create a new filament page ( TestDatePicker.php )

`<?php

namespace App\Filament\Pages;

use Filament\Pages\Page;
use Carbon\Carbon;
use Filament\Forms;
use Closure;

class TestDatePicker extends Page
{
    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.pages.test-date-picker';

    protected function getFormSchema(): array
    {
        return [
            Forms\Components\DatePicker::make('datePickerFrom')
                ->minDate(now()->subDays(7))
                // ->format('d/m/Y')
                ->displayFormat('d/m/Y')
                ->required(),
        ];
    }

    public function mount(): void
    {
        $this->form->fill([
            'datePickerFrom' => now()->subDays(2),
            'datePickerTo' => now()->addDays(2),
        ]);
    }
}
`

- Creare a related blade file for that page (test-date-picker.blade.php)

`<x-filament::page>
    <form wire:submit.prevent="submit">
        {{ $this->form }}

        <button type="submit">
            Filter
        </button>
    </form>
</x-filament::page>
`

- You can see that it's not working as expected if you uncomment that part:

`->format('d/m/Y')`

**Comment by danharrin** [comment]
Fixed by #2502.
