### ISSUE TITLE
Rich and Markdown Editors Failed to bind value, show undefined and broken

### ISSUE THREAD

**Issue by aligulzar729** [laravel-filament/filament#2465]
### Package

filament/filament

### Package Version

2.12.8

### Laravel Version

9.13.0

### Livewire Version

2.10.5

### PHP Version

8.1.5

### Bug description

Hey,
So I've discussed about this bug on discord with @danharrin and @iantasker and me confirmed the bug.
The bug is that RichEditor and MarkdownEditor break when using it in versions 2.12.8. 
It show undefined in content, doesn't model/bind the value but works in prior versions.

### Steps to reproduce

1. Changing/locking the version in composer.json
2. `composer update`
3. `php artisan filament:upgrade`
4. `npm run dev`
5. `Force refreshing the browser`

**Comment by danharrin** [comment]
Does #2477 fix this and not introduce any other issues?
