### ISSUE TITLE
RelationGroup cannot switch

### ISSUE THREAD

**Issue by ziming** [laravel-filament/filament#2472]
### Package

filament/filament

### Package Version

2.12.11

### Laravel Version

9.13

### Livewire Version

2.10.5

### PHP Version

8.1.6

### Bug description

I tried to use the new FilamentGroup. But when I go to the edit view

after the main resource it shows

[Physical][Virtual]

Books

Toys

I click on Virtual, it didn't switch too. Also Books and toys are vertically stacked which is not what I expected. What I expected is

[Books][Toys]
Either Book or Toy here shown depending on what is clicked.

[Videos][Songs]
Either Videos or Songs here shown depending on what is clicked

### Steps to reproduce

```php
public static function getRelations(): array
    {
        return [
            //

            RelationGroup::make('Physical', [
                RelationManagers\BooksRelationManager::class,
                RelationManagers\ToysRelationManager::class,
            ]),

            RelationGroup::make('Virtual', [
                RelationManagers\VideosRelationManager::class,
                RelationManagers\SongsRelationManager::class,
            ]),

        ];
    }

```

**Comment by ziming** [comment]
![image](https://user-images.githubusercontent.com/679513/169327980-81a8cd02-1455-4387-a16a-40ea5d0f76a9.png)

**Comment by danharrin** [comment]
Does it work if you take the relation managers out of the groups?

**Comment by ziming** [comment]
Ok so I changed the code to something like this

```php
public static function getRelations(): array
    {
        return [
            //
            RelationManagers\PicturesRelationManager::class,

            RelationGroup::make('Physical', [
                RelationManagers\BooksRelationManager::class,
                RelationManagers\ToysRelationManager::class,
            ]),

            RelationGroup::make('Virtual', [
                RelationManagers\VideosRelationManager::class,
                RelationManagers\SongsRelationManager::class,
            ]),

        ];
    }

```

I now see 3 tabs. Pictures, Physical, Virtual and switching between them worked although it's a little lag. If I move PicturesRelationManager back into the Virtual RelationGroup. It stops working.

Also the display is not how I expected. When I go to Physical tab I see:

[Physical]
Books
Toys

What I expected when I made the initial PR is more like:

![image](https://user-images.githubusercontent.com/679513/169650861-82dbb64f-61dd-40b4-84ee-ef7918da14bd.png)

**Comment by danharrin** [comment]
Oh no, we have previously had requests for "group" functionality where you can render multiple relation managers under the same tab, so either physical or virtual products are displayed. Apologies for misunderstanding your original request.

**Comment by ziming** [comment]
I see okay, but in this case it is still a bug right, you cannot switch from physical to virtual unless a relation manager is 1st level in the array.

**Comment by ziming** [comment]
@danharrin 

It's okay for the misunderstanding, I have since grew to like multiple resources stacked vertically under 1 tab.

Under this context. The bug still remain. If the top level of the relationsManager array are all RelationGroups, you cannot switch tabs. It currently need at least 1 RelationManager.

Meaning this work

```php
[
RelationManager,
RelationGroup([RelationManager, RelationManager]);
RelationGroup,
]
```

But this does not work because at the top level, all are RelationGroup.

```php
[
RelationGroup([RelationManager, RelationManager]);
RelationGroup([RelationManager, RelationManager]);
]
```

**Comment by danharrin** [comment]
Also, could I have a

**Comment by ziming** [comment]
hmm I will try to get back to you on this by next week!

**Comment by ziming** [comment]
Hi Dan, we have tested it.

It only work if 1 of the top level items in the $relationManagers array is a RelationManager and is the 1st item in the array

If the $relationmanager is inside a relationGroup or is 2nd or last in the $relationManagers array it don't work.

Examples:

This works

```php
[
RelationManager,
RelationGroup
RelationGroup
]
```

Meanwhile the following below does not work when trying to switch tabs and there are errors in the browser dev tools console. All RelationGroup has RelationManagers inside.

```php
[
RelationGroup,
RelationManager,
RelationGroup
]
```

```php
[
RelationGroup(RelationManager),
RelationGroup
]
```

```php
[
RelationGroup,
RelationGroup,
RelationManager
]
```

**Comment by Z3d0X** [comment]
Having a reactive resource form seems to be causing the issue
```php
public static function form(Form $form): Form
{
    return $form
        ->schema([
            TextInput::make('name')
                ->reactive(),
        ]);
}


public static function getRelations(): array
{
    return [
        RelationGroup::make('Relations', [
            RelationManagers\PostsRelationManager::class,
            RelationManagers\BooksRelationManager::class,
        ]),
        RelationGroup::make('Another Group', [
            RelationManagers\PostsRelationManager::class,
            RelationManagers\BooksRelationManager::class,
        ])
    ];
}
```

**Comment by danharrin** [comment]
Still couldnt replicate this using the `reactive()` field, then I tested on Chrome.

This bug is only in Chrome, not Safari 😫

**Comment by danharrin** [comment]
Rookie error, the Livewire component keys were not unique for grouped RMs. I fixed it.

#2636
