### ISSUE TITLE
Rich editor with repeater, cancel the the first value

### ISSUE THREAD

**Issue by maherelgamil** [laravel-filament/filament#2476]
### Package

filament/forms

### Package Version

v2.12.11

### Laravel Version

v9.0

### PHP Version

PHP 8.1

### Bug description

I have an issue with Rich editor in repeater when creating new records after updating to the latest version of filament
when adding a new row in for `repeater`, the first row data still appears in the editor, but data is not presented when clicking on create button

![image](https://user-images.githubusercontent.com/6294478/169358543-4d6f59b3-48c2-49ea-be71-821f4c39a6ba.png)

### Steps to reproduce

- add repeater with rich editor field
- navigate to create a new record page 
- try to add data to the first repeater row in its editor
- add a new row add fill it with new data
- try to save, if the field is Required system will mark the first-row editor that's field is required.

### Relevant log output

```shell
the data of the first row is not presented to be save
```

**Comment by danharrin** [comment]
Does #2477 fix this and not introduce any other issues?

**Comment by maherelgamil** [comment]
@danharrin after pulling this #2477 and trying again, still not work

**Comment by maherelgamil** [comment]
@danharrin it's works fine now
