### ISSUE TITLE
Label for table actions do not take "-"

### ISSUE THREAD

**Issue by riskmate-ac** [laravel-filament/filament#2503]
### Package

filament/tables

### Package Version

v2.12.9

### Laravel Version

v9.12.2

### Livewire Version

v2.10.5

### PHP Version

PHP 8.1.4

### Bug description

When creating a custom table action I like to only have "-" as the label used to appear in the button

### Steps to reproduce

Create a table to a custom page and add the following action to it:
```
            TableAction::make('-')
                ->action(function(Post$record) {
                    $this->record->posts()->attach($record->id);
                })
                ->button()
                ->color('danger')
                ->hidden(function (Post $record) {
                    return !$this->record->posts()->where('post_id', $record->id)->exists();
                }),
```

Now, no label appears in the button.
Other single character labels work:
```
TableAction::make('A')
TableAction::make('0')
TableAction::make('+')
```

An alternative would be to be able to either
a) have icon-only buttons (and add disableLabel to be applied) or
b) have extraAttributes on the table action to enable customization re CSS.

I am aware that the latter options are rather improvements then fixing the actual bug. also, I am aware that option b) is quite a "cribbed" way to solve things.

**Comment by danharrin** [comment]
The name passed to `make()` is used to generate the label, not the other way round. Names need to be unique and alphanumeric, for identification between actions.

Passing `->label('-')` works here.

```php
TableAction::make('attach')
    ->label('-')
```

**Comment by riskmate-ac** [comment]
Makes total sense, thank you!
