### ISSUE TITLE
Wizard Component Conditionally Hide Steps

### ISSUE THREAD

**Issue by Z3d0X** [laravel-filament/filament#2506]
### Package

filament/forms

### Package Version

v2.12.12

### Laravel Version

v8.83.13

### Livewire Version

v2.10.5

### PHP Version

PHP 8.1.5

### Bug description

So i'm trying to hide a step base on a form value. I've tried using `->hidden()` with a closure on the step. It hides the step, however it doesn't change the 'Next' button to 'Create'. See attached video below

https://user-images.githubusercontent.com/75579178/169693756-c40eed90-1f6c-40b8-b898-447801705643.mov

### Steps to reproduce

```php
protected function getSteps(): array
{
    return [
        Step::make('Basic Information')
            ->schema([
                Select::make('type')
                    ->reactive()
                    ->disablePlaceholderSelection()
                    ->options([
                        'business' => 'Business',
                        'personal' => 'Personal',
                    ]),
            ]),
        Step::make('Business Details')
            ->hidden(fn (Closure $get) => $get('type') === 'personal')
            ->schema([
                TextInput::make('business_specific_field'),
            ]),
    ];
}
```

**Comment by danharrin** [comment]
Fixed by #2618.
