### ISSUE TITLE
RichEditor overflow when attaching an item  

### ISSUE THREAD

**Issue by emieleke** [laravel-filament/filament#2514]
### Package

filament/filament

### Package Version

v2.12.13

### Laravel Version

v9.13.0

### Livewire Version

v2.10.5

### PHP Version

PHP 8.0.2

### Bug description

RichEditor overflow while attaching an item 

### Steps to reproduce

Create a belongs to many relation and attach an item using RichEditor

**Comment by danharrin** [comment]
Does #2529 fix this?
