### ISSUE TITLE
Create notification not shown on resource with relations

### ISSUE THREAD

**Issue by sten** [laravel-filament/filament#2547]
### Package

filament/filament

### Package Version

v2.12.16

### Laravel Version

v9.14.0

### Livewire Version

v2.10.5

### PHP Version

PHP 8.0.18

### Bug description

When you create a new resource with defined relations (in `getRelations()`) the notification that it is created is not shown.
If you set a redirection url with `getRedirectUrl()` in the `CreateRecord` page to go back to the index, the create notification is shown.

When you create a resource without relationships it also works. It appears to have something to do with the rendering of the relationships on the edit page.

**Comment by mohameedsherif** [comment]
same isssue

**Comment by danharrin** [comment]
Fixed by #2596.
