### ISSUE TITLE
NotificationManager don't cleanup in Octane

### ISSUE THREAD

**Issue by TFSThiagoBR98** [laravel-filament/filament#2569]
### Package

filament/filament

### Package Version

v2.12.17

### Laravel Version

v9.14.1

### Livewire Version

v2.10.5

### PHP Version

8.0.16

### Bug description

Filament\NotificationManager uses a static variable '$notifications' that is not flushed between requests, causing the same notification to show again.

**Comment by danharrin** [comment]
Thanks for the report. Can you submit a PR to fix this? Maybe we need to bind NotificationManager to the container as a facade, instead of a static class.

**Comment by TFSThiagoBR98** [comment]
@danharrin Done, can you please review it?
