### ISSUE TITLE
Protected static $tittle is not working

### ISSUE THREAD

**Issue by otavio-araujo** [laravel-filament/filament#2591]
### Package

filament/filament

### Package Version

2.0

### Laravel Version

9.0

### Livewire Version

2.0

### PHP Version

PHP 8.1.5

### Bug description

I've set the $title property on a page but it's not working when rendered.

![image](https://user-images.githubusercontent.com/30505243/170825660-2276f44b-4aed-42b9-b237-080218a6139a.png)

![image](https://user-images.githubusercontent.com/30505243/170825693-8deb9c04-9780-4dce-a3cb-abd1f168ce0a.png)

Every others customizations are working just fine.

**Comment by themahdavi** [comment]
Hi
$title attribute not for thing you mentioned.
Just for which column for searching . Define like name column for search result.

Use $label and $puralLabel for labels of your resource.

**Comment by danharrin** [comment]
The $title needs to be on the Page class, not the Resource class

for example List, Create or Edit

**Comment by otavio-araujo** [comment]
> Hi $title attribute not for thing you mentioned. Just for which column for searching . Define like name column for search result.
> 
> Use $label and $puralLabel for labels of your resource.

Thank you so much!

Im not a pro dev, but, i like learning and i really like laravel, TALL and Filament.

Im getting there!

Thanks!

**Comment by otavio-araujo** [comment]
> The $title needs to be on the Page class, not the Resource class
> 
> for example List, Create or Edit

Thank you so much!

Im not a pro dev, but, i like learning and i really like laravel, TALL and Filament.

Im getting there!

Thanks!
