### ISSUE TITLE
Markdown form text selected on Firefox is off by some pixels

### ISSUE THREAD

**Issue by minthemiddle** [laravel-filament/filament#260]
**Describe the bug**
When using the Markdown editor on the latest Firefox, when editing text, you can't select the proper text but there's a visual offset and you cannot edit the text.

**To reproduce**
1. Go to any resource with defined markdown form component
2. Click on edit 
3. Select text and try to edit

**Expected behavior**
The existing text is on the same visual line as the selected text

**Screenshots**
<img width="468" alt="Bildschirmfoto 2021-03-21 um 10 39 11" src="https://user-images.githubusercontent.com/1950766/111901912-08300380-8a3b-11eb-8b25-2d100cc2f6e3.png">

**Context**
- Package version: [v1.7.2]
- Livewire version: [v2.4.0]
- Laravel version: [v8.33.1]
- Browser: [Firefox 86.0.1 (64-bit)]
- Server OS: [MacOS]
- PHP version: [e.g. 8.0.3]
- Database: [SQlite]

**Additional details**
Add any other details about the problem here.

**Comment by danharrin** [comment]
I can replicate this on Safari too.

**Comment by danharrin** [comment]
Closed by #263.
