### ISSUE TITLE
DatePicker now breaks without config date format

### ISSUE THREAD

**Issue by DanjBethel** [laravel-filament/filament#2609]
### Package

filament/forms

### Package Version

2.12.21

### Laravel Version

9.14.1

### Livewire Version

2.10.5

### PHP Version

8.1.5

### Bug description

Before updating to v.2.12.21, DatePicker component worked without specifying a display format. Now it needs a format specified in the config or on the component to work. This is from the "DateTimePicker" class, as you can see it just attempts to return the config value, but if there isn't any it returns null. Perhaps the default config should be updated? :

```
    public function getDisplayFormat(): string
    {
        $format = $this->evaluate($this->displayFormat);

        if ($format) {
            return $format;
        }

        if (! $this->hasTime()) {
            return config('forms.components.date_time_picker.display_formats.date');
        }

        if (! $this->hasDate()) {
            return $this->hasSeconds() ?
                config('forms.components.date_time_picker.display_formats.time_with_seconds') :
                config('forms.components.date_time_picker.display_formats.time');
        }

        return $this->hasSeconds() ?
            config('forms.components.date_time_picker.display_formats.date_time_with_seconds') :
            config('forms.components.date_time_picker.display_formats.date_time');
    }
```

Here is the error

```
Filament\Forms\Components\DateTimePicker::getDisplayFormat(): Return value must be of type string, null returned
```

### Steps to reproduce

Just use a DatePicker component in your form. Didn't change anything. Just updated the filament/forms package. Was working fine before.

**Comment by danharrin** [comment]
As mentioned on Discord, fixed by removing /vendor and clearing the config cache, but we should look at adding defaults to these `config()` calls.
