### ISSUE TITLE
`HasManyRepeater` with more than one field inside cannot be deleted.

### ISSUE THREAD

**Issue by johncarter-** [laravel-filament/filament#2622]
### Package

filament/filament

### Package Version

v2.12.22

### Laravel Version

v9.11

### Livewire Version

v2.10.5

### PHP Version

v8.1.5

### Bug description

When you add more than one field to a `HasManyRepeater` container and delete all records leaving an empty `$items` array, you get a MySQL Integrity Constraint exception, saying a column cannot be null.

See this 
https://github.com/johncarter-/filament-has-many-repeater-bug/blob/main/app/Filament/Resources/QuestionResource.php#L43-L46

### Steps to reproduce

![chrome_T62ZRuMST2](https://user-images.githubusercontent.com/3776888/171268697-86bf243c-7ece-4ffd-8daf-925eb7d8fcc6.gif)

- Clone this repo: https://github.com/johncarter-/filament-has-many-repeater-bug/
- Create Filament user
- Log into Filament admin
- Go to Questions and create a new question **with no replies**.
- Edit the record to add a reply
- Save
- Refresh the page
- Delete the reply
- Save
- See exception error

**Comment by danharrin** [comment]
Fixed by #2638.
