### ISSUE TITLE
Login Screen shows uploading... when alpine not intitized yet

### ISSUE THREAD

**Issue by Saifallak** [laravel-filament/filament#2643]
### Package

filament/filament

### Package Version

^2.12.24

### Laravel Version

^9.12.2

### Livewire Version

^2.10.5

### PHP Version

8.0.0

### Bug description

see in this video. https://cdn.discordapp.com/attachments/883085267383226478/981924810147889192/video0.mov

it says uploading on the login screen..
for some secs and then shows a normal sign in

Dennis suggested `That’s because Alpine isn’t initialized yet. Maybe x-cloak could solve this? 🤔`

but I have no experience with alpine to solve it.

### Steps to reproduce

on a new browser (or incognito window / or disable cache)..

### Relevant log output

```shell
-
```

**Comment by danharrin** [comment]
Fixed by #2665.
