### ISSUE TITLE
Bug in MakePageCommand

### ISSUE THREAD

**Issue by jahazzz** [laravel-filament/filament#2659]
### Package

filament/filament

### Package Version

2.12.24

### Laravel Version

9.16

### Livewire Version

2.10.15

### PHP Version

8.1

### Bug description

Hi there,

If I create a custom page for a resource with the artisan command, the generated page class extends Page but import Filament\Resources\Pages\custom

![Capture d’écran 2022-06-04 à 08 15 33](https://user-images.githubusercontent.com/2676572/171987189-6d9c7fd4-3cb4-4c87-a57a-3a933f65a5e8.png)

I think that the line 100 in MakePageCommand.php should be

`'baseResourcePage' => 'Filament\\Resources\\Pages\\' . ($resourcePage === 'custom' ? 'Page' : $resourcePage),`

instead of 

`'baseResourcePage' => 'Filament\\Resources\\Pages\\' . $resourcePage,`

### Steps to reproduce

php artisan make:filament-page SortUsers --resource=UserResource --type=custom

**Comment by danharrin** [comment]
Fixed by #2664.
