### ISSUE TITLE
Modal buttons not visible on mobile

### ISSUE THREAD

**Issue by MakiDizajnerica** [laravel-filament/filament#2661]
### Package

filament/filament

### Package Version

v.2.0.0

### Laravel Version

v8.0.0

### Livewire Version

v2.0.0

### PHP Version

v8.0

### Bug description

When modal gets opened on the mobile it is fixed to bottom of the screen and buttons are not visible then.

**Comment by danharrin** [comment]
Screenshot? Fixing to the bottom of the screen is deliberate, but the buttons should be visible.

**Comment by MakiDizajnerica** [comment]
![Screenshot_20220604-125247_Chrome.jpg](https://user-images.githubusercontent.com/30375048/171996002-02073894-0edf-4ea9-94ab-e6b1220c406e.jpg)

**Comment by danharrin** [comment]
Which browser is this?

**Comment by MakiDizajnerica** [comment]
Its Chrome v101.0.4951.61

**Comment by danharrin** [comment]
On mobile?

**Comment by MakiDizajnerica** [comment]
Yes, Android 12, One UI v4.1

**Comment by danharrin** [comment]
Just tested this on Android Chtome, you need to scroll up so that the address bar is not visible. Not sure how we would fix this with CSS...

**Comment by MakiDizajnerica** [comment]
That works, I know there is problems with overflow on Chrome when bar is visible. Maybe fix it to the top on mobile, and leave overflow on default. Users wont be able to scroll page when modal is opened if it expands to the whole screen and if modal is higher that the screen it will be scrolled instead of the page.

**Comment by danharrin** [comment]
The reason why it is on the bottom on mobile, is because the bottom of the screen is the most accessible to your fingers when using a phone.

**Comment by MakiDizajnerica** [comment]
I get that, its totally understandable. But I assume there will be no interactive modules that have buttons above the middle of the screen right? In my projects I put interactive modules fixed at the top, and dialog modules in the center so the buttons are always below the middle of the screen where pretty much anyone can reach them.

**Comment by danharrin** [comment]
So you're suggesting that we align them in the center on mobile instead?

**Comment by MakiDizajnerica** [comment]
Well, yes. Set dialog modals in center (ones like delete action confirmation) and the form modals (modals that may be bigger that the screen) at the top. You will have visual difference and for the bigger modals you wont have bugs with the overflow if you fix them at the top.

**Comment by danharrin** [comment]
#2663

**Comment by HomaEEE** [comment]
Same problem with safari iOS and iPadOS
![8B981A63-DD10-4B25-9E7B-90CC6AFCE6D4](https://user-images.githubusercontent.com/1429343/177887649-7bef2ad7-d6c3-4346-8f86-fafe778b8012.jpeg)
