### ISSUE TITLE
RelationGroup doesn't work thru PluginServiceProvider

### ISSUE THREAD

**Issue by jahazzz** [laravel-filament/filament#2676]
### Package

filament/filament

### Package Version

2.12

### Laravel Version

9.16

### Livewire Version

2.10.15

### PHP Version

8.1

### Bug description

In a resource, I have:
```php
public static function getRelations(): array
  {
      return [
          RelationGroup::make('Orders', [
              RelationManagers\OrdersRelationManager::class
          ]),
      ];
  }
```
And it gives me:
![Capture d’écran 2022-06-06 à 15 42 53](https://user-images.githubusercontent.com/2676572/172173571-bdb730d2-519b-4c62-b615-c5acaf9eb6e4.png)

**Comment by danharrin** [comment]
Fixed by #2699.
