### ISSUE TITLE
Button shows loading indicator when alpine not initialized yet

### ISSUE THREAD

**Issue by NathanaelGT** [laravel-filament/filament#2686]
### Package

filament/filament

### Package Version

v2.12.27

### Laravel Version

v9.13.0

### Livewire Version

v2.10.5

### PHP Version

PHP 8.1.2

### Bug description

Related to #2643 and #2665

https://github.com/laravel-filament/filament/blob/683d52cbe362d4e1e9913826efabc81832017525/packages/support/resources/views/components/button.blade.php#L107 and https://github.com/laravel-filament/filament/blob/683d52cbe362d4e1e9913826efabc81832017525/packages/support/resources/views/components/button.blade.php#L117 is useless

because laravel compile blank component attribute value into its name, so these lines will be compiled into `x-cloak="x-cloak"`

the simplest way I can think to fix this is to change
https://github.com/laravel-filament/filament/blob/2e38df333b85989490833d2db0405055e178b6e7/packages/admin/resources/views/components/layouts/base.blade.php#L29
into
```css
[x-cloak=""], [x-cloak="x-cloak"], [x-cloak="1"] { display: none !important; }
```

another way is to change **all** `x-cloak` on all blade components to `x-cloak=""`

**Comment by danharrin** [comment]
Thanks for the solution
