### ISSUE TITLE
Route [filament.form-attachments.upload] not defined.

### ISSUE THREAD

**Issue by leo-unglaub** [laravel-filament/filament#269]
Hey,
since the update to `v1.7.4` i am getting the following error when i want to run an artisan command:
```sh
Route [filament.form-attachments.upload] not defined.
```
Is this a bug or just a caching issue?

**Comment by danharrin** [comment]
Hey, can you try clearing your routes cache please?

**Comment by yob-yob** [comment]
Hi, @danharrin I see that for most of the `route not defined` errors, a quick fix is to just clear the cached routes.

#86 #65 

have you ever known the cause of this issue? if it's fixable?
if not then maybe we should add this to the documentation?

**Comment by danharrin** [comment]
> Hi, @danharrin I see that for most of the `route not defined` errors, a quick fix is to just clear the cached routes.
> 
> #86 #65
> 
> have you ever known the cause of this issue? if it's fixable?
> if not then maybe we should add this to the documentation?

As far as I know, Laravel's caching relies on checking when files in your app were last updated. This does not apply to packages, so caching does not behave well.

We should add cache clearing commands to an upgrade guide in the documentation.

**Comment by DannyvdSluijs** [comment]
Ran into this same issue as well. Quick search of the issues led to this report. 
I was unable to clear the cache as the error was repeating itself over and over. After manually deleting the files in `./bootstrap/cache/` it was gone and I could successfully do a `composer install filament/filament`

Perhaps the cleaning of the cache can be automated with [composer scripts](https://getcomposer.org/doc/articles/scripts.md) running before the install ensuring during a fresh install no cache issues can be one of the first things you encounter when trying the package? If you can confirm I can draft a PR.

**Comment by danharrin** [comment]
I've suggested this to @ryangjchandler before - this seems to be a mainstream issue when we change routes, should we add `route:clear` to the composer update scripts?

**Comment by danharrin** [comment]
We've removed the call that causes issues in #272.
