### ISSUE TITLE
using ``Forms\Components\Placeholder`` don't let state change

### ISSUE THREAD

**Issue by saade** [laravel-filament/filament#2707]
### Package

filament/forms

### Package Version

v2.12.24

### Laravel Version

v9.15.0

### Livewire Version

v2.10.5

### PHP Version

8.1

### Bug description

When using a Placeholder component with the same name as one of the form input name, the state does not get updated.

eg:
```php
DateTimePicker::make('send_at'),
Placeholder::make('send_at')
    ->label('Sending date')
    ->content(fn (?Model $record) => $record ? $record->send_at->diffForHumans() : '-'),
```

https://user-images.githubusercontent.com/14329460/172764623-2bca00d9-f99d-4f7b-9417-9241edb41c18.mov

### Steps to reproduce

```php
DateTimePicker::make('send_at'),
Placeholder::make('send_at')
    ->label('Sending date')
    ->content(fn (?Model $record) => $record ? $record->send_at->diffForHumans() : '-'),
```

**Comment by danharrin** [comment]
Form component names must be unique, so name the placeholder `formatted_send_at` or something
