### ISSUE TITLE
Checkbox does not work in form view

### ISSUE THREAD

**Issue by minthemiddle** [laravel-filament/filament#271]
**Describe the bug**
The checkbox always shows as checked in the forms view and does not allow changing the underlying boolean.

**To reproduce**
1. Clone repo: https://github.com/minthemiddle/filament-checkbox
2. `composer install`
3. Set up `.env`
3. `php artisan migrate:fresh -seed`
4. `php artisan make:filament-user`
3. Log into `filament-checkbox.test/admin`
4. See red boolean in table view
5. Go to form view
6. All checkboxes are checked
7. Switching the checkbox
8. Save checkbox
9. See no changes in boolean data
5. Or watch this video: https://www.loom.com/share/c4bcb3eb33a34c7d94cb8ef76f844f32
6. Or clone repo and try yourself: 

**Expected behavior**
1. Save checkbox
2. See changes in boolean data and visual checkbox

**Screenshots**
See: https://www.loom.com/share/c4bcb3eb33a34c7d94cb8ef76f844f32

**Context**
- Package version: [v1.7.4]
- Livewire version: [v2.4.0]
- Laravel version: [v8.33.1]
- Browser: [Firefox 86.0.1]
- Server OS: [Mac OS 10.15.7]
- PHP version: [8.0.3]
- Database: [sqlite]

**Additional details**
Add any other details about the problem here.

**Comment by Tiagofv** [comment]
Hi.
I've noticed your App\Models\Post.php doesnt have the fillable property set. I think if you add, it will work.
`
protected $fillable = ['published'];
`

**Comment by minthemiddle** [comment]
Hi, I added the `fillable` and it does not make any difference. I have had the problem in another project where I have been having the fillable as well. 

It works with a `select` with values `0|1`, so I guess something else is off.

Related to: https://github.com/laravel-filament/filament/discussions/262

**Comment by minthemiddle** [comment]
Tried it with `protected $guarded = [];` but no luck either. It works with a `select` so the attribute is fillable but not with the form checkbox.

**Comment by ryangjchandler** [comment]
@minthemiddle Can you try adding a `boolean` cast to the column please.

**Comment by minthemiddle** [comment]
@ryangjchandler Thanks, that solves it:

For reference for others who are struggling:

```
class Post extends Model
{
    …
    protected $casts = [
        'published' => 'boolean',
    ];
   …
}
```
