### ISSUE TITLE
getVisibility does not exist in SpatieMediaLibraryImageColumn when displaying image in table

### ISSUE THREAD

**Issue by razisek** [laravel-filament/filament#2726]
### Package

filament/spatie-laravel-media-library-plugin

### Package Version

2.0.0

### Laravel Version

9.14.1

### Livewire Version

2.10.5

### PHP Version

8.1.2

### My Form
```php
public static function form(Form $form): Form
{
    return $form
       ->schema([
              SpatieMediaLibraryFileUpload::make('image')
                  ->collection('menu-image')
                  ->acceptedFileTypes(['image/png', 'image/jpg', 'image/jpeg'])
                  ->columnSpan('full')
                  ->required(),
....
```

### Table
```php
public static function table(Table $table): Table
{
        return $table
            ->columns([
                SpatieMediaLibraryImageColumn::make('image')
                    ->collection('menu-image'),
....
}
```
but i get the following error

![image](https://user-images.githubusercontent.com/33994563/173094079-8a45eb42-40f3-40f2-915d-94f0b2d633cc.png)

any solution ?

### Relevant log output

```shell
https://flareapp.io/share/xPQkjO15#F98
```

**Comment by danharrin** [comment]
Ensure you have the same Filament & plugin version installed

**Comment by danharrin** [comment]
Can you run `composer update`?

**Comment by danharrin** [comment]
We had this issue reported yesterday, and the problem was that the main Filament package was just out of date

**Comment by razisek** [comment]
solved, with updated version
