### ISSUE TITLE
FileUpload field failed to validate mime type of text/csv

### ISSUE THREAD

**Issue by margarizaldi** [laravel-filament/filament#2730]
### Package

filament/filament

### Package Version

v2.12.28

### Laravel Version

v9.17.0

### Livewire Version

v2.10.5

### PHP Version

PHP 8.0.8

### Bug description

Using `->acceptedFileTypes(['text/csv'])` FileUpload field failed to validate text/csv even without any rules.

![image](https://user-images.githubusercontent.com/26832856/173133750-b829c530-2623-420e-acdd-df844d05d5ec.png)

I'm not sure about the other mime types, but I have no problem with `application/pdf` and `text/plain` .

### Steps to reproduce

Just create a very simple form like this:

```
public static function form(Form $form): Form
{
    return $form
        ->schema([
            Forms\Components\FileUpload::make('filename')
                ->acceptedFileTypes(['text/csv']),
        ]);
}
```

**Comment by danharrin** [comment]
Looks like Laravel validates CSV files as `text/plain` instead of `text/csv` `https://stackoverflow.com/a/35573208`
