### ISSUE TITLE
Undefined variable $getConfig in form Wizard

### ISSUE THREAD

**Issue by razisek** [laravel-filament/filament#2733]
### Package

filament/forms

### Package Version

v2.12.28

### Laravel Version

9.17.0

### Livewire Version

2.10.5

### PHP Version

 8.1.2

### Bug description

I have an error with wizard form

my createrecord code
```php
<?php
class CreateProperty extends CreateRecord
{
    use CreateRecord\Concerns\HasWizard;
}
```

if I delete the trait, the error doesn't appear

```php
<?php
class CreateProperty extends CreateRecord
{
  //  use CreateRecord\Concerns\HasWizard;
}
```

the error detail
![image](https://user-images.githubusercontent.com/33994563/173175442-ad76df17-aa87-42e0-a46b-30024886f3ea.png)

### Relevant log output

```shell
https://flareapp.io/share/NPLpob4P#F95
```

**Comment by danharrin** [comment]
Run `composer update && php artisan filament:upgrade`, and delete any views you have overriden in /resources/vendor/views

**Comment by razisek** [comment]
when run ```php artisan filament:upgrade```, get the error
![image](https://user-images.githubusercontent.com/33994563/173176155-18b9d07d-1742-446d-9631-9c405c04a273.png)

**Comment by danharrin** [comment]
Create the directory, it's a Livewire issue that has been fixed, but the fix has not been released

**Comment by razisek** [comment]
thankss! solved
