### ISSUE TITLE
Masked text input does not update the mask using with reactive

### ISSUE THREAD

**Issue by ysfkaya** [laravel-filament/filament#2745]
### Package

filament/forms

### Package Version

v2.12

### Laravel Version

v9.16

### Livewire Version

v2.10

### PHP Version

PHP 8.1

### Bug description

First of all I'm newbie in the Filament, so I searched this issue in the issue section but couldn't find a solution.

I have a money masked input and a reactivated currency select input.  I want to change the mask currency symbol with given currency code from input. The mask is not updating when currency value is changed.

Schema:

```php
Form\Section::make('Default Price')
    ->schema([
    
        Form\TextInput::make('price')
                  ->mask(function (Form\TextInput\Mask $mask, callable $get) {
                      if ($get('currency')) {
                          $currency = new Currency($get('currency'));
                      } else {
                          $currency = new Currency('USD');
                      }
            
                    return $mask->money($currency->getSymbol(), $currency->getThousandsSeparator(), $currency->getPrecision());
                })->required(),
    
        Form\Select::make('currency')
            ->options(function () {
                return collect(Currency::getCurrencies())->mapWithKeys(fn ($currency, $code) => [
                    $code => $currency['name'],
                ]);
            })->required()->reactive(),
  
])->columns(2),
```

https://user-images.githubusercontent.com/16710972/173304950-30f93531-f3f3-44b6-8200-8b7c13930b29.mov

**Comment by themahdavi** [comment]
Hello
Are you in discord ?
totally iMask package have issue on rendering values and fix this problems on next major release.
if you need masking prefer to use custom View Field and make own field

**Comment by ysfkaya** [comment]
@themahdavi I'm in discord now. I get it and I'll try the ViewField to custom masking. Thank you for information.

Also, is there any release date for the next major release?

**Comment by danharrin** [comment]
v3 will probably be around near the end of this Summer, I expect
