### ISSUE TITLE
KeyValue can not show correct key and value on edit page

### ISSUE THREAD

**Issue by pndx** [laravel-filament/filament#2758]
### Package

filament/filament

### Package Version

v2.12.28

### Laravel Version

v9.17.0

### PHP Version

PHP 8.0.8

### Bug description

Use Forms\Components\KeyValue to save json in to mysql database. it work. then refresh the page and the edit page get wrong key value.

| Key | Value |
| --- | --- |
|0|{|
|1|"|
|2|v|
...
|50|"|
|51|}|

**Comment by danharrin** [comment]
Your column needs an `array` cast in your Model.

**Comment by pndx** [comment]
Thanks a lot. Don't know cast before.This works. @danharrin
