### ISSUE TITLE
Radio inline not working

### ISSUE THREAD

**Issue by webtimal** [laravel-filament/filament#2770]
### Package

filament/forms

### Package Version

v2.12.31

### Laravel Version

v9.17.0

### Livewire Version

v2.6

### PHP Version

PHP 8.1.5

### Bug description

Creating an inline radio button does not work as intended.

```
Radio::make('feedback')
    ->label('Do you like this post?')
    ->boolean()
    ->inline()
```

does lead up the the following output:

![bug](https://user-images.githubusercontent.com/33128507/173679879-24c806c1-1f7b-4afb-bbf8-d9b4fbad9c28.png)

The wrapper seems to always receive the tailwind class `grid-cols-1` no matter the amount of options given.

### Steps to reproduce

1. Create a fresh resource
2. Insert a radio component with the inline method appended

**Comment by danharrin** [comment]
Fixed by #2821.
