### ISSUE TITLE
RelationManager modal issue

### ISSUE THREAD

**Issue by invaders-xx** [laravel-filament/filament#2786]
### Package

filament/filament

### Package Version

v2.13.3

### Laravel Version

v9.17.0

### Livewire Version

v2.10.5

### PHP Version

PHP 8

### Bug description

In a RelationManager, when viewing or editing a relation first time, everything is fine. But if I close the modal and reopen it (edit or view), the table of the RelationManager is refreshing and I have the following error in console:
<img width="660" alt="image" src="https://user-images.githubusercontent.com/604907/173995142-8b90d7a1-ab66-483d-8476-3a658b458142.png">

**Comment by danharrin** [comment]
I assume this doesn't happen with all form components. For example, please test it with just a simple TextInput inside. Which components cause issues for you?

**Comment by invaders-xx** [comment]
It seems that I have this issue with forms having FileUpload (SpatieMedia in my case). Quite similar to #2772

**Comment by danharrin** [comment]
It's probably the same issue, all action modals are the same component

**Comment by invaders-xx** [comment]
What do you mean by "Not planned" : no fix ?

**Comment by danharrin** [comment]
Sorry the GitHub message for that is vague, I marked it as duplicate
