### ISSUE TITLE
Files not removed from disk, only db

### ISSUE THREAD

**Issue by zltn** [laravel-filament/filament#279]
**Describe the bug**
Files not removed from disk, only db

**To reproduce**
1. Create a fileupload component 
2. Upload a file and save
4. Remove the file and save
5. Check the data and folder. Database entry is gone but file remains

**Expected behavior**
File should be deleted right away or a cron job should clean up the folder regularly 

**Context**
- Package version: Latest
- Browser: Safari

**Comment by yob-yob** [comment]
I don't know if cleaning is still part of a CMS's job.

but let me just be clear, on step#3 **remove the file and save** 

you're talking about the feature on Filepond right? where you click on the "remove" button on the file uploader

you're not talking about deleting the whole model?

if so a quick model listener should be good... https://laravel.com/docs/8.x/eloquent#events

listen to an event and based on that event do something...

in the case of your problem.. listen to an "updating" event.. check if the image property value is null or empty and if so.. 
delete the image that was previously used by that model.

I'm not an official developer of Filament or any sort of connection with it.. I'm just suggesting alternative solutions...

**Comment by zltn** [comment]
I'm talking about the file, and was assuming filament would handle removal as they are also handling placement. Similar to how livewire is cleaning the tmp files used during upload  

If the expectation is that I should clean up the file myself let's make sure it's documented

**Comment by yob-yob** [comment]
this package is also using livewire.. so yeah `temp` files are also automatically handled.. your problem thou is not `temp` files. it's those files that are already moved to another directory and saved. livewire doesn't handle that for you.

but yeah, if the expectation is that we should clean it up ourselves then we should add that in the documentation. I agree.

**Comment by danharrin** [comment]
Yeah it's not a good idea for us to remove files that may already be depended on in other places.

**Comment by zltn** [comment]
Cool, I'll use a model listener to clean up. But might be worthwhile documenting that you need to handle this yourself

**Comment by danharrin** [comment]
This has now been [documented](https://filamentadmin.com/docs/forms/#fields-file-upload).
