### ISSUE TITLE
BulkAction gets $records unsorted

### ISSUE THREAD

**Issue by bomshteyn** [laravel-filament/filament#2799]
### Package

filament/tables

### Package Version

v2.13.4

### Laravel Version

v9.17

### Livewire Version

v2.10.5

### PHP Version

8.1

### Bug description

BulkAction gets records in an unsorted order even though the list is sorted.

### Steps to reproduce

Here is the code of my Bulk Action
```PHP
BulkAction::make('export')
    ->icon('heroicon-o-download')
    ->action(fn(Collection $records) => Excel::download(new ProductsExport($records), "products-export.xlsx"))
```

**Comment by danharrin** [comment]
TBH I don't think this is a bug, we never guaranteed that they would be sorted, and I don't understand why a bulk action would ever require them to be sorted.

Anyway, they are sorted now - #2820.

**Comment by bomshteyn** [comment]
@danharrin Thank you. I use the bulk action for generating an Export to CSV, hence the need to sort in the same way as displayed.
