### ISSUE TITLE
More documentation for FileUpload component

### ISSUE THREAD

**Issue by zltn** [laravel-filament/filament#280]
- I've tried using the `imagePreviewHeight("100")` and `imagePreviewHeight("100px")` but no changes to the height in component. Not sure how to use the method
- Same for `getPanelLayout($layout)`, not sure what `$layout` should be

**Comment by yob-yob** [comment]
did you try using integer instead of string?

**Comment by danharrin** [comment]
Hey @zltn, did you try @yob-yob's suggestion?

These are passed directly to [Filepond](https://pqina.nl/filepond/docs/patterns/api/filepond-instance/#properties) btw, might be worth documenting the options.

**Comment by zltn** [comment]
Yeah, tried integers as well. I did get `imageResizeTargetHeight($height)` to work with a number as string without px `"200"`

**Comment by danharrin** [comment]
I've added a link to Filepond's website where the options are listed.
