### ISSUE TITLE
Disable blue tap highlight on mobile Chromium

### ISSUE THREAD

**Issue by kamilst96** [laravel-filament/filament#2846]
### Package

filament/filament

### Package Version

v2.13.7

### Laravel Version

v9.17

### Livewire Version

v2.10.5

### PHP Version

PHP 8.1.7

### Bug description

On mobile devices with Chromium-based browsers, there's a blue highlight when tapping on elements in admin panel.

![1](https://user-images.githubusercontent.com/37311362/174633109-699ccbc7-7450-45d8-83c3-be6a9218e08a.png)
![2](https://user-images.githubusercontent.com/37311362/174633121-7db6ccb1-875d-43b4-96db-b1bf74c3b036.png)
![3](https://user-images.githubusercontent.com/37311362/174633126-de4adb65-e984-4646-a718-6f9237b9926a.png)

While the color can be controlled, the shape can't - round filter focus will have a square highlight. On another hand, it also results in aggressive flashing.

It can be disabled by setting the following, not necessarily on `html` tag:
```css
html {
    -webkit-tap-highlight-color: transparent;
}
```

This functionality doesn't exist in Gecko, so regardless of usability, disabling it will bring consistent experience.

### Steps to reproduce

- Launch admin panel on Chromium-based mobile device.
- Click on links, buttons, etc.

**Comment by danharrin** [comment]
Can you PR this? applying to `html` seems like a good idea
