### ISSUE TITLE
Hooks not triggered when getActions() method exists on ManageResource page

### ISSUE THREAD

**Issue by margarizaldi** [laravel-filament/filament#2870]
### Package

filament/filament

### Package Version

v2.13.8

### Laravel Version

v9.17.0

### Livewire Version

v2.10.5

### PHP Version

PHP 8.1

### Bug description

Hooks like `beforeCreate()` and `afterCreate()` (and probably the other) didn't triggered when `getActions()` exists on `Pages\ManageSomeResource.php` .

Those hooks run perfectly whenever I comment out the `getActions()` method.

### Steps to reproduce

The filament resource was generated using `--simple` flag, I don't know whether this issue also come in "standard" resource or not actually.

The `dd($this)` below isn't executed :

```
<?php

namespace App\Filament\Resources\OrderResource\Pages;

use App\Filament\Resources\OrderResource;
use Filament\Pages\Actions;
use Filament\Resources\Pages\ManageRecords;

class ManageOrders extends ManageRecords
{
    protected static string $resource = ImportOrderResource::class;

    protected function beforeCreate(): void
    {
        dd($this); // <-- nothing happens
    }
}

protected function getActions(): array
{
     return [
        Actions\CreateAction::make(),
     }
}
```

Then below without the existence of `getActions()` , the hook just works :
```
<?php

namespace App\Filament\Resources\OrderResource\Pages;

use App\Filament\Resources\OrderResource;
use Filament\Pages\Actions;
use Filament\Resources\Pages\ManageRecords;

class ManageOrders extends ManageRecords
{
    protected static string $resource = ImportOrderResource::class;

    protected function beforeCreate(): void
    {
        dd($this); // <---- it's shown on the modal
    }
}
```

**Comment by danharrin** [comment]
Yeah this is deliberate, hooks are deprecated on new resources. We have other, cleaner ways to do the same thing now, using modifier() methods on the Action object. Check the docs :)

**Comment by margarizaldi** [comment]
If so, I will be very happy to see where's the section of the docs explaining the modifier() methods on the Action Object but I couldn't find it so far :(
