### ISSUE TITLE
Undefined variable: slot (View: /Users/.../filament/vendor/filament/filament/packages/forms/resources/views/components/textarea.blade.php)

### ISSUE THREAD

**Issue by ShamarKellman** [laravel-filament/filament#29]
**Describe the bug**
Using Textarea form input throws error

**To reproduce**
1. Create a form
2.  add Text area input
` Textarea::make('description') ->placeholder('Description'); `

**Expected behavior**
Renders form with text area

**Screenshots**

**Context**
- Browser: Chrome
- Server OS: Mac OSX
- PHP version: [e.g. 7.4]

**Additional details**
ErrorException
Undefined variable: slot (View: /Users/.../filament/vendor/filament/filament/packages/forms/resources/views/components/textarea.blade.php)
<img width="884" alt="Screen Shot 2021-03-01 at 7 15 58 PM" src="https://user-images.githubusercontent.com/4120411/109571848-ac6cfd00-7ac2-11eb-8e03-e038ed84e0c1.png">

**Comment by ManojKiranA** [comment]
@danharrin i was planning to remove the `$slot` variable from the file because there is no need of the variable inside the component it seems :confused:

**Comment by danharrin** [comment]
Thanks! This has been fixed in v1.0.4.
