### ISSUE TITLE
Sortable not working for table columns

### ISSUE THREAD

**Issue by JamalWill** [laravel-filament/filament#293]
**Describe the bug**
When I attempt to sort on a sortable column I get a `InvalidArgumentException Orderdirection muts be "asc" or "desc"` from the query builder.

**To reproduce**
1. Go to table with sortable column. 
2. Click on column to sort.

**Expected behavior**
Sorted column

**Screenshots**

**Context**
- Package version: v1.8.2
- Livewire version: v2.4.1
- Laravel version: v8.30.0
- Server OS: Ubuntu 18.04.4
- PHP version:7.4
- Database: MySQL 8.0

**Additional details**
I think the error is in /filament/filament/packages/tables/src/Concerns/CanSortRecords.php

getSorts() is returning an associative array with $column => $direction but in applySorting line 125  i believe you expect $sort to be an array as you destructure it on the next line. 

Hope this helps

**Comment by kjunggithub** [comment]
I also have this issue with the latest release.

Reverting it back to this line makes it work again. https://github.com/laravel-filament/filament/commit/3c75d0623177eeb3476516ffdbe007d84de89716

**Comment by danharrin** [comment]
Fixed by #294.
