### ISSUE TITLE
heredoc end issue with forms

### ISSUE THREAD

**Issue by manishlok** [laravel-filament/filament#3]
ErrorException
syntax error, unexpected end of file, expecting variable (T_VARIABLE) or heredoc end (T_END_HEREDOC) or ${ (T_DOLLAR_OPEN_CURLY_BRACES) or {$ (T_CURLY_OPEN) 
(View: $project_path\vendor\filament\filament\resources\views\partials\user-actions.blade.php)
(View: $project_path\vendor\filament\filament\resources\views\partials\user-actions.blade.php)
(View: $project_path\vendor\filament\filament\resources\views\partials\user-actions.blade.php)

**Comment by manishlok** [comment]
Quick fix:
https://michaelheap.com/php-return-and-the-heredoc-syntax/

The issue is that the blade; statement of the heredoc declaration is indented. A closing heredoc statement must start in column 0.

Have to change six files and > remove 2 indents from blade;
$project_path\vendor\filament\filament\src\Http\Components\Form.php : line 57

$project_path\vendor\filament\filament\src\Http\Components\Pill.php : line 20

$project_path\vendor\filament\filament\src\Http\Components\Tab.php : line 38

$project_path\vendor\filament\filament\src\Http\Components\Well.php : line 22

$project_path\vendor\filament\filament\src\Http\Livewire\AuthUserAttribute.php : line 22

$project_path\vendor\filament\filament\src\Http\Livewire\UserAvatar.php : line 22


Should I have made a PR ?

**Comment by ryanscherler** [comment]
I haven’t encountered this error - but yes please do a PR and I will merge it in.

**Comment by ryanscherler** [comment]
What's odd about this issue is that its not documented in the Laravel docs about having to do this. https://laravel.com/docs/7.x/blade#inline-component-views

What is generating this ErrorException? Do you have a test setup that is doing this? I cannot replicate this error on my end.

**Comment by ryanscherler** [comment]
As I suspected, its a PHP version issue. https://laravel-news.com/flexible-heredoc-and-nowdoc-coming-to-php-7-3 (I am going to close out this issue now that the package requires ^7.4
