### ISSUE TITLE
Update `blade-ui-kit/blade-heroicons` to `^1.0`

### ISSUE THREAD

**Issue by Larsklopstra** [laravel-filament/filament#306]
**Describe the bug**
Installing Filament in a project with `blade-ui-kit/blade-heroicons` version `^1.0` will result in a failure.

**To reproduce**
Run have the latest version of `blade-ui-kit/blade-heroicons` and run `composer require filament/filament`.

**Expected behavior**
N/A

**Screenshots**
N/A

**Context**
N/A

**Additional details**
N/A

**Comment by danharrin** [comment]
Closed by #338.
