### ISSUE TITLE
$this->record is empty in isAuthorized function in EditRecord

### ISSUE THREAD

**Issue by tmverkuijlen** [laravel-filament/filament#308]
**Describe the bug**
`$this->record` is empty in `isAuthorized()` function in EditRecord

**To reproduce**
Add a `dd($this->record)` in the `isAuthorized()` function in the EditRecord file.

**Expected behavior**
The `$this->record` should be filled so you can properly check if you can edit the model.

**Context**
- Package version: 1.8.3
- Livewire version: 2.2
- Laravel version: 8.35

**Comment by AnasT** [comment]
This is due to the fact that the [authorization check](https://github.com/laravel-filament/filament/blob/main/src/Pages/Page.php#L27) is done before the livewire component __invoke call.

**Comment by danharrin** [comment]
Fixed by #339.
