### ISSUE TITLE
TagsInput component not saving in the database

### ISSUE THREAD

**Issue by monoman81** [laravel-filament/filament#321]
**Describe the bug**

The TagsInput component is not saving the value in the database neither in the CreateRecord or EditRecord actions

**To reproduce**

Have a table products with a field named 'tags' of type string(255)

`$table->string('tags')->nullable()`

In ProductResource:

```
public function form(Form $form)
{
      return $form->schema([
            
            /* other model's fields */

            Components\TagsInput::make('tags')
                 ->label('Product Tags')
                 ->placeholder('Enter one or more product tags for an easy search')
                 ->separator(','),
      ]);
}
```

**Expected behavior**

The TagsInput value should be saved in the products' tag field 

**Context**

- Package version: 1.8.3
- Livewire version: 2.4.2
- Laravel version: 8.35.1
- Browser: Chrome
- Server OS: Windows 10 (Laragon)
- PHP version: 7.4.7
- Database: 5.7.24

**Additional details**

The TagsInput field seems to be mapped correctly with the database field, because, if i enter manually a value for the field (i.e. in MySql Workbench) and go the EditRecord page, the tags are showed correctly and even i am able to delete tags and the deleted values are deleted in the database.

**Comment by monoman81** [comment]
In the filament discord server i got the solution from someone, or better said, the why my field wasn't saving in the database. It is needed to hit ENTER when you are done filling the input, otherwise the tags are not set to save. Just changing the focus of the input with the TAB key or with the mouse do not do the trick. 

I believe i should close this issue as is not a bug, but an UI implementation. What do you guys think?

**Comment by danharrin** [comment]
Yeah, this is desired behaviour. If you can think of ways to make it clearer, please open a discussion 👍 Thanks!
