### ISSUE TITLE
Bug when create related for 2nd time in a row

### ISSUE THREAD

**Issue by sebapastore** [laravel-filament/filament#355]
**Describe the bug**
When trying to create a related item using the Relation Manager, the first time is OK. The second time it gets an error: "Illuminate\Database\Eloquent\Relations\HasOneOrMany::create(): Argument #1 ($attributes) must be of type array, App\Models\MyModel"

**To reproduce**
1. Create a Resource; i.e: ```php artisan make:filament-resource Customer```
2. Create a relation manager; i.e: ```php artisan make:filament-relation-manager CustomerResource orders```
3. Configure the resource and the relation manager in order to make them work
4. Create a Customer
5. Go to Edit Customer
6. In the relation list create an order (save without using the "Create & Create Another" option)
7. Get back to the relation list and create another order and you will get an error

**Expected behavior**
The second order should be created without an error.

**Context**
- Package version: 1.9.3
- Livewire version: 2.3
- Laravel version: 8.37
- Browser: Tested in Chrome, Safari and Firefox
- PHP version: 8.0
- Database: MySQL 8.0

**Comment by danharrin** [comment]
Fixed by #356.
