### ISSUE TITLE
Bug when using FileUpload twice inside a relation controller

### ISSUE THREAD

**Issue by marcomessa** [laravel-filament/filament#366]
**Describe the bug**
When using FileUpload field inside a relation controller, files are correctly saved but both fields display the same file/image. This is not happening outside the relation controller

**To reproduce**
1. Create two related models
2. Create both the resources and and relation manager
3. Insert two FileUpload fields in the form and fill them with two different files
4. In the relation manager, you'll see only the latter's preview. In the resource form, previews are displayed flawlessly.

**Expected behavior**
I expect two different previews, one for each FileUpload

**Screenshots**
![relation_manageR_form](https://user-images.githubusercontent.com/4236142/115156196-61fc0b80-a083-11eb-8c9e-20e058169ae2.jpg)
![resource_form](https://user-images.githubusercontent.com/4236142/115156199-67f1ec80-a083-11eb-9faa-58997c270c5a.jpg)

**Context**
- Package version: [1.9]
- Livewire version: [e.g. 2.0.0]
- Laravel version: [e.g. 8.37.0]
- Browser: [e.g. Brave, Chrome, Firefox Dev, Safari]
- Server OS: [Osx Valet 2.13.19]
- PHP version: [7.4]
- Database: [MySQL 5.7]

**Comment by marcomessa** [comment]
Confirm this is still presente in 1.9.6

**Comment by danharrin** [comment]
Unfortunately, this is a Livewire bug (livewire/livewire#2583) which we must wait to be fixed. Apologies.

**Comment by danharrin** [comment]
Hi, still no update on the Livewire bug. I'm going to think about this problem and implement an alternative solution in v2 that avoids the bug. Sorry about that!

**Comment by marcomessa** [comment]
Thanks for the update @danharrin! If you have some idea of the right direction I'll be glad to help!
