### ISSUE TITLE
Define a link name different than the url

### ISSUE THREAD

**Issue by codedge** [laravel-filament/filament#368]
**Describe the bug**
I want to specify a link name different from the url. Using the `url()` method this is not possible, as it only except the field value and the boolean to open it in a new tab.

I have long urls in a column and don't want to show the long url, instead I want to show the name a link name.

**To reproduce**
Create a table column with `Columns\Text::make('github_url')->url(fn ($record) => $record->github_url, true)`

**Expected behavior**
A third parameter `linkName` would be a way to specify a link name.

**Context**
- Package version: 1.9.3

**Comment by danharrin** [comment]
Hey! This is already possible, by specifying a callback as the first parameter of `formatUsing()`. For example:

```php
Columns\Text::make('github_url')
    ->formatUsing(fn () => 'GitHub')
    ->url(fn ($record) => $record->github_url, true)
```
