### ISSUE TITLE
Dependant issue on Edit record

### ISSUE THREAD

**Issue by ciamarro** [laravel-filament/filament#375]
Hey, sorry ... #312  is still an issue for me on EditRecord

https://user-images.githubusercontent.com/2736722/115247886-30bc2380-a0f5-11eb-9e91-07c6dfb3fa38.mp4

**Comment by danharrin** [comment]
Hey, this is a complex issue related to a limitation with nested form components. You may fix it by not nesting your fields within layout components, but nesting will be available in v2. Sorry!
