### ISSUE TITLE
Trying to use an icon pack that's not Heroicons, but is listed on Blade UI Kit.

### ISSUE THREAD

**Issue by AlexHaible** [laravel-filament/filament#376]
**Describe the bug**
Filament doesn't seem to recognize additional icon packs installed, despite the pack being supported by Blade Icons, which from what I could see is what handles Heroicons as well.

**To reproduce**
1. Install davidhsianturi/blade-bootstrap-icons
2. Attempt to use icons, like so: 
`Columns\Icon::make('status')->options([
	'0' => 'bi-phone-landscape',
	'1' => 'bi-phone',
	'2' => 'bi-square',
]),`

**Expected behavior**
Expected icons to be showed depending on value from database.

**Code**
`Error
Call to undefined function bi-phone-landscape() (View: /Users/user/Laravel/project/vendor/filament/filament/packages/tables/resources/views/cells/icon.blade.php)
`

**Context**
- Package version: 1.9.4
- Livewire version: 2.x
- Laravel version: 8.37.0
- Browser: Chrome 90
- Server OS: MacOS 11
- PHP version: 8.0.3
- Database: MySQL 8.0

**Comment by ryangjchandler** [comment]
@AlexHaible The issue here is the syntax you're using inside of `options()`. You'll want to do something like this:

```php
Columns\Icon::make('status')
    ->options([
        'bi-phone-landscape' => fn ($status) => $status == '0'
    ])
```

**Comment by AlexHaible** [comment]
That'd explain why it didn't work as I copied it straight from the documentation.
Well, glad I could help find that issue.

**Comment by danharrin** [comment]
This has now been fixed in the docs 👍
