### ISSUE TITLE
Bug when applying multiple column search and filter

### ISSUE THREAD

**Issue by sebapastore** [laravel-filament/filament#381]
**Describe the bug**
If you apply a Filter to a table list, it is expected that the filter still apply when doing some column search. In a scenario where there are at least two searchable columns, when you apply a filter and then do a search, the filter stops applying.

**To reproduce**
1. Create a Resource; i.e: php artisan make:filament-resource Customer.
2. In the Customer List, create a filter and make at least two columns searchable.
3. Go to the list and apply the filter.
4. Perform a search and you will see that the filter stops applying.

**Expected behavior**
It is expected that the filter stills applying when performing a search

**Context**
- Package version: 1.9.3
- Livewire version: 2.3
- Laravel version: 8.37
- Browser: Tested in Chrome, Safari and Firefox
- PHP version: 8.0
- Database: MySQL 8.0

**Comment by danharrin** [comment]
Fixed by #382.
