### ISSUE TITLE
label for resource appends always extra "s" - should be only valid in english

### ISSUE THREAD

**Issue by mhenselin** [laravel-filament/filament#396]
**Describe the bug**
When adding the public variable $label to a resource, it appends an "s" to the Entry in the navigation bar. But this seems to be only valid in english language and maybe some others.

**To reproduce**
* add a resource
* add $label variable

**Expected behavior**
I would probably just turn on that feature when no custom label is set.

**Context**
- Package version: [1.9.6]
- Livewire version: [2.4.3]
- Laravel version: [8.38.0]

**Comment by danharrin** [comment]
Hey, this is a good default for most languages. You should override the static `getPluralLabel()` method on the resource to set a custom plural form, or the static `$navigationLabel` property to set a custom navigation label.

**Comment by mhenselin** [comment]
> Hey, this is a good default for most languages. You should override the static `getPluralLabel()` method on the resource to set a custom plural form, or the static `$navigationLabel` property to set a custom navigation label.

thanks a lot - works like a charm - I prefer the `$navigationLabel` over the function. would be nice to have an explanation in the docs. e.g. where do I use `$label` and where `$navigationLabel`

**Comment by danharrin** [comment]
> > Hey, this is a good default for most languages. You should override the static `getPluralLabel()` method on the resource to set a custom plural form, or the static `$navigationLabel` property to set a custom navigation label.
> 
> 
> 
> thanks a lot - works like a charm - I prefer the `$navigationLabel` over the function. would be nice to have an explanation in the docs. e.g. where do I use `$label` and where `$navigationLabel`

Feel free to submit a PR!

**Comment by danharrin** [comment]
The URL uses the `$slug` property on the resource.

**Comment by lucacalcaterra** [comment]
> The URL uses the `$slug` property on the resource.

perfect ! Thanks !

**Comment by adibpwd** [comment]
add    protected static ?string $title = "Rekening"; in file the extends to ListRecord, example :

namespace App\Filament\Resources\BankResource\Pages;

use App\Filament\Resources\BankResource;
use Filament\Pages\Actions;
use Filament\Resources\Pages\ListRecords;

class ListBanks extends ListRecords
{
    protected static string $resource = BankResource::class;

    protected static ?string $title = "Rekening";

    protected function getActions(): array
    {
        return [
            Actions\CreateAction::make()->label("Tambah Rekening"),
        ];
    }

}

**Comment by q8flix** [comment]
simple method is to add this function in Resource for example:
UserResource.php
in my case I want to Translate "Users" to arabic :


```
public static function getPluralLabel(): ?string
    {
        $locale = app()->getLocale();
        if($locale == 'ar'){
            return "المستخدمين" ;
        }
        else
            return "Users" ;

    }

```

**Comment by GoodJob** [comment]
> Hey, this is a good default for most languages. You should override the static `getPluralLabel()` method on the resource to set a custom plural form, or the static `$navigationLabel` property to set a custom navigation label.

Yes, use 

`protected static ?string $navigationLabel = 'Item';`

instead of

`protected static ?string $label = 'Item';`

to make not plural in Resource Listing, open file  "List{model}.php", add:

`protected static ?string $title = 'Item';`

**Comment by velgandr** [comment]
protected static ?string $pluralLabel = '...';
