### ISSUE TITLE
Components\Field::name method only working with prefix and doesn't return $this

### ISSUE THREAD

**Issue by bernhardh** [laravel-filament/filament#398]
**Describe the bug**

As discussed in my (closed) pull request #397: the `Filament\Forms\Components\Field::name` method has two problems.

- it doesn't return `$this` (which would be an easy fix)
- it shouldn't be called from outside the class, since you will allways need to prefix the name with `record.` (see `ManipulatesResourceRecord` trait). 

**To reproduce**

Just use the `name` method on any form:

Problem one (not returning $this):

```
Components\TextInput::make('myname')
    ->name("myname")
    ->label("My Label");
```

Problem two:

```
Components\TextInput::make('myname')
    ->name("myname");
```

**Expected behavior**

`name()` should be chainable and the value shouldn't need to be prefixed with `record.`

**Context**
- Package version: v1.9.6

**Comment by danharrin** [comment]
Hi, `name()` is deliberately not meant to be altered after its original definition. This is because of the possible dependence of other methods on its value, such as in validation rule configurations. What is the use case for calling it yourself?

To be honest, it should be protected to avoid confusion.

**Comment by bernhardh** [comment]
Yes, that is an good idea. Should I create a PR?

I just played arround to create a json field component. Thats why I tried to use the `name`method.

**Comment by danharrin** [comment]
Please, thank you :)
