### ISSUE TITLE
Column not found: SQLSTATE error

### ISSUE THREAD

**Issue by manishlok** [laravel-filament/filament#4]
### Roles route
SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'order clause' (SQL: select * from `roles` order by `` asc limit 12 offset 0) (View: $project_path\vendor\livewire\livewire\src\Macros\livewire-view.blade.php)

### Permission route
SQLSTATE[42S22]: Column not found: 1054 Unknown column '' in 'order clause' (SQL: select * from (select `permissions`.* from `permissions` group by `permissions`.`id`) as `permissions` order by `` asc limit 12 offset 0) (View: $project_path\vendor\livewire\livewire\src\Macros\livewire-view.blade.php)

> Reply  if anyone got the solution

**Comment by ryanscherler** [comment]
I likely need a bit more context as to when you encountered this issue - what were you attempting to sort by? If this on the permissions index view?

**Comment by manishlok** [comment]
Thank you @ryanscherler 
Yes it is on permissions index views as well as on roles index view.

**Comment by ryanscherler** [comment]
@manishlok I suspect you might be missing a migration? This could also be an issue with your PHP version / Eloquent? I cannot replicate this issue. I am going to close this out and if it comes up again I am happy to look into it more.

**Comment by ndessenius** [comment]
Sorry for bumping this issue but i have exactly the same problem.
It occurs when i created a role.

It seems that's the error came from the ordering method :

`orderBy($this->sortField, $this->sortAsc ? 'asc' : 'desc')`

in vendor/flament/filament/src/Http/Livewire/Permissions.php / Roles.php

**Comment by ryanscherler** [comment]
@ndessenius Yikes is this a sneaky one - I cant seem to replicate it. 😞 If you have an idea of why it might be happening I would definitely appreciate the PR!
