### ISSUE TITLE
Column cannot use `url()` and `action()`

### ISSUE THREAD

**Issue by dehboris** [laravel-filament/filament#403]
The this part of documentation 

````php
Column::make('website')
    ->url(fn ($record) => $record->website, true);
````

or 

```php
Column::make('username')
    ->action('editUsername');
```

because  `Filament\Tables\Columns\Concerns\CanCallAction` and `Filament\Tables\Columns\Concerns\CanOpenUrl` is not use inside ` Filament\Tables\Columns\Column`

**Comment by ryangjchandler** [comment]
@dehboris You should be using one of the columns that are configured like `Filament\Resources\Tables\Columns\Text`, not the base `Column` class.

**Comment by dehboris** [comment]
@ryangjchandler Thanks, but i think you need to update the `Call Action` part documentation.

**Comment by ryangjchandler** [comment]
The `Column` class used in the documentation is generic.
