### ISSUE TITLE
Image Upload Stuck in the process 

### ISSUE THREAD

**Issue by lilouch** [laravel-filament/filament#405]
**Describe the bug**
I have added a component for image upload using 

`Components\FileUpload::make('cover')->image()->directory("/exercices")`

The upload process is stuck "Waiting for size". Moreover, the tap for cancelling does not work.

**To reproduce**
1. After having added the image component, upload an image
2. The upload works well as I have the success message and the updated resources.
3. Refresh the page
4. See the file upload stuck
5. On the DB, my cover attribute is well filled "exercices/jVXKlGWftMcE5dEFeiJp3PIr3TpO3u8VrMnTWJTK.png" 

**Expected behavior**
See the image or at least the possibility to remove the image. 

**Screenshots**
<a href="https://ibb.co/wJqJN6n"><img src="https://i.ibb.co/k3T3gcL/stuck-upload.jpg" alt="stuck-upload" border="0"></a>

**Context**
- Package version: 1.9
- Livewire version: 2.4
- Laravel version: 8.12
- Browser: Brave
- Server OS: Windows 10 - Localhost
- PHP version: 7.4
- Database: MariaDB

**Comment by danharrin** [comment]
Hey, can you make sure that your public directory is linked?

```
php artisan storage:link
```

**Comment by lilouch** [comment]
Yes I have already done that !

**Comment by danharrin** [comment]
@lilouch And the file exists on the disk at the location in the database?

**Comment by lilouch** [comment]
Yes, I tried again.

 `Components\FileUpload::make('cover')->directory("/exercices/cover")->image()`

The image is called : test_unsplash.jpg

Once it is uploaded, I save and I get a message that it is well registered.
From that, my image is renamed to **"gNr8SyJbBNjiErGCYDXbTQstZPmMTUAPUELWdC8a.jpg"**  and it is well located on _"storage/exercices/cover"_ as expected.

On the database, on my cover field, the value is now `exercices/cover/gNr8SyJbBNjiErGCYDXbTQstZPmMTUAPUELWdC8a.jpg`

So everything looks good except the fact that once the upload is completed, I don't see the preview and especially it is still loading with the message "waiting for size".

**Comment by lilouch** [comment]
Any insight ?

**Comment by danharrin** [comment]
Apologies, I can't replicate this issue at all. Can you upload a repository demonstrating this issue please, with a new Filament and Laravel installation?

**Comment by dark-wind** [comment]
I meet a similar problem and solved it:

First I check the image URL

Domain error found for the requested address

Because I use `php artisan serve` to develop and visit at `http://127.0.0.1:8000`

So I modified the **.env** to accommodate this problem
`
APP_URL=http://localhost:8000
`

Then check your browser, 
Safari  reports a warning  "not allowed by Access-Control-Allow-Origin"
Switch to Chrome browser and it works well.

**Comment by lilouch** [comment]
Thank for the insight. Indeed it is a problem related to CORS.
I followed the instruction here: https://stackoverflow.com/questions/39429462/adding-access-control-allow-origin-header-response-in-laravel-5-3-passport and it solved my problem.
It is working on Chrome browser but not on Brave, which is the one I use !
