### ISSUE TITLE
Assets using absoulte url

### ISSUE THREAD

**Issue by monder007** [laravel-filament/filament#414]
**Describe the bug**
When publishing the filament assets using `php artisan vendor:publish --tag=filament-assets` the assets are copied to `/public/vendor/filament` but the assets when loading the admin pages are still using the absolute url rather than the vendor folder path.

**Expected behavior**
The asset urls should be updated to point to the vendor folder.

**Comment by danharrin** [comment]
Hey, this is expected behaviour as the vendor folder will override package files - the absolute URL should not be changed.

**Comment by monder007** [comment]
Hi @danharrin, so publishing the assets is effectively useless as the vendor files are never picked up.

Am I missing something? Using the absolute url it's always using the laravel routes rather than servering from the webserver

**Comment by danharrin** [comment]
Can you publish a repository demonstrating this issue please?
