### ISSUE TITLE
file upload isn't cleared after Create & Create Another

### ISSUE THREAD

**Issue by dark-wind** [laravel-filament/filament#443]
**Describe the bug**
file upload isn't cleared after Create & Create Another.

**To reproduce**
1. I used demo repositories to test this problem: https://github.com/laravel-filament/demo
2. I am sure updated package to "filament/filament": "^1.10",
3. just use Create Product
4. add a image 
5. click Create & Create Another

**Expected behavior**
create success and get a clean form
**Screenshots**
https://user-images.githubusercontent.com/15257951/121127871-0537f880-c85d-11eb-8bc0-015a2bd80856.mp4

**Additional details**
![image](https://user-images.githubusercontent.com/15257951/121127831-f5201900-c85c-11eb-9672-46ceae4d6810.png)
look at this watch
Listening to "value" is certainly more elegant than my pr :[fix file upload isn't cleared after create #429](https://github.com/laravel-filament/filament/pull/429/commits/020dd73e46cfa151347f010214f804b582631123)
I learned so much from your code,
but unfortunately, it doesn't seem to work

**Comment by danharrin** [comment]
This has been fixed in the upcoming v2.

If you still require a fix for v1, please submit a PR.
