### ISSUE TITLE
Table cell action duplication issue

### ISSUE THREAD

**Issue by molcsab** [laravel-filament/filament#4451]
### Package

filament/tables

### Package Version

v2.16.26

### Laravel Version

v9.34.0

### Livewire Version

v2.10.7

### PHP Version

8.1.3

### Problem description

I am defining a table cell action in a resource, but the action also appears in the action section at the end of the table.
![Cell Action Bug](https://user-images.githubusercontent.com/513356/194811859-4b6d0f21-301a-4473-a20e-59de63a2ad0f.png)

### Expected behavior

Action should appear only in cell

### Steps to reproduce

Define a table and add a cell action with an action modal

### Reproduction repository

https://github.com/molcsab/filament-actionbug

**Comment by danharrin** [comment]
Fixed by #4454.
