### ISSUE TITLE
tgalopin/html-sanitizer is abandoned.

### ISSUE THREAD

**Issue by hamzaelmaghari** [laravel-filament/filament#4509]
### Package

filament/filament

### Package Version

v2

### Laravel Version

v9

### Livewire Version

v2

### PHP Version

V8.2

### Problem description

When installing Filament the composer says that a package tgalopin/html-sanitizer is abandoned. I thought that this may cause a security problem in the future.

### Expected behavior

No errors

### Steps to reproduce

➜ laravel new marketplace && cd marketplace && npx @preset/cli apply laravel:vite && php artisan vite:tsconfig && composer require filament/filament && php artisan vendor:publish --tag=filament-config && composer require filament/spatie-laravel-settings-plugin && php artisan migrate

<img width="666" alt="Screenshot 2022-10-13 at 00 38 03" src="https://user-images.githubusercontent.com/84163115/195467735-fc64e3cd-ad34-4d7a-8012-d1dcb535733d.png">

### Reproduction repository

https://github.com/filamentphp/filament

**Comment by zepfietje** [comment]
Hey @hamzaelmaghari, thanks for opening an issue!

This is a known warning.
However, we can't upgrade to `symfony/html-sanitizer`, because its PHP 8.1 only, while we still support PHP 8.

**Comment by danharrin** [comment]
Also, the original library has been around for years, is very stable, and `symfony/html-sanitizer` was built on top of it. I don't think there is a real security risk there.

**Comment by hamzaelmaghari** [comment]
Understood guys.
Thanks
