### ISSUE TITLE
Persistent Filters with QueryString filters issue

### ISSUE THREAD

**Issue by tiagofcp** [laravel-filament/filament#4518]
### Package

filament/tables

### Package Version

latest

### Laravel Version

latest

### Livewire Version

latest

### PHP Version

8.1

### Problem description

When we use persistent filters the filters are saved to session but if we try to open a table with query string, the table should open with the filters from query string, instead its using the latest filters saved on the session

### Expected behavior

Open the table with current filters on the query string

### Steps to reproduce

Install the reproduction repo.
Open the orders table
filter by Only deleted records.
now the url should have the the following query string "?tableFilters[trashed][value]=0"
change the query string to "?tableFilters[trashed][value]=1"
this should return the table with the filter "With deleted records" but instead it goes back to the previous filter that is saved on the session

### Reproduction repository

https://github.com/tiagofcp/filament-persistentfilter-issue/

**Comment by danharrin** [comment]
Fixed by #4816.
