### ISSUE TITLE
Cannot sendSuccessNotification

### ISSUE THREAD

**Issue by zozulinskyi** [laravel-filament/filament#4532]
### Package

filament/filament

### Package Version

v2.16.32

### Laravel Version

v.9.35

### PHP Version

PHP 8.1.10

### Problem description

I have a custom page actions. My code is
```
protected function getActions(): array
{
        return [
            Actions\Action::make('reactivate')
                ->label('Reactivate')
                ->color('danger')
                ->action(fn () => UserActivated::dispatch($this->record))
                ->modalSubheading('Some heading here...')
                ->requiresConfirmation()
                ->sendSuccessNotification(),
            Actions\DeleteAction::make(),
        ];
}
```

In previous version this code successfully worked. But, after update filament to latest version, a have next problem:

> Typed property Filament\Pages\Actions\Action::$livewire must not be accessed before initialization

When I remove calling `sendSuccessNotification` method all is fine, but I doesn't have a notification after action.

### Expected behavior

Successfull notification )

### Steps to reproduce

none

### Reproduction repository

none

**Comment by danharrin** [comment]
`sendSuccessNotification()` is an internal API, you should use `Notification::make()->send()` like normal.
