### ISSUE TITLE
Fix icon size and color

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#4536]
## Size

- [x] `.filament-modal-close-button`: `h-5 w-5`
- [x] `.filament-tables-header-cell-sort-icon`: `h-5 w-5`
- [x] `.filament-notifications-close-button`: `h-5 w-5`

## Color

- [x] `.filament-tables-filters-trigger`
- [x] `.filament-tables-column-toggling-trigger`

**Comment by awcodes** [comment]
What are your thought's on the colors for the triggers? I think the primary is fine.

**Comment by zepfietje** [comment]
I think I prefer gray like Tailwind UI uses.
