### ISSUE TITLE
Font size tweaks

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#4537]
https://github.com/filamentphp/filament/pull/4046

---

- [ ] filament-global-search-input

**Comment by awcodes** [comment]
What needs to be done with this?

**Comment by zepfietje** [comment]
This issue exists as a reference to the PR that was reverted in v2.
Opened this to keep track of elements that need their font size tweaked to match Tailwind UI.

Since I created the original PR, I can handle a new one for this as well. 👍

**Comment by awcodes** [comment]
No worries. Was just having trouble following the thread back across issues and PRs.

**Comment by zepfietje** [comment]
Will keep this issue open as there's still some input sizing and Choices.js font sizes to fix.

I'll take care of this and reach out for anything we need to discuss, @awcodes.

**Comment by awcodes** [comment]
I changed the choices js font size in the stylesheet. It matches both the select and text inputs. Make sure you republish the assets in the demo.

**Comment by zepfietje** [comment]
From reading your PR I saw some places it was missing. Not just the select input font size should be updated, but also the select dropdown items. No worries, didn't expect you to catch everything I originally worked on.

**Comment by awcodes** [comment]
I believe the drop down items are already text-sm. But it's a lot across multiple package. I'm sure there are some that I missed.

**Comment by danharrin** [comment]
Fixed by #5074

**Comment by zepfietje** [comment]
@danharrin, https://github.com/filamentphp/filament/issues/4537#issuecomment-1328112902.

It's on my radar.

**Comment by zepfietje** [comment]
Closing in favor of new roadmap entry for general sizing tweaks.
Will handle this.
