### ISSUE TITLE
"Converting circular structure to JSON" when using dependable field

### ISSUE THREAD

**Issue by mrneatly** [laravel-filament/filament#454]
When selecting any option from a Select as a dependable input, next message appears in developer console:

`SupportAlpine.js:97 Uncaught TypeError: Converting circular structure to JSON`

No dependent field is shown after option being selected.

1. Use a Select input in a resource form and make it dependable
2. Select any option
4. See an error in console

Dependent fields should actually appear after selecting particular option.

- Filament version: 1.10.1
- Livewire version: 2.4.4
- Laravel version: 8.42.1
- Browser: Chrome
- Server OS: Mac OS 11.4
- PHP version: 8.0.3
- Database: MySQL 8.0.19

The `form` method of a resource:

```php
public static function form(Form $form) {
      return $form
	      ->schema([
		      Components\Select::make('type')
			      ->placeholder('Select profile type')
			      ->options([
				      'artist' => 'Artist',
				      'venue' => 'Venue',
			      ])
			      ->dependable(),
		      // ...
		      Components\TextInput::make('price_from')
			      ->required()
			      ->when(fn ($userProfile) => $userProfile->type === 'artist'),
	      ]);
}
```

**Comment by xphoenyx** [comment]
I just noticed exact same error happens after uploading an image via image upload input. Refreshing the page helps to solve the problem though.

**Comment by xphoenyx** [comment]
Ok, so I've managed to solve the problem with images not being uploaded somehow. But the initial problem still exists.

**Comment by danharrin** [comment]
How did you solve the problem? I wonder if upgrading Filament to Alpine v3 might fix it... I'll have a look when I can.

**Comment by xphoenyx** [comment]
I can't event tell how I got it back to work. I made some significant changes in my form, after which the problem disappeared.
