### ISSUE TITLE
Error when retrieving chart data for distinct column

### ISSUE THREAD

**Issue by otilor** [laravel-filament/filament#4541]
### Package

filament/filament

### Package Version

v2.16.7

### Laravel Version

v9.21.4

### Livewire Version

v2.10.7

### PHP Version

PHP 8.1.0

### Problem description

When trying to retrieve unique attendees of an event. I'm using this query:
```php
Attendee::query()->distinct('user_id')
```

It works on its own but when using it in this chart widget;
```php
Trend::query(Attendee::query()->distinct('user_id'))
            ->between(
                start: now()->setDate(2021, 1, 1),
                end: now(),
            )
            ->perMonth()
            ->count();
```

I get this error:

```
SQLSTATE[42P10]: Invalid column reference: 7 ERROR: SELECT DISTINCT ON expressions must match initial ORDER BY expressions LINE 1: select distinct on ("user_id") ^ (SQL: select distinct on ("user_id") to_char(created_at, 'YYYY-MM') as date, count(*) as aggregate from "attendees" where "created_at" between 2021-01-01 16:43:04 and 2022-10-14 16:43:04 group by "date" order by "date" asc)
```

### Expected behavior

Retrieve the data successfully and display it in form of a line chart

### Steps to reproduce

1. Create a chart widget.
2. Create an `Attendee` model with a migration that has `user_id` column the default `User` model
3. Add this code to the `getData()` column
```php
$data = Trend::query(Attendee::query()->distinct('user_id'))
            ->between(
                start: now()->setDate(2021, 1, 1),
                end: now(),
            )
            ->perMonth()
            ->count();

            return [
                'datasets' => [
                    [
                        'label' => 'Unique Attendees',
                        'data' => $data->map(fn (TrendValue $value) => $value->aggregate),
                    ],
                ],
                'labels' => $data->map(fn (TrendValue $value) => $value->date),
            ];
```

### Reproduction repository

https://github.com/humaneguy/attendee-error

**Comment by zepfietje** [comment]
@humaneguy, this doesn't seem like an issue with Filament? You might want to report the error on the [trends package repo](https://github.com/Flowframe/laravel-trend).

**Comment by otilor** [comment]
Thanks @zepfietje
