### ISSUE TITLE
Actions with slideover - padding

### ISSUE THREAD

**Issue by rowdy4e** [laravel-filament/filament#4572]
### Package

filament/filament

### Package Version

v2.16.33

### Laravel Version

9.35.1

### PHP Version

8.1.11 

### Problem description

I noticed that this problem was already solved in the older version, but in the latest version the problem reappeared.

Somehow the `->slideOver()` function behaves strangely for all Action classes. Even though it is defined in the blade file, the padding still appears in the html.

![captures_chrome-capture-2022-9-17](https://user-images.githubusercontent.com/44244456/196097938-5cfadbe8-1da4-4dfb-ad6f-d03f13a7d9c8.png)

### Expected behavior

Padding should only be included if the modal does not use slideover.

### Steps to reproduce

1. Create filament page `php artisan make:filament-page TestPage`.
2. Open `TestPage.php` and create `getActions()` function.
```
...
protected function getActions(): array
{
    return [
        Action::make('create')
            ->slideOver()
            ->action(function (array $data) {
                dd($data);
            })
            ->form([
                TextInput::make('title')
            ])
    ];
}
```
3. Visit page and click on `Create` button.

### Reproduction repository

https://github.com/rowdy4e/filamentphp-modal-slideover-padding

**Comment by zepfietje** [comment]
Thanks for reporting, @rowdy4e!

So, apparently the table action is `null` at the point the modal gets constructed, which leads to the slide-over prop defaulting to its `false` value:
```blade
<x-tables::modal
    :slide-over="$action?->isModalSlideOver()"
>
```

Any idea how this might have changed recently, @danharrin?

**Comment by danharrin** [comment]
uh nope

**Comment by zepfietje** [comment]
@rowdy4e, what's the latest Filament version when it still worked fine?

**Comment by rowdy4e** [comment]
@zepfietje I'm not sure now, but I may have confused it with the fact that notifications had this bug.

**Comment by zepfietje** [comment]
Ah fair. It might have been broken for tables all along...
