### ISSUE TITLE
->html->limit(x) or ->limit(x)->html() will override each other when used on column

### ISSUE THREAD

**Issue by miomech** [laravel-filament/filament#4589]
### Package

filament/tables

### Package Version

2.16.34

### Laravel Version

9.35

### Livewire Version

2.10.7

### PHP Version

PHP 8.1

### Problem description

When the method html and limit are chained they override each other

`->html()->limit(30)`
produces nonhtml with a limit of 30.

when this is used
`->limit(30)->html()`
it produces nonlimited html that does not get truncated at 30

### Expected behavior

when both are chained the methods should create a html string of the "limit" specified

### Steps to reproduce

use
`->html()->limit(30)`

or

`->html()->limit(30)`

The code was used in the context of a relations manager class.

### Reproduction repository

https://github.com/miomech/Temp_Bug_repo/blob/main/ComponentsRelationManager

### Relevant log output

```shell
None
```

**Comment by zepfietje** [comment]
Internally `formatStateUsing()` is used for both `limit()` and `html()`, causing this issue.

**Comment by Z3d0X** [comment]
Even if multiple `->formatStateUsing()` calls are supported, cropping in a html string could result in a middle of a tag?

**Comment by danharrin** [comment]
Yeah, limiting HTML is a bad idea anyway

**Comment by Nuhel** [comment]
Not only html or limit will override eachother. any function that call formatStateUsing internally will override the previous one.

Ant limiting html string I also think not a good idea, It can break the whole html.

But if u are sure that limit will not break html, than I think using formatStateUsing method will be a good idea.

**Comment by danharrin** [comment]
I think the `formatStateUsing()` pattern is fine at the moment, I don't see how it would clash in sensible cases.
