### ISSUE TITLE
Cannot declare class GeneralSettings, because the name is already in use

### ISSUE THREAD

**Issue by OvalMedia** [laravel-filament/filament#4593]
### Package

filament/spatie-laravel-settings-plugin

### Package Version

v2.16.29

### Laravel Version

v9.34.0

### PHP Version

PHP 8.1.11

### Problem description

I followed the docs (https://filamentphp.com/docs/2.x/spatie-laravel-settings-plugin/getting-started) and created a GeneralSettings class in app/Settings. After having prepared all that I created a settings page like mentioned in the docs: `php artisan make:filament-settings-page Einstellungen GeneralSettings`.

A new settings symbol appears in my menu and when I click it to visit the new settings page the app breaks with the error message:

```
Symfony \ Component \ ErrorHandler \ Error \ FatalError
Cannot declare class GeneralSettings, because the name is already in use
```

### Expected behavior

The settings page shows up.

### Steps to reproduce

Just follow the docs step by step.

### Reproduction repository

.

**Comment by OvalMedia** [comment]
Ok, somewhat a lack of documentation on your side and lack of coffe on mine.
Forgot to set a namespace in my settings class:

```
<?php
namespace App\Settings;

use Spatie\LaravelSettings\Settings;

class General extends Settings
{
    /**
     * @var string
     */
    public string $company;

    /**
     * @return string
     */
    public static function group(): string
    {
        return 'general';
    }
}
```

**Comment by zepfietje** [comment]
How could the documentation be improved, @OvalMedia? 🙂

**Comment by OvalMedia** [comment]
It might be an issue of the settings project itself. Already noted here: https://github.com/spatie/laravel-settings/issues/158
The whole file should be cited instead of only the class definition. I get it, it is not this project also I am a bit slow in the head.

**Comment by zepfietje** [comment]
Thanks for clarifying!
