### ISSUE TITLE
Pages with widgets not working for print

### ISSUE THREAD

**Issue by RickDBCN** [laravel-filament/filament#4614]
### Package

filament/filament

### Package Version

v2.16.4

### Laravel Version

v9.x

### Livewire Version

v2.x

### PHP Version

8.1x

### Problem description

On pages with widgets the tab crashes in Chrome. On demo dashboard page, using CTRL + P attempts to print 29000 pages.

### Expected behavior

Preview 1 or 2 pages and no crash when printing

### Steps to reproduce

- Go to https://demo.filamentphp.com/ on Chrome (using version 106.0.5249.119)
- CTRL + P to print
- Chrome attempts to print 29000 pages and the tab crashes

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by danharrin** [comment]
Any specific types of widgets? Maybe charts?

**Comment by RickDBCN** [comment]
> Any specific types of widgets? Maybe charts?

I have reason to believe it only applies to table widgets. Chart and text-only blade widgets are working fine. As soon as there is a table widget, it breaks.

Normal table pages are fine.

**Comment by danharrin** [comment]
So table widgets break, but not list pages? Which both use the same code?

**Comment by zepfietje** [comment]
Can confirm it's the table widget causing the issue. List pages work fine.

**Comment by RickDBCN** [comment]
List pages won't render the table on print. See preview:
![image](https://user-images.githubusercontent.com/9408120/196694345-23c1f535-205a-4064-a3f3-a87918344db4.png)

**Comment by zepfietje** [comment]
Works fine in Safari. Firefox just shows an empty page.

**Comment by Nuhel** [comment]
For me https://demo.filamentphp.com/ pages working fine in safari and firefox on both mobile and macbook.

And for chrome its breaks in macbook.
But for mobile in some model it works in chrome. 

May be there is some issue with css as google chrome team adding new features for css3.

**Comment by danharrin** [comment]
Yeah, I feel like this is likely a Chrome bug rather than anything we can fix?

**Comment by zepfietje** [comment]
Agree, this is likely an issue with Chart.js/Chromium.

**Comment by astalarico** [comment]
I'm not sure that this is a browser bug as it has affected all browsers on fresh installation and the only way I could print my pages was to add a z-index to the content container. Printing works if the panel sidebar is closed but not if it's open.
