### ISSUE TITLE
The list view makes queries that are in the form function

### ISSUE THREAD

**Issue by buzkall** [laravel-filament/filament#4619]
### Package

filament/filament

### Package Version

2.16.33

### Laravel Version

9.35.1

### PHP Version

8.1.11

### Problem description

When viewing the list page of a resource, debugbar shows queries that aren't in the table function, but on the form function.

For example, if the form has a Select and a query is made to define the select options, the query is performed in the list view

### Expected behavior

No form queries in the list view

### Steps to reproduce

Install and seed the repository.
Seed will create an admin user: admin@mail.com with pass secret

Navigate to activities list -> /admin/activities
Check the queries in debugbar
Backtrace points to /vendor/filament/filament/src/Resources/Pages/ListRecords.php line 257

### Reproduction repository

https://github.com/buzkall/double

**Comment by zepfietje** [comment]
Retrieving select options from the database should be wrapped in a closure to prevent it from being called multiple times internally:
```php
Select::make('tags')
    ->options(fn (): array => Tag::getOptions(TagTypeEnum::content_type))
```

**Comment by danharrin** [comment]
And this has been fixed in v3, so you don't need to use the callback then 👍
