### ISSUE TITLE
Double request when adding a new item in a repeater field

### ISSUE THREAD

**Issue by buzkall** [laravel-filament/filament#4620]
### Package

filament/filament

### Package Version

v2.16.33

### Laravel Version

9.35.1

### PHP Version

8.1.11

### Problem description

When clicking on the "Add to external links" in the Repeater field, to calls are done and if the user has selected something in the fields of the repeater, will be lost

### Expected behavior

Just one call

### Steps to reproduce

Install and seed the repository.
Seed will create an admin user: [admin@mail.com](mailto:admin@mail.com) with pass secret

Navigate to activities creation page -> /admin/activities/create
Click on "Add to external links" and check Network tab in developer tools

### Reproduction repository

https://github.com/buzkall/double

**Comment by awcodes** [comment]
It is making 2 calls because your Select field is set to preload. Preload has to make it's own call each time it is re-rendered by Livewire because it's options could be dependent on the value of another field.

**Comment by danharrin** [comment]
@awcodes does that explain "if the user has selected something in the fields of the repeater"?

**Comment by awcodes** [comment]
@danharrin I could not replicate anything happening in the fields. Nothing disappeared or changed during testing.

**Comment by danharrin** [comment]
@buzkall if you could maybe confirm which browser you replicated this on that would be great, and double check it still happens in the latest Filament version with your reproduction repo

**Comment by buzkall** [comment]
I've tested it with the latest version of Filament and Opera and Firefox browsers. 
I've recorded a video showing it with slow 3G preset in the browser -> https://www.loom.com/share/5279064462c7409391a5bf3ca4fa1905
I lose the selection but now it gets saved (?)

Also, @awcodes the select has options, but no preload call. Having options means I'm preloading? in which other way can I add the options to the select without the double call?

**Comment by awcodes** [comment]
In your demo repo your Select field has ->preload() if you remove that you'll see that it only makes one call.

**Comment by buzkall** [comment]
But it's another select, the tag's one, not the repeater one. 
So if any component of the resource has a preload, I'll get this behaviour?

**Comment by awcodes** [comment]
AFAIK, yes. the whole page is run through Livewire. Fields themselves are not livewire components. So every field get's dom diffed with each Livewire request.

**Comment by awcodes** [comment]
I do expect this behavior to be improved with Livewire v3 since we'll be able to batch requests.
