### ISSUE TITLE
Update heroicons to the newest version

### ISSUE THREAD

**Issue by SerhiiMandrykin** [laravel-filament/filament#4637]
### Package

filament/forms

### Package Version

v2.16.32

### Laravel Version

v.9.35.1

### PHP Version

8.1

### Problem description

Some icons can't be used because of old version of the heroicons.

For example, try the icon `protected static ?string $navigationIcon = 'heroicon-o-document-chart-bar';`

The error: 
![image](https://user-images.githubusercontent.com/25152924/196777216-b3e32606-4f1b-4969-b971-ac81ed3eedb2.png)

### Expected behavior

The icon is rendered and no errors are shown.

### Steps to reproduce

1. Set the navigation icon for a resource: `heroicon-o-document-chart-bar`

### Reproduction repository

https://github.com/filamentphp/filament

**Comment by zepfietje** [comment]
https://github.com/filamentphp/filament/issues/3916

**Comment by zepfietje** [comment]
https://v1.heroicons.com

`document-report` is the icon you're looking for in Heroicons v1.

**Comment by SerhiiMandrykin** [comment]
Thank you
