### ISSUE TITLE
Couldn't find class Filament\Tables\Columns\Layout\View

### ISSUE THREAD

**Issue by Congminh7799** [laravel-filament/filament#4642]
### Package

filament/tables

### Package Version

2.16

### Laravel Version

9.19

### PHP Version

8.0.2

### Problem description

I Couldn't find class Filament\Tables\Columns\Layout\View when use in List.

### Expected behavior

I want to use class Filament\Tables\Columns\Layout\View
Same as below!
![image](https://user-images.githubusercontent.com/106800650/196891353-ac14728b-7f24-48b3-8fe4-847300130910.png)

### Steps to reproduce

use Filament\Tables\Columns\Layout\View in Class List extend ListRecord.

### Reproduction repository

i dont show it with you!

**Comment by danharrin** [comment]
`composer update`
