### ISSUE TITLE
When using a colorpicker in a repeater with a "simple" resource it works once

### ISSUE THREAD

**Issue by G3z** [laravel-filament/filament#4645]
### Package

filament/filament

### Package Version

v2.16.35

### Laravel Version

v9.35.1

### PHP Version

PHP 8.1.11

### Problem description

When a colorpicker is inside of a repeater and that form is presenter in a simple resource only the first modal has working pickers in edit mode.
```php
<?php

class UserResource extends Resource
{

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Repeater::make('color')->schema([
                    ColorPicker::make('color'),
                ]),
            ]);
    }

    public static function getPages(): array
    {
        return [
            'index' => Pages\ManageUsers::route('/'),
        ];
    }
}
```

### Expected behavior

when editing every picker should work

### Steps to reproduce

- create a `--simple` resource
- add a colorpicker to a repeater
- edit more than one "simple" resource

### Reproduction repository

https://github.com/G3z/filament-bug/tree/color-picker-load

**Comment by awcodes** [comment]
This is working correctly for me, with your repo.

![Screen Shot 2022-10-30 at 11 50 22 AM](https://user-images.githubusercontent.com/3596800/198888334-4837f516-55bc-48f2-ae3b-d805cded7d95.png)

**Comment by G3z** [comment]
I tried again and recorded  a video with chrome 
just to be clear: it's the second modal that's empty
https://user-images.githubusercontent.com/875086/198890922-cd77a740-fa30-44ab-8c44-6e2ec702f027.mov

**Comment by awcodes** [comment]
Thank you for explaining in more detail. I'll investigate further.

**Comment by danharrin** [comment]
Does #4764 fix this?

**Comment by awcodes** [comment]
In the table actions yes. Have not tried with page actions but I believe they need to updated too.

**Comment by danharrin** [comment]
Page actions aren't keyed by the record already so I think its fine

**Comment by G3z** [comment]
just tested with `"filament/filament": "2.x-dev",` and it's fixed

**Comment by G3z** [comment]
I missed the release: 2.16.39 fixed the issue
