### ISSUE TITLE
Hidden widgets still take up visible space

### ISSUE THREAD

**Issue by emmadesilva** [laravel-filament/filament#4678]
### Package

filament/filament

### Package Version

v2.16.36

### Laravel Version

v9.36.4

### Livewire Version

v2.10.7

### PHP Version

8.1.10

### Problem description

When a widget is set in the `getHeaderWidgets` array, but the widget's `canView` method returns false, the `filament-widgets-container` component is still present in the DOM, while it is empty, it still takes up visible vertical space, leading to an extra gap due to the grid layout.

Here is a side by side comparison
![image](https://user-images.githubusercontent.com/95144705/197355888-abdfe03d-f752-4ba9-b4f0-06e84b9d430e.png)

### Expected behavior

The empty container should not have been added, or it should have been added in a way that does not increase the height.

### 1: Clone repo

```
git clone git@github.com:caendesilva/filament-bug-repro.git
cd filament-bug-repro
composer install
php artisan migrate --seed
```

### 2: Log in and view demo page

Visit http://127.0.0.1:8000/admin/, log in with email `test@example.com` and password `password`

Visit Filament page "[broken](http://127.0.0.1:8000/admin/broken)" and visually compare it to "[expected](http://127.0.0.1:8000/admin/expected)". The content is further down on the broken page, leading to a visual inconsistency. The broken page has a widget that is hidden, whereas the expected page has no widgets.

### Quick links to reproduction files

See this commit for a quick overview https://github.com/caendesilva/filament-bug-repro/commit/028f646882f89c753db4c2d4e7f47628d8bdd1cb

### Reproduction repository

https://github.com/caendesilva/filament-bug-repro

**Comment by emmadesilva** [comment]
I don't think this issue is missing any information.

**Comment by zepfietje** [comment]
@caendesilva, could you confirm if https://github.com/filamentphp/filament/pull/4690 fixes your issue?

**Comment by emmadesilva** [comment]
> @caendesilva, could you confirm if #4690 fixes your issue?

Sure thing, give me a second.

**Comment by emmadesilva** [comment]
> @caendesilva, could you confirm if #4690 fixes your issue?

Works great! Thanks!

**Comment by zepfietje** [comment]
Thanks for testing!
