### ISSUE TITLE
Select all button still shows after selecting when filtered

### ISSUE THREAD

**Issue by themahdavi** [laravel-filament/filament#4680]
### Package

filament/tables

### Package Version

2.16.36

### Laravel Version

9.36.4

### Livewire Version

2.10.6

### PHP Version

8.1.9

### Problem description

When select all searching and filtering result don't disappear Select All action

![image](https://user-images.githubusercontent.com/31320104/197359350-0072c083-c23b-46bb-9798-287344b8f3bd.png)

### Expected behavior

search or filter table then select all items when click on `Select All #` don't disappear .

### Steps to reproduce

Demo app tables for ex: https://demo.filamentphp.com/shop/products

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by themahdavi** [comment]
Hey @zepfietje On Products list do this steps:

1. Search `glov` on global search of table
2. show 4 results
3. click on checkbox for check all
4. see this : 
![image](https://user-images.githubusercontent.com/31320104/197400697-ffc72b3d-8392-4e74-9dab-34f2e6ef0e8c.png)
5. click on `Select all 4` and then show this action again and not disappear

**Comment by zepfietje** [comment]
Ah, I see what you mean now, @themahdavi. You'd expect the `Select all 4` link to disappear similar to how this happens without searching/filtering. Definitely a bug. Thanks for reporting.

**Comment by themahdavi** [comment]
I apologize for my language. my English is bad

**Comment by zepfietje** [comment]
No worries, @themahdavi. Your latest steps were clear!
