### ISSUE TITLE
Stuck on 403 forbidden if a user is not an admin (with gates)

### ISSUE THREAD

**Issue by theo-hrd** [laravel-filament/filament#4704]
### Package

filament/filament

### Package Version

2.0.0

### Laravel Version

9.31

### Livewire Version

2.0

### PHP Version

8.1.9

### Problem description

I'm trying to log a user by checking with gates.

I defined my gate in the AuthServiceProvider as such:
```php
public function boot()
    {
        $this->registerPolicies();

        Gate::define('isAdmin', function () {
            return Auth::user()->role_id === 3;
        });
    }
```

When I'm using the function canAccessFilament(), I do this:
```php
public function canAccessFilament(): bool
    {
        return Gate::allows('isAdmin'); 
    }
}
```

Next, I try to connect a non admin user, and get stuck on the forbidden page. 
There is no way for me to go back to the login page by modifying the url, and I'm not able to redirect in the canAccessFilament function using an if statement since it's only accepting a boolean so I don't know what to do.
This may be a Laravel error handling problem, so I don't know if I'm the problem here.

### Expected behavior

When a user is not an admin, I should be able to change at least the URL back to the login page, and in the best of world get redirected after some time to the login page of Filament.

Again this may be a Laravel thing.

### Steps to reproduce

- connect with a non admin user using gates

### Reproduction repository

sorry not public

**Comment by theo-hrd** [comment]
Sorry I'm not able to provide the repository since it's a school project and I'm not able to change the repository visibility.

**Comment by danharrin** [comment]
**Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private/confidential, since we want a link to a separate, isolated reproduction anyways.

**Comment by theo-hrd** [comment]
Alright I found what was causing the fact that I was stuck on forbidden: 

First, I removed all view in my project since it's an API, and did not need any view to logout. So it's a really particular case.

And if people are in the same case, I changed this:
```php
public function canAccessFilament(): bool
{
    return Gate::allows('isAdmin'); 
}
```

to:
```php
public function canAccessFilament(): bool
{
    if (Gate::allows('isAdmin')) {
        return true;
    } else {
        Auth::logout(); // now it logs out the user and you can retry.
        return false;
    }
}
```
