### ISSUE TITLE
Editing using a modal causes issues with input display

### ISSUE THREAD

**Issue by adampatterson** [laravel-filament/filament#4711]
### Package

filament/forms

### Package Version

v2.16.35

### Laravel Version

v9.36.4

### Livewire Version

v2.10.7

### PHP Version

8.0.22

### Problem description

I have a settings table that contains `key, value, data_type`.

In my form I am using a match within the schema method to load the proper Field based on `data_type`

```php
$form->schema(function ($get) {
    $type = $get('data_type');

    return match ($type) {
        // https://gist.github.com/adampatterson/989bcc8859f8ad2135c7b0e397f1ba81
    };
});
```

My test data includes each form field that will be used in the site, without the **edit** page using the edit modal, the display of each input uses the display from the first row edited.

For example, if I make and edit to a setting with `data_type` of `time` then each input after that is using the same display.

- Data Time shows Time
- Date shows Time
- Time shows Time

If I edit a `bool` value then something like `url` or `tel` will display as `undefined`.

The field validation seems to be correct.

If a value is updated the display for the next field uses the display from the submitted field.

I made a quick video here https://d.pr/v/NG0idf

### Expected behavior

When editing using the modal I'd expect the input display to be correct based on the field loaded in the schema.

- Data Time should show the Date Time
- Date should show the Date
- Time should show Time
- Bool should show Bool

### Steps to reproduce

Here is the function that processes my fields.
https://gist.github.com/adampatterson/989bcc8859f8ad2135c7b0e397f1ba81

Migration:
https://gist.github.com/adampatterson/1fe2ec47465e8c9aae7d01e8659baea3

Seeder:
https://gist.github.com/adampatterson/51bc3742f31c847243e52f80e86343ff

Login details: https://github.com/adampatterson/filament-test/blob/main/database/seeders/UserSeeder.php#L24

In a `GlobalSettingsResouce.php` under `getPages()` comment out **edit**.

With **edit** commented out this issue will happen, if **edit** is uncommented and you use the page, then everything works as expected. 

### Reproduction repository

https://github.com/adampatterson/filament-test

**Comment by awcodes** [comment]
This has been resolved and will be in the next release.

Thanks.

**Comment by adampatterson** [comment]
Thanks!
