### ISSUE TITLE
The CreateAction.php always returns $record to null in any ResourceManager.

### ISSUE THREAD

**Issue by loanbesson** [laravel-filament/filament#4713]
### Package

filament/filament

### Package Version

v2.16.36

### Laravel Version

v9.37.0

### Livewire Version

v2.10.7

### PHP Version

PHP 8.1.11

### Problem description

The CreateAction.php always returns $record to null.

To fix this problem, I have commented out the `$this->record(null);` on line 70 in `vendor/filament/src/Pages/Actions/CreateAction.php`.

### Expected behavior

I thought I would get the $record of the action, instead I got always null.

### Steps to reproduce

```bash
cp .env.exemple .env

./vendor/bin/sail up -d

./vendor/bin/sail php artisan migrate --seed
```

Go to [http://localhost/admin/users](http://localhost/admin/users)
Connect with `admin@technique / password`
Click on "Créer" button.

Fill the form with random values.

Click on "Créer" button.

It will display the dump with the null $record.

To fix this problem, I have commented out the `$this->record(null);` on line 70 in `vendor/filament/src/Pages/Actions/CreateAction.php`.
Try again, it returns a Model now.

### Reproduction repository

https://github.com/LoanBesson/fix-record-on-filament-package

**Comment by danharrin** [comment]
The record should be null, because it doesnt exist yet. Maybe you're looking for `$livewire->ownerRecord`?

**Comment by loanbesson** [comment]
Thanks for your feedback.

It's just that it was hidden deep in the doc in "RelationManager" which was not my case at all...
