### ISSUE TITLE
KeyValue field does not work properly with the i18n plugin

### ISSUE THREAD

**Issue by makhweeb** [laravel-filament/filament#4757]
### Package

filament/forms

### Package Version

v2.16.36

### Laravel Version

v9.37.0

### Livewire Version

v2.10.7

### PHP Version

PHP 8.1.0

### Problem description

KeyValue field stores content without language keys in the database. (using filamentphp/spatie-laravel-translatable-plugin)

### Expected behavior

-

### Steps to reproduce

-

### Reproduction repository

-

**Comment by makhweeb** [comment]
@danharrin

**Comment by danharrin** [comment]
No, report the issue properly and we will have a look at it. Writing one sentence is not helpful.
