### ISSUE TITLE
Tailwind error when trying to use a custom the theme

### ISSUE THREAD

**Issue by lucacri** [laravel-filament/filament#4785]
### Package

filament/forms

### Package Version

v2.16.37

### Laravel Version

9.37.0

### Livewire Version

v2.10.7

### PHP Version

8.1

### Problem description

I'm trying to use Vite with Tailwind to extend the base CSS file as described in the docs ( https://filamentphp.com/docs/2.x/admin/appearance#building-themes ).

Folliwing the instructions to the letter, I receive the following error in Vite:

```
[plugin:vite:css] [postcss] /Users/lucacri/Sites/site/vendor/filament/forms/dist/module.esm.css:1653:3: The `border-danger-600` class does not exist. If `border-danger-600` is a custom class, make sure it is defined within a `@layer` directive.
/Users/lucacri/Sites/site/vendor/filament/forms/dist/module.esm.css:1653:3
```

Upon checking, I can see that the file `module.esm.css` was updated during the merge request #4454 , introducing the error.

### Expected behavior

Custom CSS works as described in the docs

### Steps to reproduce

Create a new filament project, follow the docs ("Building themes" section)

### Reproduction repository

https://github.com/lucacri/filament-bug

**Comment by lucacri** [comment]
This requirement of a repository is.. a lot. I'll make one soon

**Comment by danharrin** [comment]
I just downloaded your repo

`composer install && npm i`
`npm run build`

No errors. #4454 didnt change module.esm.css, and that is a compiled file anyway.

**Comment by lucacri** [comment]
Sorry, the problem was with the fact that I was trying to customize the tailwind css but with multiple vite configurations.

The only way I could make this work was to change the filament.css to:

```css
@import 'tippy.js/dist/tippy.css';
@import 'tippy.js/themes/light.css';
@import '../../vendor/filament/filament/resources/css/app.css';
@config "../../tailwind.filament.config.js"


@tailwind base;
@tailwind components;
@tailwind utilities;

```

Basically I had to import some of the contents of the vendor css (the two tippy lines), and then add the `@tailwind` section at the end.

In this way, it creates a full and correct css.

**Comment by nsetyo** [comment]
It is happened to me as well, can we open this issue again? @danharrin 

My repo is here https://github.com/nsetyo/simimc/tree/34fd4377bd616d90200802ba3083b8f16368d880/app

![image](https://user-images.githubusercontent.com/4555074/204090733-e682c583-5788-43f4-963e-81eea49e19ba.png)

**Comment by danharrin** [comment]
Try upgrading Tailwind? This isnt a Filament issue, Tailwind handles the CSS compilation

**Comment by dchatry** [comment]
Definitely a Tailwind issue, update your `tailwind.config.js` with `primary`, `danger`, `success` and `warning` colors and it should fix the problem.
See documentation [here](https://filamentphp.com/docs/2.x/admin/appearance#building-themes).

**Comment by nsetyo** [comment]
> Definitely a Tailwind issue, update your `tailwind.config.js` with `primary`, `danger`, `success` and `warning` colors and it should fix the problem. See documentation [here](https://filamentphp.com/docs/2.x/admin/appearance#building-themes).

My tailwind config exactly like the one in the documentation as I following it

https://github.com/nsetyo/simimc/blob/34fd4377bd616d90200802ba3083b8f16368d880/app/tailwind.config.js

**Comment by nsetyo** [comment]
> Try upgrading Tailwind? This isnt a Filament issue, Tailwind handles the CSS compilation

I'm using latest tailwind and following guide in the filament documentation

**Comment by nikolaos-spyratos** [comment]
> Try upgrading Tailwind? This isnt a Filament issue, Tailwind handles the CSS compilation

I think it's more around the filament.css - I had this go away as soon as I removed my custom filament.css from the Vite config (wasn't doing anything special with it, just wanted to change the theme's primary colour).
