### ISSUE TITLE
table column searchable with custom query does not set isFirst to false

### ISSUE THREAD

**Issue by ricventu** [laravel-filament/filament#4789]
### Package

filament/tables

### Package Version

v2.16.37

### Laravel Version

v9.38.0

### PHP Version

PHP 8.1

### Problem description

In Resources table method, if the first column is defined as searchable with a custom query, the following searchable columns are not added with or but with and.

### Expected behavior

if the first column is defined as searchable with a custom query, the following searchable columns must be added to the query whit 'or' condition

### Steps to reproduce

Crate UserResource and search by name or email, there are no results

```
    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')->searchable(query: fn ($query, $search) => $query->where('name', 'like', "%$search%")),
                Tables\Columns\TextColumn::make('email')->searchable(),
            ])
```

### Reproduction repository

https://github.com/ricventu/filament-search-issue

### Relevant log output

```shell
select count(*) as aggregate from "users" where ("name" like ? and "email" like ?) 
instead of
select count(*) as aggregate from "users" where ("name" like ? or "email" like ?)
```

**Comment by danharrin** [comment]
Fixed by #4790
