### ISSUE TITLE
Infinite loading on form with Select and FileUpload

### ISSUE THREAD

**Issue by icaliman** [laravel-filament/filament#4791]
### Package

filament/forms

### Package Version

v2.16.37

### Laravel Version

v9.38.0

### Livewire Version

v2.10.7

### PHP Version

PHP 8.1.12

### Problem description

When creating a form with `Select` and `FileUpload` components, it will infinitely request to server

This issue appears only if using `Select` and `FileUpload` components together.

![filament-bug](https://user-images.githubusercontent.com/4498933/199455212-530f180b-5e61-4f59-aefb-d9aff1817a34.gif)

### Expected behavior

No infinite loading

### Steps to reproduce

1. Create a form with `Select` and `FileUpload` components.

```php
                Forms\Components\Select::make('categories')
                    ->label('Categories')->translateLabel()
                    ->multiple()
                    ->relationship('categories', 'name')
                    ->preload(),

                Forms\Components\FileUpload::make('attachments')
                    ->multiple()
                    ->maxFiles(3)
                    ->storeFileNamesIn('attachment_file_names'),
```

2. Add `attachments` and `attachment_file_names` to the model fillable and casts array:
```php
    protected $casts = [
        'attachments' => 'array',
        'attachment_file_names' => 'array',
    ];
```

3. Open the resource **Create** page, upload a file and save the resource

### Reproduction repository

https://github.com/icaliman/filament-bug-infinite-loading

**Comment by icaliman** [comment]
Issue disappeared without storing the original file names:

```php
protected $casts = [
    'attachments' => 'array',
    // 'attachment_file_names' => 'array',  // <------
];
```

```php
Forms\Components\FileUpload::make('attachments')
    ->multiple()
    ->maxFiles(3),
// ->storeFileNamesIn('attachment_file_names'),  // <------
```

**Comment by danharrin** [comment]
Bug in Livewire. Related to array keys that contain `.` triggering watchers erroneously. Bumped this to v3 to see if it will be fixed with Livewire v3 when it arrives.

**Comment by arteriespeter** [comment]
I have the same undesired polling problem with preloaded Select and FileUpload. Does it have a workaround? I had to put the FileUpload to a different page but unfortunately it is not user friendly.

**Comment by danharrin** [comment]
Fixed by Livewire 3.
