### ISSUE TITLE
DateTimePicker is not localized to Japanese

### ISSUE THREAD

**Issue by tf-kwon** [laravel-filament/filament#4817]
### Package

filament/forms

### Package Version

v2.16.37

### Laravel Version

v9.37.0

### Livewire Version

v2.10.7

### PHP Version

PHP 8.1.9

### Problem description

maybe need to change the Japanese locale key in locales to **_ja_** instead of **_js_**.

File: packages/filament/forms/resources/js/components/date-time-picker.js

const locales = {
    ...
    **js: require("dayjs/locale/ja"),**
    ...
};

### Expected behavior

Localized DateTimePicker field

### Steps to reproduce

New install. Change app locale. Create some filamentresource.

### Reproduction repository

No response

### Relevant log output

```shell
No response
```

**Comment by danharrin** [comment]
Can you submit a PR please, if you're not going to provide a reproduction?
