### ISSUE TITLE
disablePlaceholderSelection with required

### ISSUE THREAD

**Issue by howdu** [laravel-filament/filament#4820]
### Package

filament/forms

### Package Version

v2.16.37

### Laravel Version

v9.38.0

### PHP Version

8.1

### Problem description

The default valudate doesn't pass validation, you're required to change the select option. 

### Expected behavior

Click save 

### Steps to reproduce

```
Forms\Components\Select::make('club_id')
    ->relationship('clubs', 'name')
    ->disablePlaceholderSelection()
    ->required(),
```

### Reproduction repository

https://github.com/howdu/filament/

**Comment by danharrin** [comment]
Set a `default()`. Also make some effort when submitting an issue, provide an actual reproduction repo, not a fork of Filament.
