### ISSUE TITLE
generate url filament.resources instead filament.pages. on custom page

### ISSUE THREAD

**Issue by carlituxman** [laravel-filament/filament#483]
**Describe the bug**
The route of generateUrl on custom pages is filament.pages

**To reproduce**
On custom page, I have:
Pages\MyCustom::routeTo('/{record}/test', 'test'),

Then use 
Pages\MyCustom::generateUrl() and it's looking for "filament.pages." route but the route is "filament.resources."

**Comment by danharrin** [comment]
Fixed by #524.
