### ISSUE TITLE
SelectFilter for Resource Table is running SQL query 20 times!

### ISSUE THREAD

**Issue by tangjh** [laravel-filament/filament#4841]
### Package

filament/filament

### Package Version

2.16.40

### Laravel Version

v9.3.10

### Livewire Version

2.10.7

### PHP Version

8.1

### Problem description

SelectFilter for Resource Table is running SQL query 20 times!
UserResource.php line 39.

### Expected behavior

Query should only run once.

### Steps to reproduce

Get the repo and click on User in the menu.  Check the number of queries executed.

### Reproduction repository

https://github.com/tangjh/issue-repo.git

**Comment by awcodes** [comment]
Batch your options in your filter by wrapping them in a function.
```php
Tables\Filters\SelectFilter::make('users')
    ->multiple()
    ->options(fn () => \App\Models\User::all()->pluck('name', 'id')->toArray())
```

**Comment by awcodes** [comment]
Closing as this in not a bug in Filament.
