### ISSUE TITLE
Nested modal not working

### ISSUE THREAD

**Issue by AAbosham** [laravel-filament/filament#4888]
### Package

Other

### Package Version

v2.16.42

### Laravel Version

v8.0

### Livewire Version

v2.0

### PHP Version

PHP 8.1.0

### Problem description

Nested modal not working after this [commit](https://github.com/filamentphp/filament/commit/61a7ae0b4dc03f2046dcd76432995bb9ef9b5a12)

### v2.16.42 modal not working

![image](https://user-images.githubusercontent.com/12083600/201082983-cb17d0fd-8bc3-4c06-beb1-6f1563832298.png)

### v2.16.41 modal working

![image](https://user-images.githubusercontent.com/12083600/201083103-f8829e5b-f1dc-4a08-84dc-8cecdedc6207.png)

### Expected behavior

Nested modal should open from inside modal

### Steps to reproduce

Open create create from inside modal

### Reproduction repository

https://github.com/AAbosham/filament-deme-nested-modal-isssue

**Comment by danharrin** [comment]
How do we reproduce this in the reproduction repo? Looks like you've just cloned the demo.

**Comment by danharrin** [comment]
If we don't have code & instructions to reproduce this with, the issue will be closed

**Comment by AAbosham** [comment]
I only add this action on PostResource

```
 Tables\Actions\ViewAction::make('comments')
                    ->modalContent(fn ($record) => view('test', compact('record'))),
                    
```

![Screenshot 2022-11-10 at 15-31-56 Posts - Filament Demo](https://user-images.githubusercontent.com/12083600/201093015-a866ed17-e59c-4e71-b9d3-c2b7ca79e4c9.png)


![Screenshot 2022-11-10 at 15-32-54 Posts - Filament Demo](https://user-images.githubusercontent.com/12083600/201093033-ccea6b1e-78c4-407b-8fd3-4b94549f022e.png)

**Comment by danharrin** [comment]
It's not possible to nest tables within table actions, since that would break W3 guidelines on nesting `<form>` elements:

![image](https://user-images.githubusercontent.com/41773797/201494080-88238774-5434-4656-a552-5026da44cf98.png)

In v3 we will aim to support this using Livewire v3's upcoming "teleport" feature.
