### ISSUE TITLE
Validation error text color

### ISSUE THREAD

**Issue by danharrin** [laravel-filament/filament#4917]
Sometimes, the validation error text colour is too dark for the background color of the layout component. For example, inside a wizard.

Maybe we should switch to using `danger` with an opacity?

<img width="1334" alt="Screenshot 2022-11-12 at 16 26 17" src="https://user-images.githubusercontent.com/41773797/201484106-ceb377dd-923e-4a24-92d7-b2fc16253196.png">

**Comment by zepfietje** [comment]
I believe Tailwind uses a lighter shade instead of the same as light theme. Will look into this. For v3 only?

**Comment by danharrin** [comment]
Nah, v2 and v3 deserve this. I suggested opacity fix since it will work with any background color.

**Comment by zepfietje** [comment]
Good one. Will have a look what are the pros and cons of each approach.

**Comment by awcodes** [comment]
I don't think opacity will work here. Opacity will make it darker on a dark background. Different colors is the way to go here.
