### ISSUE TITLE
Individual search missing in the query string

### ISSUE THREAD

**Issue by Sicklou** [laravel-filament/filament#4954]
### Package

filament/tables

### Package Version

v2.16.49

### Laravel Version

v9.39.0

### Livewire Version

v2.10.7

### PHP Version

8.1.0

### Problem description

When using the individual search input, the query string isn't changed.

### Expected behavior

That the individual search updates the url as the global search does.

### Steps to reproduce

Make a search in an individual search bar and add query string property in the component.

### Reproduction repository

https://github.com/filamentphp/filament

**Comment by zepfietje** [comment]
@Sicklou, check out the docs: https://filamentphp.com/docs/2.x/tables/getting-started#query-string.

**Comment by Sicklou** [comment]
> @Sicklou, check out the docs: https://filamentphp.com/docs/2.x/tables/getting-started#query-string.

Nothing says about it in the doc.
So I submitted a PR : https://github.com/filamentphp/filament/pull/4955

**Comment by zepfietje** [comment]
Ah it wasn't clear to me you referred to the column search. Just reviewed your PR.
