### ISSUE TITLE
v2.16.50 Is missing correct module.esm.js

### ISSUE THREAD

**Issue by dejury** [laravel-filament/filament#4973]
### Package

filament/forms

### Package Version

v2.16.50

### Laravel Version

v9.40.1

### Livewire Version

v2.10.7

### PHP Version

PHP 8.0.25

### Problem description

The last update of filament (filament 2.16.50) should contain fixes for the position of the select field.
Somehow the `module.esm.js` file is not updated in this release, which prevents the javascript updates to be available.
In your 2.x branch this file is updated, but this is excluded in the release?

See: https://github.com/filamentphp/filament/commit/6bd78a82e8a9662c998c6595900a4fae96c2909b#diff-52eec58e4c339353875fe1cc54fc37d0c7685e67995861626d63b82142f42ef2

### Expected behavior

Updated file with the position changes.
Would love to see an update for this soon, customer is awaiting this changes.

### Steps to reproduce

```php
Select::make('field')
      ->multiple()
      ->position('top'),
```

### Reproduction repository

https://github.com/dejury/filament

**Comment by danharrin** [comment]
.51 should fix this
