### ISSUE TITLE
Using Filament\Facades\Filament before boot makes FilamentServiceProvider->packageRegistered() not working properly

### ISSUE THREAD

**Issue by xiaomlove** [laravel-filament/filament#4974]
### Package

filament/filament

### Package Version

v2.16.41

### Laravel Version

v9.40.1

### Livewire Version

v2.10.7

### PHP Version

PHP 8.1.2

### Problem description

Pre-registering a Resource in the register() method of some ServiceProviders  prevents all the Resources in app/Filament/Resources from registering routes.

### Expected behavior

Registering a Resource in any location does not affect the route registration of the original location Resource, similar to the effect before 2.15.16.

### Steps to reproduce

Call Filament::register() in the AppServiceProvider's register() method to register a Resource in any of the `app/Filament/Resources` directories, and you'll see that `/admin` is already 404.

- git clone https://github.com/xiaomlove/filament-test.git
- cp .env.example .env, modify it to fill in your database connection
- run composer install
- run php artisan migrate
- run php artisan make:filament-user
- visit /admin, OK
- git checkout -b move_registration origin/move_registration
- run composer install
- visit /admin，got 404

The main branch in the example repository is version 2.15.15 and the move_registration branch is version 2.15.16. The two branches have only been upgraded and nothing else has changed.

This issue was caused by [this commit](https://github.com/filamentphp/filament/commit/544615fae547ed697520602058680da16910ee37).

### Reproduction repository

https://github.com/xiaomlove/filament-test

**Comment by danharrin** [comment]
Yeah this is a known issue, you should use a `PluginServiceProvider` to ensure that resources are registered in the correct order.
