### ISSUE TITLE
The 'admin' menu in the lower left corner is not available if debugbar is installed

### ISSUE THREAD

**Issue by rabol** [laravel-filament/filament#498]
**Describe the bug**
The 'admin' menu in the lower right corner is not available if debugbar is installed

**To reproduce**
1. composer require barryvdh/laravel-debugbar --dev
2. goto the /admin
3. Scroll down 

**Expected behavior**
Would expect the menu to adapt to the space available.

**Screenshots**

![Screenshot 2021-07-26 at 14 11 38](https://user-images.githubusercontent.com/1177191/126986685-d08c5b43-caf5-4ea2-8180-824a9af9f512.png)

**Context**
- Package version: 1.10.6
- Livewire version: 2.5.5
- Laravel version: 8.51.0
- Browser: Edge
- Server OS: MacOS 11.5
- PHP version: 8.0.3
- Database: MySQL 8.0.23

**Additional details**
Add any other details about the problem here.

**Comment by danharrin** [comment]
You can close Debugbar to access the menu.

https://user-images.githubusercontent.com/41773797/127020654-34baa241-0d6f-417d-86ab-24d7d7a4b0a9.mov

**Comment by rabol** [comment]
I know I can close, but other apps don't have the issue
