### ISSUE TITLE
Support custom color and size

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#5038]

**Comment by awcodes** [comment]
Color and size across the board or does this apply to specific components?

Also, size in regards to what exactly? Icon size, font size? These have different implications and meanings depending on what methods are being used to set them.

**Comment by zepfietje** [comment]
This issue concerns color and size in different places. Currently, some places allow passing a custom color instead of primary and such. It's not supported everywhere so needs to be updated across the entire project to make sure it works the same in all places where you can pass a color or size.

@danharrin and I have discussed this previously.

I've actually started working on this already and hope to finish today.
