### ISSUE TITLE
Bind fields to nested properties in forms not working

### ISSUE THREAD

**Issue by newuni** [laravel-filament/filament#5042]
### Package

filament/filament

### Package Version

v.2.16.52

### Laravel Version

v9.41.0

### Livewire Version

v2.10.7

### PHP Version

PHP 8.1.11

### Problem description

According to [doc](https://filamentphp.com/docs/2.x/forms/fields#text-input:~:text=Fields%20may%20be%20created%20using%20the%20static%20make()%20method%2C%20passing%20its%20name.%20The%20name%20of%20the%20field%20should%20correspond%20to%20a%20property%20on%20your%20Livewire%20component.%20You%20may%20use%20Livewire%27s%20%22dot%20syntax%22%20to%20bind%20fields%20to%20nested%20properties%20such%20as%20arrays%20and%20Eloquent%20models.):

_Fields may be created using the static make() method, passing its name. The name of the field should correspond to a property on your Livewire component. You may use Livewire's "dot syntax" to bind fields to nested properties such as arrays and Eloquent models._

When trying to bind a TextField to a nested property of a BelongsTo relationship the field renders empty. On the other hand, if I use this same mechanism in a table column, it is displayed correctly.

Forms\Components\TextInput::make('woffuUser.nombreCompleto'), => empty field
Tables\Columns\TextColumn::make('woffuUser.nombreCompleto')->searchable()->sortable(), => displayer correctly

### Expected behavior

Show the value of the nested properties.

### Steps to reproduce

Try to bind a nested property to a TextInput. Please see reproduction repository, Filament/Resources/CommentResource.php:29

### Reproduction repository

https://github.com/newuni/filament-nested-broken

**Comment by newuni** [comment]
To get around the problem, I am temporarily using  mutateFormDataBeforeFill for in my ViewRecord in order to show value properly. Using this I can render value properly.

` protected function mutateFormDataBeforeFill(array $data): array
    {
        $cliente = Client::find($data['client_id']);
        $data['cliente_id'] = $client->name;

        return $data;
    }`

**Comment by danharrin** [comment]
Relationships arent loaded into the form data because that causes unintended side effects with casting. Use this instead - https://filamentphp.com/docs/2.x/forms/layout#saving-data-to-relationships

**Comment by newuni** [comment]
Thanks,

sorry for late reply.
