### ISSUE TITLE
Select searchable getSearchResultsUsing problem

### ISSUE THREAD

**Issue by hahatulk** [laravel-filament/filament#5054]
### Package

filament/forms

### Package Version

2.16.52

### Laravel Version

9.41

### PHP Version

8.1/8.0.2 tested

### Problem description

Full options list not appearing when search field is emptied

### Expected behavior

Initial list should appear after search field is emptied

### Steps to reproduce

![image](https://user-images.githubusercontent.com/32220397/203820845-a9f1d335-ef57-43bc-8168-b37d0d879e94.png)
![image](https://user-images.githubusercontent.com/32220397/203821015-27a4454c-bd1d-46b9-85a6-cda2dd675527.png)

https://user-images.githubusercontent.com/32220397/203820913-fb5b2204-0544-48d3-8552-e402396bf954.mp4

### Reproduction repository

https://github.com/hahatulk/filament-select-bug

**Comment by danharrin** [comment]
Unfortunately this is an issue with our Select library Choices.js - the `search` event we listen for isn't fired when the field is empty :(

**Comment by Welfordian** [comment]
@danharrin This bug is still present in v3. Any plans to switch to a different Select library in v4?

**Comment by danharrin** [comment]
Any suggestions? I struggle to find one that has everything we need.

**Comment by danharrin** [comment]
I worked on a new custom one, will see how testing goes during the beta period, I might need to revert back to Choices.js if its bad - #16612
