### ISSUE TITLE
min() and max() is not rendered on textinput

### ISSUE THREAD

**Issue by rabol** [laravel-filament/filament#507]
**Describe the bug**
the min and max attributes of a number input is not rendered in the html

**To reproduce**
1. create a resource
2. add this in the form() method:
TextInput::make('price')->type('number')->min(0)->max(9999)->extraAttributes(['step' =>'0.1'])->numeric(),

**Expected behavior**
that the minimum value allowed in the input would be 0

**Screenshots**
![Screenshot 2021-07-27 at 13 39 52](https://user-images.githubusercontent.com/1177191/127147678-6b12529c-e8f6-46c4-8722-53e3d7b77821.png)

**Context**
- Package version: 1.10.6
- Livewire version: 2.5.5.
- Laravel version: 8.51.0
- Browser: Edge
- Server OS: [e.g. Ubuntu 18.04.4]
- PHP version: [e.g. 7.4]
- Database: [e.g. MySQL 8.0]

**Additional details**
Add any other details about the problem here.

**Comment by danharrin** [comment]
This is not technically a bug, as the backend `min` / `max` validation is still applied (let me know if this isn't the case). Feel free to submit a PR adding this new feature, else it will be available in v2.

**Comment by rabol** [comment]
why is it not a bug ?
there is a property on the input and it does not work

**Comment by ryangjchandler** [comment]
@rabol Those methods do not target the HTML attributes, they apply the `min` and `max` validation rules.

**Comment by danharrin** [comment]
You'd need two extra properties on the class to render the attributes, so feel free to make a PR if you want that behaviour.

**Comment by ryangjchandler** [comment]
Or just use the `->extraAttributes` methods to add them.

**Comment by danharrin** [comment]
Hi, just FYI this feature has been implemented in v2.
