### ISSUE TITLE
searchable does not work with the associated table containing a json type column

### ISSUE THREAD

**Issue by saidhappy010** [laravel-filament/filament#5090]
### Package

filament/tables

### Package Version

^2.0

### Laravel Version

^9.19

### Livewire Version

^2.10

### PHP Version

^8.1

### Problem description

I have 2 tables, school and state
the school table has a foreign key (city_id),
I am displaying school info like (name, address and state).
This is my code
In class School I have

```
public function getTableQuery(): \Illuminate\Database\Eloquent\Builder
{
    $query = School::query();
    return $query;
}

protected function getTableColumns(): array
{
    return [
      TextColumn::make( 'name' )
        ->label( __( 'name' ) )
      TextColumn::make( 'state.city.name' )
        ->label( __( 'state' ) )
        ->searchable('state.city.name' ),
     ];
}
```
models

```
class School extends Model {
    public function city(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo( City::class, 'city_id', 'id' );
    }
}
```
```
class City extends Model {
    public function state(): \Illuminate\Database\Eloquent\Relations\BelongsTo
    {
        return $this->belongsTo( State::class, 'state_id', 'id' );
    }

    public function schools(): \Illuminate\Database\Eloquent\Relations\HasMany
    {
        return $this->hasMany( School::class, 'city_id', 'id' );
    }
}
```

I would like to search by name of city, but it does not work.
if I search by city id it works fine, but by name not.
knowing that the name column is a json type (for the translation).
that's why maybe I can have the result.

### Expected behavior

I think we need to add an option so that we can rename the columns (alias).
I think the problem is that the 3 tables have a column called name,
and always the query is based on the first column name of the first table in this case it is the schools table
 it is for maybe that there is an ambiguity between the tables.

### Steps to reproduce

sorry no idea

### Reproduction repository

https://github.com/saidhappy010/searchable_issue.git

**Comment by danharrin** [comment]
Fixed in v3 by #5359.

In v2, you can use:

```php
TextColumn::make( 'city.state.name' )
    ->label( __( 'name of state' ) )
    ->searchable(query: function ($query, $search) {
        return $query->whereHas('city', function ($query) use ($search) {
            return $query->whereHas('state', function ($query) use ($search) {
                return $query->whereRaw('lower(states.name) like ?', "%{$search}%");
            });
        });
    }),
```
