### ISSUE TITLE
Dependable toggle component causing weird side affects if wrapped in a Group Component and/or Tab Component

### ISSUE THREAD

**Issue by jamie-brown** [laravel-filament/filament#513]
**Describe the bug**
When wrapping a KeyValue Component inside of a Component Group that is dependable from an outside Toggle Component, the Key/Value does not render properly (does not show the input fields) and does not allow you to add rows.

**To reproduce**
1. Create a toggle component that is dependable
2. Wrap a KeyValue component inside a Group Component
3. Ensure the group component has a when method chained which only shows when the toggle component is true
4. Reload the browser window and activate the toggle.

**Expected behavior**
I expect the KeyValue component to render the input fields so I can add key/value pairs and also when I click on the 'Add Row' button it adds another row.

**Screenshots**
<img width="1404" alt="Screenshot 2021-08-04 at 10 12 41" src="https://user-images.githubusercontent.com/3788827/128156174-9a53dbe3-893e-4463-a3cc-c4fcd2ad46c9.png">
<img width="1266" alt="Screenshot 2021-08-04 at 10 15 07" src="https://user-images.githubusercontent.com/3788827/128156185-5ce9ce2c-9d05-4ceb-9d38-b6932249ca5c.png">
<img width="1266" alt="Screenshot 2021-08-04 at 10 24 46" src="https://user-images.githubusercontent.com/3788827/128157161-08612370-7cb4-4a3d-938c-d00c8d9b1801.png">

https://user-images.githubusercontent.com/3788827/128156092-e0c69787-20c2-45b4-990d-bd3a56fd4733.mov
https://user-images.githubusercontent.com/3788827/128156251-c8b206f3-514e-4c90-ae85-6d6e5417a26f.mov

**Context**
- Package version: 1.10.6
- Livewire version: 2.5.5
- Laravel version: 8.52
- Browser: Chrome, Safari, Firefox
- Server OS: MacOS Monteray
- PHP version: 8.0.6
- Database: [e.g. MySQL 8.0]

**Additional details**
I have also added another video that highlights that this issue with the Toggle component also causes problems when it is wrapped inside of a Tab Component. The tab contents do not show at all and then when you switch back to the original tab, the whole of the contents of the second tab displays inside of the first tab. 

Finally, as you can see in the video, the tab immediately deactivates again when you toggle it to true.

**Comment by danharrin** [comment]
Hey, are there any console errors for either of these? It's definitely a bug with Alpine.js, maybe when we upgrade to Alpine v3 it will fix itself.

**Comment by danharrin** [comment]
Hi Jamie, is this still an issue?

**Comment by jamie-brown** [comment]
Hi Dan, 

Sorry for the delay. I will try to reproduce this and let you know if it is still an issue. 

I'll hopefully get back to you at some point today 👍🏻.

**Comment by danharrin** [comment]
Ah, how have you been working around it in the meantime?
