### ISSUE TITLE
Rich editor - Link Input text color not readable

### ISSUE THREAD

**Issue by sbritz** [laravel-filament/filament#5131]
### Package

filament/forms

### Package Version

v2.0

### Laravel Version

v9.19

### Livewire Version

v2.10

### PHP Version

8.1.3

### Problem description

Hi,
if using the link-function of Rich editor in dark mode, you cannot read the input-value because the input-text-color is light and the input-field itself is a white field. It's a css-problem.
<img width="550" alt="Bildschirmfoto 2022-12-01 um 18 33 15" src="https://user-images.githubusercontent.com/25327081/205133379-68c591e3-003a-40c8-99a6-da97f10c6f27.png">

### Expected behavior

I expect a dark  text-color in this link input-field or better a dark input-field, cause it looks nicer. ;)

### Steps to reproduce

link-function of Rich editor in dark-mode

### Reproduction repository

https://github.com/sbritz/filament-blog-demo.git

**Comment by danharrin** [comment]
Fixed by #5216
