### ISSUE TITLE
Stats card graph color requires reload after switching dark mode

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#5134]

**Comment by zepfietje** [comment]
@awcodes, #5615 doesn't seem to have fixed the issue for me.
I'm getting `Alpine Expression Error: Maximum call stack size exceeded.` in Safari macOS.
Could you test it once more on your end?

**Comment by danharrin** [comment]
Hmm ok I've reverted it for now

**Comment by danharrin** [comment]
and the branch is restored so we can reopen the PR :)

**Comment by zepfietje** [comment]
Thanks, @danharrin.
I'm unable to reopen the PR, can you or @awcodes?

**Comment by danharrin** [comment]
its not possible to reopen the same pr after merge, but we can open a new one with the restored branch

**Comment by awcodes** [comment]
I wasn't getting any errors and it worked correctly, but yea I can look again.

**Comment by danharrin** [comment]
thanks Adam, no rush though ☺️

**Comment by zepfietje** [comment]
Hmm, did my changes break it or did you test after that, @awcodes?
Happy to help, so just let me know.

**Comment by awcodes** [comment]
I think https://github.com/filamentphp/filament/pull/5615#discussion_r1096578206 breaks it.

Calling update in this context is likely causing it to loop it's alpine update. That's probably why I had to destroy it and re-initialize it on the dark mode event listener.

**Comment by zepfietje** [comment]
Hmm it's weird that we have to reinitialize the entire chart, but it works indeed.
Was able to clean up the fix massively: https://github.com/filamentphp/filament/pull/5630.
