### ISSUE TITLE
Notification position animation broken

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#5152]
Broken since 2.16.0: https://github.com/filamentphp/filament/pull/3847.

**Comment by awcodes** [comment]
What exactly is broken? Having trouble getting context for this.

**Comment by zepfietje** [comment]
The notification should slide in horizontally.
Currently, that doesn't happen and the notification just appears without animation.

I think this might be related to the notifications with actions issue I reported on Discord recently.
The notification animation is triggered by the notifications Livewire component response hook in JS.
Most probably something goes wrong there.

**Comment by awcodes** [comment]
These are animating correctly for me in Chrome, Safari and Firefox.

**Comment by zepfietje** [comment]
Sorry, I was wrong.
It's not about the horizontal animation, but the vertical position animation when new notifications slide in.

Try spamming the save button here: https://demo.filamentphp.com/shop/products/1/edit?activeRelationManager=0.

Context: AFAIK this only happens in admin panel or pages which have actions.
