### ISSUE TITLE
Cast evaluate results

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#5163]
https://github.com/filamentphp/filament/pull/5108#discussion_r1038129755

**Comment by zepfietje** [comment]
@danharrin, I'm not entirely sure when we'd like to cast. It's a little tricky with nullable values.

**Comment by danharrin** [comment]
Only for `: bool` returns I think

**Comment by zepfietje** [comment]
Ok, will have a look.

**Comment by danharrin** [comment]
7674874349eb0eb98f12492272481d01fef93309

**Comment by danharrin** [comment]
7674874349eb0eb98f12492272481d01fef93309

**Comment by zepfietje** [comment]
Perfect, thanks.
