### ISSUE TITLE
Declaration of Filament\Support\Components\ViewComponent::view(string $view): static must be compatible with Illuminate\View\Component::view($view, $data = [], $mergeData = [])

### ISSUE THREAD

**Issue by accesstechnology-mike** [laravel-filament/filament#5181]
### Package

filament/filament

### Package Version

v2.13.21

### Laravel Version

v9.42.2

### Livewire Version

v2.10.6

### PHP Version

PHP 8.0.3

### Problem description

Filament does not run on this config. 
Error: Declaration of Filament\Support\Components\ViewComponent::view(string $view): static must be compatible with Illuminate\View\Component::view($view, $data = [], $mergeData = [])

### Expected behavior

Filament to load

### Steps to reproduce

composer update...

### Reproduction repository

N/A

**Comment by danharrin** [comment]
This was caused by a Laravel breaking change months ago, which prompted us to stop extending their View component class. The fact youre still getting this error is a symptom that your Filament version is not up to date

**Comment by accesstechnology-mike** [comment]
That's got it, thanks

**Comment by abdulwahhabkhan** [comment]
I was getting this error but after upgrading to Laravel 9.48 it resolved.
