### ISSUE TITLE
Pagination query count bug

### ISSUE THREAD

**Issue by hejcmichal** [laravel-filament/filament#5196]
### Package

filament/filament

### Package Version

v2.16.54

### Laravel Version

v9.43.0

### Livewire Version

v2.10.7

### PHP Version

PHP 8.1.10

### Problem description

Problem with query to generate pagination in case of [-1] (all records). In this case `$query-count()` is called to fill the perPage parametr on line 33 - CanPaginateRecords.php When you have some GROUP BY statement in query this doesnt work. The reason is that the result SQL statement dont have whole query in subquery and aggregate function counting through the grouped results. Result is count of all records of first row from query.

SQL Example:

`select count(*) as aggregate from `to_invoice` left join `to_invoice_toggl_ac_entries_bind` on `to_invoice`.`id` = `to_invoice_toggl_ac_entries_bind`.`to_invoice_id` left join `toggl_ac_entries_bind` on `to_invoice_toggl_ac_entries_bind`.`toggl_entry_id` = `toggl_ac_entries_bind`.`toggl_entry_id` group by `to_invoice`.`id` order by `to_invoice`.`timestamp` desc`

### Expected behavior

`select count(*) as aggregate from (SELECT to_invoice.id FROM `to_invoice` left join `to_invoice_toggl_ac_entries_bind` on `to_invoice`.`id` = `to_invoice_toggl_ac_entries_bind`.`to_invoice_id` left join `toggl_ac_entries_bind` on `to_invoice_toggl_ac_entries_bind`.`toggl_entry_id` = `toggl_ac_entries_bind`.`toggl_entry_id` group by `to_invoice`.`id` order by `to_invoice`.`timestamp` desc) as subquery;`

### Steps to reproduce

Use some GROUP BY statement in query.

### Reproduction repository

dont have yet

**Comment by mackhankins** [comment]
@hejcmichal  Did you ever solve this?  I'm running into a similar issue.

**Comment by khusan-dev** [comment]
> @hejcmichal Did you ever solve this? I'm running into a similar issue.

Not the best solution, but nevertheless the problem is solved.

```php
protected function getTableRecordsPerPage(): int
    {
        if ($this->tableRecordsPerPage < 0){
            return 99999999999999999;
        } else {
            return $this->tableRecordsPerPage;
        }
    }
```
