### ISSUE TITLE
Loading indicators heavily impact diffing performance

### ISSUE THREAD

**Issue by pxlrbt** [laravel-filament/filament#5210]
### Package

filament/tables

### Package Version

v2.x

### Laravel Version

Any

### Livewire Version

Any

### PHP Version

Any

### Problem description

When filtering/updating tables with large datasets the tables' loading indicators cause massive performance issues, sometimes taking a 800ms request up to 10s in total time. A reload is faster than request via Livewire.

250 records with 4 columns will result in 1000 loading indicators.

Example: Filtering 292 items to 41 items:

https://user-images.githubusercontent.com/22632550/206466920-508fd08d-d18a-42cf-9a27-a8448508ab05.mov

### Expected behavior

Faster loading:

https://user-images.githubusercontent.com/22632550/206466733-089fcc45-4834-4261-b0a3-e8c6d10f1f6e.mov

### Steps to reproduce

- Large table with > 100/200 entries.
- Filter from All to a small set
- 

### Reproduction repository

2 private repos available from me and "hmihail"

**Comment by danharrin** [comment]
Closing as stale.
