### ISSUE TITLE
Searchable query doesn't handle or when is not first searchable

### ISSUE THREAD

**Issue by ricventu** [laravel-filament/filament#5222]
### Package

filament/tables

### Package Version

v2.16.55

### Laravel Version

v9.43.0

### PHP Version

8.1.11

### Problem description

if resource has searchable that is not the first column, the query is added with AND 

### Expected behavior

if resource has searchable that is not the first column, the query is added with OR 

### Steps to reproduce

```php
    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')->searchable(),
                Tables\Columns\TextColumn::make('email')
                    ->searchable(query: fn ($query, $search) => $query->where('email', 'like', "%$search%")),
            ])
```

### Reproduction repository

https://github.com/ricventu/filament-search-issue

### Relevant log output

```shell
query is

select count(*) as aggregate from `users` where (`name` like ? and `email` like ?) ["%test%","%test%"] 


instead of
```sql
select count(*) as aggregate from `users` where (`name` like ? OR `email` like ?) ["%test%","%test%"] 
```
```

**Comment by danharrin** [comment]
Fixed by #5223
