### ISSUE TITLE
$dataChecksum error on updatedFilter

### ISSUE THREAD

**Issue by studio-creativo** [laravel-filament/filament#5237]
### Package

filament/filament

### Package Version

v2.16.19

### Laravel Version

v9.33.0

### Livewire Version

v2.10.7

### PHP Version

PHP 8.0.21

### Problem description

I created a chart widget that works correctly after mount, but when I hit the filter button the chart doesn't refresh and instead I get this error:
**Typed property Filament\Widgets\ChartWidget::$dataChecksum must not be accessed before initialization**

I tried to add this on top of my widget class:
public string $dataChecksum = '';
And if i add an empty string to this variable the chart works.

### Expected behavior

I can update the chart when hit the filter button.

### Steps to reproduce

Create a new chart widget, add some data and filters as the documentation says and try to update the chart hitting the filter.

### Reproduction repository

https://github.com/filamentphp/filament

**Comment by AshishDhamalaAD** [comment]
I also had the same issue.
The widgets are lazily loaded by default. If you have more widgets on the dashboard and some of them are not in the view and then if we change the filters, we get this issue.

@studio-creativo for now, you can add this on your widget class and you won't get this error:
`protected static bool $isLazy = false;`

I hope it helps
