### ISSUE TITLE
Edit page - delete button error

### ISSUE THREAD

**Issue by leandrocfe** [laravel-filament/filament#5240]
### Package

filament/filament

### Package Version

v2.16.55

### Laravel Version

v9

### Livewire Version

v2

### PHP Version

8.1

### Problem description

Edit page - Error 500 when the delete button is clicked.
https://www.veed.io/view/88817495-3db8-4d58-8e71-a6b0e2e1b2b0?sharingWidget=true&panel=share

### Expected behavior

200 status code

### Steps to reproduce

Go to the posts page and edit a post. Ex: https://demo.filamentphp.com/blog/posts/9/edit?activeRelationManager=0
Click on the delete button.

### Reproduction repository

https://github.com/leandrocfe/filament-demo

### Relevant log output

```shell
local.ERROR: Missing required parameter for [Route: filament.resources.posts.view] [URI: admin/posts/{record}] [Missing parameter: record]...
```

**Comment by danilopolani** [comment]
The delete button in the hosted demo app (on filament domain) works fine to me. Is your repository any way different from the demo one?

**Comment by leandrocfe** [comment]
> The delete button in the hosted demo app (on filament domain) works fine to me. Is your repository any way different from the demo one?

Take a look:

![image](https://user-images.githubusercontent.com/3833889/207891455-8c4c96a3-f059-4e82-b8ed-932625d52698.png)
![image](https://user-images.githubusercontent.com/3833889/207891561-0041c9ef-8531-4f83-a967-3175e761079e.png)
![image](https://user-images.githubusercontent.com/3833889/207891685-f15cea8c-b196-41f5-9c9b-e2613486f2d7.png)

**Comment by vdeville** [comment]
Hello,

Same problem for me when delete one ressource
`
[2022-12-15 16:03:58] local.ERROR: Missing required parameter for [Route: filament.resources.documents.edit] [URI: admin/documents/{record}/edit] [Missing parameter: record]. {"userId":"df19dc58-0348-42da-8c11-af14b70eaac6","exception":"[object] (Illuminate\\Routing\\Exceptions\\UrlGenerationException(code: 0): Missing required parameter for [Route: filament.resources.documents.edit] [URI: admin/documents/{record}/edit] [Missing parameter: record]. at /usr/src/app/vendor/laravel/framework/src/Illuminate/Routing/Exceptions/UrlGenerationException.php:35)
`

**Comment by danilopolani** [comment]
Oh right, it happens only for a sec.

**Comment by RizwanNaasir** [comment]
The Reason for this is when delete the record successfully by default filament will redirect you back to that record. yes that is deleted so that's why you are receiving required attribute is missing which is the id of deleted record.
You can override in any of resource pages.
```php

public function getRedirectUrl(): string
{
    return $this->getResource()::getURL('index');
}
```

**Comment by danharrin** [comment]
For me, it's actually being caused by Livewire and not Filament. Livewire tries to generate the URL with a null record with its "browser history" feature

**Comment by ftzero** [comment]
Hello,

Is there any progress on this i am getting the same error?

**Comment by diegobas** [comment]
In Filament/Resources/Pages/EditRecord.php, method `delete()`, I get that `$this->getDeleteRedirectUrl() `is deprecated, but changing it by the suggested method `$this->successRedirectUrl()` does nothing to solve the error. Instead, changing the line: 

`$this->redirect($this->getDeleteRedirectUrl());`

by:

`$this->dispatchSuccessRedirect();`

the error disappears.

**Comment by danharrin** [comment]
Still a LW bug, but a workaround has been implemented in #5738

**Comment by abanghendri** [comment]
Hi, a face an error too on delete button, but different error
my error is `SQLSTATE[HY000]: General error: 1008 Can't drop database 'tenanttenant2'; database doesn't exist (Connection: mysql, SQL: DROP DATABASE `tenanttenant2`)` when I delete 'tenant2' record
FYI, tenant2 is a new record I made before, without any relationship with another model
this is my TenancResource
```<?php

namespace App\Filament\Resources\Admin;

use App\Filament\Resources\Admin\TenantResource\Pages;
use App\Filament\Resources\Admin\TenantResource\RelationManagers;
use App\Models\Tenant;
use Filament\Forms;
use Filament\Forms\Components\TextInput;
use Filament\Resources\Form;
use Filament\Resources\Resource;
use Filament\Resources\Table;
use Filament\Tables;
use Filament\Tables\Columns;
use Filament\Tables\Columns\TextColumn;
use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\SoftDeletingScope;

class TenantResource extends Resource
{
    protected static ?string $model = Tenant::class;

    protected static ?string $navigationIcon = 'heroicon-o-collection';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                TextInput::make('id')->autofocus()->placeholder('Tenant ID')
            ]);
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('id')->label('Tenant'),
                TextColumn::make('created_at')->dateTime()->label('Created'),
                TextColumn::make('name')->label('Users')
            ])
            ->filters([
            ])
            ->actions([
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\DeleteBulkAction::make(),
            ]);
    }
    
    public static function getRelations(): array
    {
        return [
            RelationManagers\UsersRelationManager::class
        ];
    }
    
    public static function getPages(): array
    {
        return [
            'index' => Pages\ListTenants::route('/'),
            'create' => Pages\CreateTenant::route('/create'),
            'edit' => Pages\EditTenant::route('/{record}/edit'),
        ];
    }    
}
```

how to fix this?

**Comment by danharrin** [comment]
Filament doesnt control dropping tenant databases so its probably not something we can help with

**Comment by abanghendri** [comment]
oops, my fault
I build single database multi tenant app using https://tenancyforlaravel.com/ and forget to comment Jobs\DeleteDatabase::class on delete tenant action pipelines

**Comment by danharrin** [comment]
Please seek support from that community, all Filament does is delete the DB record.
