### ISSUE TITLE
I have error, when uploading SVG to FileUpload form.

### ISSUE THREAD

**Issue by starcevpro** [laravel-filament/filament#5261]
### Package

filament/filament

### Package Version

v2.16.56

### Laravel Version

v9.43.0

### Livewire Version

v2.10.7

### PHP Version

v8.1.13

### Problem description

I have error, when uploading files to FileUpload form.

### Expected behavior

![image](https://user-images.githubusercontent.com/24702947/207858038-a44dc4dd-4cb2-467c-a627-20c6f560ee53.png)
![image](https://user-images.githubusercontent.com/24702947/207858091-5451ebbf-9ea9-4094-bfca-ba663ea0cc02.png)

If you click on the link in the console, my SVG will open.

Data and file name are written to the database correctly.
![image](https://user-images.githubusercontent.com/24702947/207858872-b1d30c52-480e-4205-ba97-65aa5af45ad5.png)

### Steps to reproduce

add this form to resource
```php
Forms\Components\FileUpload::make('icon')->image(),
```

when upload SVG file

### Reproduction repository

https://github.com/starcevpro/filament-problem

**Comment by danharrin** [comment]
Your APP_URL is set wrong.

**Comment by starcevpro** [comment]
Thanks, but now I have another problem, I will open a new issue
