### ISSUE TITLE
app.css/app.js Failed to load resource: the server responded with a status of 404 ()

### ISSUE THREAD

**Issue by adrianschenker** [laravel-filament/filament#5276]
### Package

filament/filament

### Package Version

v2.16.57

### Laravel Version

v9.4.0

### Livewire Version

v2.10.7

### PHP Version

PHP 8.1

### Problem description

Hello everyone!

I worked already with filament and never faced a similar issue like this. I often worked on a shared hosting and everything worked perfectly. Now I set up a VPS and installed CloudPanel (https://www.cloudpanel.io/). In cloud panel I can define if it is a PHP-application (with laravel) - and I guess, this has an impact on the nginx settings at the end.

After I set up my laravel application, installed livewire and filament, I navigate to `/admin`. The page shows up and I can login. But the page looks bad (how a page looks when a CSS-file cannot be found) and the console tells me, that the resource files cannot be found:
`app.css - Failed to load resource: the server responded with a status of 404 ()`
`app.js - Failed to load resource: the server responded with a status of 404 ()`

As I've seen, I am not the first person with that error (However, according to the number of results on google - it is nothing that happens quite often I think :) ) - so I tried these solutions:

**Adapting the nginx config file:**
_Explained here: https://kodekativ.co/s/nginx-configuration-for-laravel-filament-5fBR_
This changes the error 404 in the console to "Refused to execute script because strict MIME type..." - which I guess occurs because of the sames problem...
_A similar explanation I found, didn't work either: https://stackoverflow.com/questions/74196740/digital-ocean-app-platform-laravel-filament_

**Checking if accessible over http (insted https):**
I removed the 301 redirect and tried to access via http - same problem.

**Extending AppProvider:**
I also added the following in the "boot()":
`if (app()->isProduction()) {
      \URL::forceScheme('https');
      \URL::forceRootUrl(config('app.url'));
}`
Doesn't help... I see the effect, when I disable the 301 redirect in nginx config. But it doesn't solve the problem.

**Try another server:**
I moved the project to another server (in this case with plesk installed) - everything works. 

So, I guess the problem is in the nginx config. So, it is actually not a filament problem :) But maybe you can help me a lot, by quickly looking over my nginx config. The rest of the laravel application is working perfectly.
[nginxconfig.txt](https://github.com/filamentphp/filament/files/10250958/nginxconfig.txt)

Thanks in advance!

### Expected behavior

If I navigate to /admin, it should show a proper login page. As well as a proper dashboard when I log in.

### Steps to reproduce

As it worked when I moved the project to another server, the only way (that I see) to reproduce it, is to use my attached nginx configuration.

### Reproduction repository

https://github.com/adrianschenker/ngfm12341234/

**Comment by adrianschenker** [comment]
I fixed it by copying from the vendor folder. I will close the issue - thanks!

**Comment by danharrin** [comment]
I would advise against copying because the assets will become out of date. Check https://github.com/livewire/livewire/issues/242#issuecomment-948054946

**Comment by adrianschenker** [comment]
Thanks for your reply @danharrin ! 

Meanwhile I went through the books about nginx settings again. I managed to make it work like it should :) 
Really awesome solution!! Thanks a lot for your great work!

**Comment by rich06** [comment]
Can someone please tell me what the fix is here? I just installed Filament and the app.css and app.js resources are both throwing 404s. The article linked at by @danharrin refers to a Livewire resource load issue ... so what should I do to get Filament working? 

NB: I tried the nginx directive change suggested in that article but that didn't work.

Basically these links are 404'ing and thus Filament is unusable:-

```
<domain>/filament/assets/app.css 
<domain>/filament/assets/app.js 

```
Thanks!

**Comment by danharrin** [comment]
There isnt a solution I can write up that fits everyone, because everyone has their own unique server configurations. It's always people who are not following the Laravel recommended Nginx configuration or not using Forge/Vapor who have issues. I really dont know how to help with that, nor do I have time to be honest.

**Comment by danharrin** [comment]
I'd like to add - I've never heard of anyone who has flat out been unable to get Filament working in the end. They always work it out. It takes some debugging and tweaking, and often checking against the Laravel recommended Nginx configuration, but it's definitely not impossible.

**Comment by rich06** [comment]
@danharrin - thanks for your response. I've fixed it by changing the nginx config as per the following tricks page:- [https://filamentphp.com/tricks/fix-filament-assets-nginx](url)

Sorry for the noise.

**Comment by faizananwerali** [comment]
> 

not working, instead, it is showing the main website of the index.php

**Comment by faizananwerali** [comment]
> @danharrin - thanks for your response. I've fixed it by changing the nginx config as per the following tricks page:- [https://filamentphp.com/tricks/fix-filament-assets-nginx](url)
> 
> Sorry for the noise.


not working, instead, it is showing the main website of the index.php
