### ISSUE TITLE
Replicate action attempting to replicate non-column

### ISSUE THREAD

**Issue by howdu** [laravel-filament/filament#5288]
### Package

filament/filament

### Package Version

v2.16.58

### Laravel Version

v9.4.0

### Livewire Version

v2.10.7

### PHP Version

8.1.13

### Problem description

When using `withCount()` in `getEloquentQuery()` and attempt to replicate a row throws error:
 Column not found: 1054 Unknown column 'comments_count' in 'field list' 

### Expected behavior

Ignore non-fillable

### Steps to reproduce

Go to Products resource and click to Replicate a row. 

### Reproduction repository

https://github.com/howdu/filament-tester/tree/replicate-product-issue

**Comment by danharrin** [comment]
You can use `excludeAttributes()` to exclude those columns, but apart from that, this is a bug with Laravel. Laravel provides the base `replicate()` action that we use.
