### ISSUE TITLE
Table ToggleColumn collide with Alpine Component tooltip

### ISSUE THREAD

**Issue by ekandreas** [laravel-filament/filament#5292]
### Package

filament/tables

### Package Version

2.16.58

### Laravel Version

v9

### Livewire Version

v2

### PHP Version

PHP 8.1

### Problem description

The property "x-tooltip" is set to "error" as default in the Table ToggleColumn blade component. Eg,
```
x-tooltip="error"
```
This causes the the page to show "error" when hovering on any toggle button in the table list.

Note! This is when using Alpine Component tooltip/tippy. Perhaps Filament should use it's own magic?

### Expected behavior

Exist in cooperation with Alpine Component Tooltip.

### Steps to reproduce

1. Clone the repo
2. Migrate
3. Go to startpage /
4. Hover over the toggle button in the table

### Reproduction repository

https://github.com/ekandreas/x-tooltip

**Comment by danharrin** [comment]
Sorry if this wasnt clear in the docs, but you actually need [`@ryangjchandler/alpine-tooltip`](https://github.com/ryangjchandler/alpine-tooltip) for this, not the raw Tippy library and a custom directive. Ryan's package treats `x-tooltip` content as a JS expression, not a string.
