### ISSUE TITLE
Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'wireEl.__livewire')

### ISSUE THREAD

**Issue by mikrosmile** [laravel-filament/filament#5298]
### Package

filament/filament

### Package Version

v.2.16.58

### Laravel Version

v.9.45.0

### Livewire Version

v.2.3

### PHP Version

PHP 8.1.13

### Problem description

There are two errors occurred in Select component

1. Alpine: Cannot reference "$wire" outside a Livewire component.
2. Unhandled Promise Rejection: TypeError: null is not an object (evaluating 'wireEl.__livewire')

If Select is multiple, when choosing an option in the Select dropdown and closing modal the above errors occurred 

https://user-images.githubusercontent.com/2136612/208868832-e934dae9-3ca5-4ac2-9dcf-a64460d800c7.mov

### Expected behavior

No errors

### Steps to reproduce

1. Create a Filament page
2. Add Action
3. Add form to action with Select form with ->multiple() method
4. Open modal & choose any option available & close modal

### Reproduction repository

https://github.com/mikrosmile/filament-bug

**Comment by danharrin** [comment]
This is a bug in Livewire that will be solved in v3 hopefully. It doesn't affect the Filament's functionality at all, right?

**Comment by mikrosmile** [comment]
> This is a bug in Livewire that will be solved in v3 hopefully. It doesn't affect the Filament's functionality at all, right?

Right
