### ISSUE TITLE
SelectColumn options() runs for every line

### ISSUE THREAD

**Issue by MiloudiMohamed** [laravel-filament/filament#5324]
### Package

filament/tables

### Package Version

v2.16.53

### Laravel Version

v9.42.2

### Livewire Version

v2.10.7

### PHP Version

v8.1.6

### Problem description

Assuming we have the following code:
```php
Tables\Columns\SelectColumn::make('blog_category_id')
  ->options(Category::pluck('id', 'name')),
```
This query `Category::pluck('id', 'name')` gets called for each line. 

I've used the filament-demo to replicate the issue (repo link attached below), here are some screenshots:

**Without any change:**

![image](https://user-images.githubusercontent.com/10816975/209230818-e4dc6f66-9eb9-4216-813e-d2ce383807aa.png)

**Using Category::pluck('id', 'name'))**

![image (1)](https://user-images.githubusercontent.com/10816975/209230980-e9604dac-d596-41a3-9c0c-c68b00936c42.png)

**Using fn () => Category::pluck('id', 'name'))**

![image (2)](https://user-images.githubusercontent.com/10816975/209231049-257e19fb-9691-4263-9419-491f09bf9fd0.png)

### Expected behavior

`Category::pluck('id', 'name'))` is expected to run only once

### Steps to reproduce

Just open and run the project demo and see the debug bar queries with/without the added code

### Reproduction repository

https://github.com/MiloudiMohamed/filament-demo

**Comment by danharrin** [comment]
Try this - `->options(fn () => Category::pluck('id', 'name'))`

This has been fixed in v3

**Comment by MiloudiMohamed** [comment]
@danharrin I've tried that. you can see the screenshot, a query for each line. 
Having two or three similar selects would crash the page unfortunately

I wonder if there's a workaround, like saving the query result somewhere else and just referencing the variable?

**Comment by danharrin** [comment]
I'm not sure if there is a fix then, because potentially the options could be different for each row

Try `spatie/once` - https://github.com/spatie/once

**Comment by MiloudiMohamed** [comment]
Yes, `spatie/once` fixed the problem.
I had to create another function to return the result like this
```php
public static function getCategories()
{
  return once(fn () => Category::pluck('name', 'id'));
}
```

Closing this issue, Thanks for your help 🙏

**Comment by itwondersteam** [comment]
@MiloudiMohamed may try using class variable to cache the eloquent as well

**Comment by MiloudiMohamed** [comment]
@itwondersteam what do you mean by **class variable**? can you give an example?
