### ISSUE TITLE
"View [cells.column]" not found.when calling Column::make().

### ISSUE THREAD

**Issue by Imangazaliev** [laravel-filament/filament#537]
**Describe the bug**
I'm trying to show a relationship data [according documentation ](https://filamentadmin.com/docs/tables/#columns-displaying-relationship-data), but I'm getting a error `View [cells.column] not found`.

**To reproduce**
```php
public static function table(Table $table)
{
    return $table
        ->columns([
            Columns\Text::make('name')->primary()->searchable(),
            Columns\Boolean::make('is_published'),
            Columns\Column::make('author.english_name'),
        ])
    ;
}
```

**Expected behavior**
Show a relationship data (author name).

**Context**
- Package version: 1.10.10
- Laravel version: 8.55.0
- Browser: Chrome
- Server OS: 20.04.2
- PHP version: 8.0
- Database: PostgreSQL 12

**Comment by danharrin** [comment]
Please use `Columns\Text` instead of `Columns\Column`.
