### ISSUE TITLE
Form input values not retained after form submission

### ISSUE THREAD

**Issue by mostafa-amine** [laravel-filament/filament#5372]
### Package

filament/forms

### Package Version

v2.0.0

### Laravel Version

v8.0.0

### Livewire Version

v2.10

### PHP Version

8.0.0

### Problem description

I am using the Rewrite component in my Livewire application and I have noticed that the form input values are not being retained after the form is submitted. 

The form resets the input values `null`.

And if a user fills out the form and clicks on the submit button then he wants to change a value from the select input, all the previously selected options return empty.

I am not sure what could be causing this issue, but it is causing problems for me as I need to retain the old values in the form after it is submitted.

https://user-images.githubusercontent.com/90805670/210137696-163ca991-5b3c-4a15-be88-ad5a61d9d397.mp4

### Expected behavior

The form input values should not reinitialize to null.

### Steps to reproduce

1. Go to the page with the Rewrite component.
2. Fill out the form with some values.
3. Submit the form.
4. Observe that the form input values are reset to `null`.

### Reproduction repository

https://github.com/mostafa-amine/form-reset-reproduction

**Comment by danharrin** [comment]
Downloaded your repo, cannot reproduce this

Uploading Screen Recording 2023-01-02 at 22.04.29.mov…
