### ISSUE TITLE
Exception when using a locale dictionary

### ISSUE THREAD

**Issue by tekord** [laravel-filament/filament#538]
**Describe the bug**

Got the following:

```
htmlspecialchars(): Argument #1 ($string) must be of type string, array given (View: G:\xampp\www\my-project\vendor\filament\filament\resources\views\components\nav-link.blade.php)
```

This is definitely related to the way Laravel deals with translations.

**To reproduce**

Create OrderResource class, add 'orders.php' file to the resources/lang. It is important to test it on a non-empty file. The file must return an array containing at least 1 item. Here is my case:

```
<?php

return [
	'statuses' => [
		'new' => '...',
		'shipped' => '...',
	],
];

```

**Expected behavior**

No error

**Context**

- Package version: [1.10.10]
- Livewire version: [2.5.5]
- Laravel version: [8]
- PHP version: [e.g. 8]

**Comment by tekord** [comment]
Resource's label is used as a dictionary name, not a key inside a dictionary. Overriding $label variable is a work-around solution.

**Comment by tekord** [comment]
Also, the $label is forced to display as plural. I think it should not be like that. I've already overridden the label in the form I need. Makes no sense to add 's' at end of it programmatically.

**Comment by danharrin** [comment]
> Resource's label is used as a dictionary name, not a key inside a dictionary. Overriding $label variable to something different from 'Orders' is a work-around solution.

Because of this, I think fixing the issue would be a breaking change. If you want to avoid Filament using the plural label, I think you just need to [set a custom navigation label](https://filamentadmin.com/docs/1.x/admin/navigation)?
