### ISSUE TITLE
Attach table action mounting in test suites

### ISSUE THREAD

**Issue by AndyTWF** [laravel-filament/filament#5384]
### Package

filament/tables

### Package Version

2.16.46+

### Laravel Version

9.46.0

### Livewire Version

N/A

### PHP Version

8.1 & 8.2

### Problem description

Bit of an odd one this one, as it's been working with no problems for a while now.  I'm therefore not sure if something broke in Filament or whether I was doing a test wrong the whole time!

In tests where I'm asserting the performance of an attach action on the relations manager I get the following error:

`Failed asserting that an event [open-modal] was fired with parameters: {"id":"ano6IXliKRN9vCERlBF4-table-action"}`

This assertion code is triggered, from what I can see, in the `mountTableAction` method of TestsActions.php in Filament.

Working it through, the problem seems to have been introduced in Filament 2.16.46 by the change at https://github.com/filamentphp/filament/commit/d04c9526986079e971c8a4c3c887e3e73d431c9e

Specifically, if I remove the checks on lines 159 and 93 of HasActions.php (relating to filled records), the test passes again. It was bailing at this point because `$action->getRecord()` returns null. I've included my test code below, just incase it's me doing something wrong!

### Expected behavior

The modal should be opened as the table action is mounted, and therefore the unit test should continue to pass.

### Steps to reproduce

I have this code in a test:

```PHP
        Livewire::test(
            UserResource\RelationManagers\RolesRelationManager::class,
            ['ownerRecord' => $this->user()]
        )
            ->callTableAction(AttachAction::class, Role::fromKey(RoleKeys::DIVISION_STAFF_GROUP), ['recordId' => Role::fromKey(RoleKeys::DIVISION_STAFF_GROUP)])
            ->assertHasNoTableActionErrors();
```

This code should take the DSG role and attach it (relation is many-to-many) to the user. 

### Reproduction repository

https://github.com/VATSIM-UK/uk-controller-api/pull/1172

**Comment by danharrin** [comment]
It's because you're passing in the `Role::fromKey(RoleKeys::DIVISION_STAFF_GROUP)` as the second argument. No need to use that in this case, that's only for actions on table rows.

`->callTableAction(AttachAction::class, data: ['recordId' => Role::fromKey(RoleKeys::DIVISION_STAFF_GROUP)])`

Let me know if that doesn't fix!
