### ISSUE TITLE
Ternary filter default value select dropdown no default selected

### ISSUE THREAD

**Issue by vdeville** [laravel-filament/filament#5388]
### Package

filament/tables

### Package Version

v2.16.59

### Laravel Version

v9.45.1

### Livewire Version

v2.10.8

### PHP Version

8.2

### Problem description

Hello,
I use ternary filter with default value, all is working like a charm, the indicator work and indicate the good default filter but when you open the filter dorpdown, the select has not the good option selected.

Default value to false

### Expected behavior

Select with the good selected option

### Steps to reproduce

Create ternary filter, set ->default(false), and open the filter dropdown

### Reproduction repository

https://gist.github.com/vdeville/5863d93bd16ec307ad0d30f1a4723085

**Comment by danharrin** [comment]
Try `->default(0)`

**Comment by vdeville** [comment]
Hello @danharrin ,
Thanks is work !
Merci
