### ISSUE TITLE
CheckboxColumn not working

### ISSUE THREAD

**Issue by ThijmenKort** [laravel-filament/filament#5389]
### Package

filament/filament

### Package Version

v2.16.59

### Laravel Version

v9.46.0

### Livewire Version

v2

### PHP Version

PHP8.1

### Problem description

Checkbox Columns are not working anymore after update to .59. In the database a boolean is true but the checkbox does nothing.

### Expected behavior

Checkbox will be checked when true in database

### Steps to reproduce

Connect database
Migrate the database
Seed the database
Log in with:
email: admin@admin.nl
password: admin123

Check the resource to see checkbox not checked

### Reproduction repository

https://github.com/ThijmenKort/Checkbox

**Comment by ArtMin96** [comment]
I think the problem is that you disabled it

```php
CheckboxColumn::make('open')
    ->label('Open')
    ->disabled() // <- Remove this
```

**Comment by ThijmenKort** [comment]
> I think the problem is that you disabled it
> 
> ```
> CheckboxColumn::make('open')
>     ->label('Open')
>     ->disabled() // <- Remove this
> ```

No, disabled has nothing to do with this. This issue is about it not working anymore after updating and i created this repo for the mantainers to check.

But thankyou for trying to sort it out.

**Comment by danharrin** [comment]
It's because you don't have a `boolean` cast on that column in the database. Which is why I couldn't reproduce the issue.

I will add a check manually into Filament, but ultimately this is user error.

**Comment by ThijmenKort** [comment]
> It's because you don't have a `boolean` cast on that column in the database. Which is why I couldn't reproduce the issue.
> 
> I will add a check manually into Filament, but ultimately this is user error.

So why was it working before and not anymore?

**Comment by danharrin** [comment]
Because we switched from Livewire to Alpine handling this. Regardless, the cast should be there.
