### ISSUE TITLE
window.livewire returns "Component" instead of "Livewire" since v2.16.42

### ISSUE THREAD

**Issue by SebastianSchoeps** [laravel-filament/filament#5391]
### Package

filament/filament

### Package Version

v2.16.42

### Laravel Version

v9.46.0

### Livewire Version

v2.10.8

### PHP Version

PHP 8.2.0

### Problem description

`@this` does not work anymore.

I dug into this and it seems that it's not working anymore since v2.16.42 (which I find pretty strange that it is just realized now?! Maybe I am totally wrong...).

The reason is that `window.livewire` returns the `Component` and not `Livewire` (just use the browser console to check). This different behavior was introduced in https://github.com/filamentphp/filament/compare/v2.16.41...v2.16.42. If I use a version >= 2.16.42, it works if I manually remove 

```
x-init="this.livewire = $wire.__instance"
```

from the files

- packages/admin/resources/views/components/page.blade.php
- packages/forms/resources/views/components/actions/modal/index.blade.php
- packages/tables/resources/views/index.blade.php (2x)

Maybe this is also related to the error reported at the end of https://github.com/filamentphp/filament/pull/4880.

I could recreate this on a brand new project without any other changes - just use `window.livewire` at the console.

### Expected behavior

`window.livewire` return `Livewire` and not `Component`

### Steps to reproduce

- create a new Laravel project
- install Filament and an user
- use `window.livewire` at the developer console (result: `Component`)
- remove the lines mentioned above from the three files
- use `window.livewire` at the developer console (result: `Livewire`)

### Reproduction repository

https://github.com/i-guess-its-easier-to-create-this-issue-from-scratch/but-i-will-provide-a-repository-if-you-need-it

**Comment by eorenstein1** [comment]
I'm having this same issue after upgrading my app's filament version from 2.16.26 to 2.16.53. Thank you for pinpointing the exact version and issue.

**Comment by danharrin** [comment]
Should be fixed by #5448
