### ISSUE TITLE
Multiple forms in separate tabs

### ISSUE THREAD

**Issue by Zain541** [laravel-filament/filament#5402]
### Package

filament/forms

### Package Version

v2.x

### Laravel Version

v9.x

### Livewire Version

v2.10.8

### PHP Version

PHP 8.x

### Problem description

I have been trying to add multiple forms in multiple tabs separately. Previously I have successfully implemented the tab for a single form. The documentation doesn't seem very much clear about adding multiple forms to the multiple tabs

### Expected behavior

Multiple forms should be created in separate tabs

### Steps to reproduce

    
    protected function getFormSchema(): array
    {

        return [
            Tabs::make('Heading')
                ->tabs([
                    Tabs\Tab::make('Label 1')
                        ->schema([
                            $this->getTravelDocumentationSchema()
                        ]),
                    Tabs\Tab::make('Label 2')
                        ->schema([
                            $this->getContactSchema()
                        ]),
                ])
        ];
    }

Form Functions

    protected function getTravelDocumentationSchema()
    {

        return [
            Forms\Components\TextInput::make('title')->required(),
            Forms\Components\MarkdownEditor::make('content'),
        ];
        
    }

    protected function getContactSchema()
    {
    

        return [
            Forms\Components\TextInput::make('title')->required(),
            Forms\Components\MarkdownEditor::make('content'),
        ];
    }
Overriding the getForm function

    protected function getForms(): array
    {
        return [
            'travelDocumentationForm' => $this->makeForm()
                ->schema($this->getTravelDocumentationSchema())
                ->model(TravelDocumentation::class),
            'contactForm' => $this->makeForm()
                ->schema($this->getContactSchema())
                ->model(Contact::class)

        ];
    }
Livewire blade file
      
      <x-wire-elements-pro::tailwind.slide-over on-submit="save" :content-padding="false">
      <x-slot name="title">{{ __('Travel Details') }}</x-slot>

      
      <form wire:submit.prevent="submit">
        {{ $this->travelDocumentationForm }}
        <div class="d-flex mt-3 justify-content-end">
          <button type="submit" style="text-align:right" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
            {{ __('Submit') }}
          </button>
        </div>

      </form>

        <form wire:submit.prevent="submit">
        {{ $this->contactForm }}
        <div class="d-flex mt-3 justify-content-end">
          <button type="submit" style="text-align:right" class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded">
            {{ __('Submit') }}
          </button>
        </div>

      </form>
    </x-wire-elements-pro::tailwind.slide-over>

### Reproduction repository

https://github.com/Zain541/filamentTabsIssue

**Comment by zepfietje** [comment]
Hey @Zain541, thanks for creating a bug report.
Unfortunately, it's unclear to me what exactly is the issue with Filament here.

You might be confusing multiple forms with a single form including a tab component.
If your goal is to create tabs and have each tab contain its own separate form with submit button, your best bet is to [create two forms as per the docs](https://filamentphp.com/docs/2.x/forms/getting-started#using-multiple-forms) and create a custom tabs component which switches between showing any of the two forms.

Let us know if there's anything we're missing here.
If you could include more specifics and extra info, we're able to help you better. 😊

**Comment by Zain541** [comment]
Hi @zepfietje, thank you so much for replying to me. Yes, this is exactly what I want. Could you please guide me on how can we inject forms in the tab component and how the blade file would work in this case? Is there any docs available?

**Comment by danharrin** [comment]
You just add the Tabs to 1 form. Then each tab has form components inside of it. Then you can fetch the data for all tabs at once when you call `$this->form->getState()`

**Comment by Zain541** [comment]
> You just add the Tabs to 1 form. Then each tab has form components inside of it. Then you can fetch the data for all tabs at once when you call `$this->form->getState()`

Do you mean putting livewire form components inside the tabs? Could you please guide me on how to do that?

**Comment by danharrin** [comment]
No. Tabs contain form components

```php
Tabs::make('Heading')
    ->tabs([
        Tabs\Tab::make('Label 1')
            ->schema([
                TextInput::make('name')
            ]),
        Tabs\Tab::make('Label 2')
            ->schema([
                TextInput::make('email')
            ]),
        Tabs\Tab::make('Label 3')
            ->schema([
                TextInput::make('password')
            ]),
    ])
```

**Comment by Zain541** [comment]
My problem is I want separate forms with submit buttons in each of the tabs.

    Tabs::make('Heading')
    ->tabs([
        Tabs\Tab::make('Label 1')
            ->schema([
                //form 1
               // form 1 submit button
            ]),
        Tabs\Tab::make('Label 2')
            ->schema([
                //form 2
               // form 2 submit button
            ]),
        Tabs\Tab::make('Label 3')
            ->schema([
                //form 3
               // form 3 submit button
            ]),
    ])

**Comment by danharrin** [comment]
Dont use the Filament tabs then, create 3 separate forms and put them inside your own tabs.

**Comment by Zain541** [comment]
Ok perfect. Thanks for your help :)

**Comment by thaolaptrinh** [comment]
> Ok perfect. Thanks for your help :)

Please give your solution to me.

**Comment by DevianandaYunitasari** [comment]
can you help me pleasee

**Comment by thaolaptrinh** [comment]
> can you help me pleasee

What do you need?

**Comment by abdosaeedelhassan** [comment]
> Ok perfect. Thanks for your help :)

Please tell me how you do it

**Comment by rvzug** [comment]
I think you all want something like this:

Edit record page:
![image](https://github.com/user-attachments/assets/7a6f17a5-2921-4d9e-8326-70fd99a55c70)
(normal Edit page)

![image](https://github.com/user-attachments/assets/20b8e77a-7306-46bb-9641-8b30acc1bb33)
(other tab/edit page with form in it)

![image](https://github.com/user-attachments/assets/ad02b464-8760-48e1-b7c9-9d89af8af176)
(other tab/edit page with relation)

This aren't tabs, but separate editpages. It makes use of the [Creating another Edit page](https://filamentphp.com/docs/3.x/panels/resources/editing-records#creating-another-edit-page)
and [Resource sub-navigation](https://filamentphp.com/docs/3.x/panels/resources/getting-started#resource-sub-navigation) docs.

Basicly you create multiple Edit pages, register them in the ```FooResource::getPages()``` like:
```php
    public static function getPages(): array
    {
        return [
            'index' => Pages\ListProjects::route('/'),
            'create' => Pages\CreateProject::route('/create'),
            'edit' => Pages\EditProject::route('/{record}/edit'),
            'edit_prognosis' => Pages\EditProjectPrognosis::route('/{record}/edit_prognosis'),
            'edit_disposal_plan' => Pages\EditProjectDisposalPlan::route('/{record}/edit_disposal_plan'),
            'edit_final_report' => Pages\EditProjectFinalReport::route('/{record}/edit_final_report'),
            'edit_users' => Pages\EditProjectUsers::route('/{record}/edit_users'),
            'manage_disposals' => Pages\ManageProjectDisposals::route('/{record}/manage_disposals'),
        ];
    }
```

And than register the method ```FooResource::getRecordSubNavigation()``` like:
```php
    public static function getRecordSubNavigation(Page $page): array
    {   
        return $page->generateNavigationItems([
            Pages\EditProject::class,
            Pages\EditProjectPrognosis::class,
            Pages\EditProjectDisposalPlan::class,
            Pages\EditProjectFinalReport::class,
            Pages\ManageProjectDisposals::class,
            Pages\EditProjectUsers::class,
        ]);
    }
```

Finally, add 
```php
protected static SubNavigationPosition $subNavigationPosition = SubNavigationPosition::Top;
```
to your FooResource, to add the links/'tabs' on top of the Form.

The docs also says: 
> If you're looking to add sub-navigation to switch between entire resources and [custom pages](https://filamentphp.com/docs/3.x/panels/pages), you might be looking for [clusters](https://filamentphp.com/docs/3.x/panels/clusters), which are used to group these together. The getRecordSubNavigation() method is intended to construct a navigation between pages that relate to a particular record inside a resource.

**Comment by abdosaeedelhassan** [comment]
> I think you all want something like this:
> 
> Edit record page: ![image](https://private-user-images.githubusercontent.com/7152234/356603591-7a6f17a5-2921-4d9e-8326-70fd99a55c70.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNDcxNTksIm5iZiI6MTcyMzI0Njg1OSwicGF0aCI6Ii83MTUyMjM0LzM1NjYwMzU5MS03YTZmMTdhNS0yOTIxLTRkOWUtODMyNi03MGZkOTlhNTVjNzAucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDlUMjM0MDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9MTEyMWFkZGFhNGJlMjQxNjQ0NTU5MjJiNGY1OWQ3N2I4YjZjMzBmYzRmOGI4MDNhZmYyODdkZWI2NzE1NDcwZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.aGFdxTpYLTcbzF2U1qSNNDKw3RbBuloLxB31HEDuwkI) (normal Edit page)
> 
> ![image](https://private-user-images.githubusercontent.com/7152234/356604045-20b8e77a-7306-46bb-9641-8b30acc1bb33.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNDcxNTksIm5iZiI6MTcyMzI0Njg1OSwicGF0aCI6Ii83MTUyMjM0LzM1NjYwNDA0NS0yMGI4ZTc3YS03MzA2LTQ2YmItOTY0MS04YjMwYWNjMWJiMzMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDlUMjM0MDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGQ3NGJjYjQ0ZTM1NzgwMzIzNzM4MTllNWEwOGM2MzViOWRlMWFjZjE5NWY1M2I0YmVkNGUyZTc2ODBlNWJkMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.QcxtxKmTIfsLct2r-4sUYuVULG67suKUhFFFd6CyDuo) (other tab/edit page with form in it)
> 
> ![image](https://private-user-images.githubusercontent.com/7152234/356604342-ad02b464-8760-48e1-b7c9-9d89af8af176.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMyNDcxNTksIm5iZiI6MTcyMzI0Njg1OSwicGF0aCI6Ii83MTUyMjM0LzM1NjYwNDM0Mi1hZDAyYjQ2NC04NzYwLTQ4ZTEtYjdjOS05ZDg5YWY4YWYxNzYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgwOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MDlUMjM0MDU5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDdiMzU2NzRhZGQ4NGZjOTQ5ZjJiMzM2OTc2NzZlOWM3ZjZlOWM4NmY0ZmU4ODU2ZmI3MThiYTEwNTE5YWZiZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._Dq0BGmfGGmWI6btjqIsy2DczCBFQ3So9A33SgAqp-M) (other tab/edit page with relation)
> 
> This aren't tabs, but separate editpages. It makes use of the [Creating another Edit page](https://filamentphp.com/docs/3.x/panels/resources/editing-records#creating-another-edit-page) and [Resource sub-navigation](https://filamentphp.com/docs/3.x/panels/resources/getting-started#resource-sub-navigation) docs.
> 
> Basicly you create multiple Edit pages, register them in the `FooResource::getPages()` like:
> 
> ```
>     public static function getPages(): array
>     {
>         return [
>             'index' => Pages\ListProjects::route('/'),
>             'create' => Pages\CreateProject::route('/create'),
>             'edit' => Pages\EditProject::route('/{record}/edit'),
>             'edit_prognosis' => Pages\EditProjectPrognosis::route('/{record}/edit_prognosis'),
>             'edit_disposal_plan' => Pages\EditProjectDisposalPlan::route('/{record}/edit_disposal_plan'),
>             'edit_final_report' => Pages\EditProjectFinalReport::route('/{record}/edit_final_report'),
>             'edit_users' => Pages\EditProjectUsers::route('/{record}/edit_users'),
>             'manage_disposals' => Pages\ManageProjectDisposals::route('/{record}/manage_disposals'),
>         ];
>     }
> ```
> 
> And than register the method `FooResource::getRecordSubNavigation()` like:
> 
> ```
>     public static function getRecordSubNavigation(Page $page): array
>     {   
>         return $page->generateNavigationItems([
>             Pages\EditProject::class,
>             Pages\EditProjectPrognosis::class,
>             Pages\EditProjectDisposalPlan::class,
>             Pages\EditProjectFinalReport::class,
>             Pages\ManageProjectDisposals::class,
>             Pages\EditProjectUsers::class,
>         ]);
>     }
> ```
> 
> Finally, add
> 
> ```
> protected static SubNavigationPosition $subNavigationPosition = SubNavigationPosition::Top;
> ```
> 
> to your FooResource, to add the links/'tabs' on top of the Form.
> 
> The docs also says:
> 
> > If you're looking to add sub-navigation to switch between entire resources and [custom pages](https://filamentphp.com/docs/3.x/panels/pages), you might be looking for [clusters](https://filamentphp.com/docs/3.x/panels/clusters), which are used to group these together. The getRecordSubNavigation() method is intended to construct a navigation between pages that relate to a particular record inside a resource.

Thank you to let me known about clusters
