### ISSUE TITLE
Model Relation Manager won't update after the model get updated

### ISSUE THREAD

**Issue by ousid** [laravel-filament/filament#5434]
### Package

filament/filament

### Package Version

^2.0

### Laravel Version

^9.19

### Livewire Version

^2.10

### PHP Version

PHP 8.0.14

### Problem description

After updating an existing model records, who has a `ModelRelationManager` associated with it (In my case the relationship is `BelongsToMany`) You will notice that the model relationship table won't update, unless you refreshed the Database.

### Expected behavior

It would be nice, if there's a `hook` behavior, or an `emit` event to update the `RelationManager` after updating the model instance, with their relation records.

### Steps to reproduce

In this example, I'm using a `Category` model, with the `Type` model as an association instance.

- Create New Category Record
- Update the Category Type Values
- Hit Update
- No changes on the `TypesRelationManager` Table.

### Reproduction repository

https://github.com/ousid/filament-issues/tree/model-relation-issue

**Comment by hdaklue** [comment]
I have the same issue. Keep saying 'waiting file size'

**Comment by rajentrivedi** [comment]
I am also getting same behaviour, it would be nice if relationship manager get updated.

**Comment by danharrin** [comment]
Hey, I don't think this is a bug in Filament, it's just not a feature. I don't think it's expected behaviour to always refresh the relation manager whether or not something has changed in the form, that might not always be desired.

You can always emit a LW event from the `afterSave()` hook of the page and create a `$listeners` on the relation manager to refresh it?

**Comment by danharrin** [comment]
> I have the same issue. Keep saying 'waiting file size'

@hdaklue https://filamentphp.com/tricks/file-upload-previews-not-loading

**Comment by ousid** [comment]
@danharrin 

Agreed, technically, it's not a bug, but maybe a "nice to have" feature. Don't you think?

I'm happy to submit a PR, if you see it fit, as an included feature in filament.

**Comment by danharrin** [comment]
I certainly wouldnt want it as default behaviour, and I feel like the Livewire listener approach requires such little code that its probably not worth it?
