### ISSUE TITLE
Fileupload Component of Filament/Forms cannot be filled with images when using for editing purpose.

### ISSUE THREAD

**Issue by RizwanNaasir** [laravel-filament/filament#5441]
### Package

filament/forms

### Package Version

v2.16

### Laravel Version

v9.46

### Livewire Version

v2.10.8

### PHP Version

PHP 8.1

### Problem description

[This](https://github.com/RizwanNaasir/filament-form-issue) Repo contains minimal reproduction of issue in Filament/Forms when using outside of admin panel.

Fileupload Component of Filament/Forms cannot be filled with images when using for editing purpose.

[Discord Discussion ](https://discord.com/channels/883083792112300104/883085278993068082/1058402284381413387)

### Expected behavior

Image Should be filled when provided with

```php
       $this->form->fill([
                'name' => Storage::url($imageModal->name),
                //Which returns => '/storage/lhzqVslif5W4rivcnSnOr4RCeJFwLo0b0kNp8Z3r.jpg'
      ]);
```

### Steps to reproduce

-  Fresh Install Laravel
-  composer require filament/forms
-  php artisan forms:install
-  npm install && npm run dev

- Simple New Model just to store Image Name

```php
Schema::create('images', function (Blueprint $table) {
            $table->id();

            $table->string('name');

            $table->timestamps();
        });
```
- make new Livewire Component make form.
- [Prepared Livewire Component](https://filamentphp.com/docs/2.x/forms/getting-started#preparing-your-livewire-component)
- made Fileupload in `getFormSchema()`
```php
protected function getFormSchema(): array
    {
        return [
            FileUpload::make('name')->required()
        ];
    }
```
- Now get image from first element in array and store it in public folder 
- Now Fill the form with 'mount()'
```php
public function mount(): void
    {
        $image = Image::query()->first();
        if(isset($image)){
            $this->form->fill([
                'name' => Storage::url($image->name),
                //Which returns => '/storage/lhzqVslif5W4rivcnSnOr4RCeJFwLo0b0kNp8Z3r.jpg'
            ]);
        }
    }
```
- But No file is not being filled.

### Reproduction repository

https://github.com/RizwanNaasir/filament-form-issue

**Comment by danharrin** [comment]
You just need the file name when filling a file in edit mode. Nothing special like the URL. Exactly what gets returned when you save the form in the first place - same as every other Filament field. Just `lhzqVslif5W4rivcnSnOr4RCeJFwLo0b0kNp8Z3r.jpg`, for example. Make sure the `disk()` and `directory()` are set correctly if you have those.

cc @larsasolidor @nickspringham @magarrent @rizwannaasir
