### ISSUE TITLE
Cannot associate records in a relation manager when the name of the primary key column is different to the parent table

### ISSUE THREAD

**Issue by realslimsutton** [laravel-filament/filament#5459]
### Package

filament/filament

### Package Version

v2.16.61

### Laravel Version

v9.47.0

### PHP Version

PHP 8.2.0

### Problem description

When clicking a record in the select form of the `AssociateAction` action in a relation manager, no record is selected.

### Expected behavior

When choosing a record to associate, the record that was clicked on should be selected in the form.

### Steps to reproduce

1. Clone repo
2. Migrate everything
3. Create your first user (to login with)
4. Create a second user
5. Use CharacterFactory to create some characters
6. Go to /admin/users/2/edit and attempt to associate a character to the user

### Reproduction repository

https://github.com/realslimsutton/filament-relations

**Comment by realslimsutton** [comment]
I have proposed a potential solution here #5460

**Comment by danharrin** [comment]
Fixed by #5460
