### ISSUE TITLE
Side menu collapsing issue 

### ISSUE THREAD

**Issue by CovertError** [laravel-filament/filament#5479]
### Package

filament/filament

### Package Version

v2.16.60

### Laravel Version

v9.46.0

### PHP Version

PHP 8.1

### Problem description

Navigation groups dont collapse

<img width="385" alt="image" src="https://user-images.githubusercontent.com/34497804/212557360-dc218bdb-2a49-45d6-a9eb-26b0612fc33b.png">

### Expected behavior

to be collapsed

### Steps to reproduce

   
adding this to the specific resources page 

 protected static ?string $navigationGroup = 'client';

then modifying the FilamentServiceProvider
```
<?php

namespace App\Providers;

use Filament\Facades\Filament;
use Filament\Navigation\NavigationGroup;
use Filament\Navigation\NavigationItem;
use Illuminate\Support\ServiceProvider;

class FilamentServiceProvider extends ServiceProvider
{
    /**
     * Register any application services.
     *
     * @return void
     */
    public function register()
    {
        //
    }

    /**
     * Bootstrap any application services.
     *
     * @return void
     */
    public function boot()
    {
        Filament::serving(function () {
            Filament::registerNavigationGroups([
                NavigationGroup::make()
                    ->label('client')
                    ->collapsed(),
            ]);
        });
    }
}

```

### Reproduction repository

https://github.com/CovertError/fillamentGroupIssue

**Comment by CovertError** [comment]
just to make it clear you can collapse it but by default its not collapsed

**Comment by CovertError** [comment]
looks like somehow its fixed thanks filament team

**Comment by mohssinekun** [comment]
> looks like somehow its fixed thanks filament team

Still not working :/

**Comment by danharrin** [comment]
Because your view cache or browser local storage is not clear

**Comment by programozas** [comment]
This is what I use and I love it: https://filamentphp.com/plugins/clear-cache

**Comment by bilogic** [comment]
The behavior is, if you expand that group, its expanded state is cached by the browser. It stays expanded after even after reloading the page. I think this is what makes it confusing as most people will not expect a behavior like this to be "remembered".

I would suggest having 1 more method
1. `->cacheCollapseState()` remembers the collapse state, with the default as collapsed
2. `->cacheCollapseState(false)` remembers the collapse state, with the default as expanded (Default if none of these methods are called)
3. `->collapsed()` will not remember anything, and always collapse
4. `->collapsed(false)` will not remember anything, and always expanded
