### ISSUE TITLE
Filament is not autodiscovered

### ISSUE THREAD

**Issue by coding-sunshine** [laravel-filament/filament#5504]
### Package

filament/filament

### Package Version

v2.x

### Laravel Version

v9.45

### Livewire Version

v2.x

### PHP Version

PHP 8.2

### Problem description

I am trying to Install filament on the existing project and adequately following the installation steps. 

``composer require filament/filament:"^2.0"``
 works fine and the filament is in vendor directory.
But it is not autodiscovered so none of the filament commands are registered and even the /admin routes doesn't work.

### Expected behavior

composer require filament/filament:"^2.0"
works fine and the filament is in vendor directory.
Auto-discovery should work so the filament commands should be registered and even the /admin routes should work.

### Steps to reproduce

composer require filament/filament:"^2.0"
works fine and the filament is in vendor directory.
Auto-discovery should work so the filament commands should be registered and even the /admin routes should work.

### Reproduction repository

https://github.com/coding-sunshine/lineone

**Comment by danharrin** [comment]
Please provide a public reproduction repo, otherwise we can't help you. You can reopen this issue once it has been provided.

**Comment by coding-sunshine** [comment]
@danharrin I couldn't reopen issue as it was closed by repo admins, So had to create a new one, it is having public repo link. 
https://github.com/filamentphp/filament/issues/5505
