### ISSUE TITLE
Filament is not autodiscovered

### ISSUE THREAD

**Issue by coding-sunshine** [laravel-filament/filament#5505]
### Package

filament/filament

### Package Version

v2.x

### Laravel Version

v9.45

### Livewire Version

v2.x

### PHP Version

PHP 8.2

### Problem description

I am trying to Install filament on the existing project and adequately following the installation steps.

``composer require filament/filament:"^2.0"``
works fine and the filament is in vendor directory.
But it is not autodiscovered so none of the filament commands are registered and even the /admin routes doesn't work.

### Expected behavior

composer require filament/filament:"^2.0"
works fine and the filament is in vendor directory.
Auto-discovery should work so the filament commands should be registered and even the /admin routes should work.

### Steps to reproduce

composer require filament/filament:"^2.0"
works fine and the filament is in vendor directory.
Auto-discovery should work so the filament commands should be registered and even the /admin routes should work.

### Reproduction repository

https://github.com/coding-sunshine/lineone

**Comment by coding-sunshine** [comment]
<img width="1312" alt="Screenshot 2023-01-21 at 12 57 23 AM" src="https://user-images.githubusercontent.com/3206025/213714546-85c8f2b4-5c46-4bc8-86e3-6ddefaa7d479.png">
<img width="673" alt="Screenshot 2023-01-21 at 12 57 53 AM" src="https://user-images.githubusercontent.com/3206025/213714605-ec48c227-cc94-4d32-8edf-688d11f51a32.png">
<img width="588" alt="Screenshot 2023-01-21 at 12 58 07 AM" src="https://user-images.githubusercontent.com/3206025/213714623-07f10030-7153-435c-8c94-b0fc19afb30a.png">

**Comment by danharrin** [comment]
Filament isn't even in composer.json, so it didn't get installed

**Comment by coding-sunshine** [comment]
@danharrin sorry for any confusion if my language is easily not understood, as I described in the process.
The following happens when I follow the below process on the above repository:

I run following command:

``composer require filament/filament:"^2.0"``

after that I run following :

``php artisan vendor:publish --tag=filament-config``

But it gives me error as mentioned in above screenshot.

The whole process I am following is visible in above screenshot.

**Comment by danharrin** [comment]
Try `composer require filament/filament` without the version. Your composer is trying to install a non-existent version of Filament, and nothing gets installed.

**Comment by coding-sunshine** [comment]
@danharrin when i do without any version, it's not working as it's conflicting with blade-ui-kit Heroicons

 - filament/forms[v2.16.0, ..., 2.x-dev] require blade-ui-kit/blade-heroicons ^1.2 -> found blade-ui-kit/blade-heroicons[1.2.0, 1.2.1, 1.3.0, 1.3.1] but it conflicts with your root composer.json require (^2.0).

My current version of blade-ui-kit/blade-heroicons is 2.x

**Comment by danharrin** [comment]
We only support 1.x so that needs downgrading

**Comment by danharrin** [comment]
2.x is supported in upcoming Filament v3

**Comment by coding-sunshine** [comment]
Ah ok. Thanks for the help.

**Comment by Waleedviews** [comment]
i have the same issue, any help please? @danharrin

**Comment by danharrin** [comment]
Send your composer.json
