### ISSUE TITLE
Database notifications slide-over covered by scroll bar on Windows Firefox

### ISSUE THREAD

**Issue by MarJose123** [laravel-filament/filament#5518]
### Package

filament/filament

### Package Version

v2

### Laravel Version

v9

### Livewire Version

v2

### PHP Version

PHP 8.1

### Problem description

The modal close button is on the edge of the monitor and it hard to see and click.

Please see the screenshot

![image](https://user-images.githubusercontent.com/18107626/213993821-b1ff5807-e9e5-4abf-b828-502884028f04.png)

### Expected behavior

It should not on the edge and it should be visible and easy to see.

### Steps to reproduce

1. enable the `Database Notification` in filament notification

### Reproduction repository

https://github.com/MarJose123/FilamentPHP-ViewPage-Error

**Comment by zepfietje** [comment]
@MarJose123, could you share which OS, browser and versions you're using?

**Comment by MarJose123** [comment]
> @MarJose123, could you share which OS, browser and versions you're using?

I'm using Windows 10, Firefox latest version (109.0 (64-bit))

**Comment by zepfietje** [comment]
Thanks, @MarJose123!
Does this issue also show for you on https://demo.filamentphp.com?

**Comment by MarJose123** [comment]
Yeah, the same issue.

![image](https://user-images.githubusercontent.com/18107626/214010717-29bf0aff-3fbe-499e-a9e4-ae573088f620.png)

**Comment by zepfietje** [comment]
Since I'm not on Windows, could you check if this also occurs on Chromium-based browsers?

**Comment by MarJose123** [comment]
I tried it on different browser like Opera browser, the issue occurs only on firefox not sure on Mac and Linux

**Comment by MarJose123** [comment]
> Since I'm not on Windows, could you check if this also occurs on Chromium-based browsers?

No, it only occurs on Firefox, have you tried it on firefox for Mac?

**Comment by zepfietje** [comment]
On macOS it doesn't show a persistent scrollbar so there the issue doesn't exist.

**Comment by zepfietje** [comment]
@MarJose123 have you been able to test a potential fix on your device?

**Comment by MarJose123** [comment]
> @MarJose123 have you been able to test a potential fix on your device?

Not yet, I'm still debugging, it might be a `overflow` that cause not sure.

**Comment by ArtMin96** [comment]
Everything is fine with Linux and firefox
![user-menu](https://user-images.githubusercontent.com/29732308/214843717-8d84b6eb-5469-4ed5-a5e6-6840d8d0f86d.png)

![user-menu](https://user-images.githubusercontent.com/29732308/214842760-00e814e3-e082-4e0c-a7a4-5ddee612a37c.png)

**Comment by danharrin** [comment]
Since we don't have a way to test this on Windows, @MarJose123 or someone else will need to submit a fix for this. Thanks for the issue!
