### ISSUE TITLE
RelationManager\ListRecords::getQuery() cannot be called statically

### ISSUE THREAD

**Issue by mikerockett** [laravel-filament/filament#552]
**Describe the bug**

I'm trying to use `reorderOn` on a relation manager table so I can reorder a HasMany relation. When dragging a row in the relation manager table, the following exception is thrown:

> Non-static method Filament\Resources\RelationManager\ListRecords::getQuery() cannot be called statically

This is thrown from packages/tables/src/Table.php:244.

**To reproduce**
1. Create a model with a has many relation - an order column should be present on the relation table
2. Create a resource for that model and a relation manager for the has many relation
3. Call `reorderOn` in the table definition on the relation manager
4. Create a few records
5. Drag one of them

**Expected behavior**

The relation should be re-ordered.

**Context**
- Package version: v1.10.11
- Laravel version: 8.57

**Additional details**

I'm guessing that re-ordering relations is not yet supported. Re-ordering anything doesn't seem to be documented either.

**Comment by danharrin** [comment]
Apologies, due to the way we handle relation managers this is a technical limitation - hence why relations cannot be reordered at this time. I'll make sure to add it to the list for v2. #408

**Comment by mikerockett** [comment]
Thanks Dan, much appreciated :)
