### ISSUE TITLE
Latest Livewire v2.11.1 breaks Spatie MediaLibrary

### ISSUE THREAD

**Issue by AlexisSerneels** [laravel-filament/filament#5568]
### Package

filament/filament

### Package Version

2.16.66

### Laravel Version

9.48

### Livewire Version

2.11.1

### PHP Version

8.1

### Problem description

A new Livewire version has just been released: https://github.com/livewire/livewire/releases

Since then, the `SpatieMediaLibraryFileUpload`field returns:
```
Call to undefined method Spatie\MediaLibrary\MediaCollections\Models\Media::getOriginalUrlAttribute()
```

Downgrading to `"livewire/livewire": "2.11.0"`fixes the issue, so latest version is the cause;

### Expected behavior

N/A

### Steps to reproduce

1. Install FIlament Media Library, add the Fields
2. Upgrade Livewire to version 2.11.1.
3. See yourself

### Reproduction repository

https://github.com/livewire/livewire

**Comment by AlexisSerneels** [comment]
Although I understand why you would close some reports automatically, this is a wrong systematic behavior for legitimate bug reports. Anyway.

**Comment by danharrin** [comment]
Thanks for the issue. Surely it should be an issue with Livewire though, since it's a breaking change in a patch release?

> Although I understand why you would close some reports automatically, this is a wrong systematic behavior for legitimate bug reports. Anyway.

I understand it's frustrating, but any time you spend not replicating the issue, we have to do it instead, for you. Is that fairer? It saves us time when we're servicing thousands of users.

**Comment by AlexisSerneels** [comment]
For the record, issues start to raise on Livewire side : https://github.com/livewire/livewire/discussions/5535

Seems things are broken there and no adaptations would be needed to be performed in Filament.

Anyway, this issue might help others knowing what’s happening.

**Comment by joshhanley** [comment]
@AlexisSerneels and @danharrin yep definitely on the Livewire End. The author of that linked discussion has submitted a PR to fix it, so I will have a look at it tomorrow.

**Comment by danharrin** [comment]
Thanks @joshhanley!

**Comment by ariaieboy** [comment]
Thanks for the issue, I've spent 1 hour to find out why my tests are not passing and after I found out the exception was coming from the livewire side and I downgraded livewire I found out its a bug and after some searching, I came across this issue

**Comment by joshhanley** [comment]
We've decided to revert the Livewire PR that caused this issue and have tagged a new release of Livewire v2.11.2. See my comment on PR https://github.com/livewire/livewire/pull/5536#issuecomment-1407813069 for more details on why it was reverted.

cc: @danharrin @AlexisSerneels @ariaieboy

**Comment by danharrin** [comment]
thanks @joshhanley!

**Comment by joshhanley** [comment]
No worries! 🙂
