### ISSUE TITLE
Zoomed-out when using RTL 

### ISSUE THREAD

**Issue by Zacktamondo** [laravel-filament/filament#5626]
### Package

filament/filament

### Package Version

v2.0.0

### Laravel Version

v9.19

### Livewire Version

v2.11

### PHP Version

PHP 8.2.1

### Problem description

When using a RTL language like Arabic the everything appears smaller.
### Arabic
![image](https://user-images.githubusercontent.com/7546287/217302440-866f9101-8cc7-4453-bd7a-6fd9d24608ec.png)
### English
![image](https://user-images.githubusercontent.com/7546287/217302563-bf46e06f-5ff1-4492-a326-8c011a9c7c6f.png)

The Admin panel in Arabic needs to be zoomed in to 133% to look like the Admin panel in English.

### Expected behavior

It should look like the English version.

### Steps to reproduce

Change the locale in the app.php config file to ar instead of en.

### Reproduction repository

https://github.com/Zacktamondo/filamentIssue

**Comment by danharrin** [comment]
We don't officially support the RTL version, as none of the core team has RTL experience. It has been built by the community. Feel free to PR to fix this but I'd have no clue where to start 👍
