### ISSUE TITLE
Form not filled after changing language

### ISSUE THREAD

**Issue by icaliman** [laravel-filament/filament#5639]
### Package

filament/spatie-laravel-translatable-plugin

### Package Version

v2.16.69

### Laravel Version

v9.51.0

### Livewire Version

v2.11.2

### PHP Version

8.1.13

### Problem description

After changing language the form is not filled with data and Tabs are broken.

This happens when using `Tabs` in a form. 

https://user-images.githubusercontent.com/4498933/217831660-47a84733-7b11-4a37-b6f0-7e6b27126162.mov

### Expected behavior

After changing language the form must be filled and the tabs must work.

### Steps to reproduce

1. Create a page.
2. Add an Action block
3. Fill the form with some data
4. Change the language

### Reproduction repository

https://github.com/icaliman/filament-bug-translatable-tabs

**Comment by danharrin** [comment]
Fixed by #5639
