### ISSUE TITLE
TernaryFilter on relationship

### ISSUE THREAD

**Issue by howdu** [laravel-filament/filament#5651]
### Package

filament/tables

### Package Version

v2.16.70

### Laravel Version

v9.51.0

### Livewire Version

v2.11.2

### PHP Version

PHP 8.2.1

### Problem description

When using a TernaryFilter on a relationship nothing get filtered. 

```php
Tables\Filters\TernaryFilter::make('productType.status')
```

https://github.com/howdu/filament-tester/blob/ternary-filter-relationship/app/Filament/Resources/ProductResource.php#L54

### Expected behavior

The same result you get for non-relationship filtering. 

### Steps to reproduce

In the example project "Products" has a status filter on the "ProductType" status but it does not work.

### Reproduction repository

https://github.com/howdu/filament-tester/tree/ternary-filter-relationship

**Comment by Z3d0X** [comment]
This seems to work
```php
TernaryFilter::make('productType')
     ->relationship('productType', 'status')
````

**Comment by howdu** [comment]
That works thanks
