### ISSUE TITLE
Multi-select does not display current values on fill

### ISSUE THREAD

**Issue by Rudston** [laravel-filament/filament#5670]
### Package

filament/filament

### Package Version

2.16

### Laravel Version

9.43

### Livewire Version

2.10

### PHP Version

8.0

### Problem description

The multi-select does not fill with the current values as the other fields do 

### Expected behavior

The current values should be displayed as selected

### Steps to reproduce

Please see the README in the repo below.

### Reproduction repository

https://github.com/Rudston/filament-issues.git

### Relevant log output

```shell
none
```

**Comment by danharrin** [comment]
You named your field `tagIds` but you filled `tagsIds`.

**Comment by Rudston** [comment]
Apologies, sorry for wasting your time and thanks for filament!
