### ISSUE TITLE
Custom UserResource messes with package default UserResource

### ISSUE THREAD

**Issue by jonagoldman** [laravel-filament/filament#57]
**Describe the bug**
Creating a custom `UserResource` messes with the default UserResource

**To reproduce**
1. Create a resource called `UserResource` with a custom User in the `$model` property
2. Customize the `form()` method to return only the `name` field
3. Click on the authenticated user and go to `Manage Users`
4. Click on `Create`
5. See that the form shown is the one we just customized instead of the Filament user

**Expected behavior**
The package UserResource should be used for for internal admin users.

**Screenshots**
![Screenshot from 2021-03-02 22-10-08](https://user-images.githubusercontent.com/1297559/109737068-3214a980-7ba4-11eb-81b8-67946c72cdf6.png)

**Context**
- Browser: Chrome
- Server OS: Ubuntu 20.04
- PHP version: 8.0

**Comment by danharrin** [comment]
Thanks! Fixed in v1.2.1.
