### ISSUE TITLE
Weird behavior when using arrows in a searchable selection

### ISSUE THREAD

**Issue by bebetoalves** [laravel-filament/filament#5706]
### Package

filament/filament

### Package Version

2.15

### Laravel Version

9.19

### PHP Version

8.2

### Problem description

When using the tab + arrow keys in a searchable selection, it apparently adds the name of the key to the search input. I don't know if it's a desirable behavior by the community, I also didn't find topics that talked about it.

Video demo: https://streamable.com/ovbnbi

### Expected behavior

The arrow key name should not appear in the search field.

### Steps to reproduce

1. Go to: https://demo.filamentphp.com/blog/posts/create
2. Click into "Content" field and press tab to jump to "Author" field;
3. Press any arrow key;
4. The drop down should collapse and the name of the arrow key should be in the search bar.

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by danharrin** [comment]
Ah I see you opened another
