### ISSUE TITLE
Tab + arrows keys fill the searchable select with the name of the key

### ISSUE THREAD

**Issue by bebetoalves** [laravel-filament/filament#5707]
### Package

filament/filament

### Package Version

2.17.2

### Laravel Version

10

### PHP Version

8.2

### Problem description

When using the tab + arrow keys in a searchable select, it apparently fills the name of the key to the search input. I don't know if it's a desirable behavior by the community, I also didn't find topics that talked about it.

[demo](https://streamable.com/xox1mo)

### Expected behavior

The arrow key name should not appear in the search field.

### Steps to reproduce

1. Clone the repo or create a searchable select input;
2. Click into "Name" field and press tab to jump to "Roles" field;
3. Press any arrow key;
4. The drop down should collapse and the name of the arrow key should be in the search bar.

### Reproduction repository

https://github.com/bebetoalves/bug-searchable-select-filament

**Comment by bebetoalves** [comment]
Apparently this is a bug related to choices.js 👀

https://github.com/Choices-js/Choices/issues/1080

**Comment by danharrin** [comment]
Okay not much we can do then, but thanks for the report.

**Comment by patie** [comment]
@danharrin it looks like it was fixed in new version of Choices.js as mentioned here https://github.com/Choices-js/Choices/issues/1080#issuecomment-2305038062, any chance there will be upgrade of Choices.js library in Filament to v11? 🙏

**Comment by danharrin** [comment]
It will be upgraded in v4 to ensure we don't introduce breaking changes: #13829

**Comment by patie** [comment]
@danharrin thank you, any ETA for v4? ;)
