### ISSUE TITLE
Page height extended unexpectedly when form is using tabs and collapsed sections

### ISSUE THREAD

**Issue by margarizaldi** [laravel-filament/filament#5709]
### Package

filament/filament

### Package Version

v2.17.2

### Laravel Version

Laravel 10.0.2 (also happened in 9.x)

### PHP Version

PHP 8.1.10

### Problem description

When using form with tabs, the page height is extended unexpectedly. And the worst part is, the extended part has light background in the dark mode.
![image](https://user-images.githubusercontent.com/26832856/219556592-6ecf5b3e-963f-47a6-9e5f-2203d5df2bda.png)

### Expected behavior

Should not happen

### Steps to reproduce

Install the repo and see the form in browser,  there's only one resource there.

### Reproduction repository

https://github.com/margarizaldi/filament-page-height-extended

**Comment by zepfietje** [comment]
@margarizaldi, do you think this was introduced in a recent release of Filament?
If possible, please check what was the latest release that didn't contain this bug.

I'm guessing this might have something to do with the page height fixes you worked on recently, @awcodes?

**Comment by margarizaldi** [comment]
@zepfietje Not really, it happened also in previous versions. Not really sure from which version but I knew it since I started to use tab form about a month ago. The repo I made here is a fresh installation of laravel & filament today (latest release), no additional packages, overrides etc. Just dark mode enabled to see the effect more clear.

And I think Mr. awcodes addressed same issue but in different part.

**Comment by margarizaldi** [comment]
Hi @zepfietje I also update the repo with collapsed sections which behaves the same.

**Comment by awcodes** [comment]
I am unable to replicate the issue with your provided repo. Tested in Firefox, Chrome and Safari.

![Screen Shot 2023-02-18 at 10 17 05 AM](https://user-images.githubusercontent.com/3596800/219873668-bf06e6af-9495-4ec1-910a-1dcfafb1c0dd.png)
![Screen Shot 2023-02-18 at 10 16 48 AM](https://user-images.githubusercontent.com/3596800/219873671-9397b51c-18f8-4549-b592-1f5d3c26db49.png)

**Comment by margarizaldi** [comment]
Hi @awcodes, big thanks for testing. I just tested it again more carefully and this time also tested using firefox. I can confirm the problem is totally disappeared in firefox, but it still appeared in Chrome and Edge _"in some situation"_.

I found some interesting fact that might cause this problem. In Windows, there's a default configuration that scale up the screen size to 125% or 150% to keep text readable, see https://stackoverflow.com/questions/58868613/default-windows-is-scaled-to-150. Then firefox —maybe its engine— handles it better so there's no problem, but unfortunately not with Chrome and Edge.

And to get this problem appear for you, you may try to zoom-in the Chrome browser to 125% - 150% and see whether the problem appears or not. But if you or anyone thinks that this issue is too specific and doesn't need to be addressed, then this issue can be closed.

However, most of my users are using windows and highly possible to encounter this problem, I will override the base view and remove "bg-gray-100" class in the html tag to make it just invisible. Not a big problem actually...

**Comment by zepfietje** [comment]
@margarizaldi could you point to the exact place of the HTML element having that `bg-gray-100` class? Maybe it's just a matter of adding a dark class there as well.

Edit: only now see you already mentioned this in your last sentence.

**Comment by zepfietje** [comment]
Could you pull in https://github.com/filamentphp/filament/pull/5734 and see if it fixes the issue for you, @margarizaldi?

**Comment by margarizaldi** [comment]
> Could you pull in #5734 and see if it fixes the issue for you, @margarizaldi?

@zepfietje Nah, that's gonna be perfect!
