### ISSUE TITLE
Form Select component : using '->' to access nested json value in relationship method

### ISSUE THREAD

**Issue by drhootch** [laravel-filament/filament#5740]
### Package

filament/filament

### Package Version

v2.17.3

### Laravel Version

v9.52.0

### Livewire Version

v2.11.3

### PHP Version

PHP 8.0.2

### Problem description

When using the select component and passing a string containing the '->' as the second parameter in the relationship method, for example if we want to get the value of name from data json field
````
\Filament\Forms\Components\Select::make('select')->relationship('relation', 'data->name');

````
the following error is thrown
````
Undefined property: stdClass::$data->name
````

### Expected behavior

The select component should display the options based on the relationship and the $titleColumnName (being the value from json column in this case) defined in the second parameter of the relationship method.

### Steps to reproduce

Create a select component in a form with a relationship method call and set titleColumnName parameter to be a value from json column:
```
Select::make('select')
    ->relationship('relation', 'data->name')
```
Run the code and observe the error thrown.

### Reproduction repository

https://github.com/drhootch/filament-select-relationship-json-issue

**Comment by zepfietje** [comment]
@drhootch, not sure but could you try using `data.name` instead of `data->name`?

**Comment by drhootch** [comment]
> @drhootch, not sure but could you try using `data.name` instead of `data->name`?

this will not get recognized by mysql and throws
```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'data.name' in 'field list' (Connection: mysql, SQL: select `data`.`name`, `id` from `table` order by `data`.`name` asc)
```

**Comment by drhootch** [comment]
I believe this is related to laravel's query pluck not accepting '->'
A related issue from Laravel github is : https://github.com/laravel/framework/issues/14086#issuecomment-245290983
which suggests to use alias 'as' in the relationshipTitleColumnName (example : 'data->name as name')
But this wont do in current Select class because orderBy in Select is also using $component->getRelationshipTitleColumnName()
```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'as `name` asc' at line 1 (Connection: mysql, SQL: select json_unquote(json_extract(`data`, '$."name"')) as `name`, `id` from `table` order by json_unquote(json_extract(`data`, '$."name"')) as `name` asc)
```
I would suggest to use the alias as described in the solution proposed in the above laravel issue only when calling $component->getRelationshipTitleColumnName() inside pluck
example : 
```php
->pluck($component->getRelationshipTitleColumnName().' as '.$component->getRelationshipTitleColumnName()
```
the result would be :
```php
select
  json_unquote(json_extract(`data`, '$."name"')) as `data->name`
from
  `table`
order by
  json_unquote(json_extract(`data`, '$."name"')) asc
```
this way it works for both json and non-json fields without breaking anything

@zepfietje

**Comment by zepfietje** [comment]
@drhootch, could you create a PR with that fix?
Then @danharrin can do a proper review, as he's deeper into the query parts of Filament.

**Comment by drhootch** [comment]
> @drhootch, could you create a PR with that fix? Then @danharrin can do a proper review, as he's deeper into the query parts of Filament.

it will be my first filament PR and i'm very excited to do this :)

**Comment by drhootch** [comment]
> @drhootch, could you create a PR with that fix? Then @danharrin can do a proper review, as he's deeper into the query parts of Filament.

A PR has been submitted https://github.com/filamentphp/filament/pull/5742
Thank you for the great work :)

**Comment by zepfietje** [comment]
Thanks, @drhootch!

**Comment by drhootch** [comment]
@danharrin @zepfietje So apparently there has been a conflict with spatie/translatable package (unfortunately),
But there is still hope to use Json columns with relationship without the need for getOptionLabelFromRecordUsing(),
So when using :
```php
\Filament\Forms\Components\Select::make('select')->relationship('relation', 'data->name');
```
the following error is thrown
```
Undefined property: stdClass::$data->name
```
Therefore an alias 'as' must be added to the relationshipTitleColumnName :
```php
Select::make('select')->relationship('relation', 'data->name as name');
```
But this wont do in current Select class because orderBy in Select is also using $component->getRelationshipTitleColumnName() which breaks with the following error :
```
SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'as `name` asc' at line 1 (Connection: mysql, SQL: select json_unquote(json_extract(`data`, '$."name"')) as `name`, `id` from `table` order by json_unquote(json_extract(`data`, '$."name"')) as `name` asc)
```
So to fix this there is a working solution with Forms/Components/Select without changing the code :
- By customizing the database query that retrieves options using the third parameter of the relationship() method:
```php
use Illuminate\Database\Eloquent\Builder;
 
Select::make('select')->relationship('relation', 'data->name as name', fn (Builder $query) => $query->orderBy('data->name'))
```
- By adding orderBy to the query, Select will cease using $component->getRelationshipTitleColumnName() in its orderBy and everything will work fine.

Hopefully this will help when using JSON columns with Select relationship,

**Comment by drhootch** [comment]
@danharrin @zepfietje i would like to suggest another PR that fixes the issue without breaking anything this time and without the need to customize the database query :

So in Forms\Components\Select instead of doing this (the previous PR):
```php
$relationshipTitleColumnName = $component->getRelationshipTitleColumnName();

return $relationshipQuery
    ->pluck("{$relationshipTitleColumnName} as {$relationshipTitleColumnName}", $keyName)
    ->toArray();
```
Which applies the alias every time; thus will cause conflicts with Spatie/Translatable.

So to fix this, we can conditionally apply the alias only if the requested column is a JSON by checking for '->' : 
```php
$relationshipTitleColumnName = $component->getRelationshipTitleColumnName();
if (str_contains($relationshipTitleColumnName, '->') && !str_contains($relationshipTitleColumnName, ' as ')) $relationshipTitleColumnName .= ' as ' . $relationshipTitleColumnName;

return $relationshipQuery
    ->pluck($relationshipTitleColumnName, $keyName)
    ->toArray();
```
And now it will work with both the following examples :
```php
Select::make('select')->relationship('relation', 'data->name')
```
```php
Select::make('select')->relationship('relation', 'data->name as name', fn (Builder $query) => $query->orderBy('data->name'))
```
If this seems right i can apply for the PR,

And finally, I thank you very much for this excellent project!

**Comment by danharrin** [comment]
Sure, try to PR that version then 👍
