### ISSUE TITLE
Json searchable column

### ISSUE THREAD

**Issue by joaovdiasb** [laravel-filament/filament#5746]
### Package

filament/filament

### Package Version

v2.17.3

### Laravel Version

v10.0.3

### Livewire Version

v2.12.0

### PHP Version

8.1.13

### Problem description

When search individual json column the search is converted to lower case, but not the query, making it not bring data with uppercase letters, using pgsql

<img width="351" alt="CleanShot 2023-02-20 at 17 21 17@2x" src="https://user-images.githubusercontent.com/51106311/220192147-812f4399-cd1a-408d-a425-676e9986d577.png">

![CleanShot 2023-02-20 at 16 58 59@2x](https://user-images.githubusercontent.com/51106311/220189509-c542f7ff-e138-4488-8ca8-ee5706f51918.png)

### Expected behavior

`LOWER("data"->>'tipo_pessoa')::text LIKE '%físic%'`

Bring result that contains uppercase letters

### Steps to reproduce

Search some individual json column

### Reproduction repository

https://github.com/joaovdiasb/fix-filament-json-column-search

**Comment by danharrin** [comment]
So does this work ok on the normal `searchable()`, just a problem with individual?

**Comment by joaovdiasb** [comment]
> So does this work ok on the normal `searchable()`, just a problem with individual?

Oh, global search too.
When set condition works, but custom query don't

**Comment by danharrin** [comment]
I don't use Postgres, how do you fix the query so that it works as it should? You should attempt a PR otherwise you will likely be waiting a long time for someone else to fix it

**Comment by joaovdiasb** [comment]
> I don't use Postgres, how do you fix the query so that it works as it should? You should attempt a PR otherwise you will likely be waiting a long time for someone else to fix it

Because of whereRaw doesn't work:
```
->searchable(
     query: function(Builder $query, string $search): Builder {
         return $query->whereRaw('LOWER("data->>tipo_pessoa")::text LIKE ?', ["%{$search}%"]);
     }
 )
```

This should work, because of internal database type casts of filament:
```
->searchable(
     query: function(Builder $query, string $search): Builder {
         return $query->where('data->tipo_pessoa', 'LIKE', "%{$search}%");
     }
 )
```
Output:
`("data"->>'tipo_pessoa')::text LIKE '%search%'`

And this work, casting to LOWER:
```
->searchable(
     condition: ['data->tipo_pessoa']
 )
```
Output:
`LOWER("data"->>'tipo_pessoa')::text LIKE '%search%'`

I will try to submit something

**Comment by rasul-chopurov** [comment]
> ->searchable(
>      condition: ['data->tipo_pessoa']
>  )

my data in column exampel, repeater data

[{"scholl":"test","type":"5","position":null,"start":null,"end":null},{"scholl":"test2","type":"3","position":null,"start":null,"end":null}]

how to using select filter for type or searchable  for scholll?
