### ISSUE TITLE
Table : Counting rows when loading is deferred 

### ISSUE THREAD

**Issue by Sicklou** [laravel-filament/filament#5754]
### Package

filament/tables

### Package Version

v2.17.4

### Laravel Version

v9.52.0

### Livewire Version

v2.12.0

### PHP Version

PHP 8.1.0

### Problem description

Thanks again for the merge of my PR about deferred loading.

Altough, I can see that a "SELECT COUNT(*)" is still triggered even if deferred loading is activated.

It cames from the `getAllRecordsCount()` inside the call of the `x-tables::selection-indicator` component.

### Expected behavior

Not any query at all when the page is loading

### Steps to reproduce

Activate defer loading on table

### Reproduction repository

https://github.com/Sicklou/filament-fix-loading-count

**Comment by zepfietje** [comment]
Thanks for reporting!
Would you be able to attempt a PR to fix this, @Sicklou?
