### ISSUE TITLE
error on copy & paste an image in markdown editor

### ISSUE THREAD

**Issue by simonwong1985hk** [laravel-filament/filament#5764]
### Package

filament/filament

### Package Version

v2.17.4

### Laravel Version

v9.52.4

### Livewire Version

v2.12.1

### PHP Version

PHP 8.2.2

### Problem description

There is an error on copy & paste an image in markdown editor, which happened in Chrome and Safari, but doesn't in Firefox.

This is a screenshot from Safari.
<img width="1680" alt="safari" src="https://user-images.githubusercontent.com/18599865/220804474-2eaa1377-fcdc-4e45-93c8-12b25af0f042.png">

This is a screenshot from Chrome.
<img width="1680" alt="chrome" src="https://user-images.githubusercontent.com/18599865/220804497-7412f419-3389-49f6-8054-5e430fb9516c.png">

### Expected behavior

It should work in Chrome and Safari, as it work in Firefox.

### Steps to reproduce

copy & paste an image in markdown editor

### Reproduction repository

https://github.com/simonwong1985hk/markdown-issue-filament

**Comment by zepfietje** [comment]
Probably introduced by https://github.com/filamentphp/filament/pull/5727.

Could you have a look, @awcodes @danharrin?

**Comment by awcodes** [comment]
It was introduced by 5727, but adding it was also the fix. So, I'll have to debug some more for Safari and Chrome to see why that property isn't showing up on the event.
