### ISSUE TITLE
Wrong default action for CheckboxList bulk toggleable action

### ISSUE THREAD

**Issue by psyao** [laravel-filament/filament#5766]
### Package

filament/filament

### Package Version

v2.17.4

### Laravel Version

9.52.4

### PHP Version

8.2.0

### Problem description

The default bulk toggleable button action for CheckboxList component is set as 'Deselect all' even when no checkbox is selected.

### Expected behavior

The default action should be 'Select All'.

### Steps to reproduce

Add a checkbox list to a resource

```php
Forms\Components\CheckboxList::make('technologies')
                            ->options([
                                'tailwind' => 'Tailwind CSS',
                                'alpine'   => 'Alpine.js',
                                'laravel'  => 'Laravel',
                                'livewire' => 'Laravel Livewire',
                            ])
                            ->bulkToggleable()
```

or 

```php
Forms\Components\CheckboxList::make('languages')
                            ->relationship('languages', 'name')
                            ->bulkToggleable(),
```

### Reproduction repository

https://github.com/psyao/filament-bulktoggleable-checkboxlist

**Comment by danharrin** [comment]
Fixed in the next release
