### ISSUE TITLE
Make default items dynamically change based on reactive input number

### ISSUE THREAD

**Issue by julio-cavallari** [laravel-filament/filament#5771]
### Package

filament/filament

### Package Version

v2.0.0

### Laravel Version

v9.19.0

### Livewire Version

v2.11

### PHP Version

PHP 8.0

### Problem description

When changing the value of a reactive field, the default number of Repeater items does not change

### Expected behavior

I need that when changing the value of a field, I can create a logic to dynamically generate several Repeater items at once, to make it easier for the user

### Steps to reproduce

Create any field and a Repeater, and create a logic that changes the value of the Repeater's defaultItems method based on the value of the reactive field

```
Forms\Components\Grid::make(1)->schema([
    Forms\Components\TextInput::make('quantidade_de_variacoes')
        ->numeric()
        ->label('Quantidade de Variações')
        ->reactive()
        ->required(),
    Forms\Components\Repeater::make('varicoes')
        ->label('Variações')
        ->hidden(fn (Closure $get) => $get('quantidade_de_variacoes') === 0)
        ->schema([
            Forms\Components\TextInput::make('nome')
                ->label('Nome')
                ->required()
                ->maxLength(255),
            Forms\Components\TextInput::make('preco')
                ->numeric()
                ->mask(fn (Forms\Components\TextInput\Mask $mask) => $mask
                    ->numeric()
                    ->decimalPlaces(2)
                    ->decimalSeparator(',')
                    ->mapToDecimalSeparator([','])
                    ->minValue(0)
                    ->maxValue(999999.99)
                    ->normalizeZeros()
                    ->padFractionalZeros()
                    ->autofix()
                    ->thousandsSeparator('.'),
                )
                ->label('Preço')
                ->required(),
        ])
        ->defaultItems(fn (Closure $get) => $get('quantidade_de_variacoes') ?? 0)
        ->collapsible()
  ])
```

### Reproduction repository

https://github.com/julio-cavallari/filament-test

**Comment by danharrin** [comment]
The default items get loaded when the form is first loaded. You need to use `afterStateUpdated()` to `$set` the repeater with the correct number of items.

**Comment by begueradj** [comment]
Is it mandatory to use the Repeater ? @danharrin

**Comment by danharrin** [comment]
I don't know what you mean, the repeater is used in the original question

**Comment by begueradj** [comment]
I had a typo, hence my stupid question. Sorry.
Great work you have done.
Have a nice day. @danharrin
