### ISSUE TITLE
Table : Selected elements are deselected when using search

### ISSUE THREAD

**Issue by Sicklou** [laravel-filament/filament#5776]
### Package

filament/filament

### Package Version

v2.17.4

### Laravel Version

v9.52.0

### Livewire Version

v2.12.0

### PHP Version

PHP 8.1.0

### Problem description

When using search and select rows, changing the search is making selected rows disappear.

### Expected behavior

To keep the rows selected as it is.

Let's say I need to select two rows not on the same page, I search one, select it, then do another search in order to select the other row.

The selection disappear.

Would be nice to keep it, and maybe, have a way to show what is selected ? (as a bonus feature)

### Steps to reproduce

In the demo, make search and selection on the order page.

### Reproduction repository

https://github.com/Sicklou/filament-fix-loading-count

**Comment by danharrin** [comment]
This is deliberate, we use the filtered table query to fetch bulk action records. If the records are not in the query result, then they won't get returned. That isn't expected behaviour, so whenever the table is filtered or searched, we clear the selection.

**Comment by Sicklou** [comment]
I'm sorry to insist on this subject, I don't want to be unpleasant at all. I'm grateful for all the work you guys done and do !

I thought the ids of selected rows were kept in public variable. And then the bulk action are made on those selected ids in a not filtered query.
When I put myself in the shoes of a user, I need to select two rows and use search to find them, then clear the search at the end, making a bulk action at the end.

Maybe I can open a discussion or mention it on the discord to see if I'm the only one who thinks it is a "basic" feature or not.

If you think it cas be a nice addition, I can try to make a PR about it.

**Comment by danharrin** [comment]
#5788 -  you can now override `shouldDeselectAllRecordsWhenTableFiltered()` to return false if you want this.

**Comment by Sicklou** [comment]
Thanks a lot !

It is perfect, UX is really improved imho.

**Comment by marktopper** [comment]
Hi. How can this be set in v3?

**Comment by sefayildirim** [comment]
I tried but I could not find a solution, is there a detailed explanation, where should I add this method?
