### ISSUE TITLE
Test callTableBulkAction

### ISSUE THREAD

**Issue by Krato** [laravel-filament/filament#5786]
### Package

filament/tables

### Package Version

v2.16.36

### Laravel Version

v9.36.4

### Livewire Version

v2.10.7

### PHP Version

PHP 8.1.14

### Problem description

When creating a test for a `BulkAction::class` throws an error cause the `BulkAction::class` doesn't have the method `getDefaultName()` called on `TestsActions file line 28`.

Filament tests are passing cause you use a `DeleteBulkAction::class` that has that method, but when you use the BulkAction::class test fails cause is returning null.

### Expected behavior

Test should not fail 

### Steps to reproduce

Create a simple test for a filamente table component:

```

it('can call bulk action', function () {
    $posts = Post::factory()->count(10)->create();

    livewire(PostsTable::class)
        ->callTableBulkAction(BulkAction::class, $posts)
        ->assertHasNoTableBulkActionErrors()

});
```

### Reproduction repository

https://github.com/Krato/livewire-table-test

**Comment by danharrin** [comment]
Instead of `BulkAction::class`, pass the name of your bulk action. The class syntax only works for our internal bulk actions or any that define `getDefaultName()`.

**Comment by danharrin** [comment]
So in this case, `->callTableBulkAction('Logger', $posts)`
