### ISSUE TITLE
Forms\Components\FileUpload not uploading on disk

### ISSUE THREAD

**Issue by andreacivita** [laravel-filament/filament#5791]
### Package

filament/filament

### Package Version

v2.17.3

### Laravel Version

v10

### PHP Version

8.2

### Problem description

I have been attempting to upload a file on s3 disk using the Forms\Components\FileUpload feature. However, the file does not seem to be stored on disk even though the upload appears to be successful.
                   

### Expected behavior

I'm expecting to find image on s3 disk

### Steps to reproduce

```php
Forms\Components\FileUpload::make('image')
                                    ->disk('s3')
                                    ->visibility('private')
                                    ->directory('tmp')
                                    ```

**Comment by danharrin** [comment]
Read the comment above, and also we can't debug issues in your local environment. This is more of a support request instead of a bug report.

**Comment by ulasoft** [comment]
Hi!  @andreacivita   found solutions I have the same error! If you found it, you can share it?

**Comment by jbardnz** [comment]
Ran into this issue myself and found the issue. If you set the visibility to public, but your S3 bucket doesn't allow public files it will just silently fail. This is also happening in Filament V3.

**Comment by giagara** [comment]
@jbardnz can you elaborate it please?

**Comment by lpeterke** [comment]
I am also having this issue. It seems like visibility('public') is the internal default with Filament, which will silently fail, because it doesnt seem to align with the default settings for a fresh S3 bucket.

adding visibility('private') to my code fixed the problem.

**Comment by binsarjr** [comment]
does the preview work? I managed to upload this to my S3 minio. But there was no preview when editing
