### ISSUE TITLE
Clickable Record Actions Throwing TypeError

### ISSUE THREAD

**Issue by SupianIDz** [laravel-filament/filament#5817]
### Package

filament/filament

### Package Version

v2.17.8

### Laravel Version

v10.1.5

### PHP Version

PHP 8.1

### Problem description

Based on [documentation](https://filamentphp.com/docs/2.x/tables/getting-started#record-actions), I can change the action when Row is clicked. But when applied it shows an error related to return type.

See [**source example**](https://github.com/SupianIDz/filament-issue/blob/main/app/Filament/Resources/UserResource/Pages/ListUsers.php#L29-L32
)

```php
protected function getTableRecordActionUsing() : ?Closure
{
    return fn() : Action => Actions\DeleteAction::make();
}

```

![image](https://user-images.githubusercontent.com/37969970/222033078-867b0f3d-ee7f-4c6b-84c8-6a6fb3113956.png)

### Expected behavior

When clicked on Row, the data will be deleted.

### Steps to reproduce

1. clone reproduction repository
2. run composer install
3. run migrate
4. create a user
5. go to http://127.0.0.1:8000/admin/users

### Reproduction repository

https://github.com/SupianIDz/filament-issue

### Relevant log output

```shell
App\Filament\Resources\UserResource\Pages\ListUsers::App\Filament\Resources\UserResource\Pages\{closure}(): Return value must be of type Filament\Tables\Actions\Action, Filament\Pages\Actions\DeleteAction returned
```

**Comment by danharrin** [comment]
You imported the wrong action, it should be Filament\Tables instead of Filament\Pages

**Comment by SupianIDz** [comment]
> You imported the wrong action, it should be Filament\Tables instead of Filament\Pages

sorry @danharrin , I imported it wrongly in the reproduction repository. I've [fixed](https://github.com/SupianIDz/filament-issue/blob/main/app/Filament/Resources/UserResource/Pages/ListUsers.php#L28-L31) wrong imported action, but it's still happening.

[Screencast from 2023-03-01 19-45-38.webm](https://user-images.githubusercontent.com/37969970/222130488-894cb45f-bfa1-4232-911c-8c62e390d0a7.webm)

**Comment by danharrin** [comment]
What's the error now?

**Comment by SupianIDz** [comment]
> What's the error now?

`Filament\Tables\Table::getRecordAction(): Return value must be of type ?string, Filament\Tables\Actions\DeleteAction returned`

my [code](https://github.com/SupianIDz/filament-issue/blob/main/app/Filament/Resources/UserResource/Pages/ListUsers.php#L28-L31)

**Comment by danharrin** [comment]
I will fix the docs, they're wrong. This should be `fn () => 'delete'`, as long as you have a `DeleteAction` existing on the row too.
