### ISSUE TITLE
Pagination Not Showing on Chrome in Windows 10

### ISSUE THREAD

**Issue by intrepidws** [laravel-filament/filament#5823]
### Package

filament/filament

### Package Version

v2.17.8

### Laravel Version

v9.52.4

### Livewire Version

v2.12.2

### PHP Version

PHP 8.1.16

### Problem description

The pagination footer that appears at the bottom of tables isn't showing up in the latest version of Google Chrome on Windows 10. This has been tested on my Filament app and also on the Filament demo app, on two different computers running Windows 10. Chrome on Mac OS appears fine.

I'm working on testing older versions of Filament but I can tell you that it's been like this since at least v2.16.66 and is still like this in the most recent version (v2.17.8).

Here are screenshots from both of the Windows 10 computers, in both dark and light mode:

![windows-02](https://user-images.githubusercontent.com/125735/222248056-137f29c5-7ea6-43f8-b6e3-a8ab0d24c9e5.jpg)
![windows-01](https://user-images.githubusercontent.com/125735/222248019-c46e7603-0261-4e43-bcd0-70e51af97ab5.jpg)

### Expected behavior

I have tested this on Chrome in Mac OS and it appears fine. Here is a screenshot from that, showing what it should look like.

![mac-01](https://user-images.githubusercontent.com/125735/222249066-cbdbe3ca-54e2-4661-b4af-02f745e5f805.jpg)

### Steps to reproduce

On a Windows 10 computer running Google Chrome, access the [Filament Demo](https://demo.filamentphp.com/) and click into the "Products" or "Orders" sections. The footer that should show the pagination appears empty.

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by intrepidws** [comment]
@danharrin Not sure why this got auto-closed, as I did put in a repo. This issue exists in the demo app, which is the quickest and easiest way to see it.

**Comment by danharrin** [comment]
Usually people are lazy and just put the demo repo for unrelated issues

**Comment by danharrin** [comment]
If we can't replicate this in MacOS, I doubt this will be fixed by the core team so its probably best if you submit a PR if you want to see it fixed soon

**Comment by intrepidws** [comment]
I'm looking into it.

**Comment by intrepidws** [comment]
This was reported to me by a client originally. After getting my hands on a Windows machine via BrowserStack, I now have reason to think this is a PEBCAK situation. I'm closing this for now pending further investigation.

**Comment by alex-r-redfern** [comment]
In case anyone ends up here pulling their hair out: If you are using vite/mix and can't see the pagination links: Try adding the filament vendor folders (tables, filament and forms) to the content in the tailwind.config.js and recompiling. E.G. 
```module.exports = {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './vendor/laravel/jetstream/**/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',

        './vendor/filament/tables/**/*.blade.php',
        './vendor/filament/filament/**/*.blade.php',
        './vendor/filament/forms/**/*.blade.php',
    ], 
``` 

This will be the issue if you inspect the bottom of the table and the pagination dom is there, but the class `hidden` is hiding it but `lg:grid` isn't in any of your custom templates.

Hope this helps anyone stumbling on this issue!

**Comment by intrepidws** [comment]
In my case, it was a Chrome extension that was universally setting `display: none` on a class that Filament uses.
