### ISSUE TITLE
Dropdown components render issue

### ISSUE THREAD

**Issue by ravenKaisar** [laravel-filament/filament#5830]
### Package

filament/filament

### Package Version

V2.17.9

### Laravel Version

9.52.4

### PHP Version

8.2.2

### Problem description

Problem is the ```$form``` variable undefined in ```packages/support/resources/views/components/dropdown/list/item.blade.php``` file. Yesterday @danharrin had commit in this file. The commit link is [here](https://github.com/filamentphp/filament/commit/eaabe682d13125bb4b31eaf848ada3b8bb0d9e73)

![image](https://user-images.githubusercontent.com/16849877/222371328-96d4c40f-1ff7-4db8-9ece-f6ab374da13f.png)

### Expected behavior

![image](https://user-images.githubusercontent.com/16849877/222371839-c929ed1a-87cf-4fda-80b6-1ccb6e506a10.png)

### Steps to reproduce

Just composer update or set the specific version. The version is v2.17.9

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by zepfietje** [comment]
@ravenKaisar, thanks for reporting! This will be fixed as soon as possible. 👍

**Comment by zepfietje** [comment]
Fixed in [v2.17.10](https://github.com/filamentphp/filament/releases/tag/v2.17.10).

**Comment by ravenKaisar** [comment]
Thank you @zepfietje, @danharrin

It's working 👍
