### ISSUE TITLE
Undefined variable $form when using ActionGroup

### ISSUE THREAD

**Issue by Reinbier** [laravel-filament/filament#5831]
### Package

filament/filament

### Package Version

v2.17.9

### Laravel Version

v10.1.5

### PHP Version

PHP 8.1.8

### Problem description

Updating filament/filament to version v2.17.9 in my project broke the pages where I make use of `Filament\Pages\Actions\ActionGroup`, to provide a dropdown list with actions.

A dropdown list with Actions that point to a `->url()` are no problem. However, by making use of `->action('method_name')` the page will show an error:
**Undefined variable $form** in PROJECT_ROOT/vendor/filament/support/resources/views/components/dropdown/list/item.blade.php at **line: 74**

I backtraced the problem to occur due to the commit [eaabe68](https://github.com/filamentphp/filament/commit/eaabe682d13125bb4b31eaf848ada3b8bb0d9e73) by @danharrin.

I tested it using filament v2.17.8 and there is no issue.

### Expected behavior

No error should occur and the dropdown list within an ActionGroup should show as normal.

### Steps to reproduce

1. Clone the reproduction repository,
2. Setup the project following the instructions provided by the README,
3. login into the project on localhost using the credentials from the README,
4. Navigate to the Users 'index' page,
5. In the code at `App\Filament\Resources\UserResource\Pages\ListUsers`; uncomment lines 24-27 to show that `->action(...)` works outside an ActionGroup,
6. uncomment line 36 and refresh the browser to receive an error page.

### Reproduction repository

https://github.com/Reinbier/filament-bug-undefined-form

**Comment by danharrin** [comment]
This was already fixed in .10, LMK if not.

**Comment by Reinbier** [comment]
You are very quick! Thank you Dan!
