### ISSUE TITLE
Repeater and relationships broken since upgrade from 2.17.8

### ISSUE THREAD

**Issue by howdu** [laravel-filament/filament#5833]
### Package

filament/filament

### Package Version

2.17.10

### Laravel Version

10

### PHP Version

8.2

### Problem description

Since upgrade from 2.17.8 to 2.17.10

The repeater relationship is no longer working getting error:
Call to undefined method App\Models\Customer::address()

Reverting back this change fixes the issue:
https://github.com/filamentphp/filament/commit/426e03a5607b14d5515e97336790a375d377a346

### Expected behavior

Go to create a customer: /admin/customers/create

### Steps to reproduce

Login to admin and go to create a customer: /admin/customers/create

### Reproduction repository

https://github.com/howdu/filament-tester/tree/repeater-relationship

**Comment by howdu** [comment]
Code to reproduce. It seems to be when there's a group with relationship inside the repeater.
https://github.com/howdu/filament-tester/blob/repeater-relationship/app/Filament/Resources/CustomerResource.php

```php
Forms\Components\Repeater::make('customer_addresses')
        ->relationship('addresses')
        ->schema([
            Forms\Components\Select::make('address_id')
                ->hiddenOn('edit')
                ->relationship('address', 'name'),

            Forms\Components\Group::make()
                ->relationship('address')
                ->visibleOn('edit')
                ->schema([
                    Forms\Components\TextInput::make('name'),
                ])
        ])
```

**Comment by howdu** [comment]
I'm just working on the project to reproduce it corectly.

**Comment by danharrin** [comment]
Fixed in next release

**Comment by howdu** [comment]
The latest release is missing this fix
https://github.com/filamentphp/filament/releases/tag/v2.17.11

**Comment by danharrin** [comment]
It's just not in the changelog. Try it

**Comment by howdu** [comment]
Thanks that's come through now, but now a new error stemming from `getClone`.

<img width="1237" alt="Screenshot 2023-03-03 at 10 46 44" src="https://user-images.githubusercontent.com/533658/222700989-bd0ed51f-c305-4a78-b28a-d6547cc34f7b.png">

**Comment by danharrin** [comment]
Please share the Flare exception Url so I can explore the stack trace

**Comment by howdu** [comment]
https://flareapp.io/share/w5Bv4Q65#F102

**Comment by howdu** [comment]
@danharrin I've updated to v2.17.12 but getting the same error: https://flareapp.io/share/95JZb425#F72

Also updated my [example repository](https://github.com/howdu/filament-tester/tree/repeater-relationship) to reproduce this: go to Layout create and click to add a Container will throw the error. 

It seems to be when you use Builder + Repeater and then get the state inside the schema
```php
->schema(function ($state): array {
```
https://github.com/howdu/filament-tester/blob/repeater-relationship/app/Filament/Resources/LayoutResource.php

**Comment by danharrin** [comment]
Hopefully #5850 fixes that one
