### ISSUE TITLE
BelongsToSelect: Call to a member function save() on string 

### ISSUE THREAD

**Issue by viezel** [laravel-filament/filament#585]
### Package

filament/forms

### Package Version

2.0.0-beta23

### Laravel Version

8.61.0

### Livewire Version

2.5

### PHP Version

8.0

### Bug description

When calling `$this->form->getState()` then BelongsToSelect line 108 throws an error, due to `$this->getModel()` returns a string and not the model class. 

Bug or did I miss something obvious?

### Steps to reproduce

The model:

```php
class Department extends Model
{
    protected $fillable = [
        'title',
        'parent_id'
    ];

    public function owner(): BelongsTo
    {
        return $this->belongsTo(User::class);
    }
}
```

Livewire component

```php
protected function getFormSchema(): array
{
    return [
        TextInput::make('title')->required()->unique(Department::class),
        BelongsToSelect::make('owner')->relationship('owner', 'name')
    ];
}

protected function getFormModel(): string
{
    return Department::class;
}

public function create(): void
{
    Department::create($this->form->getState());
}
```

**Comment by danharrin** [comment]
Haha - you're early! 😂 

I've just released a small fix in beta25.

Now, you should call `saveRelationships()` once you have a model to associate with:

```php
public function create(): void
{
    $department = Department::create($this->form->getState());

    $this->form->model($department)->saveRelationships();
}
```

I think this is explained a bit in the docs but it's a difficult concept to explain. If you see any clarity improvements, submit a PR.

**Comment by viezel** [comment]
It’s really fantastic! Love how I can use all these fields all over the app.
