### ISSUE TITLE
`Method Filament\Forms\Components\SpatieMediaLibraryFileUpload::getUploadedFileUrlUsing does not exist.` in v3

### ISSUE THREAD

**Issue by SebastiaanKloos** [laravel-filament/filament#5864]
### Package

filament/filament

### Package Version

v3.0.0-alpha59

### Laravel Version

v9.52.4

### PHP Version

8.2.3

### Problem description

When using the SpatieMediaLibraryFileUpload field in a form this issue occurs.

### Expected behavior

Not crashing

### Steps to reproduce

Add a simple SpatieMediaLibraryFileUpload field to a form.

### Reproduction repository

-

**Comment by wychoong** [comment]
Make sure when you composer require this SpatieMediaLibraryFileUpload for v3

I had the same issue when I thought composer is smart enough to get the v3 when the rest of the packages installed is with 3.x-dev@dev

**Comment by SebastiaanKloos** [comment]
@wychoong thank you so much. I totally forgot this. Sorry @danharrin I'll close this issue.

**Comment by eduardonwa** [comment]
i just installed the package, and updated my Post model accordingly, everything went okay, migrations, etc but im getting a similar error than OP, mine is: ```\SpatieMediaLibraryFileUpload::getUploadedFileUsing does not exist.``` 

how do i require SpatieMediaLibraryFileupload, @wychoong 

```Make sure when you composer require this SpatieMediaLibraryFileUpload for v3```

**Comment by wychoong** [comment]
> i just installed the package, and updated my Post model accordingly, everything went okay, migrations, etc but im getting a similar error than OP, mine is: `\SpatieMediaLibraryFileUpload::getUploadedFileUsing does not exist.`
> 
> how do i require SpatieMediaLibraryFileupload, @wychoong
> 
> `Make sure when you composer require this SpatieMediaLibraryFileUpload for v3`

I believe Dan updated the doc command to install the package with specific version/tag. You can either composer require again or update the composer.json file and composer update

**Comment by eduardonwa** [comment]
Hm. I understand, I gave it a try again but to the same output I don't understand, ran both composer require and update; there were no signs of any errors? not that im aware. i am using  v2.17.52 of filament :-)
