### ISSUE TITLE
enableReordering inversed in form

### ISSUE THREAD

**Issue by Grazulex** [laravel-filament/filament#5885]
### Package

filament/filament

### Package Version

v2.17.14

### Laravel Version

v9.52.4

### PHP Version

PHP 8.1

### Problem description

I'm using the upload form field with Spatie.
When I'm using the enableReordering() in the form, the order of the pictures is inversed in the list.
In the database, the order int is correct but in the form, on the screen, the last picture (order) is on the top of the list, and the first in the order is at bottom.
order is db is :
- 1 
- 2
- 3
on the screen :
-3 
-2
-1

### Expected behavior

order is db is :
- 1 
- 2
- 3
on the screen :
-1
-2
-3

### Steps to reproduce

            Forms\Components\Section::make('Pictures')
                ->schema([
                    Forms\Components\SpatieMediaLibraryFileUpload::make('pictures')
                        ->disk('products')
                        ->enableReordering()
                        ->image()
                        ->preserveFilenames()
                        ->multiple(),
                ]),

### Reproduction repository

https://gitlab.com/jnkconsultbv/cetronic

**Comment by danharrin** [comment]
Try `appendFiles()`

**Comment by Grazulex** [comment]
Thanks...that was the solution
