### ISSUE TITLE
TextInput min max are not correct

### ISSUE THREAD

**Issue by viezel** [laravel-filament/filament#589]
### Package

filament/forms

### Package Version

2.0.0-beta30

### Laravel Version

8.61.0

### Livewire Version

2.5

### PHP Version

8.0

### Bug description

The below code works for the HTML input in the browser. However, its during incorrect in Laravel validation, as it returns "The current value must be at least 10 characters." which for text string and not number input. 

### Steps to reproduce

```php
TextInput::make('current_value')
    ->type('number')
    ->minValue(10)
    ->maxValue(23)
    ->required(),
```

Output:

<img width="998" alt="image" src="https://user-images.githubusercontent.com/312065/133583356-394f8af1-944e-45a5-9f9c-a71062733fde.png">

**Comment by viezel** [comment]
one possible solution is for the ` ->type('number')` to automatically add `->rules(["numeric"])` - to tell laravel to make sure its numbers to validate against.

**Comment by ryangjchandler** [comment]
@viezel There is a `numeric()` method on the input too.

**Comment by viezel** [comment]
Alright.. then ill close it :)

**Comment by danharrin** [comment]
Yeah, `numeric()` on the input should fix this.
