### ISSUE TITLE
Rich Text Editor not rendering

### ISSUE THREAD

**Issue by ShamarKellman** [laravel-filament/filament#59]
**Describe the bug**
Rich text editor not rendering and throws error in console

**To reproduce**
1. Create rich text editor
2. 
```
RichEditor::make('description')
                    ->attachmentDisk('public')
                    ->attachmentDirectory('richtext')
                    ->autofocus()
                    ->disableAllToolbarButtons()
                    ->disableToolbarButtons($buttons = [])
                    ->enableToolbarButtons($buttons = [])
                    ->placeholder('Description'),
```
3. Check developer console for error
```
alpine.js:1907 Uncaught SyntaxError: Unexpected token u in JSON at position 0
    at JSON.parse (<anonymous>)
    at SupportAlpine.js:70
    at Array.forEach (<anonymous>)
    at SupportAlpine.js:55
    at alpine.js:1498
    at Array.forEach (<anonymous>)
    at new qe (alpine.js:1498)
    at alpine.js:1607
    at alpine.js:1589
    at u (alpine.js:90)
(anonymous) @ SupportAlpine.js:70
(anonymous) @ SupportAlpine.js:55
(anonymous) @ alpine.js:1498
qe @ alpine.js:1498
(anonymous) @ alpine.js:1607
(anonymous) @ alpine.js:1589
u @ alpine.js:90
u @ alpine.js:94
u @ alpine.js:94
u @ alpine.js:94
u @ alpine.js:94
u @ alpine.js:94
u @ alpine.js:94
u @ alpine.js:94
u @ alpine.js:94
u @ alpine.js:94
u @ alpine.js:94
u @ alpine.js:94
walkAndSkipNestedComponents @ alpine.js:1583
initializeElements @ alpine.js:1600
qe @ alpine.js:1510
initializeComponent @ alpine.js:1904
(anonymous) @ alpine.js:1849
(anonymous) @ alpine.js:1863
discoverComponents @ alpine.js:1862
start @ alpine.js:1848
setTimeout (async)
initializeComponent @ alpine.js:1906
(anonymous) @ alpine.js:1849
(anonymous) @ alpine.js:1863
discoverComponents @ alpine.js:1862
start @ alpine.js:1848
async function (async)
start @ alpine.js:1845
(anonymous) @ alpine.js:1933
(anonymous) @ create:529
dispatch @ dispatch.js:6
value @ index.js:87
(anonymous) @ create:534

```

**Expected behavior**
Expects to see a Trix editor

**Screenshots**

**Context**
- Browser: Chrome
- Server OS: MacOSX
- PHP version: [e.g. 7.4]

**Additional details**
Appears to be cause by   `value: @entangle($formComponent->name).defer,` found in rich-editor.blade.php line 42

**Comment by danharrin** [comment]
Hey! I will write some documentation on this... but it happens when you use components in the `Filament\Forms\Components` namespace rather than the `Filament\Resources\Forms\Components` namespace.

Components in the second namespace automatically prepend `record.` to the name of the field, so they can be used to write to the `$record` property on the Livewire components that create and update records. If you'd like to try it for yourself - change the name to `record.description` and watch the error disappear.

The namespace definitely needs clarifying in the docs though 👍
