### ISSUE TITLE
Laravel Echo cannot be found - causing issues when subscribing to public and private Pusher channels

### ISSUE THREAD

**Issue by bphippen** [laravel-filament/filament#5914]
### Package

filament/filament

### Package Version

v2.17.11

### Laravel Version

v10.2.0

### PHP Version

8.1.13

### Problem description

Enabled Filament's Echo config to subscribe to a custom Pusher channel on a custom Filament page.

Was getting a successful auth subscription to the App.Models.User.X channel

Was not getting any subscription to my custom channel via a Livewire listener.
ie. `"echo-private:App.Properties.{$this->record->id},TrainingEvent" => 'notifyTrainingEvent'`

When loading the Filament page, I got a "Laravel Echo cannot be found" console notice.

To fix this issue took a little digging and I'm not sure what the repercussions might be but inside of base.blade.php if you remove the defer on line 113 and remove the DOMContentLoaded event listener on line 119, then subscriptions start working again.

![Screen Shot2023-03-12 at 17 00 05@2x](https://user-images.githubusercontent.com/1563364/224609204-84b610ce-fec4-46bd-9bf2-e5654fdfba8e.jpg)

### Expected behavior

I expected to be getting a successful subscription that should have been visible in the Pusher logs.

### Steps to reproduce

1. Enable the Filament Echo config settings
2. Create a custom Filament page
3. Create a method something like this: 
```
public function getListeners(): array
    {
        return [
            "echo-private:App.Properties.{$this->record->id},TrainingEvent" => 'notifyTrainingEvent',
        ];
    }
```
4. Create a broadcast channel for that.
```
Broadcast::channel('App.Properties.{propertyId}', function ($user, $propertyId) {
    return true;
});
```
5. Assuming you have a Pusher account and creds, this is where you would see the subscription for that channel, but its not showing up there due to a bug.

### Reproduction repository

https://github.com/bphippen/filament-echo

**Comment by danharrin** [comment]
The reason why we defer loading Echo is because we struggled to get Livewire to listen to our events conditionally.

Currently, I cannot work out a way to support Livewire's Echo implementation within the Filament admin panel. I can suggest a way to subscribe to events and run Livewire methods though, by adding code to your Livewire view:

```blade
<div
    x-data="{}"
    x-init="
        window.addEventListener('EchoLoaded', () => {
            window.Echo.private('channel name here')
                .listen('.private-event-name', () => {
                    $wire.doSomethingHere()
                })
        })
    "
></div>
```

I would welcome a PR to standardise our Echo implementation more so we don't need the EchoLoaded event or something, but you'd need to do manual testing with our database notifications panel & broadcast notifications.

**Comment by Saifallak** [comment]
> adding code to your Livewire view:
> 
> ```
> <div
>     x-data="{}"
>     x-init="
>         window.addEventListener('EchoLoaded', () => {
>             window.Echo.private('channel name here')
>                 .listen('.private-event-name', () => {
>                     $wire.doSomethingHere()
>                 })
>         })
>     "
> ></div>
> ```

i can see in pusher debug that I'm subscripted to that channel, but whatever I listen on isn't firing inside filament dashboard, but outside it gets fired. even simple console.log


```

<x-filament-panels::page>
    <div
        x-data="{}"
        x-init="
        window.addEventListener('EchoLoaded', () => {
            console.log('here loaded');
            window.Echo.private('mc-chat-conversation.2').listenToAll((event, data) => { console.log(event, data); });
        })
    ">
</div>

```

any idea where I should look for?

**Comment by lordjack** [comment]
Hello guys, I was able to solve this error following this tutorial, I hope it helps you too.

https://laraveldaily.com/post/configure-laravel-reverb-filament-broadcasting
