### ISSUE TITLE
Tenant menu overflows collapsed sidebar

### ISSUE THREAD

**Issue by josefbehr** [laravel-filament/filament#5928]
### Package

filament/filament

### Package Version

v3

### Laravel Version

10

### Livewire Version

v2

### PHP Version

PHP 8.2

### Problem description

When tenancy is enabled and the sidebar is collapsible, the tenant menu stays inside the confines of the collapsed sidebare and extends over the edge of the page:

![image](https://user-images.githubusercontent.com/4368880/224854300-9515800c-23dc-4f52-9ef5-ea35ac76d782.png)

### Expected behavior

The tenant menu opens normally in full width even with collapsed sidebare

### Steps to reproduce

Configure a context with tenancy and collapsible sidebar, add two tenants for a user, sign in as the user and collapse the sidebar, then click the tenant initials to open the menu

### Reproduction repository

https://github.com/josefbehr/filament-v3-tenant-menu-collapsible-demo

**Comment by zepfietje** [comment]
@josefbehr, could you try adding the `shift` and/or `teleport` attribute to the dropdown in `tenant-menu.blade.php`?
```blade
<x-filament::dropdown
    placement="bottom-start"
    shift
    teleport
>
```

**Comment by josefbehr** [comment]
@zepfietje sure, thanks. That change at least appears to fix the overflow, if not the sizing issue:
![image](https://user-images.githubusercontent.com/4368880/224967610-de2db1a5-f0cf-42f7-b857-6d811c95a15d.png)

**Comment by zepfietje** [comment]
Hmm, the width issue occurs with both shift and teleport applied?

**Comment by danharrin** [comment]
very weird, is there an overflow-hidden on the sidebar maybe

**Comment by zepfietje** [comment]
`teleport` would work around that, right?

**Comment by josefbehr** [comment]
> very weird, is there an overflow-hidden on the sidebar maybe

Seems like it: 
![image](https://user-images.githubusercontent.com/4368880/224991928-7532e38d-0b22-493e-879c-ef91feb91da8.png)

I can try teleport. Where should the dropdown be teleported to though?

**Comment by josefbehr** [comment]
I tried just adding teleport as suggested by @zepfietje, but no change

**Comment by zepfietje** [comment]
That's strange as the overflow issue is exactly what this is used for with the table filters dropdown. Maybe you could take a look at those and see what's different.

**Comment by zepfietje** [comment]
@josefbehr, have you been able to look into this issue once more?

**Comment by josefbehr** [comment]
No, did not find time to do that as of yet, but I will try to do so the next week.

**Comment by zepfietje** [comment]
I've created a PR that fixes this issue, @josefbehr!
