### ISSUE TITLE
Select form component is not disabling by callable

### ISSUE THREAD

**Issue by aisuvro** [laravel-filament/filament#5953]
### Package

filament/forms

### Package Version

^2.16

### Laravel Version

9

### Livewire Version

2

### PHP Version

8.2

### Problem description

Hi,
I have found an issue in the Select component the disable is not working.

![Screenshot from 2023-03-17 16-34-12](https://user-images.githubusercontent.com/2842856/225882292-13378279-97a0-4206-9a6a-e4c88fb95eb2.png)

### Expected behavior

It should be disabled like other components.

### Steps to reproduce

`         Select::make($prefix.'country_code')
                            ->label("Country")
                            ->options(Address::countries())
                            ->reactive()
                            ->required()
                            ->dehydrated(
                                fn(callable $get): bool => !$get($prefix.'use_default')
                            )
                            **->disabled(
                                fn(callable $get): bool => $get($prefix.'use_default')
                            )**`

### Reproduction repository

https://github.com/filamentphp/filament/blob/2.x/packages/forms/src/Components/Select.php

**Comment by danharrin** [comment]
It's a known limitation with Choices.js that we are unable to fix at the moment.
