### ISSUE TITLE
Date parsing

### ISSUE THREAD

**Issue by vincent-tarrit** [laravel-filament/filament#5959]
### Package

filament/filament

### Package Version

v.2.0.0

### Laravel Version

v.9.52

### PHP Version

PHP 8.1

### Problem description

Hello, 

I want to show a date picker as 

```php
 DateTimePicker::make('start_at')
                ->required()
                ->label('Date de début')
                ->withoutSeconds(),
```

My date to parse is : 2023-04-01 08:00:00

But in the field it's 4th january 2023. However, Carbon parse it well as 1st april.

Do you have some idea for me ? Thank you !

### Expected behavior

showing 1st april

### Steps to reproduce

in the config :

'timezone' => 'Europe/Paris',
'locale' => 'fr',

### Reproduction repository

https://github.com

**Comment by danharrin** [comment]
Set the `format()`? but I would strongly suggest not using a weird date format for storage. Stick to `yyyy-mm-dd`

**Comment by vincent-tarrit** [comment]
Thank you Dan, it's like this in DB, really strange...
