### ISSUE TITLE
Paginate does not work

### ISSUE THREAD

**Issue by loranger** [laravel-filament/filament#603]
### Package

filament/filament

### Package Version

1.10

### Laravel Version

8.61.0

### PHP Version

7.4.16

### Bug description

My pagination does not work. The paginator displays the correct amount of pages, but clicking on a page refresh the first one only.

I thought my tables where messed up but the issue is behave the same way on the default user list:

![Enregistrement de l’écran 2021-09-23 à 17 59 29](https://user-images.githubusercontent.com/6014/134545541-ac2445ae-87eb-4242-9f61-1da520884bcc.gif)

Here is an ouput of telescope showing the last click of the gif: the page 7. 

<img width="981" alt="Capture d’écran 2021-09-23 à 18 00 47" src="https://user-images.githubusercontent.com/6014/134545603-02b3e66c-24a2-4f74-abdb-698f95d4b5b9.png">

The MySQL query does not seems to get the correct offset.

What may have caused this issue and how can I fix it ?

**Comment by danharrin** [comment]
What is your Livewire version?

**Comment by loranger** [comment]
Sorry I did not fill the version because it's the one shipped with filament.
It seems it's 2.2

**Comment by danharrin** [comment]
Interesting. Can you create a brand new project and see if the issue is there too? I've never hit this.

**Comment by loranger** [comment]
I've just create a brand new project and the result is the same.

Here is what I have done:

- Create project using `composer create-project --prefer-dist laravel/laravel`
- Adjust `.env` variables for docker
- Setup and start a docker-compose file (nginx, php-fpm:latest, mariadb:latest)
- Install filament
    - `composer require filament/filament`
    - add `FILAMENT_AUTH_GUARD=web` to `.env` file
    - prepare User Model (adding traits and make all users filament admin)
    - add `ignoreMigrations()` to `AppServiceProvider`
- Prepare seeding 100 users with factory
- Migrate (`artisan migrate --seed`)
- Create my user account (`artisan make:filament-user`)
- Restart container to use the latest `.env` variables
- Log in `/admin`, click on paginator. Datas refreshed, but the same page.

**Comment by NeroAzure** [comment]
I faced the same issues a few days ago, and was thinking about making a pr. The issue here is the 2.6 update of Livewire (which should be installed here), they changed the pagination code to support multiple paginations, they now use an array with the paginations name to handle the page number.

Changing the setPage function in this package to include the array, fixed it for me:
```php
public function setPage($page)
{
    $this->page = $page;
    $this->paginators['page'] = $page; // this line here

    $this->selected = [];
}
```

**Comment by danharrin** [comment]
I'll bump the minimum Livewire version to v2.6 and PR that fix. Thank you.
