### ISSUE TITLE
Collapsible Content Table Layout Design

### ISSUE THREAD

**Issue by andrewdwallo** [laravel-filament/filament#6035]
### Package

filament/filament

### Package Version

v2.17.18

### Laravel Version

v10.4.1

### Livewire Version

v2.12.3

### PHP Version

PHP 8.2.4

### Problem description

When table rows are not collapsible using provided Documentation here: https://filamentphp.com/docs/2.x/tables/layout#collapsible-content

Much needed space between the Split and collapsible Panel content is removed. The contents in the Panel component are essentially touching the Split content above it. 

### Expected behavior

I expected that when the Panel component is not collapsible it would have as much room above it as for example when the 
`->collapsed()` option is set to false or just when `->collapsible()` is set and when you click to open a collapsed row.

Panel is not collapsible. Panel Content is touching the Tags for abilities.
![Screenshot 2023-03-26 201612](https://user-images.githubusercontent.com/104294090/227814237-1878e3b0-15d3-4704-9bdc-66c4c8847f59.png)

Panel is set to `collapsed(false)`. Much more room. I expected it to look like this just without the collapsible arrow of course. 
![Screenshot 2023-03-26 201750](https://user-images.githubusercontent.com/104294090/227814317-d7dab816-c2ea-4bdd-bebe-b25cb103d078.png)

### Steps to reproduce

Download Reproduction repository. Seed database. Run application. 

```
Login
email: admin@filament.com
password: password
```

Go to Users Page and see. 
Go to `app/Filament/Resources/UserResource.php` and set the Panel Component for the table to be `collapsed(false)` to see the difference.

### Reproduction repository

https://github.com/andrewdwallo/filament-table

**Comment by danharrin** [comment]
The reason why it looks good when the panel is collapsible is because we actually teleport the panel to a different part of the layout and treat it differently to a normal panel so that the arrow layout can be aside the content. The panel is no longer a normal layout component.

In your case, you just need to add a Stack with some spacing, for example:

```php
Tables\Columns\Layout\Stack::make([
    Tables\Columns\Layout\Split::make([
        Tables\Columns\TextColumn::make('name')
            ->sortable()
            ->searchable(),
        Tables\Columns\TagsColumn::make('abilities'),
    ]),
    Tables\Columns\Layout\Panel::make([
        Tables\Columns\Layout\Stack::make([
            Tables\Columns\TextColumn::make('email')
                ->sortable()
                ->searchable(),
            Tables\Columns\TextColumn::make('company')
                ->sortable()
                ->searchable(),
            Tables\Columns\TextColumn::make('phone')
                ->sortable()
                ->searchable(),
            Tables\Columns\TextColumn::make('address')
                ->sortable()
                ->searchable(),
        ]),
    ]),
])->space(3),
```

**Comment by andrewdwallo** [comment]
Okay thank you
