### ISSUE TITLE
Forms using Select don't get Default value when Searchable

### ISSUE THREAD

**Issue by yamakrane** [laravel-filament/filament#6037]
### Package

filament/filament

### Package Version

v2.0.0

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

php 8

### Problem description

In my Forms, as soon as I add ->searchable() to my Select, the ->default() value is not selected anymore.

### Expected behavior

It is supposed to preselect the item Draft after page loading.

### Steps to reproduce

`Select::make('test')->options([
                        'draft' => 'Draft',
                        'reviewing' => 'Reviewing',
                        'published' => 'Published',
                    ])
                    ->default('draft')
                   ->searchable()
                    ->preload(),`

### Reproduction repository

https://github.com/yamakrane/test

**Comment by danharrin** [comment]
Please follow the instructions and create a reproduction repository, otherwise this issue will not be investigated. We make it very clear on the issue form why this repository is required.

**Comment by yamakrane** [comment]
Sorry, it is modified. 

Http/Livewire/Youssef.php

is the file

**Comment by danharrin** [comment]
There is no `$this->form->fill()` in `mount()`, so the default values aren't there.
