### ISSUE TITLE
There is some issue in filament/forms/src/Concerns/InteractsWithForms.php

### ISSUE THREAD

**Issue by sayasuhendra** [laravel-filament/filament#604]
### Package

filament/forms

### Package Version

v2.0

### Laravel Version

v8.54

### Livewire Version

v2.6

### PHP Version

PHP 8.0.8

### Bug description

There is some issue in filament/forms/src/Concerns/InteractsWithForms.php

### Steps to reproduce

I Just install filament form and play with it.

1. I install new laravel project
2. Install laravel ui and tall preset
3. install filament form
4. I create a new livewire and make new form but I got this error

```php
<?php

 

namespace App\Http\Livewire;

 

use Filament\Forms\Concerns\InteractsWithForms;

use Filament\Forms\Contracts\HasForms;

use Livewire\Component;

 

class Belajar extends Component implements HasForms

{

    use InteractsWithForms;

 

    public function render()

    {

        return view('livewire.belajar');

    }

}

```

### Relevant log output

```shell
Symfony\Component\ErrorHandler\Error\FatalError
During class fetch: Uncaught ParseError: syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /Users/user/Documents/github/livewire/preset/vendor/filament/forms/src/Concerns/InteractsWithForms.php:167 Stack trace: #0 /Users/user/Documents/github/livewire/preset/vendor/composer/ClassLoader.php(428): Composer\Autoload\includeFile('/Users/user/Doc...') #1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Filament\\Forms\\...') #2
```

**Comment by sayasuhendra** [comment]
When I switch to php 7.4.21 the problem solve. it seems issue is related to php version 8

**Comment by danharrin** [comment]
Sorry, I can't reproduce this.

The minimum version for the forms package is PHP 8. Please make sure that your web server is running PHP 8, not just your PHP CLI. The only reason this line should be throwing an exception is when you are using a PHP version < 8, because we're using the null safe operator.
