### ISSUE TITLE
Change footer logo

### ISSUE THREAD

**Issue by mstfkhazaal** [laravel-filament/filament#6089]
### Package

filament/filament

### Package Version

v2.17.21

### Laravel Version

v10.0.0

### PHP Version

php 8.0.0

### Problem description

I need to change footer and put our footer like copiright

### Expected behavior

Nothing

### Steps to reproduce

I looked in the docs but only found the footer hide

### Reproduction repository

.

**Comment by wychoong** [comment]
Hide the footer by config then use render hook ‘footer.start’
