### ISSUE TITLE
Block builder field wrapper view not correct

### ISSUE THREAD

**Issue by misbahansori** [laravel-filament/filament#6098]
### Package

filament/filament

### Package Version

v2.17.17

### Laravel Version

10.4.1  

### PHP Version

8.2.1

### Problem description

I have created a builder component, I want to customize the block component title to make it bigger and bolder.
<img width="1093" alt="Screenshot 2023-04-02 at 20 53 53" src="https://user-images.githubusercontent.com/20674057/229357389-f03f2e8e-94a3-43f9-af28-5c517e791c9f.png">
I tried using `fieldWrapperView('wrapper')` on the block component like this : 
```
Builder::make('questions')
    ->blocks([
        Block::make('general')
            ->fieldWrapperView('wrapper')
            ->schema([
                TextInput::make('name')
                    ->label('Project Name')
                    ->required(),
            ]),
    ])
    ->columnSpanFull(),
```
with the view like this : 
```
<div>
    <span>Test wrapper</span>
    <div>
        {{ $slot }}
    </div>
</div>
```
but the wrapper is applied on the TextInput component instead : 
<img width="1090" alt="Screenshot 2023-04-02 at 20 59 35" src="https://user-images.githubusercontent.com/20674057/229357657-308fc626-5866-43e1-b097-c34b31ad082c.png">
when I add another TextInput to the Block component like this : 
```
Builder::make('questions')
    ->blocks([
        Block::make('general')
            ->fieldWrapperView('wrapper')
            ->schema([
                TextInput::make('name')
                    ->label('Project Name')
                    ->required(),
                TextInput::make('company')
                    ->label('Company Name')
                    ->required(),
            ]),
    ])
    ->columnSpanFull()
```
it will look like this : 
<img width="1099" alt="Screenshot 2023-04-02 at 21 01 18" src="https://user-images.githubusercontent.com/20674057/229357778-ee4857d9-958c-4676-b713-1a6ef181e45e.png">

### Expected behavior

When I change the `fieldWrapperView('wrapper')` It should change the wrapper for the Block component instead of the TextField component.

### Steps to reproduce

Create a Builder component with one block and one input
```
Builder::make('questions')
    ->blocks([
        Block::make('general')
            ->fieldWrapperView('wrapper')
            ->schema([
                TextInput::make('name'),
            ]),
    ]),
``` 
Create a view resources/views/components/wrapper.blade.php
```
<div>
    <span>Test Wrapper</span>
    <div>
        {{ $slot }}
    </div>
</div>

```

### Reproduction repository

https://github.com/misbahansori/filament-example-app/

**Comment by danharrin** [comment]
The part you want to customise is not in the field wrapper, because Block is not a field. Youd need to use CSS to do this 👍
