### ISSUE TITLE
Relations are duplicated when you call `getState` in `afterCreate` hook

### ISSUE THREAD

**Issue by oddvalue** [laravel-filament/filament#6107]
### Package

filament/filament

### Package Version

v2.17.21

### Laravel Version

v10.5.1

### Livewire Version

v2.12.3

### PHP Version

8.2.4

### Problem description

When you call `getState` relations are saved, creating duplicated records. This didn't happen in v2.17.20.
Bug appears to have been introduced in this commit https://github.com/filamentphp/filament/pull/6077/files

### Expected behavior

Calling `getState` to not cause duplicated records to be inserted

### Steps to reproduce

Call `getState` in `afterCreate` on create page of resource. Issue shown in demo repo example test

### Reproduction repository

https://github.com/oddvalue/broken-relationship-demo

**Comment by zepfietje** [comment]
@danharrin, could you look into this issue?

**Comment by oddvalue** [comment]
@danharrin any news on this?

**Comment by danharrin** [comment]
Reverted the broken PR.
