### ISSUE TITLE
Fileupload used in form inside a modal (JetStream)

### ISSUE THREAD

**Issue by yamakrane** [laravel-filament/filament#6122]
### Package

filament/filament

### Package Version

2

### Laravel Version

10

### Livewire Version

2

### PHP Version

8

### Problem description

Hello an thank you for this great work,

I ran into an issue, when I wanted to insert a filament form inside a modal using jetstream modal component.

The FileUpload using the default component or Spatie's, are behaving similarly. In other words,

when I put the form inside the page (not in a modal) everything goes fine but when I put the FileUpload inside a modal, there is a duplicate filepond fileupload div, Empty + Filled one overlapping which doesnt let me click on the buttons of Download, Remove or Open as this will make me click on the overlapping empty filepond FileUpload input file.

Plus when i upload a new file on top of that, i can see two separate fileuploads and they both get cleared, then the file path is removed from the database if I use spatie's.

PS: This happens only when Form is FILLED

Here are some screenshots:

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/38190169/229932659-cc469781-5ee6-4194-baf8-03bae8c1b1ee.png">

<img width="1009" alt="image" src="https://user-images.githubusercontent.com/38190169/229932775-6cb662f9-249d-48d1-abe8-f400affbad53.png">

### Expected behavior

Normal behavior letting me Fill the input file, and then replace it, remove it, downloaded it and open the file without going through double inputs overlapping.

### Steps to reproduce

1. Install Jetstream (maybe its only using jetstream's x-dialog-modal)
2. Create Livewire component (Example is Youssef livewire component)
3. Insert modal <x-dialog-modal> in the blade with a button opening that modal
4. Insert {{$this->form}} inside the modal
5. Fill the form in the livewire component indicating the fileinput in the mount function.
6. Preview with existing record containing path of the file

### Reproduction repository

https://github.com/yamakrane/test.git

**Comment by yamakrane** [comment]
wire:ignore

**Comment by yamakrane** [comment]
Idk why when I put it in the modal, the .filepond--drop-label div takes the following style:` transform: translate3d(0px, 0px, 0px); opacity: 1;` instead of `transform: translate3d(0px, 30px, 0px); opacity: 0; visibility: hidden; pointer-events: none;`

I believe that this is where the problem comes from

**Comment by danharrin** [comment]
I don't think this is a Filament issue, we didn't design the Jetstream modal and it may need some tweaking to get it to work. Our own admin panel modal component works fine with forms so it must be something in your implementation.

**Comment by yamakrane** [comment]
true, I created a new modal component to work with it. thanks

**Comment by yamakrane** [comment]
For those who are still encountering this issue.

This is actually happening in every modal using the Hide/Show as if it recreates the filepond.

The trick is to build the form only when the modal is open, example:
<x-dialog-modal wire:model="modalOpen">
@if($modalOpen) // <---- This is the thing
{{ $this->form }}
@endif
</x-dialog-modal>

**Comment by KhairulAzmi21** [comment]
> For those who are still encountering this issue.
> 
> This is actually happening in every modal using the Hide/Show as if it recreates the filepond.
> 
> The trick is to build the form only when the modal is open, example: @if($modalOpen) // <---- This is the thing {{ $this->form }} @endif

how to build the form only when the modal is open ?

**Comment by CristinaQi** [comment]
> For those who are still encountering this issue.
> 
> This is actually happening in every modal using the Hide/Show as if it recreates the filepond.
> 
> The trick is to build the form only when the modal is open, example: @if($modalOpen) // <---- This is the thing {{ $this->form }} @endif

You saved my day! Thank you!
