### ISSUE TITLE
KeyValue field with on initial entry - no delete icon

### ISSUE THREAD

**Issue by ap1969** [laravel-filament/filament#6132]
### Package

filament/filament

### Package Version

v2.17.21

### Laravel Version

v10.6.2

### Livewire Version

v2.12.3

### PHP Version

PHP  8.1.2

### Problem description

Hi,
When a basic edit page initially loads, with the record having one entry in the KeyValue field, there is no delete button.

If I press "Add Row" in the KeyValue field, the delete icon appears for the new row and the original row.

If I edit a record with more than one initial entry in the KeyValue field, the delete icon is present for all rows.

https://www.loom.com/share/ce2aa3789e8b47efa66bff5303f601dd

### Expected behavior

Expect a delete icon even on that first row

### Steps to reproduce

Create a keyvalue field with one entry.

Note - the sample repo is not complete, eg, it won't update the model. The metadata value on the model is hard-coded to a one-entry array.

### Reproduction repository

https://github.com/ap1969/filament-keyvalue

**Comment by ap1969** [comment]
Investigated further: 

vendor\filament\forms\resources\views\components\key-value.blade.php

has the block:
```
@if (($canDeleteRows() || $isReorderable()) && $isEnabled())
    <th
        scope="col"
        x-show="rows.length > 1"
        class="{{ ($canDeleteRows() && $isReorderable()) ? 'w-16' : 'w-12' }}"
    >
        <span class="sr-only"></span>
    </th>
@endif
```

Should that be "rows.length > 0" ?

**Comment by zepfietje** [comment]
Thanks for reporting, @ap1969!
Seems like a bug to me too.

Could you PR a fix?

**Comment by zepfietje** [comment]
Actually I just found some other weird behavior:

1. Key-value field has 1 row by default.
2. Add another row.
3. Delete one row.
4. Both rows disappear.

**Comment by danharrin** [comment]
Thats because the keys are blank

**Comment by zepfietje** [comment]
But still a bug, right?

**Comment by danharrin** [comment]
Eh, I don't think it's much of a problem if they both delete when the key is not filled in.

**Comment by zepfietje** [comment]
Sure, we can leave it as is for now, though it's confusing behavior to me.

**Comment by zepfietje** [comment]
What do you think about the original issue, @danharrin?

**Comment by ap1969** [comment]
> Thanks for reporting, @ap1969! Seems like a bug to me too.
> 
> Could you PR a fix?

Done: https://github.com/filamentphp/filament/pull/6166

**Comment by zepfietje** [comment]
Thanks, @ap1969!
Waiting on a final review from @danharrin.
