### ISSUE TITLE
table toggleable function not working in  split::make

### ISSUE THREAD

**Issue by milad4444** [laravel-filament/filament#6158]
### Package

filament/tables

### Package Version

v2.x

### Laravel Version

v10

### Livewire Version

v2

### PHP Version

php 8.1

### Problem description

table toggleable function not working in  split::make

### Expected behavior

just correct action for toggleable function in split::make

### Steps to reproduce

null

### Reproduction repository

https://github.com/filamentphp/filament

**Comment by danharrin** [comment]
Toggleable support doesnt exist for layouts, its not a feature that has been built. Not sure if it is even a good idea

**Comment by milad4444** [comment]
thank you danharring.
the filament changed my life realy.
i love you man ❤
