### ISSUE TITLE
 Integrity constraint violation: Duplicate entry

### ISSUE THREAD

**Issue by mstfkhazaal** [laravel-filament/filament#6183]
### Package

filament/filament

### Package Version

v2.17.24

### Laravel Version

v10.0.0

### PHP Version

8.2.4

### Problem description

when i add a row in table has relationship i get this error

SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '2' for key 'services.PRIMARY' (Connection: mysql, SQL: update `services` set `id` = 2, `services`.`updated_at` = 2023-04-12 11:40:59 where `id` = 6)

https://user-images.githubusercontent.com/47450090/231453172-7aee7900-eb0c-48b0-a0f0-b7c749703ccb.mov

### Expected behavior

That the process is completed successfully without errors

### Steps to reproduce

You can use and run my project
don't forget php artisan migrate:fresh --seed
email: admin@gmail.com
password: 123456789

### Reproduction repository

https://github.com/mstfkhazaal/subscribo

**Comment by mstfkhazaal** [comment]
@danharrin Please check my issue as soon as possible

**Comment by andresnijder** [comment]
@mstfkhazaal you defined the wrong foreign key in your model: https://github.com/mstfkhazaal/subscribo/blob/master/app/Models/Service.php#L30
rename it to 'currency' should solve your issue.

`public function currency(): BelongsTo
    {
        return $this->belongsTo(Currency::class,'currency);
    }`

**Comment by mstfkhazaal** [comment]
> @mstfkhazaal you defined the wrong foreign key in your model: https://github.com/mstfkhazaal/subscribo/blob/master/app/Models/Service.php#L30 rename it to 'currency' should solve your issue.
> 
> `public function currency(): BelongsTo { return $this->belongsTo(Currency::class,'currency); }`

not work


Undefined property: App\Models\Service::$currency

**Comment by mstfkhazaal** [comment]
> @mstfkhazaal you defined the wrong foreign key in your model: https://github.com/mstfkhazaal/subscribo/blob/master/app/Models/Service.php#L30 rename it to 'currency' should solve your issue.
> 
> `public function currency(): BelongsTo { return $this->belongsTo(Currency::class,'currency); }`

Thanks i found the problem is in the team() 
https://github.com/mstfkhazaal/subscribo/blob/master/app/Models/Service.php#L25

  public function teams(): BelongsTo
    {
        return $this->belongsTo(Team::class,'team_id');
    }
