### ISSUE TITLE
Create User - is_admin cannot be null

### ISSUE THREAD

**Issue by nunoturbina** [laravel-filament/filament#62]
**Describe the bug**
If i don't check a new user as admin the following error is throw

**To reproduce**
1. Go to 'Create User'
2. Insert name, email and passwords
3. Click 'Create'

![image](https://user-images.githubusercontent.com/15314558/109788828-9ddc2e00-7c07-11eb-9cb5-e08e35747158.png)

**Comment by danharrin** [comment]
Thanks! Fixed in v1.2.4.
