### ISSUE TITLE
Toggle column issues

### ISSUE THREAD

**Issue by archilex** [laravel-filament/filament#6215]
### Package

filament/filament

### Package Version

v2

### Laravel Version

v9

### Livewire Version

v2

### PHP Version

8.1

### Problem description

Since I mentioned some bugs with the toggle columns in PR #6198 I thought it'd be helpful to have a minimal demo repo to make it easy to see and discuss the issues. Some of the issues that have been mentioned here and on discord:

1. Console error `cannot read properties of undefined (reading 'value')` (addresssed with PR #6198)
2. Console error  `cannot read properties of undefined (reading 'dispatchEvent') (address with PR #6198)
3. Only the first toggle works after filtering the page with the same type of column
4. Infinite loop on toggles on slow connections
5. Switching 1 toggle actually causes a different toggle to switch
6. Other issues??

### Expected behavior

Toggle columns should work

### Steps to reproduce

Clone the repo

```bash
composer install
```

Edit .env file as needed and then

```bash
php artisan key:generate
php artisan migrate:fresh --seed
```

Then head to the `User` resource.

## Steps to reproduce

After each test be sure to refresh your browser to clear out any caches and start with all the toggles **active**. This will give everyone the same starting point.

**Issue 1**
1. Open your console
2. Click on the `next page` button
3. Click on the `previous page` button
4. See the console error

**Issue 2**
1. Open your console
2. Open filters and select `Yes` from `Active`
3. Click on the first toggle button to make it `inactive` and thus remove it from the view.
4. See the console error

**Issue 3**
1. Open filters and select `Yes` from `Active`
2. Only the first toggle can be toggled
3. All other toggles cannot be turned off anymore. Note that two queries are being made. One to turn it off and one to turn it on.
4. If you refresh the page everything works again.

**Issue 4**
1. Turn your dev tools throttling to `fast 3g`
2. Refresh to page to load under `fast 3g`
3. Go down the list and toggle each of the toggles. 
4. Usually by the 5th or 6th toggle, the toggles will enter an infinite loop, each loop sending queries to the DB

**Issue 5**
I have seen this, but not sure how to reproduce at the moment

Hope this helps to get discussion going on how to fix this.

Thanks!

### Reproduction repository

https://github.com/archilex/filament-toggle-column-demo

**Comment by danharrin** [comment]
So which issues does #6198 fix?

**Comment by archilex** [comment]
In my list above it's issue 1 and 2. I probably shouldn't have used the word "issue" for listing the problems I was describing. So PR #6198 fixes PROBLEMS 1 and 2 above
