### ISSUE TITLE
Wrong error message on one filetype for FileUpload

### ISSUE THREAD

**Issue by krikru95** [laravel-filament/filament#6234]
### Package

filament/filament

### Package Version

2.17.24

### Laravel Version

10.7.1

### Livewire Version

2.12.3

### PHP Version

8.2.3

### Problem description

If we configure a FileUpload Field with only one allowed mimetype and upload a not allowed file type we get a wrong error message.

Configuration: ` ->acceptedFileTypes(['video/mp4]);`

Error Message: "Erwartet oder video/mp4"

### Expected behavior

The correct message would be "Erwartet video/mp4", without the "oder" (or). 

### Steps to reproduce

1. Configure a FileUpload Field in a form
2. Allow only on FileType
3. Upload one not allowed file

### Reproduction repository

https://github.com/filamentphp/filament

**Comment by zepfietje** [comment]
Thanks for reporting!

This seems like something that should be fixed in the file uploader (Filepond) though: https://github.com/pqina/filepond.

Feel free to suggest a fix there. 😊

**Comment by krikru95** [comment]
Thank you, i created an issue for filepond
