### ISSUE TITLE
Tables\Filters\Filter: `$query->join()` operations not working

### ISSUE THREAD

**Issue by daris-trngl** [laravel-filament/filament#6270]
### Package

filament/filament

### Package Version

v2.17.24

### Laravel Version

v9.52.5

### Livewire Version

v2.12.3

### PHP Version

PHP 8.2.4 

### Problem description

If I try to use the `join()` method on the Filter's query I get an error and the "join" part of the SQL query gets ignored.

```PHP
Filter::make('out_of_stock')
    ->query(fn (Builder $query): Builder => $query->join('product_warehouse', 'products.id', '=', 'product_warehouse.product_id')
        ->whereRaw('greatest(0, (product_warehouse.total_stock - product_warehouse.reserved_stock)) = 0'))
```

The error is:

```
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'product_warehouse.total_stock' in 'where clause'
```
```sql
SELECT
  count(*) AS aggregate
FROM
  `products`
WHERE
  (
    greatest(
      0,
      (
        product_warehouse.total_stock - product_warehouse.reserved_stock
      )
    ) = 0
  )
```

**_Note: The same query works fine by its own._**

### Expected behavior

I want to filter the table records based on a condition on a relationship.

### Steps to reproduce

1. Use the `join()` method on the custom query of a Table Filter

### Reproduction repository

https://github.com

**Comment by rtrocc** [comment]
hi, I'm having this problem and would like to resurrect this discussion/bug if that's alright? I can set up a demo to reproduce it if that's what's needed, but let me know first please. Thanks!

**Comment by rtrocc** [comment]
ok, while looking into the problem I see the true reason this isn't working 😂 

There is a `baseQuery()` method that allows modification of the base query, otherwise the regular `query()` method is actually a `Where` clause query which is why the join gets ignored.
