### ISSUE TITLE
RelationManager->can() behaves weird if you pass a record via parameter

### ISSUE THREAD

**Issue by nikcani** [laravel-filament/filament#6313]
### Package

filament/filament

### Package Version

v2.17.24

### Laravel Version

v10.7.1

### PHP Version

PHP 8.2.4

### Problem description

I was trying to check a custom policy inside the canAttach method of a RelationManager.

```
protected function canAttach() : bool
{
    return $this->can('customPolicyMethod', $this->ownerRecord);
}
```

Either I am using RelationManager->can() incorrect or it behaves weird.
It checks if the policy action exists on the **related model**
If that is true, it then checks the result of the policy action on the **model of the record passed via parameter**.

### Expected behavior

I would expect RelationManager->can() to do the following if I pass a record via paramter:
It checks if the policy action exists on the **model of the record passed via parameter**
If that is true, it then checks the result of the policy action on the **model of the record passed via parameter**.

### Steps to reproduce

1. Create Model A & B, Resource A & B as well as Policy A & B.
2. Create a ManyToMany relation for A & B.
3. Create a RelationManager for A that shows all related B.
4. Call $this->can() insidse the RelationManager with a record as second parameter.
5. Inside the actual can method: Check which policy action is loaded by `$policy = Gate::getPolicyFor($model);` and which policy action is actually tested by `return Gate::forUser($user)->check($action, $record ?? $model);`.

### Reproduction repository

https://github.com/nikcani/blank

**Comment by danharrin** [comment]
This isn't a bug, it's the way we've decided for it to work. You are absolutely welcome to override any of the authorisation methods to achieve the behaviour you are looking for. It's not something we can change in core as it's a breaking change. We have just chosen a simple standard implementation that should work for most cases.
