### ISSUE TITLE
Removing the default sort and refreshing brings back the default sort

### ISSUE THREAD

**Issue by Roboroads** [laravel-filament/filament#6391]
### Package

filament/filament

### Package Version

v2.17.34

### Laravel Version

v10.9.0

### Livewire Version

v2.12.3

### PHP Version

PHP 8.2.4

### Problem description

When setting a default sort, you get redirected to a URL containing this default sort. 

E.g. 
```php
// UserResource
$table
    ->defaultSort('id', 'desc');
 ```
 
 If you go to the page, you go to filament.test/admin/users then get 'redirected' to filament.test/admin/users?tableSortColumn=id&tableSortDirection=desc to setup the default sort. However, click in the table now on the 'id' column, it removes the sort on id, and the URL becomes filament.test/admin/users again. Then, refresh - since no sort has been given, you get redirected to the default sort again.
 
 This becomes an annoyance if you send the URL to someone else and they do net get the same overview as you have, or refresh yourself and get a different overview. This doesn't happen for any other case, just when removing the default sort going back to the first page of unsorted records.

### Expected behavior

From the example above: I expect when I refresh, to receive the same overview as before the refresh. Or: send the link over to my colleague and they getting the same overview I had.

Two possible solutions:

1. The URL without any sort GET params should give you the default sort, (in my examples case, /users sorts on id-desc, /users?tableSortColumn=null sorts on nothing).
2. The navigation links to a URL where the default sort is already present, instead of setting it after loading the page.-+

### Steps to reproduce

**Setup**

1. `cit clone git@github.com:/Roboroads/filamentphp-bugs.git`
2. `cd filamentphp-bugs`
3. `composer setup` does composer install, sets up env, boots sail, migrates/seeds database.
4. Login at [http://127.0.0.1/admin/login](http://127.0.0.1/admin/login) with `test@example.com` / `password`

**Reproduction**

1. Click "Users" in navigation. 
    You go to /admin/users, after which URL changes to /admin/users?tableSortColumn=id&tableSortDirection=desc
2. Remove the sort from id by clicking on the column header
    URL changes to /admin/users
3. Refresh.
    URL changes back to /admin/users?tableSortColumn=id&tableSortDirection=desc and default sort is put back.

### Reproduction repository

https://github.com/Roboroads/filamentphp-bugs

**Comment by danharrin** [comment]
Personally I disagree. If there is a null table sort, it should go back to use the default sort. As such, I don't agree that this is a bug. You are more than welcome to override any behaviour inside Filament - in this case you want to override `applySortingToTableQuery()` on any resource list page.
