### ISSUE TITLE
Translations for form component does not automatically update data picker locale

### ISSUE THREAD

**Issue by Michael-HEIW** [laravel-filament/filament#6396]
### Package

filament/filament

### Package Version

v2.17.24

### Laravel Version

v10.7.1

### PHP Version

v8.1.16

### Problem description

When a PR is submitted for a new locale the date picker dayjs also need to be manually updated. 

See discussion on discord:  https://discord.com/channels/883083792112300104/1102987402806566952

## For example

The Welsh translation 'cy' pull requested and accepted in Feb (#5741). 

The date time picker: [packages/forms/resources/js/components/date-time-picker.js](https://github.com/filamentphp/filament/blob/2.x/packages/forms/resources/js/components/date-time-picker.js) has the locales at the end of the file.

![date picker english format](https://user-images.githubusercontent.com/71503011/235927510-fd4744e6-8620-49ae-8003-508fc5f3d044.png)

The red area is the datepicker, the green shows the dates are translated in other parts of the table. (using Carbon's translatedFormat method.)

The dayjs library has a translation for 'cy', however, it is not 'required' by the **date-time-picker.js**

## Current matches

- Filament forms/**/compoent.php has 40 locales translated 
- **date-time-picker.js** only requires 34! Welsh (cy) is one of the languages which are not 'required'. *

| form  | date picker |
|:------|:------------|
| ar    | ar          |
| bn    |             |
| bs    | bs          |
| ca    | ca          |
| cs    | cs          |
| cy    |  *          |
| da    | da          |
| de    | de          |
| en    | en          |
| es    | es          |
| eu    |             |
| fa    | fa          |
| fi    | fi          |
| fr    | fr          |
| he    |             |
| hi    | hi          |
| hu    | hu          |
| hy    | hy/hy-am    |
| id    | id          |
| it    | it          |
| ja    | ja          |
| ka    | ka          |
|       | km          |
| ku    | ku          |
| lt    |             |
| lv    |             |
| ms    | ms          |
| my    | my          |
| nl    | nl          |
| pl    | pl          |
| pt_BR | pt_BR/pt_br |
| pt_PT | pt_PT/pt    |
| ro    | ro          |
| ru    | ru          |
| sv    | sv          |
| sw    |             |
| tr    | tr          |
| uk    | uk          |
| vi    | vi          |
| zh_CN | zh_CN       |
| zh_TW | zh_TW       |

\* I have raised a PR to add Welsh 'cy': #6395

The ideal situation is the build process automatically adds a new locale, although there are some locales which are not exact matches. E.g. Filament form : pt_PT, date picker: `pt_PT: require('dayjs/locale/pt')`

### Expected behavior

I would expect the build process to automatically detect the new locale and update any required components. 

Possibly the file directory could be scanned and a json file generated, the date picker read the automatically generated file to 'require' all of them.

### Steps to reproduce

Switch locale in Laravel to one of the translated locales that do not have a require in the date picker e.g. **bn** or **cy**. The date picker will display English dates. 

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by danharrin** [comment]
The problem is that we don't control the Day.js translations, so we have to manually import them. It should be the responsibility of whoever adds the language to import it in the date picker JS IMO.

**Comment by Michael-HEIW** [comment]
Thanks for the prompt reply, 

I agree Day.js is a third party app, it has over 100 translations.

I think at a minimum the exact steps needs to be documented.

I didn't know this when I added the translation in Feb. There are five other translations added to forms which are also not imported in the date picker js.

The date picker JS is part of the filament project.

**Comment by danharrin** [comment]
You're more than welcome to PR improvements to our README about contributing translations

**Comment by Michael-HEIW** [comment]
Thanks Dan, I'll take a look 👍

Thinking about automating the import, it isn't worth it for 40 translations in 2 years.

I looked at other PRs, the one for adding Finnish translations looks like a good example:

- https://github.com/filamentphp/filament/commit/2f1c0af6b25378a2968cd8fb249b71dd32168f39

It looks like **file-uploads.js** has an import too 😔.

Do you think this would be a good example to add to the contribution guide?

Can you see anything missing?

**Comment by danharrin** [comment]
It would be good to just make a note in the README to point to the directories and files that need updating when making a new translation. You could search a popular language like `nl` in all files to see if any have been missed. Off the top of my head, its only the date picker and file upload though.

**Comment by Michael-HEIW** [comment]
Thanks for accepting the PRs. The date time picker is now working in Welsh 🎉

<img width="560" alt="image" src="https://github.com/filamentphp/filament/assets/71503011/499e1244-e0f8-4c11-9d2d-8056ff7eaf66">

I've put a PR into Fileponds for the file upload, as it doesn't have Welsh translation. 

I have a TODO to follow up a table with contributing locale.

**Comment by danharrin** [comment]
🏴󠁧󠁢󠁷󠁬󠁳󠁿 ❤️
