### ISSUE TITLE
$resource is undefined - @jetstreams

### ISSUE THREAD

**Issue by manueljmedina** [laravel-filament/filament#64]
**Describe the bug**
when ejecute php artisan make:filament-page Settings  trow $resource is undefined

**To reproduce**
ejecute php artisan make:filament-page Settings

**Expected behavior**
$resource is undefined

{

        $this->items = collect();

 

        $this->items->push(

            NavigationItem::make('filament::dashboard.title', route('filament.dashboard'))

                ->activeRule('filament.dashboard')

                ->icon('heroicon-o-home')

                ->sort(-1),

        );

 

        foreach (Filament::getResources() as $resource) {

            if ($resource::authorizationManager()->can()) {

                $this->items->push(...$resource::navigationItems());

            }

        }

 

        foreach (Filament::getPages() as $page) {

            if ($resource::authorizationManager()->can()) {

                $this->items->push(...$page::navigationItems());

            }

        }

 

        return $this->items->sortBy(fn ($item) => $item->sort);

    }

 

    public function render()

    {

        return view('filament::components.nav');

    }

}

**Screenshots**

![error](https://user-images.githubusercontent.com/34580541/109811020-51d5bd00-7bf8-11eb-9ab5-6acf8e60ac66.PNG)

**Comment by danharrin** [comment]
Hi! This should be fixed in v1.2.5.
