### ISSUE TITLE
Error on Console: Uncaught SyntaxError

### ISSUE THREAD

**Issue by mstfkhazaal** [laravel-filament/filament#6417]
### Package

filament/filament

### Package Version

v2.17.35

### Laravel Version

v10.0.0

### PHP Version

8.2.4 

### Problem description

After update i get this error in the console
Uncaught SyntaxError: Unexpected token '}' (at app.js?id=e86eecc2b1e06821fc6e52592bc106bd:180:141512)

### Expected behavior

Nothing

### Steps to reproduce

Nothing

### Reproduction repository

Nothing

**Comment by danharrin** [comment]
Please send a reproduction repository, or I cant help

**Comment by danharrin** [comment]
I've tried myself and it works

**Comment by zepfietje** [comment]
So let's close it for now then?

Edit: looking into it.

**Comment by mstfkhazaal** [comment]
https://github.com/mstfkhazaal/filament-test
![image](https://user-images.githubusercontent.com/47450090/236411586-c3cc7c46-c051-463b-9bc5-e3717bd744bf.png)

**Comment by zepfietje** [comment]
Thanks, @mstfkhazaal.
We found a fix already: #6418.

**Comment by mstfkhazaal** [comment]
> Thanks, @mstfkhazaal. We found a fix already: #6418.

I update my project to 2.17.36
but the error stay in console

**Comment by danharrin** [comment]
Clear your browser cache

**Comment by mstfkhazaal** [comment]
> Clear your browser cache

Thanks
