### ISSUE TITLE
extraAttributes on bulk actions not working correctly

### ISSUE THREAD

**Issue by daerentis** [laravel-filament/filament#6473]
### Package

filament/filament

### Package Version

v2.17.32

### Laravel Version

v10.9.0

### PHP Version

PHP 8.1.18

### Problem description

Trying to add extraAttributes to a bulk action but it is not rendered in the HTML.

### Expected behavior

It should render correctly in the HTML like in single actions.

### Steps to reproduce

```php
->bulkActions([
    Tables\Actions\BulkAction::make('groupCalculation')
        ->icon('heroicon-o-calculator')
        ->action(function (Collection $records) {
            // Doing something...
        })
        ->extraAttributes(['some' => 'attribute'])
])
```

### Reproduction repository

https://github.com/daerentis/bulk-action-extra-attributes

**Comment by danharrin** [comment]
Fixed by #6582.
