### ISSUE TITLE
unable to delete bulk records when sorted with on relation table property (count)

### ISSUE THREAD

**Issue by henk-n** [laravel-filament/filament#6492]
### Package

filament/filament

### Package Version

v2.17.38

### Laravel Version

10.10.0

### PHP Version

8.2.2

### Problem description

When sorting on a related count column in the table, you get an error message when you want to delete the selected rows in the bulk action. 

response: (example of the git repo)
SQLSTATE[42S22]: Column not found: 1054 Unknown column 'clothing_count' in 'order clause'

### Expected behavior

that the selected rows are deleted without error message

### Steps to reproduce

clone repo
configure a mysql database
migrate and seed
start laravel
go to the agencies resource
select one or more rows
bulk action, choose delete selected
sql error

### Reproduction repository

https://github.com/henk-n/sortissue/

**Comment by danharrin** [comment]
Fixed by #6554
