### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by tanthammar** [laravel-filament/filament#65]
**Describe the bug**
Following the "Getting Started" guide, when I get to the third step I get an error.

**To reproduce**
did this:
```
composer require filament/filament
php artisan migrate
```
 
Then this, but get an error: `Route [filament.auth.login] not defined`
 ```
php artisan make:filament-user
```
I enter `name`, `password` and "`yes`" to create an `administrator` user.

**Screenshots**
![](https://cdn.discordapp.com/attachments/816387015729086494/816645836842336296/unknown.png)

**Context**
Fresh Laravel 8 Jetstream with Teams and Livewire.
php 8

**Comment by tplessis** [comment]
Same here. Laravel 8, PHP 7.4.

![Install Issue](https://i.imgur.com/sxkqoGP.png)

**Comment by tanthammar** [comment]
I did a fresh installation of w Laravel 8 Jetstream + teams.
it worked. Will try to figure out what Filament doesn't like with my boilerplate.

**Comment by tplessis** [comment]
After running a `php artisan route:clear` before installation, problem solved. 👍

**Comment by tanthammar** [comment]
I found the culprit in my boilerplate.

Collided with my **custom** `config/nova->path` and filament default url. Both were set to "`admin`".

A humble suggestion would be to add a check to the Filament `RouteServiceProvider`. 

Like 
```
// if route exists
// throw an error to console
// else 
// register the routes to the app...
```

Guess others might have an existing admin route when installing the package.

**Comment by ariustigger** [comment]
how did you solve that, I already got installed nova now I want also to add filament...? thanks in advance

**Comment by knowsarzehmeh** [comment]
> how did you solve that, I already got installed nova now I want also to add filament...? thanks in advance

i'm just digging into filament and i ran into the same issue, filament path conflicts with what i have in nova config, so i will suggest you change nova.path in config to something different from what filament uses or change the filament.path in the config too

**Comment by ivnlabs** [comment]
check this link https://laracasts.com/discuss/channels/code-review/install-nova-and-filament

**Comment by nurMangg** [comment]
if you using linux php, you can install :
im using Fedora :
sudo dnf install php-intl

Linux apt :
sudo apt-get install php-intl

and try install filament laravel again :
composer require filament/actions:"^3.2" -W

its worked for me
php 8.2.18
laravel 11
OS Linux Fedora 39
