### ISSUE TITLE
I get an error where executing php artisan make:filament-user 

### ISSUE THREAD

**Issue by abdelhamiderrahmouni** [laravel-filament/filament#6567]
### Package

filament/filament

### Package Version

v3.0.0-alpha100

### Laravel Version

9.52.7

### Livewire Version

v2.10.7

### PHP Version

8.1

### Problem description

I get ``` Call to a member function auth() on null ```
![Screenshot 2023-05-19 192627](https://github.com/filamentphp/filament/assets/26693672/7cd84c65-3f36-4874-9c8e-7907f71257d2)

### Expected behavior

it should create a filament user

### Steps to reproduce

require the latest alpha version and run ``` php artisan make:filament-user ```

### Reproduction repository

https://github.com/abdelhamiderrahmouni/filament-v3

### Relevant log output

```shell
Call to a member function auth() on null

  at vendor/filament/filament/src/FilamentManager.php:44
     40▕     protected ?Model $tenant = null;
     41▕
     42▕     public function auth(): Guard
     43▕     {
  ➜  44▕         return $this->getCurrentContext()->auth();
     45▕     }
     46▕
     47▕     public function bootCurrentContext(): void
     48▕     {

      +19 vendor frames
  20  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()
```

**Comment by danharrin** [comment]
I can't reproduce this. Also, Filament v3 is not ready for use, please stick to v2 as we do not have the resources to support everyone using an unreleased verison.
