### ISSUE TITLE
Inline Radio Issue

### ISSUE THREAD

**Issue by andrewdwallo** [laravel-filament/filament#6618]
### Package

filament/filament

### Package Version

v2.17.43

### Laravel Version

v10.12.0

### Livewire Version

v2.12.3

### PHP Version

PHP 8.1

### Inline Radio's do not work.

**Example: Inline as of right now**
![Screenshot 2023-05-25 191040](https://github.com/filamentphp/filament/assets/104294090/0f112a0e-787e-4ff5-b7f4-2290024fdd9c)

**Example: Not Inline**
![Screenshot 2023-05-25 192134](https://github.com/filamentphp/filament/assets/104294090/3c2e7866-59bc-45b0-8faa-39fa7cc9e34e)

### Expected behavior is to be inline when `inline()` method is used.

**Expected behavior (Straight from Filament website):**

![Screenshot 2023-05-25 192613](https://github.com/filamentphp/filament/assets/104294090/576ce179-dc90-4d7c-a377-08982ac997dc)

### Steps to reproduce

Step 1: Download reproduction repository.
Step 2: Create user and sign in.
Step 3: Go to "Users" Page in Navigation.
Step 4: Click to create a new User.
- You will then notice that the inline Radio does not look like it is supposed to in the form.

If you are supposed to also use the `->columns()` method/option (even though it does not say to in documentation), it does not work like it is supposed to either way.

**In Form:**
```
Forms\Components\Radio::make('role')
                    ->boolean() // or use ->options(...)
                    ->inline()
                    ->required(),
```

### Reproduction repository

https://github.com/andrewdwallo/filamenttest

**Comment by andrewdwallo** [comment]
Please reopen. This issue needs to be fixed please. I have provided all the information necessary to reproduce the issue.

**Comment by valpuia** [comment]
It's working fine..

Edited: Our version is same (v2.17.43)

![Screenshot from 2023-05-26 17-01-02](https://github.com/filamentphp/filament/assets/28250303/b6abccab-c5ab-4305-8ae1-41e3560cb20b)
![Screenshot from 2023-05-26 17-00-46](https://github.com/filamentphp/filament/assets/28250303/d8dc8d6d-06b1-4fab-95b6-a4fbc3192bef)

**Comment by andrewdwallo** [comment]
I literally used the same repo I posted above, it was on the latest version so I don't understand...

**Comment by andrewdwallo** [comment]
Does it show 1 column for 2 options?

**Comment by valpuia** [comment]
> Does it show 1 column for 2 options?

Same result if it's 2, 3, or more

**Comment by valpuia** [comment]
Hi, this is coming If you use layout card with Inline label [https://filamentphp.com/docs/2.x/forms/layout#inline-labels](https://filamentphp.com/docs/2.x/forms/layout#inline-labels)

![Screenshot from 2023-05-26 17-16-23](https://github.com/filamentphp/filament/assets/28250303/9129ecf3-7ad6-4aec-9f93-2bdea7307ee3)
![Screenshot from 2023-05-26 17-16-01](https://github.com/filamentphp/filament/assets/28250303/6ad0c0fa-f59b-47ac-877d-3ee6fb5fee57)

**Comment by andrewdwallo** [comment]
I didn't use that though. I used the same thing in the reproduction repo I posted in this issue.

**Comment by valpuia** [comment]
> I didn't use that though. I used the same thing in the reproduction repo I posted in this issue.

I don't have any idea then.. let's wait for the core team helps

**Comment by andrewdwallo** [comment]
Alright, yeah I'm very confused.

**Comment by andrewdwallo** [comment]
Apologies... just confirmed that it was the browser that was causing the issue. I was using Microsoft Edge Dev. Could be the cache from a previous version or a development flag set for the browser. Either way, it seems that this issue does not exist in the correct browser version. Thanks for your time.
