### ISSUE TITLE
missing php vendor files and node_modules in dockerfile buiding process

### ISSUE THREAD

**Issue by MMTE** [laravel-filament/filament#6639]
### Package

filament/filament

### Package Version

v2.0.0

### Laravel Version

v10.0.0

### Livewire Version

V2.10.7

### PHP Version

PHP 8.1.17

### Problem description

as it's been mentioned in documentations, user can make custom themes using [building themes process](https://filamentphp.com/docs/2.x/admin/appearance#building-themes)

this process is fine if you have already built the vite manifest. but when there isn't vite manifest and we install PHP vendors for example using `composer install`, then we would have the error mentioning that we should build the vite files first:

   ```
Exception 

  Vite manifest not found at: /home/mahdi/freelance-projects/pro/behdasht-backend/public/build/manifest.json

  at vendor/laravel/framework/src/Illuminate/Foundation/Vite.php:684
    680▕         $path = $this->manifestPath($buildDirectory);
    681▕ 
    682▕         if (! isset(static::$manifests[$path])) {
    683▕             if (! is_file($path)) {
  ➜ 684▕                 throw new Exception("Vite manifest not found at: {$path}");
    685▕             }
    686▕ 
    687▕             static::$manifests[$path] = json_decode(file_get_contents($path), true);
    688▕         }

  Start the development server: Run `npm run dev` in your terminal and refresh the page. 
  https://laravel.com/docs/9.x/vite#running-vite


```

on the other hand when you want to build the vite files the filament.css file refers to default filament CSS file in the vendor which isn't installed yet. for example:
```
@import '../../vendor/filament/filament/resources/css/app.css';

@tailwind base;
@tailwind components;
@tailwind utilities;
```

this isn't major problem if you are working on localhost or a VPS but it makes an chicken-egg problem in dockerfiles. 

AppServiceProvider: 
`Filament::registerViteTheme('resources/css/filament.css');`

vite.config.js:
```
import { defineConfig } from 'vite'
import laravel, { refreshPaths } from 'laravel-vite-plugin'

export default defineConfig({
    plugins: [
        laravel({
            input: [
                'resources/css/filament.css',
                'resources/css/app.css',
                'resources/js/app.js'
            ],
            refresh: [...refreshPaths, 'app/Http/Livewire/**'],
        }),
    ],
})

```

### Expected behavior

We have a dependency between the frontend and the backend. so if I'm going to build a project with a docker file using different docker images for the front and back, I would need to solve this dependency.

for example, I have to install filament in a separate php-fpm docker image and then copy the vendor's file in a node docker image and then I build vite files and then I've to copy /public/build folder to the php-fpm image. then I need to install other npm packages and so on...

or maybe we need to prevent running  `registerViteTheme` function in the service provider when the composer is running to install packages.

I'm not trying to split hairs here but there is something missing or I'm doing something wrong. 

### Steps to reproduce

- install a new Laravel project
- install filament
- create a custom theme using [the process](https://filamentphp.com/docs/2.x/admin/appearance#building-themes)
- add a custom filament file to the service provider. for example:
```
// AppServiceProvider 
Filament::registerViteTheme('resources/css/filament.css');t
```
- remove the vendors folder (maybe unnecessary, I don't know) 
- install composer packages 

### Reproduction repository

https://github.com/MMTE/filamentphp-custom-theme

**Comment by danharrin** [comment]
Use `composer install --no-scripts` so it doesn't attempt to run any service providers. IMO, this really isn't a problem with Filament that we can fix.
