### ISSUE TITLE
Dark mode: searchable select 

### ISSUE THREAD

**Issue by alvarezrrj** [laravel-filament/filament#6647]
### Package

filament/forms

### Package Version

v2.17.44

### Laravel Version

v10.13.0

### Livewire Version

v2.12.3

### PHP Version

PHP 8.1.2

### Problem description

Hi everyone 👋, thank you for an awesome package, it has come in real handy lately.

I've recently found that the Select component doesn't seem to behave as expected regarding dark mode:
When adding the `searchable()` option to a Select component, the `dark:` tailwind classes disappear and the component becomes light.

### Expected behavior

I suppose the component should keep on respecting dark mode even when it's searchable?

### Steps to reproduce

- Install Filament on a fresh Laravel app
- Publish configuration
- Set `'dark_mode' => true`
- Create a Livewire component
- Create a Filament Select component in it
- Visit your page (in dark mode) to see a dark Select component
- Go back to your livewire file and make the Select `searchable()`
- The Select component is now light (inspecting the page shows all `dark:` classes are gone)

### Reproduction repository

https://github.com/alvarezrrj/filament-select-issue

**Comment by danharrin** [comment]
At the moment, we only support Tailwind configurations with `darkMode: 'class'` (I think its in the installation docs?). Then, ensure that the `dark` class is added to `<body>` when dark mode is enabled. Let me know if you have any other problems.

**Comment by alvarezrrj** [comment]
> At the moment, we only support Tailwind configurations with `darkMode: 'class'` (I think its in the installation docs?). Then, ensure that the `dark` class is added to `<body>` when dark mode is enabled. Let me know if you have any other problems.

Ok I see, now it works. I couldn't find anything about adding the `dark` class to the `&lt;body&gt;` in the docs. Or maybe it's something one is expected to know but I'm only a rookie. 

Thanks  again.
