### ISSUE TITLE
Spaces in model labels when using capitals

### ISSUE THREAD

**Issue by arne-s** [laravel-filament/filament#6669]
### Package

filament/filament

### Package Version

v2.17.44

### Laravel Version

v10.13.0

### Livewire Version

v2.12.3

### PHP Version

PHP 8.1.19

### Problem description

When setting the `$modelLabel` or `$label` in the model resource to a string with multiple capital letters, the outputted string used in <title> and the breadcrumbs has additional spaces. 

### Expected behavior

The output should not have any spaces that were not specified in the $modelLabel or $label string. 

### Steps to reproduce

In a model resource (e.g. `UserResource`) specify the `$modelLabel` as follows:

`protected static ?string $modelLabel = "ZZP'er";`

When viewing the overview page, on several places there are spaces inserted, for example the title:

`<title>Z Z P&#039;ers -  MySiteName</title>`

And the page title: 

```
<h1 class="filament-header-heading text-2xl font-bold tracking-tight">
    Z Z P'ers
</h1>
```

### Reproduction repository

https://github.com/arne-s/filamentphp-demo-mini

**Comment by danharrin** [comment]
Unfortunately this is just the behaviour of Laravel's string helper for generating titles. Everything is customisable though, the docs explain how to override things like the page title or heading, or navigation item

**Comment by arne-s** [comment]
Are you sure?  `Str::title("ZZP'er");` returns `"Zzp'er"` on my system.

**Comment by danharrin** [comment]
We use `Str::headline()`, as `Str::title()` destroys the casing

**Comment by arne-s** [comment]
Ok, thanks for looking into it, you may close this issue. I'll figure out how to use a different method. 👍
