### ISSUE TITLE
Infinite loop with FileUpload `multiple=true` and `panelLayout=integrated`

### ISSUE THREAD

**Issue by adevade** [laravel-filament/filament#6674]
### Package

filament/forms

### Package Version

v2.17.44

### Laravel Version

v10.13.0

### Livewire Version

v2.12.3

### PHP Version

PHP 8.1.9

### Problem description

When a `FileUpload` component has `->multiple(true)` and `->panelLayout('integrated')` the page grows taller and taller infinitely.

https://github.com/filamentphp/filament/assets/1066486/5431e053-c434-4453-93c1-da987257eed7

### Expected behavior

I expect it to work like when the `panelLayout` is set to `compact` or `circle`.

### Steps to reproduce

Try to upload one or more files to the last field in the demo repo. The first two fields are working as expected.

### Reproduction repository

https://github.com/adevade/filament-file-upload-bug

### Additional info

I'm using Edge on Windows 11. Same bug is happening in latest Firefox as well, though.

**Comment by awcodes** [comment]
Multiple can't be used with 'integrated'. This is a limitation in FilePond.

[https://github.com/pqina/filepond/issues/389](https://github.com/pqina/filepond/issues/389)

**Comment by nikans** [comment]
Maybe it should be documented [here](https://pqina.nl/filepond/docs/api/instance/properties/#disabling-credits) or somewhere else...
