### ISSUE TITLE
Broken tag : `v2.17.44`

### ISSUE THREAD

**Issue by tgeorgel** [laravel-filament/filament#6684]
### Package

filament/tables

### Package Version

v2.17.33

### Laravel Version

v10.13.1

### Livewire Version

v2.12.3

### PHP Version

PHP 8.2.6

### Problem description

Hi there ! 

I think that the [filament/forms @ v2.17.33](https://github.com/filamentphp/tables/releases/tag/v2.17.33) tag is broken as it seems to include this particular commit extracted from `v3.x` : https://github.com/filamentphp/tables/commit/fe91e2668dce4e5581a7d751a8ee25f1b53443e9

Issue : When trying to create a BadgeColumn using the `enum()` method, it throws `Filament\Tables\Columns\BadgeColumn::enum does not exist.` as it has been removed in v3.

Code : 
```
Columns\BadgeColumn::make('type')
                ->enum(['foo' => 'Bar']),
```
```
Columns\TextColumn::make('type')
                ->enum(['foo' => 'Bar'])
                ->badge(),
```

Exception : 
![screenshot 2023-06-03 à 20 40 52](https://github.com/filamentphp/filament/assets/11785727/6e963c8b-5e4a-4ccf-a34d-f6de49ca80d7)

It seems to have taken this version as I'm using `blade-ui-kit/blade-heroicons:^2.1`

### Expected behavior

To have the code base following the actual v2 documentation.

### Steps to reproduce

Require the package at this version : 

```
composer require filament/tables:"v2.17.33"
```

Try to use a BadgeColumn with `enum()` method on a Table : 

```
Columns\BadgeColumn::make('type')
                ->enum(['foo' => 'Bar']),
```

### Reproduction repository

https://github.com

**Comment by danharrin** [comment]
Yeah we have been aware and are actively trying to get that release off of Packagist. We have many other releases to choose from though, you don't need to use .33 😉 You will have to downgrade Heroicons, sorry

**Comment by tgeorgel** [comment]
Hey, I'm glad you are aware 👍
Yup lot of release to pick from, just wanted to let you know. Thanks a lot!

**Comment by danharrin** [comment]
Since we released we have been deleting the tag off Packagist, but each time we release again it is back. Probably a bug on their end
