### ISSUE TITLE
Bulkaction has no loading indicator

### ISSUE THREAD

**Issue by kyrill71** [laravel-filament/filament#6689]
### Package

filament/tables

### Package Version

V2.17.44

### Laravel Version

v10.13.0

### Livewire Version

v2.12.3

### PHP Version

PHP 8.2.0

### Problem description

There is no loading indicator when someone clicks on a bulk action. So the user need to wait until the popup of the bulkactions shows up. But without any feedback to the user that something is loading, the user doesn't know that it is loading.

### Expected behavior

There should be a loading indicator that provides feedback to the user that the bulk action is loading. So the user knows that something is loading and then the popup of the bulkaction shows up.

#### Setup

1. `git clone git@github.com:kyrill71/no_loading_indicator_bulkaction.git`
2. ` cd no_loading_indicator_bulkaction`
3. ` composer install`
4. make a user with: `php artisan make:filament-user`
5. Login at http://127.0.0.1:8000/admin/users

#### Reproduction

1. Click "Users" in navigation.
2. Select the checkbox before the username.
3. click on the 3 dots( bulkactions) and select the 'Edit selected'.

### Reproduction repository

https://github.com/kyrill71/no_loading_indicator_bulkaction

**Comment by fabianosfbr** [comment]
Hi, 
I had the same problem, I made this hack to show user feedback something was running

File: vendor/filament/tables/resources/views/actions/bulk-action.blade.php

`<x-tables::dropdown.list.item
    :x-on:click="'mountBulkAction(\'' . $getName() . '\')'"
    :icon="$getIcon()"
    **wire:loading.attr="disabled"
    wire:loading.class="cursor-wait opacity-70"**
    :color="$getColor()"
    :attributes="\Filament\Support\prepare_inherited_attributes($getExtraAttributeBag())"
    class="filament-tables-bulk-action"
>
    {{ $getLabel() }}
</x-tables::dropdown.list.item>`

**Comment by magarrent** [comment]
Nice and easy option from @fabianosfbr ! Just tried and it works.

In my case, I have to download multiple files using the bulk action, and there is no available "loading" state to use it (I think)

**Comment by danharrin** [comment]
Fixed in v3
