### ISSUE TITLE
Wizard field bug when pressing next

### ISSUE THREAD

**Issue by romaldyminaya** [laravel-filament/filament#6703]
### Package

filament/forms

### Package Version

v2.17.14

### Laravel Version

v9.52.4

### Livewire Version

v2.12.3

### PHP Version

PHP 8.1.12

### Problem description

When using the Wizard and steps fields in a filament page, when passing to the next step, a javascript error appears. The next step is displayed but when the next step has a Select with searchable option enabled, it doesnt works propperty.

![image](https://github.com/filamentphp/filament/assets/2809147/4ead4e80-615d-4bc5-868e-0dc9d6f646d5)

### Expected behavior

To not throw an exception and display the select field accordingly.

### Steps to reproduce

Visit the settings page in the next link http://127.0.0.1:8000/settings-page

populate the required fields with random data and press next.

### Reproduction repository

https://github.com/romaldyminaya/demo

**Comment by petrisorcraciun** [comment]
try to set a state for form and add 'nif' with null value. :) or add public .. $nif = null;

public array $data = [ 'nif' => null ];

protected function getFormStatePath(): string 
{
    return 'data';
}

**Comment by danharrin** [comment]
Can you please test if this is an issue with v3 beta? Thanks!

**Comment by zepfietje** [comment]
@romaldyminaya @petrisorcraciun, since it's been a month without activity on this issue, could both of you test if this bug still occurs on the latest version of v3?
