### ISSUE TITLE
directory() method when chaining on SpatieMediaLibraryFileUpload does not work

### ISSUE THREAD

**Issue by joshembling** [laravel-filament/filament#6708]
### Package

filament/filament

### Package Version

v2

### Laravel Version

v9

### PHP Version

PHP 8.1

### Problem description

According to the docs, you should be able to do something like this, to upload to a subdir within a bucket of S3. 

```
SpatieMediaLibraryFileUpload::make('image')
      ->disk('s3')
      ->directory('images')
```

Instead, it adds the record to the media table, uploads to the S3 bucket but ignores the directory method. Even if you manually create the directory in the bucket, it still ignores it and uploads in the numeric folder fashion e.g. 24/, 25/, /26 etc. (matching the id)

In the same way using FileUpload, this method works and uploads to the correct subdir:

```
FileUpload::make('image')
      ->disk('s3')
      ->directory('images')
```

This seems to be an ongoing issue that has been present since last year. 
See: https://stackoverflow.com/questions/73753284/directory-method-of-filament-doesnt-work

### Expected behavior

To upload files to an S3 bucket within a sub directory using SpatieMediaLibraryFileUpload, much like the FileUpload component already does. 

### Steps to reproduce

Set up an S3 bucket with your credentials and try this form component:

```
SpatieMediaLibraryFileUpload::make('image')
      ->disk('s3')
      ->directory('images')
```

### Reproduction repository

https://github.com/joshembling/filament-image-bug

**Comment by danharrin** [comment]
This is not a problem with Filament, Spatie does not natively support changing the directory of the image. You must create a custom PathGenerator https://spatie.be/docs/laravel-medialibrary/v10/advanced-usage/using-a-custom-directory-structure
