### ISSUE TITLE
Unique validation fails but database record added

### ISSUE THREAD

**Issue by therezor** [laravel-filament/filament#6740]
### Package

filament/filament

### Package Version

2.17.46

### Laravel Version

10.13.5

### Livewire Version

2.12.3

### PHP Version

8.2

### Problem description

Fill form and press create, and has validation error "The slug has already been taken." but model and related models are created
```
   ->relationship('path')
            ->schema([
                Forms\Components\TextInput::make('slug')
                    ->label(__('attributes.slug'))
                    ->required()
                    ->maxLength(255)
                    ->unique(Path::class, 'slug', ignoreRecord: true),
```

### Expected behavior

No validation error expected, redirect to edit page.

### Steps to reproduce

Create form with relationship.
Make field unique.

### Reproduction repository

https://github.com/recca0120/filament-bug

**Comment by therezor** [comment]
Related to https://github.com/filamentphp/filament/issues/6258

**Comment by danharrin** [comment]
Hi, I've just upgraded the repository to v3. The error seems to go away when you add `ignoreRecord: true`

https://github.com/filamentphp/filament/assets/41773797/18db4041-2f3e-4572-a03c-0f9d9af16a5a
