### ISSUE TITLE
Modal overlay covers modal scrollbar in Firefox 114 on Windows 10

### ISSUE THREAD

**Issue by freshleafmedia** [laravel-filament/filament#6773]
### Package

filament/filament

### Package Version

v2.17.43

### Laravel Version

v9.52.7

### PHP Version

PHP 8.1.20

### Problem description

On Firefox 114 on Windows 10, if a modal that's taller than the browser window is active, the scrollbar is covered by the modal overlay, making it inaccessible. Using the scroll-wheel continues to work.

![Screenshot of an active modal in the Filament demo instance where the modal scrollbar is covered by the modal overlay](https://github.com/filamentphp/filament/assets/10062339/500f2a14-7c3c-45f9-ac02-ece4c1e6b11a)

### Expected behavior

Modals that are taller than the browser window can be scrolled using the scrollbar.

### Steps to reproduce

1. In Firefox 114 on Windows 10, visit the [Filament demo instance](https://demo.filamentphp.com).
2. [Find a page with a modal](https://demo.filamentphp.com/shop/categories/1/edit?activeRelationManager=0), activate it, and resize the browser window so that it is smaller than the modal.

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by zepfietje** [comment]
Essentially same thing on macOS Safari, even though the scrollbar isn't persistent.
Will look into this for v3.

**Comment by zepfietje** [comment]
I haven't found a way to make this work, so feel free to create a pull request if you know how to fix it. Since it's not a major bug, I'm keeping this issue closed.
