### ISSUE TITLE
Replacing an image via drag-and-drop not working correctly

### ISSUE THREAD

**Issue by arjendejong12** [laravel-filament/filament#6775]
### Package

filament/filament

### Package Version

v2.17.48

### Laravel Version

v10.13.5

### PHP Version

PHP 8.2.7

### Problem description

When dragging an image into an image field with an existing image, the image gets replaced and afterwards the fields get emptied.

https://github.com/filamentphp/filament/assets/10572554/0440c885-a038-4021-b532-8f6b820d2c30

### Expected behavior

The image should be correctly replaced.

### Steps to reproduce

1. Create a post in the Post resource, with an image inserted in the thumbnail field.
2. Drag another image in the thumbnail field.

### Reproduction repository

https://github.com/arjendejong12/filament-repo

**Comment by romansh** [comment]
Can confirmed that. Don't know is this behaviour important in real life, but I have reproduced that.

**Comment by danharrin** [comment]
Issue with FilePond: pqina/filepond#544

I've disabled the "replace" functionality to prevent loss of the original file.

**Comment by danharrin** [comment]
Reverted my fix as it breaks the image editor. FilePond is too buggy for me to fix this. If you'd like to see it fixed, please open an issue with FilePond. There isn't much we can do on the Filament side.

**Comment by arjendejong12** [comment]
Thanks Dan, I will open an issue at FIlePond.

**Comment by KhairulAzmi21** [comment]
> Thanks Dan, I will open an issue at FIlePond.

Hi @arjendejong12 , did you find solution for this ?

**Comment by LemarinelNet** [comment]
That issue is still present. 
Has anyone found a workaround ?

**Comment by asusenko** [comment]
> That issue is still present. Has anyone found a workaround ?

I'm working on this at the moment, but still have no solution.
