### ISSUE TITLE
Loosing focus of the selected item from the side menu.

### ISSUE THREAD

**Issue by ibrahimBougaoua** [laravel-filament/filament#6779]
### Package

filament/filament

### Package Version

v2.17.46

### Laravel Version

v10.13.5

### PHP Version

8.1

### Problem description

The issue even appears whene reloading the page with f5 or refreshing the page in general via any means ( opening a new page , clicking on a button which lunch an event .... etc ) it would allways reset the side menu view to the top of the list which loses focus on the selected item from the list . It will be still selected but the view will be set to the top of the list.

### Expected behavior

Keep the side menu view at the same spot of the selected item from the list.

You found ezzi-resto.sql in database folder.

user/pass : ibrahim@gmail.com/ibrahim@gmail.com

### Steps to reproduce

The issue occurs whene there is enough elements on the side menu so wene the view change we can notice it .

### Reproduction repository

https://github.com/ibrahimBougaoua/ezzi-resto

**Comment by ibrahimBougaoua** [comment]
![](https://raw.githubusercontent.com/ibrahimBougaoua/ezzi-resto/main/public/issue.gif)

**Comment by zepfietje** [comment]
This isn't really a bug to be honest, it's just a page reload.
I believe this has been brought up before, but it's hard to fix in a nice way.
You can however implement a solution in your own project if you like to automatically scroll down to the current page in the sidebar on page load.

Potentially Livewire v3 will solve this with `wire:navigate`.
So closing this issue for now.

**Comment by ibrahimBougaoua** [comment]
> This isn't really a bug to be honest, it's just a page reload. I believe this has been brought up before, but it's hard to fix in a nice way. You can however implement a solution in your own project if you like to automatically scroll down to the current page in the sidebar on page load.
> 
> Potentially Livewire v3 will solve this with `wire:navigate`. So closing this issue for now.

It would be considered as ui or ux issue since if the user had a long liste of element as i did he will each time loose the track of the element selected. And from another point of view every major library had fixed this issue so it's considered as a major thing to have implemented.
