### ISSUE TITLE
Design review

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#6787]

**Comment by zepfietje** [comment]
@danharrin, what are the `action-container.blade.php` views for?
It's unclear to me as `packages/actions/resources/views/components/actions.blade.php` already filters out hidden actions.

**Comment by danharrin** [comment]
Essentially it wraps an action class as a form component class so it can be rendered like any other form component as part of a schema

**Comment by danharrin** [comment]
Required for UI (IMO)

## Tables

- [ ] `tables/resources/views/components/cell.blade.php`
- [ ] `tables/resources/views/components/checkbox/cell.blade.php`
- [ ] `tables/resources/views/components/checkbox/index.blade.php`
- [ ] `tables/resources/views/components/empty-state/description.blade.php`
- [ ] `tables/resources/views/components/empty-state/heading.blade.php`
- [ ] `tables/resources/views/components/empty-state/index.blade.php`
- [ ] `tables/resources/views/components/header-cell.blade.php`
- [ ] `tables/resources/views/components/header/description.blade.php`
- [ ] `tables/resources/views/components/header/heading.blade.php`
- [ ] `tables/resources/views/components/header/index.blade.php`
- [ ] `tables/resources/views/components/loading-cell.blade.php`
- [ ] `tables/resources/views/components/pagination/index.blade.php`
- [ ] `tables/resources/views/components/pagination/item.blade.php`
- [ ] `tables/resources/views/components/pagination/records-per-page-selector.blade.php`
- [ ] `tables/resources/views/components/row.blade.php`
- [ ] `tables/resources/views/components/table.blade.php`
