### ISSUE TITLE
getOptionLabelFromRecordUsing requires titleColumnName

### ISSUE THREAD

**Issue by francoism90** [laravel-filament/filament#6789]
### Package

filament/filament

### Package Version

2.17.48

### Laravel Version

10.13.5

### Livewire Version

2.12.3

### PHP Version

8.1

### Problem description

The given example doesn't work: https://filamentphp.com/docs/2.x/forms/fields#handling-morphto-relationships

This does not work (`titleColumnName` must be set - and `name` is a dynamic model attribute):
```php
MorphToSelect\Type::make(User::class)
    ->getOptionLabelFromRecordUsing(fn (User $record): string => $record->name)
```

However the following workaround works (the attribute needs to exists on the database):
```php
MorphToSelect\Type::make(User::class)
    ->getOptionLabelFromRecordUsing(fn (User $record): string => $record->name)
    ->titleColumnName('email'),
```

### Expected behavior

No need to give `titleColumnName`, as it should be overwritten by `getOptionLabelFromRecordUsing`.

### Steps to reproduce

```php
use Filament\Forms\Components\MorphToSelect;
 
MorphToSelect::make('commentable')
    ->types([
        MorphToSelect\Type::make(Product::class)
            ->getOptionLabelFromRecordUsing(fn (Product $record): string => "{$record->name} - {$record->slug}"),
        MorphToSelect\Type::make(Post::class)->titleColumnName('title'),
    ])
```

### Reproduction repository

https://github.com/francoism90/filament

### Relevant log output

```shell
MorphToSelect type [App\Models\User] must have a [titleColumnName()] set.
```

**Comment by nessimabadi** [comment]
Can confirm the same thing.

Copied and adapted the code on the example and received the same output error

**Comment by zepfietje** [comment]
Please provide a real reproduction repository, @francoism90.

**Comment by francoism90** [comment]
@zepfietje Sorry, I'll provide a reproduction repository next time. :)

I think this is by design.

**Comment by nessimabadi** [comment]
Hi @zepfietje 

I created a demo repository that reproduces the error.

https://github.com/nessimabadi/filament-demo-repository

If a change is needed let me know.

Thanks for this amazing package

**Comment by nessimabadi** [comment]
HI @zepfietje 

FYI, Upgraded to V3 and the bug is already fixed

Thanks

**Comment by zepfietje** [comment]
Thanks for getting back on this, @nessimabadi!
@danharrin can decide if this should be closed.
