### ISSUE TITLE
Native Notification API from browser not usable

### ISSUE THREAD

**Issue by glamorous** [laravel-filament/filament#6831]
### Package

filament/notifications

### Package Version

v2.17.38

### Laravel Version

10.9.0

### PHP Version

PHP 8.2

### Problem description

window.Notification (native functionality) is overriden by Filament

### Expected behavior

To be able to use window.Notification native API without it been overwritten by Filament.

### Steps to reproduce

Run Notification.permission in your console. Normally it should say "default", "granted" or "denied" but it show "undefined" because it doesn't exists anymore

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by zepfietje** [comment]
Thanks for reporting, @glamorous.

CC: @danharrin, this is something we need to look into.

**Comment by glamorous** [comment]
My current workaround is to store the native window.Notification inside another variable and this way I can access the native Notification API

**Comment by danharrin** [comment]
I didn't realise it was reserved, we will just move it to window.FilamentNotification in v3.

**Comment by danharrin** [comment]
I didn't realise it was reserved, we will just move it to window.FilamentNotification in v3.

**Comment by danharrin** [comment]
Fixed in v3.
