### ISSUE TITLE
Issue encountered when performing actions with relations

### ISSUE THREAD

**Issue by AnassGBNL** [laravel-filament/filament#6858]
### Package

filament/filament

### Package Version

v2.17.49

### Laravel Version

v10.13.5

### Livewire Version

v2.12.3

### PHP Version

PHP 8.1.11

### Problem
Every time I try to perform an action with a relation, I encounter the same error. I have been trying to solve it on my own for a few days now, but I haven't found a solution yet.

### Error Message
The strange thing is that I can attach a relation, but when I attempt to edit or detach it, I receive the following error message:

```
Filament\Resources\RelationManagers\RelationManager::getTableRecordTitle(): Argument #1 ($record) must be of type Illuminate\Database\Eloquent\Model, null given, called in /Users/{{$user}}/Sites/{{$project}}/vendor/filament/tables/src/Actions/Action.php on line 89
```

### Research Done
I have searched online and checked the documentation, but I couldn't find anyone else experiencing the same problem or any relevant information. The Filament documentation is also very vague regarding this issue.

### Steps to reproduce

To reproduce the issue, follow these steps:

1. Consider a scenario where I have a single user who belongs to a Company class.
2. The Company class should be associated with multiple other classes, such as teams, orders, invoices, etc.
3. Here is how I have set up my relations:

```php
class User extends Authenticatable implements FilamentUser
{
    public function companies(): BelongsTo
    {
        return $this->belongsTo(Company::class, 'companies_id', 'id');
    }
}
```

```php
class Company extends Model
{
    public function users(): HasMany
    {
        return $this->hasMany(User::class, 'companies_id');
    }
}
```

4. Perform an action that involves editing or detaching the relation.

Please note that the Filament documentation is not providing clear guidance on resolving this issue.

### Reproduction repository

i run my project local

https://github.com/filamentphp/panels

### Relevant log output

```shell
Filament\Resources\RelationManagers\RelationManager::getTableRecordTitle(): Argument #1 ($record) must be of type Illuminate\Database\Eloquent\Model, null given, called in /Users/{{$user}}/Sites/{{$project}}/vendor/filament/tables/src/Actions/Action.php on line 89
```

**Comment by AnassGBNL** [comment]
Hi everyone,

I understand the importance of providing code samples for troubleshooting purposes, but I'm unable to share the source code of my SaaS application due to confidentiality reasons. I have already tried running the code locally to reproduce the issue, but I'm still encountering the error mentioned above.

I appreciate any guidance or suggestions that can help me resolve the issue without sharing the source code.

Thank you for your understanding.

**Comment by zepfietje** [comment]
> **Please do not link to your actual project**, what we need instead is a _minimal_ reproduction in a fresh project without any unnecessary code. This means it doesn't matter if your real project is private / confidential, since we want a link to a separate, isolated reproduction.

**Comment by godlikeAlex** [comment]
@zepfietje Hello, I have same problem, but only with RestoreAction, RestoreBulkAction works perfectly :)

Filament Relation:
```
class AddonsRelationManager extends RelationManager
{
  protected static string $relationship = "addons";

  protected static ?string $recordTitleAttribute = "title";

  public static function form(Form $form): Form
  {
    return $form->schema([
      Forms\Components\TextInput::make("title")
        ->required()
        ->maxLength(255),
      Forms\Components\TextInput::make("condition")
        ->required()
        ->maxLength(255),
      Forms\Components\Toggle::make("with_qty")
        ->required()
        ->label("This addon will be with Quantity?"),
    ]);
  }

  public static function table(Table $table): Table
  {
    return $table
      ->columns([Tables\Columns\TextColumn::make("title")])
      ->filters([Tables\Filters\TrashedFilter::make()])
      ->headerActions([Tables\Actions\CreateAction::make()])
      ->actions([
        Tables\Actions\EditAction::make(),
        Tables\Actions\DeleteAction::make(),
        Tables\Actions\ForceDeleteAction::make(),
        Tables\Actions\RestoreAction::make(),
      ])
      ->bulkActions([
        Tables\Actions\DeleteBulkAction::make(),
        Tables\Actions\RestoreBulkAction::make(),
        Tables\Actions\ForceDeleteBulkAction::make(),
      ]);
  }

  protected function getTableQuery(): Builder
  {
    return parent::getTableQuery()->withoutGlobalScopes([
      SoftDeletingScope::class,
    ]);
  }
}
```

Product model:

```
class Product extends Model
{
  use HasFactory, SoftDeletes;

  public function addons()
  {
    return $this->belongsToMany(
      ProductAddons::class,
      "product_product_addon",
      "product_id",
      "product_addon_id"
    );
  }  
}
```

ProductAddon Model:
```

<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\SoftDeletes;

class ProductAddons extends Model
{
  use HasFactory, SoftDeletes;

  protected $guarded = [];

  public function addons()
  {
    return $this->belongsToMany(
      Product::class,
      "product_product_addon",
      "product_addon_id",
      "product_id"
    );
  }
}

```

**Comment by zepfietje** [comment]
Please open an issue following the bug report template including a complete but minimal reproduction repository, @godlikeAlex. Then we can look into your issue.

**Comment by Lluisma** [comment]
Hi, @AnassGBNL 

I got this message because the related class (in your case the `Company` class) had an string type identifier field and I forgot to define it in its Model (`protected $keyType = 'string'; `).

Hope it can helps you.
