### ISSUE TITLE
Memory allocation error

### ISSUE THREAD

**Issue by aurawindsurfing** [laravel-filament/filament#6863]
### Package

filament/filament

### Package Version

v2.17

### Laravel Version

v10.0

### PHP Version

PHP 8.2

### Problem description

One of columns on my table is json and consists of base64 encoded pdf's

While this is clearly MYSQL error It would be good to specify which columns need to be loaded with the query:

SQLSTATE[HY001]: Memory allocation error: 1038 Out of sort memory, consider increasing server sort buffer size

```
select
  *
from
  `orders`
where
  (
    exists (
      select
        *
      from
        `patients`
      where
        `orders`.`patient_id` = `patients`.`id`
        and `name` like % j %
    )
    or exists (
      select
        *
      from
        `patients`
      where
        `orders`.`patient_id` = `patients`.`id`
        and `surname` like % j %
    )
  )
order by
  `created_at` desc
limit
  50 offset 0
```

### Expected behavior

Ability to dynamically load only columns present in the table schema

### Steps to reproduce

create json with base64 encoded files

### Reproduction repository

https://github.com/aurawindsurfing/filament

**Comment by aurawindsurfing** [comment]
workaround for the moment is to increase buffer limit:

```
[mysqld]
sort_buffer_size=2048k
```

**Comment by zepfietje** [comment]
Please provide a real reproduction repository.

**Comment by aurawindsurfing** [comment]
Its private ;-)

**Comment by zepfietje** [comment]
Please read the comment: https://github.com/filamentphp/filament/issues/6863#issuecomment-1610999898.

**Comment by danharrin** [comment]
Also, this isnt a Filament issue, if your DB is out of memory due to your data theres nothing we can do

**Comment by aurawindsurfing** [comment]
I actually realised it is MySQL 8.0 bug. Nothing to do with filament.

[https://bugs.mysql.com/bug.php?id=103465](https://bugs.mysql.com/bug.php?id=103465)
