### ISSUE TITLE
`Method Filament\Forms\Components\Group::table does not exist` error when using with SelectFilter in filters method of admin resource

### ISSUE THREAD

**Issue by faizananwerali** [laravel-filament/filament#6870]
### Package

filament/filament

### Package Version

v2.17.49

### Laravel Version

v10.14.0

### Livewire Version

v2.12.3

### PHP Version

v8.1.19

### Problem description

```
use Filament\Resources\Form;
```

```
        ->filters([
            Forms\Components\Group::make()
//                ->label('Status')
//                ->columns(1)
                ->schema([
                    SelectFilter::make('status')
                        ->multiple()
                        ->options([
                            Friend::NEW => 'New',
                            Friend::ACCEPTED => 'Accepted',
                        ]),
                ]), 
        ]);
```

This is my filament admin panel Resources code `->filters()` and it is giving me the `Method Filament\Forms\Components\Group::table does not exist.` error.

<img width="1281" alt="image" src="https://github.com/filamentphp/filament/assets/12691366/38f03af5-0bdc-4bf4-a450-67064d890f14">

### Expected behavior

Should be working but somehow not.

### Steps to reproduce

add the filter I mention and try it yourself.

### Reproduction repository

https://github.com/faizananwerali/filament_demo

**Comment by danharrin** [comment]
This is not supported, only filters can be passed into the filters() array, not form components raw

**Comment by faizananwerali** [comment]
how did the 'webbingbrasil/filament-advancedfilter' plugin have done it? I'm just asking, it looks bad in my app. I can't wrap around with Group Component.

<img width="1085" alt="Screenshot 2023-06-29 at 2 57 02 AM" src="https://github.com/filamentphp/filament/assets/12691366/ad8ce63a-d67a-47f4-9939-71b782dfc99a">

**Comment by zepfietje** [comment]
I think you're looking for custom filter forms: https://filamentphp.com/docs/2.x/tables/filters#custom-filter-forms.
