### ISSUE TITLE
The data in the database is being changed successfully, but the data in the frontend is out of date.

### ISSUE THREAD

**Issue by romatexdev** [laravel-filament/filament#6892]
### Package

filament/filament

### Package Version

v2.16.60

### Laravel Version

v8.83.27

### Livewire Version

v2.10.8

### PHP Version

8.1.9

### Problem description

Hi guys! When I update the data in Relation Manager in modal form, the data is successfully changed in the database, but in the frontend of the project I get old data from the database. 
In order for the "changes" to apply, I have to go into the resource of the model itself, which I changed in the Relationship Manager and just click "Save". And then finally the data in frontend becomes relevant. 

How does such magic work and how to make it update the model?

### Expected behavior

I expect that if I change the data in the Relation Manager, they will immediately be displayed in the frontend

### Steps to reproduce

Install the project from scratch and try to change the data in Relation Manager. The data in the database is being changed successfully, but the data in the frontend is out of date.

### Reproduction repository

https://github.com/romatexdev/adminVodoley

**Comment by danharrin** [comment]
Please submit a public reproduction repository according to our guidelines, and we will reopen.

However, this doesnt sound like a bug, you probably need to emit a Livewire event to reload the component?

**Comment by romatexdev** [comment]
Hi, Dan! I tried to create a listener in the model and called an event at the end of the script, but it didn't help.

**Comment by romatexdev** [comment]
How does this magic work? =) Changes occur in the database, but I get the data before the change.

**Comment by danharrin** [comment]
The event needs to be dispatched from the page afterSave() and then listened for on the relation manager, please search because there should be many examples of this online

**Comment by romatexdev** [comment]
I have 2 entities: ProductResource and VersionResource. 
VersionResource has a ProductRelationManager. 
In the ProductRelationManager I add 

`->actions([
                Tables\Actions\EditAction::make()
                    ->after(function (RelationManager $livewire){
                        $livewire->emit('modalEdit');
                    }),`

 and the listener

`protected $listeners = ['modalEdit' => '$refresh'];`

 to ProductResources\EditPage. 

However, this does not solve the problem. I've tried different options, I'm at a dead end! Pls, help!

**Comment by danharrin** [comment]
In the listener, you probably need `refreshFormData()` https://filamentphp.com/docs/2.x/admin/pages/actions#refreshing-form-data
