### ISSUE TITLE
Issue with creating resources for models not residing in App\<

### ISSUE THREAD

**Issue by whoacowboy** [laravel-filament/filament#6898]
### Package

filament/filament

### Package Version

2

### Laravel Version

10

### Livewire Version

v2

### PHP Version

php 8.1

### Problem description

Hi.
I am having an issue with something very similar to [2920](https://github.com/filamentphp/filament/pull/2920). 

We store my models in a package that has a different namespace then `App\Models`, let's say `MyNamespace\Models` in order to share them across a few projects.

When I run 

```
php artisan make:filament-resource MyNamespace/Models/User --generate
```

Filament looks for the `User` model in `App\Models\MyNamespace\Models\User`

### Expected behavior

If I were to run.

```
php artisan make:filament-resource /MyNamespace/Models/User --generate;
```
or
```
php artisan make:filament-resource \\MyNamespace\\Models\\User --generate
```

In class files such as `UserResource` I would expect it to write.

```
use MyNamespace\Models\User;
```

instead it writes.

```
use App\Models\MyNamespace\Models\User;
```

### Steps to reproduce

Clone the repo.

Composer Install, Database Migrate.

Log in using 

test@example.com
password

Click Posts on left nav

See error.

### Reproduction repository

https://github.com/whoacowboy/filament-bug

### Relevant log output

```shell
Error
PHP 8.1.4
10.14.1
Class "App\Models\MyNamespace\Models\Post" not found
```

**Comment by whoacowboy** [comment]
I did figure out a work around for now.

I created a new model that extends my model.

```
namespace App\Models;

use MyNamespace\Models\Post as MyNamespacePost;

class Post extends MyNamespacePost
{

}
```

Then when I run 

```
php artisan make:filament-resource Post --generate;
```

it works as expected. 

It works nicely for the User model because then I can add the Filament specific UserFilament implementation methods without bogging down my User model.

```
    public function canAccessFilament(): bool
    {
        return $this->email === 'test@example.com';
    }

    public function getFilamentAvatarUrl(): ?string
    {
        return $this->user_icon;
    }
```

It's be nice if we didn't have to go through the extra step but so far I am loving Filament.

**Comment by danharrin** [comment]
There's no need to duplicate model classes, you can use `php artisan make:filament-resource Post ` and then go into the `PostResource.php` and just change the `$model` import to point towards your real model class. The only thing that wont work is `--generate`. PRing a `--model` flag as a new feature would be cool, but it is not a bug.

The reason Using/A/Path behaves like that is because that tells Filament which directory to put the *resource* in, not where to find the model.

**Comment by whoacowboy** [comment]
Hi @danharrin, I tried that originally and it did not work. Filament will go through the crud index and edit screens but there are no fields.

I updated the repo.

![Screenshot 2023-07-03 at 8 39 01 AM](https://github.com/filamentphp/filament/assets/8116953/ae2bc6c1-7391-48e1-9419-407d744fb610)

![Screenshot 2023-07-03 at 8 42 55 AM](https://github.com/filamentphp/filament/assets/8116953/bc7bc2f4-cec7-422e-946b-7e4b50ba3457)

**Comment by danharrin** [comment]
Yeah, generate will not work, but you can just add the columns and inputs yourself?

**Comment by whoacowboy** [comment]
OK, now I get it. 

FYI, when I do run it with an extended model,

`App\Models\Post extends MyNamespace\Models\Post`

 everything works as expected.

Thanks for your help.

**Comment by whoacowboy** [comment]
And one last trick in case someone is coming here late.

If I extend the model,

`App\Models\Post extends MyNamespace\Models\Post`

run

`php artisan make:filament-resource Post --generate`

Then go into PostResource and change `App\Models\Post` to `MyNamespace\Models\Post` it works with all of the scaffolding and I can delete `App\Models\Post`

**Comment by ardiandp** [comment]
embuh lah sek ruwet iki
