### ISSUE TITLE
Spatie media library reordering not saving on creation

### ISSUE THREAD

**Issue by ariaieboy** [laravel-filament/filament#6905]
### Package

filament/spatie-laravel-media-library-plugin

### Package Version

v2.17.49

### Laravel Version

v10.x

### Livewire Version

v2.12.3

### PHP Version

8.2.x

### Problem description

Spatie Media Library File upload on creation does not save the order of pictures and I need to edit the created record to reorder the pictures.

### Expected behavior

On creation, it must preserve the ordering.

### Steps to reproduce

Add a Spatie media library file upload :
```php
                        Forms\Components\SpatieMediaLibraryFileUpload::make('images')
                            ->collection('images')
                            ->disk('minio')
                            ->panelLayout('integrate')
                            ->image()
                            ->multiple()
                            ->enableReordering()
                            ->minFiles(1)
```
Reorder images and create the record.
The order of images is not saved.

I did not create a reproduction repository yet. 
I have a custom `handleRecordCreation` for my record. I think it might be related. I will create a reproduction repository after investigating this issue a little bit more.

### Reproduction repository

https://github.com/ariaieboy

**Comment by danharrin** [comment]
Please reopen the issue when you have a reproduction repository.

**Comment by zepfietje** [comment]
Please provide a real reproduction repository.

**Comment by danharrin** [comment]
lol

**Comment by ariaieboy** [comment]
@danharrin 
Do I need to do anything in `handleRecordCreation` to save the order of images?

**Comment by danharrin** [comment]
No

**Comment by arvids-gammersmidts** [comment]
Also having the same issue. Order is not saved correctly, if on create files are not manually reordered.
`SpatieMediaLibraryFileUpload::make('Files')
                    ->collection('mediaSetFiles')
                    ->image()
                    ->multiple()
                    ->reorderable()
                    ->openable()
                    ->required()
                    ->columnSpan(2)
                    ->preserveFilenames()
                    ->imageEditor()`

It seems others are having this issue aswell https://stackoverflow.com/questions/77371060/how-to-control-order-of-images-in-spatie-media-library-field-while-saving
