### ISSUE TITLE
Call to undefined method Illuminate\Database\Eloquent\Relations\BelongsToMany::getOwnerKeyName()

### ISSUE THREAD

**Issue by alexmanase** [laravel-filament/filament#6917]
### Package

filament/filament

### Package Version

^2.0

### Laravel Version

^10.10

### Livewire Version

^2.12

### PHP Version

8.2.7

### Problem description

When I try to use a select for a resource using `BelongsToMany` relationship I get the following error: 

```
Call to undefined method Illuminate\Database\Eloquent\Relations\BelongsToMany::getOwnerKeyName()
```

The code I am using for select:

```php
public static function form(Form $form): Form
{
    return $form->schema([
        Forms\Components\Select::make('apartment')
            ->relationship('projects', 'name'),
     ]);
}
```

### Expected behavior

It should let me select an option from a related model without throwing this error.

### Steps to reproduce

1. Create 2 models (e.g. Apartment and Project)
2. Create a pivot model (e.g. ApartmentProject)
3. For Apartment and Project add the method for relationship. (`$this->belongsToMany`)
4. Use a select with a relationship (https://filamentphp.com/docs/2.x/forms/fields#populating-automatically-from-a-relationship)
5. Check in the Filament Dashboard

### Reproduction repository

https://github.com/alexmanase/filament-select-issue-demo

### Relevant log output

```shell
https://flareapp.io/share/17xDJOG7
```

**Comment by zepfietje** [comment]
This is because using many-to-many relationships with the select field is only supported with `->multiple()`: https://filamentphp.com/docs/2.x/forms/fields#populating-automatically-from-a-relationship.

**Comment by alexmanase** [comment]
Thank you!
