### ISSUE TITLE
Custom built NavigationGroup messes up paddings and margins in sidebar (Laravel 9/10)

### ISSUE THREAD

**Issue by Husky110** [laravel-filament/filament#6939]
### Package

filament/filament

### Package Version

v2.17.50

### Laravel Version

v10.14.1 + v9.52.10

### PHP Version

PHP 8.1.17

### Problem description

Using the following code inside the AppServiceProvider messes up the margins and paddings in the menu-sidebar.  
Code:  
```
public function boot()
    {
        Filament::navigation(function (\Filament\Navigation\NavigationBuilder $navigationBuilder){
            return $navigationBuilder->items([
                NavigationItem::make('Dashboard')
                    ->icon('heroicon-o-home')
                    ->activeIcon('heroicon-o-home')
                    ->isActiveWhen(fn (): bool => request()->routeIs('filament.pages.dashboard'))
                    ->url(route('filament.pages.dashboard')),
                NavigationGroup::make('Test')->items([
                    ...MeepPage::getNavigationItems()
                ])->collapsible(false),
            ]);
        });
    }
```
The outcome looks like this:   
![image](https://github.com/filamentphp/filament/assets/13180625/502d7f90-7098-48f4-9fd0-a9151c665564)

### Expected behavior

I expect NavigationGroups to behave like a sub menu within the same alignment as it's parent.

### Steps to reproduce

1. composer create-project laravel/laravel example-app
2. composer require filament/filament:"^2.0"
3. php artisan make:filament-page MeepPage
4. Modify the MeepPage to look like this: 
```
<?php

namespace App\Filament\Pages;

use Filament\Forms\Components\TextInput;
use Filament\Pages\Page;

class MeepPage extends Page
{
    protected static ?string $navigationIcon = 'heroicon-o-document-text';

    protected static string $view = 'filament.pages.meep-page';

    protected static function getNavigationLabel(): string
    {
        return 'MEEP';
    }

    protected function getFormSchema(): array
    {
        return [
            TextInput::make('meepers')->label('Just a test')
        ];
    }
}
```
6. Modify the blade-view like this:
```
<x-filament::page>
    {{ $this->form }}
</x-filament::page>
```
7. Apply the nav-building-code above to the AppServiceProvider
8. npm install
9. npm run build
10. set up environment -> php artisan migrate
11. php artisan make:filament-user
12. php artisan fillament:upgrade

### Reproduction repository

https://github.com/Husky110/filament-navigation-bug

**Comment by zepfietje** [comment]
Make sure to wrap your first item in a group.
Reopen if there's still issues then.

**Comment by Husky110** [comment]
Well - I do not think that is how it is supposed to work!
Normally you have a navigation like this:
- Parent
  - MenuItem 1
  - MenuItem 2
  - Submenu 1
    - SubmenuItem 1
    - SubmenuItem 2
  - MenuItem 3

And so on. Going like "Well - wrap your first item in a Submenu then" is breaking that flow and that is NOT what submenus are for, cause that would lead to "Put everything in it's own submenu or you're out of luck." and I can't see that to be serious, especially given that the Dashboard-Link should always be on top.  
In fact I would say that all submenus have to align themselfs within the navigation-flow and not break it.

**Comment by Husky110** [comment]
Additionally - even IF I wrap everything inside it's own navigation group, the items still take the whole navigation-space and all paddings are lost.

**Comment by danharrin** [comment]
Zep's suggestion was to put it in a NavigationGroup with a label of `''`, which will ensure the padding is correct. But I think this should be improved.

**Comment by Husky110** [comment]
> ...which will ensure the padding is correct.

Not really. Wrapping it just breaks the padding of the Dashboard-Link aswell, since after a NavigationItem is put inside the group, the group itself has no padding. Versus a collection of Items that would have paddings on them.  
Look - I don't wanna be a nob here, but given that the pristine Dashboard-Item as the baseline, I don't think it's too much to ask that all items inside the `items()`-function  should align vertically, whereas a NavigationGroup sets a new baseline with it's label.

**Comment by Husky110** [comment]
For a better illustration - what we have right now is this:  
![image](https://github.com/filamentphp/filament/assets/13180625/601e9a9e-005f-4d3b-9e66-1043e142a7d6)

What I suggest to happen is this:  
![image](https://github.com/filamentphp/filament/assets/13180625/ab3b6db3-8362-48ef-b5c1-ebced8fc019c)

**Comment by danharrin** [comment]
Yes I agree this is weird and thats why I reopened

**Comment by zepfietje** [comment]
Isn't this just something that should be handled on the back-end side of things, @danharrin?
I mean, on the auto-generated navigation in the demo it all looks fine: https://demo.filamentphp.com.

**Comment by Husky110** [comment]
The main difference is that the demo and most examples seen so far utilize the `groups()`-function, whereas my example uses the `items()`-function directly. I ain't sure if the whole border-element and such would have had to be added there aswell, but atleast beeing inline for simple things should be possible.

**Comment by zepfietje** [comment]
Ah, see, my initial comment might have been close then. If you wrap that single item in a group, and change `items()` to `groups()` on the navigation builder, it should work fine.

Could you test that, @Husky110?

**Comment by Husky110** [comment]
@zepfietje 
I already did. The `groups`-function works nicely. But my post ist about putting a navigation-group into `items`, since its actually a legitimate thing to put there and that messes up the paddings big time. By "legitimate" I mean the following things:
- it does not throw any error or warning
- it is inside the Navigation-Realm (namespace) of Filament and not distinctively namned as an item that belongs somewhere else (f.e. UserMenuItem)
- it is supposed to create a submenu (which it actually does inside the `items`-function)
- There is a viable scenario where one uses it inside the `items`-function so create a simple menu that does not imply the nice grouping which `groups` does
- Actually it's pretty intuitive to put a NavigationGroup inside the `items`-function (that's how I got here in the first place)

**Comment by danharrin** [comment]
Why not try the standalone NavigationItem objects in `items()` and the NavigationGroup in `groups()` instead of altogether

**Comment by Husky110** [comment]
"Easier sorting" for one and "simple submenus without any fancy borders and other visuals" for two. :)

**Comment by danharrin** [comment]
The border thing is not deliberate, there should be a border, its part of our design system, you can change that with CSS. Why is sorting easier when they are combined?

**Comment by zepfietje** [comment]
> @zepfietje I already did. The `groups`-function works nicely. But my post ist about putting a navigation-group into `items`, since its actually a legitimate thing to put there and that messes up the paddings big time. By "legitimate" I mean the following things:

So you're saying what I proposed works?
If so, then I don't get the point of using `->items()` instead of `->groups()` and wrapping the first item in a group?

**Comment by zepfietje** [comment]
@danharrin and I have discussed this issue in more detail.
My proposed solution is actually how the API should be used.
While your code snippet doesn't throw an exception, it's not what the navigation API is designed for currently.
We have discussed ways to make that code work automatically by wrapping things internally etc. but that would be a breaking change in v2.
For v3, we're looking into ways to improve this.

Thanks for bringing it up. 🙂

**Comment by Husky110** [comment]
One thing that could improve the issue of "intuitiveness" in general would be to commit to way where you try to avoid arrays. Arrays can be freaking anything.
I was facing a simmlar thing and fixed this by making custom classes that extend Laravels Collection, but only allow specific items to be added.
Here's an example for that:
```
<?php

namespace Blossom\WorkerBase\Standards;

use Illuminate\Support\Collection;

class SpecificClassCollection extends Collection
{
    protected $classToBeInCollection;

    public function __construct(string $classToBeInCollection){
        $this->classToBeInCollection = $classToBeInCollection;
        parent::__construct();
    }

    public function add($item)
    {
        if(get_class($item) != $this->classToBeInCollection){
            throw new \Exception('Item falscher Klasse versucht in Collection zu packen!');
        }
        return parent::add($item);
    }

    public function keyBy($keyBy)
    {
        $collection = [];
        foreach ($this->items as $key => $item){
            $key = $item->$keyBy;
            if(is_numeric($key) == false && is_string($key) == false){
                throw new \InvalidArgumentException('SpecificCollections können nur nach Strings und Nummern Key-By!');
            }
            $collection[$key] = $item;
        }
        return collect($collection);
    }
}
```
Whilst not beeing very sophisticated, this thing could easily be implemented to accept interfaces, so the `items`-function could look like this:
`$navigationBuilder->items(new NavigationItemsCollection->collect([]))` whereas either the user (dev) has to provide said collection or you do that internally and do the collect on an array where a NavigationGroup would throw an "You can't add something like this here.". Whilst this looks a bit restrictive in the beginning, it actually emphasises new users to stick to the rules or make their own components that implement an interface which is allowed by the collection - but then they are on their own.
