### ISSUE TITLE
Sidebar item line should be extended when text wrapped

### ISSUE THREAD

**Issue by danharrin** [laravel-filament/filament#6963]

**Comment by danharrin** [comment]
@zepfietje Unassigned myself from this as I tried to do it and couldn't work out how to get the truncate to work

**Comment by zepfietje** [comment]
Do we want truncate or extension of the line?
Personally I prefer truncate, but I believe you vouched for extension previously.

**Comment by zepfietje** [comment]
Fixed on my design branch: https://github.com/filamentphp/filament/pull/6928/commits/57cacc0dde60d25134b7d85777e36bd63811f23c.
