### ISSUE TITLE
Textarea `extraAttributes` added directly to `textarea` element instead of field wrapper

### ISSUE THREAD

**Issue by bakerkretzmar** [laravel-filament/filament#7002]
### Package

filament/filament

### Package Version

v2.17.49

### Laravel Version

v10.13.5

### PHP Version

8.2.7

### Problem description

Textarea extra attributes are added directly to the textarea element instead of to the field wrapper. This is different from how all other fields behave, and not [what's documented](https://filamentphp.com/docs/2.x/forms/fields#custom-attributes):

<img width="881" alt="image" src="https://github.com/filamentphp/filament/assets/18192441/81d26acb-6fd2-4d02-afe6-5c7d22c6cefc">

Source code: https://github.com/filamentphp/filament/blob/2.x/packages/forms/resources/views/components/textarea.blade.php#L32

### Expected behavior

Textarea extra attributes should be added to the field wrapper, like they are for all other fields, and only `extraInputAttributes` should be set directly on the textarea itself.

### Steps to reproduce

These fields:

```php
TextInput::make('text')
    ->extraAttributes(['foo' => 'bar']),
Textarea::make('textarea')
    ->extraAttributes(['foo' => 'bar']),
```

Produce this HTML:

```html
<div class="..." foo="bar">
    <div class="flex-1">
        <input x-data="{}" ...>
    </div>
</div>
<!-- ... -->
<textarea foo="bar" x-data="textareaFormComponent()" ...></textarea>
```

### Reproduction repository

https://github.com/bakerkretzmar/filament-underline-issue/blob/main/app/Filament/Resources/UserResource.php#L32-L35

**Comment by danharrin** [comment]
The textarea component doesn't have any other element that wraps it, `<textarea>` is the root, hence why it is merged like that. We're not gonna add an extra `<div>` for the sake of it.
