### ISSUE TITLE
field modified/updated in $data in mutateFormDataBeforeCreate() is not reflected in beforeCreate() hook

### ISSUE THREAD

**Issue by code-reflex** [laravel-filament/filament#7021]
### Package

filament/filament

### Package Version

v2.17.50

### Laravel Version

v10.15.0

### Livewire Version

v2.12.3

### PHP Version

PHP 8.2.8

### Problem description

I am changing/modifying one of the form fields / data values in mutateFormDataBeforeCreate() so that the modified value  will be stored in the table.  But, I see that the original value is getting stored.

In the Resource class:
```
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                DateTimePicker::make('startDate'),
                DateTimePicker::make('endDate'),
            ]);
    }
```

In the CreateResource Page class:
```
    protected function mutateFormDataBeforeCreate(array $data): array
    {
        // replace start with current dateTime irrespective of user specified dateTime value
        $data["startDate"] = Carbon::now()->toDateTimeString();

        //dd($data);  
        return $data;
    }

    protected function beforeCreate(): void
    {
        // dd($this->data);
        // shows the user selected dateTime and not the mutated / modified dateTime :(
        // same with afterCreate() hook;  Database table too will have the user selected dateTime value
    }
````

### Expected behavior

The mutated dateTime value should be stored into the database table and not the user selected dateTime in the above example.

### Steps to reproduce

1. Create Event Model with migration
2. Add some field/s to the table and migrate 
3. Generate filament-resource for Event 
4. Implement the mutate method & beforeCreate() hook
5. See the die & dump or database table records

### Reproduction repository

NA

### Relevant log output

```shell
NA
```

**Comment by danharrin** [comment]
`mutateFormDataBeforeCreate` does not mutate `$this->data`. It gets passed to `handleRecordCreation()`.
