### ISSUE TITLE
Form Builder not working

### ISSUE THREAD

**Issue by tituskeuler** [laravel-filament/filament#703]
### Package

filament/forms

### Package Version

v2.2.19

### Laravel Version

v8.70.2

### Livewire Version

v2.7.2

### PHP Version

v8.0.12

### Bug description

The builder is not working from the example provided in the documentation. When I click on the "Add to content" button, there's no visible reaction. I guess from the code, there shall be a dropdown with buttons visible, which is not.

No error thrown in console. Other fields, including the repeater, are working perfectly fine. Component renders a `<li>` DOM element per block configured. I can see the x-on even is fired and hidden-status is removed from element. 

I copied the code exactly as found here: https://filamentadmin.com/docs/2.x/forms/fields#builder

Do I need to specify any addition CSS?

**Comment by tituskeuler** [comment]
Installed Laravel via Composer
Installed Jetstream via Composer
Installed filament/forms
Created component

Running inside Laravel Sail Container.

**Comment by danharrin** [comment]
Are there any console errors?

**Comment by danharrin** [comment]
Cannot reproduce this, could you please share a repo where I can?

**Comment by tituskeuler** [comment]
While preparing the repo, I found that the element is working as intended when not within the default dashboard slot coming with Jetstream. So I guess there was an error on my side. Thank you for your quick reaction.
