### ISSUE TITLE
Editing dependent select makes the parent Model select empty

### ISSUE THREAD

**Issue by javarex** [laravel-filament/filament#7038]
### Package

filament/filament

### Package Version

v2

### Laravel Version

9

### PHP Version

8.1

### Problem description

This works when I select Drawers it will populate Folders. It also saves okay.

My problem is when I will edit the record. The drawer selection is empty.

Here are my Models and their relationships:
```

class Document extends Model
{
    use HasFactory;

    protected $guarded = ['id'];

    public function folder()
    {
        return $this->belongsTo(Folder::class);
    }

    public function user()
    {
        return $this->belongsTo(User::class);
    }
}


class Drawer extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'slug', 'office_id'];

    public function folders()
    {
        return $this->hasMany(Folder::class);
    }

}


class Folder extends Model
{
    use HasFactory;

    protected $fillable = ['name', 'slug', 'drawer_id'];

    public function drawer()
    {
        return $this->belongsTo(Drawer::class);
    }

    public function documents()
    {
        return $this->hasMany(Document::class);
    }
}
```

### Expected behavior

The parent Model (Drawer select should be filled)

### Steps to reproduce

```
Select::make('drawer_id')
  ->label('Drawers')
  ->options(Drawer::all()->pluck('name', 'id')->toArray())
  ->searchable()
  ->preload()
  ->reactive()
  ->afterStateUpdated( 
      fn (callable $set) => $set('folder_id', null)
  ),

Select::make('folder_id')
    ->label('Folders')
    ->options(function (callable $get) {
        $drawer = Drawer::find($get('drawer_id'));
        
        if (! $drawer) {
            return Folder::all()->pluck('name', 'id');
        }

        return $drawer->folders->pluck('name', 'id');
    })
    ->searchable(),
```

### Reproduction repository

https://github.com/neverender24/filament_archiving

**Comment by danharrin** [comment]
If you don't have a `drawer_id` column on your actual resource model, you need to tell Filament what it is. In this case, you could maybe use `mutateFormDataBeforeFill()`?

**Comment by danharrin** [comment]
If you don't have a `drawer_id`, you need to tell Filament what it is. In this case, you could maybe use `mutateFormDataBeforeFill()`?

**Comment by PLGUPICTO** [comment]
@danharrin I understand that there is no foreign_id (drawer_id) in the actual resource but I think it is nice to have it detected also as the relationship is stated in the parent table, in this example folder table has the drawer_id.

**Comment by danharrin** [comment]
There is basically no way we can infer something like that. It would absolutely be "too much magic" if we were able to. Adding a couple of lines in the mutate function isnt bad.
