### ISSUE TITLE
When you click on the button to change the dark / light theme, the browser tab closes

### ISSUE THREAD

**Issue by D076** [laravel-filament/filament#7047]
### Package

filament/filament

### Package Version

2.17.44

### Laravel Version

10.13

### Livewire Version

2.3

### PHP Version

8.2.6

### Problem description

When you click on the button to change the dark / light theme, the browser tab closes on safari macOS.

### Expected behavior

The theme changes.

### Steps to reproduce

Open admin panel with enable dark_mode on safari macOS.
Click "Toggle dark mode" button.

### Reproduction repository

https://github.com/filamentphp/filament

### Relevant log output

```shell
Problem here in resources/views/components/layouts/app/topbar/user-menu.blade.php
If remove "close();" in on:click function, problem will be solved
<div>
    @if (config('filament.dark_mode'))
        <x-filament::dropdown.list.item icon="heroicon-s-moon" x-show="theme === 'dark'" x-on:click="close(); mode = 'manual'; theme = 'light'">
            {{ __('filament::layout.buttons.light_mode.label') }}
        </x-filament::dropdown.list.item>

        <x-filament::dropdown.list.item icon="heroicon-s-sun" x-show="theme === 'light'" x-on:click="close(); mode = 'manual'; theme = 'dark'">
            {{ __('filament::layout.buttons.dark_mode.label') }}
        </x-filament::dropdown.list.item>
    @endif
</div>
```

**Comment by zepfietje** [comment]
@danharrin this is probably because of a clash with https://developer.mozilla.org/en-US/docs/Web/API/Window/close.

I can't reproduce the issue on macOS Safari though, @D076.
