### ISSUE TITLE
Toggle or markdown editor in a modal break future actions

### ISSUE THREAD

**Issue by anthonyphysgun** [laravel-filament/filament#7064]
### Package

filament/filament

### Package Version

v3.0.0-beta2

### Laravel Version

10.10

### PHP Version

8.1.1

### Problem description

When you have a toggle on a Action form, and close it and open another it breaks actions completely

### Expected behavior

Not to break

### Steps to reproduce

env - Windows + Valet for Windows

Just clone the repo, and view the Test page and press the actions in order, then repeat and it will be broken

### Reproduction repository

https://github.com/anthonyphysgun/filament-toggleissue/tree/main

**Comment by danharrin** [comment]
Probably a Livewire issue. Similar behaviour with the markdown editor I noticed a few weeks ago.

**Comment by zepfietje** [comment]
@danharrin, I've removed the roadmap entry for that to track it using this issue.

For reference:

> When switching from modal with markdown editor to modal without markdown editor, Livewire JS error and modal without doesn't open.

**Comment by danharrin** [comment]
Should be fixed by alpinejs/alpine#3681

**Comment by danharrin** [comment]
Ok that is merged, just waiting for the next Livewire release before I close this

**Comment by zepfietje** [comment]
@danharrin https://github.com/livewire/livewire/releases/tag/v3.0.0-beta.5

**Comment by danharrin** [comment]
Unfortunately that was too early for it to be released :(

**Comment by danharrin** [comment]
Should be fixed by now
