### ISSUE TITLE
Class "Filament\Pages\Tenancy\EditTenantProfile" not found

### ISSUE THREAD

**Issue by peterkeri** [laravel-filament/filament#7069]
### Package

filament/filament

### Package Version

v3.0.0-beta1

### Laravel Version

v10.15.0

### Livewire Version

v3.0

### PHP Version

PHP 8.1.20

### Problem description

Missing file: Class "Filament\Pages\Tenancy\EditTenantProfile" not found

Flare link: https://flareapp.io/share/KPgQzoX5

### Expected behavior

Try to set multitenant via v3 documentation

### Steps to reproduce

Create app/Filament/Pages/Tenancy/EditTeamProfile.php nad try to use EditTenantProfile.php as extended file

### Reproduction repository

filamentphp/filament

**Comment by zepfietje** [comment]
Have you tried running `composer dump-autoload`?

**Comment by andrewdwallo** [comment]
@peterkeri Run `composer update` after installing as well. I had the same issue.

**Comment by misterjulo** [comment]
Just run `composer update` and it's resolved for me
