### ISSUE TITLE
Standalone Table with Row Actions not working

### ISSUE THREAD

**Issue by abishekrsrikaanth** [laravel-filament/filament#7074]
### Package

filament/tables

### Package Version

v3.0.0-beta1

### Laravel Version

v10.10

### Livewire Version

v3.0

### PHP Version

PHP 8.2

### Problem description

I have the following table actions for my standalone table.

```php
public function getTableActions(): array
    {
        return [
            Action::make('Edit')->form($this->getFormSchema())->modalWidth('md')->action(function ($data) {
                $this->company->benefits()->updateExistingPivot($data['id'], ['benefit_description' => $data['description']]);
            }),
            Action::make('Delete')->requiresConfirmation()->action(function ($data) {
                $this->company->benefits()->detach($data['id']);
            }),
        ];
    }
```

Not sure why, but clicking on the Edit or Delete actions does nothing.

No console errors but there is a network call and the response is always about close-modal. Screenshot of the network call response. Here is the video of what I am facing on the actual project https://share.cleanshot.com/4xZDqtxK

![CleanShot 2023-07-21 at 02 39 33](https://github.com/filamentphp/filament/assets/1639302/77de4303-a44b-4cc7-be04-3e80a7515959)

Here is the payload

![CleanShot 2023-07-21 at 02 40 11](https://github.com/filamentphp/filament/assets/1639302/0bc8823a-892c-469b-9c59-7659f941a617)

### Expected behavior

The Edit Modal or the Delete Confirmation Dialog doesn't show

### Steps to reproduce

Try to add the above code to a standalone table builder

### Reproduction repository
Please create a user on the database and visit the root `/` url to load the table and click the edit button
[NA](https://github.com/abishekrsrikaanth/filament-test)

**Comment by zepfietje** [comment]
Make sure your page contains the `<x-filament-actions::modals />` component: https://beta.filamentphp.com/docs/3.x/actions/adding-an-action-to-a-livewire-component/#adding-the-action.

@danharrin could you add a reference of this to the table docs if you think that's needed?

**Comment by danharrin** [comment]
The tables package should inject it by default
