### ISSUE TITLE
--no-interaction tries to open github web page

### ISSUE THREAD

**Issue by cryptobrains** [laravel-filament/filament#7077]
### Package

filament/filament

### Package Version

v2.17.50

### Laravel Version

v10.x

### PHP Version

PHP 8.2

### Problem description

When calling make:filament-user with the flag --no-interaction even on headless environments the github project page gets opened. This prevents a reliable quiet deployment script from being executed.

### Expected behavior

With the standard Laravel --no-interaction flag appended to the command the github project page should not be opened

### Steps to reproduce

<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class DeployFilamentUsers extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'deploy:filament-users';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Creates authorized filament users as part of deployment';

    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle(): int
    {
        $this->call('make:filament-user', ['--name'=>"name", '--email'=>"test@test.com", "--password"=>"password", "--no-interaction"]);
        $this->info('Done.');
        return Command::SUCCESS;
    }
}

### Reproduction repository

none

### Relevant log output

```shell
Page gets opened
```

**Comment by cryptobrains** [comment]
The actual code is embedded in the issue, no need to create a repo for that.

**Comment by danharrin** [comment]
Fixed in v3. If you want to fix it in v2, you can submit a PR.
