### ISSUE TITLE
Global search results panel overflows screen on mobile

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#7092]

**Comment by JamieBradders** [comment]
Hello 👋 I'm new to this community and would love to make a contribution by working on this bug. I just wanted to check it wasn't on anybody else's radar before taking a look over the weekend?

Thanks 🙏

**Comment by danharrin** [comment]
@JamieBradders yeah I think you're good. We want to try using Floating UI like in other places in the codebase to fix this 👍

**Comment by zepfietje** [comment]
I believe @awcodes explored using Floating UI and ran into some limitations. Maybe he can share what he found.

**Comment by JamieBradders** [comment]
> @JamieBradders yeah I think you're good. We want to try using Floating UI like in other places in the codebase to fix this 👍

Hey @danharrin thanks for confirming, I'm not familiar with Floating UI but I'll look into it before starting. You mentioned that this was used in other places within the codebase - could you please give me an example of a component using this within the app?

**Comment by awcodes** [comment]
Dropdown component
https://github.com/filamentphp/filament/blob/3.x/packages/support/resources/views/components/dropdown/index.blade.php

Floating ui docs
https://www.npmjs.com/package/@awcodes/alpine-floating-ui

**Comment by rasasak** [comment]
hmm I have idea for little fix ... 
what about fullwidth  result contaner ... on small divecies (before it hits SM breakdown)
before: 
![1](https://github.com/filamentphp/filament/assets/28921659/09a10055-534c-43d8-8505-718431bf175f)

after:
![2](https://github.com/filamentphp/filament/assets/28921659/bc5f575d-c9af-4237-86f9-c32340456a74)

for now, before founding beter solution ? 
I am testing this now... only changed by CSS

**Comment by danharrin** [comment]
Yeah lets go with that, at least until Floating UI can be worked out

**Comment by rasasak** [comment]
#7728
