### ISSUE TITLE
Livewire overrides `disabled` attribute

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#7093]
`wire:loading.attr="disabled"` overrides conditional disabled state (found in at least checkbox list and radio components).

**Comment by maharsh-mangal** [comment]
@zepfietje  hello, can i open a pr on this? i was going to make a branch and make one but i dont have permission. Can you direct me how to make contributions please if im missing something, thanks

**Comment by zepfietje** [comment]
Check out our contribution guide: https://github.com/filamentphp/filament#contributing.

**Comment by maharsh-mangal** [comment]
@zepfietje Please review my PR, thanks :)

**Comment by sumardi** [comment]
Do we still need `wire:loading.attr="disabled"` in form components? According to [the docs](https://livewire.laravel.com/docs/actions#disabling-inputs-while-a-form-is-being-submitted),

> Livewire automatically disables the submit button and all form inputs inside the <form> element while a wire:submit action is being processed. This ensures that a form isn't accidentally submitted twice.

**Comment by saade** [comment]
@sumardi not on fields I guess, but I think we need it in the submit button because other events can trigger a disabled state, like uploading a file through filepond for example

but good catch

**Comment by sumardi** [comment]
> @sumardi not on fields I guess, but I think we need it in the submit button because other events can trigger a disabled state, like uploading a file through filepond for example
> 
> but good catch

filepond use alpine `x-bind:disabled`, not an issue if we remove `wire:loading.attr="disabled"`. Because Livewire v3 automatically add `disabled` to submit button and `readonly` to form inputs.

**Comment by saade** [comment]
> > @sumardi not on fields I guess, but I think we need it in the submit button because other events can trigger a disabled state, like uploading a file through filepond for example
> > but good catch
> 
> filepond use alpine `x-bind:disabled`, not an issue if we remove `wire:loading.attr="disabled"`. Because Livewire v3 automatically add `disabled` to submit button and `readonly` to form inputs.

it uses x-bind:disabled only on the input IIRC, I think it does not apply to the submit button. The button should be disabled while uploading a file

**Comment by zepfietje** [comment]
There's a lot more cases than just fields inside forms. E.g. also text input columns on tables.

**Comment by sakanjo** [comment]
This bug is related to livewire v3, specifically [wire-loading.js](https://github.com/livewire/livewire/blob/main/js/directives/wire-loading.js#L10),

it should be fixed when the [PR](https://github.com/livewire/livewire/pull/6353) is merged.

![example](https://github.com/filamentphp/filament/assets/121197517/bf0febaa-cc0d-4396-8241-df1c19f63ecd)

**Comment by danharrin** [comment]
Thanks @sakanjo!

**Comment by zepfietje** [comment]
Confirmed the main issue been fixed by the Livewire PR @sakanjo created. Thanks!

It does seem, however, that the toggle doesn't honor the disabled state.
Reopening https://github.com/filamentphp/filament/issues/7370.
