### ISSUE TITLE
Remove workaround for `<form>` bottom margin

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#7094]
Remove `Fix extra gap below form elements from default browser stylesheet.` workaround when fixed in Livewire.

https://github.com/livewire/next/issues/109
https://github.com/livewire/livewire/pull/5784

**Comment by nuernbergerA** [comment]
@zepfietje its merged now

**Comment by zepfietje** [comment]
Thanks for notifying me, @nuernbergerA!
Was about to pick up on this issue. 😊

**Comment by zepfietje** [comment]
https://github.com/filamentphp/filament/commit/9ec9d522a8ce95502b2a42af8cbe3cae7cf79725
