### ISSUE TITLE
Style issue [ Beta Filamentphp Docs ]

### ISSUE THREAD

**Issue by ibrahimBougaoua** [laravel-filament/filament#7096]
### Package

Beta Filamentphp Docs

### Package Version

v3.0

### Laravel Version

9.19

### PHP Version

v8.1

### Problem description

Hey there,
There is an style issue in bottom section.
_Beta Filamentphp Docs_

**Thanks a lot for new updates.**

### Expected behavior

i think the issue is missing div or something like that.

### Steps to reproduce

Just go to bottom section of the page.

### Reproduction repository

https://beta.filamentphp.com/docs/3.x/widgets/charts/

**Comment by ibrahimBougaoua** [comment]
I don't know if this the right place to publish the issue.

**Comment by zepfietje** [comment]
We're aware of the issue and should be fixed on the next release.

**Comment by ibrahimBougaoua** [comment]
> We're aware of the issue and should be fixed on the next release.

Okey,thanks.
