### ISSUE TITLE
Update profile without new password failed

### ISSUE THREAD

**Issue by iliyas-inode** [laravel-filament/filament#7098]
### Package

filament/filament

### Package Version

v3.0.0-beta3

### Laravel Version

v10.15.0

### PHP Version

8.1.16

### Problem description

Exception thrown when clicking save button without new password value in profile page

### Expected behavior

It should save changes without throwing any exception

### Steps to reproduce

1. clone repo
2. composer install
3. php artisan key:generate
4. php artisan migrate --seed
5. go to http://filament-issue-profile-update/admin
6. login with default test credentials. test@example.com - password
7. go to http://filament-issue-profile-update.test/admin/profile
8. click save changes button without touching new password filed

### Reproduction repository

https://github.com/iliyas-inode/filament-issue-profile-update

**Comment by zepfietje** [comment]
Should be fixed by https://github.com/filamentphp/filament/pull/7097.
