### ISSUE TITLE
Static tables

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#7105]
Move table's Blade components to support and document their usage.

**Comment by Wulfheart** [comment]
An option to make pagination yourself would also be very cool.

**Comment by zepfietje** [comment]
@Wulfheart, what do you mean exactly?

**Comment by AyoobMH** [comment]
@zepfietje I think he means the ability to override the behavior of pagination, maybe similar to 'get Heading' function where we can return a custom component for the header. One use case for custom pagination is infinite scroll, what do you think?

**Comment by zepfietje** [comment]
I think that requires more work or a dedicated API to be honest. Not sure if that's what Alex meant though.

**Comment by devfaysal** [comment]
Great idea. 
I had a use case already.
Thank you for the initiative.
https://github.com/filamentphp/filament/discussions/8497

**Comment by lordjoo** [comment]
Any updates on this or How can we help
