### ISSUE TITLE
Default Colors in Panel Configuration are not the same as the default colors in Filament

### ISSUE THREAD

**Issue by andrewdwallo** [laravel-filament/filament#7133]
### Package

filament/filament

### Package Version

v3.0.0-beta4

### Laravel Version

v10.15.0

### Livewire Version

v3.0.0

### PHP Version

PHP 8.1

### Problem description

The default colors, or at the very least for one of them (gray), are not the same colors as Filament's default colors and not the same as TailwindCSS defaults. I noticed this when I changed the color `gray` to the default in the panel and when I changed the defaults in a custom theme to the TailwindCSS defaults. The defaults from the Panel match TailwindCSS defaults, but Filament does not match either of them.

**Before Applying the "Default" Gray in the Panel:**
![Screenshot 2023-07-21 at 8 48 58 PM](https://github.com/filamentphp/filament/assets/104294090/d1e29bc5-b281-4e7c-8733-fa6f05023995)

**After Applying the "Default" Gray:**
![Screenshot 2023-07-21 at 8 48 32 PM](https://github.com/filamentphp/filament/assets/104294090/dfb9311d-a2c3-41fe-8e60-5a33b79dcd00)

### Expected behavior

I expect the default colors for Filament to be based on the same colors that Filament uses. As well as the defaults to be based  on TailwindCSS defaults, which I think was the intention because I believe this is a bug.

### Steps to reproduce

Step 1: Download the reproduction repository.

Step 2: Go to the AdminPanelProvider and see below.

```php
public function panel(Panel $panel): Panel
{
        return $panel
            ->default()
            ->id('admin')
            ->path('admin')
            ->login()
            ->colors([
                'primary' => Color::Amber,
                'gray' => Color::Gray,
            ])
}
```

Step 3: Remove and reapply the gray default and notice the huge change in color of the background and topbar.

### Reproduction repository

https://github.com/andrewdwallo/company

**Comment by andrewdwallo** [comment]
I honestly kind of like the default gray in the configuration tho 😂

**Comment by danharrin** [comment]
Filament's default gray is now `Zinc` as it fits better with the rest of our design system. I don't think this is a bug? https://beta.filamentphp.com/docs/3.x/support/colors#customizing-the-default-colors

**Comment by zepfietje** [comment]
Not a bug indeed.

**Comment by zepfietje** [comment]
> I honestly kind of like the default gray in the configuration tho 😂

That's why we made it so easy to change the colors. 😊

**Comment by andrewdwallo** [comment]
Alright thats fine, thanks!

**Comment by andrewdwallo** [comment]
I see now why I got confused with what the actual default colors are for Filament. In this section of the docs, https://beta.filamentphp.com/docs/3.x/support/colors#customizing-the-default-colors everything is correct. I was reading from this section https://beta.filamentphp.com/docs/3.x/panels/themes#changing-the-colors and completely misunderstood what it was saying. Silly mistake, thanks again.
