### ISSUE TITLE
icon color in dark mode when tab is active

### ISSUE THREAD

**Issue by hossam-hani** [laravel-filament/filament#7134]
### Package

filament/filament

### Package Version

v3.0.0

### Laravel Version

v10.0.0

### Livewire Version

v3.0.0

### PHP Version

8.1

### Problem description

there is a little bug in icon color in the dark mode and when the tab is active 

![image](https://github.com/filamentphp/filament/assets/42097342/e47fe4c3-f44a-4fbf-a8fd-c7f4f7d89d94)

### Expected behavior

it should change the color like labels  

### Steps to reproduce

create tabs in filament resource

### Reproduction repository

.

**Comment by hossam-hani** [comment]
i didn't add any unique code from my side ,  no need to create a repo for that.

**Comment by zepfietje** [comment]
Please mention the exact Filament version you've installed.
v3.0.0 hasn't been released yet and the design looks pre-v3beta.
Make sure to use the actual beta and this has been resolved.
