### ISSUE TITLE
composer require dependency issue

### ISSUE THREAD

**Issue by code-reflex** [laravel-filament/filament#7136]
### Package

filament/filament

### Package Version

v3.0.0-beta4

### Laravel Version

v10.15.0

### PHP Version

PHP 8.2.8

### Problem description

Unable to install the filament beta package using composer require.

```
sail@3f0a3968e8a5:/var/www/html$ composer require filament/filament:"^3.0" --dry-run
./composer.json has been updated
Running composer update filament/filament
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires filament/filament ^3.0, found filament/filament[v3.0.0-alpha1, ..., 3.x-dev] but it does not match your minimum-stability.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.



sail@3f0a3968e8a5:/var/www/html$ composer require filament/filament:"v3.0.0-beta4" --dry-run
./composer.json has been updated
Running composer update filament/filament
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Root composer.json requires filament/filament v3.0.0-beta4 -> satisfiable by filament/filament[v3.0.0-beta4].
    - filament/filament v3.0.0-beta4 requires filament/actions v3.0.0-beta4 -> found filament/actions[v3.0.0-beta4] but it does not match your minimum-stability.

Installation failed, reverting ./composer.json and ./composer.lock to their original content.
```

### Expected behavior

Should be able to install filament beta package using composer in laravel 10.x

### Steps to reproduce

Run 
```
composer require filament/filament:"^3.0"
```
in the laravel application directory.

### Reproduction repository

https://github.com/code-reflex/filamentv3betatest

**Comment by andrewdwallo** [comment]
@code-reflex Use "dev" as minimum stability instead of stable before installing.

**Comment by andrewdwallo** [comment]
This will fix it. And then run "composer update" after installing as well.

**Comment by code-reflex** [comment]
> @code-reflex Use "dev" as minimum stability instead of stable before installing.

Thank you. Yes. changed the settings in composer.json after posting this issue.
```
    "minimum-stability": "dev",
    "prefer-stable": false
```

Sorted out the remaining dependencies with -W flag. 

```
composer require filament/filament:"^3.0" -W
```

Will close the issue.

**Comment by code-reflex** [comment]
Closing the issue - set stability to "DEV" and run composer update or with -W flag for resolving dependencies.

**Comment by MarcGentner** [comment]
The error message you provided suggests that you are encountering issues with PHP extensions while trying to install a package using Composer. Specifically, it appears that the ext-intl extension is required but not enabled in your PHP configuration. Here's what you can do to address this issue:

Enable the ext-intl extension: You need to enable the ext-intl extension in your PHP configuration. To do this, you can follow these steps:

a. Open the php.ini file located at C:\xampp\php\php.ini in a text editor.

b. Search for the line that begins with extension=intl (or something similar) and make sure it is not commented out (i.e., it should not have a semicolon ; at the beginning of the line). It should look like this:

makefile
Copy code
extension=intl
c. Save the php.ini file.

Restart your web server: After making changes to the php.ini file, you should restart your web server to apply the changes. This step is essential for the changes to take effect.

Run Composer: Once you have enabled the ext-intl extension and restarted your web server, try running Composer again without the --ignore-platform-req=ext-intl flag:

Copy code
composer install
This should now work without any issues related to the ext-intl extension.

only by removing the ; semicollon in the php.ini file made this error go away and install filament v3.

**Comment by AzadGh95** [comment]
`composer up --ignore-platform-req=ext-zip` woked for me.
