### ISSUE TITLE
Create button is not using $modelLabel

### ISSUE THREAD

**Issue by mokhosh** [laravel-filament/filament#7142]
### Package

filament/filament

### Package Version

* v3.0.0-beta4

### Laravel Version

* v10.15.0

### Livewire Version

* v3.0.0-beta.3

### PHP Version

* 8.2.7

### Problem description

In filament v2 I'm using `$modelLabel` to show a translation of my model's name and it's used everywhere.
In filament v3 however `$modelLabel` is ignored in the create button above the table.
`$modelLabel` works fine in the create page, but not on the list page's create button.

### Expected behavior

`$modelLabel` should be used where ever a singular version of the name of the resource is used.

### Steps to reproduce

1. install filament v3
2. create a new resource
3. override `protected static ?string $modelLabel = 'cliente';` as instructed in the docs
4. browse the users page
5. the navigation link text has changed but the create button still says "new user", this is the bug
6. go to the edit page
7. the title says "cliente" which is correct

### Reproduction repository

https://github.com/mokhosh/filament-model-label-bug-reproduction

**Comment by edeoliv** [comment]
I've this bug too

**Comment by danharrin** [comment]
Fixed in the next beta release

**Comment by farhadrahmanii** [comment]
> ### Package
> filament/filament
> 
> ### Package Version
> * v3.0.0-beta4
> 
> ### Laravel Version
> * v10.15.0
> 
> ### Livewire Version
> * v3.0.0-beta.3
> 
> ### PHP Version
> * 8.2.7
> 
> ### Problem description
> In filament v2 I'm using `$modelLabel` to show a translation of my model's name and it's used everywhere. In filament v3 however `$modelLabel` is ignored in the create button above the table. `$modelLabel` works fine in the create page, but not on the list page's create button.
> 
> ### Expected behavior
> `$modelLabel` should be used where ever a singular version of the name of the resource is used.
> 
> ### Steps to reproduce
> 1. install filament v3
> 2. create a new resource
> 3. override `protected static ?string $modelLabel = 'cliente';` as instructed in the docs
> 4. browse the users page
> 5. the navigation link text has changed but the create button still says "new user", this is the bug
> 6. go to the edit page
> 7. the title says "cliente" which is correct
> 
> ### Reproduction repository
> https://github.com/mokhosh/filament-model-label-bug-reproduction
> 
> ### Relevant log output
> _No response_

protected static ?string $modelLabel = 'cliente';

this work for me thank you hero with your support I am using your plugins too you are real hero I pround of you.
