### ISSUE TITLE
Rich editor alpine component not recognising uploaded attachments

### ISSUE THREAD

**Issue by P-James** [laravel-filament/filament#7144]
### Package

filament/filament

### Package Version

v2.17

### Laravel Version

v10.10

### Livewire Version

v2.12

### PHP Version

PHP 8.2

### Problem description

After uploading an image with RichEditor, the alpine component doesn't register the html tag.

The image successfully uploads to S3 (albeit in a `livewire-tmp/` directory), but the image is immediately lost upon saving because there is no html markup for it.

HTML is returned as `null` on the upload response, is this the issue?

![CleanShot 2023-07-22 at 13 19 30](https://github.com/filamentphp/filament/assets/51275753/dbef5865-584b-4e59-b8c1-fd9e85656200)

![CleanShot 2023-07-22 at 13 22 15](https://github.com/filamentphp/filament/assets/51275753/ac3ed6f0-d8cf-40d9-b684-f9ef91b952f3)

### Expected behavior

The image should generate some html inside the content of the RichEditor and publish along with the post.

### Steps to reproduce

1. Set Laravel filesystem to S3, make sure buckets are all configured correctly with proper permissions and cors settings.
2. Create a filament resource with RichEditor component.
3. Attach / upload an image
4. Double check the image uploaded successfully in the AWS console
5. Save resource and refresh page - image doesn't exist

### Reproduction repository

https://github.com/P-James/filament-reproduction

**Comment by danharrin** [comment]
Can you please check if this is an issue in v3 or not?

**Comment by rene0399** [comment]
I can shed some more light here. 
This is still an issue in V3, but only when fileAttachmentsVisibility is set to public. 
If the visibility is set to private as in the Doc, it works fine. However the image link is invalid after 5 min, due to the signed URL only has 5 min lifetime.

**Comment by danharrin** [comment]
Downloaded the reproduction repo, updated to v3 and set up S3:


https://github.com/filamentphp/filament/assets/41773797/7b231012-34ad-42b1-8ae3-080f49eb799b
