### ISSUE TITLE
Auth redirecting issue

### ISSUE THREAD

**Issue by 4m1n0s** [laravel-filament/filament#7148]
### Package

filament/filament

### Package Version

v3.0.0-beta

### Laravel Version

v10.15.0

### Livewire Version

v3.0.0

### PHP Version

PHP 8.2.0

### Problem description

Hey,

there is an issue on v3.0-beta on login redirect, after login url doesn't get updated to "/admin" so the dashboard page doesn't render corectelly

<img width="1280" alt="image" src="https://github.com/filamentphp/filament/assets/2763884/2811e707-60cc-4ebe-9517-c5656da25f4a">

after refresh:
<img width="1280" alt="image" src="https://github.com/filamentphp/filament/assets/2763884/ce5bbf9a-3739-47f9-b1ee-a14ab9daec44">

### Expected behavior

the expected behavior: is to redirect to "/admin" page after login

### Steps to reproduce

Fresh install of laravel and filament

### Reproduction repository

N/A

**Comment by danharrin** [comment]
Likely a LW issue

**Comment by zepfietje** [comment]
Duplicate of https://github.com/filamentphp/filament/issues/7072.
