### ISSUE TITLE
[v3 beta] $livewire undefined on Register tenant page, it's cloned from demo/tree/3.x repo

### ISSUE THREAD

**Issue by akunbeben** [laravel-filament/filament#7149]
### Package

filament/filament

### Package Version

v3 beta

### Laravel Version

v10.2.5

### Livewire Version

v3 beta

### PHP Version

PHP 8.2

### Problem description

![image](https://github.com/filamentphp/filament/assets/46495960/16b330de-d08f-4530-aea4-74b801d517db)

I cloned the demo repo, and checkout to the 3.x branch. Install it to my local, then go to /app which is tenancy features included. 
Undefined $livewire variable appears on the register tenant page. The same error appears in different fresh Filament install

### Expected behavior

This should show register tenant page

### Steps to reproduce

Clone demo repo, go to /app to try register tenant

### Reproduction repository

https://github.com/filamentphp/demo/tree/3.x

### Relevant log output

```shell
Stack trace shared through Flareapp.io https://flareapp.io/share/17WNN4JP
```

**Comment by danharrin** [comment]
3.x branch is not up to date on the demo
