### ISSUE TITLE
Error when i use "copyableState"

### ISSUE THREAD

**Issue by papipsycho** [laravel-filament/filament#7150]
### Package

filament/tables

### Package Version

v2.17.50

### Laravel Version

v8.83.27

### Livewire Version

v2.12.3

### PHP Version

8.1

### Problem description

I got an error when i use "copyableState" into a table of relation manager.

`Unable to resolve dependency [Parameter #0 [ <required> string $state ]] in class App\Filament\Resources\CandidateResource\RelationManagers\InvitationCandidateToAssessmentRelationManage`

### Expected behavior

Be able to execute the function and get the copy of the text return 

### Steps to reproduce

Here this is how i used inside my relation manager

`public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('assessment.name'),
                Tables\Columns\TextColumn::make('createdBy.name'),
                Tables\Columns\TextColumn::make('created_at')->label(__('Invited At'))->since(),
                Tables\Columns\TextColumn::make('status')->enum([
                    'sent' => __('Sent'),
                    'passing' => __('Passing'),
                    'passed' => __('Passed'),
                ]),
                Tables\Columns\TextColumn::make('slug')->copyable()->copyableState(fn (string $state): string => "URL: {$state}")
            ])
            ->filters([
                Tables\Filters\TrashedFilter::make()
            ])
            ->headerActions([
                Tables\Actions\CreateAction::make(),
            ])
            ->actions([
                Tables\Actions\CreateAction::make()
                    ->mutateFormDataUsing(function (array $data): array {
                        $data['company_id'] = auth()->user()->currentCompany->id;
                        $data['created_by'] = auth()->user()->id;
                        $data['slug'] = Str::uuid()->toString();

                        return $data;
                }),
                Tables\Actions\EditAction::make(),
                Tables\Actions\DeleteAction::make(),
                Tables\Actions\ForceDeleteAction::make(),
                Tables\Actions\RestoreAction::make(),
            ])
            ->bulkActions([
                Tables\Actions\DeleteBulkAction::make(),
                Tables\Actions\RestoreBulkAction::make(),
                Tables\Actions\ForceDeleteBulkAction::make(),
            ]);
    }`

### Reproduction repository

https://github.com

**Comment by danharrin** [comment]
Fixed in the next v2 release

**Comment by SourabhBute** [comment]
Unable to do copyable in TextInput

I want to like :
TextText::make('email')
    ->copyable()

**Comment by danharrin** [comment]
TextColumn != TextInput
