### ISSUE TITLE
`global-search.end` render hook repeated call

### ISSUE THREAD

**Issue by atmonshi** [laravel-filament/filament#7152]
### Package

filament/filament

### Package Version

v3

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

8.1

### Problem description

When enabling the render hook `global-search.end` in `AdminPanelProvider`:

```php
->renderHook(
    'global-search.end',
    fn(): View => view('filament.hooks.lang-switcher'),
)
```
the view is called many times as I have resources with global search enabled 

<img width="611" alt="Screenshot 2023-07-23 at 12 44 00 AM" src="https://github.com/filamentphp/filament/assets/1952412/e5540b4f-6873-472a-a960-d23559183981">

### Expected behavior

The view call should be only once 

### Steps to reproduce

after installing filament follow the changes here
https://github.com/lara-zeus/test-fila-three/pull/1/files

### Reproduction repository

https://github.com/lara-zeus/test-fila-three/pull/1/files

**Comment by danharrin** [comment]
Fixed in next v3 release
