### ISSUE TITLE
adding trait Translatable will make all fields Translatable

### ISSUE THREAD

**Issue by atmonshi** [laravel-filament/filament#7156]
### Package

filament/filament

### Package Version

v3

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

v8.1

### Problem description

when using the trait `Translatable` 
all fields will be translatable by adding `wire:model="data.en.status"`
which prevents saving any edits to the form

### Expected behavior

any columns not in the model:

```php
    public $translatable = [
        'name'
    ];
```

should not be translatable, and this was the default behavior in v2 

### Steps to reproduce

you can chack the pull request for more details
https://github.com/lara-zeus/test-fila-three/pull/2

add to a model
```php
use HasTranslations;
public $translatable = [
        'name'
    ];
```

follow the steps from the [docs](https://filamentphp.test/plugins/filament-spatie-translatable) to add Translatable trait to a rescoures and its pages

add an item, 
then edit none translatable field (in my repo, only name is translatable, and it saved normally but status will not be saved )

and refresh or check the database
the new data will not be saved

looks like all fields will have the lang prefex, but only tested on textinput and select

### Reproduction repository

https://github.com/lara-zeus/test-fila-three/pull/2

**Comment by atmonshi** [comment]
on v2:
```html
<select id="data.status" wire:model="data.status" dusk="filament.forms.data.status" class="">
    ...
</select>
```

on v3
```html
<select id="data.en.status" wire:model.live="data.en.status">
  ....
</select>
```

**Comment by danharrin** [comment]
The `.en.` prefix is deliberate, but it shouldn't make a difference to the actual functionality of the form. Only the translatable attributes will be saved in JSON.

**Comment by atmonshi** [comment]
I tested and updated the repo to beta7, still the same

I trace it to the function `function handleRecordUpdate` on the 
`EditRecord\Concerns\Translatable`

and its saving the data correctly 
```
$record->save();
dd($record); // the record actually saved in the database
```
but something doing another save after that with the old data and updating the database (the update_at has change again)
any idea!

**Comment by atmonshi** [comment]
hey @danharrin FINALLY found the missing part, adding to 

`spatie-laravel-translatable-plugin/src/Resources/Pages/EditRecord/Concerns/Translatable.php`

```php
public function getFormStatePath(): ?string
{
    return 'data';
}
```

also noticed some method has the comments
in `Filament\Resources\Pages\EditRecord` class

```php
/**
 * @internal Never override or call this method. If you completely override `save()`, copy the contents of this method into your override.
 */
```

but not copied to the `Translatable` trait

if this is the fix, a PR is ready :)

tested in textinput, select, and a repeater.

**Comment by danharrin** [comment]
That doesn't sound like the right fix, the state path should include the locale

**Comment by atmonshi** [comment]
ya, found this on another trait
```
public function getFormStatePath(): ?string
    {
        return "data.{$this->activeLocale}";
    }
```

**Comment by nielspeen** [comment]
I'm running into this problem too. Only on non-translatable fields of translatable resources. The translatable fields update correctly.

Hitting Save on a translatable form will first run the correct database query:

```update `pages` set `page_template_id` = '1',  `pages`.`updated_at` =...```

But then immediately after runs another query resetting non-translatable fields back to their original value:

```update `pages` set `page_template_id` = 2, `pages`.`updated_at` = '2023-07-30 19:34:13'...```

**Comment by LorisBalsamo** [comment]
> I'm running into this problem too. Only on non-translatable fields of translatable resources. The translatable fields update correctly.
> 
> Hitting Save on a translatable form will first run the correct database query:
> 
> `` update `pages` set `page_template_id` = '1', `pages`.`updated_at` =... ``
> 
> But then immediately after runs another query resetting non-translatable fields back to their original value:
> 
> `` update `pages` set `page_template_id` = 2, `pages`.`updated_at` = '2023-07-30 19:34:13'... ``

Same problem!
Here's a screenshot from Telescope.
![image](https://github.com/filamentphp/filament/assets/979680/a4dcf26b-5627-4a1a-b876-8d181ff2ae9e)

**Comment by nielspeen** [comment]
This work-around overrides the ```save()``` function and merges the correct data into all the translations. You can use it on your Edit pages until someone figures out a real fix.

```php
public function save(bool $shouldRedirect = true): void
    {
        $this->authorizeAccess();

        $originalData = $this->data;
        $originalActiveLocale = $this->activeLocale;

        $nonTranslatableData = Arr::except($originalData[$originalActiveLocale], $this->record->getTranslatableAttributes());

        try {
            foreach ($this->getTranslatableLocales() as $locale) {
                $this->setActiveLocale($locale);

                // Merge the original non-translatable data into this locale's data
                $this->data[$locale] = array_merge($this->data[$locale], $nonTranslatableData);

                /** @internal Read the DocBlock above the following method. */
                $this->validateFormAndUpdateRecordAndCallHooks();
            }
        } catch (Halt $exception) {
            return;
        }

        $this->data = $originalData;
        $this->setActiveLocale($originalActiveLocale);

        /** @internal Read the DocBlock above the following method. */
        $this->sendSavedNotificationAndRedirect(shouldRedirect: $shouldRedirect);
    }
```

**Comment by danharrin** [comment]
Should be fixed in next version

**Comment by LorisBalsamo** [comment]
> Should be fixed in next version

If I add an image fields, now it gives me error "The image field must be a file of type: image/*.", even if it saves the image.
This bug appeared after this modification.

**Comment by danharrin** [comment]
Please open a new issue with a reproduction repository
