### ISSUE TITLE
Wzard Steps Text Color issue

### ISSUE THREAD

**Issue by abishekrsrikaanth** [laravel-filament/filament#7163]
### Package

filament/forms

### Package Version

v3.0.0-beta4

### Laravel Version

v10.10

### Livewire Version

v3.0-beta.3

### PHP Version

8.2

### Problem description

I am using the standalone version of the Filament Forms and have the primary color set to Purple on the `AppServiceProvider`.

```php
 FilamentColor::register([
    'primary' => Color::Purple
]);
```

The labels on the wizard step don't show correct colors.

<img width="1056" alt="CleanShot 2023-07-23 at 23 29 08@2x" src="https://github.com/filamentphp/filament/assets/1639302/b7f6de01-199e-46f7-8090-5f7343eb584d">

### Expected behavior

The labels should render correctly based on the Primary color set and the other tabs should show the correct label colors

### Steps to reproduce

1. Dark mode enabled on the TALL app.
2. Set the Primary color to something other than the default on the `AppServiceProvider`
3. Add a wizard control with atleast 2 steps on a page.

### Reproduction repository

https://github.com/abishekrsriaanth/filament-test

**Comment by zepfietje** [comment]
The wizard is one of the final components that still need to be redesigned.
Thanks for bringing this to our attention though.
Will be fixed soon when I've revamped it.
