### ISSUE TITLE
Widget descriptionIcon "after" not showing

### ISSUE THREAD

**Issue by wychoong** [laravel-filament/filament#7165]
### Package

filament/filament

### Package Version

v3 beta4

### Laravel Version

10.15

### Livewire Version

3

### PHP Version

8.2

### Problem description

in StatsOverviewWidget
<img width="433" alt="image" src="https://github.com/filamentphp/filament/assets/67364036/b4f7a352-7457-47fd-b554-7307ad6d7b1b">

```html
<div class="fi-wi-stats-overview-card-description-icon h-5 w-5 text-custom-500" style="--c-500:var(--success-500);" name="heroicon-m-arrow-trending-up"></div>
```

### Expected behavior

show description icon color

### Steps to reproduce

```php
// from doc
  Card::make('Unique views', '192.1k')
                ->icon('heroicon-o-currency-dollar')
                ->description('asd')
                ->descriptionIcon('heroicon-m-arrow-trending-up')
                ->descriptionColor('success')
```

### Reproduction repository

-

**Comment by zepfietje** [comment]
It's by design and this has been the same in v2.

**Comment by wychoong** [comment]
the issue is due to prop renamed from `:name` to `:icon` for `filament::icon component`. fixed in the linked PR
