### ISSUE TITLE
Upgrade script is creating `AdminPanelProvider` class with calls to `env()`

### ISSUE THREAD

**Issue by pboivin** [laravel-filament/filament#7170]
### Package

filament/upgrade

### Package Version

3.x-dev

### Laravel Version

9.52.10

### Livewire Version

3.0.0-beta.3

### PHP Version

8.1.21

### Problem description

The `env()` function can be problematic outside of config files. From the [Laravel docs](https://laravel.com/docs/10.x/helpers#method-env) :

> If you execute the config:cache command during your deployment process, you should be sure that you are only calling the env function from within your configuration files. Once the configuration has been cached, the .env file will not be loaded and all calls to the env function will return null.

### Expected behavior

I'm not sure what the best solution would be. Maybe the values can be read from the existing `.env` during the upgrade?

### Steps to reproduce

```
git clone https://github.com/pboivin/filament-peek-demo --branch=1.x
cd filament-peek-demo
composer require filament/upgrade:"^3.0" --dev
./vendor/bin/filament-v3
```

### Reproduction repository

https://github.com/pboivin/filament-peek-demo

### Relevant output

```php
class AdminPanelProvider extends PanelProvider
{
    public function panel(Panel $panel): Panel
    {
        return $panel
            ->default()
            ->id('admin')
            ->path(env('FILAMENT_PATH', 'admin'))
            ->domain(env('FILAMENT_DOMAIN'))
            // ...
```

**Comment by danharrin** [comment]
Should be fixed in the next version
