### ISSUE TITLE
Problem after creating new panel

### ISSUE THREAD

**Issue by valpuia** [laravel-filament/filament#7172]
### Package

filament/filament

### Package Version

v3.0.0-beta7

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

v8.2

### Problem description

After generate new panel using [docs](https://beta.filamentphp.com/docs/3.x/panels/configuration/#creating-a-new-panel) if you switch to new panel then try to logout from new app.

Also happens before login, switch to new panel using url.

This can be fixed after putting `->login()` inside newPanelServiceProvider configuration. so, suggest to auto put `->login()` while generating/create new panel

### Expected behavior

No error

### Steps to reproduce

Generate new panel, logout from existing panel and navigate new panel using url (without login)

If you clone this project then
1. install and serve
2. navigate to `{url}/agent`

If you go to `{url}/app` then it's working because I put `->login()` inside configuration, but if you try `/agent` then this problem came

### Reproduction repository

https://github.com/valpuia/filament-v3

### Relevant log output

```shell
Filament\Http\Middleware\Authenticate::redirectTo(): Return value must be of type string, null returned
```

**Comment by zepfietje** [comment]
This is designed behavior.

**Comment by nekulin** [comment]
How to solve this problem ?

**Comment by valpuia** [comment]
> How to solve this problem ?

Put `->login()` inside YournewAppServiceProvider
