### ISSUE TITLE
Cannot reorder navigation groups

### ISSUE THREAD

**Issue by datlechin** [laravel-filament/filament#7183]
### Package

filament/filament

### Package Version

beta

### Laravel Version

latest

### Livewire Version

beta

### PHP Version

PHP 8.2

### Problem description

Like in the docs said to reordering the navigation groups by pass an array to `->navigationGroup()` https://beta.filamentphp.com/docs/3.x/panels/navigation#ordering-navigation-groups

But it not working

<img width="960" alt="image" src="https://github.com/filamentphp/filament/assets/56961917/16b7cac6-fba4-40b3-9678-a38f02918be7">

```
$panel
    ->navigationGroups([
        NavigationGroup::make()
            ->label(__('Courses')),
        NavigationGroup::make()
            ->label(__('Administration')),
    ])
    ->navigationGroups([
        'Courses',
        'Administration',
    ])
```

### Expected behavior

Reordering the navigation group

### Steps to reproduce

pass an array to `navigationGroups()`

### Reproduction repository

https://github.com/datlechin/filament-navigation-group

**Comment by zepfietje** [comment]
Please provide the requested repo, then we'll reopen the issue if you let us know.

**Comment by leandrocfe** [comment]
@datlechin
why are you using twice?

just use
```php
->navigationGroups([
    'Blog',
    'Administration',
])
```

**Comment by zepfietje** [comment]
Then it works without issues, @leandrocfe?

**Comment by leandrocfe** [comment]
> ```
> ->navigationGroups([
>     'Blog',
>     'Administration',
> ])
> ```

yes @zepfietje !

**Comment by zepfietje** [comment]
Perfect.
Thanks for jumping in, @leandrocfe!

Not a bug then.

**Comment by AkramNAKTI** [comment]
```
->navigationGroups([
    'Blog',
    'Administration',
])
```
is the solution when we have just one language in the system
But no solution for multi-languages 
```
->navigationGroups([
    __('nav.blog'),
    __('nav.administration'),
])
```
This way not working

**Comment by christopheraseidl** [comment]
@AkramNAKTI, I had the same problem and found the solution [here](https://github.com/filamentphp/filament/discussions/6210#discussioncomment-8390834). All we have to do is use a closure; so simple!
