### ISSUE TITLE
RelationManager table header is not using $pluralModelLabel

### ISSUE THREAD

**Issue by mokhosh** [laravel-filament/filament#7192]
### Package

filament/filament

### Package Version

* v3.0.0-beta9

### Laravel Version

* v10.15.0

### Livewire Version

* v3.0.0-beta.3

### PHP Version

* 8.2.7

### Problem description

The table header for `RelationManager`s is not using `$pluralModelLabel` and just shows the default name which is derived from resource name.

### Expected behavior

The table header should use `$pluralModelLabel` which was the v2 behaviour.

### Steps to reproduce

1. install filament v3
1. create a user resource
2. create a role mode, migration and resource, and relationship on the user model
3. override protected static ?string $pluralModelLabel = 'Not Roles';
4. browse the users page
5. the table header for relation manager at the bottom of the page still says "Roles", this is the bug

### Reproduction repository

https://github.com/mokhosh/filament-v3-bug-reproduction

**Comment by zepfietje** [comment]
This behavior is deprecated and you should now set the table header using the `table()` method directly.

If this is actually a bug in backwards compatibility, @danharrin will reopen this issue.

**Comment by danharrin** [comment]
Yup, the table heading is derived from `$title` or `getTitle()` which also controls the tab

**Comment by mokhosh** [comment]
Ok I think it should still work, cause "deprecated" shouldn't mean "broken", right?

And the new method is not working either https://github.com/filamentphp/filament/issues/7209

**Comment by danharrin** [comment]
the plural model label is not just for the title

**Comment by mokhosh** [comment]
Pardon?

**Comment by danharrin** [comment]
the plural model label is used in more placed than just the title, it is used for other text as well

**Comment by mokhosh** [comment]
I understand that, but is it used in "more places" which implies that it should still work here, or will it be used exclusively in other places?

If it's the second case, what's the new way of achieving this?
I thought it's the method on the table, but that seems to be the same thing.

Is it the $title property? Or is it another method on the table?

**Comment by zepfietje** [comment]
Dan will look into this later. 👍
Thanks for your patience.

**Comment by danharrin** [comment]
Reopening so I dont forget about it, but I can't guarantee that it will be looked into anytime soon. The docs should be correct on how to customize this text.

**Comment by majdghithan** [comment]
use this

`public static function getTitle(Model $ownerRecord, string $pageClass): string
    {
        return __('resources.posts');
    }`

**Comment by majdghithan** [comment]
use this:
`
public static function getTitle(Model $ownerRecord, string $pageClass): string
    {
        return __('resources.posts');
    }
`

**Comment by danharrin** [comment]
Investigated this. The reason why it isn't used in the table header, is because you may have more than one relation manager for the same model. In that case, the `modelLabel()` would be the same for each relation manager, but you'd want to differentiate between relation managers. Maybe `ApprovedCommentsRelationManager` and `SpamCommentsRelationManager`, each with `Approved comments` and `Spam comments` as the title. The relationships might be different, `approvedComments` and `spamComments`, so the titles should be different based on that.

**Comment by mokhosh** [comment]
Makes sense @danharrin 
But wouldn't it also make sense if it falls through if label is `null` on the `RelationManager` and it is overridden on the `Resource`? For many cases where you only have one relationship with another model?

**Comment by danharrin** [comment]
I don't understand how the Resource has anything to do with it? Everything is contained in the RelationManager

**Comment by mokhosh** [comment]
@danharrin ok it's been a while and I had forgotten the exact issue.

I reproduced it and the issue is still there. 

Even if you set `->pluralModelLabel('SOMETHING')` on the table, it won't be used as the header of the table. which should not be the case.

I dove into `Table` class and it's views to find that you have to set it with `->header('SOMETHING')` which I couldn't find in the docs either.

I think the table header should use `pluralModelLabel`, at least the method that is encouraged to be used on the table, if not the deprecated property too.

Also, isn't the property unique for every relation manager? So, the issue that you mentioned will never happen. Because you will have different plural label properties in `ApprovedCommentsRelationManager` and `SpamCommentsRelationManager` right?

**Comment by danharrin** [comment]
> Even if you set ->pluralModelLabel('SOMETHING') on the table, it won't be used as the header of the table. which should not be the case.

This isn't right though, the heading is not generated from the plural label, it's generated from the name of the relationship

The plural label is used for bulk actions and empty state

For `ApprovedCommentsRelationManager` and `SpamCommentsRelationManager`, label would be `comment` and plural would be `comments`, otherwise it would be way too long in multiple places

**Comment by mokhosh** [comment]
Ok cool. I'll check if that's in the docs and otherwise will try to make a PR to make it clear.
