### ISSUE TITLE
HTML render issue

### ISSUE THREAD

**Issue by vikramparihar** [laravel-filament/filament#7199]
### Package

filament/filament

### Package Version

v2.X

### Laravel Version

^8.65

### PHP Version

PHP 8.1

### Problem description

In Filament 2.x html is not parsing properly. 
The issue is only those page where we have form fields.
![image](https://github.com/filamentphp/filament/assets/5202442/9f0e525c-ff38-407c-a4c9-2091ac90c0c0)

![image](https://github.com/filamentphp/filament/assets/5202442/9dc66ccd-2290-44b3-8ee6-519048feecbd)

### Expected behavior

The page should be render the output html

### Steps to reproduce

Just install the filament project via composer.
And Livewire is also installed for my frontend application

### Reproduction repository

https://github.com/vikramparihar

**Comment by danharrin** [comment]
No reproduction repo, please submit one as per our instructions.
