### ISSUE TITLE
Command make:filament-user failed

### ISSUE THREAD

**Issue by lepresk** [laravel-filament/filament#7207]
### Package

filament/filament

### Package Version

^3.0

### Laravel Version

10.10

### PHP Version

8.1.12

### Problem description

According to the doc, the command `make:filament-user` allow to create a new user account, but it failled with "Call to a member function auth() on null" error

```bash
$ php artisan make:filament-user

   Error

  Call to a member function auth() on null

  at vendor\filament\filament\src\FilamentManager.php:46
     42▕     protected ?Model $tenant = null;
     43▕
     44▕     public function auth(): Guard
     45▕     {
  ➜  46▕         return $this->getCurrentPanel()->auth();
     47▕     }
     48▕
     49▕     public function bootCurrentPanel(): void
     50▕     {

  1   vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:353
      Filament\FilamentManager::auth()

  2   vendor\filament\filament\src\Commands\MakeUserCommand.php:56
      Illuminate\Support\Facades\Facade::__callStatic("auth", [])
```

### Expected behavior

make:filament-user must create a new user account without error

### Steps to reproduce

- Create fresh laravel project on Windows `composer create-project laravel/laravel project`
- Change minimum stability to "dev" inside `composer.json`
- Install filament `composer require filament/filament:"^3.0"`
- Run `php artisan make:filament-user`

### Reproduction repository

https://github.com/lepresk/filament-bug

### Relevant log output

```shell
$ php artisan make:filament-user

   Error

  Call to a member function auth() on null

  at vendor\filament\filament\src\FilamentManager.php:46
     42▕     protected ?Model $tenant = null;
     43▕
     44▕     public function auth(): Guard
     45▕     {
  ➜  46▕         return $this->getCurrentPanel()->auth();
     47▕     }
     48▕
     49▕     public function bootCurrentPanel(): void
     50▕     {

  1   vendor\laravel\framework\src\Illuminate\Support\Facades\Facade.php:353
      Filament\FilamentManager::auth()

  2   vendor\filament\filament\src\Commands\MakeUserCommand.php:56
      Illuminate\Support\Facades\Facade::__callStatic("auth", [])
```

**Comment by lepresk** [comment]
After investigation, the bug is caused by the fact that the `AdminPanelProvider` doesn't register automatically in `config/app.php` after installation using the `artisan filament:install --panels` command. Adding the `AdminPanelProvider` to the list of providers in `config/app.php` resolves the issue.

Note: This step of manually registering the `AdminPanelProvider` is not mentioned in the documentation.

**Comment by danharrin** [comment]
Are you definitely on the latest beta version? Check with `php artisan about`

**Comment by lepresk** [comment]
My bad 🤦‍♂️

**Comment by ana-lisboa** [comment]
I just had the same issue on V3.0.0
> fresh laravel install
> install filament v3 (failed)
> changed minimum stability on composer.json for dev
> re-ran command to install filament
> php artisan filament:install --scaffold
> php artisan make:filament-user

and then the error

**Comment by EngOmarSoudi** [comment]
php artisan filament:install --panels

  What is the ID? [admin]
❯ "admin"
don't write numbers
