### ISSUE TITLE
pluralModelLabel method not working on RelationManagers

### ISSUE THREAD

**Issue by mokhosh** [laravel-filament/filament#7209]
### Package

filament/filament

### Package Version

* v3.0.0-beta10

### Laravel Version

* v10.16.0

### Livewire Version

* v3.0.0-beta.4

### PHP Version

* 8.2.7

### Problem description

In this issue I reported that `$pluralModelLabel` is not working.
https://github.com/filamentphp/filament/issues/7192

You mentioned that it's deprecated, and I changed to the new recommended way of doing this:
```php
return $table
    ->pluralModelLabel('Not Rules');
```
And it's still not working.

### Expected behavior

The title of the table should change when you try to change it.

### Steps to reproduce

1. install filament v3
1. create a user resource
1. create a role mode, migration and resource, and relationship on the user model
1. use the method `pluralModelLabel('Not Roles');` on `$table`
1. browse the users page
1. the table header for relation manager at the bottom of the page still says "Roles", this is the bug

### Reproduction repository

https://github.com/mokhosh/filament-v3-bug-reproduction

**Comment by leandrocfe** [comment]
what about this?

```php
->heading('Badges')
->modelLabel('Badge')
```

**Comment by zepfietje** [comment]
Let's continue discussion on the original issue, @mokhosh. 🙂
https://github.com/filamentphp/filament/issues/7192#issuecomment-1650379559

**Comment by mokhosh** [comment]
@zepfietje  sorry i thought this is the new recommended way and it makes it a separate issue 🙏

**Comment by zepfietje** [comment]
Since it's very closely related to the initial issue, I'd rather keep it all there. 👍
