### ISSUE TITLE
Default panels do not function

### ISSUE THREAD

**Issue by Jamesking56** [laravel-filament/filament#7220]
### Package

filament/filament

### Package Version

v3.0.0-beta10

### Laravel Version

v10.16.1

### Livewire Version

v3.0.0-beta.4

### PHP Version

PHP 8.2.8

### Problem description

When creating a panel and changing the path to remove the prefix (so its default at `/`), following the documentation here: https://beta.filamentphp.com/docs/3.x/panels/configuration#changing-the-path

An exception occurs after logging into this newly default panel:

![image](https://github.com/filamentphp/filament/assets/253237/e434f5d7-f1b0-4667-b686-f501d18b0cdf)

### Expected behavior

The panel shows the default dashboard since I haven't done anything else yet.

### Steps to reproduce

1. Install Filament v3.0.0beta10
2. Create a new panel with `php artisan make:filament-panel dashboard`
3. Change `->path('dashboard')` to `->path('')` in the new panel service provider
4. Create a filament user if you don't have one already with `php artisan make:filament-user`
5. Go to `http://localhost/login` and login with your new filament user's details
6. :boom: exception should occur

### Reproduction repository

https://github.com/Jamesking56/filament-bug

**Comment by zepfietje** [comment]
Not sure if this fixes the issue, but could you try updating your namespaces in the `AdminPanelProvider` config methods (like `discoverPages()`) to be scoped to admin?

`App\\Filament\\Admin\\Pages`

**Comment by Jamesking56** [comment]
> Not sure if this fixes the issue, but could you try updating your namespaces in the `AdminPanelProvider` config methods (like `discoverPages()`) to be scoped to admin?
> 
> `App\\Filament\\Admin\\Pages`

Doesn't seem to fix the  issue.

Even if I completely remove `AdminPanelProvider.php` and comment it out of `config/app.php` then the exception still occurs.

**Comment by Jamesking56** [comment]
I have found a fix for the issue @zepfietje 

Its because I still have the Laravel default web route registered in `routes/web.php`:

```php
Route::get('/', function () {                                                                                                                                                                      
    return view('welcome');                                                                                                                                                                        
});
```

As soon as I remove this, it fixes the problem.

Is there a way that Filament can automatically remove this or override it properly?

**Comment by zepfietje** [comment]
Ah, of course.
You should always make sure there's no route collisions.

Not something Filament can/should handle.
