### ISSUE TITLE
Route [login] not defined

### ISSUE THREAD

**Issue by nekulin** [laravel-filament/filament#7223]
### Package

filament/filament

### Package Version

v3.0.0

### Laravel Version

^10.10

### PHP Version

PHP 8.1

### Problem description

```
Route [login] not defined.
```

### Expected behavior

Login page

### Steps to reproduce

php artisan make:filament-panel app

get http://site/app

### Reproduction repository

http://site/app

**Comment by zmiulan** [comment]
Just add `login()` to your panel provider

```
class AppPanelProvider extends PanelProvider
{
    public function panel(Panel $panel): Panel
    {
        return $panel
            ->id('app')
            ->path('')
            ->login()    <=== add this
```

Take a look in docs - https://beta.filamentphp.com/docs/3.x/panels/users/#authentication-features

**Comment by dpenacton** [comment]
🛠 **Trouble with Export/Import Functionality in Laravel Filament Admin Panel: 'Login Route Not Found' Error**

I've been tackling the export/import feature, aiming for smooth functionality. However, upon attempting to export or import a CSV, it seems to generate within the notifications. Yet, when I endeavor to download the file, a persistent 'login route not found' error arises.

![Screenshot](https://img.enacton.com/ShareX/2024/04/w4FMvKPUQJ.png)

I've configured separate guards for authentication, catering to both admin and user panels. Additionally, I've ensured that the export/import policy is correctly set to return true within the view function.

Furthermore, I've diligently included `Export::polymorphicUserRelationship();` in the app service provider and executed all requisite database changes.

Despite these efforts, I find myself still grappling with the 'login route not found' issue when attempting to access export/import. Any suggestions on resolving this within the Laravel Filament admin panel?

**Comment by kasangasj** [comment]
> 🛠 **Trouble with Export/Import Functionality in Laravel Filament Admin Panel: 'Login Route Not Found' Error**
> 
> I've been tackling the export/import feature, aiming for smooth functionality. However, upon attempting to export or import a CSV, it seems to generate within the notifications. Yet, when I endeavor to download the file, a persistent 'login route not found' error arises.
> 
> ![Screenshot](https://camo.githubusercontent.com/03cc1007b9aa156c0b3d0d96909ba5a1a274a25b21b57016b444578c48a33e49/68747470733a2f2f696d672e656e6163746f6e2e636f6d2f5368617265582f323032342f30342f7734464d764b5055514a2e706e67)
> 
> I've configured separate guards for authentication, catering to both admin and user panels. Additionally, I've ensured that the export/import policy is correctly set to return true within the view function.
> 
> Furthermore, I've diligently included `Export::polymorphicUserRelationship();` in the app service provider and executed all requisite database changes.
> 
> Despite these efforts, I find myself still grappling with the 'login route not found' issue when attempting to access export/import. Any suggestions on resolving this within the Laravel Filament admin panel?

Did you find a solution for this?

**Comment by alisalehi1380** [comment]
> 🛠 **Trouble with Export/Import Functionality in Laravel Filament Admin Panel: 'Login Route Not Found' Error**
> 
> I've been tackling the export/import feature, aiming for smooth functionality. However, upon attempting to export or import a CSV, it seems to generate within the notifications. Yet, when I endeavor to download the file, a persistent 'login route not found' error arises.
> 
> ![Screenshot](https://camo.githubusercontent.com/29a9a98e9a5fe83b4fe3fdb6a1a13f66f4b10e1f8acebd9f1abf06bb6b7219f7/68747470733a2f2f696d672e656e6163746f6e2e636f6d2f5368617265582f323032342f30342f7734464d764b5055514a2e706e67)
> 
> I've configured separate guards for authentication, catering to both admin and user panels. Additionally, I've ensured that the export/import policy is correctly set to return true within the view function.
> 
> Furthermore, I've diligently included `Export::polymorphicUserRelationship();` in the app service provider and executed all requisite database changes.
> 
> Despite these efforts, I find myself still grappling with the 'login route not found' issue when attempting to access export/import. Any suggestions on resolving this within the Laravel Filament admin panel?

any update?

**Comment by updatedData** [comment]
What helped me beeing able to log in again:

 Delete app/Providers/Filament/AdminPanelProvider.php

run composer require filament/filament:"^3.3" -W
run artisan filament:install --panels
