### ISSUE TITLE
ToggleColumn has a redundant empty tooltip

### ISSUE THREAD

**Issue by mokhosh** [laravel-filament/filament#7227]
### Package

filament/filament

### Package Version

* v3.0.0-beta11

### Laravel Version

* v10.16.1 

### Livewire Version

* v3.0.0-beta.4

### PHP Version

* 8.2.7

### Problem description

The toggle has an empty tooltip which doesn't go away by setting `->tooltip(false)` on it.

### Expected behavior

The toggle shouldn't have an empty tooltip.

### Steps to reproduce

Just add a `ToggleColumn` to a newly created resource.

### Reproduction repository

https://github.com/mokhosh/filament-v3-bug-reproduction

**Comment by zepfietje** [comment]
Thanks for reporting.
The toggle column is one of the final things I'm still revamping.
I've immediately fixed the issue though: https://github.com/filamentphp/filament/commit/213002174ca3cbfc707b48ea19263e53a114e329.
