### ISSUE TITLE
Broken styles when using Tables\Group 

### ISSUE THREAD

**Issue by TheAaronLawrence** [laravel-filament/filament#7231]
### Package

filament/filament

### Package Version

v3.0@beta

### Laravel Version

10

### Livewire Version

v3

### PHP Version

php 8.2

### Problem description

<img width="1271" alt="Screenshot 2023-07-26 at 17 22 52" src="https://github.com/filamentphp/filament/assets/91675986/e71eff12-7b98-4329-aba7-aaad823d24da">

Styling on table row when using the group is showing classes as text and not rendered as html

### Expected behavior

Expected to be rendered as HTML

### Steps to reproduce

Use table grouping

### Reproduction repository

https://github.com/unable

**Comment by danharrin** [comment]
Upgrade Filament, but please submit a reproduction in the future.
