### ISSUE TITLE
deleteAbandonedFiles somehow deletes the uploaded image with spatie media library

### ISSUE THREAD

**Issue by Saifallak** [laravel-filament/filament#7233]
### Package

filament/filament

### Package Version

v3 beta 11

### Laravel Version

10

### Livewire Version

3

### PHP Version

8.2

### Problem description

cant save images in spatie file upload 

after digging i found

deleteAbandonedFiles somehow deletes the uploaded image with spatie media library

### Expected behavior

to save correctly

### Steps to reproduce

add field and upload image

i will ad re-produce repo soon, when i get to office tomorrow.

### Reproduction repository

https://github.com/aquadic

**Comment by zepfietje** [comment]
Please provide a real reproduction repository.
Let us know when you have and we'll reopen the issue.

**Comment by Saifallak** [comment]
> Please provide a real reproduction repository. Let us know when you have and we'll reopen the issue.

i will add later today, just added the issue so i can remember to do that.

**Comment by zepfietje** [comment]
Alright, next time please only open the issue when you also add a reproduction repository right away. Otherwise maintainers have to waste time looking at issues without reproduction. Nothing personal, it just happens a lot. Thanks!
