### ISSUE TITLE
Chart widgets are not scaling down properly at small breakpoints

### ISSUE THREAD

**Issue by richeklein** [laravel-filament/filament#7235]
### Package

filament/filament

### Package Version

v3.0.0-beta15

### Laravel Version

v10.16.1

### Livewire Version

v3

### PHP Version

8.2

### Problem description

Chart widgets on the dashboard are not scaling properly at small breakpoints. This is based on the example code on https://beta.filamentphp.com/docs/3.x/panels/getting-started/#creating-a-chart-widget — with no customizations.

- ![Screenshot 2023-07-26 at 5 02 43 PM](https://github.com/filamentphp/filament/assets/99479/6bad26bd-c3d3-4d6b-aef2-00deea29d225)

### Expected behavior

The chart should scale down responsively, like Filament 2.
![Screenshot 2023-07-26 at 5 02 59 PM](https://github.com/filamentphp/filament/assets/99479/185748d0-1b88-47c0-8043-bfbfcb59c7e2)

### Steps to reproduce

Following the documentation example at https://beta.filamentphp.com/docs/3.x/panels/getting-started/#creating-a-chart-widget.

### Reproduction repository

https://github.com/richeklein/filament3-chart-scaling

**Comment by zepfietje** [comment]
Thanks for reporting, @richeklein!
Have you been able to find the cause of it?

**Comment by zepfietje** [comment]
Fixed https://github.com/filamentphp/filament/commit/ecb14ee5fcd0a03821fd1205c0318f5377ff022d.

**Comment by richeklein** [comment]
Thanks for the quick update! I noticed a color change in the chart, but the scaling still seems janky. My guess is that it's related to the grid auto-columns and the canvas widths, but I'm not 100% sure. I noticed that Filament 2 used Flexbox. Here's a [screen recording](https://share.getcloudapp.com/rRuzz1z1), so you can get see exactly what happens at the various breakpoints. Hope this helps and thanks for all of your amazing (and very hard) work on Filament 3. 🙏

Note: I'm running beta17 now.

Here are some screenshots as well:
![Screenshot 2023-07-27 at 10 05 07 AM](https://github.com/filamentphp/filament/assets/99479/74831888-7f06-4f8b-b8e1-361e04e29ff5)
![Screenshot 2023-07-27 at 10 05 17 AM](https://github.com/filamentphp/filament/assets/99479/9e7af31f-83f8-4abc-a92e-01d3834af9d0)

**Comment by zepfietje** [comment]
No new beta has been released since this fix, so please pull in 3.x to check, @richeklein.

**Comment by RoseRiyadh** [comment]
I have the same problem but in the downwards direction, is there any fix to that?
