### ISSUE TITLE
[2.x] Error on the date input if the current value is before min.

### ISSUE THREAD

**Issue by henriquecm** [laravel-filament/filament#725]
### Package

filament/forms

### Package Version

2.4.10

### Laravel Version

8.69

### Livewire Version

2.72

### PHP Version

8.0

### Bug description

Date Picker doesn't work if initial value is before min value.
The input won't display the current vale, and the dropdown won't work.

### Steps to reproduce

Set on the form data the initial date to be yesterday or earlier.
Create a date input.
Set the min date to be today.

**Comment by danharrin** [comment]
I cannot reproduce this from your instructions. Please post code / relevant log output.

https://user-images.githubusercontent.com/41773797/143413837-a17957f8-4275-4ee2-867f-fdbd6dc6a865.mov

**Comment by henriquecm** [comment]
I think this is better than the steps I gave before.

Also, the value saved on the database is of the type date YYYY-MM-DD.

![filament-form-date](https://user-images.githubusercontent.com/15136037/143449661-f81acd79-7416-4cf6-9bbc-edb576e62380.png)

**Comment by danharrin** [comment]
Just tried this again, cannot reproduce it unfortunately :(

I've tried it in many different ways, and none of them produce an error.

Please make sure that you're using the latest version of Filament, and that your JS has been compiled up to date.
