### ISSUE TITLE
MakePageCommand creates pages in /Resources

### ISSUE THREAD

**Issue by JohnnyEvo** [laravel-filament/filament#7261]
### Package

filament/filament

### Package Version

v3.0.0-beta17

### Laravel Version

v10.16.1

### PHP Version

PHP 8.2.8

### Problem description

When I run MakePageCommand without Resource argument, the two pages is creating in /Resources directory of the Filament directory.

### Expected behavior

The documentation says : 
> This command will create two files - a page class in the /Pages directory of the Filament directory, and a view in the /pages > directory of the Filament views directory.

### Steps to reproduce

Execute command from terminal : 

```sh
php artisan make:filament-page Settings
```

### Reproduction repository

https://github.com/JohnnyEvo/filament-sandbox

**Comment by danharrin** [comment]
Fixed in the next release
