### ISSUE TITLE
Database notifications component does not listen to DatabaseNotificationsSent event

### ISSUE THREAD

**Issue by damiandejong** [laravel-filament/filament#7262]
### Package

filament/filament

### Package Version

v3.0.0-beta2

### Laravel Version

v.9.52.10

### Livewire Version

v3.0.0-beta.1

### PHP Version

PHP 8.2.7

### Problem description

After I installed the broadcasting functionality (via Pusher) for Filament correctly, the database notifications component does not listen to the broadcast event that a database notification is sent, which should refresh the component. The broadcast functionality was setup properly as a broadcast notification is received. In addition, the `database-notifications.sent` event is received in Pusher.

### Expected behavior

The expectation is that the database notifications component is refreshed after the event dispatches.

### Steps to reproduce

For the reproduction repository:
- Setup the repository as with the regular Filament Demo
- Add working Pusher keys to the `.env` file
- Go to the dashboard
- Push the button 'Send notification'
- You can see that nothing happens. If you refresh the page, you'll see that the notification was sent
- When you manually call `window.dispatchEvent(new CustomEvent('EchoLoaded'))` and you push the button again, the component will refresh properly

### Reproduction repository

https://github.com/damiandejong/filament-echo

**Comment by damiandejong** [comment]
See #7263 for a possible fix.

**Comment by danharrin** [comment]
Fixed by #7263
