### ISSUE TITLE
Rename helper text to description and support position

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#7265]
Option to show helper text below label instead of below field.

https://github.com/filamentphp/filament/discussions/4333#discussioncomment-6419262
https://github.com/filamentphp/filament/pull/7258

**Comment by danharrin** [comment]
Form fields:
- `hint()` -> `textAsideLabel()` / `textBelowLabel()` for inline layouts
- `hintActions()` -> `actionsAsideLabel()` / `actionsBelowLabel()` for inline layouts
- `hintColor()` -> `textAsideLabelColor()` / `textBelowLabelColor()` for inline layouts
- `hintIcon()` -> `iconAsideLabel()` / `iconBelowLabel()` for inline layouts
- `hintIconTooltip()` -> `iconAsideLabelTooltip()` / `iconBelowLabelTooltip()` for inline layouts
- `helperText()` -> `textBelowField()`

Infolist entries:
- `hint()` -> `textAsideLabel()` / `textBelowLabel()` for inline layouts
- `hintActions()` -> `actionsAsideLabel()` / `actionsBelowLabel()` for inline layouts
- `hintColor()` -> `textAsideLabelColor()` / `textBelowLabelColor()` for inline layouts
- `hintIcon()` -> `iconAsideLabel()` / `iconBelowLabel()` for inline layouts
- `hintIconTooltip()` -> `iconAsideLabelTooltip()` / `iconBelowLabelTooltip()` for inline layouts
- `helperText()` -> `textBelowContent()`

**Comment by danharrin** [comment]
Gonna push this to v4, otherwise it could result in quite a lot of internal tech debt if implemented in a BC way. Especially to do with custom form fields / infolist entries.

**Comment by zepfietje** [comment]
In my opinion, `helper text` can just be renamed to `description` with an option for position like `below field` and `above field`.

Or am I missing something?

**Comment by faizananwerali** [comment]
any update?

**Comment by ralphjsmit** [comment]
It would be cool to have an extra option to show text below the label, but I personally don't see the reason to rename these methods (helperText -> description would be the only one I could understand). These methods are used in basically every Filament app and everyone is now used to helperText and hint. Even if you keep the old methods supported by aliasing them to the new method, every single Filament project in existence would now suddenly have a code chore to remove these deprecations.

**Comment by faizananwerali** [comment]
Are there any pull requests to resolve this issue?

**Comment by ralphjsmit** [comment]
I don't think, I just saw this on roadmap for "at some point".

**Comment by ringform** [comment]
For anyone finding this just now, refer to [these functions](https://github.com/filamentphp/filament/pull/13327/commits/2d83c51befc21a9346bfc408285a2e115aeb520c#diff-a16ad6be11f6f6031b01948f0770bfe1d8d69dfe8eae637082485f2e82e1dc18R109).

To put the "helper text" right below the label, use `aboveContent()` instead of `helperText()`.
