### ISSUE TITLE
Filament::getTenant() return null

### ISSUE THREAD

**Issue by mstfkhazaal** [laravel-filament/filament#7284]
### Package

filament/filament

### Package Version

v3.0.0-beta21

### Laravel Version

v10.0.0

### Livewire Version

v3.0.0

### PHP Version

php 8.0.0

### Problem description

Filament::getTenant() return null

### Expected behavior

Get Tenant

### Steps to reproduce

None

### Reproduction repository

https://github.com/mstfkhazaal

**Comment by kurucu** [comment]
I'm now getting the same - and its when I use it as follows, in the SparkServiceProvider, for Spark:

```php
Spark::billable(Team::class)->resolve(function (Request $request) {
    return Filament::getTenant();
});
```
