### ISSUE TITLE
I cannot access to auth()->user() in panel

### ISSUE THREAD

**Issue by mstfkhazaal** [laravel-filament/filament#7288]
### Package

filament/filament

### Package Version

v3.0.0-beta21

### Laravel Version

v10.0.0

### Livewire Version

v3.0.0

### PHP Version

8.2.4 

### Problem description

`auth()->user() ` return null in panel
```
class AdminPanelProvider extends PanelProvider
{
    public function panel(Panel $panel): Panel
    {
        dd(auth()->user());// Null
        return $panel
            ->default()
            ->id('admin')
            ->path('admin')
            ->login()
```

### Expected behavior

Get User normaly

### Steps to reproduce

i try using Filament::serving
I get th ressult but i need to check user info inside the panel
Filament::serving(fn() => dd(auth()->user());

### Reproduction repository

https://github.com/mstfkhazaal/test

**Comment by zepfietje** [comment]
Use a callback in the function inside which you need to access the user.

**Comment by mstfkhazaal** [comment]
> Use a callback in the function inside which you need to access the user.

How?
My Problem i need to get data for userMenuItems
```
if(auth()user()->isAdmin){
  ->userMenuItems([
                        'account' => MenuItem::make()->url( route('admin),auth()->user->getTenant());
                    ]);
                    }
```

**Comment by dlespinosa365** [comment]
you can use the navigaton method 
![image](https://github.com/filamentphp/filament/assets/17776950/a5fd05c1-c535-4e94-9a06-2aaa98d58937)

**Comment by Tklaversma** [comment]
Any update on this? We can't get the user object of who is logged in at the moment in the `AdminPanelProvider`.

**Comment by leandrocfe** [comment]
> Any update on this? We can't get the user object of who is logged in at the moment in the `AdminPanelProvider`.

This session is initialized in middleware. If you’re looking for an alternative approach, consider creating a custom middleware and add it in the AdminPanelProvider. Inside that middleware, you can access `auth()->user()` / `filament()->getCurrentPanel()` to achieve what you need.

**Comment by Tklaversma** [comment]
@leandrocfe thanks, got it working:

AdminPanel:

```php
class AdminPanelProvider extends PanelProvider
{
    public function panel(Panel $panel): Panel
    {
        return $panel
            ->default()
            ->middleware([
                ...
                AddUserMenuItems::class,
                ...
            ])

            ...
    }
```

Middleware:

```php
<?php

class AddUserMenuItems
{
    public function handle(Request $request, Closure $next): Response
    {
        if (!auth()->check()) {
            return $next($request);
        }

        filament()->getCurrentPanel()->userMenuItems([
            MenuItem::make()
                    ->label('Profile')
                    ->url(
                        EditUserFilament::getUrl([
                            'record' => auth()->user()->id,
                        ])
                    ),
        ]);

        return $next($request);
    }
}
```
