### ISSUE TITLE
Improve chart widget header

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#7293]
Chart widget filter select should maybe have negative y margin to align heading with chart widgets without filter.

Potentially add divider like on section cards.

**Comment by KartikWatts** [comment]
Hi @zepfietje I have been using Filament in many of my projects and have just gone through the Contribution guides and would really love to contribute.
In fact, I have already been analyzing the issue, can you please assign this issue to me if feasible. Regards.

Also, during the analysis, I got somewhat confused, as both the headings without filter and with filter seem to be aligned properly in all screen sizes (as marked by yellow lines in the screenshot attached), just want to confirm I'm looking into the correct place, can you kindly confirm that as well. Thanks a lot.

![Screenshot_493](https://github.com/filamentphp/filament/assets/22623256/0a07240a-1044-4e77-8705-1330fe418678)

**Comment by zepfietje** [comment]
Thanks for bringing this up, @KartikWatts!
In fact, I fixed this already during a refactor before v3 was released.
So should be all good!

**Comment by KartikWatts** [comment]
@zepfietje That's great. If there is any other active confirmed issue you feel I can work on, can you please assign it to me, that would be really awesome. 
I have been working with all the tech stack: PHP, Laravel, Javascript

**Comment by zepfietje** [comment]
Maybe have a look at the open issues tagged `ui`?
You could work on something like https://github.com/filamentphp/filament/issues/7410 potentially?
