### ISSUE TITLE
Extract toggle component and improve design

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#7295]
- [ ] `forms/resources/views/components/toggle.blade.php`
- [ ] `tables/resources/views/columns/toggle-column.blade.php`

**Comment by damms005** [comment]
Does this take care of the current [latency/entagnlement issue](https://discord.com/channels/883083792112300104/1268943554630127617/1268943554630127617) or out of scope?

**Comment by zepfietje** [comment]
> Does this take care of the current [latency/entagnlement issue](https://discord.com/channels/883083792112300104/1268943554630127617/1268943554630127617) or out of scope?

Unrelated to this issue.

**Comment by zepfietje** [comment]
@danharrin could you point me at the commits so I can check what still has to be done (if anything)?

**Comment by danharrin** [comment]
c1189cc6590ae1d22245638bed75cd6c339211db

**Comment by zepfietje** [comment]
Great, thanks!
Will do a design review (didn't get to that for v3) during a general styling review for v4 later.
