### ISSUE TITLE
Table Action triggered before form

### ISSUE THREAD

**Issue by mrgla55** [laravel-filament/filament#7324]
### Package

filament/tables

### Package Version

v3.0.0-beta25

### Laravel Version

v10.16.1

### Livewire Version

v3.0.0-beta.5

### PHP Version

PHP 8.2.7

### Problem description

When defining a closure action within the Table Action definition, it is called correctly after submitting the form. But if I reference the function with a string - it calls the action before the form is shown.

Result : Unable to resolve dependency [Parameter #1 [ <required> array $data ]] 

### Expected behavior

The form should show before the action is called. The data of the form passed to the action function

### Steps to reproduce

(The commented variations work correctly)

Filament\Tables\Actions\Action::make('Payment')
                ->button()
                // ->action(fn(Attendance $attendance, array $data) => dd($data))
                // ->action(function(Attendance $attendance, array $data) {
                //     dd($data);
                // })
                ->action('payment')
                ->form([
                    TextInput::make('amount')
                        ->numeric()
                        ->required(),

    public function payment(Attendance $attendance, array $data)
    {
        dd($data);
    }

### Reproduction repository

https://github.com/mrgla55/filament-testing

**Comment by danharrin** [comment]
Hey, where in the docs does it say this is supported? Because it isn't, as far as I know

**Comment by mrgla55** [comment]
Ok. Just checked the docs, its always Closures, but the action function is defined to accept string

    public function action(Closure | string | null $action): static

I had used the string previously in v2 to separate the action logic from the action definition

**Comment by danharrin** [comment]
Okay, we have actually changed it in v3 so that the string gets fed directly into the `wire:click`, which is something you couldn't do before. And that explains why the modal doesn't open, because we can't intercept it. To do what you want to accomplish, try `->action(Closure::fromCallable([$this, 'payment']))`

**Comment by mrgla55** [comment]
thanks @danharrin, planning on moving the logic into the model or something similar. Great job on v3 - fills a huge list of great enhancements
