### ISSUE TITLE
artisan route:cache runs out of memory

### ISSUE THREAD

**Issue by nikspyratos** [laravel-filament/filament#7354]
### Package

filament/filament

### Package Version

3.0.0

### Laravel Version

10.17.0

### Livewire Version

3.0.0-beta.4

### PHP Version

8.2

### Problem description

I've been in the process of upgrading my personal Filament project. The upgrade itself works fine, and the app seems to work A-OK. However, one of my deployment steps is to run `php artisan route:cache`. Since the upgrade, this command now fails.

I tried to `dump` the `$data` var in the serializer in the stack trace, and it basically seems to have a humongous output. It's in a `wrapClosures` function, so I think something to do with closures and either Livewire or Filament is unhappy.

Initially in my reproduction repository I tried copying some of my project's filament resources over, and then removed them one by one in case the issue stopped at some threshold. To my surprise, I ended up removing _all_ of my Filament code besides the default V3 code, and the issue still occurs.

In another project where I've not yet created any Filament resources, this issue doesn't seem to occur, which makes this a bit confusing.

### Expected behavior

`php artisan route:cache` should serialize & cache routes normally.

### Steps to reproduce

- New Filament V3 project
- Run `php artisan route:cache` 

### Reproduction repository

https://github.com/nikspyratos/artisan-route-cache-fail

### Relevant log output

```shell
Whoops\Exception\ErrorException 

  Allowed memory size of 536870912 bytes exhausted (tried to allocate 20480 bytes)

  at vendor/laravel/serializable-closure/src/Serializers/Native.php:222
    218▕             if (isset($data[self::ARRAY_RECURSIVE_KEY])) {
    219▕                 return;
    220▕             }
    221▕
  ➜ 222▕             $data[self::ARRAY_RECURSIVE_KEY] = true;
    223▕ 
    224▕             foreach ($data as $key => &$value) {
    225▕                 if ($key === self::ARRAY_RECURSIVE_KEY) {
    226▕                     continue;

      +1 vendor frames 

  2   [internal]:0
      Whoops\Run::handleShutdown()
```
```

**Comment by zepfietje** [comment]
Make sure to use the latest Livewire version. A similar (or potentially this) issue was fixed recently. Let us know if it still occurs on the latest version, then we'll reopen.

**Comment by nikspyratos** [comment]
Ah you're right! beta 5 did the trick.
