### ISSUE TITLE
Class "Filament\Support\Facades\FilamentView" not found

### ISSUE THREAD

**Issue by alvleont** [laravel-filament/filament#7356]
### Package

filament/filament

### Package Version

v3.0.0

### Laravel Version

v10.17.0

### PHP Version

PHP 8.2.7

### Problem description

Trying to render a hook according to documentation [https://filamentphp.com/docs/3.x/support/render-hooks](for v3), 
It returns the error Class "Filament\Support\Facades\FilamentView" not found. 

(Actually digged it into code and this class is not found into filament/support repo).

### Expected behavior

Registering hooks without any error of missing Class.

### Steps to reproduce

1. Open the provider to include 
```php
use Filament\Support\Facades\FilamentView;
```
to use:
```php
FilamentView::registerRenderHook(
    'panels::body.start',
    fn (): string => Blade::render('@livewire(\'theuienhancement\')'),
);
```
2. Just save it.

### Reproduction repository

0

**Comment by danharrin** [comment]
Check your Filament version `php artisan about`

**Comment by alvleont** [comment]
Yeah, checked that, this is why I didn't reopen the issue.

IDK why it installed v3.?alpha if it was a fresh install.



*Alvaro León Torres*
Químico Farmacéutico - UdeA
Telf: +57-305-263-3211
Integrante Grupo de PyP Farmacéutica - Universidad de Antioquia
Farmacéutico por pasión
Colombia.

**Comment by danharrin** [comment]
```bash
composer require filament/filament:"^3.0-stable" -W
```
