### ISSUE TITLE
Non-native DateTimePicker reinitializes without time

### ISSUE THREAD

**Issue by valpuia** [laravel-filament/filament#7369]
### Package

filament/filament

### Package Version

v3.0.2

### Laravel Version

v10.17

### Livewire Version

v3-beta

### PHP Version

8.2

### Problem description

[Screencast from 08-02-2023 10:18:03 AM.webm](https://github.com/filamentphp/filament/assets/28250303/4874f04c-97cd-4280-8bda-9739ad381460)

As we can see from the video, the `DateTimePicker` display different date-time in even click.. means, at first it display correct but second time wrong data.. third time correct and wrong data in fourth and so on..

If `->native(false)` is not used then it's correct

### Expected behavior

Show the correct date-time when using `->native(false)`

### Steps to reproduce

Clone
Install
migrate --seed
Check user resource

### Reproduction repository

https://github.com/valpuia/v3-datetimepicker-bug

**Comment by danharrin** [comment]
Cannot reproduce using the repo

https://github.com/filamentphp/filament/assets/41773797/431de7c0-5bec-4069-92f9-4004d1b03610
