### ISSUE TITLE
[2.x] getImagePath should be url encoded

### ISSUE THREAD

**Issue by blite** [laravel-filament/filament#737]
### Package

filament/filament

### Package Version

v2

### Laravel Version

v8

### Livewire Version

v2

### PHP Version

PHP 8

### Bug description

Currently if you have a ```'``` in your image's path it will work for ImageColumn until you set ->rounded(), then the ImageColumn will not show.  

I know this package by default / livewire renames files to random names, but if you have a ```'``` in your path you will still get this error.  

This is due to the correct quoting for -rounded() in https://github.com/laravel-filament/filament/blob/2.x/packages/tables/resources/views/columns/image-column.blade.php.

For me this is failing with bird names specifically:
```http://laravel.test/storage/images/Baird's_Sandpiper/Calidris_bairdii.jpg```

**Comment by karam-mustafa** [comment]
"I know this package by default/livewire renames files to random names",
Liveware shouldn't make a file name with a single or double quote, What steps did you follow to get this link?

**Comment by danharrin** [comment]
Fixed in #766.
