### ISSUE TITLE
Unable to find component: [app.filament.pages.tenancy.register]

### ISSUE THREAD

**Issue by mstfkhazaal** [laravel-filament/filament#7377]
### Package

filament/filament

### Package Version

v3.0.2

### Laravel Version

v10.0.0

### Livewire Version

v3.0.0

### PHP Version

8.2.4 

### Problem description

I Edit Register Tenant but when i add FileUpload i get this error
https://github.com/filamentphp/filament/assets/47450090/8174369a-1134-42e5-9e6d-b304254ac9c3

[this is file](https://github.com/mstfkhazaal/onyx/blob/master/app/Filament/Pages/Tenancy/RegisterEntity.php)

I have

### Expected behavior

The code works without any problems

### Steps to reproduce

I searched for a similar problem and couldn't find it

### Reproduction repository

https://github.com/mstfkhazaal/onyx

**Comment by telkins** [comment]
This is happening to at least two other people: https://discord.com/channels/883083792112300104/1136210890987929682

In my case, it's happening with 3.0.7.

**Comment by danharrin** [comment]
@telkins please provide a reproduction repository

**Comment by telkins** [comment]
> @telkins please provide a reproduction repository

Thx.  I will try to get one set up asap.

**Comment by mstfkhazaal** [comment]
I find the solution for this
Because the the page is not in folder of panel 
Move the file to folder panel and it work

In my case a move Register page from App\Filament\Pages\Tenancy
To
App\Filament\App\Pages\Tenancy

App is name of my panel

Is not a bug because the panel access to specific folder

This note should be added to the documentation

**Comment by telkins** [comment]
> @telkins please provide a reproduction repository

@danharrin Here is a reproduction repository: https://github.com/telkins/tenancy-bug-demo

Steps to reproduce:

- migrate
- create filament user
- log in
- point browser to http://localhost/employers
- enter name for new organization
- you should see the error when you submit the register organization form

**Please note that I have not yet tried @mstfkhazaal 's suggestion...yet.  I'll update once I do.**

**Comment by mstfkhazaal** [comment]
> > @telkins please provide a reproduction repository
> 
> @danharrin Here is a reproduction repository: https://github.com/telkins/tenancy-bug-demo
> 
> Steps to reproduce:
> 
> * migrate
> * create filament user
> * log in
> * point browser to http://localhost/employers
> * enter name for new organization
> * you should see the error when you submit the register organization form
> 
> **Please note that I have not yet tried @mstfkhazaal 's suggestion...yet. I'll update once I do.**

https://github.com/telkins/tenancy-bug-demo/pull/1
check PR

**Comment by telkins** [comment]
> App\Pages\Tenancy

I followed @mstfkhazaal 's suggestion and it worked...!  🤓   Thx, @mstfkhazaal .

Fwiw, it wasn't clear to me from the documentation that this was required.  It wasn't obvious to me and it seems like a bug.  😳 

In any case, I'm able to move forward, but am still curious to see what happens with this issue and I'm happy to help with this however I can.  🤓

**Comment by telkins** [comment]
> > > @telkins please provide a reproduction repository
> > 
> > 
> > @danharrin Here is a reproduction repository: https://github.com/telkins/tenancy-bug-demo
> > Steps to reproduce:
> > 
> > * migrate
> > * create filament user
> > * log in
> > * point browser to http://localhost/employers
> > * enter name for new organization
> > * you should see the error when you submit the register organization form
> > 
> > **Please note that I have not yet tried @mstfkhazaal 's suggestion...yet. I'll update once I do.**
> 
> [telkins/tenancy-bug-demo#1](https://github.com/telkins/tenancy-bug-demo/pull/1) check PR

Thx for the extra help.  I know you took care of the main problem with the PR, but forgot to update the namespace in the panel provider class.  🤓

**Comment by mstfkhazaal** [comment]
> I followed @mstfkhazaal 's suggestion and it worked...! 🤓 Thx, @mstfkhazaal .
> 
> Fwiw, it wasn't clear to me from the documentation that this was required. It wasn't obvious to me and it seems like a bug. 😳
> 
> In any case, I'm able to move forward, but am still curious to see what happens with this issue and I'm happy to help with this however I can. 🤓

Welcome
Someone should add this note to the docs

**Comment by mstfkhazaal** [comment]
> Thx for the extra help. I know you took care of the main problem with the PR, but forgot to update the namespace in the panel provider class. 🤓

Sorry, I forgot to change it, the important thing is that the code works successfully

**Comment by EriksonEnterprises** [comment]
Don't forget to update your namespaces, and also update the specific PanelProvider `use` statement

**Comment by aisuvro** [comment]
![image](https://github.com/filamentphp/filament/assets/2842856/f22e37b7-9bd0-4631-b1e8-e30f8db4481d)
Same here.

Someone let me know how to ride out of it.

**Comment by ghassanhjr** [comment]
I have the same issue. I applied the guidance mentioned on the following page [https://filamentphp.com/docs/3.x/panels/users](https://filamentphp.com/docs/3.x/panels/users ) exactly  100%, and I received the following error, please support,
![image](https://github.com/filamentphp/filament/assets/90517109/277f391b-25da-4ff2-a840-25d3e5c394cc)

**Comment by danharrin** [comment]
Read above https://github.com/filamentphp/filament/issues/7377#issuecomment-1664842115
