### ISSUE TITLE
Selected Choices Not Reflecting in Form State When Multiple Select Field is Populated Using a Relationship (Livewire Form Component)

### ISSUE THREAD

**Issue by elbaylot** [laravel-filament/filament#7378]
### Package

filament/forms

### Package Version

v3.0.0

### Laravel Version

v10.17

### Livewire Version

v3.0.0-beta.6

### PHP Version

8.1

### Problem description

When working with a livewire component, an issue arises when you are incorporating a Select multiple field into a form. 

The Select field's options are populated from a `BelongsToMany ` relationship, but the choices made by the users aren't reflected in the form's state when accessed using `$this->form->getState()`. However, if you populate the choices using the `->options() `method or if it's not a multiple select, the selections do appear as expected. 

### Expected behavior

 The choices selected by the users should be properly displayed in the state of the form when accessed with `$this->form->getState()`

### Steps to reproduce

`git clone https://github.com/elbaylot/filament-issue-select-mulitple-relationship.git
`
`composer install
`
`npm install
`
`npm run build
`

Setup your database in the .env

`php artisan migrate:fresh --seed
`
`php artisan migrate:fresh
`

Go to http://127.0.0.1:8000, choose options and click on Submit button

### Reproduction repository

https://github.com/elbaylot/filament-issue-select-mulitple-relationship

**Comment by danharrin** [comment]
This is deliberate, the relationship data is not returned from `getState()` as that should be able to be passed directly to `Model::create()`, which wouldn't work. You need to use https://filamentphp.com/docs/3.x/forms/adding-a-form-to-a-livewire-component#passing-the-form-model-after-the-form-has-been-submitted

**Comment by elbaylot** [comment]
Thanks @danharrin for the reply, i understand the point.

In version 2, for a complex use case, I was overriding the `createOptionUsing `function to create an option without automatically including the "belongs to many" relationship. By utilizing the `->relationship()` method, I was able to fetch the options (applying filters on the query as needed in the real use case), and then create an option without linking it directly to the model. The links were only created when the user submitted the form, regardless of whether the newly created option was among the selected choices.


```
Select::make('select_multiple')
          ->required()
          ->multiple()
          ->relationship('users', 'name')
          ->createOptionModalHeading('Add a new user to the project')
          ->createOptionForm([
              TextInput::make('name')
                  ->columnSpanFull()
                  ->required(),
          ])
          ->createOptionUsing(function (Select $component, array $data, ComponentContainer $form, \Filament\Forms\Get $get) {
              $state = $form->getState();

              $userService = new UserService();
              $user = $userService->store([
                  'name' => $state['name'],
              ]);

              return $user->getKey();
          })
          ->preload()
```

**Comment by elbaylot** [comment]
If is too tricky and not a general use cas, don't worry i will get the choices directly from the data array 👍

**Comment by danharrin** [comment]
When you use relationship(), you shouldnt really need to use `createOptionUsing()`

**Comment by Hegabovic** [comment]
is this issue solved ?? i'm currently facing the same problem as select   ->multiple() doesn't support relationship

**Comment by danharrin** [comment]
It does support it for BelongsToMany relationships

**Comment by Hegabovic** [comment]
but it is morph in spatie roles package 

use Spatie\Permission\Traits\HasRoles;

**Comment by danharrin** [comment]
MorphToMany extends BelongsToMany, it should work

**Comment by Hegabovic** [comment]
not working 

```
        Forms\Components\Select::make('roles')
//                                    ->live()
//                                    ->label(__('filament-user-management::translation.roles'))
//                                    ->multiple()
//                                    ->relationship('roles','name')
//                                    ->preload()
//                                    ->disableOptionWhen(fn (string $value): bool => $value === '3')
//                                    ->optionsLimit(5)
//                                    ->preload()
//                                    ->required(),
```

using this case , the key is not returned in my array of $data  using this method 
  protected function mutateFormDataBeforeCreate(array $data): array
    { 
    dd($data);
    return $data ;
    }

**Comment by danharrin** [comment]
It does not get returned as it gets saved automatically

**Comment by Hegabovic** [comment]
yes when i dd $data , the key roles is not included in it 

because i'm sending this data to some messaging broker before creating

**Comment by danharrin** [comment]
make that Select `->dehydrated()`

**Comment by Hegabovic** [comment]
same issue , the roles key is not shown in the data array

**Comment by danharrin** [comment]
send the code for the Select

**Comment by Hegabovic** [comment]
Forms\Components\Select::make('roles')
                                    ->label(__('filament-user-management::translation.roles'))
                                    ->dehydrated()
                                    ->multiple()
                                    ->relationship('roles', 'name')
                                    ->preload()
                                    ->disableOptionWhen(fn (string $value): bool => $value === '3')
                                    ->optionsLimit(5)
                                    ->preload()
                                    ->required(),

**Comment by danharrin** [comment]
Put `->dehydrated()` after `->relationship()`, not before

**Comment by Hegabovic** [comment]
perfection , it is working thanks a lot

**Comment by patie** [comment]
@danharrin i have same issue, `->dehydrated()` fixed this problem, can you please explain why its necessary here to work?

**Comment by danharrin** [comment]
If the relationship data was returned from `getState()`, passing that array to `Model::create()` or `$model->update()` would throw an error.
