### ISSUE TITLE
Type error when using Forms\Components\Select::make()->relationship() 

### ISSUE THREAD

**Issue by dalehurley** [laravel-filament/filament#7388]
### Package

filament/filament

### Package Version

v3

### Laravel Version

V10.17.0

### Livewire Version

v3

### PHP Version

PHP 8.2.8

### Problem description

When using type hinted relationship like in the example  [Panel Builder Getting started](https://filamentphp.com/docs/3.x/panels/getting-started) you get an error:

```
TypeError
App\Models\Patient::owner(): Return value must be of type App\Models\BelongsTo, Illuminate\Database\Eloquent\Relations\BelongsTo returned
```

```
 public function owner(): BelongsTo
    {
        return $this->belongsTo(Owner::class);
    }

```

 ```
           Forms\Components\Select::make('owner_id')
                ->relationship('owner', 'name')
                ->required(),
```

### Expected behavior

The correct BelongTo type detected

### Steps to reproduce

Follow the example on https://filamentphp.com/docs/3.x/panels/getting-started

### Reproduction repository

https://github.com/DaleMHurley/filament-error

### Relevant log output

```shell
TypeError
PHP 8.2.8
10.17.0
App\Models\Patient::owner(): Return value must be of type App\Models\BelongsTo, Illuminate\Database\Eloquent\Relations\BelongsTo returned
```

**Comment by sumardi** [comment]
Missing

```php
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
```

It's in the docs.

**Comment by dalehurley** [comment]
Ok. Feel free to ignore the issue but this is an error you get following the first getting started page. I am just thought that it is worth highlighting as it is likely to turn people off if they follow along and get an error within the first use.

**Comment by danharrin** [comment]
Can you PR a fix to the docs then?

**Comment by lordjack** [comment]
> Missing
> 
> ```
> use Illuminate\Database\Eloquent\Model;
> use Illuminate\Database\Eloquent\Relations\BelongsTo;
> use Illuminate\Database\Eloquent\Relations\HasMany;
> ```
> 
> It's in the docs.

Thank you for this tip! I had the same error...
