### ISSUE TITLE
Filament\Panel::getDefaultTheme(): Return value must be of type Filament\Support\Assets\Theme, null returned

### ISSUE THREAD

**Issue by andresilvagomez** [laravel-filament/filament#7399]
### Package

filament/filament

### Package Version

3.0

### Laravel Version

10.x

### Livewire Version

3.x

### PHP Version

8.2

### Problem description

That's the full error and only happens on my vapor server.

`
{
"exception": 
{
"class": 
"Illuminate\View\ViewException",
"message": 
"Filament\Panel::getDefaultTheme(): Return value must be of type Filament\Support\Assets\Theme, null returned (View: /var/task/vendor/filament/filament/resources/views/components/layouts/base.blade.php) (View: /var/task/vendor/filament/filament/resources/views/components/layouts/base.blade.php) (View: /var/task/vendor/filament/filament/resources/views/components/layouts/base.blade.php)",
"code": 
0,
"file": 
"/var/task/vendor/filament/filament/src/Panel/Concerns/HasTheme.php:52",
"previous": 
{
"class": 
"Illuminate\View\ViewException",
"message": 
"Filament\Panel::getDefaultTheme(): Return value must be of type Filament\Support\Assets\Theme, null returned (View: /var/task/vendor/filament/filament/resources/views/components/layouts/base.blade.php) (View: /var/task/vendor/filament/filament/resources/views/components/layouts/base.blade.php)",
"code": 
0,
"file": 
"/var/task/vendor/filament/filament/src/Panel/Concerns/HasTheme.php:52",
"previous": 
{
"class": 
"Illuminate\View\ViewException",
"message": 
"Filament\Panel::getDefaultTheme(): Return value must be of type Filament\Support\Assets\Theme, null returned (View: /var/task/vendor/filament/filament/resources/views/components/layouts/base.blade.php)",
"code": 
0,
"file": 
"/var/task/vendor/filament/filament/src/Panel/Concerns/HasTheme.php:52",
"previous": 
{...}
}
}
},
"aws_request_id": 
"38bc01d9-ed98-4bb8-ac2b-5bfcc26fd815"
}`

### Expected behavior

NA

### Steps to reproduce

NA

### Reproduction repository

NA

**Comment by danharrin** [comment]
Unhelpful error reports dont have a reproduction repository or instructions.

**Comment by andresilvagomez** [comment]
@danharrin I solved it, the code here:

`
FilamentAsset::register([
    Js::make('app', asset('js/filament/filament/app.js'))->core(),
    Js::make('echo', asset('js/filament/filament/echo.js'))->core(),
    Theme::make('app', Vite::asset('resources/css/filament/app/theme.css')),
], 'filament/filament');

FilamentAsset::register([
    AlpineComponent::make('color-picker', asset('js/filament/forms/components/color-picker.js')),
    AlpineComponent::make('date-time-picker', asset('js/filament/forms/components/date-time-picker.js')),
    AlpineComponent::make('file-upload', asset('js/filament/forms/components/file-upload.js')),
    AlpineComponent::make('key-value', asset('js/filament/forms/components/key-value.js')),
    AlpineComponent::make('markdown-editor', asset('js/filament/forms/components/markdown-editor.js')),
    AlpineComponent::make('rich-editor', asset('js/filament/forms/components/rich-editor.js')),
    AlpineComponent::make('select', asset('js/filament/forms/components/select.js')),
    AlpineComponent::make('tags-input', asset('js/filament/forms/components/tags-input.js')),
    AlpineComponent::make('textarea', asset('js/filament/forms/components/textarea.js')),
    Js::make('forms', asset('js/filament/forms/forms.js')),
], 'filament/forms');

FilamentAsset::register([
    Js::make('notifications', asset('js/filament/notifications/notifications.js')),
], 'filament/notifications');

FilamentAsset::register([
    Js::make('support', asset('js/filament/support/support.js')),
    Js::make('async-alpine', asset('js/filament/support/async-alpine.js')),
], 'filament/support');

FilamentAsset::register([
    Js::make('tables', asset('js/filament/tables/tables.js')),
], 'filament/tables');

FilamentAsset::register([
    AlpineComponent::make('chart', asset('js/filament/widgets/components/chart.js')),
    AlpineComponent::make('stats-overview/card/chart', asset('js/filament/widgets/components/stats-overview/card/chart.js')),
], 'filament/widgets');
`

**Comment by danharrin** [comment]
I don't understand, why do you need this code? It belongs in Filament core

**Comment by andresilvagomez** [comment]
@danharrin when you are working with serverless and balancers, who serves the asserts is a CloudFront directly, then you need to do it, not your lambda serving asserts.

Maybe it can help you. Our we can create an article, it happens with Laravel Vapor.

**Comment by danharrin** [comment]
You shouldn't need to change anything in Filament core to use it with Laravel Vapor, the code you pasted is already in Filament core, right?
