### ISSUE TITLE
DateTimePicker selected value in filter, increasing with each page refresh, if timezone is configured for DateTimePicker

### ISSUE THREAD

**Issue by bokoch** [laravel-filament/filament#7414]
### Package

filament/filament

### Package Version

v3.0.5

### Laravel Version

v10.17.1

### Livewire Version

v3.0.0-beta.6

### PHP Version

PHP 8.2.8

### Problem description

I'm trying to show date-time columns and date-time pickers according to specific timezone which are saved in "users" table. I added **timezone** field to users table (by default it is set to Europe/Berlin).
I configured timezone for DateTimePicker in create/edit form and. for TextColumn, see code example below:
```php
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('title'),
                Forms\Components\DateTimePicker::make('published_at')
                    ->native(false)
                    ->timezone(
                        auth()->user()->timezone
                    ),
            ])
            ->columns(1);
    }
```
```php
    public static function table(Table $table): Table
    {
        return $table
            ->defaultSort('id', 'desc')
            ->columns([
                Tables\Columns\TextColumn::make('id'),
                Tables\Columns\TextColumn::make('title'),
                Tables\Columns\TextColumn::make('published_at')
                    ->dateTime()
                    ->timezone(
                        auth()->user()->timezone
                    ),
            ]);
    }
```
And here everything works as expected, the value DateTimePicker is saved according to timezone which I set in this component, and in DB **publshed_at** is saved in default application timezone (UTC) as I expected. For the TextColumn same, date is shown correctly according to authenticated user timezone.

However, when I added a filter with two date-time pickers (Published Date From and Published Date To) and configured for both same authenticated user timezone as I did on create/edit page. But when I picked a date in this filter (at least for on date-time picker it doesn't matter which one), I see a filter indicator with selected date-time everything is fine, but when I refresh a page in the browser my selected date-time in the filter is increasing by configured timezone value (increased by 2 hours, because of Europe/Berling timezone). And this value is increasing with each page refreshing.
Here is my configuration for filters:
```php
public static function table(Table $table): Table
    {
        return $table
            ->defaultSort('id', 'desc')
            ->columns([
                Tables\Columns\TextColumn::make('id'),
                Tables\Columns\TextColumn::make('title'),
                Tables\Columns\TextColumn::make('published_at')
                    ->dateTime()
                    ->timezone(
                        auth()->user()->timezone
                    ),
            ])
            ->filters([
                Tables\Filters\Filter::make('published_at')
                    ->label('Published Date')
                    ->form([
                        Forms\Components\DateTimePicker::make('from')
                            ->label('Published Date From')
                            ->timezone(
                                auth()->user()->timezone
                            )
                            ->native(false),
                        Forms\Components\DateTimePicker::make('to')
                            ->label('Published Date To')
                            ->timezone(
                                auth()->user()->timezone
                            )
                            ->native(false),
                    ])
                    ->query(function (Builder $query, array $data) {
                        $query
                            ->when($data['from'], function (Builder $q, string $from) {
                                return $q->where('published_at', '>=', $from);
                            })
                            ->when($data['to'], function (Builder $q, string $to) {
                                return $q->where('published_at', '<=', $to);
                            });
                    })
                    ->indicateUsing(function (array $data) {
                        $indicatorLabels = collect();

                        if ($data['from']) {
                            $indicatorLabels->add('from ' . $data['from']);
                        }

                        if ($data['to']) {
                            $indicatorLabels->add('to ' . $data['to']);
                        }

                        if ($indicatorLabels->isEmpty()) {
                            return null;
                        }

                        return 'Published date ' . $indicatorLabels->implode(' ');
                    })
            ]);
    }
```

https://github.com/filamentphp/filament/assets/9802540/ae7b20be-a70f-464a-95c2-f753215ff215

Not sure if it's a bug or I missed something.

### Expected behavior

The selected value from DateTimePicker in a filter should be the same after refreshing the page (if DateTimePicker has configured custom timezone).

### Steps to reproduce

# Filament Demo
### Demo for reproducing issue with timezone in filters
Steps to reproduce:
1. Clone this repository:
```bash 
git clone https://github.com/bokoch/filament-timezone-issue.git
```
2. Copy .env.example to .env:
```bash 
cp .env.example .env
```
3. Start docker containers:
```bash 
docker-compose up -d
```
4. Install composer dependencies:
```bash 
composer install
```
5. Run migrations:
```bash 
./vendor/bin/sail artisan migrate
```
6. Run seeders:
```bash 
./vendor/bin/sail artisan db:seed
```
7. Go to http://laravel.test/admin and login in 
with credentials:
Email: test@example.com
Password: password
8. Go to http://laravel.test/admin/posts
9. On the posts page open filters menu and pick date for
"**Published Date From**" or/and "**Published Date To**"
10. After picked values will be applied, you will see them in browser
url string and filter indicator. After that refresh the browser page with applied filters
and you will see that picked filter date is increasing
by configured timezone with each page refresh.

### Reproduction repository

https://github.com/bokoch/filament-timezone-issue/

**Comment by josefbehr** [comment]
Can confirm this issue. Already had the problem in v2 and still having it now with an app I'm building. Since I need the dateTime filters, I'll look into it and try to figure out the cause.

My guess is that the saved filter value (from query or session) gets applied to the DateTimePicker in the filter form, which interprets it as UTC and converts to the set timezone. So it would have to be converted to UTC before that, depending on the set timezone. Not sure if this is achievable.

**Comment by josefbehr** [comment]
Ok, like I suspected, the `src/Components/DateTimePicker.php` sets the supplied timezone to the `$state` (line 99):
![image](https://github.com/filamentphp/filament/assets/4368880/a948bc19-f1e9-4633-8921-a044b990bf18)
This is fine and well, of course, if the `$state` is a `DateTime` object in UTC (e.g. from the database), but creates this weird behavior, if the `$state` is a `string` that already is in the required timezone, which is what happens, when the state gets set from the `tableFilters` query parameter (in case the DateTimePicker has a timezone set at least).

So the solution to the jumping time is relatively easy: Supply the timezone when parsing the string to a date:
![image](https://github.com/filamentphp/filament/assets/4368880/8c0dbab1-103b-4d8f-a6e5-1c02ada6d363)
Assumption being, that all supplied dates (in string format) for picker with set timezone are in that timezone. Might be breaking stuff for some people.

The next problem then is that the entered date will be used for the database query without being converted to UTC (or whatever the internal app timezone is).

**Comment by kjjd84** [comment]
@danharrin 

this still happens as of nov 2024, see my discussion with video example here: https://github.com/filamentphp/filament/discussions/14822

**Comment by kjjd84** [comment]
@danharrin 

i figured out this bug. if you use the native datepicker this does not happen. the non-native datepicker seems to append the timezone offset to the filter value, which changes each time you refresh the page

so i am just using the native datepicker from now on

**Comment by peteswan** [comment]
Can this be fixed for non native datetimepicker?

Especially if I use live() then it refreshes in an infinite loop.
