### ISSUE TITLE
FileUpload field on repeater loses state after adding a repeater item

### ISSUE THREAD

**Issue by vanhooff** [laravel-filament/filament#7421]
### Package

filament/forms

### Package Version

v3.0.5

### Laravel Version

v10.17.1

### Livewire Version

v3.0.0-beta.6

### PHP Version

PHP 8.2.8

### Problem description

FileUpload field on Repeater loses state after adding a second Repeater item.

https://share.cleanshot.com/7RJ4QYsl

### Expected behavior

FileUpload states are being kept when adding/removing repeater items.

### Steps to reproduce

1. Install reproduction repository (clone, copy .env.example, generate app_key, composer install, npm install, npm run dev)
2. Go to homepage
3. Add a file to the repeater
4. Add a second repeater item

### Reproduction repository

https://github.com/vanhooff/filament-v3-bug-reproduction

**Comment by falko100** [comment]
Experiencing the same issue.

**Comment by danharrin** [comment]
Just to let you know we are looking into this. I believe that #7421, #7450, #7475 and #7485 (and other duplicate issues) are all the same bug, related to Livewire's entangle feature.

**Comment by danharrin** [comment]
livewire/livewire#6289

**Comment by vanhooff** [comment]
I've updated the reproduction repository to v3.0.24, but the issue still remains. Can we reopen this @danharrin ?

**Comment by zepfietje** [comment]
@vanhooff, just checking, did you make sure to also bump Livewire to the latest version?

**Comment by vanhooff** [comment]
Hi @zepfietje, Yep just updated the reproduction repository to Filament 3.0.27 and Livewire v3.0.0-beta.10. The issue is still there.

**Comment by zepfietje** [comment]
Okay thanks for confirming.

**Comment by vanhooff** [comment]
@danharrin  @zepfietje Do you guys have a clue/suspicion where this bug might be originating from? If so, I can maybe take a stab at it.

**Comment by danharrin** [comment]
If it worked fine on v2, it will probably be originating from Livewire 3. But I don't have any details apart from that

**Comment by danharrin** [comment]
Issue with collapsible repeaters. Fixed by #8384.
