### ISSUE TITLE
Laravel Vapor with Octane not working

### ISSUE THREAD

**Issue by sweebee** [laravel-filament/filament#7427]
### Package

filament/filament

### Package Version

v3.0.7

### Laravel Version

v10.17.1

### Livewire Version

v3.0.0-beta.6

### PHP Version

8.2.8

### Problem description

The first request works fine, the second one doesnt. Getting the following exception:

```
Filament\Panel::getDefaultTheme(): Return value must be of type Filament\Support\Assets\Theme, null returned (View: /var/task/vendor/filament/filament/resources/views/components/layout/base.blade.php) (View: /var/task/vendor/filament/filament/resources/views/components/layout/base.blade.php) (View: /var/task/vendor/filament/filament/resources/views/components/layout/base.blade.php)
```

I tried to add this to the panel config (and published the theme.css in the public dir):

```php
 ->theme(Theme::make('app', asset('theme.css'))->package('filament/filament'))
```
After that the page loads fine, but alpinejs doesnt work (first request it works after a deploy).

### Expected behavior

Should work :)

### Steps to reproduce

Deploy to Laravel Vapor, load the index page 2 times.

https://graceful-cavern-f29ddqvba9co.vapor-farm-f1.com/login

### Reproduction repository

https://github.com/sweebee/filamentv3octane

### Relevant log output

```shell
https://graceful-cavern-f29ddqvba9co.vapor-farm-f1.com/login
```

**Comment by danharrin** [comment]
Can you look into it and submit a PR if possible? I don't really use either so its quite tricky

**Comment by garethnic** [comment]
I experienced the same thing but managed to sort it out by generating a theme and applying 
`->viteTheme('resources/css/filament/admin/theme.css')`.  Only issue I'm running into now is subsequent requests fail due to octane/swoole.

**Comment by gwlortscher** [comment]
Did you figure this out? I'm running into the same issue with just Octane (no Vapor). Doesn't work with either Roadrunner or Swoole. After the first request to Filament, every subsequent request fails.

**Comment by garethnic** [comment]
I didn't and I sadly haven't had time to tinker with it again. I've tried all the variations of the `flush` config setting mentioned in past issues, I've tried using a custom service provider, using middleware but nothing. It's sitting inside a docker container as well which makes finding the silver bullet that much more time consuming. Feels like it has to be something silly that's being overlooked.

**Comment by danharrin** [comment]
I can probably guess why this is happening

**Comment by danharrin** [comment]
The AssetManager is a scoped singleton, and the assets are only registered once in boot()

**Comment by danharrin** [comment]
@sweebee @gwlortscher @garethnic as I said, I don't use Octane really so haven't tested this, so please review #7552 and let me know if it fixes

**Comment by danharrin** [comment]
Anyone tested?

**Comment by sweebee** [comment]
> Anyone tested?

Yes, seems to work great!
