### ISSUE TITLE
FileUpload lose file after validation error

### ISSUE THREAD

**Issue by Red0ck** [laravel-filament/filament#7447]
### Package

filament/filament

### Package Version

3.0

### Laravel Version

10.17.0

### Livewire Version

2.1

### PHP Version

8.2

### Problem description

When we upload files e.g. photos and pass the form without mandatory fields filled we got an error, and this is correct.
But then when we fill these fields with errors correctly, and pass the form again, we got information under the FileUpload `only allowed images/*`.
Looks like somewhere form is losing its connection to a file that was uploaded or some validation problem.

### Expected behavior

The form should hold information about the file after errors

### Steps to reproduce

We need a simple form with at least 2 inputs (FileUpload - restricted to images only, whatever input - field should be required).

1. Upload a file
2. Pass the form without the required input
3. Validation error
4. Fill the required input
5. Pass the form
6. Error on FileUpload

### Reproduction repository

-

**Comment by bennettblack** [comment]
I've also encountered this. Seems that the `FileUpload` field's value is cleared if the form fails any validation rules, then is resubmitted. A work around is to just re-upload the file - admittedly not ideal.

**Comment by carrilhorafael57** [comment]
Was this issue fixed? I still have the same. Someone found a workaround?

**Comment by Frozire** [comment]
> Was this issue fixed? I still have the same. Someone found a workaround?

Still hitting the same problem, will update here if I find a solution.

**Comment by carrilhorafael57** [comment]
> > Was this issue fixed? I still have the same. Someone found a workaround?
> 
> Still hitting the same problem, will update here if I find a solution.

I was actually able to create a workaround.

I am saving my file in cache and checking my cache when theres a validation error.

**Comment by tuimz** [comment]
> > > Was this issue fixed? I still have the same. Someone found a workaround?
> > 
> > 
> > Still hitting the same problem, will update here if I find a solution.
> 
> I was actually able to create a workaround.
> 
> I am saving my file in cache and checking my cache when theres a validation error.

Any hints as to how this was done? Running into the issue myself as well.
