### ISSUE TITLE
Property type not supported in Livewire for property

### ISSUE THREAD

**Issue by maxacarvalho** [laravel-filament/filament#7465]
### Package

filament/filament

### Package Version

v3.0.7

### Laravel Version

v10.17.1

### Livewire Version

v3.0.0-beta7

### PHP Version

PHP 8.2.7

### Problem description

After migrating to Filament 3 I started getting the following error when loading a resource edit page:

- `Property type not supported in Livewire for property: ["POST"]`

After quite I spent sometime investigating I had to try some desperate move and started deleting columns from the DB table.  
The thing is, I have two columns inside my table. One is named `type` and the other, `handling_type`.  

The error above happens when the `type` column is present. The `"POST"` in there refers to the column value.
Once I remove that column, I get the following error:

- `Property type not supported in Livewire for property: ["STORE_AND_PROCESS"]`

The `"STORE_AND_PROCESS"` above refers to the `handling_type` column.  

Once I remove both columns the resource edit page loads normally.  
I'm not sure if that's a Livewire error/limitation or if that has something to do with Filament. For the moment I'm asking around to try to get some help.

### Expected behavior

I'd expect to have the resource edit page loaded.

### Steps to reproduce

I didn't try with a fresh project but I'd say one could create a table and model with the columns above and check it out.

Here's the table's DDL if that helps:
```sql
CREATE TABLE `integration_types` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `company_id` bigint unsigned DEFAULT NULL,
  `code` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `description` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `handling_type` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `target_url` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `is_visible` tinyint(1) NOT NULL DEFAULT '1',
  `is_enabled` tinyint(1) NOT NULL DEFAULT '1',
  `is_protected` tinyint(1) NOT NULL DEFAULT '0',
  `is_synchronous` tinyint(1) NOT NULL DEFAULT '0',
  `processor` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `allows_duplicates` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '0',
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  KEY `integration_types_created_at_index` (`created_at`),
  KEY `integration_types_updated_at_index` (`updated_at`),
  KEY `integration_types_company_id_index` (`company_id`),
  KEY `integration_types_code_index` (`code`)
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
```

### Reproduction repository

na

**Comment by danharrin** [comment]
Do you have custom casts on the model

**Comment by maxacarvalho** [comment]
Hi @danharrin I just realised that it's related to the enums and not to the DB column names.
Yes I have enums, but I'm using the `Spatie\Enum\Laravel\Enum`, so the classes are declared like so:
```php
<?php

namespace App\Enums;

use Spatie\Enum\Laravel\Enum;

/**
 * @method static self GET()
 * @method static self POST()
 */
final class IntegrationTypeEnum extends Enum
{
}
```

Inside the model I have:
```php

    protected $casts = [
        self::TYPE => IntegrationTypeEnum::class,
        self::HANDLING_TYPE => IntegrationHandlingTypeEnum::class.':nullable',
        self::IS_VISIBLE => 'boolean',
        self::IS_ENABLED => 'boolean',
        self::IS_PROTECTED => 'boolean',
        self::IS_SYNCHRONOUS => 'boolean',
        self::ALLOWS_DUPLICATES => 'boolean',
    ];
```

**Comment by danharrin** [comment]
Try making the enum "wireable", or use the Filament mutate hooks on the pages to transform it into a storeable value. This is a Livewire thing, not Filament.

**Comment by maxacarvalho** [comment]
I see. I'll have a look, thank you @danharrin.

**Comment by maxacarvalho** [comment]
@danharrin out of curiosity, any reference on the: making the enum "wireable"?  
So far I couldn't find anything about it.

**Comment by danharrin** [comment]
https://livewire.laravel.com/docs/properties#supporting-custom-types
