### ISSUE TITLE
Multi tenancy not working according to docs

### ISSUE THREAD

**Issue by ducopro** [laravel-filament/filament#7466]
### Package

filament/filament

### Package Version

v3

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

8.1

### Problem description

When adding multi tenancy, the register page does not work. Several method not found errors will be thrown because the inheritance tree is not correct.

According to the docs we need to inherit from the RegisterTenant class, but if we do that the Page class is not in the inheritance tree and we are missing out several methods.

### Expected behavior

To see a registration page :-)

### Steps to reproduce

Just follow the steps in the docs

### Reproduction repository

<none>

**Comment by danharrin** [comment]
RegisterTenant extends SimplePage extends BasePage, so what's the problem here? Please create a reproduction.
