### ISSUE TITLE
Postgres search issues

### ISSUE THREAD

**Issue by EQuimper** [laravel-filament/filament#75]
**Describe the bug**
I have a BelongsToSelect form relation in my post model. `Components\BelongsToSelect::make('user_id')->relationship('user', 'username')->required(),` 

I can search any user who have the username all lowercase. But for those Uppercase one this never match, even if I search with the Uppercase letter.

**To reproduce**
Having uppercase username in a table with a BelongsToSelect relation.

**Expected behavior**
I expected to see any user matching the search term.

**Screenshots**
<img width="1369" alt="Screen Shot 2021-03-04 at 9 22 41 AM" src="https://user-images.githubusercontent.com/15819498/109977879-4901eb80-7ccb-11eb-8662-942ede69d3c4.png">
<img width="1353" alt="Screen Shot 2021-03-04 at 9 22 50 AM" src="https://user-images.githubusercontent.com/15819498/109977891-4dc69f80-7ccb-11eb-9aad-975a2ad44a29.png">

**Context**
- Browser:  Chrome
- Server OS: Localhost on MacOS Catalina 10.15.7
- PHP version: 8.0

**Additional details**

As you can see, when I type `e` I get EQuimper there. But the reason is because of the `er` at the end. This never match the big `E`

**Comment by shuvroroy** [comment]
@EQuimper I have checked and everything seems ok as expected

**Comment by danharrin** [comment]
Yeah, `like` on the query should handle results case insensitively?

**Comment by ryangjchandler** [comment]
@danharrin Only with MySQL / MariaDB - Postgres is case-sensitive if I remember correctly.

**Comment by EQuimper** [comment]
@danharrin I'm using postgresql also. Not sure if this change something

**Comment by ryangjchandler** [comment]
Postgres is case-sensitive when querying @EQuimper.

**Comment by danharrin** [comment]
@ryangjchandler AFAIK `ilike` is the case insensitive version for Postgres, but this is not compatible with MySQL. Do you think we should detect the DB driver a switch appropriately?

**Comment by EQuimper** [comment]
@ryangjchandler Yeah I mean I do understand it and did see in the code the like search you do. But why this is happening in my case. In postgres I use iLike for those issue.

**Comment by ryangjchandler** [comment]
@danharrin Yeah, that could work. It's a little bit annoying but would fix the issue and it's only going to be on place really.

**Comment by danharrin** [comment]
@ryangjchandler maybe a helper function to return the correct operator based on the driver?

**Comment by ryangjchandler** [comment]
> @ryangjchandler maybe a helper function to return the correct operator based on the driver?

Yeah, that's one way for sure.

**Comment by danharrin** [comment]
I'm pretty sure this is used in the tables package too so will decide depending on the complexity.

**Comment by ryangjchandler** [comment]
@danharrin An alternative solution would be doing a `where('LOWER(column_name)')` and then doing an `mb_strtolower()` on the search itself.

**Comment by danharrin** [comment]
Would there be a considerable performance impact using that with MySQL?

**Comment by shuvroroy** [comment]
@danharrin I guess no.

**Comment by ryangjchandler** [comment]
> Would there be a considerable performance impact using that with MySQL?

Not that I can think of. This is what Spatie's search package does when you want to search based on a partial match, like the original issue.

**Comment by shuvroroy** [comment]
@danharrin @ryangjchandler I am working these issue and will make a pr soon

**Comment by shuvroroy** [comment]
@danharrin @EQuimper @ryangjchandler Please check these PR.

https://github.com/laravel-filament/filament/pull/78

**Comment by danharrin** [comment]
Fixed in #78.

**Comment by EQuimper** [comment]
@danharrin I think something else come from the fix at #78 Now when I search with an integer I get this error

```
SQLSTATE[42883]: Undefined function: 7 ERROR: function lower(bigint) does not exist LINE 1: select count(*) as aggregate from "users" where (LOWER(id) L... ^ HINT: No function matches the given name and argument types. You might need to add explicit type casts. (SQL: select count(*) as aggregate from "users" where (LOWER(id) LIKE %2%) or (LOWER(email) LIKE %2%) or (LOWER(username) LIKE %2%))
```

Remember this is on postgres

**Comment by danilopolani** [comment]
Maybe it's easier to just change the operators according to the DB driver, for example:

```php
$operators = [
  'mysql' => 'LIKE',
  'pgsql' => 'ILIKE',
];

/** @var string $dbConnection */
$dbConnection = config('database.default');

$query->where('field', $operators[$dbConnection] ?? 'LIKE', '%' . $searchValue . '%');
```

I was looking through Laravel DB drivers APIs to achieve this in a smarter way, but there's nothing related to a "like" operator based on the driver neither in [Grammar](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Query/Grammars/PostgresGrammar.php) class unluckily

**Comment by ryangjchandler** [comment]
> Maybe it's easier to just change the operators according to the DB driver I think, for example:
> 
> ```
> $operators = [
>   'mysql' => 'LIKE',
>   'pgsql' => 'ILIKE',
> ];
> 
> /** @var string $dbConnection */
> $dbConnection = config('database.default');
> 
> $query->where('field', $operators[$dbConnection] ?? 'LIKE', '%' . $searchValue . '%');
> ```
> 
> I was looking through Laravel DB drivers APIs to achieve this in a smarter way, but there's nothing related to a "like" operator based on the driver neither in [Grammar](https://github.com/laravel/framework/blob/8.x/src/Illuminate/Database/Query/Grammars/PostgresGrammar.php) class unfortunately (cc @danharrin )

I think there's an extra bit of complexity here because the connection being used for queries might change based on the model, so it would need to use the model's connection instead of the default one.

**Comment by EQuimper** [comment]
What do you think about adding an options to the searchable method where we can override default value ? This way you let the user manage it from model to model etc ?

**Comment by danilopolani** [comment]
It seems a bit dirty, but what a solution like this?

```sql
SELECT * FROM table WHERE LOWER(CONCAT(position, '')) like '%55%'; // position is an int in this case
```

It forces any field to cast into a string by performing a concat with nothing and it works with both Postgres and MySQL.

Before this solution, I was trying to take advantage of `CAST`, but I couldn't find a cast type that works for both:

```sql
select * from demo where lower(CAST(position as CHAR)) like '%55%' // Search works in MySQL but not in Postgres (no errors)
select * from demo where lower(CAST(position as VARCHAR)) like '%55%' // Valid in MySQL but not in Postgres
select * from demo where lower(CAST(position as TEXT)) like '%55%' // Valid in Postgres but not in MySQL
select * from demo where lower(CAST(position as BINARY)) like '%55%' // Valid in MySQL but not in Postgres
```

**Comment by danharrin** [comment]
We can use `$record->getConnection()->connection()->getDriverName()` to get the driver name BTW.

**Comment by danilopolani** [comment]
> We can use `$record->getConnection()->getDriverName()` to get the driver name BTW.

That's good. I mean, right now there are two possible solutions:

1. A driver-aware syntax "map" (through `getDriverName()`)
2. A SQL-only solution valid for both Postgres and MySQL with `CONCAT` (Idk about performance here)

I think the main pros of the solutions are:

- Driver-aware: can ship support for many drivers out-of-the-box; can do more optimization based on the driver (?)
- Concat: avoid more business logic

Sooo... It's up to you guys 😄

**Comment by danharrin** [comment]
@EQuimper @danilopolani I've opened #168, please check if it fixes the issue.

**Comment by danharrin** [comment]
Closed by #168.

**Comment by bram-pkg** [comment]
Hello, it seems this was never ported to Filament 3 - hence always requiring the `forceSearchCaseInsensitive()` method to be called in order to search for queries where the results contain upper case characters. Any plans to port it?

**Comment by danharrin** [comment]
The docs explain why `forceSearchCaseInsensitive()` exists. Whats your issue with it?
