### ISSUE TITLE
Page::getUrl() adds tenant to parameters when not using tenancy.

### ISSUE THREAD

**Issue by iantasker** [laravel-filament/filament#7500]
### Package

filament/filament

### Package Version

v3.0.8

### Laravel Version

v10.10

### Livewire Version

v3.0

### PHP Version

PHP 8.2.0

### Problem description

Page::getUrl() is assuming that all pages are going to be tenant aware. 

If a plugin adds a page that doesn't required a tenant a missing parameters exception is thrown. 

This happens in the of breezy, when it tries to add the my profile page it with throw the error.  

### Expected behavior

A page url should be generated even if tenant is null.

### Steps to reproduce

Install breezy and add the plugin to a panel and enable myProfile(). 

### Reproduction repository

https://github.com/iantasker/filament

**Comment by datlechin** [comment]
use closure function instead.
```php
(fn () => Page::getUrl())
```

**Comment by iantasker** [comment]
@datlechin Thanks that has resolved the issue.
