### ISSUE TITLE
Table Action Group not rendering

### ISSUE THREAD

**Issue by matt-shirey** [laravel-filament/filament#7502]
### Package

filament/forms

### Package Version

3.0-stable

### Laravel Version

10.17.1

### PHP Version

8.2.7

### Problem description

When adding adding row actions into a group, I get the error `Method Filament\Actions\ActionGroup::table does not exist.`.

```
ActionGroup::make([
    ViewAction::make(),
    EditAction::make(),
    DeleteAction::make(),
])
```

### Expected behavior

Render a dropdown of row actions.

### Steps to reproduce

Add a row group to any table with any action.

### Reproduction repository

https://github.com

**Comment by C14r** [comment]
It seems like the issue stems from using the wrong class. Instead of using `Filament\Actions\ActionGroup`, you should use `Filament\Tables\Actions\ActionGroup`.

Even though this issue is already closed, I wanted to add this here in case someone else encounters the same problem. I hope this helps!
