### ISSUE TITLE
Custom form field throws ErrorException 'Undefined variable' on custom var

### ISSUE THREAD

**Issue by Jelmerkeij** [laravel-filament/filament#7509]
### Package

filament/forms

### Package Version

v3.0.7

### Laravel Version

10.17.1

### Livewire Version

dev-main 6e529b7

### PHP Version

PHP 8.2.0

### Problem description

Created a custom Form Field as described in the docs here: https://filamentphp.com/docs/3.x/forms/fields/custom

It does indeed generate a custom component. Now when adding a custom variable `public string $testVar = 'testValue';` to the component and try to show it in the components `view` it throws `ErrorException: Undefined variable $testVar`

### Expected behavior

The value `testValue` appears in the custom component's view where I put `value is: {{  $testVar  }}`

### Steps to reproduce

1. Create custom component as described in the docs: `php artisan make:form-field RangeSlider`
2. Add custom var to generated file `Forms/Components/RangeSlider.php`:
```php
class RangeSlider extends Field
{
    protected string $view = 'forms.components.range-slider';

    public string $testVar = 'testValue';
}
```

3. Try to show the value of this variable in the generated view file `resources/views/forms/components/range-slider.blade.php`:

```php
<x-dynamic-component
    :component="$getFieldWrapperView()"
    :field="$field"
>

    Value is: {{  $testVar  }}

    <div x-data="{ state: $wire.entangle('{{ $getStatePath() }}') }">
        <!-- Interact with the `state` property in Alpine.js -->
        And again, the value is: {{  $testVar  }}
    </div>
</x-dynamic-component>
```

4. Add the custom component to a form, trying to get it to show. Using the `filament-demo` repo, in `Filament/Resources/Blog/PostResource.php`:

```php
return $form
            ->schema([
                Forms\Components\Group::make()
                    ->schema([
                        Forms\Components\Section::make()
                            ->schema([
                                // Here is our "prototype" RangeSlider
                                // Attribute doesn't matter for the test so just use `title`
                                RangeSlider::make('title'),

                                /*Forms\Components\TextInput::make('title')
                                    ->required()
                                    ->live(onBlur: true)
                                    ->afterStateUpdated(fn (string $operation, $state, Forms\Set $set) => $operation === 'create' ? $set('slug', Str::slug($state)) : null),*/

                                Forms\Components\TextInput::make('slug')
                                    ->disabled()
                                    ->dehydrated()
                                    ->required()
                                    ->unique(Post::class, 'slug', ignoreRecord: true),
...
```

**But when putting this in `composer.json` :    `"filament/filament": "3.0.6",` and running `composer update -W`, it does work and I see the expected output!**

### Reproduction repository

https://github.com/Jelmerkeij/filament-demo-v3

**Comment by Jelmerkeij** [comment]
For info, I've also raised this issue on Discord a few days ago: https://discord.com/channels/883083792112300104/1136959355372183603

**Comment by petrisorcraciun** [comment]
in Components/ViewComponent.php for render method, in v3 it returns only the public methods. You tried to create a public method to call in the blade for return the value ?

public function getTestVar() : string { return $this->testVar; } in blade : $getTestVar();

[v3.0.6](https://github.com/filamentphp/filament/blob/79d693b0444ed6ad4ef80f91b1dc3de252994dee/packages/support/src/Components/ViewComponent.php#L175)

[v3.0.10](https://github.com/filamentphp/filament/blob/e7a4b26b1cfea36a86289b3ac048ade5e0551ca5/packages/support/src/Components/ViewComponent.php#L137)

**Comment by Jelmerkeij** [comment]
Hi @petrisorcraciun thanks for your reply. You are correct, the public function does indeed work. Do you have any information on why this has changed from version 3.0.6 and/or where I could have read about this change? Just for myself as a reminder to avoid posting issues that aren't exactly issues :-) Thanks again!

**Comment by petrisorcraciun** [comment]
I don't know and I don't think it is documented anywhere. I checked directly on the branch a possible cause, which he confirmed.

**Comment by Jelmerkeij** [comment]
Alright. Thanks again and I’ll close the issue. Hopefully someone will find this info useful in the future.
