### ISSUE TITLE
HasManyThrough Relation Manager problem when trying to add record

### ISSUE THREAD

**Issue by guiofranca** [laravel-filament/filament#7513]
### Package

filament/filament

### Package Version

3.0.8

### Laravel Version

10.17.1

### PHP Version

8.2.8

### Problem description

When trying to save a model using a HasManyThrough relation in the Relation Manager the application throws an exception.

https://flareapp.io/share/W7z8XNVm

### Expected behavior

It was expected to save the model.

### Steps to reproduce

There are instructions on the reproduction repository. 

The error also happens on the demo page under `Customers->Payments`. Pick a Customer with any Orders placed and try to add a Payment. https://demo.filamentphp.com/shop/customers

### Reproduction repository

https://github.com/guiofranca/relation-manager-error

**Comment by guiofranca** [comment]
I could get it to work by changing the line https://github.com/filamentphp/filament/blob/3.x/packages/tables/src/Actions/CreateAction.php#L66C39-L66C39 to:

```php
if (! $relationship || $relationship instanceof HasManyThrough) {
    
    $record->save();

    return $record;
}
```
I don't know how it would affect other features.

**Comment by petrisorcraciun** [comment]
in Components/ViewComponent.php for render method, in v3 it returns only the public methods. You tried to create a public method to call in the blade for return the value ?

**Comment by danharrin** [comment]
Please submit a PR if you can
