### ISSUE TITLE
Action Group with Label set doesn't show Label on the UI

### ISSUE THREAD

**Issue by abishekrsrikaanth** [laravel-filament/filament#7561]
### Package

filament/tables

### Package Version

v3.0.12

### Laravel Version

v10.18

### Livewire Version

v3.0-beta.7

### PHP Version

PHP 8.2

### Problem description

When creating an `ActionGroup` with a label set, doesn't show the label

```php
ActionGroup::make([
                Action::make('a')->label('Action A'),
                Action::make('b')->label('Action B'),
            ])->label('Header Actions Label')
```

<img width="591" alt="CleanShot 2023-08-08 at 20 31 42@2x" src="https://github.com/filamentphp/filament/assets/1639302/9b3fefc0-234e-4123-8969-91b6b185150c">

In addition to the above issue, when there are multiple `ActionGroups`, they stick to each other. They need a margin between them

<img width="362" alt="CleanShot 2023-08-08 at 20 41 24@2x" src="https://github.com/filamentphp/filament/assets/1639302/bbb9ef00-182c-4705-99a3-11c4638f185b">

### Expected behavior

As per the documentation here https://filamentphp.com/docs/3.x/actions/grouping-actions#customizing-the-group-trigger-style and the image showcased, the label should show on the `ActionGroup`

![image](https://github.com/filamentphp/filament/assets/1639302/f0ece56b-f420-4153-9087-66cd8739e539)

### Steps to reproduce

Please refer to the code in the below repository. Class `ActionGroupLabelNotDisplayIssue` and the following code should help reproduce this issue

```php
    public function table(Table $table): Table
    {
        return $table->query(function () {
            return User::query();
        })->columns([
            TextColumn::make('name'),
            TextColumn::make('email'),
        ])->actions([

        ])->headerActions([
            ActionGroup::make([
                Action::make('a')->label('Action A'),
                Action::make('b')->label('Action B'),
            ])->label('Header Actions Label')
        ]);
    }
```

### Reproduction repository

https://github.com/abishekrsriaanth/filament-test

**Comment by danharrin** [comment]
`->button()`
