### ISSUE TITLE
Uncaught TypeError: "Snapshot missing on Livewire component with id: " is not a constructor

### ISSUE THREAD

**Issue by iAmKevinMcKee** [laravel-filament/filament#7567]
### Package

filament/filament

### Package Version

v3.0.12

### Laravel Version

v10.18.0

### Livewire Version

v3.0.0-beta7

### PHP Version

PHP 8.2

### Problem description

Having multiple widget classes on a resource causes dom diffing issues and causes the whole page to break

### Expected behavior

When livewire updates are made on a page with multiple widgets, the page should work without livewire issues breaking everything.

### Steps to reproduce

Load the repo I added below. Create a speaker and view that record (you need to get to the ViewSpeaker class).

When you get to that page and click a livewire button (for example, change the relation manager from one to the other), you'll see one of the widgets disappears. The dom diffing loses track of one of them, and everything ends up breaking. There is a console error that reads:

`Uncaught TypeError: "Snapshot missing on Livewire component with id: " is not a constructor`

Somehow those components are not getting a Livewire ID it seems.

I've tried many ways of adding a unique identifier to those widgets, but no matter what I do (wire:key, standard html id), after the first livewire update it loses track of them.

### Reproduction repository

https://github.com/iAmKevinMcKee/filament3

**Comment by cheesegrits** [comment]
Can confirm this, have this exact behavior with more than one widget on a resource page.

Here's a screencast I did when discussing it in Discord.

https://app.screencast.com/gFXNrZwfIFCtf

**Comment by tanthammar** [comment]
Confirmed. Downloaded the repository and added wire:key manually to the widgets and in other places.
Problem remains.
This is a livewire 3 thing...

**Comment by awcodes** [comment]
Adding wire:ignore to the Widgets grid container solves the issue, but it does appear to be an issue in Livewire with nested LW components where it's duplicating the id's in the placeholders before dehydrating the state and re-rendering the children.

https://github.com/filamentphp/filament/assets/3596800/249102de-bdc6-4622-b5f2-9bc690b6a05e

![Screenshot 2023-08-09 at 1 23 55 PM](https://github.com/filamentphp/filament/assets/3596800/00304ec7-6c58-4bb4-a725-b5d7a957a625)

**Comment by juanmmc** [comment]
Tuve un problema similar "*Uncaught Snapshot missing on Livewire component with id:*". Lo resolví forzando el renderizado del componente secundario asignando una nueva llave de la siguiente manera:

`<livewire:pages.about-job-offer :$job_offer :key="$job_offer->pluck('id')->join(uniqid())" />`

De esta manera obligo a livewire a registrar nuevamente el componente, ya que pierde la referencia en algún momento del procesamiento de la solicitud.

**Comment by PulsarArena** [comment]
Juanmmc
En qué módulo o sección pongo esto ?

**Comment by juanmmc** [comment]
> Juanmmc En qué módulo o sección pongo esto ?

En la vista

**Comment by muba00** [comment]
I am having same issue but with Relationship manager on Latest Filament version
