### ISSUE TITLE
Filament\Tables\Filters\Filter::apply() must be instance of Closure 

### ISSUE THREAD

**Issue by ManojKiranA** [laravel-filament/filament#757]
### Package

filament/filament

### Package Version

2.x-dev

### Laravel Version

8.65

### Livewire Version

Not needed

### PHP Version

8.0.12

### Bug description

After creating the resource when i try to Create a filter I am getting the following error

```
TypeError
Filament\Tables\Filters\Filter::apply(): Argument #1 ($query) must be of type Illuminate\Database\Eloquent\Builder, Closure given, called in C:\xampp\htdocs\filamenttest\app\Filament\Resources\CustomerResource.php on line 49
```
![image](https://user-images.githubusercontent.com/30294553/144863263-753b9ae9-12ee-4da1-b297-2c81c86ac40e.png)

I think the problem is [apply](https://github.com/laravel-filament/filament/blob/2.x/packages/tables/src/Filters/Concerns/InteractsWithTableQuery.php#L12) Method  of `InteractsWithTableQuery` trait will only accept instance of `Illuminate\Database\Eloquent\Builder`

### Steps to reproduce

```
public static function table(Table $table): Table
    {
        return $table
            ->columns([
            TextColumn::make('first_name'),
            ])
            ->filters([
                Tables\Filters\Filter::make('verified')
                    ->apply(fn (Builder $query): Builder => $query->whereNotNull('email_verified_at')),
            ]);
    }
```

### Relevant log output

```shell
TypeError
Filament\Tables\Filters\Filter::apply(): Argument #1 ($query) must be of type Illuminate\Database\Eloquent\Builder, Closure given, called in C:\xampp\htdocs\filamenttest\app\Filament\Resources\CustomerResource.php
```

**Comment by danharrin** [comment]
Hey, please use `query()` instead of `apply()` to set the callback. Are the docs wrong?

**Comment by ManojKiranA** [comment]
I am not sure that issue is in docs or method signature 😕

**Comment by ManojKiranA** [comment]
Shall I send pr to Docs with change

**Comment by danharrin** [comment]
Yes please, I can't see where they're incorrect though?
