### ISSUE TITLE
Invalid tenant menu item dropdown panel stack order when sidebar collapsed

### ISSUE THREAD

**Issue by qoqn** [laravel-filament/filament#7577]
### Package

filament/filament

### Package Version

v3.0.12

### Laravel Version

v10.17.1

### PHP Version

8.2.8

### Problem description

In multi tenant application, when using `sidebarCollapsibleOnDesktop()` option on panel and collapsing the sidebar in desktop the stack order is invalid, tenant menu items is inside (or behind?) the collapsed sidebar.

<img width="315" alt="image" src="https://github.com/filamentphp/filament/assets/22430343/f4fbe1aa-763e-4794-bc57-c2d2a3e46a76">

### Expected behavior

Tenant menu (dropdown) should be above sidebar, viewable and clickable even on collapsed sidebar.

### Steps to reproduce

Using this panel configuration, or the default `tenantMenuItems()` configuration (where the tenant selector exists)

```php
return $panel
			// ... other settings
            ->sidebarCollapsibleOnDesktop()
			// ... other settings
            ->tenantMenuItems([
                MenuItem::make()
                    ->label('Settings')
                    ->icon('heroicon-m-cog-8-tooth'),
            ])
			// ... other settings
```

### Reproduction repository

https://github.com/muoya

**Comment by danharrin** [comment]
No reproduction repo?

**Comment by lamberttraccard** [comment]
@danharrin could we reopen the issue please ?
I have a made a reproduction repo https://github.com/lamberttraccard/filament-issue

**Comment by lamberttraccard** [comment]
Thanks 🙂

**Comment by zepfietje** [comment]
Fixed in https://github.com/filamentphp/filament/commit/cfe9d6067413525739ef9eaab89b54e017d302f2.
