### ISSUE TITLE
Incorrect per-group aggregate values in tables

### ISSUE THREAD

**Issue by austincarpenter** [laravel-filament/filament#7578]
### Package

filament/filament

### Package Version

v3.0.7

### Laravel Version

v10.x

### Livewire Version

v3.x

### PHP Version

>= 8.1

### Problem description

When grouping by a column in a table, per-group aggregates (`sum` in the case of the filament demo) only show the value of the last row.

<img width="1246" alt="Screenshot 2023-08-09 at 1 15 46 pm" src="https://github.com/filamentphp/filament/assets/3736774/0c76c719-b059-4408-9f5d-eec9dad6de1b">

Pressed for time at the moment otherwise I'd investigate further and look to PR instead of just create the issue. Will still try to.

### Expected behavior

Per-group aggregate value to actually aggregate correctly.

### Steps to reproduce

1. Go to orders list page of filament demo
2. Apply group by order date (either direction)
3. Observe per-group aggregates only showing last row's value.

### Reproduction repository

https://github.com/ + filamentphp/demo

**Comment by austincarpenter** [comment]
Surely the filament demo is a valid repo to submit?

**Comment by saschagysel** [comment]
The problem is also there with the average function. It seems to take only a few of the records in the group into account.

![image](https://github.com/filamentphp/filament/assets/58490316/8f4f1dab-4764-4af9-91ba-196a9c00f3b9)

**Comment by timwassenburg** [comment]
I can confirm this issue, it seems to get only the last value of the group when using `sum`.

<img width="297" alt="afbeelding" src="https://github.com/filamentphp/filament/assets/75377381/861ed7ef-5196-47d0-a7f7-58b7139e9180">

**Comment by danharrin** [comment]
This is an issue with date-based groups, which you should use `->date()` on the group to fix, introduced in #8394
