### ISSUE TITLE
AttachAction $titleAttribute vs. recordTitle()

### ISSUE THREAD

**Issue by danharrin** [laravel-filament/filament#7581]
### Discussed in https://github.com/filamentphp/filament/discussions/7568

<div type='discussions-op-text'>

<sup>Originally posted by **ajnsn** August  8, 2023</sup>
In v2 it was possible to have a $recordTitleAttribute on the RelationManager together with a custom recordTitle() on the AttachAction.

In v3 there's this if-clause (currently on line [268](https://github.com/filamentphp/filament/blob/3.x/packages/tables/src/Actions/AttachAction.php#L268)) which prefers the  $titleAttribute to the mapping with getRecordTitle() (currently on line [278](https://github.com/filamentphp/filament/blob/3.x/packages/tables/src/Actions/AttachAction.php#L278)) 

Took me a while to find out and it seems to be unwanted, at least from my side. The RelationManager's should be the fallback, not the priority.  This specifically prevents the ability to show HTML labels with the record select. Or is there any other way to achieve this in v3?

Thanks</div>

**Comment by ajnsn** [comment]
Thanks @danharrin for tracking this further.

**Comment by danharrin** [comment]
Should be fixed by #8992
