### ISSUE TITLE
If we make lot of pages like 1k+ pages then we go to last page its page numbering merge with the view data size (which is like 10, 25,50,all) data show) so this is problem please solve it 

### ISSUE THREAD

**Issue by DevVerma07** [laravel-filament/filament#7582]
### Package

filament/tables

### Package Version

v3.0

### Laravel Version

v10.0+

### Livewire Version

v3.0

### PHP Version

PHP 8.2+

### Problem description

If we make a lot of pages like 1k+ pages then we go to the last page its page numbering merges with the view data size (which is like 10, 25,50, all) data show) so this is a problem please solve it  
here is the image example for this [https://www.linkpicture.com/q/Screenshot-from-2023-08-09-12-13-04.png](url)

### Expected behavior

it should be moving right with the height of the page number line.

### Steps to reproduce

it only work for HTML codes

### Reproduction repository

https://github.com/DevVerma07/Filament-Beginner

### Relevant log output

```shell
hey please solve it.
```

**Comment by danharrin** [comment]
No real reproduction repo. No screenshots.

**Comment by DevVerma07** [comment]
I am sorry sir my official project is corrently is in private repo but had
sent you the screenshot link i am sorry i am beginner in coading as well as
in github so therefore i am not able to define the error/bug but i sent you
the screenshot through  a link.
Thank you i will definitely help you in future.
