### ISSUE TITLE
Repeater seems broken

### ISSUE THREAD

**Issue by Cannonb4ll** [laravel-filament/filament#7584]
### Package

filament/filament

### Package Version

V3

### Laravel Version

V10

### Livewire Version

V3 BETA.8

### PHP Version

PHP 8.2.6

### Problem description

Considering the following form:

```php
return $form
    ->schema([
        Forms\Components\Repeater::make('test')->columns(2)->schema([
            Forms\Components\TextInput::make('hi'),
            Forms\Components\Select::make('options')
                ->searchable()
                ->options([
                    'one', 'two'
                ])
        ]),
    ]);
```

The repeater seems completely broken when you have components that use JS, in this case, using `->searchable()` causes to introduce JS inside a component, which breaks the repeater badly. 

- It won't delete records at some point
- It will spawn multiple rows when you only press once
- It will spawn rows when you delete a record randomly
- It will cause scrolling to top issues

https://github.com/filamentphp/filament/assets/3110750/b17e65cf-31f9-4b8f-9fee-16ab3d3dd6f1

### Expected behavior

I expect the Repeater to not glitch so much with the bugs described above.

### Steps to reproduce

An code example is provided, you can just enter that in any resource you have.

### Reproduction repository

https://github.com/Cannonb4ll/filament-repeater-bug

**Comment by danharrin** [comment]
Dup of #7485

**Comment by danharrin** [comment]
livewire/livewire#6289
