### ISSUE TITLE
Modify table search debounce from `$table` configuration

### ISSUE THREAD

**Issue by danharrin** [laravel-filament/filament#7590]

**Comment by cipriannemtoc** [comment]
This might be a high priority as the search gets deleted chars after the request is completed and overrides the search string. Is there any other way to apply the debounce?

**Comment by danharrin** [comment]
You can try submitting a PR if you want.

**Comment by yannisc** [comment]
That would be nice to have for the global search as well.

**Comment by danharrin** [comment]
Again, feel free to submit a PR

**Comment by yannisc** [comment]
I just did
