### ISSUE TITLE
Translatable resource with media bug

### ISSUE THREAD

**Issue by anaseqal** [laravel-filament/filament#7591]
### Package

filament/spatie-laravel-translatable-plugin

### Package Version

v3.0.13

### Laravel Version

v10.18.0

### Livewire Version

v3.0.0-beta.8

### PHP Version

PHP 8.2.8

### Problem description

Editing translatable resource image throw exception: 

> Call to a member function hasGeneratedConversion() on null

Even if no conversion defined, there is still an error:

> Call to a member function getAttributeValue() on null

### Expected behavior

Edit image(s) without throwing errors

### Steps to reproduce

1. create a new customer and upload an image.
2. edit the customer and change the image then click save changes

![image](https://github.com/filamentphp/filament/assets/5034308/d358b091-6dc8-4b89-890c-7888d6933f6f)

### Reproduction repository

https://github.com/anaseqal/filament3-media-translation

**Comment by AlexanderFalkenberg** [comment]
Having the same issue.

**Comment by AxelDeneu** [comment]
Same here

**Comment by elnurxf** [comment]
One more here. Stuck for hours to figure it out. :/

**Comment by Saifallak** [comment]
Same here

**Comment by pieinn** [comment]
Same issue 
![issue](https://github.com/filamentphp/filament/assets/29000827/530e3f7a-efda-48d7-8295-529a950a97ec)

**Comment by awcodes** [comment]
Figured out the issue, not sure of how to resolve it though, @danharrin leaving this here for you to see what I'm seeing.

The issue is in the Translatable Plugin at Resources\Pages\EditRecord\Concerns\Translatable class.

When looping through the locales to save the record data is getting out of sync.

data in `save()` for 'en' loop:
![Screenshot 2023-08-26 at 2 59 26 PM](https://github.com/filamentphp/filament/assets/3596800/28d94a3e-c3a1-412d-b22e-f845cb4c38cf)

record in `handleRecordUpdate()`:
![Screenshot 2023-08-26 at 2 59 33 PM](https://github.com/filamentphp/filament/assets/3596800/ddecab6e-e16f-4db0-8c7c-f1f2beaa1433)

All good to this point.

data in `save()` for 'es' loop:
![Screenshot 2023-08-26 at 2 59 37 PM](https://github.com/filamentphp/filament/assets/3596800/ddd70f5d-a2a2-409b-a49d-862844de54e9)

record in `handleRecordUpdate()`:
![Screenshot 2023-08-26 at 2 59 42 PM](https://github.com/filamentphp/filament/assets/3596800/7c07f35c-bcdf-4569-a821-a042833c9c57)

Which means that when the 'es' handle record runs the 'media' state is [], which causes the FileUpload Plugin to delete the originally saved media item, resulting in it not existing when the state is refreshed after save.

**Comment by atmonshi** [comment]
@awcodes  I reached similar thing and didnt know were to go from there
I think it needed something like this to mearg the data
https://github.com/filamentphp/filament/pull/7503/files

but the `getState` in the edit is not getting the relations (it merges the data for all local if it's not relation like spatie uploader) so I don't know where to handle the "merge" for the data

**Comment by awcodes** [comment]
The issue is that non translated fields don't seem to be honoring their state separately. Somehow the media field, in this example, is existing in two different states. One for each locale.

**Comment by awcodes** [comment]
You can see that the es loop is getting updated with the origin values of the en loop but it's like it always a step behind.

**Comment by eroctra** [comment]
same issue

**Comment by PterodactylStore** [comment]
same issue

**Comment by danharrin** [comment]
Please stop commenting if you have the "same issue", there are 👍 reactions for that. Try submitting a PR if you would like to be helpful.

**Comment by pekka** [comment]
To clarify the original problem description, this appears to also happen when the image field itself is _not_ translatable. It is enough for the field to be inside a resource that `HasTranslations` (which I'd argue makes it a bit higher priority than "low"). 

Only workaround I can see at this point (for anyone under pressure to use spatie-translatable but also this field type RIGHT NOW) is to have a separate, `my_media` table and resource, upload the images there, and connect them to the original resource using a relationship.

**Comment by tahacankurt** [comment]
And somehow when you add some validation to FileUpload such as image() etc.. its showing error but saving eventually.

**Comment by robertorinaldi-dev** [comment]
I had a very similar issue (it gave me an error when trying to get the file_size).
Can you try if https://github.com/filamentphp/filament/pull/8432 solves the issue for you too?

**Comment by mohamedsabil83** [comment]
This issue still occurred as @awcodes explained [above](https://github.com/filamentphp/filament/issues/7591#issuecomment-1694483651). The #8432 seems doesn't fix it, or does it need extra steps @robertorinaldi-dev?

```
[
    'en' => [    
        'id' => 8,
        'position' => 5,
        'description' => '',
        'url' => '',
        'order_column' => 8,
        'created_at' => '2023-05-29T07:52:50.000000Z',
        'updated_at' => '2023-05-29T07:52:50.000000Z',
        'deleted_at' => null,
        'image' => [],,
    ],
    'ar' => [    
        'id' => 8,
        'position' => 5,
        'description' => '',
        'url' => '',
        'order_column' => 8,
        'created_at' => '2023-05-29T07:52:50.000000Z',
        'updated_at' => '2023-05-29T07:52:50.000000Z',
        'deleted_at' => null,
        'image' => [],,
    ],
]
```

**Comment by mohamedsabil83** [comment]
@robertorinaldi-dev, the #8432 seems doesn't fix it. It still occurred, as @awcodes explained [above](https://github.com/filamentphp/filament/issues/7591#issuecomment-1694483651).
Do you think it needs any extra steps?

```
[
    'en' => [    
        'id' => 8,
        'position' => 5,
        'description' => '',
        'url' => '',
        'order_column' => 8,
        'created_at' => '2023-05-29T07:52:50.000000Z',
        'updated_at' => '2023-05-29T07:52:50.000000Z',
        'deleted_at' => null,
        'image' => [],
    ],
    'ar' => [    
        'id' => 8,
        'position' => 5,
        'description' => '',
        'url' => '',
        'order_column' => 8,
        'created_at' => '2023-05-29T07:52:50.000000Z',
        'updated_at' => '2023-05-29T07:52:50.000000Z',
        'deleted_at' => null,
        'image' => [],
    ],
]
```

## Update
> [!IMPORTANT]
This happened in one of my projects using **stancl/tenancy**. For those who used that package, it happened on the tenant's site, not the central one. It may be related to changes in **Livewire 3**.

**Comment by danharrin** [comment]
Does not seem to be an issue any more, I've tried the reproduction repo.
