### ISSUE TITLE
Open a modal in a view page with 2 charts on it breaks the page

### ISSUE THREAD

**Issue by miguilimzero** [laravel-filament/filament#7626]
### Package

filament/filament

### Package Version

v3.0.15

### Laravel Version

v10.18.0

### Livewire Version

v3.0.0-beta7

### PHP Version

PHP 8.2.8

### Problem description

When you have a view resource page with more than one chart and then try to open a modal (ex. delete the resource modal), the page stop working, and everything breaks.

It seems related to an error when the code tries to re-spawn the chart canvas.

### Expected behavior

The modal opens normally and doesn't break the page.

### Steps to reproduce

- Clone the repository
- php artisan migrate
- php artisan make:filament-user
- Login to the panel
- Click to view your own user resource
- Click on the delete button to open the confirmation modal
- Bug appears

### Reproduction repository

https://github.com/miguilimzero/filament-chart-bug-example

### Relevant log output

![image](https://github.com/filamentphp/filament/assets/35383529/9b8afa76-1383-4d6f-b480-7fa6c342efda)

**Comment by miguilimzero** [comment]
It does not seem to be related to chart.js. If you put two stats widget, it will happen a similar error.

**Comment by zepfietje** [comment]
Stats overview widget also uses Chart.js for charts.

**Comment by awcodes** [comment]
This was a Livewire bug that has been fixed. 

Please update your composer.json to use "filament/filament": "^3.0" and run a composer update.

Verify by running `php artisan about` and make sure are on at least these versions:
![Screenshot 2023-08-26 at 3 18 17 PM](https://github.com/filamentphp/filament/assets/3596800/232053e1-7fd2-478c-b7d8-ff5831188430)
