### ISSUE TITLE
Custom table row borders

### ISSUE THREAD

**Issue by ajnsn** [laravel-filament/filament#7632]
### Package

filament/tables

### Package Version

v3.0.13

### Laravel Version

v10

### PHP Version

8.2

### Problem description

If using `Split` and `Stack` within a table, the dividing border get rendered twice, currently also visible within the Demo's authors list:
https://demo.filamentphp.com/blog/authors

The primary cause seems to be [L503](https://github.com/filamentphp/filament/blob/3.x/packages/tables/resources/views/index.blade.php#L503)). 

There's also a double border between the header and the first row if you're not using at least one sortable column. Origin seems to be the divide-Class in [L381](https://github.com/filamentphp/filament/blob/3.x/packages/tables/resources/views/index.blade.php#L381)

As I do not know all the possbile combinations, I am quite stucked how to solve via a PR without breaking any other layout approach. Just wanted to bring this to your attention. If you have an idea how to solve this, I am happy to provide a PR. Thank you!

### Expected behavior

No double borders :)

### Steps to reproduce

Add `Split` and `Stack` columns to any table layout.
Test

### Reproduction repository

https://github.com/ajnsn/filament-demo-borders

**Comment by danharrin** [comment]
This is actually deliberate, I think Zep encountered a browser bug where the single divider would not be rendered at all. You're welcome to attempt a PR to fix it.

**Comment by ajnsn** [comment]
Ah :)
I've tested on Mac Safari, Chrome and Firefox and both have the doubled border - which looks ImHo not to good, especially if you move from one column-table to a grid-table.

 If you have any insight where this bug occured, let me know.

**Comment by danharrin** [comment]
Yeah I agree that it doesn't look good, but we could not get a 1px border to consistently render. You are welcome to attempt to do it, because we probably won't be able to, we've already tried.

**Comment by zepfietje** [comment]
Reopened this issue as https://github.com/filamentphp/filament/pull/7636 doesn't entirely fix the issue.

**Comment by zepfietje** [comment]
Closing in favor of https://github.com/filamentphp/filament/issues/7784.
