### ISSUE TITLE
Stats chart line disappearing on polling

### ISSUE THREAD

**Issue by CodeWithDennis** [laravel-filament/filament#7635]
### Package

filament/filament

### Package Version

v3.0.16.0

### Laravel Version

v10.10

### PHP Version

PHP 8.1.0

### Problem description

The chart line is disappearing on polling (refreshing)

Start happening after `v3.0.8` https://github.com/filamentphp/filament/pull/7468

https://github.com/filamentphp/filament/assets/23448484/cd0c848d-57b9-4802-9bb0-3ee8e90b36cc

### Expected behavior

Show the new data line

### Steps to reproduce

Create a stats chart and add it to the dashboard

### Reproduction repository

https://github.com/CodeWithDennis/filament-chart-line-bug

**Comment by CodeWithDennis** [comment]
Bugs out on: Brave, IE, Chrome, Safari
Works on: Firefox

**Comment by danharrin** [comment]
Fixed by #7653
