### ISSUE TITLE
Adding form fields to AttachAction does not work

### ISSUE THREAD

**Issue by bram-pkg** [laravel-filament/filament#7649]
### Package

filament/tables

### Package Version

v3.0.16

### Laravel Version

v10.18.0

### Livewire Version

v3.0.0-beta.7

### PHP Version

PHP 8.2.8

### Problem description

When adding an AttachAction to a table inside a RelationManager, any custom fields added to it using `->form()` do not show up. Below are two images and the resulting form:

![image](https://github.com/filamentphp/filament/assets/13304739/1a4a0be4-94cf-4fe5-88ba-afed945678af)

![image](https://github.com/filamentphp/filament/assets/13304739/16e5941c-9e6d-4c2a-8b77-799d265f6caf)

A link to the relation manager that is misbehaving: https://github.com/bram-pkg/filament-issue-7649/blob/main/app/Filament/Admin/Resources/TenantResource/RelationManagers/UsersRelationManager.php#L43-L49

Note that I have confirmed with the documentation that this is the expected syntax.

### Expected behavior

It's expected that the select dropdown shows up underneath the user selection dropdown.

### Steps to reproduce

Create an AttachAction inside a RelationManager and add a custom field to the form with code like:

```php
Tables\Actions\AttachAction::make()
    ->preloadRecordSelect()
    ->form(fn (Tables\Actions\AttachAction $action): array => [
        $action->getRecordSelect(),
        Forms\Components\TextInput::make('role')->required(),
    ])
```
                   

### Reproduction repository

https://github.com/bram-pkg/filament-issue-7649

**Comment by bram-pkg** [comment]
I've imported the repo to GitHub, hopefully that's fine now.

**Comment by danharrin** [comment]
I have a feeling this is to do with the `emptyStateActions()` AttachAction with the same name... can you try moving the custom form to there instead? Whichever action is defined last will be used I think.

**Comment by bram-pkg** [comment]
That seems to have fixed the form rendering, yes. It feels a bit unintuitive, though. Any chance this behaviour could be adjusted in the future? (I noticed you added this to the roadmap, so I'm guessing you have already)

**Comment by danharrin** [comment]
I don't really know how to fix it yet to be honest. All issues are added to the roadmap automatically

**Comment by bram-pkg** [comment]
Hm okay. Let's see then, it would be good to note this in the docs regardless of if there's a fix coming!

**Comment by zepfietje** [comment]
Closing this issue as it isn't a bug really. (Also see https://github.com/filamentphp/filament/issues/7547#issuecomment-1685844698.)

Might have to add a note to the docs indeed as multiple people seem to run into this, @danharrin.

**Comment by danharrin** [comment]
I want to work out a way to fix it, hence why I kept it open

**Comment by zepfietje** [comment]
Okay, let's keep this issue open then and leave the other duplicate closed.
