### ISSUE TITLE
[2.x] Mixed Key-Value in KeyValue Form Component

### ISSUE THREAD

**Issue by raphael-evolutap** [laravel-filament/filament#765]
### Package

filament/filament

### Package Version

v2.5.6

### Laravel Version

v8.75.0

### Livewire Version

v2.8.1

### PHP Version

PHP 8.1.0

### Bug description

After save and reloading page, it is mixing key and values.

I'm using a json column in DB.
Casting to  AsArrayObject::class in model.

![unknown](https://user-images.githubusercontent.com/47394773/145109012-25e7c9f9-8c0c-4da9-a4ca-541e5f944280.png)

![unknown 1](https://user-images.githubusercontent.com/47394773/145109076-88d4c203-07fc-4d1f-b7a8-c920071b0bcf.png)

### Steps to reproduce

- Fill key value
- Save 
- Reload page

**Comment by danharrin** [comment]
Fixed in #833 :)
