### ISSUE TITLE
file upload not display image when field is full url

### ISSUE THREAD

**Issue by febelery** [laravel-filament/filament#7669]
### Package

filament/filament

### Package Version

3

### Laravel Version

10

### Livewire Version

3

### PHP Version

8.2

### Problem description

image url is `xxxxxxxx.png` show
but `http://localhost/storage/xxxxxxxx.png` not show

### Expected behavior

`http://localhost/storage/xxxxxxxx.png` show

### Steps to reproduce

```php
 Forms\Components\FileUpload::make('title')
                        ->image()
                        ->openable()
                        ->imageEditor()
                        ->downloadable()
                        ->imageEditorEmptyFillColor('#000000')
                        ->imageEditorAspectRatios([
                            '16:9',
                            '4:3',
                            '1:1',
                        ])
```

### Reproduction repository

https://github.com/filamentphp/filament

**Comment by thethunderturner** [comment]
I think you missed some steps. Try the following:
1) Go to the .env file and add the port :8000 (or whatever port you are using) to the APP URL
2) Type `php artisan storage:link `

Then it should work:)

**Comment by febelery** [comment]
> I think you missed some steps. Try the following:
> 
> 1. Go to the .env file and add the port :8000 (or whatever port you are using) to the APP URL
> 2. Type `php artisan storage:link `
> 
> Then it should work:)

I know `php artisan storage:link`.
I need `http://localhost/storage/xxxxxxxx.png` can show when field is `Forms\Components\FileUpload`.
`http://localhost/storage/xxxxxxxx.png` is the correct url path accessible

**Comment by danharrin** [comment]
The path for the file upload should be relative to the storage disk that you're using. Otherwise we don't know where the file is located that we are interacting with.

**Comment by tanthammar** [comment]
Maybe this is a preserve original filename thing?

**Comment by MarJose123** [comment]
In my case, I'm using cloudinary.

Approach on what I did, and it works for me for full URL instead of relative path
https://gist.github.com/MarJose123/195d5d7d88b4daa70fb8a7bde8279ace

**Comment by aoeng** [comment]
@MarJose123  only use `getUploadedFileUsing` not work,but and use `afterStateHydrated` is working! 
```
 Forms\Components\FileUpload::make('picture')
                    ->image()
                    ->afterStateHydrated(static function (BaseFileUpload $component, string|array|null $state) {
                        if (blank($state)) {
                            $component->state([]);
                            return;
                        }
                        $component->state([((string) Str::uuid()) => $state]);
                    })
                    ->getUploadedFileUsing(static function (BaseFileUpload $component, string $file, string|array|null $storedFileNames): ?array {

                        return [
                            'name' => basename($file),
                            'size' => 0,
                            'type' => null,
                            'url' => Storage::url($file),
                        ];
                    }),
```
I don't know why not show image? use this:
```
Forms\Components\FileUpload::make('picture')
                    ->image()
```
I use `oss`

**Comment by MarJose123** [comment]
> [@MarJose123](https://github.com/MarJose123) only use `getUploadedFileUsing` not work,but and use `afterStateHydrated` is working!
> 
> ```
>  Forms\Components\FileUpload::make('picture')
>                     ->image()
>                     ->afterStateHydrated(static function (BaseFileUpload $component, string|array|null $state) {
>                         if (blank($state)) {
>                             $component->state([]);
>                             return;
>                         }
>                         $component->state([((string) Str::uuid()) => $state]);
>                     })
>                     ->getUploadedFileUsing(static function (BaseFileUpload $component, string $file, string|array|null $storedFileNames): ?array {
> 
>                         return [
>                             'name' => basename($file),
>                             'size' => 0,
>                             'type' => null,
>                             'url' => Storage::url($file),
>                         ];
>                     }),
> ```
> 
> I don't know why not show image? use this:
> 
> ```
> Forms\Components\FileUpload::make('picture')
>                     ->image()
> ```
> 
> I use `oss`


`getUploadedFileUsing ` This will be called by the filament once you upload a new image for preview, and `afterStateHydrated` will be called after fetching records from the DB.

If you are using Cloudinary or another cloud storage provider that isn't compatible with AWS SDK, then you need to modify the filament on how it retrieve and saves into the DB

**Comment by hoachan** [comment]
let's update .env with "APP_URL" value to match your domain setting (for example : I'm setting the hostname for my enviroment is "latasa.dev" --> APP_URL in .env is latasa.dev, hoping your problem done
