### ISSUE TITLE
Setting a Toggle field to disable does nothing

### ISSUE THREAD

**Issue by kirkbushell** [laravel-filament/filament#7690]
### Package

filament/filament

### Package Version

v3.0.12

### Laravel Version

v10.10

### Livewire Version

v3 beta 7

### PHP Version

PHP 8.1.22

### Problem description

If you set a toggle to disabled, as below:

```php
Toggle::make('toggle')->disabled()
```

The toggle is still modifiable, and can have its state changed.

### Expected behavior

The toggle should not be modifiable and should maintain whatever state it is set to (for example if the default value is true or false, it should respect that value, in addition to not being modifiable).

### Steps to reproduce

Set a toggle field, set it to disabled.

### Reproduction repository

-

**Comment by dev3k** [comment]
same here with latest version of filament  v3.0.27

**Comment by iotron** [comment]
https://github.com/filamentphp/filament/pull/7505

It's a bug in Livewire

**Comment by iotron** [comment]
https://github.com/livewire/livewire/pull/6353

PR on Livewire

**Comment by zepfietje** [comment]
Could y'all test this with Livewire [v3.0.0-beta.10](https://github.com/livewire/livewire/releases/tag/v3.0.0-beta.10)?

**Comment by dev3k** [comment]
working here 👍

**Comment by zepfietje** [comment]
Thanks for the quick reply, @dev3k!
I'm failing to make it work on my end though. 🤔
Seems like the main issue with `disabled` was fixed but toggles still don't honor their disabled state: https://github.com/filamentphp/filament/issues/7093#issuecomment-1685804579.

**Comment by zepfietje** [comment]
Let's move all discussion to https://github.com/filamentphp/filament/issues/7370.

**Comment by dev3k** [comment]
one more thing I just noticed, not sure if related to new Livewire or new filament release but tabs in list page lost "activeTab" query param when navigating between tabs, downgrading filament v3.0.27 => v3.0.23 Livewire v3.0.0-beta.10 => v3.0.0-beta.9 fixed it

**Comment by zepfietje** [comment]
Please open a separate issue for that if no exists yet, @dev3k.
