### ISSUE TITLE
mutateFormDataUsing() not called on create action of simple (modal) resources

### ISSUE THREAD

**Issue by xahmedtaha** [laravel-filament/filament#7695]
### Package

filament/filament

### Package Version

v3.0.18

### Laravel Version

v10.18.0

### Livewire Version

v3.0.0-beta.7

### PHP Version

PHP 8.1.10

### Problem description

In **simple (modal) resources** `mutateFormDataUsing()` doesn't get called on the **create action**. Even a `dd()` doesn't interrupt the code.

### Expected behavior

`mutateFormDataUsing()` should get called properly to allow form data manipulation in **simple (modal) resources**.

### Steps to reproduce

1. Create a simple (modal) resource (`php artisan make:filament-resource --simple`)
2. Call `mutateFormDataUsing()` on the create action in the ManageResource file
![image](https://github.com/filamentphp/filament/assets/26720111/12ca9274-e498-4d68-9148-0f6704ae603e)

### Reproduction repository

https://github.com/xahmedtaha/filament-mutateFormDataUsing-bug-reproduction

**Comment by xahmedtaha** [comment]
While playing around with this I noticed that even the `using()` method is disregarded.
![image](https://github.com/filamentphp/filament/assets/26720111/eefe538e-146e-4cb1-821f-8330aaf92bec)


Apparently, I can't customize the creation process at all.

**Comment by danharrin** [comment]
I think you're pressing the empty state action instead of the header action?

**Comment by MtoMCreation** [comment]
Same error  here
It gives me a "SQLSTATE[23000]: Integrity constraint violation: 19 NOT NULL constraint failed: categories.slug"
<img width="603" alt="Capture d’écran, le 2023-08-28 à 15 37 58" src="https://github.com/filamentphp/filament/assets/41706853/5927791e-c7f3-498e-b460-5a5dac680966">

**Comment by MtoMCreation** [comment]
Just saw the from answer @zepfietje on the issue #7547

"All actions inside a Livewire component should have a unique name.
Since you're using CreateAction twice (header and empty state), modifications to the header action don't actually work, since the empty state action get's triggered (because of the duplicate name, as CreateAction instances have a default name of create).

This isn't a bug, though I understand it's confusing when you encounter it at first.
So, make sure to pass a unique name if you're using multiple instances of prebuilt actions on a single Livewire component."

**Comment by lupinitylabs** [comment]
Can confirm this issue, `using()`, `mutateFormDataUsing()` etc. are not executed for me in one Filament 3.2.x project. Weirdly enough, it works in another. Other things like the button color or the label are set correctly, however.

I could track this down to the `action()` closure not being executed in `Filament\Tables\Actions\CreateAction` line 45.

For everyone having issues with this: I have found a workaround overwriting the `handleRecordCreation()` method of the CreateRecord page.

```php
    protected function handleRecordCreation(array $data): Model
    {
        // Mutate $data if needed...

        $createdRecord = parent::handleRecordCreation($data);

        // Do whatever else you want to do with the record...

        return $createdRecord;
    }
```

This is not documented, but I am quite ok with this solution.

**Comment by danharrin** [comment]
If there is a page, customisations made to the action do not apply. They apply to the modal if you don't have a page.

<img width="893" alt="Screenshot 2024-07-10 at 11 40 33" src="https://github.com/filamentphp/filament/assets/41773797/b88a1660-9da5-40dc-a29f-67ac01a9e1bf">

**Comment by lupinitylabs** [comment]
> If there is a page, customisations made to the action do not apply. They apply to the modal if you don't have a page.

Oh! Thanks!
I just didn't find anything but the `mutateFormDataUsingBeforeCreate()` method there, and had the impression that just using `handleRecordCreation` feels a bit hacky. But this is actually the proper stand-in for `using` then?

**Comment by Costigan-Stephen** [comment]
This is a closed topic, but I wanted to pass on as I stumbled here too and wanted to help the next person.

These functions are not broken, they simply work after the record is created. The best function to use [fillForm()](https://filamentphp.com/docs/3.x/actions/modals#filling-the-form-with-existing-data). As a quick reference using your example code:

```
CreateAction::make()
    // whatever else
    ->model(YourModel::class)
    ->fillForm([
        'random_number' => rand(0,100)
    ])
    ->form(fn (Form $form) => // your logic here, or a call to an existing resource )
```

**Comment by sourcecodeit** [comment]
I need help with this. I understand I can customize the CreateAction, the problem is I don't understand **where**.

I have a modal for creating new records (read: I removed the create page from the pages array). So I don't have a place where I can place this:

```
CreateAction::make()
    // whatever else
    ->model(YourModel::class)
    ->fillForm([
        'random_number' => rand(0,100)
    ])
    ->form(fn (Form $form) => // your logic here, or a call to an existing resource )
```

**Comment by danharrin** [comment]
`CreateAction::make()` will be in the List/Manage page of the resource in the headeractions
