### ISSUE TITLE
Remove and Edit buttons overlap on FileUpload field with both avatar() and imageEditor()

### ISSUE THREAD

**Issue by kitbs** [laravel-filament/filament#7703]
### Package

filament/forms

### Package Version

v3.0.19

### Laravel Version

v10.18.0

### Livewire Version

v3.0.0-beta.7

### PHP Version

8.2.8

### Problem description

When attempting to use avatar() and imageEditor() on a FileUpload field, the X (remove) icon is overlapped by the pencil (edit) icon, so only the pencil is clickable.

### Avatar field without editor

```php
FileUpload::make('avatar')
    ->avatar()
```
![image](https://github.com/filamentphp/filament/assets/4569320/1fad13ac-ee76-4d7c-9b5d-446055c18d43)

### Avatar field with editor

```php
FileUpload::make('avatar')
    ->avatar()
    ->imageEditor()
```

![image](https://github.com/filamentphp/filament/assets/4569320/ef0407b9-fba8-491d-9c39-7d1f8e7c1c0b)

### Detail of overlapping buttons
![image](https://github.com/filamentphp/filament/assets/4569320/b138f9e3-57e6-41cc-b4b0-fcac019ca0b3)

### Expected behavior

Although there is not much room for both buttons to be displayed in the avatar circle, it should be possible to both remove the avatar and also edit it using the image editor. 

### Steps to reproduce

1. Add the following field to a resource's form:

```php
FileUpload::make('avatar')
    ->avatar()
    ->imageEditor()
```

2. Navigate to the resource's edit page

### Reproduction repository

https://github.com/kitbs/filament-7703

**Comment by danharrin** [comment]
Unfortunately we cannot do anything about this, it's how Filepond is designed. You cannot use the avatar layout with the editor

**Comment by kitbs** [comment]
Hi @danharrin

The Filepond demo shows the remove and edit buttons side by side: https://pqina.nl/filepond/#profile-picture-demo

![image](https://github.com/filamentphp/filament/assets/4569320/28d61acd-ed13-4b0b-b633-a931c047442c)

This seems to be achieved with the option `styleButtonRemoveItemPosition: 'left bottom'`

**Comment by danharrin** [comment]
Okay go on then, you can PR it if you want :) Didn't know this layout existed
