### ISSUE TITLE
Issue with test

### ISSUE THREAD

**Issue by datlechin** [laravel-filament/filament#7704]
### Package

filament/filament

### Package Version

v3.0.19

### Laravel Version

latest

### Livewire Version

lateest

### PHP Version

latest

### Problem description

when running pest test it shows:

```log
Call to a member function auth() on null (View: /home/ngoquocdat/Workspace/polycasts/storage/framework/views/a168b0ebcff266df6b662fc4b6d06e88.blade.php)

  at vendor/filament/filament/src/FilamentManager.php:50
     46▕     protected ?Model $tenant = null;
     47▕ 
     48▕     public function auth(): Guard
     49▕     {
  ➜  50▕         return $this->getCurrentPanel()->auth();
     51▕     }
```

my pest code:
```php
it('can render page', function () {
    $this->actingAs(\App\Models\User::factory()->create());

    livewire(ListPosts::class)->assertSuccessful();
});

```

### Expected behavior

pass

### Steps to reproduce

Run the above Pest code and it wills show the error

### Reproduction repository

https://github.com/datlechin/filament

**Comment by danharrin** [comment]
No reproduction repo. Please don't be lazy

**Comment by jhoanborges** [comment]
This worked for me:
Try adding this line to you **config/app.php**

` App\Providers\Filament\AdminPanelProvider::class
`

**Comment by amirrezashahidi83** [comment]
I have the same issue. 
this is my code:

```
<?php
namespace Tests\Feature;

use function Pest\Livewire\livewire;
it('creates admin',function () {
        livewire(\App\Filament\Resources\AdminResource\Pages\CreateAdmin::class)
        ->fillForm([

        ])
        ->call('create')
        ->assertHasNoFormErrors();
    }
);

```
and this is my repository:

https://github.com/amirrezashahidi83/risman-admin
