### ISSUE TITLE
issue with getRouteKeyName function

### ISSUE THREAD

**Issue by PterodactylStore** [laravel-filament/filament#7706]
### Package

filament/filament

### Package Version

v3.0.19

### Laravel Version

v10.18.0

### Livewire Version

v3.0.0-beta.8

### PHP Version

PHP 8.2.8

### Problem description

when using this function in Post Model to get slug in the route instead id in the edit route/page
```php
public function getRouteKeyName()
{
    return 'slug';
}
```
getting error 404 not found

### Expected behavior

Expected to work and getting slug in the url instead id
for example ``/admin/post/{slug}/edit`` instead ``/admin/post/{id}/edit``

### Steps to reproduce

create new post from admin
then try to view or edit the post created (getting error 404)
becasue this in the Post Model
```php
public function getRouteKeyName()
{
    return 'slug';
}
```

then try to visit edit page 

### Reproduction repository

https://github.com/PterodactylStore/filament-test

**Comment by danharrin** [comment]
In the resource, set `$recordRouteKeyName` to `slug`

**Comment by PterodactylStore** [comment]
need to set slug->locale
becasue i try this only and not work:
```php
protected static ?string $recordRouteKeyName = 'slug';
```

when try this its work
```php
protected static ?string $recordRouteKeyName = 'slug->en';
```

i try to make it dynamic but not working
```php
protected static ?string $locale = app()->getLocale();
protected static ?string $recordRouteKeyName = 'slug->$locale';
```

**Comment by StefanoTesla** [comment]
I got the same problem too

**Comment by aaykacc** [comment]
\Filament\Resources\Pages\CreateRecord
protected function getRedirectUrl(): string
    {
        $resource = static::getResource();

        if ($resource::hasPage('view') && $resource::canView($this->getRecord())) {
            return $resource::getUrl('view', ['record' => $this->getRecord(), ...$this->getRedirectUrlParameters()]);
        }

        if ($resource::hasPage('edit') && $resource::canEdit($this->getRecord())) {
           // put "->id" here
            return $resource::getUrl('edit', ['record' => $this->getRecord()->id, ...$this->getRedirectUrlParameters()]);
        }

        return $resource::getUrl('index');
    }
    
    or 
    
    // redirect to the index (list) page after creating a record in the create page
    protected function getRedirectUrl(): string
	{
		return $this->getResource()::getUrl('index');
	}
