### ISSUE TITLE
Filament search not working on Postgres Database but working fine in mysql

### ISSUE THREAD

**Issue by khanakia** [laravel-filament/filament#7717]
### Package

filament/filament

### Package Version

^3.0-stable (v3.0.19)

### Laravel Version

10.18.0

### Livewire Version

v3

### PHP Version

PHP 8.2

### Problem description

Search is not working in Postgres nor Case Sensitive or Case Insensitive.

### Expected behavior

The search should work.

### Steps to reproduce

1. I have committed the `.env` and `filament_search_pg.sql` files within the root directory
2. Restore the POSTGRES database file
3. Run `php artisan serve`
4. Login with user: `admin@admin.com` and pass: `admin`
5. Search for any item it won't work

### Reproduction repository

https://github.com/khanakia/filament_search_pg

### Relevant log output

```shell
1. On searching anything e.g. `Java` filament converts all the searches to lowercase under the hood
2. Then it runs this query `select count(*) as aggregate from "items" where ("name"::text like ?) ["%wood%"]`

But Postgres uses the ILIKE operator for case Insensitive queries. So we should send ILIKE if the database is Postgres.
```

https://github.com/filamentphp/filament/assets/2174170/51f26024-22f5-40a9-8f7c-f589432e5e40

**Comment by timsinakiran** [comment]
I can confirm this is a legit bug. I have two production filament admin panels both of which are using Postgres, and searchable is not working in both.

**Comment by timsinakiran** [comment]
UPDATE: This is rather strange bug. 

It works with first letter removed from search query in single word searches. And does not work at all when two full words are types. So I believe it has some issues at the query with the way search is implemented.

**Comment by timsinakiran** [comment]
PR: 
https://github.com/timsinakiran/filament/compare/3.x...timsinakiran-postgres-search-patch

**Comment by timsinakiran** [comment]
Fix:

Search works at once with ->forceSearchCaseInsensitive()

**Comment by danharrin** [comment]
You shouldn't need to use that setting anymore
