### ISSUE TITLE
[2.x] Avatar url in left bottom is wrong

### ISSUE THREAD

**Issue by webparadoxer** [laravel-filament/filament#773]
### Package

filament/filament

### Package Version

2.0

### Laravel Version

8.75.0

### Livewire Version

2.8

### PHP Version

8.0.11 

### Bug description

Avatar url in left bottom is wrong
`<div class="w-11 h-11 rounded-full bg-gray-200 bg-cover bg-center" style="background-image: url('JRhKLAUF8J8KrvGWc8AieAZSX13c4SpS0unu2yee.jpg')"></div>
`
/storage/ missed

### Steps to reproduce

    public function getFilamentAvatarUrl(): ?string
    {
        return $this->avatar_url;
    }

**Comment by ryangjchandler** [comment]
@webparadoxer You probably want to do a `Storage::url()` or something.

**Comment by webparadoxer** [comment]
but in table all ok, and left corner going from admin, not me

**Comment by webparadoxer** [comment]
hmm, and second problem - if clear avatar_url showing ok from ui-avatars.com
but nothing in table

**Comment by webparadoxer** [comment]
https://filamentadmin.com/docs/2.x/admin/users#setting-up-avatars

**Comment by danharrin** [comment]
You need to wrap your URL in `Storage::url()` within `getFilamentAvatarUrl()`.

**Comment by webparadoxer** [comment]
> You need to wrap your URL in `Storage::url()` within `getFilamentAvatarUrl()`.



> You need to wrap your URL in `Storage::url()` within `getFilamentAvatarUrl()`.

but how can show avatars from  ui-avatars in table?

**Comment by ryangjchandler** [comment]
@webparadoxer The ui-avatars are automatically generated.
