### ISSUE TITLE
center notifications to the center or bottom not working

### ISSUE THREAD

**Issue by alkoumi** [laravel-filament/filament#7750]
### Package

filament/filament

### Package Version

v3

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

8.2

### Problem description

center notifications to the center or bottom not working

### Expected behavior

center notifications to the center or bottom not working

### Steps to reproduce

center notifications to the center or bottom not working

### Reproduction repository

https://github.com/alkoumi/huda

### Relevant log output

```shell
center notifications to the center or bottom not working
```

**Comment by leandrocfe** [comment]
https://github.com/filamentphp/filament/discussions/7748

**Comment by zepfietje** [comment]
We can't help when no clear reproduction steps are provided and the reproduction repo just contains an initial commit.
