### ISSUE TITLE
Dark Mode Inconsistency: Streaks of Varying Darkness around Elements and Half of Dashboard Screen in Chromium Browsers

### ISSUE THREAD

**Issue by andrewdwallo** [laravel-filament/filament#7759]
### Package

filament/filament

### Package Version

v3.0.21

### Laravel Version

v10.18.0

### Livewire Version

v3.0.0-beta.7

### PHP Version

PHP 8.2.8

### Problem description

While using dark mode in an application using Filament, I noticed some inconsistencies in the display. Specifically, half of the screen and areas around certain elements exhibit different shades of darkness, resulting in noticeable streaks. This issue affects the overall visual appearance and user experience. This bug is only present in Chromium Browsers (Edge and Chrome) and not Safari. I have not tried Firefox or other browsers.

### Chrome:
![Screenshot 2023-08-14 at 5 33 09 PM](https://github.com/filamentphp/filament/assets/104294090/ab86bec1-5556-4be5-8d83-28015f7037a6)

### Edge:
![Screenshot 2023-08-14 at 5 32 42 PM](https://github.com/filamentphp/filament/assets/104294090/e4ba2fa8-cc45-4c28-83e7-61cd82323396)

### Edge:
![Screenshot 2023-08-12 at 9 53 38 PM](https://github.com/filamentphp/filament/assets/104294090/11b1572b-06c3-4ca2-9ff4-e4926dac1650)

### Safari:
![Screenshot 2023-08-14 at 5 33 47 PM](https://github.com/filamentphp/filament/assets/104294090/923e0adf-f71a-43fb-8d91-a8622a1535ac)

### Expected behavior

The dark mode should provide a consistent color scheme, with uniform shades of darkness across all elements and areas of the screen in most if not all browsers. Chrome and Edge are very popular browsers which is why I'm surprised this has not been addressed recently by anyone. I have no extensions in both Chromium browsers. I actually just got a new computer and just downloaded both browsers recently.

### Steps to reproduce

Steps:
1. Use any Chromium Browser (Edge or Chrome)
2. Download reproduction repository (or any repository should do).
3. Navigate to any page in Filament.
4. Enable dark mode.
5. Observe the streaks of varying darkness around elements (or half the screen in the panel).

### Reproduction repository

https://github.com/andrewdwallo/company

**Comment by 199ocero** [comment]
I've got this issue too since I'm using edge browser like half bottom part is more darker than the upper part.

**Comment by andrewdwallo** [comment]
@199ocero Yeah I'm not sure how this could be fixed on their side.

**Comment by danharrin** [comment]
I'm sorry, but I don't know how we can even fix this within Filament? If you have any ideas, go PR, but I don't think it's worth keeping this issue open as there is nothing actionable really?

**Comment by andrewdwallo** [comment]
@danharrin It just kind of sucks because it's such a noticeable thing and affects the entire view to the user. I will try to do some research and see if anything can be fixed here.
