### ISSUE TITLE
isIndividual searchable field lose focus after lazy load

### ISSUE THREAD

**Issue by hsul4n** [laravel-filament/filament#7767]
### Package

filament/tables

### Package Version

v3.0.14.0

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

PHP 8.2

### Problem description

When start typing on individual search table column after finish writing the focus is lost and I should press on the field again to finish writing and when no result found the field is disappeared and not showing anymore unless clear filters again.

### Expected behavior

- Field should be focused while typing and after typing.
- Filed should not be disappeared if result not found.

### Steps to reproduce

- Add searchable `TextColumn` field and add `isIndividual: true` property then start writing and focus will be lost and hide when no result found.

### Reproduction repository

https://github.com/hsul4n/filamentphp-demo

**Comment by sakanjo** [comment]
The same happens with me, plus the search filters are not saved

Waiting for a confirm from the assignees so i can start working on it

**Comment by danharrin** [comment]
Doesn't appear to be a problem in the latest release.
