### ISSUE TITLE
[2.x]  MultipleFileUpload json

### ISSUE THREAD

**Issue by webparadoxer** [laravel-filament/filament#778]
### Package

filament/forms

### Package Version

2.5.9

### Laravel Version

8.75.0

### Livewire Version

2.7

### PHP Version

8.01

### Bug description

In database media type TEXT

After

`
Forms\Components\MultipleFileUpload::make('media')
                    ->uploadComponent(
                        Forms\Components\FileUpload::make('file')->image(),
                    )
`

`{"0":"nw9PGSmTxoJp2R7iX2R3i3k9SbPZlTI5mnwCFfaW.jpg","1cfd2d0c-5877-45c9-9755-cba3e4de010a":{"file":"nw9PGSmTxoJp2R7iX2R3i3k9SbPZlTI5mnwCFfaW.jpg"},"07434681-60fa-4f43-ae3b-07b885386066":{"file":null}}`

**Comment by danharrin** [comment]
Update: this PR to Livewire is to blame for this - https://github.com/livewire/livewire/pull/4239

**Comment by danharrin** [comment]
Fixed by #787.

**Comment by danharrin** [comment]
This has now been released in Livewire v2.8.2. Please update :)
