### ISSUE TITLE
double quotes in form data can sometimes cause Livewire error when loaded reactively 

### ISSUE THREAD

**Issue by pintend** [laravel-filament/filament#7796]
### Package

filament/filament

### Package Version

v2.17.52

### Laravel Version

v10.19

### Livewire Version

v2.12.6

### PHP Version

PHP 8.2.8 - Herd

### Problem description

This may happen in other places too but I bumped into it at `TextInput::placehoder()`

If for whatever reason there is a double quote which gets dynamically rendered in the placeholder there is a `DOMException: Failed to execute 'setAttribute' on 'Element': 'xxx"' is not a valid attribute name.` This error is coming from Livewire.js Here is a similar error https://github.com/livewire/livewire/issues/37

In my case I have a field which renders a placeholder for default text which is generated from other user inputs, the placeholder is showing the user what it would look like if they don't override the text (leave the input blank they get the generated input, or they can fill it out...)

Background: 
Issue has been reported by a client who said when trying to edit specific records the edit modal would not load (those records were imported via csv so they never had the issue when creating with a filament form) upon further investigation (linked repo is what was used to debug) I discovered the cause

Temporary (or maybe permanent) fix:

use Laravel e helper to html encode the " characters
```php
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('name')->reactive(),
                Forms\Components\TextInput::make('test')->placeholder(fn (Closure $get) => e($get('name')))
            ]);
    }
```

### Expected behavior

Render content without an error

### Steps to reproduce

```php
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('name')->reactive(),
                Forms\Components\TextInput::make('email'),
                Forms\Components\TextInput::make('test')->placeholder(fn (Closure $get) => $get('name'))
            ]);
    }
```

Type a double quote " in the name field and check the console logs

### Reproduction repository

https://github.com/pintend/livewirefillamentbug

### Relevant log output

```shell
index.js:152 Uncaught (in promise) DOMException: Failed to execute 'setAttribute' on 'Element': 'xxxxxx"' is not a valid attribute name.
    at Element.setAttribute (https://example.com/livewire/livewire.js?id=90730a3b0e7144480175:13:162292)
    at morphAttrs (https://example.com/livewire/livewire.js?id=90730a3b0e7144480175:13:94937)
    at morphEl (https://example.com/livewire/livewire.js?id=90730a3b0e7144480175:13:100976)
    at https://example.com/livewire/livewire.js?id=90730a3b0e7144480175:13:102432
    at morphEl (https://example.com/livewire/livewire.js?id=90730a3b0e7144480175:13:104253)
    at https://example.com/livewire/livewire.js?id=90730a3b0e7144480175:13:102432
    at morphEl (https://example.com/livewire/livewire.js?id=90730a3b0e7144480175:13:104253)
    at https://example.com/livewire/livewire.js?id=90730a3b0e7144480175:13:102432
    at morphEl (https://example.com/livewire/livewire.js?id=90730a3b0e7144480175:13:104253)
    at https://example.com/livewire/livewire.js?id=90730a3b0e7144480175:13:102432
```

**Comment by danharrin** [comment]
Is it worth keeping this issue open if it's just a Livewire bug?

**Comment by danharrin** [comment]
Gonna close this as there's not much we can do on our end, thanks for the report though 👍
