### ISSUE TITLE
Changing logo : Livewire encountered a missing root tag when trying to render a component. When rendering a Blade view, make sure it contains a root HTML tag.

### ISSUE THREAD

**Issue by swrtom** [laravel-filament/filament#7800]
### Package

filament/filament

### Package Version

v3.0.0

### Laravel Version

v10.19.0

### PHP Version

PHP 8.2.5

### Problem description

When I created views/vendor/filament-panels/components/brand.blade.php and added my logo like this : 
<div>
    <img src="{{ asset('assets/images/logo.png') }}" alt="Logo" class="h-10">
</div>

it prompts me this error : 

Livewire encountered a missing root tag when trying to render a component. When rendering a Blade view, make sure it contains a root HTML tag.

### Expected behavior

Display the logo

### Steps to reproduce

Setup a new filament v3.0.0 project and try to change the logo

### Reproduction repository

https://github.com/pintend/livewirefillamentbug

**Comment by RickDBCN** [comment]
Hi @sheepbild,

Please follow the v3 docs accordingly:
https://filamentphp.com/docs/3.x/panels/themes#changing-the-logo

It looks like you have followed the v2 documentation, which doesn't work for v3 :)

**Comment by swrtom** [comment]
Hi @RickDBCN,

It's weird I have followed the v3 documentation.. I changed "filament" folder to "filament-panels", it would be supposed to work

![image](https://github.com/filamentphp/filament/assets/44288315/16c50c61-f525-462b-9f78-0e77ca4a811f)

**Comment by swrtom** [comment]
The thing now is even with removing the vendor/ folder, the error doesn't disappear..

**Comment by swrtom** [comment]
Ok with php artisan optimize:clear the error went away :) thank for your reactivity !

**Comment by RickDBCN** [comment]
@sheepbild it appears, according to your reproduction repo that you did not create the view correctly. Did you change the file in the root vendor folder? You shouldn't change files there.
