### ISSUE TITLE
Repeater shows wrong values

### ISSUE THREAD

**Issue by telkins** [laravel-filament/filament#7808]
### Package

filament/filament

### Package Version

v3.0.23

### Laravel Version

v10.19.0

### Livewire Version

v3.0.0-beta.9

### PHP Version

PHP 8.2.8

### Problem description

I have a repeater, using it to reflect a many-to-many relationship per the documentation: https://filamentphp.com/docs/3.x/forms/fields/repeater#integrating-with-a-belongstomany-eloquent-relationship

I have a Select inside my repeater to represent the related model, and I want that Select to exclude any options which are selected in that field on other instances of the repeater.  As such, I followed the suggestions found in a number of places in Discord, including @cheesegrits 's example: https://github.com/cheesegrits/demo/blob/repeater-select/app/Filament/Resources/Shop/OrderResource.php#L225

I noticed that when I use the repeater in certain ways, some of the elements values appear to change.  (The changes appear to be visual only...as saving and then refreshing seems to show that the actual values don't change.)

To make it easier to understand, I created a simple repo with a user-role relationship.

I have a UserResource with the roles implemented as a repeater.  I have a handful of roles: Role 1, Role 2, etc.

If I add Role 3, Role 6, and Role 9 and save, everything's fine.

**Then, when I add a new entry in the repeater, everything's good...until I select the actual role.  If I select Role 5, then Role 3 remains intact, but Role 6 and Role 9 change to Role 7 and Role 10, respectively.**

### Expected behavior

I expect all of the previous roles to remain unchanged when adding a new role.

### Steps to reproduce

I have a handful of roles: Role 1, Role 2, etc.

I add Role 3, Role 6, and Role 9 and save.  (Saving isn't actually necessary, but it does help to show that the data that is saved to the database appears to be fine.  It seems to be a visual issue.)

I add a new entry in the repeater and select a role that has an ID less than one or more of the previously selected roles.

Any previously selected role that has an ID greater than the new one that was just selected will change to the next role.

### Reproduction repository

https://github.com/telkins/repeater-issue

**Comment by telkins** [comment]
From @idpry in Discord: "I encountered a similar problem, which specifically occurred with native Select. Try adding ->native(false) to your Select, it resolved the issue for me."

I tried this myself and it seems to make the problem go away.  This doesn't resolve the issue, exactly, but it could be helpful in figuring out when/why/where/how this occurs.

**Comment by cheesegrits** [comment]
As per thread in discord, this isn't a Filament issue, it's an HTML issue.  Removing option from previously display/selected selects changes the option the selectedIndex references.  This works if using Choices, as it's all driven on the fly using JS, but not with native selects.  So making the Select be searchable() would work round it.

I'm re-doing that example I gave you so it disables unavailable options rather than removing them from the option list.
