### ISSUE TITLE
Laravel Select component relationship bug: Null value not properly handled when using relationship() method

### ISSUE THREAD

**Issue by abdulmejidshemsu** [laravel-filament/filament#7822]
### Package

filament/forms

### Package Version

v3.0-stable

### Laravel Version

10.10

### PHP Version

8.2.7

### Problem description

There is a possible bug with the relationship on Select component.

The bug is that if you use a relationship on Select to select one value and save it, it works correctly. However, if you want to make the value null, you can select the "Select an option" option to select a null value. However, the component does not allow you to make it null, and it will save the old value.

This bug only occurs when you use the relationship() method. If you use the option() method instead, it works correctly.

The issue is happening after the $this->dehydrateState($state) method in the HasState concerns. This method is responsible for converting the state of the component into a serializable format. For some reason, it is not properly handling the null value when it is used with the relationship() method.

![image](https://github.com/filamentphp/filament/assets/53785447/8fd977b7-d038-4132-a5ed-bc8b5207e56d)

I tried to replicate locally
![image](https://github.com/filamentphp/filament/assets/53785447/73ad202f-2737-4ef1-b096-887615df55aa)

### Expected behavior

It should allow to make the select null or EMPTY instead of saving the old value

### Steps to reproduce

1. Go to https://demo.filamentphp.com/shop/products/1/edit
2. Make brand value null
![image](https://github.com/filamentphp/filament/assets/53785447/c66caa31-cc9f-4519-9a90-4f23bb9abb1c)
3.Click Save

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by playerro** [comment]
Any solution to this?

**Comment by danharrin** [comment]
This specific issue is fixed in #7824. If you have a new one, please open a new issue with a reproduction repository
