### ISSUE TITLE
Navigation menu is cut off on mobile with Multi Tenancy

### ISSUE THREAD

**Issue by EriksonEnterprises** [laravel-filament/filament#7830]
### Package

filament/filament

### Package Version

V3.0

### Laravel Version

V10.0

### PHP Version

V8.2.8

### Problem description

With multi tenancy dropdown enabled, the navigation bar cuts off the last link on mobile devices

### Expected behavior

Be able to see/view all links

### Steps to reproduce

Enable multi tenancy completely to where dropdown menu shows to allow switching

Add enough resources to fill the navigation links until it gets to a point of scrolling. Go to website on mobile device, try to access menu, try to scroll to the last item on the list - the last link is cut off

### Reproduction repository

https://github.com/jamesautodude/filament

**Comment by danharrin** [comment]
There is no reproduction repository. Please @ me with one and I will reopen the issue.

Also, please detail the mobile device and browser you used to test, and whether or not it is reproducible using a thin browser on desktop.

**Comment by declum** [comment]
@danharrin 

Repro Repo: https://github.com/declum/example-repo

For mimicing the mobile, i reduced the width of browser, and css mobile media kicked in, and scroll stopped working.

1. git clone https://github.com/declum/example-repo
2. cd example-repo
3. mv .env.example .env
4. php artisan migrate --seed <- This will also create admin@admin.dev user with 100 teams (password is "password")
5.php artisan serve

**Comment by declum** [comment]
Can we also make this list limited to a customizable count with a default of 15, and allow filters to search the team? 

If a user belongs to more teams, the menu keeps growing.

**Comment by danharrin** [comment]
Ah just seen you opened a new one
