### ISSUE TITLE
FileUpload component `->moveFiles()` breaks upload due to protected property on TemporaryUploadedFile

### ISSUE THREAD

**Issue by josefbehr** [laravel-filament/filament#7842]
### Package

filament/filament

### Package Version

v3.0.25

### Laravel Version

v10.19.0

### Livewire Version

v3.0.0-beta.7

### PHP Version

PHP 8.2.6

### Problem description

Using a `FileUpload` component with `moveFiles(true)` results in an error on upload since the `$disk` property on Livewire's `TemporaryUploadedFile` is not protected and therefore not accessible from the `BaseFileUpload` class.

![Screenshot_20230817_112114](https://github.com/filamentphp/filament/assets/4368880/3add3b71-a8a7-497a-8373-eaa71e56ca78)
![image](https://github.com/filamentphp/filament/assets/4368880/b743d8ed-dba1-4751-a88a-c1d81a2c697c)

### Expected behavior

Upload works without errors and moves files

### Steps to reproduce

Create a `FileUpload` component on any form and set `moveFiles()`, then try to upload a file.

Reproduction repo:

1. run `php artisan migrate && php artisan db:seed`
2. log in as `test@example.com` with password `password`
3. go to the user resource and add a new one or edit the existing one, showing the file upload component
4. add a file and submit

### Reproduction repository

https://github.com/josefbehr/filament-fileupload-bug

**Comment by danharrin** [comment]
Fixed by 321d8b93eeab832e6e73c415a2a6e793d1f39822.
