### ISSUE TITLE
When used SELECT the options not translated by  Spatie/Laravel-translatable 

### ISSUE THREAD

**Issue by mohabmamdouh** [laravel-filament/filament#7843]
### Package

filament/forms

### Package Version

v3

### Laravel Version

*

### Livewire Version

*

### PHP Version

*

### Problem description

When used SELECT form component 
and i used relationship 
like 
SELECT::make('dd')->relationship('categories','name'),

name returned as json  but i still add configrations right in model and working fine in when update or create 
only SELECT option returned as json

### Expected behavior

When used SELECT form component 
and i used relationship 
like 
SELECT::make('dd')->relationship('categories','name'),

name returned as json  but i still add configrations right in model and working fine in when update or create 
only SELECT option returned as json

### Steps to reproduce

When used SELECT form component 
and i used relationship 
like 
SELECT::make('dd')->relationship('categories','name'),

name returned as json  but i still add configrations right in model and working fine in when update or create 
only SELECT option returned as json

### Reproduction repository

11

**Comment by lutek** [comment]
got the same problem;

```php
                Forms\Components\Select::make('state_id')
                    ->relationship(name: 'state', titleAttribute: 'name')
                    ->required(),
```

![image](https://github.com/filamentphp/filament/assets/846598/f35bb17a-ee90-41c3-8cc6-199984e552e8)

**Comment by nikita2608** [comment]
Same problem

<img width="434" alt="Снимок экрана 2023-10-27 в 22 11 40" src="https://github.com/filamentphp/filament/assets/33571010/dc25f6a9-4108-45ad-a5c6-c90be068cdd1">

**Comment by nikita2608** [comment]
> got the same problem;
> 
> ```
>                 Forms\Components\Select::make('state_id')
>                     ->relationship(name: 'state', titleAttribute: 'name')
>                     ->required(),
> ```
> 
> ![image](https://user-images.githubusercontent.com/846598/278032951-f35bb17a-ee90-41c3-8cc6-199984e552e8.png)


Here's a working solution

```
Forms\Components\Select::make('category_id')
                        ->label('Категория')
                        ->relationship('category', 'title')
                        ->getOptionLabelFromRecordUsing(fn (Category $record) => $record->title)
```

**Comment by ahmedkalash** [comment]
Same problem

**Comment by AlaaHabib** [comment]
Try this , it's working 

Forms\Components\Select::make('category_id')
                        ->label('Категория')
                        ->relationship('category', 'title')
                        ->getOptionLabelFromRecordUsing(fn($record, $livewire) => $record->getTranslation('title', $livewire->activeLocale))

**Comment by AlaaHabib** [comment]
@ahmedkalash , if you are still looking for the answer , I have found it.
what you're looking for is a property called activeLocale and it exists on $livewire.
to access it you use a Closure and inject $livewire.
For example:
If you have a relationship called type and you want to display it's name in a Forms\Components\Select this is how I was able to make it display the correct values in the locale chosen in the LocaleSwithcher
```
// use the database field id
Forms\Components\Select::make('type_id')
// specify the relationship
->relationship('type', 'name')
// specify how to get the relationship translated values
->getOptionLabelFromRecordUsing(fn($record, $livewire) => $record->getTranslation('name', $livewire->activeLocale))
```
Hope this helps
And I hope this gets added to the docs to avoid future confusion.

**Comment by ahmedkalash** [comment]
@AlaaHabib 

Thanks a lot, bro you made my life easier

**Comment by rustraut** [comment]
Yes you are right.
Great thanks!

**Comment by Khant-Nyar** [comment]
> @ahmedkalash , if you are still looking for the answer , I have found it. what you're looking for is a property called activeLocale and it exists on $livewire. to access it you use a Closure and inject $livewire. For example: If you have a relationship called type and you want to display it's name in a Forms\Components\Select this is how I was able to make it display the correct values in the locale chosen in the LocaleSwithcher
> 
> ```
> // use the database field id
> Forms\Components\Select::make('type_id')
> // specify the relationship
> ->relationship('type', 'name')
> // specify how to get the relationship translated values
> ->getOptionLabelFromRecordUsing(fn($record, $livewire) => $record->getTranslation('name', $livewire->activeLocale))
> ```
> 
> Hope this helps And I hope this gets added to the docs to avoid future confusion.

thanks for the that tips 
now how to show again in table 

![image](https://github.com/filamentphp/filament/assets/61083917/af42f985-2273-457d-98bd-f337845e857f)

**Comment by AlaaHabib** [comment]
> > @ahmedkalash , if you are still looking for the answer , I have found it. what you're looking for is a property called activeLocale and it exists on $livewire. to access it you use a Closure and inject $livewire. For example: If you have a relationship called type and you want to display it's name in a Forms\Components\Select this is how I was able to make it display the correct values in the locale chosen in the LocaleSwithcher
> > ```
> > // use the database field id
> > Forms\Components\Select::make('type_id')
> > // specify the relationship
> > ->relationship('type', 'name')
> > // specify how to get the relationship translated values
> > ->getOptionLabelFromRecordUsing(fn($record, $livewire) => $record->getTranslation('name', $livewire->activeLocale))
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Hope this helps And I hope this gets added to the docs to avoid future confusion.
> 
> thanks for the that tips now how to show again in table
> 
> ![image](https://private-user-images.githubusercontent.com/61083917/336312886-af42f985-2273-457d-98bd-f337845e857f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0ODU5OTUsIm5iZiI6MTcxNzQ4NTY5NSwicGF0aCI6Ii82MTA4MzkxNy8zMzYzMTI4ODYtYWY0MmY5ODUtMjI3My00NTdkLTk4YmQtZjMzNzg0NWU4NTdmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA0VDA3MjEzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY0OGRiNGVmM2ZmMWEwM2FjNGNkNTE5ZTk4NjMwYjIyYjI4ZjI2MTFiMWE0NDg3YmQ3NGNmNTdiMzAyMzY1ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BqswChCLQCBIy6lO2YDkH9SykM4WHmo4HGEHbqPr7JM)

**You can try using 
 ->getStateUsing instead of ->getLabel**

**Comment by Khant-Nyar** [comment]
in the screenshoot i already try that way but i got 
![image](https://github.com/filamentphp/filament/assets/61083917/948ba939-fc51-4ab6-be11-5c1edc18db25)
