### ISSUE TITLE
[2.x] Forms: Placeholder state callback results in loop

### ISSUE THREAD

**Issue by pxlrbt** [laravel-filament/filament#786]
### Package

filament/forms

### Package Version

v.2.5.11

### Laravel Version

v.8.74.0

### Livewire Version

v.2.8.1

### PHP Version

PHP 8.1

### Bug description

When using a callable as an argument the placeholders state function collides with the evaluation in `EvaluatesCallbacks` which tries to evaluate the state and results in a loop.

```php
Forms\Components\Placeholder::make('Test')
    ->state(function ($record) {
        return $record->id;
    })
```

What's the best solution for this?
1. Mention this exception in the docs.
2. Rename `->state()` to `->content()` or `->text()` on `Placeholder` components.
3. Exclude `Placeholder` components from state evaluation (`'state' => static::class == Placeholder::class ? null : $this->getState(),`)

I'd prefer way 2 but that would be a breaking change. Any other thoughts on this?

**Comment by danharrin** [comment]
Fixed by #890.
