### ISSUE TITLE
Tenant middleware with isPersistent parameter does not run on every request

### ISSUE THREAD

**Issue by lamberttraccard** [laravel-filament/filament#7867]
### Package

filament/filament

### Package Version

v3.0.26

### Laravel Version

v10.19.0

### PHP Version

PHP 8.2

### Problem description

In a panel provider, setting a tenant middleware with the persistent parameter does not apply the middleware on every request.

### Expected behavior

The middleware should be applied on every request and not only the first one.

### Steps to reproduce

1. sail up -d
2. sail art migrate:fresh --seed
3. login with test@example.com -> password
4. go to roles resource
5. click on one of the tabs

A role not belonging to the tenant appear

```php
 return $panel
            ->default()
            ->id('admin')
            ->path('admin')
            ->tenant(Team::class)
            ->tenantMiddleware([
                ApplyTenantScope::class,
            ], isPersistent: true)
```

### Reproduction repository

[lamberttraccard/filament-issue](https://github.com/lamberttraccard/filament-issue)

**Comment by elasti-co** [comment]
The same issue with `authMiddleware` with `isPeristent: true`.
When click on Resource relation tab the middleware is not run.

**Comment by leonardomrl** [comment]
I'm having the same problem to persist the middleware, but the hack I did was in the provider where you configure your panel, you add it manually, at least until we have a solution.
```php
public function panel(Panel $panel): Panel
{
  $panel
      ->id('admin')
      // others configs
      ->tenantMiddleware([
          ApplyTenantScopes::class
      ]);
  
  Livewire::addPersistentMiddleware($panel->getTenantMiddleware()); // or any middleware
  
  return $panel;
}
```

**Comment by danharrin** [comment]
Should be fixed by #8492.

**Comment by JakeOcean** [comment]
I'm having issues with this in a fresh install

**Comment by tnatanael** [comment]
Having issues with this right now... the middleware runs, but before the livewire update request do his job...
