### ISSUE TITLE
Table::reorderable() - random shuffling

### ISSUE THREAD

**Issue by EvodiaAut** [laravel-filament/filament#7873]
### Package

filament/tables

### Package Version

v3.0.25 (demo.filamentphp.com)

### Laravel Version

10 (demo.filamentphp.com)

### PHP Version

>8.1 (demo.filamentphp.com)

### Problem description

If you finish to sort a brand he start random shuffling all brands.

### Expected behavior

A right sorting after sorting a brand (In version 2 works).

### Steps to reproduce

Open https://demo.filamentphp.com/shop/brands?isTableReordering=true
Drag first brand to second position and see what happens.

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by pxlrbt** [comment]
Dan, not sure if the demo is enough reproduction repo in this case. I'll reopen for now and you decide.

**Comment by danharrin** [comment]
Cannot reproduce locally though, only on the Live demo

**Comment by pxlrbt** [comment]
Old Livewire version?

**Comment by zepfietje** [comment]
Just updated dependencies on the demo and tested in production.
Can't reproduce the issue anymore so seems to be fixed.

**Comment by EvodiaAut** [comment]
If you start sorting now, he load all items in one table?
I don't think it was like that before.

It's need a lot of power for server and client by 400 items. Let's be 10.000 items its done with both 😅

**Comment by danharrin** [comment]
It is documented, it was a bug before the previous version. You can change that behaviour.

**Comment by EvodiaAut** [comment]
You mean https://filamentphp.com/docs/3.x/tables/advanced#enabling-pagination-while-reordering

Cool amazing, maybe you show this in the demo.
Thanks for checking and clarification.
