### ISSUE TITLE
Filters are always applied to a dashboard widget

### ISSUE THREAD

**Issue by citronkaste** [laravel-filament/filament#7875]
### Package

filament/filament

### Package Version

3.0.26

### Laravel Version

10.19.0

### PHP Version

8.2.9

### Problem description

When widget is added to a dashboard panel - it automatically applies all defined filters within its resource table filters array, and therefore displays filtered stats. But it shouldn't - there are no default filters set to be applied.

### Expected behavior

When widget is added to a dashboard panel - by default it should not apply any filters. Behavior and stats must be same as when viewing default resource table list.

### Steps to reproduce

**On my example app:**

1. Clone my example-app repo.
2. Sail up.
3. Run migrate and seed.
4. Create admin user and login.
5. Check Users page

![users](https://i.imgur.com/Uvz6rx9.png)

6. Check dashboard stats.

![dashboard](https://i.imgur.com/gEtmUAc.png)

**Or check on your own app:**

1. Add any filter to table filters array.

```php
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name'),
                Tables\Columns\TextColumn::make('email'),
            ])
            ->filters([
                Tables\Filters\Filter::make('test_a')
                ->query(fn (Builder $query) => $query->where('name', 'Test User A'))
            ])
```

2. Create basic stats widget.

```php
<?php

namespace App\Filament\Resources\UserResource\Widgets;

use App\Filament\Resources\UserResource\Pages\ListUsers;
use Filament\Widgets\Concerns\InteractsWithPageTable;
use Filament\Widgets\StatsOverviewWidget as BaseWidget;
use Filament\Widgets\StatsOverviewWidget\Stat;

class UserOverview extends BaseWidget
{
    use InteractsWithPageTable;

    protected function getStats(): array
    {
        $total = $this->getPageTableQuery()->count();

        return [
            Stat::make('total', $total),
        ];
    }

    protected function getTablePage(): string
    {
        return ListUsers::class;
    }
}

```

3. Add widget to a dashboard panel.

```php
        return $panel
            ->widgets([
                Widgets\AccountWidget::class,
                Widgets\FilamentInfoWidget::class,
                UserOverview::class,
            ])
```

4. Dashboard panel will display filtered stats.

---

**Temporary solution is this:**

```php

    protected function getStats(): array
    {

        if($this->tableFilters === null) {
            $this->getTablePageInstance()
                ->getTableFiltersForm()
                ->fill();
        }

        $total = $this->getPageTableQuery()->count();

        return [
            Stat::make('total', $total),
        ];
    }

```

### Reproduction repository

https://github.com/CodeKJ/filament-bug-report

**Comment by danharrin** [comment]
If you're using `InteractsWithPageTable` on a page, you cannot then use that on the dashboard, as the (dashboard) page doesn't have a table on it. You should remove the trait, then create another class that extends the original widget and apply it there.
