### ISSUE TITLE
[2.x] KNOWN ISSUE - Livewire v2.8 file uploads

### ISSUE THREAD

**Issue by danharrin** [laravel-filament/filament#788]
File uploads (especially multiple-file uploads, file uploads within a nested array & rich editor / markdown editor file uploads) are broken in Livewire v2.8.0.

This is caused by PR livewire/livewire#4239.

**Symptoms:**
- File uploads magically disappear after they are uploaded.
- "Cannot assign string to property `$componentFileAttachments`".
- Files get uploaded as `livewire-files`.

**To fix:**
- Downgrade to Livewire < v2.8.0.
  `composer require livewire/livewire:2.7.2`

I have contacted the Livewire internal team to work out a solution / revert the change.

**Comment by danharrin** [comment]
Related: #778.

**Comment by budiardianata** [comment]
Related to #748

**Comment by danharrin** [comment]
Hey everyone, I've just submitted a PR to Livewire fixing this - livewire/livewire#4378.

Just waiting for it to be merged and tagged :)

**Comment by danharrin** [comment]
This has now been released in Livewire v2.8.2. Please update :)
