### ISSUE TITLE
Repeater add multiple fields instead of one

### ISSUE THREAD

**Issue by stontyg** [laravel-filament/filament#7902]
### Package

filament/filament

### Package Version

v3.0.27

### Laravel Version

v10.19.0

### Livewire Version

v3.0.0-beta.9

### PHP Version

PHP 8.1.14

### Problem description

Clicking the 'add item' button in Repeater field creates multiple fields instead of one.

### Expected behavior

One field created when clicking the add button.

### Steps to reproduce

Create a repeater component (integrated with an Eloquent relationship) nested in a Relation Manager. Add/Edit the repeater fields.

https://github.com/filamentphp/filament/assets/6479447/0dd7ccf6-8b3e-4e0a-b4ef-7fb6005de80e

### Reproduction repository

-

**Comment by aeq-dev** [comment]
I confirm this,
It happens with me when I open the modal to add/edit record and close it, then reopen again : here it adds many fields
