### ISSUE TITLE
Array to string conversion

### ISSUE THREAD

**Issue by oumaimaamkane** [laravel-filament/filament#7903]
### Package

filament/filament

### Package Version

v2.0

### Laravel Version

v10.19

### PHP Version

php 8.2

### Problem description

I used Repeater field and save the data to the database as json , I did the cast of the column in array , but when I want to list the records it gives me 'Array to string conversion' , I don't know how to trait the data before listing 
`    protected $casts =[
        'product' => 'array'
    ];`
![image](https://github.com/filamentphp/filament/assets/62530553/010638e0-494f-443c-a2d0-a32015d2b81d)

### Expected behavior

I expected to show the product as text in the list

### Steps to reproduce

 I don't know

### Reproduction repository

https://github.com

**Comment by Z3d0X** [comment]
Hi, GitHub issues is not the place to reach out for support, please use GitHub Discussions or Discord

**Comment by jodinathan** [comment]
this is also happening to me.  
this page https://filamentphp.com/community/how-to-consume-an-external-api-with-filament-tables could surely add an example with a more complex json.
