### ISSUE TITLE
Fail create user with filament-user

### ISSUE THREAD

**Issue by MarceloSantosCorrea** [laravel-filament/filament#791]
### Package

filament/filament

### Package Version

v2.5.11

### Laravel Version

v8.75.0

### Livewire Version

v2.8.1

### PHP Version

8.1.0

### Bug description

Fail run command php artisan make:filament-user

### Steps to reproduce

composer create-project laravel/laravel laravel-filament
php artisan sail:install  (0,3)
vendor/bin/sail up -d
vendor/bin/sail shell
composer require filament/filament
php artisan migrate
    
fill name with special characters. Ex: Marcelo Corrêa

### Relevant log output

```shell
SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xC3\xC3\xAAa' for column 'name' at row 1 (SQL: insert into `users` (`name`, `email`, `password`, `updated_at`, `created_at`) values (Marcelo Corr?êa, marcelocorrea229@gmail.com, $2y$10$8Wpw6OAWha97zsKW/642W.4mV1yMrNZjgVKhD3miwUxb9oFV5EQvO, 2021-12-09 20:56:14, 2021-12-09 20:56:14))
```

**Comment by dmandrade** [comment]
@MarceloSantosCorrea I think this is caused by a wrong charset/collate in your database.
Did you try to create user direct in db to confirm?

**Comment by danharrin** [comment]
Yeah. As @dmandrade, this is to do with your MySQL config instead of Filament. Check out https://stackoverflow.com/questions/10957238/incorrect-string-value-when-trying-to-insert-utf-8-into-mysql-via-jdbc/10959780
