### ISSUE TITLE
Key-value Input

### ISSUE THREAD

**Issue by hussainabuhajjaj** [laravel-filament/filament#7918]
### Package

filament/forms

### Package Version

3.0-stable

### Laravel Version

10.x

### Livewire Version

3.x

### PHP Version

8.1

### Problem description

i do add key value input and when trying to add a new row it's adding it and deletes it at the same time 

### Expected behavior

the expected is to add new row without deleting it like when add new row it should show and stay in the form

### Steps to reproduce

follow the Key-value docs in filament docs that what i did 

### Reproduction repository

https://github.com/hussainabuhajjaj/Verona-Rentakar/blob/main/app/Filament/Resources/CarResource.php

**Comment by zepfietje** [comment]
Could you please test if this is still an issue on the latest stable versions of Filament and Livewire, @hussainabuhajjaj?

**Comment by valpuia** [comment]
I've test this with the following versions and I think it's already fixed
`filament/filament (v3.0.37)`
`laravel/framework (v10.21.0)`
`livewire/livewire (v3.0.1)`

[Screencast from 08-31-2023 10:29:04 AM.webm](https://github.com/filamentphp/filament/assets/28250303/a0238f17-6536-4c0d-ae99-2a20e140aa65)

**Comment by zepfietje** [comment]
Thanks for checking and the clear video, @valpuia!
