### ISSUE TITLE
canViewForRecord() in RelationManager Not change properly

### ISSUE THREAD

**Issue by chickgit** [laravel-filament/filament#7923]
### Package

filament/filament

### Package Version

v3.0.19

### Laravel Version

v10.19.0

### PHP Version

PHP 8.1.21

### Problem description

After i implement [this](https://filamentphp.com/docs/3.x/panels/resources/relation-managers#conditionally-showing-relation-managers)

```php
public static function canViewForRecord(Model $ownerRecord, string $pageClass): bool
{
    return $ownerRecord->type === FoodPackageType::PACKAGE;
}
```

the relation in edit page not changed properly

### Expected behavior

The relation is changed according to record set in canViewForRecord() method

### Steps to reproduce

1. Choose a food package
![image](https://github.com/filamentphp/filament/assets/15156382/b5709695-e8c0-4681-aa2c-ffee1dbc3297)
2. open edit page of a food package
![image](https://github.com/filamentphp/filament/assets/15156382/33ea7ff9-aa3e-4c05-828a-79cf47aa6479)
3. change type to 'snack' and the relation is gone
![image](https://github.com/filamentphp/filament/assets/15156382/fecb1760-2672-4d2d-bc6f-0142cdf24c7b)
4. the console give me this error
![image](https://github.com/filamentphp/filament/assets/15156382/de7c0f0f-2a46-4048-9bf0-e01b87e5c145)
5. but if i refresh the page. the relation is back to normal and show according to canViewForRecord()
![image](https://github.com/filamentphp/filament/assets/15156382/2bb2ef32-45b0-4d35-bc7f-25b6c220d313)

### Reproduction repository

https://github.com/chickgit/filament-canViewForRecord-bug

**Comment by danharrin** [comment]
Should be fixed in #8495
