### ISSUE TITLE
Bug with filters

### ISSUE THREAD

**Issue by noxoua** [laravel-filament/filament#7933]
### Package

filament/filament

### Package Version

demo.filamentphp.com

### Laravel Version

demo.filamentphp.com

### PHP Version

demo.filamentphp.com

### Problem description

Filter stuck after page reload.

### Expected behavior

Reset filters.

### Steps to reproduce

here is a video 

https://github.com/filamentphp/filament/assets/142592979/f4ce63d2-8d62-4efb-904d-78b45032a63b

### Reproduction repository

https://github.com/filamentphp/filament

**Comment by noxoua** [comment]
@danharrin please watch the video

**Comment by danharrin** [comment]
This is going to be a LW bug instead of Filament

**Comment by archilex** [comment]
@noxoua Hi. This is a known issue with Livewire. Follow along on this thread as well as temporary fix you can implement: https://github.com/filamentphp/filament/issues/7129
