### ISSUE TITLE
Date(Time)Picker does not take timezone into account

### ISSUE THREAD

**Issue by marcreichel** [laravel-filament/filament#795]
### Package

filament/forms

### Package Version

v2.5.11

### Laravel Version

v8.75.0

### Livewire Version

v2.8.1

### PHP Version

PHP 8.0.6

### Bug description

The `Filament\Forms\Components\DatePicker` and `Filament\Forms\Components\DateTimePicker` does not take the configured timezone into account. In my current timezone the pickers are one hour off. So when setting a date (in the `DatePicker`) or a date at midnight (in the `DateTimePicker`) and saving the resource the date(time) is one day earlier at 23:00:00.

### Steps to reproduce

Set the `timezone` in `config/app.php` to `Europe/Berlin` and update a resource like described in the bug description.

**Comment by aliloubm** [comment]
https://laravel.com/docs/7.x/upgrade#date-serialization
You should add it to your User model:

```
use DateTimeInterface;

/**
 * Prepare a date for array / JSON serialization.
 *
 * @param  \DateTimeInterface  $date
 * @return string
 */
protected function serializeDate(DateTimeInterface $date)
{
    return $date->format('Y-m-d H:i:s');
}
```

**Comment by marcreichel** [comment]
@aliloubm Works! Thank you very much! Seems like I totally missed this part in the docs.

**Comment by danharrin** [comment]
Hey, this is not in the docs but it's intended to not take timezones into account. When you're dealing with apps that handle multiple timezones, such as event scheduling apps, you don't want to have any timezones being converted automatically.

While @aliloubm's solution works, I think that you might have just forgotten to add `date` / `datetime` casts to those properties? Or maybe I'm wrong there.

**Comment by marcreichel** [comment]
@danharrin Actually I have the following:

```php
protected $dates = [
    'published_at',
];
```

And adding

```php
protected $casts = [
    'published_at' => 'datetime',
];
```

as well, does not help.

But the example of @aliloubm does 👍🏼

**Comment by danharrin** [comment]
Cool, good to know!
