### ISSUE TITLE
Tables\Filters\SelectFilter appears null

### ISSUE THREAD

**Issue by wxfjamdc** [laravel-filament/filament#7985]
### Package

filament/filament

### Package Version

v3.0.30

### Laravel Version

v10.19.0

### PHP Version

8.1.18

### Problem description

When using search with multiple selections, fields with no selections will appear in the link and be assigned a value of null.

Refresh the page at this time, the selection item becomes null.

### Expected behavior

Nulls do not appear in links.

### Steps to reproduce

1. Open the table,
2. Drop down and select user
3. Refresh the page.

### Reproduction repository

https://github.com/wxfjamdc/filament_SelectFilter

**Comment by archilex** [comment]
@wxfjamdc Hi. This is a known issue with Livewire. Follow along on this thread as well as temporary fix you can implement: #7129
