### ISSUE TITLE
Css https://fonts.bunny.net unresponsive

### ISSUE THREAD

**Issue by Adnank999** [laravel-filament/filament#7987]
### Package

filament/filament

### Package Version

v3

### Laravel Version

v10

### Livewire Version

v3@beta

### PHP Version

PHP 8.1

### Problem description

I was trying to login to filament admin dashboard but it takes long to login in.Even when I am trying to click on user,catagories from my model in Dashboard,it takes long arround 10s to get response.This problem this due to https://fonts.bunny.net/ in the app.blade.php header css file.I am providing screenshots.
![Screenshot 2023-08-22 163229](https://github.com/filamentphp/filament/assets/108197930/8f366d7b-f348-4d45-93bc-2991c27ac807)

### Expected behavior

I was expecting login and other functionalities goes smoothly.I was also expecting responsive behaviour or fillament dashboard.

### Steps to reproduce

docs-assets/app/resources/views/components/layouts

Here in the app.blade.php there is a header on line 16,17.

  <link rel="preconnect" href="https://fonts.bunny.net">
        <link href="https://fonts.bunny.net/css?family=inter:300,400,500,600,700&amp;display=swap" rel="stylesheet">

This two line because I think the link is unresponsive.

### Reproduction repository

https://github.com/Adnank999/fillament

**Comment by danharrin** [comment]
Please put effort into a reproduction repository. We did not ask for you to clone the repo, did we.
