### ISSUE TITLE
Error when using Get closure in visible method of a form action

### ISSUE THREAD

**Issue by howdu** [laravel-filament/filament#7993]
### Package

filament/filament

### Package Version

v3.0.30

### Laravel Version

10.19.0

### Livewire Version

v3.0.0-beta.10

### PHP Version

8.1.14

### Problem description

Using the `visible` method combined with `$get` throws an error:
> Typed property Filament\Forms\Components\Component::$container must not be accessed before initialization

### Expected behavior

Get closure works the same as other form components. 

### Steps to reproduce

```php
Forms\Components\Repeater::make('test')
    ->statePath('test')
    ->minItems(1)
    ->schema([
        Forms\Components\TextInput::make('name')->required(),

        Forms\Components\Actions::make([
            Forms\Components\Actions\Action::make('clear')
                ->visible(function(Forms\Get $get): bool {
                    return (bool)$get('name');
                })
                ->action(function(Forms\Set $set) {
                    $set('name', null);
                })
        ])
    ])
```
Same error if the visible is added to the Actions component. 

### Reproduction repository

https://github.com/howdu/filament-tester/tree/bug-hide-action

**Comment by awcodes** [comment]
You repo is falling because you are not returning a bool while declaring it as the return type:
```php
Forms\Components\Actions\Action::make('clear')
        ->visible(function(Forms\Get $get): bool {
            return $get('name'); <- returns null, not false
        })
```

However, the code you posted above, works fine in your repo:
```php
Forms\Components\Actions\Action::make('clear')
        ->visible(function(Forms\Get $get): bool {
            return $get('name') || $get('email'); <- returns bool, since it's a test
        })
```

Closing this as it is not a Filament bug.

**Comment by howdu** [comment]
Strange I'm still getting the same error when calling`$get` and before anything is returned.

**Comment by awcodes** [comment]
I tested your code on latest filament and LW 3.0.1. Maybe you just need to update.

**Comment by howdu** [comment]
Thanks yeah I've just realised it needed to be inside a repeater I've updated repo. If you go to create a customer you see the error. 

Also flare trace report:
https://flareapp.io/share/87nYBn6P

**Comment by awcodes** [comment]
Does null cast to false? And I wasn't experiencing the error when returning false. Still don't think it's a filament issue though. $get will return the value of the field which in this case will be a sting or null. However, in the code you shared above that also has email it's checking an actual condition via the || operator.

**Comment by awcodes** [comment]
Could be that name is returning and empty string too. Maybe filled() would be better than a cast.

**Comment by howdu** [comment]
The error is thrown from Filament before anything is returned. 
<img width="1437" alt="Screenshot 2023-08-27 at 17 10 45" src="https://github.com/filamentphp/filament/assets/533658/13285982-f1f0-4a81-84c7-648781599766">

 It needs to be inside a repeater I've updated the example repository and code above.

**Comment by jimarick** [comment]
I'm seeing this same error within repeater items when using $get() to access values.

**Comment by howdu** [comment]
Yeah I don't think it was ever fixed

**Comment by touqeershafi** [comment]
I'm also getting the very Weird error just using this code:

```php
protected function getFormActions(): array
    {
        return [
            Action::make("test")->label("Test")->button()->visible()
        ];
    }
```

![image](https://github.com/filamentphp/filament/assets/4585116/f2b6b5ba-8757-45e9-a5e7-9199d439de20)

**Comment by salihanmridha** [comment]
Is there any solution for this issue? I've having the same issue. same error within repeater items when using $get() or $livewire.
@danharrin

**Comment by howdu** [comment]
@salihanmridha I used the arguments and component state instead:
```php
->hidden(
   fn (array $arguments, Repeater $component): bool => blank(
      $component->getRawItemState($arguments['item'])['url']
   )
)
```
