### ISSUE TITLE
Translatable Plugin not working for TextInputColumn

### ISSUE THREAD

**Issue by OliverTe** [laravel-filament/filament#7994]
### Package

filament/spatie-laravel-translatable-plugin

### Package Version

v3.0.30

### Laravel Version

v10.20

### Livewire Version

v3.0.0-beta.10

### PHP Version

PHP 8.2.7

### Problem description

When using a TextInputColumn with a translatable field, changing the language via the Dropdown in a Table View does not change the TextInputColumn's content to the selected language version. In the associated edit modal, the language change is reflected as expected.

https://github.com/filamentphp/filament/assets/5622142/d4788ed0-9bf2-4602-a696-98c643412ec5

### Expected behavior

When changing the language via the select menu, the value of the TextInputColumn field should be shown in the selected language.

### Steps to reproduce

Clone the rep, add mysql details to .env, run php artisan migrate and login with user "test@example.com" with password "1234". The Countries are seeded with Germany and France with translations in de, en and fr.

### Reproduction repository

https://github.com/OliverTe/filament-translatable-textinputcolumn-bug

**Comment by danharrin** [comment]
Downloaded the repository and it worked with the latest Filament version.
