### ISSUE TITLE
Footer widgets disappeared

### ISSUE THREAD

**Issue by globalinvestai** [laravel-filament/filament#7996]
### Package

filament/filament

### Package Version

v3

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

PHP 8.1

### Problem description

I have 4 widgets at Edit Resource page. Initially, the 4 widgets show up but if I edit the form data with reactive, only the last widget show up. The other 3 widgets disappeared. Filament V2 works fine for this behavior.

Thanks

### Expected behavior

The widgets should not disappear

### Steps to reproduce

1. Edit an model with footer 4 widgets
2. Update some fields with reactive 
3. Only last widget show up and the rest of widgets disappear

### Reproduction repository

https://github.com/globalinvestai/investai-portal

### Relevant log output

```shell
Thanks
```

**Comment by danharrin** [comment]
No public reproduction repo
