### ISSUE TITLE
Dependent select searchable not firing afterStateUpdated()

### ISSUE THREAD

**Issue by PLGUPICTO** [laravel-filament/filament#8010]
### Package

filament/filament

### Package Version

v3.0.30

### Laravel Version

10.20.0 

### Livewire Version

v3.0.0-beta.10

### PHP Version

8.1.10  

### Problem description

If I comment searchable() the $get() will get the drawer_id, but if uncomment it, it will get a null value. That's why I can't query in the second select when using searchable in both select.

```
Select::make('drawer_id')
                            // ->searchable() 

    ->options(Drawer::query()->pluck('name', 'id'))
    ->afterStateUpdated(fn (Set $set) => $set('folder_id', null))
    ->live()
    ->preload(),

Select::make('folder_id')
    ->searchable()
    ->getSearchResultsUsing(fn (Get $get): array => dd($get('drawer_id'))) //this will get null if drawer searchable is uncomment
    ->getOptionLabelUsing(fn ($value): ?string => Folder::find($value)?->name),
```

### Expected behavior

Second select must populate when first select is selected even when searchable()

### Steps to reproduce

```
Select::make('drawer_id')
                            // ->searchable() 

    ->options(Drawer::query()->pluck('name', 'id'))
    ->afterStateUpdated(fn (Set $set) => $set('folder_id', null))
    ->live()
    ->preload(),

Select::make('folder_id')
    ->searchable()
    ->getSearchResultsUsing(fn (Get $get): array => dd($get('drawer_id'))) //this will get null if drawer searchable is uncomment
    ->getOptionLabelUsing(fn ($value): ?string => Folder::find($value)?->name),
```

### Reproduction repository

https://github.com/PLGUPICTO/archive_filamentv3/blob/master/app/Filament/Resources/DocumentResource.php

**Comment by ManojKiranA** [comment]
Any console errors ?

**Comment by PLGUPICTO** [comment]
![image](https://github.com/filamentphp/filament/assets/118878534/79731077-48fc-43de-807e-7e4bf21c79f3)

I only got these errors which idk why I'm getting as this is not a custom page and pure resource --generate. 

Upon selecting the dropdowns no errors were found.

**Comment by elcapo** [comment]
I've been experiencing a similar issue and here is what I've found:

1. it seems like the first select is missing a **->reactive()** call,
2. making the first select reactive triggers the **->afterStateUpdated** method but still does not clear the other select,
3. the issue seems to be clearing other field (for instance, setting it to **null** or to an empty string).

The versions I'm using are pretty much the same as @PLGUPICTO.

**Comment by stijntrinos** [comment]
@PLGUPICTO, I had a similar issue with the `afterStateUpdated` function not being triggered.

I had below code
```
Select::make('data.qa1')
  ->label('qa1')
  ->options([
    'a1' => 'a1',
    'a2' => 'a2',
    'a3' => 'a3',
  ])
  ->live()
  ->afterStateUpdated(function (Get $get, Component $component, ?string $state) {
    echo $state;
  }),
```

In V2 the `afterStateUpdated` was called and everything worked. Now it doesn't work anymore. I found that when I add `public $data;` at the top of the class, it works again

**Comment by leandrocfe** [comment]
Why are you overriding the mount method? If you need to override it, it should be done like this.
```php
public function mount(): void
{
    parent::mount();
    //...
}
```
the issue is here [mount method](https://github.com/PLGUPICTO/archive_filamentv3/blob/master/app/Filament/Resources/DocumentResource/Pages/CreateDocument.php)

**Comment by neverender24** [comment]
@leandrocfe hi, its just a test for can() access in that page, I think it doesn't affect the whole problem in this issue. Even if you go to edit page where I don't override it, the issue exists.

**Comment by leandrocfe** [comment]
This issue should be made clearer and should include the final code you want to achieve, instead of using `dd()`. I'm testing the specific point you mentioned: *this will be null if drawer searchable is uncommented*. It works and doesn't produce any console errors when you remove the mount method (or add `$this->fillForm()`) in the CreateDocument.php file.

**Comment by neverender24** [comment]
@leandrocfe that is the main problem in the  description, it should not be null, you can read my issue again.

**Comment by PLGUPICTO** [comment]
@leandrocfe I think you're right removing the mount() fix it. Maybe the docs should also be improved https://filamentphp.com/docs/3.x/panels/pages#conditionally-hiding-pages-in-navigation as I just implemented what says in there. Maybe add parent::mount(); in the example
