### ISSUE TITLE
[2.x] Repeater component getting console error

### ISSUE THREAD

**Issue by shuvroroy** [laravel-filament/filament#802]
### Package

filament/forms

### Package Version

v2

### Laravel Version

v8

### PHP Version

PHP 8.1

### Bug description

When I remove element from Repeater component I am getting console error.

<img width="1671" alt="Screenshot 2021-12-10 at 7 50 20 PM" src="https://user-images.githubusercontent.com/21066418/145584133-1eb6c905-0ecb-4438-ae17-68c6c9c4e7e0.png">

<img width="1262" alt="Screenshot 2021-12-10 at 7 50 44 PM" src="https://user-images.githubusercontent.com/21066418/145584217-9ca38c33-cb49-483d-aa42-4c4280d2994f.png">

### Steps to reproduce

[Video](https://www.awesomescreenshot.com/video/6403333?key=1bfed5512782763427e90a6a3c0e0c97)

**Comment by danharrin** [comment]
Couldn't replicate, as mentioned on Discord.
