### ISSUE TITLE
 Infolists\Components\Actions\Action get an error in a view modal

### ISSUE THREAD

**Issue by breakzhuo** [laravel-filament/filament#8034]
### Package

filament/filament

### Package Version

v3.0.30

### Laravel Version

v10.20.0

### Livewire Version

v3.0.0-beta.10

### PHP Version

8.1.0

### Problem description

 Infolists\Components\Actions\Action get an error in a view modal,using the same code.

![image](https://github.com/filamentphp/filament/assets/90298699/d9e2d5c4-7e1c-43b2-8b24-4c8288e7d0ca)

simple （ view  in a  modal）,i got:

![image](https://github.com/filamentphp/filament/assets/90298699/0c406a3d-fcd4-4c92-aae0-01534ca06be3)
 

### Expected behavior

![image](https://github.com/filamentphp/filament/assets/90298699/b767fb74-d63c-4be8-b247-850746292cb2)

### Steps to reproduce

1.add this code to a ViewAction ：
`
 Infolists\Components\TextEntry::make('title')
                                            ->hint('wwww')
                                            ->hintAction(
                                                Infolists\Components\Actions\Action::make('resetStars')
                                                    ->icon('heroicon-m-x-mark')
                                                    ->color('danger')
                                                    ->requiresConfirmation()
                                            ),
`
2. ViewAction is  "simple",show in a modal
3. trigger ViewAction

### Reproduction repository

https://github.com/filamentphp/demo

### Relevant log output

```shell
Typed property Filament\Infolists\Infolist::$name must not be accessed before initialization
```

**Comment by ralphjsmit** [comment]
I'm also getting this error. It is as simple as adding any Action in an infolist modal. For example, a table action with an infolist:

```php
Infolists\Components\Actions::make([
    Infolists\Components\Actions\Action::make('download')
        ->icon('heroicon-o-arrow-down-tray')
        ->action(function () {
            dd('X');
        }),
]),
```

Can this one be re-opened @danharrin?

**Comment by danharrin** [comment]
Duplicate #7630

**Comment by ralphjsmit** [comment]
Okay, thank you!
