### ISSUE TITLE
Bulleted text column doesn't show bullets

### ISSUE THREAD

**Issue by ilpav12** [laravel-filament/filament#8055]
### Package

filament/tables

### Package Version

v3.0.34

### Laravel Version

v10.20

### Livewire Version

v3

### PHP Version

PHP 8.2

### Problem description

Text column with `->bulleted()` does not show the the bullets because of the `flex` class applied to the `<li>` tag.

### Expected behavior

Showing the bullets.

### Steps to reproduce

Clone the `bug/bulleted-text-column` branch of the reproduction repository
Migrate and seed db
login with test@email.com, password
See Groups table list where text column does not show bullets

### Reproduction repository

https://github.com/ilpav12/filament-bug

**Comment by hsul4n** [comment]
Same issue also after updating to v3.0.34
