### ISSUE TITLE
Remove deprecated CSS hook classes

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#8064]
`fi-tabs-item-active`
`fi-sidebar-item-active`

**Comment by danharrin** [comment]
IMO we should somehow make a note in the source code that these are deprecated so people stop using them

**Comment by zepfietje** [comment]
Sure, suggestions on how to note?

**Comment by danharrin** [comment]
Honestly not sure, maybe a Blade comment. Ideally we'd put it in the HTML output itself tbh

**Comment by zepfietje** [comment]
Hmm, it's tricky though as this class is used in `x-bind:class` as well as `@class()`.
