### ISSUE TITLE
Inputs doesn't support translatable

### ISSUE THREAD

**Issue by sanis** [laravel-filament/filament#8068]
### Package

filament/spatie-laravel-translatable-plugin

### Package Version

v3.0.34

### Laravel Version

v10.20.0

### Livewire Version

v3.0.0

### PHP Version

8.2.8

### Problem description

Currently nether searchable `Select` supports translatable models, nether multiple `Select` with `multiple()` option. Basically it displays the string from the database, but not the translated value accordingly to selected language.

Im attaching screenshot as a example:
![image](https://github.com/filamentphp/filament/assets/3956177/6fbe7dcb-a213-4585-a8fb-76dd44de69d3)

More to add, `TextInput` in `Repeater` also doesn't respond to the language in the model that I edit right now.

### Expected behavior

I expect, that all the fields that are translatable displays titles in select, search accordingly and when I change language fields in repeater changes in language as well.

### Steps to reproduce

Inside the Product resource I have added relation to `ProductVariant` which has translatable field "title". 

Also I have changed `Category` and `Band` to use translatable name. So everything could be reproduced by using Product edit page by changing band/category and adding `ProductVariant`.

More to add I'm attaching JAM to show it as a video format.

https://jam.dev/c/e3f87c3f-2363-4125-9bee-208dfc83595a

There is a branch on repository called `translatable-issues` where you could see the code changes.

### Reproduction repository

https://github.com/sanis/filament-demo/tree/translatable-issues

**Comment by tomas-doudera** [comment]
If you comment this row in vendor translations works as expected. FYI.
So there is some problem with casts it seems.

Filament\Forms\Components\Select.php

<img width="1225" alt="image" src="https://github.com/filamentphp/filament/assets/32466344/90235679-ef35-439f-a916-106612a0ea02">

**Comment by ArtMin96** [comment]
I have the same problem when using searchable select

**Comment by sanis** [comment]
> If you comment this row in vendor translations works as expected. FYI. So there is some problem with casts it seems.
> 
> Filament\Forms\Components\Select.php
> 
> <img alt="image" width="1225" src="https://user-images.githubusercontent.com/32466344/263305798-90235679-ef35-439f-a916-106612a0ea02.png">

This might somehow magically help in select fields, however repeater isn't really working in that way. However the lines above looks like call for attributes that are language specific and it could be easy fix.

**Comment by danharrin** [comment]
There isn't a nice way to detect this on the database level, you should try `->getOptionLabelFromRecordUsing(fn ($record) => $record->translatable_column_name)`

**Comment by JelmerIJff** [comment]
@danharrin When using the relationship select filter it also shows a json object instead of only the name. https://filamentphp.com/docs/3.x/tables/filters#relationship-select-filters. Above fix doesn't work on a SelectFilter.
