### ISSUE TITLE
TernaryFilter null state is broken after refreshing and reseting filters

### ISSUE THREAD

**Issue by Plytas** [laravel-filament/filament#8073]
### Package

filament/filament

### Package Version

v3.0.34

### Laravel Version

v10.20.0

### Livewire Version

v3.0.0

### PHP Version

PHP 8.2.7

### Problem description

Ran into issue with TernaryFilter, which also applies to TrashedFilter that's present in https://github.com/filamentphp/demo.
This only started breaking since version 3.0.28 when filter query params were introduced.
This does not happen on https://demo.filamentphp.com because it's still on version 3.0.27.

Refreshing a page with filters enabled and then trying to reset filters will put `null` in query parameter causing filter to treat it as `true`.

Recording of this issue:

https://github.com/filamentphp/filament/assets/17316322/fe7966fe-e61b-4835-8009-75025c6ba887

Notice that when applying With deleted records there's a first row `Dr. Dustin ...` that's actually soft deleted. After reseting filters and refreshing page the filter gets applied again.
This does not happen if you don't refresh the page in step `5`. In that case reseting filters removes query param completely.
I believe what happens is that state value becomes a string `"null"` and it becomes true when being cast to bool.

### Expected behavior

Expected filter reset to use null state.

### Steps to reproduce

1. Set up filament demo
2. Upgrade to version 3.0.28 or above
3. Open Customers index /shop/customers
4. Enable filter With deleted records
5. Refresh the page
6. Click Reset button in filter form
7. Observe that url query parameter has null for filter value
8. Refresh the page
9. Observe incorrect filter being applied.

### Reproduction repository

https://github.com/Plytas/demo

**Comment by archilex** [comment]
@Plytas Hi. This is a known issue with Livewire. Follow along on this thread as well as temporary fix you can implement: https://github.com/filamentphp/filament/issues/7129

**Comment by Plytas** [comment]
Thanks you, will close this in favor of #7129
