### ISSUE TITLE
File upload is looking a bit odd

### ISSUE THREAD

**Issue by dejagersh** [laravel-filament/filament#8090]
### Package

filament/forms

### Package Version

v3.0.34

### Laravel Version

v10.20.0

### Livewire Version

3.0.1

### PHP Version

8.2.8

### Problem description

<img width="727" alt="image" src="https://github.com/filamentphp/filament/assets/9981548/b6e5d9ca-2dfd-4b14-b644-d7f58420547a">

I am missing padding + it's taking up only about half of the space.

### Expected behavior

<img width="367" alt="image" src="https://github.com/filamentphp/filament/assets/9981548/54ccf64a-954c-4782-8791-6bc7589daf2e">

Something like this ^

### Steps to reproduce

Create a file upload field, upload e.g. a PDF file.

### Reproduction repository

https://github.com/dejagersh/filament-upload

**Comment by dejagersh** [comment]
<img width="640" alt="image" src="https://github.com/filamentphp/filament/assets/9981548/ecf1bc19-d5a6-4797-8d02-494913f397a2">

In the admin demo it's also kinda weird. Is this intended behaviour?

**Comment by zepfietje** [comment]
Thanks for reporting, @dejagersh.
I don't really think this is a bug indeed.
It's probably just how FilePond works.

Feel free to create a PR to improve the UI though if you can. 😊

**Comment by deonoize** [comment]
It still looks the same. Can this be fixed?
