### ISSUE TITLE
Arranging records into a grid not works

### ISSUE THREAD

**Issue by heshamamer98** [laravel-filament/filament#8160]
### Package

filament/tables

### Package Version

v3.0.36

### Laravel Version

v10.21.0

### Livewire Version

v3.0.1

### PHP Version

PHP 8.1.21

### Problem description

When using `->contentGrid()`, the table still looks like a classic table, and the actions are getting disappeared.

### Expected behavior
The table layout should be grid like the screenshot below and actions should appear at the bottom of each grid cell
![Screen Shot 2023-08-29 at 10 20 04 PM](https://github.com/filamentphp/filament/assets/55026818/4be985e4-a6de-40a8-83e4-a6d32c95f137)

### Steps to reproduce

- Using filament demo project
- Update filament package to version v3.0.36
- Add `->contentGrid(['md' => 2,'xl' => 3])` to ProductResource table or any other table you prefer

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by frcamposalmarales** [comment]
I have the same problem. 
![image](https://github.com/filamentphp/filament/assets/39931475/9fa6b600-7ac2-458b-8fae-de9398242416)

**Comment by nomitoor** [comment]
any one found solution for this problem ?
