### ISSUE TITLE
Chart filters are loading infinitely

### ISSUE THREAD

**Issue by ModestasV** [laravel-filament/filament#8175]
### Package

filament/filament

### Package Version

v3.0.37

### Laravel Version

v10.0.21

### PHP Version

8.2.7

### Problem description

When a filter is created for a widget - it is loading non-stop:

<img width="814" alt="image" src="https://github.com/filamentphp/filament/assets/3809773/9da2e27e-284d-4be0-828c-c41e9664b423">

<img width="713" alt="image" src="https://github.com/filamentphp/filament/assets/3809773/a4142a65-79df-441f-a7cb-b13e8431152e">

This indicator never goes away

### Expected behavior

The loading indicator should disappear once the filter is done loading

### Steps to reproduce

Log in to the application using:
admin@admin.com / password

On the dashboard, you will see the issue.

---

The chart was created from the documentation example without any other modifications:
https://filamentphp.com/docs/3.x/widgets/charts#filtering-chart-data

### Reproduction repository

https://github.com/ModestasV/filamentissue-chart-loading-infinite

**Comment by ModestasV** [comment]
Additional:

This was also mentioned in Discord (https://discord.com/channels/883083792112300104/1145717941745238086) as an issue with a potential solution.

**Comment by sakanjo** [comment]
@ModestasV Thanks for reporting the bug!

**Comment by ModestasV** [comment]
@sakanjo Thank you for the fix attempt!
