### ISSUE TITLE
console error while deleting image.

### ISSUE THREAD

**Issue by iRajul** [laravel-filament/filament#8186]
### Package

filament/filament

### Package Version

v3.0.32

### Laravel Version

v10.21.0

### Livewire Version

V2.0.1

### PHP Version

PHP 8.1

### Problem description

Install the reproduction repository.
Go to `admin/users/1/edit` 
Upload an image and after uploading refresh the page. 
Then press the "cross" button to delete the image. It will show following console logs. 

This is happening after upgrading to Filament version 3.0.32
I further see the different between 3.0.32 and 3.0.31 and find out that following line has been removed in `SupportServiceProvider.php` 
`config()->set('livewire.inject_morph_markers', false);` If I add this line then issue go away. 

This is not reproducible in localhost. I have setup a cloudflare tunnel to a staging subdomain for localhost. 
So this issue happens only with this setup. I am not sure what is the issue but after adding `inject_morph_markers` to false everthing works again.

```
Uncaught (in promise) Could not find Livewire component in DOM tree
(anonymous) @ file-upload.js?v=3.0.31.0:40
await in (anonymous) (async)
(anonymous) @ livewire.js?id=11c49d7e:2984
2file-upload.js?v=3.0.31.0:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertBefore')
    at Ra (file-upload.js?v=3.0.31.0:1:9444)
    at Object.replaceElement (file-upload.js?v=3.0.31.0:2:72963)
    at Id (file-upload.js?v=3.0.31.0:2:74588)
    at bd (file-upload.js?v=3.0.31.0:2:74629)
    at at (file-upload.js?v=3.0.31.0:2:76831)
    at Proxy.init (file-upload.js?v=3.0.31.0:40:81100)
```

### Expected behavior

Image should be delete without any console errors.

### Steps to reproduce

- Install the reproduction repository.
- php artisan migrate
- go to `admin/users/1/edit`
- Upload an image and after uploading refresh the page. 
- Then press the "cross" button to delete the image. It will show following console logs. 

### Reproduction repository

https://github.com/iRajul/laravel_app_1.git

### Relevant log output

```shell
Uncaught (in promise) Could not find Livewire component in DOM tree
(anonymous) @ file-upload.js?v=3.0.31.0:40
await in (anonymous) (async)
(anonymous) @ livewire.js?id=11c49d7e:2984
2file-upload.js?v=3.0.31.0:1 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertBefore')
    at Ra (file-upload.js?v=3.0.31.0:1:9444)
    at Object.replaceElement (file-upload.js?v=3.0.31.0:2:72963)
    at Id (file-upload.js?v=3.0.31.0:2:74588)
    at bd (file-upload.js?v=3.0.31.0:2:74629)
    at at (file-upload.js?v=3.0.31.0:2:76831)
    at Proxy.init (file-upload.js?v=3.0.31.0:40:81100)
```
```

**Comment by danharrin** [comment]
Please track down where the morph comment is being added by Livewire in the wrong place. You can then submit a failing test PR to Livewire (a bug report, basically), and they can fix it.

Temporarily, in your livewire.php config file, set `inject_morph_markers` to false, and verify it works.

I can't reproduce this BTW.
