### ISSUE TITLE
Action ->hidden() does not hide  but instead disabled the button

### ISSUE THREAD

**Issue by ezani92** [laravel-filament/filament#8196]
### Package

filament/filament

### Package Version

3

### Laravel Version

10

### Livewire Version

3

### PHP Version

8.2

### Problem description

`return Action::make('posadminlogin')`
`        ->label('Sign In')`
`        ->url($this->account.'/sso/'.$this->sso())`
`        ->hidden()`
`        ->extraAttributes(['class' => 'btn-wide w-full bg-indigo-800 text-white']);`

Above is code how i add an action to custom page. instead of hide the action button. its show the button but in disabled mode.

### Expected behavior

Button should be hidden instead of disabled when using hidden()

### Steps to reproduce

`return Action::make('posadminlogin')`
`        ->label('Sign In')`
`        ->url($this->account.'/sso/'.$this->sso())`
`        ->hidden()`
`        ->extraAttributes(['class' => 'btn-wide w-full bg-indigo-800 text-white']);`

### Reproduction repository

https://github.com/filamentphp/filament

**Comment by russdot** [comment]
I am encountering this same problem. I have an Action on a widget and calling `->hidden()` results in it showing as disabled?

**Comment by conghuyn42** [comment]
I also encountered this issue and had to resolve it by wrapping the "return Action..." statement within an if condition.

**Comment by PaulMcML** [comment]
This is still an issue. The need to generate an entire publicly available project to demonstrate bugs is a serious impedement to bug reporting and improving this project. Filament has become a lead weight around our necks and I am currently advising all PHP developers to avoid using it. You will not improve this project by handling bugs in this manner, you need to engage with the community or filament will die.
