### ISSUE TITLE
Global search results dropdown is clipped on Safari

### ISSUE THREAD

**Issue by fauzie811** [laravel-filament/filament#8215]
### Package

filament/filament

### Package Version

v3.0.27

### Laravel Version

v10.19.0

### Livewire Version

v3.0.1

### PHP Version

PHP 8.1.0

### Problem description

The global search results dropdown is clipped on **Safari 16.5 on macOS Monterey 12.6.6** when the results total height is less than the dropdown's max height, i.e.: no scrollbar.

**Has scrollbar:**
<img width="1392" alt="Screen Shot 2023-09-01 at 19 27 01" src="https://github.com/filamentphp/filament/assets/318095/07ca9271-ebdc-43fc-b5a7-bddcace39770">

**No scrollbar:**
<img width="1392" alt="Screen Shot 2023-09-01 at 19 27 20" src="https://github.com/filamentphp/filament/assets/318095/d528175c-3b86-40e7-84e4-8088f66cdcbb">

### Expected behavior

The dropdown shouldn't be clipped.

### Steps to reproduce

Search for anything specific where there's only a few results.

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by zepfietje** [comment]
I've looked into this issue but can't find a way to fix it...
It seems like a Safari bug, as it doesn't happen in other browsers, but I can't even find any references of it on the internet.

Would be great if someone else could try and find the bug/fix.

**Comment by howdu** [comment]
@zepfietje it's related to the `overflow-x-clip` on `fi-topbar`. If you remove this it displays correctly.

**Comment by zepfietje** [comment]
Good catch, @howdu!
We need that class though, as it's required to clip the shadows on the topbar and prevent them from overflowing onto the sidebar header...

**Comment by danharrin** [comment]
Are we not able to use z-index somehow

**Comment by zepfietje** [comment]
I tried... to no avail. 🥲

**Comment by zepfietje** [comment]
Fixed by https://github.com/filamentphp/filament/commit/0c49de8f3070e6cec99b33085c2c61d67fd4e078 and https://github.com/filamentphp/filament/commit/a2d3ddf1cccb8c6807047abe346d55acc8ad507a.
