### ISSUE TITLE
edit in policy does not work

### ISSUE THREAD

**Issue by rabol** [laravel-filament/filament#822]
### Package

filament/filament

### Package Version

v2.5.14

### Laravel Version

v8.75

### Livewire Version

v2.8.2

### PHP Version

v8.0.13

### Bug description

Documentation say that edit() control if a resource can be edited, but in fact it is update().
https://filamentadmin.com/docs/2.x/admin/resources#authorization

if one have a edit like this:

````
public function edit(User $user, Country $country)
    {
        if($country->short_code == 'es')
            return false;

        return true;
    }
````
one can edit the record, but this works

````
public function update(User $user, Country $country)
    {   
        if($country->short_code == 'es')
            return false;

        return true;
    }
````

### Steps to reproduce

create an edit method in a policy an observe that it does not have any effect

**Comment by danharrin** [comment]
All good, this was fixed in the docs a few days ago but I need to redeploy the site. Thanks.
