### ISSUE TITLE
FileUpload foreach() argument must be of type array|object, string given

### ISSUE THREAD

**Issue by pslxx** [laravel-filament/filament#8224]
### Package

filament/filament

### Package Version

V3.0.38

### Laravel Version

10

### Livewire Version

3.0.1

### PHP Version

8.1

### Problem description

<img width="783" alt="image" src="https:github.com/filamentphp/filament/assets/8417207/31a7e481-d805-4553-af73-7df44ab6e847">

`
class Setting extends Page{
 public array $data = [
        'file'=>'1.txt'
    ];

  public function form(Form $form): Form
    {
        return $form->schema([
            FileUpload::make('file')->label('file'),
  }
}
`

### Expected behavior

`

### Steps to reproduce

`

### Reproduction repository

`

### Relevant log output

```shell
`
```

**Comment by pslxx** [comment]
<img width="676" alt="image" src="https://github.com/filamentphp/filament/assets/8417207/d77f1a8f-f7ae-4808-95a8-6f48519bd00a">
<img width="1414" alt="image" src="https://github.com/filamentphp/filament/assets/8417207/fb18aa99-f61f-4eb3-8d2a-ccdd99b1d1b4">

**Comment by sh4msi** [comment]
I also have this problem in EditRecord
Is there a solution?

**Comment by sh4msi** [comment]
I also have this problem in EditRecord
Is there a solution?

@danharrin 
@pslxx

**Comment by abanghendri** [comment]
I also face this issue on laravel 11 and filament 3.2
is there any update for this Mr. @danharrin

**Comment by danharrin** [comment]
We do not investigate issues without reproduction repositories. If you submit a new issue with one, we will check it out. Please start from a blank Laravel app.

**Comment by abanghendri** [comment]
thanks Mr. @danharrin , I've created an issue #12076

**Comment by abanghendri** [comment]
Hi @pslxx @sh4msi , I also face that issue and make a new issue #12076 , I do this to fix it, try to change your data init from this
```
class Setting extends Page{
public array $data = [
'file'=>'1.txt'
];
```

to this:
```
class Setting extends Page{
public array $data = [
'file'=>['1.txt']
];
```
since $this->getState() should return and array, not string
