### ISSUE TITLE
Testing a create action is not creating a model

### ISSUE THREAD

**Issue by alexmanase** [laravel-filament/filament#8225]
### Package

filament/filament

### Package Version

v3.0.39

### Laravel Version

10.21.0

### Livewire Version

v3.0.1

### PHP Version

8.2.8

### Problem description

When I test a `createAction` component the tests are passing, but a model is not created.

For example for this create action:

```php
public function createAction()
{
    return CreateAction::make('create')
        ->model(Post::class)
        ->form([
            TextInput::make('title')
                ->required()
                ->maxLength(255),
        ]);
    }
```

And this test:

```php
livewire(CreatePost::class)
       ->callAction('create')
       ->assertOk();
```

The list of models will be empty, even though the the test is passing. 

### Expected behavior

A model to be created after calling the action in testing.

### Steps to reproduce

1. Create an action component.

```php
public function createAction()
    {
        return CreateAction::make('create')
                ->model(Post::class)
                ->form([
                    TextInput::make('title')
                        ->required()
                        ->maxLength(255),
                ]);
    }
```

2. Create a test.

```php
livewire(CreatePost::class, ['name' => 'alex'])
    ->callAction('create')
    ->assertOk(); // PASS

expect(Post::first())->name->toBe('alex'); // FAIL
```

3. Observe that the Livewire test is passing, but the database it's not.

### Reproduction repository

https://github.com/alexmanase/filament-create-action-testing-issue

**Comment by danharrin** [comment]
```
livewire(CreatePost::class)
    ->callAction('create', ['name' => 'alex'])
    ->assertHasNoActionErrors() // More useful than assertOk()
    ->assertNotified();

expect(Post::first())->name->toBe('alex');
```

**Comment by alexmanase** [comment]
Thank you!
