### ISSUE TITLE
Unique validation error on update

### ISSUE THREAD

**Issue by AlexVanSteenhoven** [laravel-filament/filament#8228]
### Package

filament/forms

### Package Version

v3.0.36

### Laravel Version

v10.20

### Livewire Version

v3.0.1

### PHP Version

PHP 8.1.0

### Problem
When I am trying to changing the status of my record (active or inactive) I am getting an validation error.
The error tells me the following error on the name field (which is unique in this case): _"The name has already been taken."_

#### Example
![image](https://github.com/filamentphp/filament/assets/67007082/07cff651-59c5-4fd7-8dff-fca8646a179f)

#### My code
```php
public static function form(Form $form): Form
{
  return $form
    ->schema([
      Forms\Components\TextInput::make('name')
        ->autofocus()
        ->required()
        ->unique(Services::class, 'name')
        ->placeholder(__('Name')),

      Forms\Components\Textarea::make('description')
        ->placeholder(__('Description')),

      Forms\Components\TextInput::make('price')
        ->required()
        ->placeholder(__('Price'))
        ->numeric(),

      Forms\Components\FileUpload::make('image')
        ->placeholder(__('Image'))
        ->storeFileNamesIn('services'),

      Forms\Components\Toggle::make('status')
        ->required()
        ->label(__('Status')),
    ]);
}
```

### Expected behavior

Expecting to update the status field (active in DB) without getting the error that the name has already been taken.

### Steps to reproduce

1. Identify an Existing Record:
Look for an existing record within the "Services" form that you would like to edit. Ensure that this record has a unique "name" field, and remember the current "name" value.

2. Edit the Record:
Select the record you identified for editing. Make changes to the record, specifically changing the "status" field from "inactive" to "active." Do not modify the "name" field.

3. Save the Changes:
After making the change to the "status" field, locate and click the "Update" or "Save" button on the form to save the changes you made to the record.

4. Observe the Error:
Pay close attention to the screen for any error messages that appear after you click the "Update" or "Save" button. Look for an error message that mentions the "name" field already being taken.

### Reproduction repository

https://github.com/AlexVanSteenhoven/filament-forms-unique-bug

**Comment by wychoong** [comment]
have you read the doc? it specifically mentioned your scenario https://filamentphp.com/docs/3.x/forms/validation#unique

**Comment by AlexVanSteenhoven** [comment]
@wychoong Thanks, I didn't read it properly I think. `ignoredRecord: true` fixed it for me.

**Comment by AbhinasRegmi** [comment]
this works during create but validation errors out during update.

I have two tables users and applicants the applicants belongsTo users and users hasOne applicants.

I have this form field for ApplicantResource's form
Forms\Components\TextInput::make('email')
                    ->required()
                    ->email()
                    ->unique('users',ignoreRecord:true),

This works during creation of applicant in which i have. But during edit it errors out like this

Connection: mysql, SQL: select count(*) as aggregate from `users` where `email` = error@gmail.com and `applicants`.`id` <> 9)

here applicant_profiles.id = 9 i believe this is incorrect. applicants should be a table not a field

**Comment by wychoong** [comment]
> here applicant_profiles.id = 9 i believe this is incorrect. applicants should be a table not a field

Because you are using it incorrectly. The parameter name is literally telling you ‘ignore record’ and in this context of ApplicantResource, it is the applicant record. 

“select count(*) as aggregate from users where email = error@gmail.com and id <> 9)” is wrong too, it’s using applicant id in user table

If you understand what’s wrong, you should be able to change the rule with `modifyRuleUsing` to fit your usage

If you unable to fix it or insist it’s a bug. Open a new issue, as it’s a different issue to this solved issue

**Comment by AbhinasRegmi** [comment]
where do i add modifyRuleUsing. I am lost here.
