### ISSUE TITLE
File upload not working

### ISSUE THREAD

**Issue by damms005** [laravel-filament/filament#8229]
### Package

filament/filament

### Package Version

v3.0.39

### Laravel Version

v10.21.0

### Livewire Version

v3.0.1

### PHP Version

PHP 8.1.22

### Problem description

When I upload this CSV file, it shows error: Property type not supported in Livewire for property: [null]

[2023-2024-first-semester-dol-101-2023-09-01-20-07-41.csv](https://github.com/filamentphp/filament/files/12501727/2023-2024-first-semester-dol-101-2023-09-01-20-07-41.csv)

### Expected behavior

When I upload this CSV file, it should not show error and the file should be assigned to the `file` public property.

### Steps to reproduce

- Clone https://github.com/damms005/example-app
- `composer install`
- Make a user to login with `php artisan make:filament-user`
- Start server `php artisan serve`
- Visit upload page http://127.0.0.1:8000/admin/upload-scoresheet (assumes your server address is `http://127.0.0.1:8000`)
- Upload the attached CSV file into the Scoresheet input field
- See the error similar to screenshot below:

![image](https://github.com/filamentphp/filament/assets/9839355/8c576202-6d27-4968-89cf-0b13bfaec3d3)

[2023-2024-first-semester-dol-101-2023-09-01-20-07-41.csv](https://github.com/filamentphp/filament/files/12501744/2023-2024-first-semester-dol-101-2023-09-01-20-07-41.csv)

### Reproduction repository

https://github.com/damms005/example-app

**Comment by sakanjo** [comment]
@damms005 thanks for reporting, it's not an issue with filamentphp, instead reading the [docs](https://filamentphp.com/docs/3.x/forms/adding-a-form-to-a-livewire-component#adding-the-form) will fix the problem.

```php
<?php

namespace App\Filament\Pages;

use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\Grid;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Forms\Form;
use Filament\Pages\Page;

class UploadScoresheet extends Page implements HasForms
{
    use InteractsWithForms;

    protected static string $view = 'filament.pages.upload-scoresheet';

    protected static ?string $navigationGroup = 'Academic Result';

    protected static ?int $navigationSort = 2;

    public ?array $data = [];

    public function form(Form $form): Form
    {
        return $form->schema([
            Grid::make(1)
                ->schema([
                    FileUpload::make('file'),
                ]),
        ])
            ->statePath('data');
    }
}
```

**Comment by sakanjo** [comment]
Please refer to official docs of 3.x and not 2.x, since there's a big difference in the syntax.

**Comment by damms005** [comment]
Oops. I over-relied on the upgrade guide.

Many thanks, @sakanjo

**Comment by XarchencoMO** [comment]
Hey, @damms005, can you help me, how you resolved your problem ? i have a same problem in my project, but i did all steps via documentation for filament v3

**Comment by damms005** [comment]
Can't recall exactly the fix that worked for me, but checking the upgrade guide was what fixed it for me because the official livewire update script did not handle something about how I was handling file upload.
