### ISSUE TITLE
Console error when using Select in modal

### ISSUE THREAD

**Issue by wychoong** [laravel-filament/filament#8234]
### Package

filament/filament

### Package Version

3.0.39

### Laravel Version

10.21.0

### Livewire Version

3.0.1

### PHP Version

8.1.22

### Problem description

using none native in a modal, a console error is shown after closing the modal

![image](https://github.com/filamentphp/filament/assets/67364036/7a729e41-efea-452b-b166-a1654235aacc)

### Expected behavior

no error in console

### Steps to reproduce

- pull the repo @ branch: select-field-console-error
- `artisan test:init`
- navigate to Task > create/edit > click Create task item (relation manager) > close, don't need to create or open dropdown

### Reproduction repository

https://github.com/wychoong/filament-test/tree/select-field-console-error

**Comment by sakanjo** [comment]
@wychoong the re-production repo seems not to exist, can you re-check please.

**Comment by wychoong** [comment]
> @wychoong the re-production repo seems not to exist, can you re-check please.

Shoot, it was private 😂

**Comment by danharrin** [comment]
It's a Livewire 3 issue where it runs watchers after the properties from the component are destroyed, I tried submitting a failing test before but it wasn't good enough

**Comment by danharrin** [comment]
It's a Livewire 3 issue where it runs watchers after the properties from the component are destroyed, I tried submitting a failing test before but it wasn't good enough

**Comment by uevandalla** [comment]
> It's a Livewire 3 issue where it runs watchers after the properties from the component are destroyed, I tried submitting a failing test before but it wasn't good enough

Any movement on this?  we are having the same issue after upgrading from Filament version 2 to version 3 with several of our pages

**Comment by danharrin** [comment]
@uevandalla While there is a console error, it should not affect the functionality of the page.

**Comment by danharrin** [comment]
If you'd like to see movement on this, submit a failing test to Livewire. Else, be patient until I have time to investigate further.

**Comment by ue-shuston** [comment]
This seems to be related to [Livewire discussion #6704](https://github.com/livewire/livewire/discussions/6704) and may be related to "using a subdomain with cloudflare".

**Comment by wychoong** [comment]
> This seems to be related to [Livewire discussion #6704](https://github.com/livewire/livewire/discussions/6704) and may be related to "using a subdomain with cloudflare".

Not related at all. This is on local, without subdomain. 

Not all console error are related, and the error message is different too.

**Comment by zepfietje** [comment]
Is this still an issue, or has it been fixed in Livewire since?

**Comment by wychoong** [comment]
> Is this still an issue, or has it been fixed in Livewire since?

error still exist
<img width="521" alt="image" src="https://github.com/filamentphp/filament/assets/67364036/f169cdaa-9e00-460f-ac26-f6cb076dc0d6">

**Comment by wychoong** [comment]
~~@zepfietje while testing with the latest release, I also notice a new error message~~
<img width="563" alt="image" src="https://github.com/filamentphp/filament/assets/67364036/c183ebfb-e906-47bd-91f6-42267f8c5cfe">

~~it happens since 3.0.57, and doing a release compare I don't see any notification.js related changes other than assets rebuild~~


**update: fixed in 3.0.62**

**Comment by zepfietje** [comment]
Thanks for checking!

**Comment by wychoong** [comment]
> Thanks for checking!

Sorry maybe I confused you. The one fixed is another error. The original error still persist after update.

**Comment by zepfietje** [comment]
Oh that wasn't clear to me.

**Comment by wychoong** [comment]
still an issue with 3.073 and LW3.07

**Comment by danharrin** [comment]
Don't think we're gonna get a fix for this in LW so I've just added a null check https://github.com/filamentphp/filament/commit/5545c5307127ba5604f7678cac1d746eb09f337a
