### ISSUE TITLE
Money Mask fails the integer or numeric validation

### ISSUE THREAD

**Issue by ariaieboy** [laravel-filament/filament#8238]
### Package

filament/forms

### Package Version

v3.0.39

### Laravel Version

v10.21.0

### Livewire Version

v3.0.1

### PHP Version

8.2.x

### Problem description

When we use a money mask to add a thousand separators to an input field the validation fails and says it must be a numeric input.

### Expected behavior

It must mask the value in the front end and return the unmasked value to the back end.

### Steps to reproduce

create a text input like this:
```php
                Forms\Components\TextInput::make('balance')
                    ->required()
                    ->integer()
                    ->mask(RawJs::make("\$money(\$input)"))
                    ->default(0),
```

then send a value like `1000000` and you encounter this error:
`The balance field must be a number.` while the input is actually a number just masked to have a thousand separators.

### Reproduction repository

https://github.com/ariaieboy/filament-mask-bug

**Comment by danharrin** [comment]
Nothing we can do about this, the validation doesn't allow characters like `$`, it's a browser thing

**Comment by ariaieboy** [comment]
> Nothing we can do about this; the validation doesn't allow characters like `$`, it's a browser thing

That's not a browser validation error.
The problem is that the Alpine masks the `1000000` into `1,000,000`, and the laravel validation does not accept `1,000,000` as an integer. 

We need a way to remove the thousand separator when the value passes to the backend.

In V2, the mask option didn't have this problem. Because the mask only applies in the front end, and the value that passes to the backend is the non-masked value.

**Comment by Akhmami** [comment]
@ariaieboy same issue, any solution about this?

**Comment by andrewdwallo** [comment]
@Akhmami Yes you have to not use numeric for validation, and then use a cast before saving to the database.

**Comment by ariaieboy** [comment]
> @Akhmami Yes you have to not use numeric for validation, and then use a cast before saving to the database.

Removing the validation is not a good idea. Besides the security problems, we can not use other laravel validation rules either.
for example, if I have 2 column, one of them must be bigger than the other one, and when I use that rule without the numeric validation, laravel compare them as 2 string instead of 2 integer.

I temporarily removed the mask from my project, but since I am working with big numbers in my application, I must have a thousand separators. 

1 dollar is equal to 500,000 rial over here so numbers can get big very soon 😄

**Comment by ariaieboy** [comment]
@andrewdwallo 
the simple solution would be mutating the user input before we pass it to the validation process etc.
but we don't have a hook for it in the input level.

you can hook into `beforeValidate()` in you create and edit page but that's not clean in my opinion.
we need a hook on input level so we can change the specific input before validation.

**Comment by andrewdwallo** [comment]
@ariaieboy Hey man, I'm definitely not disagreeing with you... I was just providing the solution I was told to use.

**Comment by ariaieboy** [comment]
@Akhmami until this issue get fixed you can use my [filament-currency](https://github.com/ariaieboy/filament-currency) package.

instead of `mask` just use `currencyMask`

**Comment by andrewdwallo** [comment]
@ariaieboy Does your package work with reactive states?

Such as the following:
```php
\Filament\Forms\Components\TextInput::make('money')
    ->currencyMask(static function (Forms\Get $get) {
            $currency_code = $get('currency_code');
            //...
    }
```

**Comment by ariaieboy** [comment]
@andrewdwallo No
This method does not do anything in the back-end. All magic happens in the front end.
It masks the input using alpinejs $money and returns the unmasked value to the backend.

```js
    {
        input:\$wire.{$applyStateBindingModifiers("\$entangle('{$statePath}')")},
        masked:'',
        init(){
            this.masked = this.input;
            \$watch('masked',()=>this.updateInput());
        },
        updateInput(){
            this.input = this.masked.replaceAll('$thousandSeparator','').replaceAll('$decimalSeparator','.');
        }
    }
```
it might not be the best solution, but it solves my problem for now.
you can customize the thousandSeparator, decimalSeparator, and the precision.

**Comment by sibdib** [comment]
I haven't actually looked through the source code, but I think I might have a solution. Having written that, Im not sure what the end goal is, so depending on that, you might want to [hydrate](https://filamentphp.com/docs/3.x/forms/advanced#field-hydration) or [dehydrate](https://filamentphp.com/docs/3.x/forms/advanced#field-dehydration). 
Dehydrate is the right way to go, because you can also perform validation on it before you store it in the DB. So, one of the ideas of Field Dehydration is to show the user modified/formatted data in the front-end, while storing untouched raw data in the DB, which is what you want I believe. 
I noticed you had some issues where Laravel Validation compares strings  instead of integers and it leads to false results. I believe I have that handled. Sorry for the drafted code, should be enough to get an idea:
```php
use Validator;
use Filament\Forms\Components\TextInput;

TextInput::make('balance')
    ->required()
//    ->numeric()
//    ->default(0) Dont need these 2 unless you do
    ->dehydrateStateUsing(function (string $state) {

//---------------------------------------------------------------------
//      Validation idea 1 -> double safety, handles numeric string. The if-else is useless
        $moneyVal = intval($state);
        if(is_numeric($moneyVal)) $money = (int)$moneyVal;
        else $money = 0;
//      <Function to store $money in the DB>
//---------------------------------------------------------------------
//---------------------------------------------------------------------
//      Validation idea 2 -> simple validator
        $validator = Validator::make(['balance' => $money], [
            'balance' => 'numeric',
        ]);
        if ($validator->fails()) {
            //Handle
        }else {
            //Store $money in DB as its the raw value
        }
//---------------------------------------------------------------------
//      Basically return a modified $state
        return $this->_addThousandComma($money);
    })

private function _addThousandComma($value) : int
{
    $formatter = new NumberFormatter('en_US', NumberFormatter::CURRENCY);
    return $formatter->formatCurrency($value, 'USD'); //return the modified value of $state to the user
}
```
Please let me know If you have tried anything and if it worked.

**Comment by ariaieboy** [comment]
@sibdib I've created a small package called [filament-currency](https://github.com/ariaieboy/filament-currency) that you can fix this problem using it.

**Comment by sibdib** [comment]
Im really interested in learning more about De/Hydration in Filament, seems like a very cool thing. Since there arent many examples, I have to figure it out on my own.

**Comment by sibdib** [comment]
Oh, wait, you're the author, lol. Did you figure out what the issue was?

**Comment by ariaieboy** [comment]
@sibdib 
I explained the problem in the comments above, but In short, the problem here is that the Alpinejs mask method changes the input value to the masked version. 
For example, if you enter the number `4000`, it changes it to `4,000.00`, and it returns to the backend as a string instead of a number value. The problem is much, much worse when you use custom thousand and decimal separators based on your currency.

My package does a simple job. I separate the actual value from the masked value in the front end, so when you start typing, the mask value will show up in the field, but the value that will return to the backend is the actual number. 

Nothing has to change on the backend side. The front end must return the values in the correct format.

**Comment by mokhosh** [comment]
@danharrin I'm trying to use `dehydrateStateUsing` to remove commas from the string and turn it into a numeric value before it's validated, but seems like dehydration is not happening before validation.

If we could dehydrate before validation we could easily solve this issue like this:
```php
Forms\Components\TextInput::make('price')
    ->numeric()
    ->dehydrateStateUsing(fn ($state) => floatval(str_replace(',', '', $state)))
    ->mask(RawJs::make('$money($input)')),
```

**Comment by danharrin** [comment]
Fixed by #10092 when you use `stripCharacters()`

**Comment by danielschweiger** [comment]
`TextInput::make('amount')
                    ->mask(RawJs::make(<<<'JS'
                        $money($input, ',', '.')
                        JS))`

how can I do when I use the comma as thousend seperator and the dot as comma seperator?

**Comment by danharrin** [comment]
```php
->stripCharacters('.')
->mutateStateForValidationUsing(fn ($state) => str_replace(',', '.', $state))
->mutateDehydratedStateUsing(fn ($state) => str_replace(',', '.', $state))
```

**Comment by Youssef-Amjad** [comment]
> Nothing we can do about this, the validation doesn't allow characters like `$`, it's a browser thing

I have a question: why isn't `maxValue` implemented so that when used with `->mask(RawJs::make('$money($input)'))`, the `maxValue` value isn't exceeded? This would make it more logical. If it's not included, is there a way to implement this logic?
