### ISSUE TITLE
Error testing view page that has notification

### ISSUE THREAD

**Issue by damms005** [laravel-filament/filament#8256]
### Package

filament/notifications

### Package Version

v3.0.39

### Laravel Version

v10.21.0

### Livewire Version

v3.0.1

### PHP Version

PHP 8.1.23

### Problem description

I believe this is similar to #7609, but now with a reproduction URL at https://github.com/damms005/example-app/tree/bug/filament-notification

Briefly, error is thrown when testing a view that has notification, with message:
```
Property [$paginators] not found on component: [filament.livewire.notifications]
```

### Expected behavior

The test should pass

### Steps to reproduce

- Clone the repo https://github.com/damms005/example-app
- Checkout the `bug/filament-notification` branch
- `composer install`
- Run test `php artisan test tests/Feature/GetRoutesSmoketTest.php`

See error similar to:
```
Property [$paginators] not found on component: [filament.livewire.notifications]
```

### Reproduction repository

https://github.com/damms005/example-app/tree/bug/filament-notification

**Comment by alexmanase** [comment]
Do you still have the problem? I just cloned the repo and ran the tests and it worked for me.

**Comment by danharrin** [comment]
Seems like a LW bug that has now been resolved, the test passes on the latest version
