### ISSUE TITLE
Error testing custom rule

### ISSUE THREAD

**Issue by damms005** [laravel-filament/filament#8259]
### Package

filament/filament

### Package Version

v3.0.39

### Laravel Version

v10.21.0

### Livewire Version

v3.0.1

### PHP Version

PHP 8.1

### Problem description

When writing test for a custom form input rule, an error similar to below is thrown:
```
Too few arguments to function Filament\Resources\Pages\ListRecords::form(), 0 passed in /home/damms005/code/websites/example-app/vendor/filament/actions/src/Concerns/InteractsWithActions.php on line 309 and exactly 1 expected
```

### Expected behavior

The test should pass without errors

### Steps to reproduce

- Clone the repo https://github.com/damms005/example-app
- Checkout the `bug/filament-actions` branch
- `composer install`
- Run test `php artisan test tests/Feature/UserResourceTest.php`

You will see an error similar to below:
```
Too few arguments to function Filament\Resources\Pages\ListRecords::form(), 0 passed in /home/damms005/code/websites/example-app/vendor/filament/actions/src/Concerns/InteractsWithActions.php on line 309 and exactly 1 expected
```

### Reproduction repository

https://github.com/damms005/example-app/tree/bug/filament-actions

**Comment by danharrin** [comment]
You need to use the action assertions and not the form assertions

```
it('rejects bad names', function () {
    Livewire::test(ManageUsers::class)
        ->callAction(CreateAction::class, [
            'name' => 'bad',
            'email' => 'test@mail.com',
            'password' => 'password',
        ])
        ->assertHasNoActionErrors(['name']);
});
```
