### ISSUE TITLE
Select Field not returns expected titleAttribute 

### ISSUE THREAD

**Issue by shafiqruslan** [laravel-filament/filament#8288]
### Package

filament/filament

### Package Version

v3.0.39

### Laravel Version

v10.22.0

### PHP Version

PHP 8.24

### Problem description

I found the bug where Select Field did not returns the expected titleAttribute, it returns default column id. 

```
$form->schema([
                Forms\Components\Select::make('parking_id')
                    ->searchable()
                    ->relationship(
                        name:'parking',
                        titleAttribute: 'name',
                        modifyQueryUsing: fn (Builder $query) => $query->where('type', 'reserved')->where('status', 'available'),
                    ),
            ]);
```

### Expected behavior

return the expected titleAttribute

### Steps to reproduce

It only happens when i use third parameter 'modifyQueryUsing' in Select Field.

### Reproduction repository

https://gist.github.com/shafiqruslan/a2956712706fde1f2d950802e97038db

**Comment by kirkita** [comment]
Actually bug exists,  but only when form operation is view
