### ISSUE TITLE
v3, FiltersLayout::AboveContent doesn't manage columns anymore

### ISSUE THREAD

**Issue by Eighke** [laravel-filament/filament#8299]
### Package

filament/filament

### Package Version

v3.0.39

### Laravel Version

v10

### PHP Version

PHP 8.2

### Problem description

On a table, when the Layout is setup to `FiltersLayout::AboveContent`, it doesn't manage the Column as in the v2 but only show a single column.

I checked on `\Filament\Tables\Table\Concerns\HasFilters::getFiltersFormColumns()`  how it was implemented, and noticed the code is still here.

```php
        return $this->evaluate($this->filtersFormColumns) ?? match ($this->getFiltersLayout()) {
            FiltersLayout::AboveContent, FiltersLayout::BelowContent => [
                'sm' => 2,
                'lg' => 3,
                'xl' => 4,
                '2xl' => 5,
            ],
            default => 1,
        };
```

Currently the only problem is that `this->evaluate($this->filtersFormColumns)` will always return something (1 but default)

```php
    protected int | array | Closure $filtersFormColumns = 1;
```

---

At the moment the only way to make the columns as they were before is either to add them manually

```php
$table->filtersFormColumns([
    'sm' => 2,
    'lg' => 3,
    'xl' => 4,
    '2xl' => 5,
])
```

Or to use an ano function to setup the columns to null~

```php
$table->filtersFormColumns(fn () => null)
```

### Expected behavior

Having the columns automatically when using `FiltersLayout::AboveContent` or at least being able to setup `filtersFormColumns` to null.

PS: If the good behaviour is to do it manually, the code inside `getFiltersFormColumns` should probably be removed.

### Steps to reproduce

```php
    public static function table(Table $table): Table
    {
        return $table
            ->filters([
                TernaryFilter::make('foo'),
                TernaryFilter::make('bar'),
            ], FiltersLayout::AboveContent);
    }
```

### Reproduction repository

https://github.com/Eighke/debug

**Comment by danharrin** [comment]
So is the fix here to change that line to `protected int | array | Closure | null $filtersFormColumns = null;` so it uses the default?

**Comment by danharrin** [comment]
If so, please submit a PR :)

**Comment by Eighke** [comment]
Guess I was too slow :D

Thanks for the fix :)
