### ISSUE TITLE
Dependent toggle erratic behaviour

### ISSUE THREAD

**Issue by molcsab** [laravel-filament/filament#831]
### Package

filament/forms

### Package Version

v2.5.17

### Laravel Version

v8.65

### Livewire Version

v2.8.2

### PHP Version

PHP 8.0.13

### Bug description

When a reactive toggle has dependent fields the default value is not filled and after a few status changes starts to behave erratically.
![dependent-toggle](https://user-images.githubusercontent.com/513356/145748385-8532f073-a5d0-4881-a1de-44242a73df61.gif)

### Steps to reproduce

```php
Toggle::make('toggle1')
  ->reactive()
  ->default(true),
Toggle::make('toggle2')
  ->hidden(fn (callable $get) => $get('toggle1') == false)
  ->default(true),
TextInput::make('TestInput')
  ->label('Test')
  ->default('Default content')
  ->hidden(fn (callable $get) => $get('toggle1') == false)
  ->required(),
```

**Comment by danharrin** [comment]
I can replicate this, all your issues are solved if you use `===` instead of `==` :)

https://user-images.githubusercontent.com/41773797/146691836-7f691f50-cb34-41eb-bcf5-7fb40bfe48cf.mov
