### ISSUE TITLE
Route [filament.app.auth.logout] not defined when ->path('')

### ISSUE THREAD

**Issue by django23** [laravel-filament/filament#8349]
### Package

filament/filament

### Package Version

v3.0.40

### Laravel Version

v10.22

### Livewire Version

v3.0.2

### PHP Version

PHP 8.2

### Problem description

When following the instruction to remove the path 'admin' to make the page available at '' it seems the route for logout is not defined.

I have installed Laravel with --teams

![CleanShot 2023-09-08 at 16 54 50](https://github.com/filamentphp/filament/assets/827397/c8d2cd03-884a-4599-954d-0be67eda983b)

### Expected behavior

That the route was accessible

### Steps to reproduce

- Checkout the project
- Update your .env for database credentials
- Run `php artisan migrate:fresh --seed`
- Run `npm run dev`
- Run your php server (Herd in my case)
- Open a browser

Or

In ```AdmiPanelProvider```

Upddate:

```
return $panel
            ->default()
            ->id('app')
            **->path('')**
```

### Reproduction repository

https://github.com/django23/FilamentRouteMissing

**Comment by danharrin** [comment]
It's Jetstream, it has a route with the same path

**Comment by gexcube** [comment]
Route [filament.app.auth.profile] not defined as well

**Comment by 0sloft** [comment]
just comment line at route /logout at the route/auth.php

**Comment by django23** [comment]
Thanks for everyone's help. Should I create a PR for the documentation to add this info? Or is this to much of a corner case?

**Comment by JayteeNZ** [comment]
So whatever happened with this? Was it a bug or?

On a fresh L10 install with Filament v3: Have installed Fortify but not Jetstream or Breeze and receiving this same error straight off the bat.

Cheers

**Comment by danharrin** [comment]
Send the output of `artisan route:list`

**Comment by JayteeNZ** [comment]
I ended up creating my own solution to work with Fortify, however:

Route list was fine, except logout. Occasionally I'd have a login error too.

Isolated it down to panels that have the ``->path('')`` or ``->path('/')``. Setting a normal path name causes no issues.

**Comment by danharrin** [comment]
So you have Fortify installed? Laravel wont let you register routes with the same paths

**Comment by JayteeNZ** [comment]
Yep Fortify is installed.

Yep I know, still had errors (even with disabling Fortify views and running own routes with filament route names).

Only seems to play up with panels that have no prefix for the path.

Have since extended and created my own Livewire classes for ``->login()`` etc.

When I can be bothered, I'll boot up a test app and nail down the issue a little better, I'm having enough headaches as it is with the docs.

**Comment by danharrin** [comment]
Yes, the path controls where Filament registers its routes. Like its logout route. {path}/logout, and when the path is empty it will clash with Fortify.

Its not a bug, you just dont really need to use Fortify when you use Filament

**Comment by JayteeNZ** [comment]
I'm pretty sure it's a bug mate.

I've spun something up. Prefix is /app (was previously only failing with /)

Fortify is installed, views are registered separately to filament login, and yet the issue still occurs.

^ As in, both Fortify login routes and filament login routes are registered without clashing

```
GET|HEAD   app .................................................... filament.app.pages.dashboard › Filament\Pages › Dashboard
GET|HEAD   app/login ........................................... filament.app.pages.login › App\Filament\App\Pages\Auth\Login
POST       app/logout ........................................... filament.app.auth.logout › Filament\Http › LogoutController
```

```
GET|HEAD   login ............................................ login › Laravel\Fortify › AuthenticatedSessionController@create
POST       login ..................................................... Laravel\Fortify › AuthenticatedSessionController@store
POST       logout ......................................... logout › Laravel\Fortify › AuthenticatedSessionController@destroy
GET|HEAD   register ............................................ register › Laravel\Fortify › RegisteredUserController@create
POST       register ........................................................ Laravel\Fortify › RegisteredUserController@store
POST       reset-password ................................... password.update › Laravel\Fortify › NewPasswordController@store
GET|HEAD   reset-password/{token} ........................... password.reset › Laravel\Fortify › NewPasswordController@create
GET|HEAD   sanctum/csrf-cookie ............................ sanctum.csrf-cookie › Laravel\Sanctum › CsrfCookieController@show
GET|HEAD   user/confirm-password ....................................... Laravel\Fortify › ConfirmablePasswordController@show
POST       user/confirm-password ................... password.confirm › Laravel\Fortify › ConfirmablePasswordController@store
  GET|HEAD   user/confirmed-password-status .. password.confirmation › Laravel\Fortify › ConfirmedPasswordStatusController@show
```

Error that occurs:

```
Route [filament.app.auth.login] not defined.

```

2. I'm using Fortify for two reasons: I need to pair it with Sanctum later down the line for some complex auth that I want to swap out, alongside API access, but most importantly: I'm using it because Filament updates like it's in alpha and shit is always breaking or unintended. Working with the docs is painful enough.

**Comment by JayteeNZ** [comment]
> I'm pretty sure it's a bug mate.
> 
> 
> 
> I've spun something up. Prefix is /app (was previously only failing with /)
> 
> 
> 
> Fortify is installed, views are registered separately to filament login, and yet the issue still occurs.
> 
> 
> 
> ^ As in, both Fortify login routes and filament login routes are registered without clashing
> 
> 
> 
> ```
> 
> GET|HEAD   app .................................................... filament.app.pages.dashboard › Filament\Pages › Dashboard
> 
> GET|HEAD   app/login ........................................... filament.app.pages.login › App\Filament\App\Pages\Auth\Login
> 
> POST       app/logout ........................................... filament.app.auth.logout › Filament\Http › LogoutController
> 
> ```
> 
> 
> 
> ```
> 
> GET|HEAD   login ............................................ login › Laravel\Fortify › AuthenticatedSessionController@create
> 
> POST       login ..................................................... Laravel\Fortify › AuthenticatedSessionController@store
> 
> POST       logout ......................................... logout › Laravel\Fortify › AuthenticatedSessionController@destroy
> 
> GET|HEAD   register ............................................ register › Laravel\Fortify › RegisteredUserController@create
> 
> POST       register ........................................................ Laravel\Fortify › RegisteredUserController@store
> 
> POST       reset-password ................................... password.update › Laravel\Fortify › NewPasswordController@store
> 
> GET|HEAD   reset-password/{token} ........................... password.reset › Laravel\Fortify › NewPasswordController@create
> 
> GET|HEAD   sanctum/csrf-cookie ............................ sanctum.csrf-cookie › Laravel\Sanctum › CsrfCookieController@show
> 
> GET|HEAD   user/confirm-password ....................................... Laravel\Fortify › ConfirmablePasswordController@show
> 
> POST       user/confirm-password ................... password.confirm › Laravel\Fortify › ConfirmablePasswordController@store
> 
>   GET|HEAD   user/confirmed-password-status .. password.confirmation › Laravel\Fortify › ConfirmedPasswordStatusController@show
> 
> ```
> 
> 
> 
> Error that occurs:
> 
> 
> 
> ```
> 
> Route [filament.app.auth.login] not defined.
> 
> 
> 
> ```
> 
> 
> 
> 2. I'm using Fortify for two reasons: I need to pair it with Sanctum later down the line for some complex auth that I want to swap out, alongside API access, but most importantly: I'm using it because Filament updates like it's in alpha and shit is always breaking or unintended. Working with the docs is painful enough.
> 
> 
> 
> 

I've just clicked, seems to be independent of panels as it's moaning about filament.app.auth.login instead of filament.app.pages.login,

So what's the deal there? Where does filament.app.auth.login come from?

P.S: On phone for this response, hence formatting.

**Comment by danharrin** [comment]
By default, the Filament path is `/admin`
- Filament registers /admin/login
- Filament registers /admin/logout

You change the Filament path to `/`
- Filament now registers /login instead
- Filament now registers /logout instead

You install Fortify
- Fortify also registers /login
- Fortify also registers /logout

How is this a bug in Filament? Laravel will not register multiple routes with the same path. The error `Route [filament.app.auth.login] not defined.` is because Laravel does not register Filament's route.

Even if you don't want to remove Fortify, you should disable Fortify's login and logout routes, so they don't overwrite Filament's. You shouldn't have a problem after that.

Also, there is no need for the passive aggressive side comments about our updates or stability. Do you think that's what maintainers want to read when we're helping you in our spare time?

**Comment by gator92** [comment]
If you're using another auth provider, one solution is to rename your logout route to 'filament.admin.auth.logout'. However, this seems a little hackish. If another guard is set, ie authGuard('my-guard') and login() not included, why would the panel still use the builtin filament logout? This really does look like a bug and doesn't seem like it would be difficult to remediate. It's just a matter of considering the case where the application does not use Filaments built-in auth.

**Comment by yakou32** [comment]
Hey!

I'm basically trying to put Filament at the root.

What I did so far was: 
  - Comment out the default Laravel routes from `/routes/web.php`
  - Comment out the default routes from `/routes/auth.php`
  - Update the path from `/admin` to `/` in `app/Providers/Filament/AdminPanelProvider.php`
  - Update the Home const from `/dashboard` to `/` in `app/Providers/RouteServiceProvider.php`
  
  This works quite well for most of the pages.
  However, some lead to 404 errors, such as `register` and likely `forgot-password`, `reset-password`.
  Therefore, I cannot move the project online yet, having issues to create new users...
  
Do I miss something?
  
If you agree, I think it would make sense to have the answer as part of the documentation, for people who want to use Filament as a standalone feature of their Laravel project, therefore located at the root url. 

Thanks for your help!!!

**Comment by LukasCCB** [comment]
I had the same problem and managed to solve it. Filament running at the root.

Laravel 11, Filament, Fortify.

I basically went to `config/fortify.php` and in prefix I added anything.

`'prefix' => 'fort',`

**Comment by FabianoLothor** [comment]
This is annoying.

I'm not using fortify, though I'm getting the same error:

```
$ php artisan route:list | grep login
  GET|HEAD   app/login ................................................................................................................................................................................................. filament.app.auth.login › Filament\Auth › Login
```

```
            ->navigationItems([
                NavigationItem::make('Login')->url(route('filament.app.auth.login')),
            ])
```

Same error: `Route [filament.app.auth.login] not defined.`

That's my sad workaround:

```
            ->navigationItems([
                NavigationItem::make('Login')->url('app/login'),
            ])
```

Appreciate any suggestion of how to adjust this using `route`.

**Comment by xcopy** [comment]
FYI, setting `$panel->domain(config('app.url'))` fixed the issue.
