### ISSUE TITLE
Unwanted space between link Blade component and punctuation

### ISSUE THREAD

**Issue by emmadesilva** [laravel-filament/filament#8352]
### Package

filament/filament

### Package Version

v3.0.41

### Laravel Version

10.22.0

### Livewire Version

v3.0.2

### PHP Version

8.2.10

### Problem description

When using the Filament link component a space in the output HTML is added, which looks very clunky when followed by punctuation. I suspect this is due to a newline in the output?

I am not going to make a reproduction repository for this since it can be reproduced with a single line of code so I don't think I would save anyone's time by creating one.

By the way, a `php artisan filament:diagnose` command to print all the versions for the bug report would be really nice IMO. What do you think? Should I make an issue/PR?

### Expected behavior

A link gets rendered like this:

There will be a space after this link !

When this is expected:

There will be a space after this link!

![laravel test_](https://github.com/filamentphp/filament/assets/95144705/2ab6498e-0ead-4b85-88b4-30cf283ff00e)

### Steps to reproduce

Use the following Blade snippet:

```blade
<p>
    There will be a space after this <x-filament::link>link</x-filament::link>!
</p>
```

### Reproduction repository

https://github.com/caendesilva/filament-bug-repro

**Comment by emmadesilva** [comment]
I don't think it's beneficial for anyone's time to create a repro repo for a single line of code...

**Comment by andcarpi** [comment]
Probably a Laravel Blade issue.
The readability would get worst, but could be solved removing the line break in link.blade.php line 139 
![image](https://github.com/filamentphp/filament/assets/13441557/cfb2ff3f-761a-4dba-8082-3ee75c6fffb5)
to
![image](https://github.com/filamentphp/filament/assets/13441557/345911f6-e5b8-4fed-b54e-ab263229f90e)

**Comment by emmadesilva** [comment]
> Probably a Laravel Blade issue. The readability would get worst, but could be solved removing the line break in link.blade.php line 139 

Yeah I think this is the cause too. In my opinion, the rendered result should come before the source code readability in this case, as this is a limitation within Blade and I don't see another way around it than sacrificing source code readability, though someone else might.

**Comment by zepfietje** [comment]
This is a limitation with Blade indeed.
@caendesilva, can you confirm the fix @andcarpi suggested also works for links using the `<button>` tag?

As far as I know, I haven't been able to find a fix for this issue in the past.

**Comment by zepfietje** [comment]
I'm going to close this issue, as it's a limitation with Blade and there hasn't been any activity since my last reply.

Feel free to work on this if you can.

**Comment by emmadesilva** [comment]
Sorry, I missed the ping. Currently out of town but will try it when I get back if I remember!

**Comment by zepfietje** [comment]
Alright, no worries.
Will reopen and assign it to you, if that's ok with you, @caendesilva.

**Comment by emmadesilva** [comment]
> This is a limitation with Blade indeed. @caendesilva, can you confirm the fix @andcarpi suggested also works for links using the `<button>` tag?
> 
> As far as I know, I haven't been able to find a fix for this issue in the past.

I can confirm the fix works, however it needs to be applied in more places. Browsers (or at the very least, Chrome) renders source code newlines as (a single) whitespace. So there must be no newlines between the `{{ $slot }}` and the closing `</a>`/`</button>` tag. 

So for example, this works: (As the code enclosed in Blade conditional directives are not rendered in my repro as the badge is not filled)

```blade
{{ $slot }}@if (filled($badge))
  // ...
@endif</a>@elseif ($tag === 'button')
```

But this does not:

```blade
{{ $slot }}
@if (filled($badge))
    // ...
@endif
</a>
```

Ideally, this would be fixed upstream in Laravel, but as it is now, I personally would think it's worth having a patch in Filament for this as I feel that the issue sadly makes websites made with Filament look less professional, which is of course highly regrettable.

**Comment by zepfietje** [comment]
Thanks for looking into this, @caendesilva!
Could you create a PR with above fix, so we can see how messed up the source code will have to be? 😅

**Comment by emmadesilva** [comment]
> Thanks for looking into this, @caendesilva! Could you create a PR with above fix, so we can see how messed up the source code will have to be? 😅

Sure, no problem. How big of a scope should the PR be? Should I limit it to just the most common link options or try to apply it to all conditional paths in the component?

**Comment by zepfietje** [comment]
Ideally all cases should be covered, as it's only going to be more of a nightmare if only some are supported I think. But feel free to tackle the parts you think are doable and start a discussion on the PR if you think something is not worth it.

**Comment by emmadesilva** [comment]
Okay cool! Just want to make sure I don't break things. I'll take a look
during the week! Super swamped with school this weekend.

**Comment by emmadesilva** [comment]
> Ideally all cases should be covered, as it's only going to be more of a nightmare if only some are supported I think. But feel free to tackle the parts you think are doable and start a discussion on the PR if you think something is not worth it.

@zepfietje I've been playing around with this and I honestly can't fix this in the Blade view in a way that doesn't completely mangle it. 

So let's talk alternatives?

I don't know if it's possible, but maybe if using a class based component we could override the Blade view loading mechanism to apply the needed transformations there, instead of in the source code?

Or we could supply a CSS class that has the same styles. My original problem in was that I wanted a simple `<a>` link styled the same way as other Filament links. A `.filament-link` class would suffice, and we could add a test that ensures the class is up to date with any changes made to the Blade file.

**Comment by zepfietje** [comment]
Best is probably to fix this in Laravel if possible?

Having a CSS class for links doesn't solve the cases where you're using Filament actions, so I wouldn't go that route as it's not a complete fix.

**Comment by emmadesilva** [comment]
> Best is probably to fix this in Laravel if possible?

Probably..

> Having a CSS class for links doesn't solve the cases where you're using Filament actions

In my case I just wanted a link within a custom view (the make:filament-page kind)
