### ISSUE TITLE
$set in afterStateUpdated on select with scoped relationship not working in v3

### ISSUE THREAD

**Issue by elifenceflow** [laravel-filament/filament#8368]
### Package

filament/filament

### Package Version

3.0.42

### Laravel Version

10.22.0

### PHP Version

8.2.9

### Problem description

I'm trying to set the property select to the customer's first property when a customer is selected. This worked in v2 but doesn't work in v3.

The issue is the where clause on the property select to scope the options to the selected customer. This isn't updated before the $set is called, so the select doesn't have the correct options.

```
Select::make('customer_id')
    ->relationship(
        'customer',
        'name',
        modifyQueryUsing: fn (Builder $query) => $query->whereBelongsTo(Filament::getTenant()))
    ->searchable()
    ->afterStateUpdated(function (Set $set, ?string $state) {
        $set('property_id', Customer::find($state)?->properties()->first()?->id);
    })
    ->required()
    ->reactive(),
Select::make('property_id')
    ->relationship('property', 'address_formatted',
        function (Builder $query, Get $get) {
            return $query->where('customer_id', $get('customer_id'));
        }
    )
    ->required(),
```

### Expected behavior

The property select should update when the customer select is updated.

### Steps to reproduce

Clone the reproduction repository. Create a new customer and property. Visit /admin/estimates/create and select a customer. The property should change to that customer's first property, but it doesn't. The relevant code is in app/Filament/Resources/EstimateResource.php.

### Reproduction repository

https://github.com/eorenstein1/filament-set-reproduction

**Comment by richhuth** [comment]
Had a similar issue, but was able to fix it by adding: 
`->live(debounce: 50)`

**Comment by danharrin** [comment]
This is a Livewire bug. Livewire is updating the options for the second select after the value has been updated. This is too late.

You can bypass Livewire by using a searchable select. You can do this by adding `native(false)` or `searchable()` onto the second select.

**Comment by danharrin** [comment]
See Livewire issue to track this bug: livewire/livewire#6984

**Comment by geccatta** [comment]
Had the same problem and I have been trying to fix it for 3 days, thank you so much!
