### ISSUE TITLE
Repeater reorderable

### ISSUE THREAD

**Issue by datlechin** [laravel-filament/filament#8370]
### Package

filament/filament

### Package Version

v3.0.42

### Laravel Version

v10.22.0

### Livewire Version

v3.0.2

### PHP Version

PHP 8.2.9

## Issue 1: Simple Repeater Duplicates Field

When using a simple Repeater and rearranging the order of the fields, the field is duplicated.

```php
Repeater::make('repeaters')
    ->relationship('repeaters')
    ->reorderable()
    ->simple(
        Forms\Components\TextInput::make('text')
            ->string()
            ->required(),
    ),
```

https://github.com/filamentphp/filament/assets/56961917/b56a5bbc-8e2d-4b24-8407-dadd2bde8521

## Issue 2: Classic Repeater Throws Error when Reordering

When using a classic Repeater and rearranging the order of the fields, an error occurs:

```
Filament\Forms\ComponentContainer::getRawState(): Return value must be of type Illuminate\Contracts\Support\Arrayable|array, int returned
```

```php
Repeater::make('faqs')
    ->relationship('faqs')
    ->hiddenLabel()
    ->reorderable()
    ->schema([
        Forms\Components\TextInput::make('question')
            ->string()
            ->required(),

        Forms\Components\TextInput::make('answer')
            ->string()
            ->required(),
    ])
```

https://github.com/filamentphp/filament/assets/56961917/db668401-a619-4213-a2bc-bf8b9043488a

### Expected behavior

works

### Steps to reproduce

1. Clone the reproduction repository.
2. Run the application.
3. Navigate to `/shop/products/create`.
4. In the `FAQs/Repeaters` section, click on **Add to...** to create a new FAQ/Repeater.
5. Add multiple fields
6. Try reordering the fields

### Reproduction repository

https://github.com/datlechin/filament-repeater-reorder-issues

**Comment by danharrin** [comment]
Was issue 2 introduced today or was it present in the last release also?

**Comment by datlechin** [comment]
These issues are present in Filament version v3.0.42

**Comment by danharrin** [comment]
Yes, but were they in .41 or .40

**Comment by peter-mw** [comment]
I have the same issue

**Comment by ali-arnoos** [comment]
Fixed the issue by using `(string) Str::uuid()`  as an array key to the updated repeater array.

Example code:

```
        $itemsArray = $items->toArray();
        $updatedItems = [];

        foreach ($updatedItems as $item) {
            $key = (string) \Illuminate\Support\Str::uuid();
            $updatedItems[$key] = $item;
        }
```

I use the result of the above code to set the form state with `$set('items', $items);`

**Comment by citricguy** [comment]
Can confirm, and @ali-arnoos method works!

```php
->afterStateUpdated(function ($state, $set) {
    if (is_array($state)) {
        // Create a new array with UUID keys for each item
        $updatedItems = [];
        foreach ($state as $item) {
            if (is_array($item)) {
                $key = (string) Str::uuid();
                $updatedItems[$key] = $item;
            }
        }
        // Only update if we have items
        if (!empty($updatedItems)) {
            $set('tagline_select_options', $updatedItems);
        } else {
            // Fallback to array_values for empty or corrupted state
            $set('tagline_select_options', array_values($state));
        }
    } else {
        // Handle case where $state isn't an array (corrupted state)
        $set('tagline_select_options', []);
    }
})
```

**Comment by mikemeijer** [comment]
I also had problem with ordering (issue 2) related to the Repeater in Filament 3.X. Fixed it by adding `record-` prefix to the state keys. 

```php
->afterStateHydrated(function (Forms\Components\Repeater $component, $state, $record) {
    if (! $record) {
        return;
    }

    $fields = $record->fields
        ->sortBy('order')
        ->mapWithKeys(function ($field) {
            return ['record-' . $field->id => [
                'id' => $field->id,
                'label' => $field->label,
                'name' => $field->name,
                'type' => $field->type,
                'options' => $field->options,
                'required' => $field->required,
                'order' => $field->order,
            ]];
        })->toArray();

    $component->state($fields);
}),
```
