### ISSUE TITLE
Array to string conversion when using spatie tags

### ISSUE THREAD

**Issue by tim-frensch** [laravel-filament/filament#8411]
### Package

filament/filament

### Package Version

v3.0.47

### Laravel Version

v10.10

### Livewire Version

v3.0.2

### PHP Version

PHP 8.10

### Problem description

When you try to add tags using the spatieTagsInput to any resource there's a string to array conversion error. This worked fine on 3.0.40. Updated a project today and it didn't work anymore.

### Expected behavior

A tag to be assigned to the resource.

### Steps to reproduce

Try to add a tag to the user resource in the example project.

### Reproduction repository

https://github.com/Tim-Frensch/filament-tags-bug

**Comment by lorlab** [comment]
I can confirm this also happens to me

**Comment by sairiz** [comment]
I tried the fix. Apparently it only works when the model doesnt have any tags. 

1. If it already has, and new tags were to be saved, it will throw SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry
2. If it already has and some of the tags removed and were to be saved, it will throw SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry
3. If it already has and all of the tags removed and were to be saved, no error thrown but the tags doesnt get removed.
