### ISSUE TITLE
Multitenancy selector on topNavigation

### ISSUE THREAD

**Issue by jean-triches** [laravel-filament/filament#8413]
### Package

filament/filament

### Package Version

v3.0.0

### Laravel Version

v10

### PHP Version

PHP 8.2.4

### Problem description

Multitenancy selector not showing on ->topNavigation()

### Expected behavior

to show the selector

### Steps to reproduce

1 - implements multitenancy 
2 - set ->topNavigation() on AdminPanelProvider

### Reproduction repository

https://github.com/jean-triches/mt

### Relevant log output

```shell
none other
```

**Comment by danharrin** [comment]
Upgrade Filament.
