### ISSUE TITLE
ToggleColum onIcon and offIcon visual bug

### ISSUE THREAD

**Issue by Khal-ID** [laravel-filament/filament#8430]
### Package

filament/tables

### Package Version

v3.0.47

### Laravel Version

v10.22.0

### Livewire Version

v3.0.3

### PHP Version

PHP 8.2.9

### Problem description

Visual bug when using

```
Tables\Columns\ToggleColumn::make('is_featured')
   ->onIcon('heroicon-m-check')
   ->offIcon('heroicon-m-x-mark'),
```

![Screenshot](https://github.com/filamentphp/filament/assets/3290848/2f67016b-c76e-470b-8aac-c81387fd667e)

### Expected behavior

Same as in Forms Components, the icons looks centered.

```
Forms\Components\Toggle::make('is_featured')
    ->onIcon('heroicon-m-check')
    ->offIcon('heroicon-m-x-mark'),
```
![Screenshot 1](https://github.com/filamentphp/filament/assets/3290848/eb1c564e-3c34-4a78-b990-03a04b8bf50b)

![Screenshot 2](https://github.com/filamentphp/filament/assets/3290848/70be79db-36d2-48da-b40a-5c9010505767)

### Steps to reproduce

In any resource that has a boolean field, use the ToggleColumn in tables, for example:

```
Tables\Columns\ToggleColumn::make('is_admin')
   ->onIcon('heroicon-m-check')
   ->offIcon('heroicon-m-x-mark'),
```

### Reproduction repository

https://github.com/Khal-ID/khalid

**Comment by danharrin** [comment]
#8436
