### ISSUE TITLE
Unable to set default `emptyStateDescription`

### ISSUE THREAD

**Issue by billmn** [laravel-filament/filament#8437]
### Package

filament/tables

### Package Version

v3.0.47

### Laravel Version

v10.22.0

### PHP Version

PHP 8.2

### Problem description

I have tried to set the default table *empty state description* using:

```php
Table::configureUsing(function (Table $table) {
    $table
        ->emptyStateHeading('Default heading') // <-- This works
        ->emptyStateDescription('Default description'); // <-- This doesn't work
});
```

But the description doesn't change (I haven't used the `emptyStateDescription` on the resource table)

### Expected behavior

If I set a default description for empty state I expect that empty tables show this description instead of the one provided by Filament

### Steps to reproduce

Add the code below in the AppServiceProvider and check the default description on empty tables.

```php
Table::configureUsing(function (Table $table) {
    $table
        ->emptyStateHeading('Default heading') // <-- This works
        ->emptyStateDescription('Default description'); // <-- This doesn't work
});
```

The heading should be "Default heading" but the description will not be "Default description"

### Reproduction repository

https://github.com/billmn/filament-issues

**Comment by danharrin** [comment]
Can you try submitting a PR?

**Comment by danharrin** [comment]
Try this:

```php
Table::configureUsing(function (Table $table) {
    $table
        ->emptyStateHeading('Default heading')
        ->emptyStateDescription('Default description');
}, isImportant: true);
```

**Comment by billmn** [comment]
@danharrin With `isImportant` parameter it works, thank you!

I was thinking whether it is correct to have to use this parameter to override the default description when it is not necessary for other properties (e.g. default heading, ...).

**Comment by danharrin** [comment]
Basically, it decides whether to run the configuration before or after the `setUp()`, if that makes sense.

**Comment by billmn** [comment]
Great, thank you for the clarification.

**Comment by billmn** [comment]
@danharrin I have found an issue using `isImportant` parameter.

I do not get the correct result using `$table->hasAction('create')` ... it always returns `false` (probably because is executed before `setUp()`).

Therefore, I cannot define the default description in case there is or is not an action.

**Comment by danharrin** [comment]
This is not an isImportant problem. You just need to pass in an additional function to emptyStateDescription() so it doesnt get evaluated too early.

**Comment by billmn** [comment]
Great suggestion, thank you
