### ISSUE TITLE
Identifier 'collapsedGroups' has already been declared - Console errors using new $panel->spa() method

### ISSUE THREAD

**Issue by CharlieEtienne** [laravel-filament/filament#8439]
### Package

filament/filament

### Package Version

v3.0.47

### Laravel Version

v10.22.0

### Livewire Version

v3.0.2

### PHP Version

PHP 8.1

### Problem description

Adding spa() method to the panel causes console error.

I think it comes from recently added `public/js/filament/tables/components/table.js`

### Expected behavior

No console error

### Steps to reproduce

```php
class AdminPanelProvider extends PanelProvider
{
    public function panel(Panel $panel): Panel
    {
        return $panel
            // [...]
            ->spa();
    }
}
```

then

`npm run dev`

### Reproduction repository

Private repo only, sorry

### Relevant log output

```shell
Uncaught SyntaxError: Identifier 'collapsedGroups' has already been declared
    at swapCurrentPageWithNewHtml (livewire.js?id=51f84ddf:5742:19)
    at livewire.js?id=51f84ddf:5895:11
    at preventAlpineFromPickingUpDomChanges (livewire.js?id=51f84ddf:5934:5)
    at livewire.js?id=51f84ddf:5893:9
    at prefetches.<computed>.whenFinished (livewire.js?id=51f84ddf:5537:9)
    at storeThePrefetchedHtmlForWhenALinkIsClicked (livewire.js?id=51f84ddf:5523:11)
    at livewire.js?id=51f84ddf:5879:11
    at livewire.js?id=51f84ddf:5516:7
```

**Comment by kedniko** [comment]
Having the same issue with 

```php
class AdminPanelProvider extends PanelProvider
{
    public function panel(Panel $panel): Panel
    {
        return $panel
            // [...]
            ->spa();
    }
}
```

**Comment by uwascan** [comment]
I have the same error. Removing the spa() method does not fix the bug. This error causes a cascade of other JavaScript errors.

**Comment by qzmenko** [comment]
Same for me, but only if SPA enabled.

**Comment by Nelh** [comment]
any timeline on when this issue will be fixed?

**Comment by MGeurts** [comment]
Same for me, also only if SPA enabled.

**Comment by alkoumi** [comment]
Same for me, but only if SPA enabled.

**Comment by abrahamgreyson** [comment]
Same issue here when I chained `spa()` method on Panel object, removed the `spa()` the issue gone.

**Comment by DannyV90** [comment]
Same here, only with `spa()`
