### ISSUE TITLE
Console errors with filaments components when using wire:navigate

### ISSUE THREAD

**Issue by tareq-alqadi** [laravel-filament/filament#8460]
### Package

filament/filament

### Package Version

v3

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

PHP 8.2

### Problem description

When i using a wire:navigate links the the errors happened as you can see in the following picture
![image](https://github.com/filamentphp/filament/assets/70425045/e2be71f3-08e9-40d6-9453-b8a8fef22aad)

I noticed this problem first time when i am working on my project, then i decide to create a fresh Laravel project with installing filament as it's described in the docs and use spa() method with create a filament user as it's described in docs.

when i login to admin panel and click the dashboard link in the sidebar the error in the previous picture thrown.

this is not the only error i faced similar problems with table and some form fields. 

### Expected behavior

It's supposed to navigate between pages without any error

### Steps to reproduce

Just create a new Laravel project, install filament and use spa() method

### Reproduction repository

https://github.com/tareq-alqadi/testNavigate.git

**Comment by yash-tiwari18** [comment]
In my case the spa() method doesn't exist on Filament\Panel.
I am getting this error Method Filament\Panel::spa does not exist.

**Comment by tareq-alqadi** [comment]
> In my case the spa() method doesn't exist on Filament\Panel. I am getting this error Method Filament\Panel::spa does not exist.

You need to update filament to latest version or at least to [v3.0.46](https://github.com/filamentphp/filament/releases/tag/v3.0.46)

**Comment by tabatii** [comment]
same problem

**Comment by franckdpt** [comment]
> ### Package
> filament/filament
> 
> ### Package Version
> v3
> 
> ### Laravel Version
> v10
> 
> ### Livewire Version
> v3
> 
> ### PHP Version
> PHP 8.2
> 
> ### Problem description
> When i using a wire:navigate links the the errors happened as you can see in the following picture ![image](https://user-images.githubusercontent.com/70425045/267733739-e2be71f3-08e9-40d6-9453-b8a8fef22aad.png)
> 
> I noticed this problem first time when i am working on my project, then i decide to create a fresh Laravel project with installing filament as it's described in the docs and use spa() method with create a filament user as it's described in docs.
> 
> when i login to admin panel and click the dashboard link in the sidebar the error in the previous picture thrown.
> 
> this is not the only error i faced similar problems with table and some form fields.
> 
> ### Expected behavior
> It's supposed to navigate between pages without any error
> 
> ### Steps to reproduce
> Just create a new Laravel project, install filament and use spa() method
> 
> ### Reproduction repository
> https://github.com/tareq-alqadi/testNavigate.git
> 
> ### Relevant log output
> _No response_

Same here

**Comment by gyaanesh** [comment]
I am too getting same errors in my console
![image](https://github.com/filamentphp/filament/assets/43063785/6e58597c-4b05-480c-a3d2-fd34073a122e)

**Comment by bytemewebdev** [comment]
I am experiencing this too, thats why I don't use the `->spa()` yet. Im still waiting for a fix about this issue

**Comment by tijsbakker** [comment]
I'm having the same problem when I navigate to a Livewire/Volt full-page component that has a Filament\Table on it …

<img width="1512" alt="Scherm­afbeelding 2023-10-14 om 10 46 40" src="https://github.com/filamentphp/filament/assets/3167757/fb7a05af-3c46-44aa-bfe6-aa0971202d5c">

**Comment by danharrin** [comment]
It's an Alpine/LW bug where global stores dont work, you can submit a failing test to Livewire to get it fixed, otherwise you will need to wait for me to find time to do the same thing

**Comment by tijsbakker** [comment]
Thanks @danharrin , unfortunately I'm not very familiar with writing failing tests and I also don't really see how the error is related to the global store (this is also used in the rest of the site but does not produce any errors) ... what I do see however is that table.js is called twice and the $wire object/component is only found on the second call. Could the error perhaps have something to do with the moment the script is called and/or the fact that this happens twice?

**Comment by danharrin** [comment]
collapsedGroups is a global store

**Comment by DanielSpravtsev** [comment]
> I'm having the same problem when I navigate to a Livewire/Volt full-page component that has a Filament\Table on it …
> 
> <img alt="Scherm­afbeelding 2023-10-14 om 10 46 40" width="1512" src="https://user-images.githubusercontent.com/3167757/275204157-fb7a05af-3c46-44aa-bfe6-aa0971202d5c.png">

Fixed as https://github.com/filamentphp/filament/pull/9151 
Update and check it

**Comment by danharrin** [comment]
The collapsible sidebar issue is probably still present

**Comment by danharrin** [comment]
Should be fixed.
