### ISSUE TITLE
TextColumn::make('myBigIntColumn')->searchable() on  with BigInteger value not working

### ISSUE THREAD

**Issue by edwink75** [laravel-filament/filament#8487]
### Package

filament/filament

### Package Version

3.0.46 (in lower versions like 3.0.8 the error does not exist)

### Laravel Version

V10.23.1

### Livewire Version

v3.0.3

### PHP Version

PHP 8.1

### Problem description

When using the tables search window the following error comes up.
Error message: 
`SQLSTATE[42883]: Undefined function: 7 ERROR: function lower(bigint) does not exist LINE 1: select count(*) as aggregate from "users" where (lower(myBigIntColumnName....`

### Expected behavior

Display search results

### Steps to reproduce

Install repo, 
use .env.sail as .env file
run vendor/bin/sail up 
Login with admin@admin.admin / password: admin 
http://localhost/admin/users
use search window in table

### Reproduction repository

https://github.com/edwink75/filament-issue-1

**Comment by danharrin** [comment]
Trying to not be rude here, but you're expecting us to fix an issue that you can't even reproduce yourself? Please submit a reproduction as we asked for it.

**Comment by edwink75** [comment]
@danharrin Repo and instructions added. I'm new here, so I don't know how detailed this needs to be.

**Comment by mariomka** [comment]
I have the same issue with a `timestamp` column:

```
ERROR: function lower(timestamp without time zone) does not exist...
```

**Comment by ShaungBhone** [comment]
What's the search window? I don't get it.

**Comment by gexcube** [comment]
This introduced a new bug when using `FilterableTagsColumn` with data stored in db as array column. Also using postgresql. (Filament version 3.0.84 is fine, version 3.0.85 throws error column tags::text not found).

**Comment by danharrin** [comment]
What is FilterableTagsColumn?
