### ISSUE TITLE
RelationManager DeleteAction Skips Confirmation

### ISSUE THREAD

**Issue by bobwurtz** [laravel-filament/filament#8505]
### Package

filament/filament

### Package Version

v3.0.50

### Laravel Version

v10.23.1

### PHP Version

PHP 8.2.8

### Problem description

The standard `Tables\Actions\DeleteAction` in a relation manager does not require confirmation when the `modalDescription` is null or empty unless `requiresConfirmation()` is used after it is applied.

### Expected behavior

The `DeleteAction` should require confirmation before deleting the record.

### Steps to reproduce

Create a resource and a relation manager. Add a related record to the resource. Customize the `modalDescription` of the `DeleteAction` to `null` or `''`. Delete a related record. It will not require confirmation.

View the `CommentsRelationManager` in the attached reproduction repository for a specific example.

### Reproduction repository

https://github.com/bobwurtz/filamentTesting

**Comment by danharrin** [comment]
This is deliberately a criteria that we look for when deciding whether or not to open a modal, otherwise modals would open in situations you wouldn't want them to (modal header alone is set automatically), the fix is to add some content there
