### ISSUE TITLE
Property [$table] not found on component on production

### ISSUE THREAD

**Issue by alexmanase** [laravel-filament/filament#8516]
### Package

filament/filament

### Package Version

V3.0.50

### Laravel Version

v10.23.1

### Livewire Version

v3.0.4

### PHP Version

PHP 8.2.0

### Problem description

I created a custom livewire component that contains a Filament Table (https://filamentphp.com/docs/3.x/tables/adding-a-table-to-a-livewire-component). On local the table is fine and works perfectly, but when I deploy it on a server it says:

```
Property [$table] not found on component: [list-seo-content]
```

### Expected behavior

It should successfully render the table.

### Steps to reproduce

I don't know how to reproduce it. I creating a basic Filament project, I deployed it and it worked.

### Reproduction repository

https://github.com/alexmanase/filament-table-rendering-issue-on-production

### Relevant log output

```shell
[2023-09-15 10:18:44] production.ERROR: Property [$table] not found on component: [list-seo-content] {"userId":1,"exception":"[object] (Livewire\\Exceptions\\PropertyNotFoundException(code: 0): Property [$table] not found on component: [list-seo-content] at /home/forge/unicorn-ai.app/vendor/livewire/livewire/src/Component.php:103)
```

**Comment by gyparedes1** [comment]
Hi! Did you manage to solve it? I have the same problem

**Comment by alexmanase** [comment]
Yes, but I don't really remember how. Probably I didn't read the full documentation.
