### ISSUE TITLE
Relationmanager tabs not working anymore

### ISSUE THREAD

**Issue by francoism90** [laravel-filament/filament#8517]
### Package

filament/filament

### Package Version

v3.0.50

### Laravel Version

v10.23.1

### Livewire Version

v3.0.4

### PHP Version

8.2.6

### Problem description

After upgrading to `v3.0.50`, the tabs stop working.

I cannot click on another relationship, it simply keeps pointing at the same tab.
I'm using session save, maybe this is the problem?

### Expected behavior

Tabs/relationmanagers working, as seen in =<3.0.48

### Steps to reproduce

1. Upgrade to latest version
2. Try to open a relationmanager (e.g. MediaRelationManager)

### Reproduction repository

https://github.com/francoism90/hub-api

### Relevant log output

```shell
It appends `?activeRelationManager=0` on the URL, even when I just clicked on a different relation.
```

**Comment by francoism90** [comment]
So I noticed, this seems to happen before the upgrade:
```
activeRelationManager=null <-- first tab
activeRelationManager=0 <-- opening relationmanager
```
On the latest upgrade it keeps `0` as value.

**Comment by danharrin** [comment]
Which page of your repository am I looking at, its huge

**Comment by danharrin** [comment]
That VideoResource only has one relation manager, I'm unsure of the problem you're reporting

**Comment by francoism90** [comment]
@danharrin Oh sorry, Filement is in https://github.com/francoism90/hub-api/tree/main/src/App/Admin

After checking the commits, this revert seems to fix the issue:
```
:active-manager="$activeRelationManager"
```

See https://github.com/filamentphp/filament/pull/8495/files

**Comment by francoism90** [comment]
@danharrin Yeah, I cannot even open that one.

I do have this:
https://github.com/francoism90/hub-api/blob/176f89ab67f5e8455c148eaf87d97e6cb4676071/src/App/Admin/Resources/VideoResource/Pages/EditVideo.php#L68

**Comment by lamberttraccard** [comment]
Same problem here 😞

**Comment by danharrin** [comment]
Fixed by #8519.

**Comment by lamberttraccard** [comment]
With the hasCombinedRelationManagerTabsWithContent set to true, I cannot go the edit form anymore
<img width="1146" alt="image" src="https://github.com/filamentphp/filament/assets/4272598/a7676435-0552-454d-a088-3d194128b0fd">

**Comment by francoism90** [comment]
@danharrin Just a confirmation it now works fine again!

Thanks again, great weekend.
