### ISSUE TITLE
TagsColumn show empty value on initial when use separator

### ISSUE THREAD

**Issue by AAbosham** [laravel-filament/filament#852]
### Package

filament/forms

### Package Version

v2.0.0

### Laravel Version

v8.0.0

### Livewire Version

v2.8

### PHP Version

PHP 8.0.0

### Bug description

TagsColumn show empty value on initial  when use separator

get from 
```
$this->afterStateHydrated(function (TagsInput $component, $state): void {
            ..
            if ($separator = $component->getSeparator()) {
                $component->state(explode($separator, $state));
```
can replace with this that be also not allow duplication by default 
```
if ($separator = $component->getSeparator()) {
    $component->state(Str::of($state)->explode($separator)->filter()->toArray());

```

**Comment by danharrin** [comment]
Fixed by #859.
