### ISSUE TITLE
Bug when trying to upload image using FileUpload with two different storages

### ISSUE THREAD

**Issue by miguilimzero** [laravel-filament/filament#8530]
### Package

filament/filament

### Package Version

v3.0.51

### Laravel Version

v10.23.1

### Livewire Version

v3.0.4

### PHP Version

PHP 8.2.10

### Problem description

When trying to upload an image file with `FILESYSTEM_DISK` to s3 and `FILAMENT_FILESYSTEM_DISK` set anything else. The Filament will try to first upload to the s3 and then to the desired disk.

However, my S3 disk does not have the CORS setup since it has nothing related to my filament panel.

### Expected behavior

The file upload should fully use the `FILAMENT_FILESYSTEM_DISK`.

### Steps to reproduce

- Clone example repo
- `php artisan migrate`
- `php artisan make:filament-user`
- Enter admin panel
- Try to create a post

### Reproduction repository

https://github.com/miguilimzero/filament-file-upload-bug-example

**Comment by miguilimzero** [comment]
Following the livewire documentation, it seems that the Temporary preview URL is trying to use the default disk and not the filament disk.

https://livewire.laravel.com/docs/uploads#temporary-preview-urls.

**Comment by danharrin** [comment]
You should also set the disk in the Livewire config, we can't do that for you unfortunately.

**Comment by devsumitkarn** [comment]
i was uploadin image and document file facing  issue can you solved this

doc path is here

DALL·E 2025-02-15 00.35.52 - A vibrant outdoor nature concert scene surrounded by lush green forests and colorful flowers. The stage is beautifully decorated with string lights, a
