### ISSUE TITLE
Need to call `fillForm()` when using `mount()` to authorize a settings page

### ISSUE THREAD

**Issue by alexjustesen** [laravel-filament/filament#8555]
### Package

filament/spatie-laravel-settings-plugin

### Package Version

v3.0.52

### Laravel Version

v10.23.1

### Livewire Version

v3.0.4

### PHP Version

PHP 8.2.10

### Problem description

When using `mount()` to authorize a settings page you need to refill the form by including `$this->fillForm()`.

### Expected behavior

The form should be filled regardless of authorization checks.

### Steps to reproduce

While using the plugin authorize the page using `mount()` as referenced in the docs for a page.

```php
public function mount(): void
{
    abort_unless(auth()->user()->is_admin, 403);
}
```

This can be fixed when by calling `$this->fillForm()` to initiate the form values again.

```php
public function mount(): void
{
    abort_unless(auth()->user()->is_admin, 403);

    $this->fillForm();
}
```

### Reproduction repository

https://github.com/alexjustesen/speedtest-tracker/pull/773

**Comment by danharrin** [comment]
Sorry, I don't really understand why this is a bug? You're overriding a method to extend it, so ofc you need to `parent::mount()` or copy the original code, that's just the nature of inheritance. It's not a hook class. If you want a hook class, `beforeFill()` is there.

**Comment by alexjustesen** [comment]
This was a my bad, had a complete and utter brain dead parent moment and you beat me to closing it out.
