### ISSUE TITLE
Extra footer actions are triggering a `MethodNotFoundException`

### ISSUE THREAD

**Issue by alexmanase** [laravel-filament/filament#8595]
### Package

filament/filament

### Package Version

3.0.53

### Laravel Version

10.23.1

### Livewire Version

3.0.5

### PHP Version

8.2.8

### Problem description

I tried to create an action in the footer of an Action moodal, and it triggers `MethodNotFoundException`. 

https://github.com/filamentphp/filament/assets/10696975/29798683-7d25-485b-ada7-41eb76d4a5ed

Here is the documenation section:

https://filamentphp.com/docs/3.x/actions/modals#opening-another-modal-from-an-extra-footer-action

### Expected behavior

Trigger the action when pressing the button in the Action modal footer.

### Steps to reproduce

1. Clone the repository: https://github.com/alexmanase/filament-action-in-footer-issue
2. Follow the instructions from `README.md`
3. Open an "edit" modal
4. Press the "Generate" button.

### Reproduction repository

https://github.com/alexmanase/filament-action-in-footer-issue

### Relevant log output

```shell
https://flareapp.io/share/x7XrLRRm
```

**Comment by danharrin** [comment]
Please use Filament\Tables\Actions\Action instead of Filament\Actions\Action

Child actions need to be the same class as their parent

**Comment by alexmanase** [comment]
@danharrin I just did it and now I get an error when I try to use `$set`:

```
Typed property Filament\Forms\Components\Component::$container must not be accessed before initialization
```

I also updated the demo.

**Comment by danharrin** [comment]
`$set` is part of the forms package, not the tables package. What are you trying to do?

**Comment by alexmanase** [comment]
I want to change the value of the `name` input from the modal.

This one:

<img width="564" alt="image" src="https://github.com/filamentphp/filament/assets/10696975/4dde5261-e880-4498-be43-e2d2b278114a">

**Comment by danharrin** [comment]
that's gonna be tricky, probably `$this->mountedTableActionsData['edit']['name'] = 'new value'`, which isn't very clean

**Comment by alexmanase** [comment]
This one worked for me:

```php
$this->mountedTableActionsData[0]['name'] = 'New generated content';
```

It's enough for me.

Thank you for your help!
