### ISSUE TITLE
Route [filament.users.index] not defined

### ISSUE THREAD

**Issue by drhoussem** [laravel-filament/filament#86]
I am getting an exception when I try to login to dashboard as an admin:
`Symfony\Component\Routing\Exception\RouteNotFoundException
Route [filament.users.index] not defined. (View: \www\projet\vendor\filament\filament\resources\views\components\layouts\app.blade.php)`

This happens only to admin user. I am using laravel 8 and Jetstream, I tried to look for this route and I did not find it on vendor folder.

Let me know if you need any more details.

**Comment by ryangjchandler** [comment]
Not able to reproduce this on a fresh, non-Jetstream installation. Will retry with a Jetstream installation.

**Comment by ryangjchandler** [comment]
Still not able to reproduce in a fresh Jetstream application. @drhoussem Did you install into a brand new application?

**Comment by danilopolani** [comment]
Have you tried running `php artisan route:clear`? The route is (I guess) registered here with a dynamic name: https://github.com/laravel-filament/filament/blob/main/routes/web.php#L43-L46

**Comment by shaffe-fr** [comment]
Hi, 
In case of someone encounters the issue, here is what happend for me.

I encountered the issue because I was registering resources manually the `boot` method of a `ServiceProvider`. 
```php
class FilamentServiceProvider extends PluginServiceProvider
{
    public function boot(): void
    {
        $resources = [
            UserResource::class,
        ];
        foreach ($resources as $resource) {
            Filament::registerResource($resource);
        }
        $pages = [
            CreateUser::class,
            EditUser::class,
            ListUsers::class,
        ];
        foreach ($pages as $page) {
            Filament::registerPage($page);
        }
    }
}
```

As the resource was registered to early in the request lifecycle, routes weren't created by Filament.
I ended up extending a `\Filament\PluginServiceProvider` and I used the `$resources` property.

```php
<?php

namespace App\Providers;

use App\Domain\User\Filament\Pages\CreateUser;
use App\Domain\User\Filament\Pages\EditUser;
use App\Domain\User\Filament\Pages\ListUsers;
use App\Domain\User\Filament\UserResource;
use Filament\PluginServiceProvider;

class FilamentServiceProvider extends PluginServiceProvider
{
    protected $pages = [
        CreateUser::class,
        EditUser::class,
        ListUsers::class,
    ];
    protected $resources = [
        UserResource::class,
    ];
}
```

If I create a namespace base auto discovery mechanism, I'll register the resources as follow:
```php
public function register(): void
{
    $this->app->booting(function () {
        // Register resources
    });
}
```

**Comment by bureauvk** [comment]
@shaffe-fr, I tried your solution. Stil the same problem for me.
Also I think we should use `Filament::serving(function() {....}); `, so it's only registering resources when accessing Filament right?

**Comment by aytackayin** [comment]
did u try filament.admin.resources.users.index   ?

**Comment by hamidroohani** [comment]
The problem is, that you have the same route with users in your `web.php`

**Comment by hosseinhashemi** [comment]
> Have you tried running `php artisan route:clear`? The route is (I guess) registered here with a dynamic name: https://github.com/laravel-filament/filament/blob/main/routes/web.php#L43-L46

It Worked. Thank you

**Comment by ariiprs** [comment]
i run "php artisan route:cache" or "php artisan route:clear" then it works again
