### ISSUE TITLE
Repeater with `BelongsToMany` relationship doesn't work as expected

### ISSUE THREAD

**Issue by sprtk-ches** [laravel-filament/filament#8616]
### Package

filament/forms

### Package Version

v3.0.53

### Laravel Version

v10.24.0

### Livewire Version

v3.0.5

### PHP Version

8.2

### Problem description

Following the [documentation ](https://filamentphp.com/docs/3.x/forms/fields/repeater#integrating-with-a-belongstomany-eloquent-relationship) for the `Repeater` type doesn't work as expected.

1. Not all related fields are shown. In the linked repo example, we have a user with 2 roles but only one is shown
2. Any edits to the roles usually lead to some sort of error, depending on the action (eg trying to remove an existing role might give a different error than trying to add a new one)

I have tried changing the name of the repeater and other suggested solutions from [here (discord link)](https://discord.com/channels/883083792112300104/1151806053164523591) but nothing seemed to work.

### Expected behavior

Using the `Repeater` I should be able to manage `BelongsToMany` relationships

### Steps to reproduce

Using the linked repo

1. Build the app 
2. Run the migrations and serve
3. Navigate to the homepage
4. You should have at least one user with 2 roles but only one will appear
5. Try editing the roles

Note that creating new relationships seems to work for the 1st time. After that, we get back to the original issue where not all records appear in the form.

### Reproduction repository

https://github.com/sprtk-ches/laravel-filament

**Comment by MarkKhromov** [comment]
@sprtk-ches, hi, friend! I had the same problem. While researching the Filament code, I discovered that it uses a model key to display the elements in the repeater. Try adding something like this to your pivot model:

```
protected $primaryKey = 'custom_id';
public function getCustomIdAttribute(): string {
    return $this->model1_id. '_' . $this->model2_id;
}
```

This code will fix the problem with displaying one entry, but it will not be possible to change it. I'm dealing with the change right now.

**Comment by MarkKhromov** [comment]
@sprtk-ches after studying the Filament code in more detail, I came to the conclusion that the easiest way would be to add an identifier to your Pivot, for example, some kind of UUID. This will solve almost all problems with changing, adding and deleting records. I'll do some more digging to see if I can fix this on the Filament side.

**Comment by sprtk-ches** [comment]
@MarkKhromov Thanks for the workaround 👍 ! I'll leave the issue open and let the filament team decide how they want to handle this.

**Comment by danharrin** [comment]
Hi, this is explained in the docs. https://filamentphp.com/docs/3.x/forms/fields/repeater#integrating-with-a-belongstomany-eloquent-relationship

You must use the HasMany pivot model as the relationship for the repeater, as each item represents a pivot record and not a related record

**Comment by MarkKhromov** [comment]
> Hi, this is explained in the docs. https://filamentphp.com/docs/3.x/forms/fields/repeater#integrating-with-a-belongstomany-eloquent-relationship
> 
> You must use the HasMany pivot model as the relationship for the repeater, as each item represents a pivot record and not a related record

@danharrin Yes, that's exactly what we do. But this doesn't work at all as expected. This will only work correctly with one entry. I won't be able to add a new entry if the identifier is not specified. Then it is necessary to describe this in the documentation. My code uses the Pivot table, as in the example. It has two columns work_id, employee_id and nothing else. And it doesn't work for me. I studied the repeater code and noticed that it simply cannot work correctly if there is no identifier for the record, no matter whether it is a pivot or a regular model. I suggest considering the possibility of working with a primary key formed from several columns. For example, if the model is set to $primaryKey = ['column1', 'column2'];
Just if you provide for this in the repeater, then the scenario with pivots will work correctly, and not as it does now. How do you look at this? I can help, try to implement this mechanism, but I need your help.

**Comment by danharrin** [comment]
We need a primary key, otherwise we cant easily keep track of which pivot entries have been created or deleted.

**Comment by MarkKhromov** [comment]
> We need a primary key, otherwise we cant easily keep track of which pivot entries have been created or deleted.

That's what I'm talking about too, but for a pivot table, the primary key can be made up of two columns.

**Comment by danharrin** [comment]
You can just use an easy auto increment, it doesnt need to be composite

**Comment by MarkKhromov** [comment]
> You can just use an easy auto increment, it doesnt need to be composite

Yes, I understand you. In order not to use auto-increment, I simply made my identifier in the pivot as uuid and everything works fine for me. But still, it wasn't entirely obvious that it should be used that way. It seems to me that the documentation should be supplemented to indicate that the table must have an identifier with a primary key.

**Comment by georgknabl** [comment]
> You can just use an easy auto increment, it doesnt need to be composite

@danharrin Another perspective from my side:
I typically only create data structures that are absolutely necessary. Hence, most pivot tables do not have an "id" column as the primary key is combined of both referenced tables. This is fine in vanilla Laravel. However, when using Filament, this becomes an issue as belongsToMany is built using hasMany structures. Not providing a single primary key column in the pivot table causes strange bugs in Filament forms that, in my case, took significant time to debug and pinpoint the issue to the "missing" id column. If Filament requires such a column, it would be great if this was stated in the docs. Even better: throwing an error, if such an incompatible configuration was found.

**Comment by danharrin** [comment]
Great, I agree it should be in the docs. There is an "Edit" button at the bottom of each docs page when you are ready to make the contribution 😄

**Comment by sathishreddynp** [comment]
Please add this in docs

**Comment by dharen008** [comment]
i just use formatStateUsing

TextEntry::make( 'members' )
->formatStateUsing( function ( $state ) {
return $state->name;
} )
->placeholder( 'No Members' )
->badge(),

**Comment by jvcss** [comment]
in my case, bcz I don't have a model for my pivot table, and I want to prefufill my edit modal with the data with relation with this specific table like this, adding the mutateRecordDataUsing like editing the data before it is passed to my Repeater. it works, so to populate the Repeater in this specific context I had to call the mutateRecordDataUsing from EditAction. the usage of using is to sync my changes for this model/table + pivot (I'm a beginner with laravel and filament and php as well haha, please be nice)

so far as I undertood it's like a context issue, because there is a correct place to change the $data before pass it to the Repeater component 
```php
public static function table(Table $table): Table

return $table->actions([
                DeleteAction::make(),
                EditAction::make()
                    ->mutateRecordDataUsing(function (array $data, Commission $record): array {
                        // Caso o campo 'items' não exista (ou esteja vazio), injeta os dados da pivot
                        if (empty($data['items'])) {
                            $data['items'] = $record->entities->map(function ($entity) {
                                return [
                                    'entity_id' => $entity->id,
                                    'commission_range_id' => $entity->pivot->commission_range_id,
                                    'goal' => $entity->pivot->goal,
                                    'result' => $entity->pivot->result,
                                    'allocated' => $entity->pivot->allocated,
                                ];
                            })->toArray();
                        }
                        return $data;
                    })
                    ->form(function (Commission $record) {
                        return [
                            Wizard::make([
                                Step::make('Distribuição')
                                    ->description('Defina as faixas e metas para cada Entidade')
                                    ->schema([
                                        Repeater::make('items')
                                            ->label('Entidades e Faixas')
                                            ->schema([
                                                Select::make('entity_id')
                                                    ->label('Entidade')
                                                    ->options(Entity::pluck('name', 'id'))
                                                    ->searchable()
                                                    ->required(),
                                                Select::make('commission_range_id')
                                                    ->label('Faixa de Comissão')
                                                    ->options(CommissionRange::pluck('percent', 'id'))
                                                    ->searchable()
                                                    ->required(),
                                                TextInput::make('goal')
                                                    ->numeric()
                                                    ->default(0)
                                                    ->label('Meta'),
                                                TextInput::make('result')
                                                    ->numeric()
                                                    ->default(0)
                                                    ->label('Resultado'),
                                                TextInput::make('allocated')
                                                    ->numeric()
                                                    ->default(0)
                                                    ->label('Alocado'),
                                            ])
                                            ->minItems(1)
                                            ->collapsible()
                                            ->itemLabel(
                                                fn(array $state): ?string =>
                                                Entity::find($state['entity_id'] ?? null)?->name ?? 'Nova Entidade'
                                            ),
                                    ]),
                            ])
                                ->persistStepInQueryString(),
                        ];
                    })
                    ->using(function (Commission $record, array $data) {
                        // Atualiza os dados básicos 
                        $record->update([
                            'name' => $data['name'],
                            'commission_value' => $data['commission_value'],
                            'user_id' => $data['user_id'],
                        ]);

                        // Sincroniza as relações na pivot
                        $relations = [];
                        foreach ($data['items'] as $item) {
                            $relations[$item['entity_id']] = [
                                'commission_range_id' => $item['commission_range_id'],
                                'goal' => $item['goal'],
                                'result' => $item['result'],
                                'allocated' => $item['allocated'],
                            ];
                        }
                        $record->entities()->sync($relations);

                        return $record;
                    }),
            ])
```
