### ISSUE TITLE
Call to a member function auth() on null

### ISSUE THREAD

**Issue by mosco23** [laravel-filament/filament#8618]
### Package

filament/filament

### Package Version

v3.0

### Laravel Version

v10.10

### PHP Version

PHP 8.1

### Problem description

php artisan make:filament-user

### Expected behavior

Call to a member function auth() on null

  at vendor/filament/filament/src/FilamentManager.php:50
     46▕     protected ?Model $tenant = null;
     47▕ 
     48▕     public function auth(): Guard
     49▕     {
  ➜  50▕         return $this->getCurrentPanel()->auth();
     51▕     }
     52▕ 
     53▕     public function bootCurrentPanel(): void
     54▕     {

      +18 vendor frames 

  19  artisan:37
      Illuminate\Foundation\Console\Kernel::handle()

### Steps to reproduce

1. Install Filament package
```
 composer require filament/filament:"^3.0-stable" -W
```
3.  update Model User
```php

<?php
 
namespace App\Models;
 
use Filament\Models\Contracts\FilamentUser;
use Filament\Panel;
use Illuminate\Foundation\Auth\User as Authenticatable;
 
class User extends Authenticatable implements FilamentUser
{
    // ...
 
    public function canAccessPanel(Panel $panel): bool
    {
        return str_ends_with($this->email, '@yourdomain.com') && $this->hasVerifiedEmail();
    }
}
```
3. Create Filament User
```
php artisan make:filament-user
```

### Reproduction repository

https://github.com/mosco23/ong-test.git

**Comment by zepfietje** [comment]
Make sure to follow all steps in the documentation. Your linked repo doesn't even have a panel provider: https://github.com/mosco23/ong-test/tree/main/app/Providers.

**Comment by jhoanborges** [comment]
This worked for me:
Try adding this line to you **config/app.php**

` App\Providers\Filament\AdminPanelProvider::class
`
