### ISSUE TITLE
Method Filament\Panel::spa does not exist.

### ISSUE THREAD

**Issue by isaacdarcilla** [laravel-filament/filament#8636]
### Package

filament/filament

### Package Version

3.0-stable

### Laravel Version

10.18.0

### Livewire Version

3.0

### PHP Version

PHP 8.2.3

### Problem description

BadMethodCallException
Method Filament\Panel::spa does not exist.

View the details here:
https://flareapp.io/share/qm1vooGP

### Expected behavior

SPA should work

### Steps to reproduce

Add spa() in admin panel provider

### Reproduction repository

None

### Relevant log output

```shell
BadMethodCallException
PHP 8.2.3
10.18.0
Method Filament\Panel::spa does not exist.


View the details here:
https://flareapp.io/share/qm1vooGP
```

**Comment by AbhinavNmdo** [comment]
Exactly, I am also facing this error

**Comment by sergiorodenas** [comment]
I can confirm it isn't working on Laravel 9 but it's working on Laravel 10

**Comment by isaacdarcilla** [comment]
Works now, shoutout to `fae._1`.

To fix this, you would need to change the filament version to `^3.0` in composer.json and then run `composer update`. It'll update from `3.0-stable` to latest version.

**Comment by CodeWithPranta** [comment]
Thank you @isaacdarcilla, your solution is working.

**Comment by CharrafiMed** [comment]
@isaacdarcilla  thanks you
