### ISSUE TITLE
Route [filament.app.pages.profile] not defined for custom tenant edit page

### ISSUE THREAD

**Issue by workflou** [laravel-filament/filament#8643]
### Package

filament/filament

### Package Version

v3.0.54

### Laravel Version

v10.24.0

### PHP Version

PHP 8.2.10

### Problem description

When registering a custom tenant profile page as described in [documentation](https://filamentphp.com/docs/3.x/panels/tenancy#adding-a-tenant-profile-page), the route is named `filament.app.tenant.profile`:

```GET|HEAD   {tenant}/profile ................. filament.app.tenant.profile › App\Filament\App\Pages\EditTeam```

However, when I run `getUrl` helper in tests:

```
use App\Filament\App\Pages\EditTeam;

EditTeam::getUrl(panel: 'app', tenant: $team)
```

I get an error:

`Route [filament.app.pages.profile] not defined.`

### Expected behavior

`getUrl` helper should generate url to `filament.app.tenant.profile` route

### Steps to reproduce

1. Create a custom tenant profile page
2. Register it in panel provider
3. Call `getUrl` helper method on a custom page

### Reproduction repository

https://github.com/workflou/workflou

**Comment by danharrin** [comment]
No reproduction.

**Comment by Stichoza** [comment]
I'm having the same issue. I'll add more context to it:

You have two panels - **A** panel has tenancy, **B** panel does not.

If you call `B\AnyResource::getUrl()` from any page of **A** panel (or vice-versa), you'll get "route not defined" error.
