### ISSUE TITLE
Undefined variable $activeTab introduced in #8652

### ISSUE THREAD

**Issue by lamberttraccard** [laravel-filament/filament#8655]
### Package

filament/filament

### Package Version

v3.0.57

### Laravel Version

v10.24.0

### Livewire Version

v3.0.5

### PHP Version

PHP 8.2

### Problem description

Undefined variable $activeTab exception

### Expected behavior

No exception

### Steps to reproduce

Using tabs in a listRecord resource

### Reproduction repository

https://github.com/lamberttraccard/filament

**Comment by drbyte** [comment]
More info to aid in troubleshooting: https://github.com/filamentphp/filament/pull/8652#issuecomment-1730146697

**Comment by danharrin** [comment]
Whoops, didn't see this and I fixed it myself
