### ISSUE TITLE
Issue with repeater and builder when saving in relation manager using spatie-laravel-translatable-plugin

### ISSUE THREAD

**Issue by tlegenbayangali** [laravel-filament/filament#8656]
### Package

filament/spatie-laravel-translatable-plugin

### Package Version

v3.0.57

### Laravel Version

v10.24.0

### Livewire Version

v3.0.5

### PHP Version

PHP 8.1.1

### Problem description

When attempting to save records through the relation manager, the repeater and builder using the spatie-laravel-translatable-plugin are not saved properly. I have two models: **CarModel** (hasMany Equipment) and **Equipment** (belongsTo CarModel). 

I created **EquipmentRelationManager** and added it to the list of relation managers list in the **CarModelResource** resource. In **EquipmentRelationManager** I added a **Repeater** field where you can add exterior items. At the same time, I made the relationship manager reactive, as indicated in the instructions, and also added $activeLocal = null.

But, unfortunately, the recording does not save data based on localization. I will describe more in the expectations section.

### Expected behavior

I expected that the data would be saved in the _equipment_ table based on localization, for example:

`{"kk": [{"option": "Хромдалған ұстағыштар"}], "ru": [{"option": "Хромированные ручки"}]}`

But the data from the repeater is saved as follows:

`[{"option": "Хромированные ручки"}]`

### Steps to reproduce

1. Clone reproduction repository
2. Install deps and open admin panel
3. Go to Car Models
4. Create Car Model
5. Create equipment to car model via relation manager, set some items in repeater field
6. Open created equipment in relation manager and see that data in repeater field is null
7. Check DB and see that value saved without localization.

### Reproduction repository

https://github.com/tlegenbayangali/filament-repeater-translatable-issue

**Comment by sten** [comment]
I am having similar issues with the builder and the spatie translatable package. It appears there is something wrong with setting the state. In my case, sometimes empty blocks are added, and it seems the livewire hash is included sometimes.

```
{
   "fr":{
      "86c0ea9b-a5f2-4e63-a29c-53b658db5f28":{
         "data":{
            "title":"dsdsd NL",
            "content":"<p>sdsdsssdsdsds</p>",
            "block_style":"default",
            "background_colour":"default"
         },
         "type":"filament-flexible-content-blocks::text"
      }
   },
   "nl":[
      {
         "data":{
            "title":"dsdsd NL",
            "content":"<p>sdsdsssdsdsds</p>",
            "block_style":"default",
            "background_colour":"default"
         },
         "type":"filament-flexible-content-blocks::text"
      },
      {
         "data":{
            "title":null,
            "content":null,
            "block_style":null,
            "background_colour":null
         }
      }
   ]
}
```

If this corrupted data is saved, the builder crashes because there is no `type` variable in the empty block.

**Comment by MichaelMdp** [comment]
Similar issues here.

What I observed, is that the `saveRelationshipsUsing` callback is triggered twice when saving a resource when the translatable plugin is enabled.
The second time the state is empty, triggering the delete of the relation record created in the first call. (in my many-to-many table)

**Comment by Robinvm** [comment]
Im experiencing this too, when is this fixed?
