### ISSUE TITLE
Modal Form not able to create record using the multi-tenancy

### ISSUE THREAD

**Issue by renztoygwapo** [laravel-filament/filament#8681]
### Package

filament/filament

### Package Version

v3

### Laravel Version

v10

### Livewire Version

3

### PHP Version

php 8.2

### Problem description

I am setting up the multi-tenancy and then created resource using the --simple tag which is modal.
the tenant_id when creating the record doesnt able to include on the save function the reason it wil get an errror.

### Expected behavior

the tenant_id should automatically filled up since they are already related each other and done setting up their relationships

### Steps to reproduce

1. setting up multi-tenancy
2. create a model and migration
3. setting up relationship many-to-many relation
4. create a resource with a --simple tag
5. Create a form -> this time you cannot save the form.

### Reproduction repository

production

**Comment by renztoygwapo** [comment]
<img width="1778" alt="image" src="https://github.com/filamentphp/filament/assets/4898681/fbc9f675-84f8-4a5f-bf33-1d7fb2bf9feb">

**Comment by jdion84** [comment]
perhaps filament can offer a trait that you can apply to tenant-scoped models

for example lets say that a user belongs to a team, and that team has posts

right now the docs show how to set this up for the user, but not for non-user models

i've manually added a trait that does this using my own logic:

```php
trait HasTenant
{
    public static function bootHasTenant()
    {
        static::addGlobalScope('tenant', function (Builder $query) {
            if (auth()->hasUser() && auth()->user()->tenant_id) {
                $query->where('tenant_id', auth()->user()->tenant_id);
            }
        });

        static::creating(function ($model) {
            if (!$model->tenant_id && auth()->hasUser()) {
                $model->tenant_id = auth()->user()->tenant_id;
            }
        });
    }

    public function tenant()
    {
        return $this->belongsTo(Tenant::class);
    }
}
```

however if this was built into filament so you could easily add this type of trait to non-user models that would be nice

as of right now, its not clear how to do this. the OP clearly forgot to add the column for a team id to his model, but he will also run into the issue of scoping queries and setting this value automatically based on which tenant the auth user is currently logged into
