### ISSUE TITLE
Getting breaking change when upgrade to v3.0.60

### ISSUE THREAD

**Issue by datlechin** [laravel-filament/filament#8686]
### Package

filament/filament

### Package Version

v3.0.60

### Laravel Version

v10.24.0

### Livewire Version

v3.0.5v3.0.5

### PHP Version

PHP 8.2.10

### Problem description

When upgrading from Filament version `v3.0.52` to `v3.0.60`, I encountered a critical issue with the `Action` component, specifically in the `->submit()` method. I suspect this change occurred sometime between these two versions but can pinpoint it to a commit: [link to the relevant commit](https://github.com/filamentphp/filament/commit/1ada03f4828d360f8b2401cecdc9606f6d9d1bf2).

In versions prior to `v3.0.52`, the `->submit()` method did not require any arguments. However, in the latest version (`v3.0.60`), a breaking change was introduced, and `submit()` now requires one parameter.

The issue is highlighted in the PHPStan report below:

```
Error: Method Filament\Actions\StaticAction::submit() invoked with 0 parameters, 1 required.
Error: Method Filament\Actions\StaticAction::submit() invoked with 0 parameters, 1 required.
 ------ --------------------------------------------------------------- 
  Line   Filament/Pages/Profile.php                                     
 ------ --------------------------------------------------------------- 
  77     Method Filament\Actions\StaticAction::submit() invoked with 0  
         parameters, 1 required.                                        
  1[18](...#step:6:19)    Method Filament\Actions\StaticAction::submit() invoked with 0  
         parameters, 1 required.                                        
 ------ ---------------------------------------------------------------
```

### Expected behavior

Expected behavior: The ->submit() method should function without any changes in Filament version 3.0.60 compared to version 3.0.52. It should not require any additional parameters in version 3.0.60 if it didn't in version 3.0.52.

### Steps to reproduce

To reproduce the issue related to the ->submit() method breaking change in Filament version 3.0.60, follow these steps:

Install Filament: Ensure that you have Filament installed in your PHP project and that it is currently running version 3.0.60.

Access the Code: Locate the code or file where you use the ->submit() method within Filament.

Invoke ->submit() Method: Make a call to the ->submit() method without passing any parameters. This can be done in the code that interacts with Filament.

```php
Action::make('create')->submit(); // No parameters passed
```

Observe Error: After invoking the `->submit()` method without parameters, observe the error message that indicates the method is invoked with 0 parameters but requires 1.

`Error: Method Filament\Actions\StaticAction::submit() is invoked with 0 parameters, but 1 is required.`

This error message should demonstrate the breaking change in the ->submit() method behavior when upgrading from Filament version 3.0.52 to 3.0.60, confirming the issue's reproducibility.

Upgrade to v3.0.60

### Reproduction repository

https://github.com/datlechin/filament

**Comment by zepfietje** [comment]
This is known and an intended change by @danharrin.
The `submit()` should have required a form in the past, as it's needed to display the loading indicator (since it requires a `wire:target`).
Also, previously it was impossible to remove the form to submit.

So even though it may break in some applications, I don't think this is a breaking change, rather a bug fix. Not sure if @danharrin has anything to add to that?

**Comment by danharrin** [comment]
Agree, it is a bug fix, passing in the form has pretty much always been mandatory otherwise the loading state is broken.
