### ISSUE TITLE
Could not identify an equality operator for type json

### ISSUE THREAD

**Issue by mrahmadt** [laravel-filament/filament#8698]
### Package

filament/forms

### Package Version

3.0-stable

### Laravel Version

v10.10

### PHP Version

8.2.10

### Problem description

Using below code for form creation
```
            Forms\Components\Select::make('services')
                ->multiple()
                ->relationship(name: 'apis', titleAttribute: 'name',modifyQueryUsing: fn (Builder $query) => $query->where('isActive',true))
                ->preload()
                ->searchable(['name', 'description'])
                ->loadingMessage('Loading...')->live()
```

will generate this error 

```
SQLSTATE[42883]: Undefined function: 7 ERROR: could not identify an equality operator for type json LINE 1: select distinct "apis".* from "apis" left join "api_app" on ... ^ 


select
  distinct "apis".*
from
  "apis"
  left join "api_app" on "apis"."id" = "api_app"."api_id"
where
  "isActive" = 1
order by
  "apis"."name" asc

```

I think this is related to the fact I'm using postgresql database

### Expected behavior

The select form field should list all options

```
                ->relationship(name: 'apis', titleAttribute: 'name',modifyQueryUsing: fn (Builder $query) => $query->where('isActive',true))
```

### Steps to reproduce

Nothing special or any customization has been done, just do this:

1. Use Postgresql database (not sure about MySQL)
2. create "create" form with select and relationship (many to many with pivot table)
3. the second model should have json column
4. browse to "create" page and you will get this error

### Reproduction repository

https://github.com/mrahmadt/filamentphp-bug-sql-json

### Relevant log output

```shell
Route:

    App\Filament\Resources\AppResource\Pages\CreateApp@__invoke



    filament.admin.resources.apps.create



        panel:admin

Illuminate\Cookie\Middleware\EncryptCookies

Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse

Illuminate\Session\Middleware\StartSession

Illuminate\Session\Middleware\AuthenticateSession

Illuminate\View\Middleware\ShareErrorsFromSession

Illuminate\Foundation\Http\Middleware\VerifyCsrfToken

Illuminate\Routing\Middleware\SubstituteBindings

Filament\Http\Middleware\DisableBladeIconComponents

Filament\Http\Middleware\DispatchServingFilamentEvent

Filament\Http\Middleware\Authenticate
```

**Comment by mrahmadt** [comment]
I'm not able to get around this issue, any workaround please?

**Comment by steinoy** [comment]
Same here. Issue is using relationship() when there's a json column on the table.

Workaround: Alter the select clause to remove the json column from the query (the default fetches everything, `select *`, including json columns etc., which does not work with DISTINCT)

```php
->relationship(name: 'terms', titleAttribute: 'title', modifyQueryUsing: function (Builder $query) {
    return $query->select('terms.id', 'terms.title')->distinct();
})
```

**Comment by danharrin** [comment]
As per canyongbs/advisingapp#324, the solution is to switch to a `jsonb` column. The `distinct()` part of the query does not come from the Filament codebase (as far as I can see), so there is not anything we can change about it.

**Comment by kmaphane** [comment]
Not too sure if I am right, I am always wrong. Is this not a big part of event sourcing? Dan and the team think of everything, and I honestly don't have the confidence to make an opinion here.  I can create a different approach, but does not sit right. Wish I knew enough to work on a solution.

**Comment by danharrin** [comment]
Is avoiding jsonb a requirement? It should be a good replacement for json

**Comment by kmaphane** [comment]
Hi,

Thanks for the response. Let me read up on it (jsonb) and test it. It's not a requirement, was thinking that my data structure is wrong for some reason and I need to change my approach. Did not read the above correctly. My apologies.

**Comment by kmaphane** [comment]
Oh WOW. Just like that it works.!! Thanks much appreciated.
