### ISSUE TITLE
Default value applied twice when grouping options within a multiple select field

### ISSUE THREAD

**Issue by EthosLuke** [laravel-filament/filament#8707]
### Package

filament/forms

### Package Version

v3.0.60

### Laravel Version

v10.24.0

### Livewire Version

v3.0.5

### PHP Version

PHP 8.1.2

### Problem description

When setting the default value of a multiple select field that has grouped options, the default value is applied twice. 

![image](https://github.com/filamentphp/filament/assets/98974453/457c1455-4e66-4125-ab6e-e17f0f22bc2b)

When the options are not grouped, the default value is applied in the expected way. 

![image](https://github.com/filamentphp/filament/assets/98974453/46395b39-4a4e-4b74-98af-681e941b4936)

### Expected behavior

I expect just one instance of the default value to be applied.

### Steps to reproduce

Simply create a form with a Select Field that has grouped options, multiple select, and a default value. Example below:

```
Select::make('Multi-Select with Grouped Options')
                    ->options([
                            'Group 1' => [
                                    'option_1' => 'Option 1',
                                    'option_2' => 'Option 2',
                                    'option_3' => 'Option 3',
                                    'option_4' => 'Option 4'
                                ],
                            'Group 2' => [
                                'option_5' => 'Option 5',
                                'option_6' => 'Option 6',
                                'option_7' => 'Option 7',
                                'option_8' => 'Option 8',
                        ]
                    ])
                    ->multiple()
                    ->default(['option_2']),
```

### Reproduction repository

https://github.com/EthosLuke/filament-select-group-bug

**Comment by benboubekeur** [comment]
I'm having the issue.

**Comment by saschagysel** [comment]
I have this issue too. It is not only the default value, it also happening for manually selected values (e.g. in a multiselect filter with option groups). If you select an option and then reload the page and open the filter again the selected options are there twice.
