### ISSUE TITLE
Form Select with enum options and multiple generates an error when removing an item and saving.

### ISSUE THREAD

**Issue by MichaelMdp** [laravel-filament/filament#8735]
### Package

filament/forms

### Package Version

v3.0.62

### Laravel Version

10.24.0

### Livewire Version

v3.0.5

### PHP Version

8.1.16

### Problem description

I have a basic Enum with a cast to convert it to json in the DB as we can expect multiple values to be selected.
When removing a value and then either save or try opening the select dropdown, an error is generated.

### Expected behavior

The option is removed and succesfully saved.

### Steps to reproduce

- login to filament
- go to the User resource
- edit a user
- add one or more roles to the roles field.
- save
- refresh
- remove a role
- save

As a result an error is returned.

### Reproduction repository

https://github.com/MichaelMdp/filamentv3-multiple-enum-select-repro

### Relevant log output

```shell
"__rm__" is not a valid backing value for enum "App\Enums\UserRoles"
```

**Comment by zepfietje** [comment]
Related to https://github.com/filamentphp/filament/issues/8423?

**Comment by ilpav12** [comment]
@zepfietje correct, same issue

**Comment by zepfietje** [comment]
Alright, closing as duplicate then.
Note we may still reopen https://github.com/filamentphp/filament/issues/8423 if it's not a Livewire issue or there's a way for us to work around it.
