### ISSUE TITLE
Conditionally Displaying a Field No Longer Live Updates

### ISSUE THREAD

**Issue by onairmarc** [laravel-filament/filament#8736]
### Package

filament/filament

### Package Version

3.0.62

### Laravel Version

10.24.0

### Livewire Version

3.0.5

### PHP Version

8.2.10

### Problem description

When a ```Toggle``` is true, it no longer triggers the display of a ```Select``` field that is conditionally required upon the ```Toggle``` being true. However, when I go to save the model, it flashes an error message that triggers the conditionally required ```Select``` to display as expected. Placing a value in the conditionally required ```Select``` field then allows the Model to save properly. The flash message on the ```Select``` field is expected behavior because this field is now required due to the ```Toggle``` now being true, but the ```Select``` field is never displayed for the user to enter a value before clicking save. It previously did dynamically appear when the ```Toggle``` had a value of true before saving in v3.0.53.

I'm curious if anyone else is encountering this issue and if any fixes have been found.

Here is the relevant code:

```php
 Forms\Components\Toggle::make('key_contact')
    ->label('Key Contact'),
Forms\Components\Select::make('key_reason_id')
    ->relationship(name: 'keyReason', titleAttribute: 'name')
    ->label('Key Reason')
    ->native(false)
    ->hidden(fn (Get $get) => $get('key_contact') != true)
    ->required(fn (Get $get) => $get('key_contact') == true)
    ->validationAttribute('Key Contact Reason'),
```

If any clarification is required, please just let me know.

Thanks!

### Expected behavior

When a ```Toggle``` is set to true in a form, the ```Select``` field should then display. When the ```Toggle``` is changed to false, the ```Select``` field should be hidden.

### Steps to reproduce

1. composer install
2. npm install
3. php artisan serve
4. navigate to http://localhost:8000/admin
5. login with username [demo@demo.com](mailto:demo@demo.com) and password demo
6. navigate to the demo resource
7. create new resource
8. set toggle to true
9. click create

The Select Field now appears with a flashed error message. The expected behavior is that the Select Field appears prior to pressing create or save.

### Reproduction repository

https://github.com/onairmarc/filament-issue-8736

**Comment by onairmarc** [comment]
Reproduction repo provided and filament installed. Demo Model and Demo Resource created. Heading into some meetings now and will update the repo more later this afternoon.

**Comment by onairmarc** [comment]
Reproduction Complete. Steps to reproduce:

1. composer install
2. npm install
3. php artisan serve
4. navigate to http://localhost:8000/admin
5. login with username demo@demo.com and password demo
6. navigate to the demo resource
7. create new resource
8. set toggle to true
9. click create

The Select Field now appears with a flashed error message. The expected behavior is that the Select Field appears prior to pressing create or save.

**Comment by zepfietje** [comment]
Okay so here's what I think happened.
Your code previously worked due to a bug in Livewire that made all fields live update.
That bug has recently been fixed in Livewire (and a workaround in Filament).

Please check the docs on [dependent fields](https://filamentphp.com/docs/3.x/forms/getting-started#dependant-fields).
Adding `live()` to the toggle should give you the desired result.
Feel free to comment on here if the issue still occurs.

**Comment by onairmarc** [comment]
@zepfietje yep that fixed it! Thank you!
