### ISSUE TITLE
DatetimePicker component year field get stuck when typing the first 2 chars slowly.

### ISSUE THREAD

**Issue by sawirricardo** [laravel-filament/filament#874]
### Package

filament/forms

### Package Version

v2.5

### Laravel Version

v8.76

### Livewire Version

v2.8

### PHP Version

PHP 8.1

### When typing the first 2 chars slowly, the datetime picker component get stuck.
![image](https://user-images.githubusercontent.com/37329575/146163618-d016b72f-bcac-4f46-8c60-ad0c54e94782.png)
### What happened in the browser console when this happened
![image](https://user-images.githubusercontent.com/37329575/146163970-d3934bd6-8cc7-49e7-a8e4-f022fda6c159.png)

### Steps to reproduce

Type first 2 chars in the datetime picker component on year field slowly.

**Comment by danharrin** [comment]
Fixed by #932.
