### ISSUE TITLE
Resource sub-navigation should keep its own collapsed state

### ISSUE THREAD

**Issue by saade** [laravel-filament/filament#8755]
### Package

filament/filament

### Package Version

v3.0.62

### Laravel Version

10.25.1

### Livewire Version

v3.0.5

### PHP Version

8.2.10

### Problem description

Resource subnavigation is getting collapsed with the sidebar (which makes sense because it uses the same `$store.sidebar.isOpen`)

https://github.com/filamentphp/filament/assets/14329460/875c3d61-9c1b-4c11-89a7-9c1f2d308dff

### Expected behavior

The subnavigation should not collapse with the sidebar

### Steps to reproduce

- Create a page
- Add a SubNavigation

### Reproduction repository

https://github.com/saade/filament-issue-reproduction-repo

**Comment by saade** [comment]
@zepfietje should i add a real reproduction repo to this? seems pretty easy to reproduce as its just adding subnavigation to the page.

**Comment by zepfietje** [comment]
I think it's ok as is.
Only @danharrin has worked on this so far.
Still pending design review by me.

**Comment by glennjacobs** [comment]
I will attempt to solve this today/tomorrow.
