### ISSUE TITLE
Collapsible section with a lot of content displaces sidebar

### ISSUE THREAD

**Issue by ghost** [laravel-filament/filament#8757]
### Package

filament/filament

### Package Version

v3.x

### Laravel Version

v10.x

### PHP Version

v8.2.*

### Problem description

When using a collapsible section like is described [here](https://filamentphp.com/docs/3.x/infolists/layout/section#collapsing-sections) and put in a bunch of `TextInputs` (you need to reach a certain height limit so use like 30), the sidebar starts to scroll upwards and will go out of view if the section is _collapsed_.

The logo in the upper left moves out of view too. As soon as you scroll up again, the logo comes into view again. Expanding the collapsible section fixes the issue too; it only occurs when the section is collapsed.

![image](https://github.com/filamentphp/filament/assets/143426227/da5db38a-d7fc-489c-be86-f7dfcd7b702b)

### Expected behavior

Show a sticky sidebar at all times.

### Steps to reproduce

```php
Filament\Forms\Components\Section::make(__('company.columns.details.details'))
    ->schema(
        collect(range(1, 30))->map(function ($i) {
            return Filament\Forms\Components\TextInput::make($i)->columnSpan(12);
        })->toArray()
    )
    ->collapsible();
```
Collapse and expand the section. Scroll vertically on the page. You should see weird sidebar behaviour.

### Reproduction repository

https://github.com/laravel/framework

**Comment by archilex** [comment]
@zepfietje This appears to be happening due to `invisible` being used on `fi-section` instead of `hidden` which is keeping all the section elements in the dom when the section is collapsed. `hidden` fixes this. Is there a reason why `invisible` was used instead of `hidden`? 

I can PR this if you like.

**Comment by zepfietje** [comment]
This was brought up in a recent discussion too, and Dan found the reason why `invisible` is used: https://github.com/filamentphp/filament/pull/8076#issuecomment-1700747748.

Please have a look at the final comment for the steps that need to be taken: https://github.com/filamentphp/filament/pull/8076#issuecomment-1712654553.

**Comment by leonardomrl** [comment]
Somehow I used it in css and managed to solve it when using "collapsed" the scrool understood the content as "invisible" but when using hidden it stopped bugging the sidebar and main scrool.

```css
.fi-collapsed {
    .fi-section-content {
        @apply hidden;
    }
}
```
