### ISSUE TITLE
Default value option doesn't work with native select

### ISSUE THREAD

**Issue by gergo85** [laravel-filament/filament#8776]
### Package

filament/forms

### Package Version

v3.0.62

### Laravel Version

10.25.1

### PHP Version

8.2.4

### Problem description

When I set the native option to false, the default value option doesn't work.

### Expected behavior

No selected default value.

### Steps to reproduce

Has default value of select field:
```
Select::make('print_all')
    ->options([
        1 => 'Yes',
        0 => 'no',
    ])
    ->default(1)
    ->required(),
```

No default value of select field:
```
Select::make('print_all')
    ->native(false)
    ->options([
        1 => 'Yes',
        0 => 'no'
    ])
    ->default(1)
    ->required(),
```

### Reproduction repository

https://github.com/gergo85/filament-test-selectfield

**Comment by ilpav12** [comment]
@gergo85 you forgot to mount the form this is why `->default()` is not working.
You can add the `mount()` function as show in the [documentation](https://filamentphp.com/docs/3.x/forms/adding-a-form-to-a-livewire-component#adding-the-form:~:text=public%20function%20mount()%3A,%7D).
Then you can use native selects:
```php
Select::make('print_all')
  ->options([
      1 => 'Yes',
      0 => 'No'
  ])
  ->default(1)
  ->selectablePlaceholder(false)
  ->live()
  ->required(),
Select::make('select_label')
  ->options(['None', 1, 2, 3])
  ->selectablePlaceholder(false)
  ->disabled(fn (Get $get) => $get('print_all') == 1)
  ->required(),
```

**Comment by gergo85** [comment]
Thank you very much! :)

**Comment by denismart** [comment]
It does not work, it creates visibility of work because after set `selectablePlaceholder(false)` it takes first option in list. Try to get another one and **_it does not work with native = true_** and **_it does not work with native = false_**

Here is my code for example:
```
<?php

namespace App\Livewire\photos;

use App\Models\Photo;
use Filament\Forms\Components\RichEditor;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Forms\Form;
use Livewire\Component;
use Livewire\WithPagination;

class Layout extends Component implements HasForms
{
    use WithPagination, InteractsWithForms;

    public ?array $data = [];

    public function mount(): void
    {
        $this->form->fill();
    }

    public function form(Form $form): Form
    {
        return $form
            ->schema([
                Select::make('print_all')
                    ->options([
                        1 => 'Yes',
                        0 => 'No'
                    ])
                    ->default(0)
                    ->selectablePlaceholder(false)
                    ->required(),
            ]);
    }

    public function render()
    {
        return view('livewire.photos.layout');
    }
}

```

**Comment by orebarranco** [comment]
Any solution to the problem?

**Comment by UtkuDalmaz** [comment]
Still no solution?

**Comment by ilpav12** [comment]
I have tried both examples provided by the original poster and the code provided by @denismart, and in version 3.2.121 are all working fine for me. I added those select components in the form method of a resource class

**Comment by hridani** [comment]
I'm reaching out to share an observation with the Select component in Filament forms, specifically related to the .default() method behavior. I've encountered an inconsistency that I hope you could help clarify or resolve.
Here are the details of the scenarios I'm working with:
Scenario 1: Working as expected
```
<?php
use Filament\Forms\Components\Select;

Select::make('status')
    ->options([
        'draft' => 'Draft',
        'reviewing' => 'Reviewing',
        'published' => 'Published',
    ])
    ->default('draft')
    ->selectablePlaceholder(false);  // This works correctly and selects the 'Draft' option.
```
Scenario 2: Not working as expected
```
<?php
use Filament\Forms\Components\Select;

Select::make('status')
    ->options([
        'draft' => 'Draft',
        'reviewing' => 'Reviewing',
        'published' => 'Published',
    ])
    ->default('reviewing')
    ->selectablePlaceholder(false);  // This does not select the 'Reviewing' option as expected.
```
In the second scenario, despite setting .default('reviewing'), the component does not correctly reflect this as the selected option when the form is initially displayed. It appears as though the default setting is ignored or not recognized.

Could you please provide some insight into whether there might be a specific reason why .default('reviewing') behaves differently? Could there be a configuration detail I'm missing, or is this potentially a bug in how default values are handled?

**Comment by orebarranco** [comment]
You are using adminpanel or individual pages to display the select

**Comment by hridani** [comment]
Yes, I use an admin panel. I am creating a form, calling it through the model. This is the code.

```
public static function getForm()
    {
        return [
            Grid::make()
                ->schema([  
                Select::make('status')
                    ->options([
                        'draft' => 'Draft',
                        'reviewing' => 'Reviewing',
                        'published' => 'Published',
                    ])
                    ->default('reviewing')
                    ->selectablePlaceholder(false)
                ])
        ];
    }    
```

 When I create, it's okay. 
![create](https://github.com/user-attachments/assets/f33de52b-0120-440e-a256-94446b243851)

 But when I edit - it's not what I expect.
![edit](https://github.com/user-attachments/assets/527d4ebd-b76f-47e8-9a25-9fe3468afc2f)

**Comment by spacedogstudios** [comment]
@hridani is this editing or creating a record? I believe the default value is only respected on create. For editing, you can try something like:

```
<?php
use Filament\Forms\Components\Select;

Select::make('status')
    ->options([
        'draft' => 'Draft',
        'reviewing' => 'Reviewing',
        'published' => 'Published',
    ])
    ->default('reviewing')
    ->afterStateHydrated(function (Select $component, ?string $state) {
        if ($state === null) {
            $component->state('reviewing');
        }
    })
    ->selectablePlaceholder(false); 
```

**Comment by hridani** [comment]
Thank you for your suggestion! Your solution works perfectly. I appreciate
your help.

На пн, 2.12.2024 г. в 1:43 spacedogstudios ***@***.***>
написа:

**Comment by hridani** [comment]
Thank you for your suggestion! Your solution works perfectly. I appreciate your help.
