### ISSUE TITLE
Autofocus issue with form fields

### ISSUE THREAD

**Issue by gergo85** [laravel-filament/filament#8783]
### Package

filament/forms

### Package Version

v3.0.62

### Laravel Version

10.25.1

### PHP Version

8.2.4

### Problem description

I set the autofocus, it works in the first case. But when I refresh the page, it doesn't work anymore.

### Expected behavior

No autofocus on form field after multiple page refreshes.

### Steps to reproduce

Use the autofocus option.

### Reproduction repository

https://github.com/gergo85/filament-test-autofocus

**Comment by zepfietje** [comment]
Could you share a short video and a report of which browsers this issue occurs on?

**Comment by gergo85** [comment]
I tried it in both Firefox and Chrome browsers.
https://github.com/filamentphp/filament/assets/2959112/7a6c823f-ebec-456d-873d-5d25070fc057

**Comment by gergo85** [comment]
Thank you for fix!
