### ISSUE TITLE
Issue when toggling a resources relationmanager

### ISSUE THREAD

**Issue by tvdr** [laravel-filament/filament#8788]
### Package

filament/filament

### Package Version

v3.0.62

### Laravel Version

v10.25.2

### Livewire Version

v3.0.5

### PHP Version

PHP 8.2.5

### Problem description

Having two relationmanagers on a resource, one with canViewForRecord(), controlled by an  $ownerRecord attribute, e.g. a boolen toggle.

switch off the toggle,save record -> all relationmanagers disappear with js error : "Uncaught Snapshot missing on Livewire component with id: cdUvjw37Lpwhz4xgoRYE"

switch on the toggle, save record -> tablist nav item is shown, but relationmanager tabpanel has empty livewire component, also js error: "Uncaught Snapshot missing on Livewire component with id: JBybPURsFHmsJocGGswn"

### Expected behavior

tabbed relationmanagers to appear when controller attribute is set, or remove tabbed manager and show single relationmanager when attribute is unset

### Steps to reproduce

add Toggle to a form of a resource with two relationmanagers

```
public static function getRelations(): array
{
        return [
            RelationManagers\AddressesRelationManager::class,
            RelationManagers\PaymentsRelationManager::class,
        ];
}
```

```
Forms\Components\Toggle::make('has_payments')
```

define canViewForRecord method on one of the managers

```
public static function canViewForRecord(Model $ownerRecord, string $pageClass): bool
    {
        return $ownerRecord->has_payments;
    }
```

### Reproduction repository

https://github.com/tvdr/filamentdemo/tree/tabbed_relationmanager_fix

**Comment by tvdr** [comment]
https://github.com/filamentphp/filament/assets/6872670/03342e68-e506-4b8e-bbd7-c08dae571845

**Comment by danharrin** [comment]
https://github.com/filamentphp/filament/pull/8790#issuecomment-1763314753

**Comment by michaelklopf** [comment]
We recently came back to a filament project with an older release than this and now upgraded. It broke a view where we add the relation manager like this:

https://filamentphp.com/docs/3.x/panels/resources/viewing-records#custom-view

The change here broke the view as the `$this->activeRelationManager` was still a `$activeRelationManager`.
