### ISSUE TITLE
The relationship select field is not passing the value on the create page but it's working fine on an edit page

### ISSUE THREAD

**Issue by naamsachin** [laravel-filament/filament#8789]
### Package

filament/filament

### Package Version

^3.0-stable

### Laravel Version

^10.10

### Livewire Version

^3.0

### PHP Version

8.2.9

### Problem description

The relationship select field is not passing the value on the create page but it's working fine on an edit page

![image](https://github.com/filamentphp/filament/assets/21311262/28ba641b-d571-405d-a1d2-60c0b4c4cf6d)

### Expected behavior

It should pass the value on the create page as well

### Steps to reproduce

It is worked on changing the filament version to 3.0-stable without the caret symbol

### Reproduction repository

https://github.com/sachinagerwal/sachinagerwal

**Comment by zepfietje** [comment]
I'm confused, as you're talking about create and edit page, while your screenshot shows the view page?

**Comment by naamsachin** [comment]
@zepfietje - Select field issue with create page only
Video: https://drive.google.com/file/d/10V6xRHynRJSWh9fVEuJ2g_KeQUoIcGQZ/view

**Comment by naamsachin** [comment]
The create page is not submitting the selected relationship category on the post resource.

**Comment by naamsachin** [comment]
@zepfietje The issue is solved by adding **category_id** as  **$fillable** in the **Post Model**

**Comment by awcodes** [comment]
Marking as closed since this is not an issue with Filament.
