### ISSUE TITLE
Rows not match theme and text invisible while draggin in dark-mode

### ISSUE THREAD

**Issue by valpuia** [laravel-filament/filament#8794]
### Package

filament/filament

### Package Version

v3.0.60

### Laravel Version

latest

### Livewire Version

latest

### PHP Version

8

### Problem description

While dragging, the rows became white and all data is invisible in dark-mode.

[Screencast from 09-30-2023 12:50:28 PM.webm](https://github.com/filamentphp/filament/assets/28250303/34bebfa3-2d6f-4028-91c3-ee7651c62e16)

### Expected behavior

Rows matching theme and data visible in dark mode while dragging

### Steps to reproduce

Goto `Brand` in demo (https://demo.filamentphp.com/shop/brands)
Set theme to dark
Enable drag-and-drop mode
Start dragging

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by zepfietje** [comment]
Can't reproduce this issue on macOS Chromium and Safari.
Likely related to your operating system, so please attempt a fix.

**Comment by valpuia** [comment]
> Can't reproduce this issue on macOS Chromium and Safari. Likely related to your operating system, so please attempt a fix.

Hi, I try to fix (check) this.. but I cannot find where to check :rofl: can you point me where to look please

**Comment by valpuia** [comment]
[Screencast from 10-02-2023 10:26:00 AM.webm](https://github.com/filamentphp/filament/assets/28250303/d05ac179-7085-4acc-8524-925d730294bf)

Checking more this, I think this is related to my chrome browser.. work fine in Other browser.. and also working fine in my colleagues browser (chrome).. hence closed
