### ISSUE TITLE
Problem with CheckboxList and bulkToggleable

### ISSUE THREAD

**Issue by danielbehrendt** [laravel-filament/filament#8796]
### Package

filament/filament

### Package Version

v2.17.53

### Laravel Version

v10.25.2

### PHP Version

PHP 8.2.11

### Problem description

There is a problem with the `CheckboxList` field and `bulkToggleable` in combination with `reactive()` or `lazy()`. When trying to bulk toggle the first checkbox always gets unchecked. 

Without reactive()or lazy() everything works as expected.

### Expected behavior

All checkboxes should be checked.

### Steps to reproduce

Use this small form schema to reproduce:

```
public static function form(Form $form): Form
{
    return $form
        ->schema([
            Forms\Components\CheckboxList::make('list_a')
                ->options(['A', 'B', 'C'])
                ->bulkToggleable()
                ->reactive(),
        ]);
}
```

### Reproduction repository

https://github.com/danielbehrendt/filament-test

**Comment by danharrin** [comment]
Could you please see if this is an issue on v3?

**Comment by danharrin** [comment]
Seems to be ok on v3:

https://github.com/filamentphp/filament/assets/41773797/73c0886a-f4c2-47d4-bba0-19b9f20bad33

I am more than happy to merge and release bug fixes for v2. However, I am no longer fixing bugs myself in that version.

If there are security issues with v2, I will make bug fixes myself.
