### ISSUE TITLE
Reordering a repeater item with file upload error

### ISSUE THREAD

**Issue by emmexx** [laravel-filament/filament#8801]
### Package

filament/filament

### Package Version

v3.0.40

### Laravel Version

v10.22.0

### Livewire Version

v3.0.2

### PHP Version

8.1.23

### Problem description

When using the repeater with a file upload field and reordering with drag and drop is enabled, if you drop the repeater item  in the drop area of the file upload you are left with empty file upload items.

### Expected behavior

The repeater item should not be droppable over the drop area of a file upload.  

### Steps to reproduce

Add a repeater to a form schema.
Inside the repeater schema add a fileUpload component.
Load the form.
Add a file to the fileUpload of the 1st repeater.
Add a repeater item.
Click on the reorder icon of the 1st repeater item and drop it on the upload area of the fileUpload of the 2nd repeater item.

### Reproduction repository

https://gist.github.com/emmexx/b7f988592bb215acce2cb1fd31a19f1a#file-photoresource-php

**Comment by danharrin** [comment]
This is unfortunately a bug within Filepond that we are not able to fix. Filepond should only delete items when an image is dropped.

**Comment by faizananwerali** [comment]
+1
