### ISSUE TITLE
Table Builder - Custom columns Command create a blade file in the wrong path

### ISSUE THREAD

**Issue by ryo-kozin** [laravel-filament/filament#8805]
### Package

filament/tables

### Package Version

v3.0

### Laravel Version

v10.20.0

### Livewire Version

v3.0.0

### PHP Version

PHP 8.2.10

### Problem description

The problem is I got a table-column blade file in the wrong path.

I the command below.
php artisan make:table-column StatusSwitcher

Then I got ./resources/views/tables/columns/status-switcher.blade.php

[Filament docs. Custom columns.](https://filamentphp.com/docs/3.x/tables/columns/custom)

According to the filament docs, a file named status-switcher can be created under resources/views/filament/tables/components/.

### Expected behavior

I create ./resources/views/filament/tables/columns/status-switcher.blade.php

### Steps to reproduce

Executing php artisan make:table-column StatusSwitcher

### Reproduction repository

https://gist.github.com/ryo-kozin/fff049d112b6927576e2acc4356204d1

**Comment by acharseth** [comment]
Both the Artisan Command and the folder in which the blade file is created indicates that these (class and blade) are not Filament spesific files. Is this correct? If so I can kind of understand that this issue was closed, but should't it at least be corrected in the documentation?
@ryo-kozin , I suggest you either reopen, or may be better, recreate this as a documentation bug. Agree?

**Comment by ryo-kozin** [comment]
@acharseth 
Hi,

Thank you for the responses. I initially raised this issue because, according to my understanding at that time, the Filament documentation indicated that the `status-switcher` blade file should be created under `resources/views/filament/tables/components/`. However, upon rechecking today, I found that the documentation now correctly reflects the appropriate path.

Given this correction, there is no need to reopen this issue, and it can remain closed.

Thanks again for your support.
