### ISSUE TITLE
we cannot set rules for rich editor attachments

### ISSUE THREAD

**Issue by Epicaler** [laravel-filament/filament#8829]
### Package

filament/forms

### Package Version

v3.0.63

### Laravel Version

v10.25.2

### Livewire Version

v3.0.5

### PHP Version

PHP 8.2.10

### Problem description

in the Rich editor Forms, we cannot set rules for attachments unlike FileUpload Class that have `->image` method.
So we can upload everything like a shell or bad files.

### Expected behavior

Rich Editor class should have a method that we can Set rules or mime types for attachment files!

### Steps to reproduce

1: Use Rich Editor class in a form.
2: Upload a bad file like a shell or virus.

### Reproduction repository

https://github.com/Epicaler/filament-uploading-richeditor-issue.git

**Comment by zepfietje** [comment]
This isn't really a bug report, rather a feature request, right?

**Comment by Epicaler** [comment]
> This isn't really a bug report, rather a feature request, right?

but we can upload a shell or bad files to access the whole website! is not this a security bug?

**Comment by vjanssens** [comment]
For anyone ending up here through a Google search: The RichText editor uses native `$wire.upload` method which can be configured with the global configuration file: https://livewire.laravel.com/docs/uploads#global-validation. This allows you to validate only images are uploaded.
