### ISSUE TITLE
Table bulk selection checkbox doesn't get unchecked after changing page

### ISSUE THREAD

**Issue by zepfietje** [laravel-filament/filament#8844]
### Package

filament/filament

### Package Version

v3.0.60

### Laravel Version

10.24.0

### Livewire Version

3.0.5

### PHP Version

8.2.10

### Problem description

Bulk selection checkbox doesn't update after changing page.

https://github.com/filamentphp/filament/assets/44533235/53cd62ec-878e-4969-b0b1-d9b279cc3337

### Expected behavior

Expected the checkbox to be unchecked after moving to the a page which doesn't have all records selected.

### Steps to reproduce

1. Go to https://demo.filamentphp.com/shop/products.
2. Check the bulk selection checkbox to select all rows on the first page.
3. Go to the second page.
4. Find that the checkbox is still checked.

### Reproduction repository

http://github.com/filamentphp/demo

**Comment by o-tari** [comment]
Seems if I console.log it, the value is false (correct), but can't seem to resolve it tho

<img width="743" alt="Screenshot 2023-10-25 at 02 49 25" src="https://github.com/filamentphp/filament/assets/51799275/d9d965c9-6436-431e-b7f9-62d6062cc238">

**Comment by zepfietje** [comment]
Not sure how this worked previously, but the the checked state should be updated whenever the records on the page change, right..?

**Comment by zepfietje** [comment]
Could you provide some more info, @danharrin?
As I suppose you've built this initially. 🙂

**Comment by ashleyshenton** [comment]
I've attempted a fix for this and the only thing I could do to get it working was to add `wire:key="{{ rand() }}"` which forces a re-render. This same issue also occurs on the demo when you select all and then change the column used for sorting.
