### ISSUE TITLE
ViewColumn has one <a> edit link too many in V3

### ISSUE THREAD

**Issue by swrtom** [laravel-filament/filament#8871]
### Package

filament/filament

### Package Version

v3.0-stable

### Laravel Version

v10.19.0

### PHP Version

PHP 8.2.5

### Problem description

I have a filament Resource with a Table. This table has a ViewColumn class which return the write code with a link too many in the inspect console of the browser : 

**Resource column :**
`ViewColumn::make('contact')->view('tables.columns.user_contact')->label('Contact')`

**HTML template user_contact.blade.php :** 
```
<div class="flex items-center">
    @if($getRecord()->email)
        <a href="mailto:{{ $getRecord()->email }}" class="text-indigo-600 hover:text-indigo-900">
            <svg ...>
                 ...
            </svg>
        </a>
    @endif
    @if($getRecord()->tel)
        <a href="tel:+33{{ $getRecord()->tel }}" class="text-indigo-600 hover:text-indigo-900">
            <svg ...>
                ...
            </svg>
        </a>
    @endif
</div>
```

Result in the inspector with the <a> element too many :
![image](https://github.com/filamentphp/filament/assets/44288315/9dee1b96-9f14-4996-8ea0-f6b893fd4b98)

You can try by yourself I tested many different code with similar syntax : after each beginning of a div inside this view, a "edit link" pops from nowhere.

The "edit link" : 
![image](https://github.com/filamentphp/filament/assets/44288315/96b096a4-6379-4615-bfcf-068aa95c573f)

### Expected behavior

That this code : 
![image](https://github.com/filamentphp/filament/assets/44288315/2ac58433-1692-4c4c-8fa0-8a90e95d1947)

doesn't look like this in the console : 
![image](https://github.com/filamentphp/filament/assets/44288315/2e82706c-e260-42ff-b258-8ee16a1f687d)

### Steps to reproduce

Create a new Resource class and fill it with UserResource class of the repo below. Set the user_contact view and inspect the code in the browser

### Reproduction repository

https://github.com/sheepbild/filament-viewcolumn-bug/tree/main/columns-bug

**Comment by wychoong** [comment]
Add ->disabledClick() to your column

**Comment by zepfietje** [comment]
Yeah I think disabling the column link action should work.
This is probably caused by nesting links, which is not allowed.
