### ISSUE TITLE
Installing FilamentPHP with --no-interaction opens the GitHub webpage

### ISSUE THREAD

**Issue by emmadesilva** [laravel-filament/filament#8880]
### Package

filament/filament

### Package Version

v3.0.67

### Laravel Version

10.26.2

### Livewire Version

v3.0.5

### PHP Version

8.2.11

### Problem description

When running `php artisan filament:install --panels --no-interaction`, the https://github.com/filamentphp/filament page opens in the browser.

### Expected behavior

The page should not be opened in the browser when running without interaction.

This could probably be fixed by changing the default value of the "Would you like to show some love by starring the Filament repo" prompt to false when running without the interactive flag.

### Steps to reproduce

Setup:

```bash
laravel new filament-bug-repro --no-interaction
cd filament-bug-repro 
composer require filament/filament:"^3.0-stable" -W --no-interaction
```

Repro:
```bash
php artisan filament:install --panels --no-interaction
```

NOTE: Since the bug does not require a repro, I just posted my standard one. All you need to do is to run the repro command above.

### Reproduction repository

https://github.com/caendesilva/filament-bug-repro

**Comment by zepfietje** [comment]
Yeah this is a known bug.
Would you be able to create a PR to fix it, @caendesilva?
As this is low priority relatively to other issues, we probably won't be looking into it soon.

**Comment by emmadesilva** [comment]
> Yeah this is a known bug. Would you be able to create a PR to fix it, @caendesilva? As this is low priority relatively to other issues, we probably won't be looking into it soon.

Yeah, I've messed with Console conditionals before for HydePHP so it shouldn't be a problem. Please assign it to me and I'll get it done soon-ish. Currently working on my term papers so a bit busy this week but I'll mark it for my calendar next week in case I forget.
