### ISSUE TITLE
White rendered input fields on dark theme

### ISSUE THREAD

**Issue by francoism90** [laravel-filament/filament#8920]
### Package

filament/filament

### Package Version

v3.0.68

### Laravel Version

10.26.2

### Livewire Version

3.0.5

### PHP Version

PHP 8.2.0

### Problem description

It seems the dark isn't being applied correctly. Every input has been changed to white-bg, which makes it unreadable when using a dark-theme (Gnome-shell):

![image](https://github.com/filamentphp/filament/assets/5028905/5d786c6b-51fe-4bae-8cb8-76d53dee3096)

This wasn't an issue before `v3.0.68`.

### Expected behavior

Correctly render on dark environment.

### Steps to reproduce

1. Upgrade to latest v3.0.68
2. Create edit form for a resource
3. Open edit page

### Reproduction repository

https://github.com/francoism90/hub-api

**Comment by zepfietje** [comment]
Please recompile your theme.

**Comment by francoism90** [comment]
@zepfietje Yep, that worked!

Sorry for the noise.

**Comment by zepfietje** [comment]
@francoism90, make sure to recompile after every Filament update, since new Tailwind classes may be added.

**Comment by sakthimanikandan558** [comment]
> Please recompile your theme.

How to do that?. I have that same issue...
