### ISSUE TITLE
Table row actions not working on custom livewire page

### ISSUE THREAD

**Issue by biebthesecond** [laravel-filament/filament#8924]
### Package

filament/filament

### Package Version

v3.0.68

### Laravel Version

v10.26.2

### Livewire Version

v3.0.5

### PHP Version

8.1.19

### Problem description

I wanted to add a row action to a table element on a custom livewire page. So I did this according to the documentation. But when I then clicked the row action in the table itself only a short loading icon appears and then nothing.

I did test with a ->url(route('someroute'))->openUrlInNewTab() that the action is actually being triggered, which it is.
After that I tried a bulk action with the exact same code which then worked perfectly. So I assume this is a bug in Filament.

Said action.
```           
->actions([
                 \Filament\Tables\Actions\Action::make('DissociateTeamMember')
                    ->requiresConfirmation()
                    ->hidden(!$this->isTeamAdmin)
                    ->color('danger')
                    ->icon('heroicon-o-x-mark')
                    ->label('Teamlid verwijderen')
                    ->action(function () {
                        dd('test');
                    }),

            ])
```

### Expected behavior

That the action modal triggered and the code in the ->action(function() { //code  }) runs.

### Steps to reproduce

* Create a livewire page
* add filament table to page
* add action to table ( Example action above )

Aditional info which might be useful,
* I have multiple other standalone actions in the same page,
* Yes I did include: <x-filament-actions::modals/>
* the query for the table is:  
 ```
->query($this->team->members()->getQuery())
```

### Reproduction repository

https://github.com/biebthesecond/filamentActionBug

**Comment by Tray2** [comment]
Have you tried using the `recordAction` instead?

```
public static function table(Table $table): Table
    {
        return $table
            ->columns(...)
            ->filters(...)
            ->actions(...)
            ->bulkActions(...)
            ->recordAction(Tables\Actions\ViewAction::class) 
            ->recordUrl(null);
    }
```

**Comment by popdaul** [comment]
I have same issue, pls kill the bug~

**Comment by xBigDaddyx** [comment]
same issue

**Comment by hyphen81** [comment]
I think I'm having the same issue, but not a table action. Just an anonymous action on my livewire component. if I do `mountUsing` I can `dd` a value, but nothing happens in the `action` method itself.

**Comment by vandershraaf** [comment]
I got the same issue with filament 3.0.87 version. 

![bug](https://github.com/filamentphp/filament/assets/599221/ca979e19-d880-40ef-a5d1-1b2cb6a91f7b)
```php
class ListTools extends Component implements HasTable, HasForms, HasActions
{
    use InteractsWithTable;
    use InteractsWithForms;
    use InteractsWithActions;
    public function table(Table $table): Table {
        return $table
            ->query(Tool::query())
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->searchable(),
                Tables\Columns\TextColumn::make('product.name')
                    ->sortable(),
.....
.....
->actions([
                Tables\Actions\ViewAction::make()
            ])

```

**Comment by vandershraaf** [comment]
As a workaround, I use recordUrl() from the $table instance instead of actions(), and sets it to redirect to another custom Form with all disabled fields. This fulfills my requirement to show the row info, though it is slightly inconvenient to create new Form, as it is not necessary if ViewAction does work in actions().

```php
 public function table(Table $table): Table {

        return $table
            ->query(Tool::query())
            ->columns([
....
...
-> recordUrl(fn (Tool $tool): string => route('tool.view', ['id' => $tool -> id]),)
```
![bug](https://github.com/filamentphp/filament/assets/599221/82ce47e1-ff8d-401f-81b7-06750e8007e4)


In new Livewire component for the read-only form:

```php
class ViewTool extends Component implements HasForms
{
    use InteractsWithForms;

    public Tool $tool;
    public ?array $data = [];

    public function mount($id) {
        $this -> tool = Tool::findOrFail($id);
        $this -> form -> fill($this -> tool -> toArray());
    }

    public function form(Form $form): Form
    {
        return $form
            ->model($this -> tool)
            ->schema([
                Forms\Components\Fieldset::make('essentials')
                    -> label('Essentials')
                    -> schema([
                        Forms\Components\TextInput::make('name')
                            -> readOnly()
                            -> disabled(),
......
......
```
Routing as full page Livewire component:

```php
Route::get('/tools/{id}', \App\Livewire\ViewTool::class) -> name('tool.view');
```

**Comment by danharrin** [comment]
There are many comments in this thread, and I highly doubt that any of them are related to the original issue.

The original issue is that the author is trying to use a relationship query without defining it properly:

Instead of:

```
->query(
                $this->team?->members()->getQuery() ?? Team::query()
            )
```

Use:

```
->relationship(fn () => $this->team->members())
```

And it will work. Docs: https://filamentphp.com/docs/3.x/tables/adding-a-table-to-a-livewire-component#building-a-table-for-an-eloquent-relationship

**Comment by jimiero** [comment]
Hello,

In case someone hits this issue, it seems the cause is when you do something like this in your table query

return  Costs::select([
            'costs.id as id_costs',

for some reason that id_costs confuses things, and doesn't works even if you set getTableRecordKey to it

**Comment by raobilal482** [comment]
i found the solution the problem is in table query if you are using relation ship in query then it will not work but if you using simple query then the actions will work.
