### ISSUE TITLE
Preview mode on Markdown editor

### ISSUE THREAD

**Issue by jals-es** [laravel-filament/filament#8933]
### Package

filament/filament

### Package Version

v3.0.68

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

PHP 8.1.0

### Problem description

In Filament v2, the markdown editor has a preview mode, but in v3, the preview mode doesn't appear.

### Expected behavior

A label to switch to preview mode.

### Steps to reproduce

Adding a markdown editor.

### Reproduction repository

https://github.com/filamentphp/filament

**Comment by movicat** [comment]
https://github.com/filamentphp/filament/assets/36602392/c57b79c7-de76-4988-86c7-0bda3f2034e7
