### ISSUE TITLE
Preview mode on Markdown editor

### ISSUE THREAD

**Issue by jals-es** [laravel-filament/filament#8934]
### Package

filament/filament

### Package Version

v3.0.68

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

PHP 8.1.0

### Problem description

In Filament v2, the markdown editor has a preview mode, but in v3, the preview mode doesn't appear.

### Expected behavior

A label to switch to preview mode.

### Steps to reproduce

Adding a markdown editor.

### Reproduction repository

https://github.com/filamentphp/demo.git

**Comment by zepfietje** [comment]
This is by design, since the new Markdown editor is kind of a WYSIWYG editor.

**Comment by ismaail** [comment]
the Markdown Editor is based on [EasyMDE](https://github.com/Ionaru/easy-markdown-editor) wich supports preview button.

why not allowing this ?

**Comment by movicat** [comment]
https://github.com/filamentphp/filament/assets/36602392/c71c6738-ec5c-4a45-a200-38eb46adad93

**Comment by Daniil-Solovyev** [comment]
Without a preview it's very inconvenient. Is there any progress on this issue?

**Comment by jals-es** [comment]
> Without a preview it's very inconvenient. Is there any progress on this issue?

Finaly I do my custom component. No news about the preview of the filament markdown editor.

**Comment by jals-es** [comment]
> > Without a preview it's very inconvenient. Is there any progress on this issue?
> 
> Finaly I do my custom component using EasyMDE library. No news about the preview of the filament markdown editor.
>
