### ISSUE TITLE
Wondering if border is needed in this icon ?

### ISSUE THREAD

**Issue by ghost** [laravel-filament/filament#8941]
### Package

filament/filament

### Package Version

3.0.49

### Laravel Version

10.10

### PHP Version

8.1.0

### Problem description

<img width="317" alt="Screenshot 2023-10-07 at 13 08 30" src="https://github.com/filamentphp/filament/assets/5849907/cce7d02f-ea43-4b85-a42e-049d0e4b8e3d">

<img width="278" alt="Screenshot 2023-10-07 at 13 10 47" src="https://github.com/filamentphp/filament/assets/5849907/e6568957-30e3-4120-acaa-08ed7acd3f03">

Small border design issue, in both dark/light modes. Is this a bug or intentional (in that case close the issue)? Thank you.

### Expected behavior

No borders, or a different approach.

### Steps to reproduce

BelongsToSelect with create/edit relation ship.

### Reproduction repository

https://no-reproduction-repository.com

**Comment by zepfietje** [comment]
This is caused by the focus states of both components.
We're aware of this and planning to fix it.
