### ISSUE TITLE
$table->defaultSort(...) needs 2 clicks, to go from asc to desc

### ISSUE THREAD

**Issue by MichaelMdp** [laravel-filament/filament#8971]
### Package

filament/filament

### Package Version

v3.0.62

### Laravel Version

10.24.0

### Livewire Version

v3.0.5

### PHP Version

8.1.16

### Problem description

When using a filament table with a column flagged as 'sortable' and a defaultSort defined on the table. the sorting is applied e.g. : ascending.

- The sort arrow is visualized as 'inactive', indicating a 'not sorted' state. (but it is actually sorted based on the 'defaultSort('email', 'asc')
- When clicking the column header / sort arrow, nothing happens, sort icon is now active and indicating 'asc' order.
-  if you click it again, to sorting switches to desc and sort icon is active and indicating 'desc' order.

Similar behavior is reproducable in the admin panels.
This was not the case in v2.

component used for testing is (App\Livewire\DropdownTest)

### Expected behavior

if the default sorting is defined and you click the column header / sort arrow, the sorting direction should change and the records should be ordered accordingly.

### Steps to reproduce

artisan migrate:fresh --seed
got the the home page /
a table should be visible with 10 users
click the sort arrow on the 'email' field. => nothing changes
click the sort arrow on the 'email' field again. => order is reversed

### Reproduction repository

https://github.com/MichaelMdp/filamentv3-default-sort-issue

**Comment by danharrin** [comment]
Yes, this is a deliberate behaviour. Default sorting in v3 is not associated with a column, as now you can pass any combination of multiple columns, or a custom query. Clicking the first time activates the per-column sort, and then clicking again makes it descend. This was the best behaviour we could find when investigating this feature for v3.

**Comment by MichaelMdp** [comment]
Ok, thanks for the feedback!
