### ISSUE TITLE
Does not filter correctly with multiple where in getEloquentQuery

### ISSUE THREAD

**Issue by mendizalea** [laravel-filament/filament#8975]
### Package

filament/filament

### Package Version

3.0.71

### Laravel Version

10.26.2

### Livewire Version

3.0.6

### PHP Version

8.2.11

### Problem description

It does not filter correctly when you select, for example, status by any of the options or when the resource is started with the default filter.

### Expected behavior

That filters correctly whether with the default or with any selected options.

### Steps to reproduce

Once the Ticket resource is opened, it does not filter correctly through the default state filter. If you select any of the options in the filter it doesn't work either.

### Reproduction repository

https://github.com/mendizalea/filament-query-bug/tree/master

**Comment by zepfietje** [comment]
Could you confirm if this is caused by https://github.com/filamentphp/filament/issues/8972, @mendizalea? Maybe by switching to `native(false)` on the select?

**Comment by mendizalea** [comment]
> Could you confirm if this is caused by #8972, @mendizalea? Maybe by switching to `native(false)` on the select?

I couldn't tell you for sure if it is related, but I would say that is not related. I just tried with native(false) and same problem.

**Comment by zepfietje** [comment]
Alright, will leave this issue open then.

**Comment by mendizalea** [comment]
> Alright, will leave this issue open then.

I have detected a second problem related to this. When I go to edit or view a table record it always opens the same record.

**Comment by danharrin** [comment]
The `orWhere()` is interfering with further constraints applied by the filters etc:

```
public static function getEloquentQuery(): Builder
    {
        return parent::getEloquentQuery()->withoutGlobalScopes([SoftDeletingScope::class])
            ->where(fn ($query) => $query->whereBelongsTo(auth()->user(), 'ownedBy')
            ->orWhereBelongsTo(auth()->user(), 'requestedBy'));
    }
```

Wrapping both in a nested `where()` should fix all issues
