### ISSUE TITLE
description on TextColumn return null 

### ISSUE THREAD

**Issue by alimsan** [laravel-filament/filament#8988]
### Package

filament/filament

### Package Version

v.3.0.73

### Laravel Version

v.10.27.0

### Livewire Version

v3.0.7

### PHP Version

PHP 8.1.22

### Problem description

It seems there is an error in the text column where the column is not connected to the database or returns from the model, previously in version V.3.0.0 and I still have stable code in that version.
Code
TextColumn::make('costumkl')
                    ->label('Kolom Costum')
                    ->copyable()
                   ->description(function ($record) {
                        $data = "<strong>{$record->name}</strong>,<br>{$record->last_name}";
                        $html = new HtmlString($data);
                        return ($html);
                    })

but the column in version ^3.0 reproduces empty values, not in version 3.0.0, the description reproduces existing data values.
Maybe that's all I hope this can help other colleagues and myself.

cool package, keep up the good work!

### Expected behavior

it should return the appropriate data as version 3.0.0

### Steps to reproduce

I can't seem to find the steps yet, although I have tried to reproduce them in the customization view

### Reproduction repository

https://github.com/infaltech/kominfo_stunting_app

**Comment by alimsan** [comment]
Please note that this TextColumn::make('costumkl') column is not related to the model or database. I just created the custom column in the resource

**Comment by zepfietje** [comment]
Reproduction repository throws a 404.
