### ISSUE TITLE
League \ Flysystem \ UnableToCheckDirectoryExistence for DO spaces s3 driver

### ISSUE THREAD

**Issue by zlatangoralija** [laravel-filament/filament#8999]
### Package

filament/filament

### Package Version

v3.0.68

### Laravel Version

v10.26.2

### PHP Version

v8.2.11

### Problem description

I'm using Digital Ocean spaces to store images. I can load this image by going to the URL just fine. Only thing I noticed, is that the protocol part in URL is missing one `/`, so instead of `https://` it's actually `https:/`. I assume that is the reason for this error, but unfortunately, I can't find a way to fix it. Here's the setup of my code:

.env:
```
DO_SPACES_KEY=key
DO_SPACES_SECRET=secret
DO_SPACES_ENDPOINT=https://spaces.url
DO_SPACES_REGION=fra1
DO_SPACES_BUCKET=bucket.name
DO_SPACES_USE_PATH_STYLE_ENDPOINT=false
```

filesystems.php
```
's3' => [
        'driver' => 's3',
        'key' => env('DO_SPACES_KEY'),
        'secret' => env('DO_SPACES_SECRET'),
        'endpoint' => env('DO_SPACES_ENDPOINT'),
        'region' => env('DO_SPACES_REGION'),
        'bucket' => env('DO_SPACES_BUCKET'),
        'use_path_style_endpoint' => env('DO_SPACES_USE_PATH_STYLE_ENDPOINT', false),
        'throw' => false,
        'visibility' => 'public',
],
```

This is how I retrieve the image url:

`return Storage::disk('s3')->url($featuredImage->path);`

If I do a `dd()` of this value, I get the correct link with two // in the protocol. But the same exception occurs. If I comment out this value, I get no exception.

`"https://spaces.link/bucket.name/posts/istockphoto-457796927-612x612.jpg" // app/Models/Post.php:103`

When I remove the getter, everything work just fine. Also, the getter works just fine when using `tinker`, so that's why I assume that there is an error with filament. 

Problem is probably located in namespace `App\Filament\Resources\PostResource`

### Expected behavior

For the edit view of the post to show, instead of throwing an exception. 

### Steps to reproduce

I created a getter for this in the `Post.php` model, and this is where I get the mentioned exception:

```
protected function featuredImage(): Attribute{
    return Attribute::make(
        get: fn () => $this->getFeaturedImage(),
    );
}

public function getFeaturedImage(){
    $featuredImage = $this->images()->where('featured', true)->first();
    if($featuredImage){
        return Storage::disk('s3')->url($featuredImage->path);
    }

    return null;
}

public function images(){
    return $this->hasMany(PostImage::class, 'post_id');
}
```

After I store the new record with images uploaded, I'm navigated away to "edit" page and then exception is shown.

### Reproduction repository

https://github.com/zlatangoralija/filament-s3-bug

### Relevant log output

```shell
League \ Flysystem \ UnableToCheckDirectoryExistence
Unable to check existence for: https:/spaces.link/bucket-name/posts/istockphoto-457796927-612x612.jpg
```

**Comment by danharrin** [comment]
When filling a file upload field in a Filament form, Filament generates the URL for you based on the path. So in this case, it only needs `posts/istockphoto-457796927-612x612.jpg`. We generate a URL from that. This problem is caused by the fact that you have a custom accessor on the model which overrides this value and passes the entire URL. You will need to remove the accessor, rename it to something that won't clash, or use `mutateFormDataBeforeFill()` on the Edit page to convert the URL back into a path.

Filament uses the path instead of the URL since we fetch other data about the file like its size, and we need the path for this to use the Filesystem helpers.
