### ISSUE TITLE
Translatable Columns Appears as JSON on the Dashboard 

### ISSUE THREAD

**Issue by YoussefIbraheem** [laravel-filament/filament#9033]
### Package

filament/filament

### Package Version

v3.0.63

### Laravel Version

v10.25.2

### Livewire Version

v3.0.5 

### PHP Version

8.1.0

### Problem description

Whenever there is a column that is **translatable**, it appears as a **JSON** property like below:

{"en":"ad","ar":"tenetur"}

This Happens to all Input Fields that have the option() helper such as:

1- `Select::`
2- `SelectFilter::`
3- `CheckboxList::`

This issue can sometimes be tackled using the `->options()` helper, but if you need to use `->relationship()` then there is no way that it would be able to be tackled or altered and even if you added ->options() with ->relationship it will be displayed as JSON, and if you removed the relationship it will give an error especially if the relationship is many-to-many. I had a discussion on Discord with one of the moderators but there was no luck in tackling it, here is the URL below for the conversation:

[JSON columns issue
](https://discord.com/channels/883083792112300104/1148602552871551137
)

### Expected behavior

It should return the data as a string depending on the chosen language or the locale set however it seems to be failing to parse the data to the expected outcome like the example below 

* Column data in the table:

`title: {"en":"ad","ar":"tenetur"}`

* Expected Outcome if the chosen language is English:

`title: "ad"`

* Expected Outcome if the chosen language is Arabic:

`title: "tenetur"`

* Actual Outcome:

`title: {"en":"ad","ar":"tenetur"}`

### Steps to reproduce

```
  CheckboxList::make('services')
                        ->label(__('Services'))
                        ->relationship('services', 'title')
                        ->required(),
```
```
Services
{"en":"ad","ar":"tenetur"}
{"en":"consequatur","ar":"est"}
{"en":"dolorum","ar":"quo"}
{"en":"est","ar":"odit"}
{"en":"et","ar":"earum"}
{"en":"fuga","ar":"in"}
{"en":"omnis","ar":"perspiciatis"}
{"en":"quam","ar":"et"}
{"en":"qui","ar":"enim"}
{"en":"quis","ar":"deserunt"}
```

### Reproduction repository

https://github.com/YoussefIbraheem/dummy-project

**Comment by awcodes** [comment]
Leaving this open pending a question I've posed to Dan.

For the time being though, you can get your desired results with the `->getOptionLabelFromRecordUsing()` method. Spatie's package works by calling the field directly off the model itself.

```php
CheckboxList::make('services_test')
    ->label('Services')
    ->relationship('services', 'title')
    ->getOptionLabelFromRecordUsing(fn($record) => $record->title)
    ->required(),
```

**Comment by awcodes** [comment]
After talking to Dan, `getOptionLabelFromRecordUsing` should be required when using relationships on fields with translatable fields.

We will get the docs updated soon.

Thanks.

**Comment by valentinceaprazaru** [comment]
@awcodes but how can i get the value from the Database for the current selected language? 

This is my Host Resource: 

`class ActivityResource extends Resource
{
    use Translatable;

    protected static ?string $model = Activity::class;

    protected static ?string $navigationIcon = 'heroicon-o-rectangle-stack';

    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                TextInput::make('name')
                    ->required()
                    ->maxLength(255),
                Textarea::make('description')
                    ->maxLength(65535)
                    ->columnSpanFull(),
                Select::make('category_id')
                    ->label('Category')
                    ->relationship('category', 'name')
                    ->getOptionLabelFromRecordUsing(function($record) {
                      return $record->name;
                    })
                    ->required(),`
                    
And i get only the Locale of EN. Which is set globally. But i would like to get the current locale for the Resource:

![image](https://github.com/user-attachments/assets/fd072b89-10b9-4262-a0f1-79c65394c9ba)

**Comment by awcodes** [comment]
You shouldn't need it. Spatie's package infers it from the current app locale when you call the property on the record.
