### ISSUE TITLE
Bug with custom summarize in groupings

### ISSUE THREAD

**Issue by d3v1anX** [laravel-filament/filament#9073]
### Package

filament/filament

### Package Version

v3.0.74

### Laravel Version

v10.28.0

### Livewire Version

v3.0.8

### PHP Version

PHP 8.2.11

### Problem description

With custom summarize-functions and grouping the summarize function will not summarize as expected. The summarize function works as expected on the buttom of the table. Unfortunately the group-summaries seems like there is something wrong. 
![Bildschirmfoto 2023-10-13 um 11 10 29 AM](https://github.com/filamentphp/filament/assets/21339066/5948ad9c-9872-4ee9-888d-8380114ba608)

### Expected behavior

summarizing of grouped columns correct.

### Steps to reproduce

install repository down below
```
// install composer dependencies
composer install
// migrate fresh database
php artisan migrate
// create filament-user
php artisan make:filament-user   
// seed database with sample data
php artisan db:seed WorktimeSeeder
```

Login on local environment
Click on worktimes

### Reproduction repository

https://github.com/d3v1anX/filament-bug.git

**Comment by danharrin** [comment]
Try this:

```php
Tables\Columns\Summarizers\Sum::make()
    ->formatStateUsing(function (int $state) {
        $interval = CarbonInterval::seconds($state)->cascade();
        $totalHours = $interval->d * 24 + $interval->h;
        $newInterval = CarbonInterval::hours($totalHours)->minutes($interval->minutes)->seconds($interval->seconds);

        return $newInterval->format('%H:%I:%S');
    }),
```

You can rely on the existing Sum which can handle grouping properly, and just format the result

**Comment by d3v1anX** [comment]
> Try this:
> 
> ```
> Tables\Columns\Summarizers\Sum::make()
>     ->formatStateUsing(function (int $state) {
>         $interval = CarbonInterval::seconds($state)->cascade();
>         $totalHours = $interval->d * 24 + $interval->h;
>         $newInterval = CarbonInterval::hours($totalHours)->minutes($interval->minutes)->seconds($interval->seconds);
> 
>         return $newInterval->format('%H:%I:%S');
>     }),
> ```
> 
> You can rely on the existing Sum which can handle grouping properly, and just format the result

Its working :) Thank you Dan!
