### ISSUE TITLE
Route [login] not defined. when php artisan migrate:fres --seed

### ISSUE THREAD

**Issue by gyaanesh** [laravel-filament/filament#9075]
### Package

filament/filament

### Package Version

^3.0

### Laravel Version

10.28.0

### PHP Version

^8.1

### Problem description

when I am logged in to my admin dashboard and running PHP artisan migrate:fresh --seed in my terminal and after migrated and seeded I refresh my page it shows Route [login] not defined 

### Expected behavior

should redirect to the default route provided by filament

### Steps to reproduce

clone repository.  setup the project. run 
`php artisan migrate --seed`
 login with  
username=> admin@gmail.com 
Password=>Admin@1on1
when you are logged in 
go back to the terminal and run 
 `artisan migrate:fresh --seed`
refresh your browser page 

### Reproduction repository

https://github.com/gyaanesh/filament.git

**Comment by awcodes** [comment]
This is a side effect of Laravel's login route.

You can add this to your `routes/web.php`

replace 'admin' with whatever route your panel is using.

```php
Route::redirect('/login', '/admin/login')
    ->name('login');
```

or you can just refresh the page. :)

**Comment by gyaanesh** [comment]
Thanks . this Works for Me
