### ISSUE TITLE
FileUpload imageEditor cannot restrict free cropping

### ISSUE THREAD

**Issue by NaungYeHtet** [laravel-filament/filament#9097]
### Package

filament/forms

### Package Version

v3.0.0

### Laravel Version

v10.10

### PHP Version

8.1

### Problem description

Cannot crop based on Aspect Ratios.

`
FileUpload::make('image')
    ->image()
    ->imageEditor()
    ->imageEditorAspectRatios([
        '1:1',
    ])
`

<img width="1127" alt="image" src="https://github.com/filamentphp/filament/assets/49832780/3ed46cd1-e411-49d9-bdd8-cc21d67fc5b1">

### Expected behavior

User can only crop based on permitted aspect ratios.

### Steps to reproduce

`
->imageEditorAspectRatios([
        '1:1',
    ])
`

### Reproduction repository

https://github.com/NaungYeHtet/filament-ascept-ratio

**Comment by chosten** [comment]
When there is only one aspect ratio, you can use `imageEditorViewportHeight` and `imageEditorViewportWidth` to force the aspect ratio.
It's not very clear and I'm not sure those 2 methods do what their name suggest.
