### ISSUE TITLE
Property not found on component

### ISSUE THREAD

**Issue by dmitrijsmihailovs** [laravel-filament/filament#91]
**Describe the bug**
Installed fresh latest Laravel 8 and filament cms, created model, migration and resource, added title field and tried to save, got this error or sometimes - No property found for validation

**Screenshots**
![image](https://user-images.githubusercontent.com/6555569/110156457-a727ef00-7def-11eb-8d15-95b17eb4ab9d.png)
![image](https://user-images.githubusercontent.com/6555569/110156496-b444de00-7def-11eb-8b6a-30be6f960dd7.png)

**Context**
- Browser: Chrome
- Server OS: Laradock on Windows
- PHP version: 7.4
- Database: MySQL 8.0

**Comment by ryangjchandler** [comment]
@dmitrijsmihailovs Can you share your form / fields code?

Im guessing you're not using the resource field and using the normal field (not for resource forms).

**Comment by dmitrijsmihailovs** [comment]
I tried it this ways

`public static function form(Form $form)
    {
        return $form
            ->schema([
                TextInput::make('title')
            ]);
    }`

**Comment by danharrin** [comment]
@dmitrijsmihailovs could you show us where you imported `TextInput` please? It should be `Filament\Resources\Forms\Components\TextInput`.
