### ISSUE TITLE
$set() does not update KeyValue Field the first times

### ISSUE THREAD

**Issue by eugenpasca** [laravel-filament/filament#9120]
### Package

filament/filament

### Package Version

v3.0.77

### Laravel Version

v10.28.0

### Livewire Version

required from Filament: v3.0.8

### PHP Version

8.2.11

### Problem description

When using `$set` on a `Forms\Components\KeyValue` doesn`t work for the first few times:

1. A User has a JSON field called `fields` it is cast as `array`
2. In a filament Resource form, when I select a field template, I want to prepopulate the fields KeyValue Field with some data
3. on the first run it does not change, only after switching between templates a few times it starts working

The same bug was found and repaired in version 2: https://github.com/filamentphp/filament/issues/2939

### Expected behavior

When I select a template, the KeyValue is populated with the correct data on the first time

### Steps to reproduce

1. Create the resource Form:
```PHP
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\TextInput::make('email')
                    ->email(),

                Forms\Components\Select::make('field_template')
                    ->options([
                        'no-fields' => 'No fields',
                        'many-fields' => 'Many Fields',
                    ])
                    ->live()
                    ->afterStateUpdated(function (Forms\Set $set, ?string $state) {
                        if ($state == 'no-fields') {
                            return $set('fields', []);
                        } else {
                            return $set('fields', [
                                'key_1' => 'value 1',
                                'key_2' => 'value 2',
                                'key_3' => 'value 3',
                            ]);
                        }
                    }),
                Forms\Components\KeyValue::make('fields')
                    ->default([]),
            ])
            ->columns(1);
    }
```
2. Navigate to the User Resource page: `admin/users/create`
3. Select a template field. The `fields` doesn`t update
4. Select a new template field. The same
5. Only after a few selections the `fields` are populated

Here are the screenshots with all the steps:
![image](https://github.com/filamentphp/filament/assets/26302190/b15bfbc6-08f6-4d7e-9ec5-7a0ceb911cbf)
![image](https://github.com/filamentphp/filament/assets/26302190/b502eeaf-b875-4331-ac4c-c12c8383deff)
![image](https://github.com/filamentphp/filament/assets/26302190/fe106c47-6523-458e-9333-d2a764966908)
![image](https://github.com/filamentphp/filament/assets/26302190/ce698603-023e-4447-812e-64b45890c5ac)
![image](https://github.com/filamentphp/filament/assets/26302190/9973dd82-862e-4ad4-be94-d7c4689f07cb)
![image](https://github.com/filamentphp/filament/assets/26302190/c494563f-a4d3-49e3-b8eb-66ba11c7da98)
![image](https://github.com/filamentphp/filament/assets/26302190/33c6c061-27d6-41ad-b445-7d1854e54586)

### Reproduction repository

https://github.com/eugenpasca/filemant-key-value-bug

**Comment by martin-ro** [comment]
Having the same issue.

**Comment by brianglz** [comment]
Hola comunidad, alguien logró solucionar el problema o saben como hacer para que funcione.

Hello community, did someone manage to solve the problem or know how to make it work.

**Comment by itsandreu** [comment]
Yo encontré una solución añadiendo el método hidden en el KeyValue , tal que así:
->hidden(fn (Get $get) => $get('field_template') === null)

I found a solution adding the hidden method in the KeyValue , like this:
->hidden(fn (Get $get) => $get('field_template') === null)

Tell me if it worked for you.
