### ISSUE TITLE
bg-primary classes missing from action buttons?

### ISSUE THREAD

**Issue by danharrin** [laravel-filament/filament#913]
### Discussed in https://github.com/laravel-filament/filament/discussions/911

<div type='discussions-op-text'>

<sup>Originally posted by **iancallahan** December 17, 2021</sup>
First of all, thank you for creating such a great product. I've used Filament to create quick admins for some side projects and it has worked beautifully. 

I'm using Filament 2 for the first time on an existing project and I have hit a snag that is probably because I've missed something. It seems that the bg-primary, etc.  classes are missing from action buttons. This leaves me with white text on a white background for all of the action buttons. 

I've set up a tailwind theme and that is working fine for the sidebar navigation, but the default action buttons for resources are all showing up this way. 

It looks like the second element in the  $buttonClasses array in the button component is not being applied, and I don't know why. 

<img width="338" alt="Screen Shot 2021-12-17 at 3 01 11 PM" src="https://user-images.githubusercontent.com/4192103/146601525-3fd5525a-1181-4c6d-9f09-721520476d75.png">
<img width="245" alt="Screen Shot 2021-12-17 at 3 01 01 PM" src="https://user-images.githubusercontent.com/4192103/146601526-bcee7954-4090-456e-8a7f-83953bf74464.png">
</div>

**Comment by iancallahan** [comment]
The tailwind config is below, but FWIW this happened right out of the box. I installed Filament with composer and as soon as I added my first model, before registering a theme, I noticed the action buttons were white on white. I pursued tailwind customization thinking that there were no defaults before I realized the tailwind classes were not showing up in the button HTML. 

Here's my tailwind.config.js:
```
const colors = require('tailwindcss/colors')

module.exports = 
{content:["app/**/*.php",
"resources/**/*.js",
"resources/**/*.php",
"./vendor/filament/**/*.blade.php"
],
"theme":{"extend":{"colors":{"gray":colors.trueGray,"red":colors.red,"orange":colors.orange,"yellow":colors.yellow,"green":colors.green,"blue":colors.cyan,"purple":colors.violet,"pink":colors.pink,"999999":"#999999","e6e6e6":"#e6e6e6","666666":"#666666","cccccc":"#cccccc","3d3d3d":"#3d3d3d","b3b3b3":"#b3b3b3",danger: colors.rose,
primary: colors.blue,
success: colors.green,
warning: colors.yellow,
}}
},
"variants":{"extend":[]},
plugins: [
    require('@tailwindcss/forms'), 
    require('@tailwindcss/typography'), 
]}

```

**Comment by danharrin** [comment]
Hey, I definitely can't replicate this issue. Can you make sure your view cache is clear?

**Comment by danharrin** [comment]
I'm gonna close this, can you create a brand new repo and see if you can replicate the issue. Please send a link here if you can and I'll reopen :)

**Comment by iancallahan** [comment]
It turns out I had a $color variable set in a global view composer that was interfering with the Filament color prop. Just mentioning this in case anyone runs into a similar issue.
