### ISSUE TITLE
Errors with RichEditor field in custom (non panel) component

### ISSUE THREAD

**Issue by MasterOfWeb** [laravel-filament/filament#9141]
### Package

filament/filament

### Package Version

v3.0.78

### Laravel Version

v10.28

### PHP Version

PHP 8.1

### Problem description

As soon as I add a RichEditor or Markdown field to my form in a custom component, I get this livewire error in my browser console:

Livewire Entangle Error: Livewire property ['data.description'] cannot be found on component: ['create-post'] 

Therefore, the RichEditor field can be edited but the data can't be sent to the server.

<img width="1455" alt="Bildschirmfoto 2023-10-17 um 12 35 37" src="https://github.com/filamentphp/filament/assets/13961958/cc67040e-168d-480a-b885-ffae5eec3d78">
<img width="1454" alt="Bildschirmfoto 2023-10-17 um 12 35 51" src="https://github.com/filamentphp/filament/assets/13961958/f3488517-7dcc-4d14-88cf-fb36d425eaa7">

### Expected behavior

The RichEditor field can be used as normal.

### Steps to reproduce

1. create a fresh laravel installation with filament installed
2. create a custom livewire component and adding a simple form to i as descriped in https://filamentphp.com/docs/3.x/forms/adding-a-form-to-a-livewire-component

### Reproduction repository

https://github.com/MasterOfWeb/test

### Relevant log output

```shell
In the reproduction project I get this browser error: 

Livewire Entangle Error: Livewire property ['data.description'] cannot be found on component: ['create-post'] 

In my real project I get these browser errors:
Alpine Expression Error: $wire is not defined
Uncaught ReferenceError: $wire is not defined
```

**Comment by zepfietje** [comment]
Please follow the docs and call `$this->form->fill()`.

**Comment by MasterOfWeb** [comment]
WTF?!? Why did I comment this part out? So embarrassing … 3h wasted again. 

Thanks for checking and helping!

**Comment by zepfietje** [comment]
No worries, happens to the best of us! 😄

**Comment by CodeWithPranta** [comment]
Just add your form name attibute inside $data; `public ?array $data = ['biography' => ''];`
Example of a full component outside panel with RichEditor-
`<?php

namespace App\Filament\Artisan\Pages;

use App\Models\Artisan;
use App\Models\Category;
use App\Models\City;
use App\Models\Country;
use App\Models\State;
use Filament\Actions\Action;
use Filament\Facades\Filament;
use Filament\Forms\Components\DatePicker;
use Filament\Forms\Components\FileUpload;
use Filament\Forms\Components\Grid;
use Filament\Forms\Components\RichEditor;
use Filament\Forms\Components\Select;
use Filament\Forms\Components\Textarea;
use Filament\Forms\Components\TextInput;
use Filament\Forms\Concerns\InteractsWithForms;
use Filament\Forms\Contracts\HasForms;
use Filament\Forms\Form;
use Filament\Notifications\Notification;
use Filament\Pages\Page;
use Filament\Tables\Filters\SelectFilter;
use FilamentTiptapEditor\TiptapEditor;
use FilamentTiptapEditor\Enums\TiptapOutput;


class ArtisanProfile extends Page implements HasForms
{
    use InteractsWithForms;

    protected static ?string $navigationIcon = 'heroicon-o-user';

    protected static string $view = 'filament.artisan.pages.artisan-profile';

    public ?array $data = ['biography' => ''];

    public function mount(): void
    {
        $artisanInfo = Artisan::where('user_id', Filament::auth()->user()->id)->first();

        if ($artisanInfo)
        {
            $this->form->fill($artisanInfo->attributesToArray());
        }
    }

    public function form(Form $form): Form
    {
        return $form
        ->schema([
            Grid::make([
                'default' => 1,
                'sm' => 2,
            ])
            ->schema([
                FileUpload::make('cover_photo')
                        ->label('Cover photo (16:9)')
                        ->image()
                        ->imageEditor()
                        ->imageEditorAspectRatios([
                            '16:9',
                            '4:3',
                            '1:1',
                        ])
                        ->required(),
                FileUpload::make('profile_photo')
                        ->image()
                        ->imageEditor()
                        ->imageEditorAspectRatios([
                            '16:9',
                            '4:3',
                            '1:1',
                        ])
                        ->required(),
                TextInput::make('full_name')
                  ->minLength(3)
                  ->maxLength(255)
                  ->required(),
                Select::make('category_id')
                   ->label('Service category')
                   ->options(
                    Category::orderBy('name')->pluck('name', 'id')
                   )
                   ->required(),
                TextInput::make('profession')
                    ->label('Profession (e.g. Web Developer)')
                    ->minLength(2)->required(),
                Select::make('profession_type')
                   ->options([
                    'Full-time' => 'Full-time',
                    'Part-time' => 'Part-time',
                    'Contract' => 'Contract',
                   ])
                   ->required(),
                TextInput::make('experience_in_year')
                  ->numeric()
                  ->required(),

                TextInput::make('last_education')->placeholder('e.g. Diploma in Computer Science')
                   ->label('Last educational qualification')
                   ->required(),
                DatePicker::make('date_of_birth')
                    ->minDate(now()->subYears(100))
                    ->maxDate(now()->subYear(13))
                    ->required(),
                Select::make('country_id')
                    ->label('Country')
                    ->options(Country::pluck('name', 'id')->toArray())
                    ->live()
                    ->reactive()
                    ->required(),
                Select::make('state_id')
                    ->label('Region')
                    ->options(function (callable $get){
                        $country = Country::find($get('country_id'));
                        if (!$country)
                        {
                            return [0001 => 'Select a country first'];
                        }
                        return $country->states->pluck('name', 'id');
                    })
                    ->reactive()
                    ->required(),
                Select::make('city_id')
                    ->label('City')
                    ->options(function (callable $get){
                        $state = State::find($get('state_id'));
                        if (!$state)
                        {
                            return [0001 => 'Select a region first'];
                        }
                        return $state->cities->pluck('name', 'id');
                    })
                    ->reactive()
                    ->required(),
                Textarea::make('address')->required(),
                TextInput::make('website')->url(),
                RichEditor::make('biography')
                  ->label('Write about yourself')
                  ->required()
                  ->columnSpanFull(),
            ])
        ])
        ->statePath('data');
    }

    protected function getFormActions(): array
    {
        return [
            Action::make('save')
                ->label(__('filament-panels::resources/pages/edit-record.form.actions.save.label'))
                ->submit('save'),
        ];
    }


    public function save(): void
    {
        $data = $this->form->getState();
        $userId = Filament::auth()->user()->id;
        $existingArtisanInfo = Artisan::where('user_id', $userId)->first();

        //dd($existingArtisanInfo);

        if ($existingArtisanInfo) {
            //$data['user_id'] = Filament::auth()->user()->id;
            $existingArtisanInfo->update($data);
        } else {
            $data['user_id'] = $userId;
            //dd($this->form->getState());
            Artisan::create($data);
        }

        // $data = $this->form->getState();
        // $userId = Filament::auth()->user()->id;

        // $existingArtisanInfo = Artisan::firstOrNew(['user_id' => $userId]);
        // $existingArtisanInfo->fill($data);
        // $existingArtisanInfo->save();


        Notification::make()
            ->success()
            ->title(__('filament-panels::resources/pages/edit-record.notifications.saved.title'))
            ->send();
    }
}
`

**Comment by unit-cesar** [comment]
For me, the solution was to remove `->spa()` from the Panel in `app/Providers/Filament/AdminPanelProvider.php`

I was getting warnings and errors in the console about:
`dateTimePickerFormComponent is not defined`
`richEditorFormComponent is not defined`

I don't have it anymore!
