### ISSUE TITLE
KeyValue Component should not allow duplicated keys

### ISSUE THREAD

**Issue by juliangums** [laravel-filament/filament#9142]
### Package

filament/filament

### Package Version

v3.0.78

### Laravel Version

v10.28.0

### Livewire Version

v3.0.8

### PHP Version

8.2.11

### Problem description

When entering the same key twice (or more) in a KeyValue component, only one entry is saved. This can be frustrating for users and lead to data loss without warning. I think it should throw a validation error. I tried doing it with a custom rule, however, this is not possible as the $value in the rule class is already the array which can only have one key of the same name. It needs to be done when reading the value from the input fields. I could try to extend it, but I think this seems like a bug to me and would be good to fix it for everyone.

### Expected behavior

Error message saying I can't use the same :keyLabel more than once.

### Steps to reproduce

1. Create a KeyValue component
2. Enter the same key twice with different values.
3. Hit save
4. One entry is now deleted

### Reproduction repository

https://github.com/juliangums/filament

### Relevant log output

```shell
none
```

**Comment by juliangums** [comment]
Also when keys are empty, it just deletes those rows including its value. Would be nice to get a validation message before save to make sure they are in there.

**Comment by andcarpi** [comment]
Actually, this is a JS problem... json objects and arrays does not support duplicate keys, and the "last" entry in the list keeps its value
to fix this, the component should be reworked to store the keys as parameter and not a key in the array, but in my opinion it would go against the "key" meaning...

**Comment by juliangums** [comment]
@andcarpi but you could treat it as parameters on the component and validate it as such and then transform it into a key-value array and store it that way? That way it wouldn't really go against the meaning.

Otherwise, is there an easy way to replicate the KeyValue component to be used with parameters and possible multiple columns? Basically like a repeater but in the style of the KeyValue component?

**Comment by danharrin** [comment]
No reproduction repository, and @andcarpi is right, it's a JS limitation

You can use a repeater and then transform the data before the form is filled and before its saved

**Comment by juliangums** [comment]
This is really bad UX though

**Comment by danharrin** [comment]
I don't know what you want us to do, by the time the data is in Laravel, the duplicate keys are lost

**Comment by juliangums** [comment]
@danharrin frontend validation as outlined here
> Error message saying I can't use the same :keyLabel more than once.

That way, the user is aware of the limitation. It is not obvious that duplicated keys can be created on the frontend, and they disappear when hitting save, and it leads to data loss and user frustration. Especially if the user is not a developer.

**Comment by danharrin** [comment]
Go on then, I would welcome a PR.

**Comment by juliangums** [comment]
I'd love to be of help and I had tried it previously, but it seems to be beyond my capabilities. I'm struggling. But if this stays open, maybe someone more capable will pick it up?

**Comment by ashkesarmaa** [comment]
Hi @juliangums ,

this works for me `->rules([
                            function () {
                                return function ($attribute, $value, \Closure $fail) {
                                    if (!is_array($value)) {
                                        return;
                                    }

                                    $keys = array_keys($value);

                                    // Check if there are duplicate keys
                                    $duplicates = array_diff_key(array_count_values($keys), array_unique($keys));

                                    if (!empty($duplicates)) {
                                        $fail('There are duplicate keys in your attributes.');
                                    }
                                };
                            }
                        ]),` 

I hope it helps
