### ISSUE TITLE
Disabling bulk actions for some rows should not check all records in the database table

### ISSUE THREAD

**Issue by PLGUPICTO** [laravel-filament/filament#9207]
### Package

filament/filament

### Package Version

v3.0.53

### Laravel Version

10.10

### Livewire Version

v3.0.5

### PHP Version

8.1.10  

### Problem description

When I added disable bulk action for some rows, it ran to all the records in the database table. This is okay with small records, but if we deal with thousands, the performance significantly drops.
```
->checkIfRecordIsSelectableUsing(
            fn (Model $record): bool => $record->status === Status::Enabled,
  );
```

![Screenshot_1](https://github.com/filamentphp/filament/assets/118878534/ece9a7cf-3fd8-4a46-b795-da7a4ca8e83a)

### Expected behavior

It should only apply to the current paginated limit list, in my case, the pagination is limited to 10 records. Querying the entire table record is not very performant.

### Steps to reproduce

I added this code in the OrderResource of the Filament Demo. Then I checked using the Clockwork Chrome plugin.

```
->checkIfRecordIsSelectableUsing(
                fn (Model $record): bool => $record->status === "new",
            )
```

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by danharrin** [comment]
We cannot pass each $record instance into the function without first fetching them from the database. We get all records so we can render the count for the total number of selectable records.

Try `selectCurrentPageOnly()` on the table

**Comment by devmount** [comment]
Just for your information: With the current Filament, using `checkIfRecordIsSelectableUsing` significantly increases loading time, even if the callback just returns true:

```php
->checkIfRecordIsSelectableUsing(
    fn (Model $record): bool => true,
)
```

So maybe this is worth some more investigation, if possible.
