### ISSUE TITLE
date method not worked for groups

### ISSUE THREAD

**Issue by mofashi998** [laravel-filament/filament#9209]
### Package

filament/filament

### Package Version

v3.0.53

### Laravel Version

10.10

### Livewire Version

v3.0.5

### PHP Version

8.1.10

### Problem description

`
    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                .............
                Tables\Columns\TextColumn::make('sn')->searchable(),
            ])
            ->groups([
                Tables\Grouping\Group::make('created_at')
                    ->label('Order Date')
                    ->date()    
                    ->collapsible(),
            ])
    }
`
date method not worked for groups

### Expected behavior

table   date method not worked for groups

### Steps to reproduce

`
    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                .............
                Tables\Columns\TextColumn::make('sn')->searchable(),
            ])
            ->groups([
                Tables\Grouping\Group::make('created_at')
                    ->label('Order Date')
                    ->date()    
                    ->collapsible(),
            ])
    }
`
date method not worked for groups

### Reproduction repository

https://github.com/filamentphp/demo

### Relevant log output

```shell
No response
```

**Comment by zepfietje** [comment]
Please provide a real reproduction repository and clearly describe how the experienced behavior is different than what you'd expect.
