### ISSUE TITLE
Hiding fields based on page needs Pages\EditUser not just EditUser

### ISSUE THREAD

**Issue by BrendanTWhite** [laravel-filament/filament#923]
### Package

filament/filament

### Package Version

v2.5.31

### Laravel Version

v8.76.2

### Livewire Version

v2.8.2

### PHP Version

PHP Version 8.1.0 Build Date Nov 28 2021 01:42:05

### Bug description

In the documentation for "[Hiding components based on the page](https://filamentadmin.com/docs/2.x/admin/resources#hiding-components-based-on-the-page)", it says we can hide the `password` field on the `EditUser` page like this:

```php
->hidden(fn (Component $livewire): bool => $livewire instanceof EditUser)
```

But in my project this is actually checking if the Component is an instance of `App\Filament\Resources\EditUser` - which it never is.

My  current workaround is to check like this instead, specifying that `EditUser` is in `Pages`:

```php
->hidden(fn (Component $livewire): bool => $livewire instanceof Pages\EditUser)
```

Similarly, I'm changing `->visible(fn (Component $livewire): bool => $livewire instanceof CreateUser)` to `->visible(fn (Component $livewire): bool => $livewire instanceof Pages\ CreateUser)` for the same reason.

Either I'm doing something wrong (which is always possible!), or the documentation is slightly incorrect. 

### Steps to reproduce

Just follow the documentation for "[Hiding components based on the page](https://filamentadmin.com/docs/2.x/admin/resources#hiding-components-based-on-the-page)" in a fresh filament install

**Comment by danharrin** [comment]
Sorry, I probably didn't make it clear that the class needs importing. I'll add it to the docs.

**Comment by BrendanTWhite** [comment]
Thanks.

**Comment by BrendanTWhite** [comment]
Thanks @danharrin.  I would be happy do a PR but I couldn't find "Hiding components based on the page" in the [filamentadmin.com repo ](https://github.com/laravel-filament/filamentadmin.com)... is it in a database perhaps? 

Anyway, I'm really happy to do a PR if that helps, if someone can point me to the right file.

**Comment by danharrin** [comment]
I've already done it, just need to redeploy the site :)

**Comment by danharrin** [comment]
Btw - the docs are in the /docs directory of each package.

**Comment by BrendanTWhite** [comment]
> I've already done it, just need to redeploy the site :)

You, sir, are a champion.  Many thanks!

**Comment by BrendanTWhite** [comment]
> Btw - the docs are in the /docs directory of each package.

Well, that's embarrassing! I'll look harder next time.  :-)

**Comment by danharrin** [comment]
No worries ahah! Enjoy the rest of your day.
