### ISSUE TITLE
EditAction record() closure does not receive arguments reliably

### ISSUE THREAD

**Issue by jacksleight** [laravel-filament/filament#9234]
### Package

filament/filament

### Package Version

3.0.82

### Laravel Version

10.28.0

### Livewire Version

3.0.10 

### PHP Version

8.2.11

### Problem description

I'm using the `Filament\Actions\EditAction` on a custom panel page, as I want to be able to edit certain records directly from this custom page rather than via the usual resource pages. I'm passing the record ID's as an argument through to the action as per [these docs](https://filamentphp.com/docs/3.x/actions/adding-an-action-to-a-livewire-component#passing-action-arguments).

Here's my action:

```php
return EditAction::make()
    ->record(function (array $arguments) {
        return Client::find($arguments['client']);
    })
    ->form([
        Forms\Components\TextInput::make('name')
            ->required(),
    ]);
```
```blade
{{ ($this->editAction)(['client' => $client->id]) }}
```

When the modal opens an error is thrown:

```
Undefined array key "client"
```

The `record()` closure is being called five times (see dump below), and on the fifth call the `$arguments` array is empty for some reason, causing this error.

### Dump:

![Screenshot 2023-10-21 at 14 13 46](https://github.com/filamentphp/filament/assets/126740/b667c819-5f9e-4dec-9d9b-155e05ef017d)

### Expected behavior

When clicking on the button the modal should open, allowing you to edit and save the record.

### Steps to reproduce

1. Go to the Example page
2. Open one of the modals by clicking an Edit button

### Reproduction repository

https://github.com/jacksleight/filament-edit-action

**Comment by zepfietje** [comment]
I've fixed this in the docs: https://github.com/filamentphp/filament/commit/1d14468b98243f778df3a5ade25ba89812eb3f81.

**Comment by jacksleight** [comment]
Thanks @zepfietje! I've updated the description and reproduction repo to match.

**Comment by zepfietje** [comment]
Thanks, Jack.

**Comment by wychoong** [comment]
i think this is the same issue https://github.com/filamentphp/filament/issues/8763

**Comment by zepfietje** [comment]
Seems like it is. Will close this as dupe.
