### ISSUE TITLE
not working on env production or development

### ISSUE THREAD

**Issue by emreakay** [laravel-filament/filament#924]
### Package

filament/filament

### Package Version

v2

### Laravel Version

v8

### Livewire Version

v2

### PHP Version

8.0

### Bug description

/admin page is not rendering if APP_ENV is not local

**Comment by danharrin** [comment]
Hey, check out [this page in the docs](https://filamentadmin.com/docs/2.x/admin/users).

**Comment by emreakay** [comment]
thanks @danharrin
