### ISSUE TITLE
Add Default Value For  InputText In Custom Page

### ISSUE THREAD

**Issue by jrpikong** [laravel-filament/filament#9273]
### Package

filament/filament

### Package Version

v3.0.0

### Laravel Version

v10.0.0

### Livewire Version

v3.0.0

### PHP Version

PHP 8.2

### Problem description

Hi, I have new page wit type custom page, 
I want to add new TextInput with default value.

`class AddBudgetPlanner extends Page implements HasForms
{
    use InteractsWithForms, InteractsWithActions, HasPageSidebar;

    protected static string $resource = BranchResource::class;
    protected static string $view = 'filament.resources.branch-resource.pages.create-budget-planner';
    public Branch $record;
    protected static ?string $model = Branch::class;

    protected static ?string $navigationGroup = 'Budget planner';
    protected static ?string $navigationLabel = 'Add Budget Planner';

    public function getBreadcrumb(): ?string
    {
        return __('Manage Branch Budget Planner');
    }

    public function form(Form $form): Form
    {
        return $form->schema([
            \Filament\Forms\Components\TextInput::make('code')->default('some value'),
        ]);
    }`
    
    
    But TextInput not show my defailt value, I have done trype with another option implement with `afterStateHydrated` but still not work .

### Expected behavior

Exptected to show default value in TextInput like in create or edit page. 

### Steps to reproduce

Add TextInput and set ->default()

### Reproduction repository

https://github.com/jrpikong/learnFilament

**Comment by sumardi** [comment]
Not a filament issue. Your code missing state. Read the docs: https://filamentphp.com/docs/3.x/forms/adding-a-form-to-a-livewire-component#adding-the-form
