### ISSUE TITLE
Method Filament\Forms\Components\FileUpload::deletable does not exist.

### ISSUE THREAD

**Issue by lourbert** [laravel-filament/filament#9290]
### Package

filament/filament

### Package Version

v3

### Laravel Version

v10

### Livewire Version

v3

### PHP Version

PHP 8.2

### Problem description

Method Filament\Forms\Components\FileUpload::deletable does not exist.

### Expected behavior

delete the Uploaded File

### Steps to reproduce

![delete](https://github.com/filamentphp/filament/assets/143614407/106534d5-826c-42dc-bb3d-fce55dd3280b)

### Reproduction repository

https://github.com/lourbert/student_management.git

**Comment by petrisorcraciun** [comment]
Reproduction repository is not available

**Comment by zepfietje** [comment]
Also we need exact framework versions.

Please provide those and a public reproduction repo, then we can reopen.

**Comment by bayprogrammer** [comment]
@lourbert I was having this issue too. It looks like the `::deletable()` method was added to `BaseUploadFile` with version [`v3.0.39`](https://github.com/filamentphp/filament/blob/v3.0.39/packages/forms/src/Components/BaseFileUpload.php#L221) (I was still on `v3.0.32`). Updating to the latest version fixed the issue for me.
