### ISSUE TITLE
Wrong indicator in SelectFilter with multiple and translatable field

### ISSUE THREAD

**Issue by buzkall** [laravel-filament/filament#9292]
### Package

filament/filament

### Package Version

v3.0.83

### Laravel Version

v10.29.0

### PHP Version

PHP 8.2.11

### Problem description

When using a SelectFilter in a table with a relationship and the option **multiple**, if the field is translatable, it will show the json in the indicator
The indicator of a filter without multiple, will work the way it's supposed to.

### Expected behavior

To show the name in the active locale

### Steps to reproduce

Install the linked repo. Migrate and seed
The filters are already created in the user resource.
The admin panel's path is /

![2](https://github.com/filamentphp/filament/assets/5702/25d35a5b-8ca5-4a07-825f-2258eda7320f)

### Reproduction repository

https://github.com/buzkall/filament-indicator-translatable-multiple

**Comment by NaungYeHtet** [comment]
+1

**Comment by buzkall** [comment]
Debugging the indicateUsing callback in the SelectFilter I've seen that the pluck to get the names is done with: 
```
$relationshipQuery->qualifyColumn($filter->getRelationshipTitleAttribute())
```
which will make the pluck with something like "tableName.columnName" and that returns the Spatie's translatable json, but if we do the pluck without the qualifyColumn, just with:

```
$filter->getRelationshipTitleAttribute()
```
it will return just the names, and not the json.

Why it's necessary the qualifyColumn function?

**Comment by danharrin** [comment]
Bug in Laravel: laravel/framework#49288

**Comment by zsoltgombocz** [comment]
Hi, I am just curious that this should be resolved by now right? 
PHP: 8.2
Laravel: 10.48.14
Filament: 3.2.92

Having the same issue.

Thanks for the answer in advance.

**Comment by danharrin** [comment]
It is fixed in Laravel 11 as per https://github.com/laravel/framework/pull/49288
