### ISSUE TITLE
Each character automatically becoming tags when pasting in a TagsInput

### ISSUE THREAD

**Issue by NaungYeHtet** [laravel-filament/filament#9313]
### Package

filament/filament

### Package Version

v3.0.0

### Laravel Version

v10.10

### PHP Version

8.2

### Problem description

When pasting texts into the TagsInput field, every character of the text becomes a tag.

<img width="594" alt="image" src="https://github.com/filamentphp/filament/assets/49832780/a8b07395-9231-40e8-99ae-cf8d3c85f283">

### Expected behavior

Pasted text will be a single tag

### Steps to reproduce

Copy some texts and paste into the TagsInput field.

### Reproduction repository

https://github.com/NaungYeHtet/filament-ascept-ratio

**Comment by zepfietje** [comment]
Thanks for reporting! Fixed by https://github.com/filamentphp/filament/commit/78f9a7b4c12462d457755ea780d84874bc382f8a.

Let us know if you still experience any problems after the next update.
