### ISSUE TITLE
Filters' visibility issue when depending on activeTab

### ISSUE THREAD

**Issue by tiagof** [laravel-filament/filament#9324]
### Package

filament/filament

### Package Version

v3.0.84

### Laravel Version

v.10.29

### PHP Version

PHP 8.2

### Problem description

A table filter's visibility that's dependant on the activeTab does not work - or, to be precise, the visibility only changes in the next livewire cycle.

### Expected behavior

The filter's visibility is correctly applied.

### Steps to reproduce

Clone the repo, go to the MyModels page and switch to the tab "b": the filter is not hidden as it should.
Click the tab "b" again, the filter now disappears.

Switch tabs multiple times as see the behiavour of the "only on tab 'A'" filter...

Alternatively, in a resource's List page:

```php
class ListMyResource extends ListRecords
{
    public function getTabs(): array
    {
        return [
            'A' => Tab::make('a')->modifyQueryUsing(fn (Builder $query) => $query),
            'B' => Tab::make('b')->modifyQueryUsing(fn (Builder $query) => $query),
        ];
    }
}
```

in your Resource:

```php
class MyModelResource extends Resource
{
    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                //
            ])
            ->filters([
                Tables\Filters\Filter::make('always_visible'),
                Tables\Filters\Filter::make('only on tab "A"')
                    ->visible(fn(Component $livewire): bool => $livewire->activeTab === 'A'),
            ], layout: Tables\Enums\FiltersLayout::AboveContent);
    }
}
```

### Reproduction repository

https://github.com/tiagof/filament-bugs-report/tree/filter-visibility

**Comment by danharrin** [comment]
The reproduction repository is not public, please fix that.

**Comment by tiagof** [comment]
That's a noob mistake 😅
Done.

**Comment by danharrin** [comment]
Thank you!

**Comment by danharrin** [comment]
In `afterActiveTabUpdated()`: `$this->resetTable()`

**Comment by tiagof** [comment]
Thanks!

For reference, we must use the new (livewire v3) hook which is `updatedActiveTab()`instead of the old `activeTabUpdated()`.

Full code for future reference:

```php
class ListMyResource extends ListRecords
{
    public function getTabs(): array
    {
        return [
            'A' => Tab::make('a')->modifyQueryUsing(fn (Builder $query) => $query),
            'B' => Tab::make('b')->modifyQueryUsing(fn (Builder $query) => $query),
        ];
    }

    public function updatedActiveTab(): void
    {
        $this->resetTable();
    }
}
```

**Comment by theofanisv** [comment]
**In v3.3.3 this is not enough**. (and possibly older versions) 

`\Filament\Tables\Concerns\InteractsWithTable::bootedInteractsWithTable` is run on boot which contains 
```php
$this->cacheForm('tableFiltersForm', $this->getTableFiltersForm());
```
This makes the form being cached on boot meaning **before** the `updatedActiveTab()` is run.
So when the filter form is evaluated the `visible(fn(Component $livewire) ...)`/`hidden(...)` on each field sees the old value of `$livewire->activeTab`.

My workaround is to invalidate the cache form.

```php
    public function updatedActiveTab(): void
    {
        parent::updatedActiveTab();

        $this->cacheForm('tableFiltersForm', null); // Invalidate
        $this->cacheForm('tableFiltersForm', $this->getTableFiltersForm()); // Cache fresh instance with correct `$filter->visible(...)` 
    }
```

**Comment by danharrin** [comment]
@theofanisv where are you calling `resetTable()` in your code?

**Comment by theofanisv** [comment]
I am not calling it. It is in the standard place `\Filament\Resources\Concerns\HasTabs::updatedActiveTab` (`vendor/filament/filament/src/Resources/Concerns/HasTabs.php:49`) as inherited from `\Filament\Resources\Pages\ListRecords`

During my debugging, I found this is the sequence that produces the problem.

```
- incoming filament request

- vendor/filament/tables/src/Concerns/InteractsWithTable.php:60
  `$this->cacheForm('tableFiltersForm', $this->getTableFiltersForm());`

- vendor/filament/tables/src/Concerns/HasFilters.php:32
  `schema($this->getTable()->getFiltersFormSchema())`

- vendor/filament/tables/src/Table/Concerns/HasFilters.php:184
  `foreach ($this->getFilters() as $filterName => $filter) {`

- vendor/filament/tables/src/Table/Concerns/HasFilters.php:156
  `fn (BaseFilter $filter): bool => $filter->isVisible(),`

- `$filter->visible(fn(Component $livewire) =>$livewire->activeTab == ...)` is validated that sees the old `activeTab`
```

**Comment by danharrin** [comment]
`updatedActiveTab()` calls `resetPage()`, not `resetTable()`. `resetTable()` clears the cached forms. Please read all of the above thread very carefully.

**Comment by theofanisv** [comment]
You are right, I tried and it works. So sorry for the troubles.

**Comment by dharen008** [comment]
This help me a lot! thanks!
