### ISSUE TITLE
error when using sushi/sqlite with summaries

### ISSUE THREAD

**Issue by wychoong** [laravel-filament/filament#9347]
### Package

filament/filament

### Package Version

3.0.85

### Laravel Version

10.28.0

### Livewire Version

3.0.10

### PHP Version

8.2.11

### Problem description

"SQLSTATE[HY000]: General error: 1 near ".": syntax error" when using summaries in table using Sushi model

### Expected behavior

no error

### Steps to reproduce

clone the repo, open Sales menu

### Reproduction repository

https://github.com/wychoong/filament-test/tree/sqlite-summaries

### Relevant log output

```shell
https://flareapp.io/share/dmk3Zdwm
```

**Comment by danharrin** [comment]
Since this is a SQL error, can you work out what the SQL needs to be instead for this to work with Sushi? I'm feeling like this isn't going to be fixable on the Filament end.

**Comment by wychoong** [comment]
> Since this is a SQL error, can you work out what the SQL needs to be instead for this to work with Sushi? I'm feeling like this isn't going to be fixable on the Filament end.

I will try with plain SQLite, if it’s Sushi only issue I don’t think it’s worth the effort.

**Comment by wychoong** [comment]
its only with Sushi

**Comment by khalidmaquilang** [comment]
Any update on this?

**Comment by t-poeschl** [comment]
We have same issue

**Comment by danharrin** [comment]
Maybe addressed in #15293
