### ISSUE TITLE
UX problem in table empty state

### ISSUE THREAD

**Issue by ariaieboy** [laravel-filament/filament#9353]
### Package

filament/tables

### Package Version

v3.x

### Laravel Version

v10.x

### Livewire Version

v3.x

### PHP Version

8.x

### Problem description

When we use the individual search on table columns, if the search result is empty, the individual search field disappears and we need to remove the active filter from the header so the fields come back.
It's super annoying especially when we have a typo and we need to edit our search query.

### Expected behavior

The search fields should be visible in all conditions.

### Steps to reproduce

1. go to the demo app of filament 
2. open customer page https://demo.filamentphp.com/shop/customers
3. search something that does not have any results in individual search
4. the individual search fields disappear

![image](https://github.com/filamentphp/filament/assets/15873972/259a9e3d-2d5c-4a04-bfdc-4194a11e563a)
![image](https://github.com/filamentphp/filament/assets/15873972/750e8daf-b457-414b-9e4b-a974c06b66b4)

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by danharrin** [comment]
Hey, this is not going to happen. We remove the entire `<table>` element from the empty state, and without that we would not be able to render the inputs in columns. This is not a bug. You may set the `$table->emptyState()` to your own custom view to render the columns if you wish.

**Comment by ariaieboy** [comment]
@danharrin 
I know it is not a bug and its intended behavior.
But as I explained as UX perspective, it has serious problems.
If it was a selectable filter or a checkbox, removing the filter from the header was a good option.
But since it's a user input field, it's so annoying.
Sometimes, while I am typing, it refreshes the table, and since I have a typo in my search query, the fields disappear, and I need to remove the filter from the header so I can start typing from the beginning again.
At least we can introduce a config to change the update process from live to defer. so the search only applies when the user presses enter.

**Comment by ariaieboy** [comment]
@danharrin 
Just watch this video and see what happens when I want to search the word `example` in the search field.
I can type slowly, or my connection might not be reliable.
[screen-capture.webm](https://github.com/filamentphp/filament/assets/15873972/39c486ae-824c-4ff6-a7d2-dd0078d49540)

**Comment by danharrin** [comment]
Sure, you can PR a lazySearch() option or something for the $table

**Comment by danharrin** [comment]
Sure, you can PR a lazySearch() option or something for the $table

**Comment by muhammadALdali** [comment]
1. Extend the Table Configuration in Your Resource
In your table() method of a Filament Resource, add the following code to define which columns are searchable and to inject them into a custom empty state view.
public static function table(Table $table): Table
{
    $searchableColumns = ['fullname', 'username', 'email', 'phone'];

    return $table
        ->emptyState(view('tables.empty-state', [
            'columns' => $table->getColumns(),
            'hasFilters' => $table->getFilters() !== [],
            'searchableColumns' => $searchableColumns,
        ]))
        ->columns([
            // Define your columns here
        ]);
}

 Create a Custom Blade View for the Table
Create a Blade file at resources/views/tables/empty-state.blade.php. This view will contain the full HTML for the table, including:

Table headers based on the $columns array.

A row with search inputs under each searchable column.

A dummy row (placeholder row) that appears when the table has no data.

Use the following @props directive to receive the necessary data:




@props([
    'columns',
    'hasBulkActions' => false,
    'hasFilters' => false,
    'searchableColumns' => [],
])

<table class="fi-ta-table w-full table-auto divide-y divide-gray-200 text-start dark:divide-white/5">
    <thead class="divide-y divide-gray-200 dark:divide-white/5">
        <tr class="bg-gray-50 dark:bg-white/5">
            @if($hasBulkActions)
                <th class="fi-ta-cell p-0 first-of-type:ps-1 last-of-type:pe-1 sm:first-of-type:ps-3 sm:last-of-type:pe-3 fi-ta-selection-cell w-1">
                    <div class="px-3 py-4">
                        <label class="flex">
                            <input type="checkbox" class="fi-checkbox-input" disabled>
                            <span class="sr-only">Select/deselect all items for bulk actions.</span>
                        </label>
                    </div>
                </th>
            @endif

            @foreach($columns as $column)
                <th class="fi-ta-header-cell px-3 py-3.5 sm:first-of-type:ps-6 sm:last-of-type:pe-6">
                    <span class="group flex w-full items-center gap-x-1 whitespace-nowrap justify-start">
                        <span class="fi-ta-header-cell-label text-sm font-semibold text-gray-950 dark:text-white">
                            {{ $column->getLabel() }}
                        </span>
                    </span>
                </th>
            @endforeach

            @if($hasFilters)
                <th aria-label="Actions" class="fi-ta-actions-header-cell w-1"></th>
            @endif
        </tr>
    </thead>

    <tbody class="divide-y divide-gray-200 whitespace-nowrap dark:divide-white/5">
        
        <tr class="fi-ta-row [@media(hover:hover)]:transition [@media(hover:hover)]:duration-75">
            @if($hasBulkActions)
                <td></td>
            @endif

            @foreach($columns as $column)
                @php
                    $isSearchable = in_array($column->getName(), $searchableColumns);
                    $columnName = $column->getName();
                @endphp

                <td class="fi-ta-cell p-0 first-of-type:ps-1 last-of-type:pe-1 sm:first-of-type:ps-3 sm:last-of-type:pe-3 fi-table-individual-search-cell-{{ $columnName }} min-w-48 px-3 py-2">
                    @if($isSearchable)
                        <div x-id="['input']" class="fi-ta-search-field">
                            <label x-bind:for="$id('input')" class="sr-only" for="input-{{ $columnName }}">
                                {{ $column->getLabel() }}
                            </label>

                            <div class="fi-input-wrp flex rounded-lg shadow-sm ring-1 transition duration-75 bg-white dark:bg-white/5 [&:not(:has(.fi-ac-action:focus))]:focus-within:ring-2 ring-gray-950/10 dark:ring-white/20 [&:not(:has(.fi-ac-action:focus))]:focus-within:ring-primary-600 dark:[&:not(:has(.fi-ac-action:focus))]:focus-within:ring-primary-500">
                                <div class="fi-input-wrp-prefix items-center gap-x-3 ps-3 flex pe-2">
                                    <svg wire:loading.remove.delay.default="1" wire:target="tableColumnSearches.{{ $columnName }}" class="fi-input-wrp-icon h-5 w-5 text-gray-400 dark:text-gray-500" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true" data-slot="icon">
                                        <path fill-rule="evenodd" d="M9 3.5a5.5 5.5 0 1 0 0 11 5.5 5.5 0 0 0 0-11ZM2 9a7 7 0 1 1 12.452 4.391l3.328 3.329a.75.75 0 1 1-1.06 1.06l-3.329-3.328A7 7 0 0 1 2 9Z" clip-rule="evenodd"></path>
                                    </svg>
                                    <svg fill="none" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" class="animate-spin fi-input-wrp-icon h-5 w-5 text-gray-400 dark:text-gray-500" wire:loading.delay.default="" wire:target="tableColumnSearches.{{ $columnName }}">
                                        <path clip-rule="evenodd" d="M12 19C15.866 19 19 15.866 19 12C19 8.13401 15.866 5 12 5C8.13401 5 5 8.13401 5 12C5 15.866 8.13401 19 12 19ZM12 22C17.5228 22 22 17.5228 22 12C22 6.47715 17.5228 2 12 2C6.47715 2 2 6.47715 2 12C2 17.5228 6.47715 22 12 22Z" fill-rule="evenodd" fill="currentColor" opacity="0.2"></path>
                                        <path d="M2 12C2 6.47715 6.47715 2 12 2V5C8.13401 5 5 8.13401 5 12H2Z" fill="currentColor"></path>
                                    </svg>
                                </div>

                                <div class="fi-input-wrp-input min-w-0 flex-1">
                                    <input
                                        class="fi-input block w-full border-none py-1.5 text-base text-gray-950 transition duration-75 placeholder:text-gray-400 focus:ring-0 disabled:text-gray-500 disabled:[-webkit-text-fill-color:theme(colors.gray.500)] disabled:placeholder:[-webkit-text-fill-color:theme(colors.gray.400)] dark:text-white dark:placeholder:text-gray-500 dark:disabled:text-gray-400 dark:disabled:[-webkit-text-fill-color:theme(colors.gray.400)] dark:disabled:placeholder:[-webkit-text-fill-color:theme(colors.gray.500)] sm:text-sm sm:leading-6 bg-white/0 ps-0 pe-3"
                                        autocomplete="off"
                                        maxlength="1000"
                                        placeholder="{{ $column->getLabel() }}"
                                        type="search"
                                        wire:key="{{ $columnName }}.search.input"
                                        wire:model.live.debounce.300ms="tableColumnSearches.{{ $columnName }}"
                                        x-bind:id="$id('input')"
                                        x-on:keyup="if ($event.key === 'Enter') { $wire.$refresh() }"
                                        id="input-{{ $columnName }}"
                                        @if(!$isSearchable) disabled @endif
                                    >
                                </div>
                            </div>
                        </div>
                    @endif
                </td>
            @endforeach

            @if($hasFilters)
                <td></td>
            @endif
        </tr>

        
        <tr class="fi-ta-row">
            @if($hasBulkActions)
                <td class="fi-ta-cell p-0 first-of-type:ps-1 last-of-type:pe-1 sm:first-of-type:ps-3 sm:last-of-type:pe-3">
                    <div class="px-3 py-4">
                        <input type="checkbox" class="fi-checkbox-input" disabled>
                    </div>
                </td>
            @endif

            @foreach($columns as $column)
                <td class="fi-ta-cell p-0 first-of-type:ps-1 last-of-type:pe-1 sm:first-of-type:ps-3 sm:last-of-type:pe-3 px-3 py-4">
                    <div class="text-sm text-gray-500 dark:text-gray-400">
                        --
                    </div>
                </td>
            @endforeach

            @if($hasFilters)
                <td class="fi-ta-actions-cell p-0 first-of-type:ps-1 last-of-type:pe-1 sm:first-of-type:ps-3 sm:last-of-type:pe-3"></td>
            @endif
        </tr>
    </tbody>
</table>
