### ISSUE TITLE
Searchable select not outputting value in wizard on page

### ISSUE THREAD

**Issue by brain82** [laravel-filament/filament#9377]
### Package

filament/forms

### Package Version

v3.0.88

### Laravel Version

v10.29.0

### Livewire Version

v3.0.10

### PHP Version

PHP 8.2.11

### Problem description

When a select form element is set to searchable in a wizard, the value is not output.

<img width="781" alt="image" src="https://github.com/filamentphp/filament/assets/6013683/ad7d5372-b9dc-404a-94cc-4d089693b726">

<img width="945" alt="ui-screenshot" src="https://github.com/filamentphp/filament/assets/6013683/043a1a81-c73d-4d2f-a840-60b34823ec79">

<img width="471" alt="dd-screenshot" src="https://github.com/filamentphp/filament/assets/6013683/5872d22b-3dba-4834-b0e0-ab25317dc762">

### Expected behavior

Expected output below.

<img width="455" alt="dd-expected-screenshot" src="https://github.com/filamentphp/filament/assets/6013683/1ae3be55-2e96-4fb8-9c03-162dd6f3db88">

### Steps to reproduce

1. Clone the repository
2. Navigate to the wizard page 
3. Select a customer and enter a note
4. Click the next button

### Reproduction repository

https://github.com/brain82/filament-bug

**Comment by zepfietje** [comment]
Please read the docs and call `$this->form->fill()`.

**Comment by sezohessen** [comment]
Same issue in table
