### ISSUE TITLE
Autofocus not working on createOptionForm

### ISSUE THREAD

**Issue by pablozagni** [laravel-filament/filament#9382]
### Package

filament/filament

### Package Version

^3.0-stable

### Laravel Version

^10.10

### Livewire Version

^3

### PHP Version

^8.1

### Problem description

Autofocus doesn't work on createOptionForm

     return $form
            ->schema([
                TextInput::make('name')
                    ->autofocus()
                    ->label('Nombre')
                    ->required(),
                Select::make('sector_id')
                    ->label('Sector')
                    ->options(Sector::orderBy('name')->pluck('name', 'id'))
                    ->searchable()
                    ->required()
                    ->createOptionForm([
                        TextInput::make('name')
                            ->label('Nombre')
                            ->autofocus()
                            ->unique(ignoreRecord: true)
                            ->required(),
                    ]),
            ]);

### Expected behavior

Cursor on text input after modal pop up

### Steps to reproduce

None

### Reproduction repository

none

**Comment by amandine16** [comment]
I have the same request
