### ISSUE TITLE
FilterLayout dropdown issue in table

### ISSUE THREAD

**Issue by valpuia** [laravel-filament/filament#9388]
### Package

filament/filament

### Package Version

3.0.88

### Laravel Version

10.29

### Livewire Version

3.0.10

### PHP Version

8.2

### Problem description

When using `FiltersLayout` with `Select` and when that table have small data then the select option is not clearly visible.

If `FiltersLayout::AboveContent` is used then this is the result

![Screenshot from 2023-10-31 16-48-10](https://github.com/filamentphp/filament/assets/28250303/e5107c69-d425-4b9e-ac78-bce855e1c455)
If `FiltersLayout::BelowContent` is used then this is the result

![Screenshot from 2023-10-31 16-53-10](https://github.com/filamentphp/filament/assets/28250303/1fba8c3d-419b-4426-84d4-0348c70ac430)

### Expected behavior

Expecting to clearly seen the select option data when using FilterLayout with small or big data

### Steps to reproduce

Clone, install
Migrate with seed
login using `admin@example.com` and `password` credentials
Go to User, and check the filter.

Note: I'll just put `FiltersLayout::BelowContent` for now, you can change to `AboveContent` to check other issue

### Reproduction repository

https://github.com/valpuia/fila-dropdown

**Comment by zepfietje** [comment]
I don't think there's much we can do here, as the table container needs `overflow-hidden`.
Let us know if you think there is a way to work around this though.

**Comment by valpuia** [comment]
> I don't think there's much we can do here, as the table container needs `overflow-hidden`. Let us know if you think there is a way to work around this though.

But without `->searchable()` it's showing like below, hope we can display like this.

![Screenshot from 2023-11-01 09-04-40](https://github.com/filamentphp/filament/assets/28250303/79104ca8-adb2-4e84-872f-8b9c4fa12e6a)
![Screenshot from 2023-11-01 09-04-23](https://github.com/filamentphp/filament/assets/28250303/199e14fb-edba-4459-bb1b-41735403e641)

**Comment by zepfietje** [comment]
That's because that's the native `<select>` which is handled by the browser/OS.
