### ISSUE TITLE
Custom Create action button does not work in getHeaderActions

### ISSUE THREAD

**Issue by framansi** [laravel-filament/filament#9391]
### Package

filament/filament

### Package Version

v3.0.0

### Laravel Version

v10.10

### Livewire Version

v3.0.0

### PHP Version

PHP 8.2.11

### Problem description

I inserted an action button in the 'getHeaderActions' method, but when I try to load an image, the variable 'isUploadingFile' is not triggered:

```
Action::make('create')
->label(__('filament-panels::resources/pages/create-record.form.actions.create.label'))
->action('create')
->keyBindings(['command+s', 'ctrl+s']),
```

If, instead, I replace `->action()` with `->submit()`, nothing happens because the submit button is outside the form:

```
Action::make('create')
->label(__('filament-panels::resources/pages/create-record.form.actions.create.label'))
->submit('create')
->keyBindings(['command+s', 'ctrl+s']),
```

### Expected behavior

The expected result is that in `->action('create')` you can inherit all the functionality of the submit button in the form

### Steps to reproduce

1 - Add the getHeaderActions method in CreateResource;
2 - Insert a custom Action as follows: 
```
Action::make('create')
->label(__('filament-panels::resources/pages/create-record.form.actions.create.label'))
->create('create')
->keyBindings(['command+s', 'ctrl+s']),
```
3. Try clicking on the button in the form

### Reproduction repository

https://github.com/framansi/filament-cms/blob/master/app/Filament/Resources/PostResource/Pages/CreatePost.php

**Comment by zepfietje** [comment]
Honestly, this isn't a bug as the `isUploadingFile` variable is set on the form.
So I'll close this issue, but will ask @danharrin for any suggestions.

**Comment by danharrin** [comment]
Yeah this isn't a bug, when you introduce a custom feature you are the one introducing the limitation
