### ISSUE TITLE
Table's `reorderable` is not configurable

### ISSUE THREAD

**Issue by Reinbier** [laravel-filament/filament#9420]
### Package

filament/filament

### Package Version

v3.0.88

### Laravel Version

v10.30.1

### Livewire Version

v3.0.10

### PHP Version

PHP 8.2.9

### Problem description

In my project all my models utilize Spatie's [SortableTrait](https://github.com/spatie/eloquent-sortable).

Thererfore, i'd like my resources to have reordering enabled by default. Since the `Filament\Tables\Table` is configurable I put the following code in the boot method of my `AppServiceProvider`:

```php
use Filament\Tables\Table;

public function boot(): void
{
    Table::configureUsing(function(Table $table) {
        $table
            ->reorderable('order_column')
            ->defaultSort('order_column', 'desc');
    });
}
```

The defaultSort() is being applied correctly, however the icon for reordering doesn't show and reordering is not enabled.

### Expected behavior

I expect all resources would be reorderable.

### Steps to reproduce

Please install the repository below and see that the configuration is not working as expected.

Make sure to:
- migrate + seed database
- login using email+pw:
  - test@example.com
  - test

### Reproduction repository

https://github.com/Reinbier/filament-auto-reorderable-bug

**Comment by danharrin** [comment]
Fixed by #10191.
