### ISSUE TITLE
CreateRecord wizard navbar and page UI bugs

### ISSUE THREAD

**Issue by JUEChristopher** [laravel-filament/filament#9426]
### Package

filament/filament

### Package Version

v3.0.88

### Laravel Version

v10.30.1

### Livewire Version

v3.0.10

### PHP Version

PHP 8.1

### Problem description

I wanted to implement a wizard for creating records of a resource, so I followed this section of the documentation:

https://filamentphp.com/docs/3.x/panels/resources/creating-records#using-a-wizard

Everything is functioning correctly from a logical standpoint. However, I am encountering several UI issues.

The first problem is that the navigation bar breaks when I scroll, which is likely related to the second problem. The sidebar within the navigation bar becomes fixed after a certain point in scrolling.

![image](https://github.com/filamentphp/filament/assets/78968379/5421cf58-cb40-4a5f-ba81-b51707a1b150)

The second problem is that the page height is excessively long for no apparent reason, resulting in a large white space below the content. It appears that subsequent steps following an initial long step have the same height, even if their content is shorter.

![image](https://github.com/filamentphp/filament/assets/78968379/4d9a39b4-e9b5-4d0e-8212-f132c331343a)

### Expected behavior

I expect the navigation bar to remain fixed in its entirety when I scroll through the wizard steps, and for the page height to adjust according to the size of the step's content.

### Steps to reproduce

To reproduce these bugs, simply open the create form for the resource in the provided reproduction repository below and proceed to the second step (after completing the fields in the first step, of course). While on the second step, you can observe all the bugs (this also applies to the 3rd step, as its content is smaller than the first step). You can also return to the first step, and when you scroll all the way to the bottom, you'll encounter the navigation bar bug. This issue is not present before you navigate to the second step for the first time.

### Reproduction repository

https://github.com/JUEChristopher/wizard_ui_bugs

**Comment by JUEChristopher** [comment]
Hi, is it possible to change the priority please ? Because I don't think its a low one @zepfietje

**Comment by zepfietje** [comment]
I haven't been able to reproduce this issue yet.
Could you provide more info about OS and browsers you've tested?
Makes it easier for us to look into.

**Comment by JUEChristopher** [comment]
Ah ok, its weird. I'm on Windows 11 and I have this problem with Chrome, Opera and Edge (not really important for Edge ...), but nothing when using Firefox suprisingly.
