### ISSUE TITLE
Wrong colors on linechart tooltip

### ISSUE THREAD

**Issue by bernhardh** [laravel-filament/filament#9462]
### Package

filament/filament

### Package Version

v3.0.89

### Laravel Version

v10.30.1

### Livewire Version

v3.1.0

### PHP Version

8.1.25

### Problem description

When setting `backgroundColor` to a linechart `dataset`, the color is used in the legend, but not in the tooltip. The `borderColor` is used in both:

```php
[
    'label' => 'Blue',
    'data' => [...],
    "backgroundColor" => "blue",
    'borderColor' => "blue"
],
```

![image](https://github.com/filamentphp/filament/assets/642292/1e5ed3e5-3aa9-4b0e-95ed-d7304a75efa9)

When changing diagram type to `bar` chart

```php
    protected function getType(): string
    {
        return 'bar';
    }
```

both are shown correct:

![image](https://github.com/filamentphp/filament/assets/642292/b2ce4931-3d98-45d4-b2bb-053237020f9e)

Btw. same goes for pie and Doughnut, both are correct.

### Expected behavior

The tooltip rectancle should use the correct (backgroundColor) colors (in the example case it should be filled blue), just like the bar chart.

### Steps to reproduce

Just use me demo repository on the `issue/line-chart-wrong-color` branch (https://github.com/bernhardh/test-filament-multi/tree/issue/line-chart-wrong-color). And look at the dashboard. There are 2 Charts:

- bar chart
- line chart

Hover over on dataset of the charts and compare the colors of the tooltip bloxes

This is wrong:
![image](https://github.com/filamentphp/filament/assets/642292/fd985983-b6e0-46d1-88ea-3482a638d1d7)

This is correct:
![image](https://github.com/filamentphp/filament/assets/642292/4efbaadb-f0f2-4feb-b1dd-90e184e435c7)

##### No need for my demo repository

You can just drop this class in your widgets folder and you can see it as well

```php
class DemoChart extends ChartWidget
{
    protected static ?string $heading = 'Line Chart';
    protected static ?string $pollingInterval = null;
    protected int | string | array $columnSpan = "full";


    protected function getData(): array
    {
        return [
            'datasets' => [
                [
                    'label' => 'Green',
                    'data' => $this->getRandomNumbers(),
                    "backgroundColor" => "green",
                    'borderColor' => "green"
                ],
                [
                    'label' => 'Blue',
                    'data' => $this->getRandomNumbers(),
                    "backgroundColor" => "blue",
                    'borderColor' => "blue"
                ],
                [
                    'label' => 'Red',
                    'data' => $this->getRandomNumbers(),
                    "backgroundColor" => "red",
                    'borderColor' => "red"
                ],
            ],
            'labels' => ['Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec'],
        ];
    }


    protected function getType(): string
    {
        return 'line';
    }


    private function getRandomNumbers(): array
    {
        $start = 0;
        $end = 25;
        $quantity = 12;

        $numbers = array();
        for ($i=0; $i<$quantity/($end-$start); $i++)
            $numbers = array_merge($numbers, range($start, $end));
        shuffle($numbers);

        return array_slice($numbers,0,$quantity);
    }
}
```

This is the inital discord discussion:

https://discord.com/channels/883083792112300104/1159015783200985189

### Reproduction repository

https://github.com/bernhardh/test-filament-multi

### Relevant log output

```shell
No Output needed
```

**Comment by zepfietje** [comment]
Not a Filament bug. Please check the Chart.js docs for the exact props you want to use. In this case it's `pointBackgroundColor` and `pointHoverBackgroundColor`.
