### ISSUE TITLE
Resource sub-navigation

### ISSUE THREAD

**Issue by danharrin** [laravel-filament/filament#9477]
## Todo for @zepfietje

- [x] Review design
- [x] Add tabs API

**Comment by danharrin** [comment]
Docs done here: https://github.com/filamentphp/filament/commit/36169c61bc860d547ea1764d4d52654703cc19ff

@zepfietje this can be closed when you have completed your design review.

**Comment by danharrin** [comment]
Thing to fix: `sidebarCollapsibleOnDesktop()` also collapses the resource navigationItems

**Comment by zepfietje** [comment]
https://github.com/filamentphp/filament/commit/94aa7744d6a6c63a7b4a1db1649026573271413d
