### ISSUE TITLE
Stable SPA mode

### ISSUE THREAD

**Issue by danharrin** [laravel-filament/filament#9478]

**Comment by binaryfire** [comment]
Not a stability issue, but would be great to properly persist the sidebar and topbar so they don’t flicker on page changes. This really breaks the SPA-feel IMHO.

**Comment by zepfietje** [comment]
Also, if we decide to enable this by default, we should improve the improve the design of the  loading indicators. Currently it shows 2 by default (which just doesn't make sense). Also, we should set the color to the primary color.

**Comment by danharrin** [comment]
I'm not ever enabling this by default, I just want to fix the console errors.

> Not a stability issue, but would be great to properly persist the sidebar and topbar so they don’t flicker on page changes. This really breaks the SPA-feel IMHO.

It would break the active highlighting of the current menu item, which is done in Blade right now.
