### ISSUE TITLE
brandLogo does not accept HTML string

### ISSUE THREAD

**Issue by bilogic** [laravel-filament/filament#9485]
### Package

filament/filament

### Package Version

781586a68ba1581344d6c02744e492be20ab51db

### Laravel Version

10.30.1

### Livewire Version

 v3.1.0       

### PHP Version

 8.1.20

### Problem description

Passing HTML string directly did not work, instead what seems to be required is a view.

https://filamentphp.com/docs/3.x/panels/themes#adding-a-logo

```PHP
 ->brandLogo(function () {
                return <<<'SVG'
                    <svg
                        viewBox="0 0 128 26"
                        xmlns="http://www.w3.org/2000/svg"
                        class="h-full fill-gray-500 dark:fill-gray-400"
                    >
                        <!-- ... -->
                    </svg>
                SVG;
            })
```

### Expected behavior

SVG should render correctly

### Steps to reproduce

Source code to replicate the issue provided above

### Reproduction repository

Don't think it is needed, the short snippet recreates the problem

### Relevant log output

```shell
I'm on a custom branch, so I specified the commit I'm based off.
That commit is less than 1 day old, so this problem still exists.
```

**Comment by zepfietje** [comment]
Make sure to return an `HtmlString` instance if you want to return it directly from the method.
