### ISSUE TITLE
AttachAction select cannot translate.

### ISSUE THREAD

**Issue by NaungYeHtet** [laravel-filament/filament#9490]
### Package

filament/spatie-laravel-translatable-plugin

### Package Version

3.0.0

### Laravel Version

10.10

### PHP Version

8.1

### Problem description

**recordSelect** field of **AttachAction** cannot translate.

<img width="575" alt="image" src="https://github.com/filamentphp/filament/assets/49832780/166c3990-16bc-4ef6-9646-ce01bae53fb2">

### Expected behavior

AttachAction can translate

### Steps to reproduce

Use RelationManager AttachAction and `filament/spatie-laravel-translatable-plugin`

### Reproduction repository

https://github.com/NaungYeHtet/filament-naungyehtet

**Comment by tuyenhv007** [comment]
Forms\Components\Select::make('company_city_id')
                                    ->relationship('city', 'name')
                                    ->getOptionLabelFromRecordUsing(fn (Model $record) => "{$record->getTranslation('name', app()->getLocale())}")
                                    ->preload()
                                    ->searchable()
                                    ->required(),
Is it what you need?

**Comment by danharrin** [comment]
Or even `->getOptionLabelFromRecordUsing(fn (Model $record) => $record->name)`

**Comment by NaungYeHtet** [comment]
```
Tables\Actions\AttachAction::make()
    ->preloadRecordSelect()
    ->getOptionLabelFromRecordUsing(fn (Model $record) => $record->name),
```

`->getOptionLabelFromRecordUsing`

AttachAction::getOptionLabelFromRecordUsing does not exist.

I am using AttachAction not Select
