### ISSUE TITLE
Cannot override or disable actions in RelationManager with shared resource table.

### ISSUE THREAD

**Issue by NaungYeHtet** [laravel-filament/filament#9492]
### Package

filament/filament

### Package Version

3.0.0

### Laravel Version

10.0.0

### PHP Version

8.1

### Problem description

Cannot override actions in RelationManager with **Shared Resource Table**.

I want to override to remove EditAction in RelationManager

```
return TagResource::table($table)
    ->recordTitleAttribute('name')
    ->headerActions([
        Tables\Actions\AttachAction::make(),
    ])
    ->actions([
        Tables\Actions\DetachAction::make(),
    ])
    ->bulkActions([
        Tables\Actions\BulkActionGroup::make([
            Tables\Actions\DetachBulkAction::make(),
        ]),
    ]);
```

Parent resource TagResource has **EditAction**

**Edit** button was disappeared after overriding

Editing the record in parent resource can be disabled after removing the edit route from  `getPages` function.
But In RelationMangers, the only way to disable the edit action is to remove EditAction but got this behaviour.

When clicking the row, it shows:
1. **Edit** model if RelationManager has form function 
2. Saved alert  if RelationManager do not has form function 

### Expected behavior

**Edit** modal will not open when clicking the row after overriding `EditAction.`

### Steps to reproduce

1. Use shared resource table in RelationManger
2. Override actions 

### Reproduction repository

https://github.com/NaungYeHtet/filament-ascept-ratio/tree/override-actions

**Comment by zepfietje** [comment]
You probably just want to add `->url()` to your edit action then?

**Comment by NaungYeHtet** [comment]
Actually I want to disable EditAction modal on shared resource table in RelationManager.

**Comment by luchaos** [comment]
@NaungYeHtet were you able to resolve this issue? Reused tables in `RelationManager`s still behave unexpectedly for me. Both the `view` and `edit` actions from the original table show empty modals for me and I'd like to override/disable those actions 🤔

**Comment by danielschweiger** [comment]
I was able to overwrite the ViewAction or just set it to visible = false

```
public function table(Table $table): Table
    {
        return BranchResource::table($table)
            ->headerActions([
                CreateAction::make()
                    ->modalHeading(function($livewire) {
                        return $livewire->ownerRecord->name;
                    })
                    ->authorize(function() {
                        return true;
                    })
            ])
            ->actions([
                ViewAction::make()
                    ->url('https://www.google.com')
                    //->visible(false) // alternative
                    ,
                EditAction::make()
                    ->label(false)
                    ->tooltip(__('msg.general.buttons.edit'))
                    ->modalHeading(false),
                DeleteAction::make()
                    ->label(false)
                    ->tooltip(__('msg.general.buttons.delete'))
                    ->modalHeading(__('msg.branches.label').' '.strtolower(__('msg.general.buttons.delete'))),
            ]);

    }
```
