### ISSUE TITLE
Markdown Editor has contrast issues in dark mode

### ISSUE THREAD

**Issue by jobara** [laravel-filament/filament#9497]
### Package

filament/forms

### Package Version

v3.0.83

### Laravel Version

v10.28.0

### Livewire Version

v3.0.8

### PHP Version

PHP 8.1.24

### Problem description

The markdown editor has many contrast issues for the formatted text. The list items are virtually unreadable and others are also below WCAG AA standards.

<img width="1194" alt="Screenshot showing low contrast in dark mode" src="https://github.com/filamentphp/filament/assets/556024/00d5ab1c-9da9-4f63-9ab4-890de62b27bb">

Text should be 4.5:1 ratio unless it is large or bold text, then I can be 3:1. (see: [MDN Color Contrast](https://developer.mozilla.org/en-US/docs/Web/Accessibility/Understanding_WCAG/Perceivable/Color_contrast?utm_source=devtools&utm_medium=a11y-panel-checks-color-contrast))

- Selected text (without any formatting colour) is 1.41:1
- The Quote is 4.45:1
- Lists are 1.36:1
- Code block is 3.03:1

### Expected behavior

The contrast should be at least WCAG AA compliant.

### Steps to reproduce

1. Go to the [create demo](https://demo.filamentphp.com/blog/posts/create) 
2. change to the dark mode
3. enter markdown syntax into the markdown editor.

I linked to the filament repo because it's reproducible in your own demo.

### Reproduction repository

https://github.com/jobara/filament-demo

**Comment by jobara** [comment]
The quote is actually below WCAG AA contrast in light mode as well, being only 3.48:1.

**Comment by zepfietje** [comment]
We're aware of this issue, as we haven't been able to add dark mode styles for the Markdown editor in time for v3.

Feel free to work on this already if you want though. 🙂

**Comment by movicat** [comment]
https://github.com/filamentphp/filament/assets/36602392/cac22d2d-779d-4f78-b193-d70207aaf0c7

**Comment by movicat** [comment]
https://github.com/filamentphp/filament/assets/36602392/657c97ce-0e6e-4286-b5f9-7b4a0fe697f2
