### ISSUE TITLE
Modal hides part of DateTimePicker popup in RelationsManager

### ISSUE THREAD

**Issue by elementarteilchen-charm** [laravel-filament/filament#95]
**Modal hides part of DateTimePicker popup in RelationsManager**

I have setup a relationship Project->hasMany(Item::class) and created an ItemsRelationManager to list all related items for a project.

In the ItemsRelationsManager I have defined the form as follows:

```
public static function form(Form $form)
    {
        return $form
            ->schema([
                Components\TextInput::make('category')->autofocus()->required(),
                Components\Textarea::make('description'),
                Components\DateTimePicker::make('start')->required(),
                Components\DateTimePicker::make('end'),
            ]);
    }
```
When clicking edit or new the modal pops up and shows all fields correctly.

**The Problem**

When opening the DateTimePicker is is partly outside of the modal and is unreachable.
(overflow-hidden class is set)

**Expected behavior**

DateTimePicker should be reachable.

**Suggested quick fix**

Change `overflow-hidden` to `overflow-auto`.

It's not pretty but it works :)

**Screenshots**

<img width="824" alt="Bildschirmfoto 2021-03-06 um 07 09 36" src="https://user-images.githubusercontent.com/5823962/110197379-8d1bfa00-7e4b-11eb-936d-a87b3399c7d2.png">

**Context**
- Browser: [Safari]

**Comment by ryangjchandler** [comment]
@elementarteilchen-charm Could you try upgrading to the latest version please - I removed the overflow classes in a new release so that the select box in the "Attach" modal would overflow correctly.

**Comment by danharrin** [comment]
The modal should be proper width with the latest release too (I hope).
