### ISSUE TITLE
 RelationManager toggaleable() with many columns renders offscreen.

### ISSUE THREAD

**Issue by uqjohart** [laravel-filament/filament#9517]
### Package

filament/filament

### Package Version

3.0

### Laravel Version

10.10

### Livewire Version

3.1

### PHP Version

8.1

### Problem description

Note: I had to make a new ticket as the gitbot closed my other one without a repo link and I cant seem to reopen it. 
https://github.com/filamentphp/filament/issues/9468 

When using a relation manager with many columns that use toggleable(), the widget draw sometimes renders vertically off the screen and is unusable. It appears to only be an issue when the widget button is close the the bottom of the page so it tries to render the draw upward and off screen.

### Expected behavior

1. The top of the draw should never go above the top of the page (or the bottom of the header if using the ->topNavigation()
2. If the panel is taller than the viewport, split into multiple columns.
3. Allow for the toggles to appear in a modal window with multiple columns.

### Steps to reproduce

If using Sail:
1. Download the repo
2. Change directory to the root
3. Create a sail/docker instance: ./vendor/bin/sail up -d
4. Start docker: ./vendor/bin/sail start
Add ./vendor/bin/sail to the start of each command below in 'the main part'

If not using sail:
1. Setup your own database
2. Setup your own host/ports 
3. Setup your own application directory
4. Download the repo

The main part:
1. Create an .env file
2. Generate an application key php artisan key:generate
3. Install the composer dependencies: composer install
5. Install the NPM dependencies:  npm install
6. Run the builder: npm run build
7. Create database: phpl artisan migrate:fresh --seed
8. In your browser go to http://localhost/admin
9. Log in with '[admin@none.com](mailto:admin@none.com)' 'password'
10. Navigate to http://localhost/admin/roles/1/edit
11. Click the toggle columns button on the relation manager. 
**NOTE: This will work correctly as there are many records in the relation**
12. Navigate to http://localhost/admin/roles/2/edit
13. Click the toggle columns button on the relation manager. 
**NOTE: This will show the breakage as there are few records but many columns. The toggle columns button will not snap to it's lower position and the top controls are inaccessable.**
<img width="353" alt="bug" src="https://github.com/filamentphp/filament/assets/85085437/ebb96d35-0b2b-4a74-a158-f7ad0e59b925">

### Reproduction repository

git@github.com:uqjohart/filamentphp-issue-9468.git

**Comment by zepfietje** [comment]
This is a tricky issue, and not much we can do I think.
The best solution is probably to set a max height on the columns dropdown if you're expecting it to be too tall, using `columnToggleFormMaxHeight()`.

Give it a try, and let me know if you still run into any issues.
