### ISSUE TITLE
Select\BelongsToSelect field with IT locale

### ISSUE THREAD

**Issue by Simoneu01** [laravel-filament/filament#952]
### Package

filament/forms

### Package Version

v2.6.3

### Laravel Version

v8.76.2

### Livewire Version

v2.8.2

### PHP Version

PHP 8.0.13

### Bug description

the $getPlaceholder function does not escape the single quote

[line 75 ](https://github.com/laravel-filament/filament/blob/bf93ccb24a62ad9720b1b7609c70be205992282b/packages/forms/resources/views/components/select.blade.php#L75)

my temp solution:
add `->placeholder('Seleziona un\\\'opzione')` to the field to escape the single quote

### Steps to reproduce

1. Add Select or BelongsToSelect field
2. add "->searchable()" 
3. Set locale in config/app.php to "it"
4. Try to use it

### Relevant log output

```shell
Alpine Expression Error: Unexpected identifier

Expression: "label ?? 'Seleziona un'opzione'"

<span x-show=​"! isOpen" x-text=​"label ?? 'Seleziona un'opzione'" class=​"absolute w-full bg-white">​</span>​
```

**Comment by danharrin** [comment]
Fixed by #954.
