### ISSUE TITLE
recordTitleAttribute of RelationManager cannot resolve eloquent accessor.

### ISSUE THREAD

**Issue by NaungYeHtet** [laravel-filament/filament#9566]
### Package

filament/filament

### Package Version

3.0.0

### Laravel Version

10.10

### PHP Version

8.2.12

### Problem description

<img width="1049" alt="image" src="https://github.com/filamentphp/filament/assets/49832780/7f83755d-9159-4025-b096-6dff526ebb6b">

The problem is with AttachAction when the model load it has to show the title attribute.

### Expected behavior

Can show recordTitleAttributes with RelationManagers and accessors

### Steps to reproduce

1. Edit Tag
2. Click on attach of OptionRelationManager

### Reproduction repository

https://github.com/NaungYeHtet/filament-naungyehtet/tree/issue/record-title

**Comment by danharrin** [comment]
Because we use `pluck()`. You can use `recordTitle(fn ($record) => $record->custom_name)` instead.
