### ISSUE TITLE
Color picker resets before value is set when using lazy properties

### ISSUE THREAD

**Issue by therezor** [laravel-filament/filament#9606]
### Package

filament/filament

### Package Version

v3.0.94

### Laravel Version

v10.31.0

### Livewire Version

v3.1.0

### PHP Version

PHP 8.2.12 

### Problem description

The color picker component in Filament PHP resets its state before the color was selected when using lazy properties. This prevents the color value from being picked.
![ezgif-2-ba8491409f](https://github.com/filamentphp/filament/assets/15324879/ccabba22-9021-410e-ae3c-30101e84dd33)

### Expected behavior

State should be set after color picker was closed.

### Steps to reproduce

1. Create color picker field with lazy property
2. Try to change color
```
     ColorPicker::make('secondary')
                            ->lazy()
                            ->default('#181a2a');
```

### Reproduction repository

https://github.com/therezor/erpsaas

**Comment by danharrin** [comment]
I have searched the reproduction repository for "ColorPicker" and cannot find it.

**Comment by therezor** [comment]
@danharrin  sorry, wrong repo. Added example.
Updated repo.
Picker located it app/Filament/Company/Pages/Setting/Invoice.php:209

**Comment by therezor** [comment]
Problem is that it acts as live when set to lazy
