### ISSUE TITLE
 not open edit page and create page relation mangers

### ISSUE THREAD

**Issue by farhad321** [laravel-filament/filament#962]
### Package

filament/filament

### Package Version

v2.6.5

### Laravel Version

8.77.1

### Livewire Version

v2.8.2
### PHP Version

 8.0.3 

### Bug description

 not open edit page and create page relation mangers
![Untitled](https://user-images.githubusercontent.com/9474884/147141381-6b07fb92-0a43-43c0-bb23-674840f7fdd1.png)

**Comment by danharrin** [comment]
Hey, can you run `php artisan view:clear` please.

**Comment by danharrin** [comment]
Hey, I'm 99% sure that will solve this issue but please let me know if it does not.
