### ISSUE TITLE
Blade icons causing performance issues, even on non-Filament pages

### ISSUE THREAD

**Issue by vjanssens** [laravel-filament/filament#9672]
### Package

filament/support

### Package Version

v3.0.94

### Laravel Version

v10.31.0

### Livewire Version

v3.1.0

### PHP Version

PHP 8.2.12

### Problem description

The package `blade-ui-kit/blade-heroicons` loaded by `filament/support` is causing quite severe performance issues on non-Filament pages (regular routes loading regular blade views). It took me long to get to the bottom of the issue, but after including `DisableBladeIconComponents` (https://github.com/filamentphp/filament/blob/e8d44231fcba1a0f4e9625afe7368447d56b2866/packages/panels/src/Http/Middleware/DisableBladeIconComponents.php) in my main middleware stack the problem resolved.

I think it's interesting to note Filament apparently seen this issue before, include the mentioned Middleware it in the `AdminPanelProvider.php`, but the package is still causing issues. So loading this middleware only in an AdminPanelProvider does not fully resolve it.

* Why are blade-heroicons loaded for every request, even though I'm not in a Filament panel? Is the Filament team aware of this?
* Should the `DisableBladeIconComponent` be mentioned in the documentation, for others to take note?
* What are the downsides of including this middleware?

I wonder if I should include `DisableBladeIconComponent` in all of my other projects containing Filament V3?

Please also see the issue created in blade-icons: https://github.com/blade-ui-kit/blade-icons/issues/71#issuecomment-1810493388.

### Expected behavior

No performance penalty on non-Filament pages after installing Filament v3.

### Steps to reproduce

-

### Reproduction repository

-

**Comment by kayvanaarssen** [comment]
@zepfietje Can you check this one. And reopen?
Maybe this also has an effect on the slow loading ot the tables.

**Comment by zepfietje** [comment]
Are you using any Blade icons outside Filament panels, @vjanssens?

@kayvanaarssen, this shouldn't have anything to do with table performance within panels.

**Comment by vjanssens** [comment]
@zepfietje No, I wasn't using icons outside Filament panels. I now see it has already been mentioned in the installation docs, something I did not take note of: https://filamentphp.com/docs/3.x/panels/installation#caching-blade-icons.
