### ISSUE TITLE
Please stop using Str::headline in Resource class or alow some kind of disable flag as is breaking the bread crumbs and labels

### ISSUE THREAD

**Issue by quasiperfect** [laravel-filament/filament#9682]
### Package

filament/filament

### Package Version

v3.0.0

### Laravel Version

v10.0.0

### PHP Version

PHP 8.1.10

### Problem description

For example if i use the string 'E-mailuri blocate' as label i expect to get that string not 
![277732367-d8c8cc9f-a8f9-44d8-892d-7a285315900b](https://github.com/filamentphp/filament/assets/287513/1c11c34d-ddbe-4e72-b330-2a9e57d924c1)

### Expected behavior

Don't change my strings unless i say so by a config or some other method

### Steps to reproduce

Use in any resource

```
public static function getModelLabel(): string
{
    return 'My-custom label';
}

public static function getPluralModelLabel(): string
{
    return 'My-custom label';
}
```

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by malle-pietje** [comment]
The easiest approach would be to have a private property for the breadcrumb string like with the navigation label and heading where we can override the default behavior which probably works nicely in 80% of the cases. For the other 20% some level of control would be great.

**Comment by zepfietje** [comment]
The breadcrumb can be customized separately using the `$breadcrumb` property on a resource or page, or the `getBreadcrumb()` method.

I do think however that maybe we shouldn't use the `headline()` method, but use `ucfirst()` instead, @danharrin.

**Comment by danharrin** [comment]
The idea is that each word is capitalised based on title case, not just the first

And yes, this can easily be overridden in the breadcrumb, page titles etc

**Comment by quasiperfect** [comment]
@zepfietje @danharrin if you have a ton of resources is not that fun to do.
Or if you have some plugin installed that doesn't allow you to extend the resource etc. 
So please provide a method to turn off this behavior for people that doesn't need/want it (maybe it makes a lot of sense for english language but for some other languages that is a problem). 

Also the **-** are replaced with spaces.

Thanks for your time and understanding.

**Comment by danharrin** [comment]
It is not as simple as you are making it sound, the label is used in other places, not just this.

I will think about adding a new property where you can set the breadcrumb and page titles at the same time.
