### ISSUE TITLE
Table query modification causes problem with record's row rendering at table view

### ISSUE THREAD

**Issue by jakubkopkiewicz** [laravel-filament/filament#9684]
### Package

filament/filament

### Package Version

v3.0.0

### Laravel Version

v10

### Livewire Version

v 3.0.0

### PHP Version

PHP 8.1

### Problem description

I'm trying to modify a table query of my resource by modifying table's query method. But after that there is no rendered rows at table view, but I see pagination, and I don't have an empty table message.

There is my code : 

`<?php

namespace App\Filament\Resources\EngagementResource\Pages;

use App\Enums\Engagement\EngagementStatusEnum;
use App\Filament\Resources\EngagementResource;
use Filament\Actions;
use Filament\Resources\Pages\ListRecords;
use Filament\Tables\Table;
use Illuminate\Database\Eloquent\Builder;

class ListEngagements extends ListRecords
{
    protected static string $resource = EngagementResource::class;

    protected function getHeaderActions(): array
    {
        return [
            Actions\CreateAction::make(),
        ];
    }

    public function table(Table $table): Table
    {
        return $table
            ->modifyQueryUsing(fn (Builder $query) => $query->where('status','offer));
    }
}
`
I made some test with query, and eloquent returns needed data correctly, also inside modified closure. Also when I just passed a query without any modification, still getting the same behavior.

### Expected behavior

Records should be rendered properly

### Steps to reproduce

Just try to modify table query.

### Reproduction repository

Will be updated soon...

**Comment by willcastillo** [comment]
Solved here: https://github.com/filamentphp/filament/issues/8647
