### ISSUE TITLE
Add Table Builder inside Custom Field  Not work

### ISSUE THREAD

**Issue by mstfkhazaal** [laravel-filament/filament#9695]
### Package

filament/filament

### Package Version

v3.0.0

### Laravel Version

v10.0.0

### Livewire Version

v3.0.0

### PHP Version

8.2.4

### Problem description

I try to insert table builder inside Custom Field 
i get this error `Property [$table] not found on component`

Field:
```
class TableField extends Field implements HasForms, HasTable
{
    use \Filament\Forms\Concerns\InteractsWithForms;
    use \Filament\Tables\Concerns\InteractsWithTable;

    public function getView(): string
    {
        return 'forms.components.table-field';
    }

    public function table(Table $table): Table
    {
        return $table
            ->columns([
                TextColumn::make('name'),
            ])
            ->query(User::query());

    }
}
```
View:
```
<x-dynamic-component
    :component="$getFieldWrapperView()"
    :field="$field"
>
    <div x-data="{ state: $wire.$entangle('{{ $getStatePath() }}') }">

        {{$this->table}}

    </div>
</x-dynamic-component>
```

### Expected behavior

To work normally

### Steps to reproduce

i try add this comand insid getView but not work

```
 public function getView(): string
    {
        $this->table =$this->table($this->makeTable());
        return 'forms.components.table-field';
    }

```

### Reproduction repository

https://github.com/mstfkhazaal/test-table-field

**Comment by aqjw** [comment]
👀

**Comment by olivM** [comment]
the TableBuilder inside a custom field works well (display rows and even reorder/field edit from a relationship are correctly saved on blur)

BUT it prevent the rest of the form to work :  the form 'submit' button doesn't trigger any network activity

demo : https://github.com/olivM/test-table-field

```
php artisan migrate db:seed
php artisan serve
```
-> http://127.0.0.1:8000/admin/users/1/edit
