### ISSUE TITLE
FileUpload bug with upload some files

### ISSUE THREAD

**Issue by OlyaK95** [laravel-filament/filament#9702]
### Package

filament/filament

### Package Version

3.0.97

### Laravel Version

10.32.1

### Livewire Version

3.1.0

### PHP Version

8.2.8

### Problem description

An error occurs when trying to upload some files. At the beginning I thought. that's a matter of file size, but it doesn't matter. Some files are uploaded, some are not.

Resource file:
```
FileUpload::make("documentation")
	->label("ZIP")
	->disk("public")
	->directory("documentations")
	->visibility("public")
	->acceptedFileTypes(["application/zip"])
	->maxSize(49152)
	->maxFiles(1)
	->downloadable()
	->disabled(
		fn() => !auth()
			->user()
			->isAdminstrator()
	)
	->getUploadedFileNameForStorageUsing(
		fn(
		 TemporaryUploadedFile $file
		): string => (string) str(
		 $file->getClientOriginalName()
		)->prepend(now()->timestamp . "-")
	)
	->columnSpan([
		"sm" => 1,
		"lg" => 2,
	]),
FileUpload::make("report")
	->label("PDF")
	->disk("public")
	->directory("reports")
	->visibility("public")
	->acceptedFileTypes(["application/pdf"])
	->maxSize(49152)
	->maxFiles(1)
	->downloadable()
	->getUploadedFileNameForStorageUsing(
		fn(
		 TemporaryUploadedFile $file
		): string => (string) str(
		 $file->getClientOriginalName()
		)->prepend(now()->timestamp . "-")
	)
	->columnSpan([
		"sm" => 1,
		"lg" => 2,
	]),
```

php.ini
```
; Maximum size of POST data that PHP will accept.
; Its value may be 0 to disable the limit. It is ignored if POST data reading
; is disabled through enable_post_data_reading.
; https://php.net/post-max-size
post_max_size = 2G

;;;;;;;;;;;;;;;;
; File Uploads ;
;;;;;;;;;;;;;;;;

; Whether to allow HTTP file uploads.
; https://php.net/file-uploads
file_uploads = On

; Temporary directory for HTTP uploaded files (will use system default if not
; specified).
; https://php.net/upload-tmp-dir
;upload_tmp_dir =

; Maximum allowed size for uploaded files.
; https://php.net/upload-max-filesize
upload_max_filesize = 2G

; Maximum number of files that can be uploaded via a single request
max_file_uploads = 20
```

Some screenshots
![2023-11-17_01-33-52](https://github.com/filamentphp/filament/assets/129214474/460a09fe-4a67-4f5d-8618-736c3846f861)
![2023-11-17_01-33-08](https://github.com/filamentphp/filament/assets/129214474/764489ce-0d20-451b-8f23-e84f89c0fc90)
![2023-11-17_01-32-21](https://github.com/filamentphp/filament/assets/129214474/127fae63-d629-4563-aeea-73ddfec6c882)

### Expected behavior

FileUpload must upload any PDF or ZIP files.

### Steps to reproduce

Copy my code to any Resource file.

### Reproduction repository

https://github.com/filamentphp/demo

**Comment by sinnbeck** [comment]
Check the mime of the file locally. Here is how you do it on linux
```shell
file --mime-type -b more.pdf
```
if it does not say applicaiton/pdf, then filepond is doing it correctly.

**Comment by OlyaK95** [comment]
> ```shell
> file --mime-type -b more.pdf
> ```

![2023-11-17_12-37-02](https://github.com/filamentphp/filament/assets/129214474/3df3ace5-70e2-4bfa-8b99-5ec165d01db4)

**Comment by sinnbeck** [comment]
Maybe you can provide a link to the file that does not work? I have tried with several pdf files but cannot get it to fail

What is the error message exactly? I cannot read it ;)

**Comment by OlyaK95** [comment]
> Maybe you can provide a link to the file that does not work? I have tried with several pdf files but cannot get it to fail

Yes, of course
https://disk.yandex.ru/d/xl9FHJ-ClLjt2A

> What is the error message exactly? I cannot read it ;)

1) Error during load.
Tap to retry

2) File of invalid type.
Waiting or application/pdf

Console error:
Failed to load resource: the server responded with a status of 422 (Unprocessable Content)

**Comment by danharrin** [comment]
Probably missing validation rule from the config/livewire.php temporary file uploads section?

**Comment by OlyaK95** [comment]
> Probably missing validation rule from the config/livewire.php temporary file uploads section?

I have no config/livewire.php file. Do I need it?

**Comment by danharrin** [comment]
Thinking about it again, probably not

But a 422 error doesn't sound like it's coming from Filament, it sounds like something on your server is blocking PDF uploads

**Comment by OlyaK95** [comment]
> Thinking about it again, probably not
> 
> But a 422 error doesn't sound like it's coming from Filament, it sounds like something on your server is blocking PDF uploads

@danharrin You was right. I don't know, but by default Livewire have validation that uploaded files can be max 12 MB.
https://livewire.laravel.com/docs/uploads#global-validation

I added config/livewire.php with text:
```
<?php

return [
    "temporary_file_upload" => [
        "rules" => "file|mimes:pdf,zip|max:49152",
    ],
];
```
And the problem with PDF gone.

About ZIP files I have another solution - I added more file types:
```
FileUpload::make("documentation")
	->label("ZIP")
	->disk("public")
	->directory("documentations")
	->visibility("public")
	->acceptedFileTypes([
		"application/x-compressed",
		"application/x-zip-compressed",
		"application/zip",
		"multipart/x-zip",
	])
	->maxSize(49152)
	->maxFiles(1)
	->downloadable()
	->disabled(
		fn() => !auth()
			->user()
			->isAdminstrator()
	)
```
