### ISSUE TITLE
missing $navigationLabel for in page  Dashbord.php

### ISSUE THREAD

**Issue by aliloubm** [laravel-filament/filament#973]
### Package

filament/filament

### Package Version

v2

### Laravel Version

v8

### Livewire Version

V2

### PHP Version

php 8

### Bug description

Missing $navigationLabel for using translation of   "Dashboard" in page  Dashbord.php

I added this if this is the best way to do it

```
protected static ?string $navigationLabel = null;

    public function mount(): void
    {
        static::$navigationLabel = $this->getTitle();
    }
```

**Comment by danharrin** [comment]
Fixed in #974.
