### ISSUE TITLE
Resource List Searchable Column Case Sensitivity with JSON Column Type in MySQL

### ISSUE THREAD

**Issue by dev3k** [laravel-filament/filament#9736]
### Package

filament/filament

### Package Version

v3.0.98

### Laravel Version

v10.32.1

### Livewire Version

V3.1.0

### PHP Version

PHP 8.2.9

### Problem description

The MySQL JSON column type is inherently case-sensitive.

When using it for a Resource List, the searchable column is not defaulting to lowercase in queries.

Ref: https://github.com/filamentphp/filament/discussions/2162#discussioncomment-7558842

### Expected behavior

The search query should be case-insensitive by default specially for JSON columns in MySQL, allowing users to find resources regardless of case variations.

### Steps to reproduce

1. Create a table with a Field with JSON column type.
2. Add data with mixed-case values in the searchable column.
3. Attempt to search for a resource using a different case.

In my repo, I added two posts with title
1. AAA
2. bbb

Navigate to http://json-column.test/admin/posts?tableSearch=aaa or http://json-column.test/admin/posts?tableSearch=BBB, No results are returned

### Reproduction repository

https://github.com/dev3k/json-column

**Comment by danharrin** [comment]
I did download your repo and visited the URLs, but they seemed to return the correct results? MySQL 8.0.27

![Image](https://github.com/filamentphp/filament/assets/41773797/1402b9d8-3901-4492-93c0-d40a4341337b)
![Image](https://github.com/filamentphp/filament/assets/41773797/b51cd166-ace3-4061-b7da-05795a48513d)

**Comment by dev3k** [comment]
@danharrin I'm using 8.2, I think its from my collation I'm using 

> Because utf8mb4_bin is a binary collation, comparison of JSON values is case-sensitive.

https://dev.mysql.com/doc/refman/8.2/en/json.html

**Comment by danharrin** [comment]
Check the queries that Filament is running. What should be different about them?

**Comment by dev3k** [comment]
they should be like below with lower function, currently, I use ->forceSearchCaseInsensitive() as work around 

```
select count(*) as aggregate from `posts` where (lower(json_extract(title, "$.en")) like '%bb%');
select * from `posts` where (lower(json_extract(title, "$.en")) like '%bb%') order by `posts`.`id` asc limit 10 offset 0;
```

**Comment by danharrin** [comment]
This is kinda the point of `forceSearchCaseInsensitive()`

1) For both MySQL and Postgres, case insensitivity should work out of the box with the default configuration. And it does for me, you're just using an alternative collation.
2) When using `lower()`, it can have a performance impact. Most users don't need this, so we don't enable it by default.
3) We give `forceSearchCaseInsensitive()` to users who need to use it, so as not to affect anyone else

**Comment by dev3k** [comment]
understandable 👍

**Comment by daniouyea** [comment]
This fails for me too :(
If I use `forceSearchCaseInsensitive()`, the SQL query is: `lower(license_owner_info->name) LIKE %dani%` and it gives an SQL Syntax error.
If not: `json_unquote(json_extract('license_owner_info', '$."name"')) like %Dani%`.

Using: Filament v3.2.92 and MySQL 8.0.37

**Comment by mikaelpopowicz** [comment]
> @danharrin I'm using 8.2, I think its from my collation I'm using
> 
> > Because utf8mb4_bin is a binary collation, comparison of JSON values is case-sensitive.
> 
> https://dev.mysql.com/doc/refman/8.2/en/json.html

Filament provides the ability to use a `search collation` :

```php
// config/database.php

return [
    // ...

    'connections' => [
        'you_connection' => [
            // ...
            'search_collation' => 'utf8mb4_unicode_ci', // or any other collation you want to use
        ],
    ],
};
```

This adds ` collate {search_collation}` after the column name

```sql
select count(*) as aggregate
from `language_lines`
where (
    id collate utf8mb4_unicode_ci like %locale%
    or group collate utf8mb4_unicode_ci like %locale%
    or key collate utf8mb4_unicode_ci like %locale%
    or lower(json_extract(value, "$.en")) collate utf8mb4_unicode_ci like '%locale%'
);
```

But there is a drawback using this method : the columns are no longer wrapped correctly (e.g ``` `column` ```) , which can lead to an SQL syntax error if you have columns named as reserved keywords.
