### ISSUE TITLE
In the creation screen, when using `afterStateUpdated` with a select, there are instances where data cannot be retrieved with `Get $get`.

### ISSUE THREAD

**Issue by bzy107** [laravel-filament/filament#9743]
### Package

filament/filament

### Package Version

v3.0.98

### Laravel Version

v10.32.1

### Livewire Version

v3.1.0

### PHP Version

PHP8.2.11

### Problem description

I attempted to clear the second select box when changing the first select box using `afterStateUpdated`, but there are cases where the value of the second select box does not become empty.
```php
    public static function form(Form $form): Form
    {
        return $form
            ->schema([
                Forms\Components\Select::make('type')
                    ->options([
                        'cat' => 'Cat',
                        'dog' => 'Dog',
                        'rabbit' => 'Rabbit',
                    ])
                    ->searchable()
                    ->preload()
                    ->afterStateUpdated(function (Set $set) {
                        $set('type2', '');
                    })
                    ->live()
                    ->required(),
                Forms\Components\Select::make('type2')
                    ->options([
                        'cat2' => 'Cat2',
                        'dog2' => 'Dog2',
                        'rabbit2' => 'Rabbit2',
                    ])
                    ->searchable(),
            ]);
    }
```

Upon investigation, I found that the value was not set when using `$get`. 
It appears that the issue is resolved after the second consecutive operation. Also, I confirmed that the data is not empty in $get from the second operation onward.
Perhaps, because data cannot be retrieved with $get on the initial attempt, setting values with $set might also be impossible.
However, as a Livewire and Filament beginner, I'm not sure where the issue is originating. Thank you.
```php
                    ->afterStateUpdated(function (Set $set, Get $get) {
                        $get('type2'); // type2: ''
                        $set('type2', '');
                    })
```

This may be related to issue #9120

### Expected behavior

When the first select box is modified, the second select box becomes empty.

### Steps to reproduce

1. Selected any value in the 'type' select box.
![スクリーンショット 2023-11-19 21 14 14](https://github.com/filamentphp/filament/assets/28666304/c98fb8e0-912b-4a8c-9657-1f9350e9e368)
2. Selected any value in the 'type2' select box.
![スクリーンショット 2023-11-19 21 14 34](https://github.com/filamentphp/filament/assets/28666304/710987db-924e-43d0-be60-15adb8ffb236)
3. Clicked the delete button for 'type' to remove the value.
![スクリーンショット 2023-11-19 21 14 44](https://github.com/filamentphp/filament/assets/28666304/92bf0bd9-4df9-4a74-baae-f92d734e3834)

value of the second select box does not become empty.
![スクリーンショット 2023-11-19 21 15 19](https://github.com/filamentphp/filament/assets/28666304/cf84d8fd-6309-4992-8867-d138d3febc46)

Additionally, when I changed the order of 'type' and 'type2', the issue did not occur with the above steps.
```php
        return $form
            ->schema([
                Forms\Components\Select::make('type2')
                    ->options([
                        'cat2' => 'Cat2',
                        'dog2' => 'Dog2',
                        'rabbit2' => 'Rabbit2',
                    ])
                    ->searchable(),
                Forms\Components\Select::make('type')
                    ->options([
                        'cat' => 'Cat',
                        'dog' => 'Dog',
                        'rabbit' => 'Rabbit',
                    ])
                    ->searchable()
                    ->preload()
                    ->afterStateUpdated(function (Set $set) {
                        $set('type2', '');
                    })
                    ->live()
                    ->required(),
            ]);
```

### Reproduction repository

https://github.com/bzy107/filament-select-bug

**Comment by danharrin** [comment]
Livewire bug livewire/livewire#7510

**Comment by danharrin** [comment]
It's been fixed in Livewire now
