### ISSUE TITLE
Pagination page not persisted when navigating back

### ISSUE THREAD

**Issue by kayvanaarssen** [laravel-filament/filament#9773]
### Package

filament/filament

### Package Version

Latest

### Laravel Version

Latest

### PHP Version

PHP 8.2

### Problem description

When you navigate to for example page 3 in the demo or in your own filament project. And you click somewhere or go to the view a record page. And navigate back your page will be reset to `page=1`

Confirmed with @zepfietje and this also happens in the Demo Project of Filament 

See here: https://app.screencast.com/EC7Wm8HEQYT6v

### Expected behavior

Navigate back to the page where you came from for example if you were on `Page=3` you should be getting back to `page=3`  and not `page=1`

### Steps to reproduce

Also in the Demo; See screencast: https://app.screencast.com/EC7Wm8HEQYT6v

### Reproduction repository

N/A

**Comment by kayvanaarssen** [comment]
@zepfietje Please reopen this issue as discussed earlier. Thanks!

**Comment by agusmaulanayusufnoor** [comment]
my pagination not show in filament 3.0.80...i downgrade to 3.0.79 to show pagination in table. can everybody solve it?

**Comment by zepfietje** [comment]
Please create a separate bug report, @agusmaulanayusufnoor.

**Comment by Jehizkia** [comment]
I have investigated the issue, and it appears that the pagination of the `databaseNotification` package is related to this problem. If you remove `->databaseNotifications()` from your `panelProvider`, the issue will no longer occur.

To further test this assumption, I changed `$isPaginated` to `false` in `filament/notification/src/Livewire/DatabaseNotifications.php`, and the issue disappeared.

**Comment by danharrin** [comment]
Cannot reproduce. Even with DB notifications. And even if I could, it would need to be filed as an issue to the Livewire repository and not this one.


https://github.com/filamentphp/filament/assets/41773797/0b4bad4c-ef59-4e5e-88d9-7e69556472ca

**Comment by kayvanaarssen** [comment]
@danharrin Weird that you cannot reproduce this, still having this issue, in our Projects and also in the demo... 
So you are convinced this is a Livewire issue? If so i'll create an issue there.

As you take a look at my screencast you see the page parameter is wrong in the URL

**Comment by danharrin** [comment]
Filament does not contain any logic to read the query string and set the pagination page. That is a feature of Livewire. So is query string "back button" preservation.

To submit the bug to Livewire, you will need to write a failing test in a PR.
