### ISSUE TITLE
FileUpload reset after locale switch

### ISSUE THREAD

**Issue by Ahmant** [laravel-filament/filament#9791]
### Package

filament/filament

### Package Version

3.0-stable

### Laravel Version

10.10

### PHP Version

8.1

### Problem description

In "Edit/Create" form which has a "FileUpload" component, the "FileUpload" content/file will reset/clear when we switch the locale using the "LocaleSwitcher" action button.

https://github.com/filamentphp/filament/assets/39812462/978d95d8-987c-4a01-9a12-207cc789525d

### Expected behavior

1. If the "file" column is not translatable:
When switching the locale, the "FileUpload" field must not change its state.

2. If the "file" field is translatable:
When switching the locale, the "FileUpload" field must change its state to the new edited locale value, not resetting/clearing every its state.

### Steps to reproduce

1. Create a resource with "Create" and "Edit" pages, with translation
2. Add a "FileUpload" component to the resource form (note that the field/column is not translatable)
3. Open the "Create" or the "Edit" page (similar issue for both pages)
4. Choose a file
5. Switch the locale
=> The "FileUpload" will reset

### Reproduction repository

https://github.com/Ahmant/filament-bugs

**Comment by danharrin** [comment]
Fixed when #10257 gets merged
