### ISSUE TITLE
Pagination Pagination is not displayed

### ISSUE THREAD

**Issue by agusmaulanayusufnoor** [laravel-filament/filament#9819]
### Package

filament/tables

### Package Version

v.3.0.91

### Laravel Version

v10.10

### Livewire Version

v3.0.0

### PHP Version

PHP 8.1.0

### Problem description

My pagination not display in normal layout but its displayed only on mobile resolutions.
i try downgrade to filament 3.0.79 pagination displayed normally.

![gambar](https://github.com/filamentphp/filament/assets/97864204/d9fcdf1d-8544-4f64-ac86-55ce1823cd59)
not show in version 3.0.91

![gambar](https://github.com/filamentphp/filament/assets/97864204/011e477f-e526-42e3-b01d-87b01140024c)
pagination show in mobile resolution version 3.0.91

![gambar](https://github.com/filamentphp/filament/assets/97864204/267a8557-48c8-4455-8be0-0ea0ce87ed99)
pagination show in filament version 3.0.79

how solve this?

### Expected behavior

please fix this bug. thanks

### Steps to reproduce

i dont know pieces of code this bug. please cek this link => https://www.answeroverflow.com/m/1168612679938736158
because he is same problem with me. thanks

### Reproduction repository

https://github.com/agusmaulanayusufnoor/e-monitoringku

**Comment by zepfietje** [comment]
Please upgrade to the latest version of Filament.
