### ISSUE TITLE
Placeholder HintAction Modal not work

### ISSUE THREAD

**Issue by mstfkhazaal** [laravel-filament/filament#9821]
### Package

filament/filament

### Package Version

v3.0.0

### Laravel Version

v10.0.0

### Livewire Version

v3.0.0

### PHP Version

8.2.4 

### Problem description

HintAction in placeholder not work with action

https://github.com/filamentphp/filament/assets/47450090/7e014f39-16e7-4d50-95bf-06b1e3d54ea6

### Expected behavior

Work normaly

### Steps to reproduce

I add `<x-filament-actions::modals />` on every page 

### Reproduction repository

https://github.com/mstfkhazaal/test-table-field

**Comment by zepfietje** [comment]
Actions need to have a unique name.

**Comment by mstfkhazaal** [comment]
> Actions need to have a unique name.

I apologize for this error, but unfortunately it is not the reason
The name was changed and it didn't work

https://github.com/filamentphp/filament/assets/47450090/6e2449b4-9869-46e0-aed2-13dd9210723b

**Comment by danharrin** [comment]
Pass `->key('action_test_2')` to the placeholder

**Comment by mstfkhazaal** [comment]
> Pass `->key('action_test_2')` to the placeholder

Is work thanks
