### ISSUE TITLE
Spatie Media Library - Image not uploading during filament resource create page but works on edit page

### ISSUE THREAD

**Issue by SerhiiMandrykin** [laravel-filament/filament#9835]
### Package

filament/spatie-laravel-media-library-plugin

### Package Version

v3.0.101

### Laravel Version

v10.33.0

### PHP Version

PHP 8.1

### Problem description

I'm experiencing the same issue as described in #6143

When i upload images on resource creating page - it does not work

So here is my form:
```php
public static function form(Form $form): Form
{
    return $form
        ->schema(
            [
                Forms\Components\TextInput::make('title')
                                          ->required()
                                          ->maxLength(255)
                                          ->columnSpanFull(),
                Forms\Components\RichEditor::make('text')
                                           ->required()
                                           ->columnSpanFull()
                                           ->fileAttachmentsDisk(config('media-library.disk_name'))
                                           ->fileAttachmentsDirectory('news-attachments')
                                           ->fileAttachmentsVisibility('public'),

                SpatieMediaLibraryFileUpload::make('images')
                                            ->label('Зображення')
                                            ->collection('default')
                                            ->multiple()
                                            ->image()
                                            ->disk(config('media-library.disk_name'))
                                            ->conversion('thumb')
                                            ->columnSpanFull()
            ]
        );
}
```

The model has all the necessary info:
```php
class News extends Model implements HasMedia
{
    use HasFactory, InteractsWithMedia, HasComments;
``` 

I tried to debug it and I came up with the thing that `$this->getState()` is considered blank so images are not saved

`\Filament\Forms\Components\BaseFileUpload::saveUploadedFiles`:
```php
public function saveUploadedFiles(): void
{
  if (blank($this->getState())) {
      $this->state([]);

      return;
  }
}
...
``` 

Here are the queries executed on save:
![image](https://github.com/filamentphp/filament/assets/25152924/85d272dc-5cb4-42bf-bb05-08dab1245671)

### Expected behavior

The images are uploaded along with model creation

### Steps to reproduce

Resource created with image on Laravel filament admin panel using Spatie Media Library

### Reproduction repository

https://github.com/SerhiiMandrykin/filament-media-library-bug-report

**Comment by danharrin** [comment]
Can you please send a screen recording showing what is happening?

**Comment by SerhiiMandrykin** [comment]
@danharrin here is the recording, sorry for such delay

https://github.com/filamentphp/filament/assets/25152924/ba06f92f-a3a9-43fb-9f9a-6c966e79fe89

**Comment by danharrin** [comment]
The problem is your `beforeValidate()`. Do you need `mutateFormDataBeforeCreate()` instead, check the docs?

This is why we ask you put time into making a proper reproduction repository from scratch. This could have been found weeks ago if you had built this again instead of copying code from your project.

**Comment by SerhiiMandrykin** [comment]
@danharrin what is wrong with beforeValidate ? if you are talking about filling **slug** - it is not the core issue

I tried without beforeValidate as well , the same result

**Comment by danharrin** [comment]
I've removed the beforeValidate() and it seems to work fine. I don't know why you are calling `form->fill()` there

**Comment by SerhiiMandrykin** [comment]
@danharrin i've done the same thing and still no result.

However, I'll try to rebuild it. Maybe I missed sth.

**Comment by danharrin** [comment]
Start from a new Laravel project, create a resource with only a media field, and see if it works.

**Comment by sebastillar** [comment]
@SerhiiMandrykin @danharrin I'm facing same issue here. This is my component:

                        FileUpload::make('images')
                        ->disk(function () {
                            return config('filesystems.default');
                        })
                        ->directory('course-images')
                        ->image()
                        ->label('Images')
                        ->multiple()
                        ->required()
                        ->enableReordering()
                        ->enableDownload()
                        ->columns(2),
                        
Any update?

Thanks!

**Comment by Jason6809** [comment]
The issue still exist.
