### ISSUE TITLE
Select does not save null values when options no longer exist

### ISSUE THREAD

**Issue by joshembling** [laravel-filament/filament#9841]
### Package

filament/filament

### Package Version

v^3.0-stable

### Laravel Version

v10.10

### Livewire Version

v3.0

### PHP Version

PHP 8.1.0

### Problem description

If the Select has options and the user has saved the form with an option selected, the data is submitted to the database - as expected.

If the Select no longer has any options i.e. an empty state with the placeholder "Select an option", this should save a null value back to the database but it doesn't.

It still has the data saved in the db that existed before. Even though the Select is empty, it does not override this to return to null.

### Expected behavior

Values should save as null when no options exist.

## Steps to recreate

Must be using MySQL 8.0 or greater due to nullable json column.

1. Clone this repo
2. `composer install`
3. Clone `.env.example`, set up your database creds
4. `php artisan migrate`
5. `php artisan make:filament-user`
6. Login at `/admin/login`
7. Go to Post resource
8. Create a post with all fields filled in - Title, Body, Category, Author
9. Check database has all these fields
10. Go to `App\Filament\Resources\PostResource`
11. Remove select options so you are left with:

```php
Forms\Components\Select::make('category')
->options([]),
```

and

```php
Forms\Components\Select::make('author')
->options([]),
```

12. Now go back to the post you created at `/admin/posts/1/edit`
13. Check no options exist in either select
14. Save resource
15. See that the database values have not changed for `category` and the `author` json.

This is not expected behaviour. If values no longer exist this should save the fields as null, just as when a user selects the placeholder manually.

### Reproduction repository

https://github.com/joshembling/filament-select-bug

**Comment by danharrin** [comment]
This isn't the desired behaviour IMO. It could result in data loss, if the options failed to load from the server for whatever reason. If you want this behaviour, you should implement it in an observer, shouldn't be too bad.

**Comment by maurorepuesto** [comment]
how to implement that observer? I'm running into the same issue
