### ISSUE TITLE
Badge TextEntry does't center with alignment()

### ISSUE THREAD

**Issue by basiltap** [laravel-filament/filament#9872]
### Package

filament/filament

### Package Version

^3.0-stable

### Laravel Version

^10.10

### PHP Version

8.2.12

### Problem description

I'm centering different entries in a section infolist with ->alignment(Alignment::Center) and it is working properly, but when the entry is a badge().

### Expected behavior

The badge is expected to be centered also, isn't it?

### Steps to reproduce

return $infolist
            ->schema([
                Section::make([
                    TextEntry::make('badge')
                        ->alignment(Alignment::Center)
                        ->label(false)
                        ->badge()
                        ->color('success'),

                    TextEntry::make('text1')
                        ->alignment(Alignment::Center)
                        ->label(false),

                    TextEntry::make('text2')
                        ->alignment(Alignment::Center)
                        ->label(false),
                ])

            ]);

### Reproduction repository

https://github.com/basiltap/filament-align-badge

**Comment by zepfietje** [comment]
Should be fixed by https://github.com/filamentphp/filament/pull/9149.
