### ISSUE TITLE
V3 Docs: Repeater missing ->addBetweenAction()

### ISSUE THREAD

**Issue by devhoussam1998** [laravel-filament/filament#9886]
### Package

filament/filament

### Package Version

^3.0.102

### Laravel Version

^10.10

### Livewire Version

^3.1

### PHP Version

^8.1

### Problem description

The v3 repeater form component missing `->addBetweenAction()` at [customizing-the-repeater-action-objects](https://filamentphp.com/docs/3.x/forms/fields/repeater#customizing-the-repeater-action-objects)

for more information: https://github.com/filamentphp/filament/blob/3.x/packages/forms/src/Components/Repeater.php#L190

### Expected behavior

`->addBetweenAction()` should be exist with other repeater action objects.

### Steps to reproduce

`->addBetweenAction()`

### Reproduction repository

https://filamentphp.com/docs/3.x/forms/fields/repeater#customizing-the-repeater-action-objects

**Comment by danharrin** [comment]
This is not a bug, please submit a PR if you want to add docs
