### ISSUE TITLE
Column search in RelationManager leads to QueryException for homonym columns

### ISSUE THREAD

**Issue by giovanniledda** [laravel-filament/filament#9906]
### Package

filament/filament

### Package Version

v3.0.102

### Laravel Version

v10.33.0

### Livewire Version

v3

### PHP Version

PHP 8.1

### Problem description

I've a Model "Order" with a relationship with model "Parts".
Both models have a "code" field.
I'm using RelationManager to show "parts" relationship in OrderResource (PartsRelationManager).
Parts table in PartsRelationManager has the "code" column "searchable".
When I type any char in the search input a "QueryException" get fired:

`SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'code' in where clause is ambiguous
`

I'v solved by myself by using searchable + closure: 

`
               Tables\Columns\TextColumn::make('code')
                    ->searchable(query: function (Builder $query, string $search): Builder {
                        return $query->where('parts.code', 'like', "%{$search}%");
                    })
`

..but of course this is just a workaround.

### Expected behavior

The searchable option must be applied without a closure workaround.

### Steps to reproduce

- create Model Order with column "code"
- create model Part with columns "code" and "order_id"
- create PartsRelationManager and link it in "getRelations()" function inside OrderResource
- make "code" column searchable in table function 
- start a search

### Reproduction repository

https://github.com/giovanniledda/shiptrack/blob/develop/app/Filament/Resources/OrderResource/RelationManagers/PartsRelationManager.php

**Comment by danharrin** [comment]
I'm not sure we can fix this without introducing a breaking change. The easiest way to solve on your end would be `searchable('parts.code')`

**Comment by danharrin** [comment]
We cannot always prefix the column name in case people are relying on joins that they've added to their table queries etc
