### ISSUE TITLE
Object of class Filament\Support\Enums\MaxWidth could not be converted to string, after filament update

### ISSUE THREAD

**Issue by giovanniledda** [laravel-filament/filament#9908]
### Package

filament/filament

### Package Version

v3.0.102

### Laravel Version

v10.33.0

### Livewire Version

v3

### PHP Version

PHP 8.1

### Problem description

Trying to open any Livewire modal gives this error.

**Object of class Filament\Support\Enums\MaxWidth could not be converted to string**

Everything used to work regularly before the update.

Restoring previous Filament version (mine was v3.0.101) "fixes" the bug.

### Expected behavior

The classic view modal should open

### Steps to reproduce

https://flareapp.io/share/KPgWJpqP

### Reproduction repository

https://github.com/giovanniledda/shiptrack

**Comment by giovanniledda** [comment]
Restoring previous Filament version (v3.0.39) "fixes" the bug, but few functions used in the code (like, for example, $table->searchPlaceholder()) are not available.

**Comment by danharrin** [comment]
Your views are published, you need to update them. Please delete any views you do not change.

**Comment by dave-laye** [comment]
I encountered this problem when creating relationships but this solve it : `Tables\Actions\CreateAction::make()->slideOver()->modalWidth('md'),`
