### ISSUE TITLE
JS Script is not loading inside Widget

### ISSUE THREAD

**Issue by danielpopperl** [laravel-filament/filament#9911]
### Package

filament/filament

### Package Version

3.0-stable

### Laravel Version

v10

### Livewire Version

v3.0

### PHP Version

PHP 8.1

### Problem description

I'm trying to implementing a date-picker (flatpickr) on Widget page, but the script is not loading.

![image](https://github.com/filamentphp/filament/assets/79609349/fd66de70-8b5c-4c8b-861b-9afadd4cd890)

In other hand, this script works perfectly if I load outside my Filament Widget.

![image](https://github.com/filamentphp/filament/assets/79609349/fc5c6527-db3c-47eb-b2b6-4f36e1501fc8)

### Expected behavior

The expected behavior is that Script could load inside widget.

### Steps to reproduce

- Create a Widget
- Load an external Script

### Reproduction repository

https://github.com/danielpopperl/filament-issue-widget

**Comment by danharrin** [comment]
Widgets are lazy loaded by default. So, `window.onload` wont get run late enough. Either switch to `x-init` in Alpine, or set `$isLazy = false` in the widget.
