### ISSUE TITLE
When the 'isSearchForcedCaseInsensitive' is set to false in PostgreSQL, the table's searchable column generates an incorrect query.

### ISSUE THREAD

**Issue by pongpet** [laravel-filament/filament#9916]
### Package

filament/filament

### Package Version

3.0-stable (v3.0.102)

### Laravel Version

10.10

### PHP Version

8.2.13

### Problem description

I am using PostgreSQL as a database, and certain columns are in Pascal case. When 'isSearchForcedCaseInsensitive' is set to false, the table's searchable column generates an incorrect query. For instance, for the column named 'SchoolID,' the resulting query appears as follows: **WHERE ("SchoolID::text"::text LIKE %somevalue%)**.

It works fine on v3.0.83. The difference lies in v3.0.102, where the function 'generate_search_column_expression' is utilized.

### Expected behavior

The search query should be correct in PostgreSQL when 'isSearchForcedCaseInsensitive' is set to false.

### Steps to reproduce

1. Utilize PostgreSQL as the database.
2. Establish a model and database with columns in Pascal case.
3. Create a table with searchable columns.
4. Set 'forceSearchCaseInsensitive' = false,
5. Attempt to search for results.

### Reproduction repository

https://github.com/pongpet/postgres-no-search-forced-case-insensitive

**Comment by danharrin** [comment]
What is wrong with the query specifically? What should it be instead?

**Comment by pongpet** [comment]
The following is the error I've encountered:
![error](https://github.com/filamentphp/filament/assets/1904861/a2fc44ea-76a8-44d5-addc-022f9d634145)

I believe it should be `("Name"::text LIKE %tes%)` instead.

**Comment by danharrin** [comment]
Laravel's query builder is adding the quotes and `::text` when it shouldn't be. The problem is that the quotes need to be wrapped around the column name.

The easiest way to fix this in your app, without needing to make a PR to fix Laravel, is to rename the column from `Name` to `name`. The capitalisation here is prompting the issue. Using lower case column names, as Laravel recommends, seems to work just fine.
