### ISSUE TITLE
recordClasses() is only correctly applied to the first entry of a Table

### ISSUE THREAD

**Issue by maxleistner** [laravel-filament/filament#9945]
### Package

filament/tables

### Package Version

v3.0.103

### Laravel Version

v10.34.2

### PHP Version

PHP 8.2.0

### Problem description

https://filamentphp.com/docs/3.x/tables/advanced#custom-row-classes

Calling this fn in the table view leads to only style the first row correctly - every other row falls back to default even the returns are true

```
->recordClasses(fn (Booking $record) => match ($record->state) {
                State::InApproval => 'border-l-4 border-red-600',
                State::Approved => 'border-l-4 border-blue-600',
                State::Invoiced => 'border-l-4 border-blue-600',
                State::Paid => 'border-l-4 border-green-600',
                default => null,
            })
```

### Expected behavior

That not only the first row is styled. 

### Steps to reproduce

Add this code to a table view

### Reproduction repository

https://github.com/maxleistner/laravel-filament-table-recordClasses-bug

**Comment by maxleistner** [comment]
I found the problem. 
**Problem**
The CSS is generated correctly, but the style is overwritten by filament css. 

**Solution**
The classes needs to be important to actually style even the other rows. `!border-s-2 !border-red-500`.
As this is not a nice solution, i guess the order of the css or the class definitions need to be optimized by filament.

**Comment by zepfietje** [comment]
Order of CSS classes won't matter, since it depends on the order in which they're defined in Tailwind CSS. I don't think this is a bug honestly. Let me know if I'm missing something though, @maxleistner. 🙂
