### ISSUE TITLE
Hover Underline Issue with TextColumn Links when Using ->url Method

### ISSUE THREAD

**Issue by nadirabbas** [laravel-filament/filament#9965]
### Package

filament/filament

### Package Version

v3.1.0

### Laravel Version

v10.10

### Livewire Version

v3.2

### PHP Version

PHP 8.1.17

### Problem description

When `Tables\Columns\TextColumn` is used as a link by using the `->url` method, the generated link only gets underlined when the `span` inside  the `a` tag is hovered and not the whole `a` tag. Here's a demo (Pay attention to the URL in bottom-left)

https://github.com/filamentphp/filament/assets/38838675/a28b8cb6-6831-4171-803e-63edf2868c02

### Expected behavior

Link should show underline when the anchor tag is hovered instead of the child span.

### Steps to reproduce

`Tables\Columns\TextColumn::make('example')->url('https://google.com')`

### Reproduction repository

https://github.com/nadirabbas/bug-reproduction/tree/filament-bug-1

**Comment by zepfietje** [comment]
This is designed behavior, since text columns can contain a list of strings, each having their own link. Correct me if I'm wrong, @danharrin.

**Comment by nadirabbas** [comment]
@zepfietje  But in this particular case, you can see how confusing that could be for the user. Since the link boundary isn't clear.

**Comment by zepfietje** [comment]
If you want the entire cell to be clickable, you may be looking for column actions instead: https://filamentphp.com/docs/3.x/tables/columns/getting-started#column-actions-and-urls.

**Comment by nadirabbas** [comment]
@zepfietje When utilizing the `->url(...)` method, the entire column indeed becomes clickable. However, a significant UX issue arises. The sole indication that the entire column is a separate link is the underline visible upon hovering over the text. The underline only appears when hovering directly over the text. Clicking anywhere within the column, even outside the text, redirects to the column link rather than the intended record link which confuses the user.

**Comment by zepfietje** [comment]
Yeah so then you should only use either the cell URL or the item url.

**Comment by LuizCristino** [comment]
I agree with @nadirabbas. This week I suffered with the same issue. I took me a while to understand that the full column becomes the clickable link, just because the decoration only appears when the text is hovered.

What I see are two possibilities:
1. Add the possibility to target only the value inside the cell as a URL.
2. Show the underline decoration when hovering the column
