### ISSUE TITLE
In a polymorphic scenario, clicking on "Associate" will not display options where the model type field is null.

### ISSUE THREAD

**Issue by wuhl92** [laravel-filament/filament#9969]
### Package

filament/filament

### Package Version

3.1.0

### Laravel Version

v10.34.2

### Livewire Version

v3.2.2

### PHP Version

PHP 8.2.3

### Problem description

![image](https://github.com/filamentphp/filament/assets/28152197/7d6a2f83-d5fe-4323-933e-5fee75d2e795)
![image](https://github.com/filamentphp/filament/assets/28152197/60e6ee69-180c-4f4d-a5fc-d3f3898e614e)
In a polymorphic scenario, clicking on "Associate" will not display options where the model type field is null.
![image](https://github.com/filamentphp/filament/assets/28152197/8bf8aa8b-13e1-4965-8f7e-49aaf6134eac)
I believe this code snippet is causing the issue.
This code snippet is located in Tables\Actions\AssociateAction。

### Expected behavior

Display options with a null model type field as usual

### Steps to reproduce

Click the associate button

### Reproduction repository

https://github.com/wuhl92/demo/blob/main/IpAddressesRelationManager.php

**Comment by danharrin** [comment]
Please let me know when you create a full reproduction repository. I do not have access to your models or DB structure. Please create a new Laravel project, start from scratch to reproduce the issue. Upload it to the repository, and I will reopen the issue and investigate.
