### ISSUE TITLE
Builder sort order is not working

### ISSUE THREAD

**Issue by kenjilabs** [laravel-filament/filament#997]
### Package

filament/forms

### Package Version

v2.7.0

### Laravel Version

v8.77.1

### Livewire Version

v2.8.2

### PHP Version

PHP 8.1

### Bug description

Builder sort order is not working

Builder is using Block name instead of uuid 

### Video link
https://www.loom.com/share/f95a9d9fdb924ec29673a258798919d0

### Blocks schema

![image](https://user-images.githubusercontent.com/2118549/147383730-9caf8bd1-feb4-438f-8abb-1f3f5c578a40.png)

### Block filed 

![image](https://user-images.githubusercontent.com/2118549/147383699-77db77e2-6e2a-4d5d-b01e-cd7b58b86342.png)

**Comment by danharrin** [comment]
Fixed by #1008.
