### ISSUE TITLE
Getting an error with minimal theme.

### ISSUE THREAD

**Issue by StaffCollab** [laravel-filament/filament#9981]
### Package

filament/minimal-theme

### Package Version

v3.0.0-alpha8

### Laravel Version

10

### Livewire Version

v3

### PHP Version

8.1

### Problem description

Getting this error, on installation.
Call to undefined method Filament\Support\Colors\ColorManager::addShades()

Also, can I never again use the forge GUI to deploy?
Because it requires a interactive console... Why cannot I just use a auth.json file?

### Expected behavior

use auth.json
and no errors

### Steps to reproduce

Nothing just install

### Reproduction repository

https://github.com

**Comment by zepfietje** [comment]
Hey @StaffCollab, sorry for missing your issue!

Please make sure to update to the latest version of Filament using `composer update`. That should resolve the `addShades()` exception, as it was added in a recent version of Filament.

Also, you can just use your `auth.json` file by adding this to it:
```json
"http-basic": {
    "filament.privato.pub": {
        "username": "the email address used for your order",
        "password": "they license key you received"
    }
},
```

If you have any other questions, just let me know by opening a new issue or contacting me via email (I won't be notified here). 🙂
